### ISSUE TITLE
Compile the code wihtout GPU and Cuda

### ISSUE THREAD

**Issue by VanitarNordic** [AlexeyAB/darknet#1]
Hello,

I want to open the VS project and compile the code without using GPU and Cuda, what should I do?

**Comment by AlexeyAB** [comment]
@VanitarNordic Hi,
You can simply open and build: `build/darknet/darknet_no_gpu.vcxproj` I just added it.

**Comment by VanitarNordic** [comment]
Hello again,

Thank you very much, but I still get Cuda related errors. Please look at the picture.

![2016-12-09_21-34-18](https://cloud.githubusercontent.com/assets/18719591/21059399/710b3a8c-be57-11e6-90e5-b010bac86f75.jpg)

**Comment by VanitarNordic** [comment]
I could load the darknet_no_gpu.vcxproj by deleting the darknet.vcxproj file.

Now it loads flawlessly. Thank you sir.

**Comment by mychina75** [comment]
How about the performance? Frames/sec

**Comment by VanitarNordic** [comment]
one frame per few seconds

**Comment by vishalmanes109** [comment]
1>D:\GitHub\darknet\src\image_opencv.cpp(15,10): error C1083:  Cannot open include file: 'opencv2/core/version.hpp': No such file or directory

**Comment by vishalmanes109** [comment]
****I am using darknet_no_gpu but it still giving 2 **errors.****

1>D:\GitHub\darknet\src\image_opencv.cpp(15,10): error C1083:  Cannot open include file: 'opencv2/core/version.hpp': No such file or directory



![image](https://user-images.githubusercontent.com/36571896/65159060-20435300-da51-11e9-91e5-ecc22283bbe3.png)**
