### ISSUE TITLE
data.h #includes non-Windows pthread.h

### ISSUE THREAD

**Issue by BenjaminPelletier** [AlexeyAB/darknet#10]
After installing Visual Studio 2015 Community 14.0.25431.01 Update 3, CUDA 8.0, and OpenCV 2.4.9 as linked, attempting to build build\darknet\darknet.sln results in "Cannot open include file: 'pthread.h'", and therefore "Identifier "pthread_t" is undefined" later in data.h.  Does this project have an undocumented dependency on some Linux-compatibility package?  Like, for instance: https://technet.microsoft.com/en-us/library/bb463209.aspx  If so, which pthread library is working for you to build under Windows?

**Comment by AlexeyAB** [comment]
@BenjaminPelletier 
`pthread.h` is already here: https://github.com/AlexeyAB/darknet/tree/master/3rdparty/include
`pthreadVC2.dll` & `pthreadGC2.dll` are here: https://github.com/AlexeyAB/darknet/tree/master/3rdparty/dll/x64

1. Did you compile for **x64 & Release**?
2. Did you change any include pathes in `darknet.sln`?

* Open `darknet.sln` in MSVS -> (Right click) on solution `darknet` -> C/C++ -> General -> Include directories **should be**: `C:\opencv_2.4.9\opencv\build\include;..\..\3rdparty\include;%(AdditionalIncludeDirectories);$(CudaToolkitIncludeDir);$(cudnn)\include`

* And try to change this part `..\..\3rdparty\include` to location of these files https://github.com/AlexeyAB/darknet/tree/master/3rdparty/include on you computer.

**Comment by BenjaminPelletier** [comment]
Ah, ok -- thanks for the amazing support!  As far as I can tell, following the instructions under "How to compile" exactly results in Debug and Win32 selected by default.  Changing to Release and x64 fixed that problem without either of the bullet checks; that would probably be helpful to note in the README.

However, then VS couldn't find opencv2/highgui/highgui_c.h.  It turns out OpenCV must have a very particular folder structure -- specifically, I had, e.g., C:\opencv_2.4.9\build\include whereas this code wants C:\opencv_2.4.9\opencv\build\include.

And now I'm getting "LNK1181 cannot open input file cudnn.lib".  Is this because of this issue: https://support.microsoft.com/en-us/kb/815645  I installed CUDA with all the defaults, and I think it got put in C:\Program Files\...  If so, that would be nice to mention in the README also.

**Comment by AlexeyAB** [comment]
@BenjaminPelletier Thank you. I'll add this to readme.md.

Now try to pull last commit, it should work.

**Comment by AlexeyAB** [comment]
@BenjaminPelletier  I  fixed `Reame.md` and also changed path in `darknet.vcxproj` for OpenCV lib from **vc12** (MSVS2013) to **vc14** (MSVS2015).

If you have MSVS 2015, CUDA 8.0 and OpenCV 2.4.9 (with pathes: `C:\opencv_2.4.9\opencv\build\include` & `C:\opencv_2.4.9\opencv\build\x64\vc14\lib`), then start MSVS, open `build\darknet\darknet.sln`, set **x64** and **Release**, and do the: Build -> Build darknet

**Comment by BenjaminPelletier** [comment]
The README changes look great.  I'm not against installing CUDNN, but I was going to try without first to test the optional-ness of the dependency.  And, with that, I'm still getting the cudnn.lib link error.  I'm not at all experienced with C++, but a text search finds #pragma comment(lib, "cudnn.lib") in convolutional_layer.c and it seems (http://stackoverflow.com/questions/12199595) that's probably what's pulling cudnn.lib into the linker since I checked the vcxproj and the only place cudnn.lib is located is in the Release Win32 configuration (which I'm not using...perhaps that should be deleted too).  Fewer dependencies is cool, but perhaps CUDNN should actually be a required dependency?

Thanks again for your amazing support -- can I buy you a beer or something or do you have a Patreon account?

**Comment by AlexeyAB** [comment]
@BenjaminPelletier Now it's really fixed )

Thank you. No, I have not account on Patreon. Simply, you can just advise to anyone to use this fork.

**Comment by BenjaminPelletier** [comment]
Ah, that (the #ifdefs) makes sense and do seem to resolve the cudnn.lib thing.  However, I'm now getting a linker error "cannot open file 'opencv_core249.lib'".  Upon investigation, that's because the project thinks it should look for libraries in C:\opencv_2.4.9\opencv\build\x64\vc14\lib (which makes sense because I am indeed using vc14), but this version of OpenCV (linked in README) only seems to include vc10, vc11, and vc12.  I could change the library link to point to vc12, but is there a good place for me to download OpenCV 2.4.9 for Visual Studio 14?  Perhaps you built it from source and I should too?

**Comment by AlexeyAB** [comment]
@BenjaminPelletier I added both paths, the first for vc14, and the second for vc12.

Those, vs14 is preferable, but if it is not there, then will be used vc12.

**Comment by BenjaminPelletier** [comment]
Awesome, compilation succeeded :)  It might be nice to mention where the vs14 folder comes from (did you build OpenCV 2.4.9 from source in VS14?), but vs12 seems to work, so that's great .
