### ISSUE TITLE
Which files I need to change to train detector for classes=1

### ISSUE THREAD

**Issue by vg123** [AlexeyAB/darknet#100]
I changed `yolo-voc.cfg` following files.
```
batch=32
subdivision=8
filters=(5+1)*5=30
classes=1;
```
copied it and saved in `yolo-car.cfg`.
/src/yolo.c
```
char *voc_names[] ={"car"};
char *train_images = "/home/vishal/darknet/data/test-train/traincar.txt";
```
created following files and folders.

1)`cfg/car.names ` contains `car` one class only.
2)`cfg/car.data` 
```
classes= 1
train  = data/test-train/train.txt
valid  = data/test-train/train.txt
names = data/car.names
backup = backup/
```
3)`cfg/yolo-car.cfg`

4)`darknet/data/cars/`
contain 300 examples with image files and corresponding text files generated using `yolo_mark`.

And during training It is saving each Iteration weight file.and just after one iteration `learning_rate` reduced to `0.0000`.

**Comment by AlexeyAB** [comment]
> /src/yolo.c
> 
> char *voc_names[] ={"car"};
> char *train_images = "/home/vishal/darknet/data/test-train/traincar.txt";

1. You should not change any source code if you want to train Yolo v2 for your custom objects, just use this manual: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

2. Also you should use `yolo-voc.2.0.cfg` as inital cfg for you `yolo-car.cfg` as described here: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

3. You should take `yolo-voc.2.0.cfg` and change only that lines, which described in manual. All other lines should remain unchanged.
