### ISSUE TITLE
How to use the yolo detector in c program

### ISSUE THREAD

**Issue by AditiBhiwaniwala** [AlexeyAB/darknet#101]
Hey all,
I want to write a c program using the pretrainned weight file of yolo to find out the location of car in my image. Can you help me with it?

**Comment by AlexeyAB** [comment]
Hi,
For a quick start, just look at the C++-code of my DLL - this is the fastest way to understand how to implement your own API on C to use detection of Yolo in your own C-programm:

* `yolo_v2_class.cpp`: https://github.com/AlexeyAB/darknet/blob/b585124e55fcd18a7511d3b2fdc6bc3db5368ef4/src/yolo_v2_class.cpp
* `yolo_v2_class.hpp`: https://github.com/AlexeyAB/darknet/blob/b585124e55fcd18a7511d3b2fdc6bc3db5368ef4/src/yolo_v2_class.hpp

Just look at functions, 
* where I init Yolo: https://github.com/AlexeyAB/darknet/blob/b585124e55fcd18a7511d3b2fdc6bc3db5368ef4/src/yolo_v2_class.cpp#L35
* and where I do detection: https://github.com/AlexeyAB/darknet/blob/b585124e55fcd18a7511d3b2fdc6bc3db5368ef4/src/yolo_v2_class.cpp#L157

----

And how I use this DLL in my console programm `yolo_console_dll.cpp`: https://github.com/AlexeyAB/darknet/blob/b585124e55fcd18a7511d3b2fdc6bc3db5368ef4/src/yolo_console_dll.cpp
