### ISSUE TITLE
Segmentation fault during Training of detector 

### ISSUE THREAD

**Issue by visha-l** [AlexeyAB/darknet#102]
Your git repository and your website both are great and helped a lot, and I have reached to the training step. But now when I am training It. It is giving me segmentation fault after 1400th iterations. WHY?

`darknet/MAKEFILE`
```
GPU=1
CUDNN=0
OPENCV=0
....
```

`darknet/cfg/yolo-obj.cfg`
```
batch = 16
subdivision = 8
....
filters =30
.....
classes =1
```
I am training It on `EC2 instance of AWS` `p2.xlarge`. 
I don't now why it is giving segmentation fault after 1400th iteration. please tell me what I need to change.

**Comment by visha-l** [comment]
After changing `yolo-obj.cfg` to this
```
batch=16
subdivision=16
height=1088
width = 1088
....
filters = 30
..
classes =1

```
and now when I run it for training model , it stopped training after 256 iterations with message killed.
```
killed
```

**Comment by visha-l** [comment]
Again after changing `yolo-obj.cfg` to this.
```
batch = 16
subdivisions =8
height=416
width =416
...
filters =30
...
classes = 1
```

And now when I run this for training It ran for `1610 `iterations after that it gave me `segmentation fault`

**Comment by AlexeyAB** [comment]
1. If you train on Linux then you should use source code from repo: https://github.com/pjreddie/darknet
2. Also you should set 2 params in the file `yolo-obj.cfg`: 

    * `filters =30` only in the last convolutional layer: https://github.com/pjreddie/darknet/blob/f9446acb689230b027ab1a63189338000d463507/cfg/yolo-voc.2.0.cfg#L224
    * `classes = 1` https://github.com/pjreddie/darknet/blob/f9446acb689230b027ab1a63189338000d463507/cfg/yolo-voc.2.0.cfg#L230

3. And also in the file `obj.data` you should set `classes = 1` https://github.com/pjreddie/darknet/blob/f9446acb689230b027ab1a63189338000d463507/cfg/voc.data#L1

----

K80 has 2 x 12 GB GPU-RAM: https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units#Tesla
But if your GPU has no more than 4 GB GPU-RAM, then you should use in cfg-file: 

```
batch = 64
subdivisions =8
height=416
width =416

random=0
```
