### ISSUE TITLE
c code copied from demo.c doesn't work correctly

### ISSUE THREAD

**Issue by goodtogood** [AlexeyAB/darknet#1025]
Hi @AlexeyAB 
the code cloned from this repo is latest, I created one win console project, 
the code below is almost copied from test_detector function of detector.c,
It always exited with exception. I wanna detect one image and get output. 

```
#include "network.h"
#include "unistd.h"
#include "parser.h"
#include "region_layer.h"
#include <opencv2/highgui/highgui_c.h>
#include "utils.h"
void draw_detections_cv_v3(IplImage* show_img, detection* dets, int num, float thresh, char** names, image** alphabet,
                           int classes, int ext_output);

int main(int argc, char* argv[])
{
	char* namefile = "./data/coco.names";
	char* cfgfile = "./yolov2-tiny.cfg";
	char* weightfile = "./yolov2-tiny.weights";
	char* input = "./data/dog.jpg";
	int gpu_index = 0;
	float thresh = .24;
	float nms = .45;
	float hier_thresh = 0.5;
	int demo_ext_output = 0;

	char** names = get_labels(namefile);

	image** alphabet = load_alphabet();

	cuda_set_device(gpu_index);

	network net = parse_network_cfg_custom(cfgfile, 1);
	if (weightfile)
	{
		load_weights(&net, weightfile);
	}
	//set_batch_network(&net, 1);
	fuse_conv_batchnorm(net);

	srand(2222222);

	image im = load_image(input, 0, 0, net.c);

	image sized = resize_image(im, net.w, net.h);

	layer l = net.layers[net.n - 1];

	float* X = sized.data;

	double time = what_time_is_it_now();
	network_predict(net, X);
	printf("%s: Predicted in %f seconds.\n", input, (what_time_is_it_now() - time));

	int nboxes = 0;
	int letterbox = 0;
	detection* dets = get_network_boxes(&net, im.w, im.h, thresh, hier_thresh, 0, 1, &nboxes, letterbox);
	printf("nboxes %d  classes %d   \n", nboxes, l.classes);
	if (nms) do_nms_sort(dets, nboxes, l.classes, nms);

	 draw_detections_v3(im, dets, nboxes, thresh, names, alphabet, l.classes, demo_ext_output);
	//save_image(im, "draw");	
       //  label ,confidence, bbox



	free_detections(dets, nboxes);
	free_image(im);
	free_image(sized);

	// free memory
	free_ptrs(names, net.layers[net.n - 1].classes);
	free_network(net);

	return 0;
}

```

It seems that  the value of l.classes always is zero, so draw_detections_v3 throw the exception.
Is there something I missed?
thanks a lot !

**Comment by AlexeyAB** [comment]
@goodtogood Hi,

Try to copy this part of code too: https://github.com/AlexeyAB/darknet/blob/eff487ba3626a39e135d13929117e04bc4cf5823/src/detector.c#L1-L30

Show screenshot of output.

Does it work if you comment this line `draw_detections_v3(...)`?

**Comment by goodtogood** [comment]
Hi, @AlexeyAB 
I tried copying the code  as you mentioned above,
 exception was thrown , see attached image below
![ex](https://user-images.githubusercontent.com/10088733/41265091-0e4c890a-6e23-11e8-80c0-e33d1da860eb.jpg)

 if I comment the line draw_detections_v3(...), no exception was not thrown and no text output
![ex3](https://user-images.githubusercontent.com/10088733/41265315-2e527ed4-6e24-11e8-87db-40b0d3b20b9a.jpg)

**Comment by goodtogood** [comment]
the code is almost the same , it's kinda weird.

**Comment by arnaudl** [comment]
I had the same issue, you need to make sure you give the same flags to gcc as the ones you used to compile the shared library (GPU, OPENCV...):

    gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN
