### ISSUE TITLE
mAP slow

### ISSUE THREAD

**Issue by PotentialPie** [AlexeyAB/darknet#1028]
When i use the command ` ./darknet detector map .data .cfg .weights` to calculate the mAP of my validate dataset ,  I found it running very slowly.  The original validation data set has more than 4000 images, but it is really slow. So I changed to 18 images, but it still took a very long time. Below is the output:

```
Loading weights from backup/dota_train/yolov3-dota_50000.weights...
seen 64
Done!
16
4
8
12
16
detections_count = 219, unique_truth_count = 29
class_id = 0, name = bridge, 	 ap = 33.33 %
class_id = 1, name = baseball-diamond, 	 ap = 0.00 %
class_id = 2, name = basketball-court, 	 ap = 0.00 %
class_id = 3, name = harbor, 	 ap = 0.00 %
class_id = 4, name = soccer-ball-field, 	 ap = 100.00 %
class_id = 5, name = ground-track-field, 	 ap = 100.00 %
class_id = 6, name = small-vehicle, 	 ap = 0.00 %
class_id = 7, name = storage-tank, 	 ap = 100.00 %
class_id = 8, name = large-vehicle, 	 ap = 24.55 %
class_id = 9, name = plane, 	 ap = 50.76 %
class_id = 10, name = roundabout, 	 ap = 0.00 %
class_id = 11, name = tennis-court, 	 ap = 0.00 %
class_id = 12, name = helicopter, 	 ap = 0.00 %
class_id = 13, name = ship, 	 ap = 0.00 %
class_id = 14, name = swimming-pool, 	 ap = 0.00 %
 for thresh = 0.25, precision = 0.67, recall = 0.41, F1-score = 0.51
 for thresh = 0.25, TP = 12, FP = 6, FN = 17, average IoU = 48.76 %

 mean average precision (mAP) = 0.272424, or 27.24 %
Total Detection Time: 255.000000 Seconds
```

The following is the configuration of the CPU：

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
Stepping:              1
CPU MHz:               1837.624
CPU max MHz:           3000.0000
CPU min MHz:           1200.0000
BogoMIPS:              4200.31
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0-7,16-23
NUMA node1 CPU(s):     8-15,24-31

The GPU is GTX 1080 Ti

**Comment by AlexeyAB** [comment]
> Total Detection Time: 255.000000 Seconds

Yes, it is very slow for 18 images. But was training fast?


* What params do you use in the Makefile for detector map?
* What images resolution do you use?
* What width= height= in your cfg-file?

**Comment by PotentialPie** [comment]
Thank you very much. According to your hint, I find where the problem is.

I trained my weight by the original Darknet(https://github.com/pjreddie/darknet), which compiled in the Makefile with default GPU = 1, while your code compiled with default gpu=0, I did not make changes before make. After change it runs very fast. 

One more question, the size of my training images is 1024*1024, so I want to scale the training input into 832*832. In addition to modifying the height , width, the  anchors and the filters of the last three yolo layers, what else can be done to improve?

**Comment by AlexeyAB** [comment]
Just what is written here: https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

**Comment by AlexeyAB** [comment]
@PotentialPie 
In the most cases it helps. But may be in your case the most objects are large, so it doesn't help.

* What mAP can you get if you decrease network resolution to 736x736?
* What anchors did you use for training?

**Comment by PotentialPie** [comment]
With the size of 832x832, the anchors are :
[14,16,  22,34,  38,18,  40,98,  40,38,  76,58,  126,194,  134,102,  342,338]

When i decrease network resolution to 736x736 without changing anchors, it gets  38.73%
With changing anchors to [12, 13, 19, 29, 33, 15, 34, 85, 34, 33, 66, 50, 109, 169, 116, 89, 298, 294] it gets 32.10%

If i decrease network resolution to 416x416, it gets no more than 1% mAP.

**Comment by AlexeyAB** [comment]
Perhaps network resolution 832x832 is enought for your dataset, so increasing of network can't give any advantage.

* Do you use training dataset for validation mAP? `valid=train.txt`
* How many images ~ in your validation dataset?
* What random= and jitter= did you use in cfg-file?

**Comment by PotentialPie** [comment]
- With the input size of 832x832, the training data gets 51% mAP.

- There are 1w4 training images and 4k validation images.

- I set the random = 0 and jitter =0.3.

What does the jitter mean?

**Comment by AlexeyAB** [comment]
* Looks like relative sizes of objects very different in the Training and Test datasets, so this rule is broken: https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

> General rule - your training dataset should include such a set of relative sizes of objects that you want to detect - differing by no more than 2 times:
> 
> train_network_width * train_obj_width / train_image_width ~= detection_network_width * detection_obj_width / detection_image_width
> train_network_height * train_obj_height / train_image_height ~= detection_network_height * detection_obj_height / detection_image_height
> 

* What is the 1w4? What resolution?

* Preferably to set `random=1` for training, if you are going to increase network resolution after training

About jitter: https://github.com/AlexeyAB/darknet/issues/755#issuecomment-388620937

**Comment by PotentialPie** [comment]
Sorry, '1w4' is the abbreviation in Chinese for 14000, which in Chinese is '1万4'. 
The resolution of the training data and validation data is both 1024x1024.
I tried random=1 but OOM. I am afraid that decreasing the batch size but setting random = 1 won't improve the mAP. I will try it.

**Comment by AlexeyAB** [comment]
> I am afraid that decreasing the batch size but setting random = 1 won't improve the mAP.

You shouldn't decrease batch size, should be always `batch=64`.
If OOM occurs then increase `subdivisions=64` or 32



Also can you show anchors for your validation dataset? Set `train=valid.txt` in the `obj.data`, calculate anchors and show them here. Then revert `train=train.txt`
Will be valid-anchors very different from train-anchors?

**Comment by PotentialPie** [comment]
OK, i will try to train with `batch=64`, `subdivision=32/64` and `random=1`.
Should i set the input size to 1024x1024 to improve the results?

I just recalculated the anchors of validation data set as below:
```
[20.55958219   14.63738045]
 [  33.45251773   33.90778121]
 [  51.65634116   75.35361144]
 [  89.60180454   31.77858512]
 [ 111.51067073  130.29948273]
 [ 169.10261887  270.45686293]
 [ 376.13135163  119.5101626 ]
 [ 439.87486501  402.00850432]
```

It seems a little different from the training data:
`14,16, 22,34, 38,18, 40,98, 40,38, 76,58, 126,194, 134,102, 342,338`

**Comment by AlexeyAB** [comment]
> Should i set the input size to 1024x1024 to improve the results?

Try to train with 1024x1024 random=1, but if the error out of memory occurs, then train with 832x832 random=1. After training calculate mAP for 832x832 or 1024x1024.

It seems that objects in validation dataset ~1.5x larger than in training dataset - this is why increasing resolution after training doesn't help.
Because if you increase network resolution, then sizes of objects (in pixels) are increased too. Since objects in valid-dataset already `~1.5x` larger, then if after training you increase network from 832 to 1024 (`~1.2x` times) then difference between sizes (in pixels) in training and validation dataset will be `~1.8x`.
Therefore, in your case, you should train with `random=1` and train with maximum possible network resolution if the error doesn't occur 1024x1024 (or 832x832).

**Comment by PotentialPie** [comment]
I tried to train with input size 1024x1024 and random = 1, it didn't get a good result as expected.
Below is the detail of .cfg config:

```
batch=64
subdivisions=32
width=1024
height=1024
...
[yolo]
mask = 6,7,8
anchors = 17, 19, 27, 41, 46, 22, 49, 120, 49, 46, 93, 71, 155, 238, 164, 125, 420, 415
classes=15
num=9
jitter=.3
ignore_thresh = .5
truth_thresh = 1
random=1
...
[yolo]
mask = 3,4,5
anchors = 17, 19, 27, 41, 46, 22, 49, 120, 49, 46, 93, 71, 155, 238, 164, 125, 420, 415
classes=15
num=9
jitter=.3
ignore_thresh = .5
truth_thresh = 1
random=1
...
[yolo]
mask = 0,1,2
anchors = 17, 19, 27, 41, 46, 22, 49, 120, 49, 46, 93, 71, 155, 238, 164, 125, 420, 415
classes=15
num=9
jitter=.3
ignore_thresh = .5
truth_thresh = 1
random=1
```

Trained with 1024x1024, random = 1, the results are:

|iterations|mAP|
|-|-|
|10000 iterations:|25.74%|
|20000 iterations:|32.52%|
|30000 iterations:|31.79%|
|40000 iterations:|34.52%|
|50000 iterations:|31.27%|

Trained with 832x832, random = 0, the results are:

|iterations|mAP|
|-|-|
|10000 iterations:|39.20%|
|20000 iterations:|38.82%|
|30000 iterations:|41.49%|
|40000 iterations:|38.52%|

The results are all evaluated on the validation set. As seen, when i increase the network resolution and set random with 1, it get down. I don't know what happened.

**Comment by AlexeyAB** [comment]
This is very strange.
Can you show 2 screenshots of windows with points?

* for training dataset `train=train.txt`
    `darknet.exe detector calc_anchors data/obj.data -num_of_clusters 9 -width 832 -height 832 -show`

* for validation dataset `train=valid.txt`
    `darknet.exe detector calc_anchors data/obj.data -num_of_clusters 9 -width 832 -height 832 -show`

**Comment by PotentialPie** [comment]
When i run calc_anchors, i meet a problem with opencv. So i use the code [gen_anchors.py](https://github.com/AlexeyAB/darknet/blob/master/scripts/gen_anchors.py). I change the width_in_cfg_file = 832, height_in_cfg_file = 832 and change
```
anchors[i][0]*=width_in_cfg_file/32.
anchors[i][1]*=height_in_cfg_file/32.
```
to
```
anchors[i][0]*=width_in_cfg_file
anchors[i][1]*=height_in_cfg_file
```
Below are the result.
For the training data:
```
Centroids =  [[ 0.04546942  0.01991081]
 [ 0.08853306  0.06345611]
 [ 0.48524596  0.55388764]
 [ 0.1580567   0.28531726]
 [ 0.04774647  0.11080654]
 [ 0.35423425  0.23864997]
 [ 0.03677115  0.04254341]
 [ 0.01737779  0.02619705]
 [ 0.13449543  0.14132845]]
(9, 2)
Anchors =  [[  14.45832121   21.79594907]
 [  30.59360043   35.39611568]
 [  37.83055628   16.56579319]
 [  39.72506693   92.19104384]
 [  73.65950969   52.79548596]
 [ 111.90019763  117.58526945]
 [ 131.50317824  237.38396134]
 [ 294.7228975   198.55677836]
 [ 403.72463865  460.83451552]]

centroids.shape (9, 2)
```


For the validation data:
```
Centroids =  [[ 0.07653267  0.07592854]
 [ 0.10995997  0.03079147]
 [ 0.03654988  0.11566664]
 [ 0.15166881  0.1593259 ]
 [ 0.5548756   0.39300135]
 [ 0.01808894  0.04076993]
 [ 0.02351733  0.01691494]
 [ 0.03991525  0.03975625]
 [ 0.2138062   0.33856617]]
(9, 2)
Anchors =  [[  15.04999503   33.92058224]
 [  19.56641531   14.07323086]
 [  30.40949602   96.23464079]
 [  33.2094902    33.07719939]
 [  63.67518034   63.17254391]
 [  91.48669554   25.61850248]
 [ 126.18844722  132.55915208]
 [ 177.88675941  281.68704964]
 [ 461.6565008   326.97712681]]

centroids.shape (9, 2)
```

**Comment by AlexeyAB** [comment]
I mean such screenshot, where we can see aproximately how many objects are there for each anchor 

![image](https://user-images.githubusercontent.com/4096485/41599494-0ca5ad5c-73dc-11e8-8dcb-aba804404415.png)
