### ISSUE TITLE
yolo_console_dll.sln not working in debug mode

### ISSUE THREAD

**Issue by piyusharorawork** [AlexeyAB/darknet#1048]
I wanted to build the yolo_console_dll.sln with the following settings 

1. Debug mode 
2. In C++->Code generation , I need to switch to Multi Threaded Debug Mode 

I am able to build the solution in both **muti threaded debug** as well as **muti threaded**  but It looks like it is only working in muti threaded not in multi threaded debug . 

Can you please check the issue

**Comment by AlexeyAB** [comment]
Did you build both `yolo_cpp_dll.sln` and `yolo_console_dll.sln` in **muti threaded debug** mode?

**Comment by piyusharorawork** [comment]
Thanks for your response . 

I am able to solve the problem partially . 

I mean when I build the yolo_cpp_dll.sln in **release** mode with **multi threaded debug** and then if I build the yolo_cpp_console.sln in **debug** mode with **multi threaded dubug**  it is working fine . 

But when I build the yolo_cpp_sln in debug mode with any multi threading settings , I am not able to build the yolo_cpp_console in debug mode . 

I get this error 
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: class std::vector<struct bbox_t,class std::allocator<struct bbox_t> > __cdecl Detector::detect(struct image_t,float,bool)" (__imp_?detect@Detector@@QEAA?AV?$vector@Ubbox_t@@V?$allocator@Ubbox_t@@@std@@@std@@Uimage_t@@M_N@Z) referenced in function main	yolo_console_dll	D:\Projects\Experiments2\YOLOV3\darknet-Yolo_v3\build\darknet\yolo_console_dll.obj	1	


I mean , is it possible that the yolo_cpp_dll meant to be compiled only in release mode to be used by yolo_console_dll or am I missing something ?

**Comment by AlexeyAB** [comment]
Looks like yes, yolo_cpp_dll should be compiled in release mode.

**Comment by piyusharorawork** [comment]
Ok then , I am closing the issue if that is the case . But I think in future , we need to provide the support for yolo_cpp_dll to be built in debug mode too .

Thanks for your support.

**Comment by rmx564354093** [comment]
Excuse me!   Is can Compiled yolo_cpp_dll in  debug mode  And  then use the dll  in yolo_cpp_console project in debug mode?
