### ISSUE TITLE
Totally wrong labels but high mAP

### ISSUE THREAD

**Issue by hinnBU** [AlexeyAB/darknet#1059]
**First: Great  work at all.**

I am using your implementation of tiny-yolo with a Jetson TX2 combined and a Stereolabs ZED video stream. The pictures have a size of 720x1280px.

My target is to detect cones of blue,yellow, orangebig and orangesmall type.
So here is the content of my obj.names:

[obj .names.txt](https://github.com/AlexeyAB/darknet/files/2113005/obj.names.txt)

I transfered my dataset with 2000 images and around 6 to 8 different cones per image from VOC format, every single label is validated in your tool Yolo_mark.

I trained with recalculated anchors, random=1 and resized width and height. Training works fine, config file see below.

Now my problem: from ./darknet detector map i get an output like this:

**detections_count = 2395, unique_truth_count = 1269  
class_id = 0, name = blue, 5     ap = 80.71 % 
class_id = 1, name = yellow, 	 ap = 75.88 % 
class_id = 2, name = orangebig, 	 ap = 90.23 % 
class_id = 3, name = orangesmall, 	 ap = 88.37 % 
 for thresh = 0.25, precision = 0.80, recall = 0.90, F1-score = 0.84 
 for thresh = 0.25, TP = 1143, FP = 294, FN = 126, average IoU = 62.37 % 

 mean average precision (mAP) = 0.837973, or 83.80 %** 

So i let the net detect an image of the validation data, you clearly can see the problem here:

What it looks like:
annotation: i validated my bndbxs in the darknet.py with the output you get from debug=True.

![image](https://user-images.githubusercontent.com/40371314/41562881-3a2edde0-734e-11e8-918a-553ee70c3b18.png)

What it  should look like:
![marking images_screenshot_18 06 2018](https://user-images.githubusercontent.com/40371314/41562888-3c75d45a-734e-11e8-95bb-6775e20e61f4.png)

Output with debug=True:
[output.txt](https://github.com/AlexeyAB/darknet/files/2113053/output.txt)

my .cfg:
[yolo3.txt](https://github.com/AlexeyAB/darknet/files/2113033/yolo3.txt)

Hope you have an idea whats going on :)

**Comment by AlexeyAB** [comment]
* Do you use Linux?
* Do you use the same `obj.names` for Yolo_mark and for Yolo?
* Do you get the same wrong labels if you use `darknet detector test` instead of `darknet.py`?
* Show content of `obj.data` file

**Comment by AlexeyAB** [comment]
So do you get bad result only when use these lines: https://github.com/AlexeyAB/darknet/blob/7f0079dec5da19072cfe64aee233ecacd8ef2ffd/darknet.py#L226-L227

----

But if you use these lines, then everything works well:
* or https://github.com/AlexeyAB/darknet/blob/7f0079dec5da19072cfe64aee233ecacd8ef2ffd/darknet.py#L228-L229
* or https://github.com/AlexeyAB/darknet/blob/7f0079dec5da19072cfe64aee233ecacd8ef2ffd/darknet.py#L225

**Comment by hinnBU** [comment]
I found the bug and the fix for it.

Here we go:

cv2.imread() reads color images with bgr encoding, but your algorithm needs rgb encoding. For this reason the colors are totally messed up and for example yellow cones are blue or everything else than yellow.

Just add following 2 lines after cv2.imread():

 #b,g,r = cv2.split(temp_image)       # get b,g,r
 #temp_image = cv2.merge([r,g,b])     # switch it to rgb

updated darknet.py:

[darknet.py.txt](https://github.com/AlexeyAB/darknet/files/2116275/darknet.py.txt)

**Comment by AlexeyAB** [comment]
@hinnBU 

Try to use - it should work faster:

```python
import cv2 
custom_image_bgr = cv2.imread(image) # use: detect(,,imagePath,) 
custom_image = cv2.cvtColor(custom_image_bgr, cv2.COLOR_BGR2RGB)
```

**Comment by hinnBU** [comment]
>Try to use - it should work faster:
import cv2 
custom_image_bgr = cv2.imread(image) # use: detect(,,imagePath,) 
custom_image = cv2.cvtColor(custom_image_bgr, cv2.COLOR_BGR2RGB)

I am using the cv_bridge module, which comes with the possibility to specify an encoding :)

Thanks for your support, glad we could find this bug!
