### ISSUE TITLE
darknet_no_gpu is very slow

### ISSUE THREAD

**Issue by fishman2008** [AlexeyAB/darknet#106]
Hi AlexyAB,

It appears that the cpu version is very slow when tested with PC camera. I only obtained around 1FPS for the regular model. The window has been resized to 416*416 and the video writing function is also turned off as suggested. The GPU version has approximately 7FPS with K620 on my machine. I have searched the previous issues and it seems that these fixes did not solve the problem. Any thoughts on this? Thanks.

**Comment by AlexeyAB** [comment]
Hi, @fishman2008 

1. Darknet-Yolo uses only 1 CPU-Core, and without builtin SSE/AVX SIMD-optimmizations, so, out of box Yolo works slow on CPU.

The most time takes the function `gemm_nn()`: https://github.com/AlexeyAB/darknet/blob/b585124e55fcd18a7511d3b2fdc6bc3db5368ef4/src/gemm.c#L74

This is the General matrix multiply ([GEMM](https://en.wikipedia.org/wiki/Basic_Linear_Algebra_Subprograms#Level_3)). You can manually optimize it or implement by using OpenBLAS, Itnel MKL, or others blas-library.

2. Also you can use more faster Tiny-Yolo `tiny-yolo-voc.cfg` - all steps for training are the same as for ordinary Yolo model: https://github.com/AlexeyAB/darknet/blob/b585124e55fcd18a7511d3b2fdc6bc3db5368ef4/cfg/tiny-yolo-voc.cfg

----

There is such call-stack with percent of CPU-usage%:

![gemm](https://user-images.githubusercontent.com/4096485/27137532-e361d11a-5126-11e7-8b3a-0eee0118edbd.jpg)

Also there is manual how to implement Tiny-Yolo for smartphone on iOS: http://machinethink.net/blog/object-detection-with-yolo/

**Comment by AlexeyAB** [comment]
@fishman2008 Hi,

I added some fixes using OpenMP: https://github.com/AlexeyAB/darknet/commit/51477ab274bbb40be259844bdaab9685f693b028

And it **increses perfrormance at 2.3 x times** on CPU Intel Core i7 6700K 4 Cores (8 HT-Cores) 4 GHz: http://ark.intel.com/products/88195/Intel-Core-i7-6700K-Processor-8M-Cache-up-to-4_20-GHz
Was 3.5 sec per img, now **1.5 sec per img** on CPU for 416x416 network resolution.

----

So, to increase FPS more on CPU, you can use `tiny-yolo-voc.cfg` and change `width=288 height=288` in the `tiny-yolo-voc.cfg`

* `tiny-yolo-voc.cfg`: https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/tiny-yolo-voc.cfg
* `tiny-yolo-voc.weight`: https://pjreddie.com/media/files/tiny-yolo-voc.weights
* change to `width=288 height=288` in the `tiny-yolo-voc.cfg`
* run `darknet.exe detector demo voc.data cfg/tiny-yolo-voc.cfg tiny-yolo-voc.weights video-file.mp4`

You will get about ~3 FPS (i.e. 0.3 sec per image) on CPU Intel Core i7 6700K 4 Cores (8 HT-Cores) 4 GHz.
