### ISSUE TITLE
In yolov2 there is no "cvReleaseVideoWriter" function

### ISSUE THREAD

**Issue by dontWantToBeUnemployed** [AlexeyAB/darknet#1060]
I think it make result video corrupt.

so i can not play the result video in windows media player.

where do i have to write "cvReleaseVideoWriter" function?

I had tried to use yolov3, but training was not worked. so I am using yolov2.

Please let me know what can i do.

https://github.com/unsky/yolo-for-windows-v2/blob/4b79288a1a601dfd2427b771953ab42244652ba3/src/image.c#L447

I tried a few ways, but output_video is "static".

It make me confuse how to apply cvReleaseVideoWriter.

**Comment by AlexeyAB** [comment]
Hi,

Update your code from GitHub and recompile

* or press ESC in the demo Window
* or just whait while the video ends

Function `cvReleaseVideoWriter(&output_video_writer);` will be called.

https://github.com/AlexeyAB/darknet/blob/7f0079dec5da19072cfe64aee233ecacd8ef2ffd/src/demo.c#L243-L246

https://github.com/AlexeyAB/darknet/blob/7f0079dec5da19072cfe64aee233ecacd8ef2ffd/src/demo.c#L275

https://github.com/AlexeyAB/darknet/blob/7f0079dec5da19072cfe64aee233ecacd8ef2ffd/src/demo.c#L305-L309

**Comment by dontWantToBeUnemployed** [comment]
Thanks it works!
