### ISSUE TITLE
Undeclared identifier on yolo_cpp_dll 

### ISSUE THREAD

**Issue by thriskel** [AlexeyAB/darknet#1065]
Using windows, trying to compile yolo_cpp_dll  it gives the following errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2065	'_CRTDBG_LEAK_CHECK_DF': undeclared identifier	yolo_cpp_dll	c:\path\darknet\src\darknet.c	355	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2065	'_CRTDBG_ALLOC_MEM_DF': undeclared identifier	yolo_cpp_dll	c:\path\darknet\src\darknet.c	355

is there anything file I should include?

**Comment by thriskel** [comment]
gives this error, but the file is in there....
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'cudnn.h': No such file or directory	yolo_cpp_dll	c:\path\darknet\src\cuda.h	33

**Comment by AlexeyAB** [comment]
Did you install cuDNN?

> 1.3. To install CUDNN (speedup neural network), do the following:
> 
> download and install cuDNN 7.0 for CUDA 9.1: https://developer.nvidia.com/cudnn
> 
> add Windows system variable cudnn with path to CUDNN: https://hsto.org/files/a49/3dc/fc4/a493dcfc4bd34a1295fd15e0e2e01f26.jpg

If you didn't install cuDNN, then do: https://github.com/AlexeyAB/darknet#how-to-compile-on-windows

> 1.4. If you want to build without CUDNN then: open \yolo_cpp_dll.sln -> (right click on project) -> properties -> C/C++ -> Preprocessor -> Preprocessor Definitions, and remove this: `CUDNN;`

**Comment by thriskel** [comment]
Should I run console dll on debug or release?
installing CUDNN solved it, thank you, I thought I had it installed.

**Comment by AlexeyAB** [comment]
> Should I run console dll on debug or release?

Release too.
