### ISSUE TITLE
Convert custom dataset .xml files to Darknet format

### ISSUE THREAD

**Issue by erlendhade** [AlexeyAB/darknet#1067]
Hi @AlexeyAB!

I have previously made a custom dataset for detecting ships, and in my previous attempts have been using a Keras/Tensorflow implementation of YOLO, however I am now considering changing to using your repo as the framework for my project.

A problem arises in that all my annotation files are in the VOC xml format, and the issue i would like help to resolve is converting theese annotation files to the darknet .txt format.
I am fairly new to Machine Learning and python in general, and am wondering whether the voc_label.py script can be adjusted to help me accomplish this or whether I will have to find another solution.

Thanks for any help in advance!

**Comment by AlexeyAB** [comment]
@erlendhade Hi,

Yes, you can use `voc_label.py` script.

Also you can check your resulting darknet-format, just put txt-labels to the same directory where are images, and run Yolo_mark: https://github.com/AlexeyAB/Yolo_mark

`./yolo_mark /img_directory /train.txt /obj.names`

**Comment by erlendhade** [comment]
What a relief!

The dataset is organized as follows: 
    train/images and train/annotations

Could you tell me what changes I would have to do to `voc_labels.py`?

**Comment by AlexeyAB** [comment]
Try to put your images, labels and voc_label.py in a such way:
```
VOCdevkit\VOC2007\JPEGImages
VOCdevkit\VOC2007\Annotations
voc_label.py
yolo_mark
```

Then just run `voc_label.py`.
Then put generated files from `VOCdevkit\VOC2007\labels` to the `VOCdevkit\VOC2007\JPEGImages` and run Yolo_mark:
`./yolo_mark /VOCdevkit/VOC2007/JPEGImages /train.txt /obj.names`

If you will see correct bounding boxes in the images by using Yolo_mark, then everything is fine.

**Comment by erlendhade** [comment]
OK

I will try to get it working before bothering you more, thank you for your assistance!

**Comment by erlendhade** [comment]
Hi again @AlexeyAB 

I organized the files as you instructed

folder structure:

VOCdevkit\VOC2007\JPEGImages
VOCdevkit\VOC2007\Annotations
voc_label.py
Yolo_mark 

In JPEGImages there are just .jpg images
In Annotations there are just .xml files

when I run voc_label.py i get the error:
`Traceback (most recent call last):
  File "voc_label.py", line 50, in <module>
    image_ids = open('VOCdevkit/VOC%s/ImageSets/Main/%s.txt'%(year, image_set)).read().strip().split()
FileNotFoundError: [Errno 2] No such file or directory: 'VOCdevkit/VOC2007/ImageSets/Main/train.txt'`

Could you tell me how to proceed?

**Comment by erlendhade** [comment]
Nevermind, got it working fine.

Thank you for your help

**Comment by AlexeyAB** [comment]
> when I run voc_label.py i get the error:
> Traceback (most recent call last): File "voc_label.py", line 50, in <module> image_ids = open('VOCdevkit/VOC%s/ImageSets/Main/%s.txt'%(year, image_set)).read().strip().split() FileNotFoundError: [Errno 2] No such file or directory: 'VOCdevkit/VOC2007/ImageSets/Main/train.txt'

How did you fix it?
