### ISSUE TITLE
How to use gstreamer to decode rtsp in your code

### ISSUE THREAD

**Issue by mahxn0** [AlexeyAB/darknet#1069]
I used  gstreamer at opencv  to decode rtsp stream , example:
`./darknet detector demo cfg/yolov3-tiny_cat.cfg yolov3-tiny_cat_final.weights "rtspsrc location = rtsp://admin:666666@192.168.0.222:554/h264/ch1/main/av_stream latency=0 ! rtph264depay ! h264parse ! omxh264dec ! videoconvert ! appsink sync=false"  ` 
but there some error , 
![image](https://user-images.githubusercontent.com/19154155/41641684-a77907ae-7498-11e8-891f-ca67c02a647e.png)
pjreddie version  no this error
![1529477108 1](https://user-images.githubusercontent.com/19154155/41641658-8f919142-7498-11e8-9d32-cca138d413e6.jpg)

i change get_capture_from_video to cvCaptureFromFile,   same error occured .

**Comment by AlexeyAB** [comment]
@mahxn0 Hi,

I fixed it. Update your code from GitHub.

**Comment by mahxn0** [comment]
thank you@AlexeyAB
