### ISSUE TITLE
Is there memory leakage in darknet code ?

### ISSUE THREAD

**Issue by vg123** [AlexeyAB/darknet#107]
I am calling test_detector() with command  `./darknet detector test cfg/obj.data cfg/yolo-obj.cfg yolo-obj_13000.weights images/1.jpg`  and also I edited your code in `darknet.c` where I just added an infinite loop in the `main()` function, So that program do not terminate after returning from `run_detector()` in `main()` of `darknet.c`.

But when It returns program is not releasing `70MB` of memory,  where is this leakage,  please help me I have freed almost all allocated memory after returning from the `test_detector()` function.

Below are the codes with my edit.

`detector.c` 
```
void test_detctor(...){
        .....
        .....
        .....
        free_image(im);
        free_image(sized);
        free(boxes);
        free_ptrs((void **)probs, l.w*l.h*l.n);
        if (filename) break;
    }
    
    free_network(net);
    free_list(options);
 //   free(name_list);
    int name_iterator;
    for(name_iterator=0;name_iterator<37;name_iterator++)   //38 is number of classes.
    {
        free(names[name_iterator]);
    }
    int alpha_iterator;
    for(alpha_iterator=0;alpha_iterator<8;alpha_iterator++) // nsize is 8 
    {
        free_image(*alphabet[alpha_iterator]);
    }   
    free(alphabet); 
}
```

`darknet.c`

```
int main(int argc, char **argv){
....
....
....
 while(1){ printf("a");}
....
}
```

after returning from run_detector() back into main()
`htop`
![htop](https://user-images.githubusercontent.com/18382096/27280147-871e3178-5504-11e7-9f36-e636f88fe087.png)

Why this 0.9% of memory is still consumed by this program?

**Comment by AlexeyAB** [comment]
Yes, there is memory leak: https://github.com/AlexeyAB/darknet/issues/56

I have not yet looked for a place where a memory leak occurs.

But it occurs only if you init and de-init Yolo many times - i.e. if you stert `test_detector()` many times. So if you will start `test_detector()` only once, and if you will work only in this loop, then you will not see memory leak: https://github.com/AlexeyAB/darknet/blob/b585124e55fcd18a7511d3b2fdc6bc3db5368ef4/src/detector.c#L480

**Comment by vg123** [comment]
The structure of node(declared in `darknet.h`) has a ` void *val ` . But in `free_node` function(written in `list.c` ) you directly free the node without releasing the memory pointed by `*val` . Can that be a reason for memory leak??

**Comment by AlexeyAB** [comment]
@vg123 Hi,

The memory of the variable `void *val` is released in the `void free_list_contents(list *l)`: https://github.com/AlexeyAB/darknet/blob/master/src/list.c#L77

Other memory leaks are fixed now.
