### ISSUE TITLE
libopencv_highgui.so.3.4 error

### ISSUE THREAD

**Issue by erlendhade** [AlexeyAB/darknet#1077]
Hi @AlexeyAB 

I have recently compiled darknet, and to my knowledge I did so successfully

When i try to run: `./darknet detector demo cfg/yolov3.cfg yolov3.weights -i 0 -thresh 0.4`
I get the error message: `./darknet: error while loading shared libraries: libopencv_highgui.so.3.4: cannot open shared object file: No such file or directory
`
The file exists, and is located in /usr/local/lib

I used your instructions in #861 to compile opencv

**Comment by ahsan856jalal** [comment]
which version of OpenCV is installed
pkg-config --modversion opencv ?
try to make the darknet after enabling opencv in Makefile by Opencv=1 and
see whether you are getting errors or not
I had this issue when I was using opencv 3.4.1
Regards
Ahsan

**Comment by erlendhade** [comment]
`pkg-config --modversion opencv
3.4.0`
In makefile opencv = 1

I do not get compilation errors while compiling darknet..

**Comment by ahsan856jalal** [comment]
this '.so' file is present in /usr/local/lib folder. you can check yours
by the way the darknet command should have .data file as well
./darknet detector demo dataq/your_obj.data cfg/yolov3.cfg yolov3.weights
-i 0 -thresh 0.4
Regards
Ahsan

**Comment by erlendhade** [comment]
I can confirm that the .so file is present in /usr/local/lib

`./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights -i 0 -thresh 0.4
` 
 still returns
`./darknet: error while loading shared libraries: libopencv_highgui.so.3.4: cannot open shared object file: No such file or directory
`

**Comment by AlexeyAB** [comment]
Just try to copy `libopencv_highgui.so.3.4` to the Darknet directory.

Or set path to it in the `bashrc.` file: https://stackoverflow.com/questions/41042952/update-bashrc-file-to-locate-opencv-libraries

**Comment by erlendhade** [comment]
This solved the issue for me: 

In opencv-3.x.x directory
`mkdir build`
`cd build`
`cmake -D CMAKE_BUILD_TYPE=RELEASE -D BUILD_EXAMPLES=ON -D WITH_FFMPEG=ON -D WITH_V4L=ON -D WITH_OPENGL=ON -D WITH_CUDA=ON -D CUDA_ARCH_BIN="3.0 5.0 6.1" -D WITH_CUBLAS=ON -D WITH_CUFFT=ON -D WITH_EIGEN=ON (+filepath to CMakeLists.txt)

make all -j8
make install
`
`export LD_LIBRARY_PATH=/PATH_TO_.so_FILES/${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}`

then in darknet dir
`make`
