### ISSUE TITLE
local webcam get lower frame rate?

### ISSUE THREAD

**Issue by mcjjin** [AlexeyAB/darknet#109]
hi

I have  run the yolo-voc demo detector succesfully using a local webcam but the frame rate only takes around 7 FPS　and for video-files with the same yolo-voc demo I got over 50FPS , So is there anything wrong with my setting?　I work it on Nvidia Gforce 1070 8G and i7 -7700k and CUDA 8.0 with cudnn 5.1 
below are the out data

![local webcam 1](https://user-images.githubusercontent.com/8590489/27444102-da6430b2-57a7-11e7-9065-e287604c9b13.png)
![local webcam 2](https://user-images.githubusercontent.com/8590489/27444103-db7edeca-57a7-11e7-9060-3596aad3a637.png)
![mp4 file 1](https://user-images.githubusercontent.com/8590489/27444109-e0519b5e-57a7-11e7-83f9-eb5b2ce2bb32.png)
![mp4 file 2](https://user-images.githubusercontent.com/8590489/27444115-e2f3eede-57a7-11e7-9084-e3fa4b41ee84.png)

**Comment by AlexeyAB** [comment]
Hi,

Can you write a simple example (in C/C++ and OpenCV) that gets frames from VideoCam, show it in window and measures FPS? Then how many FPS can you get by this example?

May be your webcam can't give out more 7 FPS.

**Comment by mcjjin** [comment]
hi 
I have run the test on my mobile camera with Net cam and it runs about 40FPS so it should be my VideoCam problem Thanks 👍
