### ISSUE TITLE
Keep getting error complaining about the CUDA driver version

### ISSUE THREAD

**Issue by chinmay5** [AlexeyAB/darknet#1090]
I keep getting this error when I try to start the training

CUDA Error: CUDA driver version is insufficient for CUDA runtime version
darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
Aborted (core dumped)

**Comment by AlexeyAB** [comment]
You should install new nVidia driver.

**Comment by chinmay5** [comment]
I would need some hep understanding this. I have the results:-
![image](https://user-images.githubusercontent.com/16525717/41819933-8abccd9c-77c9-11e8-8408-d2d79df89e68.png)
And,
![image](https://user-images.githubusercontent.com/16525717/41819940-9cc09dd4-77c9-11e8-9337-9204a3625d1f.png)

I don't know what exactly I need to do since the execution is not even starting
![image](https://user-images.githubusercontent.com/16525717/41819946-b93b8316-77c9-11e8-8f49-5ff7425067fb.png)

**Comment by AlexeyAB** [comment]
There is actual nVidia GPU driver inside cuda-installator.
You can try to reinstall CUDA, and during CUDA installation press to install nVidia GPU driver.

**Comment by AlexeyAB** [comment]
Try to set `CUDNN=0` in the Makefile and recompile
```
make clean
make -j8
```

**Comment by chinmay5** [comment]
Seemed there was some weird error with my CUDA installation. I shut down my cloud GPU and when I tried running it today, it worked fine. I will close this issue. Thank you so much for your support
