### ISSUE TITLE
avg loss -nan 

### ISSUE THREAD

**Issue by varen27** [AlexeyAB/darknet#1097]
the training  goes ok initially but after 150 iteration the avg loss and everything becomes -nan
i have tried couple of times , it is happening again and again.

**Comment by hasirk** [comment]
To add to this; I then re trained using original anchor boxes in YOLO V3 and the training runs without avg loss being nan. Now it's over 5200 iterations. However, the avg loss is still just fluctuating in between 10-14 from about 1000th iteration. 

So the previous problem was due to custom anchor boxes ?

Custom anchor boxes I got was like below;
6.5459,10.4597, 14.0183,24.3307, 27.1623,43.2734, 31.8321,96.9522, 56.3607,63.7827, 92.0249,108.4348, 73.0259,175.0636, 141.2092,177.6285, 144.3338,290.7226

**Comment by AlexeyAB** [comment]
@hasirk 

> Now it's over 5200 iterations. However, the avg loss is still just fluctuating in between 10-14 from about 1000th iteration.

What mAP can you get? https://github.com/AlexeyAB/darknet#when-should-i-stop-training
`./darknet detector map data/obj.data yolo-obj.cfg backup\yolo-obj_5200.weights`

**Comment by hasirk** [comment]
I just checked the results, below is the output. I can’t figure what I am doing wrong here. 

detections_count = 0, unique_truth_count = 185578  
class_id = 0, name = bike,   ap = 0.00 % 
class_id = 1, name = bus,   ap = 0.00 % 
class_id = 2, name = car,   ap = 0.00 % 
class_id = 3, name = motor,   ap = 0.00 % 
class_id = 4, name = person,   ap = 0.00 % 
class_id = 5, name = rider,   ap = 0.00 % 
class_id = 6, name = traffic light,   ap = 0.00 % 
class_id = 7, name = traffic sign,   ap = 0.00 % 
class_id = 8, name = train,   ap = 0.00 % 
class_id = 9, name = truck,   ap = 0.00 % 
 for thresh = 0.25, precision = -nan, recall = 0.00, F1-score = -nan 
 for thresh = 0.25, TP = 0, FP = 0, FN = 185578, average IoU = 0.00 % 

 mean average precision (mAP) = 0.000000, or 0.00 % 
Total Detection Time: 506.000000 Seconds

**Comment by hasirk** [comment]
@AlexeyAB 
In your code 'utils.c' I have changed the code part in 'void replace_image_to_label(char *input_path, char *output_path) { }' to read labels from different folder. I hope it doesn't have anything to do with the training.

**Comment by AlexeyAB** [comment]
@hasirk 

* So in all cases your training goes wrong, due to wrong dataset
* What dataset do you use?
* What folders do you have in your dataset?
* Did you create your dataset by using Yolo_mark? https://github.com/AlexeyAB/Yolo_mark
* Did you check your dataset by using Yolo_mark? https://github.com/AlexeyAB/Yolo_mark

https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

> check that each object are mandatory labeled in your dataset - no one object in your data set should not be without label. In the most training issues - there are wrong labels in your dataset (got labels by using some conversion script, marked with a third-party tool, ...). Always check your dataset by using: https://github.com/AlexeyAB/Yolo_mark

**Comment by hasirk** [comment]
@AlexeyAB 

- Dataset I use is [BDD](https://github.com/ucbdrive/bdd-data). 
- The structure is as below;

> bdd100k

    |-- images/100k/
            |-- train
                |-- [xxxxxxxx-xxxxxxx].jpg
            |-- val
                |-- [xxxxxxxx-xxxxxxx].jpg
    |-- labels/100k/
            |-- train
                |-- [xxxxxxxx-xxxxxxx].txt
                |-- [xxxxxxxx-xxxxxxx].json
            |-- val
                |-- [xxxxxxxx-xxxxxxx].txt
                |-- [xxxxxxxx-xxxxxxx].json

- I use a python code that I wrote to convert the original .json files to .txt files. Attach is my python file and few sample label and image files.
[data.tar.gz](https://github.com/AlexeyAB/darknet/files/2147763/data.tar.gz)

- I check with your Yolo Mark repo and the labels are displayed correctly on the image. 

- Do also note that I have trained the same dataset with https://pjreddie.com/darknet/yolo/ earlier. But the after 25k iteration the avg loss was fluctuating around 7. So that's why I wanted to try your repo to further reduced the error, which was the case when I trained Yolo V2 with your repo.

**Comment by AlexeyAB** [comment]
@hasirk 

> I use a python code that I wrote to convert the original .json files to .txt files. Attach is my python file and few sample label and image files.
> data.tar.gz

**Your dataset is correct.**

----

> Do also note that I have trained the same dataset with https://pjreddie.com/darknet/yolo/ earlier. But the after 25k iteration the avg loss was fluctuating around 7. So that's why I wanted to try your repo to further reduced the error, which was the case when I trained Yolo V2 with your repo.

Can you detect anything by using this trained weights-file?

----


1. What parameters do you use in the Makefile? And can you show your cfg-file?

> In your code 'utils.c' I have changed the code part in 'void replace_image_to_label(char *input_path, char *output_path) { }' to read labels from different folder. I hope it doesn't have anything to do with the training.

2. Try to revert this changes. Then put all txt-files to the same directory with jpg-files. And train it by using this repository. Then try to check mAP.

3. It looks like that there are many small objects, 
* base your cfg-file on `yolov3.cfg` (not on yolov3-tiny.cfg)
* set `max=60` for each of 3 `[yolo]` layer
* try to increase `width=736 height=416` instead of `width=416 height=416`, and recalculate anchors 
    `./darknet detector calc_anchors data/obj.data -num_of_clusters 9 -width 736 -height 416`
    * if the error out of memory occurs then increase `subdivisions=32` or 64

**Comment by hasirk** [comment]
@AlexeyAB 
I can detect all most all objects using trained weights using https://pjreddie.com/darknet/yolo/ . But I could not get a mAP for the validation set. But instead it saved all the detection result per each class in seperate txt files for each class. Please check the attachment.
[results.tar.gz](https://github.com/AlexeyAB/darknet/files/2151415/results.tar.gz)
![predictions](https://user-images.githubusercontent.com/17522266/42121431-8c76f7f8-7c1e-11e8-9e06-ddc4e4d3725e.jpg)

1. My Makefile configuration is as below and cfg is as attached.
GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=1
AVX=0
OPENMP=0
LIBSO=0

[yolov3-bdd.cfg.txt](https://github.com/AlexeyAB/darknet/files/2151416/yolov3-bdd.cfg.txt)

2. Only change I did is as below. But I will revert and retrain as per your instruction in point 3 and update you.  
`find_replace(output_path, "/images/", "/labels/", output_path);`

**Comment by hasirk** [comment]
@AlexeyAB 

> set max=60 for each of 3 [yolo] layer

I cannot find such 'max' parameter in cfg file. Can you kindly direct me ?

**Comment by AlexeyAB** [comment]
@hasirk 

This is strange that you can get mAP:
`./darknet detector map data/obj.data yolo-obj.cfg backup\yolo-obj_5200.weights`

Try to comment this line `find_replace(output_path, "/images/", "/labels/", output_path);`, put txt-files in the same directory where are images, and run `detector map`.

**Comment by hasirk** [comment]
@AlexeyAB 
 I changed the anchor boxes as you suggested and did brand new clone of your repo and trained again. But did not used below as I have already started training by that time. 
> Just add in each [yolo] layer new parameter max=100 in these 3 places:

Average loss started reducing slowly and stopped the training at below point to test the mAP.
>  2351: 6.500229, 6.660212 avg loss, 0.001000 rate, 14.105374 seconds, 150464 images

The new structure of the dataset is as below
> bdd100k

    |-- images/100k/
            |-- train
                |-- [xxxxxxxx-xxxxxxx].jpg
                |-- [xxxxxxxx-xxxxxxx].txt
            |-- val
                |-- [xxxxxxxx-xxxxxxx].jpg
                |-- [xxxxxxxx-xxxxxxx].txt

The mAP I got was as below;
> ./darknet detector map data/obj.data yolo-obj.cfg backup/yolo-obj_2300.weights

    detections_count = 1080159, unique_truth_count = 185578  
    class_id = 0, name = bike, 10801 ap = 11.54 % 
    class_id = 1, name = bus, 	 ap = 22.49 % 
    class_id = 2, name = car, 	 ap = 53.64 % 
    class_id = 3, name = motor, 	 ap = 7.77 % 
    class_id = 4, name = person, 	 ap = 31.14 % 
    class_id = 5, name = rider, 	 ap = 14.57 % 
    class_id = 6, name = traffic light, 	 ap = 30.63 % 
    class_id = 7, name = traffic sign, 	 ap = 43.57 % 
    class_id = 8, name = train, 	 ap = 0.00 % 
    class_id = 9, name = truck, 	 ap = 31.14 % 
    for thresh = 0.25, precision = 0.68, recall = 0.37, F1-score = 0.48 
    for thresh = 0.25, TP = 68660, FP = 32835, FN = 116918, average IoU = 49.61 % 
    mean average precision (mAP) = 0.246514, or 24.65 % 
    Total Detection Time: 721.000000 Seconds

I calculated the anchors using the below code;
> ./darknet detector calc_anchors data/obj.data -num_of_clusters 9 -width 736 -height 416

The make file, cfg file, obj.data and anchors file is as attached below;
[anchors.txt](https://github.com/AlexeyAB/darknet/files/2152408/anchors.txt)
[Makefile.txt](https://github.com/AlexeyAB/darknet/files/2152409/Makefile.txt)
[yolo-obj.cfg.txt](https://github.com/AlexeyAB/darknet/files/2152410/yolo-obj.cfg.txt)
[obj.data.txt](https://github.com/AlexeyAB/darknet/files/2152412/obj.data.txt)

**When writing the anchor boxes to yolo-obj.cfg I get rid of the decimal places and just use integer values.** @AlexeyAB I do not know whether this has any effect.

@AlexeyAB Do I still need to add the below or keep training as it is ? What do you think is better ?
> Just add in each [yolo] layer new parameter max=100 in these 3 places:

 Thank you so much fir helping me out.

**Comment by AlexeyAB** [comment]
@hasirk 
You can keep training as it is.

Also later try to calculate mAP for previous weights-file that you got by training on  pjreddie/darknet. Just to compare is there any improvements.

**Comment by AlexeyAB** [comment]
@hasirk What avg loss can you get now?
For some dataset good avg loss can be ~1.0, so it depends on dataset. 
mAP is much more important than avg loss.

**Comment by hasirk** [comment]
@AlexeyAB 
It's still around 5. 
Thanks

**Comment by andeyeluguo** [comment]
Will you please release the model you have trained?  I have train the by your config file which is finetuned from the yolov3.weights from the darknet website?  But It only get   when it trained 6200.
`detections_count = 1328659, unique_truth_count = 185578
class_id = 0, name = car,  13286 ap = 46.33 %
class_id = 1, name = bus,        ap = 22.95 %
class_id = 2, name = person,     ap = 28.44 %
class_id = 3, name = bike,       ap = 17.53 %
class_id = 4, name = truck,      ap = 35.64 %
class_id = 5, name = motor,      ap = 8.39 %
class_id = 6, name = train,      ap = 0.00 %
class_id = 7, name = rider,      ap = 19.43 %
class_id = 8, name = traffic sign,       ap = 35.77 %
class_id = 9, name = traffic light,      ap = 21.59 %
 for thresh = 0.25, precision = 0.46, recall = 0.45, F1-score = 0.46
 for thresh = 0.25, TP = 83341, FP = 97210, FN = 102237, average IoU = 32.41 %

 mean average precision (mAP) = 0.236072, or 23.61 %
`

**Comment by hasirk** [comment]
@andeyeluguo 
Sorry I don't know for sure which one is the weight file for this results as it's long time back. But may be you can try the one below and let me know.
https://entuedu-my.sharepoint.com/:u:/g/personal/karu0009_e_ntu_edu_sg/Ed1xrpPqrhxIkFAchP-6UNMB6bxdqYJBOKgXHESAFeeQew?e=x7QvGi

**Comment by andeyeluguo** [comment]
The model seems train from kitti not BDD100K....

the map is zero.

**Comment by andeyeluguo** [comment]
@AlexeyAB 
also the iou is very low,only 33. 
Can you give me some advice to get the iou up?
Thank you very  very much.

**Comment by hasirk** [comment]
@andeyeluguo 
Please try this link below;
https://entuedu-my.sharepoint.com/:u:/g/personal/karu0009_e_ntu_edu_sg/EeuhfZYPM01PjMUlZMa-VlwBZW5X2Y7ztqJaKc8u7jc49g?e=fhlBuT

If not try this one;
https://entuedu-my.sharepoint.com/:u:/g/personal/karu0009_e_ntu_edu_sg/EayOLZBvruJHu6v_hnXWFl4BbSTdsN5CO7SGaR5QEOGEfg?e=PnT80P

**Comment by AlexeyAB** [comment]
@hasirk Can you share cfg-files for these weights there https://github.com/AlexeyAB/darknet/issues/3874 ?

I created pinned issue where anybody can post trained models.
