### ISSUE TITLE
Additional bounding box prediction ?

### ISSUE THREAD

**Issue by phongnhhn92** [AlexeyAB/darknet#110]
Hello guys, I have a quick question. Normally a bounding box has 5 elements: x,y,w,h and confidence score.
In my case, the object I would like to detect is a sign which has an arrow with a direction(up,down,left,right). Is that possible for me to add the 6th direction to the bounding box information and if it is possible then how to do it ?
I would appreciate if someone can help me on this.
Thanks !

**Comment by AlexeyAB** [comment]
Hi,

* Simple way is to mark arrow for each direction as separate class of object. So arrow with a direction(up,down,left,right) are 4 different objects.

* There are many places where 5 is hardcoded, so if you want to add the 6th direction to the bounding box information, then you should change many places in the source code.

**Comment by phongnhhn92** [comment]
I tried doing as your first suggestion but the result is poor especially when the sign is rotated so that the up sign will look like down or left sign. It's much better to have a model to be able to predict direction. I guess you dive into the source code more than me when you said 5 is hardcoded many times so would you tell me where are they ? I am please to help you out on this one if you dont have time.

**Comment by AlexeyAB** [comment]
* I think if everything is done correctly, then there should not be problems with finding different directions, as different objects. You need to switch off the flip (mirror flip of the image during data augmentation) - comment this line `// if(flip) flip_image(sized);` https://github.com/AlexeyAB/darknet/blob/b585124e55fcd18a7511d3b2fdc6bc3db5368ef4/src/data.c#L710

* Start your search here - `region_layer.c`
`get_region_boxes()` and other functions: https://github.com/AlexeyAB/darknet/blob/b585124e55fcd18a7511d3b2fdc6bc3db5368ef4/src/region_layer.c#L337

    And change this line: https://github.com/AlexeyAB/darknet/blob/b585124e55fcd18a7511d3b2fdc6bc3db5368ef4/cfg/yolo-voc.2.0.cfg#L224

**Comment by phongnhhn92** [comment]
Ok thanks! I will work on this one and update progress on this thread.
