### ISSUE TITLE
lists images is right?

### ISSUE THREAD

**Issue by swy0915** [AlexeyAB/darknet#1100]
To process a list of images data/train.txt and save results of detection to result.txt use:
darknet.exe detector test data/voc.data yolo-voc.cfg yolo-voc.weights -dont_show -ext_output < data/train.txt > result.txt

i change 'darknet.exe detector test data/voc.data yolo-voc.cfg yolo-voc.weights -dont_show -ext_output data/train.txt result.txt'
i run this command ,but it's wrong, i think it can't process a list of images.

**Comment by swy0915** [comment]
this command is right,i am wrong,sorry

**Comment by AlexeyAB** [comment]
This command is correct:  https://github.com/AlexeyAB/darknet#how-to-use-on-the-command-line

`./darknet detector test cfg/voc.data yolo-voc.cfg yolo-voc.weights -dont_show -ext_output < data/train.txt > result.txt`
