### ISSUE TITLE
The reason of -nan, -nan(ind)

### ISSUE THREAD

**Issue by xitman47** [AlexeyAB/darknet#111]
Alex, hi,

I have the same issues mentioned in this thread:
[The reason of -nan, -nan(ind)](https://github.com/AlexeyAB/darknet/issues/19)

I keep getting -1.#IND00 though average loss is calculated at the end of batch. BUT it goes from 10-20 to 0.01 in like 100 batches which is very quick! And if you check predictions they are empty.. I've tried playing with learn rate, threshold, image size, batches/subdivisions and so on but the problem hasn't gone.

May I kindly ask you to check if it works OK on your machine? I think maybe I haven't built YOLO properly. I couldnt attach data here so I am sharing link (100 mb):
[nan_problem](https://drive.google.com/file/d/0ByCQKhoqwUJ5cGl2Q1VqUTNyaDA/view?usp=sharing)

Many thanks!

**Comment by AlexeyAB** [comment]
@xitman47 Hi,

Your label text-files are wrong:

> 2 116.79071045 186.861824036 72.9339599609 54.8262176514
> 3 271.209495546 179.568431854 54.8262176514 71.4249801636
> 3 45.6172866796 64.8860740662 48.2873077393 31.1855545044
> 2 69.2579460144 110.909915924 64.3830795288 42.7543869019
> 0 154.012464518 101.856040955 50.8022727966 62.8740997314

Coord values should be more than 0, and less than 1.

----

You should use this tool **Yolo_mark**: https://github.com/AlexeyAB/Yolo_mark

Read this: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

> 
> 5. Create `.txt`-file for each `.jpg`-image-file - in the same directory and with the same name, but with `.txt`-extension, and put to file: object number and object coordinates on this image, for each object in new line: `<object-class> <x> <y> <width> <height>`
> 
>   Where: 
>   * `<object-class>` - integer number of object from `0` to `(classes-1)`
>   * `<x> <y> <width> <height>` - float values relative to width and height of image, it can be equal from 0.0 to 1.0 
>   * for example: `<x> = <absolute_x> / <image_width>` or `<height> = <absolute_height> / <image_height>`
>   * atention: `<x> <y>` - are center of rectangle (are not top-left corner)
> 
>   For example for `img1.jpg` you should create `img1.txt` containing:
> 
>   ```
>   1 0.716797 0.395833 0.216406 0.147222
>   0 0.687109 0.379167 0.255469 0.158333
>   1 0.420312 0.395833 0.140625 0.166667
>   ```
>

**Comment by xitman47** [comment]
Alex,

Thank you very much for quick response and your help, nuch appreciated! It works! Last time it worked without normalization so I thought it should work again.

Last q - darknet19_448 weights have 448 in file name. Should I set 448x448 input image size in .cfg file or default 416x416? Can I increase resolution during training to find small objects, I mean is it acceptable as darknet19_448 weights were designed for certain resolution and would it help? Or I should just increase resolution during detection?

**Comment by AlexeyAB** [comment]
You can use any resolution of network multiple of 32.
For example: 288, 416, 448, 608, 832, 1088, ...

**Comment by xitman47** [comment]
Thank you!
