### ISSUE TITLE
avoid load image after detection

### ISSUE THREAD

**Issue by thriskel** [AlexeyAB/darknet#1110]
I want to detect objects in the image only showing it in the console without showing the image frame, what  should I modify?

**Comment by AlexeyAB** [comment]
Use flag `-dont_show` at the end of command

**Comment by thriskel** [comment]
I did try it but  is still showing

**Comment by AlexeyAB** [comment]
* Do you use this repository?
* Show your command

**Comment by thriskel** [comment]
darknet.exe detect yolo-obj.cfg backup/yolo-obj_17848.weights data/ladybug_cube_000694_2.jpg -thresh 0.50 -gpus 0,1 -dont_show

**Comment by AlexeyAB** [comment]
This is wrong command. 
Use such command:
`darknet.exe detector test obj.data yolo-obj.cfg backup/yolo-obj_17848.weights data/ladybug_cube_000694_2.jpg -thresh 0.50 -dont_show`

----

`-gpus 0,1` - can be used for training only, not for detection

`darknet.exe detect` - can be used for COCO-model only, not for custom models

More:  https://github.com/AlexeyAB/darknet#how-to-use-on-the-command-line

**Comment by thriskel** [comment]
Thank you, working great :+1:
