### ISSUE TITLE
Can I Learn even small images ?

### ISSUE THREAD

**Issue by RexKT** [AlexeyAB/darknet#1112]
Hi,

Can I learn even small images?

I could not do it well.

For example, Image size is 416 * 32.

I tried the following settings

[net]
width=416
height=32

[yolo]
anchors = 11.3186,18.4342, 11.3495,23.6338, 16.2385,21.0475, 13.2598,28.8015, 16.0004,25.3587, 20.3254,24.8049, 18.4719,29.2200, 23.0463,28.7159, 27.3326,29.7581

If you had known about that, please tell me how to set up.

Thank you

**Comment by AlexeyAB** [comment]
Hi,

* Do all of your images have the same size 416x32?
* Did you recalculate anchors and change in all 3 [yolo]-layer? https://github.com/AlexeyAB/darknet#how-to-improve-object-detection
`darknet.exe detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 32`

> I could not do it well.

* How many iterations did you train and what mAP did you get? https://github.com/AlexeyAB/darknet#when-should-i-stop-training

**Comment by RexKT** [comment]
Thanks for the reply.

>・Do all of your images have the same size _416x32?

Yes, Learning image are all same size(416x32).
but, I pasted a random small image to the white background.

>・Did you recalculate anchors and change in all 3 [yolo]-layer?

Yes, I chenged the all 3[yolo]-layer.


>・How many iterations did you train and what mAP did you get?

I trained 50020 times and got the mAP value is 95.46%
Other result:  
for thresh = 0.25, precision = 0.92, recall = 1.00, F1-score = 0.96
for thresh = 0.25, TP = 54627, FP = 4496, FN = 216, average IoU = 80.85 %


I can detect to a certain extent. 
but, Sometimes detected frame in a strange place.

Here is the file No.1: 
![miss image1](https://user-images.githubusercontent.com/40647814/42074413-19ef556c-7ba7-11e8-95c3-0513c0bbce3c.jpg)

Here is the file No.2: 
![miss image2](https://user-images.githubusercontent.com/40647814/42074424-26d93c84-7ba7-11e8-960e-7020de7b9990.jpg)




Thank you in advance.

**Comment by AlexeyAB** [comment]
@RexKT Can you attach your cfg-file? Just rename it to txt file and drag-n-drop to your message.

**Comment by RexKT** [comment]
Thanks for the reply.

>@RexKT Can you attach your cfg-file?

Here is my cfg-file:
[yolov3-custom-train.txt](https://github.com/AlexeyAB/darknet/files/2153438/yolov3-custom-train.txt)

>Also did you check your dataset by using Yolo_mark?

Yes. It is as follows:
![yolo_mark_s](https://user-images.githubusercontent.com/40647814/42141340-88e7cf4c-7de3-11e8-81ae-3e1816249cea.png)

Thank you in advance.

**Comment by AlexeyAB** [comment]
> Here is my cfg-file:
> yolov3-custom-train.txt

Use `saturation=1` instead of `saturation=0` to disable color data augmentation.

And set `steps=40000,45000` instead of `steps=400000,450000`

Also try to set `ignore_thresh = .7` instead of `ignore_thresh = .5` in each of 3 `[yolo]`-layers, may be it will solve this issue:
![miss image2](https://user-images.githubusercontent.com/40647814/42074424-26d93c84-7ba7-11e8-960e-7020de7b9990.jpg)

And train again from the begining.

**Comment by RexKT** [comment]
I changed cfg file as follows and learned it again (50020 iteration).
・saturation=1
・steps=40000,45000
・ignore_thresh = .7 in each of 3 [yolo]-layers

As a result, I could improve false detection a little.
However, there is a false detection as described below,
and the value of "prob" is also high (65.8%), so it is difficult to remove it.
![06756_t 5d a _r 5d a d a](https://user-images.githubusercontent.com/40647814/42297039-10443700-8037-11e8-829a-3f60962ed894.png)


Because the target image was very similar to mine,
I also carried out the following advice on issue # 1123.

>Can you show screenshot of result of this command?
darknet.exe detector calc_anchors data/obj.data -num_of_clusters 5 -width 13 -height 9

The result as follows:
0.3531,3.8528, 0.4225,4.6509, 0.4847,5.3221, 0.5472,5.9653, 0.6093,6.5904
As a result, false detection has increased very much.

And I also learned the image like below with yolov3.cfg's default network size and anchor.
As a result, there was no false detection.
However, in order to detect it faster, I would like to reduce the network size to about 416 * 32.
![00056](https://user-images.githubusercontent.com/40647814/42297044-1bcfffdc-8037-11e8-9017-1642d3c8ad23.jpg)

Because it is very effective to change the setting of the anchor,
please advise the setting of a better anchor.

Thank you in advance.

**Comment by AlexeyAB** [comment]
You can just pseudo-disable the 1st [yolo]-layer:

* Change last 3 anchors values to the very high values:
`anchors = 11.3186,18.4342, 11.3495,23.6338, 16.2385,21.0475, 13.2598,28.8015, 16.0004,25.3587, 20.3254,24.8049, 100,100, 200,200, 300,300`

* Set it for all 3 [yolo] layers

* Train again.

* And check mAP

So will be used only 2nd and 3rd [yolo]-layers with higher size of final feature map, so it can distinguish close placed objects better.

**Comment by RexKT** [comment]
I changed the anchors and trained again(50020 iteration).
The result as follows:
     for thresh = 0.25, precision = 0.99, recall = 1.00, F1-score = 1.00
     for thresh = 0.25, TP = 72936, FP = 416, FN = 56, average IoU = 89.06 %
     mean average precision (mAP) = 0.992149, or 99.21 %

If the threshold is lowered, the following false detection will occur,
but since it can be erased later, there is no problem.
![00720_t f b 2 a 8 _r 3 a f b 2 a 8](https://user-images.githubusercontent.com/40647814/42425366-60abab6a-8357-11e8-85f8-10d97c625859.png)
![09043_t 75t a p a z 2 c9 a m c t a v b 7d a _r 75t a p a z 2 c9 a m c t a t a v b 7d a](https://user-images.githubusercontent.com/40647814/42425368-674e8fc8-8357-11e8-8cbf-9b1d0bdcccf7.png)

Thank you for your advice.

**Comment by zhliu2018** [comment]
@RexKT  Hi, My data is very similar to you， and  the resolution is low（about 100*50）,how can I improve recall using yolov3.Can you tell me your resolution  of your picture?

**Comment by AlexeyAB** [comment]
@zhliu2018 Resolution of picture is 416x32.
So just set very high last 6 values in you `anchors` like `100,100, 200,200, 300,300` in each of 3 [yolo] layers in your cfg-file.

**Comment by Lepiloff** [comment]
@RexKT I try to do the same thigs. Do you have dataset with characters for training?

**Comment by eye289475** [comment]
I read. It's a wonderful character enclosure.
I want to use this yolo, how do I do it?
can you tell me?
Now I can use keras-yolov3 Ordinary pattern.

**Comment by KO-KMS-AT12** [comment]
> Thanks for the reply.
> 
> > @RexKT Can you attach your cfg-file?
> 
> Here is my cfg-file:
> [yolov3-custom-train.txt](https://github.com/AlexeyAB/darknet/files/2153438/yolov3-custom-train.txt)
> 
> > Also did you check your dataset by using Yolo_mark?
> 
> Yes. It is as follows:
> ![yolo_mark_s](https://user-images.githubusercontent.com/40647814/42141340-88e7cf4c-7de3-11e8-81ae-3e1816249cea.png)
> 
> Thank you in advance.

I changed cfg file as follows and learned it again:
  - use channel = 3 
=>Unrecognizable results
Why channel = 1 => The identification results are quite accurate ?
