### ISSUE TITLE
Accelerate detection on GPU by parallel images upload?

### ISSUE THREAD

**Issue by thehemen** [AlexeyAB/darknet#1118]
Hello. I'm not sure, is it possible physically, but can we upload multiple images in advance before detection, to speed up it, instead of uploading them one-by-one?

**Comment by AlexeyAB** [comment]
Hello, it is implemented for `darknet detector valid` and `darknet detector map`: https://github.com/AlexeyAB/darknet/blob/1e9d1fcedf1a361bcdb384f15b5b14bdb526576d/src/detector.c#L619-L638

But it isn't implemented for  `darknet detector map` so you should implement it by yourself.

**Comment by thehemen** [comment]
You've said:
> Hello, it is implemented for _darknet detector valid_ and _darknet detector map_
> But it isn't implemented for _darknet detector map_
Maybe you mean, that it is not implemented for _darknet detector test_?
I've forgotten to say i want to find the implementation of testing set of images)

**Comment by AlexeyAB** [comment]
Yes, I fixed a typo )

**Comment by thehemen** [comment]
Ok, got it. Thanks )
