### ISSUE TITLE
In the process of running the program will be interrupted when i use the yolo dll to load yolov3-voc.cfg for detect image

### ISSUE THREAD

**Issue by RellyLee** [AlexeyAB/darknet#1119]
Hello sir!

**Comment by RellyLee** [comment]
my code has a breakpoint when it run this sentence:
	std::vector<bbox_t> box_guanjie = de_guanjie.detect(img, 0.4, false);

**Comment by RellyLee** [comment]
@AlexeyAB

**Comment by RellyLee** [comment]
sometimes i use the same yolov3-voc.cfg file in windows cmd it can work. but sometimes it can not work. when i use yolov2-voc.cfg do not have this problem.

**Comment by RellyLee** [comment]
When use the yolo dlll in my code it has a breakpoint when it read some picture
the breakpoint:
	std::vector<bbox_t> box_guanjie=de_guanjie.detect(img, 0.4, false);

**Comment by RellyLee** [comment]
@AlexeyAB

**Comment by AlexeyAB** [comment]
@RellyLee Hi,
I don't understand what is the problem?

**Comment by RellyLee** [comment]
After I commented on this line of code（free_detections(dets, nboxes);）, the problem disappeared, but I don't know if it will have any impact on the program.

**Comment by AlexeyAB** [comment]
@RellyLee In what file did you comment this line?

**Comment by RellyLee** [comment]
In yolo_v2_class.cpp

**Comment by popper0912** [comment]
have you solvered?

**Comment by RellyLee** [comment]
@popper0912 Yes, I've solved it.The cause of the problem is shown in the picture：
![20180726113623](https://user-images.githubusercontent.com/16131563/43240258-28e2eeb8-90c8-11e8-917d-fac5a13fb7c2.png)
I only modified one of the lines，but there are three lines that need to be modified.
