### ISSUE TITLE
Depthwise/Separable Convolution on Darknet

### ISSUE THREAD

**Issue by Sunmyfong** [AlexeyAB/darknet#112]
Hi Alexey,
To speedup the yolo-tiny, I attempt to modify the src to implment the depthwise conv of MobileNets [https://arxiv.org/abs/1704.04861]. But it seems to be difficult for me>_<. Do u have any plan to implement the DepthwiseConv layer?

**Comment by bhkim** [comment]
I am checking the implementation in "https://github.com/hjimce/darknet_mobilenet" where three codes are added: depthwise_convolutional_kernels.cu, depthwise_convolutional_layer.c, and depthwise_convolutional_layer.h. 
I am planning to merge this implementation to AlexeyAB's darknet version. If I would succeed, I will share it as a forked version.
