### ISSUE TITLE
image size rescaling inquiry

### ISSUE THREAD

**Issue by ilayoon** [AlexeyAB/darknet#1120]
I have a fully annotated dataset but I would like to rescale the image size down to fit the network input resolution. I wonder whether are there any easier way than me re-annotating my whole dataset again. Your answer would be helpful.

My picture is around 1920 x1080. And the reason that I would like to rescale image instead of the network resolution is to keep the final grid cell as 13x13.

**Comment by AlexeyAB** [comment]
Any image will be resized to the network resolution (width= height= in cfg) **automatically**. So you shouldn't do it.

Also because annotation is relative, then it doesn't depend on the size of image, and still the same always.

**Comment by git-sohib** [comment]
for example if I have 1920x1080 image dataset and I'll train it with 640x448 (in cfg). Then I changed the resolution of image dataset to 960x540 and I'll train it with same size in cfg (640x448). Is there any use?
