### ISSUE TITLE
Cyrillic letters instead of strings

### ISSUE THREAD

**Issue by xinvestoriginal** [AlexeyAB/darknet#113]
Hi, Alexey, when i buld yolo_console_dll, then app close with message: "Couldn't open file: @aкtx" on Detector constructor, is my code:
```
std::string cfg = "yolo-voc.cfg";
std::string weights = "yolo-voc.weights";
Detector detector(cfg, weights);
```
what is it?

**Comment by AlexeyAB** [comment]
Hi, @xinvestoriginal 

Did you try to run `yolo_console_dll` from MSVS? If yes, then you should put cfg/weights files near with `darknet.vcxproj`-file.

Put files `yolo-voc.cfg`, `yolo-voc.weights` and `voc.data` to the path `build\darknet`.

**Comment by xinvestoriginal** [comment]
Yes, I copied these files, but I think the problem is in data transfer to dll, if I run the project yolo_cpp_dll.sln and put the breakpoint in the constructor YOLODLL_API Detector::Detector(std::string cfg_filename, std::string weight_filename, int gpu_id), I see the cyrillic characters in the header instead of "yolo-voc.cfg" and "yolo-voc.weights"

**Comment by xinvestoriginal** [comment]
- no
- no
- ok, but see also result, can i write rus?

**Comment by xinvestoriginal** [comment]
if i set file names inside constructor, it works, but arise unknown excaptions as [http://skrinshoter.ru/s/290617/WJbnGNKZ?a](url)

**Comment by AlexeyAB** [comment]
Just update your code from the last commit. I fixed it.

----

You use Debug mode for console application (exe), that uses **Debug** Multithreaded Runtime library. But DLL uses release Multithreaded Runtime library.

You should use the same **release** Runtime library both for DLL and EXE.  So you should set in the **yolo-console-dll**:
(right click on project) -> properties  ->  `C/C++ -> Code generation -> Run Time library -> Multi-threaded DLL (/MD)`

**Comment by xinvestoriginal** [comment]
thanks, now it work fine.
