### ISSUE TITLE
How did you calculate BFLOPS ?

### ISSUE THREAD

**Issue by zrobotparking** [AlexeyAB/darknet#1134]
I tried to understand the following code, and tried to convert BFLOPS to MAC count.
(a*b+c will be 1 mac, a,b,c is ft32)
Can you explain the meaning of this line, and how to calculate MAC ?

https://github.com/AlexeyAB/darknet/blob/6d2e31bf2026301a25a3e8dabeae0680c159328b/src/convolutional_layer.c#L401

**Comment by AlexeyAB** [comment]
What is the MAC? Is it FMA (Fused-multiply-add)? https://en.wikipedia.org/wiki/FMA_instruction_set

`l.bflops = (2.0 * l.n * l.size*l.size*l.c * l.out_h*l.out_w) / 1000000000.; `

* l.n - number of convolutional filters
* l.size - size of conv filter (width and height are the same)
* l.c - number of input channels
* l.out_h - height of output feature map
* l.out_w - width of output feature map
* 2.0 - there are 2 operations (Multiply and Add)
* 1000000000 - just for convertation flops to Gflops

If you want to get number of FMA operations, then just don't mutiply by 2.0:
`l.bflops = (l.n * l.size*l.size*l.c * l.out_h*l.out_w) / 1000000000.; `

Or just divide BFLOPS by 2.

**Comment by zrobotparking** [comment]
Thanks a lot~

**Comment by git-sohib** [comment]
what is BFLOPS anyway? How is it important?
