### ISSUE TITLE
cv::VideoCapture cant open any video file

### ISSUE THREAD

**Issue by xinvestoriginal** [AlexeyAB/darknet#114]
how to fix this?

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet/issues/34#issuecomment-283315500

C:\opencv_2.4.9\opencv\build\x64\vc12\bin

> The file opencv_ffmpeg249_64.dll had existed in the vc12 folder, just copy-pasted it near darknet.exe and it worked. it is amazing why I was not getting any .dll absence error.

**Comment by xinvestoriginal** [comment]
ooooeee it work! )

**Comment by xinvestoriginal** [comment]
hmmm, after process print: exception: file not found, but i copy all dll into x64

**Comment by AlexeyAB** [comment]
Try to build in Release. And run .exe file directly from explorer instead of MSVS.

**Comment by xinvestoriginal** [comment]
Yes, I did, but the same exception appears after processing the file.
