### ISSUE TITLE
"darknet.exe stop running" ----A  Headache Problem!!!

### ISSUE THREAD

**Issue by gl60481667** [AlexeyAB/darknet#1143]
Hi,@AlexeyAB
     I've set the darknet platform  as your guide on my (windows 7+ core i7 6500 + AMD Radeon R7 200 Series +16G RAM +VS2015 + OPENCV2.4.13) computer, the compile process is successful, but when I start  "darknet_yolo_v3.cmd", it displayed "darknet.exe stop running", and the win32 console stoped like this :
![jpeg](https://user-images.githubusercontent.com/40851761/42355436-ae83903c-80ff-11e8-89e7-dfc0f9dfcbef.jpg)
 so I debuge this exe file  in VS, it  displayed"0x000000013FC45485 处有未经处理的异常(在 darknet_no_gpu.exe 中): 0xC0000005: 读取位置 0xFFFFFFFFFFFFFFFF 时发生访问冲突。"
![jpeg 2](https://user-images.githubusercontent.com/40851761/42355566-4dc9c6a2-8100-11e8-84ff-bf4655a00e55.jpg)
This is my opencv set information:
![jpeg 3](https://user-images.githubusercontent.com/40851761/42355611-843bf160-8100-11e8-9a32-e4e403136529.jpg)
![jpeg 4](https://user-images.githubusercontent.com/40851761/42355613-849b6c44-8100-11e8-8063-0d07916b1ad8.jpg)
 Could you help me finding out the reason, thanks a lot!!!!

**Comment by AlexeyAB** [comment]
* Do you use the latest version of this repository?

* Can you show content of your `darknet_yolo_v3.cmd` file?

* Did you change any file: yolov3.cfg, coco.data, coco.names?

**Comment by Jped** [comment]
I am having the same problem. After switching over to ms coco, training no longer works for more than a few batches. 
I get this error then, after I chose the option to debug I get this: 
![image](https://user-images.githubusercontent.com/5013466/42416998-443db1a6-824b-11e8-9434-7b1586e5c89b.png)

**Comment by Jped** [comment]
Here are more details on the issue 
![error](https://user-images.githubusercontent.com/5013466/42420462-4eea3518-8294-11e8-9ae8-83a026d3432c.png)

**Comment by AlexeyAB** [comment]
@Jped 

* Show you cammand for training
* Show your files: yolov3.cfg, coco.data, coco.names

**Comment by gl60481667** [comment]
@AlexeyAB
“Do you use the latest version of this repository?

Can you show content of your darknet_yolo_v3.cmd file?

Did you change any file: yolov3.cfg, coco.data, coco.names, ...?“

All the data files were  never  modified.
This problem was not appeared on my  notebook，so I'll reset my PC OS today, hope it can be work!

**Comment by gl60481667** [comment]
@Jped 
During my debuge, the variable  "**objectness**" displayed "NAN", I think it maybe the reason why the "0x0005"flaut happened.

**Comment by gl60481667** [comment]
After resetting my PS OS , the issue is handout!
![1122](https://user-images.githubusercontent.com/40851761/42440070-20b4d712-8397-11e8-94da-389044e459d6.jpg)

**Comment by Jped** [comment]
Yes I followed [this](https://www.reddit.com/r/computervision/comments/7urujr/yolo_suddenly_crashes_during_training/) thread, apparently there were a few images that were missing that caused this error. Once I replaced them it worked.
