### ISSUE TITLE
compile err,src/unistd.h not found

### ISSUE THREAD

**Issue by pageedward** [AlexeyAB/darknet#1144]
compile in ubuntu16 ,how can i fix it?
In file included from ./src/utils.c:4:0:
src/unistd.h:10:16: fatal error: io.h: No such file or directory
compilation terminated.
Makefile:130: recipe for target 'obj/utils.o' failed
make: *** [obj/utils.o] Error 1

**Comment by pageedward** [comment]
i have fix it ,just remove line 12 #include <unistd.h>

**Comment by AlexeyAB** [comment]
Try to do:
```
sudo apt-get install build-essential
sudo ln -s /usr/include/asm-generic /usr/include/asm
```

----

`"unistd.h"` (that contains `<io.h>`) will be included only on Windows.
`<unistd.h>` will be included only on Linux, and file  `<unistd.h>` can't cause an error:
https://github.com/AlexeyAB/darknet/blob/04c0c4fdf84bb7b9e89604e8b9a6079016d5968c/src/utils.c#L8-L14

**Comment by pushkalkatara** [comment]
Deleting the unistd.h file from /darknet/src worked.
