### ISSUE TITLE
What is the meaning of gemm_series?

### ISSUE THREAD

**Issue by zrobotparking** [AlexeyAB/darknet#1146]
What is the meaning of `gemm_nn, gemm_tn, gemm_nt, gemm_tt` ?

**Comment by AlexeyAB** [comment]
What is the GEMM (general matrix multiplication): https://en.wikipedia.org/wiki/Basic_Linear_Algebra_Subprograms#Level_3

What is the NN, TN, NT, TT (N - non-transposed, T - transposed). So `TN` means that 1st matrix is Transposed and 2nd matrix is Non-transposed: https://pdfs.semanticscholar.org/3785/cf27cf56830f798eba8948631347020639be.pdf


> Note this figure corresponds to SGEMM with
> both matrices A and B in non-transpose format (hereafter
> we call this “NN” kernel). If input flags to GEMM is to specify
> transpose matrix A, memory access pattern is different
> as shown in Figure 3 (we call this “TN” kernel).
