### ISSUE TITLE
Peak in GPU consumption

### ISSUE THREAD

**Issue by anavc94** [AlexeyAB/darknet#1148]
Hello again, 

I know there have been a lot of issues about this topic but none of them gave me a working solution.
I've a problem while training YOLOv3 with my own dataset and with VOC dataset. I can start training successfully but after some iterations, the training stops.

I've been checking the GPU and memory consumption while training and it's almost constant (less than 2GB in a 6GB GPU) but when training stops, a peak in  GPU consumption appears. I mean, a CUDA out of memory error.

I am using batch=64, subdivisions=32 and tried to increase subdivisions to 64 but the error still appears. It's a bit strange because as I've said, the training starts successfully and after five min aprox. the peak in GPU consumption appears and training stops.

Thank you so much!

**Comment by AlexeyAB** [comment]
@anavc94 Hi,
Try to use `batch=64 subdivision=64 random=0`

**Comment by anavc94** [comment]
Thanks for the quick reply.

I'm afraid that doesn't work,, same problem.

I've noticed that if i use subdivisions=64 and batch=64 keeping random=1 and use VOC dataset the training seems not to stop, but it does with my data.

**Comment by anavc94** [comment]
I've tried to execute darknet.exe detector map with my data:

darknet.exe detector map data/obj.data yolo-obj.cfg backup/yolo-obj_100.weights

output:

Total BFLOPS 65.312
Loading weights from backup/yolo-obj_100.weights...
 seen 32
Done!
detections_count = 0, unique_truth_count = 0
class_id = 0, name = movistar,   ap = 0.00 %
class_id = 1, name = bmw,        ap = 0.00 %
class_id = 2, name = tissot,     ap = 0.00 %
class_id = 3, name = motul,      ap = 0.00 %
 for thresh = 0.25, precision = -nan(ind), recall = -nan(ind), F1-score = -nan(ind)
 for thresh = 0.25, TP = 0, FP = 0, FN = 0, average IoU = 0.00 %

 mean average precision (mAP) = 0.000000, or 0.00 %
Total Detection Time: 0.000000 Seconds


I don't know what can be wrong with my data, I've check the labels format, the paths of train.txt, I used it for Yolov2 and a lot of things like that. There's no "Couldn't load image" message, just training stops after some iterations when calculating avg loss.

Any help would be appreciated, thank you so much

**Comment by AlexeyAB** [comment]
* Do you use the latest version of this repository?
* Did you check your dataset by using Yolo_mark? https://github.com/AlexeyAB/Yolo_mark
