### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by ycui123** [AlexeyAB/darknet#1149]
I was training using yolov3. And I got out of memory. I'm currently using 1080Ti 11GB and 32GB RAM. If that's not enough, what parameters should I change? Thank you!

**Comment by AlexeyAB** [comment]
if error `Out of memory` occurs then in `.cfg`-file you should increase `subdivisions=16`, 32 or 64: [link](https://github.com/AlexeyAB/darknet/blob/0039fd26786ab5f71d5af725fc18b3f521e7acfd/cfg/yolov3.cfg#L4)

**Comment by ycui123** [comment]
Thank you for the quick reply. Could you tell me what does this parameter do ?

**Comment by ycui123** [comment]
Nevermind, I found an explanation in another post. Thank you !

**Comment by PranjaLBiswas27** [comment]
Hi,

I am using a GTX 1060 6GB, but I got out of memory error after sometime the training started. I already increased subdivision to 32. Also, I am using images with resolution of 512 * 416. How to resolve this issue? Please let me know. Thanks a lot in advance.

Kind Regards
Pranjal Biswas

**Comment by AlexeyAB** [comment]
@PranjaLBiswas27 

>  I got out of memory error after **sometime** the training started

Or use random=0 in your cfg-file.
Or set batch=64 subdivisions=64.

**Comment by PranjaLBiswas27** [comment]
Thanks, using  batch =64 and subdivisions =64 helped with the issue.

**Comment by maliifat** [comment]
I have same error, using batch =64 and subdivisions =64 Or use random=0 in my cfg-file. 

but error occurs.
