### ISSUE TITLE
Couldn't open file：cfg/coco.data

### ISSUE THREAD

**Issue by LuserBen** [AlexeyAB/darknet#115]
Hello,AlexeyAB,
I run .\darknet_no_gpu.exe detect .\cfg\tiny-yolo.cfg tiny-yolo.weights, but it shows Couldn't open file: cfg/coco.data. So how to address this problem.
Thanks

**Comment by LuserBen** [comment]
I have solve this error.
I use absolute path "G:\darknet-master\cfg\coco.data", it worked.

**Comment by AlexeyAB** [comment]
Hi, @LuserBen 

* Yes, you should use: `darknet_no_gpu.exe detector test data/coco.data tiny-yolo.cfg tiny-yolo.weights`
* Or:  `darknet_no_gpu.exe detector test G:\darknet-master\cfg\coco.data tiny-yolo.cfg tiny-yolo.weights`
