### ISSUE TITLE
Question About Training Object

### ISSUE THREAD

**Issue by skipm3** [AlexeyAB/darknet#1151]
Hi. I've passed the installation now i'm going to train my custom object.

What does "integer number of object " mean?
I'm just train one object, so i just should write it 0 for all?

edit: is there any software that makes find out x, y, width, and height easier?  I'm using photoshop now.

**Comment by AlexeyAB** [comment]
> I'm just train one object, so i just should write it 0 for all?

Yes.

> edit: is there any software that makes find out x, y, width, and height easier? I'm using photoshop now.

Use this software to mark objects: https://github.com/AlexeyAB/Yolo_mark



https://github.com/AlexeyAB/darknet#how-to-mark-bounded-boxes-of-objects-and-create-annotation-files

> Here you can find repository with GUI-software for marking bounded boxes of objects and generating annotation files for Yolo v2 & v3: https://github.com/AlexeyAB/Yolo_mark
> 
> With example of: train.txt, obj.names, obj.data, yolo-obj.cfg, air1-6.txt, bird1-4.txt for 2 classes of objects (air, bird) and train_obj.cmd with example how to train this image-set with Yolo v2 & v3

**Comment by Eyshika** [comment]
@AlexeyAB in <x> <y> <width> <height> are <width> and <height> image width and heights ? if yes then how can we normalize it ? it will be 1 isnt it ?

Also just want to confirm if i understood correct <x>= center of rectangle/image width
and <y> center of rectangle /image height

One last question if i am searching for 3 classes then I should have all 3 in one .txt file for that image right ?

**Comment by AlexeyAB** [comment]
@Eyshika 

> One last question if i am searching for 3 classes then I should have all 3 in one .txt file for that image right ?

Yes.

https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

5. You should label each object on images from your dataset. Use this visual GUI-software for marking bounded boxes of objects and generating annotation files for Yolo v2 & v3: https://github.com/AlexeyAB/Yolo_mark

It will create `.txt`-file for each `.jpg`-image-file - in the same directory and with the same name, but with `.txt`-extension, and put to file: object number and object coordinates on this image, for each object in new line: `<object-class> <x> <y> <width> <height>`

  Where: 
  * `<object-class>` - integer object number from `0` to `(classes-1)`
  * `<x> <y> <width> <height>` - float values relative to width and height of image, it can be equal from (0.0 to 1.0]
  * for example: `<x> = <absolute_x> / <image_width>` or `<height> = <absolute_height> / <image_height>`
  * atention: `<x> <y>` - are center of rectangle (are not top-left corner)

  For example for `img1.jpg` you will be created `img1.txt` containing:

  ```
  1 0.716797 0.395833 0.216406 0.147222
  0 0.687109 0.379167 0.255469 0.158333
  1 0.420312 0.395833 0.140625 0.166667
  ```

**Comment by Eyshika** [comment]
@AlexeyAB I read this and I already have my labelled data in json file , not from this gui though, but since I have top left and bottom right cords so i can convert to center point on my own but for confirmation of width and height , it will be 1 right ? because that's image width/image width and image height/image height
if not then what do you mean by absolute height , is it bounding box height ? if yes then that's not constant in all images

**Comment by AlexeyAB** [comment]
@Eyshika Do you mean, what is relative_image_width? Yes, `relative_image_width = image_width / image_width = 1`

**Comment by Eyshika** [comment]
@AlexeyAB Thanx can you please also answer here : https://github.com/AlexeyAB/darknet/issues/279#issuecomment-347002399
