### ISSUE TITLE
anchors for yolov2

### ISSUE THREAD

**Issue by nsantavas** [AlexeyAB/darknet#1157]
Hi 

Are the anchors for yolov3 and yolov2 the same? If not, how could I calculate them for yolo**v2**? 

Thank you

**Comment by ahsan856jalal** [comment]
./darknet  detector calc_anchors cfg/MyDataset.data -num_of_clusters 9 -width 832 -height 832 (for yolo v3)

Also there is a file scripts/gen_anchors which will create anchors for yolov2

**Comment by Alphonses** [comment]
./darknet detector calc_anchors cfg/MyDataset.data -num_of_clusters 9 -width 416 -height 416 (for yolo v3)
