### ISSUE TITLE
no objects were found

### ISSUE THREAD

**Issue by wani2919** [AlexeyAB/darknet#1160]
Hello

I train 18 objects. but, no objects were found.
Please look at the picture, and cfg.

My train info: Yolo v2, Nivida 1080Ti 11G

cfg:
  [net]
  batch=64
  subdivisions=8
  height=576
  width=1024
  channels=3
  momentum=0.9
  decay=0.0005
  angle=0
  saturation = 1.5
  exposure = 1.5
  hue=.1
  
  [convolutional]
  size=1
  stride=1
  pad=1
  filters=115
  activation=linear
  
  [region]
  anchors = 1.08,1.19,  3.42,4.41,  6.63,11.38,  9.42,5.11,  16.62,10.52
  bias_match=1
  classes=18
  coords=4
  num=5
  softmax=1
  jitter=.2
  rescore=1

Picture:
![image](https://user-images.githubusercontent.com/16110709/42444181-62548646-83aa-11e8-8350-d8489ef91f1c.png)

**Comment by fryng** [comment]
you probably forgot  to load the weights `darknet53.conv.74`

**Comment by wani2919** [comment]
I train count 10600, but, no objects were found.

train info:
  yolo v2 and train weights file darknet19_448.conv.23
 GPU, 1080Ti 11G

![image](https://user-images.githubusercontent.com/16110709/42483111-8c07ac62-8426-11e8-9cdf-9fbba5917df9.png)

**Comment by wani2919** [comment]
re-traing yolo v2 and train weights file darknet53.conv.74

**Comment by wani2919** [comment]
Thank you!
Recognized after weights file change(daeknet53.conv.74),
