### ISSUE TITLE
darknet.sln loading failed in MSVS after changing CUDA version

### ISSUE THREAD

**Issue by LuserBen** [AlexeyAB/darknet#117]
Hi, AlexeyAB
I met another problem. CUDA 8.0 runtime version can't match my CUDA driver version, so I installed CUDA 5.0 and changed  _build\darknet\darknet.vcxproj_  by using Notepad. However when I openned build\darknet\darknet.sln  by VS2015, it showed darknet loading failed. If no changing ,it's OK.
So did I miss something important.

**Comment by AlexeyAB** [comment]
Hi, Do you really use very old CUDA Toolkit 5.0 (Oct 2012)? https://developer.nvidia.com/cuda-toolkit-archive

Or maybe you meant CC 5.0 (Compute capability 5.0)? https://en.wikipedia.org/wiki/CUDA#GPUs_supported

If you can open `darknet.sln` successfully by VS2015 then you use CUDA 8.0.

**Comment by LuserBen** [comment]
Haha, I really use very old CUDA Toolkit 5.0. When I installed CUDA Toolkit 7.0 and 8.0, it showed _

The graphics driver could not find compatible graphics hardware. You may continue installation, but you will not be able to run CUDA application.

_So I tried CUDA Toolkit 5.0.
I insatlled CUDA Toolkit 8.0 and runned darknet.exe, it showed _CUDA  Error：CUDA driver version is insufficient for CUDA runtime version._
The main reason is my gpu is very old, Geforce 405.

**Comment by AlexeyAB** [comment]
>  If no changing ,it's OK.

Try to open unchanged `darknet.sln` by MSVS2015 and then:

 (right click on project) -> Build dependecies -> Build customization files -> set checkbox - CUDA 5.0

![18633_original](https://user-images.githubusercontent.com/4096485/27799910-c373e372-601f-11e7-9cb1-b26b18719aeb.png)

**Comment by LuserBen** [comment]
@AlexeyAB Thanks for your help.
 I have to give up using gpu. My computer is so old that it can not do something lastest.
Thanks very much.

**Comment by Anhaoxu** [comment]
@AlexeyAB @LuserBen   hello, I met a similar problem, I use VS2015, but I only can compile no gpu projects, so I guess there is something wrong with cuda, I use cuda8.0, then I change the cuda path of darknet.vcxproj. However it didn't work, the error is : darknet.sln loading failed, one or many error occurred.

**Comment by LuserBen** [comment]
可能是GPU不行，我后来换了台新电脑，在ububtu上GPU版本跑起来没问题

**Comment by Anhaoxu** [comment]
Thanks, so strange, only darknet.sln can't open, the 3 else projects are very well for me, so I think it's some problem with cuda, but I can use cuda in other projects, maybe I can test it on another machine.

**Comment by AlexeyAB** [comment]
@Anhaoxu 

* Try to do in MSVS open `\darknet.sln` -> (right click on project) -> properties -> C/C++ -> Preprocessor -> Preprocessor Definitions, and remove this: `CUDNN;`

* Can you show screenshot from? (right click on project) -> Build dependecies -> Build customization files -> set checkbox - CUDA 8.0

**Comment by Anhaoxu** [comment]
@AlexeyAB  hello, Loading failed, and it showed me no properties of **darknet.sln**, so you mentioned above I can't do it.

**Comment by AlexeyAB** [comment]
@Anhaoxu Try to re install CUDA 9.1

Or try to do: https://github.com/AlexeyAB/darknet#how-to-compile-on-windows

> If you have other version of CUDA (not 9.1) then open build\darknet\darknet.vcxproj by using Notepad, find 2 places with "CUDA 9.1" and change it to your CUDA-version, then do step 1
