### ISSUE TITLE
 Cannot load image " ■C" Couldn't open file:  ■C

### ISSUE THREAD

**Issue by iMeteox** [AlexeyAB/darknet#1186]
I'm having problems with the training. I follow along the steps, but when I run the command "./darknet.exe detector train data/voc.data yolo-voc.cfg darknet53.conv.74" (These are the correct paths in my case), I get this: 

![image](https://user-images.githubusercontent.com/33431710/42583691-84053a32-84ff-11e8-9263-0a482dc6f0ef.png)

I've inspected the text files that contain the labels to the pictures, and I cannot find a typo or anything that could result in that output. I tried using the VOCdevkit from yolo-v2-for-windows, and I've tried with the version on https://pjreddie.com/darknet/yolo/#train-voc, and both give me the exact same result.

Any idea what or where could be the problem?

**Comment by AlexeyAB** [comment]
Do you use Linux?
Did you transfer `train.txt` that will be created on Windows?


Try to install dos2unix on Linux
```
sudo yum install dos2unix
# or
sudo apt-get install dos2unix
```

and then do
```
dos2unix ./train.txt
```

**Comment by iMeteox** [comment]
My bad for not specifying, I'm trying to run it on Windows, and I've built the solution using Visual Studio. I branched from "https://github.com/unsky/yolo-for-windows-v2", but I'm pretty sure darknet is the source of the issue. 

I'm trying to understand why it's trying to get a file from " ■C" instead of the paths specified in the test/train files that I've all copied to train.txt, or how it even manages to end up with " ■C" as a result. Other than that, everything looks neat and clean for now.

**Comment by AlexeyAB** [comment]
@iMeteox Try to use this repository on Windows, will it have this issue?

**Comment by iMeteox** [comment]
Sorry for such a late reply.

I've tried building this solution, but on MSVS2017, I get the error "-- unsupported Miscrosoft Visual Studio version! Only the versions 2012, 2013, 205 and 2017 are supported!". 
And on MSVS2015, I get the error "The build tools for v141 (Platform Toolset = 'v141') cannot be found.

I'll be working to fix the MSVS2017 error, since I finally managed to get the v141 tools after updating everything. I have no clue what is causing it.

**Comment by iMeteox** [comment]
Alright, I've got everything fixed using this repository. The error was coming from CUDA, and I found a fix here : https://devtalk.nvidia.com/default/topic/1022648/cuda-setup-and-installation/cuda-9-unsupported-visual-studio-version-error/
