### ISSUE TITLE
huge bounding box error at the crowded scene.

### ISSUE THREAD

**Issue by noirmist** [AlexeyAB/darknet#1189]
Hi all, 
I'm currently testing yolo v3 for detecting people.

I'm using this command to test pretrained weights
$./darknet detector valid cfg/coco.data cfg/yolov3.cfg yolov3.weights

From the output results, I draw bounding boxes and found weird huge boxes at the crowded scene.
Is there anyone has this issue? 
If you solve it, please share the solution with me.
Thank you!

Here are some examples. (the images come from coco datasets.)
![screen shot 2018-07-10 at 4 45 06 pm](https://user-images.githubusercontent.com/8666069/42614110-5e9e9866-85df-11e8-9f32-42b24ff2f9bd.png)
![screen shot 2018-07-10 at 12 48 15 pm](https://user-images.githubusercontent.com/8666069/42614132-6bb678d4-85df-11e8-96db-0b2fbb1669bb.png)
![screen shot 2018-07-10 at 12 35 12 pm](https://user-images.githubusercontent.com/8666069/42614141-72045260-85df-11e8-8f73-c5e0b0873eec.png)
![screen shot 2018-07-10 at 12 30 39 pm](https://user-images.githubusercontent.com/8666069/42614153-79d9f7ce-85df-11e8-8209-e669db549a4a.png)

**Comment by Pattorio** [comment]
Did you use class person from coco datasets for training? If so, I think it's normal since coco do have these kind of huge boxes.

**Comment by noirmist** [comment]
@Pattorio Yes. I'm using pre-trained weights by coco dataset. Thank you. I didn't know that.
