### ISSUE TITLE
Problem with Apple Apple HLS reading and OpenCV

### ISSUE THREAD

**Issue by luiscosio** [AlexeyAB/darknet#119]
Hello!

I'm trying to read Apple HSL stream within Darknet, but I keep getting this error:

![image](https://user-images.githubusercontent.com/1666/27842883-9c0508fc-60d3-11e7-8df4-e0f2fc81c9ff.png)

This is the command I'm using:
![image](https://user-images.githubusercontent.com/1666/27842901-ca41fc0c-60d3-11e7-85b0-16544eabee48.png)

No problems with .mp4 files or other video files, and when I try to run the same command on a Ubuntu box, it works just fine.

Did a clean install under Windows Server 2012 R2, following your instructions.

Regards,

**Comment by AlexeyAB** [comment]
@luiscosio Hi,
If you can process Apple HSL stream by using Darknet Yolo on Linux, but can't on Windows, then Windows-version of OpenCV-dll `opencv_ffmpeg249_64.dll` doesn't support HLS-stream.

Do you use the same version of OpenCV both on Linux and Windows?

**Comment by luiscosio** [comment]
@AlexeyAB No, it is not the same version. I'm going to try recompiling with the latest version of OpenCV. 

Just wondering, is there any specific reason why you are suggesting using OpenCV 2.4.9 instead of 3.2.0?

**Comment by AlexeyAB** [comment]
@luiscosio Darknet doesn't work with OpenCV 3.x without fixes like these: https://github.com/pjreddie/darknet/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20opencv3%20

Also try to write your own simple C++ OpenCV application, can it read and show Apple HSL stream?

```cpp
int main() {
 cv::Mat frame;
 cv::VideoCapture cap;
 cap.open("https://...url to hls stream...");
 while(true) {
  cap >> frame;
  cv::imshow("window name", frame);
  cv::waitKey(10);
  }
 return 0;
}
```
