### ISSUE TITLE
My computer memory is 32G,when training,out of memory

### ISSUE THREAD

**Issue by wytcsuch** [AlexeyAB/darknet#1190]
Hello everyone,my computer memory is 32G,there is still a lack of memory when batch is 64 and subdivisions is 8.I open the task manager,it shows that only 32％ memory is used.what's wrong?

**Comment by door5719** [comment]
How about your GPU? If your GPU is 1080ti,you can set  batch = 16 .That woud be better.

**Comment by ycui123** [comment]
> Note: if error Out of memory occurs then in .cfg-file you should increase subdivisions=16, 32 or 64: link

**Comment by TheMikeyR** [comment]
I assume you have 32 gigabyte of RAM, how much RAM you have doesn't matter, it is the memory available on your GPU which matter. So you should check status of your GPU, if you are running linux you can use `nvidia-smi` to show stats about your GPU.
