### ISSUE TITLE
Unable to detect anything using customized training for single class object detection.

### ISSUE THREAD

**Issue by JohnWnx** [AlexeyAB/darknet#1199]
I have been following this tutorial to customize object detection to a single class only for yolo.
https://timebutt.github.io/static/how-to-train-yolov2-to-detect-custom-objects/

Following the method, I have created 3 files: 
1. obj.data (Set classes = 1, train, valid , names and backup bath) 
2. yolo-obj.cfg (copied directly from yolov3.cfg edited the number of classes and the filter number before each yolo layer.) Batch size set to 64, subdivision 32.
3. obj.names (NFPA is the name)

However, I am unable to detect anything with the trained weights.

Here is my training output:

Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000513, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.721301, Class: 0.764853, Obj: 0.012279, No Obj: 0.003255, .5R: 1.000000, .75R: 0.000000,  count: 1
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.001174, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: 0.231108, Class: 0.363481, Obj: 0.001690, No Obj: 0.000549, .5R: 0.000000, .75R: 0.000000,  count: 2
Region 82 Avg IOU: 0.440125, Class: 0.728664, Obj: 0.024457, No Obj: 0.003694, .5R: 0.500000, .75R: 0.000000,  count: 2
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.001216, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000535, .5R: -nan, .75R: -nan,  count: 0
371: 2.653604, 3.078943 avg, 0.000019 rate, 12.796011 seconds, 23744 images
Loaded: 0.000032 seconds

=========
1. Is there something wrong with my "Class" value? i.e. Class: 0.728664
Since I only have 1 class, does that mean the "Class" value should be either 1 or 0?
2. Why am I getting -nan for the output, is this normal?
3. Do I need at least batch size = 64 for detection? (I'm using a 6gb GTX1060 gpu, so having 64/8 or 64/16 will cause CUDA to run out of memory). Currently training with batch size 64, subdivision 32, which takes very long time.
4. Do I need to revert to batch size =1 and sub division =1 when detecting (after training)?

Thanks.

**Comment by Eyshika** [comment]
@JohnWnx Di you figure it out ? Am also getting same problem. Not able to detect anything.
@AlexeyAB can you please reply on this ?

**Comment by AlexeyAB** [comment]
@JohnWnx @Eyshika 
Training goes well, just train more than 4000 iterations.

**Comment by JohnWnx** [comment]
![lossgraph](https://user-images.githubusercontent.com/40804580/43907710-af92187e-9c28-11e8-9e06-926b84744984.JPG) **did not managed to record the loss graph in the missing sections.

@Eyshika Yes, issues resolved after training for more iterations.
Training takes about 4 minutes per 100 weights on single class training using GTX1060, 6GB.
Loss starts around 300-500 at the start. It will decrease quickly as seen in the loss graph (screenshot above).

I've got the best results @ 88100 iterations, with loss  around 0.54. The loss fluctuates between 1.2 to 0.5. I've stopped the training at around 130,000 iterations as not much further improvement can be seen. 

@AlexeyAB is there a method to resume plotting the loss graph every time I pause the training and resume afterwards? Currently, I have to take a screenshot every time when I want to pause the training. At the end, I will need to reconstruct all the graphs from the separate screenshots.

**Comment by AlexeyAB** [comment]
@JohnWnx 

> is there a method to resume plotting the loss graph every time I pause the training and resume afterwards? 

No.

May be later I will add automatically mAp calculation during training for each 1000 - 5 000 iterations, so you will not need to stop/resume training to check mAP.
