### ISSUE TITLE
Weights didn't save after 100 iterations.

### ISSUE THREAD

**Issue by pushkalkatara** [AlexeyAB/darknet#1202]
No weights saved in the backup directory. Training custom classes on Google Cloud, Ubuntu 16.04 with Tesla K80. 
Directory description - 
```
/darknet/cfg/yolo-obj.cfg
/darknet/darknet53.conv.74
/darknet/data/train.txt 
/darknet/data/obj.names
/darknet/data/obj.data
/darknet/backup/ - Empty
```

**Comment by ahsan856jalal** [comment]
Suppose if you have backup=my_model in your .data file , then you should
make a folder 'my_model' in darknet main directory. Then start training
Regards
Ahsan

**Comment by pushkalkatara** [comment]
@ahsan856jalal Thanks for the reply. I already have a backup folder.
My data file -
```
classes= 5
train  = data/train.txt
valid  = data/test.txt
names = data/obj.names
backup = backup/
```
And there's already a folder in /darknet named as backup. But still weights are not saved.

**Comment by ahsan856jalal** [comment]
can you try just backup instead of backup/

Otherwise in detector.c, search if(i%1000==0 || (i < 1000 && i%100 == 0)){
and replace 1000 with 100 , remake and retry
Regards
Ahsan

**Comment by pushkalkatara** [comment]
![gcs](https://user-images.githubusercontent.com/21266230/42704001-e3e513a8-86eb-11e8-98f3-ef6b24055f79.png)

**Comment by gustavovaliati** [comment]
Hi @pushkalkatara ,

Are the permissions to the backup folder OK? Can you create files in it?
Try to create a file with the same user you run the darknet app.
`touch backup/test`

**Comment by pushkalkatara** [comment]
@gustavovaliati Oh. Must be this issue. thanks for pointing out. I'll try this superfast and revert back.
