### ISSUE TITLE
receptive field for YOLO V3

### ISSUE THREAD

**Issue by YL-123** [AlexeyAB/darknet#1206]
Hi, @AlexeyAB
Thanks for sharing calculating the receptive field[ post](https://github.com/AlexeyAB/darknet/issues/179), I calculated the YOLO V3 network and found the receptive field of a single activation of the last layer, pixels is only 103*103, much smaller than the YOLOV2 and even smaller than the tiny YOLO V2.
![image](https://user-images.githubusercontent.com/26073213/42713485-7d841a24-86a4-11e8-83cf-9cce72e791b6.png)
![image](https://user-images.githubusercontent.com/26073213/42713467-6e288452-86a4-11e8-9456-f21ef0e7f9c9.png)

Is there something wrong with my calculation?
The reason why I ask is I found my trained YOLO V3 did a good job of detecting the small objects, but for larger ones, many bounding boxes could be stacked on a single larger object, which brings more false positives.

**Comment by wait1988** [comment]
@AlexeyAB So when stride =2 ,filter =3 in conv layer,what operation should it be?

**Comment by AlexeyAB** [comment]
@wait1988 @Yinling-123 

> So when `stride =2 ,filter =3` in conv layer,what operation should it be?

`* 2 + 1`


So, if receptive field was 10x10, then after `stride =2 ,filter =3` will be 21x21.

**Comment by wait1988** [comment]
@AlexeyAB Thx so much.
