### ISSUE TITLE
hyper parameters tuning for darknet

### ISSUE THREAD

**Issue by YL-123** [AlexeyAB/darknet#1208]
Considering so many hyper parameters could be optimized in one YOLO V3 cfg file, I am wondering if there any hyper parameters tuning system (black box optimization) like Bayesian Optimization implementation for darknet,  or anyone has hints how to do it? thanks

**Comment by EyGy** [comment]
Hi @lynnw123,
since you closed that issue I was wondering if you made any progress / found a practicable solution for param tuning.
Any useful tipps are appreciated!
Thanks :)
