### ISSUE TITLE
Should I mark all object in the train image?

### ISSUE THREAD

**Issue by matakk** [AlexeyAB/darknet#121]
Thanks!
I use darknet to detect cars on road  , My train image is grab from the traffic camera,and I mark the car object in the image , But , There are many cars in my image ,and the car is overlap with other cars ,Should I mark all cars in my object ?
also there are some very small cars in the far away on the road . I have ignore those small object , 
Sorry my english expression.

**Comment by AlexeyAB** [comment]
Hi, @matakk 
* If you want to detect small cars - then you should mark small cars.
    (But if the car has a size smaller than width = (16 * image_width/network_width) pixels, then it is better not to mark such cars)

* If you see more than 0.24 (i.e. 24%) of overlaped car, then you should mark this car
    (Here 0.24 is equal to default threshold)

**Comment by matakk** [comment]
Thank you very much!
1. my camera's resolution is 1080p, and the small car is 48*48,  I should crop the big 1080p image to like 1080*1080?

2: what 0.24 (%24) meaning ?   default threshold  is meaing use darknet.exe default threshold ?

**Comment by AlexeyAB** [comment]
1. If car has size 48 x 48, and you use 1920 x 1080 image on 416 x 416 network size: https://github.com/AlexeyAB/darknet/blob/master/cfg/yolo.2.0.cfg#L4
    then object smaller than 73 x 41 - it will be difficult to detect and it makes little sense to mark their

2.  For example:

* If you use `darknet.exe detector test data/coco.data yolo.cfg yolo.weights -thresh 0.2` then **threshold =0.2**

* If you use `darknet.exe detector test data/coco.data yolo.cfg yolo.weights` then **threshold =0.24** by default

**Comment by matakk** [comment]
👍 thank you!
