### ISSUE TITLE
Removing opencv dependency

### ISSUE THREAD

**Issue by dexception** [AlexeyAB/darknet#1213]
I was going through the opencv code and it seems to be allocating unnecessary resources. Even the number of threads being created to play videos is not necessary as other libraries are better at handling such activity. I know it's a lot of effort but the next step should in this direction.

**Comment by vinjn** [comment]
opencv is already am optional lib :)

**Comment by AlexeyAB** [comment]
To remove OpenCV dependcies:

* On Linux: just use `OPENCV=0` in the Makefile.

* Or on Windows: in MSVS open `\darknet.sln` -> (right click on project) -> properties -> C/C++ -> Preprocessor -> Preprocessor Definitions, and remove here: `OPENCV;`

Or do you mean to replace OpenCV by other lib?

**Comment by dexception** [comment]
@AlexeyAB 
I am talking about replacing opencv with inbuilt code for showing images and playing videos.

**Comment by vinjn** [comment]
`showing images and playing videos` is not a trivial work, especially if you want to go cross-platform.

**Comment by dexception** [comment]
Yes...
