### ISSUE TITLE
Open sourcing a visualization tool - feature-viz

### ISSUE THREAD

**Issue by vinjn** [AlexeyAB/darknet#1215]
https://github.com/jing-vision/lightnet/tree/master/feature-viz

Supports most all the darknet layer type, it now visualize filter values and activation values.
Supports reading from camera, picture and video file.
Has minim dependency, darknet + opencv is enough.

![image](https://user-images.githubusercontent.com/558657/42735729-e3d8b97c-888b-11e8-85c0-fb0cfcbb72c3.png)

**Comment by fabioac** [comment]
Thank you vinjn

**Comment by lvshuaigg** [comment]
@vinjn How can I use this visualization tool?

**Comment by vinjn** [comment]
It's open-sourced, sync the code and build it :)

**Comment by lvshuaigg** [comment]
@vinjn 
Thank you very much, how to configure it, I saw the link, but did not find how to configure feature-viz.

**Comment by lvshuaigg** [comment]
@vinjn 
How can I generate feature-viz.exe, I have not succeeded for a long time.Thank you very much.

**Comment by vinjn** [comment]
1. Execute `build.bat`, making sure there is no error.
2. Download premake from https://premake.github.io/download.html
3. enter `feature-viz' folder, execute `premake5 vs2015`
4. open `feature-viz\vs2015\feature-viz.sln` and build
5. Read `feature-viz\README.md` for more samples

**Comment by lvshuaigg** [comment]
@vinjn 
Hello, I am very sorry, my computer was originally installed when the opencv3.2 version, but when I build feature-viz.sln, it could not be opened including the file opencv2/dnn.hpp:No such file or directory. I found a lot No data can solve this problem.

**Comment by lvshuaigg** [comment]
@vinjn Hello, the above problem is solved, I downloaded an opencv3.4, but there is a new problem, can not open the input file: yolo_cpp_dll.lib, do not know how to solve.

**Comment by lvshuaigg** [comment]
Hello, I downloaded a yolo_cpp_dll.dll online, and then the error is gone, but there are many errors.
![image](https://user-images.githubusercontent.com/37791922/44086183-581ec2ee-9fee-11e8-8683-89561ad6c2b6.png)

**Comment by vinjn** [comment]
No, you should & must build `yolo_cpp_dll.dll` yourself.
You need to run `build.bat` at the root folder and make sure there is no error.

**Comment by lvshuaigg** [comment]
@vinjn Hello, I am finally done, and it is also very good work, that is, the interface is not very complete, I want to see the right and below can not see, and there is no way to pull.

**Comment by vinjn** [comment]
@lvshuaigg can you have more details about the problem? A screenshot will be very helpful.

**Comment by lvshuaigg** [comment]
@vinjn For example, this picture, he is running very well now, but I want to see some feature maps on the far right, but I can't move. When I move around in full screen, I can't move.
![qq 20180820141305](https://user-images.githubusercontent.com/37791922/44323246-9c045200-a483-11e8-802c-e20dfd2bcc85.png)

**Comment by vinjn** [comment]
Should be a bug, what network do you use? Is it yolo v2?

**Comment by lvshuaigg** [comment]
@vinjn This is yolov3-tiny, that is, you can't see the rightmost and bottommost images, you can only see the size of the image displayed.

**Comment by vinjn** [comment]
@lvshuaigg I've added a fix, can you try again?

**Comment by lvshuaigg** [comment]
@vinjn Thank you very much, it works very well, and now I can see all of it, but it is a bit small.

**Comment by vinjn** [comment]
It's an open source project, feel free to contribute your ideas to it.
