### ISSUE TITLE
What kind of hardware can run this code well？

### ISSUE THREAD

**Issue by LuserBen** [AlexeyAB/darknet#122]
Hi, AlexeyAB. 
Can you tell me some information about your hardware, such as win OS, CPU, RAM, GPU RAM and so on. I don't know whether a general computer or notebook can run this code well. And how long does it take to process an image?
Thanks.

**Comment by AlexeyAB** [comment]
Hi, @LuserBen 

* Windows 7 x86_64
* Intel Core i7-6700K: http://ark.intel.com/products/88195/Intel-Core-i7-6700K-Processor-8M-Cache-up-to-4_20-GHz
* 32 GB RAM
* nVidia GeForce GTX 970 - 4 GB RAM - 1664 Cores - 3.5 TFlops-SP: https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units#GeForce_900_series

This GPU get about 35-40 FPS on video.

I have many computers. And yes, notebook with a **discrete nVidia graphics card** with GPU-RAM more or equal 2 GB can run this code well, but preferably 4 GB or more: https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units

**Comment by LuserBen** [comment]
@AlexeyAB Ok, thanks for your replay. I get it.
