### ISSUE TITLE
Memory leak in the detector map command

### ISSUE THREAD

**Issue by Dragule** [AlexeyAB/darknet#1233]
Hello,

I am currently trying to get some stats about my YOLO training, using the map command of this fork.
So it basically parse each file of the validation set, and try to predict boxes in it.

The thing is either the image or the labels file is not correctly closed, causing a memory leak.
I had to increase the maximum number of files that can be open simultaneously by a single user, and it temporary fixed the problem, at least for Tiny YOLO.
But when trying to validate with a large resolution YOLOv2, my computer lacks the memory to go though the whole validation process, and end up getting killed (despite his 16Go RAM).

I had a look to the source code, [here](https://github.com/AlexeyAB/darknet/blob/master/src/data.c#L171) and [here](https://github.com/AlexeyAB/darknet/blob/master/src/image.c#L985), but both the files seem to be closed properly.
But I'm pretty sure they are not, and looking for help because I don't know where does the leak come from.

Any clue ?

**Comment by AlexeyAB** [comment]
Hi,

> large resolution YOLOv2,

* What resolution did you use?
* Do you use the latest code from this repository?
* Did you change anything in the source code?
* Do you meet same problem when you do `detector valid` or `detector recall` or `detector train` on the same dataset?
* How many images are in your dataset that you uses for mAP-calculation?
* Did you get your dataset by using Yolo_mark? https://github.com/AlexeyAB/Yolo_mark

**Comment by Dragule** [comment]
The resolution is 1024*1024

I cloned the repo 2 month ago, so it's not the latest version but it's close to be. The thing is I modified some part of the code to make it fit my needs so I don't want to erase that by updating the repo :/
Will do if it's necessary though.

There is no problem while using `detector train`, I'm currently trying with recall.

There are around 5930 images in my dataset. The process gets killed near the end, or maybe when it reaches the end.

I didn't use Yolo_mark, I use frames from some videos that I annotated myself. But the boxes are good for training so I guess they should be ok for validating too.

**Comment by Dragule** [comment]
Looks like I fixed it : The mistake was mine, as I was trying to test the weights with a wrong cfg file.
I think there were too many detections, because darknet was going crazy, and it caused the memory overflow.

Anyway, there still is a problem when closing the files, because I had to increase the maximum number of files in linux settings. It was set to 1024 by default, so the validation stopped when reaching ~1000 images. So either the images or the labels are not closed properly.
I increased that limit to 65536 and it's now working, but I guess the code is broken in some way.

I will try tomorrow with the fork updated.
I will tell you the results :)

**Comment by Dragule** [comment]
It seems to be working because it went past 2400 files, but it's really really slow (2464 files over the night), so there's still something off.
Well I guess my initial problem is solved though. I guess it was fixed in a later version, and the files are now closed properly.
