### ISSUE TITLE
How to use python to get the results of the classification？

### ISSUE THREAD

**Issue by githublyp0606** [AlexeyAB/darknet#1236]
Thank you for watching my problem.I am sorry for my poor english.
I have trained the cfg/cifar_small.cfg in my own data. The prediction result seems very well.It shows blow:
![1](https://user-images.githubusercontent.com/11245643/42875905-623d5758-8ac8-11e8-969f-a7c3f5e24b5c.jpg)
But when i code like this it just doesn't work. I added this in the bottom of darknet.py.
```
if __name__ == "__main__":
    net = load_net(b"./rechar.cfg", b"./backup/small/rechar_200500.weights",0)
    im = load_image(b"./1.jpg",0,0)
    meta = load_meta(b"./rechar.data")
    r = classify(net, meta, im)
    print (r[:10])    
````
I tested in jupyter notebook. It looks like the "meta.names" is the problem. Because when i try to get the "meta.names[0]" , the Browser crashed.
This is my "rechar.data":
```
classes = 72
train = /home/ivan/cs/plate_recognize/rec/plates_recognition/data/train.list
labels = /home/ivan/cs/plate_recognize/rec/plates_recognition/data/labels/labels.txt
backup = /home/ivan/cs/plate_recognize/rec/plates_recognition/data/backup
top = 2
```
This is my labels.txt:
`
NumZero
NumOne
NumTwo
NumThree
NumFour
NumFive
NumSix
NumSeven
NumEight
NumNine
AlphaA
AlphaB
AlphaC
AlphaD
AlphaE
ALphaF
AlphaG
AlphaH
AlphaJ
AlphaK
AlphaL
AlphaM
AlphaN
AlphaP
AlphaQ
AlphaR
AlphaS
AlphaT
AlphaU
AlphaV
AlphaW
AlphaX
AlphaY
AlphaZ
HanZiAo
HanZiZang
HanZiChuan
HanZiE
HanZiGan1
HanZiGan2
HanZiGang
HanZiGua
HanZiGui1
HanZiGui2
HanZiHei
HanZiHu
HanZiJi1
HanZiJi2
HanZiJin1
HanZiJin2
HanZiJing1
HanZiJing2
HanZiLiao
HanZiLing
HanZiLu
HanZiMeng
HanZiMing
HanZiNing
HanZiQing
HanZiQiong
HanZiShan
HanZiShi
HanZiSu
HanZiWan
HanZiXiang
HanZiXin
HanZiXue
HanZiYu1
HanZiYu2
HanZiYue
HanZiYun
HanZiZhe
`
Maybe i should create a file with suffix “.names“ and add it to the "rechar.data". I tried this doesn't work.
I just want to get the classifier results.
Doed anyone can help me? This problem has plagued me for a long time.

**Comment by n5ken** [comment]
There is a problem reading meta from C interface, so my workaround is to read meta by `configparser`, for example:

```python
import configparser

config = configparser.RawConfigParser()
config.read(metaPath)

self.altNames = []

with open(config['name']['names'], 'r') as file:
    self.altNames = file.read().splitlines()
```

**Comment by n5ken** [comment]
我看你是在做车牌识别吧？

**Comment by githublyp0606** [comment]
@n5ken thnak you~对的，参加了一个学校的小比赛，我等会试试行不行 (*´∀`)~♥

**Comment by githublyp0606** [comment]
@n5ken I solved this problem by another way. But i notice that i changed the image ,the output of the classify is always the same. Even i don't write the right path of the image, the code `im = load_image("xxxx")` don't get any error. And the output of calssify is the same too.Why does this happend?

**Comment by n5ken** [comment]
You can try “from darknet import Darknet” instead of “from darknet.darknet import Darknet”
