### ISSUE TITLE
YOLO using Python

### ISSUE THREAD

**Issue by skipm3** [AlexeyAB/darknet#1247]
Is [this](https://github.com/pjreddie/darknet/blob/56be49aa4854b81b855f6a9daffce4b4ad1fbb9e/examples/detector.py) applicable to this repo? How? 

Thank you.

**Comment by ahsan856jalal** [comment]
yes, check the scripts folder
Regards
Ahsan

**Comment by skipm3** [comment]
@ahsan856jalal yes but it needs [libdarknet.so](https://github.com/pjreddie/darknet/blob/56be49aa4854b81b855f6a9daffce4b4ad1fbb9e/python/darknet.py#L39) and i'm using windows. any suggestion?

**Comment by skipm3** [comment]
Uh. Found [this issue](https://github.com/AlexeyAB/darknet/issues/955). I will close the issue for a moment.

**Comment by skipm3** [comment]
I'd like to reopen.
I tried to build yolo_cpp_dll and success.
Then, i tried to use this command
`python darknet.py`

and got this error
`Traceback (most recent call last):                                                                                        File "darknet.py", line 110, in <module>                                                                                  lib = CDLL(winGPUdll, RTLD_GLOBAL)                                                                                    File "C:\Python27\lib\ctypes\__init__.py", line 366, in __init__                                                          self._handle = _dlopen(self._name, mode)                                                                            WindowsError: [Error 193] %1 is not a valid Win32 application `

what's wrong? thank you.
@ahsan856jalal @AlexeyAB

**Comment by AlexeyAB** [comment]
@skipm3 

Did you run exactly this darknet.py?  https://github.com/AlexeyAB/darknet/blob/master/build/darknet/x64/darknet.py
Exactly in this folder `/build/darknet/x64/`

**Comment by phamngocquy** [comment]
The python wrapper   have speed decrease?

**Comment by skipm3** [comment]
@EhsanVahab no prob haha. i'm currently using other machine for compare the performance.
But, "copy into your project". I'm running darknet.py in build/darknet/x64, so where should i copy the dlls?

**Comment by EhsanVahab** [comment]
they're in the same directory you found darknet.py.
after building darknet they will be appeared .
