### ISSUE TITLE
YOLO for car counting

### ISSUE THREAD

**Issue by skipm3** [AlexeyAB/darknet#1249]
Hi. I recently found an [youtube video](https://www.youtube.com/watch?v=W7IcPkAzQFU). Is it possible to make something like this with this repo? Any reference?

**Comment by AlexeyAB** [comment]
@skipm3 Hi,
You can try to build Darknet with `LIBSO=1` in the `Makefile`
And then run: 
`LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./uselib data/coco.names cfg/yolov3.cfg yolov3.weights test.mp4`

**Comment by skipm3** [comment]
@AlexeyAB what is that for? I'm using windows btw.

**Comment by dexception** [comment]
@skipm3 
Look for detection based tracking in OpenCV.
