### ISSUE TITLE
Why are there two calls for delta_yolo_box() in forward_yolo_layer()?

### ISSUE THREAD

**Issue by eyalzubia** [AlexeyAB/darknet#1253]
First, thanks very much for this repository!

1. The first call to delta_yolo_box in forward_yolo_layer function is the straightforward one (near line 230). But I can't understand why there's a second call, updating l.delta, near line 261, iterating over mask_n. Could you explain?

2. Also, I don't understand where is the confidence loss - I see only class delta and box delta updates.

Thanks!

**Comment by AlexeyAB** [comment]
1. 
* 1st is for any predictions which have `IoU > truth_thresh`, i.e. delta_yolo_box can be calculated for several final cells/anchors (but in current models `truth_thresh=1` so this part of code is disabled)
 https://github.com/AlexeyAB/darknet/blob/6682f0b98984e2b92049e985b21ed81b76666565/src/yolo_layer.c#L222-L231

* 2nd is for best `prediction` only, so delta_yolo_box will be calculated for the best final cell/anchor only: https://github.com/AlexeyAB/darknet/blob/6682f0b98984e2b92049e985b21ed81b76666565/src/yolo_layer.c#L259-L261

----

2. `confidence (probability) = objectness * class_probability`

* objectness:
    * https://github.com/AlexeyAB/darknet/blob/6682f0b98984e2b92049e985b21ed81b76666565/src/yolo_layer.c#L216-L223
    * https://github.com/AlexeyAB/darknet/blob/6682f0b98984e2b92049e985b21ed81b76666565/src/yolo_layer.c#L263-L265

* class_probability: 
    * disabled cuz truth_thresh=1 in cfg-file: https://github.com/AlexeyAB/darknet/blob/6682f0b98984e2b92049e985b21ed81b76666565/src/yolo_layer.c#L228
    * https://github.com/AlexeyAB/darknet/blob/6682f0b98984e2b92049e985b21ed81b76666565/src/yolo_layer.c#L270

**Comment by eyalzubia** [comment]
Thanks!
