### ISSUE TITLE
Yolo_console_dll vs Darknet_demo Performance

### ISSUE THREAD

**Issue by phamquanghung263** [AlexeyAB/darknet#126]
Hi, you did a great work.
I have a question about Yolo_console_dll performance.
I used a video ,when run with Daknet.exe => result: 25 fps, 100% GPU load
Run with  Yolo_console_dll => result: 13-14 fps, 50% GPU load
So how to make GPU using full potential when working with Yolo_console_dll ? 
Please help.

**Comment by AlexeyAB** [comment]
@phamquanghung263 Hi,

* What command line do you use to run Darknet.exe?
* What video resolution do you use?

**Comment by phamquanghung263** [comment]
Hi, 
I used command "darknet.exe detector test data/voc.data yolo-voc.cfg yolo-voc.weights -i 0 -thresh 0.2"
My video resolution: 1920x1080
I've compare 2 app and found some things:
-The detect function seem be equal (in my computer take about 50 ms/fame)
-In Yolo_console the block code
`	for (k = 0; k < c; ++k) {
			for (i = 0; i < h; ++i) {
				for (j = 0; j < w; ++j) {
					out.data[count++] = data[i*step + j*c + k] / 255.;
				}
			}
		}`
of funtion "static image_t ipl_to_image(IplImage* src)" take 35-40 ms to run.
=>Detect function must wait for it's input that make my GPU working "tick-tock".
So can we improve it?

**Comment by VanitarNordic** [comment]
I'll try to check also. if it exists, it must be fixed.

**Comment by AlexeyAB** [comment]
@phamquanghung263 Hi,

1. Update file `yolo_v2_class.hpp` from repo: https://github.com/AlexeyAB/darknet/blob/master/src/yolo_v2_class.hpp

2. Add `#include <thread>` at the top of file `yolo_console_dll.cpp`

3. And replace in the file `yolo_console_dll.cpp` this `if{ ... }`: https://github.com/AlexeyAB/darknet/blob/master/src/yolo_console_dll.cpp#L67

To this:
```cpp
if (file_ext == "avi" || file_ext == "mp4" || file_ext == "mjpg" || file_ext == "mov") {	// video file
	cv::Mat frame, prev_frame;
	std::vector<bbox_t> result_vec, thread_result_vec;
	detector.nms = 0.02;	// comment it - if track_id is not required
	for(cv::VideoCapture cap(filename); cap >> frame, cap.isOpened();) {
		auto image_ptr = detector.mat_to_image(frame);
		std::thread td([&]() { thread_result_vec = detector.detect(*image_ptr, 0.2); });

		if (!prev_frame.empty()) {
			result_vec = detector.tracking(result_vec);	// comment it - if track_id is not required
			draw_boxes(prev_frame, result_vec, obj_names, 3);
			show_result(result_vec, obj_names);
		}
		td.join();
		prev_frame = frame;
		result_vec = thread_result_vec;
	}
}
```

----

Fix above allows to divide this code to 2 threads:
1. **58%** of execution time: `network_predict()` + `resize_image()`
2. **42%** of execution time: `mat_to_image()` + `draw_boxes()` + `ffmpeg and cv::VideoCapture` + ...

So this fix speedup at 1.72 times `= (1 / 0.58)`.

This is call stack with execution time:
![cpu_usage](https://user-images.githubusercontent.com/4096485/28539123-4bbdcbb8-70b9-11e7-886f-a5fe324123b1.jpg)

**Comment by AlexeyAB** [comment]
@phamquanghung263 @VanitarNordic 
I added this code to the repo: https://github.com/AlexeyAB/darknet/blob/master/src/yolo_console_dll.cpp#L75

Now it should works 1.7x faster.

**Comment by phamquanghung263** [comment]
@AlexeyAB @VanitarNordic.
Sorry for late reply, I was on vacation.
I've test your suggestion, but in my computer the problem is 'detector.mat_to_image(frame)' take to much time for running. May be it's because of my CPU and my video resolution (1920x1080).
So i decided to use a small buffer to store frames, that make the detector working as i expected.
Thanks for your help.

**Comment by AlexeyAB** [comment]
@phamquanghung263 I changed `mat_to_image()` so now it took only 2% instead of 10%. And now example uses 2 threads. Now I can achive more than 50 FPS on FullHD 1920x1080 video .

![mat_to_image](https://user-images.githubusercontent.com/4096485/28985095-a0a8fff4-7969-11e7-97b8-55b8216925c5.jpg)

**Comment by phamquanghung263** [comment]
This change is magical. Thanks you.
