### ISSUE TITLE
How much memory is needed at the minimum for train?

### ISSUE THREAD

**Issue by xunkaixin** [AlexeyAB/darknet#127]
hi
   thank you for your work.  According to your prompt, I changed the code in detector.c and set 
random = 1 in config file   for different width and height 
   args.w = dim;  
   for(i = 0; i < ngpus; ++i){
        resize_network(nets + i, dim, dim);

     to

     args.w = dim*2;  
     for(i = 0; i < ngpus; ++i){
         resize_network(nets + i, dim*2, dim);
 
  during training  show  “out of memory”  
  but i  set random = 0, it's ok.  so i think  there is not enough memory   (gtx1070 8G)

**Comment by AlexeyAB** [comment]
@xunkaixin Hi,

Yes, there are random network sizes (640x320 - 1216x608),  so can lack memory at the maximum 1216x608.

You can do 2 fixes:

* `int dim = (rand() % 5 + 10) * 32;` so random network sizes will be (640x320 - 960x480) and will be required 1.6 times less memory: https://github.com/AlexeyAB/darknet/blob/9920410ba9cc756c46d6ee84f7b7a2a9fe941448/src/detector.c#L83

* `subdivisions=16` or `subdivisions=32` so at one moment will be loaded /2 or /4 less images during the training and will be required 2x or 4x times less memory: 
 https://github.com/AlexeyAB/darknet/blob/9920410ba9cc756c46d6ee84f7b7a2a9fe941448/cfg/yolo-voc.2.0.cfg#L3

----

Also after training, in your .cfg-file you should use network resolution with the same aspect ration 2:1, i.e. (640x320 - 960x480) with width and height multiple of 32, for example `width=960` and `height=480` https://github.com/AlexeyAB/darknet/blob/9920410ba9cc756c46d6ee84f7b7a2a9fe941448/cfg/yolo-voc.2.0.cfg#L4

**Comment by xunkaixin** [comment]
thank you!
