### ISSUE TITLE
Nan avg loss occurred when Tensor Core was training

### ISSUE THREAD

**Issue by ryumansang** [AlexeyAB/darknet#1271]
Nice to meet you.

I'm currently a Tesla V00 GPU, and when I turn on the Tensor Core option,
1 step and 2 step are normally displayed (8000 avg loss), followed by inf avg loss in 3 step, followed by nan avg loss.

In such cases, disabling CUDNN_HALF will allow you to learn without any problems.
But I think it's meaningless if you can't use the Tensor core.

There are no problems with the data set, and thecfg default settings are the same.

Is there anything suspicious?
I can't think of a solution.

i use this set
opencv: 3.4.0
cuda: 9.1
cudnn: 7.0.5
darkenet: newest

![test](https://user-images.githubusercontent.com/11490836/43173092-e6c049ca-8fed-11e8-9b23-3b459581fa93.PNG)

**Comment by AlexeyAB** [comment]
* Do you train with 1 or several GPUs?
* Try to train first 1000 iterations with `CUDNN_HALF=0`, then stop and continue training from 1000 iteration with `CUDNN_HALF=1`

**Comment by ryumansang** [comment]
Oh, God.
It works!! Thank you.
