### ISSUE TITLE
multiple gpu ram question

### ISSUE THREAD

**Issue by rytisss** [AlexeyAB/darknet#1276]
If I would train model with 2 x GTX1060, does video RAM sums up? For example, will it be possible to utilize 12GB of RAM over both GPUs or training will only utilize memory in one GPU (6GB)?

**Comment by AlexeyAB** [comment]
Video RAM doesn't sum up. But will be used GPU-RAM on both GPU 0 and 1.

GPU 0 and 1 will work in parallel simultaneosely: GPU-0 will be used for odd-iterations, while GPU-1 will be used for even-iterations. Then results from both GPUs will be synchronized automatically.
