### ISSUE TITLE
GPU not full load

### ISSUE THREAD

**Issue by phamngocquy** [AlexeyAB/darknet#1278]
i'm use YOLOv3 on gtx 1050Ti.
but fps is: 10 with mp4 video 1280*720
GPU load < 10%
i'm using yolov3.weights

**Comment by AlexeyAB** [comment]
* Do you use this repository?
* What CPU do you use?
* How many FPS can you get on video like 640x480?

**Comment by phamngocquy** [comment]
i using yolo_cpp_dll.sln and run on python code
And using this reposiroty ^^
My CPU is: i7-7740X
I cant get on video 640*480 is 10 this same with video 1920*1080.

**Comment by AlexeyAB** [comment]
python code - is a bottleneck definitely.
Do you use `cv2.resize()` to resize image to 416x416?

**Comment by phamngocquy** [comment]
thank u so much.
i will try.
May be resize image have decrease accuracy?

**Comment by phamngocquy** [comment]
but, resize the image to 416*416 make increase fps. But GPU is not full load. 
I can make gpu work with its full power ?
Thank u so much

**Comment by Jacob-Stevens-Haas** [comment]
I'm having a similar issue.  Here's a screenshot of my resource monitor on `./darknet.exe detector train`.  Similarly, on `./darknet.exe detector demo` the GPU stops at about 2 of 4 GB and 8 fps.
![image](https://user-images.githubusercontent.com/37048747/48963757-4e99f400-ef4e-11e8-88be-03df4e307401.png)

**Comment by Jacob-Stevens-Haas** [comment]
@AlexeyAB , thank you.  Sometimes when I try training, I get a GPU out of memory error.  When I reduce the batch size, it is able to train.  Will shrinking my images help me use larger batch sizes, or will using a smaller net?

**Comment by AlexeyAB** [comment]
@Jacob-Stevens-Haas 

Set `batch=64 subdivisions=64`

https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

> Note: if error Out of memory occurs then in .cfg-file you should increase subdivisions=16, 32 or 64

**Comment by Jacob-Stevens-Haas** [comment]
@AlexeyAB , I saw that, but it was confusing. If subivisions starts at 64, wouldn't increasing it require more memory?  Or is that supposed to say decrease subdivisions?

**Comment by AlexeyAB** [comment]
@Jacob-Stevens-Haas `memory = batch / subdivisions = 64 / 64 = 1`

**Comment by Jacob-Stevens-Haas** [comment]
@AlexeyAB Thank you - that makes sense!  So if `batch=64  subdivisions = 64` isn't working, I'll try to increase subdivisions to `128` or `256`.  Are subdivisions limited by size of the image?  I'm using 672x368 images.

**Comment by Jacob-Stevens-Haas** [comment]
@AlexeyAB  thank you for the help!  It looks like there's a deeper issue in CUDA/the driver.  For this and other repos, I can avoid these memory errors if I restart my computer and try it fresh.  Apparently it isn't a darknet issue.
