### ISSUE TITLE
Any plans to update for VS2017?

### ISSUE THREAD

**Issue by rtrahms** [AlexeyAB/darknet#128]
I noticed these solutions don't load into MS Visual Studio 2017.  Any plans to make this compatible with this version?
Thanks!
Rob

**Comment by AlexeyAB** [comment]
Hi, yes, there are plans to support MSVS 2017 and cuDNN 6.0.

* What problems with MSVS2017? 
 * Did you install CUDA 8.0 after installing MSVS2017?

**Comment by rtrahms** [comment]
Thanks for the prompt reply!
Yes, we installed CUDA 8.0 after installing VS2017.  The error was that the .vcxproj file could not find the CUDA 8.0.props file.

**Comment by Nfear** [comment]
Having the same problem. Did you find a fix?

**Comment by cenit** [comment]
The solution is VS2017 compatible. Also it is possible now to create solutions for all supported VS versions thanks to CMake.
Note also that VS 2017 and newer support the Open Folder functionality directly, which lets you skip completely the solution
