### ISSUE TITLE
Does it support OpenImages dataset?

### ISSUE THREAD

**Issue by xmubingo** [AlexeyAB/darknet#1285]
As yolov3 paper mentioned, 

> During training we use binary cross-entropy loss for the class predictions.
> This formulation helps when we move to more complex domains like the Open Images Dataset

How to setup the datalayer which support the multilabel training.

**Comment by dexception** [comment]
@AlexeyAB 
Have you tried downloading open images v4 dataset ?
20% of the links are dead and flickr blocks downloads with timeouts.
