### ISSUE TITLE
Check if cuda  available programmatically

### ISSUE THREAD

**Issue by xinvestoriginal** [AlexeyAB/darknet#129]
Hi AlexeyAB, can i check if cuda  available programmatically?

**Comment by AlexeyAB** [comment]
@xinvestoriginal Hi,
You can check if GPU available programmatically - only if it compiled by using CUDA, this is already implemented and may it will work, but I didn't test it: https://github.com/AlexeyAB/darknet/blob/d6ea2ef02689d124798ed97fbc062dbc669e8b1a/src/network.c#L460

But if you want to create source project that will compile with or without CUDA depends on it presence, then you should create your own `CMakeLists.txt` file: https://cmake.org/cmake-tutorial/
