### ISSUE TITLE
Different Result Given

### ISSUE THREAD

**Issue by skipm3** [AlexeyAB/darknet#1291]
![whatsapp image 2018-07-23 at 12 30 37](https://user-images.githubusercontent.com/40790209/43301749-2def128c-9191-11e8-8e62-cf5a9929a419.jpeg)
![whatsapp image 2018-07-23 at 12 30 37 1](https://user-images.githubusercontent.com/40790209/43301751-31880002-9191-11e8-8f42-c7f66f11ed16.jpeg)

The correct one is first image btw. I can get the same x and y coordinate. But how can i get the width and height?

**Comment by AlexeyAB** [comment]
`./darknet detector` gives you coordinates of Top-Left corner of bounded box.
`darknet.py` gives you coordinates of Center of bounded box.

For example, for Truck: `474 + 216/2 = 582`
