### ISSUE TITLE
stop printing TH in cudnnhalf = 1

### ISSUE THREAD

**Issue by nafis00141** [AlexeyAB/darknet#1295]
![capture](https://user-images.githubusercontent.com/17634162/43318523-e75bfe48-91c2-11e8-9491-2e201a01aada.PNG)

how to stop printing TH ?

**Comment by AlexeyAB** [comment]
Commen these lines: https://github.com/AlexeyAB/darknet/blob/6682f0b98984e2b92049e985b21ed81b76666565/src/convolutional_layer.c#L252-L253
