### ISSUE TITLE
Compilation errors on Ubuntu 18.04, OpenCV 3.4 and CUDA 9.1

### ISSUE THREAD

**Issue by endo123** [AlexeyAB/darknet#1297]
Hi, 

I am trying to build Darknet on the aforementioned environment and get the following which suggests potential OpenCV version mismatch or the all the include files not in the path -

*******************************************************

**g_cc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -O0 -g -DOPENCV -fopenmp -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/image.c -o obj/image.o
./src/image.c: In function ‘draw_detections_cv_v3’:
./src/image.c:476:19: warning: variable ‘rgb’ set but not used [-Wunused-but-set-variable]
             float rgb[3];
                   ^~~
./src/image.c: In function ‘draw_detections_cv’:
./src/image.c:577:19: warning: variable ‘rgb’ set but not used [-Wunused-but-set-variable]
             float rgb[3];
                   ^~~
./src/image.c: In function ‘draw_train_chart’:
./src/image.c:631:16: warning: implicit declaration of function ‘CV_RGB’; did you mean ‘CV_C’? [-Wimplicit-function-declaration]
     cvSet(img, CV_RGB(255, 255, 255), 0);
                ^~~~~~
                CV_C
./src/image.c:631:16: error: incompatible type for argument 2 of ‘cvSet’
compilation terminated due to -Wfatal-errors.
Makefile:130: recipe for target 'obj/image.o' failed
make: *** [obj/image.o] Error 1_**

******************************************************************************************************

Could somebody please point me in the right direction?  

Thanks in advance.

**Comment by fabioac** [comment]
hi endo123,

which version of open cv are you using? 3.4.0 exactly or 3.4.1.
you should use 3.4.0 as version 3.4.1 doesn't offer support to C just C++

**Comment by endo123** [comment]
Thanks! I thought I was picking up 3.4.0 from its github repository, but it seems like I have 3.4.2 .. or at least that is what pkg-config --modversion opencv is showing.  Is there a simple way to uninstall OpenCV so I re-install 3.4 on a clean environment..

**Comment by fabioac** [comment]
Try this tutorial, it removes and install again (you should compile). Attention on git ckecout [https://www.learnopencv.com/install-opencv3-on-ubuntu/](url)

**Comment by fabioac** [comment]
try thist tutorial, pay attention on git chekcout

https://www.learnopencv.com/install-opencv3-on-ubuntu/

**Comment by endo123** [comment]
Thanks! That fixed the problem I was having. With 3.4.0, I am able to successfully build darknet in my environment (Ubuntu 18.04, CUDA 9.1).
