### ISSUE TITLE
Custom training - amount of images needed for training

### ISSUE THREAD

**Issue by WajWaraich** [AlexeyAB/darknet#13]
Hi,

Thanks for sharing your Windows build for darknet, I want to run some custom training but I am unsure as to how many samples I need, I want to train using two extra classes headphones and video cards (I do not need these classes to be generalised) I just need the detection to be done on those particular objects that I have taken pictures from.

I know this question probably doesn't just have one correct answer but thought I'd throw it out there to get an idea in regards to how much labelling I would have to do.

Kind regards,
Waj

**Comment by AlexeyAB** [comment]
Hi,

* If you want to detect only those sides of objects which shown on training images, with the same rotations, only on backgrounds from training images, then you can use about ~10-100 images per object (to train ~(100*objects) iterations )

* If you want to detect any objects from any: sides, rotations, lighting, without false-detection on any backgrounds - then you should use about ~2000 images per object

**Comment by WajWaraich** [comment]
@AlexeyAB Thanks for your reply, it is much appreciated.
