### ISSUE TITLE
Yolo-label format 

### ISSUE THREAD

**Issue by urvashibhavsar** [AlexeyAB/darknet#130]
the 4th column i.e the width is the 
`(complete width of the bounding box/image width)`
 right? so the xmin would be 
`[center-(width /2)]*image_width`
is this correct?

**Comment by AlexeyAB** [comment]
Yes, `abs_obj_x_min = [relative_obj_center - (relative_obj_width/2)] * abs_image_width`

**Comment by urvashibhavsar** [comment]
Thanks!
