### ISSUE TITLE
question

### ISSUE THREAD

**Issue by zhaojc001** [AlexeyAB/darknet#1316]
when I compile , it happens the error:
LINK : fatal error LNK1181: 无法打开输入文件“x64\yolo_cpp_dll.lib”,
I can not find yolo_cpp_dll.lib in x64 folder,please help me,where i get yolo_cpp_dll.lib.

**Comment by AlexeyAB** [comment]
First, you should compile `yolo_cpp_dll.sln`

**Comment by zhaojc001** [comment]
when I compile,it happens the error that LINK : fatal error LNK1181:can not open input file“x64\yolo_cpp_dll.lib”,i do not know the cause of the error,the yolov2 code,i
can find  yolo_cpp_dll.lib in the folder x64,it can compile sucessfully.

**Comment by zhaojc001** [comment]
I have another question that the yolo9000,i test object detection in real time,it happens that the result occurs a lot of error results,i do not know the cause of it.

**Comment by zhaojc001** [comment]
Thank you very much,I follow what your have said, first compiling yolo_cpp_dll.sln before compiling yolo_console_dll.cpp,I solve the problem.
