### ISSUE TITLE
Prevent plotting of loss graph

### ISSUE THREAD

**Issue by Perseus14** [AlexeyAB/darknet#1318]
Hi, I am running my code in a server and it doesn't have any GUI components, is there a parameter to prevent darknet from plotting the loss graph or should we change the code (if not would appreciate being shown where the code is)?

Thanks

**Comment by AlexeyAB** [comment]
Hi, use flag `-dont_show` at the end of command.

**Comment by Perseus14** [comment]
Thanks, it works!
