### ISSUE TITLE
Model Save 

### ISSUE THREAD

**Issue by Kn15263ss** [AlexeyAB/darknet#132]
Hi, 
I am having a bit of a problem trying to train a model.
For every 100 iterations, an updated set of weights is trained as a ___XXX.weights where XXX is the iteration number.
New weights are not saved after iterating past 1000 iterations (No ____1000.weights file is generated), instead a new file is created as yolo-voc.backup and no new weights are created.
This should just be a simple case of changing a for loop statement somewhere in some C file but I cannot determine which C file to change.
Is there someone that can tell me where to change this value so that new weights are saved after 1000 iterations instead of as a .backup?

Thank You

**Comment by AlexeyAB** [comment]
Hi,

In Linux Yolo in the file `detector.c`: https://github.com/pjreddie/darknet/blob/0710531b666d233cae5f88706c754d900a2600af/examples/detector.c#L136
* change this line: `if(i%10000==0 || (i < 1000 && i%100 == 0)){`
* to this line: `if(i%1000==0 || (i < 1000 && i%100 == 0)){`

**Comment by Kn15263ss** [comment]
Thank you!  it would be save!!
