### ISSUE TITLE
VERY Slow inferencing on Titan V

### ISSUE THREAD

**Issue by kooscode** [AlexeyAB/darknet#1322]
I just installed a Titan V and it seems inference is at least 60% slower than with my GTX 1080 

Training is pretty fast though..

I recompiled with: CUDNN_HALF=1

and set ARCH= -gencode arch=compute_70,code=[sm_70,compute_70]

Any ideas ??

![titanv](https://user-images.githubusercontent.com/35713435/43562637-83e60962-95d2-11e8-93b3-dd7d1a893ea4.jpg)

![titanv-2](https://user-images.githubusercontent.com/35713435/43562796-9995cf44-95d3-11e8-938a-d51b735d3159.jpg)

**Comment by kooscode** [comment]
Yes, I have those values in the Makefile.

I'm going to add some to to capture timing of inference, but just eyeballing it, the Titan V was visibly a lot slower.. I cut up a 20 megapixel photo into 512x512 blocks and run inferencing on that (network input size is 512x512) and on a separate thread update the display..

the Titan V was visibly at least 50-60% slower.  But I'll add timing code and report back the weekend.

![makefile](https://user-images.githubusercontent.com/35713435/43592707-09e44274-962b-11e8-904a-0954b3f3c724.jpg)

**Comment by AlexeyAB** [comment]
> EDIT: Actually.. I have timing code in there.. the GTX 1080 took 35 seconds to process the entire image and the Titan V took 178 seconds.

1. What time can you get if `CUDNN_HALF=0` ?
2. Do you use the latest version from this repository?
3. Did you change anything in the source code?
4. What versions of CUDA and cuDNN do you use?
5. What time can you get on both TitanV and 1080 if you use width=416 height=416 in cfg file?

**Comment by kooscode** [comment]
Hmm..  interresting,

1. CUDNN_HALF = 0 time is 178 seconds, so no change... let me do a bit of digging into the code and see if there are any threading issues using the Titan V.
2. Latest, Yes, just got a pull few sec. ago.
3. No changes.
4. NVCC version is V9.2.148
5. not sure about 416x416, let me go dig into that too..

I'll go dig into 1. and 5. and let you know soon..

btw, THANK YOU for the help and super fast response, you are awesome!!

cheers

**Comment by AlexeyAB** [comment]
> NVCC version is V9.2.148

Also what cuDNN version do you use?

Try to use

* CUDA 9.1: https://developer.nvidia.com/cuda-91-download-archive
* download and install cuDNN 7.0 for CUDA 9.1: https://developer.nvidia.com/cudnn

**Comment by kooscode** [comment]
cuDNN version 7.0.5    

I REALLY dont want to re-install CUDA 9.1.. its a big PITA and also would have to re-install nvidia drivers and recompile OpenCV etc. etc..

let me check the network input sizes and threading stuff though..

**Comment by kooscode** [comment]
AAARRRGGGHH...

I am SO sorry..  completely rookie stupid mistake..

I was linking against an old version of darknet.so that was compiled for GTX1080  and I never updated the .so file in my /usr/lib where its being linked form after i recompiled darknet for Titan V...

I now get 22 seconds instead of 178 seconds...      Its still not as fast as I would have though a TitanV to be over a GTX 1080... but I'll go to work in optimizing the app..  

SORRY again...
