### ISSUE TITLE
what mean "-i" and "0"?

### ISSUE THREAD

**Issue by murras** [AlexeyAB/darknet#1326]
In cmd line `darknet.exe detector test data/coco.data cfg/yolov3.cfg yolov3.weights -i 0 -thresh 0.25`

what mean -i and 0 ?

and `- thresh 0.25` means objects over 0.25 prob are displayed?

Sorry for my bad English.

**Comment by AlexeyAB** [comment]
> and - thresh 0.25 means objects over 0.25 prob are displayed?

Yes.


`-i 0` means that will be used `GPU-0`

**Comment by murras** [comment]
I run on notebook.
It has intel graphic and gtx 1050 ti.
If I want use 1050 ti, i should use -i 1?

**Comment by AlexeyAB** [comment]
No, there is numbered only nVidia GPUs (not Intel or AMD). Use `-i 0`

**Comment by murras** [comment]
Thank you
