### ISSUE TITLE
Some problem for training for small objects in yolov3-tiny

### ISSUE THREAD

**Issue by RosaShao** [AlexeyAB/darknet#1329]
Thanks for your detailed code, that help me detect lots objects.

But when I train for small object, I got  something wrong.
I set layers = -1, 11  and stride=4 in yolov3-tiny.cfg like you said in "How to improve object detection:"
And run "darknet.exe partial cfg/yolov3-tiny.cfg yolov3-tiny.weights yolov3-tiny.conv.15 15".
I got that: 
  20 route  19 36
  21 Layer before convolutional layer must output image.: Cannot allocate memory
darknet: ./src/utils.c:255: error: Assertion `0' failed.

Then I chane batch to 1 and subvisions to 1, I got that:
  20 route  19 36
  21 Layer before convolutional layer must output image.: File exists
darknet: ./src/utils.c:255: error: Assertion `0' failed.

Could you help me?
Thanks for your help!

**Comment by RosaShao** [comment]
I change batch to 32 and subvisions to 8, I also got that:
20 route 19 36
21 Layer before convolutional layer must output image.: File exists
darknet: ./src/utils.c:255: error: Assertion `0' failed.

**Comment by AlexeyAB** [comment]
For yolov3-tiny.cfg

* set here `stride= 8` https://github.com/AlexeyAB/darknet/blob/6682f0b98984e2b92049e985b21ed81b76666565/cfg/yolov3-tiny.cfg#L154


* set here `layers = -1, 4` https://github.com/AlexeyAB/darknet/blob/6682f0b98984e2b92049e985b21ed81b76666565/cfg/yolov3-tiny.cfg#L157

**Comment by RosaShao** [comment]
It's work, it's work!
I can't thank you enough!

**Comment by goodtogood** [comment]
@AlexeyAB 
what's the benefit of modifying the layer for small object?

**Comment by RosaShao** [comment]
According to my experience, when you modifying the layer for small object, the testing effectiveness of small object will greatly improve. But the large ones may be lost.

**Comment by AlexeyAB** [comment]
@goodtogood Yes, if most of your objects are small, it can be a reason to do this fix - it will improve accuracy for small objects.

**Comment by fabioac** [comment]
Hi, 
these setting also works for yolov3 for detecting small objects?
Thanks
Fabio

**Comment by AlexeyAB** [comment]
@fabioac 
For `yolov3.cfg` use this fix:

 * for training for small objects - set `layers = -1, 11` instead of https://github.com/AlexeyAB/darknet/blob/6390a5a2ab61a0bdf6f1a9a6b4a739c16b36e0d7/cfg/yolov3.cfg#L720 and set `stride=4` instead of https://github.com/AlexeyAB/darknet/blob/6390a5a2ab61a0bdf6f1a9a6b4a739c16b36e0d7/cfg/yolov3.cfg#L717


More info: https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

**Comment by fabioac** [comment]
Thank you @AlexeyAB
