### ISSUE TITLE
YoloWrapper.cs Not able to use detect_mat

### ISSUE THREAD

**Issue by goelx029** [AlexeyAB/darknet#1333]
Hi,

I am trying to use the YoloWrapper.cs that has been given in the code base. It works fine when I use it in my application with the detect_image function, however when I try to convert my image to a byte array and then use the detect_mat, it throws an error - NotSupportedException.

I have tried numerous things (which I dont think could resolve the problem) but nothing happens. Is there a way that I can resolve this problem?

**Comment by AlexeyAB** [comment]
@goelx029 Hi,

open in MSVS2015 file `build\darknet\yolo_cpp_dll.sln` -> (right click on project) -> properties -> C/C++ -> Preprocessor -> Preprocessor Definitions -> Add here at the begining of line `OPENCV;`

And recompile `yolo_cpp_dll.sln`


----

If some errors occur then check paths to the OpenCV:

* (right click on project) -> properties -> C/C++ -> General -> Additional Include Directories
* (right click on project) -> properties -> Linker -> General -> Additional Library Directories
