### ISSUE TITLE
Detecting Big Objects

### ISSUE THREAD

**Issue by liaoluke** [AlexeyAB/darknet#1334]
Hi, is there any way to modify yolo v3 to be more accurate at detecting bigger objects? I'm trying to use it for a purpose where detecting small objects is not as important. Thanks.

**Comment by AlexeyAB** [comment]
@liaoluke Hi,

You can:

* remove these layers: https://github.com/AlexeyAB/darknet/blob/b8e6e80c6d411d05a9e09f1e3676eb9a7f3ea0e8/cfg/yolov3.cfg#L705-L788

* set here `mask = 4,5,6,7,8` https://github.com/AlexeyAB/darknet/blob/b8e6e80c6d411d05a9e09f1e3676eb9a7f3ea0e8/cfg/yolov3.cfg#L608

* set here `mask = 0,1,2,3` https://github.com/AlexeyAB/darknet/blob/b8e6e80c6d411d05a9e09f1e3676eb9a7f3ea0e8/cfg/yolov3.cfg#L694

* recalculate anchors as usuall: https://github.com/AlexeyAB/darknet#how-to-improve-object-detection
`darknet.exe detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416`

And train as usuall.

**Comment by liaoluke** [comment]
Ok, thanks.
