### ISSUE TITLE
why mask setting is different ?

### ISSUE THREAD

**Issue by goodtogood** [AlexeyAB/darknet#1341]
Hi, @AlexeyAB 
I found mask setting is different after comparing [yolov3-tiny.cfg](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov3-tiny.cfg#L175) with [yolov3-tiny_obj.cfg](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov3-tiny_obj.cfg#L175)
why , It's mean or just a typo ?
thanks!

**Comment by AlexeyAB** [comment]
@goodtogood Hi,

Yes.

* In the yolov3-tiny.cfg is a typo. But you can't fix it, because https://pjreddie.com/media/files/yolov3-tiny.weights  is trained and can be used only with this typo.

* But for training your own model you can fix this typo.

**Comment by goodtogood** [comment]
I see,  thank you so much!
