### ISSUE TITLE
names 80 that isn't equal to classes=1

### ISSUE THREAD

**Issue by androuino** [AlexeyAB/darknet#1348]
Hi,

I'm having this error of
`
Error: in the file data/coco.names number of names 80 that isn't equal to classes=1 in the file build/darknet/x64/cfg/yolo-obj.cfg build/darknet/x64/obj/3.jpg: Predicted in 0.03 seconds
`

my dataset contains only 20 .jpg images and while I was training, it's always nan from the beginning and count is always equal to 0.

Am I missing something? Thanks.

**Comment by dexception** [comment]
80 is the number of classes in mscoco dataset. If your training on your own dataset. You need to make your own names file and specify the number of categories.
