### ISSUE TITLE
use darknet weights with java

### ISSUE THREAD

**Issue by androuino** [AlexeyAB/darknet#1349]
Hi, I would like to ask if I can use the trained weights with java and how? Thanks

**Comment by uday60** [comment]
Why would you use Java when the whole world is trying to speed up things ? Java would just be a bottleneck like Python.

**Comment by androuino** [comment]
I'm used to java and have tried the DeepLearning4J ML library. Based on a benchmark, it turns out that Java is faster than python.

**Comment by agibsonccc** [comment]
@androuino could you file an issue on the dl4j repo instead? This doesn't seem like the right place to ask . I understand the author's reluctance to support java specifically. We can work on importing these weights or maybe work with you on a pull request.

**Comment by androuino** [comment]
@agibsonccc  sure. I'll go ahead to dl4j repo. Thanks.
