### ISSUE TITLE
A bug in network.c

### ISSUE THREAD

**Issue by Teoge** [AlexeyAB/darknet#135]
In the commit 5bc62b1, you add a line [`free(net.workspace);`](https://github.com/AlexeyAB/darknet/blob/master/src/network.c#L598) in `void free_network(network net)` of [network.c](https://github.com/AlexeyAB/darknet/blob/master/src/network.c).
But in `network parse_network_cfg(char *filename)` of [parser.c](https://github.com/AlexeyAB/darknet/blob/master/src/parser.c), the variable `net.workspace` is allocated as follows:
```
#ifdef GPU
        if(gpu_index >= 0){
            net.workspace = cuda_make_array(0, (workspace_size-1)/sizeof(float)+1);
        }else {
            net.workspace = calloc(1, workspace_size);
        }
#else
        net.workspace = calloc(1, workspace_size);
#endif
```
Therefore while using gpu solutions, [`free(net.workspace);`](https://github.com/AlexeyAB/darknet/blob/master/src/network.c#L598) will cause an exception because it is allocated using `cuda_make_array`.
Please fix this small bug, thank you.

**Comment by AlexeyAB** [comment]
@Teoge Hi,

Thank you, I fixed it: https://github.com/AlexeyAB/darknet/commit/576dbe12e64697f10aaa15f6ef23e0a3d5eea5b5
