### ISSUE TITLE
Save Detection Output to .txt file

### ISSUE THREAD

**Issue by silvernine209** [AlexeyAB/darknet#1355]
Hi AlexeyAB,

First of all, thank you for your hard and diligent work on your repo!
My training is going very well thanks to your good instructions.

Here is my question if you can spare some time! :)
After I'm done training weights on 1+ million training set images over 500 classes, I need to detect objects in 100k testing set images and save output for each image. I feel like there should already answer but I wasn't able to find easily. I would like to save detection for all of 100k images in one text file in following format :

        <image name> <class> <confidence> <x_min> <y_min> <x_max> <y_max>

I can postprocess to obtain<x_min> <y_min> <x_max> <y_max> if it is easier for you to recommend a way to have <x_center> <y_center> <w> <h>

Thank you for your work again and appreciate your help in advance!

**Comment by ritwikdubey** [comment]
More experienced folks would answer it better but there's a code section in detector.c which could help you. Another relevant function would be `draw_detections_v3` in image.c.

If you test using the flag `-save_labels`, following code would save the tag file similar to label file generated by yolo_mark, Though it may not be exactly what you're looking for, class_id, names[class_id], dets, dets.bbox.x/y/w/h are some of the variables in the function which could be used to fetch what you've mentioned. 

```
void test_detector(….)
        // pseudo labeling concept - fast.ai
        if(save_labels)
        {
            char labelpath[4096];
            replace_image_to_label(input, labelpath);

            FILE* fw = fopen(labelpath, "wb");
            int i;
            for (i = 0; i < nboxes; ++i) {
                char buff[1024];
                int class_id = -1;
                float prob = 0;
                for (j = 0; j < l.classes; ++j) {
                    if (dets[i].prob[j] > thresh && dets[i].prob[j] > prob) {
                        prob = dets[i].prob[j];
                        class_id = j;
                    }
                }
                if (class_id >= 0) {
                    sprintf(buff, "%d %2.4f %2.4f %2.4f %2.4f\n", class_id, dets[i].bbox.x, dets[i].bbox.y, dets[i].bbox.w, dets[i].bbox.h);
                    fwrite(buff, sizeof(char), strlen(buff), fw);
                }
            }
            fclose(fw);
        }
```

dets.bbox.x/y *are* coordinates of the center scaled by width and height. `draw_detections_v3` show calculations to interpret corners from x/y/w/h.
```
            printf("\t(left_x: %4.0f   top_y: %4.0f   width: %4.0f   height: %4.0f)\n",
                (selected_detections[i].det.bbox.x - selected_detections[i].det.bbox.w / 2)*im.w,
                (selected_detections[i].det.bbox.y - selected_detections[i].det.bbox.h / 2)*im.h,
                selected_detections[i].det.bbox.w*im.w, selected_detections[i].det.bbox.h*im.h);
```

**Comment by AlexeyAB** [comment]
Did you try to use this command?

`./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights -dont_show -ext_output < train.txt > result.txt`

**Comment by silvernine209** [comment]
Thank you guys for the support, I will play around with the code 👍

**Comment by zaradamou** [comment]
Hi silvernine209, 

I am looking for the exact same format you requested in this post. Any chance you figured this out? 

Thank you!
