### ISSUE TITLE
darknet build error MSB3721

### ISSUE THREAD

**Issue by gimmy4268** [AlexeyAB/darknet#136]
hi,

i have met some error

error 	MSB3721	命令 ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe" -gencode=arch=compute_20,code=\"sm_20,compute_20\" --use-local-env --cl-version 2015 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin"  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include"  -G   --keep-dir Debug -maxrregcount=0  --machine 32 --compile -cudart static  -g   -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /FS /Zi /RTC1 /MDd " -o Debug\activation_kernels.cu.obj "D:\darknet-master\src\activation_kernels.cu"" exited with code 2。	

after  i google it , i can't  find good a solution

so , please help me with it

![1](https://user-images.githubusercontent.com/30428270/28660012-f3a9d534-72e3-11e7-9252-5b81bae863cc.png)

**Comment by AlexeyAB** [comment]
Hi, I can't reproduce you problem.

1. Do you use Windows 7 x64, MSVS 2015, CUDA 8.0, OpenCV 2.4.x?
2. What file did you open in MSVS, is it `darknet.sln`?
3. Did you install CUDA 8.0 after MSVS 2015 has been installed?

**Comment by gimmy4268** [comment]
1. I use Win10 x64 , MSVS2015 , CUDA 8.0 ,and Opencv  2.4.13.2
2. yes , i open darknet .sln
3. yes ,i install MSVS2015 then i install CUDA 8.0

is there any problem with my CUDA ?
Because when first time i install CUDA ,the screen just black out 
So i just install again, and it  sucessly install

**Comment by AlexeyAB** [comment]
@gimmy4268 Can you show Build customization window in your MSVS when you opened darknet.sln? Such as:

![cuda_check](https://user-images.githubusercontent.com/4096485/28683035-bd409aea-7307-11e7-9ac2-dab13b7ebaf9.jpg)


You can find it here:

![vs2013-r-5](https://user-images.githubusercontent.com/4096485/28683058-d101ea66-7307-11e7-8338-d698b749f7bf.jpg)

**Comment by AlexeyAB** [comment]
Also try set x64 and Release and do:
* Build -> Clean
* Build -> Rebuild

**Comment by AlexeyAB** [comment]
Also do:

1. (right click on project) -> Retarget SDK Version -> set **10.0.xxx**

![ic827368](https://user-images.githubusercontent.com/4096485/28688766-b1eeab50-731b-11e7-8b1f-b2a37305ef6b.jpeg)

![6014 5](https://user-images.githubusercontent.com/4096485/28688896-3e9f37a4-731c-11e7-8e0a-20217ff001e5.png)

2. (right click on project) -> Properties -> General -> Target Platform version -> set **10.0.10240.0** (or set inherir from parent)

![8715 2](https://user-images.githubusercontent.com/4096485/28688973-8e54707a-731c-11e7-8e3c-ad2857b8e419.png)


----

Then set x64 and Release and do:
* Build -> Clean
* Build -> Rebuild

**Comment by sumith96** [comment]
![screenshot 10](https://user-images.githubusercontent.com/30292961/28689974-29595afa-7335-11e7-9d28-10c99f56607e.png)
the same as are enabled in dependencies and iam not getting win10 option there even though mine in win10...could you plz help me out

**Comment by AlexeyAB** [comment]
@sumith96 Try to find solution here: https://stackoverflow.com/questions/38290169/cannot-find-corecrt-h-universalcrt-includepath-is-wrong

What directories do you have?:

* in the `C:\Program Files (x86)\Windows Kits\10\Include\`
* and in the `C:\Program Files (x86)\Windows Kits\10\Lib\`

----

Also try to do:

* (right click on project) -> properties -> C/C++ -> General -> Additional Include Directories, put here:
` C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\ucrt\;C:\opencv_2.4.9\opencv\build\include;..\..\3rdparty\include;%(AdditionalIncludeDirectories);$(CudaToolkitIncludeDir);$(cudnn)\include`

* (right click on project) -> properties -> Linker -> General -> Additional Library Directories, put here:
`C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt\x64;C:\opencv_2.4.9\opencv\build\x64\vc12\lib;$(CUDA_PATH)lib\$(PlatformName);$(cudnn)\lib\x64;%(AdditionalLibraryDirectories)`

**Comment by gimmy4268** [comment]
It works !
After your instruction, i build successfully!

Thank you for  kindly helping !

**Comment by sumith96** [comment]
C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\x64
except this every thing is checked and is present
still getting same errors....could u plz help me out!

**Comment by AlexeyAB** [comment]
@gimmy4268 Which of my inctruction did help you?
Then I could recommend these instructions to other people.

**Comment by gimmy4268** [comment]
i don't know which one  did help me.
because i just do all your instructions, and then it works! 
sorry can not help you

**Comment by azim92** [comment]
Hello AlexeyAB
I cant find any pthread.h in the downloaded folder.
May I know if these error has a solution?
Thank you in advance!

![capture](https://user-images.githubusercontent.com/30527495/33154810-1961e8da-d026-11e7-971a-042cab1c28a5.JPG)

**Comment by azim92** [comment]
Oh found the solution.
https://github.com/AlexeyAB/darknet/issues/175

**Comment by mudapaladinni** [comment]
How to find the Object background color and border thickness of the object using yolo?

**Comment by mudapaladinni** [comment]
How to find the Object features like color, border thickness, co-ordinates, angle of the object etc..?

Please help me out
