### ISSUE TITLE
Can't open label file. (This can be normal only if you use MSCOCO)

### ISSUE THREAD

**Issue by omg777** [AlexeyAB/darknet#1364]
Hi,
I tried to calculate mAP for PASCAL VOC dataset. but I got 
`
Can't open label file. (This can be normal only if you use MSCOCO)
` error.
This is my command to get mAP (in linux)
`./darknet detector map cfg/voc.data own.cfg yolo.weights`

Here is my file setteings
1. cfg/voc.data
```
classes= 20
train  = /darknet/train.txt
valid  = /2007_test.txt
names = data/voc.names
backup = /backup/
```
(All locations are correct)

2.train.txt and 2007_test.txt include the image path like
`VOCdevkit/VOC2007/JPEGImages/000034.jpg 
 ...
`

+
Where should I place the `annotation`s path information`?

**Comment by AlexeyAB** [comment]
There was a bug, I just fixed it. 
Update your code from Github.

**Comment by JasOlean** [comment]
I downloaded your repo but there is still error like this.

**Comment by AlexeyAB** [comment]
@JasOlean 

* Did you use the latest commit?

* Can you show screenshot of this error?

* How it can be solved: https://github.com/AlexeyAB/darknet/issues/1365#issuecomment-411753375

**Comment by JasOlean** [comment]
Did you use the latest commit?
Yes, I use latest.

Can you show screenshot of this error?
the error is "Can't open label file. (This can be normal only if you use MSCOCO)"
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.003262, Avg Recall: -nan,  count: 0


this is my .data file.
classes = 1            
train = /home/user/darknet/data/train.txt            
valid = /home/user/darknet/data/eval.txt            
names = /home/user/darknet/data/obj.names            
backup = /home/user/darknet/backup/

this is my img path.
/home/user/darknet/data/train/images/CARDS_OFFICE_H_T_frame_0556.jpg

How can I solve this.

**Comment by AlexeyAB** [comment]
@JasOlean 
1. Do you have **txt** file?
`/home/user/darknet/data/train/images/CARDS_OFFICE_H_T_frame_0556.txt`

----

> this is my img path.
> /home/user/darknet/data/train/images/CARDS_OFFICE_H_T_frame_0556.jpg

2. Do you have this image in the `/home/user/darknet/data/eval.txt` ?

**Comment by mhaghighat** [comment]
I got the latest version as of today (08/15/18), and built it on an Ubuntu machine. But I keep seeing this message frequently:
`Can't open label file. (This can be normal only if you use MSCOCO)`

I am confident that for every file that is listed in the **train.txt** there is a **.jpg** and a **.txt** file in the **images** and the **labels** folders, respectively.

Here is a sample screen-shot:

![image](https://user-images.githubusercontent.com/13155707/44171901-5c5af600-a090-11e8-9b4d-7b359493981e.png)

**Comment by AlexeyAB** [comment]
@mhaghighat Put txt-files to the same folder where are jpg-files.

**Comment by mhaghighat** [comment]
@AlexeyAB I really appreciate your prompt reply and support.
For some reason, it gets fixed when I uncomment [this line](https://github.com/AlexeyAB/darknet/blob/a723e1c62a27aeb39aaf7fcdeb3beb4e89fba32d/src/utils.c#L209) instead of the two following lines at `replace_image_to_label()`.

```
find_replace(input_path, "/images/", "/labels/", output_path);
//find_replace(input_path, "/images/train2014/", "/labels/train2014/", output_path);
//find_replace(output_path, "/images/val2014/", "/labels/val2014/", output_path);
```

It puzzles me why the latter two lines weren't doing the job!

**Comment by AlexeyAB** [comment]
@mhaghighat 

Some people put txt/jpg files in a such directory `.../some/images/dataset1`, and they don't expect that Darknet will search txt-files in the `.../some/labels/dataset1`.
Also initally there were such issues: https://github.com/pjreddie/darknet/issues/842

Some people put txt/jpg files in the same directory (images), but some puts in different directories (images, labels). 
And only in the datasets like PascalVOC/MS COCO there are txt and jpg files are in the different directories, and this functions solve these cases: https://github.com/AlexeyAB/darknet/blob/a723e1c62a27aeb39aaf7fcdeb3beb4e89fba32d/src/utils.c#L210-L215
