### ISSUE TITLE
Unable to calculate mAP: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by JohnWnx** [AlexeyAB/darknet#1369]
Hi, I'm unable to calculate the mAP for the trained weights as the error occurred: 
![image](https://user-images.githubusercontent.com/40804580/43938878-d089a130-9c98-11e8-90a2-820637f737cd.png)

I have verified that training and detection works for the weights file and the data file.

can anyone advise on this?

Thanks!

**Comment by samanthawyf** [comment]
Same problem. Have you solved it? Indeed, I succeeded at first, then it goes wrong, showing "Segmentation fault".

**Comment by AlexeyAB** [comment]
@JohnWnx @samanthawyf In the screenshot you forgot to specify `yolo-text.cfg` file.

Example: https://github.com/AlexeyAB/darknet#when-should-i-stop-training

`./darknet detector map data/obj.data yolo-obj.cfg backup\yolo-obj_7000.weights`

**Comment by AlexeyAB** [comment]
@JohnWnx Hi,

> Is the mAP performed on the images specified in test.txt? 

Yes.
Try to set `valid = /home/john/Desktop/ALEXEY/data/text_dataset/train.txt`

Run mAP calculation. And show fullscreen screenshot.

**Comment by JohnWnx** [comment]
![image](https://user-images.githubusercontent.com/40804580/45091770-0e448a00-b146-11e8-8477-a867ee003cb9.png)

![image](https://user-images.githubusercontent.com/40804580/45091808-24eae100-b146-11e8-815c-e485601342ed.png)

![image](https://user-images.githubusercontent.com/40804580/45091865-4e0b7180-b146-11e8-9034-017a03ea0e2d.png)

**Comment by AlexeyAB** [comment]
Does `./darknet detecto recall ...` and `./darknet detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416` work well?

**Comment by i-chaochen** [comment]
I have the same issue when I calculate mAP for coco dataset.  

I am using the download yolov3.weight, except class 1 and 5, is ap too low? it's smaller than 0.5%...

$ ./darknet detector map cfg/voc.data cfg/yolov3.cfg ~/Desktop/yolov3.weights 
layer     filters    size              input                output
   0 conv     32  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  32 0.299 BF
   1 conv     64  3 x 3 / 2   416 x 416 x  32   ->   208 x 208 x  64 1.595 BF
   2 conv     32  1 x 1 / 1   208 x 208 x  64   ->   208 x 208 x  32 0.177 BF
   3 conv     64  3 x 3 / 1   208 x 208 x  32   ->   208 x 208 x  64 1.595 BF
   4 Shortcut Layer: 1
   5 conv    128  3 x 3 / 2   208 x 208 x  64   ->   104 x 104 x 128 1.595 BF
   6 conv     64  1 x 1 / 1   104 x 104 x 128   ->   104 x 104 x  64 0.177 BF
   7 conv    128  3 x 3 / 1   104 x 104 x  64   ->   104 x 104 x 128 1.595 BF
   8 Shortcut Layer: 5
   9 conv     64  1 x 1 / 1   104 x 104 x 128   ->   104 x 104 x  64 0.177 BF
  10 conv    128  3 x 3 / 1   104 x 104 x  64   ->   104 x 104 x 128 1.595 BF
  11 Shortcut Layer: 8
  12 conv    256  3 x 3 / 2   104 x 104 x 128   ->    52 x  52 x 256 1.595 BF
  13 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128 0.177 BF
  14 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256 1.595 BF
  15 Shortcut Layer: 12
  16 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128 0.177 BF
  17 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256 1.595 BF
  18 Shortcut Layer: 15
  19 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128 0.177 BF
  20 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256 1.595 BF
  21 Shortcut Layer: 18
  22 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128 0.177 BF
  23 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256 1.595 BF
  24 Shortcut Layer: 21
  25 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128 0.177 BF
  26 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256 1.595 BF
  27 Shortcut Layer: 24
  28 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128 0.177 BF
  29 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256 1.595 BF
  30 Shortcut Layer: 27
  31 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128 0.177 BF
  32 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256 1.595 BF
  33 Shortcut Layer: 30
  34 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128 0.177 BF
  35 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256 1.595 BF
  36 Shortcut Layer: 33
  37 conv    512  3 x 3 / 2    52 x  52 x 256   ->    26 x  26 x 512 1.595 BF
  38 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256 0.177 BF
  39 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512 1.595 BF
  40 Shortcut Layer: 37
  41 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256 0.177 BF
  42 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512 1.595 BF
  43 Shortcut Layer: 40
  44 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256 0.177 BF
  45 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512 1.595 BF
  46 Shortcut Layer: 43
  47 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256 0.177 BF
  48 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512 1.595 BF
  49 Shortcut Layer: 46
  50 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256 0.177 BF
  51 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512 1.595 BF
  52 Shortcut Layer: 49
  53 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256 0.177 BF
  54 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512 1.595 BF
  55 Shortcut Layer: 52
  56 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256 0.177 BF
  57 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512 1.595 BF
  58 Shortcut Layer: 55
  59 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256 0.177 BF
  60 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512 1.595 BF
  61 Shortcut Layer: 58
  62 conv   1024  3 x 3 / 2    26 x  26 x 512   ->    13 x  13 x1024 1.595 BF
  63 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512 0.177 BF
  64 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024 1.595 BF
  65 Shortcut Layer: 62
  66 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512 0.177 BF
  67 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024 1.595 BF
  68 Shortcut Layer: 65
  69 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512 0.177 BF
  70 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024 1.595 BF
  71 Shortcut Layer: 68
  72 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512 0.177 BF
  73 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024 1.595 BF
  74 Shortcut Layer: 71
  75 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512 0.177 BF
  76 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024 1.595 BF
  77 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512 0.177 BF
  78 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024 1.595 BF
  79 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512 0.177 BF
  80 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024 1.595 BF
  81 conv    255  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 255 0.088 BF
  82 yolo
  83 route  79
  84 conv    256  1 x 1 / 1    13 x  13 x 512   ->    13 x  13 x 256 0.044 BF
  85 upsample            2x    13 x  13 x 256   ->    26 x  26 x 256
  86 route  85 61
  87 conv    256  1 x 1 / 1    26 x  26 x 768   ->    26 x  26 x 256 0.266 BF
  88 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512 1.595 BF
  89 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256 0.177 BF
  90 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512 1.595 BF
  91 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256 0.177 BF
  92 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512 1.595 BF
  93 conv    255  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 255 0.177 BF
  94 yolo
  95 route  91
  96 conv    128  1 x 1 / 1    26 x  26 x 256   ->    26 x  26 x 128 0.044 BF
  97 upsample            2x    26 x  26 x 128   ->    52 x  52 x 128
  98 route  97 36
  99 conv    128  1 x 1 / 1    52 x  52 x 384   ->    52 x  52 x 128 0.266 BF
 100 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256 1.595 BF
 101 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128 0.177 BF
 102 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256 1.595 BF
 103 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128 0.177 BF
 104 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256 1.595 BF
 105 conv    255  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 255 0.353 BF
 106 yolo
Total BFLOPS 65.864 
 Allocate additional workspace_size = 52.43 MB 
Loading weights from /home/chao/Desktop/yolov3.weights...
 seen 64 
Done!

 calculation mAP (mean average precision)...
4952
 detections_count = 172409, unique_truth_count = 12032  
class_id = 0, name = aeroplane, ap = 0.01%   	 (TP = 2, FP = 6592) 
class_id = 1, name = bicycle, ap = 89.30%   	 (TP = 294, FP = 124) 
class_id = 2, name = bird, ap = 0.00%   	 (TP = 0, FP = 1689) 
class_id = 3, name = boat, ap = 0.00%   	 (TP = 0, FP = 370) 
class_id = 4, name = bottle, ap = 0.00%   	 (TP = 0, FP = 283) 
class_id = 5, name = bus, ap = 94.80%   	 (TP = 203, FP = 51) 
class_id = 6, name = car, ap = 0.21%   	 (TP = 3, FP = 299) 
class_id = 7, name = cat, ap = 0.00%   	 (TP = 0, FP = 457) 
class_id = 8, name = chair, ap = 0.00%   	 (TP = 0, FP = 357) 
class_id = 9, name = cow, ap = 0.00%   	 (TP = 0, FP = 107) 
class_id = 10, name = diningtable, ap = 0.00%   	 (TP = 0, FP = 9) 
class_id = 11, name = dog, ap = 0.00%   	 (TP = 0, FP = 6) 
class_id = 12, name = horse, ap = 0.00%   	 (TP = 0, FP = 6) 
class_id = 13, name = motorbike, ap = 0.00%   	 (TP = 0, FP = 123) 
class_id = 14, name = person, ap = 0.00%   	 (TP = 1, FP = 479) 
class_id = 15, name = pottedplant, ap = 0.00%   	 (TP = 0, FP = 398) 
class_id = 16, name = sheep, ap = 3.04%   	 (TP = 22, FP = 621) 
class_id = 17, name = sofa, ap = 0.00%   	 (TP = 0, FP = 446) 
class_id = 18, name = train, ap = 0.00%   	 (TP = 0, FP = 315) 
class_id = 19, name = tvmonitor, ap = 0.00%   	 (TP = 0, FP = 289) 
class_id = 20, name = (null), ap = 0.00%   	 (TP = 0, FP = 8) 
class_id = 21, name = (null), ap = 0.00%   	 (TP = 0, FP = 22) 
class_id = 22, name = (null), ap = 0.00%   	 (TP = 0, FP = 1) 
Segmentation fault (core dumped)

**Comment by AlexeyAB** [comment]
@i-chaochen 
Yes, you should use:
`./darknet detector map cfg/coco.data cfg/yolov3.cfg ~/Desktop/yolov3.weights`

instead of 
`./darknet detector map cfg/voc.data cfg/yolov3.cfg ~/Desktop/yolov3.weights`

**Comment by i-chaochen** [comment]
> @i-chaochen
> Yes, you should use:
> `./darknet detector map cfg/coco.data cfg/yolov3.cfg ~/Desktop/yolov3.weights`
> 
> instead of
> `./darknet detector map cfg/voc.data cfg/yolov3.cfg ~/Desktop/yolov3.weights`

Thanks for your reply.

As I said, I am also wondering the map result is is terribly low..... I am using the downloaded yolov3.weight from darknet website. 

But If I used the weight I trained it myself, results will be much better. It something wrong?

for thresh = 0.25, precision = 0.02, recall = 0.04, F1-score = 0.03
for thresh = 0.25, TP = 525, FP = 22235, FN = 11507, average IoU = 1.93 %

IoU threshold = 50 %, used Area-Under-Curve for each unique Recall
mean average precision (mAP@0.50) = 0.023422, or 2.34 %
Total Detection Time: 85.000000 Seconds

**Comment by AlexeyAB** [comment]
Did you use this script  https://github.com/AlexeyAB/darknet/blob/master/scripts/get_coco_dataset.sh  to get MS COCO validation dataset?

**Comment by i-chaochen** [comment]
> @i-chaochen
> 
> Did you use this script https://github.com/AlexeyAB/darknet/blob/master/scripts/get_coco_dataset.sh to get MS COCO validation dataset?

Nope, I used the tutorial from pjeddit darknet on Training YOLO, the VOC data from 2007 to 2012.  
Since it's a detector model, is it should be acceptable for all dataset?

https://github.com/pjreddie/darknet/wiki/YOLO:-Real-Time-Object-Detection

**Comment by AlexeyAB** [comment]
@i-chaochen
> Since it's a detector model, is it should have an "acceptable" map results for all datasets?

Yes, but you should use identical class_id for mAP calculation.
While MS COCO and PASCAL VOC have different class_ids. You should change PASCAL VOC annotations files, changing class_id.

**Comment by i-chaochen** [comment]
> @i-chaochen
> 
> > Since it's a detector model, is it should have an "acceptable" map results for all datasets?
> 
> Yes, but you should use identical class_id for mAP calculation.
> While MS COCO and PASCAL VOC have different class_ids. You should change PASCAL VOC annotations files, changing class_id.

I see! Thank you very much for the explanations!

**Comment by i-chaochen** [comment]
I used the MS COCO script, how do you generate coco_testdev ?  

I cannot run in coco dataset as 
Couldn't open file: coco_testdev

https://github.com/AlexeyAB/darknet/issues/784

I see there is a similar issue as well.

@AlexeyAB

**Comment by i-chaochen** [comment]
I used coco dataset have no problem, but I don't know why I used voc dataset always have class_id problem. 

I have already changed my cfg/voc.data as the the following:

classes= 20
train = /media/backup/VOC_dataset/train.txt
valid = /media/backup/VOC_dataset/2007_test.txt
names = data/voc.names
backup = backup

,and my data/voc.names has 20 class_id as the following:
aeroplane
bicycle
bird
boat
bottle
bus
car
cat
chair
cow
diningtable
dog
horse
motorbike
person
pottedplant
sheep
sofa
train
tvmonitor

**Comment by i-chaochen** [comment]
Based on your tutorial from [calculate mAP on VOC 2007](https://github.com/AlexeyAB/darknet#how-to-train-pascal-voc-data
) I download voc_label_difficult.py at the voc folder, run it and get difficult_2007_test.txt and difficult_2012_val.txt, and I add ```difficult = /media/backup/VOC_dataset/difficult_2007_test.txt``` into the voc.data.

When I calculate mAP by ```./darknet detector map cfg/voc.data cfg/yolov3.cfg ~/Desktop/yolov3.weights```, I still have Segmentation fault (core dumped) as the incorrect class_id.

**Comment by AlexeyAB** [comment]
`cfg/yolov3.cfg` is trained for 80 classes (MS COCO), while `voc.data` is uses Pascal VOC for 20 classes.

Use these files to check the mAP on Pascal VOC:
http://pjreddie.com/media/files/yolo-voc.weights
https://github.com/AlexeyAB/darknet/blob/master/cfg/yolo-voc.cfg

**Comment by i-chaochen** [comment]
> `cfg/yolov3.cfg` is trained for 80 classes (MS COCO), while `voc.data` is uses Pascal VOC for 20 classes.
> 
> Use these files to check the mAP on Pascal VOC:
> http://pjreddie.com/media/files/yolo-voc.weights
> https://github.com/AlexeyAB/darknet/blob/master/cfg/yolo-voc.cfg

I see, thank you indeed for clarifying this. 

I thought yolov3.cfg is a "general" yolo version-3 network topology and yolov3.weight is the relative weight file. Supposing if I need to change another dataset all I need is to change xxx.data file to specify the path of test/train data...It seems not working in this way...

So if I understood correctly, if I need to train a custom dataset, I also need to change yolov3.cfg as well?

**Comment by i-chaochen** [comment]
> `cfg/yolov3.cfg` is trained for 80 classes (MS COCO), while `voc.data` is uses Pascal VOC for 20 classes.
> 
> Use these files to check the mAP on Pascal VOC:
> http://pjreddie.com/media/files/yolo-voc.weights
> https://github.com/AlexeyAB/darknet/blob/master/cfg/yolo-voc.cfg

Thank you very much for the explanation! Yes, I found there is a yolov3-voc.cfg as well. 
Salute!
