### ISSUE TITLE
Error    C1083    Cannot open include file: 'corecrt.h': No such file or directory

### ISSUE THREAD

**Issue by sumith96** [AlexeyAB/darknet#137]
hi,
can you help me out with this error.

![screenshot 10](https://user-images.githubusercontent.com/30292961/28690328-687443f2-7336-11e7-8484-cfb468b76b9d.png)

**Comment by AlexeyAB** [comment]
Hi,

Try to find solution here: https://stackoverflow.com/questions/38290169/cannot-find-corecrt-h-universalcrt-includepath-is-wrong

Try to do:

* (right click on project) -> properties -> C/C++ -> General -> Additional Include Directories, put here:
` C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\;C:\opencv_2.4.9\opencv\build\include;..\..\3rdparty\include;%(AdditionalIncludeDirectories);$(CudaToolkitIncludeDir);$(cudnn)\include`

* (right click on project) -> properties -> Linker -> General -> Additional Library Directories, put here:
`C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt\x64;C:\opencv_2.4.9\opencv\build\x64\vc12\lib;$(CUDA_PATH)lib\$(PlatformName);$(cudnn)\lib\x64;%(AdditionalLibraryDirectories)`

----

Also:

 1. Run Visual Studio Installer.
 2. Select Modify button.
 3. Go to "Individual Components" tab.
 4. Scroll down to "Compilers, build tools and runtimes".
 5. Tick "Windows Universal CRT SDK".
 6. Install.

**Comment by sumith96** [comment]
C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\x64
except this every thing is checked and is present
still getting same errors....could u plz help me out!

**Comment by AlexeyAB** [comment]
@sumith96 

* Did you set Release and x64 to build?
* Did you press Build -> Clean, and then press Build -> Rebuild ?
* Did you set both params as here? https://github.com/AlexeyAB/darknet/issues/136#issuecomment-318465726

1. this
![6014 5](https://user-images.githubusercontent.com/4096485/28688896-3e9f37a4-731c-11e7-8e0a-20217ff001e5.png)

2. and this
![8715 2](https://user-images.githubusercontent.com/4096485/28688973-8e54707a-731c-11e7-8e3c-ad2857b8e419.png)

**Comment by sumith96** [comment]
in target platform only version 8.1 is showing and not 10
i cross checked all other parameters

**Comment by AlexeyAB** [comment]
@sumith96 

What about this?

Also:

>  1. Run Visual Studio Installer.
>  2. Select Modify button.
>  3. Go to "Individual Components" tab.
>  4. Scroll down to "Compilers, build tools and runtimes".
>  5. Tick "Windows Universal CRT SDK".
>  6. Install.

**Comment by sumith96** [comment]
iam not getting individual components option at all
i tried running no gpu file currently the error shows files missing in path ,how to rectify this issue??
![capture](https://user-images.githubusercontent.com/30292961/28857504-a22f0412-7767-11e7-93a1-2df83cc18fda.PNG)

**Comment by AlexeyAB** [comment]
As said here, you should change paths to your OpenCV 2.4.x: https://github.com/AlexeyAB/darknet#how-to-compile

> 1. If you have MSVS 2015, CUDA 8.0 and OpenCV 2.4.9 (with paths: C:\opencv_2.4.9\opencv\build\include & C:\opencv_2.4.9\opencv\build\x64\vc12\lib or vc14\lib), then start MSVS, open build\darknet\darknet.sln, set x64 and Release, and do the: Build -> Build darknet

...

> 3. If you have other version of OpenCV 2.4.x (not 2.4.9) then you should change pathes after \darknet.sln is opened
> 
> 3.1 (right click on project) -> properties -> C/C++ -> General -> Additional Include Directories
> 
> 3.2 (right click on project) -> properties -> Linker -> General -> Additional Library Directories
> 
> 3.3 Open file: \src\yolo.c and change 3 lines to your OpenCV-version - 249 (for 2.4.9), 2413 (for 2.4.13), ... :
> 
> * `#pragma comment(lib, "opencv_core249.lib")`
> * `#pragma comment(lib, "opencv_imgproc249.lib")`
> * `#pragma comment(lib, "opencv_highgui249.lib")`
