### ISSUE TITLE
RE: Calculation of anchors

### ISSUE THREAD

**Issue by JohnWnx** [AlexeyAB/darknet#1370]
For: "recalculate anchors for your dataset for width and height from cfg-file: darknet.exe detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416 then set the same 9 anchors in each of 3 [yolo]-layers in your cfg-file"

I have received the following 9 values for the respective anchors:
![image](https://user-images.githubusercontent.com/40804580/43939182-d6d407e0-9c9a-11e8-864e-dfbb1bdae52d.png)

After changing the three sections in  yolov3.cfg file say:
![image](https://user-images.githubusercontent.com/40804580/43939251-4156a01e-9c9b-11e8-8588-c3242e9219d7.png)

Do I need to retrain the model? or I could just use the weights directly for detection.

Thanks!

**Comment by tkcrown** [comment]
of course you have to retrain.
