### ISSUE TITLE
YoloV3 detection results are worse compared with pjreddie master 

### ISSUE THREAD

**Issue by PIXEVIA** [AlexeyAB/darknet#1375]
Detection results are worse compared with pjreddie master with all tested images using YoloV3 configuration and YoloV3 weights

test image:  http://www.pixevia.com/media/img/items.jpeg

Main (pjreddie) branch results:
![](http://www.pixevia.com/media/img/y3_orig.png)

AlexeyAB branch results:
![](http://www.pixevia.com/media/img/y3_a.png)

width=416
height=416

current darknet branch, command:
~/workspace/darknet3/darknet detect  yolov3.cfg yolov3.weights ~/items.jpeg  -thresh 0.05
bottle: 27%
book: 20%
book: 9%
book: 8%
chair: 99%
bottle: 99%
bottle: 66%
person: 100%

GPU=1
CUDNN=1
OPENCV=0
OPENMP=0
DEBUG=0

current AlexeyAB branch, command:
~/workspace/darkneta/darknet detect  yolov3.cfg yolov3.weights ~/items.jpeg  -thresh 0.05
bench: 12%      (left_x:   57   top_y:  248   width:  708   height:  596)
chair: 95%      (left_x:   71   top_y:  276   width:  535   height:  557)
person: 100%    (left_x:  118   top_y:   58   width:  611   height:  747)
person: 10%     (left_x:  344   top_y:  185   width:  343   height:  591)
bottle: 96%     (left_x:  628   top_y:   96   width:   70   height:  182)
bottle: 87%     (left_x:  703   top_y:  187   width:   45   height:  110)
bottle: 7%      (left_x:  742   top_y:  190   width:   30   height:  102)
bottle: 54%     (left_x:  754   top_y:  191   width:   45   height:  104)
bottle: 22%     (left_x:  780   top_y:  199   width:   33   height:  101)

GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=0
AVX=0
OPENMP=0
LIBSO=0

Cuda compilation tools, release 9.0, V9.0.176
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7

**Comment by AlexeyAB** [comment]
The difference in resize approach: https://github.com/AlexeyAB/darknet/issues/232#issuecomment-336955485
In some cases better the first approach, in other better the second.

In this repository https://github.com/AlexeyAB/darknet do simple change:

* comment this line: https://github.com/AlexeyAB/darknet/blob/3e856ec04ebe3cf072939641ba6cd7871bfefc32/src/detector.c#L1124
* un-comment this line: https://github.com/AlexeyAB/darknet/blob/3e856ec04ebe3cf072939641ba6cd7871bfefc32/src/detector.c#L1125


```

darknet.exe detector test data/coco.data yolov3.cfg yolov3.weights items.jpeg -ext_output -thresh 0.05

chair: 99%      (left_x:   74   top_y:  314   width:  520   height:  534)
person: 100%    (left_x:  131   top_y:   39   width:  579   height:  773)
bottle: 99%     (left_x:  633   top_y:   84   width:   65   height:  205)
bottle: 59%     (left_x:  701   top_y:  184   width:   47   height:  111)
bottle: 26%     (left_x:  753   top_y:  181   width:   51   height:  116)
book: 20%
book: 7%        (left_x:  778   top_y:  187   width:   34   height:  111)
book: 6%        (left_x:  811   top_y:  187   width:   61   height:  113)
```


![predictions](https://user-images.githubusercontent.com/4096485/43956846-5504b41c-9cae-11e8-9f86-8253a17a34b1.jpg)

**Comment by PIXEVIA** [comment]
Thank you!  Now works perfectly:)
With v2 we got very similar results, but with v3 and v3-spp  the results with lower thresholds were much worse. Most likely a neural network should be trained also with the same resize function to achieve better performance.

**Comment by AlexeyAB** [comment]
@PIXEVIA Yes. Because for my datasets the resize() is better than letterbox(), then Training and Detection using resize() give me the best result.
