### ISSUE TITLE
Using non gpu giving no results on COCO Yolo v3

### ISSUE THREAD

**Issue by abhimanyusinghal** [AlexeyAB/darknet#1376]
I Comipled darknet_no_gpu as mentioned in Readme.md

> If you don't have GPU, but have MSVS 2015 and OpenCV 3.0 (with paths: C:\opencv_3.0\opencv\build\include & C:\opencv_3.0\opencv\build\x64\vc14\lib), then start MSVS, open build\darknet\darknet_no_gpu.sln, set x64 and Release, and do the: Build -> Build darknet_no_gpu

Downloaded yolov3 weights from: https://pjreddie.com/media/files/yolov3.weights

Command I am running: 
darknet_no_gpu.exe detector test data/coco.data yolov3.cfg yolov3.weights -i 0 -thresh 0.25 dog.jpg -ext_output

It is not detecting dog. 

I am running a CPU only Machine with 8 GB Ram and i7 Processor.

Objective was to try out if we can use darknet to detect objects using a pre-trained model on a Windows x64 CPU based machine. 

Am I missing something?

**Comment by AlexeyAB** [comment]
I just ran:
`darknet_no_gpu.exe detector test data/coco.data yolov3.cfg yolov3.weights -thresh 0.25 dog.jpg -ext_output`

On Windws 7 x64, Intel CPU Core i7 6700K 4 Cores (8 HT), MSVS 2015, OpenCV 3.4.0

![image](https://user-images.githubusercontent.com/4096485/43960296-43baaa5c-9cba-11e8-8a46-8e20fb286f8a.png)

**Comment by abhimanyusinghal** [comment]
I Switched to OpenCV 3.4.0
Changed Libraries from vc12 to vc14. 
rebuilt darknet_no_gpu

not getting results. Screenshot below: 
![image](https://user-images.githubusercontent.com/5702282/43964250-08098b2a-9cda-11e8-908a-01fefb946ba9.png) 

This is Windows 10 x64 OS.

**Comment by AlexeyAB** [comment]
Try to change this line: https://github.com/AlexeyAB/darknet/blob/3e856ec04ebe3cf072939641ba6cd7871bfefc32/src/gemm.c#L307

to this:
`#if (defined(__AVX__) && defined(__x86_64__))`

**Comment by abhimanyusinghal** [comment]
After changing these Lines: The results are not good. 

![image](https://user-images.githubusercontent.com/5702282/43968457-c349c29c-9ce4-11e8-8e34-0da286abe146.png)

**Comment by abhimanyusinghal** [comment]
On Further Investigation: 

I am getting exception at gemm.c
activate_array_cpu_custom Method. Line No: 650

`__m256i sign256 = _mm256_and_si256(_mm256_castps_si256(src256), all256_sing1); // check sign in 8 x 32-bit floats
`

Exception: 
Unhandled exception at 0x00007FF6D4088738 in darknet_no_gpu.exe: 0xC000001D: Illegal Instruction.

![image](https://user-images.githubusercontent.com/5702282/43980821-2f0c13ae-9d0d-11e8-96bb-369bf932058f.png)

System Summary: 

OS Name	Microsoft Windows 10 Enterprise
Version	10.0.17134 Build 17134
System Manufacturer	LENOVO
System Model	34601F0
System Type	x64-based PC
Processor	Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz, 2001 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	LENOVO G6ET96WW (2.56 ), 29-04-2013
SMBIOS Version	2.7
Embedded Controller Version	1.03
BIOS Mode	Legacy
Secure Boot State	Unsupported
Hardware Abstraction Layer	Version = "10.0.17134.1"
Installed Physical Memory (RAM)	8.00 GB
Total Physical Memory	7.70 GB
Available Physical Memory	1.59 GB
Total Virtual Memory	13.9 GB
Available Virtual Memory	4.64 GB
Page File Space	6.23 GB
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Device Encryption Support	Reasons for failed automatic device encryption: PCR7 binding is not supported, Hardware Security Test Interface failed and device is not InstantGo, Un-allowed DMA capable bus/device(s) detected
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

**Comment by abhimanyusinghal** [comment]
So if I make the change as follows: 

Uncommnet Line: 832 and Comment Line 833 in convolutional_layer.c 
It works on my system. 

```
    activate_array(l.output, m*n*l.batch, l.activation);
    //activate_array_cpu_custom(l.output, m*n*l.batch, l.activation);
```

But I think this will essentially undo someof your recent changes related to performance optimziation for CPU.

**Comment by AlexeyAB** [comment]
@abhimanyusinghal Thanks. I fixed it.

**Comment by abhimanyusinghal** [comment]
@AlexeyAB Please point me to the commit. I will also verify on my system.

**Comment by AlexeyAB** [comment]
@abhimanyusinghal Just use last commit.

There are several fixes:
* https://github.com/AlexeyAB/darknet/commit/b1dddf02ccf8dcfaadee4e8a5ed8726725ec1b93
* https://github.com/AlexeyAB/darknet/commit/f92b20580a21663c5db9eb8608f8cabd7adbeb10
* https://github.com/AlexeyAB/darknet/commit/e5484891825a4a07cc49a8768d019987a017116e
