### ISSUE TITLE
./src/gemm.c:457:18: error: incompatible types when initializing type

### ISSUE THREAD

**Issue by deimsdeutsch** [AlexeyAB/darknet#1377]
root@localhost darknet]# make
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -ffp-contract=fast -mavx -msse4.1 -msse4a -Ofast -DOPENCV -fopenmp -DGPU -DCUDNN -I/usr/local/cudnn/include -c ./src/gemm.c -o obj/gemm.o
./src/gemm.c: In function ‘count256’:
./src/gemm.c:457:5: warning: implicit declaration of function ‘_mm256_and_si256’ [-Wimplicit-function-declaration]
     __m256i lo = _mm256_and_si256(v, low_mask);
     ^
./src/gemm.c:457:18: error: incompatible types when initializing type ‘__m256i’ using type ‘int’
     __m256i lo = _mm256_and_si256(v, low_mask);
                  ^
compilation terminated due to -Wfatal-errors.
make: *** [obj/gemm.o] Error 1

Took checkout 2 mins back.

**Comment by AlexeyAB** [comment]
What can you get by this command? 
`gcc --version`

Looks like you use very old compiler - so gcc did not properly define this symbol _mm256_and_si256(). It uses `_mm_and_si256()` instead of `_mm256_and_si256()`

* Or update your GCC: 
```
sudo apt-get update
sudo apt-get install gcc-4.9 g++-4.9
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
```

* Or just compile with `AVX=0` in the Makefile.

**Comment by deimsdeutsch** [comment]
GCC Version 4.9
Unable to compile using AVX for some reason. 
```
[root@localhost darknet]# make
g++  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -ffp-contract=fast -mavx -msse4.1 -msse4a -Ofast -DOPENCV -fopenmp -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/http_stream.cpp -o obj/http_stream.o
./src/http_stream.cpp: In member function ‘bool MJPGWriter::write(const cv::Mat&)’:
./src/http_stream.cpp:184:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 if (n < outlen)
                       ^
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -ffp-contract=fast -mavx -msse4.1 -msse4a -Ofast -DOPENCV -fopenmp -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/gemm.c -o obj/gemm.o
./src/gemm.c: In function ‘popcnt256_custom’:
./src/gemm.c:469:15: error: request for member ‘m256i_i64’ in something not a structure or union
     return val.m256i_i64[0] +
               ^
compilation terminated due to -Wfatal-errors.
make: *** [obj/gemm.o] Error 1
```


Changed AVX = 0 
and now its working !

**Comment by deimsdeutsch** [comment]
@AlexeyAB 
Not working !

make
g++  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -ffp-contract=fast -mavx -msse4.1 -msse4a -Ofast -DOPENCV -fopenmp -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/http_stream.cpp -o obj/http_stream.o
./src/http_stream.cpp: In member function ‘bool MJPGWriter::write(const cv::Mat&)’:
./src/http_stream.cpp:184:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 if (n < outlen)
                     ~~^~~~~~~~
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -ffp-contract=fast -mavx -msse4.1 -msse4a -Ofast -DOPENCV -fopenmp -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/gemm.c -o obj/gemm.o
./src/gemm.c: In function ‘popcnt256_custom’:
./src/gemm.c:469:15: error: request for member ‘m256i_i64’ in something not a structure or union
     return val.m256i_i64[0] +
               ^
compilation terminated due to -Wfatal-errors.
make: *** [obj/gemm.o] Error 1

**Comment by AlexeyAB** [comment]
I made some fixes. Try to update your code from GitHub and recompile.

**Comment by deimsdeutsch** [comment]
@AlexeyAB

Working !

Please don't use newer version of GCC because Redhat/Centos are not shipped with newer GCC until they are stable. Latest version for GCC on Centos 7 is (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
