### ISSUE TITLE
Non labeled objects

### ISSUE THREAD

**Issue by anguoyang** [AlexeyAB/darknet#1384]
@AlexeyAB , I found some error detection: I trained the model with goods(drink, chocolate, etc.) but it could detect faces.
and I found this:
 "desirable that your training dataset include images with non-labeled objects that you do not want to detect - negative samples without bounded box (empty .txt files) - use as many images of negative samples as there are images with objects"

So I decide to add some non-labeled images with empty .txt files(same name with the images), but when I train it I got these errors:
"Can't open label file. (This can be normal only if you use MSCOCO)"

Thank you.

**Comment by AlexeyAB** [comment]
@anguoyang 

> @AlexeyAB , I found some error detection: I trained the model with goods(drink, chocolate, etc.) but it could detect faces.
> and I found this:
>  "desirable that your training dataset include images with non-labeled objects that you do not want to detect - negative samples without bounded box **(empty .txt files)** - use as many images of negative samples as there are images with objects"

Check, are there **empty .txt files** for non-labeled images?

**Comment by anguoyang** [comment]
@AlexeyAB thank you, its my mistake
