### ISSUE TITLE
yolov3-spp training

### ISSUE THREAD

**Issue by linghu8812** [AlexeyAB/darknet#1388]
Hi,

When I trained yolov3 with yolov3-spp.cfg, it shows "Layer before convolutional layer must output image.: No error", could you tell me how to fix this error? 
Thank you!

![default](https://user-images.githubusercontent.com/36389436/44036221-da151bb4-9f43-11e8-8d69-96fa1d4f143b.png)

**Comment by AlexeyAB** [comment]
This bug is fixed. Try to update your code from this GitHub.

**Comment by linghu8812** [comment]
OK, thank you!
