### ISSUE TITLE
Visual Studio build Error: C1083 'opencv2/highgui/highgui_c.h': No such file or directory	darknet_no_gpu	  darknet-master\darknet-master\src\yolo.c

### ISSUE THREAD

**Issue by leekwunfung817** [AlexeyAB/darknet#1389]
I did compile the darknet-master\build\darknet\darknet_no_gpu.sln

but the software have these problem, help thx!

**Comment by AlexeyAB** [comment]
* Can you build `darknet.sln` successfully?
* What version of OpenCV do you use?

**Comment by PeterQuinn925** [comment]
I think this is a known problem with OpenCV. Try using OpenCV 3.4.0.

**Comment by AlexeyAB** [comment]
Try to use OpenCV 3.4.0 or 3.3.0

**Comment by SomeO** [comment]
@AlexeyAB ，I also meet the same problem，when building darkenet_no_gpu. And I use OpenCV 3.4.0. After that, I check the directory OPENCV_PATH/include/opencv2/, there  is no folder named highgui . Please help , thanks!

**Comment by AlexeyAB** [comment]
@SomeO Try to use this archive: https://sourceforge.net/projects/opencvlibrary/files/opencv-win/3.3.0/opencv-3.3.0-vc14.exe/download

There is `opencv\build\include\opencv2` directory.

**Comment by leekwunfung817** [comment]
problem fixed. Thanks EveryOne!!!

**Comment by leekwunfung817** [comment]
I have another problem in build the darknet.exe,
I will ask the question in the next post.

**Comment by leekwunfung817** [comment]
I fix all bugs using the following tutorial
https://github.com/AlexeyAB/darknet/issues/1455#issuecomment-416030423
