### ISSUE TITLE
regarding tracking with old gpu

### ISSUE THREAD

**Issue by akde** [AlexeyAB/darknet#1392]
Hi @AlexeyAB 
Thx for this awesome repository. It is a very powerful one bot in terms of speed & accuracy!

I am currently using this (https://github.com/pjreddie/darknet/wiki/YOLO:-Real-Time-Object-Detection) repository with the gpu support and opencv with the following set up:

CUDA version: 8.0, V8.0.61
GPU               : GeForce GT 635M
Ubuntu           : 16.04

however there is no tracking in it!
So my question is that if I start using this repository (https://github.com/AlexeyAB/darknet/) am I going to be able to use the tracking with the GPU support? I am confused because my GPU does NOT support CUDA 9.x

**Comment by AlexeyAB** [comment]
@akde Hi,
* For Detection - Darknet support only CPU and nVidia GPU (CUDA).
* For Tracking after Detection - there can be used CPU or GPU (CUDA)

So you can use or CPU or GPU with CUDA only.

**Comment by akde** [comment]
thx for the reply. 
Can I use detection and all other properties with CUDA 8.0? Or do I need CUDA 9.1?

**Comment by AlexeyAB** [comment]
You can use CUDA 8.0
