### ISSUE TITLE
yolo_cpp_dll_no_gpu crash

### ISSUE THREAD

**Issue by tinohager** [AlexeyAB/darknet#1394]
The current master branch crash on cpu version "detect_image" or "detect_mat", the gpu project works fine.

Microsoft Windows 10 Pro
Intel i7-3770

**Comment by AlexeyAB** [comment]
I can't reproduce this error. It looks like that [Intel CPU i7-3770 (Q2'12)](https://ark.intel.com/products/65719/Intel-Core-i7-3770-Processor-8M-Cache-up-to-3_90-GHz) doesn't support AVX2 instruction that I use for XNOR-net.

Does this error occur for different images/videos with the different resolution?

1. Try to un-comment this line: https://github.com/AlexeyAB/darknet/blob/a9fef1bd66e6b2c40c344c1bdcd33bb1d209461c/src/convolutional_layer.c#L828
and comment this line: https://github.com/AlexeyAB/darknet/blob/a9fef1bd66e6b2c40c344c1bdcd33bb1d209461c/src/convolutional_layer.c#L829

Also un-comment this line: https://github.com/AlexeyAB/darknet/blob/a9fef1bd66e6b2c40c344c1bdcd33bb1d209461c/src/convolutional_layer.c#L682
and comment this line: https://github.com/AlexeyAB/darknet/blob/a9fef1bd66e6b2c40c344c1bdcd33bb1d209461c/src/convolutional_layer.c#L692

then recompile `yolo_cpp_dll_no_gpu.sln`

----

2. If 1. doesn't help, then try to change this line: https://github.com/AlexeyAB/darknet/blob/a9fef1bd66e6b2c40c344c1bdcd33bb1d209461c/src/gemm.c#L307
to this
`#if defined(DONT_USE)`

and recompile `yolo_cpp_dll_no_gpu.sln`

**Comment by tinohager** [comment]
Yes with un/comment the lines it works. Maybe we can add a cpu switch https://stackoverflow.com/questions/6121792/how-to-check-if-a-cpu-supports-the-sse3-instruction-set

**Comment by AlexeyAB** [comment]
There is already function for check some SSE/AVX features, I have not changed it for all new AVX/SSE features yet.

https://github.com/AlexeyAB/darknet/blob/a9fef1bd66e6b2c40c344c1bdcd33bb1d209461c/src/gemm.c#L328-L371

**Comment by AlexeyAB** [comment]
I made some fixes. Try to update your code from GitHub and recompile.

**Comment by tinohager** [comment]
I have update the code but i cannot build the project now. Two errors with _mm256_extract_epi64 and _mm256_extract_epi32.

![intrinsic function, cannot be defined](https://user-images.githubusercontent.com/8215186/44072931-b4ef491a-9f91-11e8-88db-035d83ebc9c1.png)

**Comment by AlexeyAB** [comment]
@tinohager What MSVS version do you use?

**Comment by tinohager** [comment]
I am use Visual Studio 2017

**Comment by AlexeyAB** [comment]
I added another one fix, update your code from GitHub

**Comment by tinohager** [comment]
I have test again and it crash again, the same dll work on an other machine with i7-7820HQ CPU.

**Comment by tinohager** [comment]
Intel i7-3770

**Comment by AlexeyAB** [comment]
I made some fixes, try to update code from GitHub.

Currently I check AVX and AVX2+FMA separately, by using function you referred to: https://github.com/AlexeyAB/darknet/issues/1394#issuecomment-412682331

* AVX: http://www.cpu-world.com/CPUs/Core_i7/Intel-Core%20i7-3770.html

* AVX2 + FMA: http://www.cpu-world.com/CPUs/Core_i7/Intel-Core%20i7%20i7-7820HQ.html

**Comment by tinohager** [comment]
Now it works with Intel i7-3770, Thanks
