### ISSUE TITLE
Error on AVX intrinsics in gemm.c

### ISSUE THREAD

**Issue by joshuajnoble** [AlexeyAB/darknet#1395]
Not sure if this a bug or just something that needs tweaking in my set-up or in the SLN but when I try to compile yolo_cpp_dll.sln with Visual Studio 2017 I get the following errors:

```
1>c:\users\winbase\projects\openstudio\yolo\yolo_output\src\gemm.c(320): error C2169: '_mm256_extract_epi64': intrinsic function, cannot be defined
1>c:\users\winbase\projects\openstudio\yolo\yolo_output\src\gemm.c(324): error C2169: '_mm256_extract_epi32': intrinsic function, cannot be defined
```

Has anyone else encountered this?

**Comment by AlexeyAB** [comment]
Try to comment these lines: https://github.com/AlexeyAB/darknet/blob/f92b20580a21663c5db9eb8608f8cabd7adbeb10/src/gemm.c#L321-L327

Does it help?

**Comment by joshuajnoble** [comment]
After I add "_SCL_SECURE_NO_WARNINGS" to the Preprocessor Definitions, this works fine. Thanks!

**Comment by AlexeyAB** [comment]
Do you mean that there were some warnings without `_SCL_SECURE_NO_WARNINGS` but you can compile, or did you even can't compile?

**Comment by joshuajnoble** [comment]
I mean that without "_SCL_SECURE_NO_WARNINGS" I cannot compile. When I add it to the Preprocessor Definitions, I can, and it works perfectly.
