### ISSUE TITLE
Visual Studio darknet_no_gpu build error

### ISSUE THREAD

**Issue by ShadowMole** [AlexeyAB/darknet#1399]
I am getting Code: "C2057" Description: "expected constant expression" Project: "darknet_no_gpu" File: "gemm.c" Line: "337" when trying to build the project. 

I was able to successfully compile darknet on my other computer, but I don't have a webcam on that one.  This computer does not have a GPU, so I cannot do that.  Can you help me with this error?

**Comment by AlexeyAB** [comment]
* What version of MSVS do you use?

* Try to change this line: https://github.com/AlexeyAB/darknet/blob/e5484891825a4a07cc49a8768d019987a017116e/src/gemm.c#L337
to this
`return a.m256_f32[index];`

**Comment by ShadowMole** [comment]
MSVS 17 and that fix worked thank you.

**Comment by AlexeyAB** [comment]
I added new commit with this fix.
