### ISSUE TITLE
Obects tracking linux

### ISSUE THREAD

**Issue by KAIIUK** [AlexeyAB/darknet#140]
Hi! I would like to ask - can I use your tracker in the Linux version of darknet? If so, how to port it?

**Comment by AlexeyAB** [comment]
Hi, I'll try to make this repo portable for both Windows and Linux in a few days.

**Comment by KAIIUK** [comment]
That would be wonderful.

**Comment by TobiMiller** [comment]
+1 would be cool.

**Comment by lesreaper** [comment]
+1 Definitely what I'm looking for.

**Comment by KAIIUK** [comment]
Thank you very much, it works very cool, but how can I start the tracker with displaying the numbers?(Linux)

**Comment by KAIIUK** [comment]
And immediately the question: did you try to expand the network? What would she be able to process multiple images at the same time? My attempts were not successful, but I know that this is possible.

**Comment by AlexeyAB** [comment]
@KAIIUK @TobiMiller @lesreaper Now this repo supports:
* both Windows and Linux
* both OpenCV 3.x and OpenCV 2.4.13
* both cuDNN 5 and cuDNN 6
* also create SO library on Linux and DLL library on Windows

> Thank you very much, it works very cool, but how can I start the tracker with displaying the numbers?(Linux)

Just change line to `LIBSO=1` in the Makefile: https://github.com/AlexeyAB/darknet/blob/master/Makefile#L6
Then will be created `darknet.so` library and `uselib` runable file, that uses library.
Run `uselib`, then enter filename of video and you will see detection on this video with tracking numbers.


> And immediately the question: did you try to expand the network? What would she be able to process multiple images at the same time? 

If you want to process many images from the txt-file of list of images, then run `uselib` and enter filename of text-file.

For example, you have `air.txt` with such conent:

> air1.jpg
> air2.jpg
> air3.jpg
> air4.jpg

And you will see such results:

![list_of_predictions](https://user-images.githubusercontent.com/4096485/28989927-56cbe0aa-7981-11e7-91fb-4e71a2153972.jpg)

**Comment by KAIIUK** [comment]
Many thanks, but I'm talking about something else. There is a way to "stretch" the network and process several images SIMULTANEOUSLY. In particular, I work with video streams and I'm interested in how to handle several threads, initializing the network only once. Perhaps you know something about this?

**Comment by AlexeyAB** [comment]
@KAIIUK Are you about fuse 4 images into 1 image, process it and get bounded boxes on this 1 image?
To increase network resolution just set `width=832 height=832` int the `yolo-voc.cfg` and use original `yolo-voc.weights`: https://github.com/AlexeyAB/darknet/blob/master/cfg/yolo-voc.cfg#L8
I.e. is the main question how to fuse 4 video streams into 1 video stream?

**Comment by KAIIUK** [comment]
Not really, I was thinking about merging the streams into 1 image and submitting it to the network, but it will not be possible to gain much in performance, because the processing time will increase, plus the time for combining the frames = the fall of the FPS, which is already 18-21 for Gtx-1070. I absolutely know that you can stretch the network itself and submit several images to the input that will be processed at the same time, but I did not succeed. Simply, now it is necessary to run one network on one video stream and after the 3rd initialization the FPS drops to 10, that is, too much resources are expended.

**Comment by KAIIUK** [comment]
I will not take up your time, thank you so much for the help with tracking, we'll wait for an example of how to work with the lstm layer, which was recently added.
