### ISSUE TITLE
How to run darknet with other configs.

### ISSUE THREAD

**Issue by xinvestoriginal** [AlexeyAB/darknet#141]
Hi Alexey, i try run detect darknet with other configs, as: AlexNet, VGG-16, Darknet Reference Model, and it not work. I change  batch and subdivisions params, but not see changes. Yolo-voc, yolo, tiny-yolo-voc works is fine. My command:
darknet.exe detector test data/coco.data yolo.cfg yolo.weights -i 0 -thresh 0.3pause
I changed coco.data on voc.data but do not see the difference.  Please answer, should these configurations work in windows and what am I doing wrong?

**Comment by AlexeyAB** [comment]
@xinvestoriginal Hi, AlexNet, VGG-16, Darknet Reference - these are classification models, but are not detection models. So they can say what objects presence on the image, but can't say where are they located.

Did you use such commands for train and classification when used: AlexNet, VGG-16, Darknet Reference Model, Extraction, CIFAR?

* train: `./darknet classifier train cfg/imagenet1k.data cfg/extraction.cfg`
* detection: `./darknet classifier predict cfg/imagenet1k.data cfg/extraction.cfg extraction.weights data/eagle.jpg`

----

How ot train CIFAR: https://pjreddie.com/darknet/train-cifar/
Other models: https://pjreddie.com/darknet/imagenet/

**Comment by xinvestoriginal** [comment]
Alexey, thank you for the answer, while I was not yet engaged in training the network, but will try.
