### ISSUE TITLE
set argv parameter to vs2015

### ISSUE THREAD

**Issue by minjuprinces1004** [AlexeyAB/darknet#1421]
hi, alexey.

i tried argv parameter to darknet property pages using vs2015.
but, the main function didn't receive the value that i set in command arguments of property pages.
// darknet.c
int main(int argc, char **argv)
{
    - argc always is 1
}

to resolve this problem, i reinstalled VS2015, but the same problem occurred.
maybe, alexey, do you have this problem?

i always thank you.

**Comment by AlexeyAB** [comment]
> i tried argv parameter to darknet property pages using vs2015.

Can you show screenshot where did you try to set argv parameters?

**Comment by minjuprinces1004** [comment]
![argv](https://user-images.githubusercontent.com/30395809/44239661-f9f61880-a1a9-11e8-9af9-458efd376c89.png)

**Comment by AlexeyAB** [comment]
This is strange. It works on my default `darknet.sln` solution.
But I use `$(ProjectDir)\x64` for Workning Directory on this Window.

**Comment by minjuprinces1004** [comment]
i also think it is a problem with my vs2015. thank you for your response and i wil analyze the configuration values of my vs2015.
