### ISSUE TITLE
Results differ between CPU and GPU, and between 64 and 32 bit OS.

### ISSUE THREAD

**Issue by Mikkolehtimaki** [AlexeyAB/darknet#1422]
Hello! I was looking to run your darknet fork on raspberry pi, running raspbian jessie 32 bit OS. The detection results are different than what I get on my 64 bit ubuntu desktop. On my ubuntu machine, the results are also different if built with CPU or GPU. I tabulated the results and compared to pjreddie's darknet repository:

These are run with the tiny yolov3 CFG provided in each repository, which is for coco dataset. Weights are from pjreddie.

## pjreddie repository

Tested with command:

  ./darknet detect cfg/yolov3-tiny.cfg yolov3-tiny.weights data/horses.jpg

### GPU & CUDNN, ubuntu 18.04 64bit

data/horses.jpg: Predicted in 0.010905 seconds.
cow: 56%
cow: 54%
horse: 56%

### CPU, ubuntu 18.04 64bit

data/horses.jpg: Predicted in 0.711414 seconds.
cow: 56%
cow: 54%
horse: 56%

### CPU, raspberry pi, raspbian jessie 32bit

data/horses.jpg: Predicted in 10.482995 seconds.
cow: 56%
cow: 54%
horse: 56%

## AlexeyAB repository

Tested with command:

  ./darknet detector test cfg/coco.data cfg/yolov3-tiny.cfg yolov3-tiny.weights data/horses.jpg

### GPU & CUDNN, ubuntu 18.04 64bit

data/horses.jpg: Predicted in 0.009532 seconds.
horse: 54%
horse: 71%
horse: 32%
horse: 70%
cow: 51%

### CPU, Ubuntu 18.04 64bit

data/horses.jpg: Predicted in 0.706599 seconds.
horse: 26%
horse: 71%
horse: 32%
cow: 56%
horse: 68%

### CPU, raspberry pi, raspbian jessie 32bit

data/horses.jpg: Predicted in 9.483302 seconds.
diningtable: 100%
person: 100%

So I conclude that with GPU the results by your fork are better than the original. But for some reason there is a difference depending on if detection is run with GPU or CPU. Finally, on the raspberry I do not get proper results. pjreddie's repository seems consistent regardless of platform.

I just wanna get the detection on raspberry to match either GPU or CPU on my ubuntu. Do you have any ideas?

**Comment by AlexeyAB** [comment]
@Mikkolehtimaki 
What params did you use in the `Makefile` for Detection on CPU (64bit / 32bit) for my repo?

**Comment by Mikkolehtimaki** [comment]
GPU=0                                                                                                                                                                                                                                 
CUDNN=0                                                                                                                                                                                                                            
CUDNN_HALF=0                                                                                                                                                                                                                              
OPENCV=0                                                                                                                                                                                                                                  
AVX=0                                                                                                                                                                                                                                     
OPENMP=0                                                                                                                                                                                                                                  
LIBSO=1 

DEBUG=0

Didn't use mpi for this test. These are the only lines I edited, so same settings in both. Also no OpenCV installed in the 32bit system so did not include it.

**Comment by AlexeyAB** [comment]
@Mikkolehtimaki 
Did you change anything in the source code?

**Comment by Mikkolehtimaki** [comment]
@AlexeyAB not in your source. `git diff src/` gives nothing. In pjreddie's repo I had to fix the sizeof(size_t) bug to make it run properly on 32bit system.

I did remove the build/ dir before building.

**Comment by AlexeyAB** [comment]
@Mikkolehtimaki 

I think the problem is that: `yolov3-tiny.cfg` and `yolov3-tiny.weights` were changed recently:
* https://github.com/AlexeyAB/darknet/commit/1e866f0063b8c60d56aaf2e6210e051ff0047aba#diff-66f9e6fd2177122c75b040097d86e5f4R175
* https://github.com/pjreddie/darknet/commit/f86901f6177dfc6116360a13cc06ab680e0c86b0#diff-2b0e16f442a744897f1606ff1a0f99d3R175

You should download new `yolov3-tiny.cfg` and `yolov3-tiny.weights` for each of Darknet instance (64/32bit, ...)
* https://pjreddie.com/media/files/yolov3-tiny.weights
* https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov3-tiny.cfg

**Comment by Mikkolehtimaki** [comment]
I checked out latest repositories and downloaded weights. Results in pjreddie's repository are the same as before. Looking at the this one image (data/horses.jpg), results in your repository seemed better before the update. Here are the results in your repository

## AlexeyAB repository, with weights and tiny yolo cfg from latest pjreddie

Tested with command:

  ./darknet detector test cfg/coco.data cfg/yolov3-tiny.cfg yolov3-tiny.weights data/horses.jpg

### GPU & CUDNN, ubuntu 18.04 64bit, no MPI

data/horses.jpg: Predicted in 0.009625 seconds.
horse: 31%
horse: 71%
horse: 54%
horse: 32%
horse: 68%
cow: 39%
horse: 70%
cow: 51%

### CPU, Ubuntu 18.04 64bit, no MPI

data/horses.jpg: Predicted in 0.654682 seconds.
horse: 54%
sheep: 36%
horse: 32%
horse: 71%
cow: 35%
horse: 71%
cow: 49%

### CPU, raspberry pi, raspbian jessie 32bit, without MPI

data/horses.jpg: Predicted in 30.094460 seconds.
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
diningtable: 100%
horse: 32%

### CPU, raspberry pi, raspbian jessie 32bit, with MPI

data/horses.jpg: Predicted in 9.531153 seconds.

(no predictions)

**Comment by Mikkolehtimaki** [comment]
@AlexeyAB Do you have any other ideas I could try?

**Comment by AlexeyAB** [comment]
@Mikkolehtimaki You can try to use older version of this repository (on CPU, raspberry pi, raspbian jessie 32bit, without MPI): https://github.com/AlexeyAB/darknet/archive/81d4688b12702ecede13bbc50993eece57469db3.zip

But use new tiny yolo v3:
https://pjreddie.com/media/files/yolov3-tiny.weights
https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov3-tiny.cfg

Thus we can check, whether there are some issue in the last changes.

**Comment by Mikkolehtimaki** [comment]
@AlexeyAB Nice idea! With the commit you linked the prediction on 32 bit raspbian works correctly:

### CPU, raspberry pi, raspbian jessie 32bit, without MPI

data/horses.jpg: Predicted in 30.322840 seconds.
horse: 31%
horse: 71%
horse: 54%
horse: 32%
horse: 68%
cow: 39%
horse: 70%
cow: 51%

### CPU, raspberry pi, raspbian jessie 32bit, with MPI

data/horses.jpg: Predicted in 9.414913 seconds.
horse: 31%
horse: 71%
horse: 54%
horse: 32%
horse: 68%
cow: 39%
horse: 70%
cow: 51%

And these are same that I get with 64 bit machine on GPU with the latest commit (Latest commit's 64 bit GPU and CPU give slightly different confidences).

Thanks a lot and let me know if you want to me to do any more testing!

**Comment by AlexeyAB** [comment]
@Mikkolehtimaki Thanks! I added some fixes. 
Try to use the latest version of this repo (on CPU, raspberry pi, raspbian jessie 32bit, without MPI).

**Comment by PeterQuinn925** [comment]
I just tried on a Raspi3 and it's not working for me. I had it working previously. I did a clean git clone and edited the Makefile set the options =0 for all except LIBSO and get:

./darknet detect cfg/yolov3.cfg yolov3.weights data/dog.jpg
.
.
.
 105 conv    255  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 255 0.353 BF
 106 yolo
Total BFLOPS 65.864
Loading weights from yolov3.weights...
 seen 64
Done!
Killed

Any idea what's going wrong?

**Comment by AlexeyAB** [comment]
@PeterQuinn925 Does this version work on Raspi3? https://github.com/AlexeyAB/darknet/archive/81d4688b12702ecede13bbc50993eece57469db3.zip

**Comment by AlexeyAB** [comment]
@PeterQuinn925 This is strange, because there was successfull test on Rasberry pi3B+: https://github.com/AlexeyAB/darknet/issues/942#issuecomment-393731666

**Comment by PeterQuinn925** [comment]
Looks like a memory issue.  Raspberry PI can allocate memory to GPU or CPU. I had 512MB allocated to GPU. Setting GPU memory to 64MB, it runs, but I get a seg fault:
Loading weights from yolov3.weights...
 seen 64
Done!
data/dog.jpg: Predicted in 401.951358 seconds.
Segmentation fault

I have been mucking around with VC4CL and that may have screwed something up. I'm going to clean things up and try again. I bet it's something I've done and not anything with this code.

Details on debugging in case anyone else runs into this:
Ran it with gdb  and I get - 
Program terminated with signal SIGKILL, Killed.
The program no longer exists.

/var/log/syslog shows:
Aug 21 14:07:39 raspi3 kernel: [362553.711626] Out of memory: Kill process 26893 (darknet) score 698 or sacrifice child
Aug 21 14:07:39 raspi3 kernel: [362553.711638] Killed process 26893 (darknet) total-vm:1304704kB, anon-rss:363660kB, file-rss:144kB, shmem-rss:0kB
Aug 21 14:07:39 raspi3 kernel: [362553.806010] oom_reaper: reaped process 26893 (darknet), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

**Comment by PeterQuinn925** [comment]
Ok. My mistake - I was running regular Yolov3 not tiny-v3. Running with tiny-v3 works fine. 
data/horses.jpg: Predicted in 35.154935 seconds.
horse: 31%
horse: 71%
horse: 54%
horse: 32%
horse: 68%
cow: 39%
horse: 70%
cow: 51%
Sorry for the confusion.

**Comment by Mikkolehtimaki** [comment]
I can also confirm the latest commit working on my raspberry, thanks!

**Comment by ljh14** [comment]
> Ok. My mistake - I was running regular Yolov3 not tiny-v3. Running with tiny-v3 works fine.
> data/horses.jpg:
> OPENMP=0
> Predicted in 35.154935 seconds.
> horse: 31%
> horse: 71%
> horse: 54%
> horse: 32%
> horse: 68%
> cow: 39%
> horse: 70%
> cow: 51%
> OPENMP=1
> same results,  10.2 seconds
> Sorry for the confusion.

I was running tiny-v3 and got segmentation fault, and that's why ? I use pjreddie's darknet to train. My model works well on my server(also Linux os).

**Comment by AlexeyAB** [comment]
@ljh14 

> I was running tiny-v3 and got segmentation fault, and that's why ? **I use pjreddie's darknet to train.** My model works well on my server(also Linux os).

Do you use https://github.com/AlexeyAB/darknet or https://github.com/pjreddie/darknet for Detection?

What command do you use?

What parameters do you use in the Makefile?
