### ISSUE TITLE
compile gemm.c [c2a8cc2 ] error in gcc 

### ISSUE THREAD

**Issue by hujunyao** [AlexeyAB/darknet#1423]
./src/gemm.c: In function ‘count256’:
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx2intrin.h:581:1: error: inlining failed in call to always_inline ‘_mm256_sad_epu8’: target specific option mismatch
 _mm256_sad_epu8 (__m256i __A, __m256i __B)

ubuntu 16.04

**Comment by AlexeyAB** [comment]
* Do you use the latest commit from this repo?
* Did you change anything in the Makefile?
* What GCC version do you use? `gcc --version`

**Comment by hujunyao** [comment]
it is my fault. i forget to change makefile  to  CFLAGS+= -ffp-contract=fast -mavx -mavx2 -msse3 -msse4.1 -msse4.2 -msse4a
