### ISSUE TITLE
Provide data and names when using Dll

### ISSUE THREAD

**Issue by abhimanyusinghal** [AlexeyAB/darknet#1424]
Quick Question: 

How do you provide custom obj.data and .names file when using Windows DLL. Could not find in Readme.md

Thanks
Abhimanyu

**Comment by AlexeyAB** [comment]
Compile `yolo_cpp_dll.sln` and `yolo_console_dll.sln` then run:
`yolo_console_dll.exe data/coco.names cfg/yolov3.cfg yolov3.weights test.mp4`

there is used obj.names file rather than obj.data.
