### ISSUE TITLE
Training my network again after adding more data

### ISSUE THREAD

**Issue by amankagarwal** [AlexeyAB/darknet#1425]
So I already have a suitable `yolo-obj_2000.weights` file which does a decent job detecting the 2 classes it is supposed too. I have about 100 pictures more now, of the same two classes, which I want to add to my dataset and train again. Is there a workaround from training from scratch?

**Comment by AlexeyAB** [comment]
You can continue training from `yolo-obj_2000.weights` with old+new images.
