### ISSUE TITLE
Training in higher resolution than testing

### ISSUE THREAD

**Issue by mathieuorhan** [AlexeyAB/darknet#1427]
Hi @AlexeyAB,

in your [readme](https://github.com/AlexeyAB/darknet#how-to-improve-object-detection) your say that using higher resolution improves accuracy. 
I have 1024x720 images to train on, but in practice the resolution is 640x480. Should I train with 1024x720 or 640x480 ?

Thank you for your work on Darknet and YOLO

**Comment by mathieuorhan** [comment]
Thank you a lot for your quick reply @AlexeyAB 

Yes, to clarify, the dataset I use is public, mostly in 1024x720, but the purpose of the detector is to be embedded in a car where the resolution is lower (640x480). For now, I was training and testing with a 640x480 network.

This rule is a bit obscure to me, could you explain me a bit what are the variables  and where this rule comes from ?

**Comment by AlexeyAB** [comment]
All modern Convolutional Neural Network are not scale invariance.
So relative objects size should be the almost same during Training and Detection.

-----

* train_network_width - `width` in cfg file during training
* detection_network_width  - `width` in cfg file during detection

* train_obj_width - `width` of object in pixels during training
* detection_obj_width - `width` of object in pixels during detection

* train_image_width - `width` of image in pixels during training
* detection_image_width- `width` of image in pixels during detection

**Comment by mathieuorhan** [comment]
Thank you, I get it. In my case as the ratio obj_width/image_width is quite the same in both training and detection, width in both config files should be equal : keeping 640x480 for both is the best ?
