### ISSUE TITLE
memset redefinition

### ISSUE THREAD

**Issue by kli017** [AlexeyAB/darknet#1428]
Error 2520 error C2373: 'memset' : redefinition; different type modifiersC:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\string.h
please help

**Comment by AlexeyAB** [comment]
* What MSVS version do you use?
* Do you try to compile `darknet.sln` or `darknet_no_gpu.sln` or something else?
* What OpenCV version do you use?
* Can you show screenshot of this error?

**Comment by kli017** [comment]
Thank you for the reply!
I was using vs2013 with update 5
I was trying to compile darknet.sln 
My OpenCV version is3.1
I have compiled no_gpu successfully in the same env on other laptop  but meet this error on my GPU Machine.
I will update a screenshot later
Thanks

**Comment by kli017** [comment]
@AlexeyAB 
![image](https://user-images.githubusercontent.com/14877573/44274560-04311900-a275-11e8-8c7d-a92c7a1e9f94.png)

**Comment by AlexeyAB** [comment]
Try to build **x64 and Release**
Did you change anything inside darknet.sln?

**Comment by kli017** [comment]
yes I changed cuda version  to 8, platform to win10  , PlatformToolset to v120 and added opencv3.1 include and lib to project

**Comment by kli017** [comment]
@build with x64 Release succeed

**Comment by AlexeyAB** [comment]
> PlatformToolset to v120 

Also Darknet perhaps doesn't support MSVS2013 (v120) propertly. Try to use v140.

In the MSVS (v140) memset is in the `vcruntime_string.h` rather than `string.h`

https://github.com/AlexeyAB/darknet#requires

> Requires:
> Linux GCC>=4.9 or Windows MS Visual Studio 2015 (v140): https://go.microsoft.com/fwlink/?LinkId=532606&clcid=0x409 (or offline ISO image)
