### ISSUE TITLE
Annotating obscured objects

### ISSUE THREAD

**Issue by yashkotadia** [AlexeyAB/darknet#1435]
I am having doubts regarding annotating objects which are high obscured. Consider the case given below.

Person-0
![image](https://user-images.githubusercontent.com/22071530/44258256-0ae76e00-a22c-11e8-9ead-8c9c3677b71b.png)

Person-1
![image](https://user-images.githubusercontent.com/22071530/44258320-31a5a480-a22c-11e8-8ec9-3982865e033f.png)

As it can be seen, Person-0 obscures Person-1 such that the center of the bounding box of 1 lies upon 0. Would this lead to confusing the model? How should I annotate in such cases?

**Comment by AlexeyAB** [comment]
> Would this lead to confusing the model? 

No.

> How should I annotate in such cases?

Use such a box, that you want to see during detection.

**Comment by yashkotadia** [comment]
@AlexeyAB Thanks
