### ISSUE TITLE
General questions to train own model

### ISSUE THREAD

**Issue by TobiMiller** [AlexeyAB/darknet#144]
Hey,

thanks for your documentation about training the NN.  
i can compile with cuda on linux (orig darknet master repo) and get it runnning at realtime with the "yolo.weights".

Now i want to train just one object. i have only 50 pictures with around 20 times the same object in each. i created some bounding boxes with an tool. it is training actually. 

my question: how fast should it train with an 770 (~1500cuda cores). one iteration takes ~15sec. is it definitly running on gpu? my "avg" is ~12.0 after 1700 iterations. is my dataset too bad or do i need more pictures?

are there more documentations like yours about train a model or use darknet? All i find is not really good documented about "what happens". i mean. on the darknet website is a cfg file for a sample training but i dont know what it does. i feel a little bit helpless with darknet. 

hope somebody can gimme some tricks/tips

best regards

**Comment by AlexeyAB** [comment]
Hi,
Yes, 15 sec per iteration is good. If you want to speedup training, change widht=416 height=416 random=0 in your cfg, but it will reduce precision at 1-3%.
I have not seen more detailed documentation - how to train Yolo.

You should have ~2000 images per class, and should train ~2000 iterations per class. Your images shouldn't be less than 416x416, and objects shouldn't be too small.

Try to get IoU for your obj_2000.weights: https://github.com/AlexeyAB/darknet#when-should-i-stop-training

**Comment by TobiMiller** [comment]
@AlexeyAB Thanks a lot! i have just 50 images with 25 boundingboxes in each. and the bounding boxes are very small sometimes :/
