### ISSUE TITLE
Visual Studio 2017 build Error MSB6003: The specified task executable "cl.exe" could not be run. The system cannot find the file specified. When build darknet.exe from darknet.sln. 

### ISSUE THREAD

**Issue by leekwunfung817** [AlexeyAB/darknet#1442]
When build **darknet.exe** from **darknet.sln**, I have only 1 bug to solve.
I am using Visual Studio 2017 and OpenCV 3.3.0.

Path:
- Not found file: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\BuildCustomizations\cl.exe
- Build Source: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\BuildCustomizations\CUDA 9.0.targets

I don't understand the purpose of **cl.exe**
1. What is this? 
2. What matter it is? 
3. How to get it or install it?

I don't understand the purpose of **CUDA 9.0.targets**
1. Is that related to cuda or visual studio version?
2. What is this? 

![image](https://user-images.githubusercontent.com/18736700/44304218-2071aa80-a388-11e8-80cf-e55c7eadfac7.png)

Python Environments:
**Anaconda 5.2.0 (3.6, 64-bit)**

Error Information:
Error	**MSB6003**	

The specified task executable "**cl.exe**" could not be run. 
The system cannot find the file specified	

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\BuildCustomizations	

**CUDA 9.0.targets Line	428	Build**

**Comment by AlexeyAB** [comment]
* Try to build x64 & Release
* Do you set check for CUDA 9.1 in the: \darknet.sln -> (right click on project) -> Build Dependecies ?
* What CUDA version do you use?
* Try this: https://stackoverflow.com/questions/8125826/error-compiling-cuda-from-command-prompt

**Comment by leekwunfung817** [comment]
**1. Try to build x64 & Release**
- I have been try. The above method is not working. The Error is the same.
- Thank you that you tell me build in x64


**2. Do you set check for CUDA 9.1 in the: \darknet.sln -> (right click on project) -> Build Dependecies ?
The CUDA 9.1 have been set.**
- Thank you that you tell me the CUDA 9.1 and Build Dependecies
- I have been try. The above method is not working. The Error is the same.

MSB6003	The specified task executable "cl.exe" could not be run. The system cannot find the file specified	darknet	1	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\BuildCustomizations	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\BuildCustomizations\CUDA 9.1.targets	428	Build	

**3. What CUDA version do you use?**
- CUDA 9.0

4. Try this: https://stackoverflow.com/questions/8125826/error-compiling-cuda-from-command-prompt
- I have no cl.exe in my whole C drive

![image](https://user-images.githubusercontent.com/18736700/44304443-8fea9880-a38e-11e8-9e8c-0a97dc8bd9da.png)

**Comment by AlexeyAB** [comment]
* Can you build `darknet_no_gpu.sln` successfully?

* What is the path to your Darknet directory?

* Visual Studio 2017 doesn't install C++ by default. You have to rerun the setup, select Modify and then check Programming Language -> C++
(Then you can also run vcvars32.bat from there to set up your environment.)

* It should be somewhere like there: `C:\Program Files (x86)\Microsoft Visual Studio 15.0\VC\bin\cl.exe`

**Comment by koutini** [comment]
Hello, thanks for the tutorial. i get 11 errors with the same description : 
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3721	The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\bin\nvcc.exe" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_75,code=\"sm_75,compute_75\" --use-local-env --cl-version 2015 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64"  -IC:\opencv_3.0\opencv\build\include\opencv2 -IC:\opencv_3.0\opencv\build\include\opencv -IC:\opencv_3.0\opencv\build\include -I..\..\include -I..\..\3rdparty\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\include" -I\include -I\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static     -DOPENCV -DCUDNN -D_TIMESPEC_DEFINED -D_SCL_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -D_CRT_RAND_S -DGPU -DWIN32 -DNDEBUG -D_CONSOLE -D_LIB -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /FS /Zi  /MD " -o x64\Release\convolutional_kernels.cu.obj "C:\Users\assus\darknet\src\convolutional_kernels.cu"" exited with code 1.	darknet	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations\CUDA 8.0.targets	689	


can you help me please ??

**Comment by AlexeyAB** [comment]
@koutini Try to compile darknet by using Cmake.

**Comment by koutini** [comment]
Hello,Thank you so much your answer i really need help;
i try cmake on my Makefile it's work but i don't get darknet.exe
What should I do ??

**Comment by AlexeyAB** [comment]
@koutini 

* Rename this file to cmd-file: [run_cmake.cmd.txt](https://github.com/AlexeyAB/darknet/files/2947632/run_cmake.cmd.txt)
* Run `run_cmake.cmd`
* Press Configure
* Set `MSVS 15` or 17 (and `x64` in the **Optional platform for generator**)
* Press Finish
* Press Generate
* Press Open Project
* Set Release in the opened MSVS
* in the MSVS press: Build -> Build solution

**Comment by koutini** [comment]
i get this error : project file invalid   Cmake -gui what i set in "where is the code source" ??

**Comment by koutini** [comment]
now i get one error : Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3191	Unable to create directory "darknet.dir\Release\C:\Users\assus\darknet\src\". The given path's format is not supported.	darknet	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations\CUDA 8.0.targets	420

**Comment by AlexeyAB** [comment]
@koutini Can you show fullscreen screenshot of this error?

**Comment by koutini** [comment]
![image](https://user-images.githubusercontent.com/48357797/54060184-0e5c3a00-41fc-11e9-8cc5-83f7f8e700bf.png)

**Comment by AlexeyAB** [comment]
@koutini Thanks! 

* What MSVS version do you use?
* And what CUDA version do you use?

**Comment by koutini** [comment]
VS 2015 and cuda 8.0

**Comment by AlexeyAB** [comment]
@koutini 
It seems you have installed MSVS after CUDA. You MSVS doesn't have nsight plugin as I see on screenshot.

Try to reinstall CUDA 8.0, or **better install CUDA 10.0** https://developer.nvidia.com/cuda-downloads

**Comment by koutini** [comment]
![image](https://user-images.githubusercontent.com/48357797/54061324-a5c38c00-4200-11e9-901a-0652ccecbe1b.png)
i have  nsight and yes update MSVS after CUDA

**Comment by koutini** [comment]
okey thank you so much i well try to use CUDA10

**Comment by koutini** [comment]
![image](https://user-images.githubusercontent.com/48357797/54061954-91cd5980-4203-11e9-9ecb-af0abc89e94e.png)
i stell use my cuda version and nsight  existe in VS2015 but i get the same error

**Comment by koutini** [comment]
![image](https://user-images.githubusercontent.com/48357797/54077547-3ca04f00-42ba-11e9-8380-6d0bb9f6a336.png)
hello , now i try with CUDA10 and i get this error

**Comment by koutini** [comment]
it's work thank you so much  for the add
