### ISSUE TITLE
Unable to load custom weights

### ISSUE THREAD

**Issue by alpexjava** [AlexeyAB/darknet#1445]
Hi Alexey.
Step1. I have successfully compiled (forked 28-Jun-2018):
darknet.exe, 
darknet_no_gpu.exe, 
yolo_cpp_dll.dll,
yolo_cpp_dll_no_cudnn.dll,
yolo_cpp_dll_no_gpu.dll

Step2. I have successfully trained 2 classes custom dataset for YoloV3 and YoloV3_Tiny:
yolov3_tiny_RF_24800.weights (mAP = 0.6270, and 0.7694 for these 2 classes)
yolov3_RF_8400.weights (mAP = 0.7844, and 0.7840 for these 2 classes).

Step3. I can successfully  detect objects using EXEs and DLLs from step1 loading your original weights and configs (it confirms that EXEs and DLLs compiled well)

Step4. I can successfully detect CUSTOM objects using EXEs loading CUSTOM trained weights.

Step5. I can  NOT Load CUSTOM weights using DLLs from Step1.

Please advise.

Thank you.
Alexei P.

**Comment by AlexeyAB** [comment]
@alpexjava Hi,

> Step5. I can NOT Load CUSTOM weights using DLLs from Step1.

* What is the error?
* What do you do for it?
* Can you compile and run successfully `yolo_console_dll.sln`? 
`yolo_console_dll.exe data/coco.names yolov3.cfg yolov3.weights test.mp4`

**Comment by AlexeyAB** [comment]
1. You should build `yolo_cpp_dll.sln` with OpenCV:

`yolo_cpp_dll.sln` -> (right click on project) -> properties -> C/C++ -> Preprocessor -> Preprocessor Definitions, and add here: `OPENCV;`

2. Also check paths to your OpenCV:

* `yolo_cpp_dll.sln` -> (right click on project) -> properties -> C/C++ -> General -> Additional Include Directories: C:\opencv_3.3\opencv\build\include

* `yolo_cpp_dll.sln` -> (right click on project) -> properties -> Linker -> General -> Additional Library Directories: C:\opencv_3.3\opencv\build\x64\vc14\lib


----

3. Does this function work?
```c#
         [DllImport(YoloLibraryName, EntryPoint = "detect_image")]
        private static extern int DetectImage(string filename, ref BboxContainer container);
```

**Comment by alpexjava** [comment]
Alexey, you confused me a little bit.
As mentioned don't need yolo_console_dll.exe
1. And i've compiled yolo_cpp_dll.sln and as result i have a few flavours if it: yolo_cpp_dll.dll, yolo_cpp_dll_no_cudnn.dll and yolo_cpp_dll_no_gpu.dll.

2.
Does this function work?
         [DllImport(YoloLibraryName, EntryPoint = "detect_image")]
        private static extern int DetectImage(string filename, ref BboxContainer container);

i didn't test/check the function, but i use public bbox_t[] Detect(byte[] imageData) function.
and it DOES work.
BUT
It works with original weights/configs only. (please see the table)
AND 
crashes with custom trained weights/configs
![capture3](https://user-images.githubusercontent.com/3071250/44309518-3e342380-a40b-11e8-8647-b9289ee7a747.PNG)

**Comment by alpexjava** [comment]
At the same time custom weights / configs work perfectly with darknet.exe i compiled as well (please see table above)

**Comment by AlexeyAB** [comment]
Can you share your cfg-file? Compress it and attach to your message.

**Comment by alpexjava** [comment]
Sure. Please take a glance at (attached).
[DarknetY3_2classesConfigsAlexeiP.zip](https://github.com/AlexeyAB/darknet/files/2300387/DarknetY3_2classesConfigsAlexeiP.zip)

**Comment by alpexjava** [comment]
Sorry, AlexeyAB :(

Silly me !! It was my fault. I copied and renamed wrong CFGs files and thought it was from trained scope. Yes, you're right - the old configs processed for 80 classes instead for 2 as expected. I just replaced wrong with REAL CFGs i trained - and everything works now brilliantly! 

I appreciate  your time, patience and efforts you spent. Thank you again.

Regards,
Alexei P.
