### ISSUE TITLE
Can We Use Pre-Train Weights and add new classes to it.

### ISSUE THREAD

**Issue by syedmustafa54** [AlexeyAB/darknet#1450]
I have Trained 6 classes and got yolo_5000.weights file.
Now I wanted to add 4 more new classes to my existing classes instead of going and retraining my all my classes (10 classes ) can we do something to reuse the pre-train models or any alternative.
Any help from anyone would be useful for me and for new yolo users.
Because I have searched a lot even seen yolo doc but found something call transfer learning but don't know how to implement it because new to yolo.

**Comment by silvernine209** [comment]
You have to retrain your weights if number of classes changed.
What command did you use to train for 6 classes?
You just follow Alexey's instructions and update number of filters and classes in `.names`` .data`` .cfg` files. Then just use your` yolo_5000.weights` instead of `darknet53.conv.74`

**Comment by syedmustafa54** [comment]
@silvernine209 
Thank's for the quick response,
 I use this command 
```
./darknet detector train data/obj.data yolo-obj.cfg darknet53.conv.74
```
so if i use this will this command speed up the process in traning 
```
./darknet detector train data/obj.data yolo-obj.cfg yolo_5000.weights
```

Because  I am getting 5 to 8 new products (to train) every day so what do you suggest me to do.

**Comment by silvernine209** [comment]
@syedmustafa54 AlexeyAB will tell you that you need to retrain when number of classes change. I would update `obj.data`  and `yolo-obj.cfg` with new classes and just use  `darknet53.conv.74` to train again. If you want to expedite training, you can do fine tuning instead of transfer learning. 
By default, AlexeyAB's repo will make your model to perform transfer learning, you can do fine-tuning by modifying `yolo-obj.cfg`, and this information is covered in AlexeyAB's repo as well.

**Comment by syedmustafa54** [comment]
Hi @AlexeyAB and @silvernine209  
To be more clear Please say "Yes" or "No" here is my Problem 
I have trained a model of 10k products (Classes) and got yolo_5000000.weights now 
now I am getting 2 to 5 new Products per day I want to add this products to my trained data so is this possible or not 
If Possible Yes:-How
If Not Possible No:-Why

**Comment by AlexeyAB** [comment]
@syedmustafa54 

If your cfg-file is based on `yolov3.cfg` then do:

1. `./darknet partial yolo.cfg yolo_5000000.weights yolo.conv.81 81`

2. Change `classes=` and `filters=` in 3 places in your `yolo.cfg`-file, also change `obj.data` and `obj.names`

3. Train by using command:
`./darknet detector train obj.data yolo.cfg yolo.conv.81`

Training may be will go faster than by using `darknet53.conv.74`

**Comment by syedmustafa54** [comment]
@AlexeyAB 
Thank's for the quick response, Alexey
So no one tried it and the answer is "No" But I will give a try to it and reply 

I Was thinking instead of retraining and making it 1 weight file I will train new models separate like yolo_12kProducts.weights and yolo_1kProducts.weights 
   
Is there any way to use more than one weight for prediction for example 
`./darknet detect cfg/yolov3.cfg yolo_12kProducts.weights yolo_1kProducts.weights data/dog.jp`
So this can Solve My Problem Or do you have any other Idea better than this

**Comment by AlexeyAB** [comment]
> Is there any way to use more than one weight for prediction for example

No.


The best way is: https://github.com/AlexeyAB/darknet/issues/1450#issuecomment-414445651

**Comment by syedmustafa54** [comment]
Hi @AlexeyAB 
# Now I am getting Segmentation fault (core dumped)
`4: 2.375307, 398.732697 avg loss, 0.001000 rate, 2.092843 seconds, 256 images
Loaded: 0.000042 seconds
Cannot load image "ata/obj/ashirvad_006.jpg"
Region 82 Avg IOU: 0.564517, Class: 0.456497, Obj: 0.007656, No Obj: 0.000072, .5R: 0.750000, .75R: 0.250000,  count: 4
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.613791, Class: 0.375657, Obj: 0.007017, No Obj: 0.000060, .5R: 0.750000, .75R: 0.250000,  count: 4
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.499639, Class: 0.507193, Obj: 0.019064, No Obj: 0.000076, .5R: 0.500000, .75R: 0.000000,  count: 4
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.425831, Class: 0.468613, Obj: 0.000293, No Obj: 0.000028, .5R: 0.666667, .75R: 0.000000,  count: 3
Region 94 Avg IOU: 0.433684, Class: 0.598862, Obj: 0.000000, No Obj: 0.000000, .5R: 0.250000, .75R: 0.250000,  count: 4
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.326005, Class: 0.483588, Obj: 0.070492, No Obj: 0.000183, .5R: 0.000000, .75R: 0.000000,  count: 3
Region 94 Avg IOU: 0.502443, Class: 0.448609, Obj: 0.000000, No Obj: 0.000000, .5R: 0.666667, .75R: 0.000000,  count: 3
Region 106 Avg IOU: 0.469855, Class: 0.421250, Obj: 0.000000, No Obj: 0.000000, .5R: 0.000000, .75R: 0.000000,  count: 1
Region 82 Avg IOU: 0.489729, Class: 0.456997, Obj: 0.001689, No Obj: 0.000066, .5R: 0.500000, .75R: 0.000000,  count: 4
Region 94 Avg IOU: 0.489129, Class: 0.532057, Obj: 0.000000, No Obj: 0.000000, .5R: 0.333333, .75R: 0.166667,  count: 6
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.468061, Class: 0.405958, Obj: 0.017424, No Obj: 0.000135, .5R: 0.250000, .75R: 0.000000,  count: 4
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.612985, Class: 0.392304, Obj: 0.002824, No Obj: 0.000037, .5R: 0.750000, .75R: 0.250000,  count: 4
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.555892, Class: 0.391296, Obj: 0.002451, No Obj: 0.000011, .5R: 0.500000, .75R: 0.250000,  count: 4
Region 94 Avg IOU: 0.262094, Class: 0.431491, Obj: 0.000000, No Obj: 0.000000, .5R: 0.000000, .75R: 0.000000,  count: 1
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.400996, Class: 0.562962, Obj: 0.002511, No Obj: 0.000195, .5R: 0.000000, .75R: 0.000000,  count: 6
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.584226, Class: 0.503052, Obj: 0.009390, No Obj: 0.000189, .5R: 1.000000, .75R: 0.250000,  count: 4
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.479752, Class: 0.454211, Obj: 0.068032, No Obj: 0.000600, .5R: 0.333333, .75R: 0.000000,  count: 3
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.635752, Class: 0.528492, Obj: 0.000632, No Obj: 0.000006, .5R: 1.000000, .75R: 0.000000,  count: 3
Region 94 Avg IOU: 0.561953, Class: 0.521604, Obj: 0.000000, No Obj: 0.000000, .5R: 1.000000, .75R: 0.000000,  count: 2
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Segmentation fault (core dumped)`
# Even i changed my yolov3.cfg
`batch=64
subdivisions=16`
# I use 1080 ti graphics card but cannot use this conf
`batch=64
subdivisions=8or16`
# I have changed classes =7  and filters=36 check my full yolov3.cfg file 

```
batch=64
subdivisions=16
[net]
# Testing
batch=64
subdivisions=16
# Training
# batch=64
# subdivisions=16
width=416
height=416
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
burn_in=1000
max_batches = 500200
policy=steps
steps=400000,450000
scales=.1,.1

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

# Downsample

[convolutional]
batch_normalize=1
filters=64
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=32
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

# Downsample

[convolutional]
batch_normalize=1
filters=128
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

# Downsample

[convolutional]
batch_normalize=1
filters=256
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear


[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

# Downsample

[convolutional]
batch_normalize=1
filters=512
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear


[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear


[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear


[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear


[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear


[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

 Downsample

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear



[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=36
activation=linear


[yolo]
mask = 6,7,8
anchors = 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326
classes=7
num=9
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1


[route]
layers = -4

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[upsample]
stride=2

[route]
layers = -1, 61



[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=512
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=512
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=512
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=36
activation=linear


[yolo]
mask = 3,4,5
anchors = 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326
classes=7
num=9
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1



[route]
layers = -4

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[upsample]
stride=2

[route]
layers = -1, 36



[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=256
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=256
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=256
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=36
activation=linear


[yolo]
mask = 0,1,2
anchors = 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326
classes=7
num=9
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1
