### ISSUE TITLE
Oversample and Undersample Capability?

### ISSUE THREAD

**Issue by silvernine209** [AlexeyAB/darknet#1453]
If train dataset is very imbalanced, is there a way to over&under-sample within code other than manually adjusting train images?

Below shows imbalance of train set by counting positive bounding boxes with its classes.
![image](https://user-images.githubusercontent.com/37491067/44345449-69496200-a461-11e8-9707-ce3efd193c56.png)

**Comment by silvernine209** [comment]
For simplicity, imagine I have 10 images(1.jpg,2.jpg,3.jpg....10.jpg) and 3 classes.
Of 10 images, class 1 has 6 images, class 2 has 2 images, and class 3 has 2 images for training.
Therefore, imbalance of classes class 0 has 60% of images, class 1 has 20% of images, and class 2 has 20% of images.

To make the training sample images equally, can I do below in my **`train.txt`** ?
1.jpg
2.jpg
2.jpg
2.jpg
2.jpg
2.jpg
2.jpg
2.jpg
2.jpg
2.jpg

**Comment by AlexeyAB** [comment]
> To make the training sample images equally, can I do below in my train.txt ?
> ```
> 1.jpg
> 2.jpg
> 3.jpg
> 4.jpg
> 5.jpg
> 6.jpg
> 7.jpg
> 7.jpg
> 7.jpg
> 8.jpg
> 8.jpg
> 8.jpg
> 9jpg
> 9jpg
> 9jpg
> 10.jpg
> 10.jpg
> 10.jpg
> ```

**Yes, you can do it.**

----

Also you can try to add in the each of 3 `[yolo]` layers parameter `focal_loss=1`
https://arxiv.org/abs/1708.02002

But it doesn't help for MS COCO dataset: https://pjreddie.com/media/files/papers/YOLOv3.pdf

> Focal loss. We tried using focal loss. It dropped our
> mAP about 2 points. YOLOv3 may already be robust to
> the problem focal loss is trying to solve because it has separate
> objectness predictions and conditional class predictions.
> Thus for most examples there is no loss from the
> class predictions? Or something? We aren’t totally sure.

-----

> Lastly, If 10.txt for 10.jpg has the following, will it ignore information about class 4, which is not what I'm training for.
> 
> 10.txt
> 
> 1 0.41 0.22 0.66 0.78
> 2 0.63 0.23 0.13 0.33
> 3 0.23 0.42 0.12 0.45
> 4 0.56 0.24 0.43 0.26
> 4 0.73 0.44 0.66 0.12


It will lead to warning, and will waiting for press Enter. To avoid id - comment this line: https://github.com/AlexeyAB/darknet/blob/08d0e07ed64139d2552d7801b755af7f34b4a75e/src/data.c#L340
