### ISSUE TITLE
Output video is in slow motion

### ISSUE THREAD

**Issue by DonCorle0ne** [AlexeyAB/darknet#1458]
Hi @AlexeyAB , I used this command line to run detection on my customized video:
./darknet detector demo cfg/voc.data cfg/yolov3-voc.cfg backup/yolov3-voc_28824.weights IE.m4v -out_filename IEtest.m4v -dont_show

But the output video is in slow motion, any idea what might be the reason? Thanks!

**Comment by AlexeyAB** [comment]
@DonCorle0ne Hi,

* Do you use the latest version of this repo?

* Do you get warning at the starting of `./darknet detector demo` command?
`Can't get FPS of source videofile. For output video FPS = 25 by default.`

* Perhaps it can't get FPS of the source video, or may be source file is broken.
You can try to set FPS manually here - but it will be applied for all output videos, set `src_fps = 25;` if you need 25 fps: https://github.com/AlexeyAB/darknet/blob/8e018980a8eb15e319fec5c28163bf4ef408b1f0/src/demo.c#L223

**Comment by DonCorle0ne** [comment]
@AlexeyAB Thanks for the prompt reply!

- I think I was using an old version, downloaded earlier this year.

- No I did not get any warning

- I actually did testing on 3 different videos, 2 are online resources (mp4), 1 is recorded using my iPhone (m4v). Does the format of the video matter?

**Comment by DonCorle0ne** [comment]
@AlexeyAB  Updates: new version solved the problem! I saw some changes in demo.c file, is that the reason?

**Comment by AlexeyAB** [comment]
@DonCorle0ne Yes, new version should work well.
