### ISSUE TITLE
1 cannot use yolo_cpp_dll.dll

### ISSUE THREAD

**Issue by Marzuki001** [AlexeyAB/darknet#146]
hi alex, i was try your simple code at [https://github.com/AlexeyAB/darknet/blob/ab1c5f9e57b4175f29a6ef39e7e68987d3e98704/src/yolo_console_dll.cpp#L75]
but have a problen in here #include "yolo_v2_class.hpp"	// imported functions from DLL
it cannot open yolo_v2_class.hpp.

can you help me?
best regards

**Comment by Marzuki001** [comment]
hi @AlexeyAB,  my research topic is about graph analytics which the name (class) of object and amount of object is needed and image as input. i'm interesting with your work. now a starting from download, install Yolo2 under windows. but here is my problem  (#include "yolo_v2_class.hpp"	// imported functions from DLL) it cannot open yolo_v2_class.hpp. 
how to solve this problem and could my research be related with yours?

best regards

**Comment by AlexeyAB** [comment]
@Marzuki001 Hi,
* Can you show screenshot of full error message?
* Do you open `\build\darknet\yolo_console_dll.sln` in MSVS 2015 and do you try to compile it with x64 & Release?

**Comment by Marzuki001** [comment]
@AlexeyAB yes i have compiled it with x64 & Release , can not run  from MSVS2015 but it can run at console application from Windows Explore. now i try to develop simple application using yolo_cpp_dll.dll 

![error](https://user-images.githubusercontent.com/10569176/29070549-0e313b6a-7c6a-11e7-9af2-2f5f86900372.png)

**Comment by AlexeyAB** [comment]
@Marzuki001 

These are very different things `#include <yolo_v2_class.hpp>` and `#include "yolo_v2_class.hpp"`  https://github.com/AlexeyAB/darknet/blob/b202eaee259572cf8b627a776a62ce9d59aa50a6/src/yolo_console_dll.cpp#L11

* Use `#include "yolo_v2_class.hpp"`  
* Put `yolo_v2_class.hpp` near with your `openCvForm.h`

**Comment by Marzuki001** [comment]
@AlexeyAB  i cannot found yolo_v2_class.hpp, is it not include in yolo_cpp_dll.dll ? i have Put  yolo_cpp_dll.dll near with openCvForm.h

![error](https://user-images.githubusercontent.com/10569176/29071436-d2a28f46-7c6d-11e7-8c01-496bbf0f3c4e.png)

**Comment by AlexeyAB** [comment]
@Marzuki001 Try to see here: https://github.com/AlexeyAB/darknet/tree/master/src

For example: https://github.com/AlexeyAB/darknet/blob/master/src/yolo_v2_class.hpp

**Comment by Marzuki001** [comment]
OK i will try 
thanks @AlexeyAB

**Comment by Marzuki001** [comment]
@AlexeyAB why i can not run yolo_console_dll from MSVS2015 ? (i have copy 2 files yolo-voc.cfg and yolo-voc.weights to the directory build\darknet\ ) even though no error and sucsses create yolo_console_dll.exe

**Comment by AlexeyAB** [comment]
Also copy `yolo_cpp_dll.dll` to the directory build\darknet\

**Comment by Marzuki001** [comment]
@AlexeyAB i did it. but still like that
![error](https://user-images.githubusercontent.com/10569176/29079771-41235904-7c88-11e7-9633-45c21bba6d1e.png)

**Comment by AlexeyAB** [comment]
Something wrong with your code.
How do you launch your exe-file in detail?

**Comment by Marzuki001** [comment]
i just use your code:
1. extract darknet-master (built darknet sln)
2. open  in MSVS2015 file build\darknet\yolo_cpp_dll.sln with release and x64.
3. at theprject=right click -properties-c/c++-preprocessor-preprocessor definition + add CUDNN
4. Built
5. Open yolo_console_dll from MSVS2015 
6. copy opencv_world320.dll to /darknet and darknet/64
7. built with release and x64
8. copy yolo-voc.weights and  yolo-voc.cfg  to to /darknet and darknet/64
9 Run
![result](https://user-images.githubusercontent.com/10569176/29081409-b4e21a52-7c8c-11e7-8d75-3f9fcef6f05c.png)

**Comment by AlexeyAB** [comment]
Add line `getchar();` before `return 0` in the file `yolo_console_dll.cpp`: https://github.com/AlexeyAB/darknet/blob/4528f9b4b49dc701d3de7b38fa59c17c41702679/src/yolo_console_dll.cpp#L142

And try to run  `yolo_console_dll.exe` from MSVS. Show screenshot.

**Comment by Marzuki001** [comment]
wow... i have new problem now
 
![result](https://user-images.githubusercontent.com/10569176/29082251-2c7f8f98-7c8f-11e7-833a-7deaf41b8ce1.png)

**Comment by AlexeyAB** [comment]
* Build -> Clean
* Build -> Rebuild

**Comment by Marzuki001** [comment]
i try to run.. console windows open for a moment only and then closed by it self. in the screenshot i pause it
![result](https://user-images.githubusercontent.com/10569176/29083113-d3c9df04-7c91-11e7-9576-285ca0033ef8.png)

**Comment by Marzuki001** [comment]
@AlexeyAB :  you are very friendly and considerate. I am very proud to know you.
Tomorrow I will repeat step by step from the beginning
I'm sleepy now .. it's here at 11:40 pm

Thanks and warm regards

**Comment by Marzuki001** [comment]
@AlexeyAB i think the problem why can not run yolo_console_dll from MSVS (screen shot) but i can't solve it
![result](https://user-images.githubusercontent.com/10569176/29108284-69bcd496-7d08-11e7-8d9a-eb0743ea06cc.png)

**Comment by Marzuki001** [comment]
oh. i found it. there is not yolo-voc.cfg.. 
solve with: copy yolo-voc.cfg to the directory build\darknet\

thanks
