### ISSUE TITLE
1-2 seconds delay 

### ISSUE THREAD

**Issue by bryantclcqq** [AlexeyAB/darknet#147]
when the inputs are video streamings from a camera,  the detection outputs (also a video) has1-2 seconds delay to the real world,   which is very uncomfortable!
why?   and how can we reduce the delays?

**Comment by AlexeyAB** [comment]
This is the total delay in several places: camera-delay (WBR, 3D DNR, ...) + network-delay + OpenCV-capture-buffer-delay + Yolo-mean-deleay(3 frames)

Do you use **RTSP** network camera?

1. Try to build `build\darknet\yolo_console_dll.sln`
2. Run `yolo_console_dll.exe` and enter network-camera-URL

3. If delay still high then:
* try to increase FPS on the camera at maximum
* then uncomment this line: `if(protocol == "rtsp") while (!ready_flag) cap.grab();` https://github.com/AlexeyAB/darknet/blob/master/src/yolo_console_dll.cpp#L101
* rebuild `yolo_console_dll.sln`, run `yolo_console_dll.exe` and enter network-camera-URL

**Comment by bryantclcqq** [comment]
many thx for the reply.  i try to build
build\darknet\yolo_console_dll.sln,    
however,i got the error:
LNK118:  cannot open input file "yolo_cpp_dll.lib"

**Comment by AlexeyAB** [comment]
@bryantclcqq  At first try to build `yolo_cpp_dll.dll` and only after that try to build `yolo_console_dll.sln` https://github.com/AlexeyAB/darknet#how-to-use-yolo-as-dll

**Comment by bryantclcqq** [comment]
great!   I successful build it!  thx!

however,  can i use it with my own model? 
it seems that it load yolo_voc.weights by default?
and if i use rtsp camera, what is exactly the command format like?
i tried  yolo_console_dll.exe detector demo data\i.data i.cfg i.weights rtsp://user:passwd@xx.xx.xx.xx/xx/ch1/main/av_stream    
it seems isnot the right way?

**Comment by AlexeyAB** [comment]
To use your own model - change these 2 line in the source code `yolo_console_dll.cpp`: https://github.com/AlexeyAB/darknet/blob/b202eaee259572cf8b627a776a62ce9d59aa50a6/src/yolo_console_dll.cpp#L67
```cpp
	Detector detector("yolo-voc.cfg", "yolo-voc.weights");
	auto obj_names = objects_names_from_file("data/voc.names");
```
----

To use rtsp-camera, run `yolo_console_dll.exe` and after it will have been runed, then enter
 `rtsp://user:passwd@xx.xx.xx.xx/xx/ch1/main/av_stream`

**Comment by bryantclcqq** [comment]
thx!   i will try that!
but,   why  yolo_console_dll.exe  is supposed to have less latency  than darknet.exe ?
i mean than this way:
darknet.exe detector demo data\i.data i.cfg i.weights rtsp://user:passwd@xx.xx.xx.xx/xx/ch1/main/av_stream

**Comment by AlexeyAB** [comment]
1. `yolo_console_dll.exe` uses faster functions to resize and show image: https://github.com/AlexeyAB/darknet/issues/126#issuecomment-320343311
2. `yolo_console_dll.exe` able not to use `mean_arrays()` or use it in other way.
3. `yolo_console_dll.exe` use `cap.grab()` that flush OpenCV-cap-buffer, if it uncommented: https://github.com/AlexeyAB/darknet/blob/4528f9b4b49dc701d3de7b38fa59c17c41702679/src/yolo_console_dll.cpp#L104

**Comment by bryantclcqq** [comment]
I tried 
""To use your own model using DLL - change these 2 line in the source code yolo_console_dll.cpp:""
however, when i rebuild it, .some errors came out:
C2661 Detector::detect :  no overloaded function takes 3 arguments    
 in line93  yolo_console_dll.cpp

**Comment by bryantclcqq** [comment]
another thing is，after all these operations  the latency seems still around 1second.
is it possible that  the multi_thread is not running correctly?
before, I also found that  DarkNet.exe   ... _s

**Comment by bryantclcqq** [comment]
another thing is，after all these operations the latency seems still around 1second.
is it possible that the multi_thread is not running correctly?
before, I also found that DarkNet.exe ... —s   cannot work   so  can this problem  common reasons with the latency problems?

**Comment by AlexeyAB** [comment]
Did you try to uncomment this line?  https://github.com/AlexeyAB/darknet/blob/4528f9b4b49dc701d3de7b38fa59c17c41702679/src/yolo_console_dll.cpp#L104

If latency still around 1 sec, then it is problem with your Video-Cam. Not all cameras have a low latency.

**Comment by bryantclcqq** [comment]
yes,   have already uncomment that line!
i am wondering any other installation issues caused the latency,    as  i found that  darknet detector.demo data\i.data  i.cfg  i.weights  –s 10  cannot work either.
