### ISSUE TITLE
Using MAP command, changing threshold 

### ISSUE THREAD

**Issue by kylynf** [AlexeyAB/darknet#1477]
Hi! So I am trying to validate my weights and run map. AlexeyAB conveniently has a map command that no one else has (./darknet detector map) and so far I love it. 

My question is how to increase the threshold amount so the network is more accurate. I used 10 test images and manually did some validation by hand and want to cross check my calculations with the MAP command calculations, but used a threshold of 0.50. How do I increase it?

Thank you!

**Comment by AlexeyAB** [comment]
@kylynf Hi,

* To change threshold add a flag `-thresh 0.5` at the end of any command.

* If you want to change probability of objects - then you can't change it.

**Comment by kylynf** [comment]
Hi @AlexeyAB.. thank you! I don't know why I didn't think of that. It worked! Thank you so much love your repo!
