### ISSUE TITLE
Training Not Responding: average loss (Not Responding)

### ISSUE THREAD

**Issue by leekwunfung817** [AlexeyAB/darknet#1479]
The training stop suddenly!
The log were stop to generated.

**The top of the window show: average loss (Not Responding)**
![untitled](https://user-images.githubusercontent.com/18736700/44638398-38c97100-a9e9-11e8-98cb-32e81dd5580a.png)

![untitled](https://user-images.githubusercontent.com/18736700/44638350-fef86a80-a9e8-11e8-831f-8adac2ff4894.png)

**Comment by leekwunfung817** [comment]
When I push the button ( Ctrl + C ) then the training is continue again, what happen?

**Comment by CHNWhite** [comment]
I have the same problem as you, have you solved it

**Comment by AlexeyAB** [comment]
Try to train with flag `-dont_show` at the end of command.

**Comment by AlexeyAB** [comment]
Decrease this value: https://github.com/AlexeyAB/darknet/blob/57e878b4f9512cf9995ff6b5cd6e0d7dc1da9eaf/cfg/yolov3.cfg#L20

**Comment by CHNWhite** [comment]
Thank you very much
