### ISSUE TITLE
no bounding box in preditcions.png and no file in results folder

### ISSUE THREAD

**Issue by Bigoudom** [AlexeyAB/darknet#1484]
Hi,

I have installed darknet following the instructions of AlexeyAB (from https://github.com/AlexeyAB/darknet).

I also install opencv-3.4.0 following http://www.python36.com/how-to-install-opencv340-on-ubuntu1604/
and compile darknet with the following options in Makefile:

GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=1
AVX=0
OPENMP=0
LIBSO=0

...

DEBUG=0

...

Everything seems to work perfectly during the compilation.
However when I test darknet by using the following command: 

./darknet detector test ./cfg/coco.data ./cfg/yolov3.cfg ./yolov3.weights

I have the following display:
**layer     filters    size              input                output
   0 conv     32  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  32 0.299 BF
   1 conv     64  3 x 3 / 2   416 x 416 x  32   ->   208 x 208 x  64 1.595 BF
   2 conv     32  1 x 1 / 1   208 x 208 x  64   ->   208 x 208 x  32 0.177 BF
   3 conv     64  3 x 3 / 1   208 x 208 x  32   ->   208 x 208 x  64 1.595 BF
....
 106 yolo
Total BFLOPS 65.864 
Loading weights from ./yolov3.weights...
 seen 64 
Done!
Enter Image Path:**

I type for example **data/dog.jpg**

And have only this result (i.e. no probability for belonging to a class):
**data/dog.jpg: Predicted in 0.008205 seconds.**

The image data/dog.jpg is now open and I have no bouding box.

Any idea?
below more information on my system.

Thanks!

System information

    Operating system: Ubuntu 16.04 LTS (64bits)
    Compiler version: gcc/g++ 5.4 / cmake 3.5.1
    CUDA version: 8.0
    cuDNN version: 7.2.1
    NVIDIA driver version: 384.130
    GPU models (for all devices if they are not all the same): GeForce GTX 1080TI
    Python : Python 2.7.15 :: Anaconda, Inc.

**Comment by AlexeyAB** [comment]
@Bigoudom Hi,

> And have only this result (i.e. no probability for belonging to a class):
> data/dog.jpg: Predicted in 0.008205 seconds.

* Can you show screenshot?
* Can you detect anything with `CUDNN=0` in the Makefile (then recompile)?
* If can't, then try to use:

    * CUDA 9.0 https://developer.nvidia.com/compute/cuda/9.0/Prod/local_installers/cuda_9.0.176_windows-exe

    * cuDNN 7.1.3 for CUDA 9.0: https://developer.nvidia.com/compute/machine-learning/cudnn/secure/v7.1.3/prod/9.0_20180414/cudnn-9.0-windows7-x64-v7.1

**Comment by Bigoudom** [comment]
@AlexeyAB Hi,

I recompile with CUDNN=0 and it works now!
Do you think I should use Cuda 9.0 and cuDNN 7.1.3, or I can continue with my configuration and train the model on my own data?

Many thanks for your answer!

**Comment by AlexeyAB** [comment]
@Bigoudom 

You can use your configuration with CUDNN=0.

But Cuda 9.0 and cuDNN 7.1.3 with CUDNN=1 will train faster.

**Comment by Bigoudom** [comment]
@AlexeyAB 
Training works, thanks for all!
