### ISSUE TITLE
Store Coordinates only once?

### ISSUE THREAD

**Issue by fdkssdks** [AlexeyAB/darknet#1485]
Hello, I am interested to know if there's a way to store the coordinates of the detected object only once?

So, when the detection is running it keeps on detecting the object and keeps on appending the coordinate of the same objects again and again(I am using CSV file to write the coordinates). Though there's a slight delta in the coordinates but that doesn't matter since the object is stationary.

Any help is appreciated.
Thanks

**Comment by AlexeyAB** [comment]
@fdkssdks Hello,

No.

You should write your own code/script that will remove (fuse) detection from several frames if obj_id is the same and delta is small. Or you should implement Tracking algorithm, that will say you is it the same object or not.

**Comment by fdkssdks** [comment]
Thanks, I will write my function for fuse detection. This looks promising.

**Comment by fdkssdks** [comment]
I was able to solve this with the signal high/low from SBC.
The function I came up with was using Detection + Tracking which added more computation hence slower fps. So, I'd to remove the function.
