### ISSUE TITLE
The code executeion cannot proceed because (4 Files) was not found. Reinstalling the program may fix this problem.

### ISSUE THREAD

**Issue by leekwunfung817** [AlexeyAB/darknet#1488]
How to solve this problem?

When I execute the following command, the alert prompt shown.
`darknet.exe detector train cfg/obj.data cfg/yolov3-tiny.cfg darknet19_448.conv.23`

1. cublas64_91.dll
2. opencv_world340.dll
3. cudart64_91.dll
4. curand64_91.dll

![p1](https://user-images.githubusercontent.com/18736700/44703593-d3e64780-aaca-11e8-84e3-4e252064d945.png)
![p2](https://user-images.githubusercontent.com/18736700/44703594-d3e64780-aaca-11e8-803d-440769af4af2.png)
![p3](https://user-images.githubusercontent.com/18736700/44703595-d47ede00-aaca-11e8-9992-5b685a7a6d30.png)
![p4](https://user-images.githubusercontent.com/18736700/44703596-d47ede00-aaca-11e8-885c-b59b21315824.png)

when I rebuild the darknet.exe I get this
![pp5](https://user-images.githubusercontent.com/18736700/44703757-6555b980-aacb-11e8-8f98-3a7dabed4203.png)

**Comment by AlexeyAB** [comment]
> 1. cublas64_91.dll
> 2. opencv_world340.dll
> 3. cudart64_91.dll
> 4. curand64_91.dll

Copy these files from CUDA and OpenCV folders - to the Directory with `darknet.exe`.

**Comment by leekwunfung817** [comment]
problem solved
