### ISSUE TITLE
Compile darknet with out CUDA in windows

### ISSUE THREAD

**Issue by saiprasadb** [AlexeyAB/darknet#149]
Hi ,

I just started using darknet, I have installed cuda in windows as per documentation and compiled using visual studio which successfully generated darknet.exe, but when I start executing the darknet for sample I got an CUDA driver version is insufficient for CUDA runtime version error because I dont have NVIDIA graphics, is it possible to compile and run with out cuda in windows by using only opencv as per the below guidelines from https://pjreddie.com/darknet/install/ 

**Darknet is easy to install with only two optional dependancies:
OpenCV if you want a wider variety of supported image types.
CUDA if you want GPU computation.**

Regards,
Sai Prasad

**Comment by AlexeyAB** [comment]
Hi, you should open `build\darknet\darknet_no_gpu.sln` instead of `darknet.sln` in this case.

I added this to the manual: https://github.com/AlexeyAB/darknet#how-to-compile-on-windows

> 3. If you don't have GPU, but have MSVS 2015 and OpenCV 3.0 (with paths: C:\opencv_3.0\opencv\build\include & C:\opencv_3.0\opencv\build\x64\vc14\lib), then start MSVS, open `build\darknet\darknet_no_gpu.sln`, set x64 and Release, and do the: Build -> Build darknet

**Comment by saiprasadb** [comment]
Hi Alexey,

Thanks for the support, I have tried as per your suggestions it working fine.
