### ISSUE TITLE
CUDA Error: no kernel image is available for execution on the device darknet: ./src/cuda.c:36: check_error: Assertion `0' failed

### ISSUE THREAD

**Issue by komalpharate** [AlexeyAB/darknet#1491]
Hi,
I'm trying to run this darknet on DGX-1 with Makefile options for ARCH
ARCH= -gencode arch=compute_60,code=sm_60

make is successful
But getting above error while running darknet on image as given:
./darknet detect cfg/yolov3.cfg yolov3.weights data/dog.jpg

```
CUDA Error: no kernel image is available for execution on the device
darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
Aborted (core dumped)

```

**Comment by AlexeyAB** [comment]
@komalpharate Hi,

Try to use this command:
`./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg`

Also do you use `GPU=1 CUDNN=1 DEBUG=0`?

**Comment by komalpharate** [comment]
Hey, it's typing mistake. I used yolov3 files only.
And using - 
Settings-
GPU=1
CUDNN=0
DEBUG=0

**Comment by AlexeyAB** [comment]
@komalpharate 
* What GPU are in your DGX-1, is it new Volta or old Pascal?
* What CUDA and cuDNN versions do you use?

> I'm trying to run this darknet on DGX-1 with Makefile options for ARCH
> ARCH= -gencode arch=compute_60,code=sm_60

Try to **undo** this.
And change these lines: https://github.com/AlexeyAB/darknet/blob/18d5e4f39c1441f2c21043ac3204b5cb279f8758/Makefile#L15-L19
to these:
```
 ARCH= -gencode arch=compute_60,code=sm_60 \ 
       -gencode arch=compute_70,code=sm_70 \ 
       -gencode arch=compute_50,code=[sm_50,compute_50] \ 
       -gencode arch=compute_52,code=[sm_52,compute_52] \ 
 	  -gencode arch=compute_61,code=[sm_61,compute_61] 
```

If it doesn't help, try to compile with `CUDNN=1`.

**Comment by komalpharate** [comment]
Yes it worked.
Updating little late.
Thanks a lot.
It's giving 49-60 fps for yolov2.
