### ISSUE TITLE
rectangular aspect ratio

### ISSUE THREAD

**Issue by groot-1313** [AlexeyAB/darknet#1496]
Hi, I have images that are 640x280 in size. I would like to perform object detection using YOLO v1. Now my main concern is to be able to maintain this rectangular aspect ratio and obtain a final grid of say, 10x4 size, which would then be converted to a fully connected layer(v1). 
I see that I can change the height and width in the config file, but there is only one parameter `side` for grid size, which means i end up with a square grid of say 7x7 if `side=7`. 
Any thoughts on how I can achieve a rectangular aspect ratio would help a lot. Thanks!

**Comment by groot-1313** [comment]
How can I change the aspect ratio in YOLO v2? Basically, I will have more detections across the width of the image, so I would like to have a final grid size of say, 13x7 for more resolution across columns. Is this possible?

**Comment by AlexeyAB** [comment]
@groot-1313 
set in the [net] section in your cfg-file `width=416` `height=224`
