### ISSUE TITLE
Some questions regarding training and detection(test) images and their sizes 

### ISSUE THREAD

**Issue by VanitarNordic** [AlexeyAB/darknet#15]
Hello,

1) When we gather the training images, all of them should have the same size (resolution)? for example `800 * 600`

2) if we train the YOLO (`height` and `width` of the `Net`) with `416 * 416`, then the test images or input camera resolution should be `416 * 416` or an ****integer multiplication result**** of `416 * 416`? for example `(416 * 2 = 832 * 832`)? 

if Yes, then we should change the 416 * 416 to the input camera or test image resolution (for example 1024 * 768)?

3) How the `batch` and `subdivision` parameters are calculated in case of changing the `height` and` width` of the Net?

**Comment by AlexeyAB** [comment]
Hi,

1. No, sizes of input images may be any. Images will be resized to Net-size inside Yolo-code.

2. No. You can train Yolo on 416x416, then you can change `.cfg`-file to resolution 544x544 or 288x288 and use this cfg with `.weights`-file trained on 416x416.

    2.1. If you use camera with resolution 1024x768, then changing `.cfg`-file to resolution 768x768 can help to detect small or distant objects, but decrease speed 3.4 x times. But I don't recommend to change `.cfg`-file to resolution 1024x768 because it changes aspect ratio from 1:1 to 4:3 - this can greatly reduce the accuracy of detection.

3. You should not change `batch` and `subdivision` if there is no error: out of memory on GPU. Increasing `subdivision` can help avoid this error.

**Comment by VanitarNordic** [comment]
Thanks.

1) So if I understood correctly, if we have a camera or image with 1024 * 768 resolution, the 416 * 416 size in the `cfg` file still can detect objects accurately and no need to change the size in the `cfg` file, yes?

2) what's the reason of more than one detection boxes on an object and how it could be solved?

**Comment by VanitarNordic** [comment]
Thanks.

1) So if I understood correctly, if we have a camera or image with 1024 * 768 resolution, the 416 * 416 size in the `cfg` file still can detect objects accurately and no need to change the size in the `cfg` file, yes?

2) what's the reason of more than one detection boxes on an object and how it could be solved?

**Comment by VanitarNordic** [comment]
I am specifically referring to this issue: https://github.com/AlexeyAB/darknet/issues/12

it seems changing the size in the `.cfg` file in accordane with test images/camera resolution will **significantly** increase the detection accuracy.

You mentioned:

Trained 416x416, and detection 416x416:
![b269304a-e04b-11e6-90e1-fd60929b6e92](https://cloud.githubusercontent.com/assets/18719591/22591014/996a1e7a-ea27-11e6-8ce2-855fea4138cc.jpg)

Trained 416x416, and detection 832x832:
![b66250e6-e04b-11e6-8659-86c3f40bcbb3](https://cloud.githubusercontent.com/assets/18719591/22591024/a27cff8c-ea27-11e6-8751-4e6abcfa4996.jpg)

**Comment by AlexeyAB** [comment]
@VanitarNordic 

1. Yes, no need to change the size in the cfg file. But you can do it for searching the optimum balance between speed and accuracy.

2. It is false positive detection. Network thinks that there are two different aircraft. 

To solve this:
* usually enough train the network better: more images, more variety of images and long training.
* or increase `-thresh`
* also you can play with changing this parameter `float nms=.4;` to merge overlapping boxes: 
    * detect on image: https://github.com/AlexeyAB/darknet/blob/master/src/detector.c#L456
    * detect on video: https://github.com/AlexeyAB/darknet/blob/master/src/demo.c#L55

**Comment by VanitarNordic** [comment]
Thank you again.

I know how to test the model with image and camera, is there anyway to feed it with a video and see the detection?
