### ISSUE TITLE
I need yolo9000.weights

### ISSUE THREAD

**Issue by zoufangyu1987** [AlexeyAB/darknet#150]
HI:
I need "yolo9000.weights",but I cann`t find it.
where is it ?
thank you!

**Comment by AlexeyAB** [comment]
Hi,

* yolo9000.cfg: https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolo9000.cfg
* (186 MB Yolo9000-model) - require 4 GB GPU-RAM: http://pjreddie.com/media/files/yolo9000.weights

**Comment by zoufangyu1987** [comment]
thank you a lot!
