### ISSUE TITLE
error while executing ./uselib

### ISSUE THREAD

**Issue by BlcaKHat** [AlexeyAB/darknet#1509]
I am facing error while trying to execute ./uselib

$ ./uselib 
./uselib: error while loading shared libraries: darknet.so: cannot open shared object file: No such file or directory

**Comment by AlexeyAB** [comment]
Try to run it in such a way:
`LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./uselib data/coco.names cfg/yolov3.cfg yolov3.weights test.mp4`

**Comment by BlcaKHat** [comment]
can you explain it . I didn't get it properly

**Comment by AlexeyAB** [comment]
Just run this line 
`LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./uselib data/coco.names cfg/yolov3.cfg yolov3.weights dog.jpg`
And show me screenshot of result.

**Comment by BlcaKHat** [comment]
![gt](https://user-images.githubusercontent.com/16970999/44852773-bc9d8a80-ac81-11e8-9f9b-4c5af1ff769e.png)

**Comment by BlcaKHat** [comment]
![gt2](https://user-images.githubusercontent.com/16970999/44852880-038b8000-ac82-11e8-984d-d700a9c732f1.png)

**Comment by BlcaKHat** [comment]
this is working

**Comment by BlcaKHat** [comment]
alex I want to count the number of person how should i proceed

**Comment by BlcaKHat** [comment]
say i hav 100 images in a folder , I want to classify images to other folder by counting people . 
if one , then move to folder one, if two, then move to folder 2
