### ISSUE TITLE
Is there a possibility to fine-tune middle layers in yolov3 using stopbackward?( say from layer 10 to layer 15 and freeze the remaining layers) 

### ISSUE THREAD

**Issue by kssk16** [AlexeyAB/darknet#1528]
Hi,
I have modified the network a little and have obtained pretrained weights from the yolov3. I like to fine-tune or update the weights of only few layers and freeze the other layers. Is this possible?

By the way, Thank you for the repo:)

**Comment by AlexeyAB** [comment]
@kssk16 Hi, By default No. You can freez only the first N layers by using `stopbackward=1`.

-----

But you can change the source code.

To do what you want - you should change this line: https://github.com/AlexeyAB/darknet/blob/18d5e4f39c1441f2c21043ac3204b5cb279f8758/src/network_kernels.cu#L88
to this: `if (l.stopbackward) continue;`

And you should set `stopbackward=1` for each layer which you want to freeze.

**Comment by kssk16** [comment]
Thanks @AlexeyAB. I will try your suggestion.

**Comment by AlexeyAB** [comment]
@kssk16 I fixed my previous answer: https://github.com/AlexeyAB/darknet/issues/1528#issuecomment-418141407

**Comment by kssk16** [comment]
Thank You:)
