### ISSUE TITLE
Why does not CUDNN_HALF option work on training?

### ISSUE THREAD

**Issue by dsgh2** [AlexeyAB/darknet#1539]
Hello.

I would like to say thanks for your contribution above all.
I have faced with this strange problem and I do not know how solve this problem.

I am wondering that why CUDNN_HALF option does not work on training stage.
According to #407, It should show a significant better result when tensor core is used.
However, mine was not.
Please let me know how solve this problem. I have spent too much time trying to fix this.

Here is my environment and configuration.

---------------------------------------------------------------------
1. Environment
GPU: Titan V x 7
OS: Ubuntu 16.04
commit: probably latest(3 days ago)
CUDA: 9.2(and CUDNN 7.2.1)
           9.1(and CUDNN 7.1)
           Both havebeen tested and the result was same.
OpenCV: 3.4.0

2. Makefile configuration
GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=1
AVX=1
OPENMP=1
LIBSO=0

#Tesla V100
ARCH= -gencode arch=compute_70,code=[sm_70,compute_70]

The others things have not been changed.

----------------------------------------------------------------------

3. Result
Depending on the option CUDNN_HALF, time cost varies.

yolo-v3(input: 320x320), batch=64, subdivision 16
After 1000 iters, 

When CUDNN_HALF=0 on single idle GPU,
1.65~1.71 seconds / 1 iteration , approximately.

When CUDNN_HALF=1 on single idle GPU,
**1.82~1.87 seconds** / 1 iteration , approximately.

---------------------------------------------------------------------

No typos.  CUDNN_HALF=1 is slower than CUDNN_HALF=0, obviously. Performance increases not at all.

And I have tried to find out problems, it seemed to be no problem because I have found that it flows into CUDNN_TENSOR_OP_MATH in the source code.

In inference stage(darknet demo command), 30% of FPS increases. However, this does not seem to be enough as #407 shown.

How can I fix this?

Thank you.

**Comment by AlexeyAB** [comment]
@dsgh2 Hi,

> yolo-v3(input: 320x320), batch=64, subdivision 16
> After 1000 iters,
> 
> When CUDNN_HALF=0 on single idle GPU,
> 1.65~1.71 seconds / 1 iteration , approximately.
> 
> When CUDNN_HALF=1 on single idle GPU,
> 1.82~1.87 seconds / 1 iteration , approximately.

There are can be 3 bottlenecks: 
* GPU (unlikely)
* CPU - if OPENCV=0, or OpenCV is compiled without AVX/multithreading, or if is used DEBUG=1 in the Makefile of Darknet
* HDD - if is used HDD or slow SSD, so training images loaded slowly

----

1. For clean testing, try to test with small `train.txt` file about 64 images, and wait several iterations, while it will be cached.

2. Also for clean testing try to test with `random=0` in your cfg-file. Because if random=1 then for each runing time there will be different network size and will be different speed.

3. Try to use `batch=64 subdivision=4 width=416 height=416 random=0` (or subdivisions=8 if Out of memory occurs), what time can you get for CUDNN_HALF=0 and CUDNN_HALF=1?

**Comment by AlexeyAB** [comment]
> What was the problem with subdivision size?
> How affects the subdivision size performance?

Darknet processes `mini_batch` images for one forward-backward-pass during training, where `mini_batch=batch/subdivisions`. The higher `mini_batch` - the higher speed - the higher accuracy will be achieved.

1 iteration = `batch`(images) = `mini_batch`(images) x `subdivisions`(passages).

> By the way, could I use 7 gpus? I have seen that it is up to 4.

Darknet was well tested for 4 GPUs. So you can try to use 7 GPUs, but I don't know will it work well or not.

To get the higher final accuracy, try to train the first 1000-2000 iterations with only 1 GPU and CUDNN_HALF=0. And then continue training with 4-7 GPUs `-gpus 0,1,2,3,4,5,6` and `CUDNN_HALF=1`.

----

Also what CPU do you use, and how many CPUs do you have?

**Comment by dsgh2** [comment]
I am using 2 of E5-2640 v4

**Comment by AlexeyAB** [comment]
So you have 20 CPU-Cores (40 HT), it is should be enough for data augmentation of datastream for at least 5 GPUs. May be it will be enough for 7 GPUs too.

I think you can train successfully your model by using 7 GPUs.

**Comment by dsgh2** [comment]
It seems to work well on 7 GPUs.

Thank you so much!

**Comment by dsgh2** [comment]
One more question,

If I set random option to 1, it shows out of memory.
So subdivision should increase. But if increase, bottleneck(as what you called) occurs.
If I fix input size, it would go well. But I cannot expect detection performance than I tried to initially and images cannot be processed as fast as previous one. Eventually, training may be slow.
Should batch size decrease? When decreased, there was an alert like below.
batch_size 32 is too small, set to batch_size=64, subdivision=64
I remember that the error occurs like this.

I have faced with the dilemma over these problem.
What should I do? Please let me know.

**Comment by AlexeyAB** [comment]
Try to change random multiplier, from `1.4` to `1.2` https://github.com/AlexeyAB/darknet/blob/18d5e4f39c1441f2c21043ac3204b5cb279f8758/src/detector.c#L137
And then try to use `random=1`, width=416 height=416, and `batch=64 subdivisions=4`

----

In general, if you get error Out of memory, then you should set `batch=64 subdivisions=64`. It doesn't make sense to decrease batch=. You should increase subdivisions= but not greater than batch=.
But yes, high subdivisions= will decrease speed of training.

Also there is no ideal solution, in any case there should be a compromise:
* Or you use random=1 and lower width= height=
* Or you use random=0 and higher width= height=
