### ISSUE TITLE
Question about training

### ISSUE THREAD

**Issue by erlendhade** [AlexeyAB/darknet#1542]
Hi @AlexeyAB 

I was wondering, when darknet trains a model, do the training images get loaded sequencially from the list train.txt, or does darknet pick (batch/subdivisions) images at random from the training set for each iteration?

Thanks

**Comment by AlexeyAB** [comment]
@erlendhade Hi,

Random.

https://github.com/AlexeyAB/darknet/blob/18d5e4f39c1441f2c21043ac3204b5cb279f8758/src/data.c#L736-L739

https://github.com/AlexeyAB/darknet/blob/18d5e4f39c1441f2c21043ac3204b5cb279f8758/src/data.c#L42-L59

**Comment by erlendhade** [comment]
OK

Thank you!
