### ISSUE TITLE
How to use yolo inn C++ application on linux

### ISSUE THREAD

**Issue by erlendhade** [AlexeyAB/darknet#1543]
Hi

I am quite new to the linux environment, and I want to use my trained model in a C++ application.
However, I am unsure as to how to accomplish this.

My current IDE is CLion, but I am open to suggestions if other IDEs make my goal easyer to accomplish.

Could someone provide a guide explaining how to use my trained yolov3 model in a C++ application.

Thanks

**Comment by AlexeyAB** [comment]
@erlendhade Hi,

Do you use Linux?

Just set `LIBSO=1` in the Makefile, and compile. You will get `darknet.so` library.
Then use such C++ example for using darknet.so library: https://github.com/AlexeyAB/darknet/blob/master/src/yolo_console_dll.cpp

There is C++ API of darknet.so: https://github.com/AlexeyAB/darknet/blob/master/src/yolo_v2_class.hpp

**Comment by erlendhade** [comment]
Yes, I do use Linux.

I have the darknet.so, but I am indirekte how to use it.. I have previously only used Visual Studio 2015, and I am unfamiliar with Clion and how to use the library in the IDE

**Comment by AlexeyAB** [comment]
If you use `CmakeList.txt` with Clion, then try to use such command `TARGET_LINK_LIBRARIES(GLBall darknet)`  https://stackoverflow.com/a/8776420/1558037

Also google how to use shared-library in Clion.

**Comment by erlendhade** [comment]
Hi @AlexeyAB 

This is how my `CmakeList-txt` looks:
`cmake_minimum_required(VERSION 3.12)
project(Utkikk9000)

set(CMAKE_CXX_STANDARD 14)

add_executable(Utkikk9000 main.cpp)

find_library(lib SHARED darknet)



target_link_libraries(GLBall darknet)`

Still getting error:
`CMake Error at CMakeLists.txt:12 (target_link_libraries):
  Cannot specify link libraries for target "GLBall" which is not built by
  this project.`

Do you know what the problem is?

**Comment by erlendhade** [comment]
Got rid of the error by changing GLBall to "Utkikk9000"

**Comment by erlendhade** [comment]
Hi @AlexeyAB 

I have successfully added darknet.so to my project.
Now I attempting to write my own application to do detection with my trained model on a webcam stream, however i am unsure of which files to add to the project/ include to make this possible.

For example, i get the error: `use of undeclared identifier cv`

I have included: 
`<yolo_v2_class.cpp>` 
`<yolo_console_dll.cpp>`

any help here would be appreciated.

**Comment by AlexeyAB** [comment]
> I have included:
> <yolo_v2_class.cpp>
> <yolo_console_dll.cpp>

It is required to add in your cpp-file:
```cpp
#define OPENCV
#include <yolo_v2_class.hpp>
```

**Comment by erlendhade** [comment]
Do I need to put

#include GPU as well?

**Comment by AlexeyAB** [comment]
@erlendhade 

For compiling your cpp-application you shouldn't add `#define GPU`.

For compiling darknet.so you should add `#define GPU` if it isn't done yet in the CmakeList.txt

**Comment by erlendhade** [comment]
OK

Should I just add

`#define GPU`

anywhere in CmakeList.txt?

**Comment by erlendhade** [comment]
I defined like this in CmakeLists.txt:
`add_compile_definitions(GPU)`

building my c++ application yields error:

In file included from /home/bachelor/darknet-master/src/activations.h:3:0,
                 from /home/bachelor/darknet-master/src/layer.h:4,
                 from /home/bachelor/darknet-master/src/network.h:6,
                 from /home/bachelor/darknet-master/src/yolo_v2_class.cpp:3,
                 from /home/bachelor/CLionProjects/Utkikk9000/main.cpp:3:
/home/bachelor/darknet-master/src/cuda.h:28:26: fatal error: cuda_runtime.h: No such file or directory
compilation terminated.
CMakeFiles/Utkikk9000.dir/build.make:62: recipe for target 'CMakeFiles/Utkikk9000.dir/main.cpp.o' failed
make[3]: *** [CMakeFiles/Utkikk9000.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/Utkikk9000.dir/all' failed
make[2]: *** [CMakeFiles/Utkikk9000.dir/all] Error 2
CMakeFiles/Makefile2:84: recipe for target 'CMakeFiles/Utkikk9000.dir/rule' failed
make[1]: *** [CMakeFiles/Utkikk9000.dir/rule] Error 2
Makefile:118: recipe for target 'Utkikk9000' failed
make: *** [Utkikk9000] Error 2
