### ISSUE TITLE
Darknet on Video using Python

### ISSUE THREAD

**Issue by mdv3101** [AlexeyAB/darknet#1544]
I want to use darknet.py file on a video. But the problem is, it is only accepting a single image at a time. Is there any method by which we can implement it, without loosing the speed.
I have build darknet_no_gpu.sln
PS: I also tried https://github.com/AlexeyAB/darknet/issues/955 the solution listed in it, but it is not showing bounding boxes or any detection of objects.

**Comment by mdv3101** [comment]
Hi, 
I manage to solve it. Check my forked script.
[Darknet_video.py](https://github.com/mdv3101/darknet/blob/master/darknet_video.py)

**Comment by WefPok** [comment]
@mdv3101 Hi! how did you solved it? trying to solve this problem for a week.....

**Comment by mnalam30** [comment]
@mdv3101 Can you show the full code of your Darknet_video.py?
Page not found on your repo.

> Hi,
> I manage to solve it. Check my forked script.
> [Darknet_video.py](https://github.com/mdv3101/darknet/blob/master/darknet_video.py)

**Comment by mdv3101** [comment]
@WefPok @mnalam30 Beacuse of some policy issues, i have to remove the file from my repo. Sorry for that.
You can find the code in the main repo of AlexeyAB. here is the link.
https://github.com/AlexeyAB/darknet/blob/master/darknet_video.py

Hope it would be helpful.
