### ISSUE TITLE
Real time detection Application (from folder) (to folder)

### ISSUE THREAD

**Issue by leekwunfung817** [AlexeyAB/darknet#1547]
### Question:
**How to make a application** that is real time to detect all image file from **folder_A**
and all output crop object to **folder_B** **object_name.jpg** in current directory **in easiest way**?

1. change the C Program in darknet.sln to my own application (using Visual Studio)
2. complie yolo_cpp_dll.dll to export to cpp project (using Visual Studio)
3. use the third party library to use the trained model

### Conditions:
I have trained .weights and .cfg and well result in darknet showed demo.
I have been tried OpenCV to detect the object but the result is not expected

### Addition
I am not well in C++, do anyone have the example in using yolo_cpp_dll.dll to build application?

I detected the dll have these function
![untitled](https://user-images.githubusercontent.com/18736700/45113914-3cde5700-b17e-11e8-9582-b2c58e827bdf.png)

How to continue to develop?
```
#include "stdafx.h"
#include "MyForm.h"
#include <Windows.h>
#include <iostream>
using namespace System;
using namespace System::Windows::Forms;


typedef unsigned int(WINAPI* AvVersion) (void);

[STAThread]
void main(array<String^>^ args) {
	HINSTANCE hInst = LoadLibrary(L"‪C:\\Users\\User\\Documents\\Visual Studio 2015\\Projects\\yolo_cpp_dll.dll");
	if (NULL != hInst) {
		AvVersion detect_image = (AvVersion)GetProcAddress(hInst, "detect_image");
		if (NULL != detect_image) {
			unsigned int result = detect_image();
		}
	}

	Application::EnableVisualStyles();
	Application::SetCompatibleTextRenderingDefault(false);
	Application_1::MyForm form;
	Application::Run(%form);
}
```

**Comment by leekwunfung817** [comment]
@PeterQuinn925 How to install darknetAB in sort_photos.py (line 11)?

> import cv2
> from darknetAB import performDetect
>

**Comment by PeterQuinn925** [comment]
I don't remember. I don't think I had to install anything. Make sure you have the path right or call your python program from the directory with darknetAB.py in it.

**Comment by leekwunfung817** [comment]
@PeterQuinn925 I cannot find darknetAB.py in any github project and website.
Can you provide the project or file?

**Comment by PeterQuinn925** [comment]
Sorry. Now I remember. I was switching from using PJ Reddie's version to Alexy so I renamed the darknet.py in AlexyAB's repository as darknetAB so I would be sure I was using the right one. Change my line 11 in my script to darknet from darknetAB and you should be good.

**Comment by leekwunfung817** [comment]
@PeterQuinn925 python may not a good solution for production, but thank for your help.

I  edit the darknet project, I solved the problem.
