### ISSUE TITLE
how do i create just train.txt . 

### ISSUE THREAD

**Issue by BlcaKHat** [AlexeyAB/darknet#1549]
I have data with co-ordinates. how do i write filenames with path in txt file?

**Comment by AlexeyAB** [comment]
It is better to use https://github.com/AlexeyAB/Yolo_mark for this. Just open your dataset in the Yolo_mark and train.txt will be created automatically.

**Comment by BlcaKHat** [comment]
awk '$0="prefix"$0' file > new_file

helped.
anyway, thanx for help
