### ISSUE TITLE
are png files supported for training??

### ISSUE THREAD

**Issue by AyushP123** [AlexeyAB/darknet#1551]
Hi,
       I wanted to know if .png files are supported for training. We tried training using .png files and there was no progress in learning, when we switched to .jpg we could see substantial training.

**Comment by AlexeyAB** [comment]
@AyushP123 Hi,

Yes, png is supported for both Training and Detection. 

> here was no progress in learning

* How did you check it? How many iterations did you train and what avg-loss and mAP did you get?
* Do you use this fork?
* Did you train with OPENCV=1 in the Makefile?
