### ISSUE TITLE
Input image aspect ratio and Steps to generate anchor boxes for Custom data 

### ISSUE THREAD

**Issue by PranjaLBiswas27** [AlexeyAB/darknet#1552]
Hi,

After reading literature about YOLO, I understand that anchor boxes need to be recalculated for custom data sets in priori. I have a data set with resolution of 512 * 424, which I intend to rescale to 512 * 416 so that the width and height are multiples of 32. Although everywhere in literature I see a 1:1 aspect ratio of the images. I have following queries on this matter: 

1. Will I be fine using images with different aspect ratio until they are multiples of 32?
2. In order to generate the anchors, what steps exactly I need to follow? Do I need to annotate my data set using Yolo_Mark, before I can generate my anchors?

Please let me know.

Kind Regards
Pranjal Biswas

**Comment by AlexeyAB** [comment]
@PranjaLBiswas27 Hi,

1. You can use any images with any aspect ratios. You can use 512 x 424 images. Any images will be resized to the network size 416x416 automatically in Yolo. Only network size (width= and height= in your cfg-file) should be divisible by 32 without a remainder.

2. Yes, you should annotate your dataset and then recalculate anchors as it is written here: https://github.com/AlexeyAB/darknet#how-to-improve-object-detection
    `./darknet detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416`

**Comment by AlexeyAB** [comment]
1. Accuracy may be will be increased - speed will be decreased: https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

2. The network size is the `width= and height=` parameters in your cfg-file.

**Comment by PranjaLBiswas27** [comment]
@AlexeyAB , thanks a lot for the help. This clears my doubts regarding the issue.

**Comment by PranjaLBiswas27** [comment]
Hi, 
I wanted to clarify whether YOLOv3 makes detection at the original network size scale or not, or just at scales corresponding to stride sizes of 8, 16 and 32? Please let me know.

Kind Regards
Pranjal Biswas
