### ISSUE TITLE
Question - What is mask and random in [Yolo] layer?

### ISSUE THREAD

**Issue by benn94** [AlexeyAB/darknet#1572]
As it is stated in the title?

```
[yolo]
mask = 6,7,8
anchors = 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326
classes=80
num=9
jitter=.3
ignore_thresh = .5
truth_thresh = 1
random=1
```

1- I assume this layer make the prediction
2- I have observed that the mask of each yolo layers are different but couldn't figure them out.
3- Could you explain why random=1 ?

**Comment by AlexeyAB** [comment]
1. yes

2. yes. `mask=` are indexes of anchors [0 - 9], i.e. current [yolo] layer will use anchors with numbers 6,7,8, i.e. `116,90,  156,198,  373,326`

3. random=1 is used during training, so Yolo will randomly resize neural network with coefficient /1.4 - x1.4 for each 10 iterations, it is part of data augmentation

**Comment by benn94** [comment]
Thank you for your kind reply Alexey. 
Could you tell me more about the coefficient? because i could not find its mention in the pape.

**Comment by AlexeyAB** [comment]
Just look at this code: https://github.com/AlexeyAB/darknet/blob/57e878b4f9512cf9995ff6b5cd6e0d7dc1da9eaf/src/detector.c#L137-L142

it will randomly resize the network not more than this coefficient 1.4 x /.

**Comment by benn94** [comment]
thank you @AlexeyAB
