### ISSUE TITLE
nvcc fatal  : Unsupported gpu architecture 'compute_61'

### ISSUE THREAD

**Issue by Panjok** [AlexeyAB/darknet#1579]
Hi Alexey.
I have problems compilating.
Previously I have compiled and worked fine with original darknet and openpose, using Opencv and gpu.
But when compiling your darknet fork with CUDDN=0 this is what compiler tells me:
nvcc fatal   : Unsupported gpu architecture 'compute_61'
Makefile:136: recipe for target 'obj/convolutional_kernels.o' failed
make: *** [obj/convolutional_kernels.o] Error 1

When compiling with CUDNN=1 i get:
In file included from ./src/activations.h:3:0,
                 from ./src/gemm.h:3,
                 from ./src/gemm.c:1:
./src/cuda.h:33:19: fatal error: cudnn.h: No such file or directory
compilation terminated.
Makefile:130: recipe for target 'obj/gemm.o' failed
make: *** [obj/gemm.o] Error 1

I have installed 9.2 cuda and god this error, then I've seen that you recommend 9.1 cuda. So I have removed nvidia and cuda. Installed latest nvidia drivers 396. I have two Gtx1060 btw. Then I've installed Cuda 9.1 but still got the same error. Could you please point me to the right direction ?

nvcc --version
Cuda compilation tools, release 7.5, V7.5.17

nvidia-smi
Driver Version: 396.54

**Comment by AlexeyAB** [comment]
@Panjok Hi,

> nvcc --version
> Cuda compilation tools, release **7.5**, V7.5.17
> 
> nvidia-smi
> Driver Version: 396.54

So you have CUDA 7.5.

Therefore, CUDA 9.1 ins't installed properly.

You should create symbolic link during installation of CUDA: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

And set path environment to the CUDA in `.bashrc` file. Google about it.

----


> When compiling with CUDNN=1 i get:
> In file included from ./src/activations.h:3:0,
> from ./src/gemm.h:3,
> from ./src/gemm.c:1:
> ./src/cuda.h:33:19: fatal error: cudnn.h: No such file or directory
> compilation terminated.
> Makefile:130: recipe for target 'obj/gemm.o' failed
> make: *** [obj/gemm.o] Error 1

You didn't set path environment to the cuDNN in the `.bashrc` file. https://medium.com/@mishra.thedeepak/cuda-and-cudnn-installation-for-tensorflow-gpu-79beebb356d2

**Comment by Panjok** [comment]
Thanks for the fast reply you were really helpful. I managed to compile first variant adding the PATH variable. As for CUDNN I think the problem was cudnn run time version, after installing dev version it worked fine. But not sure for 100% as I was experimenting with many things. May be you could add that into readme page next to Cudnn version if you know that for sure, that would help many newcomers. 
P.S. I have CUDA 9.2 and it works fine for me.
