### ISSUE TITLE
Why the weights file trained by this repository is 4 bytes smaller than the official one?

### ISSUE THREAD

**Issue by ZYT5ting** [AlexeyAB/darknet#1601]
the yolov3 weights file(248,007,044 bytes) trained by this command:
`darknet.exe detector train data/obj.data cfg/yolov3.cfg yolov3.conv.81`
is 4 bytes smaller than the official  weights file(248,007,048 bytes).
I also encountered the same problem when training yolov3-tiny weights file(also 4 bytes smaller than the official one).
I just changed the "random" value from 1 to 0 in yolov3.cfg.

does it relate to the [save_weights_upto  Function](https://github.com/AlexeyAB/darknet/blob/8e0b265067acb761f4667a1704cfe944caf564e4/src/parser.c#L958)??
can someone tell me why?Thanks!

**Comment by BlcaKHat** [comment]
hey  @ZYT5ting , how you trained your data, I have problem training data on colab, an you test my training setup on your machine 
#1569  have a look.

**Comment by ZYT5ting** [comment]
@BlcaKHat follow this: [https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects](url)  you can train your dataset too

**Comment by ZYT5ting** [comment]
@BlcaKHat follow this: [](https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects) you can train your dataset too

**Comment by ZYT5ting** [comment]
@BlcaKHat follow [https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects](this), you can train your datasets too.

**Comment by BlcaKHat** [comment]
I followed the tutorial, but getting error as mentioned in #1569 . can you test my dataset on your machine for few minutes. so I can figure out what is the issue.

**Comment by ZYT5ting** [comment]
I found out where the problem is.[here](https://github.com/AlexeyAB/darknet/blob/8e0b265067acb761f4667a1704cfe944caf564e4/src/parser.c#L975)  Change to
` fwrite(net.seen, sizeof(size_t), 1, fp);`

**Comment by AlexeyAB** [comment]
@ZYT5ting 

> I found out where the problem is.here Change to
> fwrite(net.seen, sizeof(size_t), 1, fp);

Yes, but it is a bad practice to use `size_t` for variables that are saved in files, because `size_t` will be 32-bit on 32-bit OS, and 64-bit on 64-bit OS. So weights-files trained on 64-bit OS will not work on 32-bit OS, and vice versa.

While `int ` always is 32-bit on any OS (64-bit / 32- bit).
