### ISSUE TITLE
How Many Classes Are Max On YOLO-V3 

### ISSUE THREAD

**Issue by syedmustafa54** [AlexeyAB/darknet#1604]
Hi,
@AlexeyAB 
 I have 50K Classes Can we Train this all classes on Yolo V3 asking this because Yolo V2 Supports only 9k Classes.
1. What is the Limit For this. 
2.If not any Idea How to deal with this.

**Comment by AlexeyAB** [comment]
@syedmustafa54 Hi,

1. There is no strict limit. 

2. Just the more classes - the less accuracy you will get. For example, if you want to increase accuracy - you can try to increase 2x numbers of filters, that will lead to 2x memory consumption and to a 2x slowdown in detection.

**Comment by syedmustafa54** [comment]
Thanks a lot
