### ISSUE TITLE
Use yolo_cpp_dll_no_gpu as dll in C#

### ISSUE THREAD

**Issue by saiprasadb** [AlexeyAB/darknet#161]
Hi Alexey AB,

Is it possible to use yolo_cpp_dll_no_gpu as dll in C#, Am trying to use yolo_cpp_dll_no_gpu as dll in C# by DllImport method, but I got below error
**Unable to find an entry point named 'Detector' in DLL 'yolo_cpp_dll.dll'**, can you please me on this.

Regards,
Sai Prasad

**Comment by AlexeyAB** [comment]
Hi,

You should use files `yolo_v2_class.cpp`, `yolo_v2_class.hpp`, `YoloBridge.cs` from the zip-archive in this comment: https://github.com/AlexeyAB/darknet/issues/118#issuecomment-316299027

**Comment by VanitarNordic** [comment]
@AlexeyAB 

is it possible to use the DLL in other programming languages such as VB/Vb.Net?

**Comment by saiprasadb** [comment]
Hi Alexey AB,

Thanks for the suggestion I have done the changes as per your suggestion its working.

**Comment by saiprasadb** [comment]
Hi Alexey AB,

Thanks for the suggestion I have done the changes as per your suggestion its working.

**Comment by rodrigojbp** [comment]
@saiprasadb Can you share your code?
