### ISSUE TITLE
Upstream fixed a bug in maxpool_layer

### ISSUE THREAD

**Issue by vinjn** [AlexeyAB/darknet#1614]
https://github.com/pjreddie/darknet/commit/b13f67bfdd87434e141af532cdb5dc1b8369aa3b#diff-9f8eac4bd4bbc86cabfe69de7a0a7a60

**Comment by AlexeyAB** [comment]
There is another one fix later: https://github.com/pjreddie/darknet/commit/9a4b19c4158b064a164e34a83ec8a16401580850
It was applied to this repo: https://github.com/AlexeyAB/darknet/commit/043289426b2d08d925fc1c980b0d2a01e2360e93

Discussion: https://github.com/pjreddie/darknet/issues/1018#issuecomment-410390180

**Comment by vinjn** [comment]
Cool, thx
