### ISSUE TITLE
How to convert cv::Mat to image_t

### ISSUE THREAD

**Issue by AyushP123** [AlexeyAB/darknet#1616]
Hi,
      I use opencv extensively in my application. I have started using darknet yolo for object detection for some parts of my application. I use yolo_cpp_dll built with CUDA support for inference, which is built without opencv. My application requires me to continuously run opencv Mat objects through yolo_cpp_dll. I tried converting Mat to image_t using the following code without any success.

```
#include <darknet/yolo_v2_class.hpp>
#include <opencv2/core.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/opencv.hpp>

using namespace std;
int main()
{
    cv::Mat img = cv::imread("something.png", 1);
    Detector abc("yolo.cfg", "yolo.weights");
    image_t darknet_image= {416, 416, 3, (float*)(img.data)};
    vector<bbox_t> boxes = abc.detect(darknet_image);
    return 0;
}
```
I did verify that I was able to read the image correctly. Would be grateful for your help in figuring out how to proceed.

**Comment by AyushP123** [comment]
The issue is that it crashes on calling .detect function.

**Comment by AlexeyAB** [comment]
Try this
```cpp
#include <darknet/yolo_v2_class.hpp>
#include <opencv2/core.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/opencv.hpp>

using namespace std;
int main()
{
    cv::Mat img = cv::imread("something.png", 1);
    Detector abc("yolo.cfg", "yolo.weights");
    std::shared_ptr<image_t> darknet_image = Detector::mat_to_image(img);
    vector<bbox_t> boxes = abc.detect(*darknet_image);
    return 0;
}
```

**Comment by AyushP123** [comment]
Hi,
        Thanks for your response. Here is the code I used for inference:

`#define OPENCV
#include <darknet/yolo_v2_class.hpp>
#include <iostream>
#include <opencv2/core.hpp>
#include <opencv2/dnn.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/opencv.hpp>

using namespace std;

int main()
{
    cv::Mat img = cv::imread("something.png", cv::IMREAD_COLOR);
    Detector abc("yolo.cfg", "yolo.weights");
    std::shared_ptr<image_t> darknet_image = Detector::mat_to_image(img);
    vector<bbox_t> boxes = abc.detect(*darknet_image, 0.2);
    cout << boxes.size() << endl;
    return 0;
}
` 
I realized that the result is way off the correct output. I am using nms = 0.45 and thresh = 0.2. Expected output is 3 boxes but the result is 362 boxes. I saw in the header files that resizing of the images was taking place internally so I didn't resize or rescale the image ( i.e. divide each element by 255 ). I have attached all the files [here](https://drive.google.com/drive/folders/1BRCatAc1v7haZriZpQ7Yl7b5xqF85iWg?ogsrc=32) for forward pass in windows using qt creator ( you can just unzip the temp_project.zip in c++ specific folder and use the .pro file to create the qt project ). I have also attached the python script being used for correct inference. I apologize for asking you to debug this.

**Comment by AlexeyAB** [comment]
```cpp
#define OPENCV
#include <darknet/yolo_v2_class.hpp>
#include <iostream>
#include <opencv2/core.hpp>
#include <opencv2/dnn.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/opencv.hpp>

using namespace std;

int main()
{
    cv::Mat img = cv::imread("something.png", cv::IMREAD_COLOR);
    Detector abc("yolo.cfg", "yolo.weights");
    vector<bbox_t> result_vec = abc.detect(img, 0.2);

    for (auto &i : result_vec) {
        //if (obj_names.size() > i.obj_id) std::cout << obj_names[i.obj_id] << " - ";
        std::cout << "obj_id = " << i.obj_id << ",  x = " << i.x << ", y = " << i.y 
            << ", w = " << i.w << ", h = " << i.h
            << std::setprecision(3) << ", prob = " << i.prob << std::endl;
    }

    return 0;
}
```

**Comment by toplinuxsir** [comment]
How to use python to convert cv::Mat to image_t? 
any examles ?Thanks !
