### ISSUE TITLE
What camera should I use For Taking Images and running Detection

### ISSUE THREAD

**Issue by syedmustafa54** [AlexeyAB/darknet#1646]
Hi all,
1. What is the best way to run detection without using a webcam because webcam quality is not that much grate so can I use Handycam as a webcam as shown [ted talk by  Joseph Redmon](https://youtu.be/Cgxsv1riJhI?t=322) how can i do this.
2. Can I use this handycam in opencv as `cap = cv2.VideoCapture(0)
`
3. I want to Purchese this handycam so want to be clear before purchesing it can i use it for traning and predection

**Comment by BlcaKHat** [comment]
yeah, most probably you can. just try to make it default webcam( follow stackoverflow).
