### ISSUE TITLE
Build fails on MSVS 2017, Windows 10 with CUDA 10.0, CUDNN 7.3 and OpenCV 3.4.3

### ISSUE THREAD

**Issue by DarthVi** [AlexeyAB/darknet#1660]
I've tried following the steps needed to compile the project with CUDA version different from 9.1 and it didn't work. I even tried to partially follow the guide on Microsoft's blog (this one: https://blogs.msdn.microsoft.com/uk_faculty_connection/2018/05/03/running-yolo-v2-on-the-microsoft-data-science-virtual-machine/ ), but using CUDA 10.0 instead of 9.1 proposed by them.
Still not working. I'll attach the compiler messages and point out some of the errors in the following lines.

There are errors like
`1>c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.11.25503\include\cstdint(9): error C2061: syntax error: identifier 'std' (compiling source file ..\..\src\cifar.c)
1>c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.11.25503\include\cstdint(9): error C2059: syntax error: ';' (compiling source file ..\..\src\cifar.c)
1>c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.11.25503\include\cstdint(9): error C2449: found '{' at file scope (missing function header?) (compiling source file ..\..\src\cifar.c)
1>c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.11.25503\include\cstdint(49): error C2059: syntax error: '}' (compiling source file ..\..\src\cifar.c)`

Moreover there are a lot of error like the following one:
`1>c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.11.25503\include\type_traits(432): error C4233: nonstandard extension used: '__is_union' keyword only supported in C++, not C (compiling source file ..\..\src\cifar.c)`

Is there any way to compile everything without resorting to use MSVS 2015 and CUDA 9.1?

This is the whole build output log
[darknetCompileLog.txt](https://github.com/AlexeyAB/darknet/files/2417069/darknetCompileLog.txt)

I will really appreciate any help you can provide.

**Comment by vinjn** [comment]
OpenCV 3.4.3 is not supported, check
https://github.com/AlexeyAB/darknet#how-to-compile-on-windows

**Comment by DarthVi** [comment]
Thanks, I missed that warning.

Anyway I managed to get it working not only by downgrading OpenCV to 3.4.0 but also by switching to CUDA 9.1. With CUDA 10.0 I get an error about cudaThreadSynchronize being deprecated which, well, since it's an error and not a warning, doesn't allow the build process to complete successfully.

**Comment by AlexeyAB** [comment]
@DarthVi 


> With CUDA 10.0 I get an error about cudaThreadSynchronize being deprecated


Yes, `cudaThreadSynchronize()` was removed 9 days ago: https://github.com/AlexeyAB/darknet/commit/c0e2512af2a4e3e29f61e383e78ac346b8165044#diff-ee485e80dbd4792e05ef21a4b7436b6bL2149

So just update your code from GitHub, and you can try use CUDA 10

**Comment by DarthVi** [comment]
@AlexeyAB thanks, it worked
