### ISSUE TITLE
darknet detector map fails with "CUDA Error: invalid argument" after loading the network weights

### ISSUE THREAD

**Issue by dweemx** [AlexeyAB/darknet#1666]
I compiled today darknet with:
```
GPU=1
CUDNN=1
```
with CUDA version 9.1.85 on CentOS Linux release 7.4.1708 (Core).
I've already a trained model and wants to compute the mAP metric of my model using:
```
darknet detector map cfg/my_data.data cfg/my_.cfg backup/model_1000.weights
```
But everytime I run the above command, I hit this error: 
```
Total BFLOPS 171.582 
Loading weights from backup/model_1000.weights...
 seen 64 
Done!
4
CUDA Error: invalid argument
darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
Aborted (core dumped)
```
After a few debugging step, it seems that the error is triggered at https://github.com/AlexeyAB/darknet/blob/e203ab9046732c9c000a6ded1b14c4f2b10bc496/src/detector.c#L645 

Then I tried darknet using CPU by compiling it with:
```
GPU=0
CUDNN=0
...
AVX=1
OPENMP=1
```
and it works perfectly although it's slow.

**Comment by AlexeyAB** [comment]
@mase5 

* Do you get this error if you use `GPU=1 CUDNN=0` ?

* Can you compress  your 3 files: `my_.cfg`, `my_data.data` and your `valid.txt` and attach them to your message?

* Can you set `train=` the same as `valid=` in your `my_data.data` and successfully calculate anchors? `./darknet detector calc_anchors cfg/my_data.data -num_of_clusters 9 -width 416 -height 416`

**Comment by AlexeyAB** [comment]
@wzjiang Just try another CUDA and cuDNN version.

**Comment by mase5** [comment]
Just recompiled darknet with the same settings above (initial message) and now it's working, weird. I still don't understand how I got there... 
@AlexeyAB so I didn't check what you suggested. Thanks though!
