### ISSUE TITLE
How is probability calculated?

### ISSUE THREAD

**Issue by erlendhade** [AlexeyAB/darknet#1669]
Hi @AlexeyAB 

Could you explain how probability in `show_console_result` from `yolo_console_dll.cpp` is calculated?
I know its called using `i.prob`, but how is this number calculated?

**Comment by erlendhade** [comment]
Do you know @AlexeyAB ?

As I have understood from the paper and other resources the final probability score displayed in YOLO is supposed to be the class probability times the confidence score of the object. But the papers explain that the confidence score of wheather or not there is an object present in the box is P(object)*IOU. 

The thing i cant figure out though, is that during testing on for example, video, there is no ground truth box to calculate IOU. How can object confidence, and consequently class probability be calculated?

**Comment by AlexeyAB** [comment]
@erlendhade Hi,

> the class probability times the confidence score of the object

Yes, `Probability = objectness(T0) * the_highest_class_probability`

> But the papers explain that the confidence score of wheather or not there is an object present in the box is P(object)*IOU.

Something like this is used only during Training. Not for detection.


For Detection is used: `Probability = objectness(T0) * the_highest_class_probability`

**Comment by erlendhade** [comment]
OK

Thank you for your insights!
