### ISSUE TITLE
WordTree of YOLO9000?

### ISSUE THREAD

**Issue by Ken2yLiu** [AlexeyAB/darknet#167]
Where can I find the WordTree of YOLO9000?
I want to fine-tine from the YOLO9000 weights but detect my own objects, in this case, I would like to check out if my objects is contained in the WordTree of YOLO9000.
Thanks

**Comment by AlexeyAB** [comment]
* `9k.tree` - **WordTree**  - `<label> <parent_it>`, if `parent_id == -1` then this label hasn't parent: https://raw.githubusercontent.com/AlexeyAB/darknet/master/build/darknet/x64/data/9k.tree

* `coco9k.map` - map the categories from MSCOCO to WordTree `9k.tree`: https://raw.githubusercontent.com/AlexeyAB/darknet/master/build/darknet/x64/data/coco9k.map

* `combine9k.data` - data file, there are paths to: 9k.labels, 9k.names, inet9k.map, (change path to your `combine9k.train.list`): https://raw.githubusercontent.com/AlexeyAB/darknet/master/build/darknet/x64/data/combine9k.data

* `9k.labels` - 9418 labels of objects: https://raw.githubusercontent.com/AlexeyAB/darknet/master/build/darknet/x64/data/9k.labels

* `9k.names` -
9418 names of objects: https://raw.githubusercontent.com/AlexeyAB/darknet/master/build/darknet/x64/data/9k.names

* `inet9k.map` - map the categories from ImageNet to WordTree `9k.tree`: https://raw.githubusercontent.com/AlexeyAB/darknet/master/build/darknet/x64/data/inet9k.map

**Comment by Ken2yLiu** [comment]
@AlexeyAB Thanks!
