### ISSUE TITLE
mAP calculation for yoloV2 and yoloV2-tiny-voc

### ISSUE THREAD

**Issue by hcharaya** [AlexeyAB/darknet#1670]
I have taken the latest config and weigths file from https://pjreddie.com/darknet/yolov2/ and used https://github.com/Cartucho/mAP/tree/master to calculate mAP with considering difficult ground truths however i am getting around 73% for yolov2-voc and around 53% for tiny yolov2-voc which is around 4% inferior to mAP mentioned at https://pjreddie.com/darknet/yolov2/. I have used following command to generate the prediction for 4952 VOC 2007 test images ./flow --imgdir sample_img/ --model cfg/yolov2-tiny-voc.cfg --load bin/yolov2-tiny-voc.weights --json --gpu 1.0 --threshold 0.001.
./flow --imgdir sample_img/ --model cfg/yolov2-voc.cfg --load bin/yolov2-voc.weights --json --gpu 1.0 --threshold 0.001

Please let me know if i missed something

**Comment by AlexeyAB** [comment]
* Do you use network resolution 416x416?

* What mAP can you get by using this manual? https://github.com/AlexeyAB/darknet#how-to-calculate-map-on-pascalvoc-2007

**Comment by hcharaya** [comment]
- Do you use network resolution 416x416?
   Yes

- What mAP can you get by using this manual? https://github.com/AlexeyAB/darknet#how-to-calculate-map-on-pascalvoc-2007
   I used the above mentioned method and found mAP was around 75.8% and due to this i could figure out that there was label name mismatch for "diningtable" prediction which was causing around 4% drop in mAP. Thanks a lot for your kind support.

**Comment by AlexeyAB** [comment]
What mAP can you get now by using this script https://github.com/Cartucho/mAP/tree/master ?
