### ISSUE TITLE
this layer0 feature map look like OK?TKS!

### ISSUE THREAD

**Issue by yongcong1415** [AlexeyAB/darknet#1676]
Hi, i am monitor the feature map and save it,the picture is so 'RED',is OK?

![image](https://user-images.githubusercontent.com/16781337/46182166-bb04c800-c2fc-11e8-9f1a-93170d782419.png)

![image](https://user-images.githubusercontent.com/16781337/46182227-04edae00-c2fd-11e8-83c3-8fb64b455422.png)

**Comment by AlexeyAB** [comment]
@yongcong1415 Hi,
Yes, this is ok.

You can change this line: https://github.com/AlexeyAB/darknet/blob/67f33ff5dc4bf489bcd9a0cd25e146ffddc92e18/src/network_kernels.cu#L77
to these 3 lines - to show black-white images instead of black-red:
```cpp
                memcpy(img.data, l.output + l.out_w*l.out_h*j, l.out_w*l.out_h * 1 * sizeof(float));
                memcpy(img.data + l.out_w*l.out_h * 1, l.output + l.out_w*l.out_h*j, l.out_w*l.out_h * 1 * sizeof(float));
                memcpy(img.data + l.out_w*l.out_h * 2, l.output + l.out_w*l.out_h*j, l.out_w*l.out_h * 1 * sizeof(float));
```

**Comment by yongcong1415** [comment]
thanks very much,so good;

**Comment by aluds123** [comment]
@yongcong1415  @AlexeyAB 
It can only save 32 pictures at once in my test.
Can I save all layers' feature maps at once?
Thanks.

**Comment by aluds123** [comment]
@yongcong1415  @AlexeyAB 
Can I choose a folder for feature maps to save?
