### ISSUE TITLE
different plateform different result

### ISSUE THREAD

**Issue by wzjiang** [AlexeyAB/darknet#1677]
I meet some trouble when I train the yolov3-tiny. I train yolov3 tiny in 1080Ti with cudnn and cuda. I have a correct result. But I have a error result when I test without cudnn or "cudnn and cuda". Can you give me some help? Thanks you very much.

**Comment by wzjiang** [comment]
![1538124819 1](https://user-images.githubusercontent.com/26684904/46198452-16f04080-c33f-11e8-88fe-76493a7b5b48.png)

**Comment by wzjiang** [comment]
![Uploading TM[0IC)$XNJ(T@9KKHA4V@I.jpg…]()

**Comment by wzjiang** [comment]
But when I train model by cfg/yolov3-voc.cfg, every thing is normal. The result is perfect.

**Comment by wzjiang** [comment]
![y 7s4vr sy6f6e0 f 48](https://user-images.githubusercontent.com/26684904/46198847-042a3b80-c340-11e8-94fb-7157878a3a27.jpg)

**Comment by wzjiang** [comment]
![tm 0ic xnj t 9kkha4v i](https://user-images.githubusercontent.com/26684904/46198861-09878600-c340-11e8-890c-03c9e50eb3dc.jpg)

**Comment by AlexeyAB** [comment]
* Do you use this https://github.com/AlexeyAB/darknet or https://github.com/pjreddie/darknet repsoitory?

* Do you use the latest version of this repository?

* Did you train your own model? And what GPU and OS did you use for this?

* Do you get good results when you try to detect by using default weights-file? https://pjreddie.com/media/files/yolov3-tiny.weights

* Did you use 32-bit OS or 64-bit OS for TX2 and TX1?

* Do you use OPENMP=1 AVX=1 when you set GPU=0 CUDNN=0?

**Comment by wzjiang** [comment]
Thanks for your reply. I use the latest version of https://github.com/pjreddie/darknet repsoitory.  I get the good results when I detect by using default weights-file（https://pjreddie.com/media/files/yolov3-tiny.weights）.OS for TX2 and TX1 is 64-bit.（aarch64）I set OPENMP=0 AVX=0 when I set GPU=0 CUDNN=0。

**Comment by AlexeyAB** [comment]
Try to train by using the latest version of this repository. https://github.com/AlexeyAB/darknet

**Comment by wzjiang** [comment]
thank you

**Comment by wzjiang** [comment]
AlexeyAB, I find I have the error result（different plateform different result） when I train yolov3 in my server1. But there is no problem when I train yolo in other server. I dont kown why. And I meet another trouble with I test in the tx1 with GPU=1 CUDNN=1(CUDA Error: invalid argument). I have a normal result when I use GPU=1 CUDNN=0. Can you give me some help?

**Comment by AlexeyAB** [comment]
@wzjiang 

> I find I have the error result（different plateform different result） when I train yolov3 in my server1.

What GPU, CUDA and cuDNN version do you use on the server1?

----

> And I meet another trouble with I test in the tx1 with GPU=1 CUDNN=1(CUDA Error: invalid argument).

What CUDA and cuDNN version do you use on the TX1?


(there is GPU (GM20B) Maxwell 256 Cores - CC 5.3)

**Comment by wzjiang** [comment]
GPU is 1080Ti, CUDA is 8.0 and cuDNN is libcudnn.so.5 in my server1. CUDA is 8.0 and cuDNN is libcudnn.so.5 in the tx1.

**Comment by AlexeyAB** [comment]
Try to use

* CUDA 9.1 https://developer.nvidia.com/cuda-91-download-archive


* cuDNN v7.1.3 (April 17, 2018), for CUDA 9.1 https://developer.nvidia.com/rdp/cudnn-archive#a-collapse713-91

**Comment by wzjiang** [comment]
Thanks you, AlexeyAB. I use a cuda8.0 and cudnn 6.0 suitable for TX1. And I solved the problem. I have another problem that Which model is faster in Xnor version and tiny version ？ Or is there a faster model? If Xnor is the fastest. Where can I find its pre-training model?

**Comment by AlexeyAB** [comment]
@wzjiang 

Currently XNOR implementation is experimental. 

Just use https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov3-tiny.cfg it is more optimal (accuracy/speed) than any SSD.
If you want to increase speed, try to reduce `width=320 height=320` or 224x224 in your cfg-file.

**Comment by wzjiang** [comment]
thanks
