### ISSUE TITLE
How to debug Segmentation Fault - Core dump issues?

### ISSUE THREAD

**Issue by shriprateek** [AlexeyAB/darknet#1678]
I trained my yolov3 with 2 classes and then till 7700 iterations I reached 69% map on validation set.
But while running the demo on a test clip I get this error of segmentation fault. I am not getting this error while testing on a single image.

Segmentation fault (core dumped)

I am not getting this error while running demo with same code on different classes (num_classes =14).
I am attaching the cfg and names files, let me know If I missed something.

[tad_yolov3_2_cfg.txt](https://github.com/AlexeyAB/darknet/files/2427498/tad_yolov3_2_cfg.txt)
[tad_yolov3_2_names.txt](https://github.com/AlexeyAB/darknet/files/2427499/tad_yolov3_2_names.txt)

**Comment by AlexeyAB** [comment]
Can you share your obj.data file?

And what command do you use for detection on video?

Try to use another video file.

**Comment by shriprateek** [comment]
I have faced same issue on multiple video clips plus the same video clip works for the model trained on same data but divided into 14 classes.  I validated the data with yolo mark also.

Attaching the data file also. 

[tad_yolov3_2_data.txt](https://github.com/AlexeyAB/darknet/files/2429052/tad_yolov3_2_data.txt)

Below is the command I used for it:
./darknet detector demo tad_yolov3_2.data cfg/tad_yolov3_2.cfg  tad_yolov3_2_7700.weights  IIITJn-IIIT_15.MP4  -out_filename iiitjn_iiit_15.avi -dont_show

**Comment by shriprateek** [comment]
Thanks, I missed out on changing the number of classes to 2 in data file, it was causing the segmentation fault. Is there any documentation available which can help browsing through the code or debug such faults?

**Comment by AlexeyAB** [comment]
>  Is there any documentation available which can help browsing through the code or debug such faults?

Isn't yet.
