### ISSUE TITLE
Training my own data for small object detection

### ISSUE THREAD

**Issue by ChuckGithub** [AlexeyAB/darknet#168]
Hi,Alex
    I want to train a model specifically for pedestrian detection,How to train a single class of small object detection model? what's network should i use? Do I need to modify the source code? 

This is the result of training with the person class in the voc2007 and voc2012 datasets

I modified the voc_label.py file
![12](https://user-images.githubusercontent.com/24219758/29618425-b38f1dd4-884a-11e7-9c1e-32a2c876da2f.png)

Training process [https://github.com/AlexeyAB/darknet#how-to-train-pascal-voc-data](https://github.com/AlexeyAB/darknet#how-to-train-pascal-voc-data)
![111](https://user-images.githubusercontent.com/24219758/29618426-b3955848-884a-11e7-8e5e-42e74cc8e918.png)

**Comment by AlexeyAB** [comment]
Hi @ChuckGithub 

1. What cfg file did you use  `yolo-voc.2.0.cfg` or  `yolo-voc.cfg` ?

2. What command line did you use for training?

3. Did you change **`classes=1`** in your `voc.data` file?

4. Did you do such changes in `yolo-voc.2.0.cfg` file to **`classes=1` and `filters=30`**? https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

     * change line batch to [`batch=64`](https://github.com/AlexeyAB/darknet/blob/master/build/darknet/x64/yolo-voc.2.0.cfg#L2)
     * change line subdivisions to [`subdivisions=8`](https://github.com/AlexeyAB/darknet/blob/master/build/darknet/x64/yolo-voc.2.0.cfg#L3)
     * change line `classes=20` to your number of objects
     * change line #237 from [`filters=125`](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolo-voc.2.0.cfg#L224) to `filters=(classes + 5)*5` (generally this depends on the `num` and `coords`, i.e. equal to `(classes + coords + 1)*num`)

5. To train for small objects you can increase network resolution - bit it will be decrease speed of detection. Change `width=832 height=832 random=0` in your cfg-file before training, and use it after training too.

**Comment by ChuckGithub** [comment]
Yes,I use `yolo-voc.2.0.cfg` use command `darknet.exe detector train data/obj.data yolo-voc.2.0.cfg darknet19_448.conv.23` for training , and change `classes = 1` in `obj.data` and `yolo-voc.2.0.cfg` and change `filters=30`.
The above description of these I have modified,as the fifth point, I have not tried.Can voc2007 and voc2012 data sets meet the needs of small object detection? If it can't,How about caltech pedestrian dataset?Does the training only need to modify the command line without modifying the C source code?

**Comment by AlexeyAB** [comment]
1. About small objects, if you use PascalVOC training dataset that doesn't relate with your test images (has different size of images and objects), then just `width=832 height=832 random=1` - train with these parameters in cfg and test detection with the same cfg.

----

1.1. A more subtle selection of parameters can be:

* if you know that in training dataset: image_width=500, average object_width=20
* and if you know that in your test-detection dataset: image_width=1920, average object_width=10

Then:
* you should train with network resolution (set before training): width=160 height=160 random=0  (i.e. `160 ~= (20/500) / (10/1920)` )
* you should detect with network resolution (set after training): width=1088 height=1088


----

2. Also it looks like that something went wrong - **check your dataset by using Yolo-mark:** https://github.com/AlexeyAB/Yolo_mark

![111](https://user-images.githubusercontent.com/24219758/29618426-b3955848-884a-11e7-8e5e-42e74cc8e918.png)

**Comment by ChuckGithub** [comment]
OK,I got it.I will try it again.Thank you!

**Comment by ChuckGithub** [comment]
Hi,Alex
When I get the small object's model, I want use` yolo` as `DLL` ，Do I need to recompile `yolo_cpp_dll.sln`?

**Comment by AlexeyAB** [comment]
No, you only should change paths to 2 your files: cfg and weights: https://github.com/AlexeyAB/darknet/blob/195ba5dee284d41dfbb8022d025ae77b75e1b00c/src/yolo_console_dll.cpp#L71

And then recompile your application (for example `yolo_console_dll.sln`).

**Comment by ChuckGithub** [comment]
OK

**Comment by ChuckGithub** [comment]
Hi,Alex
    I used `yolo-voc.2.0.cfg` to train for 1 class, but I could not detect the object border with `Detector detector ('yolo-voc.2.0.cfg', 'yolo-obj_20000.weights')`.

**Comment by AlexeyAB** [comment]
@ChuckGithub Hi, set correct names and paths to files, or copy cfg/weights files near to exe.

**Comment by ChuckGithub** [comment]
It works.Thanks.
