### ISSUE TITLE
Teaching yolo one image 

### ISSUE THREAD

**Issue by hazemati** [AlexeyAB/darknet#1682]
Hey, 
I'm a newb here, never done any kind of machine learning before a couple weeks ago. I'm trying to train yolo. As a test, I'm trying to train it with 1 image. It takes more than a half hour, and instead of 1 image it says that it's training 1280 images (even though I feed 1). Can you please give me some insight as to where it's getting that number from?

**Comment by AlexeyAB** [comment]
@hazemati Hi,

It uses one the same image many times, just automatically changes color, size and aspect ratio of this image (google: data augmentation).

**Comment by hazemati** [comment]
also, I was wondering what the smallest image size is that Yolo can detect?

**Comment by AlexeyAB** [comment]
>  In other words, how do I train yolo to deal with scale invariance?

You use many images with different object sizes for training. Partially it can be solved by automatic data augmentation that I mentioned above.


> also, I was wondering what the smallest image size is that Yolo can detect?

1x1 pixels after that your image is resized to the 416x416 (width and height in your cfg-file)

**Comment by hazemati** [comment]
how many images do you recommend I use?

**Comment by AlexeyAB** [comment]
2000 images per each class.

**Comment by hazemati** [comment]
Hey the way, I'm very impressed with your responsiveness. I really appreciate the help!

**Comment by hazemati** [comment]
Just to make sure I understand, you want images 2000 class, that does not include the images that yolo is going to generate while it's training?

**Comment by AlexeyAB** [comment]
Yes.
If you have 5 classes, then you should have 10 000 files (images). And you should train at least 10 000 iterations.
