### ISSUE TITLE
Optimization for multiple streams

### ISSUE THREAD

**Issue by bogdanul2003** [AlexeyAB/darknet#169]
Hi,

You have more experience with the code and I would like to know your opinion on how to use cuda streams in order to process 2 video streams in parallel.
I noticed that running the demo on a gtx 1080 uses 40-50% of GPU compute time at 40-45 FPS. Theoretically you could reach 100% GPU utilization by processing 2 video streams in parallel at almost the same frame rate. 
Can you give some hints on what functions I need to look into in order to setup two cuda streams that will process the frames from the 2 videos in parallel? For the beginning I would create two network structures in the GPU memory and each stream would use it's own data structure.

Thanks,
Bogdan

**Comment by AlexeyAB** [comment]
Hi,

You shouldn't think about CUDA streams, because for each video frame used about ~150 CUDA-kernels, so these kernels will alternate automatically, evenly distributing the GPU-load.

Just use 2 commands that uses different input video streams and different output video streams (res1.avi and res2.avi), for example - in 2 individual terminals/cmd, for example:
* `darknet.exe detector demo data/voc.data yolo-voc.cfg yolo-voc.weights http://192.168.0.80:8080/video?dummy=param.mjpg -i 0 -out_filename res1.avi`

* `darknet.exe detector demo data/voc.data yolo-voc.cfg yolo-voc.weights http://192.168.0.81:8080/video?dummy=param.mjpg -i 0 -out_filename res2.avi`

----

Or if you want to use your own application, then you can just compile Darknet as DLL or SO library: * 
* Linux `LIBSO=1`: https://github.com/AlexeyAB/darknet/tree/195ba5dee284d41dfbb8022d025ae77b75e1b00c#how-to-compile-on-linux
* Windows `yolo_console_dll.sln`: https://github.com/AlexeyAB/darknet/tree/195ba5dee284d41dfbb8022d025ae77b75e1b00c#how-to-use-yolo-as-dll

Then link DLL/SO to your application, and in your application create 2 objects:
* `Detector detector1("yolo-voc.cfg", "yolo-voc.weights");`
* `Detector detector2("yolo-voc.cfg", "yolo-voc.weights");`

And use these 2 for-loops in 2 different threads:   https://github.com/AlexeyAB/darknet/blob/195ba5dee284d41dfbb8022d025ae77b75e1b00c/src/yolo_console_dll.cpp#L94

* for 1st video stream use input filename1 and detector1:
```cpp
for (cv::VideoCapture cap(filename1); cap >> frame, cap.isOpened();) {
...
td = std::thread([&]() { thread_result_vec = detector1.detect(det_frame, 0.24, true); ready_flag = true; });
```

* for 2nd video stream use input filename2 and detector2:
```cpp
for (cv::VideoCapture cap(filename2); cap >> frame, cap.isOpened();) {
...
td = std::thread([&]() { thread_result_vec = detector2.detect(det_frame, 0.24, true); ready_flag = true; });
```

**Comment by bogdanul2003** [comment]
Hi Alexey,

Thank you for your reply. I took some time to analyse your proposal with two demo instances. At a first run I've got 25 FPS at maximum per instance, half of fps when I was running a single instance. This signals a lack of parallelism.
Next I've used nvprof and nvidia visual profiler to profile two simultaneous instances and I noticed that all kernels are scheduled on the default cuda stream, stream 0. The 150 kernels used per frame alternate on the same cuda stream but a GTX 1080 video card has 20 streaming multiprocessors which means it can run 20 cuda streams in parallel but the demo application uses the same stream (the default one) for all instances that you open.
In order to run a kernel on different cuda stream you need to specify a stream number when you lunch a cuda kernel. For a short description please take a look at this link:
https://devblogs.nvidia.com/parallelforall/gpu-pro-tip-cuda-7-streams-simplify-concurrency/
So the GPU will not dispatch work in parallel unless you instruct it to do so because it can't figure out data dependencies.

**Comment by AlexeyAB** [comment]
@bogdanul2003 Hi, did you try `yolo_console_dll.sln`?

Try to update your code from this fork and recompile. I added some modifications.

Any one CUDA-kernel-function can use all CUDA-Cores of GPU if used number of BLOCKS equal to SM (Streaming multiprocessors).

**Comment by bogdanul2003** [comment]
I use Ubuntu so I don't have access to Visual Studio. The changes you have made are also for linux ? Can you tell me a commit ID with your modifications ?

**Comment by AlexeyAB** [comment]
Yes, this commit for both Windows and Linux: https://github.com/AlexeyAB/darknet/commit/76276fdbeade20f30f9474e32a289dba5c09d920

After update from this commit, you should use such command: `./darknet detector demo data/voc.data yolo-voc.cfg yolo-voc.weights test.mp4 -i 0`

----

Using this fork I get ~37 FPS on GTX970 and ~40 FPS on GTX1060 Notebook on both Windows and Linux.

Your bottleneck in CPU:

* or save output video: https://github.com/AlexeyAB/darknet/blob/195ba5dee284d41dfbb8022d025ae77b75e1b00c/src/image.c#L548
* or capture video from video-file or video-camera: https://github.com/AlexeyAB/darknet/blob/195ba5dee284d41dfbb8022d025ae77b75e1b00c/src/demo.c#L60

With the new commit output video stored only when used optional flag `-out_filename res.avi`. Don't use it.

**Comment by AlexeyAB** [comment]
@bogdanul2003 Also:
1. Do you use this fork https://github.com/AlexeyAB/darknet 
or origianl fork https://github.com/pjreddie/darknet ?
2. Do you use video-file or video-stream from Web/Network-camera?

**Comment by bogdanul2003** [comment]
Hi, 
1. I use your fork. 
2. I use video file and I don't need to output the result in a file. 

You get ~40 FPS per instance with two instances running in the same time? 
I looked at the commit ID 76276fd but it's related to output file functionality. I'm not using an output file. 
I looked in the code and I didn't find any kernel call where the cuda stream is specified.

**Comment by AlexeyAB** [comment]
@bogdanul2003 Hi, It's too bad that you did not try the last commit.

* I get **40 FPS for 1 instance** and ~100% GPU-usage, or 20 FPS per instance for 2 instances on **GTX1060** Notebook 
* So on **GTX1080** you should get about **100 FPS** using this fork and `yolo-voc.cfg` and `yolo-voc.weights` with network size 416x416
* If you don't use last commit - it forces the video output to file - **this will limit the FPS**
* The **drop in performance** in your case **isn't related to usage of CUDA-streams**.
* CUDA-streams should be used only for computation overlaping:
    * overlap: computation and data-transfer
    * overlap: computation of 2 functions with number of BLOCKs smaller than CUDA-SMs (or with small number of threads, when latency to GPU-RAM / CPU-RAM can't be hided using fine-grained-multithreading/circuit-slowing)
    * overlap: 2 functions, one of which takes a little time (and can't wait 2nd function), and the other takes a lot of time

Use GCC profiling to find you bottleneck on CPU.

**Comment by groot-1313** [comment]
Hi, 
I am facing a similar issue. I have trained a tiny yolo v2 model.
I have not built darknet using opencv, so I cannot use `./darknet detector demo ..` .
So, I am using the script `darknet.py` with a few modifications to run on a video file. I am timing only a single line to get the FPS - 
`detections = detect(netMain, metaMain, frame, thresh)  `
I do this for 5000 frames and get the FPS as - `total_frames/total_time_seconds` .
When I run the python script from one terminal on a GTX 1080 TI, I get an FPS of 109 frames per second. 
When I run the python script from 2 separate terminals simultaneously, they both print an FPS of 90 frames per second. 

I would like to run 2 detection streams with no loss in FPS. How can I optimise further?

**Comment by wting861006** [comment]
@AlexeyAB Hi
I want to know if python can do it?I have 2 1080ti.
