### ISSUE TITLE
video not detecting which is produced from a set of trained and detecting images 

### ISSUE THREAD

**Issue by rajvishnu27** [AlexeyAB/darknet#1698]
Hello,
I have this issue where 
1) i have trained yolo on a custom dataset of images, on testing the images are perfectly detected 
2) same set of images when i convert as video frames yolo fails to detect the objects in the video frames

**Comment by AlexeyAB** [comment]
@rajvishnu27 Hi,

Set `#define FRAMES 1` here https://github.com/AlexeyAB/darknet/blob/6c8642b3eb19b68a11f3fae6a55bbfd528a800d3/src/demo.c#L18

Also may be quality of video worse than quality of images, or you do something wrong.

**Comment by rajvishnu27** [comment]
Hello Alexey ,

I have change the frames value defined to 1 and it is working perfectly.

Thanks for the prompt reply.

Regards

Vishnu Raj
