### ISSUE TITLE
Train Yolo2 with custom data, yolo-obj.cfg file

### ISSUE THREAD

**Issue by VanitarNordic** [AlexeyAB/darknet#17]
Hello,

In the description you have mentioned: 

- change line` filters=425` to `filters=(classes + 5)*5`

inside `yolo-voc.cfg` , I could not find the ` filters=425` phrase. Several ` filters= ...` exist inside this file, which one should be modified? 
or I have to modify them all? 

I think you meant the last convolution layer

**Comment by AlexeyAB** [comment]
@VanitarNordic Thanks for note, I fixed it.

* if you edit VOC `yolo-voc.cfg` you should change  `filters=125` on line 224: https://github.com/AlexeyAB/darknet/blob/master/cfg/yolo-voc.cfg#L224
* if you edit COCO `yolo.cfg` you should change  `filters=425` on line 224: https://github.com/AlexeyAB/darknet/blob/master/cfg/yolo.cfg#L224
