### ISSUE TITLE
how to detect only two classes?

### ISSUE THREAD

**Issue by wanghua609** [AlexeyAB/darknet#170]
Hi,
 I have used yolo.weights, yolo.cfg  and coco.data downloaded from the website to detect. It seems that it detects about 80 classes and draw the boxes for the objects detected .   I want to detect only 3 kinds of objections, such as person, car and plane.  This means that I don't want other things such as dogs, cats to be detected and labled. How to realize this? 
Thanks a lot!

**Comment by AlexeyAB** [comment]
Hi,
Just change two lines in `image.c`:
1. `if (prob > thresh && (class == 0 || class == 6 || class ==14)) {`  https://github.com/AlexeyAB/darknet/blob/195ba5dee284d41dfbb8022d025ae77b75e1b00c/src/image.c#L191

2. `if (prob > thresh && (class == 0 || class == 6 || class ==14)) {`    https://github.com/AlexeyAB/darknet/blob/195ba5dee284d41dfbb8022d025ae77b75e1b00c/src/image.c#L241

Recompile, and use `yolo-voc.cfg` and `yolo-voc.weights` file for detection.

**Comment by wanghua609** [comment]
Yes, it works well via your method. There are another two questions:
1. It seems there will be labes such as "aeroplane, car ,person" displayed upon every box. How to delete these labes? I want to draw the boxes without labes, i.e just boxes without "person areoplane".
2. When I am training on voc2007 +2012. I want to train 3 classes, ie.person, car and plane. Do I need to delete the images that don't contain those 3 classes? If I don't delete them, will there be some negative results on the yolo-voc-final.weights?
Thanks a lot!
