### ISSUE TITLE
Segmentation fault when running map

### ISSUE THREAD

**Issue by ShurayukiHime** [AlexeyAB/darknet#1700]
Hi @AlexeyAB ,
I know you are very busy but could you please consider my issue.
I managed to train the network and now I would like to calculate map with the following command:
`./darknet detector map data/obj.data cfg/yolo-obj.cfg yolo-obj_9900.weights`.

My output prints all the layers of the network, then a series of numbers and eventually it crashes.

     103 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128 0.177 BF
     104 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256 1.595 BF
     105 conv     27  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x  27 0.037 BF
     106 yolo
     Total BFLOPS 65.312 
     Loading weights from yolo-obj_9900.weights...
     seen 64 
    Done!
    4
    8
    12
    16
    20
    24
    28
    32
    36
    40
    44
    48
    52
    56
    60
    64
    68
    72
    76
    80
    84
    88
    92
    96
    100
    104
    108
    Segmentation fault (core dumped)

I think that it crashes around here in the code even though I don't know why: https://github.com/AlexeyAB/darknet/blob/master/src/detector.c#L772 .
My paths for images and files should be okay since I can train the network, still here are some details:
- I compiled with GPU=1 but left everything else =0
- batch=64 and subdivision = 16
- classes = 4 and filters = 27
- obj.data:
    classes= 4
    train  = /home/diffie/AlexeyDarknet/data/train.txt
    valid  = /home/diffie/AlexeyDarknet/data/test.txt
    names  = /home/diffie/AlexeyDarknet/data/obj.names
    backup = backup/

Could you point me in the right direction, please?

**Comment by AlexeyAB** [comment]
@ShurayukiHime Hi,
* How many images do you have in the train.txt file?
* Remove empty last lines from `train.txt`

**Comment by ShurayukiHime** [comment]
Thank you for your fast reply!

> @ShurayukiHime Hi,
> 
>     * How many images do you have in the train.txt file?
> 
I have 445 lines.

>     * Remove empty last lines from `train.txt`

I double-checked, but there are no empty last lines.

**Comment by ShurayukiHime** [comment]
> @ShurayukiHime
> 
>     * Check the same for `test.txt`. And how many images inside `test.txt`?
> 
There are 223 lines, and no final empty line.

>     * Set `train = /home/diffie/AlexeyDarknet/data/test.txt` and do this command, does it work well?
>       `./darknet detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416`
> 
I tried this but it didn't work, most probably because I have no OpenCV installed (also I compiled with opencv = 0). The error message is:
`k-means++ can't be used without OpenCV, because there is used cvKMeans2 implementation`

Is it necessary to have OpenCV?
> 
> Also does this command work well?
> `./darknet detector recall data/obj.data cfg/yolo-obj.cfg yolo-obj_9900.weights`

This command works perfectly, also the number of images printed in the output matches with the number of images. Here is the last line:
`  222  1735  1803	RPs/Img: 9.10	IOU: 86.65%	Recall:96.23%`

Thank you for your time.

**Comment by AlexeyAB** [comment]
This is strange.

Can you run successfully this command?
`./darknet detector valid data/obj.data cfg/yolo-obj.cfg yolo-obj_9900.weights`

**Comment by joaomiguelvieira** [comment]
Hi @AlexeyAB,

I am also getting a segmentation fault when running map. However, I only get a segmentation fault if I specify both `test = test.txt` and `difficult = difficult.txt` in the `.data` file. If I merge these two files into one, only specify `test = test_and_difficult.txt` in the `.data` file and then run map, everything works fine.

**Comment by AlexeyAB** [comment]
@joaomiguelvieira Hi,

Do you use `difficult = difficult_2007_test.txt` for Pascal VOC dataset? https://github.com/AlexeyAB/darknet#how-to-calculate-map-on-pascalvoc-2007

Do you get seg-fault immideately?

**Comment by joaomiguelvieira** [comment]
@AlexeyAB,

No, I am using a different dataset called street view house numbers. Under the circumstances I described above, I get a segmentation fault when it reached the number of iterations equal to the number of images that I have on my `test.txt`. My best guess is that something wrong happens after processing the images in `test.txt` and before processing those in `difficult.txt`.

**Comment by AlexeyAB** [comment]
@joaomiguelvieira 

`Difficult` is implemented for Pascal VOC only.

Do you use `difficult.txt` for the required purpose - the same list of images as in test.txt, just the filenames are changed, and each correspnod `difficult_...txt` file contains bboxes for the objects which we shouldn't take into account during mAP calculation?

**Comment by joaomiguelvieira** [comment]
@AlexeyAB,

My bad, then I am using that file wrongly. I thought it had another purpose. Nevermind.
