### ISSUE TITLE
How do I find hte gencode arch for my GPU?

### ISSUE THREAD

**Issue by hazemati** [AlexeyAB/darknet#1701]
Hey, 
I'm using a GK210GL [Tesla K80] (I don't see that being supported in the makefile anywhere. I was wondering where I can get the ARCH (see below) for my GPU from? Is that from a spec sheet somewhere?   
ARCH= -gencode arch=compute_30,code=sm_30 \
      -gencode arch=compute_35,code=sm_35 \
      -gencode arch=compute_50,code=[sm_50,compute_50] \
      -gencode arch=compute_52,code=[sm_52,compute_52]

**Comment by AlexeyAB** [comment]
@hazemati Hi,

Usually is used `-gencode arch=compute_35,code=sm_35 ` for Tesla K80

----

Also you can try to use `-gencode arch=compute_37,code=sm_35` https://en.wikipedia.org/wiki/CUDA#GPUs_supported
CC 3.7 - GK210 - Tesla K80

**Comment by hazemati** [comment]
Sounds good. So, unrelated question, is it normal to spend an entire week or two training your model?

**Comment by AlexeyAB** [comment]
@hazemati Yes.
It depends on GPU and model. Also you should know, that if you have Tesla K80 in your computer (not in the cloud) then there are actually 2 GPUs in one board, so after 2000 iterations you can continue train by using 2 GPU - using this flag at the end of training command `-gpus 0,1`
https://github.com/AlexeyAB/darknet#how-to-train-with-multi-gpu


----

But much better to use not very expensive modern GPU: 
* Geforce GTX 1070 (Pascal)
* or Geforce RTX 2070 (Turing) - will be release in two weeks: https://www.nvidia.com/en-us/geforce/20-series/

**Comment by hazemati** [comment]
quick one for you, is there any way around having to manually annotate 2000 images for training?

**Comment by ali-babaei** [comment]
@AlexeyAB Hi,
Sorry, I know it's too late, but this appears in search results.
while compiling:
`-gencode arch=compute_37,code=sm_35`
gives error, but
`-gencode arch=compute_37,code=sm_37`
works fine.
