### ISSUE TITLE
Cant open Label File Error

### ISSUE THREAD

**Issue by goelsaksham** [AlexeyAB/darknet#1702]
Hi Alexey,

I have been using YOLO for some time now but I encountered this error for the first time (Could be because I am using Windows now instead of Linux to train the model).

The screenshot of the error is as follows:

![5350fbd9](https://user-images.githubusercontent.com/42523205/46370545-7b671480-c64b-11e8-8be8-92403d282174.PNG)

I hope you can help me find the reason for this problem.

My directory structure is as follows:
----
|
* | - darknet.exe
|
* | - data/
   * | - experiment/
     * | images (.bmp), label_files(.txt)
   * | training_data.txt
   * | validation_data.txt
   * | cfg_file.cfg
   * | metadata_file.data
   * | defect_names.names

My training and validation data files look something like:
     data\experiment\image1.bmp
     .....
     data\experiment\imagen.bmp

My metadata file looks something like this:
classes= 9
train  = data\training_data.txt
valid  = data\validation_data.txt
names = data\defect_names.names
backup = data\cfg_exp_1_backup_weights\

**Comment by AlexeyAB** [comment]
@goelsaksham 

Change this line: https://github.com/AlexeyAB/darknet/blob/6c8642b3eb19b68a11f3fae6a55bbfd528a800d3/src/data.c#L145
to this 
`printf("Can't open label file. (This can be normal only if you use MSCOCO): %s \n", filename);`
recompile, run training and show screenshot again.


Also can you run successfully this command?
`darknet.exe detector calc_anchors data/metadata_file.data -num_of_clusters 9 -width 416 -height 416`

**Comment by goelsaksham** [comment]
Hi Alexey,

Thanks a lot for your suggestion. As it turns out I didnt have some .txt files corresponding to the images that I listed in the training data file. I found this out and pasted every .txt file again. Now everything is working. Thanks a lot for helping me figure this out.
