### ISSUE TITLE
Error when compiling with OpenCV

### ISSUE THREAD

**Issue by raden** [AlexeyAB/darknet#1712]
Hi,

I enabled OpenCV in the make file, but I got the following error. 

./src/image.c:637:16: error: incompatible type for argument 2 of ‘cvSet’
     cvSet(img, CV_RGB(255, 255, 255), 0);
                ^~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make: *** [Makefile:130: obj/image.o] Error 1

Is there anything I could do to proceed with the clean compile?

Thanks!

**Comment by depauwjimmy** [comment]
I am using the version 3.4.3 and have the same error.
The fix above let me compile though.

**Comment by raden** [comment]
> edit ./src/image.c and add the following:
> 
> `#define CV_RGB(r, g, b) cvScalar( (b), (g), (r), 0 )`
> 
> you probably need to do the same for detector.c

Thank you, works for me.
It seems that in ./src/image.c I already saw `#define CV_RGB(r, g, b) cvScalar( (b), (g), (r), 0 )`
And putting in in ./src/detector.c solved the problem. Thank you!
