### ISSUE TITLE
Can't save webcam or video file results using -out_filename parameter

### ISSUE THREAD

**Issue by priyankasingh** [AlexeyAB/darknet#1713]
Hi,
I am trying to save output of webcam detection or video detection into a video file. I keep getting the following error:

``./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights -i 0 -out_filename test.mp4

Total BFLOPS 65.864 
Loading weights from yolov3.weights...
 seen 64 
Done!
Webcam index: 0
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
Video stream: 640 x 480

FPS:0.0
Objects:

person: 100% 
person: 37% 
HIGHGUI ERROR: V4L2: Unable to get property <unknown property string>(5) - Invalid argument
darknet: /builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:500: virtual bool CvVideoWriter_GStreamer::open(const char*, int, double, CvSize, bool): Assertion `fps > 0' failed.
Aborted (core dumped)
``

**I am using OpenCV2 version 3.4.0.14 and CUDA version 9.1, V9.1.85
I have used the latest master version and compiled using GPU, CUDNN and OpenCV**

This is the result of the command
''
$ v4l2-ctl --list-formats
ioctl: VIDIOC_ENUM_FMT
	Index       : 0
	Type        : Video Capture
	Pixel Format: 'MJPG' (compressed)
	Name        : MJPEG

	Index       : 1
	Type        : Video Capture
	Pixel Format: 'YUYV'
	Name        : YUV 4:2:2 (YUYV)
''

I want to save the output of detection done on videos (webcam stream, rtsp stream or video files).
Any help will be appreciated.

**Comment by AlexeyAB** [comment]
@priyankasingh Hi,

* Does this command work with input video-file?
`./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights input.mp4`
or this:
`./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights input.mp4 -i 0 -out_filename test.mp4`

* Does any other OpenCV application work with your web-cam?

**Comment by priyankasingh** [comment]
No, it doesn't. Running either of the command gives me the following error.

`Total BFLOPS 65.864 
Loading weights from yolov3.weights...
 seen 64 
Done!
video file: input.mp4
warning: GStreamer: Error opening bin
 (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:354)
 Video-stream stoped! 
Stream closed.
 Video-stream stoped! 
Stream closed.
CUDA Error: invalid argument
darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
Aborted (core dumped)
`

I use OpenCvVsometimes to save RTSP video stream (not from Darknet, this is a separate python script) and it works fine, it saves the video.

Do you think it's something wrong with my OpenCV?

**Comment by AlexeyAB** [comment]
> warning: GStreamer: Error opening bin (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:354) 
> 
> Do you think it's something wrong with my OpenCV?

May be yes.
Also try to build OpenCV without GStreamer.

**Comment by priyankasingh** [comment]
Hi Alexey,

I built the OpenCV 3.4.0 from source without the GStreamer this time and tried it again.

When I run the following command the detection works but the output test.mp4 file is not generated.

`$ ./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights -i 0 -out_filename test.mp4`

When I run the command 

`./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights input.mp4 -i 0 -out_filename test.mp4`

This error message is generated
```
Total BFLOPS 65.864 
Loading weights from yolov3.weights...
 seen 64 
Done!
video file: input.mp4
Unable to stop the stream: Inappropriate ioctl for device
 Video-stream stoped! 
Stream closed.
 Video-stream stoped! 
Stream closed.
CUDA Error: invalid argument
darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
```

I have installed ffmpeg but not GStreamer. What else can I do to fix this issue?

**Comment by visshvesh** [comment]
@priyankasingh : Did you find the solution on this error?
getting the same error when I run

./darknet detector demo data/dt.data yolov3-windturbine.cfg yolov3-windturbine_4500.weights test.mp4


**Unable to stop the stream: Inappropriate ioctl for device
 Video-stream stoped! 
Stream closed.
 Video-stream stoped! 
Stream closed.**
 @AlexeyAB

**Comment by priyankasingh** [comment]
@visshvesh No, I haven't managed to fix this issue yet. I have doing screen-capture to record the result videos but I would really like to fix this issue.

**Comment by AlexeyAB** [comment]
@priyankasingh 

* Do you use the latest version from GitHub?

* Does it work successfully for video-file intead of web-cam?
`./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights input.mp4 -i 0 -out_filename test.mp4`


* Try to comment this line: https://github.com/AlexeyAB/darknet/blob/9e2c894a32fa7cdfd1ee115be8e4184df3c96dbe/src/demo.c#L233
and un-comment another line: https://github.com/AlexeyAB/darknet/blob/9e2c894a32fa7cdfd1ee115be8e4184df3c96dbe/src/demo.c#L232-L238

**Comment by priyankasingh** [comment]
@AlexeyAB 
>     * Do you use the latest version from GitHub?

Yes, I am

>     * Does it work successfully for web-cam without saving videofile?
>       `./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights -c 0`

Yes, it does, without any errors.

>     * Does it work successfully for video-file intead of web-cam?
>       `./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights input.mp4 -i 0 -out_filename test.mp4`

No, it causes the following error:
` Total BFLOPS 65.864 
Loading weights from yolov3.weights...
 seen 64 
Done!
video file: input.mp4
Unable to stop the stream: Inappropriate ioctl for device
 Video-stream stoped! 
Stream closed.
 Video-stream stoped! 
Stream closed.
CUDA Error: invalid argument
darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
Aborted (core dumped)
`

>     * Try to comment this line:           
>             [darknet/src/demo.c](https://github.com/AlexeyAB/darknet/blob/9e2c894a32fa7cdfd1ee115be8e4184df3c96dbe/src/demo.c#L233)
          
>                Line 233
>             in
>             [9e2c894](/AlexeyAB/darknet/commit/9e2c894a32fa7cdfd1ee115be8e4184df3c96dbe)
>                        
>                 
>                  output_video_writer = cvCreateVideoWriter(out_filename, CV_FOURCC('D', 'I', 'V', 'X'), src_fps, size, 1); 
>                    
>       and un-comment another line:       
>           
>             [darknet/src/demo.c](https://github.com/AlexeyAB/darknet/blob/9e2c894a32fa7cdfd1ee115be8e4184df3c96dbe/src/demo.c#L232-L238)
>           
>           
>               Lines 232 to 238
>             in
>             [9e2c894](/AlexeyAB/darknet/commit/9e2c894a32fa7cdfd1ee115be8e4184df3c96dbe)
>           
>           
>           
>           
>       
>               
>                 
>                  //output_video_writer = cvCreateVideoWriter(out_filename, CV_FOURCC('H', '2', '6', '4'), src_fps, size, 1); 
>               
>       
>               
>                 
>                  output_video_writer = cvCreateVideoWriter(out_filename, CV_FOURCC('D', 'I', 'V', 'X'), src_fps, size, 1); 
>               
>       
>               
>                 
>                  //output_video_writer = cvCreateVideoWriter(out_filename, CV_FOURCC('M', 'J', 'P', 'G'), src_fps, size, 1); 
>               
>       
>               
>                 
>                  //output_video_writer = cvCreateVideoWriter(out_filename, CV_FOURCC('M', 'P', '4', 'V'), src_fps, size, 1); 
>               
>       
>               
>                 
>                  //output_video_writer = cvCreateVideoWriter(out_filename, CV_FOURCC('M', 'P', '4', '2'), src_fps, size, 1); 
>               
>       
>               
>                 
>                  //output_video_writer = cvCreateVideoWriter(out_filename, CV_FOURCC('X', 'V', 'I', 'D'), src_fps, size, 1); 
>               
>       
>               
>                 
>                  //output_video_writer = cvCreateVideoWriter(out_filename, CV_FOURCC('W', 'M', 'V', '2'), src_fps, size, 1);

I did this step and uncommented MP4V and tried to save  '-out_filename test.mp4 ' output. 
When I test it with webcamera, it doesn't cause any error but doesn't save the result. It only shows the webcam results.
When I test it with input.mp4 file, it shows the same error as above.

I also tested by uncommenting each line one at a time and tried to save result using each file type to save the output and still it won't save the results.

What else am I missing? Do I install ffmpeg and test again?

@visshvesh Did it work for you?

**Comment by AlexeyAB** [comment]
> Do I install ffmpeg and test again?

Yes.

Also you can try to reinstall OpenCV with flag `-D WITH_FFMPEG=1` after that ffmpeg will be installed.

> cmake -D CMAKE_BUILD_TYPE=RELEASE -D BUILD_EXAMPLES=OFF -D WITH_FFMPEG=ON -D WITH_V4L=ON -D WITH_OPENGL=ON -D WITH_CUDA=ON -D CUDA_ARCH_BIN="3.0 5.0 6.1" -D WITH_CUBLAS=ON -D WITH_CUFFT=ON -D WITH_EIGEN=ON ./

What OS do you use?

**Comment by dimimal** [comment]
Same issue here. It works with webcam but not  with video file.

**Comment by arunasank** [comment]
👋 @AlexeyAB Seeing this issue on linux. 

* OS: Ubuntu 18.04.
* OpenCV version 3.2.0
* ffmpeg version: 3.4.6-0ubuntu0.18.04.1

> Also you can try to reinstall OpenCV with flag -D WITH_FFMPEG=1 after that ffmpeg will be installed.

I am using `make`, instead of `cmake`, and I have installed ffmpeg on the machine with `apt-get install ffmpeg`. What else do I need to do?
