### ISSUE TITLE
Segmentation Fault (Core Dumped)

### ISSUE THREAD

**Issue by goelsaksham** [AlexeyAB/darknet#1715]
Hi Alexey,

I am using SSH to train a YOLO model, however, it always does around 3-10 iterations and then shows Segmentation Fault (core dumped)

The command I am using is as follows:
./darknet detector train data/metadata_exp_1_2.data data/cfg_exp_1.cfg darknet53.conv.74 -dont_show

The screenshot of the error is:
![image](https://user-images.githubusercontent.com/42523205/46496131-d67c4100-c7dc-11e8-8847-96873bd78226.png)

Could this be because the size of the images is too large (Each image = 22 MB) and I have around 2500 such images for my training? Or is there other reason?

Thanks.

**Comment by goelsaksham** [comment]
@AlexeyAB 

* GPU - Nvidia 1080 Ti
* I have GPU = 1, OPENCV = 1, LIBSO = 1
* I will share my cfg file after some time. I am currently out, and will get access to my computer when I rech back home
* No, I was using my own Python Scripts to change the annotations collected by my research team.

Regards,
Saksham

**Comment by AlexeyAB** [comment]
@goelsaksham 

* Check your dataset by using: https://github.com/AlexeyAB/Yolo_mark

* Also check that there are no empty lines in your txt label files - it caused seg fault in this case: https://github.com/AlexeyAB/darknet/issues/1700#issuecomment-426932056

**Comment by goelsaksham** [comment]
@AlexeyAB 

Will do thanks!

**Comment by goelsaksham** [comment]
Hi @AlexeyAB 

I checked the Training data and it does not have any blank lines. Also, I was able to make it work for around 198 iterations without seg fault, now, however, I am not able to make it work for more than 30 iterations over 100 (using saved weights from 100th iteration). I checked that the label file does not have any error (out of bounds or something else). What do you think might the problem be?

**Comment by AlexeyAB** [comment]
@goelsaksham Hi,
Can you share your dataset?

**Comment by goelsaksham** [comment]
@AlexeyAB Hi,

Unfortunately, I cannot share the entire dataset (images) with you. However, I can definitely send the label files (.txt) files to you. Although I am not sure what might be the best way to share all of those (Have around 3000 .txt files). If you are looking for something particular in image files as well, I can try to figure something out, but it is unlikely. 

I can try to use the tool you suggested - 'YOLO Mark' today and see if there are any errors on the training data's side.

Thanks

**Comment by goelsaksham** [comment]
@AlexeyAB Also, what all do you need when you specifically ask for the whole dataset. Does it also include the .cfg, .names, .data files along with images and corresponding .txt files or a subset of these things?

**Comment by AlexeyAB** [comment]
Just try to compress txt-labels and cfg, names, obj.data files, and drag-n-drop to your message.

And try to check your dataset by using Yolo_mark.

**Comment by goelsaksham** [comment]
@AlexeyAB Hi,

Here is the ZIP file with the data.
[ab_data.zip](https://github.com/AlexeyAB/darknet/files/2470420/ab_data.zip)

Thanks

**Comment by AlexeyAB** [comment]
@goelsaksham Your labels looks good. May be one or several of your bmp files are broken.

* Try to set `valid  = data/training_data_2.txt` in the file `metadata_exp_1.data` and run such command:
`./darknet detector map data/metadata_exp_1_2.data data/cfg_exp_1.cfg`
will be there Core dumped?

* Also try to compile with `GPU=1 CUDNN=0 OPENCV=0 LIBSO=0 DEBUG=0 AVX=0 OPENMP=0` in the Makefile, recompile, and run `./darknet detector train`... again, will be there Core dumped?

**Comment by goelsaksham** [comment]
@AlexeyAB Hi,

I am attaching the screenshots of the two commands using "detector map".

Original (With validation=validation_data_2.txt, in metadata_exp_1.data)
https://mail.google.com/mail/u/0?ui=2&ik=816a588465&attid=0.3&permmsgid=msg-f:1614094648813863424&th=16666a880068c200&view=att&disp=safe

Modified (With validation=training_data_2.txt, in metadata_exp_1.data)
https://mail.google.com/mail/u/0?ui=2&ik=816a588465&attid=0.1&permmsgid=msg-f:1614094648813863424&th=16666a880068c200&view=att&disp=safe

However one interesting thing in the above case was that it said there was a file it was not able to open (Screenshot below)
https://mail.google.com/mail/u/0?ui=2&ik=816a588465&attid=0.2&permmsgid=msg-f:1614094648813863424&th=16666a880068c200&view=att&disp=safe

When I searched for the file in the folder, I was able to find it (am using a remote machine, so not sure whether the actual file is broken or not)


As goes for the second part, I recompiled with the given arguments and now there hasnt been any segmentation faults and it is around 1000 iterations already. Thanks for helping me figure this out. If possible can you share with me what might have made the problem go away (why might be there a problem when using the original makefile args)

Thanks.
Saksham
