### ISSUE TITLE
darknet-master gives different prediction result between CPU mode and GPU mode

### ISSUE THREAD

**Issue by tairen99** [AlexeyAB/darknet#1722]
Hi, @AlexeyAB,
     I used the darknet-master to train my tiny.net to do prediction with my own data, i.e.: detect people from infrared images, I get different results when I use CPU to run and GPU to run. I trained the weights in the GPU model. Please help me to solve this. Thank you.
The GPU mode gives prediction as follow:
![image](https://user-images.githubusercontent.com/32938376/46564593-f8e58b80-c8bc-11e8-8281-8bb6bab24dde.png)

The CPU mode gives prediction as follow:
![image](https://user-images.githubusercontent.com/32938376/46564607-0ef34c00-c8bd-11e8-8222-f5428965a9ba.png)
Thank you!

**Comment by AlexeyAB** [comment]
@tairen99 Hi,

Currently Darknet doesn't support `-nogpu` flag. If you want to use CPU - please compile Darknet with GPU=0 in the Makefile, or compile darknet_no_gpu.sln on Windows.

**Comment by tairen99** [comment]
Thanks, @AlexeyAB.
