### ISSUE TITLE
darknet.py: OSError: ./darknet.so no such file or directory

### ISSUE THREAD

**Issue by keegss** [AlexeyAB/darknet#1723]
I have successfully run Yolo on a Raspberry Pi using the darknet executable using both yolov2 and yolov2-tiny, but upon trying to use the python wrapper to retrieve the objects of detected objects I get this error:
` OSError: ./darknet.so: cannot open shared object file: No such file or directory `
 
Any ideas on how to fix?

**Comment by PeterQuinn925** [comment]
Try running from the directory that has darknet.so in it. That's what worked for me.

**Comment by AlexeyAB** [comment]
@keegss Did you compile Darknet with `LIBSO=1` in the `Makefile`?

**Comment by keegss** [comment]
@AlexeyAB Oops, I did not. I should read the docs more clearly next time 🤔 

I got it working, thank you! 😃
