### ISSUE TITLE
Many objects are often recognized as one object

### ISSUE THREAD

**Issue by wani2919** [AlexeyAB/darknet#1727]
Hi. AlexeyAB

I doing object recognition test with YOLO v3.
Although recognition of individual objects is performed accurately,
When many objects are recognized, neighboring objects can not be recognized.
and Many objects are often recognized as one object.

I will provide a way I set up so please find the improvement.
1. The [net] section width and height are 416
    train & detection image sizes are 640 x 480
![image](https://user-images.githubusercontent.com/16110709/46591926-37678a00-caf9-11e8-9e57-0edc404b7fa1.png)

2. The number of objects to be learned is 250 and the number of images is 397,912.
3. Recalculate recalculate anchors, change
![image](https://user-images.githubusercontent.com/16110709/46591944-4e0de100-caf9-11e8-9326-2551476dac0f.png)

This problem seems to be in the general rules when looking at multiple queries,
The train & detection image sizes are the same(640x480), and the size of the object is various.
Do you need to change .cfg or program based on general rules?

**Comment by AlexeyAB** [comment]
@wani2919 Hi,

0. What mAP can you get on Test dataset (or Training)?

> The train & detection image sizes are the same(640x480), and the size of the object is various.

> When many objects are recognized, **neighboring objects can not be recognized**.

1. Try to set `width=512 height=512` in cfg-file, and decrease `nms=0.2` here and test detection again, does it help to recognize neighboring objects?:
* https://github.com/AlexeyAB/darknet/blob/24b60456c70ffb8f2d64a5d7ca2d2aa1a7a6ebac/src/demo.c#L85
* https://github.com/AlexeyAB/darknet/blob/24b60456c70ffb8f2d64a5d7ca2d2aa1a7a6ebac/src/detector.c#L1126

----

2. If it doesn't help, then try to set `width=640 height=480` and train your model again.


> This problem seems to be in the general rules when looking at multiple queries,

If you use the same image resolution and network resolution for both Training and Detection, then the General rule can be broken only if your Training dataset is very different from Test-images, so you should improve your Training dataset - include images that are very similar to the Test-images.

**Comment by wani2919** [comment]
Thanks, @AlexeyAB.

Thank you for your answer.

0. What mAP can you get on Test dataset (or Training)?
  I have not got mAP yet.
  Let's try getting mAP after relearning again.

I share the results after relearning as a guide you presented.

**Comment by wani2919** [comment]
Hi @AlexeyAB 

I have another question.

Is this symptom related to the iterations?
I made a total of 100,000 iterations.

**Comment by wani2919** [comment]
thx @AlexeyAB

**Comment by wani2919** [comment]
@AlexeyAB Hi

As a result of testing as a result of changing to nms = 2 according to your advice, the phenomenon that multiple objects are recognized as one large object has become much less.
However, the recognition rate when there is only one object is good, but as long as there are multiple objects or if the object and the object are close together, the problem that is not normally recognized is still the same.

Is there a problem with my training

1. The environment is as follows.
 - Windows 10, Visual Studio 2017 (set 2015), OpenCV 3.4, CUDA 9.2, CUDDN 7.3, GTX1080Ti 1Way
 - YOLO v3
 - Training uses dark_net and test uses yolo_cpp_dll.dll.

2. I do custom training using YOLO_v3_voc.cfg and darknet 53.conv.74
 - anchors in [yolo] x3 was changed to the value obtained by executing "darknet.exe detector calc - anchors data / obj.data - num - of - - confters 9 - width 416 - height 416"
   anchors is 60.8825,80.9890, 117.2340,85.3003, 67.0293,151.4483, 87.9305,117.0896, 114.4498,154.2893, 88.2983,212.3347, 169.4741,120.3715, 152.4478,188.1766, 142.9085,257.0735
![image](https://user-images.githubusercontent.com/16110709/46963044-a3d91f00-d0df-11e8-95bb-f6b67b9964fc.png)
 - classes in [yolo] x3 was changed 258, filters was changed 789 [(258 + 5) * 3]
 - learning_rate=0.001
 - burn_in=1000
 - max_batches = 500200
 - policy=steps
 - steps=400000,450000
 - scales=.1,.1
 - did not change another values.

3. In the training image, only one object exists in one image. However, there are multiple objects in the test image.
 - I trained about 140,000 iterations about 400,000 images.
 - Training images were continuously added during training.

4. The sizes of the training image and the test image are almost the same. Of course, the size of the object is almost the same.

5. Training has been conducted about 140,000 iterations, mAP values are as follows.
![image](https://user-images.githubusercontent.com/16110709/46962945-64aace00-d0df-11e8-9da6-fc0880d5cc0d.png)


I have question
1. If multiple objects are close or overlapping, what should we do to improve recognition rate?
2. If images are added during training and it may be necessary to convert the value of max_batches, After changing max_batches value, Do you need training from the beginning? Or can you continue following the existing training?

Thanks!

**Comment by AlexeyAB** [comment]
@wani2919 

> 1. If multiple objects are close or overlapping, what should we do to improve recognition rate?
> In the training image, only one object exists in one image. However, there are multiple objects in the test image.

* You should add images with more than one objects to your Training dataset 
* You should mark several objects in one image with the minimum overlapping

> 2. If images are added during training and it may be necessary to convert the value of max_batches, After changing max_batches value, Do you need training from the beginning? Or can you continue following the existing training?

You can continue training.
In general, if you didn't change network structure and didn't change number of filters or number classes, then you can continue training.

**Comment by wani2919** [comment]
Thanks @AlexeyAB 

I will keep trying.
Please ask a lot of help.
