### ISSUE TITLE
I have drawed a PR curve ,it looks some strange, does it normal?

### ISSUE THREAD

**Issue by wurendi-xx** [AlexeyAB/darknet#1729]
It looks like this 
![pr](https://user-images.githubusercontent.com/33140531/46598054-33e1fc00-cb15-11e8-9620-0a2ba1e4837e.png)

**Comment by AlexeyAB** [comment]
Yes, it is normal for very simple objects.

**Comment by wurendi-xx** [comment]
thanks

**Comment by cyrineee** [comment]
@wurendi-xx  how did it shows for you the 11 points for each class ? i uncommented the line in detector.c but il did not show .

**Comment by cyrineee** [comment]
![test1](https://user-images.githubusercontent.com/42346254/59040659-6e07c700-8877-11e9-8c73-7f4df4492921.PNG)
![test2](https://user-images.githubusercontent.com/42346254/59040660-6ea05d80-8877-11e9-8b58-28e70058aa1c.PNG)
![test](https://user-images.githubusercontent.com/42346254/59040661-6ea05d80-8877-11e9-9843-c3f537c118ac.PNG)
 are they normal for multiclass?
