### ISSUE TITLE
Building error 

### ISSUE THREAD

**Issue by FKKrjakonzo** [AlexeyAB/darknet#173]
Hi, 
Sorry for bothering you but I run into some error during the building process. 
Similarly to this issue [https://github.com/AlexeyAB/darknet/issues/136#issuecomment-318465726](url)
but not exactly same, and also your stated fix didn't work for me. 
After I try to build darknet on windows I get this error:

`Severity    Code    Description    Project    File    Line    Suppression State
Error    MSB3721    The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-env --cl-version 2015 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64"  -IC:\opencv_3.0\opencv\build\include -I..\..\3rdparty\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I\include -I"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\x64" -I"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt\x64" -IC:\opencv_2.4.9\opencv\build\x64\vc12\lib -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0lib\x64" -I\lib\x64 -I"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.14393.0\ucrt\x64" -I"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.14393.0\um\x64" -I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\ucrt\\" -IC:\opencv_2.4.9\opencv\build\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static     -DCUDNN -DOPENCV -D_TIMESPEC_DEFINED -D_CRT_SECURE_NO_WARNINGS -D_CRT_RAND_S -DGPU -DWIN32 -DNDEBUG -D_CONSOLE -D_LIB -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /FS /Zi  /MD " -o x64\Release\dropout_layer_kernels.cu.obj "C:\Users\fredy\Desktop\darknet-master (1)\darknet-master\src\dropout_layer_kernels.cu"" exited with code 1.    darknet    C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations\CUDA 8.0.targets    689    
`
11 times. 
I tried everything available but I couldn't find the answer. Even tried newer version of CUDA but had same error.
If you have any ideas how to fix the issue, I would be thankful.

Thank you for your answer
FKKrjakonzo

**Comment by VanitarNordic** [comment]
I have compiled the Alex repo in counting with my hairs, so I'm sure there is no problem with the Build section. if all components are in place, you will not face any error. 
I suggest that you install the CUDA again, but before that, remove all traces from add/remove programs and also all traces from from your hard disk. it saves some files in several places.
Also re-open the Visual Studio if you change the CuDNN path in the environmental variables, otherwise it reads the previous path.

**Comment by FKKrjakonzo** [comment]
May I ask you, how did you manage to put all components in place? 
I installed VS2015, then installed Cuda 8.0, after that I copied openCV3.0 and put links to PC variables in paths "C:\opencv_3.0\opencv\build\include" and "C:\opencv_3.0\opencv\build\x64\vc14\lib". Then I started darknet in VS and set release and x64. I think I did everything as said. If you can suggest anything more I have to do please do so.

**Comment by VanitarNordic** [comment]
make sure the paths to your OpenCV are correct. Besides make sure that you have modified the OpenCV parameters to match with your installed OpenCV version. I mean inside `detector.c`

as the Alexey mentioned, check the paths inside pre-processors and Linker of your project properties.

**Comment by FKKrjakonzo** [comment]
All paths in detector.c seems to be working fine ( [https://snag.gy/rdqeEf.jpg](url) ), also I am using CV 3.0 so by default it should be set. Also, I checked everything from [https://snag.gy/AlUFVY.jpg](url). I am kind of desperate with it :/ .

**Comment by VanitarNordic** [comment]
I'm sure there is something wrong with your definitions, because now I'm working with it also and compiling it almost every minutes :-)

**Comment by VanitarNordic** [comment]
try to run this command in your `CMD` and see what gives you: `nvcc --version`

**Comment by FKKrjakonzo** [comment]
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Mon_Jan__9_17:32:33_CST_2017
Cuda compilation tools, release 8.0, V8.0.60

**Comment by VanitarNordic** [comment]
that's correct but again I believe something wrong with paths. I can guarantee you the repo compiles correctly.

**Comment by FKKrjakonzo** [comment]
Yeah, I agree but I can't find what. 
I double checked everything and I am out of ideas, everyone managed to build darknet easily and I am struggling hard to get it work :/ 
If you can find anything I would be glad, anyway thank you very much for trying
[https://snag.gy/pgUSui.jpg](url)

**Comment by AlexeyAB** [comment]
@FKKrjakonzo 
* What Windows version do you use?
* Can you compile any other CUDA programms?
* Show screenshots the same as: 
    *  https://user-images.githubusercontent.com/4096485/28688766-b1eeab50-731b-11e7-8b1f-b2a37305ef6b.jpeg
    * https://user-images.githubusercontent.com/4096485/28688896-3e9f37a4-731c-11e7-8e0a-20217ff001e5.png
    * https://user-images.githubusercontent.com/4096485/28688973-8e54707a-731c-11e7-8e3c-ad2857b8e419.png
    * https://user-images.githubusercontent.com/4096485/28683035-bd409aea-7307-11e7-9ac2-dab13b7ebaf9.jpg
* Try to remove `CUDNN;` from C++ -> Preprocessor definitions.
* Try to remove `compute_52,sm_52` from CUDA -> Device -> Code generation
* Try to run MSVS2015 - (right click) -> as Administrator

**Comment by AlexeyAB** [comment]
@FKKrjakonzo Also show path, where is file `opencv_world320.lib` located in your disk?
And if you have another file, then change this line, for example `opencv_world300.lib`: https://github.com/AlexeyAB/darknet/blob/0316685077bf82d4dbeadb9e947e3ea16b6ae703/src/detector.c#L16

**Comment by FKKrjakonzo** [comment]
- Windows 10 home edition
- Tried CUDA sample - same error
- [https://snag.gy/A4WPfF.jpg](url)
-nothing happend
-nothing happend
-nothing happend

I reainstalled cuda several times but I can't even build CUDA sample :/

**Comment by AlexeyAB** [comment]
@FKKrjakonzo So your problem doesn't relate to Darknet, your error relates to CUDA-installation in general: https://www.google.ru/search?q=MSB3721+CUDA

Also check PATH variable (check paths to MSVS, NVIDIA and others) in the Windows: Control Panel -> System -> Advanced System Settings -> Advanced -> Environment Variable

**Comment by FKKrjakonzo** [comment]
Sorry for bothering you guys, and thank you very much for every advice. I just tried installing darknet on another PC, and it worked just right with no problems. Now I have to find the way to run it on my PC.
