### ISSUE TITLE
Group Conv

### ISSUE THREAD

**Issue by ramanathan831** [AlexeyAB/darknet#1730]
Is there not a support for Group Convolution?

**Comment by AlexeyAB** [comment]
Currently, no.

**Comment by DRACOyu** [comment]
> Currently, no.

Hello, the latest darknet library forward function has added group, now the group convolution can not be used?

**Comment by daniel89710** [comment]
I think "group convolution" is changed in below.
https://github.com/pjreddie/darknet/commit/fbd48ab606dd91f076eaa68588f285c1d5f436fb#diff-ae59d70b262c4fc38e33107897434688
 
Could you merge for group convolution?

**Comment by AlexeyAB** [comment]
@ram1897 @DRACOyu @daniel89710 Hi,
It is implemented.

You can try to use this cfg-file: https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/resnext152-32x4d.cfg

and this weights-file: https://pjreddie.com/media/files/resnext152-32x4d.weights

by using this command: 
`./darknet classifier predict cfg/imagenet1k.data cfg/resnext152-32x4d.cfg resnext152-32x4d.weights`

----

Or also you can try to use MobileNet v2: https://drive.google.com/open?id=1xOrey4CeiLX7Kl3PwkAfj-PpoPYNxt3e

It is taken from: https://github.com/WePCf/darknet-mobilenet-v2
