### ISSUE TITLE
CUDA Error: invalid argument

### ISSUE THREAD

**Issue by nikitbiraj** [AlexeyAB/darknet#1732]
Running darkent.exe using below command on windows 10
darknet.exe detector test data/coco.data yolov3.cfg yolov3.weights -i 0 -thresh 0.25 dog.jpg -ext_output
I get
CUDA Error: invalid argument
CUDA Error: invalid argument: No error

CUDA version 9.0
Visual studio version 2015
OpenCV version  3.0

What could be the issue?
darkent_no_gpu.exe runs OK.

**Comment by AlexeyAB** [comment]
* Do you use the latest version from this GitHub repository?
* What cuDNN version do you use? Do you use cuDNN for CUDA 9.0?
* What GPU do you use?
* Did you change anything in the yolov3.cfg file?

**Comment by nikitbiraj** [comment]
Do you use the latest version from this GitHub repository?
-- Yes using latest repository
What cuDNN version do you use? Do you use cuDNN for CUDA 9.0?
--cuDNN v7.3.0 for CUDA 9.0
What GPU do you use?
--NVIDIA GeForce GT 730
Did you change anything in the yolov3.cfg file?
-- No

**Comment by AlexeyAB** [comment]
* Try to do - open `\darknet.sln` in MSVS -> (right click on project) -> properties -> CUDA C/C++ -> Device -> Code Generation, and add at the begining of line: `compute_35,sm_35;`


* If it doesn't help, then try to build without CUDNN then: open `\darknet.sln` -> (right click on project) -> properties -> C/C++ -> Preprocessor -> Preprocessor Definitions, and remove this: `CUDNN;`

**Comment by nikitbiraj** [comment]
Disabling CUDNN solved the problem.
Though I didn't understand why CUDNN was giving the error. If you can let me know the reason behind it?
Thanks in advance.

**Comment by AlexeyAB** [comment]
I don't know why nVidia cuDNN doesn't support nVidia GPU GT 730. 

May be you use nVidia driver that is older than CUDA 9.0.
What can you see if you run? 
`"C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi"`

**Comment by nikitbiraj** [comment]
Attached image link for "C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi"

![nvidia](https://user-images.githubusercontent.com/16545325/46733971-7fc8a880-ccaf-11e8-9031-5be6526e886c.png)

**Comment by AlexeyAB** [comment]
@nikitbiraj 
Try to install this nVidia GPU driver: https://www.nvidia.com/Download/driverResults.aspx/138567/en-us

**Comment by AlexeyAB** [comment]
May be some bugs in the old nVidia Drivers.

**Comment by nikitbiraj** [comment]
Thanks.
