### ISSUE TITLE
gcc: error trying to exec 'cc1plus': execvp: No such file or directory

### ISSUE THREAD

**Issue by visshvesh** [AlexeyAB/darknet#1740]
Hi,
I tried every changes suggested but still facing this issue:
Anyone got the solution?

gcc -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DGPU -DCUDNN -I/usr/local/cudnn/include -c ./src/voxel.c -o obj/voxel.o
gcc -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DGPU -DCUDNN -I/usr/local/cudnn/include -c ./src/tree.c -o obj/tree.o
gcc -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DGPU -DCUDNN -I/usr/local/cudnn/include -c ./src/yolo_layer.c -o obj/yolo_layer.o
gcc -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DGPU -DCUDNN -I/usr/local/cudnn/include -c ./src/upsample_layer.c -o obj/upsample_layer.o
nvcc -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -gencode arch=compute_61,code=[sm_61,compute_61] -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN --compiler-options "-Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DGPU -DCUDNN -I/usr/local/cudnn/include" -c ./src/convolutional_kernels.cu -o obj/convolutional_kernels.o
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
make: *** [obj/convolutional_kernels.o] Error 1

Using:
Deep learning AMI Linux-AWS
NVidia CUDA 8, cuDNN 5.1 and NVIDIA Driver 375.66
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66 Driver Version: 375.66 |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
|===============================+======================+======================|
| 0 Tesla K80 On | 0000:00:1E.0 Off | 0 |
| N/A 32C P8 30W / 149W | 0MiB / 11439MiB | 0% Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes: GPU Memory |
| GPU PID Type Process name Usage |
|=============================================================================|
| No running processes found |
+-----------------------------------------------------------------------------+
```

**Comment by AlexeyAB** [comment]
@visshvesh Hi,

Try to use this ami: 
`AMI (Ubuntu) Version 3.0 (ami-38c87440) - Deep Learning base AMI with NVidia drivers like CUDA 8 and 9, CuDNN 6 and 7`

More about training on Amazon EC2: https://github.com/AlexeyAB/darknet/issues/1380#issuecomment-412333942

**Comment by visshvesh** [comment]
Thanks a lot!! @AlexeyAB , 
Tried with Deep Learning AMI -Ubuntu (version 10) with p2.xlarge GPU ec2 instance and after changing the following things the above issue was resolved. 

Changes done:
1.)>vi Makefile 
and change:
from

ifeq ($(GPU), 1) 
COMMON+= -DGPU -I/usr/local/cuda/include/
CFLAGS+= -DGPU
LDFLAGS+= -L/usr/local/cuda/lib64 -lcuda -lcudart -lcublas -lcurand
endif

to

ifeq ($(GPU), 1) 
COMMON+= -DGPU -I/usr/local/cuda-8.0/include/
CFLAGS+= -DGPU
LDFLAGS+= -L/usr/local/cuda-8.0/lib64 -lcuda -lcudart -lcublas -lcurand
endif


2.) Add the following to your ~/.bashrc

# DARKNET
export PATH=/usr/local/cuda-8.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda8.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
