### ISSUE TITLE
ImportError: dynamic module does not define init function (initdarknet)

### ISSUE THREAD

**Issue by chrisrapson** [AlexeyAB/darknet#1741]
When I try to `import darknet` to use in a separate python program, I get the error in the title.

I am using OpenCV3.4.0, and compile darknet with options:
```
GPU=0
CUDNN=0
CUDNN_HALF=0
OPENCV=1
AVX=1
OPENMP=1
LIBSO=1
```

I have made sure that `darknet.py` is on the path:
```
import sys
darknet_path='/path/to/AlexeyAB_darknet'
sys.path.append(darknet_path)
```

[This stackoverflow page](https://stackoverflow.com/questions/24226001/importerror-dynamic-module-does-not-define-init-function-initfizzbuzz) suggests I might be missing an init file, or the init file might not have the correct naming conventions. One answer also suggests that I should try using a different python version. My default python version is 2.7. If I try python3, I get a different, but similar error:
`ImportError: dynamic module does not define module export function (PyInit_darknet)`

Am I doing something wrong, is this intended behaviour, or is there an issue with darknet?

**Comment by PeterQuinn925** [comment]
I had trouble until ran it from the directory that had darknet.so in it. Adding it to the path wasn't enough. I don't know why and as soon as I got it working, I didn't investigate further.  I am using python3.

**Comment by chrisrapson** [comment]
Thanks for the quick suggestion. I was running it from that directory when I tried the python3 example at the end of my post.

**Comment by chrisrapson** [comment]
I ended up needing two changes to make this work.
1. renaming the shared object library (`darknet_so.so`) and updating the references to the so in `darknet.py`
2. either running from the darknet directory, or linking those files into the directory I was running from.

**Comment by JSR694** [comment]
As a postscript: if you give the absolute path to darknet_so.so in darknet.py, you don't need to run it in the darknet directory (or link any files).
