### ISSUE TITLE
Location of darknet build file for training

### ISSUE THREAD

**Issue by harsham05** [AlexeyAB/darknet#1742]
@AlexeyAB  Thank you for this amazing repo! 

```$DARKNET_REPO=/path/to/darknet-master-repo-clone```

1. After cloning this repo, I edited the Makefile & ran ```make``` in ```$DARKNET_REPO```
2. I ended up with a ```./darknet``` executable in the repo at ```$DARKNET_REPO/darknet```  which works perfectly for testing YOLOv3 on images & video based on COCO pre-trained weights 👍 

3. I followed the README for training on custom data & added all the relevant files at  
```$DARKNET_REPO/build/darknet/x64/data/```

4. But the ```./darknet``` executable was never present at ```$DARKNET_REPO/build/darknet/x64/```

5. So I copied ```$DARKNET_REPO/darknet``` to ```$DARKNET_REPO/build/darknet/x64/```
I was then able to start training after doing this. Is this correct?

Should training be performed in ```$DARKNET_REPO``` or ```$DARKNET_REPO/build/darknet/x64/```?

**Comment by AlexeyAB** [comment]
@harsham05 Hi,

> So I copied $DARKNET_REPO/darknet to $DARKNET_REPO/build/darknet/x64/
> I was then able to start training after doing this. Is this correct?

Yes, you can use any way
you can use this way - put `darknet`-executable file to the `$DARKNET_REPO/build/darknet/x64/`
or better if you just put your Training dataset to the `$DARKNET_REPO` directory

**Comment by harsham05** [comment]
Thank you @AlexeyAB 👍
