### ISSUE TITLE
Что делают min_crop и max_crop в .cfg файлах?

### ISSUE THREAD

**Issue by Bongua** [AlexeyAB/darknet#1743]
Какие преобразования с изображением делают min_crop и max_crop?
Часть моего cfg файла:
height=128
width=128
min_crop=64
max_crop=224

**Comment by AlexeyAB** [comment]
[min_crop, max_crop] - the range - how much the image will be scaled (size reduced or enlarged) in data augmentation function during Classifier training.

```
low = min_crop (from cfg)
high = max_crop (from cfg)
size = width (from cfg)
aspect = random-float(from: 1/aspect, to: aspect) // where aspect (from cfg)
```


https://github.com/AlexeyAB/darknet/blob/7ee4135910624f11e80de36b236208b223f58eb4/src/image.c#L1456-L1475

**Comment by Bongua** [comment]
Как я могу отключить его?

**Comment by AlexeyAB** [comment]
`width=416 height=416 min_crop=416 max_crop=416 aspect=1`

**Comment by Bongua** [comment]
Спасибо большое

**Comment by umbralada** [comment]
А можно еще уточнить, данных параметров нет в yolo*.cfg файлах. Значит ли это, что я не могу их там использовать? Или можно их там дописать, и они будут работать? И также интересует параметр angle. Он в yolo установлен в 0. Имеет смысл его менять?

**Comment by AlexeyAB** [comment]
@umbralada 

* In the Yolo is used `jitter=0.3` instead of `min_crop, max_crop, aspect`. 
    * https://github.com/AlexeyAB/darknet/blob/31df5e27356b6b11ffd43baace9afdd3800a8aa2/src/data.c#L771-L783
    * https://github.com/AlexeyAB/darknet/blob/31df5e27356b6b11ffd43baace9afdd3800a8aa2/src/http_stream.cpp#L274-L294

* `angle` isn't implemented for Yolo.
