### ISSUE TITLE
18000 catalogs, should I choose yolov3 or yolo9000?

### ISSUE THREAD

**Issue by fanfan2000** [AlexeyAB/darknet#1745]
I am trying to use darknet to process some poor quality Chinese books (tesseract can't solve them). It involves more than 18000 characters, and I have a library for training and valid,  should I choose yolov3 or yolo9000?

**Comment by AlexeyAB** [comment]
@fanfan2000 

You should use yolov3. Use `classes=18000` in your cfg-file.

----

Also try calculate anchors for 1, 2, 3, and 9 num_of_clusters:
`./darknet detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416`

If anchors are aproximately the same, then try to use only 2 (for yolov3-tiny.cfg) or 3 (for yolov3.cfg) clusters (anchors), and correspond value
* `num=` (num_of_clusters)
* `masks=` (indexes of anchors for the current [yolo]-layer)
* `filters=(classes + 5)*anchors_per_layer)` before each of `[yolo]`-layer

For example, if you use 3 anchors - then in the each of [yolo]-layer should be:
* `anchors=50,50, 100,100, 150,150` - these values you should get by command `./darknet detector calc_anchors data/obj.data -num_of_clusters 3 -width 416 -height 416`

* `num=3`
* `masks=2` in the 1st [yolo]-layer, `masks=1` in the 2nd, `masks=0` in the 3rd (last)
* `filters=18005` in the 3 [convolutional]-layers before each [yolo]-layer


----

Also you should follow this rule: https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

> General rule - your training dataset should include such a set of relative sizes of objects that you want to detect:
> 
> * `train_network_width * train_obj_width / train_image_width ~= detection_network_width * detection_obj_width / detection_image_width`
> * `train_network_height * train_obj_height / train_image_height ~= detection_network_height * detection_obj_height / detection_image_height`

**Comment by fanfan2000** [comment]
Okey, thanks!
