### ISSUE TITLE
Prediction image is too slow on CPU

### ISSUE THREAD

**Issue by linquanxu** [AlexeyAB/darknet#1747]
Hi AlexyAB,
When I test image with my own weight on CPU, The speed of inference is very slow and Predicted in 2.741368 seconds. how to accelerate? thanks. Detailed configuration is as follows：
code：darknet_no_gpu
image size： 416x416
net: yolov3 classes=20
Intel(R) Core(TM) i5-8250U @1.60GHz 1.80 GHz, win10 64bit

**Comment by AlexeyAB** [comment]
@linquanxu Hi,

yolov3.cfg is very slow for CPU.

* Use GPU with yolov3.cfg.
* Or use yolov3-tiny.cfg on CPU.

Also you can try to use yolov3.cfg with OpenCV-dnn-module, examples: 
* https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp
* https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.py

**Comment by AlexeyAB** [comment]
Also you can try to train XNOR model - ~20 FPS: https://github.com/AlexeyAB/darknet/issues/1472

**Comment by linquanxu** [comment]
@AlexeyAB thank you for reply.

**Comment by AlexeyAB** [comment]
@linquanxu OpenCV-dnn-module is optimized for x86_64 as much as possible with using AVX/AVX2 and Multi-threading.

**Comment by linquanxu** [comment]
thank you, @AlexeyAB

**Comment by oubinke** [comment]
Hi AlexyAB,  
The time of inference on CPU is about 10s per 600*600 image. I know you said `yolov3.cfg is very slow for CPU.` , but it's really slow. Is there something wrong of my setting?  

CPU: Intel(R) Xeon(R) CPU E5-1680 v2 @ 3.00GHz  
OS: 	Ubuntu 18.04.1 LTS
Makefile: GPU=0, CUDNN=0, CUDNN_HALF=0, OPENCV=1, AVX=0, OPENMP=1, LIBSO=1

**Comment by oubinke** [comment]
I use `darknet.py` to test and print some time. The result shows `detect` function spend most time.  
[!darknet.py](https://github.com/AlexeyAB/darknet/blob/master/darknet.py)
I'm trying to use `yolov3.cfg with OpenCV-dnn-module`. But i don't know how to use it, is there any example for using it?
https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.py
