### ISSUE TITLE
NVIDIA RTX 20XX Support

### ISSUE THREAD

**Issue by occasumlux** [AlexeyAB/darknet#1752]
As the title says, will this repo support CUDA optimizations (including Tensor Cores) for the NVIDIA RTX 20XX series?

**Comment by AlexeyAB** [comment]
Yes. 

* on Linux: set `GPU=1 CUDNN=1 CUDNN_HALF=1` in the Makefile and compile

* on Windows: open `\darknet.sln` in MSVS -> (right click on project) -> properties -> C/C++ -> Preprocessor -> Preprocessor Definitions, and add at the begining of line: `CUDNN_HALF;`
    then recompile

In some cases you may need to train first 2000 iterations wihtout `CUDNN_HALF`, and then continue training with `CUDNN_HALF`.

More about Tensor Cores (CUDNN_HALF) acceleration: https://github.com/AlexeyAB/darknet/issues/407

**Comment by occasumlux** [comment]
Ok!
Thanks!!!

**Comment by AlexeyAB** [comment]
Just may be you should use Compute Capability 7.5 in the Makefile
`ARCH= -gencode arch=compute_75,code=[sm_75,compute_75]`
