### ISSUE TITLE
Failed to compile only when GPU=1

### ISSUE THREAD

**Issue by ycd2016** [AlexeyAB/darknet#1757]
Failed only when GPU=1, successful if changed to GPU=0.
Pjreddie's code compiled successfully when GPU=1.
I'm using cuda 9.1 on debian 9.

makefile:

GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=1
AVX=1
OPENMP=1
LIBSO=1

errors from console:

/usr/bin/ld: obj/im2col_kernels.o: in function `convolve_cpu':
/tmp/tmpxft_00002dc6_00000000-5_im2col_kernels.cudafe1.cpp:(.text+0xcc5): undefined reference to `__kmpc_fork_call'
/usr/bin/ld: obj/im2col_kernels.o: in function `.omp_outlined.':
/tmp/tmpxft_00002dc6_00000000-5_im2col_kernels.cudafe1.cpp:(.text+0xd51): undefined reference to `__kmpc_for_static_init_4'
/usr/bin/ld: /tmp/tmpxft_00002dc6_00000000-5_im2col_kernels.cudafe1.cpp:(.text+0x12cb): undefined reference to `__kmpc_for_static_fini'
/usr/bin/ld: obj/im2col_kernels.o: in function `convolve_bin_cpu':
/tmp/tmpxft_00002dc6_00000000-5_im2col_kernels.cudafe1.cpp:(.text+0x13be): undefined reference to `__kmpc_fork_call'
/usr/bin/ld: obj/im2col_kernels.o: in function `.omp_outlined..1':
/tmp/tmpxft_00002dc6_00000000-5_im2col_kernels.cudafe1.cpp:(.text+0x144c): undefined reference to `__kmpc_for_static_init_4'
/usr/bin/ld: /tmp/tmpxft_00002dc6_00000000-5_im2col_kernels.cudafe1.cpp:(.text+0x16e7): undefined reference to `__kmpc_for_static_fini'
collect2: error: ld returned 1 exit status

**Comment by ycd2016** [comment]
errors from console:

/usr/bin/ld: obj/convolutional_kernels.o: relocation R_X86_64_32 against symbol `_Z15binarize_kernelPfiS_' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: obj/activation_kernels.o: relocation R_X86_64_32 against symbol `_Z21activate_array_kernelPfi10ACTIVATION' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: obj/im2col_kernels.o: relocation R_X86_64_32 against symbol `_Z17im2col_gpu_kerneliPKfiiiiiiiPf' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: obj/col2im_kernels.o: relocation R_X86_64_32 against symbol `_Z17col2im_gpu_kerneliPKfiiiiiiiPf' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: obj/blas_kernels.o: relocation R_X86_64_32 against symbol `_Z17scale_bias_kernelPfS_ii' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: obj/crop_layer_kernels.o: relocation R_X86_64_32S against `.rodata.cst8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: obj/dropout_layer_kernels.o: relocation R_X86_64_32 against symbol `_Z28yoloswag420blazeit360noscopePfiS_ff' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: obj/maxpool_layer_kernels.o: relocation R_X86_64_32 against symbol `_Z28forward_maxpool_layer_kerneliiiiiiiPfS_Pi' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: obj/network_kernels.o: relocation R_X86_64_32 against symbol `_Z12train_threadPv' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: obj/avgpool_layer_kernels.o: relocation R_X86_64_32 against symbol `_Z28forward_avgpool_layer_kerneliiiiPfS_' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: 最后的链结失败: nonrepresentable section on output
collect2: error: ld returned 1 exit status

**Comment by ycd2016** [comment]
I changed line 80 to `CFLAGS+= -DGPU -fPIC` and then the compilation is successful.
Is there any problem with this rewriting?

**Comment by AlexeyAB** [comment]
This is strange, there is already -fPIC: https://github.com/AlexeyAB/darknet/blob/344f8c6d27702aad61b285bac7cba9741e7ac4e8/Makefile#L120
And I can build Darknet with `GPU=1 LIBSO=1` without additional changes.

----

* Can you drag-n-drop your Makefile to your message?
* Do you use the latest version of this repository?
* Can you show output of commands
```
nvcc --version
nvidia-smi
gcc --version
uname -r
```

**Comment by ycd2016** [comment]
Sorry, maybe my changes are due to the metaphysical reasons for the compilation success.
I tried to make clean and then re-make after I failed to load the network configuration and found that still failed so definitely not a problem with -fPIC.
I thought it might be a problem between openmp and cuda and after I disabled openmp I could successfully make it without any other changes to the code.

**Comment by AlexeyAB** [comment]
@ycd2016 
You can try to install Clang+OpenMP for MacOS as described here: https://medium.com/@asvetly/clang-openmp-setup-in-macos-dbb0638cc4df
1. Do: 
`brew install llvm`

2. Then change this line: https://github.com/AlexeyAB/darknet/blob/344f8c6d27702aad61b285bac7cba9741e7ac4e8/Makefile#L78
to this `LDFLAGS+= -fopenmp=libiomp5`

3. Then set `OPENMP=1` in the Makefile

4. And do
```
make clean
make -j8
```

**Comment by aimhabo** [comment]
similar question in compiling that:
> ...
> ...
> ./src/im2col_kernels.cu(494): error: identifier "__shfl" is undefined
> 
> ./src/im2col_kernels.cu(439): warning: variable "tmp_s" was declared but never referenced
> 
> ./src/im2col_kernels.cu(440): warning: variable "tmp256_s" was declared but never referenced
> 
> ./src/im2col_kernels.cu(968): error: identifier "__shfl_xor" is undefined
> 
> ./src/im2col_kernels.cu(1024): error: identifier "__shfl" is undefined
> 
> ./src/im2col_kernels.cu(1054): error: identifier "__shfl" is undefined
> 
> ./src/im2col_kernels.cu(1000): warning: variable "h" was declared but never referenced
> 
> ./src/im2col_kernels.cu(1300): warning: variable "k" was declared but never referenced
> 
> ./src/im2col_kernels.cu(1365): error: identifier "__shfl_down" is undefined
> ...
> ...

just git and set GPU=1 CUDNN=1 OPENCV=1 ARCH=-gencode arch=compute_61,code=[sm_61,compute_61]

**Comment by AlexeyAB** [comment]
@aimhabo 

1. Can you show output of the commands `nvidia-smi` and `nvcc --version` ?

2. What CUDA and cuDNN versions do you use?

3. Do you mean, that you can compile and run successfully by using
```
ARCH= -gencode arch=compute_30,code=sm_30 \
      -gencode arch=compute_35,code=sm_35 \
      -gencode arch=compute_50,code=[sm_50,compute_50] \
      -gencode arch=compute_52,code=[sm_52,compute_52] \
	  -gencode arch=compute_61,code=[sm_61,compute_61]
```

But you can't compile with?
```
ARCH= -gencode arch=compute_61,code=[sm_61,compute_61]
```

**Comment by ycd2016** [comment]
@AlexeyAB 
Thanks, but I'm using it on Debian. I think that cuDNN is already very fast, so I didn't plan to enable OpenMP.

**Comment by aimhabo** [comment]
@AlexeyAB 
1、
![2018-10-16 12-43-19](https://user-images.githubusercontent.com/12708080/46993351-57bec680-d141-11e8-9806-50b8eb795dd1.png)
![2018-10-16 12-45-47](https://user-images.githubusercontent.com/12708080/46993369-71600e00-d141-11e8-8928-9da7d439ae54.png)

2、 CUDA8.0+cuDNN6.0.21

3、 Yes

**Comment by vismayaps** [comment]
Hi,
I am getting the following error while compiling with GPU =1 
![compile](https://user-images.githubusercontent.com/20744084/49148065-51b92980-f32c-11e8-8573-8e5296ccecd3.png)
I'm using Debian GNU/Linux 9.6 and installed CUDA 10.0

**Comment by AlexeyAB** [comment]
@vismayaps Try to check that there are CUDA libraries by this path: https://github.com/AlexeyAB/darknet/blob/21a4ec9390b61c0baa7ef72e72e59fa143daba4c/Makefile#L88

**Comment by vismayaps** [comment]
I've checked that already and its there.

**Comment by vismayaps** [comment]
Till cuda is there but the "lib" directory is not there. But "lib64" is present.

**Comment by vismayaps** [comment]
@AlexeyAB Any updates on this ?

**Comment by AlexeyAB** [comment]
@vismayaps 

Try to change this line: https://github.com/AlexeyAB/darknet/blob/21a4ec9390b61c0baa7ef72e72e59fa143daba4c/Makefile#L88
to this
` LDFLAGS+= -L/usr/local/cuda/lib64 -lcuda -lcudart -lcublas -lcurand `

**Comment by vismayaps** [comment]
@AlexeyAB 
Giving the same error
![new_scrnsht](https://user-images.githubusercontent.com/20744084/49583638-d0dadd00-f97e-11e8-99b1-a752b5c40c18.png)

**Comment by vismayaps** [comment]
@AlexeyAB 
I think the issue was with cuda version and I reinstalled cuda 9.1 from scratch. and I'm getting the following error now. 
![clipboard-image](https://user-images.githubusercontent.com/20744084/49921913-0af33400-fed5-11e8-98f3-bc8656ace396.png)
And my system config is given below.
Ubuntu 16.04
Cuda 9.1
NVIDIA TESLA  Tesla K80

**Comment by vismayaps** [comment]
@AlexeyAB 
Sure.
![achi](https://user-images.githubusercontent.com/20744084/49936343-b31af400-fef9-11e8-8747-1479fc66d5c1.png)

**Comment by AlexeyAB** [comment]
@vismayaps Your current version is CUDA 7.5.

During installation CUDA you should set to create symlink for `/usr/local/cuda`->`/usr/local/cuda-9.1`
Also check that you specified correct paths to the CUDA 9.1 in the `.bashrc` file: https://devtalk.nvidia.com/default/topic/995815/cuda-setup-and-installation/path-amp-ld_library_path/

**Comment by vismayaps** [comment]
@AlexeyAB 
Please find the path included in .bashrc file. Please let me know if the included path is right.

![clipboard-image](https://user-images.githubusercontent.com/20744084/49940075-9506c100-ff04-11e8-92e6-1059b7c39fbf.png)

Here is the path where CUDA is installed. Its at /usr/local:

![1](https://user-images.githubusercontent.com/20744084/49940081-9cc66580-ff04-11e8-91d6-cd9b67123e6d.png)

**Comment by vismayaps** [comment]
@AlexeyAB 
I have set the above path in .bashrc and restarted the system. Executed nvcc --version and nvidia-smi. Got the below result.

There is a mismatch in CUDA version. Its showing 10.0, but I have actually installed 9.1

![new](https://user-images.githubusercontent.com/20744084/49988753-f75fd000-ff9d-11e8-9922-7c528d7e874b.png)

After restarting the instance, I am getting the same error.

**Comment by AlexeyAB** [comment]
@vismayaps 

Try to remove all CUDA versions, and install CUDA 10.0 from the begining.

----

> After restarting the instance, I am getting the same error.

Then set `GPU=1 CUDNN=0` in the Makefile, and can you show output of these two command in one window?
```
nvcc --version
make
```

**Comment by vismayaps** [comment]
hey @AlexeyAB , I have uninstalled all versions of CUDA and installed CUDA version 10.0. Made the values of Makefile as GPU=1 and CUDNN=0. Got the below result when I ran the above commands.

![cuda](https://user-images.githubusercontent.com/20744084/50266132-69c22b80-0448-11e9-9d80-ed544c9cb2b5.png)

**Comment by vismayaps** [comment]
Hi @AlexeyAB , Found a fix to the above problem. I commented out the the line -gencode arch=compute_61,code=[sm_61,compute_61] in Makefile.config as suggested in https://github.com/BVLC/caffe/issues/5141 and after which I got the below error:
"ptxas fatal   : Ptx assembly aborted due to errors" to which I found a solution in the following link: https://stackoverflow.com/questions/39287744/ubuntu-16-04-nvidia-toolkit-8-0-rc-darknet-compilation-error-expected-a where I changed the NVCC value in Makefile.config from NVCC=nvcc to NVCC=/path/where/nvcc/is/installed.
