### ISSUE TITLE
what augmentation value should be set in cfg file for x-ray type of images ??

### ISSUE THREAD

**Issue by RonakDedhiya** [AlexeyAB/darknet#1758]
Hello,
I am trying to train a network detecting boxes in x-ray images like this. Any suggestion what config parameters to use ?
![__results___24_0](https://user-images.githubusercontent.com/31977566/46904867-acc3c800-cf08-11e8-88ac-66d17ccbdf68.png)

**Comment by AlexeyAB** [comment]
@RonakDedhiya Hi,

I think you should set here: https://github.com/AlexeyAB/darknet/blob/344f8c6d27702aad61b285bac7cba9741e7ac4e8/cfg/yolov3.cfg#L14-L16
```
 saturation = 1.05 
 exposure = 2.5 
 hue=.01 
```


----

If you want to see how data augmentation affect on images, then do these changes, compile with `OPENCV=1` in the Makefile, and run Training, then press any-key to list augmented images.

Add here: https://github.com/AlexeyAB/darknet/blob/344f8c6d27702aad61b285bac7cba9741e7ac4e8/src/http_stream.cpp#L324
these lines:
```cpp
    std::stringstream window_name;
    window_name << "augmentation - " << ipl;
    cv::imshow(window_name.str(), sized);
    cv::waitKey(0);
```

**Comment by RonakDedhiya** [comment]
Thanks for the quick response!!!
