### ISSUE TITLE
Building with VS2013, showing compilation errors

### ISSUE THREAD

**Issue by Kzernobog** [AlexeyAB/darknet#176]
The only thing I changed in your "Compiling with Windows" instruction flow is to compile using Visual Studio 2013 using v120, change OpenCV paths and removed CDNN from pre-processor directives. Its giving a lot of syntax and identifier errors. Any suggestions? Is compilation with v140 a necessity?

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet/issues/3#issuecomment-267095009

It can be compiled on **MSVS 2013** (12.0.40629.00 **update 5**), but not on MSVS 2013 (12.0.21005.1). I.e. your MSVS should supports C99 standard.

**Comment by Kzernobog** [comment]
Hey thanks for the prompt reply. What sort of troubleshooting should i perform if the solution file itself is not loading on **MSVS 2015**? I went ahead and loaded the project on **MSVS 2015**, but it says that it was unable to load the project file. Tried reloading it, but nothing happens? I am a complete noob here.

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet#how-to-compile-on-windows

> If you have other version of **CUDA (not 8.0)** then open build\darknet\darknet.vcxproj by **using Notepad**, find 2 places with "CUDA 8.0" and change it to your CUDA-version, then do step 1

**Comment by Kzernobog** [comment]
Nope. I have CUDA 8.0

**Comment by AlexeyAB** [comment]
1. Can you open any solution file: `darknet.sln`, `darknet_no_gpu.sln`, `yolo_cpp_dll.sln` ?
2. Show screenshot, what error occurs?

**Comment by Kzernobog** [comment]
I can open darknet_no_gpu.sln and yolo_cpp_dll.sln. the only sln file that its not able to load is the darknet.sln.
![2015working](https://user-images.githubusercontent.com/22699172/29855675-2f4d6000-8d6b-11e7-8858-da097d37fdf1.png)

**Comment by AlexeyAB** [comment]
@Kzernobog Your MSVS2015 hasn't CUDA-Nsight plugin.
You should install CUDA 8.0 only after MSVS2015 has been installed, but not vice vers.

**Comment by Kzernobog** [comment]
Yup, Thanks a ton.
