### ISSUE TITLE
Compilation error: /bin/sh: 1: -DOPENCV: not found

### ISSUE THREAD

**Issue by JohnWnx** [AlexeyAB/darknet#1763]
Hi @AlexeyAB ,

After changing the makefile's cpp compiler from g++ to -std=c++11 (line 49 of the original make file) 
YOLO is unable to compile.

I got the following error:
![image](https://user-images.githubusercontent.com/40804580/46915469-a6078480-cfde-11e8-8b61-c37e7dcc992a.png)
"/bin/sh: 1: -DOPENCV: not found"

Does YOLO support -std=c++11?

I need to compile with -std+c++11 as it is required for compiling a file which is needed for a tesseract ocr header file which I am trying to include. i.e. If compiler is not set to "-std=c++11" ,
I'll get this error:
![image](https://user-images.githubusercontent.com/40804580/46915537-9ccae780-cfdf-11e8-8b0c-1c506ce242a3.png)

My makefile:
![image](https://user-images.githubusercontent.com/40804580/46915584-25498800-cfe0-11e8-9e76-f753523af1d4.png)

**Comment by AlexeyAB** [comment]
Try to use 
`CPP=g++ -std=c++11`

**Comment by JohnWnx** [comment]
Yup, it works now thanks!
