### ISSUE TITLE
STB Reason: can't fopen

### ISSUE THREAD

**Issue by saipran7777** [AlexeyAB/darknet#177]
I am training Darknet YOLO on Amazon EC2, p2.xlarge instance
Kindly help me with this error

My Makefile
GPU=1
CUDNN=1
OPENCV=0
OPENMP=0
DEBUG=0

Command used
./darknet detector train data/obj.data yolo-obj.cfg darknet19_448.conv.23

![capture](https://user-images.githubusercontent.com/10899398/29821201-b2bf1096-8ce4-11e7-8588-c49d2007611a.JPG)

**Comment by AlexeyAB** [comment]
Do you have file `290.jpg` in directory `data/obj/` located relatively to `darknet`-executable file?

**Comment by saipran7777** [comment]
Yes I am having both 290.jpg and 93.jpg in data/obj/ directory relative to ./darknet

**Comment by AlexeyAB** [comment]
Do you use this fork? https://github.com/AlexeyAB/darknet
Or original Linux fork? https://github.com/pjreddie/darknet

**Comment by saipran7777** [comment]
Actually I tried out both, and I am having the same problem in both.

**Comment by AlexeyAB** [comment]
@saipran7777 So, this is not related to Darknet.
It is related to your images dataset. Check paths and permissions of images files and directories using `chmod`.
Can you open this file `290.jpg` manually on Amazon instance?

**Comment by saipran7777** [comment]
Changing permissions didn't work. How do I check manually on Amazon Instance?
