### ISSUE TITLE
Errors when compiling on Windows 10

### ISSUE THREAD

**Issue by daniheras** [AlexeyAB/darknet#1778]
As the title says i have two errors when compiling.
`Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'opencv2/highgui/highgui_c.h': No such file or directory	darknet	C:\Users\Dani\Desktop\darknet\src\network_kernels.cu	40	
`

and

`Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3721	The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\nvcc.exe" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64" -x cu  -IC:\opencv_3.0\opencv\build\include -I..\..\3rdparty\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" -I\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static     -DOPENCV -DCUDNN -D_TIMESPEC_DEFINED -D_SCL_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -D_CRT_RAND_S -DGPU -DWIN32 -DNDEBUG -D_CONSOLE -D_LIB -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdx64\Release\vc141.pdb /FS /Zi  /MD " -o x64\Release\network_kernels.cu.obj "C:\Users\Dani\Desktop\darknet\src\network_kernels.cu"" exited with code 2.	darknet	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\BuildCustomizations\CUDA 10.0.targets	712	
`

Any help is welcome thank you.

**Comment by daniheras** [comment]
Okey so changing my opencv include path seems that the problem is fixed but now i have a lot of different errors, maybe i didnt fixed anything but broke it more.

![image](https://user-images.githubusercontent.com/24685447/47109773-67c4cc00-d24f-11e8-8952-86dff506dff1.png)

**Comment by AlexeyAB** [comment]
* What OpenCV version do you use?
* What MSVS version do you use?
* Did you change anything in the source code?
* Did you create your own sln-file, or do you try to compile default `build/darknet/darknet.sln` file?

**Comment by daniheras** [comment]
I'm sorry for not answering before. I was able to fix all my mistakes reading other issues, etc.
This helped me in the last mistake I mentioned https://github.com/AlexeyAB/darknet/issues/1488

**Comment by rem2016** [comment]
@daniheras Hi, I met the same problem in win10. Could you describe how you solve it?

My current env is OpenCV 3.4.3, VS 2017, and nothing was changed in the source code and using the default build/darknet/darknet_no_gpu.sln

Could simply downgrading OpenCV solve the problem?
