### ISSUE TITLE
yolov3-SPP.cfg can not training?

### ISSUE THREAD

**Issue by linqiaozhou** [AlexeyAB/darknet#1782]
it will crash when training my own data using the yolov3-spp.cfg with GPU model, while the can be run when using CPU model. is there some bug in the code?

**Comment by developer0hye** [comment]
Can you show screenshot of this error?

**Comment by AlexeyAB** [comment]
@linqiaozhou Also try to update your code from this repository, recompile and train agian.

**Comment by linqiaozhou** [comment]
> @linqiaozhou Also try to update your code from this repository, recompile and train agian.

error info in here: https://github.com/pjreddie/darknet/issues/1352

**Comment by AlexeyAB** [comment]
@linqiaozhou Use the latest version of this repository. And set `width=608 height=608` in `yolov3-spp.cfg`
