### ISSUE TITLE
make errors c++ application 

### ISSUE THREAD

**Issue by bei91** [AlexeyAB/darknet#1791]
@AlexeyAB 
Hi 
When I try to build my c++ application, the error is found:

/usr/bin/ld: cannot find -ldarknet.so

my CMakeLists.txt is following:

 # Darknet
set(DARKNET_ROOT /home/ubuntu/darknet)
include_directories(${DARKNET_ROOT}/src)
list(APPEND DARKNET_SO ${DARKNET_ROOT}/darknet.so)

add_executable(${PROJECT_NAME} main.cpp )
target_link_libraries(${PROJECT_NAME} ${DARKNET_SO} )

**Comment by AlexeyAB** [comment]
@bei91 Hi,

Try to use: https://cmake.org/cmake/help/v3.0/command/set_target_properties.html
something like this:
```
list(APPEND DARKNET_SO ${DARKNET_ROOT}/darknet.so)
SET_TARGET_PROPERTIES(${DARKNET_SO} PROPERTIES PREFIX "")
target_link_libraries(${PROJECT_NAME} ${DARKNET_SO} )
```

or something like this:
```
add_library(darknet SHARED IMPORTED)
SET_TARGET_PROPERTIES(darknet  PROPERTIES PREFIX "")
target_link_libraries(${PROJECT_NAME} darknet )
```

**Comment by bei91** [comment]
@AlexeyAB Hi,
Thanks ,I have solved this problem.
The reason for this problem is when darknet is made libdarknet.so should be generated rather than darknet.so

**Comment by gameon67** [comment]
@bei91 Hi can you show me your CMakeLists.txt full content? I keep failing using libdarknet.so for my c++ program
