### ISSUE TITLE
Problem when trying with multi gpu

### ISSUE THREAD

**Issue by deepkshikha** [AlexeyAB/darknet#1792]
root@6dd1639a0294:/workspace/data/dgx/darknet/build/darknet/x64# ./darknet detector train data/obj.data yolo-obj.cfg /backup/yolo-obj_3000.weights -gpus 0,1,2,3-dont_show
0,1,2,3-dont_show
yolo-obj
No input parameters supplied: No such file or directory
darknet: ./src/utils.c:277: error: Assertion `0' failed.
Aborted (core dumped)
root@6dd1639a0294:/workspace/data/dgx/darknet/build/darknet/x64#

**Comment by deepkshikha** [comment]
Solved

**Comment by iRmantou** [comment]
@deepkshikha 
hi, I have meet the same problem could share how you solved this problem

**Comment by deepkshikha** [comment]
I restarted the system and it works for me
