### ISSUE TITLE
Weights of YOLO 2

### ISSUE THREAD

**Issue by VanitarNordic** [AlexeyAB/darknet#18]
Hello,

The pre-trained weights which you have mentioned in the description, I mean `darknet19_448.conv.23`, refers to the 416 *416 resolution?

What about if we use the YOLO2 weights in its website in accompany with modified `.cfg` files?

![2017-02-04_11-40-22](https://cloud.githubusercontent.com/assets/18719591/22616999/2c86873c-eacf-11e6-9b20-0d1c0c430ff1.png)

**Comment by AlexeyAB** [comment]
@VanitarNordic 

You can use any weights with any resolution in `.cfg`-file.

* darknet19_**448**.conv.23 - pre-trained on ImageNet with resolution 448x448
* `yolo.weights` & `yolo-voc.weights` trained (fine-tuned) at the full 448 × 448 resolution 

https://arxiv.org/pdf/1612.08242v1.pdf?
> For YOLOv2 we first fine tune the classification network at the full 448 × 448 resolution for 10 epochs on ImageNet.

**Comment by VanitarNordic** [comment]
Thanks, Also I want to know where can I get the latest competition results of every model, such as YOLO, SSD and so on on a chart? is there any website or document for that?

**Comment by AlexeyAB** [comment]
@VanitarNordic 

See VOC, COCO & ImageNet: https://github.com/AlexeyAB/darknet/issues/2#issuecomment-271669674
And see submission dates.

**Comment by VanitarNordic** [comment]
Okay, I continue there. Thanks.

**Comment by zhouxiaoxu** [comment]
![image](https://cloud.githubusercontent.com/assets/20697973/25377461/38db1210-29da-11e7-895f-ead809ac02b4.png)
Did yolo.weights & yolo-voc.weights  not trained (fine-tuned) at the  416 × 416 resolution？

**Comment by AlexeyAB** [comment]
@zhouxiaoxu 

To be more precise:

* `darknet19_448.conv.23` - pre-trained on ImageNet with resolution 448x448
* `yolo.weights` & `yolo-voc.weights` - trained (fine-tuned) at the dynamic resolution 320x320 - 608x608

https://arxiv.org/pdf/1612.08242v1.pdf

> For YOLOv2 we first fine tune the classification network
> at the full **448 × 448 resolution for 10 epochs on ImageNet**.
> This gives the network time to adjust its filters to work better
> on higher resolution input. We then fine tune the resulting
> network on detection. 


> Instead of fixing the input image size we change the network
> every few iterations. Every 10 batches our network
> randomly chooses a new image dimension size. Since our
> model downsamples by a factor of 32, we pull from the
> following multiples of 32: {320, 352, ..., 608}. Thus the
> smallest option is **320 × 320 and the largest is 608 × 608**.
> We resize the network to that dimension and continue training.
