### ISSUE TITLE
test failed in yolov3-tiny_xnor.cfg when I use msvc(32bit,Release).

### ISSUE THREAD

**Issue by ZJU-lishuang** [AlexeyAB/darknet#1807]
Hi, I train a model use yolov3-tiny_xnor.cfg ,but I cannot test it when target win32|x86(Release) in msvc 2015.It failed in calculate_binary_weights(net).But it succeeded when target win32|x86(Debug) in msvc 2015.
Is this either a bug or my mistake?Could you help me?

Thanks a lot!

**Comment by AlexeyAB** [comment]
@ZJU-lishuang Hi,

I fixed this bug - for 32-bit compilation without GPU `darknet_no_gpu.sln`, for Debug and Release. 
Update your code from GitHub.


![image](https://user-images.githubusercontent.com/4096485/47384074-c76b1d80-d70e-11e8-9476-07524097f9ea.png)
