### ISSUE TITLE
mark object selection question

### ISSUE THREAD

**Issue by wani2919** [AlexeyAB/darknet#1813]
In an image in which a plurality of training object objects exist,
When selecting the mark target,
Should the sibling only mark the objects that appear perfect?
Or should I mark all the objects in the image, even if some are hidden?
If you have to mark some obscured objects, how much degree of obscurity is acceptable?

For example, when two objects are overlapped on one image,
The object on top is perfectly formed, and only 40% to 60% of the underlying objects are visible.
Do I have to mark or not mark only the parts of the object that are under the training object label mark?

Thanks.

**Comment by wani2919** [comment]
Thanks @AlexeyAB

Can the degree of overlap be set by adjusting the nms value, and if the default value (.45) overlaps to less than 45%, should the label not be set?

Thnaks.

**Comment by AlexeyAB** [comment]
If nms=0.45, then if 2 detected objects overlap by 45% then Yolo will show only 1 boundex box with the highest probability.

You can change nms in the source code if you want.

**Comment by wani2919** [comment]
Thanks @AlexeyAB
