### ISSUE TITLE
Parameter tuning -- ignore_thresh and truth_thresh

### ISSUE THREAD

**Issue by ZedYeung** [AlexeyAB/darknet#1814]
What are these two parameters mean?
I think that the threshold is based on IOU.
And then the IOU less than ignore_thresh would be seen as a negative sample?
IOU greater than truth_thresh would be seen as a positive sample?

**Comment by AlexeyAB** [comment]
They are used during Yolo v3 training.

* If detected bounded box overlapped with truth box with `IoU > ignore_thresh` then o**bjectness of this bounded box will not be decreased** (`delta=0`) - i.e. we think that objects is detected correctly: https://github.com/AlexeyAB/darknet/blob/7f4b859514c7fcae1f9cc86276be31f133b5bc7c/src/yolo_layer.c#L219-L221

----

* If detected bounded box overlapped with truth box with `IoU > truth_thresh` then **objectness of this bounded box will be increased** (`1 - l.output[obj_index]`) and bounded box position will be corrected - will be calculated deltas for `x,y,w,h`. It is required if we want several anchors and final activations to detect the same object with several bounded boxes, which will be fused by Non-maximum supression (nms): https://github.com/AlexeyAB/darknet/blob/7f4b859514c7fcae1f9cc86276be31f133b5bc7c/src/yolo_layer.c#L222-L231

You can set `truth_thresh=0.7` in your cfg-file, if there are a small number of objects on your images and they are not overlapped - it can increase accuracy in this case.

**Comment by ZedYeung** [comment]
Thanks

**Comment by CuongNguyen218** [comment]
@AlexeyAB ,
As I understand, IOU always in [0,1] but I saw you set truth thresh = 1. Can you explain it for me ?
