### ISSUE TITLE
darknet.sln does not build

### ISSUE THREAD

**Issue by anhminh3105** [AlexeyAB/darknet#1819]
Hello,

I try to compile darknet following your intructions on VS 2017 but when I ``build darknet``, the output always logs ``Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped``. I have try seveval ways but it still couldn't be fixed. 

![output](https://user-images.githubusercontent.com/18170028/47465197-9bc26300-d7f4-11e8-87b5-0987d534ebbe.png)

My CUDA,cuDNN verions and my system variables are shown below:

![vars](https://user-images.githubusercontent.com/18170028/47465061-f8714e00-d7f3-11e8-9899-039c212dbc91.png)

here is the property of ``darknet.sln``:

![prop](https://user-images.githubusercontent.com/18170028/47465193-9107ce00-d7f4-11e8-85c4-0bf9bac68318.png)

Also, I tried to set ``CUDA 9.1`` to ``CUDA 9.0...``` but it does not fix the problem.

![image](https://user-images.githubusercontent.com/18170028/47465391-6d915300-d7f5-11e8-9ade-50ce4ce19df5.png)

![image](https://user-images.githubusercontent.com/18170028/47465358-4a66a380-d7f5-11e8-8dfb-4e4bb415c64d.png)

Could you please help me figure this out I'm really stuck here.

**Comment by anhminh3105** [comment]
yes I did it. Also I tried other combinations but it's still the name.

Now I'm following this issue https://github.com/AlexeyAB/darknet/issues/1455#issuecomment-416030423 but weirdly I don't have the branch CUDA C/C++ on the left pane.

**Comment by AlexeyAB** [comment]
Can you show **fullscreen** screenshot with this error?
![output](https://user-images.githubusercontent.com/18170028/47465197-9bc26300-d7f4-11e8-87b5-0987d534ebbe.png)

**Comment by anhminh3105** [comment]
Thanks for your responds and supports, I finally made it work after nearly a day of struggle. Actually no error was prompted and I was quite clueless.

#### Here is how I did:

1. Followed your hint from this link https://github.com/AlexeyAB/darknet/issues/550#issuecomment-378193062 I change the CUDA version to my current one.

![image](https://user-images.githubusercontent.com/18170028/47465391-6d915300-d7f5-11e8-9ade-50ce4ce19df5.png)

![image](https://user-images.githubusercontent.com/18170028/47465358-4a66a380-d7f5-11e8-8dfb-4e4bb415c64d.png)

2. Then picked up the step from this [instruction](https://blogs.msdn.microsoft.com/jamiedalton/2018/03/23/yolo-on-azure-deep-learning-virtual-machine-windows/) which took this [reference](https://blogs.msdn.microsoft.com/vcblog/2017/11/15/side-by-side-minor-version-msvc-toolsets-in-visual-studio-2017/) I copied the .props file (mine is Microsoft.VCToolsVersion.14.11.props at this time) to the build folder and added an extra line in ``darknet.vcxproj`` to import this file.

![image](https://user-images.githubusercontent.com/18170028/47468430-ee574b80-d803-11e8-947a-1921c1fcba42.png)

Then the build works!
(For those whom got this problem and do this but it still doesn't build then try switching between the Platform Toolset in ``darknet.vcxproj``>Right Click>Properties to Visual Studio 2015 v140 and the newest one, mine is Visual Studio 2017 v141 at this time)
