### ISSUE TITLE
Backup path with whitespaces

### ISSUE THREAD

**Issue by FenryrMKIII** [AlexeyAB/darknet#1821]
I need to save the weights on google drive.
Problem is, google drive has a whitespace in its name i.e. "My Drive" and I cannot change this.

The way darknet handles the backup path, I can't manage to make it understand that there is a whitespace in "My Drive". I have tried \ , putting ' ' and " " around the path in obj.data; nothing does the trick.

Can someone provide me with a solution ? Possibly, tell me which lines I need to change in the source code so that it can handle whitespace in the path given to store the backup files ?

Thank you !

**Comment by lizyn** [comment]
I met exactly the same issue as you. And after failing at trying different things in the .cfg file, I solved it by a workaround:

Executing `!ln -s /content/gdrive/My\ Drive/path/to/dir/ darknet/backup/` in a Colab cell.

This will map a desired dir in Google Drive under `darknet/backup/`, and backup files will be 'sync' to Google Drive automatically.

**Comment by FenryrMKIII** [comment]
Wow nice workaround!
