### ISSUE TITLE
is this a valid annotation file?

### ISSUE THREAD

**Issue by k00r** [AlexeyAB/darknet#1828]
Hello Alexey,how are you? i hope you're fine,i am using a third party tool called "Boobs" for annotating my dataset https://medium.com/@drainingsun/boobs-yolo-bbox-annotation-tool-96fb765d0036
mainly because it has built-in zoom and crosshair features.The contents of it's annotation files look like this for two annotated objects of the same class;
![alexey-boobs-example](https://user-images.githubusercontent.com/38154308/47603146-7d28bb80-d9f0-11e8-9d28-a1324b93b121.JPG)
While your annotator tool's contents of it's respective files look like this,also for two annotated objects of the same class;
![alexeys-own-annotator-tool-example](https://user-images.githubusercontent.com/38154308/47603180-28d20b80-d9f1-11e8-89d7-7af2bcb47098.JPG)
Will this format difference in the annotation text files cause an error or some unwanted behaviour while training darknet? (your repo not Joseph's)

**Comment by AlexeyAB** [comment]
@k00r Hi, thanks, I am fine )

> ![alexey-boobs-example](https://user-images.githubusercontent.com/38154308/47603146-7d28bb80-d9f0-11e8-9d28-a1324b93b121.JPG)
> Will this format difference in the annotation text files cause an error or some unwanted behaviour while training darknet? 

Yes, you can't train with this annotation format.

You should use format: `<class_id> <x_center> <y_center> <width> <height>` with only 5 values per line.
Or you should write or find script for this conversion.

**Comment by AlexeyAB** [comment]
@k00r 

It looks different from the values in Yolo_mark. 
Try to replace txt-lebel file that you created in Yolo_mark to these values, then open it in Yolo_mark and show screenshot of the image with bounded boxes.

**Comment by k00r** [comment]
@AlexeyAB sorry for the delayed response,i was sick
when i open the other annotation file with Yolo_mark's latest version it shows like this;
looks all correct despite the values being a little different,what do you think?
![alexey-show](https://user-images.githubusercontent.com/38154308/47963258-77f3ee00-e03a-11e8-8907-bffbd675f28c.JPG)

**Comment by AlexeyAB** [comment]
These labels are correct )
