### ISSUE TITLE
Dependence of frame rate of test video on compilation with CUDNN

### ISSUE THREAD

**Issue by Kzernobog** [AlexeyAB/darknet#183]
Hi, just wanted to find out if there is a correlation between the frame rate at which a test video is processed using yolo, and whether or not you compile darknet.sln using the CUDNN preprocessor directive.
I removed the CUDNN pre-processor directive. I am getting a frame rate of 4.5 while utilising the pre-trained weights with a HD video.

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet/issues/61#issuecomment-293644312

> cuDNN accelerates ~1.5x times training
> cuDNN on Maxwell and Pascal - detection has the ~ same speed with or without cuDNN.
> (on Maxwell GeForce GTX 970 with and without cuDNN - detection on 1000 images - 29 sec.)
> For old Kepler or Fermi architecture cuDNN can work slowly than without cuDNN

**Comment by Kzernobog** [comment]
Also, in your 'how to use' specification doc, is there a specific command to use the yolov2.

**Comment by AlexeyAB** [comment]
@Kzernobog This doc is whole about Yolo v2: https://github.com/AlexeyAB/darknet#yolo-v2-windows-and-linux-version
