### ISSUE TITLE
Using YoloV3 as dll in C++ program

### ISSUE THREAD

**Issue by nasir3843** [AlexeyAB/darknet#1839]
Could anyone guide me through how can I make a dll file of darknet and how can I use those dll files in C++program. I have weights files available that I managed to train using my custom dataset. I am new to
dll files making and using in Visual Studio. So far, I have tried this guide 
https://github.com/AlexeyAB/darknet#how-to-use-yolo-as-dll. I can successfully build 
build\darknet\yolo_cpp_dll.sln. In second step when I try to run build\darknet\yolo_console_dll.sln to 
run the dll in console application I get this error

LINK : fatal error LNK1181: cannot open input file 'x64\yolo_cpp_dll.lib'
Any help is much appreciated

My enviroment is composed of:
Visual studio 2015
Cuda 9.1 
Cudnn 7
OpenCV 3.2.0
Windows 10

**Comment by bit-scientist** [comment]
@nasir3843 hi, please share what you did to resolve this. 
Thank you!
