### ISSUE TITLE
setting subdivisions parameter for detection

### ISSUE THREAD

**Issue by corentin87** [AlexeyAB/darknet#1853]
Hi Alex,

In your Readme in the "How to improve object detection", you wrote:
_if error Out of memory occurs then in .cfg-file you should increase subdivisions=16, 32 or 64_

But for the detection part we only pass 1 image for the training so batch and subdivisions should be equal to 1 (or equal). The subdivisions parameter tells how much memory we will use. So why would you set it up to either 16, 32, 64, and reserve more memory that what you need?

Although I've noticed this has been changed in some of the latest commits of the official darknet, making the difference between testing and training.
Maybe you need to update your Readme file?

Thanks

**Comment by AlexeyAB** [comment]
@corentin87 Hi,

> if error Out of memory occurs then in .cfg-file you should increase subdivisions=16, 32 or 64

This refers to Training.

I fixed readme: https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

> but to get even greater accuracy you should train with higher resolution 608x608 or 832x832, note: if error Out of memory occurs then in .cfg-file you should increase subdivisions=16, 32 or 64: link

----

For Detection forced `batch=1 subdivisions=1` so we shouldn't change batch=1 subdivisions=1 in cfg-file if you use this repo - it is hardcoded here: 
* https://github.com/AlexeyAB/darknet/blob/08e8e0c8c2d3cddfb6ee065e813ae5023f9568d2/src/detector.c#L342
* https://github.com/AlexeyAB/darknet/blob/08e8e0c8c2d3cddfb6ee065e813ae5023f9568d2/src/detector.c#L466
* https://github.com/AlexeyAB/darknet/blob/08e8e0c8c2d3cddfb6ee065e813ae5023f9568d2/src/detector.c#L572
* https://github.com/AlexeyAB/darknet/blob/08e8e0c8c2d3cddfb6ee065e813ae5023f9568d2/src/detector.c#L1112
* https://github.com/AlexeyAB/darknet/blob/08e8e0c8c2d3cddfb6ee065e813ae5023f9568d2/src/demo.c#L143


So

**Comment by corentin87** [comment]
Yes i'm actually using the official one and i'm not up to date with the latest commit so for detection subdivisions is not forced to 1, thus allocated too much memory.
Thanks.

**Comment by AlexeyAB** [comment]
Also note that Darknet allocates `memeory = batch/subdivisions`, so too much memory allocation occurs due to batch rather than subdivisions.

**Comment by corentin87** [comment]
right thanks. I was just changing the subdivisons parameter and _subdivions=1_ would take 1.3G while _subdivisions=8_ would take 3.2G so big difference!
