### ISSUE TITLE
Why can yolov2_tiny load the darknet19_448.conv.23?

### ISSUE THREAD

**Issue by HamanoYusuke** [AlexeyAB/darknet#1874]
Thank you for your great works. You have been VERY helpful.

I tryed training yolov2_tiny on my dataset.
I customed yolov2-voc.cfg to fit my dataset. classes and filters..etc and executed the following command.
「./darknet detector train cfg/own.data cfg/yolov2_tiny.cfg darknet19_448.conv.23」
I get following result. 
![rect4180](https://user-images.githubusercontent.com/44728376/47954013-6f62cf80-dfc8-11e8-9bf8-8de1e857892a.png)
I wonder that yolov2_tiny load darknet19_448.conv23.
I am going to understand the difference between yolov2_tiny and darknet19.
If yolov2_tiny correctly load darknet19_448.conv23, Does this aproach help to learn model?

Or, should I get the pretrianed weights by download yolov2-tiny-voc.weights from the darknet official page, and execute folloing command [./darknet partial cfg/yolov2-vco.cfg yolov2-tiny-voc.weights ]?

I am sorry for cheap my English. I am waiting for reply.

**Comment by AlexeyAB** [comment]
> Or, should I get the pretrianed weights by download yolov2-tiny-voc.weights from the darknet official page, and execute folloing command [./darknet partial cfg/yolov2-vco.cfg yolov2-tiny-voc.weights ]?

You should do exactly that: https://github.com/AlexeyAB/darknet#how-to-train-tiny-yolo-to-detect-your-custom-objects
`./darknet partial cfg/yolov3-tiny.cfg yolov3-tiny.weights yolov3-tiny.conv.15 15`

`./darknet detector train data/obj.data yolov3-tiny-obj.cfg yolov3-tiny.conv.15`

----

> If yolov2_tiny correctly load darknet19_448.conv23, Does this aproach help to learn model?

No, it doesn't load `darknet19_448.conv23`-weights-file into the model `yolov2_tiny` correctly.
It doesn't help to learn a model.

**Comment by HamanoYusuke** [comment]
I will more learn to this repositoy . Please give me your support, if I'm confused.
Thank you.
