### ISSUE TITLE
Darknet Classifier related issue

### ISSUE THREAD

**Issue by benn94** [AlexeyAB/darknet#1878]
### Issue 1
By following darknet website, I was validating classifiers on imagenet.
I have made changes to `imagenet1k.data` as mentioned bellow 

```
classes=1000
train  = /data/inet.val.list
valid  = /data/inet.val.list
backup = /home/pjreddie/backup/
labels = data/imagenet.labels.list
names  = data/imagenet.shortnames.list
top=5
```
Even after I changed `darknet19.cfg`

```
batch=64
subdivisions=64
```
I still got the same error

_command_
`darknet.exe classifier valid cfg/imagenet1k.data cfg/darknet19.cfg darknet19.weights`

_output_
```
layer     filters    size              input                output
   0 conv     32  3 x 3 / 1   224 x 224 x   3   ->   224 x 224 x  32 0.087 BF
   1 max          2 x 2 / 2   224 x 224 x  32   ->   112 x 112 x  32 0.002 BF
   2 CUDA Error: out of memory
```

while I could predict classification without any error

_command_
 `darknet.exe classifier predict cfg/imagenet1k.data cfg/darknet19.cfg darknet19.weights data/dog.jpg` 

_output_
```
Total BFLOPS 5.585
Loading weights from darknet19.weights...
seen 32
Done!
224 224
data/dog.jpg: Predicted in 0.008000 seconds.

Eskimo dog: 0.284823
malamute: 0.157039
Siberian husky: 0.141494
German shepherd: 0.045907
miniature schnauzer: 0.038957
```

### Issue 2
I also have followed your instruction at [#952](https://github.com/AlexeyAB/darknet/issues/952#issuecomment-393507121). I could get pre-trained weights for training and run command for classification successfully however I got an erro while running command for training (using same  `imagenet1k.data` mentioned above)

_command_
`darknet.exe classifier train cfg/imagenet1k.data cfg/resnet152.cfg resnet152.201`

_output_
`Couldn't open file: /data/imagenet/imagenet1k.train.list`

**Comment by ChandanVerma** [comment]
The issue 2 occurs because if you open the imagenet1k.data file you will see that it expects imagenet1k.train.list in the data folder. since this file does not come in when you clone the repository the error occurs

When it comes to issue 1 can you tell me are you using any GPU?
