### ISSUE TITLE
does source code support multi-thread?

### ISSUE THREAD

**Issue by linquanxu** [AlexeyAB/darknet#1879]
hi, AlexeyAB,
When i use this code to predict objects on Windows 10, i do not know whether the code supports multi-threading to utilize all cores of CPU？

**Comment by AlexeyAB** [comment]
@linquanxu Hi,

* If you compile `darknet_no_gpu.sln` then it uses multi-threading for Inference

* If you compile `darknet.sln` then it doesn't use multi-threading for Inference, since it doesn't make sense. 
     It only uses multi-threading for `darknet detector demo` for: capture, detection, showing in 3 separate threads.

**Comment by linquanxu** [comment]
@AlexeyAB Thank you for your rapid reply.
I compiled darknet_no_gpu.sln and set OPENMP in VS2015, however, I haven't found any improvement in inference speed.

**Comment by AlexeyAB** [comment]
You shouldn't set `#define OPENMP` on Windows, because it is enabled by default.

**Comment by linquanxu** [comment]
@AlexeyAB ,Thanks,
I set OPEMMP as follows(VS2015: properties->c/c++/Preprocessor) and Recompiled：
![image](https://user-images.githubusercontent.com/16631303/47989048-d85c5b80-e11e-11e8-89c4-48bf2fa5c601.png)
but I failed. how to fix it？

**Comment by AlexeyAB** [comment]
![article7_6](https://user-images.githubusercontent.com/4096485/47992362-c4543200-e0fd-11e8-984d-370b982ead37.png)

**Comment by linquanxu** [comment]
@AlexeyAB thank you very much.
