### ISSUE TITLE
Debug mode in VS2015 without GPU

### ISSUE THREAD

**Issue by dennistang742** [AlexeyAB/darknet#1881]
Hi AlexeyAB,

OpenCV: opencv-3.3.0-vc14.exe
IDE: VS 2015 update 3
Version: 2c5e38

First of all, thanks for your kindy share.

Now I get a problem in debug mode in VS2015.
When I in debug mode, the behavior always goes into the route which not define OpenCV (line 355 in demo.c).
But once I turn on the compile option, compiling procedure will stuck at line 58 in cvdef.h. This line said "namespace cv { namespace debug_build_guard { } using namespace debug_build_guard; }"

So I need your help that how do you enter the debug mode in VS2015, thanks.

**Comment by AlexeyAB** [comment]
@dennistang742 Hi,

This is C API bug in OpenCV: https://github.com/opencv/opencv/issues/10405
This is luck that this OpenCV C API works in Release.

Try to use earlier version of OpenCV, may be it will work.

**Comment by dennistang742** [comment]
@AlexeyAB Hi AlexeyAB,

Thanks for your kindly and quickly reply.
Now I can enter debug mode in opencv-2.4.13.6-vc14 now.
Thank you very much.
![Snapshot](https://user-images.githubusercontent.com/23069905/48037666-4e58d500-e1a8-11e8-888b-4ce8aa8f46c3.png)
