### ISSUE TITLE
unable to read darknet.vcxproj

### ISSUE THREAD

**Issue by interaktifgrup** [AlexeyAB/darknet#1894]
Hello Alexey
I ran across this issue.Using Windows 10,MSVS 2015,CUDA 9.1,cuDNN 7.1,OpenCV 3.0
Can you help?
![issue1](https://user-images.githubusercontent.com/44837803/48131557-8859d200-e2a1-11e8-921c-8b0fa7072143.PNG)

**Comment by AlexeyAB** [comment]
@interaktifgrup Hi,

* Did you installed CUDA 9.1 after that MSVS 2015 was installed?

* Do you have this file `CUDA 9.1.props` in this folder 
`C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\BuildCustomizations\` ?

**Comment by interaktifgrup** [comment]
@AlexeyAB 
1)No
2)No

**Comment by interaktifgrup** [comment]
@AlexeyAB 
problem was solved when i re-installed CUDA,it seems CUDA needs to be installed after the Visual Studio

**Comment by AlexeyAB** [comment]
> CUDA needs to be installed after the Visual Studio

Yes.
