### ISSUE TITLE
Failed to make on OPENCV = 1 and/or CUDA = 1

### ISSUE THREAD

**Issue by NullPointer0000** [AlexeyAB/darknet#1895]
I'm a beginner to this so I don't really know what's going on. At first I was getting errors where it couldn't find opencv and cuda files so I added the directories to the makefile although I don't know if this is what you should do

ie:
ifeq ($(OPENCV), 1) 
COMMON+= -DOPENCV -I"C:/opencv/build/include/"
...
ifeq ($(GPU), 1)
COMMON+= -DGPU -I"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/include/"
CFLAGS+= -DGPU
ifeq ($(OS),Darwin) #MAC
LDFLAGS+= -L"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib" -lcuda -lcudart -lcublas -lcurand
else
LDFLAGS+= -L"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64" -lcuda -lcudart -lcublas -lcurand
....

this got rid of the errors but now I have a new problem and can't find a single solution online to this

nvcc  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -gencode arch=compute_61,code=[sm_61,compute_61] -I -DOPENCV -I"C:/opencv/build/include/" `pkg-config --cflags opencv`  -DGPU -I"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/include/" --compiler-options "-Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV  -DGPU" -c ./src/convolutional_kernels.cu -o obj/convolutional_kernels.o
convolutional_kernels.cu
cl : Command line error D8021 : invalid numeric argument '/Wfatal-errors'
make: *** [Makefile:142: obj/convolutional_kernels.o] Error 2

**Comment by AlexeyAB** [comment]
If you want to compile Darknet on Windows then use this manual: https://github.com/AlexeyAB/darknet#how-to-compile-on-windows

**Comment by NullPointer0000** [comment]
> If you want to compile Darknet on Windows then use this manual: https://github.com/AlexeyAB/darknet#how-to-compile-on-windows

Thanks, worked perfectly.
