### ISSUE TITLE
voc_label_difficult.py

### ISSUE THREAD

**Issue by Sunyouteng** [AlexeyAB/darknet#1900]
@AlexeyAB 
HI, this file should be in`the dir build\darknet\x64\data\` as you said in  How to calculate mAP on PascalVOC 2007:.
in the code 
`for year, image_set in sets:
    if not os.path.exists('VOCdevkit/VOC%s/labels/'%(year)):
        os.makedirs('VOCdevkit/VOC%s/labels/'%(year))
    image_ids = open('VOCdevkit/VOC%s/ImageSets/Main/%s.txt'%(year, image_set)).read().strip().split()
    list_file = open('difficult_%s_%s.txt'%(year, image_set), 'w')
    for image_id in image_ids:
        list_file.write('%s/VOCdevkit/VOC%s/JPEGImages/difficult_%s.jpg\n'%(wd, year, image_id))
        convert_annotation(year, image_id)
    list_file.close()`
1 it will mkdir VOCdevkit first. then i will get image_ids from VOCdevkit you just created. it will be error. So is something wrong with this pytho script? 
2 why do you new the dificult.txt? why dont you just use the 2007_test.txt as sample?
look forward to your help. thanks.

**Comment by AlexeyAB** [comment]
@Sunyouteng Hi,

1. You should run `voc_label_difficult.py` near with `VOCdevkit` (not inside `VOCdevkit`)

2. You should run `voc_label_difficult.py` only if you want to get mAP for Pascal VOC by using `./darknet detector map`...

If you want to get mAP for Pascal VOC by using this scripts: https://github.com/AlexeyAB/darknet/blob/master/build/darknet/x64/calc_mAP_voc_py.cmd
then you shouldn't run  `voc_label_difficult.py`

**Comment by Sunyouteng** [comment]
@AlexeyAB 
hi, 
First, thanks for your quick reply. It need your patience to do this. You are cool
Second, I sloved my question with your suggestion. But there is still misleading words I think.
In 《How to calculate mAP on PascalVOC 2007:》

- Download PascalVOC dataset, install Python 3.x and get file 2007_test.txt as described here: https://github.com/AlexeyAB/darknet#how-to-train-pascal-voc-data
- Then download file https://raw.githubusercontent.com/AlexeyAB/darknet/master/scripts/voc_label_difficult.py to the dir build\darknet\x64\data\ then run voc_label_difficult.py to get the file difficult_2007_test.txt
In the first step, we will have `build\darknet\x64\data\voc\VOCdevkit`;
In the second step, I download voc_label_difficult.py to the dir build\darknet\x64\data\ then run voc_label_difficult.py. 
This is my understanding with this description. Obiviously it will go wrong. I dont know if i misunderstand your words or your words are misleading. 
In all, i want to give you a advice to change the detailed dir of where is the voc_label_difficult.py.
If i am wrong. Plz tell me. 
Last , your readme is much better comparing most of the githubs'.
cheers.
Youteng Sun

**Comment by zrobotparking** [comment]
I tried to train `yolov3-tiny` on VOC. But only get map 9.09%. Is that correct?
I do run `voc_label_difficult.py` before  using `./darknet detector map ..`

**Comment by reactivetype** [comment]
> @Sunyouteng Hi,
> 
> 1. You should run `voc_label_difficult.py` near with `VOCdevkit` (not inside `VOCdevkit`)
> 2. You should run `voc_label_difficult.py` only if you want to get mAP for Pascal VOC by using `./darknet detector map`...
> 
> If you want to get mAP for Pascal VOC by using this scripts: https://github.com/AlexeyAB/darknet/blob/master/build/darknet/x64/calc_mAP_voc_py.cmd
> then you shouldn't run `voc_label_difficult.py`

I do not understand why I need to run `voc_label_difficult.py` instead of `voc_label`.py in order to calculate the mAP. Looking at `voc_label_difficult.py`, it seems lists filenames with difficult objects only.
