### ISSUE TITLE
resize_image vs letterbox_image

### ISSUE THREAD

**Issue by huchhong** [AlexeyAB/darknet#1907]
I noticed that this repo use resize_image instead of letterbox_image which is used in pjreddie's version during detection training and testing. letterbox_image will keep aspect ratio of original image while resize_image won't. Any reason to make this choice?

**Comment by AlexeyAB** [comment]
* `resize_image()` is better than `letterbox_image()` for small objects

* If you the size of images in Training dataset is the same as in Test dataset, then distortion will be identical, so we shouldn't keep aspect ratio.

More: https://github.com/AlexeyAB/darknet/issues/232#issuecomment-336955485

**Comment by huchhong** [comment]
Thanks for your reply. I get it.
