### ISSUE TITLE
Large delay when using demo

### ISSUE THREAD

**Issue by HUNGLiquid** [AlexeyAB/darknet#1908]
Hi @AlexeyAB , I try to test my weights with IP camera. When I run 

"darknet.exe detector demo data/obj.data yolo-obj.cfg yolo-obj_6200.weights rtsp://192.168.0.117/user=admin_password=_channel=1_stream=0.sdp -i 0 "
 It has results but the video stream is slower than real time 20-25s. I dont know why even when the delay between the IP-PC.
![image](https://user-images.githubusercontent.com/32360741/48250024-7c9c1600-e42f-11e8-8eab-24431708d14d.png)

**Comment by AlexeyAB** [comment]
@HUNGLiquid Hi,

* comment these lines:

    * https://github.com/AlexeyAB/darknet/blob/14ed6fcb6e31dd111fc5c35c31ffa6e45fe52737/src/yolo_console_dll.cpp#L401

    * https://github.com/AlexeyAB/darknet/blob/14ed6fcb6e31dd111fc5c35c31ffa6e45fe52737/src/yolo_console_dll.cpp#L410

* Try to compile `yolo_cpp_dll.dll` then compile `yolo_console_dll.sln`
and run this command:

`yolo_console_dll.exe data/obj.names yolo-obj.cfg yolo-obj_6200.weights rtsp://192.168.0.117/user=admin_password=_channel=1_stream=0.sdp`

----


* compile OpenCV with GStreamer on Windows
    * https://stackoverflow.com/questions/45957301/how-to-build-opencv-3-3-0-with-gstreamer-on-windows
    * https://cvexplorare.wordpress.com/2016/11/15/opencv-gstreamer-windows/



Related question for Linux: https://github.com/AlexeyAB/darknet/issues/1893#issuecomment-436810914

**Comment by HUNGLiquid** [comment]
Thank you @AlexeyAB. It works. But the yolo_console_dll is too complicated and i see it didn't use "draw_detections_v3" in test_detector or same demo. I just want to get images from stream and detect after that show this. What is the simplest way I can do it?
