### ISSUE TITLE
Is there any way I can add Gaussian noise on the fly during training yolov3?

### ISSUE THREAD

**Issue by kmsravindra** [AlexeyAB/darknet#1909]
@AlexeyAB, I want to know if there is any way by which I can add gaussian noise on the fly during training yolov3? OR Do I need to create this augmented data myself and pass it through ? Thanks!

**Comment by nezygis** [comment]
@kmsravindra @AlexeyAB 

Hello, maybe there's any update to this question? Is gaussian noise an available option?

**Comment by AlexeyAB** [comment]
@kmsravindra @nezygis

There is no Gaussian noise yet. I will add it later.

----

I added only Gaussian blur.
In the last version of Darknet you can use `blur=1` parameter in the `[net]` section in cfg-file

* `blur=1` - will be used Gaussian with `kernel=31x31` only for background except objects

* `blur=2` and higher 3,4... - will be used Gaussian blur with `kernel=blur X blur` (blur-value will be increased up to odd value) for whole image

**Comment by alxBO** [comment]
Any news about Gaussian Noise during training ?

**Comment by AlexeyAB** [comment]
Added param `gaussian_noise=40` to cfg-file: https://github.com/AlexeyAB/darknet/commit/5c2ddd301e51d60a700797d58bb2e8e686b4bd47
Usage: 
```
[net]
gaussian_noise=40  # from 0 to 127
```

example of noised and non-noised training images:
![image](https://user-images.githubusercontent.com/4096485/77252090-27972380-6c63-11ea-9019-3e48bc2d3cd3.png)

**Comment by alxBO** [comment]
does it make sense to add a black and white noise when training on b&w dataset ?
