### ISSUE TITLE
Total number of parameters in yolo v2 and v3

### ISSUE THREAD

**Issue by srinivas1746** [AlexeyAB/darknet#1910]
Can anyone tell me the total number of parameters in yolo2 and v3 architecture

**Comment by AlexeyAB** [comment]
51 millions and 62 millions.


* `yolov2.weights` - 203 934 260 bytes / 4 ~= **50 983 565 floats**
(608x608 - mAP = 48.1% on MS COCO)

* `yolov3.weights` - 248 007 048 bytes / 4 ~= **62 001 762 floats**
(608x608 - mAP = 57.9% on MS COCO)

----

There is also small overhead: `major ,minor, revision, net.seen, l.outputs, size`:  https://github.com/AlexeyAB/darknet/blob/14ed6fcb6e31dd111fc5c35c31ffa6e45fe52737/src/parser.c#L967-L1023
