### ISSUE TITLE
Run multiple model on multiple GPU

### ISSUE THREAD

**Issue by developerark** [AlexeyAB/darknet#1912]
I am designing a realtime system that gets image streams from 4 input sources. Hence it needs to run 4 different models at once. I have access to 4 GPUs and would like to run one model per GPU simultaneously. 

How do I achieve this functionality of running a model per GPU? 

Is multiple GPU support only for training or is it for the running as well?

**Comment by AlexeyAB** [comment]
In 4 different terminals run these commands - one for each:

`./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights test.mp4 -i 0`

`./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights test.mp4 -i 1`

`./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights test.mp4 -i 2`

`./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights test.mp4 -i 3`

**Comment by developerark** [comment]
I am doing it through Windows DLL with C++ to build a single executable of my program. Here is the DLL interface I am using:
Detector(std::string cfg_filename, std::string weight_filename, int gpu_id = <x=0, 1, 2, 3>);
I was getting some cuda error. I checked thoroughly and it was a thread safety issue on my end. 
It is all good now. Thanks :)
