### ISSUE TITLE
Coordinates of Bounding Boxes and print area

### ISSUE THREAD

**Issue by PabloDIGITS** [AlexeyAB/darknet#1920]
Hi:
Im using YOLOv3 Tiny with a cam. I execute this command for running it:
`./darknet detector demo cfg/coc.data cfg/yolov3-tiny.cfg yolov3-tiny.weights "nvcamerasrc ! video/x-raw(memory:NVMM), width=(int)1280, height=(int)720,...... ! appsink"`
Where can I find the coordinates of the bounding boxes predicted and if I could measure the area of the bounding box, estimate the size of the object detected and print it in the console (in real time)?
Thanks for the help.

**Comment by NullPointer0000** [comment]
I believe it is in image.c in one of the draw_detections methods

**Comment by PabloDIGITS** [comment]
Ok, I found that methods. Thank you for the info.
