### ISSUE TITLE
Advice on incremental training data

### ISSUE THREAD

**Issue by kmsravindra** [AlexeyAB/darknet#1921]
@AlexeyAB, 

I have a trained model on 15000+ images for 10,000 iterations. Every week I get 3000 more new images as an increment to the existing train dataset. 

So whenever I get this incremental data, should I train the model with 18000 images (15000+3000) again from scratch ( I mean using darknet53.conv.74) 

OR 

Can I train the model just using 3000 images using the pre-trained yolo_obj_10000.weights file that I have initially and with recalculated anchors on 18000 images?

Your suggestion will be helpful.

**Comment by ManzarIMalik** [comment]
@kmsravindra Hi,

You can increase max_batches and steps in cfg file and continue from final weights. But the better approach would be not to changing anything in cfg file but add paths of new images in train and test.txt then continue training from around 6000 to 10000 weight files.
