### ISSUE TITLE
How is the weights filed saved in darknet?(the order of weights )

### ISSUE THREAD

**Issue by Sunyouteng** [AlexeyAB/darknet#1925]
@AlexeyAB 
Hi, 
This is the second time to ask you questions. thanks for spending time reading this.
Recently I am developing a tool to help prune yolo model based on your code. I want to prune the weights of yolov2-voc.weights. I load the weights file and prune it with a pruning algorithm(https://arxiv.org/pdf/1608.08710.pdf). I try to prune the first CONV1 layer with 10% filters. After finishing the development, I test it with test dataset, the mAP is 0 which is wrong obviously.
Here is my hypothesis. 
1     The weights is loaded into layer.weights. variable and the data in weights array is arranged filter by filter.For example we have 32 filters, each of them is 3*3*3. The total elemenet is  3*3*3*32  = 864. The first 27 elements is for filter0. the next 27 is for filter1, etc. 
2      In the first 27 elements, we have 3 channels, each is 3*3. The first 9 elementse is for channel 0. The next 9 is for channel 1, the last 9 is for channel 2.

When I prune some filters from on CONV layer, I have to prune corresponding channels in the next weights layer. For exaple I prune 21th filter in the first Conv layer, then i have to prune 21th channel of every filter in the next layer. I implemented the pruning algorithm based on the two basis. 
Here is my question:
Is the hypothesis wrong? If yes, can you tell me the how the filter weights ordered in the weight file?

I hope  you can understand my question and give me a hand.
If I finished this, I will try to contribut to github.
Thanks 
Youteng Sun.

**Comment by Sephirot1st** [comment]
Hello, I am looking for a feasible way to prune darknet to deploy it on mobile devices but have no idea. How is your work going? Could it apply to mobile ARM devices?

**Comment by Sunyouteng** [comment]
@Sephirot1st I finished it with pruning algorithm based on darknet. And I will open the source code and the related tool when I finished my paper. Maybe after the spring festival ,so you can follow me.

**Comment by Sephirot1st** [comment]
Oh, thanks, I will pay attention to it. But it may be a little bit late for me.

**Comment by AlexeyAB** [comment]
@Sunyouteng Hi, I just saw your question.

What advantage did you get (speedup, memory consumption, mAP)?

The simplest way to understand how inputs and weights are arranged for 1 batch - read this source code: https://github.com/AlexeyAB/yolo2_light/blob/117f196518597a902bc4c0552724f4fb99f09e3d/src/yolov2_forward_network.c#L59-L100
```
l.output[filters][width][height] +=
        state.input[channels][width][height] *
        l.weights[filters][channels][filter_width][filter_height];
```

**Comment by Sunyouteng** [comment]
@AlexeyAB Thanks for your reply. 
That is exactly the same as I imagine. I finished my pruning program with this assumption and verified the idea.
I only pruned yolov2 from Layer 18 to Layer 22. 
5 CONV layers totally. Half  of weights of each layer were kept.  The speed increased a quarter. mAP is a little smaller(after retrain), 75 compared with the original 78.
Plus, do you know some source code about how to port darknet code to FPGA implementation with HLS ?  I want to make yolo based on darknet run on FPGA + ARM. Also, that is why I prune the weights.

**Comment by AlexeyAB** [comment]
@Sunyouteng 

> do you know some source code about how to port darknet code to FPGA implementation with HLS ? I want to make yolo based on darknet run on FPGA + ARM. Also, that is why I prune the weights.

No.

You should implement by yourself or find ready solution in HLS:

* or for convolution: https://github.com/AlexeyAB/yolo2_light/blob/117f196518597a902bc4c0552724f4fb99f09e3d/src/yolov2_forward_network.c#L59-L100

* or for `im2col()` and `gemm()` (General Matrix Multiply) functions: 
    * https://github.com/AlexeyAB/yolo2_light/blob/117f196518597a902bc4c0552724f4fb99f09e3d/src/additionally.c#L39-L62
    * https://github.com/AlexeyAB/yolo2_light/blob/117f196518597a902bc4c0552724f4fb99f09e3d/src/additionally.c#L994-L1008

**Comment by Sunyouteng** [comment]
@AlexeyAB THX all the same

**Comment by hjm1990818** [comment]
> @Sephirot1st I finished it with pruning algorithm based on darknet. And I will open the source code and the related tool when I finished my paper. Maybe after the spring festival ,so you can follow me.

尊敬的师兄，你好，我想咨询一下，你发表的论文在哪里，我想追随师兄的脚步，学习如何剪枝YOLO网络，谢谢师兄了

**Comment by banyungong1** [comment]
> @Sephirot1st我用基于暗网的修剪算法完成了它。当我完成论文时，我将打开源代码和相关工具。也许在春节之后，所以你可以跟着我。

您好，想问一下您发表的论文在哪里？我想学习一下
