### ISSUE TITLE
yolo v3 xnor: training seems ok, test is abnormal

### ISSUE THREAD

**Issue by ccfire** [AlexeyAB/darknet#1929]
I train yolo v3 xnor net with this cfg:
[cc_xnor_2.txt](https://github.com/AlexeyAB/darknet/files/2574963/cc_xnor_2.txt)
the training seems ok:
![1](https://user-images.githubusercontent.com/18397098/48396656-293f0600-e756-11e8-9a39-457ee1df2a5d.png)
but testing is abnormal:
![2](https://user-images.githubusercontent.com/18397098/48396739-67d4c080-e756-11e8-92df-e41068a05843.png)
by this command: 
./darknet detector map data/cc.data cfg/cc_xnor_2.cfg backup/cc_xnor_2_252000.weights -thresh 0.05
with this repo:
https://github.com/AlexeyAB/darknet.git

thanks

**Comment by AlexeyAB** [comment]
* Check your dataset by using: https://github.com/AlexeyAB/Yolo_mark
* Can you get mAP > 0% for ~ `cc_xnor_2_10000.weights` ?
* Did you **train** your model by using this repo? https://github.com/AlexeyAB/darknet
* What params do you use in the Makefile?
* What versions of CUDA, cuDNN do you use?
* Can you show output of command `nvidia-smi` ?
* As I see you based your cfg-file on https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov3-tiny_xnor.cfg and trained it by using 3 GPUs, isn't it?

**Comment by ccfire** [comment]
Thanks for your reply!

Check your dataset by using: https://github.com/AlexeyAB/Yolo_mark
My dataset is OK, as I have trained and tested yolov3, yolov3-tiny sucessfully on my own dataset.

Can you get mAP > 0% for ~ cc_xnor_2_10000.weights ?
Yes, I check for all weights in backup folder, only several weights get mAP >0%:
![a](https://user-images.githubusercontent.com/18397098/48454260-8e940500-e7f1-11e8-814b-bfb711789ca5.png)
Most of weights get mAP like this:
![b](https://user-images.githubusercontent.com/18397098/48454271-9a7fc700-e7f1-11e8-9513-e360bedf3509.png)

Did you train your model by using this repo? https://github.com/AlexeyAB/darknet
Yes

What params do you use in the Makefile?
[Makefile.txt](https://github.com/AlexeyAB/darknet/files/2578867/Makefile.txt)

What versions of CUDA, cuDNN do you use?
CUDA9.0, cuDNN7.4

Can you show output of command nvidia-smi ?
![c](https://user-images.githubusercontent.com/18397098/48454469-4c1ef800-e7f2-11e8-8802-5cf911ffe774.png)

As I see you based your cfg-file on https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov3-tiny_xnor.cfg and trained it by using 3 GPUs, isn't it?
Yes, 3 GPUs

**Comment by ccfire** [comment]
@AlexeyAB , thank you very much.
The problem is solved. 
There was some wrong with cuda version( I used different versions of cuda and cudnn), when I use the same version, everything is OK.

**Comment by AlexeyAB** [comment]
`CUDNN_HALF=1` is only for GPU: Volta, Turing and higher.

Use `CUDNN_HALF=0` for GPU-Pascal architecture.

**Comment by kooscode** [comment]
is xnor binarization fully implemented on in this repo?  i.e. will XNOR run faster on a RPI3 vs. standard "tiny" yolo v2 ?
