### ISSUE TITLE
how do darknet find annotation file?

### ISSUE THREAD

**Issue by zrobotparking** [AlexeyAB/darknet#1931]
We only provide training image path when training yolo. But how to link them with their annotation file?

**Comment by AlexeyAB** [comment]
It just changes `jpg` or `bmp` extension to the `txt` extension. For example, 
for image:
`/darknet/data/obj/1.jpg`

it will try to load annotation file:
`/darknet/data/obj/1.txt`

**Comment by zrobotparking** [comment]
Thank you. I am trying to train on kitti dataset.
The path of *.jpg will be change into *.txt automatically  in `replace_image_to_label`, but it only support for COCO & VOC.
I need to add the following code in `utils.c` 
`find_replace(output_path, "/images-yolo/", "/labels-yolo/", output_path);    // kitti `

Is there other method to use other dataset in darknet ?

**Comment by AlexeyAB** [comment]
You can just copy all txt files from `/labels-yolo/` to the `/images-yolo/` directory.

What script did you use to get Kitti annotations in Yolo format?

**Comment by zrobotparking** [comment]
Convert by this:
https://github.com/CUFCTL/DLBD/blob/master/scripts/convert-kitti-to-yolo.py
