### ISSUE TITLE
Segmentation fault (core dumped) after enable cudnn

### ISSUE THREAD

**Issue by yyk722** [AlexeyAB/darknet#1936]
I am trying to use cudnn to speed up the training , I had tried the same training without cudnn and it worked , after set cudnn =1 and I couldn't start the training. 
I think here is the problem:
try to allocate workspace = 1 * sizeof(float),  CUDA allocate done!

Please help to fix this ,thanks!

**Comment by Nico1ee1995** [comment]
hi @yyk722 ,
have you slove it?
