### ISSUE TITLE
Couldn't open file: data/train_voc.txt

### ISSUE THREAD

**Issue by GingerCinnamon** [AlexeyAB/darknet#1959]
Hello!
I am new to the YOLO and I really need help. After all listed steps I have got an error after list of layers, but before training.
"Couldn't open file: data/train_voc.txt"

How can I fix it and what I am doing wrong?

I am using Windows 10, no_gpu version with opencv_3.3.0 and VS15.
Thank you in advance.

**Comment by PeterQuinn925** [comment]
It's looking for the data file that lists the number of classes and where to find the training data. Did you specify a data file? My guess is you didn't and it's looking for the default one.

**Comment by GingerCinnamon** [comment]
> It's looking for the data file that lists the number of classes and where to find the training data. Did you specify a data file? My guess is you didn't and it's looking for the default one.

I was trying to use default settings for first run, as was explained by AlexeyAB. Can you help me and explain how can I fix this?

**Comment by PeterQuinn925** [comment]
I assume you're following these instructions:
Run command: type 2007_train.txt 2007_val.txt 2012_*.txt > train.txt
Set batch=64 and subdivisions=8 in the file yolov3-voc.cfg: link
Start training by using train_voc.cmd or by using the command line:
darknet.exe detector train data/voc.data cfg/yolov3-voc.cfg darknet53.conv.74

The error msg indicates it can't find train_voc.txt but the instructions call for train.txt. I don't know what's in data/voc.data but from the error msg, it looks like it's calling for train_voc.txt. Either edit voc.data or rename train.txt and you should be good to go.
