### ISSUE TITLE
No detection in AB-darknet but works fine with pjreddie's repo

### ISSUE THREAD

**Issue by readicculus** [AlexeyAB/darknet#1980]
Been using this repo for a while to find mAP score but I train everything in pjreddie's darknet.  This worked well when I was training my last set of data, images were similar(only change is now my images are slightly different size and config refects that) everything was set up the same now. 

Now when I try to run test or map in this branch I get no detection results, map score of 0.0.  The interesting thing is that if I start training in this branch with the weights I generated in pjreddies branch it picks up from where it left off and works fine(loss continues to decrease/stay the same).  I'm 100% positive I coppied over config files and data file correctly and that my valid txt file is copied over.  I changed paths in my data file to reflect the new directory and still have not been able to get detection test of map to work on my  model.  

Anyone have any ideas?  Its probably something really stupid but I've checked and double checked and tripple checked everything and it should work.  My AB branch is made with GPU=1 and OPENCV=1 and everything else is left as defaults.

**Comment by yboss** [comment]
Looking into other issue posts it could be that my objects are being lost in the way AB darknet resizes differently to pjreddies.  My objects are about 20x20 pixels in a 640x512px image.  I know that normal darknet resizes well if w/h is divisible by 32 but I imagine that could be my issue here as when I had this working before my objects were ~100x100px in size.  Based on the detection results I get from pjreddies darknet I should be getting really good detection results so I do think it has something to do with how small my objects are.  Anyone have any ideas on how I can fix this to work with this branch?

**Comment by AlexeyAB** [comment]
1. If you train on pjreddie's repo and detect on pjreddie's repo, does it work?
2. If you train on pjreddie's repo and detect on AlexeyAB's repo, does it work?
3. If you train on AlexeyAB's repo and detect on AlexeyAB's repo, does it work?
4. Can you compress and attach your cfg-file to your message here?
5. What parameters do you use in the Makefile with the AlexeyAB's repo?
6. What CUDA, cuDNN and OpenCV versions do you use with the AlexeyAB's repo?
7. What GPU do you use?

**Comment by yboss** [comment]
If you train on pjreddie's repo and detect on pjreddie's repo, does it work?
Yes it works very well.

If you train on pjreddie's repo and detect on AlexeyAB's repo, does it work?
Not for this dataset (it was working when I had objects that were ~100x100px to get mAP score)

If you train on AlexeyAB's repo and detect on AlexeyAB's repo, does it work?
Works very well 86.5% mAP

Can you compress and attach your cfg-file to your message here?
[cfg.gz](https://github.com/AlexeyAB/darknet/files/2621461/cfg.gz)

What parameters do you use in the Makefile with the AlexeyAB's repo?
GPU=1
CUDNN=0
CUDNN_HALF=0
OPENCV=1
AVX=0
OPENMP=0
LIBSO=0

What CUDA, cuDNN and OpenCV versions do you use with the AlexeyAB's repo?
CUDA 9.1(V9.1.85)
OPENCV 2.4.9.1
Not sure about cuDNN it's turned off in the makefile though


What GPU do you use?
trained this model on a signle TITAN X (Pascal)

**Comment by AlexeyAB** [comment]
> If you train on pjreddie's repo and detect on AlexeyAB's repo, does it work?
> Not for this dataset 

* Can you show console output of `./darknt detector map`... in this case?

----

>  (it was working when I had objects that were ~100x100px to get mAP score)

* Did you use all anchors = 20 in that case?

* Why do you use all anchors `20` in the current cfg-file?

* Also why do you disable cuDNN?

* What anchors can you get by using command?
`darknet.exe detector calc_anchors data/obj.data -num_of_clusters 9 -width 640 -height 512`

**Comment by yboss** [comment]
Because those are the anchors I calculated based on my labels.  When I was working with the other images my config file had different anchors but everything else was the same.  This is the same config file, labels, images, and data file I used to train with pjreddie's darknet.

```
num_of_clusters = 9, width = 640, height = 512 
 read labels from 2563 images 
 loaded 	 image: 2563     box: 4175
 all loaded. 

 calculating k-means++ ...

 avg IoU = 100.00 % 

Saving anchors to the file: anchors.txt 
anchors = 20.0000,20.0000, 20.0000,20.0000, 20.0000,20.0000, 20.0000,20.0000, 20.0000,20.0000, 20.0000,20.0000, 20.0000,20.0000, 20.0000,20.0000, 20.0000,21.3333
```

Here is the mAP i get when running the weights I go on pjreddies repo with AB-darknet(note that visually detection works great when run in pjreddies repo with the weights that don't work in AB-darknet)
```
Trained in pjreddie, mAP in AB:
detections_count = 0, unique_truth_count = 656  
class_id = 0, name = Seal, 	 ap = 0.00 % 
 for thresh = 0.25, precision = -nan, recall = 0.00, F1-score = -nan 
 for thresh = 0.25, TP = 0, FP = 0, FN = 656, average IoU = 0.00 % 

 mean average precision (mAP) = 0.000000, or 0.00 % 
Total Detection Time: 40.000000 Seconds


Train in AB, mAP in AB
detections_count = 1034, unique_truth_count = 656  
class_id = 0, name = Seal, 4     ap = 86.56 % 
 for thresh = 0.25, precision = 0.90, recall = 0.92, F1-score = 0.91 
 for thresh = 0.25, TP = 606, FP = 64, FN = 50, average IoU = 69.05 % 

 mean average precision (mAP) = 0.865580, or 86.56 % 
Total Detection Time: 42.000000 Seconds
```

The reason that anchors are like that is that all I have is a centerpoint of my object and they are always pretty much the same size +- 5px or so and I generate the bboxes on my own that are all the same size around that center point.  All the images are all the same size which is why they all have the same width and height labels.

As far as why I'm not using cuDNN, I've never used it, not sure what it is, but I will look into it now!

**Comment by yboss** [comment]
![chess_fl12_p_160421_223052 503_therm-16bit](https://user-images.githubusercontent.com/3818801/49110571-b7c98200-f242-11e8-9546-0142be14bad6.jpg)

Here's an example of the objects with the drawn bbox I've generated

**Comment by AlexeyAB** [comment]
@yboss 

Try to compile **with cuDNN both repos**, and then try to **detect** by using this problem weights-file **on both repos**.

If it doesn't help, then can you share your weights-file and one of image, I will check it.
