### ISSUE TITLE
What makes darknet much faster than caffe?

### ISSUE THREAD

**Issue by huchhong** [AlexeyAB/darknet#1981]
Recently, i migrated yolov3 to caffe. After i was sure things were successful, i took a speed test between darknet and caffe. In this test, i excluded yolo layer due to some subtle implementation details. 

Then I was really suprised that darknet was much faster than caffe. I used 1080Ti. Caffe cost about 100ms to do a inference while darknet cost only 16ms. After some time, i found darknet would make a conv+bn fusion during inference, so i also implemented this in caffe which made the inference time fell to 50ms+. There was still a big gap between darknet and caffe.

I don't know whatelse would make this difference. @AlexeyAB , can you explain this?

**Comment by AlexeyAB** [comment]
* Do you use default `yolov3.cfg` model with 608x608?
* Did you compile both Caffe and Darknet with CUDA and cuDNN? What versions of CUDA and cuDNN did you use?
* Check that you measure time correctly. This is very big time difference. 

May be the reason is - non-optimal implementation of `[upsample]` layer in the Caffe, because there is no upsample-layer in the cuDNN. Is it implemented by using CUDA C++ or by using Python code in the Caffe?

**Comment by huchhong** [comment]
@AlexeyAB ,Thanks for your reply. 

1. both caffe and darknet used 416x416
2. Yes, i compile both caffe and darknet with cuda and cudnn. Since both test in the same machine, so i think cuda version (9.0) and cudnn (7.2.1) must be the same.
3. I measure the time eslapsed during network->forward. I am pretty sure both caffe and darknet have been synchornized with gpu calculation before measure.
4. the upsample layer implemention was copied from web  which was implemented in both cpu and cuda version and i am sure the cuda version was used.
5. I make a per conv layer profile which shows that each convolution layer forward costs more time in caffe than darknet.

So i think it may be some cuda settings problem which i have no idea.

**Comment by AlexeyAB** [comment]
@huchhong If both Darknet and Caffe are compiled with cuDNN, then they both should call the same cuDNN-function for convolutional layer, so speed should be the same. You can try to run Darknet and Caffe by suing `nvpp` (NVIDIA Visual Profiler that is installed with CUDA by default) to check it.

Only one thing from `[convolutional]` layer isn't implemented in the cuDNN - `leaky linear activation`, so it can be a bottleneck in the Caffe: https://github.com/AlexeyAB/darknet/blob/21a4ec9390b61c0baa7ef72e72e59fa143daba4c/src/activation_kernels.cu#L155-L162

**Comment by huchhong** [comment]
I have some work these days, so this response is a little late. I used nvprof to profile both caffe and darknet and finally found the reason.

[this](https://gist.github.com/huchhong/c1bf7370d8173a99d35dfd5ca1f1eec2) is nvprof's result on darknet yolov3 and [this one](https://gist.github.com/huchhong/88e15793fb8ecdb591ccf4900b1209c5) is nvprof's result on caffe's version. caffe's version has fused convolution and batchnorm. These two have the same network structure except yolo layer.

Compare two profile results, i found caffe did many cuda memcpy and cuda memset during network forward while darknet had this all done before network forward. So if i only inference one picture and test time spent in network forward, i would have wrong conclusion that caffe is much slower than darknet. 

If i minus cuda memcpy and cuda memset time out, then the time spend in gpu in caffe and darknet is very close. The total time (wall time) during network forward in caffe is still a few milliseconds bigger than in darknet, this should be some time spent in cpu because of different implementation.

**Comment by blayuan** [comment]
@huchhong  Hi，would you mind telling me how you converted YoloV3 to caffe？mAP dropped a lot after my conversion. I would appreciate it if you could give me some help and guidance.
