### ISSUE TITLE
Average Loss: nan

### ISSUE THREAD

**Issue by harshsharma22** [AlexeyAB/darknet#1982]
Training on the custom dataset, Average loss: nan after only 60 iterations. training for one class having 6244 images. 
help for this. 
using tiny-yolo.cfg to train a model.
Thank you.

**Comment by AlexeyAB** [comment]
Set CUDNN_HALF=0 in the Makefile. 
And check your dataset by using: https://github.com/AlexeyAB/Yolo_mark

**Comment by harshsharma22** [comment]
GPU=0
CUDNN=0
CUDNN_HALF=0
OPENCV=1
AVX=0
OPENMP=1
LIBSO=0

# set GPU=1 and CUDNN=1 to speedup on GPU
# set CUDNN_HALF=1 to further speedup 3 x times (Mixed-precision using Tensor Cores) on GPU Tesla V100, Titan V, DGX-2
# set AVX=1 and OPENMP=1 to speedup on CPU (if error occurs then set AVX=0)

DEBUG=0

ARCH= -gencode arch=compute_30,code=sm_30 \
      -gencode arch=compute_35,code=sm_35 \
      -gencode arch=compute_50,code=[sm_50,compute_50] \
      -gencode arch=compute_52,code=[sm_52,compute_52] \
          -gencode arch=compute_61,code=[sm_61,compute_61]

OS := $(shell uname)

"~/darknet/Makefile" [converted] 155L, 4544C    



Already I have taken it as it is. and we have created the dataset using YOLO-Annotation-Tool-master.

**Comment by AlexeyAB** [comment]
I didn't check traininig on CPU, because it will take about a year.
Try to buy any nVidia GPU GeForce GTX 970 or higher.

**Comment by harshsharma22** [comment]
is it any possibility that I am getting this error due to training on CPU?

**Comment by harshsharma22** [comment]
Thanks. I have solved this issue with Cuda 10.0 and Nvidia GeForce gt 710
