### ISSUE TITLE
Does image resize in darknet take care of antialiasing?

### ISSUE THREAD

**Issue by kmsravindra** [AlexeyAB/darknet#1983]
@AlexeyAB , As I understand, aliasing is going to have a negative impact on accuracy especially when the images are resized. In this context, does the image resize function present in this repo impacts image aliasing? Does it take care of anti-aliasing while downsizing the image to the network size? I see opencv INTER_LINEAR interpolation is used for image resize...not sure if it takes cares of anti-aliasing? Thanks!

**Comment by kmsravindra** [comment]
@AlexeyAB, Hi

Do you have any comments for the above question. I also happen to see this link - 
http://tanbakuchi.com/posts/comparison-of-openv-interpolation-algorithms/
under "Downsampling conversion" where different resized images are compared against the original images in opencv. Here it is mentioned that area interpolation is slightly better...but all other interpolations suffer aliasing...Given that we do linear interpolation of resizing in this repo, I wanted to understand if this has any impact if I am especially downsizing 1920x1080 HD image to something like 416x416 or 832x480 images which are quite small in comparison. It will be great to know your views / suggestions in this regard. Thanks for your help!

**Comment by AlexeyAB** [comment]
@kmsravindra Hi,

May be it can give slightly better accuracy if you will use `INTER_CUBIC` or Gaussian blur for Training and Detection.

Yes, you can try to use `INTER_CUBIC` instead of `INTER_LINEAR` or others:  https://docs.opencv.org/3.4.4/da/d54/group__imgproc__transform.html#ga5bb5a1fea74ea38e1a5445ca803ff121

----

You can change these lines or add Gaussian blur before these lines:

* for Training: https://github.com/AlexeyAB/darknet/blob/21a4ec9390b61c0baa7ef72e72e59fa143daba4c/src/http_stream.cpp#L294

* for Detection on video: https://github.com/AlexeyAB/darknet/blob/21a4ec9390b61c0baa7ef72e72e59fa143daba4c/src/image.c#L1119-L1120

* for Detection on images:
    * you should add Gaussian blur here: https://github.com/AlexeyAB/darknet/blob/21a4ec9390b61c0baa7ef72e72e59fa143daba4c/src/image.c#L1013
    * or you should implement area interpolation here: https://github.com/AlexeyAB/darknet/blob/21a4ec9390b61c0baa7ef72e72e59fa143daba4c/src/image.c#L1773

**Comment by kmsravindra** [comment]
Thanks @AlexeyAB . 

For this part - 

> * for Detection on images:

> * or you should implement area interpolation here: 
>     
>       
>         [darknet/src/image.c](https://github.com/AlexeyAB/darknet/blob/21a4ec9390b61c0baa7ef72e72e59fa143daba4c/src/image.c#L1773)
>       
>       
>            Line 1773
>         in
>         [21a4ec9](/AlexeyAB/darknet/commit/21a4ec9390b61c0baa7ef72e72e59fa143daba4c)
>       
>       
>       
>       
>   
>           
>             
>              image resize_image(image im, int w, int h)

Could you please tell me if I can do a cvResize on images as well instead doing a custom area interpolation implementation for the above?

**Comment by kmsravindra** [comment]
@AlexeyAB, Could you please let me know how can I modify " image resize_image(image im, int w, int h)" function to take care of Area interpolation rather than linear interpolation resizing? Can I use openCV resize function instead of this logic? Thanks for your help!

**Comment by AlexeyAB** [comment]
@kmsravindra 

Change `INTER_LINEAR` to the `INTER_AREA`

in these places:


* for Training: https://github.com/AlexeyAB/darknet/blob/21a4ec9390b61c0baa7ef72e72e59fa143daba4c/src/http_stream.cpp#L294

* for Detection on video: https://github.com/AlexeyAB/darknet/blob/21a4ec9390b61c0baa7ef72e72e59fa143daba4c/src/image.c#L1119-L1120

* for Detection on images - you should implement area interpolation here by using `cvResize()` with INTER_AREA: https://github.com/AlexeyAB/darknet/blob/21a4ec9390b61c0baa7ef72e72e59fa143daba4c/src/image.c#L1773

**Comment by kmsravindra** [comment]
Thanks @AlexeyAB .

Can you please tell me if I can replace the existing code of resize_image function here https://github.com/AlexeyAB/darknet/blob/21a4ec9390b61c0baa7ef72e72e59fa143daba4c/src/image.c#L1773-L1815

with the below code? 

image resize_image(image im, int w, int h) {

IplImage* new_img = cvCreateImage(cvSize(im.w, im.h), IPL_DEPTH_8U, c);
cvResize(src, new_img, CV_INTER_AREA);
image resized = ipl_to_image(new_img);
cvReleaseImage(&new_img);
return resized;

}

**Comment by AlexeyAB** [comment]
Something like this

```cpp
 image resize_image(image im, int w, int h) {
    image copy = copy_image(im);
    if(im.c == 3) rgbgr_image(copy);

    IplImage* new_img = cvCreateImage(cvSize(w, h), IPL_DEPTH_8U, im.c);
    int step = new_img->widthStep;
    int y, x, k;
    for(y = 0; y < im.h; ++y){
        for(x = 0; x < im.w; ++x){
            for(k= 0; k < im.c; ++k){
               new_img->imageData[y*step + x*im.c + k] = (unsigned char)(get_pixel(copy,x,y,k)*255);
            }
        }
    }

      cvResize(src, new_img, CV_INTER_AREA);
      image resized = ipl_to_image(new_img);
      cvReleaseImage(&new_img);
      free_image(copy);
      return resized;
 }
```

**Comment by kmsravindra** [comment]
Thanks a lot @AlexeyAB ... I will use this although I didn't understand what these extra lines are doing.... If you can help explain, that will be great...even otherwise thanks a lot for your help!

    int step = new_img->widthStep;
    int y, x, k;
    for(y = 0; y < im.h; ++y){
        for(x = 0; x < im.w; ++x){
            for(k= 0; k < im.c; ++k){
               new_img->imageData[y*step + x*im.c + k] = (unsigned char)(get_pixel(copy,x,y,k)*255);
            }
        }
    }

**Comment by AlexeyAB** [comment]
@kmsravindra 

> ..Are they needed to convert the new_img to the proper format to feed into openCV?

Yes.

OpenCV IplImage is CWH (channel, width, height) packaged.
Darknet image is WHC (width, height, channel) packaged.

**Comment by kmsravindra** [comment]
Any reason why this openCV resizing was not used for images as well? Is the way that you have done here https://github.com/AlexeyAB/darknet/blob/21a4ec9390b61c0baa7ef72e72e59fa143daba4c/src/image.c#L1773-L1815 is faster than openCV resizing?

**Comment by AlexeyAB** [comment]
@kmsravindra 

In the original repo https://github.com/pjreddie/darknet is used Darknet-`resize_image()` only in any cases.

In my repo https://github.com/AlexeyAB/darknet there are used both OpenCV-`cvResize()` and Darknet-`resize_image()` only for Training and Detection on Video:
* for speedup Training on very high-performance GPU like DGX-2 (8 x V100) with Tensor Cores
* for speedup Detection on Video - for realtime detection on high-resolution video FullHD / 4K

It isn't critical such slowdown of detection on images in my tasks.

----

* For Training there is used both OpenCV-`cvResize()` and Darknet-`resize_image()`

* For Detection on Video there is used both OpenCV-`cvResize()` and Darknet-`resize_image()`

* For Detection on Images there is used Darknet-`resize_image()`

So **all 3 tasks can be compiled without OpenCV.**

**Comment by kmsravindra** [comment]
> image resize_image(image im, int w, int h) { image copy = copy_image(im); if(im.c == 3) rgbgr_image(copy); IplImage* new_img = cvCreateImage(cvSize(w, h), IPL_DEPTH_8U, im.c); int step = new_img->widthStep; int y, x, k; for(y = 0; y < im.h; ++y){ for(x = 0; x < im.w; ++x){ for(k= 0; k < im.c; ++k){ new_img->imageData[y*step + x*im.c + k] = (unsigned char)(get_pixel(copy,x,y,k)*255); } } } cvResize(src, new_img, CV_INTER_AREA); image resized = ipl_to_image(new_img); cvReleaseImage(&new_img); free_image(copy); return resized; }

@AlexeyAB , I was trying to use this code...However, what should be my src image in cvResize(src, new_img, CV_INTER_AREA); Should I convert the image im to Iplimage src and then use it here? Could you please help?

**Comment by kmsravindra** [comment]
Hi @AlexeyAB , If you get some time, could you please help review my code above that I am unable to get it work though it compiles properly? I have commented it as well. Thanks for your time.

**Comment by AlexeyAB** [comment]
@kmsravindra I don't see any issue.

I just applied your code and check Pascal VOC 2007 mAP by using default model yolov2 model:
`darknet.exe detector map data/voc.data cfg/yolov2-voc.cfg yolo-voc.weights`

* With default `resize_image()` function I get  75.92 % mAP 
* With your `resize_image()` function I get 72.71% mAP: https://github.com/AlexeyAB/darknet/issues/1983#issuecomment-447777013


![image](https://user-images.githubusercontent.com/4096485/50228404-e9a0b500-03b8-11e9-9913-a500b3cc9730.png)

**Comment by kmsravindra** [comment]
Thanks @AlexeyAB ! It got resolved now...

But it got me to another question. 
1. What is the interpolation method you used inside the code for resize_image function when downsizing an image? Is it linear interpolation? or nearest neighbour? Because when I ran my code with either CV_INTER_AREA or  CV_INTER_LINEAR, I am getting a bad mAP score of around 58% mAP. But when I run with your code of resize_image, I get 81% mAP! Why is there so much difference? 

2. I am concerned because we are using the inference on Video stream and there we use openCV enabled darknet that does CV_INTER_LINEAR like you mentioned...

> for Detection on video:

> darknet/src/image.c

> Lines 1119 to 1120 in 21a4ec9

>  cvResize(src, *in_img, CV_INTER_LINEAR); 
>  cvResize(src, new_img, CV_INTER_LINEAR); 

So would it mean that I get lower accuracy when I run it on video detection rather than detection on images? Please clarify?

**Comment by AlexeyAB** [comment]
@kmsravindra 


Just remove this line `if(im.c == 3) rgbgr_image(copy);` from your code.

Use:
```cpp
 image resize_image(image im, int w, int h) {
// make a copy of the original image im
  image copy = copy_image(im);

 // Initialize a blank new src image with dimensions same as original image im
  IplImage* src = cvCreateImage(cvSize(im.w, im.h), IPL_DEPTH_8U, im.c);

  // copy the contents of im to src while converting "src" image to opencv image format
  int step = src->widthStep;
  int y, x, k;
  for(y = 0; y < im.h; ++y){
      for(x = 0; x < im.w; ++x){
          for(k= 0; k < im.c; ++k){
             src->imageData[y*step + x*im.c + k] = (unsigned char)(get_pixel(copy,x,y,k)*255);
            }
        }
    }

 // Initialize a blank new image with desired resize dimensions w and h
  IplImage* new_img = cvCreateImage(cvSize(w, h), IPL_DEPTH_8U, im.c);

 // resizing src image and storing the resized image to new_img using area interpolation
  cvResize(src, new_img, CV_INTER_AREA);

 //Converting new_img into darknet image format
  image resized = ipl_to_image(new_img);

  cvReleaseImage(&new_img);
  cvReleaseImage(&src);
  free_image(copy);
  return resized;
}
```


----


1. In any case is used INTER_LINEAR by default - as you can see there: https://github.com/AlexeyAB/darknet/issues/1983#issuecomment-443015051

2. By default you get the same accuracy, because anywhere is used INTER_LINEAR by default.

**Comment by kmsravindra** [comment]
@AlexeyAB , Thanks a ton! It now works perfectly...As you mentioned linear interpolation is giving superior results compared to area interpolation although I was hoping that area interpolation is supposed to work better as it was mentioned to take care of antialiasing during image downsizing. So looks like, maybe the model is finding better patterns to learn during linear interpolation rather than area interpolation. Thanks a lot for your help!
