### ISSUE TITLE
Can't resolve opencv2/highgui/highgui_c.h error 

### ISSUE THREAD

**Issue by bit-scientist** [AlexeyAB/darknet#1984]
I have newly cloned this repository and tried to compile through reading [this](https://github.com/AlexeyAB/darknet#how-to-compile-on-windows) manual. However, after setting up everything I can't seem to find a solution for  `opencv2/highgui/highgui_c.h` error. I am on Windows 10, CUDA 9.1,  cudnn 7, opencv 3.3.0. I remember facing this type of error on my other PC and solving it after some trials and errors, but with this PC, I couldn't do anything about it. I have tried CUDA 9.0, cudnn 7.1, cudnn 7.4, opencv 3.4.0, opencv 2.4.9, all interchangeably. (**_I spent my whole day on it_**). I checked and set each and every property of my working PC (that was successfully compiled) with the one I am working, but still no luck. The only difference is, this Windows 10 version is Korean under the hood. The error is  here ![](https://habrastorage.org/webt/ko/kb/i8/kokbi8ml95p8foz3_30ghraajtw.jpeg)
I have only one supposition, Korean windows system reads  `/` as `₩ `, so maybe the problem is here?

Any help is highly  appreciated.

P.S: I have tried 3 opencv versions (3.4.0, 3.3.0, 2.4.9), 2 CUDA versions (9.0, 9.1) and three cudnn versions (7.0, 7.1, 7.4) all interchangeably, after failing the main recommended settings.

**Comment by AlexeyAB** [comment]
* Check that you have file by this path: `C:\opencv_3.0\opencv\build\include\opencv2\highgui\highgui_c.h`

* Open `darknet.sln` in MSVS and check (right click on project) -> properties -> C/C++ -> General -> Additional Include Directories: `C:\opencv_3.0\opencv\build\include;`

* Check that you try to compile x64 & Release
![uhfk-eb0q-hwd9hsxhrikbokd6u](https://user-images.githubusercontent.com/4096485/49073016-923c7880-f242-11e8-86b0-5153cfceff9f.jpeg)

**Comment by bit-scientist** [comment]
@AlexeyAB I found a solution, I forgot to change `Debug` to `Release`  in **darknet property Pages** window **Configuration** part
-
![](https://habrastorage.org/webt/fz/rc/we/fzrcwef6znryloh-wxy2p5gocaq.jpeg)
-
How silly it was, phew
