### ISSUE TITLE
Question: How to improve darknet GPU performance on multiple threads

### ISSUE THREAD

**Issue by AyushP123** [AlexeyAB/darknet#1996]
Hi,
      My system configuration :
      1. Windows 10
      2. GPU: NVIDIA Geforce GTX 940 M along with Intel (R) HD Graphics 620 ( Total 4 GB ) 
      3. Using OpenCV: Yes

While using Detector::detect on a single video stream I get 20 fps. While using it on two streams it drops to 11 fps. Each stream runs on a different thread. The weights file is 42.1 MB.
GPU utilization isn't that much and it includes other process like rendering :
For 1 Thread GPU Utilization:
Intel (R) HD Graphics 620: 6 - 8 %
NVIDIA Geforce GTX 940 M: 36 - 40%

For 2 Threads GPU Utilization:
Intel (R) HD Graphics 620: 7 - 8 %
NVIDIA Geforce GTX 940 M: 43 - 45%

On Linux for a single stream I get 16-18 fps and for two streams I get 10 - 12. Is there a way that I can run both the streams at better fps??

**Comment by HagegeR** [comment]
this kind of question comes a lot, you're probably not looking at the actual usage of the GPU load. 
Try to use GPU-Z and see what is the performance bottleneck.
This fork is optimized and you shouldn't be able to get a lot more FPS if you don't change hardware or change the model that you use to one that require less computation.
reducing resolution can also help, if you are able to..,

**Comment by AyushP123** [comment]
Sure, thanks a lot for your response.
