### ISSUE TITLE
output videofile is empty

### ISSUE THREAD

**Issue by Deadmin1** [AlexeyAB/darknet#1998]
I have problems regarding the outputvideo. If im saving the video i always get an "empty"(5,7kb) videofile. 

this is the command i try to use: 
./darknet detector demo data/cone-obj.data data/cone-yolov3-tiny.cfg backup/cone-yolov3-tiny_4000.weights data/test.mp4  -out_filename res.avi -dont_show

this is a selftrained network. In the demowindow i see the video and the predictions. tried different variants in demo.c

 //output_video_writer = cvCreateVideoWriter(out_filename, CV_FOURCC('H', '2', '6', '4'), src_fps, size, 1);
        //output_video_writer = cvCreateVideoWriter(out_filename, CV_FOURCC('D', 'I', 'V', 'X'), src_fps, size, 1);
        //output_video_writer = cvCreateVideoWriter(out_filename, CV_FOURCC('M', 'J', 'P', 'G'), src_fps, size, 1);
        output_video_writer = cvCreateVideoWriter(out_filename, CV_FOURCC('M', 'P', '4', 'V'), src_fps, size, 1);
        //output_video_writer = cvCreateVideoWriter(out_filename, CV_FOURCC('M', 'P', '4', '2'), src_fps, size, 1);
        //output_video_writer = cvCreateVideoWriter(out_filename, CV_FOURCC('X', 'V', 'I', 'D'), src_fps, size, 1);
        //output_video_writer = cvCreateVideoWriter(out_filename, CV_FOURCC('W', 'M', 'V', '2'), src_fps, size, 1);
    }

Makefile is with opencv=1

using Ubuntu 18 with opencv 3.4

thx in advance

**Comment by AlexeyAB** [comment]
* Do you use Linux?
* Did you compile OpenCV with ffmpeg support? Did you use `-D WITH_FFMPEG=ON` for ccmake?

**Comment by Deadmin1** [comment]
> * Do you use Linux?
> * Did you compile OpenCV with ffmpeg support? Did you use `-D WITH_FFMPEG=ON` for ccmake?

Hi Alexey yes im Using Linux (Ubuntu 18)

no i did note compile OpenCV with ffmpeg. Trying to do so now. 
Thx for that hint. 

Keep up the good work

**Comment by Deadmin1** [comment]
Compiled and installed OpenCV with -D WITH_FFMPEG=ON

same behaviour. But when i changed makefile to Opencv=1 i see some warnings that could be the cause?! Im completly new to building and compiling and dont have that much c++ experience.

./src/demo.c:267:17: warning: implicit declaration of function ‘cvSaveImage’; did you mean ‘cvShowImage’? [-Wimplicit-function-declaration]
                 cvSaveImage(buff, show_img, 0);
                 ^~~~~~~~~~~
                 cvShowImage
There are some more warnings regarding demo.c. Is this normal? 

Thx in advance

**Comment by Deadmin1** [comment]
Gave it again a try. Now used Cuda10 and Opencv 3.4.0 with ffmpeg und suddenly it works.

**Comment by Khani1986** [comment]
Hi, 
I am new to this, how do I compile with  -D WITH_FFMPEG=ON?
