### ISSUE TITLE
The tracking id is changing for the same object

### ISSUE THREAD

**Issue by ymmshi** [AlexeyAB/darknet#2008]

**Comment by AlexeyAB** [comment]
Try to change here `10` to `100`: https://github.com/AlexeyAB/darknet/blob/21a4ec9390b61c0baa7ef72e72e59fa143daba4c/src/yolo_v2_class.hpp#L75

**Comment by ymmshi** [comment]
> Try to change here `10` to `100`:
> 
> [darknet/src/yolo_v2_class.hpp](https://github.com/AlexeyAB/darknet/blob/21a4ec9390b61c0baa7ef72e72e59fa143daba4c/src/yolo_v2_class.hpp#L75)
> Line 75 in [21a4ec9](/AlexeyAB/darknet/commit/21a4ec9390b61c0baa7ef72e72e59fa143daba4c)
>  int const frames_story = 10, int const max_dist = 150);

thanks for your reply, it seems no improvement after changing 'frame_story' from 10 to 100, the result video shows in  https://pan.baidu.com/s/1CeUWKWF8_vtYD9j7amhabg
, do you have any other suggestions?

**Comment by AlexeyAB** [comment]
Try to set frames_story=30 and max_dist = 30 here: https://github.com/AlexeyAB/darknet/blob/21a4ec9390b61c0baa7ef72e72e59fa143daba4c/src/yolo_v2_class.hpp#L75
