### ISSUE TITLE
usage of CUDNN_HALF did not result in any performance gain?

### ISSUE THREAD

**Issue by vamsiduranc** [AlexeyAB/darknet#2009]
We built darknet on NVIDIA P6000 GPU machine using CUDNN, CUDNN_HALF setting in MS Visual Studio 2015. darknet.exe was built successfully. 

We tested detection using this executable with our old weights file [which was trained using the earlier built darknet.exe on the same machine but without using the CUDNN_HALF - only using CUDNN option) and it took almost the same time to process either a video or an image for detection; as compared with the old darknet executable built only with CUDNN. In both cases we used the same weights file and same images/videos - only difference was the darknet executable itself. 

When we see the gpu utilization, when using the new executable of 16bit - it was taking more GPU memory than the old one; please see two screen shots attached of gpu utilization. 

Darknet.exe built with only CUDNN

![gpu-darknet-cudnn-only](https://user-images.githubusercontent.com/32363189/49389098-83c2f500-f74b-11e8-8be4-abf3a4ec2553.gif)

Darknet.exe built with CUDNN, CUDNN_HALF
![gpu-darknet-cudnn_half](https://user-images.githubusercontent.com/32363189/49389099-83c2f500-f74b-11e8-9a09-707965b5326f.gif)

**Comment by AlexeyAB** [comment]
> We built darknet on NVIDIA P6000 GPU machine using CUDNN


NVIDIA Quadro P6000 is a Pascal architecture that doesn't have Tensor Cores: https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units#Quadro_Pxxx_series

CUDNN_HALF=1 increase speed only on Volta, Xavier, Turing and higher architectures: https://github.com/AlexeyAB/darknet/blob/21a4ec9390b61c0baa7ef72e72e59fa143daba4c/Makefile#L10
You can use it on: Quadro GV100, Tesla V100, GeForce Titan V, Jetson Xavier, RTX 2060, RTX 2070, RTX 2080, RTX 2080ti, DGX-2, Quadro RTX ...
