### ISSUE TITLE
DLL Diffrent result then in Darknet.exe

### ISSUE THREAD

**Issue by VisionEp1** [AlexeyAB/darknet#2010]
Hi,
when i run the network via the dll i get many random boxes.
Via darknet.exe is fine

(same config and weight parameters).

It doesnt matter if i call the dll via the cv::mat method or via filename. same result.
any ideas?
(windows 10 64bit)

**Comment by AlexeyAB** [comment]
@VisionEp1 Hi,
Can you show screenshot?

**Comment by VisionEp1** [comment]
sure

**Comment by VisionEp1** [comment]
i can provide more, they all look the same tho.

correct result in the darknet.exe

wierd results in the dll

**Comment by AlexeyAB** [comment]
@VisionEp1 

Can you show all changes that you did?

What Probability-threshold do you use for DLL?

**Comment by VisionEp1** [comment]
ok just to make it sure. i just re downloaded and compilled the current version.

same result (detector.exe still works perfectly fine).
dll version does not

**Comment by VisionEp1** [comment]
maybe you could use one of your existing networks,
set a low min confidence (around 0.05 or even lower) and then test yourself?

**Comment by VisionEp1** [comment]
ok -- i think i found the issue.

Somehow my config file seemed to be corrupt (even a quick diff didnt seem to do much).
After re copy the same file (file size+ date match) it works.

So i guess it had to be something with maybe unprintable chars or what ever.
sorry to bother you. i tried everything for 2 days :/
