### ISSUE TITLE
Save result to a textfile

### ISSUE THREAD

**Issue by christian-ek** [AlexeyAB/darknet#202]
Hello, 
Thank you for all the work you put down into this awesome code!

I would like to save the result from running object detection on a videoclip in a textfile to use in another script.

Can anyone help me out with how?

**Comment by AlexeyAB** [comment]
Hi, 

* You can just add one line here: https://github.com/AlexeyAB/darknet/blob/548a0bc652b562723695cc107f0844f11d1a2207/src/image.c#L292

```
printf("left=%d, right=%d, top=%d, bottom=%d, obj_id=%d, obj=%s \n", left, right, top, bot, class, names[class]);
```

* Then build, and run darknet as:
`darknet.exe detector demo data/voc.data yolo-voc.cfg yolo-voc.weights test.mp4 -i 0 > result.txt`

File `result.txt` will have detected object, where each new frame started with text `FPS:`...

----

Or you can use yolo_console.exe:

* Just uncomment this line: https://github.com/AlexeyAB/darknet/blob/548a0bc652b562723695cc107f0844f11d1a2207/src/yolo_console_dll.cpp#L169

* Set your cfg & weights files here: https://github.com/AlexeyAB/darknet/blob/548a0bc652b562723695cc107f0844f11d1a2207/src/yolo_console_dll.cpp#L84

* Then build `yolo_cpp_dll.sln` and then build `yolo_console_dll.sln`: https://github.com/AlexeyAB/darknet#how-to-use-yolo-as-dll

* And run `yolo_console_dll.exe myvideo.mp4 > result.txt`

**Comment by christian-ek** [comment]
Thanks

**Comment by crystinaa** [comment]
@AlexeyAB 
can we save detection result to a text file in such a format that it is acceptable to sort input for tracking
