### ISSUE TITLE
.exe problems

### ISSUE THREAD

**Issue by dascar5** [AlexeyAB/darknet#2023]
So I built it, got all the libraries and files and paths set up properly, I try opening "darknet_no_gpu.exe", cmd flashes for a second, and that's it. No errors, nothing.
What am I doing wrong?

**Comment by dascar5** [comment]
So I built it, got all the libraries and files and paths set up properly, I try opening "darknet_no_gpu.exe", cmd flashes for a second, and that's it. No errors, nothing.
What am I doing wrong?

**Comment by AlexeyAB** [comment]
Did you compile https://github.com/AlexeyAB/darknet/blob/master/build/darknet/darknet_no_gpu.sln by using MSVS 2015 successfully on Windows? Can you show screenshot of this?

**Comment by dascar5** [comment]
Yes I did, but I used VS17, just retargeted the project with no errors. I
heard from somewhere that you're supposed to run it from cmd with specific
commands? I just doubleclick it.

**Comment by AlexeyAB** [comment]
@dascar5 

Create `darknet_no_gpu.cmd` file with this content:
`darknet_no_gpu.exe detector test data/coco.data yolov3.cfg yolov3.weights -thresh 0.25 dog.jpg -ext_output`

and run this `darknet_no_gpu.cmd` file

**Comment by dascar5** [comment]
Really appreciate the help man, thanks!

**Comment by dascar5** [comment]
One more question, why does it only work for the dog.jpg?
No problems with scanning everything in that picture, but as soon as I try "giraffe" or "eagle", it won't load it.

**Comment by AlexeyAB** [comment]
`darknet_no_gpu.exe detector test data/coco.data yolov3.cfg yolov3.weights -thresh 0.25 -ext_output data/giraffe.jpg`

**Comment by dascar5** [comment]
Thanks!
I'm guessing this works just the same on videos (put it in the folder and
add the filename.extension to cmd file)?
