### ISSUE TITLE
use yolo_console_dll.exe，but no image show

### ISSUE THREAD

**Issue by jiangdon** [AlexeyAB/darknet#2030]
hi ，Alex
I'm follow your steps to compile yolo as dll, but when I use yolo_console_dll.exe to test image ,there is no result show ,i already uncomment line //#define OPENCV，do you have any solutions about this?
thank you very much for your time.

**Comment by AlexeyAB** [comment]
@jiangdon Hi,

> there is no result show

What command do you use?
Do you expect result in Windows or in Console?
Did you connected by ssh or directly?
Try to un-comment this line: https://github.com/AlexeyAB/darknet/blob/742bb7c7ce51a9faad08dc01fbf2e6908ad5ba4b/src/yolo_console_dll.cpp#L409

**Comment by jiangdon** [comment]
Thank you so much for answer me.I want result in Windows.
I use yolo_console_dll.exe by cmd,i can get the prediction of coordinates,but no image result show,just like the following picture.
![20181208183355](https://user-images.githubusercontent.com/31313969/49685123-aa50a980-fb18-11e8-85cf-586615c05e65.png).

**Comment by AlexeyAB** [comment]
Find files opencv_world320.dll and opencv_ffmpeg320_64.dll (or opencv_world340.dll and opencv_ffmpeg340_64.dll) in C:\opencv_3.0\opencv\build\x64\vc14\bin and put it near with yolo_console_dll.exe


If it doesn't help, then may be something wrong with OpenCV installation.

**Comment by jiangdon** [comment]
I reinstall opencv and it worked.Thank you very much.
