### ISSUE TITLE
convolution kernel

### ISSUE THREAD

**Issue by Hello526** [AlexeyAB/darknet#2033]
Hi! AlexeyAB. 
I would like to ask a question. During the training process, I want to output the data of the convolution kernel in the convolutional layer (batch×channels×height×width, 4-dimensional tensor). What should I do?

**Comment by Hello526** [comment]
I think the convolution kernel data should be stored by l.weights, but I saw the cudnnConvolutionForward function in convolutional_kernels.cu with the following parameters:

https://github.com/AlexeyAB/darknet/blob/742bb7c7ce51a9faad08dc01fbf2e6908ad5ba4b/src/convolutional_kernels.cu#L329

I think I can find the convolution kernel data through l.weightDesc. What do you think should be done? I want to finally output the convolution kernel data as a 4D tensor: k × c × h × wk is the number of channels of the output imagec is the number of channels of the input imageh is the height of the convolution kernelw is the width of the convolution kernel

**Comment by AlexeyAB** [comment]
@Hello526 Hi,

> I want to output the data of the convolution kernel in the convolutional layer (batch×channels×height×width, 4-dimensional tensor)


What is the "data of the convolution kernel" ?

`output = convolution(input, weights)`

* weights = channels X filters X kernel_size X kernel_size
* input = batch X channels X input_width X input_height
* output = batch X filters X output_width X output_height

Which of there tensors do you want to get?

**Comment by Hello526** [comment]
Hi!
weights = channels X filters X kernel_size X kernel_size

**Comment by Hello526** [comment]
In the convolutional_kernels.cu file, I guess l.weightDesc is a pointer to weights, so how are the weights data arranged? For example, for the first convolution operation of the YOLOV3 network, 
weights = 32 × 3 × 3 × 3, that is, there are 96 convolution kernels (kernel1, kernel2, kernel3...ker96)

Assume kernel1=[f1,f2,f3,F4, f5, f6,F7, f8, f9]Kernel2=[f10,f11,f12,F13, f14, f15,F16,f17,f18]...and so onThen, can the data indexed by l.weightDesc be expressed as:[f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11...f864]

**Comment by Hello526** [comment]
In other words, I can get weights now, but it is stored in a one-dimensional array (1 × 864), then how should I convert it to 32 × 3 × 3 × 3 format? Because I don't know how this one-dimensional array is arranged?

**Comment by AlexeyAB** [comment]
@Hello526 

`l.weights_gpu` is a CUDA pointer to the Weights on the GPU - **don't use it**: https://github.com/AlexeyAB/darknet/blob/742bb7c7ce51a9faad08dc01fbf2e6908ad5ba4b/src/convolutional_kernels.cu#L398

`l.weights` is a pointer to the Weights on the **CPU** - **use it**.

`l.weights` is packaged in format `filters X channels X kernel_size X kernel_size`

I.e. for this layer: https://github.com/AlexeyAB/darknet/blob/742bb7c7ce51a9faad08dc01fbf2e6908ad5ba4b/cfg/yolov3.cfg#L35-L38
`l.weights` array have size `64 x 32 x 3 x 3`

Use this code to access to the elements of `l.weights` array:
```cpp
int filter_id, channel_id, f_y , f_x;
for (filter_id = 0; filter_id< l.n; ++filter_id)
{
  // channel index
  for (channel_id= 0; channel_id< l.c; ++channel_id)
  {
    // filter - y
    for (f_y = 0; f_y < l.size; ++f_y)
    {
      // filter - x
      for (f_x = 0; f_x < l.size; ++f_x)
      {
        float w = 
            l.weights[filter_id*l.c*l.size*l.size + channel_id*l.size*l.size + f_y*l.size + f_x];

        printf(" %f,  ", w);
      }
    }
  }
}
```

----

If you want to learn more about how does Yolo work, read this code in the `yolo2_light` project: https://github.com/AlexeyAB/yolo2_light/blob/117f196518597a902bc4c0552724f4fb99f09e3d/src/yolov2_forward_network.c

**Comment by Hello526** [comment]
Thank you!!!
Это высший класс!

**Comment by Hello526** [comment]
Большое тебе спасибо!
