### ISSUE TITLE
CUDA Error Prev: CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by SarchWu** [AlexeyAB/darknet#2039]
hello，AlexeyAB.I have an issue and have no idea to solve it.So ask for your help.
I have finished the traing of my own data, and newed a  construction to detect though yolo_cpp_dll.
When i'm running the detection vs2013 code in my pc(GTX 1060),i could get the detection result.But
 when i wanna running the same project on GPU(Telsla K80),it apppears error the title describle.But the other gpu on this machine is still training my yolov3 network.So,do you have any idea i clould solve this problem?

**Comment by AlexeyAB** [comment]
@SarchWu Hi,

> When i'm running the detection vs2013 code in my pc(GTX 1060),i could get the detection result.But
> when i wanna running the same project on GPU(Telsla K80),it apppears error the title describle.

* Did you recompile project when you tried to run it on Tesla K80?

* Do you have 2 GPUs on the same PC? gtx 1060 and Tesla K80

* What CUDA and cuDNN versions do you use?

* Can you show output of command `"C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi"`

**Comment by SarchWu** [comment]
1.i have recompiled my detection part ,and recompile yolo_cpp_dll too ,change the code_generation to fit tesla k80
2.no，there are two machine. pc has gtx1060.the other machine has tesla k80
3.cuda9.1 cudnn 7.0.5
4.

**Comment by SarchWu** [comment]
4.here is the output of command "C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi"

**Comment by SarchWu** [comment]
![nvidia-smi](https://user-images.githubusercontent.com/31023414/49799900-19c8d200-fd81-11e8-873a-cae9b8051b71.png)

**Comment by AlexeyAB** [comment]
@SarchWu 

May be your GPU Driver version 385.54 is not suitable to the CUDA version 9.1.
Try to reinstall CUDA on PC with tesla k80 (with installation GPU Driver from CUDA).

**Comment by SarchWu** [comment]
But if the driver version is not suitable,why i still could training yolov3 in this machine?

**Comment by AlexeyAB** [comment]
> But the **other gpu** on this machine is still training my yolov3 network.

**other GPU** - what kind of GPU?

> But if the driver version is not suitable,why i still could training yolov3 in this machine?

* Do you mean that on K80 you can run successfully `./darknet detector train`... but can't run successfully `./darknet detector test`...?

* Can you run these 2 commands successfully when Darknet is built without cuDNN?

* Or is issue only with yolo_cpp_dll and yolo_cpp_console?

May be your OpenCV .dll-s files (that are used from yolo_cpp_console) are compiled with other version of CUDA

**Comment by SarchWu** [comment]
hi,alexey.I have figure it out.Thanks for your help.
The other gpu is tesla K80.
I met the issue when i wanna detect by calling yolo_cpp_dll.
The traning could continue because i compiled darknet with cuda9.0 .The driver version still support .But I compiled the yolo_cpp_dll with cuda9.1. It is not suitable.
So I recompiled the yolo_cpp_dll with cuda9.0.My detect program could run.
