### ISSUE TITLE
Count the objects it sees in a net-cam stream

### ISSUE THREAD

**Issue by mandeepubc** [AlexeyAB/darknet#204]
Hi,
Is it possible for yolo to count the objects it detects? Like display something like: No. of cars = 2, or no . of persons = 5 when it processes a video stream. 
Thanks

**Comment by AlexeyAB** [comment]
Hi, try to build `yolo_cpp_dll.sln` and then build `yolo_console_dll.sln`:  https://github.com/AlexeyAB/darknet#how-to-use-yolo-as-dll

Then start `yolo_console_dll.exe` and enter you videofile name, for example `myvideo.mp4`

![bb3f87ce-1664-11e7-871e-5bca32728479](https://user-images.githubusercontent.com/4096485/30714291-ec64db9e-9f1a-11e7-8a18-de72d58d4405.jpg)

**Comment by mandeepubc** [comment]
Hi,
I did make the yolo_console_dll.exe file, but when I start it, it just shuts-off in a few seconds. Whats going wrong?
