### ISSUE TITLE
cudnn_half wrong detections

### ISSUE THREAD

**Issue by salbatron** [AlexeyAB/darknet#2040]
CUDNN_HALF = 1 detection on version [fb1ee79](https://github.com/AlexeyAB/darknet/commit/fb1ee79576f83d505211267252e070c3cb0f431e)
![image](https://user-images.githubusercontent.com/29922029/49805308-1f102780-fd55-11e8-83e0-6b47d99b31e6.png)

am I missing something?

**Comment by AlexeyAB** [comment]
@salbatron 

1. What command do you use?
2. What cfg-file do you use?
3. What CUDA and cuDNN version do you use?
4. What GPU do you use? Can you show output of `nvidia-smi` command?
5. Do you use Linux or Windows?

**Comment by salbatron** [comment]
hi @AlexeyAB 

1.  darknet.exe detector test data/coco.data yolov3.cfg yolov3.weights -i 0 -thresh 0.25 dog.jpg -ext_output
2. cfg is standard yolov3.cfg
3. CUDA10.0, cuDNN 7.3
4. RTX 2080
5. Windows

smi:
![image](https://user-images.githubusercontent.com/29922029/49809780-11ac6a80-fd60-11e8-9628-e594b1d3db0a.png)

**Comment by goodtogood** [comment]
@AlexeyAB 
same problem on windows , the code is latest .

**Comment by AlexeyAB** [comment]
@salbatron @goodtogood Thanks!

Can you successfully detect using this commit `Commits on Nov 26, 2018`? https://github.com/AlexeyAB/darknet/tree/21a4ec9390b61c0baa7ef72e72e59fa143daba4c
to download: https://github.com/AlexeyAB/darknet/archive/21a4ec9390b61c0baa7ef72e72e59fa143daba4c.zip

----

Also try to download the newset cuDNN v7.4.1 (Nov 8, 2018), for CUDA 10.0: https://developer.nvidia.com/rdp/form/cudnn-download-survey

**Comment by salbatron** [comment]
Yes, with older commits detection works just fine.

Newest version of cuDNN v7.4.1 didn't resolved the problem

**Comment by AlexeyAB** [comment]
@salbatron I added 2 fixes. Try to update your code from GitHub and recompile, does it help?

If it doesn't help then
* check that you use `width=416 height=416` in yolov3.cfg
* try to comment this line: https://github.com/AlexeyAB/darknet/blob/25f133d6efcdc1d2aa79263e4fe4880ca782c79e/src/convolutional_layer.c#L199
* and try to comment these 2 lines: 
    * https://github.com/AlexeyAB/darknet/blob/25f133d6efcdc1d2aa79263e4fe4880ca782c79e/src/convolutional_kernels.cu#L298
    * https://github.com/AlexeyAB/darknet/blob/25f133d6efcdc1d2aa79263e4fe4880ca782c79e/src/convolutional_kernels.cu#L479


If it doesn't help, try to un-comment this line and change it: https://github.com/AlexeyAB/darknet/blob/25f133d6efcdc1d2aa79263e4fe4880ca782c79e/src/convolutional_kernels.cu#L299

to this: `if(state.index == 5)`

**Comment by salbatron** [comment]
@AlexeyAB Detection is all right after your fix but I noticed that detection time increased too. Now detection time i same with CUDNN_HALF = 0 and CUDNN_HALF = 1

**Comment by AlexeyAB** [comment]
@salbatron try to un-comment these 2 lines:
* https://github.com/AlexeyAB/darknet/blob/25f133d6efcdc1d2aa79263e4fe4880ca782c79e/src/convolutional_kernels.cu#L299
* https://github.com/AlexeyAB/darknet/blob/25f133d6efcdc1d2aa79263e4fe4880ca782c79e/src/convolutional_kernels.cu#L480

**Comment by salbatron** [comment]
Now detection time decreased but have no detection with CUDNN_HALF = 0

**Comment by salbatron** [comment]
That worked, thank you 👍 
RTX 2080:
CUDNN_HALF = 0 detection time ~20.5 ms
CUDNN_HALF = 1 detection time ~19 ms

With wrong detection from start ~17.5 ms😄

**Comment by AlexeyAB** [comment]
@salbatron Thank you very much for your tests! )

There is small speedup 

1. may be because for the first detection there will be re-allocated some arrays - I will improve it. 
    Try to compile with `CUDNN_HALF=1` and run this command once `darknet.exe detector test data/coco.data yolov3.cfg yolov3.weights -i 0 -thresh 0.25 -ext_output` and enter `dog.jpg` several times 


2. or may be because for the new cuDNN >= 7.2 there is used Tensor Cores (FP16) even when `CUDNN_HALF=0`, it is used automatically inside cuDNN library. 
    Try to comment this line and compile with `CUDNN_HALF=0` https://github.com/AlexeyAB/darknet/blob/25f133d6efcdc1d2aa79263e4fe4880ca782c79e/src/convolutional_layer.c#L199

May be difference between `CUDNN_HALF=0`  and `CUDNN_HALF=1`  will be more.

**Comment by AlexeyAB** [comment]
@salbatron I added another one fix, for small speedup when `CUDNN_HALF=1`, update your code from GitHub.

**Comment by goodtogood** [comment]
@AlexeyAB 
It works now.
It performs slightly better (fps 20 VS  23.6) than  CUDNN_HALF=0 when when CUDNN_HALF=1 on windows.
Is it normal ?

**Comment by salbatron** [comment]
@AlexeyAB now the detection time is ~17.5ms with CUDNN_HALF = 1 and detections are good.
Thank you very much

@goodtogood I find yolov3_spp a slower then standard yolov3. Try with yolov3

**Comment by goodtogood** [comment]
@salbatron 
I also noticed that, 
but I just wanna see how much improvement we can get when enabled  CUDNN_HALF.

**Comment by salbatron** [comment]
@goodtogood 
I got ~27 ms with CUDNN_HALF = 1
and ~36 ms with CUDNN_HALF = 0, with yolov3-spp on RTX 2080

**Comment by AlexeyAB** [comment]
@goodtogood What GPU did you use?

> It performs slightly better (fps 20 VS 23.6) than CUDNN_HALF=0 when CUDNN_HALF=1 on windows.
> the model is yolov3_spp. Is it normal ?

**Comment by goodtogood** [comment]
@salbatron 
thanks for your info.

@AlexeyAB 
mine is a cheaper one  RTX 2070.
