### ISSUE TITLE
call dll issue

### ISSUE THREAD

**Issue by mama110** [AlexeyAB/darknet#2044]
If I compile Yolo as C++ DLL-file with CUDA10 and MSVS2015 on computer A, then i put the dll file into another project on computer B, that project was bulit by MSVS2015 and  computer B is with CUDA 9 installed, can i still call the dll file to detect images  on computer B successfully? Thanks.

**Comment by goodtogood** [comment]
you should copy all dlls (cuda10) linked by yolo to computer B, then It could work normally on B .

**Comment by AlexeyAB** [comment]
@mama110 

Copy CUDA files with .exe file: 
cudart64_10.dll
curand64_10.dll
cublas64_10.dll
cufft64_10.dll

And cuDNN files:
cudnn64_7.dll

**Comment by mama110** [comment]
Thank you. @AlexeyAB @goodtogood
