### ISSUE TITLE
Trouble with training custom object

### ISSUE THREAD

**Issue by nguyendu392** [AlexeyAB/darknet#2052]
Hello everyone,
I'm using ubuntu 18.4. and following the instruction "How to train (to detect your custom objects)" for YOLOv3. I created yolo-obj.cfg in the directory "build/darknet/x64 and obj.names, obj.data  in the directory "build\darknet\x64\data\". 
However, I run the comandline `./darknet detector train data/obj.data yolo-obj.cfg darknet53.conv.74 -map -dont_show`, I get the error:
 
![image](https://user-images.githubusercontent.com/28902802/49980703-89c28e00-ff22-11e8-879d-99ba5ef9d91a.png)

>Here is my content of obj.data:
![image](https://user-images.githubusercontent.com/28902802/49980775-dd34dc00-ff22-11e8-840c-bb574dd0cb1d.png)
**May anyone help you with this problem, please? Should I move the obj.data file from "build\darknet\x64\data\" to "darknet/data"?**

**Comment by AlexeyAB** [comment]
@nguyendu392 Hi,

> Should I move the obj.data file from "build\darknet\x64\data" to "darknet/data"?

Yes, you should.

**Comment by hasibzunair** [comment]
@AlexeyAB is there any difference while setting the config files in **darknet/data** than on **darknet/build/darknet/x64/data**?

**Comment by AlexeyAB** [comment]
@hasibzunair No.
Use `darknet/data` on Linux, and `darknet/build/darknet/x64/data` on Windows.

**Comment by hasibzunair** [comment]
Thank you so much for the fast response! Can I run this on CPU?
