### ISSUE TITLE
Why channel pruning doesn't improve speed

### ISSUE THREAD

**Issue by Sephirot1st** [AlexeyAB/darknet#2053]
Hello @AlexeyAB ,
I prune the yolov3-tiny model trained on VOC2007+2012 using channel pruning method from [Link](https://arxiv.org/abs/1608.08710). I set the pruning rate to 20% and successfully squeeze the weights file from 34.9MB to 22.4MB with 3% mAP drop. But it doesn't show any improve in FPS when I test it on local video file. The pruned cfg is attached here:

[pruned_cfg.txt](https://github.com/AlexeyAB/darknet/files/2678901/pruned_cfg.txt)

Total BFLOPS has reduced from 5.477 to 3.549, is there any chance to improve the performance?

**Comment by AlexeyAB** [comment]
@Sephirot1st Hi,

* What GPU do you use?
* How many FPS do you get?
* What parameters do you use in the Makefile?

**Comment by Sephirot1st** [comment]
Oh, today I test it on Jetson TX2, it does improve the FPS from 33 to about 45 using the same cfg and Makefile as above. That's what I didn't expect. Why it doesn't show any improve on Titan X?
