### ISSUE TITLE
How to change and train the backbone network of YOLOv3 like resnet instead of darknet53? 

### ISSUE THREAD

**Issue by MingPap** [AlexeyAB/darknet#2054]
I know darknet53 is pretty good. But I want to try and train other backbone networks like vgg16 and resnet for YOLOv3. Does anyone try it for detection, rather than classification ?

Hope for answers!!

**Comment by MingPap** [comment]
I want to know if I can train VGG and Resnet by using darknet.exe and using it as backbone network for YOLOv3 detection

**Comment by Sephirot1st** [comment]
Here is a repository implementing YOLOv3 with Mobilenet, which you may be interested in.

 [Link](https://github.com/Adamdad/keras-YOLOv3-mobilenet)

Marked.

**Comment by MingPap** [comment]
> Here is a repository implementing YOLOv3 with Mobilenet, which you may be interested in.
> 
> [Link](https://github.com/Adamdad/keras-YOLOv3-mobilenet)
> 
> Marked.

Thanks. So the answer is no? Sad story.

**Comment by Pattorio** [comment]
The answer is yes. Check this:
https://github.com/AlexeyAB/darknet/issues/315

**Comment by MingPap** [comment]
> The answer is yes. Check this:
> #315

That's cool! Thank you.
