### ISSUE TITLE
Is there a way to extract features from the Darknet classification network for YOLOv3?

### ISSUE THREAD

**Issue by limwenyao** [AlexeyAB/darknet#2055]
Instead of getting class predictions for my detection, is there a way to extract the features in the darknet model? I am using YOLOv3.

**Comment by limwenyao** [comment]
Finally managed to do feature extraction. I have done it very crudely because i'm not a C programmer, please feel free to improve on my code. I am using Windows 7, CUDA enabled. My modification works with execution of `darknet.exe detector test`. You will need to make two changes in the source code.

Determine which feature layers you want to extract first. In my case, I needed layer 36 (short-cut layer, 52x52x256)

**Part 1**
https://github.com/AlexeyAB/darknet/blob/95773cfb423266b9ac6aeea54e862db5817b5447/src/network_kernels.cu#L430-L435

For every additional layer you want to extract, call the `get_network_output_layer_gpu` with the corresponding layer number. This ensures that the feature vector is pulled out of your GPU and into CPU. Modify it as such: 
```c
float *get_network_output_gpu(network net)
{
    int i;
	for (i = net.n - 1; i > 0; --i) if (net.layers[i].type != COST) break;
	//Add as many times as you need.
	get_network_output_layer_gpu(net, 36);

    return get_network_output_layer_gpu(net, i);
}
```

**Part 2**

https://github.com/AlexeyAB/darknet/blob/95773cfb423266b9ac6aeea54e862db5817b5447/src/detector.c#L1246

In the test function, add the following lines of code **AFTER** the `network_predict(net, X);` function call. This allows you to save the feature vector as a binary file. You can modify the code below to save to a text file.
```c
//Add these lines only after network_predict(net, X) function call
layer l36f = net.layers[36];
FILE * writefile = fopen(("mysavefile.bin"), "wb");
for (int k = 0; k < l36f.outputs*l36f.batch; ++k) {
	fwrite(&l36f.output[k], 1, sizeof(l36f.output[k]), writefile);
}
fclose(writefile);
```
Here is a sample feature vector extracted.
![figure_1](https://user-images.githubusercontent.com/23585543/50509408-b1882900-0ac0-11e9-890a-154381897534.png)

**Comment by gilangarisptr** [comment]
how can you visualize the feature vector? (sorry, I'm new in python )

**Comment by gilangarisptr** [comment]
> Finally managed to do feature extraction. I have done it very crudely because i'm not a C programmer, please feel free to improve on my code. I am using Windows 7, CUDA enabled. My modification works with execution of `darknet.exe detector test`. You will need to make two changes in the source code.
> 
> Determine which feature layers you want to extract first. In my case, I needed layer 36 (short-cut layer, 52x52x256)
> 
> **Part 1**
> https://github.com/AlexeyAB/darknet/blob/95773cfb423266b9ac6aeea54e862db5817b5447/src/network_kernels.cu#L430-L435
> 
> For every additional layer you want to extract, call the `get_network_output_layer_gpu` with the corresponding layer number. This ensures that the feature vector is pulled out of your GPU and into CPU. Modify it as such:
> 
> ```c
> float *get_network_output_gpu(network net)
> {
>     int i;
>     for (i = net.n - 1; i > 0; --i) if (net.layers[i].type != COST) break;
>     //Add as many times as you need.
>     get_network_output_layer_gpu(net, 36);
> 
>     return get_network_output_layer_gpu(net, i);
> }
> ```
> 
> **Part 2**
> 
> https://github.com/AlexeyAB/darknet/blob/95773cfb423266b9ac6aeea54e862db5817b5447/src/detector.c#L1246
> 
> In the test function, add the following lines of code **AFTER** the `network_predict(net, X);` function call. This allows you to save the feature vector as a binary file. You can modify the code below to save to a text file.
> 
> ```c
> //Add these lines only after network_predict(net, X) function call
> layer l36f = net.layers[36];
> FILE * writefile = fopen(("mysavefile.bin"), "wb");
> for (int k = 0; k < l36f.outputs*l36f.batch; ++k) {
> 	fwrite(&l36f.output[k], 1, sizeof(l36f.output[k]), writefile);
> }
> fclose(writefile);
> ```
> 
> Here is a sample feature vector extracted.
> ![figure_1](https://user-images.githubusercontent.com/23585543/50509408-b1882900-0ac0-11e9-890a-154381897534.png)

how can you visualize the feature vector? (sorry, I'm new in python )
