### ISSUE TITLE
Error: invalid image size error

### ISSUE THREAD

**Issue by mandeepubc** [AlexeyAB/darknet#206]
Hi,
I am getting this error when I am running my program on a network cam. Its a 4k cam.

[rtsp @ 0x14660d0] method PAUSE failed: 455 Method Not Valid In This State
[IMGUTILS @ 0x7fe72d2dc0] Picture size 0x0 is invalid
[IMGUTILS @ 0x7fe72d2de0] Picture size 0x0 is invalid

I dont know how to solve this.
Please help.
Thanks

**Comment by RickyWong33** [comment]
there are too few information for your error.
How about your command? Have u ever succeed in using yolo?
Have u ever try "./darknet detector test" command?

**Comment by mandeepubc** [comment]
Hi,
I just updated openCV 3.0 to openCV3.1 and built darknet again and it fixed the problem.
