### ISSUE TITLE
Get different map between training on yolo_v3 based on VOC and running calc_mAP.cmd

### ISSUE THREAD

**Issue by William1Wu** [AlexeyAB/darknet#2063]
hello all ,

I am working on training yolo v3 model based on VOC dataset and use below command to execute:

**darknet.exe detector train data/voc.data cfg/yolov3-voc.cfg darknet53.conv.74 -map**

Finally, I got a chart.jpg under x64 folder but I am very confused about the 2 questions:

![chart](https://user-images.githubusercontent.com/16698410/50065234-44909d00-016a-11e9-8609-e2a6c29db10f.jpg)

1. Why the fluctuation range of mAP is so extremely ?
2. I modified calc_map.cmd script as below cmd to double confirm mAP of final weights. 

**darknet.exe detector map data/voc.data   cfg/yolov3-voc.cfg   pretrained_weights/yolov3-voc_final.weights -thresh 0.5 -iou_thresh 0.5**

Result:
 **for thresh = 0.50, precision = 0.78, recall = 0.73, F1-score = 0.76
 for thresh = 0.50, TP = 8794, FP = 2468, FN = 3238, average IoU = 62.19 %
 mean average precision (mAP) = 0.769143, or 76.91 %
 Total Detection Time: 111.000000 Seconds**

Surprisingly, the result mAP(76.91%) is so different from the last mAP (9%) during training at chart.jpg ...
I also double confirm other saved weights and compare with mAP at chart.jpg, but got the same event.  

PS: The validation phase of training and testing are executing on VOC 2007_test dataset (4952 images)

Does anyone have met this same problem? Thank you!

**Comment by AlexeyAB** [comment]
@William1Wu Hi,

Can you show output of these commands?

* `lsb_release -a`
* `gcc --version`
* `nvcc --version`
* `nvidia-smi`

**Comment by feitiandemiaomi** [comment]
@William1Wu I have same problem 
![chart](https://user-images.githubusercontent.com/18325462/50129514-3058b700-02b4-11e9-8d19-c89f003e9451.jpg)
@AlexeyAB **lsb_release -a** : 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

**gcc --version**:
 gcc (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010

nvcc **--version**: nvcc: 
NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

**nvidia-smi**:
Tue Dec 18 11:03:52 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.87                 Driver Version: 390.87                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:05:00.0 Off |                  N/A |
| 24%   43C    P8    18W / 250W |      0MiB / 11176MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:06:00.0 Off |                  N/A |
| 25%   44C    P8    12W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:09:00.0 Off |                  N/A |
| 24%   43C    P8    17W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  Off  | 00000000:0A:00.0 Off |                  N/A |
| 21%   34C    P8    17W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by William1Wu** [comment]
@AlexeyAB Hi,

**lsb_release -a :**
My system is windows 10, so i can not carry out the command.

**gcc --version**
gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**nvcc --version:**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:32_Central_Daylight_Time_2017
Cuda compilation tools, release 9.0, V9.0.176

**nvidia-smi:**
Tue Dec 18 14:38:18 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 416.34       Driver Version: 416.34       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080   WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   42C    P3    31W /  N/A |    617MiB /  8192MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       652    C+G   ...6)\Google\Chrome\Application\chrome.exe N/A      |
|    0      1800    C+G   Insufficient Permissions                   N/A      |
|    0      3908    C+G   ...mmersiveControlPanel\SystemSettings.exe N/A      |
|    0      5984    C+G   ...36.52.0_x64__kzf8qxf38zg5c\SkypeApp.exe N/A      |
|    0      7788    C+G   C:\Windows\System32\WWAHost.exe            N/A      |
|    0      8032    C+G   ...oftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe N/A      |
|    0      8244    C+G   C:\Windows\explorer.exe                    N/A      |
|    0      8672    C+G   ...t_cw5n1h2txyewy\ShellExperienceHost.exe N/A      |
|    0      9468    C+G   ...dows.Cortana_cw5n1h2txyewy\SearchUI.exe N/A      |
|    0     10484    C+G   ...241.0_x64__8wekyb3d8bbwe\Calculator.exe N/A      |
|    0     11056    C+G   ...x64__8wekyb3d8bbwe\Microsoft.Photos.exe N/A      |
|    0     13016    C+G   ...12011.0_x64__8wekyb3d8bbwe\Video.UI.exe N/A      |
|    0     15952    C+G   ...2.0_x64__8wekyb3d8bbwe\WinStore.App.exe N/A      |
+-----------------------------------------------------------------------------+

**Comment by AlexeyAB** [comment]
@William1Wu Hi,

* What MSVS version do you use?
* What CUDA and cuDNN versions do you use?

**Comment by AlexeyAB** [comment]
@William1Wu @feitiandemiaomi 
Also do you get this issue when you train with `random=0` in the last `[yolo]`-layers?

**Comment by feitiandemiaomi** [comment]
@AlexeyAB No, I set random=1 
![1545181968 1](https://user-images.githubusercontent.com/18325462/50192720-63f81780-036e-11e9-85de-897c3d6a9d56.jpg)

**Comment by William1Wu** [comment]
@AlexeyAB  Hi,

**Do you use yolov3-voc.cfg model and train on default Pascal VOC dataset?**
yes, I use yolov3-voc.cfg, but I change the batch, subdivisions, and anchors value in the yolo-v3-voc.cfg
yes, I trained on default VOC dataset

**Can you show content of your data/voc.data file?**
classes= 20
train  = data/voc/train.txt
valid  = data/voc/2007_test.txt
#difficult = data/difficult_2007_test.txt
names = data/voc.names
backup = backup/

**What MSVS version do you use?**
VS2015

**What CUDA and cuDNN versions do you use?**
CUDA V9.0.176
cuDNN V7.4.1.5

**Comment by AlexeyAB** [comment]
@William1Wu @feitiandemiaomi 

So there is this issue only if you train with `random=1` in the last `[yolo]` layer, isn't it?

If yes, then try to update your code from GitHub. I added a fix.

----

I can't reproducre this issue by using `yolov3.cfg` and `yolov3-tiny.cfg` with `random=0` or `random=1`, with `CUDNN_HALF=0` and `CUDNN_HALF=1`:
* Windows 7 x64 sp1
* MSVS 2015 version 14.0.25 update 3
* OpenCV 3.3.0
* CUDA 10.0 (cuda_10.0.130_411.31_windows.exe)
* cuDNN 7.3.1 for CUDA 10.0
* GPU Driver 417.35
* GPU GeForce RTX 2070

Using this cfg-file I get this chart for 6 objects: 
[yolov3_obj.cfg.txt](https://github.com/AlexeyAB/darknet/files/2694777/yolov3_obj.cfg.txt)

![chart](https://user-images.githubusercontent.com/4096485/50225586-084f7d80-03b2-11e9-81fc-77f84c46e204.jpg)

**Comment by feitiandemiaomi** [comment]
@AlexeyAB OK ，I have a try

**Comment by William1Wu** [comment]
@AlexeyAB  Hi,

**When i set random=0,**
![chart](https://user-images.githubusercontent.com/16698410/50259331-9ec98080-043e-11e9-990e-461a079874b7.jpg)

**Using this cfg-file I get this chart for 6 objects:**
Can I know which dataset did you use? Maybe I can try it. 

**CUDNN_HALF**
Actually, I can not find CUDNN_HALF parameter everywhere. Can you tell me the full path of CUDNN_HALF?

Then , can you explain what difference when CUDNN_HALF=0 or 1.

Sorry to bother you much time, thank you very much.

**Comment by William1Wu** [comment]
@AlexeyAB  HI,

I have a try with CUDNN_HALF = 1 now.
Is there any uncertain if my gpu is GTX-1080 and cudnn_half=1?
Thanks!
![chart](https://user-images.githubusercontent.com/16698410/50265994-ccbdbd80-045c-11e9-8358-bc4629fe12a6.jpg)

**Comment by feitiandemiaomi** [comment]
@AlexeyAB ,OK, I will show my result later, and the new code successfilly solve the bug.

**Comment by William1Wu** [comment]
> @AlexeyAB ,OK, I will show my result later, and the new code successfilly solve the bug.

@feitiandemiaomi  Hello
Do you set random=0 in last one yolo layer at the end of cfg file? or each one yolo layer in the 3 different scales?

**Comment by AlexeyAB** [comment]
@feitiandemiaomi 

> but why multi-scale training can prodece such strange problem?, could you explain that

There was an issue, when we use random=1 then network will be resized randomly, and earlier I didn't change network size to the defualt size, so each time it measured mAP at different resolution, so there was large fluctuation. 
But this does not explain the problem with the zero value of the mAP.

----

> and your new code also slove the bug with random =1,

* Did you use `CUDNN=1` in this test?
* Does it work correctly with `GPU=1 CUDNN=1` and `random=1` currently?

**Comment by William1Wu** [comment]
@AlexeyAB HI,

The bug could be solved by setting CUDNN=0.
Do you have any comment or advice? thanks. 

![chart](https://user-images.githubusercontent.com/16698410/50388800-6803ab00-075b-11e9-9fa3-0c277c364b61.jpg)

**Comment by AlexeyAB** [comment]
@William1Wu @feitiandemiaomi 
I added fix. I hope now it is fixed, even for `CUDNN=1` :)

Update your code from GitHub.

**Comment by William1Wu** [comment]
@AlexeyAB Hello,

If set random=1 in cfg, I will get memory error in beginning. 
PS:  No memory error happens by same setting in old code.
So I would set random=0 and CUDNN = 1 to try in new code.
Thanks.

**used slow CUDNN algo without Workspace! Need memory: 13109248, available: 10905190
CUDNN-slow CUDA Error: out of memory
CUDA Error: out of memory: No error**

**Comment by AlexeyAB** [comment]
@William1Wu Try to increase `subdivisions`

**Comment by AlexeyAB** [comment]
@William1Wu I just optimized memory consumtion for Training with `-map` flag in the last commit.
Try to update your code.
