### ISSUE TITLE
starting training using a pre-trained model vs. starting training without a pre-trained model

### ISSUE THREAD

**Issue by k00r** [AlexeyAB/darknet#2070]
Hello @AlexeyAB 
What are the differences,pros and cons between those two? :)

**Comment by Sephirot1st** [comment]
When you use a pre-trained weights file to start training, it helps your model to converge much faster.

**Comment by k00r** [comment]
Does it initialize weights randomly if you start training without a pre-trained file?

**Comment by AlexeyAB** [comment]
@k00r Hi,

> Does it initialize weights **randomly** if you start training without a pre-trained file?

Yes: https://github.com/AlexeyAB/darknet/blob/49189c22e8c09ba7c11622ec22a72b3678887ed2/src/convolutional_layer.c#L339-L340

**Comment by k00r** [comment]
Thank you very much for your answers
