### ISSUE TITLE
cmd neural network information

### ISSUE THREAD

**Issue by mama110** [AlexeyAB/darknet#2076]
When i run cmd, the output as follows:
  57 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512 1.595 BF
  58 Shortcut Layer: 55
  59 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256 0.177 BF
  60 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512 1.595 BF
  61 Shortcut Layer: 58
  62 conv   1024  3 x 3 / 2    26 x  26 x 512   ->    13 x  13 x1024 1.595 BF
  63 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512 0.177 BF

What should i do to disable the display of these neural network information? Thanks.

**Comment by AlexeyAB** [comment]
Edit cmd-file, and add ` 2> nul` at the end of command.

For example:
`darknet.exe detector test data/voc.data cfg/yolov2-voc.cfg yolo-voc.weights -i 0 -thresh 0.24 dog.jpg 2> nul`

![image](https://user-images.githubusercontent.com/4096485/50219392-172d3480-03a0-11e9-86e7-b87846609f2b.png)

**Comment by mama110** [comment]
@AlexeyAB, thanks for your reply, what if i'm calling the yolo_cpp_dll file, should i change the c code?

**Comment by mama110** [comment]
I've changed the code in parse.c, thanks. @AlexeyAB
