### ISSUE TITLE
Bug fix needed for calculating map on grayscale dataset

### ISSUE THREAD

**Issue by MingPap** [AlexeyAB/darknet#2082]
@AlexeyAB  
Dear AlexeyAB,

I'm very happy to see this respository can train 1 channel grayscale image.

I trained and test successfully on single image, then I get good detection result on visual.

But I find that when I use ***map*** command to calculate the mAP, the result tends to be 0 or nan as following show:

![image](https://user-images.githubusercontent.com/26671598/50263225-af362700-044f-11e9-8504-f636a27db8c3.png)

![image](https://user-images.githubusercontent.com/26671598/50263179-81e97900-044f-11e9-885c-79c3e07ab2c4.png)

This is the data cfg of mine
![image](https://user-images.githubusercontent.com/26671598/50263257-d987e480-044f-11e9-88e3-319fdc1dfc8e.png)

Could you figure it out?

Best hopefully!

**Comment by AlexeyAB** [comment]
@MingPap Hi,

`unique_truth_count=0` means that there is no one bounded boxes in labels of your validation dataset `test.txt`, i.e. `test.txt` file contains 700 images, but all corresponding label txt-files are empty.

**Comment by MingPap** [comment]
> @MingPap Hi,
> 
> `unique_truth_count=0` means that there is no one bounded boxes in labels of your validation dataset `test.txt`, i.e. `test.txt` file contains 700 images, but all corresponding label txt-files are empty.

@AlexeyAB  My fault

I copy the wrong labels to the test set .

Maybe I should train from the start ==

Anyway, Thank you so much!
