### ISSUE TITLE
darknet yolov3  output result in one line as pattern

### ISSUE THREAD

**Issue by ericwang321** [AlexeyAB/darknet#2087]
ubuntu 16.04  python 2.7 +CPU+no opencv
--------
**#./darknet detector test cfg/coco.data  cfg/yolov3.cfg yolov3.weights -dont_show < t3.txt > result3.txt**
#more result3.txt
```
Enter Image Path:/home/1/ftp/3/2018.09.03/IPC_192.168.7.231_180903162818_53_MD_ALARM.jpg: Predicted in 0.000000 milli-seconds.
Enter Image Path: /home/1/ftp/3/2018.09.03/IPC_192.168.7.231_180903162552_51_MD_ALARM.jpg: Predicted in 0.000000 milli-seconds.
person: 94%

Enter Image Path: /home/1/ftp/3/2018.09.03/IPC_192.168.7.231_180903162550_49_MD_ALARM.jpg: Predicted in 0.000000 milli-seconds.
person: 30%
person: 94%

Enter Image Path: /home/1/ftp/3/2018.09.03/IPC_192.168.7.231_180903162551_50_MD_ALARM.jpg: Predicted in 0.000000 milli-seconds.
Enter Image Path: /home/1/ftp/3/2018.09.03/IPC_192.168.7.231_180903162553_52_MD_ALARM.jpg: Predicted in 0.000000 milli-seconds.
person: 94%
Enter Image Path: /home/1/ftp/3/2018.09.03/IPC_192.168.7.231_180903162819_54_MD_ALARM.jpg: Predicted in 0.000000 milli-seconds.
```
================================================
**how to change the src code .(image.c/detect.c),one result one line without \n.
output result like  below txt ：**

```
Enter Image Path:/home/1/ftp/3/2018.09.03/IPC_192.168.7.231_180903162818_53_MD_ALARM.jpg: Predicted in 0.000000 milli-seconds.
Enter Image Path: /home/1/ftp/3/2018.09.03/IPC_192.168.7.231_180903162552_51_MD_ALARM.jpg: Predicted in 0.000000 milli-seconds.person: 94%

Enter Image Path: /home/1/ftp/3/2018.09.03/IPC_192.168.7.231_180903162550_49_MD_ALARM.jpg: Predicted in 0.000000 milli-seconds.person: 30% ,person: 94%

Enter Image Path: /home/1/ftp/3/2018.09.03/IPC_192.168.7.231_180903162551_50_MD_ALARM.jpg: Predicted in 0.000000 milli-seconds.
Enter Image Path: /home/1/ftp/3/2018.09.03/IPC_192.168.7.231_180903162553_52_MD_ALARM.jpg: Predicted in 0.000000 milli-seconds,person: 94%
Enter Image Path: /home/1/ftp/3/2018.09.03/IPC_192.168.7.231_180903162819_54_MD_ALARM.jpg: Predicted in 0.000000 milli-seconds.
```

------------
### thanks for any sugestion.

**Comment by AlexeyAB** [comment]
* Comment this line: https://github.com/AlexeyAB/darknet/blob/7d0efaa936c6b5925e68b2a55f42a89b931ca3d1/src/detector.c#L1258

* Change this line: https://github.com/AlexeyAB/darknet/blob/7d0efaa936c6b5925e68b2a55f42a89b931ca3d1/src/image.c#L469
to this `printf(", "); `

* Change this line: https://github.com/AlexeyAB/darknet/blob/7d0efaa936c6b5925e68b2a55f42a89b931ca3d1/src/detector.c#L1236
to this `printf("\nEnter Image Path: "); `

**Comment by ericwang321** [comment]
thanks very much。
just a little question。 **hope reserved full file path**， like this。how to change detetctor.c ?

`Enter Image Path: /home/1/ftp/3/00001.jpg，person: 30% ,person: 94%`

**Comment by ericwang321** [comment]
after test ，done.thanks @AlexeyAB 

organize the record as follows  
 1. detector.c  in [void test_detector ] function 

> printf("Enter Image Path: ");    ---》  printf("\nEnter Image Path: ");

 2.detector.c

> printf("%s: Predicted in %lf milli-seconds.\n", input, ((double)get_time_point() - time) / 1000);  
> change to
> printf("%s,", input); 

3.image.c   in [draw_detections_v3 ] function

> printf("\n"); ---->  printf(", "); 

----

>   for (j = 0; j < classes; ++j) {
>             if (selected_detections[i].det.prob[j] > thresh && j != best_class)
>  {printf("%s: %.0f%%\n", names[j], selected_detections[i].det.prob[j] * 100);
> 
> -->printf("%s: %.0f%%", names[j], selected_detections[i].det.prob[j] * 100);

output  example:
Total BFLOPS 65.864 

 seen 64 

> Enter Image Path: /home/toor/5/darknet/data/pic/2.jpg,
> Enter Image Path: /home/toor/5/darknet/data/pic/1.png,person: 98%,
> Enter Image Path: /home/toor/5/darknet/data/pic/4.jpg,person: 99%,person: 94%,person: 55%,traffic light:52%
> Enter Image Path: /home/toor/5/darknet/data/pic/3.png,person: 100%,person: 100%,person: 100%,person: 46%,
> Enter Image Path: 

-----
still have question:
```
how to comment total BFLOPS  seen 64  in which src file ?
how to filter export only person (after change the code as simple add if  person ,but still export traffic light )?
```
----
thanks for any suggestion.

**Comment by ericwang321** [comment]
close the issue temporarily and wait for time to better method.
