### ISSUE TITLE
training dataset with different resolution[discussion]

### ISSUE THREAD

**Issue by RickyWong33** [AlexeyAB/darknet#209]
Thanks AlexeyAB for supporting this repo, I do learn a lot by going through the whole issues.

What I am going to talk about is not a bug, but a related question.
 
Aiming to detect persons, I start to train pedestrian dataset though yolo, while it turns out the person who stands can be observed but person who sit cannot. In other words, I have to train not only pedestrian dataset, but also dataset where person has other "shape".

Obviously, different dataset has different resolution, while it seems that yolo's performance is highly related the user-defined height&width of the cfg file.

So, what's your advice?
Should I 
- compute the average ratio of the images and set a suitable height and width to train them together 
--------   
**or**
- set the first height&width to finish the first dataset's training and go on making adjustment of the cfg to train second dataset...    
-------
**or**
- just how to deal with multi-dataset training for yolo

Any suggestions will be appreciated.

**Comment by AlexeyAB** [comment]
Hi, @RickyWong33 

1. Recommendation - after resizing images to the network-size - objects should have the same size in pixels using the training-dataset and detection-dataset.

    So if you have objects(50x50) on training images(500x500), and objects(100x100) on training images(1000x1000), but you have only objects(50x50) on **detection** images(500x500)/video, then yes - you should train your model on network resolution 416x416 using images(500x500) and then train this model on network resolution 832x832 using images (1000x1000). Then in all cases objects will have the same size 42x42 pixels after resizing images to network resolution.
    In real cases you have range of sizes, but the approach is the same.

2. General recommendation is - for training: network_resolution, image_resolution, object_size - should be the same as for detection.

    So if you will train one model using different resolution for different datasets, so for detection you should use different different resolution for different datasets too.


3. This is the simplest way, start with it, measure the IoU, then try other ways and compare IoU:

> Should I compute the average ratio of the images and set a suitable height and width to train them together

**Comment by RickyWong33** [comment]
Thanks, I fully understand, reaaaally appreciate it.
Hope can do help for other.
