### ISSUE TITLE
Detection and region layers

### ISSUE THREAD

**Issue by sealedtx** [AlexeyAB/darknet#2097]
Can you briefly explain what is the difference between [region] and [detection] layers, because i often see both of them as last layer in network? When should i use one and another? Thank you

**Comment by AlexeyAB** [comment]
* `[detection]` - just experiment
* `[region]` - is the last layer for Yolo v2
* `[yolo]` - is the last layer for Yolo v3 - currently the best accuracy mAP

**Comment by sealedtx** [comment]
@AlexeyAB Thank you!
