### ISSUE TITLE
multiple network cams access at same time

### ISSUE THREAD

**Issue by mandeepubc** [AlexeyAB/darknet#210]
Hi,
I have multiple IP cameras running at the same time in which I would like to implement YOLO. Is there a way that YOLO can be run on all of them at the same time? like 4 different sections in a screen?
Thanks

**Comment by AlexeyAB** [comment]
Hi, yes, just run yolo 4 times.
(on Linux use 4 terminals)

**Comment by mandeepubc** [comment]
thanks

**Comment by SouradipBh** [comment]
Hi @mandeepubc ,
How do you connect multiple ip camera with darknet?Which part have you make changes?
