### ISSUE TITLE
clarification on anchors size

### ISSUE THREAD

**Issue by bit-scientist** [AlexeyAB/darknet#2104]
Hi everyone!
My cfg file's size is `height=416,` `width=416` and `anchors = 1.08,1.19,  3.42,4.41,  6.63,11.38,  9.42,5.11,  16.62,10.52`, `random = 0`, `classes = 1`, and trying to train with **darknet19_448.conv.23** weights.
If I increase the network size, say, 2 times, should I also increase each values of anchors 2 times as well?
LIKE THIS?
`height=832,` `width=832` and `anchors = 2.16,2.38, 6.84,8.82,  13.26,22.76,  18.84,10.22,  33.24,21.04`
Anyway, what is the relation of size and anchor values? 
The width and height of my objects are at least, 40 and 100, respectively. They get larger as they come close to the camera. 
Thank you!

**Comment by AlexeyAB** [comment]
@bit-scientist Hi,

* The anchors are initial average sizes of objects:

    * in the yolov2 relative to the output feature map 13x13
    * in the yolov3 relative to the input image size 416x416

----

> If I increase the network size, say, 2 times, should I also increase each values of anchors 2 times as well?
> LIKE THIS?
> height=832, width=832 and anchors = 2.16,2.38, 6.84,8.82, 13.26,22.76, 18.84,10.22, 33.24,21.04

In general yes. Better to do it.
