### ISSUE TITLE
Obj score keep decreasing

### ISSUE THREAD

**Issue by izesaon** [AlexeyAB/darknet#2106]
Training tiny yolo v2 on my own dataset but while loss is decreasing and iou seems to be increasing, obj score is decreasing.. is this normal? :( Stuck here

**Comment by AlexeyAB** [comment]
This is normal.

You can use the latest version from this repository. And train with flag `-map` so you will see the mAP chart (red line). While mAP is increasing - the training is going well.

**Comment by izesaon** [comment]
hi, thanks for the response. Just wondering if there is a way to speed up training since it takes quite a while with 500 images. Will 500 images be sufficient? Roughly how many iterations will be good :/

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet#when-should-i-stop-training

> Usually sufficient 2000 iterations for each class(object), but **not less than 4000 iterations in total**.

https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

> desirable that your training dataset include images with objects at diffrent: scales, rotations, lightings, from different sides, on different backgrounds - you should preferably have **2000 different images for each class or more, and you should train 2000*classes iterations or more**

**Comment by izesaon** [comment]
Thanks for the help:) can I check if this GitHub repo supports gpu training on Google Colab or Amazon EC2 etc? Not so sure how to start but guess I would have to fiddle around quite a bit.

**Comment by izesaon** [comment]
Also, I have another question, do you know why when I train on your repo vs pjreddie, initial loss for yours is much lower? What’s the difference between this repo and pjreddie? Thanks for the help once again and sorry for the inconvenience!

**Comment by AlexeyAB** [comment]
There is guide how to train on Amazon EC2: https://github.com/AlexeyAB/darknet/issues/1380#issuecomment-412333942

I used `p3.2xlarge` Amazon instance (Tesla V100) use `GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=1` in the Makefile and train with `-dont_show` flag


> I have another question, do you know why when I train on your repo vs pjreddie, initial loss for yours is much lower? What’s the difference between this repo and pjreddie?

* Difference between this repo and pjreddie's: https://github.com/AlexeyAB/darknet/issues/232#issuecomment-336955485

* Also this repo supports Tensor Cores if is used `CUDNN_HALF=1` in the `Makefile` so it works 2-3x faster on Tesla V100, Jetson Xavier or RTX 2070/2080/ti: https://github.com/AlexeyAB/darknet/issues/407

* Also Improvements in this repository: https://github.com/AlexeyAB/darknet#improvements-in-this-repository

**Comment by izesaon** [comment]
Thanks so much, I will have a look :)
