### ISSUE TITLE
Classification based on number of classes/objects

### ISSUE THREAD

**Issue by Arfinul** [AlexeyAB/darknet#2107]
I have to find number of good leaves.
Good leaf - 2 leaf and a bud, 1 leaf and a bud
Bad leaf - rest cases
I am able to classify leaf and bud, but how to classify "2 leaf and a bud", "1 leaf and a bud" ?

**Comment by AlexeyAB** [comment]
Just train your model for 2 classes.

Label on the images 2 types of objects by using this utility: https://github.com/AlexeyAB/Yolo_mark

1. mark `2 leaf and a bud` or `1 leaf and a bud` as object-0
2. mark `rest cases` as object-1

----

Or you can mark 3 classes:

1. `2 leaf and a bud`  as object-0
2. `1 leaf and a bud` as object-1
3. `rest cases` as object-2

**Comment by Arfinul** [comment]
Are you suggesting to label 2 leaves and bud together?

But there is one condition on selecting a bud among 2 leaves & a bud or 1 leaf & a bud.
Bud size > half of smaller size leaf

How you will suggest to process? 
1. Labeling 2 leaf and a bud or 1 leaf and a bud as object-0 (Good leaf)
    rest cases as object-1(Bad leaf)
    **I think, by this 2 leaf and small size bud than leaf will also be classified as object-0**
      or,
2. Labeling leaf as object-0 and bud as 1 (only from images, where bud size > half of smaller size leaf)
    And then based on counting, retrieve the number of 2 leaves and bud,1 leaf and bud etc..
    It seems this will not work?

One more suggestion:
I have to perform testing on video file of falling leaves.
Shall I prepare the training set from frames of falling leaves video captured from a distance of 1 meter? 
or,
from still images of leaves?

**Comment by AlexeyAB** [comment]
> Are you suggesting to label 2 leaves and bud together?

Yes.


----

> I think, by this 2 leaf and small size bud than leaf will also be classified as object-0

What do you mean?

----


> Shall I prepare the training set from frames of falling leaves video captured from a distance of 1 meter?
> or,
> from still images of leaves?

Combine images from "falling leaves" and "still images of leaves"

**Comment by Arfinul** [comment]
I have to find the number of good leaves.
Good leaf - 2 leaves and a bud, 1 leaf and a bud. Where **Bud size > half of smaller size leaf**
Bad leaf - rest cases

If I label 2 leaves and bud or 1 leaf and bud together
**Possible issue** - Images in which bud size < half of smaller size leaf, then
Images of 2 leaves & a bud, 1 leaf & a bud will get classified Good leaf

**Comment by AlexeyAB** [comment]
> Possible issue - Images in which bud size < half of smaller size leaf, then

you should label `bud size > half of smaller size leaf` as object-0
and `bud size < half of smaller size leaf` as object-1
