### ISSUE TITLE
result of calc_anchors are not equal for same data

### ISSUE THREAD

**Issue by zhongjiejiang** [AlexeyAB/darknet#2115]
Hi Alexey,

I execute the calc_anchors command three times , and get different results every time. is it right?

one time:
 num_of_clusters = 9, width = 512, height = 512
 read labels from 1518 images
 loaded          image: 1517     box: 2842Can't open label file. (This can be normal only if you use MSCOCO):

 all loaded.

 calculating k-means++ ...

 avg IoU = 70.39 %

Saving anchors to the file: anchors.txt
anchors =  20, 57,  71, 73,  42,148,  82,305, 151,170, 259,233, 236,390, 387,322, 424,432

two time:
num_of_clusters = 9, width = 512, height = 512
 read labels from 1518 images
 loaded          image: 1517     box: 2842Can't open label file. (This can be normal only if you use MSCOCO):

 all loaded.

 calculating k-means++ ...

 avg IoU = 71.17 %

Saving anchors to the file: anchors.txt
anchors =  17, 47,  32, 87,  84, 84,  52,191,  97,312, 188,179, 239,353, 368,303, 421,424

three time:
 num_of_clusters = 9, width = 512, height = 512
 read labels from 1518 images
 loaded          image: 1517     box: 2842Can't open label file. (This can be normal only if you use MSCOCO):

 all loaded.

 calculating k-means++ ...

 avg IoU = 71.03 %

Saving anchors to the file: anchors.txt
anchors =  17, 48,  33, 88,  87, 89,  53,202, 104,326, 189,180, 245,346, 377,309, 422,428

**Comment by AlexeyAB** [comment]
@zhongjiejiang Hi,

This is normal.

There is used random Initialization methods in the K-means: https://en.wikipedia.org/wiki/K-means_clustering#Initialization_methods
So it will get different result each time: https://github.com/AlexeyAB/darknet/blob/64e478db07190606a5a5a8bf416b40a2e570396b/src/matrix.c#L294
Just run it several times and get the best result.

**Comment by zhongjiejiang** [comment]
thank u ：）
