### ISSUE TITLE
the shake of mAP is bigger

### ISSUE THREAD

**Issue by zhongjiejiang** [AlexeyAB/darknet#2118]
Hi Alexey，

I train myself data about 2000 images， I set width=512 and height=512， and exec calc_anchors command, but the mAP have a big shake,  which is normal?  thanks.
![wechatimg117](https://user-images.githubusercontent.com/1235650/50500972-af59a680-0a8f-11e9-8873-bf2ecf5e1e4c.jpeg)

jason

**Comment by AlexeyAB** [comment]
@zhongjiejiang Hi,

* Do you use the latest version of this repository?
* Do you use random=1 in the last [yolo]-layer in your cfg-file?
* How many classes do you have?
* How many images in the Training and Validation datasets? Or do you use Training dataset only?

**Comment by zhongjiejiang** [comment]
Hi AlexeyAB,

I get the code about before six days.
I use the random=1
I have three case,  one case is 4 classes, one case is 1 classes, and one case is 10 classs
    for 4 classes: training dataset is 1500 images and validation detest is 400 images,
    for 1 classes: training dataset is 1400 images and validation detest is 500 images,
    for 10 classes(coco dataset and ourself dataset): training dataset is 70000 images and validation       detest is 5000 images,

I found the 70000 images case is ok, mAP is smoothness， but other two case the mAP is shake。
