### ISSUE TITLE
C++ inference

### ISSUE THREAD

**Issue by huaze555** [AlexeyAB/darknet#2126]
Hi， if i have a trained weight ， i  want to detect a image using c++ inference in linux, how should i do?

**Comment by AlexeyAB** [comment]
@huaze555 Hi,

* Change this file as you want: https://github.com/AlexeyAB/darknet/blob/master/src/yolo_console_dll.cpp

* Compile Darknet with `LIBSO=1` in the `Makefile`

* And run: https://github.com/AlexeyAB/darknet#how-to-compile-on-linux

`LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./uselib data/coco.names cfg/yolov3.cfg yolov3.weights test.mp4`

**Comment by huaze555** [comment]
@AlexeyAB thanks very much！！!

**Comment by huaze555** [comment]
@AlexeyAB Hi! do your c++ inference support tensorrt?
