### ISSUE TITLE
unable to predict objects after yolo-obj_100.weights for custom object

### ISSUE THREAD

**Issue by VellalaVineethKumar** [AlexeyAB/darknet#2128]
i am training darknet53.conv.74 (yolov3) with my custom data-set on Tesla V100, the object detection works only for yolo-obj_100.weights after this any weights saved do not give any predictions 
i am unable to understand why this is happening!
any help would be appreciated

my Makefile:

GPU=1
CUDNN=0
OPENCV=0
OPENMP=0
DEBUG=0

ARCH= -gencode arch=compute_30,code=sm_30 \
      -gencode arch=compute_35,code=sm_35 \
      -gencode arch=compute_50,code=[sm_50,compute_50] \
      -gencode arch=compute_52,code=[sm_52,compute_52]
#      -gencode arch=compute_20,code=[sm_20,sm_21] \ This one is deprecated?

# This is what I use, uncomment if you know your arch and want to specify
# ARCH= -gencode arch=compute_52,code=compute_52

VPATH=./src/:./examples
SLIB=libdarknet.so
ALIB=libdarknet.a
EXEC=darknet
OBJDIR=./obj/

i have run make command after changing gpu=1

**Comment by AlexeyAB** [comment]
> the object detection works only for yolo-obj_100.weights

It can't be used for detection becuse it is to low number of iterations.

* What command do you use for training?
* Do you train on the local machine or on the remote machine (connected by ssh like Amazon EC2)?
* If you train your model on machine with WindowX, then try compile Darknet with `GPU=1 CUDNN=1 OPENCV=1` and train with flag `-map`
`./darknet detector train data/obj.data yolo-obj.cfg darknet53.conv.74 -map`

and then after 4000 iterations - attach to your message generated file `chart.png` /jpg

**Comment by VellalaVineethKumar** [comment]
./darknet detector train data/obj.data cfg/yolo-obj.cfg darknet53.conv.74  is the command i use

i train on a server(nvidia DGX-1)  provided by our university 

i am training this on ubuntu 10.04 with cuda 10 installed on it

**Comment by AlexeyAB** [comment]
@VellalaVineethKumar 

So just try to train using this command at least **1000 iterations** (or better 4000 iterations)
`./darknet detector train data/obj.data cfg/yolo-obj.cfg darknet53.conv.74`

Then try to check mAP by using this command: https://github.com/AlexeyAB/darknet#when-should-i-stop-training
`./darknet detector map data/obj.data yolo-obj.cfg backup\yolo-obj_1000.weights`

or for 4000 iterations:
`./darknet detector map data/obj.data yolo-obj.cfg backup\yolo-obj_4000.weights`

----

Also try to find out if cuDNN and OpenCV libraries are installed on your server.
What can you get by using these commands?
```
nvcc --version
cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
pkg-config --cflags opencv
pkg-config --libs opencv
````

**Comment by VellalaVineethKumar** [comment]
root@68e16b712636:/workspace# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

I am inside a docker hence I get 
cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MA
cat: /usr/local/cuda/include/cudnn.h: No such file or directory

i even tried this outside the docker in my ubuntu user account i get the same 
dgx4@dgx-server:~$  cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MA
cat: /usr/local/cuda/include/cudnn.h: No such file or directory


for pkg-config --cflags opencv
root@68e16b712636:/workspace# pkg-config --cflags opencv
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
same error message in the Ubuntu user account

for pkg-config --libs opencv
root@68e16b712636:/workspace# pkg-config --libs opencv
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
and same error message for Ubuntu user account

Training in progress for 4000 iterations, there was no any output for yolo-obj_900.weights 
root@68e16b712636:/workspace/dgx4/darknet# ./darknet detector map data/obj.data cfg/yolo-obj.cfg backup/yolo-obj_900.weights 
root@68e16b712636:/workspace/dgx4/darknet# 

Thanks for your patience replies :-)

**Comment by VellalaVineethKumar** [comment]
4205: 0.502312, 0.555812 avg, 0.001000 rate, 4.195494 seconds, 269120 images
Loaded: 0.000081 seconds

after 4000 iterations i copied the yolo-obj.backup from backup directory to darknet directory and ran the ./darknet detector map data/obj.data yolo-obj.cfg backup\yolo-obj_1000.weights
command and it returned no output 
root@68e16b712636:/workspace/dgx4/darknet# ./darknet detector map data/obj.data cfg/yolo-obj.cfg yolo-obj.backup 
root@68e16b712636:/workspace/dgx4/darknet#

**Comment by AlexeyAB** [comment]
Use my repository https://github.com/AlexeyAB/darknet instead of https://github.com/pjreddie/darknet

Also read: https://github.com/AlexeyAB/darknet#improvements-in-this-repository
