### ISSUE TITLE
change thickness of box and font size

### ISSUE THREAD

**Issue by mandeepubc** [AlexeyAB/darknet#213]
Hi, 
I made changes to the width of the box detectors in the file image.c 
function draw_detections where "int width = im.h * .006;"
after saving image.c with this edit, I rebuilt yolo_cpp_dll.sln and then yolo_console_dll.sln 
The width of the box is still the same. I dont know why it is not updating.
Thanks

**Comment by AlexeyAB** [comment]
Hi,

Change number `5` in this line cv::rectangle(mat_img, cv::Rect(i.x, i.y, i.w, i.h), color, **5**); 
  
https://github.com/AlexeyAB/darknet/blob/548a0bc652b562723695cc107f0844f11d1a2207/src/yolo_console_dll.cpp#L38

**Comment by mandeepubc** [comment]
@AlexeyAB Also how do i change the size of upper box and font size which prints the object class with its track id. eg: person - 1. 
Thanks

**Comment by AlexeyAB** [comment]
@mandeepubc Look at value `1.2`

* Change font scale:  putText(mat_img, obj_name, cv::Point2f(i.x, i.y - 10), cv::FONT_HERSHEY_COMPLEX_SMALL, **1.2**, cv::Scalar(0, 0, 0), 2);
https://github.com/AlexeyAB/darknet/blob/548a0bc652b562723695cc107f0844f11d1a2207/src/yolo_console_dll.cpp#L47
  

* And change size of upper box:  cv::Size const text_size = getTextSize(obj_name, cv::FONT_HERSHEY_COMPLEX_SMALL, **1.2**, 2, 0);
https://github.com/AlexeyAB/darknet/blob/548a0bc652b562723695cc107f0844f11d1a2207/src/yolo_console_dll.cpp#L42

**Comment by mandeepubc** [comment]
@AlexeyAB omg thankyou!
