### ISSUE TITLE
Which one to use: yolov2_tiny or yolov3_tiny?

### ISSUE THREAD

**Issue by tooskoolforkool** [AlexeyAB/darknet#2132]
@AlexeyAB 

yolov2_tiny vs yolov3_tiny: which one would you recommend in terms of:

- Training speed
- Detection speed
- Detection accuracy
- any other criterion you can think of

Are there any tangible differences between the two models? I ran them on my webcam, and their performance looked similar. This is why I want to know if there is any advantage of one of the models over the other.

**Comment by AlexeyAB** [comment]
@tooskoolforkool 

As you can see: https://pjreddie.com/darknet/yolo/
Tiny v3 is `(33.1/23.7) =` **40% more precisely** and only `220/244 = ` **2% slower** than Tiny v2.


* Tiny YOLO v2 - 23.7% mAP - 244 fps

* YOLOv3-tiny - 33.1% mAP - 220 fps

So you should use v3 model in any cases.

**Comment by tooskoolforkool** [comment]
Thanks a lot
