### ISSUE TITLE
training for many objects in one image 

### ISSUE THREAD

**Issue by zhongjiejiang** [AlexeyAB/darknet#2138]
Hi AlexeAB，

I have about 2000 sheep images , which one sheep in a image or manys sheep in a image, I have label them and training(number of train about 1600, and val number about 400，change the width =608 height=608、calculate the anthor， run 12000 iterator ), but I can't get good result when I detector image which have many sheeps.  
![wechatimg121](https://user-images.githubusercontent.com/1235650/50624526-301b1580-0f5c-11e9-95f9-c547703492eb.jpeg)
![wechatimg122](https://user-images.githubusercontent.com/1235650/50624530-36a98d00-0f5c-11e9-938e-6ee8ff830692.jpeg)

can you some suggest for label and train， thanks。
jason

**Comment by AlexeyAB** [comment]
@zhongjiejiang Hi,

* Did you use Yolo_mark for labeling? https://github.com/AlexeyAB/Yolo_mark
* What mAP can you get? https://github.com/AlexeyAB/darknet#when-should-i-stop-training
* What commands did you use for Training and Detection?
* Can you attach your cfg-file? (rename it to txt-file and drag-n-drop to your message)

**Comment by zhongjiejiang** [comment]
Hi AlexeyAB, 

1)  I use the labelimg tool to mark.
2) I get the mAP about 67% & loss 2,  or other train result mAP 70% & loss 0.8, but all the detection result are not ok
3) the command for training: ./darknet detector train data\sheep-singletrain-with-coco\voc.data data\sheep-singletrain-with-coco\voc.cfg yolov3.weights.81, 
    and detection: ./darknet detector test data/sheep-singletrain-with-coco/voc.data data/sheep-singletrain-with-coco/608-anthor-stopback/voc.cfg data/sheep-singletrain-with-coco/608-anthor-stopback/backup/voc_10000.weights -i 0 -thresh 0.25 data/test/700453.jpg

4) I change the cfg file:
     set the width and calc the anchors:
         width=608
         height=608
         anchors = 15, 18,  38, 47,  70, 89,  86,194, 154,120, 170,265, 408,167, 280,364, 485,453 
     set the classes=1 :
         classes=1
         filters=18
      set stopbackward=1



[voc.cfg.txt](https://github.com/AlexeyAB/darknet/files/2725934/voc.cfg.txt)

**Comment by AlexeyAB** [comment]
@zhongjiejiang Hi,

> I use the labelimg tool to mark.

May be your dataset is wrong.

* Try to open your dataset by using Yolo_mark: https://github.com/AlexeyAB/Yolo_mark

* Check that your truth boxes don't overlap each othat in the Training dataset.

* If your dataset is correct, then try to set `float nms = 0.2;` instead of https://github.com/AlexeyAB/darknet/blob/527578744b46666fb5cd42393bf9e1fa9af126ee/src/detector.c#L1248

**Comment by zhongjiejiang** [comment]
Hi AlexeyAB，

I have checked the label by yolo_mark, label is ok.

there are little boxes are overlap in the training dataset, I will remove them.

![1](https://user-images.githubusercontent.com/1235650/50719172-66c76c00-10d3-11e9-9e62-f928ee3e8a60.jpeg)
![2](https://user-images.githubusercontent.com/1235650/50719173-66c76c00-10d3-11e9-86ee-08b838de3d44.jpeg)

thanks for your help 👍 
jason

**Comment by AlexeyAB** [comment]
@zhongjiejiang 

> there are little boxes are overlap in the training dataset, I will remove them.

* Don't remove boxes at all. Just try to mark objects without overlaps more than 40%.

* Also I see that some objects aren't labeld - it isnt' correct. Each object should be labeled in your Training dataset: https://github.com/AlexeyAB/darknet#how-to-improve-object-detection


> check that each object are mandatory labeled in your dataset - **no one object in your data set should not be without label.** In the most training issues - there are wrong labels in your dataset (got labels by using some conversion script, marked with a third-party tool, ...). Always check your dataset by using: https://github.com/AlexeyAB/Yolo_mark


----

**If you didn't mark each object on each Training image, then the network will not detect each object.**

**Comment by zhongjiejiang** [comment]
Hi AlexeAB, 

some object aren't labeled，because there are so many object in one image and they are occlusion each other.

if every object shoud be labeled,  one object in one image is better?

but I have other scnece, I get 2 classes(people and car) labels and images from coco dataset, and I found there are others object are not labeled in one image, such as dog, bus.  so can I do that for only train 2 classes about coco dataset?

**Comment by AlexeyAB** [comment]
@zhongjiejiang Hi,

> if every object shoud be labeled, one object in one image is better?

If you want to detect on images with many objects, then you should train on images with many objects, where are all objects are marked.


> but I have other scnece, I get 2 classes(people and car) labels and images from coco dataset, and I found there are others object are not labeled in one image, such as dog, bus. so can I do that for only train 2 classes about coco dataset?

Yes, if all persons and cars are marked.

**Comment by zhongjiejiang** [comment]
Hi AlexeyAB，

I found some labels are big box contain many objects in coco datasets， 

![wechatimg126](https://user-images.githubusercontent.com/1235650/50747877-4503eb80-1271-11e9-8086-157f2154b48a.jpeg)
![wechatimg127](https://user-images.githubusercontent.com/1235650/50747881-4c2af980-1271-11e9-8c62-b0dd806c89f1.jpeg)

is it labeled fault or have special meaning？ 

thanks
jason

**Comment by AlexeyAB** [comment]
@zhongjiejiang Hi,

What dataset do you use train/test/... 2014/2017/...?
Did you get this dataset by using https://github.com/AlexeyAB/darknet/blob/master/scripts/get_coco_dataset.sh ?
Can you write filenames of these images?

**Comment by zhongjiejiang** [comment]
Hi AlexeAB,
I use 2017 train and val data.
I didn't use get_coco_dataset.sh  shell to get this coco dataset. I get it from coco site and change the labels from json to txt format for darknet.
I found that many image file have this problem. like 000000001318.jpg, 000000017420.jpg and so on.
