### ISSUE TITLE
Remove classes which are not needed in dll

### ISSUE THREAD

**Issue by mandeepubc** [AlexeyAB/darknet#215]
Hi,
I am trying to delete the classes that I dont need from the dll file. But it is not being reflected after the re-build. I made changes in image.c. 

if(prob > thresh && (class == 4 || class == 5 || class == 6 || class == 8 || class == 10 || class == 14 || class == 17 || class == 19)) 
and saved it.
then re-built both cpp and console solution file. How can I make these changes in the dll files?
Thanks

**Comment by AlexeyAB** [comment]
Hi,

Before this line: https://github.com/AlexeyAB/darknet/blob/548a0bc652b562723695cc107f0844f11d1a2207/src/yolo_console_dll.cpp#L168

Add this 2 lines:
```
result_vec.resize(std::remove_if(result_vec.begin(), result_vec.end(), 
    [](auto v) {return v.obj_id != 14 && v.obj_id != 0; }) - result_vec.begin());
```

Will be removed classes 0 and 14.

More about this: https://github.com/AlexeyAB/darknet/issues/201#issuecomment-331271546

**Comment by mandeepubc** [comment]
@AlexeyAB so this will not detect airplane and person when I re-build with this code?

**Comment by AlexeyAB** [comment]
@mandeepubc No, I fixed typo. Code above removes all classes except 0 and 14.

This code will remove classes 0 and 14:
```
result_vec.resize(std::remove_if(result_vec.begin(), result_vec.end(), 
    [](auto v) {return v.obj_id == 14 || v.obj_id == 0; }) - result_vec.begin());
```

**Comment by mandeepubc** [comment]
@AlexeyAB can these cpp.dll files be compiled in Ubuntu?

**Comment by AlexeyAB** [comment]
@mandeepubc Yes, with `LIBSO=1` in the makefile: https://github.com/AlexeyAB/darknet#how-to-compile-on-linux

**Comment by mandeepubc** [comment]
@AlexeyAB I am trying to run the uselib file,but I am getting this error: 
./uselib: error while loading shared libraries: darknet.so: cannot open shared object file: no such file or directory.
which object file is missing?

**Comment by AlexeyAB** [comment]
@mandeepubc try to run so `LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./uselib`
https://github.com/AlexeyAB/darknet#how-to-compile-on-linux

**Comment by mandeepubc** [comment]
@AlexeyAB I am still getting the same error. Why is it not recognising darknet.so when it is in the same folder? Is there any other way?

**Comment by mandeepubc** [comment]
@AlexeyAB Thanks! it worked!
