### ISSUE TITLE
Compiling yolo_cpp_dll.sln in debug mode gives error.

### ISSUE THREAD

**Issue by AyushP123** [AlexeyAB/darknet#2158]
OS: Windows 10
Visual Studio Version: 2015

I tried to build yolo_cpp_dll.sln in "Debug, x64" mode and got the error:

> error C2065: '_CRTDBG_ALLOC_MEM_DF': undeclared identifier
> error C2065: '_CRTDBG_LEAK_CHECK_DF': undeclared identifier

because of these lines of code in [darknet.c](https://github.com/AlexeyAB/darknet/blob/3ff5084590bce621b195196edd32ac7e3b04bfbd/src/darknet.c#L354)

```
#ifdef _DEBUG
	_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);
#endif
```
Please help me in resolving this issue.

**Comment by AlexeyAB** [comment]
I just fixed it in the last commit.

Added `stdlib.h;crtdbg.h;%(ForcedIncludeFiles)` in the
\yolo_cpp_dll.sln -> (right click on project) -> properties -> C/C++ -> Additional -> Forced Include Files

**Comment by AyushP123** [comment]
Hi,
     Thank you for the response :) . Its fixed for me.
