### ISSUE TITLE
Issue with forward_maxpool_layer_kernel in OpenCL

### ISSUE THREAD

**Issue by sat8** [AlexeyAB/darknet#216]
Hi 

I am porting the code to OpenCL and have been able to verify that I was able to get the convolution layer output identical to that of the CUDA version. (i.e Opencl versions of im2col, gemm, batch_normalization, add_bias, scale_bias, activate kernels are good and working - producing CUDA identical output). To claim all of the above, I have compared the output of CUDA and Opencl kernels. 

However I am struggling with maxpool kernel in OpenCL. I have changed the BLOCK to 64 in OpenCL version otherwise, clEnqueueNDRangeKernel will report an CL_INVALID_WORK_GROUP_SIZE error if 512 is used (as in CUDA code)

Below is a bit of code just to aid explanation.
```
#define BLOCK 64
	globalDims.m_NumX = n / BLOCK;
	if (globalDims.m_NumX % BLOCK != 0)
		globalDims.m_NumX = ((globalDims.m_NumX + BLOCK) / BLOCK) * BLOCK;

	globalDims.m_NumY = 1;
	globalDims.m_NumZ = 1;
	m_OpenCLKernels[NN_KERNEL_IDX_MAXPOOL]->pGlobal(globalDims.m_NumX, globalDims.m_NumY, globalDims.m_NumZ)->pLocal(BLOCK, 1, 1);
```
While processing the second layer of tiny-yolo configuration, the input size for maxpool is 692224. The global work group size is worked out based on the code above to (10816, 1, 1) and the local work group to be (64, ,1, 1). 

The issue is that the kernel will ever produce the output for 10816 items of the input only (the rest are just 0's in the max pool layer's output. The calculated 10816 values are correct, though). This number is basically the global work group's x dimension. I think this is an indexing issue which I am unable to figure out.  I am using GTX 1080Ti by the way which reports 1024 x1024 x 64 as the work item sizes.

Below is the opencl kernel 

```
__kernel void maxpool(int n, int in_h, int in_w, int in_c, int stride, int size, 
				int pad, __global float *input, __global float *output, __global int *indexes) {

	int h = (in_h + 2 * pad) / stride;
	int w = (in_w + 2 * pad) / stride;
	int c = in_c;

	//int id = (blockIdx.x + blockIdx.y*gridDim.x) * blockDim.x + threadIdx.x;
	unsigned int id = (get_group_id(0) + get_group_id(1) * get_num_groups(0)) * get_local_size(0) + get_local_id(0);
	//int id = get_global_id(0);

	if (id >= n) 
		return;

	int j = id % w;
	id /= w;
	int i = id % h;
	id /= h;
	int k = id % c;
	id /= c;
	int b = id;

	int w_offset = -pad;
	int h_offset = -pad;

	int out_index = j + w*(i + h*(k + c*b));
	float maxVal = -INFINITY;
	int max_i = -1;
	int l, m;
	for (l = 0; l < size; ++l) {
		for (m = 0; m < size; ++m) {
			int cur_h = h_offset + i*stride + l;
			int cur_w = w_offset + j*stride + m;
			int index = cur_w + in_w*(cur_h + in_h*(k + b*in_c));
			int valid = (cur_h >= 0 && cur_h < in_h &&
				cur_w >= 0 && cur_w < in_w);
			float val = (valid != 0) ? input[index] : -INFINITY;
			max_i = (val > maxVal) ? index : max_i;
			maxVal = (val > maxVal) ? val : maxVal;
		}
	}
	output[out_index] = maxVal;
	indexes[out_index] = max_i;
}
```
Any ideas would be much appreciated. Thanks.

**Comment by AlexeyAB** [comment]
Hi,

There are 2 places where you could make a mistake:
* `globalDims.m_NumX = ((globalDims.m_NumX + BLOCK) / BLOCK) * BLOCK;`
* `unsigned int id = (get_group_id(0) + get_group_id(1) * get_num_groups(0)) * get_local_size(0) + get_local_id(0);`

----

1. About `globalDims.m_NumX`, do you mean this?
```
#define BLOCK 64
	globalDims.m_NumX = n / BLOCK;
	if (n % BLOCK != 0)
		globalDims.m_NumX += 1;

	globalDims.m_NumY = 1;
	globalDims.m_NumZ = 1;
	m_OpenCLKernels[NN_KERNEL_IDX_MAXPOOL]->pGlobal(globalDims.m_NumX, globalDims.m_NumY, globalDims.m_NumZ)->pLocal(BLOCK, 1, 1);
```

----

2. Try to use `int id = get_global_id(0);` https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/get_global_id.html

* Also, the main diff between CUDA and your OpenCL versions:

![maxpool_diff](https://user-images.githubusercontent.com/4096485/31091740-a2065eb8-a7b4-11e7-9720-993b974cb4f1.jpg)

* Diff between CUDA and OpenCL:

![opencv_cuda](https://user-images.githubusercontent.com/4096485/31092028-bdef4080-a7b5-11e7-96f5-c2159bae9504.jpg)

----

3. How did you get values **692224** and **10816**? 

> While processing the second layer of tiny-yolo configuration, the input size for maxpool is 692224. The global work group size is worked out based on the code above to (10816, 1, 1) and the local work group to be (64, ,1, 1).

If we speak about max-pool-layer-1 with initial size 416 x 416, then:
* input size of each channel: 416 x 416 = **173056** floats
* input size of layer: 173056 x 16 = **2768896** floats

* output size of each channel: 208 x 208 = **43264** floats
* output size of layer: 43264 x 16 = **692224** floats

![maxpool](https://user-images.githubusercontent.com/4096485/31090182-75f8885a-a7af-11e7-87ac-12443c2b9451.jpg)

----

**A.** Also look at the **max-pool-layer-11**:
* with **odd size** 13 x 13 x 512
* with stride=1

**B.** Also you should know, that for **conv-layers with `size = 1`**, always `pad=0`, even if in the cfg-file is written pad=1: 
* In the final layer of tiny-yolo: https://github.com/AlexeyAB/darknet/blob/c38ec6241985a3302f17b6178128cbe4ea2ce858/cfg/tiny-yolo.cfg#L113
* In the some of layers in the full yolo: https://github.com/AlexeyAB/darknet/blob/c38ec6241985a3302f17b6178128cbe4ea2ce858/cfg/yolo-voc.cfg#L62

**Comment by sat8** [comment]
Ok thanks for the pointers. I think the original kernel in CUDA uses 'id', the index/offset to the array input. I mis-read the code as the variable is re-used to calculate out width, height etc, It was a bug in my kernel (a a modified one than I copied here)  as I was also using the same variable.

Below is the new kernel

`__kernel void maxpool(int n, int in_h, int in_w, int in_c, int stride, int size, 
				int pad, __global float *input, __global float *output) { 

	int h = (in_h + 2 * pad) / stride;
	int w = (in_w + 2 * pad) / stride;
	int c = in_c;

	int stepSize = get_local_size(0);
	int idx = get_global_id(0) * stepSize;

	int count = 0, id = 0;
	int j, i, k, w_offset, h_offset, out_index, l, m, cur_h, cur_w, index, valid;
	float maxVal, val;

#pragma unroll 8
	for (; count < 8; count++) {

		id = idx;
		j = id % w;
		id /= w;
		i = id % h;
		id /= h;
		k = id % c;
		id /= c;

		w_offset = -pad;
		h_offset = -pad;

		out_index = j + w * (i + h * k);
		maxVal = -INFINITY;
		
		#pragma unroll 2
		for (l = 0; l < size; ++l) {
			#pragma unroll 2
			for (m = 0; m < size; ++m) {
				cur_h = h_offset + i*stride + l;
				cur_w = w_offset + j*stride + m;
				index = cur_w + in_w*(cur_h + in_h * k);
				valid = (cur_h >= 0 && cur_h < in_h &&
					cur_w >= 0 && cur_w < in_w);
				val = (valid != 0) ? input[index] : -INFINITY;
				maxVal = (val > maxVal) ? val : maxVal;
			}
		}
		output[out_index] = maxVal;
		idx = idx + 1;
	}
}
`
In a similar manned to this, I have re-implemented the rest of the kernels. The ported OpenCL version of the code on GTX 1080Ti is achieving a processing speed of ~147 fps. On a AMD RX580, I measured the speed to be ~60fps.

This is still lower compared to CUDA version of YOLO for tiny-yolo.cfg on GTX 1080 Ti as the version in this repo is achieving ~167fps. (roughly a 20fps gap between CUDA and my OpenCL port). I shall tidy up the OpenCL ported code and share it soon. thnx
