### ISSUE TITLE
It doesn't make with Debug=1

### ISSUE THREAD

**Issue by eonia89** [AlexeyAB/darknet#2162]
I am having memory leak myself and trying to figure out where it is.
Having tried it, I noticed that there is a way of finding where it exactly leaked...so I gave it -g option simply by setting Debug to 1.

Now, I cannot make it. May I get some help?!

**Comment by eonia89** [comment]
I have not got any explanation. Is it due to OpenCV? I can clearly see the label "Bug" but what do you mean by that?

**Comment by eonia89** [comment]
To someone that is suffering from the same issue, have a look at the first answer!

https://stackoverflow.com/questions/42918747/yolo-c-compilation-failure-with-debug-1/46808785#46808785

**Comment by AlexeyAB** [comment]
@eonia89 Compiling with `DEBUG=1` is fixed: https://github.com/AlexeyAB/darknet/commit/ce2e0eff009653e207df34f83fa6259a39f6fe84
