### ISSUE TITLE
how to dont processing  predictions.png ,only text result?  

### ISSUE THREAD

**Issue by ericwang321** [AlexeyAB/darknet#2163]
ubuntu 16.04 python 2.7+no gpu
when run
`./darknet detector test cfg/coco.data  cfg/yolov3.cfg yolov3.weights -dont_show < r1.txt > out1.txt`

darknet  output  result txt file   ，also output predictions.png .

> how to change the src code (image.c) to  dont output  predictions.png ? 
This processing will speed up processing efficiency

thanks for any suggestion.

**Comment by AlexeyAB** [comment]
Comment this line: https://github.com/AlexeyAB/darknet/blob/fd0df9297c86a272f0bf0841291bc4565e90a7cd/src/detector.c#L1285

**Comment by ericwang321** [comment]
it  works.thanks @AlexeyAB
