### ISSUE TITLE
Error loading network with libdarknet.so

### ISSUE THREAD

**Issue by nicolasCruzW21** [AlexeyAB/darknet#2166]
Hello,
I'm using the generated libdarknet.so in one of my projects. However when I load the network there is a mismatch between the .cfg and the defined network.

Here is the relevant part of the cfg.

[net]
# Testing
batch=1
subdivisions=1

width=608
height=608
channels=3
momentum=0.9

Here is part of the data printed while running parse_network_cfg_custom:

layer     filters    size              input                output
   0 conv     32  3 x 3 / 1   608 x 608 x   3   ->   608 x 608 x  32 0.639 BF
   1 conv     64  3 x 3 / 2   608 x 608 x  32   ->   304 x 304 x  64 3.407 BF
   2 conv     32  1 x 1 / 1   304 x 304 x  64   ->   304 x 304 x  32 0.379 BF

So far so good, however when i acces the network and print the values of the input dimensions I get the following:

net.w=608
net.h=0
net.c=608
This results in a segmentation fault later in the program. I got this results by using the current version of the repo. I tested it with an older commit and got:
net.w=608
net.h=3
net.c=1216

I also tested using pjreddie's version of darknet and the program runs fine, the dimensions are correct and the program finishes as expected.

To load the network I followed the procedure used in detector.c
Do you have any tips that could help me?

Thank you very much

**Comment by AlexeyAB** [comment]
@nicolasCruzW21 Hi,

* Do you use your own C, C++ or Python program?

* Do you use the latest version of this repo?

* What function do you use to get net.w / h / c ?

* Can you successfully use this command? https://github.com/AlexeyAB/darknet#how-to-compile-on-linux
`LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./uselib data/coco.names cfg/yolov3.cfg yolov3.weights test.mp4`

**Comment by nicolasCruzW21** [comment]
Do you use your own C, C++ or Python program?
-Yes, I use a C++ program.
Do you use the latest version of this repo?
-Yes I do.
What function do you use to get net.w / h / c ?
-hmmm
	  std::cout << net->w << std::endl;
	  std::cout << net->h << std::endl;
	  std::cout << net->c << std::endl;
XD not very elegant I know

Can you successfully use this command?
Yes, everything runs fine with that. I'm guessing it's a mistake on my program, but I don't known what i'm doing wrong.

Here is the output.

Total BFLOPS 139.481 
Loading weights from yolov3Blue_99000.weights...
 seen 64 
Done!
object names loaded 
input image or video filename:  Time: 0.0889696 sec 
b - obj_id = 1,  x = 789, y = 195, w = 378, h = 252, prob = 0.56
b - obj_id = 1,  x = 985, y = 664, w = 353, h = 223, prob = 0.472
b - obj_id = 1,  x = 1016, y = 419, w = 347, h = 216, prob = 0.217

Thank you for your kick reply!

**Comment by nicolasCruzW21** [comment]
I solved it, it was an error on my program. Thank you for your help!

(For those who have a similar error ...
Be carefull with the definitions on darknet.h, you may have forgotten a parameter if you modified something.)
