### ISSUE TITLE
Google Colab training issue

### ISSUE THREAD

**Issue by GeorgiiVdovychenko** [AlexeyAB/darknet#2167]
Hi,
I'm trying to train YOLO v3 using Google Colab but having a strange issue without any problem report, just: " ^C". Any suggestion where to look?

I've made all preparations describe in the readme. 
The pictures are fairly large - 4000x2000, maybe this is what makes trouble?

```
Total BFLOPS 65.297 
Loading weights from /content/mydrive/WORK/barcode/yolo/backup_v3/darknet53.conv.74...
 seen 64 
Done!
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Resizing
320 x 320 
^C
```

**Comment by AlexeyAB** [comment]
@GeorgiiVdovychenko Hi,

* What command do you use for training?

* What params do you use in the Makefie?

* Do other features work fine?

**Comment by GeorgiiVdovychenko** [comment]
@AlexeyAB Thanks for a fast reply!
command:
1)!./darknet detector train yolov3-labels_two.data yolov3-labels_two.cfg darknet53.conv.74
2)Haven't changed the makefile because wanted to run it on CPU first to be sure that everything works.
3)You mean other functions? Haven`t checked. It worked well with a fork from pjreddie/darknet with tiny yolo, but fails with yolo3 both your and pjreddies' version.

**Comment by AlexeyAB** [comment]
Training on CPU isn't well tested currently. So try to train by using GPU.

**Comment by GeorgiiVdovychenko** [comment]
> Training on CPU isn't well tested currently. So try to train by using GPU.

Hi once again Alex. Just wanted to share, that my problem "^C" error was due to low GPU memory and increasing the number of subdivisions helped.

**Comment by knyati** [comment]
hey i am getting similar problem on colab but after all layers are shown. i tried increasing the subdivisions in cfg . i tried decreasing it as well but it is still stuck there. i am using the command
!./darknet detector train data/people_1.data cfg/yolov3-obj.cfg darknet53.conv.74 -map
any idea/suggestion would be appreciated.
![pic2](https://user-images.githubusercontent.com/32821166/62104740-0772b880-b2be-11e9-95dc-5ecb810d9f3e.png)

**Comment by GeorgiiVdovychenko** [comment]
In my case a mistake was in image resolution I've used 2000x4000 images and
had this error. After resizing it to 800x600 the problem has gone.

вт, 30 лип. 2019 р., 09:06 користувач knyati <notifications@github.com>
пише:

**Comment by knyati** [comment]
I have images of different sizes some of them are 1024x632 most of them are of the sizes near to this.

**Comment by GeorgiiVdovychenko** [comment]
Well, I suggest reducing the img size or cutting it and procesing tiles.

чт, 1 серп. 2019 р., 14:29 користувач knyati <notifications@github.com>
пише:

**Comment by knyati** [comment]
Doesn't yolo itself resizes the input images, i read it somewhere that we do not need to resize images by ourselves as it is already included in yolo code.

**Comment by GeorgiiVdovychenko** [comment]
Of cause it does, but there could be memory issues or something.

пт, 2 серп. 2019 р., 21:31 користувач knyati <notifications@github.com>
пише:
