### ISSUE TITLE
Error after training exactly 100 epochs

### ISSUE THREAD

**Issue by maxwack** [AlexeyAB/darknet#2169]
Hello,

I used a previous version of your program which was working well (from ～july 2018) and decided to update it with the latest sources (January 2019).

Now when I try to train with my custom data set, I have an error after exactly 100 epochs saying :
→"OpenCV Error: Insufficient memory (Overflow for imageSize) in cvInitImageHeader"
which I did not have with the previous version of the sources.

I set Batch: 64 and subdivision: 32 and 64 but none of this worked. 

Is there anything I can do ? Should I stick with the previous version of the sources?
I use CUDA 10 and openCV 3.4.
Command : darknet.exe detector train data/object.data yolo_object.cfg darknet53.conv.74

Thank you for your help.

**Comment by Doubiiu** [comment]
!! I have the same problem! (But I don't have the problem of version. I just clone all codes from github)
OS: Windows
I want to train with my custom data set.
ERROR (exactly after 100 iterations):
OpenCV Error: Insufficient memory (Overflow for imageSize) in cvInitImageHeader, file C:\xxxxxxxxxx\opencv\modules\core\src\array.cpp, line 2971
And the line 2971 in array.cpp file is:
`image->imageSize = (int) imageSize_tmp`
`if( (int64)image->imageSize != imageSize_tmp )`
`CV_Error(  CV_StsNoMem, "Overflow for imageSize ");`

**Comment by AlexeyAB** [comment]
@Doubiiu @maxwack 
Try to update your code from github.

I just fixed it: https://github.com/AlexeyAB/darknet/commit/97038fefa63b9b14c0b2fd0c4f1b382db7b43e8c#diff-d63433b66e54cd65ded01be20041119cR813

**Comment by Doubiiu** [comment]
Thanks a lot😁

**Comment by maxwack** [comment]
Perfect ! 

Thank you. 👍
