### ISSUE TITLE
darknet.py fails to load DLL's

### ISSUE THREAD

**Issue by BGA3** [AlexeyAB/darknet#2180]
Hi,
When running darknet.py from Master, I get errors when loading DLL's: 
exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/GIT/darknet/darknet.py", line 110, in <module>
    lib = CDLL(winGPUdll, RTLD_GLOBAL)

  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: [WinError 126] The specified module could not be found

I simply dont know what is wrong. I build both the noGPU- and GPU DLL, and placed in darknet root dir.

set up:
Windows 10 64bit, python 3.6.7. in Spyder/Anaconda

I hope someone can help me.

**Comment by BGA3** [comment]
More info: I build the dlls using VS2017, cuda 10.0, cudnn_half and OpenCV

**Comment by AlexeyAB** [comment]
@BGA3 Hi,

Leave yolo_cpp_dll.dll in the `darknet\build\darknet\x64` and run this python script: `darknet\build\darknet\x64\darknet.py`

**Comment by BGA3** [comment]
Lol, ofc. Im stupid.

Thanks for the support!
