### ISSUE TITLE
problems while running two darknet.exe  at the same time

### ISSUE THREAD

**Issue by goodtogood** [AlexeyAB/darknet#2184]
I have two RTX2070 , two cfg files are almost the same except different class num on different samples.

darknet works well when training separately using one GPU

but if start one by one using one GPU (-gpus 0 and -gpus 1), 

the second darknet always stopped with message below,

> CUDA Error: out of memory: Not enough space

actually the second GPU is nearly free.

the code was based on this [commit  Jan 4, 2019 ] (https://github.com/AlexeyAB/darknet/commit/29f509e2b72d61300d47bc211ab1f24c2acb454a)

```
darknet detector train ./obj.data ./yolov3_obj.cfg ./darknet53.conv.74 -gpus 0

darknet detector train ./obj_2.data ./yolov3_obj_2.cfg ./darknet53.conv.74 -gpus 1
```

**Comment by AlexeyAB** [comment]
@goodtogood Hi,

**I can't reproduce your bug.**

Try to use **random=0** and show me screenshot of memory usage.

----

I used default yolov3-tiny.cfg with `batch=64 subdivisions=16 random=0` to use static size of GPU-RAM.

I used:
* Linux Debian 8.2 x64
* CUDA 9.1
* cuDNN 7.1.3
* OpenCV 3.3.0
* nVidia Driver 410.78

Used commands in 2 separate terminals to run training on GPU-1 and GPU-2:
1. `./darknet detector train ./cfg/coco.data cfg/yolov3-tiny.cfg -gpus 1 -dont_show`
2. `./darknet detector train ./cfg/coco.data cfg/yolov3-tiny.cfg -gpus 2 -dont_show`

And used commands in 3 separate terminals to get GPU-RAM Used on GPU-0, GPU-1 and GPU-2:
1. `while true; do nvidia-smi -q -i 0 | grep Used | head -n 1; done;`
2. `while true; do nvidia-smi -q -i 1 | grep Used | head -n 1; done;`
3. `while true; do nvidia-smi -q -i 2 | grep Used | head -n 1; done;`

As you see it uses GPU-RAM on GPU-1 and GPU-2, but it doesn't use RAM on GPU-0.

![image](https://user-images.githubusercontent.com/4096485/51063255-3cae0680-160b-11e9-9aa2-e6b222f2afd3.png)

**Comment by goodtogood** [comment]
Hi @AlexeyAB 

I was running darknet on windows，cuda10 cudnn 7.1.4

I thought I found why you succeeded in running multi darknet at the same time.

You can try it again when training some deeper network ( yolov3 ,yolov3_spp, etc.) firstly ,

make sure the first GPU memory usage is High and then start training the second one .

I also succeeded in starting two darknet (yolov3-tiny.cfg) at the same time using different GPU

but If I start training  yolov3-obj.cfg  using GPU 0 (waiting memory usage is 80-90%) , 

then start training another yolov3-obj.cfg  using GPU 1,

the second darknet always stopped with message, 

![error](https://user-images.githubusercontent.com/10088733/51075177-2f545300-16c3-11e9-8d00-1345352e6a69.jpg)

**Comment by AlexeyAB** [comment]
@goodtogood Hi,

Ok. I undrstand, so there is issue only when 1st Darknet-instance uses GPU-0 with memory usage 80-90%.


> but If I start training yolov3-obj.cfg using GPU 0 (waiting memory usage is 80-90%) ,then start training another yolov3-obj.cfg using GPU 1, the second darknet always stopped with message,

1. But if you run "yolov3-obj.cfg using GPU 1" when GPU-0 memory usage lower than 80%, and if were able to successfully launch both 2 Darknet instances on GPU-0 and GPU-1, then will there be an error later?

2. Try to compile Darknet without CUDNN, then will you get this error?
    open `\darknet.sln` -> (right click on project) -> properties -> C/C++ -> Preprocessor -> Preprocessor Definitions, and remove this: `CUDNN;`

**Comment by goodtogood** [comment]
Hi, @AlexeyAB 

- I tried , If I was able to run second darknet on  GPU-1 successfully ,  It can keep running well.

- If  CUDNN is disabled,  there's no problem.

I found something weird.   I have two GPUs  and memory is 8G. 

supposing that  first darknet was launched successfully  and kept running,

Let's say It allocated 5000 MB memory of GPU-0,  then If  second darknet needs 3200 MB

memory (GPU-1 specifyed),  It failed at the beginning of launching with message

`CUDA Error: out of memory: Not enough space`

If the second darknet just needs 2000MB, It could be launched successfully and kept running well on GPU-1.

It seemed that the second darknet always checks GPU-0 status  firstly when  launched.


![darknet2](https://user-images.githubusercontent.com/10088733/51424711-c57d0180-1c0c-11e9-9051-eceb15959919.gif)

**Comment by AlexeyAB** [comment]
@goodtogood Hi,

Can you rename your cfg file to txt-file and attach to your message?

> If CUDNN is disabled, there's no problem.

It looks like a problem in the cuDNN. I will think how to solve it.

> I tried , If I was able to run second darknet on GPU-1 successfully , It can keep running well.

This is the way how it can be solved currently.

----

> I also tried the python wrapper , same problem . the python code was based on darknet_video.py,

Does darknet_video.py causes CUDA Out of memory for set_gpu(1) only when CUDNN=1? And works successfully when CUDNN=0?

**Comment by goodtogood** [comment]
Hi, @AlexeyAB 

I tested a lot, even if  darknet was compiled without CUDNN,

It's not every time we can lanuch two darknet on diferent GPU separately.

It's same cfg && same samples, please refer to attached gif && txt for details.

If I start one darknet_nocudnn on GPU-0 successfully, then start python using GPU-1

`python darknet_video_nocudnn.py `

It might be possible the darknet_video_nocudnn.py stopped with message

> CUDA Error: out of memory: No error

you can see attaeched  error_darknet_video.py_nocudnn.txt for details.

[s_300_m3.cfg.txt](https://github.com/AlexeyAB/darknet/files/2775722/s_300_m3.cfg.txt)

[error_darknet_gpu_nocudnn.txt](https://github.com/AlexeyAB/darknet/files/2775723/error_darknet_gpu_nocudnn.txt)

[error_darknet_video.py_nocudnn.txt](https://github.com/AlexeyAB/darknet/files/2775724/error_darknet_video.py_nocudnn.txt)


![darknet4](https://user-images.githubusercontent.com/10088733/51429295-3b528e80-1c48-11e9-981b-80877683c409.gif)

**Comment by AlexeyAB** [comment]
@goodtogood Hi,

Thank you for very informative info.
I tested your cfg-file on the RTX 2070.

Darknet randomly resizes network for each 10 iterations if is used `random=1`, so higher resolution requires more GPU-RAM.
So, on your video, it resized network to size for each launch: 
576x576
544x544
608x608
768x768 - for `batch=64 subdivisions=32` it requires more than 8 GB GPU-RAM  that is on the RTX 2070

I added fix, for the first iteration will be used the maximum network resolution: https://github.com/AlexeyAB/darknet/commit/6e99e852ffce7d6cf9e9ec427ff3acd003cc8d5b
So it will cause CUDA Out of memory at the begining each time if there isn't enogh GPU-RAM for this network resolution.
Try to update your code from GitHub.

----

But does this issue is still occur only when `CUDNN=1` ? https://github.com/AlexeyAB/darknet/issues/2184#issuecomment-453757487

**Comment by goodtogood** [comment]
Hi, @AlexeyAB 

I made one mistake, 
I forgot modifying the s_300_m3.cfg before starting ScreenToGif.

```
batch=64
subdivisions=64
width=608
height=608
```

the real cfg should be like the attached  **s_300_m3_608_64_64.cfg.txt**  below

[s_300_m3_608_64_64.cfg.txt](https://github.com/AlexeyAB/darknet/files/2776297/s_300_m3_608_64_64.cfg.txt)

If I was using  512\*512,  768\*768 shouldn't be shown up.

[float random_val = rand_scale(1.4);    // *x or /x](https://github.com/AlexeyAB/darknet/blob/master/src/detector.c#L180)

I made some new tests using this cfg.  firstly I start one darknet on GPU-0 and keep it running.

(after start and stop some times) the size resized is  832*832.  memory allocated is about 6003MB.  

see attached image below for details .

```
darknet_gpu_nocudnn  detector train ./s_300_m3.data ./s_300_m3_608_64_64.cfg  -gpus 0 -dont_show
```

![darknet_gpu_nocudnn_608_64_64_832x832_gpu_0_succ](https://user-images.githubusercontent.com/10088733/51436167-e738c000-1cc2-11e9-8fb3-dbe964b461af.png)


then I start the second darknet on GPU-1, If the size resized is smaller than 768*768,

It can be lanuched successfully and keep running.  once the size reached 768*768

the OOM error would be displayed . see image below.

```
darknet_gpu_nocudnn  detector train ./s_300_m3.data ./s_300_m3_608_64_64.cfg  -gpus 1 -dont_show
```

![darknet_gpu_nocudnn_608_64_64_768x768_gpu_1_fail](https://user-images.githubusercontent.com/10088733/51436278-25cf7a00-1cc5-11e9-96d5-67e4dd652ed7.png)



**I stop the first darknet** and run darknet on GPU-1 only,  (after start and stop some times) 

even the size reached 768*768 or 832*832 , It can be lanuched successfully and keep running.

![darknet_gpu_nocudnn_608_64_64_832x832_gpu_1_succ](https://user-images.githubusercontent.com/10088733/51436319-eb1a1180-1cc5-11e9-9b7a-35ff8f5d7467.png)

![darknet_gpu_nocudnn_608_64_64_768x768_gpu_1_succ](https://user-images.githubusercontent.com/10088733/51436322-f3724c80-1cc5-11e9-8d78-aae5efc96113.png)

**Comment by goodtogood** [comment]
Hi, @AlexeyAB 

I updated the code to commit on [Jan 21, 2019 ](https://github.com/AlexeyAB/darknet/commit/81f7fc2c7bbddb79b5c87b5ab88fedf98f2b9963)

It still has the problem.

I have another question, please give me some advice.

I want to train a new model based on yolov3_5l.cfg.  the network size is 608*608,

I recaculated anchors ( 25 ) on new samples, details as follows,

```
`16, 20,  15, 25,  19, 24,  22, 22,  19, 29,  22, 27,  23, 31,  27, 29,  23, 36,  26, 34,  27, 39,  31, 36,  30, 44,  41, 33,  33, 41,  34, 48,  39, 46,  38, 55,  44, 57,  49, 62,  57, 74`

currently anchors were splited into five equally  as follows,

[yolo]
mask = 20,21,22,23,24
anchors = 14, 18,  14, 23,  18, 21,  17, 24,  22, 22,  20, 25,  18, 29,  21, 29,  24, 27,  23, 31,  22, 36,  30, 26,  28, 32,  25, 35,  28, 37,  31, 36,  28, 41,  39, 33,  33, 41,  31, 46,  35, 50,  39, 46,  40, 55,  47, 60,  55, 71



[yolo]
mask = 15,16,17,18,19
anchors = 14, 18,  14, 23,  18, 21,  17, 24,  22, 22,  20, 25,  18, 29,  21, 29,  24, 27,  23, 31,  22, 36,  30, 26,  28, 32,  25, 35,  28, 37,  31, 36,  28, 41,  39, 33,  33, 41,  31, 46,  35, 50,  39, 46,  40, 55,  47, 60,  55, 71



[yolo]
mask = 10,11,12,13,14
anchors = 14, 18,  14, 23,  18, 21,  17, 24,  22, 22,  20, 25,  18, 29,  21, 29,  24, 27,  23, 31,  22, 36,  30, 26,  28, 32,  25, 35,  28, 37,  31, 36,  28, 41,  39, 33,  33, 41,  31, 46,  35, 50,  39, 46,  40, 55,  47, 60,  55, 71



[yolo]
mask = 5,6,7,8,9
anchors = 14, 18,  14, 23,  18, 21,  17, 24,  22, 22,  20, 25,  18, 29,  21, 29,  24, 27,  23, 31,  22, 36,  30, 26,  28, 32,  25, 35,  28, 37,  31, 36,  28, 41,  39, 33,  33, 41,  31, 46,  35, 50,  39, 46,  40, 55,  47, 60,  55, 71



[yolo]
mask = 0,1,2,3,4
anchors = 14, 18,  14, 23,  18, 21,  17, 24,  22, 22,  20, 25,  18, 29,  21, 29,  24, 27,  23, 31,  22, 36,  30, 26,  28, 32,  25, 35,  28, 37,  31, 36,  28, 41,  39, 33,  33, 41,  31, 46,  35, 50,  39, 46,  40, 55,  47, 60,  55, 71
```

after running about 3k iters.  I tested and found the result was bad.

there must be something I missed, please point it out where I was wrong?

thanks.

**Comment by goodtogood** [comment]
this is the output of model trained

```
layer     filters    size              input                output
   0 conv     32  3 x 3 / 1   608 x 608 x   3   ->   608 x 608 x  32 0.639 BF
   1 conv     64  3 x 3 / 2   608 x 608 x  32   ->   304 x 304 x  64 3.407 BF
   2 conv     32  1 x 1 / 1   304 x 304 x  64   ->   304 x 304 x  32 0.379 BF
   3 conv     64  3 x 3 / 1   304 x 304 x  32   ->   304 x 304 x  64 3.407 BF
   4 Shortcut Layer: 1
   5 conv    128  3 x 3 / 2   304 x 304 x  64   ->   152 x 152 x 128 3.407 BF
   6 conv     64  1 x 1 / 1   152 x 152 x 128   ->   152 x 152 x  64 0.379 BF
   7 conv    128  3 x 3 / 1   152 x 152 x  64   ->   152 x 152 x 128 3.407 BF
   8 Shortcut Layer: 5
   9 conv     64  1 x 1 / 1   152 x 152 x 128   ->   152 x 152 x  64 0.379 BF
  10 conv    128  3 x 3 / 1   152 x 152 x  64   ->   152 x 152 x 128 3.407 BF
  11 Shortcut Layer: 8
  12 conv    256  3 x 3 / 2   152 x 152 x 128   ->    76 x  76 x 256 3.407 BF
  13 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128 0.379 BF
  14 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256 3.407 BF
  15 Shortcut Layer: 12
  16 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128 0.379 BF
  17 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256 3.407 BF
  18 Shortcut Layer: 15
  19 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128 0.379 BF
  20 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256 3.407 BF
  21 Shortcut Layer: 18
  22 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128 0.379 BF
  23 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256 3.407 BF
  24 Shortcut Layer: 21
  25 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128 0.379 BF
  26 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256 3.407 BF
  27 Shortcut Layer: 24
  28 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128 0.379 BF
  29 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256 3.407 BF
  30 Shortcut Layer: 27
  31 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128 0.379 BF
  32 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256 3.407 BF
  33 Shortcut Layer: 30
  34 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128 0.379 BF
  35 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256 3.407 BF
  36 Shortcut Layer: 33
  37 conv    512  3 x 3 / 2    76 x  76 x 256   ->    38 x  38 x 512 3.407 BF
  38 conv    256  1 x 1 / 1    38 x  38 x 512   ->    38 x  38 x 256 0.379 BF
  39 conv    512  3 x 3 / 1    38 x  38 x 256   ->    38 x  38 x 512 3.407 BF
  40 Shortcut Layer: 37
  41 conv    256  1 x 1 / 1    38 x  38 x 512   ->    38 x  38 x 256 0.379 BF
  42 conv    512  3 x 3 / 1    38 x  38 x 256   ->    38 x  38 x 512 3.407 BF
  43 Shortcut Layer: 40
  44 conv    256  1 x 1 / 1    38 x  38 x 512   ->    38 x  38 x 256 0.379 BF
  45 conv    512  3 x 3 / 1    38 x  38 x 256   ->    38 x  38 x 512 3.407 BF
  46 Shortcut Layer: 43
  47 conv    256  1 x 1 / 1    38 x  38 x 512   ->    38 x  38 x 256 0.379 BF
  48 conv    512  3 x 3 / 1    38 x  38 x 256   ->    38 x  38 x 512 3.407 BF
  49 Shortcut Layer: 46
  50 conv    256  1 x 1 / 1    38 x  38 x 512   ->    38 x  38 x 256 0.379 BF
  51 conv    512  3 x 3 / 1    38 x  38 x 256   ->    38 x  38 x 512 3.407 BF
  52 Shortcut Layer: 49
  53 conv    256  1 x 1 / 1    38 x  38 x 512   ->    38 x  38 x 256 0.379 BF
  54 conv    512  3 x 3 / 1    38 x  38 x 256   ->    38 x  38 x 512 3.407 BF
  55 Shortcut Layer: 52
  56 conv    256  1 x 1 / 1    38 x  38 x 512   ->    38 x  38 x 256 0.379 BF
  57 conv    512  3 x 3 / 1    38 x  38 x 256   ->    38 x  38 x 512 3.407 BF
  58 Shortcut Layer: 55
  59 conv    256  1 x 1 / 1    38 x  38 x 512   ->    38 x  38 x 256 0.379 BF
  60 conv    512  3 x 3 / 1    38 x  38 x 256   ->    38 x  38 x 512 3.407 BF
  61 Shortcut Layer: 58
  62 conv   1024  3 x 3 / 2    38 x  38 x 512   ->    19 x  19 x1024 3.407 BF
  63 conv    512  1 x 1 / 1    19 x  19 x1024   ->    19 x  19 x 512 0.379 BF
  64 conv   1024  3 x 3 / 1    19 x  19 x 512   ->    19 x  19 x1024 3.407 BF
  65 Shortcut Layer: 62
  66 conv    512  1 x 1 / 1    19 x  19 x1024   ->    19 x  19 x 512 0.379 BF
  67 conv   1024  3 x 3 / 1    19 x  19 x 512   ->    19 x  19 x1024 3.407 BF
  68 Shortcut Layer: 65
  69 conv    512  1 x 1 / 1    19 x  19 x1024   ->    19 x  19 x 512 0.379 BF
  70 conv   1024  3 x 3 / 1    19 x  19 x 512   ->    19 x  19 x1024 3.407 BF
  71 Shortcut Layer: 68
  72 conv    512  1 x 1 / 1    19 x  19 x1024   ->    19 x  19 x 512 0.379 BF
  73 conv   1024  3 x 3 / 1    19 x  19 x 512   ->    19 x  19 x1024 3.407 BF
  74 Shortcut Layer: 71
  75 conv    512  1 x 1 / 1    19 x  19 x1024   ->    19 x  19 x 512 0.379 BF
  76 conv   1024  3 x 3 / 1    19 x  19 x 512   ->    19 x  19 x1024 3.407 BF
  77 conv    512  1 x 1 / 1    19 x  19 x1024   ->    19 x  19 x 512 0.379 BF
  78 conv   1024  3 x 3 / 1    19 x  19 x 512   ->    19 x  19 x1024 3.407 BF
  79 conv    512  1 x 1 / 1    19 x  19 x1024   ->    19 x  19 x 512 0.379 BF
  80 conv   1024  3 x 3 / 1    19 x  19 x 512   ->    19 x  19 x1024 3.407 BF
  81 conv     30  1 x 1 / 1    19 x  19 x1024   ->    19 x  19 x  30 0.022 BF
  82 yolo
  83 route  79
  84 conv    256  1 x 1 / 1    19 x  19 x 512   ->    19 x  19 x 256 0.095 BF
  85 upsample            2x    19 x  19 x 256   ->    38 x  38 x 256
  86 route  85 61
  87 conv    256  1 x 1 / 1    38 x  38 x 768   ->    38 x  38 x 256 0.568 BF
  88 conv    512  3 x 3 / 1    38 x  38 x 256   ->    38 x  38 x 512 3.407 BF
  89 conv    256  1 x 1 / 1    38 x  38 x 512   ->    38 x  38 x 256 0.379 BF
  90 conv    512  3 x 3 / 1    38 x  38 x 256   ->    38 x  38 x 512 3.407 BF
  91 conv    256  1 x 1 / 1    38 x  38 x 512   ->    38 x  38 x 256 0.379 BF
  92 conv    512  3 x 3 / 1    38 x  38 x 256   ->    38 x  38 x 512 3.407 BF
  93 conv     30  1 x 1 / 1    38 x  38 x 512   ->    38 x  38 x  30 0.044 BF
  94 yolo
  95 route  91
  96 conv    128  1 x 1 / 1    38 x  38 x 256   ->    38 x  38 x 128 0.095 BF
  97 upsample            2x    38 x  38 x 128   ->    76 x  76 x 128
  98 route  97 36
  99 conv    128  1 x 1 / 1    76 x  76 x 384   ->    76 x  76 x 128 0.568 BF
 100 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256 3.407 BF
 101 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128 0.379 BF
 102 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256 3.407 BF
 103 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128 0.379 BF
 104 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256 3.407 BF
 105 conv     30  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x  30 0.089 BF
 106 yolo
 107 route  103
 108 conv    128  1 x 1 / 1    76 x  76 x 128   ->    76 x  76 x 128 0.189 BF
 109 upsample            2x    76 x  76 x 128   ->   152 x 152 x 128
 110 route  109 11
 111 conv     64  1 x 1 / 1   152 x 152 x 256   ->   152 x 152 x  64 0.757 BF
 112 conv    128  3 x 3 / 1   152 x 152 x  64   ->   152 x 152 x 128 3.407 BF
 113 conv     64  1 x 1 / 1   152 x 152 x 128   ->   152 x 152 x  64 0.379 BF
 114 conv    128  3 x 3 / 1   152 x 152 x  64   ->   152 x 152 x 128 3.407 BF
 115 conv     64  1 x 1 / 1   152 x 152 x 128   ->   152 x 152 x  64 0.379 BF
 116 conv    128  3 x 3 / 1   152 x 152 x  64   ->   152 x 152 x 128 3.407 BF
 117 conv     30  1 x 1 / 1   152 x 152 x 128   ->   152 x 152 x  30 0.177 BF
 118 yolo
 119 route  115
 120 conv    128  1 x 1 / 1   152 x 152 x  64   ->   152 x 152 x 128 0.379 BF
 121 upsample            2x   152 x 152 x 128   ->   304 x 304 x 128
 122 route  121 4
 123 conv     32  1 x 1 / 1   304 x 304 x 192   ->   304 x 304 x  32 1.136 BF
 124 conv     64  3 x 3 / 1   304 x 304 x  32   ->   304 x 304 x  64 3.407 BF
 125 conv     32  1 x 1 / 1   304 x 304 x  64   ->   304 x 304 x  32 0.379 BF
 126 conv     64  3 x 3 / 1   304 x 304 x  32   ->   304 x 304 x  64 3.407 BF
 127 conv     32  1 x 1 / 1   304 x 304 x  64   ->   304 x 304 x  32 0.379 BF
 128 conv     64  3 x 3 / 1   304 x 304 x  32   ->   304 x 304 x  64 3.407 BF
 129 conv     30  1 x 1 / 1   304 x 304 x  64   ->   304 x 304 x  30 0.355 BF
 130 yolo
```
