### ISSUE TITLE
continue training with different images

### ISSUE THREAD

**Issue by receptanilcengiz** [AlexeyAB/darknet#2189]
Hi @AlexeyAB 
I am currently training dataset using darknet yolov3. I wonder that: if I stop it after 50k iteration, and add some images more or replace totally new images, may I continue from last checkpoint? or I should start from stratch if I add new images?

Another question: after some training if I add some class more, may I continue? without lost current class prediction

I just want to start training model but still going on labelling. in this duration, may be need to add new objects, I dont want to loss current training and add more class or training on different images to increase accuracy

so am I going to start from stratch? or continue?

**Comment by AlexeyAB** [comment]
> I am currently training dataset using darknet yolov3. I wonder that: if I stop it after 50k iteration, and add some images more or replace totally new images, may I continue from last checkpoint? or I should start from stratch if I add new images?

* You can continue
    * if you use only new images, then network will gradually forget old images
    * if you use new+old images, this is normal

----

> Another question: after some training if I add some class more, may I continue? without lost current class prediction

If you add or change classes - you should train from the begining.
