### ISSUE TITLE
 non-person (for example ,chair/Tv monitor) still also output sometimes after #2109

### ISSUE THREAD

**Issue by ericwang321** [AlexeyAB/darknet#2193]
ubuntu 16.04 python 2.7+no gpu
      The previously referenced method   #2109 , the problem that only identifies people has been solved.

     

>  _but recently it has been found that **non-person** (for example ,chair/Tv monitor) will also output sometimes._

1. What else code needs to be changed?
2. Whether it is related to errors in the make?

thanks for any suggestion.

attachment is below 
1.the command :
```
./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights  ipc1.jpg
1.jpg: Predicted in 0.000000 milli-seconds.
person: 59%
person: 79%
person: 32%
chair: 41%
```

2.my darknet cfg file :

[yolov3.cfg.txt](https://github.com/AlexeyAB/darknet/files/2753937/yolov3.cfg.txt)

3.darknet make error log:
[darknet.make.error.log](https://github.com/AlexeyAB/darknet/files/2753932/darknet.make.error.log)

4.my coco.names 
```
person
bicycle
car
.....
```

5.my coco.data  
```
classes= 80
train  = /home/pjreddie/data/coco/trainvalno5k.txt
valid  = coco_testdev
#valid = data/coco_val_5k.list
names = data/coco.names
backup = /home/pjreddie/backup/
eval=coco
```

**Comment by AlexeyAB** [comment]
Just use the latest versions of this repository
and change your `coco.names` file to this:
```
person
dont_show bicycle
dont_show car
.....
```

**Comment by ericwang321** [comment]
it works . output only person without  the method of  change source code as #2109 .
 thanks @AlexeyAB 

> There is a small problem ：
> after git clone latest repository，output appears **0 miil-second**,
> how to change code （image.c)? 


```
Total BFLOPS 65.864 

 seen 64 
 Used FMA & AVX2 
 Used AVX 
data/person.jpg: Predicted in 0.000000 milli-seconds.
person: 100%

```

1. make error log 
`[make.error2.log](https://github.com/AlexeyAB/darknet/files/2762561/make.error2.log)`

2. Make option
```
GPU=0
CUDNN=0
CUDNN_HALF=0
OPENCV=0
AVX=1
OPENMP=1
LIBSO=1
```
