### ISSUE TITLE
how to select network model

### ISSUE THREAD

**Issue by duohappy** [AlexeyAB/darknet#2194]
Hi, AlexeyAB, I read the **README.md** many times, which is so helpful and amazing. Thank you! :+1:

As I know, the more categories I want to detect, the more complex network model I need to use. For example, I want to detect 80 classes in COCO dataset, simple network can not get satisfactory result, so I choose YOLOv3.

When I just want to detect 3 classes or 2 classes,  I also use YOLOv3. But, I am afraid that this complex network may cause **over fitting**.  I do not know if my idea is correct. Is there a **general rule** to choose network model?

> General rule - your training dataset should include such a set of relative sizes of objects that you want to detect:
> + train_network_width * train_obj_width / train_image_width ~= detection_network_width * detection_obj_width / detection_image_width
> + train_network_height * train_obj_height / train_image_height ~= detection_network_height * detection_obj_height / detection_image_height

**Comment by AlexeyAB** [comment]
@duohappy HI,

> As I know, the more categories I want to detect, the more complex network model I need to use. 

In general - yes. 
The more **different objects** you want to detect, the more complex network model should be used.

But you should take into account that **each: model of object, side, illimination, scale, each 15 grad** of the turn and inclination angles - these are **different objects** in terms of neural network.

So if you want to detect cars on the road from the stationary camera and if you see the cars from the same side, scale, angle and illimination - so there are only different models of cars - then it can require less complex model.

**Comment by duohappy** [comment]
> 
> 
> @duohappy HI,
> 
> > As I know, the more categories I want to detect, the more complex network model I need to use.
> 
> In general - yes.
> The more **different objects** you want to detect, the more complex network model should be used.
> 
> But you should take into account that **each: model of object, side, illimination, scale, each 30 grad** of the turn and inclination angles - these are **different objects** in terms of neural network.
> 
> So if you want to detect cars on the road from the stationary camera and if you see the cars from the same side, scale, angle and illimination - so there are only different models of cars - then it can require less complex model.

@AlexeyAB ,Thank you very much. Your reply is very clear, and I understand it more deeply.

I close this issue, :+1: :heart:
