### ISSUE TITLE
Training outputs meaning

### ISSUE THREAD

**Issue by kevin-apl** [AlexeyAB/darknet#2197]
Hello, 

I've checked out the links in here: https://github.com/pjreddie/darknet/issues/1307#issuecomment-449099912
But seems the meaning of "Class", "Obj", and "No obj" are still unclear. Have anyone figured these out yet?

Kevin

**Comment by PabloDIGITS** [comment]
Hello @kevin-apl , this is what I think

**Class:** is the mean of the probabilities of the true positives, i.e. a value of 0.931707 in this parameter means that the 93.17% of the objects detected in the corresponding subdivision belong to their correct classes.

**Obj**: The images are divided in a 13x13 mesh. To every cell of the mesh is applied a number of bounding boxes and everyone of them have a confindence, i.e. a value of 0.5621 in this parameter means that the boundix boxes that have a ground truth object in them, have a 56.21% of probalities of detecting it. High values of this parameter indicate that the training is going well.

**No obj**: The same idea that before. But now it refers to the locations where there is no object. This parameter should have low values if the training is going well.

That is mi what I know, but could be wrong. If so someone can correct me.

**Comment by kevin-apl** [comment]
Thanks for the detailed explanation, @PabloDIGITS 
Seems to make sense!
