### ISSUE TITLE
how to used caffemodel to predict via darknet

### ISSUE THREAD

**Issue by Cv9527** [AlexeyAB/darknet#22]
hi, AlexeyAB, how to convert caffemodel to darknet for face detection? if I use darknet to detect face, does darknet support multi-task training? Thank you

**Comment by AlexeyAB** [comment]
@Cv9527 Hi,

You can't use caffemodel with darknet. 

What do you mean about multi-task training? Yolo-darknet can detect multiple types of objects: https://www.youtube.com/watch?v=VOC3huqHrss

* You should train your own `.weights`-file on your image dataset: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects
* Or you can use already trained `weights`-files for Pascal VOC or MS COCO
    * VOC (256 MB): http://pjreddie.com/media/files/yolo-voc.weights
    * COCO (256 MB): http://pjreddie.com/media/files/yolo.weights

And see how to use it: https://github.com/AlexeyAB/darknet#how-to-use
