### ISSUE TITLE
set batch and subdivisions 

### ISSUE THREAD

**Issue by zhongjiejiang** [AlexeyAB/darknet#2201]
Hi AlexeyAB,

I have a limited GPU memory,  I got the out of memory when I set batch = 64 & subdivisions = 16,  it is ok when I set batch = 64 & subdivisions = 32 but slowly.

I want to know if I can set the "batch = 64 & subdivisions = 20"  or " batch = 66 & subdivisions = 22"? which will be send 3 images to the network each time?

thanks for you help
jason

**Comment by AlexeyAB** [comment]
@zhongjiejiang Hi,

> I want to know if I can set the "batch = 64 & subdivisions = 20" or " batch = 66 & subdivisions = 22"? which will be send 3 images to the network each time?

Yes, you can.

**Comment by AlexeyAB** [comment]
@phamngocthanhtrung Hi,

No.
Accuracy will ~the same.
Speed will decrese.

So you should increase subidivisons only if you don't have enough GPU-RAM.
