### ISSUE TITLE
multi detection simultaneously

### ISSUE THREAD

**Issue by receptanilcengiz** [AlexeyAB/darknet#2205]
Hi @AlexeyAB 

I am using cpp_dll. I have 6 camera on my system and I want to detect object from this cameras simultaneously. how can I achieve this? or at least, is it possible? 
or only way give images one by one?

**Comment by AlexeyAB** [comment]
@receptanilcengiz Hi,

* You can run 6 instances of `yolo_console_dll.exe` ... if your GPU has enough GPU-RAM.

* Or you can write your own cpp-file that will use one `Detector detector(cfg_file, weights_file);` object and feed it frames from alternately from 6 cameras one-by-one.

**Comment by receptanilcengiz** [comment]
I am writing in vs c# so I imported "yolo_cpp_dll.dll" so how can I create 6 instance?

**Comment by AlexeyAB** [comment]
> I am writing in vs c# so I imported "yolo_cpp_dll.dll" so how can I create 6 instance?

In this case just `init()` single instance of Detector, and feed it frames alternately from 6 cameras one-by-one, in your C# code.
