### ISSUE TITLE
Why am I running out of memory in the start?

### ISSUE THREAD

**Issue by univmalik** [AlexeyAB/darknet#2206]
Where am I going wrong?

layer     filters    size              input                output
   0 conv     32  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  32 0.299 BF
   1 CUDA Error: out of memory
CUDA Error: out of memory: No error

Does training image size matter. I am training on 3 categories, cats, cars and dogs.

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

> Note: if error Out of memory occurs then in .cfg-file you should increase subdivisions=16, 32 or 64

**Comment by univmalik** [comment]
`[net]
# Testing
batch=64
subdivisions=1
# Training
# batch=32
# subdivisions=64
height=416
width=416
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
burn_in=1000
max_batches = 80200
policy=steps
steps=40000,60000
scales=.1,.1

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky


#######

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[route]
layers=-9

[convolutional]
batch_normalize=1
size=1
stride=1
pad=1
filters=64
activation=leaky

[reorg]
stride=2

[route]
layers=-1,-4

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=125
activation=linear


[region]
anchors =  1.3221, 1.73145, 3.19275, 4.00944, 5.05587, 8.09892, 9.47112, 4.84053, 11.2364, 10.0071
bias_match=1
classes=20
coords=4
num=5
softmax=1
jitter=.3
rescore=1

object_scale=5
noobject_scale=1
class_scale=1
coord_scale=1

absolute=1
thresh = .6
random=1
`

**Comment by univmalik** [comment]
Above is my cfg_obj file. I use a GTX 1060 6 GB. It shouldn't be running out of memory

**Comment by univmalik** [comment]
Oh yes sorry, screwed up obj.cfg file... Filters

**Comment by AlexeyAB** [comment]
@univmalik 

> ```
> [net]
> # Testing
> batch=64
> subdivisions=1
> ```

You use `mini_batch = batch / subdivisions = 64/1 = 64`, it requires **26 GB GPU-RAM**.
You should use nVidia Tesla V100 with 32 GB GPU-RAM.

----

Read this first: https://github.com/AlexeyAB/darknet/issues/2206#issuecomment-454111250

**Comment by univmalik** [comment]
Yes, I actually am new to Python coming from Java. I actually changed the commented stuff :dancer:

**Comment by dreambit** [comment]
AlexeyAB, could you plz explain how to calc required memory during training? i mean having width, height, batch, subdivisions how to predict memory usage? not to have out of memory an nth iteration.

**Comment by AlexeyAB** [comment]
@dreambit I just run it and look at GPU-Z )
There is no simple way to calc required memory
It depends on model, batch/subdivisions, width x height, random=1, and some thing in the implementation.

**Comment by dreambit** [comment]
@AlexeyAB thanks for your help 👍 
we are running the training job on aws sagemaker, and it looks like the only way to find max network size that will fit into p2.xlarge is run it over and over again with different network size :)

**Comment by AlexeyAB** [comment]
@dreambit 

Also you can try to run training with random=0 and `width & height` 1.4x more than you will use. And if there is no Out of memory error, then you can use your original `width height` and random=1.

**Comment by dreambit** [comment]
Thanks for an advice 🥇

**Comment by univmalik** [comment]
Everything is working fine except it crashes when it has to show the graph. I have about 400 images for 3 categories. But to first test it, I am only providing it about 50. The folder contains 400, but the train.txt contains 50. Also do I have to put images in text.txt. Because you haven't written that in instructions. Thanks

Loading weights from darknet53.conv.74...
 seen 64
Done!
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
 If error occurs - run training with flag: -dont_show
Resizing
320 x 320
 try to allocate workspace = 1 * sizeof(float),  CUDA allocate done!
Loaded: 0.133007 seconds

**Comment by univmalik** [comment]
@AlexeyAB Write in main that cudnn64_7.dll has to be copied to x64 folder.
