### ISSUE TITLE
label of the bounding box and on-screen font

### ISSUE THREAD

**Issue by k00r** [AlexeyAB/darknet#2208]
Hello @AlexeyAB 

1)How can i turn off the coloured label of the bounding boxes? The thick part on top.
2)How can i change the colour of the class labels and make them thinner? The rendered text on the screen.

Have a nice day.

**Comment by AlexeyAB** [comment]
@k00r Hi

1. Comment these lines:
* https://github.com/AlexeyAB/darknet/blob/920d792a0c34c70c722caf1db23792e81e51af5b/src/image.c#L424
* https://github.com/AlexeyAB/darknet/blob/920d792a0c34c70c722caf1db23792e81e51af5b/src/image.c#L633

2. Change these lines:
* https://github.com/AlexeyAB/darknet/blob/920d792a0c34c70c722caf1db23792e81e51af5b/src/image.c#L360-L363
* https://github.com/AlexeyAB/darknet/blob/920d792a0c34c70c722caf1db23792e81e51af5b/src/image.c#L552-L555

**Comment by k00r** [comment]
Thank you so much
