### ISSUE TITLE
config yolov3-spp file for training for both small and large objects

### ISSUE THREAD

**Issue by zhongjiejiang** [AlexeyAB/darknet#2209]
Hi AlexeyAB,

I download the yolov3-spp.cfg from below link, and I have some question to trouble you.

1, I found that the batch=1 and subdivisons=1, is it special mean? Can I set the batch=63 and subdivsion=8?
2, can I recalculate anchors for dataset?  the smallest anchors of yolov3-spp is 10,13  and the smallest anchors of recalculate anchors is 22,39
3, how can it get he pre-train weight like as yolov3-tiny.conv.15 using command: darknet.exe partial? 

Thanks for you reply
Jason

for training for both small and large objects use modified models:
* Full-model: 5 yolo layers: https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov3_5l.cfg
* Tiny-model: 3 yolo layers: https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov3-tiny_3l.cfg
* Spatial-full-model: 3 yolo layers: https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov3-spp.cfg

**Comment by AlexeyAB** [comment]
@zhongjiejiang Hi

1. You can use any batch and subdivisions as you want. It will affect only on training.

2. Yes, you can recalculate anchors, do it as usual.

3. `darknet.exe partial cfg/yolov3-spp.cfg yolov3-spp.weights yolov3-spp.conv.81 81`
