### ISSUE TITLE
Save loss/map graph 

### ISSUE THREAD

**Issue by nsantavas** [AlexeyAB/darknet#2213]
Hi 

How could I save/update the loss/mAP graph during the training process, despite the store when the process reach the max batches?

**Comment by nsantavas** [comment]
where this files is saved, because I cannot find any `chart.png` file

**Comment by AlexeyAB** [comment]
Near with executable file `./darknet`.
* Do you use the latest version of Darknet?
* Did you compile Darknet with OPENCV=1 in Makefile?

**Comment by maikaa** [comment]
Hello, I've got the same problem. I am not the one who compiled darknet so I don't know if it was compiled with OPENCV=1 and I'm a beginner so I am a bit lost...

**Comment by AlexeyAB** [comment]
@maikaa 
If you use Linux, then you should compile exactly this repository https://github.com/AlexeyAB/darknet then you should set OPENCV=1 here: https://github.com/AlexeyAB/darknet/blob/cce34712f6928495f1fbc5d69332162fc23491b9/Makefile#L4
and compile Darknet by using `make`

**Comment by maikaa** [comment]
Thank you! I did it but it returned an error :
```
./src/image.c:637:16: error: incompatible type for argument 2 of ‘cvSet’
compilation terminated due to -Wfatal-errors.
Makefile:130: recipe for target 'obj/image.o' [failed]
make: *** [obj/image.o] Error 1
```

**Comment by saadyousuf45** [comment]
anyone solved it yet
