### ISSUE TITLE
Best Way to Re-Train a Network

### ISSUE THREAD

**Issue by daylanc** [AlexeyAB/darknet#2217]
Hello,

I'm not sure if this issue was previously addressed in a document or issue somewhere, but I wanted to know the best way (or proper) way to re-train a network. Currently, I've been constantly training my network, adding more images, and re-training it using the typical training command `./darknet detector train <path_to_data_file> <path_to_cfg_file> <path_to_pretrained_weights>` every iteration. I'm up to about 35k iterations and have "retrained" my network about 5 or 6 times. I just wanted to verify that this is the best or proper way to do this or should I just start the training from scratch? When re-training, are there some configurations I should modify? Should I add more images to the verify dataset (70%-train and 30%-verify, instead of 80%-train and 20%-verify)

On a side note, it seems like my network is learning what it needs to, I'm just wondering if this method of constantly re-training is okay, and is there something I should be doing to optimize what I'm doing.

Thanks!

**Comment by daylanc** [comment]
@AlexeyAB 

I did see that issue immediately after I posted this and it looks very similar to mine. I retrained the network 6 times because I keep updating the dataset. I'll start training, annotate about 100-200 more images, add them in, and start training again. I've done this 5-6 times so far. I'm using the same number of classes and always train with old and new images.

**Comment by AlexeyAB** [comment]
>  I'm using the same number of classes and always train with old and new images.

So you can continue train as many times as you want.
