### ISSUE TITLE
custom area detection

### ISSUE THREAD

**Issue by psxcoding** [AlexeyAB/darknet#2221]
Hello, goal is to track detected object f.e person in specific area in video. For example i put some shape like square and track if person is inside shape or outside.

On https://github.com/pjreddie/darknet/ i was able to put square like this: draw_box_width(display, 850, 344, 1100, 800, 6, 1, 1, 1);

question 1 : How to put custom shape/square on video ?
question 2: How to track person if he is in that shape?

![screenshot from 2019-01-16 16-16-15](https://user-images.githubusercontent.com/5319090/51254692-425c7100-19aa-11e9-99e2-3d2e2b4cda21.png)

**Comment by psxcoding** [comment]
@AlexeyAB any idea?

**Comment by dineshelavazhagan** [comment]
hi,
Did you find the solution?
Where do we define the area?
