### ISSUE TITLE
`fil` variable in `convolve_bin_gpu_kernel()`

### ISSUE THREAD

**Issue by alemelis** [AlexeyAB/darknet#2224]
Hello @AlexeyAB , looking at `convolve_bin_gpu_kernel()` in `im2col_kernels.cu`
https://github.com/AlexeyAB/darknet/blob/5343aa423563c107e0071b1427ad5defc27b56d2/src/im2col_kernels.cu#L2063

I noticed that the name `fil` is give to an integer variable
https://github.com/AlexeyAB/darknet/blob/5343aa423563c107e0071b1427ad5defc27b56d2/src/im2col_kernels.cu#L2081

and then to a loop index
https://github.com/AlexeyAB/darknet/blob/5343aa423563c107e0071b1427ad5defc27b56d2/src/im2col_kernels.cu#L2098

Afterward the index is referenced again
https://github.com/AlexeyAB/darknet/blob/5343aa423563c107e0071b1427ad5defc27b56d2/src/im2col_kernels.cu#L2109

Here, is its value supposed to be `max_fil` or the previously defined ` index2 / in_h`?

**Comment by AlexeyAB** [comment]
@alemelis Hi,

It is slow experimental function, just to play around.

Yes, I should have used 
```cpp
for (int new_fil = min_fil; new_fil <= max_fil; new_fil++) { 
     for (int s = threadIdx.x; s < weights_size; s += blockDim.x) { 
         //weights_shared[s + (new_fil - min_fil)*new_lda / 8] = ((uint8_t *)weights)[new_fil *new_lda / 8 + s]; 
         weights_shared[s + (new_fil - min_fil)*new_lda/32] = ((uint32_t *)weights)[new_fil *new_lda / 32 + s]; 
     } 
 } 
```
in this loop: https://github.com/AlexeyAB/darknet/blob/5343aa423563c107e0071b1427ad5defc27b56d2/src/im2col_kernels.cu#L2098-L2103

So these are different `fil` inside and outside the loop, but it works successfully: https://ideone.com/Bl41Fe


> Afterward the index is referenced again
> https://github.com/AlexeyAB/darknet/blob/5343aa423563c107e0071b1427ad5defc27b56d2/src/im2col_kernels.cu#L2109
> 
> Here, is its value supposed to be `max_fil` or the previously defined ` index2 / in_h`?

Here will be `fil = index2 / in_h;`
https://ideone.com/Bl41Fe

**Comment by alemelis** [comment]
I see, thanks for the reply! and since the function is not used further in the code, I'm not pushing any change.
