### ISSUE TITLE
Weights does not get saved during training !!

### ISSUE THREAD

**Issue by Rahul-Venugopal** [AlexeyAB/darknet#2227]
Hi ,
I was training on custom data-set following instruction per this fork and I observed that there are no weight files created in backup folder . Then I tried to change yolo.c in `'/YOLO_alexy/darknet/src/yolo.c'` as following 

> if((**i < 10 && i%2 == 0**) || (i%100==0) || (i < 1000 && i%100 == 0)){
>             char buff[256];
>             sprintf(buff, "%s/%s_%d.weights", backup_directory, base, i);
>             save_weights(net, buff);
>         }

and I ran make again as 

> make clean
> make 

Now I expect it to save weights in backup directory after every **2** iteration till 10th iteration and then after every **100** iteration till 1000 .
But when I check backup folder after 10th iteration , unfortunately I am not finding any backup files created.

**Can anyone please help me to point out the mistake I am doing ?**

My `obj.data` looks like 

> classes= 3
> train  = /home/rahul/ActiveShuttle/YOLO_alexy/darknet/data/train_obj/train.txt
> valid  = /home/rahul/ActiveShuttle/YOLO_alexy/darknet/data/train_obj/train.txt
> names = data/obj.names
> backup = /home/rahul/ActiveShuttle/YOLO_alexy/darknet/backup/

**Comment by AlexeyAB** [comment]
@Rahul-Venugopal Hi,

Can you run this command and show output?
```
cd /home/rahul/ActiveShuttle/YOLO_alexy/darknet/backup/
dir
```

And this
```
cd /home/rahul/ActiveShuttle/YOLO_alexy/darknet/
dir
```

**Comment by Rahul-Venugopal** [comment]
Hi @AlexeyAB  ,

Now I have trained it for more than 400 iterations and outputs as you asked are 

> cd  /home/rahul/ActiveShuttle/YOLO_alexy/darknet/backup/
> dir
`yolov3-obj_last.weights`

`rahul@rahul-HP-ZBook-15-G3:~/ActiveShuttle/YOLO_alexy/darknet$ dir`

> 3rdparty	   darknet.py		  LICENSE	 src
> backup		   darknet_video.py	  Makefile	 video_v2.sh
> build		   data			  net_cam_v3.sh  video_yolov3.sh
> cfg		   image_yolov2.sh	  obj		 yolov3.weights
> chart.png	   image_yolov3.sh	  README.md
> darknet		   include		  results
> darknet53.conv.74  json_mjpeg_streams.sh  scripts
>

Why is there only one weight_file in backup ?

**Comment by AlexeyAB** [comment]
Currently

* for each 100 iterations will be overwrited `yolov3-obj_last.weights` file
* for each 1000 iterations will be saved separate `yolov3-obj_1000.weights`, `yolov3-obj_2000.weights`, ... file

https://github.com/AlexeyAB/darknet/blob/5343aa423563c107e0071b1427ad5defc27b56d2/src/detector.c#L281-L299

**Comment by Rahul-Venugopal** [comment]
Yeah , I saw about it and thanks for sharing the info again. But my question is , after the edit I made  in yolo.c file ( if((i < 10 && i%2 == 0) || (i%100==0) || (i < 1000 && i%100 == 0))
 , why is it not saving the weight file after 2 iteration till 10th iteration. ( PS : Eventhough it doesn't make any sense , am just curious to know in case if I have to change it in future )

**Comment by AlexeyAB** [comment]
@Rahul-Venugopal Show the screenshot of your code, with code before and after.

Check that you didn't change the commented (dead code) code: https://github.com/AlexeyAB/darknet/blob/5343aa423563c107e0071b1427ad5defc27b56d2/src/detector.c#L279

**Comment by Rahul-Venugopal** [comment]
@AlexeyAB 

Actually I made the changes in `darknet/src/**yolo.c**` and not in `darknet/src/**detector.c**` as you mentioned above 
**After** editing 

darknet/src/yolo.c  looks like below image 

![after](https://user-images.githubusercontent.com/30955455/51333200-879da300-1a7d-11e9-9152-6d12620967ed.png)

and  the  darknet/src/detector.c looks like 
detector 

![before](https://user-images.githubusercontent.com/30955455/51333232-9a17dc80-1a7d-11e9-9e39-906162746233.png)


Hope this will help you to find the mistake I made.

**Comment by AlexeyAB** [comment]
@Rahul-Venugopal 
You should change `darknet.c`.

**Comment by Rahul-Venugopal** [comment]
Thanks for helping :+1:
