### ISSUE TITLE
output  0.000000 miil-second?

### ISSUE THREAD

**Issue by ericwang321** [AlexeyAB/darknet#2232]
ubuntu 16.04+python 2.7+no gpu
  
after git clone latest repository，output appears **0.000000 miil-second,**
 how to change code （image.c)?

```

Total BFLOPS 65.864 
seen 64 
Used FMA & AVX2 
 Used AVX 
data/person.jpg: Predicted in 0.000000 milli-seconds.
person: 100%

```

The following is the relevant record.

    make error log
    [make.error2.log](https://github.com/AlexeyAB/darknet/files/2762561/make.error2.log)

>  Make option

```
GPU=0
CUDNN=0
CUDNN_HALF=0
OPENCV=0
AVX=1
OPENMP=1
LIBSO=1
```
thanks for any suggestion

**Comment by AlexeyAB** [comment]
> ubuntu 16.04+python 2.7+no gpu

* Do you use https://github.com/AlexeyAB/darknet/blob/master/darknet.py ?
* What cfg / weights files do you use, and what image do you use?

It looks like something wrong in Python script.

**Comment by ericwang321** [comment]
thanks for you reply.

run command  

> ./darknet detect cfg/yolov3.cfg yolov3.weights data/dog.jpg

```
Total BFLOPS 65.864 
Loading weights from yolov3.weights...
 seen 64 
Done!
 Used FMA & AVX2 
 Used AVX 
data/dog.jpg: **Predicted in 0.000000 milli-seconds.**
Not compiled with OpenCV, saving to predictions.png instead
```
- - -
use yolov3.cfg and *.jpg in data  from git clone.

**Comment by AlexeyAB** [comment]
@ericwang321 I fixed it. Update your code from GitHub.
