### ISSUE TITLE
-map option gets confused as weight file

### ISSUE THREAD

**Issue by vaishnavm217** [AlexeyAB/darknet#2235]
for running `./darknet detector train data/data.path cfg/yolofiltepath -dont_show -map` says `Loading weights from -map` while it should recognise it as `-map` option. Can you verify if you are able to reproduce it? same goes for other options like `-mjpeg`

**Comment by AlexeyAB** [comment]
@vaishnavm217 You should use the latest version of Darknet from this repository https://github.com/AlexeyAB/darknet instead of https://github.com/pjreddie/darknet

**Comment by vaishnavm217** [comment]
I am using your repo, might be in nov commits.
I will pull, build and try again. BTW the option works only if I **mention weights**. So I had to run till one weight file is generated.
