### ISSUE TITLE
It is CUDA 10 mandatory?

### ISSUE THREAD

**Issue by PabloDIGITS** [AlexeyAB/darknet#2239]
Hi @AlexeyAB,

I have an old version of this repo, and I want to update it to the last. I have CUDA 9.0, but the requirements says it needs CUDA 10. It is mandatory to update the CUDA version or I can work with the last version of the repo and CUDA 9.0?

Thanks for your time.

**Comment by Rahul-Venugopal** [comment]
If it helps 

I am using cuda 9.0 and it works fine for me .

**Comment by PabloDIGITS** [comment]
Ok thank you. I will give it a try then.

**Comment by AlexeyAB** [comment]
@PabloDIGITS Hi,
You can use CUDA 9.0

If you use Windows: https://github.com/AlexeyAB/darknet#how-to-compile-on-windows

> If you have other version of CUDA (not 10.0) then open build\darknet\darknet.vcxproj by using Notepad, find 2 places with "CUDA 10.0" and change it to your CUDA-version

**Comment by PabloDIGITS** [comment]
Im using Linux. Thanks

**Comment by PabloDIGITS** [comment]
I confirm it works with CUDA 9.0.
Thanks all.
