### ISSUE TITLE
Need my custom dataset more images?

### ISSUE THREAD

**Issue by PabloDIGITS** [AlexeyAB/darknet#2244]
Hi @AlexeyAB,
Im making my own dataset. In first place this dataset is for detect just the lateral of a specific vehicle. Your repo says that a good practice is to have 2000 images by class_id.

1.Are the no obj images included inside this 2000? I.e. 1000 obj images and 1000 no obj images. Or it has to be 2000 obj images and 2000 no obj images (1:1 proportion)

2. For now I have 122 images of the lateral of my vehicle (industrial tractor) in different spaces, angles and distance. And I have 49 images with no object. I plan to apply augmented data (rotation, mirror, noise, etc) and multiply by 5 this numbers. Are this enough images or you recommend more?
Because I think is a very specific part of the vehicle which you can see only at a small range of angles. The frontal or back of the tractor dont have to be detected, just the lateral.

Here are some images from my dataset:
NO OBJ
![img_20190118_111439](https://user-images.githubusercontent.com/40455065/51384590-157c9b00-1b1d-11e9-9c2b-d6ed7338a2c5.jpg)
![img_20190118_112546](https://user-images.githubusercontent.com/40455065/51384599-1f9e9980-1b1d-11e9-8692-d55901f2c333.jpg)
OBJ
![img_20190118_110954](https://user-images.githubusercontent.com/40455065/51384603-25947a80-1b1d-11e9-9239-c43cecc6a9a1.jpg)
![img_20190118_113616](https://user-images.githubusercontent.com/40455065/51384630-347b2d00-1b1d-11e9-83fc-1dd71d1b249f.jpg)

**Comment by AlexeyAB** [comment]
@PabloDIGITS Hi,

1. Better to use  2000 obj images + 2000 no obj images.

> For now I have 122 images of the lateral of my vehicle (industrial tractor) in different spaces, angles and distance. And I have 49 images with no object. I plan to apply augmented data (rotation, mirror, noise, etc) and multiply by 5 this numbers. Are this enough images or you recommend more?

2. If you do such data augmentation by your own code/soft, I think this is enough.


> Because I think is a very specific part of the vehicle which you can see only at a small range of angles. The frontal or back of the tractor dont have to be detected, just the lateral.

Yes, in this case you can have less than 2000 images per class.

**Comment by PabloDIGITS** [comment]
Ok, thanks. Anyways I will do a few more photos to make sure my dataset is fine. Maybe more no obj images to match the proportion and a few ones with objects.

Thank you for your time.
