### ISSUE TITLE
Bounding box in prediction result is too small

### ISSUE THREAD

**Issue by OndoyManing** [AlexeyAB/darknet#2250]
I used a custom dataset with 600 images in the size of 832 x 416. I have successfully trained the model to detect only 1 class(license plate). I also changed the width and height in the yolo-voc.2.0.cfg into 832 x 416. 

I tested the model out with an image that has the size of 1024 x 768. The prediction was correct; however, the bounding box is too small for the object. 
Here's how the result [looks](https://imgur.com/btLZ9nq)

EDIT
Solved by adding more variation in training dataset.

**Comment by OndoyManing** [comment]
> Did you set width=832 height=416 in yolo-voc.2.0.cfg for both Training and Detection?

Yes, I have set it to 832 x 416 in both training and detection.

> You did not change the anchors after the training?

I have not touched the anchors before or after training because it wasn't mentioned in this [tutorial](https://medium.com/@ravidesetty/number-plate-detection-on-indian-car-vehicles-using-yolov2-8c99e1a259f5)

> What mAP can you get?

I cannot seem to get the correct command syntax for getting the map :(

> Can you detect successfully on the images from Training dataset?

Yes, I have tried it on my training dataset and the bounding box fits the plate numbers perfectly.

Thank you so much for replying, I really appreciate it.

**Comment by OndoyManing** [comment]
mAp is 99.95%, here's a [screenshot](https://imgur.com/G8sCHZA)

I used your repo since I'm on Windows.

**Comment by OndoyManing** [comment]
I actually have 600 images. Could it be due to the fact that the size of my labeled training images is 832 x 416, thus making the plate numbers in the images too small?

**Comment by OndoyManing** [comment]
Thank you so much for your patience. Though I have a few more questions which will put my mind at peace.

In my case, I only want to detect 1 class (license plate.) What .cfg do you think is the best to use? 
Is the yolo-voc.2.0.cfg okay already? 

Do I have to change the anchors in the .cfg?

Are the tips given [here](https://github.com/AlexeyAB/darknet#custom-object-detection) still applicable today or is it already outdated?

**Comment by AlexeyAB** [comment]
@OndoyManing 

Better to use yolov3.cfg (or 10x faster but less accurate yolov3-tiny.cfg) than yolo-voc.2.0.cfg.

> Are the tips given here still applicable today or is it already outdated?

It is still applicable today.

> Do I have to change the anchors in the .cfg?

Try to use default anchors.

**Comment by OndoyManing** [comment]
Thanks!
I'll train my model with yolov3.cfg after I'm done labeling the new images,  hopefully this will do the trick. 
The Yolo Mark is a big help by the way!

Any changes in yolov3.cfg file I should keep in mind(other than changing the width and height of the network)?
