### ISSUE TITLE
/content/darknet-master/build/darknet/x64 mkdir -p obj chmod +x *.sh make: *** No rule to make target 'obj/http_stream.o', needed by 'darknet'.  Stop.

### ISSUE THREAD

**Issue by rrrtype** [AlexeyAB/darknet#2256]
When I tried to make using the latest version on Google coraboratory,
%cd /content/darknet-master/build/darknet/x64
!make

 I got such an error
/content/darknet-master/build/darknet/x64
mkdir -p obj
chmod +x *.sh
make: *** No rule to make target 'obj/http_stream.o', needed by 'darknet'.  Stop.

I copied Makefile , src folder and .sh files to /64.

**Comment by duohappy** [comment]
`darknet-master/build/darknet/x64` is for **Windows System**
In Linux, just run
+ modify Makefile such as GPU=1, depend on your requirements
+ make

refer to [https://github.com/AlexeyAB/darknet](https://github.com/AlexeyAB/darknet), and read it carefully.

**Comment by rrrtype** [comment]
> `darknet-master/build/darknet/x64` is for **Windows System**
> In Linux, just run
> 
> * modify Makefile such as GPU=1, depend on your requirements
> * make
> 
> refer to https://github.com/AlexeyAB/darknet, and read it carefully.

I solved it!
And , I use Google Coraboratory.
The command of colab is unique.
