### ISSUE TITLE
 How can I get better results?

### ISSUE THREAD

**Issue by rrrtype** [AlexeyAB/darknet#2258]
I am training my model now on Google Colaboratory.

When we tried with 600weights on avg 1.3 or so, we got this result....

 we got this result....

 How can I get better results?

Train data can only be used with low image quality on colab...

**Comment by dreambit** [comment]
i think u have to provide more info...
how many images are in your train dataset, your cfg file etc. or the author have to reading the tea leaves? )))
also try to calc  mAP, IoU https://github.com/AlexeyAB/darknet#when-should-i-stop-training
on validation dataset(or train dataset if u have not one)

**Comment by rrrtype** [comment]
> i think u have to provide more info...
> how many images are in your train dataset, your cfg file etc. or the author have to read the tea leaves? )))
> also try to calc mAP, IoU https://github.com/AlexeyAB/darknet#when-should-i-stop-training
> on validation dataset(or train dataset if u have not one)


There are about 370 imgs of 8 kb.
There are 2 to 4 beans in img and one class

**Comment by rrrtype** [comment]
> @rrrtype Train at least 4000 iterations.
> 
> https://github.com/AlexeyAB/darknet#when-should-i-stop-training
> 
> > Usually sufficient 2000 iterations for each class(object), but not less than 4000 iterations in total.

OK.
I try.

**Comment by rrrtype** [comment]
> @rrrtype Train at least 4000 iterations.
> 
> https://github.com/AlexeyAB/darknet#when-should-i-stop-training
> 
> > Usually sufficient 2000 iterations for each class(object), but not less than 4000 iterations in total.

I want to detect my object.
So , I should prepare some negative samples (only picture and empty .txt)?

**Comment by AlexeyAB** [comment]
> So , I should prepare some negative samples (only picture and empty .txt)?

It is better to do it, it will increase accuracy.
