### ISSUE TITLE
How to use focal loss in softmax?

### ISSUE THREAD

**Issue by Nico1ee1995** [AlexeyAB/darknet#2259]
I want to implement a two classification through darknet-53.
However, my dataset is very imbalanced, so I plan to add focal loss in my code.
Can anyone give me any suggestion?
Thank you.

**Comment by AlexeyAB** [comment]
You can look at: https://github.com/AlexeyAB/darknet/blob/81f7fc2c7bbddb79b5c87b5ab88fedf98f2b9963/src/region_layer.c#L132-L150

**Comment by Nico1ee1995** [comment]
Could you teach me where should I add the focal loss code in: https://github.com/AlexeyAB/darknet/blob/81f7fc2c7bbddb79b5c87b5ab88fedf98f2b9963/src/softmax_layer.c ?

thank you very much.
