### ISSUE TITLE
How can I skip frames when processing a live stream?

### ISSUE THREAD

**Issue by cesarandreslopez** [AlexeyAB/darknet#226]
Compiled version for windows and have a GPU laptop that can handle around 15 fps in a live RTMP stream of 30 fps or so. The result is that I am getting excessive latency. 

Any why to skip frames that cause delay? Can I ask it to be limited to X amount of fps and ignore the rest?

**Comment by AlexeyAB** [comment]
This is already implemented if you compile: https://github.com/AlexeyAB/darknet#how-to-use-yolo-as-dll
* at first `build\darknet\yolo_cpp_dll.sln`
* and then `build\darknet\yolo_console_dll.sln`

Then run `build\darknet\x64\yolo_console_dll.exe rtmp-stream-url`

You should have files 3 files: `build\darknet\x64\yolo-voc.cfg`,  `build\darknet\x64\yolo-voc.weights` and  `build\darknet\x64\data\voc.names`. 

----

You can change it to your model here (or implement to take them from the command line): https://github.com/AlexeyAB/darknet/blob/25750d59cc2a7156cd0b9e63ef04ef75f2b92a86/src/yolo_console_dll.cpp#L84-L86
And then recompile `yolo_console_dll.sln`

**Comment by cesarandreslopez** [comment]
Excellent @AlexeyAB  thank you! Will test and report back.

**Comment by cesarandreslopez** [comment]
@AlexeyAB  when trying to compile this way I get a missing x64/yolo_cpp_dll.lib error. Can't find that library nor have a clue on how to generate it.

**Comment by AlexeyAB** [comment]
Did you successfully compile `build\darknet\yolo_cpp_dll.sln`?
After that there shuld be two files: `build\darknet\x64\yolo_cpp_dll.lib` and `build\darknet\x64\yolo_cpp_dll.dll`

**Comment by cesarandreslopez** [comment]
Thanks again @AlexeyAB I did (at least no visible error) and get a resulting .dll, .ilk and .pdb but not a .lib.

What am i doing wrong?

**Comment by cesarandreslopez** [comment]
Ok! Just realized I was not building for Release. My bad.

**Comment by cesarandreslopez** [comment]
Ok it's running now but when inputing the RTMP data stream like this:

yolo_console_dll.exe rtmp://localhost 

Get a "Image is empty" Exception.

Should this be able to handle a rtmp stream the same way that the main example does?

**Comment by AlexeyAB** [comment]
@cesarandreslopez I fixed it in `yolo_console_dll.cpp`: https://github.com/AlexeyAB/darknet/commit/5a2efd5e5327c56a362442dce70bb3e46201cb89 
Try to update your code from this repo.

**Comment by cesarandreslopez** [comment]
Works great! Thank you!
