### ISSUE TITLE
couldn't make 

### ISSUE THREAD

**Issue by rrrtype** [AlexeyAB/darknet#2262]
I couldn't do make!
linux 
GPU=1
cuDNN=1
OPENCV=1

I got such error
![make](https://user-images.githubusercontent.com/45380277/51470843-60fea580-1db8-11e9-804c-391185a2c475.png)

![m1](https://user-images.githubusercontent.com/45380277/51471306-aec7dd80-1db9-11e9-987c-8ba90ff5964f.png)
![m2](https://user-images.githubusercontent.com/45380277/51471313-b12a3780-1db9-11e9-8ed9-ced5578d247b.png)

**Comment by AlexeyAB** [comment]
Can you compile it with?
```
GPU=1
cuDNN=1
OPENCV=0
```

Try to follow this manual to compile OpenCV on Linux properly: https://docs.opencv.org/3.3.0/d7/d9f/tutorial_linux_install.html

**Comment by rrrtype** [comment]
https://github.com/AlexeyAB/darknet/issues/882
