### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by kalisto22** [AlexeyAB/darknet#2269]
Hi, @AlexeyAB 

I did work on analyzing over 10 million images (test method) and at stage 1 357 223 I received the following error:

terminate called after throwing an instance of 'std :: out_of_range'
   what (): basic_string :: substr: __pos (which is 140)> this-> size () (which is 0)
Aborted (core dumped)

What is it for?

Thank !

**Comment by AlexeyAB** [comment]
@kalisto22 Hi,

> I did work on analyzing over 10 million images (test method) and at stage 1 357 223 I received the following error:

What command do you use for detection?

**Comment by kalisto22** [comment]
@AlexeyAB 
./darknet detector test net_cfg/1.data net_cfg/1.cfg train.weights -thresh 0.70 -dont_show < data/list.csv > log.csv

**Comment by AlexeyAB** [comment]
@kalisto22 Did you compile Darknet with OPENCV?

**Comment by kalisto22** [comment]
@AlexeyAB 
Yes

**Comment by AlexeyAB** [comment]
@kalisto22 
> BUT there is another problem:
> All images (detection objects in the bbox) are now saved in a distorted form.
> (similar to strong compression)

I fixed it.

And fixed this guide: https://github.com/AlexeyAB/darknet/issues/2269#issuecomment-456398920

**Comment by kalisto22** [comment]
@AlexeyAB 
Perfectly!
Thank !!!

**Comment by adarsh-ms** [comment]
I have the same issue when training on a dataset of 78k images. I got the error at 39th iteration. Any way to solve this?

**Comment by AlexeyAB** [comment]
@adarsh-ms 
Can you show screenshot of this error?
And what parameters do you use in the Makefile?

**Comment by 0xF00000** [comment]
I have the same Issue. I got it when training, I then reduced the amount of images. This seemed to fox it. The error later also occured when detecting using my model

GPU, OPENCC cUDDN = 1
