### ISSUE TITLE
How to impove FPS value when process video?

### ISSUE THREAD

**Issue by ericwang321** [AlexeyAB/darknet#2270]
environment:
```
cpu:Intel (E5-2665/i5-7500) 2core
mem:10g
os:ubuntu 16.04 
other:python2.7  /opencv 2.4.9.1 
gpu: nvidia gtx 1080ti
```
**2.avi: RIFF (little-endian) data, AVI, 1920 x 1080, 25.00 fps, video: H.264 X.264 or H.264**

after git clone latest  ， run the following command:
`./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights   2.avi`

1.  fps value is lower than 2fps 
2. cpu and memory utilization below 30% ;
3. gpu utilization below,utilization Looks low.
> ![gpu](https://user-images.githubusercontent.com/25045112/51530746-9e296d00-1e76-11e9-800c-993354090e8d.jpg)

 **Is it related to the opencv version?
 how to  improve fps ?**

_thanks for any suggestion._

**Comment by AlexeyAB** [comment]
* What parameters do you use in the `Makefile`?
set `GPU=1 CUDNN=1 OPENCV=1`
* Do you use this repository https://github.com/AlexeyAB/darknet or this https://github.com/pjreddie/darknet ?

**Comment by ericwang321** [comment]
1. repository
Really downloaded from repository https://github.com/AlexeyAB/darknet.

2.other environment:
python2.7 CUDA8.0 cudnn5.1.10 opencv2

3.make
only Modify only the following
GPU=1
CUDNN=1
OPENCV=1

**Comment by AlexeyAB** [comment]
Did you change anything in the source code?
What date of repository do you use?

Try to download new version of this repository: https://github.com/AlexeyAB/darknet

Then set `GPU=1 CUDNN=1 OPENCV=1` in the Makefile and do 
```
make clean
make
```

And run: `./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights 2.avi`

**Comment by ericwang321** [comment]
Thank you for your patience replay.

 dont change the source code,completely re-git clone from alexeyAB/darknet .
```

Ubuntu@9c076d6a13da:~/MyFiles/8/darknet$ git status
Located at the branch master
Your branch is the same as the  branch 'origin/master'.

ubuntu@9c076d6a13da:~/MyFiles/8/darknet$ git log
commit 00b87281f35412dfd0493b879120583951ca279c
Author: AlexeyAB <alexeyab84@gmail.com>
Date:   Sun Jan 27 03:42:44 2019 +0300
```
...

> after convert file format to 400*240 ,2.mp4,4,4M,
> 
> fps still low,only to 4fps.

---
**For processing video, what are the recommended configurations?
python ?  CUDA?  cudnn?  opencv?**
plan to prepare to reinstall the environment

**Comment by AlexeyAB** [comment]
CUDA 10.0 - from nVidia site
cuDNN 7.x for CUDA 10.0 - from nVidia site
OpenCV 3.2.0 (not as python package) - from OpenCV site
Makefile
```
GPU=1
CUDNN=1
OPENCV=1
```

* Try to use another mp4-file for detection.
* Can you show screenshot of the command for detection on video-file?
* Can you show screenshot of FPS?

**Comment by ericwang321** [comment]
thanks.it works.
