### ISSUE TITLE
exactly half predictions are nan

### ISSUE THREAD

**Issue by nsantavas** [AlexeyAB/darknet#2273]
In training phase i have half batch nan.
![train](https://user-images.githubusercontent.com/37878833/51559458-98d61d80-1e8a-11e9-83c8-3da28bf3095a.png)

and my cfg:

[rolfer5.txt](https://github.com/AlexeyAB/darknet/files/2784246/rolfer5.txt)

**Comment by AlexeyAB** [comment]
training goes well

https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

> Note: If during training you see nan values for avg (loss) field - then training goes wrong, but if nan is in some other lines - then training goes well.

**Comment by nsantavas** [comment]
But the nan values are only in region 16, in every iteration. With other anchors there aren't nan values anymore

**Comment by AlexeyAB** [comment]
What GPU do you use?

**Comment by nsantavas** [comment]
V100
