### ISSUE TITLE
Image within the bounding box won't save

### ISSUE THREAD

**Issue by OndoyManing** [AlexeyAB/darknet#2275]
I have read in issue [#2157](https://github.com/AlexeyAB/darknet/issues/2157) that we can now save the portion of the image that is enclosed in a bounding box by uncommenting lines 391-405 in image.h but when I tried it out no image was saved in result_img folder. Did I miss something else?

**Comment by xinyee1997** [comment]
@OndoyManing  Can you provide detail instruction how to solve that?
