### ISSUE TITLE
problems while building darknet

### ISSUE THREAD

**Issue by bit-scientist** [AlexeyAB/darknet#2277]
Hi, @AlexeyAB ,
I have cloned this repository today  and applied steps from [here.](https://github.com/AlexeyAB/darknet#how-to-compile-on-windows)
I am on windows 10, downloaded and installed cuDNN v7.4.1 for CUDA 10.0.
I have provided screenshots below

--------------------------
![](https://habrastorage.org/webt/01/kx/ap/01kxaptxqbzct2bswgmyjqrtrlm.jpeg)
-------------------------
![](https://habrastorage.org/webt/ro/gb/tq/rogbtqdgujdx4ozz0mzw6jvt_uo.jpeg)
-------------------------
![](https://habrastorage.org/webt/da/10/fs/da10fs4llm6rwbmt9wyhckzw-6g.jpeg)
-------------------------
![](https://habrastorage.org/webt/l4/dq/up/l4dqupmfgvqktdq5_n6xgwcjwog.jpeg)
-------------------------
![](https://habrastorage.org/webt/xl/ze/ht/xlzehtxbk1kwvrw-appj1hzskqy.jpeg)
-------------------------
![](https://habrastorage.org/webt/xy/pf/lr/xypflrs5n-p7nmwqcn3hjuepaj0.jpeg)
-------------------------
![](https://habrastorage.org/webt/dj/hd/ze/djhdzeogioeiegld_kprl5akloo.jpeg)
-------------------------
![](https://habrastorage.org/webt/r1/zb/qk/r1zbqklxnjclrpgdfawdwiv5rz0.jpeg)
-------------------------
![](https://habrastorage.org/webt/lc/xs/b7/lcxsb7vo_lzrxfz48sla_ckgl1k.jpeg)
-------------------------
![](https://habrastorage.org/webt/j0/v_/-q/j0v_-q0r6n0fpirvs3hwhmyr_to.jpeg)
-------------------------
![](https://habrastorage.org/webt/bg/hm/p8/bghmp8nj7ar4avr4qdskbdoibew.jpeg)
-------------------------
![](https://habrastorage.org/webt/bw/tf/lt/bwtfltayhr4ntjwp-g8ilhdlrxe.jpeg)
-------------------------
**The last 3 screenshots highlight the issue I am having.**
**If there is anything else I can add to, please request!**

**Comment by tygrysio** [comment]
Copy darknet.h and yolo_v2_class.hpp into source directory

**Comment by AlexeyAB** [comment]
@bit-scientist 

Add to your project file `/include/darknet.h`:
https://github.com/AlexeyAB/darknet/blob/master/include/darknet.h

**Comment by bit-scientist** [comment]
@AlexeyAB  and @tygrysio thanks for your help, but it is still not working. I first copied `darknet.h` and `yolo_v2_class.hpp` from `darknet/include `to `darknet/src `directory and then added through:

------------------------------------
![](https://habrastorage.org/webt/v5/qz/kc/v5qzkctmttlq5hob-iscf_epjgq.jpeg)
------------------------------------
No change. 
Now, I have errors, I am afraid to do something on my own.
Have a look (please refer to `darknet.h` and `yolo_v2_class.hpp` files on the right and theirs properties in the bottom)

------------------------------------
![](https://habrastorage.org/webt/hg/dz/4p/hgdz4pf98zf7ffoc0q-kf_g70ok.jpeg)

![](https://habrastorage.org/webt/ic/is/ge/icisge38xpzcwxwkky9prdxq6se.jpeg)

Then, I reverted the files back to their original places and included as @AlexeyAB  suggested. No luck.
Any further suggestions? Thanks!

**Comment by tygrysio** [comment]
Right click on .cu files. Properities and set element type to CUDA / C++

**Comment by bit-scientist** [comment]
@tygrysio If you meant this,

![](https://habrastorage.org/webt/qr/kk/x1/qrkkx17sukzlykahdbvb_w3aibs.jpeg)
----------------------------
then they are already in that type.

**Comment by tygrysio** [comment]
Yes. Maybe add GPU to preprocessor definition. My compilation work. I not use OPENCV and comment yolo_v2_class.hpp and yolo_console_dll.cpp. My preprocessor
WIN32
GPU
CUDNN
_TIMESPEC_DEFINED
_CRT_SECURE_NO_WARNINGS
_LIB
_CONSOLE

**Comment by tygrysio** [comment]
Try this
https://github.com/unsky/yolo-for-windows-v2 (YOLOv2)

**Comment by AlexeyAB** [comment]
@bit-scientist Try to update your code from GitHub and build the default `darknet.sln`

**Comment by bit-scientist** [comment]
@tygrysio , @AlexeyAB  thank you guys!
@AlexeyAB, Shouldn't I apply some steps you mentioned  before building? I just git-cloned the rep and opened `darknet\build\darknet\darknet` right away and tried building it.  It ended up showing this

![](https://habrastorage.org/webt/53/jv/ga/53jvga1ptnh9zlapugqunylgu7s.jpeg)

We are back to square one now, so I am ready to try again. ☺️☺️☺️

**Comment by sounansu** [comment]
> OK:git checkout [b47db90](https://github.com/AlexeyAB/darknet/commit/b47db904eea6d628a25fc2917ce00ecc4af63b9c)
> NG:git checkout [2d3220c](https://github.com/AlexeyAB/darknet/commit/2d3220cef58fa0fffb5c2e424476173ceb296b0d)

OK:git checkout 1b15e2f8df5794a8c81fdfafddb3863c9a1a9e16

Thank you!
