### ISSUE TITLE
Max number of objects in a single image?

### ISSUE THREAD

**Issue by daylanc** [AlexeyAB/darknet#2280]
Hello,

I trained a model to detect numbers between 0 and 3 (so 4 different classes). My test images COULD have upwards of 130 to 150 different numbers on a single image. Would this be a potential problem? Is there a theoretical max number of objects that can be detected on a single image? 

Also, I know NVIDIA DIGITS using detectnet had a minimum object size requirement of 50x50 pixels. Does there exist this kind of constraint for YOLOv3? I believe most of my numbers will be around 50x50 pixels, but that could be increased by increasing the overall image size (currently using 1700x2000 image).

Thank you.

**Comment by PeterQuinn925** [comment]
https://github.com/AlexeyAB/darknet/issues/1261

**Comment by AlexeyAB** [comment]
@daylanc Hi,

The last [yolo] layer in `yolov3.cfg` (width=608 height=608) can detect 3 objects inside area 11x11 pixels after that image is resized to the network size 608x608.
