### ISSUE TITLE
Can we perform detection without using the command line?

### ISSUE THREAD

**Issue by OndoyManing** [AlexeyAB/darknet#2281]
Let's say I created a GUI and there's a `captureBtn`. The detection will be performed immediately right after the image has been captured. Is that possible?

**Comment by AlexeyAB** [comment]
Yes, just build Darknet as SO/DLL library and use it with these APIs:
* C https://github.com/AlexeyAB/darknet/blob/master/include/darknet.h
* C++ https://github.com/AlexeyAB/darknet/blob/master/include/yolo_v2_class.hpp

For example, build Darknet with LIBSO=1 in the Makefile, and see example of `libdarknet.so` usage https://github.com/AlexeyAB/darknet/blob/master/src/yolo_console_dll.cpp

**Comment by OndoyManing** [comment]
> Yes, just build Darknet as SO/DLL library and use it with these APIs:
> 
> * C https://github.com/AlexeyAB/darknet/blob/master/include/darknet.h
> * C++ https://github.com/AlexeyAB/darknet/blob/master/include/yolo_v2_class.hpp
> 
> For example, build Darknet with LIBSO=1 in the Makefile, and see example of `libdarknet.so` usage https://github.com/AlexeyAB/darknet/blob/master/src/yolo_console_dll.cpp

The thing is, I already have my weights as I have trained the model to detect a custom object. Will my weights work there?

**Comment by AlexeyAB** [comment]
> The thing is, I already have my weights as I have trained the model to detect a custom object. Will my weights work there?

Yes.

> Trained it using yolov3-tiny-obj.cfg
> I'm also using Python btw

So just write your own Python code and use your trained model.
An example: https://github.com/AlexeyAB/darknet/blob/master/darknet.py

**Comment by OndoyManing** [comment]
> > The thing is, I already have my weights as I have trained the model to detect a custom object. Will my weights work there?
> 
> Yes.
> 
> > Trained it using yolov3-tiny-obj.cfg
> > I'm also using Python btw
> 
> So just write your own Python code and use your trained model.
> An example: https://github.com/AlexeyAB/darknet/blob/master/darknet.py

@AlexeyAB I tried running darknet.py and made sure I compiled both non-gpu & gpu version and both dll are in the same directory as darknet.py but it gives me an error.

```
Traceback (most recent call last):
  File "C:/Users/Necy/Desktop/darknet-master/darknet.py", line 110, in <module>
    lib = CDLL(winGPUdll, RTLD_GLOBAL)
  File "C:\Users\Necy\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
```

I also tried changing the dll paths to the absolute path but still gives the same [error](https://imgur.com/a/TuJPhfO).
