### ISSUE TITLE
Problems while building darknet on Windows

### ISSUE THREAD

**Issue by Jaiczay** [AlexeyAB/darknet#2285]
Hi,
I use Windows 10, MSVS 2015, cuda 10.0, cudnn v7.4.2, OpenCV 3.4.0
I tried building the solution like 1. at [How to compile on Windows](https://github.com/AlexeyAB/darknet#how-to-compile-on-windows) and got this errors:
![error](https://user-images.githubusercontent.com/29538753/51677074-c3ce8780-1fd8-11e9-8f15-bd63fd675645.jpg)

**Comment by AlexeyAB** [comment]
@Jaiczay Hi,

I added fix. Try to update your code from GitHub.
