### ISSUE TITLE
Makefile error

### ISSUE THREAD

**Issue by Lepiloff** [AlexeyAB/darknet#2290]
I got error in the makefile processe. My settings are:
```
GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=0
AVX=0
OPENMP=0
LIBSO=0
```
And I have CUDA v.9.1.85 and CUDNN v.7.1.3
Error:
![2019-01-25 10-17-40](https://user-images.githubusercontent.com/28572064/51731325-b32b1980-208b-11e9-9659-c9638798b99b.png)
NEED HELP!!

**Comment by Lepiloff** [comment]
I try with:
```
GPU=1
CUDNN=0
CUDNN_HALF=0
OPENCV=0
AVX=0
OPENMP=0
LIBSO=0
```
but the same error
```
17:87: error: ‘__args_arr’ was not declared in this scope
 __Z15binarize_kernelPfiS_(float *__par0, int __par1, float *__par2){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaSetupArgSimple(__par2, 16UL);__cudaLaunch(((char *)((void ( *)(float *, int, float *))binarize_kernel)));}
                                                                     ^
compilation terminated due to -Wfatal-errors.
Makefile:142: recipe for target 'obj/convolutional_kernels.o' failed
make: *** [obj/convolutional_kernels.o] Error 1
```

**Comment by AlexeyAB** [comment]
@Lepiloff Try this: https://github.com/pjreddie/darknet/issues/200

**Comment by Lepiloff** [comment]
This comment helped me https://github.com/pjreddie/darknet/issues/200#issuecomment-329692411

**Comment by WOTU-Tech** [comment]
![Selection_002](https://user-images.githubusercontent.com/53495062/125178133-72fe7980-e1a7-11eb-90ce-8c96072a8782.jpg)
I have cuda V11.4 and cudnn v9.1.85
Got error:
![Selection_003](https://user-images.githubusercontent.com/53495062/125178163-c4a70400-e1a7-11eb-90ed-b4ebed0d6108.jpg)
