### ISSUE TITLE
 Not able to test for list of images using "test.list" on Google Cloud Instance

### ISSUE THREAD

**Issue by qwerty020** [AlexeyAB/darknet#2298]
Trying to test images on google cloud server. 
No display that is fine, but "prediction.jpg" not getting saved in the directory.
And also not able to test for list of images using "test.list"

Please suggest

1. When testing a single image, "prediction.jpg" not getting saved. 
![image](https://user-images.githubusercontent.com/45031969/51799908-8d4d7280-224d-11e9-9475-0ff6cc374fb9.png)
![image](https://user-images.githubusercontent.com/45031969/51799925-d30a3b00-224d-11e9-965f-b3302ff6f0c7.png)
2. Also tried using sudo, now no classification happening.
![image](https://user-images.githubusercontent.com/45031969/51799952-31371e00-224e-11e9-9e38-cc56ff2b0a88.png)
3. Testing for list of images, permission denied.
![image](https://user-images.githubusercontent.com/45031969/51799963-66437080-224e-11e9-99ea-7e9859e6d2d7.png)
4. Also tried with sudo
![image](https://user-images.githubusercontent.com/45031969/51799974-9d198680-224e-11e9-88a3-03f559c6fcfd.png)

Installed opencv
![image](https://user-images.githubusercontent.com/45031969/51799992-db16aa80-224e-11e9-8eb3-22cca8597eea.png)

**Comment by qwerty020** [comment]
It is working, thank you.

I am getting below counts on my local system, my local system GPU is of Nvida GeForce GTX and have trained using this GPU
![image](https://user-images.githubusercontent.com/45031969/51801082-1c16bb00-225f-11e9-8ad4-0bd59d3940ca.png)

But Fine count is different when tested on other GPU configuration of google instance 
![image](https://user-images.githubusercontent.com/45031969/51801160-2a190b80-2260-11e9-99f9-41272743a737.png)

Is this happening because i am testing on different GPU?

**Comment by AlexeyAB** [comment]
@qwerty020 

* What params do you use in the Makefile in both cases?
* Check that you use absolutely identical code and images on both computers.

**Comment by qwerty020** [comment]
Working now. 
Thank you for help..

anchors value were different in yolo config files
