### ISSUE TITLE
demo on video stream

### ISSUE THREAD

**Issue by wurstcase** [AlexeyAB/darknet#23]
If i try the demo on an rtmp video stream it works but the framerate is not synced.
So the detection works too fast ( eg. stream is 25fps and detection around 40) and video feed freezes until the next chunk.

What do i have to change in the demo.c to make it synced ?

**Comment by AlexeyAB** [comment]
@wurstcase  

* Simple fix, add `cvWaitKey(1000/(2*25));` before `return 0`: https://github.com/AlexeyAB/darknet/blob/2fc5f6d46b089368d967b3e1ad6b2473b6dc970e/src/demo.c#L50

* Slightly more complex fix, add 2 lines here before `return 0`: https://github.com/AlexeyAB/darknet/blob/2fc5f6d46b089368d967b3e1ad6b2473b6dc970e/src/demo.c#L50

```
	double const cam_fps = cvGetCaptureProperty(cap, CV_CAP_PROP_FPS);
	cvWaitKey(1000 / (2*cam_fps));
```

But note that it will decrease performance if you will want to benchmark performance of Yolo on video-files faster than real-time.

**Comment by morrigan90** [comment]
Hi AlexeyAB,

Thanks for sharing your fork, your tutorial worked to train my own class. Is there a possibility to input a video file and get a processed video file as an output, such as in Guanghan's YOLOv1 fork?

Cheers

**Comment by AlexeyAB** [comment]
@morrigan90 

Yes, this is done always automatically, run the Yolo demo as usual, and after stop it, you can watch video-file `test_dnn_out.avi`.

This code is here: https://github.com/AlexeyAB/darknet/blob/2fc5f6d46b089368d967b3e1ad6b2473b6dc970e/src/image.c#L451

```
const char* output_name = "test_dnn_out.avi";
output_video = cvCreateVideoWriter(output_name, CV_FOURCC('D', 'I', 'V', 'X'), 25, size, 1);
cvWriteFrame(output_video, disp);
```

**Comment by wurstcase** [comment]
@AlexeyAB Thanks for the quick response

Tried both solutions, they definitely make a difference and its much better now.
Although there is still some slight stutter between the chunks with both versions and when i look at the command line output it says something between 31.2 and 32.3fps.

Tested it with my own stream and this public one rtmp://184.72.239.149/vod/BigBuckBunny_115k.mov which is 24fps

Do you have any idea why this is ?

**Comment by morrigan90** [comment]
@AlexeyAB thank you, this worked for me!

**Comment by AlexeyAB** [comment]
@wurstcase 

* You can use this simple fix:
```
void *fetch_in_thread(void *ptr)
{
    in = get_image_from_stream(cap);
    if(!in.data){
        error("Stream closed.");
    }
    in_s = resize_image(in, net.w, net.h);
	double const cam_fps = cvGetCaptureProperty(cap, CV_CAP_PROP_FPS);
	cvWaitKey(1000 / cam_fps);
    return 0;
}
```

* Or this more accurate fix: 
```
void *fetch_in_thread(void *ptr)
{
	struct timeval tval_before, tval_after, tval_result;
	gettimeofday(&tval_before, NULL);

    in = get_image_from_stream(cap);
    if(!in.data){
        error("Stream closed.");
    }
    in_s = resize_image(in, net.w, net.h);
	gettimeofday(&tval_after, NULL);
	timersub(&tval_after, &tval_before, &tval_result);
	double const cam_fps = cvGetCaptureProperty(cap, CV_CAP_PROP_FPS);
	cvWaitKey((1000 / cam_fps) - tval_result.tv_usec/1000);
    return 0;
}
```

**Comment by wurstcase** [comment]
@AlexeyAB 
Man, this works absolutely flawless.
You are the best, thank you so much !
