### ISSUE TITLE
But MSVS debug(x64) of darknet_no_gpu failed.

### ISSUE THREAD

**Issue by WeiZRPW** [AlexeyAB/darknet#2300]
Release version (x64) of darknet_no_gpu can be built successfully. I compared all Options of configuration properties window between the release and debug. All looks normal to me.

All errors from lines 58 and 448 of cvdef.h  Any quick suggestion on this?? Thanks,
##############################################
#if (defined(_MSC_VER) && (defined(DEBUG) || defined(_DEBUG))) || \
    (defined(_GLIBCXX_DEBUG) || defined(_GLIBCXX_DEBUG_PEDANTIC))
// Guard to prevent using of binary incompatible binaries / runtimes
// **https://github.com/opencv/opencv/pull/9161**
#define CV__DEBUG_NS_BEGIN namespace debug_build_guard {
#define CV__DEBUG_NS_END }
**namespace cv { namespace debug_build_guard { } using namespace debug_build_guard; }**
#endif
#endif
################################################
![darknet_no_gpu](https://user-images.githubusercontent.com/24899439/51804226-bce78500-2223-11e9-9228-f9d6f41032b6.jpg)

**Comment by AlexeyAB** [comment]
Try to build it without OpenCV. Just remove `OPENCV;` from definitions for x64 & Debug.
`\darknet_no_gpu.sln` -> (right click on project) -> properties -> C/C++ -> Preprocessor -> Preprocessor Definitions, and remove this: `OPENCV;`

This is an OpenCV issue. OpenCV no longer supports C-API. I will replace C-API with C++-API later.

**Comment by WeiZRPW** [comment]
@AlexeyAB 
I am curious why the debug version of darknet with CUDA could be built successfully. 
Do you mean that you are going to replace C-API with C++ -API for all OpenCV APIs in Darknet?
Thanks,

**Comment by AlexeyAB** [comment]
> Do you mean that you are going to replace C-API with C++ -API for all OpenCV APIs in Darknet?

Yes.

**Comment by WeiZRPW** [comment]
@AlexeyAB 
One extended question on OpenCV APIs. There are a number of GitHub repos, which implements YOLO by Python and some other deep-learning frameworks such as TensorFlow and Caffe. I wonder if those YOLOs are a good code-base (easy to debug and convenient OpenCV APIs ?) for the development of the real-time (with video) object detection application. Thanks in advance for any ideas and thoughts on this discussion.

**Comment by AlexeyAB** [comment]
@WeiZRPW 

It is a good idea to use TensorRT or Darknet with real-time object detection application.

All other frameworks require skills: C++ + Python/Lua/...

There is simple C in this repository, you can build it as SO/DLL library, or you can just add C-files (with entire Yolo v3 inference) to your C-project: 
* 1 file for CPU: https://github.com/AlexeyAB/yolo2_light/blob/master/src/yolov2_forward_network.c
* 2 files for GPU: https://github.com/AlexeyAB/yolo2_light/blob/master/src/yolov2_forward_network_gpu.cu and  https://github.com/AlexeyAB/yolo2_light/blob/master/src/gpu.cu
