### ISSUE TITLE
Improve detection speed

### ISSUE THREAD

**Issue by rrrtype** [AlexeyAB/darknet#2303]
When detecting from video on tiny - yolov 3 on CPU, it was 0.7 fps and very slow result was obtained.
Is there a good idea to raise detection speed other than using GPU?

**Comment by AlexeyAB** [comment]
* You should use the latest version of this repository (there were fixes at Jan 26, 2019)
* You should build Darknet with
```
AVX=1
OPENMP=1
```

Also what CPU do you use?
And what command do you use for detection?

**Comment by AlexeyAB** [comment]
So compile with `AVX=0 OPENMP=1` in the Makefile because your CPU doesn't support AVX2: https://ark.intel.com/products/42915/Intel-Core-i5-750-Processor-8M-Cache-2-66-GHz-

**Comment by rrrtype** [comment]
The speed got about 3 times!
Thank you!
