### ISSUE TITLE
built succesfully but pressing Local Windows Debugger (in MSVS2015) gives error

### ISSUE THREAD

**Issue by bit-scientist** [AlexeyAB/darknet#2304]
I've opened x64/yolo_cpp_dll and followed [this](https://github.com/AlexeyAB/darknet#how-to-use-yolo-as-dll)
step 1 there has the following outcome

---------------------------------------------
![](https://habrastorage.org/webt/dq/ed/1z/dqed1zzaz2x7skz48zndv1sozvw.jpeg)
---------------------------------------------
Is it a must anyway, because I do have all `yolo_cpp_dll `and `yolo_console` related files in x64 folder? (I think)

----------------------------------
![](https://habrastorage.org/webt/bj/2p/_t/bj2p_tyl_bwfzblmnxyfop_hdd0.jpeg)
----------------------------------
step 2 is working perfectly, tried with demo video!

Platform: **Win 10, x64, CUDA 10, opencv 3.4.0**

**Comment by AlexeyAB** [comment]
@bit-scientist 

All is ok.

`yolo_cpp_dll.dll` can be compiled, but can be run, because it is DLL-file, not EXE-file.

> step 2 is working perfectly, tried with demo video!

So all is done correctly.
