### ISSUE TITLE
yolo_console_dll.exe processing the video at FPS Detection 1 and FPS Capture 1

### ISSUE THREAD

**Issue by bit-scientist** [AlexeyAB/darknet#2307]
Hi everybody!
I remember yesterday I tested a test video with `yolo_console_dll.exe` cmd app in the form
`yolo_console_dll.exe data/obj.names cfg/obj.cfg backup/pc_14616.weights test.mp4` and observed FPS Detection **47** and FPS Capture **47** (or 48 at times). But today, all of a sudden, that same procedure is showing FPS Detection **1** and FPS Capture **1** (or 2 at times).
Might I have done something unnecessary? Because I only compiled `yolo_cpp_dll.dll`. 
Hope someone can put the things right for me, thanks.
**Win 10, x64, CUDA 10, opencv 3.4.0**

**Comment by AlexeyAB** [comment]
Hi,
Recompile `yolo_cpp_dll.sln` again.

**Comment by bit-scientist** [comment]
@AlexeyAB  genius at work, thanks!

**Comment by bit-scientist** [comment]
@AlexeyAB Hi,
Since my issue here is directly related to this, I didn't open a new one. (let me know if I should do otherwise)
**Issue:**
As far as I remember, I could run `yolo_console_dll.exe data/obj.names cfg/obj.cfg backup/pc_14616.weights test.mp4 ` command. That indicates that there was  **_yolo_console_dll.exe_** in **_x64/_**, but now it is not there. Again I might have done some things with  `yolo_cpp_dll.sln` and `yolo_console_dll.sln`. All these are strange to me. How a **_yolo_console_dll.exe_** may simply disappear? 
I opened `yolo_console_dll.sln` again to re-compile it, but this time the error about opencv_cudaoptflow.lib
Severity	Code	Description	Project	File	Line	Suppression State
`Error	LNK1181	cannot open input file 'opencv_cudaoptflow340.lib'	yolo_console_dll	D:\kisa_projects\people_counting\darknet\build\darknet\`	

Please help me solve this.

**Comment by AlexeyAB** [comment]
@bit-scientist 

* Or comment this line: https://github.com/AlexeyAB/darknet/blob/0543278a5bd7064fae6538afd1761b06b10f73ee/src/yolo_console_dll.cpp#L18

* Or install OpenCV with CUDA (CUDA opt flow)

**Comment by bit-scientist** [comment]
@AlexeyAB  Hi,
I want to enable tracking to further count objects moving in and out. So I didn't comment `#define TRACK_OPTFLOW`. 
As for the second choice, I couldn't opencv with cuda ( optflow) where I can make **_opencv_cudaoptflow340.lib_**  file no matter what I did. Is it that difficult process? Please share a link where I can install opencv (hopefully for 3.4.0) with CUDA (optflow)?

**Comment by AlexeyAB** [comment]
@bit-scientist 

just change this line: https://github.com/AlexeyAB/darknet/blob/f154d2070aecdacd0cdfb7270e159e754ae74261/include/yolo_v2_class.hpp#L167

to this
`#if defined(TRACK_OPTFLOW) && defined(OPENCV) && defined(GPU_DISABLED)`

and recompile `yolo_console_cpp.sln`

**Comment by bit-scientist** [comment]
@AlexeyAB Hi,
the last comment you posted unfortunately didn't help. However, I was able to create **_opencv_cudaoptflow340.lib_** and other `lib`s mentioned here: https://github.com/AlexeyAB/darknet/blob/0543278a5bd7064fae6538afd1761b06b10f73ee/src/yolo_console_dll.cpp#L34-L38

Thank you your guidance and support, really appreciate it!
