### ISSUE TITLE
2080 Ti training suffer CUDA Error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by lifeel** [AlexeyAB/darknet#2309]
Hello

I always got CUDDA Error when training my custom object, so I decide to train VOC dataset to check my system by "./darknet detector train cfg/voc.data cfg/yolov3-voc.cfg darknet53.conv.74".
Error still happen......
CUDA Error: an illegal memory access was encountered
darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
Aborted (core dumped)

Can you please give me same suggestion? Thank you.

My environment :
GeForce RTX 2080 Ti
Ubuntu 18.04 alternative server
driver 410.78
CUDA 10.0.130
Cudnn 7.4.2.24
![screenshot at 2019-01-29 18-53-49](https://user-images.githubusercontent.com/39479492/51903559-6df24900-23f7-11e9-963c-a806ab10cd92.png)

Makefile
![screenshot at 2019-01-29 19-02-09](https://user-images.githubusercontent.com/39479492/51903996-7d25c680-23f8-11e9-9d7a-f07f5cf8b55f.png)

**Comment by AlexeyAB** [comment]
@lifeel Hi,

* How many iterations can you train until this error occur?
* Do you use the latest version of this repository? (or at what date) Try to download the latest version.
* Can you attach your cfg-file?
* Do you get this error with `GPU=1 CUDNN=0` in the Makefile?
* Can you show output of the command `nvcc --version` ?

**Comment by lifeel** [comment]
Hi @AlexeyAB 

- Error occur at first iteration.

- I git clone this repository yesterday.

- Same error occur with GPU=1 CUDNN=0 in the Makefile.

- $ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
- Attach file is my cfg-file
[yolov3-voc.txt](https://github.com/AlexeyAB/darknet/files/2810460/yolov3-voc.txt)

**Comment by lifeel** [comment]
When I do command "make clean && make" and much warning occur.
I hope below screenshot would be helpful.

![screenshot at 2019-01-30 16-36-22](https://user-images.githubusercontent.com/39479492/51969063-68a40580-24ae-11e9-9225-36e6ed4ce93a.png)
![screenshot at 2019-01-30 16-42-07](https://user-images.githubusercontent.com/39479492/51969067-6d68b980-24ae-11e9-807f-b0c61a3e7383.png)
![screenshot at 2019-01-30 16-42-21](https://user-images.githubusercontent.com/39479492/51969070-6fcb1380-24ae-11e9-9e5a-4054ca1f1d33.png)

**Comment by AlexeyAB** [comment]
@lifeel Hi,

Thanks!

How many CPU-RAM do you have?

Also try to compile with `GPU=1 CUDNN=0`
1. And set `random=0` in the last yolo-lyaer in your cfg-file, does it help?

2. Also try to set `width=320 height=320` in cfg-file, does it help?

3. If it doesn't help, try to download darknet from `Commits on Jan 15, 2019` https://github.com/AlexeyAB/darknet/tree/920d792a0c34c70c722caf1db23792e81e51af5b
For example this archive: https://github.com/AlexeyAB/darknet/archive/920d792a0c34c70c722caf1db23792e81e51af5b.zip

**Comment by lifeel** [comment]
Hi @AlexeyAB 
I have one GPU(i7-8700, 128MB Cache) and 16*2=32 GB RAM.
1. And set random=0 in the last yolo-lyaer in your cfg-file, does it help? >>  NO
2. Also try to set width=320 height=320 in cfg-file, does it help? >> NO
3. Download darknet from Commits on Jan 15, 2019. Compile with GPU=1 CUDNN=0 and try to train random=1 width=416 height=416. >>>
CUDA Error: an illegal memory access was encountered
darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
Aborted (core dumped)

I am new at Linux and GPU hardware. Thanks for your help.

**Comment by AlexeyAB** [comment]
@lifeel Thanks!

I'm trying to understand the reason, since I can't reproduce this bug.

* Try to comment this line: https://github.com/AlexeyAB/darknet/blob/bd91d0a908fd0cd9364e16a00c395500f59cbf58/Makefile#L27

* Also try to compile `GPU=1 CUDNN=0 OPENCV=0 AVX=0 OPENMP=0 LIBSO=0 DEBUG=0` does it help?

* And try to compile `GPU=0 CUDNN=0 OPENCV=0 AVX=0 OPENMP=0 LIBSO=0 DEBUG=0` does it help?

* Can you successfully run this command without warning messages?
`./darknet detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416` 

* Can you show content of files `bad.list` and `bad_label.list` if they exist near with `./darknet`-executable file?

* Try to install the latest version of CUDA 10.0 for Ubuntu 18.04: https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda_10.0.130_410.48_linux
Then compile `GPU=1 CUDNN=0 OPENCV=0 AVX=0 OPENMP=0 LIBSO=0 DEBUG=0`
Does it help?

**Comment by lifeel** [comment]
Hi @AlexeyAB 

- Comment line 27 "# ARCH= -gencode arch=compute_75,code=[sm_75,compute_75] " and set batch=64 subdivisions=64 in the cfg-file.
--> current avg loss show -nan for all iterations.
![screenshot at 2019-02-01 10-11-35](https://user-images.githubusercontent.com/39479492/52098642-ce0d0900-260a-11e9-891c-ed75cfa805a5.png)
![screenshot at 2019-02-01 10-24-43](https://user-images.githubusercontent.com/39479492/52098838-a1a5bc80-260b-11e9-9c0d-aafe1b014c57.png)
- Also try to compile GPU=1 CUDNN=0 OPENCV=0 AVX=0 OPENMP=0 LIBSO=0 DEBUG=0 does it help? --> No, same -nan result as above.
- And try to compile GPU=0 CUDNN=0 OPENCV=0 AVX=0 OPENMP=0 LIBSO=0 DEBUG=0 does it help?
--> I have training message successfully as below
![screenshot at 2019-02-01 10-52-10](https://user-images.githubusercontent.com/39479492/52099753-7329e080-260f-11e9-9275-a07b5936b489.png)

- Can you successfully run this command without warning messages?
./darknet detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416
--> Couldn't open file: data/obj.data. You mean cfg/voc.data? I successfully run with  cfg/voc.data.
![screenshot at 2019-02-01 11-02-42](https://user-images.githubusercontent.com/39479492/52100082-ed0e9980-2610-11e9-8d61-6589c064fb8b.png)
- Can you show content of files bad.list and bad_label.list if they exist near with ./darknet-executable file?
--> Only bad.list exist. The content of bad.list is my custom project file name, not voc file name.
[bad.txt](https://github.com/AlexeyAB/darknet/files/2819922/bad.txt)

- Try to install the latest version of CUDA 10.0 for Ubuntu 18.04.
--> I would like to reinstall ubuntu18.04 / driver 410 / CUDA10 / cudnn7.4.2 after 2/11. Do you have any suggestion about version?

**Comment by AlexeyAB** [comment]
> Comment line 27 "# ARCH= -gencode arch=compute_75,code=[sm_75,compute_75] " and set batch=64 subdivisions=64 in the cfg-file.
> --> current avg loss show -nan for all iterations.

* But you don't get "CUDA Error: an illegal memory access was encountered" anymore?
* Try to check your dataset by using https://github.com/AlexeyAB/Yolo_mark


> - Can you show content of files **bad.list and bad_label.list** if they exist near with ./darknet-executable file?
> --> Only bad.list exist. The content of bad.list is my custom project file name, not voc file name.
> [bad.txt](https://github.com/AlexeyAB/darknet/files/2819922/bad.txt)

It seems there are wrong path-files in your train.txt.

**Comment by lifeel** [comment]
Hi @AlexeyAB
The bug maybe due to 2080 Ti hardware issue (with Micron memory discussing on the internet)

My 2080 Ti card can not pass CUDA sample test. I use 1080 Ti card with same environment, it works well !! So I doubt it is hardware issue.

Thanks for your help :-)

**Comment by AlexeyAB** [comment]
@lifeel Hi,

Yes, apparently this is a hardware bug in memory (possibly memory overheating)

https://www.tomshardware.com/news/rtx-2080-ti-gpu-defects-launch,37995.html

https://www.reddit.com/r/nvidia/comments/ac3zj2/rtx_2080_ti_micron_users_still_going_good/
