### ISSUE TITLE
flip data augment only some classes

### ISSUE THREAD

**Issue by k00r** [AlexeyAB/darknet#2311]
Hello @AlexeyAB 
Like the title says :) Can we only flip some particular classes and not the others?
Have a nice day.

**Comment by Sauraus** [comment]
I don't think so because the YOLO cfg file has no 'knowledge' of individual classes as such, it only knows how many classes there are.

**Comment by AlexeyAB** [comment]
@k00r Hi,
No.

What sould we do if there are 2 classes (1st should be flipped, 2nd shouldn't) on a single image?
We flip entire image. And we flip all images.

**Comment by k00r** [comment]
Thank you @Sauraus 
Thank you @AlexeyAB 
=)
