### ISSUE TITLE
Segmentation fault in training tiny yolo

### ISSUE THREAD

**Issue by 123alaa** [AlexeyAB/darknet#2324]
Hi @AlexeyAB ,
After 3 days training for tiny yolo, i got segmentation fault, why do you think this happen?
Is there is way to add try catch in part of the code, attached copy of the error.

Another thing this error without core dumped (so it is not gpu or cuda problem). 

Thanks,
Alaa

Region 23 Avg IOU: 0.549434, Class: 0.958736, Obj: 0.606647, No Obj: 0.002595, .5R: 0.634921, .75R: 0.206349,  count: 63

 Last accuracy mAP@0.5 = 32.66 % 
 Tensor Cores are used.
 157474: 3.609997, 3.845754 avg loss, 0.000627 rate, 1.962583 seconds, 40313344 images
 MJPEG-stream sent. 
Resizing
576 x 576 
 try to allocate workspace = 11943937 * sizeof(float),  CUDA allocate done! 
 try to allocate workspace = 11943937 * sizeof(float),  CUDA allocate done! 
 try to allocate workspace = 11943937 * sizeof(float),  CUDA allocate done! 
 try to allocate workspace = 11943937 * sizeof(float),  CUDA allocate done! 
Loaded: 0.000082 seconds
Region 16 Avg IOU: 0.916881, Class: 0.999978, Obj: 0Segmentation fault

**Comment by AlexeyAB** [comment]
@AlaaAbdalhaleem1995 Hi,

Seg-fault can't be catched by try-catch.
Also Darknet is mostly written in C, where is no try-catch.

* Repository from which date do you use?
* What command did you use for training?
* What parameters do you use in the Makefile?
* What versions of CUDA, cuDNN and OpenCV do you use?
* Can you rename cfg file to the txt-file and drag-n-drop it to your message?
* Can you show output of the commands
```
nvcc --version
gcc --version
nvidia-smi
```

**Comment by AlaaAbdalhaleem1995** [comment]
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

nvidia-smi

Wed Jan 30 13:53:17 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00005E67:00:00.0 Off |                    0 |
| N/A   45C    P0    70W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 00007940:00:00.0 Off |                    0 |
| N/A   55C    P0    59W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           Off  | 0000927D:00:00.0 Off |                    0 |
| N/A   55C    P0    58W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           Off  | 0000AFC2:00:00.0 Off |                    0 |
| N/A   45C    P0    81W / 149W |      0MiB / 11441MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

***By mistake i do the batch size = 1 subdivisions = 1 (Maybe this the problem)?
*** On the models that i got, the detection was good similar to the yolov3 but the bounding boxes were not accurate. (I uses your anchors)


1. I pulled before two weeks.
2.  ./darknet detector train cfg/coco.data cfg/yolov3-tiny.cfg yolov3-tiny.conv.15 -gpus 0,1,2,3 -map -dont_show
3. cudnn: 7.2.1.38 cuda:10.0 opencv: 2.4.9.1

[yolov3-tiny.txt](https://github.com/AlexeyAB/darknet/files/2812865/yolov3-tiny.txt)

**Comment by AlaaAbdalhaleem1995** [comment]
another questions about the anchors:
I trained yolov3.cfg with the original anchors it was perfect results, and when i change the anchors to fit my data, i got bad results.

How did you explain this?
I train on images size 320*320 (and i compute the anchors based on this)

Why the original anchors give better results although one on it's anchors was ( 373,326) it bigger that my image???

Thanks

**Comment by AlaaAbdalhaleem1995** [comment]
Ok, i will pull the updated version (But if their is a problem in the data like txt file not exist or something like this, the updated vesrion will not help, right?).

Regarding the anchors yes i change them and re train and got bad results, since i ask.
Yes 

> Anchors don't depend on image size, they depend on network size width,height in cfg-file.

Yes i use this  calc_anchors data/obj.data -num_of_clusters 9 -width 320 -height 320 
and also in the cfg

**Comment by AlexeyAB** [comment]
> (But if their is a problem in the data like txt file not exist or something like this, the updated vesrion will not help, right?).

Yes.

Also look at the bad.list and bad_label.list if the exist, there can be error massages.

> Why the original anchors give better results although one on it's anchors was ( 373,326) it bigger that my image???
> 
> Yes i use this calc_anchors data/obj.data -num_of_clusters 9 -width 320 -height 320
> and also in the cfg

So in your annotations some objects are larger than the image size. 
Check your dataset by using https://github.com/AlexeyAB/Yolo_mark
Also check bad.list , bad_label.list files.

----

Also show screenshot of point of cloud - command:
`./darknet detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416 -show`

**Comment by AlexeyAB** [comment]
@123alaa  I fixed memory leak during training with flag `-map` and `random=1` in cfg-file.
