### ISSUE TITLE
Detection problem while testing

### ISSUE THREAD

**Issue by tahsinsiad** [AlexeyAB/darknet#2325]
Hello Sir, I am new in deep learning field. I followed your instructions and train the custom dataset(conatains 100 images) which was made by me. 

- All the images are in **.png** format.
- Using two classes. **classes=2**
- For training I use **yolov3-tiny-obj.cfg** file and **yolov3-tiny.weights** file. 
- For image labeling, I use **open labeling tool.** Here is the link: **https://github.com/Cartucho/OpenLabeling** 
- using **max_batch = 500200**

After 10000 iteration I use yolo-tiny_10000.weights for testing my test images. One of class is detected without any problem. But, the other is not detected. Even, there is no bounding box surrounded the test image. I don't understand where is the problem? 

Here I also mention a confusion. In the obj.data file. Four lines:
```
classes=2
train = data/train.txt
valid = data/test.txt
backup = backup/
```
I don't use **test.txt** file. Beacause, I don't understand how can I generate this **test.txt** file? Is this file make problem in training?

**Comment by PeterQuinn925** [comment]
Did you modify the cfg file for your change in number of classes? You need to change classes = 2 in 2 places and filters = 21 in two places as described in the readme. https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

**Comment by tahsinsiad** [comment]
yes sir. I placed 2 in two places and also set the value of the filters 21 by calculating (2+5)*3 = 21.

**Comment by tahsinsiad** [comment]
![train](https://user-images.githubusercontent.com/19798218/52002650-c1928e80-24ec-11e9-88cf-82884266618f.JPG)

Please see it. Either my training is ok or not?

**Comment by AlexeyAB** [comment]
@tahsinsiad 

Try to set `valid=train.txt` in your `obj.data` file and show output of this command:
`./darknet detector map data/obj.data yolo-obj.cfg backup\yolo-obj_10000.weights`


Then show screenshot of point of cloud - command:
`./darknet detector calc_anchors data/obj.data -num_of_clusters 6 -width 416 -height 416 -show`

**Comment by tahsinsiad** [comment]
![map](https://user-images.githubusercontent.com/19798218/52005005-d114d600-24f2-11e9-8c8a-dcd5dcf43b81.JPG)
![clusters](https://user-images.githubusercontent.com/19798218/52005007-d1ad6c80-24f2-11e9-8745-88cdb2dfbaca.JPG)
![anchors](https://user-images.githubusercontent.com/19798218/52005011-d3773000-24f2-11e9-835d-f4bff99eb985.JPG)

Sir, here is the screenshots.

**Comment by AlexeyAB** [comment]
@tahsinsiad 
1. You should train by using default anchors in your case.
2. You should add more images for training, 400 - 4000 training images
