### ISSUE TITLE
Remove displayed label text from result image

### ISSUE THREAD

**Issue by prosthree** [AlexeyAB/darknet#2342]
Is it possible to remove label text from result image ? since I only train 1 class, I don't need the text to be displayed, only bounding box around it

**Comment by AlexeyAB** [comment]
Comment these 2 lines:

1. https://github.com/AlexeyAB/darknet/blob/2d747cab2bf94d3d81a562bc49614ac2c4e661bf/src/image.c#L633

2. https://github.com/AlexeyAB/darknet/blob/2d747cab2bf94d3d81a562bc49614ac2c4e661bf/src/image.c#L424
