### ISSUE TITLE
MSVS 2015 release(x64) of darknet_no_gpu failed,but debug(x64) successed

### ISSUE THREAD

**Issue by yao-zheng-yi** [AlexeyAB/darknet#2344]
According to README，release version (x64) of darknet_no_gpu can be built successfully,but I failed.However,debug(x64) of darknet_no_gpu can be built successfully.
Any quick suggestion on this?? Thanks
![qq 20190203165600](https://user-images.githubusercontent.com/41265163/52174870-66ef8000-27d5-11e9-8319-bd11a4ea9a52.png)
![qq 20190203165641](https://user-images.githubusercontent.com/41265163/52174871-6b1b9d80-27d5-11e9-8008-f6b6d217fdd7.png)

**Comment by yao-zheng-yi** [comment]
> Do you try to compile default darknet_no_gpu.sln, or did you create your own sln-file?
> Did you change anything in the sln-file or c-files?

**Comment by yao-zheng-yi** [comment]
> Do you try to compile default darknet_no_gpu.sln, or did you create your own sln-file?
> Did you change anything in the sln-file or c-files?

I compile default darknet_no_gpu.sln,and didn't change anything

**Comment by theshawnz** [comment]
May seem like an obvious question...Did you compile opencv in release mode as well? I ran into a problem with failing to compile in debug vs release when I didn't compile opencv in both modes.

**Comment by yao-zheng-yi** [comment]
> May seem like an obvious question...Did you compile opencv in release mode as well? I ran into a problem with failing to compile in debug vs release when I didn't compile opencv in both modes.

Thanks, the problem is my OpenCV version, when I used OpenCV(3.4.0), all questions were solved.
