### ISSUE TITLE
training graph not displaying properly and not saving properly

### ISSUE THREAD

**Issue by LukeAI** [AlexeyAB/darknet#2348]
I'm running a training on a remote server and viewing the progress over the LAN in a web browser but the image is corrupt - it only partially displays in the browser and if I try and save it - the magic number is wrong.
![training_graph](https://user-images.githubusercontent.com/43993778/52222097-987e4f00-289a-11e9-9cf9-b2395dd175a7.png)

both server and client are Ubuntu 16.04, browser is firefox
This is training with VOC as in README.

**Comment by AlexeyAB** [comment]
* Do you use remote server in the Internet or in the your LAN network?

* Try to set here `200000` instead of `2000`: https://github.com/AlexeyAB/darknet/blob/f7cb538b32d95e99a6751bf312f7c846419389d7/src/image.c#L825

**Comment by LukeAI** [comment]
![training_graph](https://user-images.githubusercontent.com/43993778/52582856-18ba2c80-2e26-11e9-9086-dbdd055bf067.png)
I have made your suggested edit of '200000' and reran - a bit more of the graph is revealed.

**Comment by LukeAI** [comment]
After 40 iterations the whole graph mostly appears to show, although with some refreshes the bottom is lost again although the saved image is still corrupt as above. reasonable workaround is to screenshot on the good ones.

**Comment by AlexeyAB** [comment]
@LukeAI 

> although the saved image is still corrupt as above

Do you mean that automatically saved `chart.png` is corrupted?

**Comment by LukeAI** [comment]
chart.png is not corrupt, just the image saved from the browser.

**Comment by AlexeyAB** [comment]
I added this fix: https://github.com/AlexeyAB/darknet/issues/2348#issuecomment-460356554

**Comment by AlexeyAB** [comment]
@LukeAI 
I just added another fix, it should solve this problem.
