### ISSUE TITLE
Can I Train from an External Hard Drive?

### ISSUE THREAD

**Issue by daylanc** [AlexeyAB/darknet#2349]
Hello,
This might be a silly question, but I wanted to see if I could run the training from an external hard drive. I'm planning on keeping my dataset on an external hard drive due to the large size of each image. Would I be able to initiate the training from the host and access the dataset on the external drive? Or does the dataset have to be on the internal memory?

Adding onto this question... Could I have the entire darknet repo on the external hard drive? So that I could connect that external hard drive to any computer with a GPU and CUDA and run trainings and/or testing? Hmmmmmm...

**Comment by AlexeyAB** [comment]
@daylanc Hi,

Yes, you can use external HDD/SSD for Darknet/datasets/weights-files, if it allows to write on it.
