### ISSUE TITLE
Tensor cores 2080 ti

### ISSUE THREAD

**Issue by nicolasCruzW21** [AlexeyAB/darknet#2354]
Hello, I am not very experienced in GPU compute capability.
Why did you dissable tensor cores for the 2080 ti when training a detector?
Compute capability is 75 according to get_gpu_compute_capability(net->gpu_index) on my 2080 ti with cuda 10.0 and cudann 7.4, very far from the 7000 required to use tensor cores.
On the MakeFile: 

GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=1
AVX=0
OPENMP=0
LIBSO=1

DEBUG=1
Thank you for you reply!

**Comment by AlexeyAB** [comment]
@nicolasCruzW21 Hi,

> Why did you dissable tensor cores for the 2080 ti when training a detector?

Why do you think so?
Darknet uses Tensor Cores for RTX 2080 ti.
I disable Tensor Cores only for CC < 7.0. But it is still enabled for CC >= 7.0.

https://github.com/AlexeyAB/darknet/blob/fa1415e3c2ffe0e9df2a6edf7d046e7edeef1e0b/src/parser.c#L673-L676

Tensor Cores are disabled automatically for the first 1000-3000 iterations, when the training isn't stable enough.

Also `DEBUG=1` decrease speed very much, so use it only for debugging.

**Comment by nicolasCruzW21** [comment]
Hello, thank you for your quick reply.
My cc as defined in get_gpu_compute_capability is 75. So cudnn_half will be set to 0 when parsing. Given this, even if I get past 3000 iterations tensor cores won`t be used. Currently I am just bypassing this function and setting cudnn_half=1 such that tensor cores are used after the first 1000 iterations.
Thank you again for you help

**Comment by AlexeyAB** [comment]
@nicolasCruzW21 Thanks! It is a bug, I fixed it.

**Comment by nicolasCruzW21** [comment]
Thank you for the fix (:
