### ISSUE TITLE
Darknet compile error on Windows 10

### ISSUE THREAD

**Issue by amar-mustaqim** [AlexeyAB/darknet#2355]
When i try to build the "darknet_no_gpu" file, there are 19 errors occur that prompt " Cannot open include file: 'opencv2/highgui/highgui_c.h': No such file or directory " message. Can you suggest any solution? Btw, i'm using oepncv 3.0 and cuda 10 on windows 10

**Comment by AlexeyAB** [comment]
Do you have directory? `C:\opencv_3.0\opencv\build\include`

Check paths: https://github.com/AlexeyAB/darknet#how-to-compile-on-windows

> If you have OpenCV 2.4.13 instead of 3.0 then you should change pathes after \darknet.sln is opened
> 
> 4.1 (right click on project) -> properties -> C/C++ -> General -> Additional Include Directories: C:\opencv_2.4.13\opencv\build\include
> 
> 4.2 (right click on project) -> properties -> Linker -> General -> Additional Library Directories: C:\opencv_2.4.13\opencv\build\x64\vc14\lib

**Comment by amar-mustaqim** [comment]
Yes. I have fix the directory and when I run it again, this errors appear.
![darknet error](https://user-images.githubusercontent.com/31053816/52390407-1f1d7100-2ad3-11e9-9e2b-44fd5c3f17d2.PNG) 
But if I remove opencv from the preprocessor definitions it works well. But when I run the detection after opencv was removed, i need to manually find the prediction file because it is not automatically being displayed since the opencv is not compiled, so I think it becomes a problem for me because I want to run the detection through the webcam.

**Comment by AlexeyAB** [comment]
Try to install OpenCV 3.3.0 https://sourceforge.net/projects/opencvlibrary/files/opencv-win/3.3.0/opencv-3.3.0-vc14.exe/download

**Comment by amar-mustaqim** [comment]
It works! Thank you do much! 😃

**Comment by amar-mustaqim** [comment]
Anyway @AlexeyAB , I able to run darknet_no_gpu very well after using opencv 3.3 but it works poor on webcam real time object detection with 0.3 fps only. But when i try to compile darknet file, this errors occur. Do u know why?
![darknet failed](https://user-images.githubusercontent.com/31053816/52467471-a3015700-2bc0-11e9-9dc2-b0483b95759e.PNG)

**Comment by AlexeyAB** [comment]
@amar-mustaqim 

https://github.com/AlexeyAB/darknet#how-to-compile-on-windows

> 1.3. To install CUDNN (speedup neural network), do the following:
> 
> download and install cuDNN v7.4.1 for CUDA 10.0: https://developer.nvidia.com/rdp/cudnn-archive
> 
> add Windows system variable cudnn with path to CUDNN: https://hsto.org/files/a49/3dc/fc4/a493dcfc4bd34a1295fd15e0e2e01f26.jpg
> 
> copy file cudnn64_7.dll to the folder \build\darknet\x64 near with darknet.exe


Or if you can't install cuDNN, then 

> If you want to build without CUDNN then: open `\darknet.sln `-> (right click on project) -> properties -> C/C++ -> Preprocessor -> Preprocessor Definitions, and remove this: `CUDNN;`

**Comment by amar-mustaqim** [comment]
Thank you! It works after i remove cudnn
