### ISSUE TITLE
Import darknet.py Issue (undefined symbol: network_predict_ptr)

### ISSUE THREAD

**Issue by Spawnfile** [AlexeyAB/darknet#2358]
I compiled darknet AlexAB fork. GPU=1, OPENCV=1, CUDNN=1 and LIBSO=1 maked succesfully.I have set up my LD_LIBRARY_PATH in .bashrc to /usr/lib. But when I execute darknet.py I get this error. After long time googling I did not find the solution on this. Is there anyone who solve this problem. Greetings. Thanks in advance.

**Comment by AlexeyAB** [comment]
@Spawnfile Try to update your code from GitHub.

**Comment by Spawnfile** [comment]
Thanks for your attention, I updated and build again. And It's solved.
