### ISSUE TITLE
Error whu

### ISSUE THREAD

**Issue by prosthree** [AlexeyAB/darknet#2360]
I trying to compile using GPU, and got this error.
any idea?
![image](https://user-images.githubusercontent.com/44990448/52395849-31eb7200-2ae2-11e9-855f-689ea7ecaf64.png)

**Comment by AlexeyAB** [comment]
Can you show output of commands?
```
whereis nvcc
nvcc --version
nvidia-smi
```

Do you have CUDA in these paths?
`/usr/local/cuda/lib64`
`/usr/local/cuda/include/`


Read also: https://github.com/pjreddie/darknet/issues/200#issuecomment-329692411
