### ISSUE TITLE
error while build darknet.sln in VS2017

### ISSUE THREAD

**Issue by worapoptie** [AlexeyAB/darknet#2362]
i got error like this when i build darknet.sln
![error](https://user-images.githubusercontent.com/47279583/52404067-ad591d80-2afa-11e9-8c94-5b18188b4d06.PNG)

i installed CUDA 10.0 and cudnn , opencv .3.4.0 and build in VS 2017
![error1](https://user-images.githubusercontent.com/47279583/52404106-cb268280-2afa-11e9-8947-f23899a318c3.PNG)
![error2](https://user-images.githubusercontent.com/47279583/52404109-ce217300-2afa-11e9-8702-9a1732994506.PNG)

thank you

**Comment by AlexeyAB** [comment]
CUDA nsight plugin isn't installed into your MSVS 2017.

* You should re-install CUDA 10.0 after the MSVS 2017 has been installed.

* Then open darknet.sln in MSVS, go there https://devblogs.nvidia.com/wp-content/uploads/2015/01/VS2013-R-5.jpg and set CUDA 10.0

**Comment by worapoptie** [comment]
> CUDA nsight plugin isn't installed into your MSVS 2017.
> 
> * You should re-install CUDA 10.0 after the MSVS 2017 has been installed.
> * Then open darknet.sln in MSVS, go there https://devblogs.nvidia.com/wp-content/uploads/2015/01/VS2013-R-5.jpg and set CUDA 10.0

thank you , it worked, but i run command 
darknet.exe detector demo custom/trainer.data custom/yolov3.cfg yolov3_final.weights videotest.mp4
and get error like this 
![error3](https://user-images.githubusercontent.com/47279583/52428593-ddbdad80-2b34-11e9-8864-5e11532768d7.PNG)
CUDA Error: file: c:\users\tie\desktop\darknet-master\src\cuda.c : cuda_set_device() : line: 16 : build time: Feb  7 2019 - 23:32:09
CUDA Error: unknown error

**Comment by AlexeyAB** [comment]
What GPU do you have?

Rename this file to `nvidia-smi.cmd` and run it, then show me screenshot: [nvidia-smi.cmd.txt](https://github.com/AlexeyAB/darknet/files/2841993/nvidia-smi.cmd.txt)

**Comment by worapoptie** [comment]
i have gtx 1050ti ,but now i reinstall graphic driver and it work 

thank you
