### ISSUE TITLE
YOLO dll can not be used with VS2015 Debug mode (Release mode is OK)

### ISSUE THREAD

**Issue by yuanxy92** [AlexeyAB/darknet#237]
I compile Yolo-v2 Windows into *.lib and *.dll and add to my own project

However, it only works when my own project is compiled in release mode.
if debug mode is used, this error occurs:
![image](https://user-images.githubusercontent.com/4077402/31829238-47d2af34-b5ef-11e7-9c43-4e8706de5680.png)
Release mode is OK.

I use cmake for my own project:

```
cmake_minimum_required (VERSION 3.1)
set(NAME YOLOdetector)
project ( ${NAME} )

set (CMAKE_CXX_STANDARD 11)

find_package(OpenCV REQUIRED)
include_directories(${OpenCV_INCLUDE_DIRS})

find_package(CUDA)
set(CUDA_NVCC_FLAGS
    ${CUDA_NVCC_FLAGS}
	-gencode=arch=compute_61,code=\"sm_61,compute_61\"
    )

set(YOLO_SDK_INCLUDE_DIR "E:/libs/YOLO/include")
set(YOLO_SDK_LIBRARY "E:/libs/YOLO/lib/yolo_cpp_dll.lib")
include_directories(${YOLO_SDK_INCLUDE_DIR})
set(MY_SOURCE_FILES 
	main.cpp
	YOLOdetector.h
	YOLOdetector.cpp
)
cuda_add_executable(${NAME}
	${MY_SOURCE_FILES}
)
target_link_libraries(${NAME}
	${OpenCV_LIBS}
	${YOLO_SDK_LIBRARY}
)
```

Could anyone help me ?
Thanks very much!

**Comment by yuanxy92** [comment]
Every time the characters behind Couldn't open file: is different.

**Comment by AlexeyAB** [comment]
Hi, do you really need for compile `yolo_cpp_dll.sln` in Debug mode?

You should use the same **release** or **debug** Runtime library both for DLL and EXE.  So you should set in the both DLL and EXE solutions the same RTL:
* or this in both: (right click on project) -> properties  ->  C/C++ -> Code generation -> Run Time library -> `Multi-threaded DLL (/MD)`
* or this in both: (right click on project) -> properties  ->  C/C++ -> Code generation -> Run Time library -> `Multi-threaded debug DLL (/MDd)`

Also read: https://github.com/AlexeyAB/darknet/issues/134
And this: https://github.com/AlexeyAB/darknet/issues/113#issuecomment-312047304

**Comment by yuanxy92** [comment]
Actually I do not need compile yolo_cpp_dll.sln in Debug mode?

Now the problem is that I can not use lib when my own project is compiled in debug mode. (The input filename always lost). 

I will check my project setting tomorrow based on your answers.
Thanks very much!

**Comment by blakeliu** [comment]
@AlexeyAB 
release version：can produce E:\cv\object_detection\yolo\darknet-master\build\darknet\x64\yolo_cpp_dll.lib  and  E:\cv\object_detection\yolo\darknet-master\build\darknet\x64\yolo_cpp_dll.dll.
Debug version , not yolo_cpp_dll.lib, so strange.
1>e:\cv\object_detection\yolo\darknet-master\src\yolo_v2_class.cpp(280): warning C4267: “=”: 从“size_t”转换到“int”，可能丢失数据
1>  正在生成代码...
1>x64\DLL_Debug\yolo_v2_class.obj : warning LNK4042: 对象被多次指定；已忽略多余的指定
1>  yolo_cpp_dll.vcxproj -> E:\cv\object_detection\yolo\darknet-master\build\darknet\x64\yolo_cpp_dll.dll
1>  yolo_cpp_dll.vcxproj -> E:\cv\object_detection\yolo\darknet-master\build\darknet\x64\yolo_cpp_dll.pdb (Full PDB)

**Comment by yuanxy92** [comment]
Hello @AlexeyAB I encounter a new problem for the newest code because of the head file cvdef.h.
I compiled OpenCV3.3 by myself with CUDA.

Line 58 is only valid in debug mode, so release mode is OK.

![image](https://user-images.githubusercontent.com/4077402/31927685-b2f712c0-b8c7-11e7-95fc-e0904fd7e29a.png)

Thanks very much!

**Comment by blakeliu** [comment]
@yuanxy92  The same error with your project!

**Comment by yuanxy92** [comment]
I write a new one to solve this problem:
https://github.com/yuanxy92/darknet
