### ISSUE TITLE
All detections are shifted

### ISSUE THREAD

**Issue by kocica** [AlexeyAB/darknet#2375]
Hi, I've already trained YOLO many times, but this is very first time I met this kind of problem and wasn't able to find any similiar thread. The problem is that all predicted bboxes are shifted few pixels upper left, as show on the image bellow

https://imgur.com/a/nJ5sqE1

I've already checked tons of annotations and all of them were perfectly correct, right around the traffic signs. This is very first time I'm using the negative dataset, which basically as you can imagine is image with empty annotation file. As far as I know, this is correct approach and should not fail the detections.

**Comment by AlexeyAB** [comment]
@kocica Hi,
What command do you use for detection?
Attach your cfg-file
Show me screenshot of Yolo_mark with opened training dataset with such traffic signs.

**Comment by kocica** [comment]
Oh damn... I forgot coordinates of x,y in YOLO should be the center of the object, not the top-left corner... :/
