### ISSUE TITLE
Possible bug in yolo2_light

### ISSUE THREAD

**Issue by bhkim** [AlexeyAB/darknet#238]
Before starting, let me thank you for this great resources.
This may not the proper place to report bug cases for yolo2_light project, but I could not find the issue section in that project. 

When I tried to load a weights-file that have been created by training via 'darknet detector train' mode, into the yolo2_light project, I couldn't get the same detection results with the original 'darknet detector test' mode. 

I found a critical difference at the initial step of reading from the weight file, in the load_weights_upto() function, which seems to cause bit-shifts downstream, as follows:
- original: https://github.com/AlexeyAB/darknet/blob/master/src/parser.c#L1027 ~ L2034
- questionable modification: https://github.com/AlexeyAB/yolo2_light/blob/master/src/additionally.c#L1709

When I applied the original code of the darknet code to the yolo2_light, it worked correctly. 

	fread(net->seen, sizeof(int), 1, fp);

was replaced by the original code as follows:

	if ((major * 10 + minor) >= 2) {
		fread(net->seen, sizeof(uint64_t), 1, fp);
	}
	else {
		int iseen = 0;
		fread(&iseen, sizeof(int), 1, fp);
		*net->seen = iseen;
	}

which requires one more line of #include at the top of additionally.c

#include <stdint.h>

I found additional modifications in the yolo2_light project, for example, applying expf() insread of exp() in get_region_box_cpu() or logistic_activate(), but these modifications were not problematic for me (Windows 10, Visual Studio 2015, CUDA 8.0, cuDNN 7).

Could you please confirm that my rollback modification above is all that I need to utilize yolo2_light codes?

**Comment by AlexeyAB** [comment]
@bhkim Hi, thank you! I fixed it.
There are should be a little bit more changes: https://github.com/AlexeyAB/yolo2_light/commit/db1d98d1e788fc8caae6aa66a6a8d4a876a76ae7

**Comment by bhkim** [comment]
Thank you very much!!
