### ISSUE TITLE
yolo on VS 2017 and cuda 9.0 getting below errors

### ISSUE THREAD

**Issue by vikasmunjal2002** [AlexeyAB/darknet#239]
![image](https://user-images.githubusercontent.com/33007352/31865164-a8f23d72-b787-11e7-98b1-8ea20160dd6b.png)

**Comment by AlexeyAB** [comment]
Hi,

Try to remove **CUDNN** definition and recompile (Release & x64):

open \darknet.sln -> (right click on project) -> properties -> C/C++ -> Preprocessor -> Preprocessor Definitions,  from this line remove: `CUDNN;`

**Comment by vikasmunjal2002** [comment]
Thanks Alexey, 

I removed the CUDNN and recompiled, now i am getting below error:
![image](https://user-images.githubusercontent.com/33007352/31869941-cbacba18-b7c8-11e7-87d5-5d90fe38c6ee.png)

**Comment by AlexeyAB** [comment]
@vikasmunjal2002 In which directory do you have the OpenCV installed?
I.e. where is your `build` directory of OpenCV?

Change paths to your OpenCV directories: `include` and `lib` in the darknet.sln.

I.e. open `darknet.sln` and change these 2 paths:
* (right click on project) -> properties -> C/C++ -> General -> Additional Include Directories: `C:\opencv_2.4.13\opencv\build\include`
*  (right click on project) -> properties -> Linker -> General -> Additional Library Directories: `C:\opencv_2.4.13\opencv\build\x64\vc14\lib`

**Comment by vikasmunjal2002** [comment]
@AlexeyAB Thanks for help, Darknet is compiled :-)
