### ISSUE TITLE
Custom training: Scale variant

### ISSUE THREAD

**Issue by William1Wu** [AlexeyAB/darknet#2393]
Hi Alexey,

Thanks for your contribution first.

I train a custom model using yolov3-VOC as based model to detect small electronic components, such as resistant and capacity.
20,000 Training data and 5,000 validation data are photoed by digital camera in front of main board about 10 cm.
After 10,200 iterations, performance is not bad.

**class_id = 0, name = resistant ,         ap = 89.35 %
class_id = 1, name = capacity,         ap = 85.88 %
 for thresh = 0.25, precision = 0.89, recall = 0.94, F1-score = 0.91
 for thresh = 0.25, TP = 59811, FP = 7511, FN = 3839, average IoU = 66.56 %
 mean average precision (mAP) = 0.876136, or 87.61 %** 

But I get high false positive when testing data are photoed at different distance such as 15 cm or 5 cm. 
I guess this is a scale variant problem?

I have two ideas. Could you help me?
1. Should I set random = 1 in cfg to solve it?  But it will be out of memory in random_val=1.4  ...
2. Should I add more training data contained different scale objects by resizing and cropping original training data?

Thanks.

- CPU: Intel i9-8950HK
- GPU: GTX-1080 (8GB)
- RAM: 64GB

===========================================
[net]
batch=64
subdivisions=64

width=1024
height=1024
channels=3

momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
burn_in=1000
max_batches = 10200
policy=steps
steps=7500,10000
scales=.1,.1

**Comment by AlexeyAB** [comment]
@William1Wu Hi,

> But I get high false positive when testing data are photoed at different distance such as 15 cm or 5 cm.
> I guess this is a scale variant problem?

Yes.


> I have two ideas. Could you help me?
> 
> 1. Should I set random = 1 in cfg to solve it?  But it will be out of memory in random_val=1.4  ...
> 2. Should I add more training data contained different scale objects by resizing and cropping original training data?

1. Do you get out of memory with random=1 even with subdivisions=64? Do you use tiny or full yolov3 model?

2. You should add more images with different scales too.

3. Also you can change from `jitter=0.3` to the `jitter=0.35` in the last layer.


> 20,000 Training data and 5,000 validation data are photoed by digital camera in front of main board about 10 cm.

In this case better to use `max_batches=20000` - `max_batches=40000`. Also you can train with `-map` flag and see when the increase in accuracy (mAP) stops.

**Comment by William1Wu** [comment]
@AlexeyAB  Hi,

> 1. Do you get out of memory with random=1 even with subdivisions=64?
Yes, I will get out of memory on GPU.
- network input size=1024x1024
- random=1 (random_val=1.4)
- subdivisions=64 

I try a test and get the maximum network input size under my local hardware is 1056x1056.
So now I modify some code and let random=1 to train with range of random scale [ 1/1.3, 1.06 ].
Is any possible to optimize it?

> Do you use tiny or full yolov3 model?
Yes, I make a copy of yolov3-voc.cfg you provided and modify it as my cfg.

> 2. You should add more images with different scales too.
> 3. Also you can change from `jitter=0.3` to the `jitter=0.35` in the last layer.
> In this case better to use `max_batches=20000` - `max_batches=40000` or **more**. Also you can train with `-map` flag and see when the increase in accuracy (mAP) stops.
> If you want to detect object at different distance such as **15 cm or 5 cm**, then you should add such images to **both Training and Validation datasets**.

OK, thank you for your advice.
