### ISSUE TITLE
Builds fine on Windows 10 but cannot run the executable

### ISSUE THREAD

**Issue by CatsNipYummy** [AlexeyAB/darknet#24]
I'm trying to build in Windows 10. VC creates the executable for me. But I'm not able to run it. Windows complains - "The application was unable to start corectly (0xc000007b). Click OK to close the application"

Should I make any changes to the VC project before building?

**Comment by AlexeyAB** [comment]
@CatsNipYummy 

It looks like a bug of some dll. Do you use MSVS2015, CUDA 8.0, OpenCV 2.4.9 or 13?

1. Try to put `pthreadVC2.dll.dll` and `pthreadGC2.dll` libraries near with `darknet.exe`: https://github.com/AlexeyAB/darknet/tree/master/3rdparty/dll/x64

2. Also try to "run profiling by going to "profile" menu and it will run the application and stop at the exact dll that's cause the problem": http://stackoverflow.com/a/38576585/1558037

3. Try to compile without support CUDA & OpenCV:
    * open `darknet_no_gpu.sln`,  from: https://github.com/AlexeyAB/darknet/tree/master/build/darknet
    * go to Visual Studio->Project->Properties->C/C++->Preprocessor, and remove here OPENCV
    * compile it, will be error?

**Comment by VanitarNordic** [comment]
I have windows 10 X64, Cuda 8.0 and Cudnn 5.1. if you **follow the instructions of AlexeyAB**, it builds and works flawlessly. make sure to use mentioned OpenCV version (2.4.9).

Also make sure that you have the final version of VS2015. follow its update warnings and install them. 

if you got some errors, just simply copy-paste require DLLs in the same folder as `Darknet.exe`. That's it.
