### ISSUE TITLE
how to add a im without obj for traing

### ISSUE THREAD

**Issue by Francis-Xia** [AlexeyAB/darknet#2405]
I want add some im without objs for traing, but, how can I do?

**Comment by Francis-Xia** [comment]
I am using YOLOv3 to detect some thing.

**Comment by kossolax** [comment]
You should just use empty txt file for the corresponding image.

**Comment by Francis-Xia** [comment]
> You should just use empty txt file for the corresponding image.

Yes, I solve and thanks a lot.
BTW, I will close the issue.
