### ISSUE TITLE
Low GPU Usage.

### ISSUE THREAD

**Issue by RakshithGB** [AlexeyAB/darknet#2411]
After successfully training yolov3-tiny on Ubuntu `16.04`, I tested the provided python script `	darknet_video.py` on a .mp4 file. Python version is `3.6.4` and OpenCV version is `4.0.1` using Cuda `10.0` and Cudnn `7.4.2`.

I have two systems:
System 1: Core i9 7900X (10 core), Kingston SSD, 16GB RAM (2444MHZ, DDR4), GTX 1080 Ti
System 2: Core i7 9700K (8 core), Samsung SSD (better RW speeds), 16GB RAM(2444MHZ, DDR4), GTX 1080Ti

System 1: 95FPS
System 2: 100FPS

The model is trained on 416x416, input video resolution is 1920x1080. The inference time is taking about 8-9ms. The GPU usage on both systems is about **40%**. Why am I not achieving 220FPS as per official yolo site claims or at least something close to it? Since the results are on a Titan X card, theoretically 1080Ti should be similar or infact even better?

**Comment by blackwool** [comment]
[RakshithGB](/RakshithGB)
 I have used such big size image to do detect,,but  small object  could not be detected.
what accuracy do you get? and what the smallest size the object is ?

**Comment by RakshithGB** [comment]
@blackwool You need to have such data in your training set as well, my mAP is about 85% doing end to end training (i.e without using coco weights).

**Comment by RakshithGB** [comment]
Just found out the over head is from OpenCV functions resizing and drawing lines. The network alone runs at 4ms/frame (250FPS!) on GTX 1080 Ti. Closing this issue. close#2411

**Comment by dreambit** [comment]
@RakshithGB Hi, could you explain what have you commented out to get 4ms? i think i came across the save problem. Thx. I am also using 1080ti

**Comment by dreambit** [comment]
@RakshithGB What was you GPU load during the training process? Thx

**Comment by dreambit** [comment]
I also noticed that the windows task manager is showing wrong gpu usage, it shows 35% while gpu-z > 95%
