### ISSUE TITLE
Do i need to labelize all category in all images ?

### ISSUE THREAD

**Issue by MartyEz** [AlexeyAB/darknet#2415]
Hello,

I want to train yoloV3 with two category : HumanFace and Pedestrian

I have one dataset with HumanFace labels but without Pedestrian labels
and i have one dataset with Pedestrian labels but without HumanFace labels.

Do i need to labelize all category in all images ? if not, there will be a problem with negative objet which are in fact positive one ?
Thanks

**Comment by aniketvartak** [comment]
you can combine the two datasets by calling HumanFace class 0 and Pedestrian class  1 in the labels text file. Have you done that?

**Comment by MartyEz** [comment]
But the non-labeled person present in HumanFace dataset will be consired as negative.
And the non-labeled face present in Pedestrian dataset will be consired as negative.

So it will break performance of yolo. Am i right ?

**Comment by AlexeyAB** [comment]
@MartyEz Hi,

> Do i need to labelize all category in all images ?

Yes. 

https://github.com/AlexeyAB/darknet#how-to-improve-object-detection


> check that each object are mandatory labeled in your dataset - no one object in your data set should not be without label. In the most training issues - there are wrong labels in your dataset (got labels by using some conversion script, marked with a third-party tool, ...). Always check your dataset by using: https://github.com/AlexeyAB/Yolo_mark

**Comment by MartyEz** [comment]
@AlexeyAB  ok thanks a lot !
