### ISSUE TITLE
Right and left traffic sign detection

### ISSUE THREAD

**Issue by Spawnfile** [AlexeyAB/darknet#2416]
I have a dataset for detecting traffic signs including left and right. Detector has been confused when It detect right and left. There are so much wrong detection when camera see right and left sign. How can I improve that accuracy ? Using flip, rotate or something else ?

Thanks for your helping. Have a good day.

**Comment by AlexeyAB** [comment]
Set `flip=0` in the `[net]` section in cfg-file before Training.
