### ISSUE TITLE
Slow MJPEG return, incomprehensible results

### ISSUE THREAD

**Issue by chrisvoncsefalvay** [AlexeyAB/darknet#2430]
![screenshot 2019-02-18 at 12 06 15](https://user-images.githubusercontent.com/2670100/52947142-2ddb1200-3376-11e9-9564-26136c05636d.png)

1) Why does the loss start at 4.5? Initial loss was much higher.
2) Why do all iterations' loss points seem to be at or around zero?
3) Where's the rest of the image? It seems to cut off after 1.5.
4) Why does it take 27 seconds (!) for a whopping 135.82kb to be returned?

**Comment by AlexeyAB** [comment]
What Web-browser and OS do you use?

**Comment by chrisvoncsefalvay** [comment]
I tried Chrome, Firefox and Safari on iOS and OS X.

**Comment by AlexeyAB** [comment]
* Do you run Darknet on OS X?

* If you try to open MJPEG in a web-browser on the same local machine where is Darknet, do you get this issue?

**Comment by chrisvoncsefalvay** [comment]
Darknet runs on a headless EC2 instance, so can't test.

Every once in a while, I get a message noting that the `MJPG_sender` has killed the client:

<img width="489" alt="screenshot 2019-02-18 at 15 43 16" src="https://user-images.githubusercontent.com/2670100/52958239-f54a3100-3393-11e9-826b-0f021285dae7.png">

**Comment by kossolax** [comment]
Hello,

Same issue here: https://github.com/AlexeyAB/darknet/issues/2404 https://github.com/AlexeyAB/darknet/issues/2348.  This workaround https://github.com/AlexeyAB/darknet/issues/2348#issuecomment-460356554 works for me.

 Your 27 seconds delay is related to duration of one iteration. I've got 5-7 seconds delays btw.

**Comment by AlexeyAB** [comment]
@kossolax I added this fix.

**Comment by kossolax** [comment]
Well, I guess SO_SNDTIMEO is OS dependent, so this is probably not the best way to fix; but anyway thanks for the merge.

**Comment by chrisvoncsefalvay** [comment]
Thanks for fixing this, folks. Thanks for the quick merge, @AlexeyAB.

**Comment by AlexeyAB** [comment]
@chrisvoncsefalvay @kossolax 
I just added another fix, it should solve this problem.
