### ISSUE TITLE
weights file name

### ISSUE THREAD

**Issue by aadeshb7** [AlexeyAB/darknet#2432]
im using google colab to train my custom dataset using yolov3 model.
i have completed 1000 iterations. but even after 1000 iterations, the name of the weights file in backup folder is "last" .weights and not 1000.weights..please help

**Comment by AlexeyAB** [comment]
Update your code from GitHub and recompile.

**Comment by aadeshb7** [comment]
what changes should i make?

**Comment by AlexeyAB** [comment]
This changes `src/detector.c` line 292: https://github.com/AlexeyAB/darknet/commit/5e850c24897a5eb65941703059a85ead2ea5ff8c#diff-d77fa1db75cc45114696de9b1c005b26R292

**Comment by aadeshb7** [comment]
i made the changes but when im compiling them im getting an error for the files to be included

**Comment by AlexeyAB** [comment]
@aadeshb7 

Just download the latest version of Darknet. There are all these fixes.

**Comment by aadeshb7** [comment]
Done...thanks... 👍

**Comment by yassinesefrioui** [comment]
Hi, 
I need to save all files weights like : 
```
yolov3_100.weights
yolov3_200.weights 
yolov3_300.weights
```
the function in detector.c save the file but it overwrites the previous file, it does not add a new file : 
sprintf(buff, "%s/%s_last.weights", backup_directory, base) 
```
yolov3_last.weights 
```
how can i change it for the function can save all files with different iteration weights?
thank you

**Comment by aadeshb7** [comment]
@yassinesefrioui just change last to %d and recompile the project
