### ISSUE TITLE
darknet build error MSB3721

### ISSUE THREAD

**Issue by tszwailam** [AlexeyAB/darknet#2433]
Hello,

I have followed the guide of the author from #136 , I have retarget SDK Version, and included the directories listed from #136. Yet I have still receiving the same error message.

![image](https://user-images.githubusercontent.com/31747850/52976079-098f2d80-3396-11e9-8b8f-6fcf702dc21d.png)

I use Win10 x64, MSVS 2015, CUDA 9.0, and opencv 3.4.0.

The only changes that I have personally made was editing the darknet.vcproj file, changing line 55 to ".... CUDA 9.0 props" and line 291 to "... CUDA 9.0 targets". I have set it to Release and x64, and yet nothing happens. 

If anyone could help it would be greatly appreciated!

Thank you

**Comment by PeterQuinn925** [comment]
That error message isn't very helpful. Can you follow the advice [here ](https://stackoverflow.com/questions/22151402/how-can-i-resolve-the-error-the-command-exited-with-code-1)and turn message verbosity to diagnostic?
That might help you find the problem

**Comment by tszwailam** [comment]
Hello,

I turned it to diagnostic, and nothing seems to have changed except now I have 22 errors instead of 11.

![image](https://user-images.githubusercontent.com/31747850/52981420-b2955280-33ad-11e9-8fe0-ba7e40c0525b.png)
![image](https://user-images.githubusercontent.com/31747850/52981447-d8baf280-33ad-11e9-8197-61880eeaa872.png)

**Comment by zhang11wu4** [comment]
I encountered the same question, look forward someone to fix it

**Comment by PeterQuinn925** [comment]
What's on line 707 of Cuda 9.0.targets? You probably have a bad path or something.

**Comment by 0xlyc** [comment]
open file build\darknet\darknet.vcxproj by using Notepad,find 2 places with "compute_30,sm_30;compute_75,sm_75" and change it to "compute_30,sm_30;compute_52,sm_52".This value seems to be related to your GPU,my GPU is GTX1050Ti and it works.

**Comment by tszwailam** [comment]
Thank you !@0xlyc However, after changing that. I had even more errors.

![image](https://user-images.githubusercontent.com/31747850/53275781-64908f80-36ca-11e9-95ee-264b062c8831.png)

**Comment by xiaozi-ML** [comment]
"compute_30,sm_30;compute_75,sm_75" and change it to "compute_30,sm_30;compute_52,sm_52"
it works, thks

**Comment by voguke** [comment]
> 
> 
> open file build\darknet\darknet.vcxproj by using Notepad,find 2 places with "compute_30,sm_30;compute_75,sm_75" and change it to "compute_30,sm_30;compute_52,sm_52".This value seems to be related to your GPU,my GPU is GTX1050Ti and it works.

My GPU is also GTX1050Ti and it helps me.Thks!!

**Comment by Orion-wyc** [comment]
3Q . o(*￣︶￣*)o, it works.
haha, I encountered the same question this morning. When we use different GPUs, we may need modify the nvcc_ARCH flag "compute_30,sm_30;compute_75,sm_75".
LINK:https://github.com/tpruvot/ccminer/wiki/Compatibility
I am using CUDA8.0 & MSVS2019 & OpenCV 3.4. I changed the "darknet.vcxproj" :
line55:    <Import Project="$(VCTargetsPath)\BuildCustomizations\CUDA 8.0.props" />
line301:    <Import Project="$(VCTargetsPath)\BuildCustomizations\CUDA 8.0.targets" />
line107&158:<CodeGeneration>compute_30,sm_30;compute_52,sm_52</CodeGeneration>(GTX960)
Finally, I solved the porblem.

**Comment by plastizity** [comment]
Thank you @Orion-wyc!!!!
I solve my problem!

**Comment by cuihangmver** [comment]
my gpu is 2070 super，compute？ sm？ who knows？

**Comment by cenit** [comment]
cmake knows :)
