### ISSUE TITLE
Train yolo on objects it didn't get with the pretrained model

### ISSUE THREAD

**Issue by vallettea** [AlexeyAB/darknet#245]
Hello,

I've been reading your work with a lot of interest but I'm still not able to figure out if it is possible to enhance the default pretrained model by feeding him with new annotated examples ?

I want to do this because yolo gives me already good results and I don't want to retrain all the model from scratch. Can the learning process start from the pretrained model and look at my personnal examples ?

Thanks anyway for your work

**Comment by AlexeyAB** [comment]
Hi, yes you can.

* If you mean **fine-tuning** - remove last convolutional layer and train it from the begining without changes of other layers - it isn't implemented in the darknet - you can't do it
* If you mean **transfer-learning** - train using pre-trained weights:
    1. For **any number of classes** - you can do it using `darknet19_448.conv.23`: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects
    2.  For **the same number of classes** - you can do it using `yolo-voc.weights` and `yolo-voc.cfg` without changes, i.e. leave `class=20` and `filter=125`, but with increased `max_batches` - max number of iterations for training
    3. For **any number of classes** -  you can do it using:
        * `darknet.exe partial yolo-voc.cfg yolo-voc.weights yolo-voc.conv.23 23`
        *  or `darknet.exe partial yolo-voc.cfg yolo-voc.weights yolo-voc.conv.30 30`
        And then train using this pre-trained file `darknet19_448.conv.23` or `yolo-voc.weights` or `yolo-voc.conv.30` - for example: `darknet.exe detector train data/obj.data yolo-obj_8_classes.cfg yolo-voc.conv.30`

----

But I recommend using this approach: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

If you want to use mix of images from VOC-dataset with images from your-dataset, just fuse them - copy to the one folder and check bounded boxes of all images using Yolo_mark: https://github.com/AlexeyAB/Yolo_mark
This is what I usually do.

**Comment by vallettea** [comment]
thanks a lot for your quick response.
I'll try.
Best
