### ISSUE TITLE
Do you need update anchors after changing image size from 416 to 608

### ISSUE THREAD

**Issue by arkjiang** [AlexeyAB/darknet#2454]
Yolov3 Default anchors
anchors = 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326

Since anchor in yolov3 affects the output bounding box size (not only the aspect ratio), should anchors always be recalculated when you change the image size from 416 to anything else?

**Comment by AlexeyAB** [comment]
> should anchors always be recalculated when you change the image size from 416 to anything else?

You should recalculate anchors only before training and only if network size (width, height in cfg) is changed.
