### ISSUE TITLE
detect objects directly from cc camera 

### ISSUE THREAD

**Issue by VellalaVineethKumar** [AlexeyAB/darknet#2459]
i have compiled YOLOv3 with OpenCV=1 and GPU=1 and it is working perfectly
now i have the ips of the cc cameras
eg 10.2.0.10
i want to run detection algorithm for this video in real-time.
what changes can i make to achieve this

**Comment by AlexeyAB** [comment]
Do you use Network RTSP camera?
What URL can you use to see video in the VLC player? 

I use hikvision camera with this command:
`./darknet detector demo cfg/coco.data yolov3.cfg yolov3.weights -i 0 -thresh 0.25 rtsp://login:password@192.168.0.228:554`

**Comment by VellalaVineethKumar** [comment]
It works!
Thank you very much!
your help will not be forgotten!

**Comment by taehyunzzz** [comment]
Hello. I have one quick question.
Does this streaming protocol only support local network streams? It seems that people are using IP addresses that begins with 192.xx ... and from what I can remember, this is for local connections. 
I am trying to connect a webcam from my desktop to a remote server that has a GPU. My desktop and server have different IP addresses and are located far away from each other. Do you have any suggestion to make this work? Thank you!
