### ISSUE TITLE
question about training image

### ISSUE THREAD

**Issue by mck0225** [AlexeyAB/darknet#246]
Hi. I have some questions about training
[
![image](https://user-images.githubusercontent.com/26892666/32207175-a74542e6-be3d-11e7-981c-8225d9adcb0e.png)
](url)

Question 1
I want red bus coordinate define
type 1
![image](https://user-images.githubusercontent.com/26892666/32207291-51b27c76-be3e-11e7-97c4-21837aa89098.png)

type 2
![image](https://user-images.githubusercontent.com/26892666/32207301-6d028b6a-be3e-11e7-80ce-00d6241391ae.png)

What is the better of type 1 and type 2?

Question 2
I want people coordinate define
type 3
![image](https://user-images.githubusercontent.com/26892666/32208315-1195c722-be45-11e7-9410-2ddaf2f5d467.png)

type 4
![image](https://user-images.githubusercontent.com/26892666/32208330-299d8666-be45-11e7-8a38-35843b9d4ff6.png)

What is the better of type 3 and type 4?

**Comment by AlexeyAB** [comment]
Hi. You should use Type-1 and Type-3. I.e. select objects as if they were fully visible.

Also I would recommend to select slightly less background, for example:

![32208315-1195c722-be45-11e7-9410-2ddaf2f5d467](https://user-images.githubusercontent.com/4096485/32220347-6cc49cb6-be42-11e7-8fc5-9b1e0471c5ed.png)

**Comment by mck0225** [comment]
thank you very much for your help.
