### ISSUE TITLE
Darknet compiled for GPU and running on CPU

### ISSUE THREAD

**Issue by vallettea** [AlexeyAB/darknet#247]
Hello,

i'm using ubuntu 16.4 and cuda9.0 and I managed to compile darknet using `GPU=4` and `-gencode arch=compute_30,code=sm_30`.

When I train yolo using `./darknet detector train data/myyolo.data cfg/myyolo.cfg darknet19_448.conv.23` the process runs fine with no error but I see that only my CPU is running and `nvidia-smi` is giving:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GRID K520           Off  | 00000000:00:03.0 Off |                  N/A |
| N/A   38C    P0    38W / 125W |      0MiB /  4036MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
``` 

Any idea

**Comment by AlexeyAB** [comment]
Hi,

* you should set `GPU=1` in the Makefile (and I highly recommend `CUDNN=1` - it increases training speed 1.5x-2x times)

* GRID K520 actually is 2 x GPU (GK104). So to train using multi-GPU use this manual: https://github.com/AlexeyAB/darknet#how-to-train-with-multi-gpu

**Comment by vallettea** [comment]
I managed to make gpu work by changing instance to a p2.xlarge with GPU=1 CUDNN=1 and `nvcc=/usr/local/cuda-9.0/bin/nvcc`

Don't install cudnn with deb but rather by copying files as stated [here](https://stackoverflow.com/questions/31326015/how-to-verify-cudnn-installation)

**Comment by barzan-hayati** [comment]
> I managed to make gpu work by changing instance to a p2.xlarge with GPU=1 CUDNN=1 and `nvcc=/usr/local/cuda-9.0/bin/nvcc`
> 
> Don't install cudnn with deb but rather by copying files as stated [here](https://stackoverflow.com/questions/31326015/how-to-verify-cudnn-installation)

Are you sure?  By installing deb version of **CUDNN** and **CUDA**, Darknet will be run on **CPU**?

I have same problem in this link:
[ darknet take 100% CPU and 30% of GPU #4531 ](https://github.com/AlexeyAB/darknet/issues/4531#issue-538359438)
