### ISSUE TITLE
Colab and TPU

### ISSUE THREAD

**Issue by Favi0** [AlexeyAB/darknet#2474]
Hello @AlexeyAB  i just saw that this repo works with tensor cores right? im using google colab , do you think i would be able to train in it using their TPU? im not sure of the cards they are offering at the moment

**Comment by Favi0** [comment]
they are offering "TPUv2 card"

**Comment by AlexeyAB** [comment]
@Favi0 Hi,

> they are offering "TPUv2 card"

How much does it cost?

No, Darknet supports nVidia Tensor Cores on GPU Volta/Turing and higher, not Google Tensor Processing Units (TPUs).

Only TensorFlow supports TPU: https://www.blog.google/products/google-cloud/google-cloud-offer-tpus-machine-learning/
It is very expensive for mass use.

**Comment by Favi0** [comment]
> @Favi0 Hi,
> 
> > they are offering "TPUv2 card"
> 
> How much does it cost?
> 
> No, Darknet supports nVidia Tensor Cores on GPU Volta/Turing and higher, not Google Tensor Processing Units (TPUs).
> 
> Only TensorFlow supports TPU: https://www.blog.google/products/google-cloud/google-cloud-offer-tpus-machine-learning/
> It is very expensive for mass use.

seems like its free for use under [colab](https://forums.fast.ai/t/google-colab-quitely-turn-on-tpu-v2-for-free-to-everyone/23329)! , good to know wont try it with darknet then . Thanks

**Comment by ManzarIMalik** [comment]
Hey @AlexeyAB, is it possible to add TPU support to Yolo darknet?

**Comment by AlexeyAB** [comment]
@ManzarIMalik I didn't try. And I even didn't check this way.
I do not know how much it is needed

**Comment by ManzarIMalik** [comment]
@AlexeyAB, Google TPUs are extremely faster than GPUs. Do give it a shot to [What makes TPUs fine-tuned for deep learning?](https://cloud.google.com/blog/products/ai-machine-learning/what-makes-tpus-fine-tuned-for-deep-learning).

**Comment by xrv0** [comment]
Even though TPUs are not supported, google also does support GPUs. You also get 300$ free credit when registering. This means you can use an P4 16GB for 300 hours for free

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
