### ISSUE TITLE
I tried to use Yolo with webcam but it was blank

### ISSUE THREAD

**Issue by toboy32** [AlexeyAB/darknet#248]
Hi dear
I want to use Yolo with my cam. It didn't work at all. Help me.

VS2015
OPENCV3.0
CUDA9.0

command : darknet.exe detector demo cfg/coco.data cfg/yolo.cfg yolo.weights

BUT I can see only as below.
![image](https://user-images.githubusercontent.com/33257247/32226666-7bb10f94-be8c-11e7-92c5-ce0dd08057b6.png)

**Comment by AlexeyAB** [comment]
Hi,

> command : darknet.exe detector demo cfg/coco.data cfg/yolo.cfg yolo.weights


Try to use this: `darknet.exe detector demo fg/coco.data cfg/yolo.cfg yolo.weights -c 0`
As described here: https://github.com/AlexeyAB/darknet#how-to-use-on-the-command-line

Also can you see anything from your WebCam using any your own OpenCV application?

**Comment by toboy32** [comment]
Oh thanks for your kind answer, AlexeyAB.

Yeb I can see from my WebCam using my OpenCV.

But I don't know why it do not work with Darknet.

![image](https://user-images.githubusercontent.com/33257247/32280003-bfce456c-bf5d-11e7-85ce-65f9321e33a6.png)

**Comment by toboy32** [comment]
![image](https://user-images.githubusercontent.com/33257247/32336452-ba89de4c-c032-11e7-93ea-2830971ef765.png)

AlexeyAB

Refer to sample tutorial of Opencv  which is 'C:\opencv_3.0\opencv\sources\samples\cpp\tutorial_code\introduction\display_image' 
I cannot see anything. 

help me.

**Comment by bullapse** [comment]
Duplicate of #223 

Follow @vingn 's fix [here](https://github.com/AlexeyAB/darknet/issues/223#issuecomment-334909042)

**Comment by toboy32** [comment]
Thanks a lot~!!
