### ISSUE TITLE
memory error in detector.c::validate_detector_map

### ISSUE THREAD

**Issue by aimhabo** [AlexeyAB/darknet#2482]
my command is  `/home/wit/wjx/AlexeyAB/darknet/darknet detector map parameters.data yolov3-tiny.cfg yolov3-tiny.weights`
weights is downloaded from https://pjreddie.com/media/files/yolov3-tiny.weights
![2019-02-26 21-34-17](https://user-images.githubusercontent.com/12708080/53416358-50bc9480-3a0e-11e9-872e-2d77e5c015af.png)

It also happen while `/home/wit/wjx/AlexeyAB/darknet/darknet detector map parameters.data yolov3spp.cfg yolov3-spp.weights`
![2019-02-26 21-41-29](https://user-images.githubusercontent.com/12708080/53416931-7302e200-3a0f-11e9-9366-5664847c59d7.png)
and I found that 'id' https://github.com/AlexeyAB/darknet/blob/f37ea75b28f01a87f08cb3cdea2f3d58f72224f8/src/detector.c#L766 was changed unreasonable before https://github.com/AlexeyAB/darknet/blob/f37ea75b28f01a87f08cb3cdea2f3d58f72224f8/src/detector.c#L887 . So the program break down at that line this time.
but I still cannot solve this bug.

here's my parameters.data, and other files were acquired by git just half an hour ago. 
![2019-02-26 21-48-00](https://user-images.githubusercontent.com/12708080/53417446-911d1200-3a10-11e9-865e-e7456451b41e.png)

No abnormalities were found in 139 image and label.
![2019-02-26 21-54-41](https://user-images.githubusercontent.com/12708080/53417761-3637ea80-3a11-11e9-891b-d128ed07ec20.png)
![2019-02-26 21-55-30](https://user-images.githubusercontent.com/12708080/53417772-4223ac80-3a11-11e9-8730-817e22851e31.png)

**Comment by MartyEz** [comment]
What is `4path : .....139.jpg`

**Comment by AlexeyAB** [comment]
@aimhabo Hi,

* Show content of the files `bad.list` and `bad_label.list`

* Either just copy all labels from `val2017-labels` to `val2017-images` or try to add replacing-function for MS COCO 2017 there: https://github.com/AlexeyAB/darknet/blob/f37ea75b28f01a87f08cb3cdea2f3d58f72224f8/src/utils.c#L229-L236

**Comment by aimhabo** [comment]
@MartyEz there are over thousands images in both valid and test. 4 is print at the top of the 'for i' ，and path fprintf before char*id

**Comment by aimhabo** [comment]
@AlexeyAB yes, I have changed label-loading rule. there arent any bug else when calculating map on yolov3-tiny but break down at the last of calculating. But... it break down on the way to calculating spp

**Comment by AlexeyAB** [comment]
@aimhabo So currently, do you have errors only with yolov3-spp.cfg model? But does it work successfully with yolov3-tiny.cfg model?

**Comment by aimhabo** [comment]
@AlexeyAB yes. maybe values are problem, but anyway the calculating process is done. 
![2019-02-26 22-32-53](https://user-images.githubusercontent.com/12708080/53420456-ce849e00-3a16-11e9-86e6-f2802a87dad5.png)
![2019-02-26 22-33-15](https://user-images.githubusercontent.com/12708080/53420459-d17f8e80-3a16-11e9-82f5-7eac8883ca53.png)

**Comment by AlexeyAB** [comment]
@aimhabo You can try to comment some of these lines, to find where is a problem: https://github.com/AlexeyAB/darknet/blob/f37ea75b28f01a87f08cb3cdea2f3d58f72224f8/src/detector.c#L999-L1019

Since I can't reproduce it.

* Strange that mAP is too low.
* Also do you get good result on MS COCO 2014 & yolov3.cfg with good mAP?

**Comment by aimhabo** [comment]
@AlexeyAB I have failed to download mscoco2014 many times before. I can try again tomorrow. thankyou

**Comment by AlexeyAB** [comment]
@aimhabo Did you use script from my repo https://github.com/AlexeyAB/darknet/blob/master/scripts/get_coco_dataset.sh#L12-L15  instead of pjreddie's repo?

I changed links to cocodataset.org site for faster downloading.

**Comment by aimhabo** [comment]
@AlexeyAB The problem was passed after the two lines were commented.  
https://github.com/AlexeyAB/darknet/blob/f37ea75b28f01a87f08cb3cdea2f3d58f72224f8/src/detector.c#L887
https://github.com/AlexeyAB/darknet/blob/f37ea75b28f01a87f08cb3cdea2f3d58f72224f8/src/detector.c#L1004

seems good on val2014
![2019-02-27 18-06-39](https://user-images.githubusercontent.com/12708080/53482582-7ef7ae00-3aba-11e9-9794-cdad384b8895.png)
