### ISSUE TITLE
Question about cfg setting

### ISSUE THREAD

**Issue by mck0225** [AlexeyAB/darknet#249]
Hi. I have some questions about cfg parameters.

The parameters of the cfg file used for learning are set as follows.
width = 544
height = 544

What are the advantages and disadvantages of raising width and height to high values?

**Comment by TheMikeyR** [comment]
More precision, but slower detection and training time. 

If you have `random=1` in the bottom of the cfg file it will automatically scale the resolution for every 10 step so your training will generalise better by having inputs in various sizes.

**Comment by mck0225** [comment]
Thank you very much.
