### ISSUE TITLE
how to set the save interval of trained models for yolov3-tiny_3l.cfg

### ISSUE THREAD

**Issue by JohnTian** [AlexeyAB/darknet#2495]
@AlexeyAB Hi,

I find **yolov3-tiny_3l.cfg** is very useful for training for both small and large objects. But, the save interval of trained models is 1000, which is bigger in my case. Could you tell me how to set the save interval?

Thanks in advance!

**Comment by ydixon** [comment]
Probably try modifying the `1000` value and recompile

https://github.com/AlexeyAB/darknet/blob/f37ea75b28f01a87f08cb3cdea2f3d58f72224f8/src/detector.c#L306-L307

**Comment by JohnTian** [comment]
@ydixon Thanks for sharing.
