### ISSUE TITLE
How to use library so to detect objects in linux c++

### ISSUE THREAD

**Issue by phongnhhn92** [AlexeyAB/darknet#250]
Hello guys, I am trying to write a program to load the trained YOLO weights to detect objects using the darknet.so using NetBeans C++ but I dont know to do it. The given example is done in MS Visual Studio and I tried to load the weights my trained weights (in Linux) but no success. Would anyone help me on that please ?

**Comment by TheMikeyR** [comment]
Worst case you could try this wrapper https://github.com/TommyX12/darknet-cpp-wrapper he have some documentation on how to use it.

**Comment by phongnhhn92** [comment]
@TheMikeyR It's very useful for me. Thanks, I will take a look. Meanwhile I managed to use the so library on Netbeans by myself.
![screenshot from 2017-11-03 03-33-50](https://user-images.githubusercontent.com/11288381/32367453-77d2f244-c0c5-11e7-9387-3e083a9cdb8d.png)

**Comment by jimgros** [comment]
@phongnhhn92 Any chance you could share how you did it? I would like to do it in python. I'm no good in c++ but some insights as to how you called darknet.so with your weights would be very interesting. If you could share your code, that would be great. Thanks
