### ISSUE TITLE
Software suddenly stops while training

### ISSUE THREAD

**Issue by drapado** [AlexeyAB/darknet#2504]
While I'm training yolov3 for my custom dataset the program suddenly stops saying in the terminal: 4Killed. This error has happened 3 times in 7000 iterations of training. I installed darknet 4 days ago.

![capture](https://user-images.githubusercontent.com/45577687/53683223-9626dd80-3cfe-11e9-82df-adbbc205b7df.png)

I'm using a ryzen 5 2600, rtx 2060 under manjaro linux:

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

![screenshot_20190302_152208](https://user-images.githubusercontent.com/45577687/53683267-ff0e5580-3cfe-11e9-8074-3e09a198ef9c.png)

**Comment by AlexeyAB** [comment]
@drapado Hi,

* Can you successfully do the command?
`./darknet detector map ...` 

* Also you can try to update your code, I just changed memory allocation for mAP calculation during training.

**Comment by drapado** [comment]
@AlexeyAB Thanks for your answer. Yes, I can run detector. I'll update the code and see if I have the error again

**Comment by ribet31** [comment]
@AlexeyAB I had the very same problem. Calculating the mAP was consuming more memory each time, so the learning process was killed early (after ~1650 iterations).
After your commit, this works way better : the process can go up to ~14000 iterations before being killed. It looks like there is still some memory leak is the mAP computing.


Best regards


Here is the end of output :
 14100: 0.063544, 0.069845 avg loss, 0.001000 rate, 2.347695 seconds, 902400 images
Resizing to initial size: 512 x 288 
 try to allocate additional workspace_size = 33.55 MB 
 CUDA allocate done! 

 calculation mAP (mean average precision)...
24Killed

**Comment by AlexeyAB** [comment]
@ribet31 

Can you reproduce this bug for the default weights-files https://github.com/AlexeyAB/darknet#pre-trained-models and for Datasets like PascalVOC or MS COCO?

**Comment by ribet31** [comment]
I can run some specific test if you want. Could you please specify an exact command sequence so we can test always the same way?

Best regards

**Comment by AlexeyAB** [comment]
@ribet31 

Can you show content of files `bad.list` and `bad_label.list` if the exist.

What params do you use in the Makefile?

What command do you use for training?

Can you get this issue (memory leak)

* if you train your own dataset with `random=0` ?

* if you train MS COCO dataset that you get by using this script: https://github.com/AlexeyAB/darknet/blob/master/scripts/get_coco_dataset.sh
`/darknet detector train cfg/coco.data yolov3.cfg darknet53.conv.74`

* if you train with any other datasets?

**Comment by laclouis5** [comment]
Same problem.

Config: 

- Linux 18.04.2 LTS
- Nvidia GTX 1060 6GB
- 16 GB RAM (+32GB Swap on SSD)
- Intel Core i7-7700

Build:

- CUDA 10, CUDNN 7.5.0 fro CUDA 10
- OpenCV 3.1.1

Training param:

- Problem both occurs with `yolov3-tiny` and `yolov3`
- Training with own dataset, 3 classes, less than 10000 steps
- Random set to 1 (by default in cfg file)
- Training with `-map` flag
- Both occurs with pertained weights and no weights

Training works globally fine and results are OK (my trained model works on images and webcam just fine, accuracy is good and speed excellent) but during training RAM used by `darknet` increase steadily until full, then the process is killed (I use swap file as a workaround for training longer).

Command used:
`$ ./darknet detector train data/obj.data cfg/yolov3-tiny_obj.cfg my_models/yolov3-tiny.conv.15 -map`

Here is `obj.data` and config file as text files:
[obj.data.txt](https://github.com/AlexeyAB/darknet/files/2935491/obj.data.txt)
[yolov3-tiny_obj.cfg.txt](https://github.com/AlexeyAB/darknet/files/2935493/yolov3-tiny_obj.cfg.txt)

I can send more details or test different config if needed.

**Comment by AlexeyAB** [comment]
@laclouis5 Hi,

* Try to use the latest version of Darknet, I recently changed mAP calculation during training.

* Do you get this issue if you train with `random=0` ?

**Comment by laclouis5** [comment]
Just tried the latest version (still with `random=1`) and the leakage seems less important but still present. At first glance it looks like you changed the number of steps between mAP calculations so it may explain the slower rate of increase.

I'll try to train with `random=0` with the latest version and update this post.

**Comment by AlexeyAB** [comment]
@drapado @ribet31 @laclouis5 
 I fixed memory leak during training with flag `-map` and `random=1` in cfg-file.

**Comment by drapado** [comment]
Very nice, thanks @AlexeyAB !!
