### ISSUE TITLE
OpenCV Error???

### ISSUE THREAD

**Issue by yxwLearn** [AlexeyAB/darknet#2516]
@AlexeyAB 
OpenCV Error: Insufficient memory (Failed to allocate 2359296 bytes) in cv::OutOfMemoryError, file C:\build\master_winpack-build-win64-vc14\opencv\modules\core\src\alloc.cpp, line 55
OpenCV Error: Insufficient memory (Failed to allocate 4205568 bytes) in cv::OutOfMemoryError, file C:\build\master_winpack-build-win64-vc14\opencv\modules\core\src\alloc.cpp, line 55
OpenCV Erro

**Comment by AlexeyAB** [comment]
@yxwLearn 

* What OpenCV version do you use?

* What GPU do you have?

* How many CPU RAM do you have?

* What command for training do you use?

* Do you use Windows or Linux?

* What parameters do you use in the `Makefile`?

* Can you show screenshot of this error?

**Comment by yxwLearn** [comment]
@AlexeyAB 
the opencv version is 3.4.0.
GPU  is telas p-100.
CPU RAM is 30G.
The command is darknet.exe detector train data/obj.data yolo-obj.cfg darknet53.conv.74 -map
I use windows server 2016.
I didn't  modify any parametes in the makefile.
sorry,i didn't save the screenshot .

**Comment by AlexeyAB** [comment]
@yxwLearn I fixed memory leak during training with flag `-map` and `random=1` in cfg-file.
