### ISSUE TITLE
YOLO is struggling to detect the nested objects

### ISSUE THREAD

**Issue by siddharth2395** [AlexeyAB/darknet#2519]
@AlexeyAB 

I am trying to detect the custom objects i.e. geometry shapes (square and circle as of now) from an image.

I have trained yolov3 on the [data set](https://github.com/siddharth2395/YOLO-Annotation-Tool/tree/master/Images) (which consist of 1000 images for each object class) with the AVG Loss 0.0568 for 10000 iterations on GPU. 
## Square data
![square](https://user-images.githubusercontent.com/17974529/53724040-02d0e200-3e8f-11e9-8313-846ce21fc66b.JPG)

## Circle data
![circle](https://user-images.githubusercontent.com/17974529/53724041-02d0e200-3e8f-11e9-8d1f-14a082a2614d.JPG)

#### The model detects the individual objects very well.
![output](https://user-images.githubusercontent.com/17974529/53723817-90600200-3e8e-11e9-858a-915b5fa98b30.PNG)

#### But when I tried to detect the objects when one object is the nested object of another, it detects the innermost object only.
![output2](https://user-images.githubusercontent.com/17974529/53724275-8a1e5580-3e8f-11e9-81e9-d4eb70620fbe.PNG)

#### As per my understanding, class probability map should look like this for the given image.
![test-11](https://user-images.githubusercontent.com/17974529/53727165-8db4db00-3e95-11e9-99f8-b28a728a00a2.png)

Now, if we take a closer look at the class probability map it seems that the outer object's class probability cells are getting overlapped with the inner object's class probability cells. 

![test-11-2](https://user-images.githubusercontent.com/17974529/53727398-251a2e00-3e96-11e9-8f66-bd15c050dda5.png)

Whereas the inner object gets the class probability something like this.

![test-11-3](https://user-images.githubusercontent.com/17974529/53727469-55fa6300-3e96-11e9-9d19-bfeef3203b24.png)

I think this is the reason why only the inner object gets detected.

Can you please suggest how should I approach to detect both of the objects?

**Comment by holger-prause** [comment]
Well train your network with the combination which fails - and label accordingly.

From my understanding your network has never seen a combination of both and fails for this reason.

 

Gesendet: Montag, 04. März 2019 um 11:43 Uhr
Von: "Siddharth Bhavsar" <notifications@github.com>
An: AlexeyAB/darknet <darknet@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [AlexeyAB/darknet] YOLO is struggling to detect the nested objects (#2519)


@AlexeyAB

I am trying to detect the custom objects i.e. geometry shapes (square and circle as of now) from an image.

I have trained yolov3 on the data set which consist of 1000 images for each object class with the AVG Loss 0.0568 for 10000 iterations on GPU.
e.g.

Square data



Circle data



The model detects the individual objects very well.



But when I tried to detect the objects when one object is the nested object of another, it detects the innermost object only.



As per my understanding, class probability map should look like this for the given image.



Now, if we take a closer look at the class probability map it seems that the outer object's class probability cells are getting overlapped with the inner object's class probability cells.



Whereas the inner object gets the class probability something like this.



I think this is the reason why only the inner object gets detected.

Can you please suggest how should I approach to detect both of the objects?

**Comment by AlexeyAB** [comment]
@siddharth2395 

> But when I tried to detect the objects when one object is the nested object of another, it detects the 
innermost object only.

You should train on the nested objects.

**Comment by siddharth2395** [comment]
Thank you @holger-prause & @AlexeyAB. After training on combinations model has started detecting nested objects.
