### ISSUE TITLE
raise cuda error prev

### ISSUE THREAD

**Issue by duohappy** [AlexeyAB/darknet#2530]
win10
cuda10
cudnn7.4.2
vs2017
titan X

@AlexeyAB ,hi, when I use `yolo_cpp_dll` to detect object from **two camera**, it raises cuda error prev **afer about 1 min**.
But I use dll file to detect object from **one camera**, it works so well.

![](https://upload-images.jianshu.io/upload_images/7377914-f26b3b3d70aa5c04.jpg)

**Comment by AlexeyAB** [comment]
@duohappy Hi,

>  when I use yolo_cpp_dll to detect object from two camera, it raises cuda error prev afer about 1 min.

Do you use 2 instances of `class Detector` or 1 (which one you use alternating) ?

After that you created instance of `class Detector` then try set `wait_stream=true;`
```cpp
Detector detector;
detector.wait_stream=true;
```

**Comment by duohappy** [comment]
@AlexeyAB ，thanks. 
I complie a camera1.exe and camera2.exe
+ camera1.exe has1 instance of `class Detector`, and camera2.exe has 1 instance of `class Detector`
+ I put camera1.exe and camera2.exe in `yolo_cpp_dll` directory
+ I run camera1.exe, it works fine,then I run camera2.exe. After 1min, they raise error

**Comment by AlexeyAB** [comment]
@duohappy 

Try to use the latest version of Darknet.

Also try to add this line `detector.wait_stream=true;` to each of camera1/2.exe and recompile them.
I just want to understand where is an issue.

**Comment by duohappy** [comment]
@AlexeyAB , :+1: ,thanks for the advice, I will try it tomorrow, because I don't have a GPU computer in my home.
I will feedback in time.

**Comment by duohappy** [comment]
@AlexeyAB hi

I have downloaded the latest version of Darknet, and I add `detector.wait_stream=true` into my code.
but I encounter some problem.


+ details about my code
I create two thread, one thread is for detecting, another is for showing image

+ `detector.wait_stream=true`
I add `detector.wait_stream=true` into my code, and complie camera.exe, I can get about **25 FPS**
I don't add the code, and complie camera.exe, I can get about **38 FPS**

`detector.wait_stream=true`  can **reduce FPS**

--------------------------------

I add `detector.wait_stream=true` into my code, and complie camera1.exe, camera2.exe. I run camera1.exe , then run camer2.exe. 

+ raise error

![](https://upload-images.jianshu.io/upload_images/7377914-d60f048b8d1139a1.jpg)

+ no response

![](https://upload-images.jianshu.io/upload_images/7377914-d4828806be2fed6b.jpg)

if I **kill one of two cameras**, the rest one can continue runing well

**Comment by Jungmo** [comment]
Is there any solutions?
