### ISSUE TITLE
How to change default classes for demo?

### ISSUE THREAD

**Issue by shiji93** [AlexeyAB/darknet#2535]
Good day, I would like to test out my trained weights but I have seen this message **classes: Using default '20'** and got this error **Parameters don't match: in cfg-file classes=3, in data-file classes=20**, as I tried **darknet.exe detector demo data/obj.data yolo-obj.cfg yolo-obj_8000.weights try2.mp4**, I am new to programming please guide me :)

**Comment by AlexeyAB** [comment]
@shiji93 Hi,

What is the value of the parameter `classes=` 
* in obj.data file ?
* in yolo-obj.cfg file ?

**Comment by shiji93** [comment]
both are 3

**Comment by shiji93** [comment]
oh! sorry I made a mistake for obj.data file. I keyed in **class =3** instead of **classes=3** , thank you and much appreciated
