### ISSUE TITLE
loading time takes longer than training

### ISSUE THREAD

**Issue by michaelowenliu** [AlexeyAB/darknet#2538]
I trained yolov3_tiny using batch = 64, subdivisions=16, Geforce 2070, but I found the 'loaded' time is taking a long time, is it depending on the dataset size, because I used around 350k training images. The training log as below:

13528: 6.374037, 6.661028 avg loss, 0.001000 rate, 0.762016 seconds, 865792 images
Loaded: 2.078771 seconds
Region 16 Avg IOU: 0.773306, Class: 0.994652, Obj: 0.794337, No Obj: 0.009058, .5R: 0.961538, .75R: 0.730769,  count: 26
Region 23 Avg IOU: 0.548012, Class: 0.892645, Obj: 0.465613, No Obj: 0.002382, .5R: 0.695652, .75R: 0.173913,  count: 46
Region 16 Avg IOU: 0.792963, Class: 0.998975, Obj: 0.720543, No Obj: 0.003874, .5R: 0.875000, .75R: 0.750000,  count: 8
Region 23 Avg IOU: 0.576427, Class: 0.960810, Obj: 0.390477, No Obj: 0.001445, .5R: 0.666667, .75R: 0.233333,  count: 30
Region 16 Avg IOU: 0.682817, Class: 0.971882, Obj: 0.432281, No Obj: 0.003191, .5R: 0.888889, .75R: 0.444444,  count: 9
Region 23 Avg IOU: 0.518410, Class: 0.790105, Obj: 0.360324, No Obj: 0.002458, .5R: 0.574468, .75R: 0.170213,  count: 47
Region 16 Avg IOU: 0.806788, Class: 0.996262, Obj: 0.654819, No Obj: 0.007724, .5R: 0.952381, .75R: 0.714286,  count: 21
Region 23 Avg IOU: 0.539187, Class: 0.897875, Obj: 0.370225, No Obj: 0.001902, .5R: 0.571429, .75R: 0.257143,  count: 35
Region 16 Avg IOU: 0.656057, Class: 0.948274, Obj: 0.519969, No Obj: 0.003650, .5R: 0.692308, .75R: 0.384615,  count: 13
Region 23 Avg IOU: 0.553123, Class: 0.937453, Obj: 0.511071, No Obj: 0.001958, .5R: 0.709677, .75R: 0.225806,  count: 31
Region 16 Avg IOU: 0.831301, Class: 0.999797, Obj: 0.899822, No Obj: 0.005851, .5R: 1.000000, .75R: 0.846154,  count: 13
Region 23 Avg IOU: 0.481124, Class: 0.918921, Obj: 0.400283, No Obj: 0.002217, .5R: 0.586957, .75R: 0.108696,  count: 46
Region 16 Avg IOU: 0.731185, Class: 0.982158, Obj: 0.675945, No Obj: 0.004784, .5R: 0.937500, .75R: 0.750000,  count: 16
Region 23 Avg IOU: 0.561921, Class: 0.881682, Obj: 0.274186, No Obj: 0.001071, .5R: 0.708333, .75R: 0.125000,  count: 24
Region 16 Avg IOU: 0.745281, Class: 0.993457, Obj: 0.489407, No Obj: 0.003826, .5R: 0.937500, .75R: 0.500000,  count: 16
Region 23 Avg IOU: 0.520365, Class: 0.862576, Obj: 0.299067, No Obj: 0.001620, .5R: 0.636364, .75R: 0.121212,  count: 33
Region 16 Avg IOU: 0.716617, Class: 0.999013, Obj: 0.796141, No Obj: 0.004196, .5R: 0.800000, .75R: 0.600000,  count: 10
Region 23 Avg IOU: 0.632297, Class: 0.975164, Obj: 0.474184, No Obj: 0.001381, .5R: 0.720000, .75R: 0.360000,  count: 25
Region 16 Avg IOU: 0.725159, Class: 0.967802, Obj: 0.595034, No Obj: 0.009065, .5R: 0.840000, .75R: 0.560000,  count: 25
Region 23 Avg IOU: 0.462998, Class: 0.852732, Obj: 0.337561, No Obj: 0.002500, .5R: 0.408163, .75R: 0.163265,  count: 49
Region 16 Avg IOU: 0.785183, Class: 0.998037, Obj: 0.747309, No Obj: 0.004032, .5R: 0.900000, .75R: 0.700000,  count: 10
Region 23 Avg IOU: 0.649277, Class: 0.982228, Obj: 0.581003, No Obj: 0.001875, .5R: 0.843750, .75R: 0.343750,  count: 32
Region 16 Avg IOU: 0.821387, Class: 0.905639, Obj: 0.860426, No Obj: 0.004478, .5R: 0.916667, .75R: 0.833333,  count: 12
Region 23 Avg IOU: 0.512905, Class: 0.881467, Obj: 0.501052, No Obj: 0.002306, .5R: 0.628571, .75R: 0.257143,  count: 35
Region 16 Avg IOU: 0.737724, Class: 0.998918, Obj: 0.802067, No Obj: 0.002844, .5R: 0.900000, .75R: 0.700000,  count: 10
Region 23 Avg IOU: 0.566044, Class: 0.773522, Obj: 0.406455, No Obj: 0.001130, .5R: 0.600000, .75R: 0.320000,  count: 25
Region 16 Avg IOU: 0.744324, Class: 0.997872, Obj: 0.747230, No Obj: 0.004065, .5R: 0.928571, .75R: 0.642857,  count: 14
Region 23 Avg IOU: 0.567133, Class: 0.887070, Obj: 0.427976, No Obj: 0.001590, .5R: 0.666667, .75R: 0.250000,  count: 24
Region 16 Avg IOU: 0.697264, Class: 0.910167, Obj: 0.652369, No Obj: 0.006255, .5R: 0.785714, .75R: 0.642857,  count: 14
Region 23 Avg IOU: 0.498246, Class: 0.866554, Obj: 0.320587, No Obj: 0.001067, .5R: 0.611111, .75R: 0.166667,  count: 18
Region 16 Avg IOU: 0.794556, Class: 0.996889, Obj: 0.838414, No Obj: 0.005815, .5R: 1.000000, .75R: 0.666667,  count: 15
Region 23 Avg IOU: 0.533370, Class: 0.988005, Obj: 0.540701, No Obj: 0.001252, .5R: 0.535714, .75R: 0.285714,  count: 28

 13529: 5.911125, 6.586038 avg loss, 0.001000 rate, 0.746339 seconds, 865856 images
Loaded: 2.018668 seconds

**Comment by AlexeyAB** [comment]
@michaelowenliu Hi,


> loading time takes longer than training 

To avoid this you should:
* use this repository https://github.com/AlexeyAB/darknet instead of https://github.com/pjreddie/darknet

* compile Darknet with `OPENCV=1` in the Makefile (may be you should run training with `-dont_show` flag if you train on remote server)

* for AMD CPU change `3` to `12` here: https://github.com/AlexeyAB/darknet/blob/b751bac17505a742f149ada81d75689b5e692cde/src/detector.c#L173

* Use fast SSD disk instead of HDD

**Comment by michaelowenliu** [comment]
@AlexeyAB Hi, Alexey, thanks a lot. Now it becomes faster.

btw, I may ask one more question about the training annotations. Do we need to label a tiny object in an image, e.g. I am using 1920*1080 images to training yolov3-tiny (416*416), and my target object sometimes is smaller than 20*20 in the images. Currently avg loss is larger than 6.0, and mAP is less than 30% (5 classes). I suspect the tiny label could be a problem, because after resizing to 416*416, such tiny object disappears. what is your idea?

**Comment by AlexeyAB** [comment]
@michaelowenliu Hi,

I would recommend you to train https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov3-tiny_3l.cfg with `width=832 height=832` or 1024x1024 

If CUDA out of memory error occurs, then set `batch=64 subdivisions=64`

In this case you will be able to detect smaller objects.


Otherwise, if you use width=416 height=416, you don't have to label objects that are smaller than 1x1 pixels after the images had been resized to 416x416.

**Comment by michaelowenliu** [comment]
@AlexeyAB  Hi, actually I don't want to detect a very small object in practice, what I mean is do I need to eliminate the labels of tiny objects which have already been labelled in a training image, and ignore these tiny objects during training. Is it a way to decrease training loss?

2. Currently the aspect ratio of training images is around 2:1 (1920 by 1080), if set both width and height as 416 in cfg file, does it affect the final loss?

Now I am trying to figure out how to decrease the training loss which is larger than 6.0.

**Comment by AlexeyAB** [comment]
@michaelowenliu 

1. Small objects will be removed automatically during training, so it doesn't matter will you ignore or delete it: https://github.com/AlexeyAB/darknet/blob/b751bac17505a742f149ada81d75689b5e692cde/src/data.c#L374-L379

2. If you train and detect with the same image sizes and network size, then it doesn't matter do you use square 416x416 or rectangle 608x288 network sizes.

May be your dataset is too difficult, so avg loss 6.0 is a good value for it.
If it doesn't decrease, try to decrease 4x times the learning_rate and continue training.
Or try to train yolov3-tiny_3l.cfg
