### ISSUE TITLE
getting -nan for avg 

### ISSUE THREAD

**Issue by adouwitti** [AlexeyAB/darknet#2540]
i tried to train yolov3 on custom datasets. when ever i train it , i am getting this error. 
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.498698, .5R: -nan, .75R: -nan,  count: 0
as you said : " Note: If during training you see nan values for avg (loss) field - then training goes wrong, but if nan is in some other lines - then training goes well." 

my dataset is training set is around 250 images . does  the number of images affect the training ?  this is the configuration of Makefile : 
.GPU =1 
cudnn =0
opencv=0 
cudnn_half=0 

what should i do ? thanks in advance @AlexeyAB 

![image](https://user-images.githubusercontent.com/44825125/53865645-a276a780-402a-11e9-9f9d-79a89c4fc0af.png)

**Comment by AlexeyAB** [comment]
@adouwitti Hi,

This is normal: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

> Note: If during training you see nan values for avg (loss) field - then training goes wrong, but if nan is in some other lines - then training goes well.

**Comment by adouwitti** [comment]
ok 
thanks @AlexeyAB
