### ISSUE TITLE
How to use gpu #1 for detecting?

### ISSUE THREAD

**Issue by xvyaward** [AlexeyAB/darknet#2545]
Hi! Thanks for your implementation.
I'm using 4 GPUs, model K80. I found that I cannot use multiple gpus on detecting, and currently darknet is using gpu number 0.

![image](https://user-images.githubusercontent.com/32446763/53891551-f9ea3700-406d-11e9-88fc-1df0d28d1131.png)

However, I'm trying to process another DL program(SRGAN) simultaneously with darknet, and it is also using gpu 0. Memory is enough so I can run both program but both runs much slower because gpu #0 have to process all.
So I want to process darknet with GPU 1 (or just except gpu 0), how can I do this?

below image is gpu usage of both program running

![image](https://user-images.githubusercontent.com/32446763/53891587-10908e00-406e-11e9-80e2-052eeacc0d00.png)

**Comment by WEITINGLIN32** [comment]
@xvyaward 
Do you train with the command ./darknet detector train cfg/.data cfg/.cfg -weight -gpus 0,1,2,3 ??

**Comment by xvyaward** [comment]
@WEITINGLIN32 
I didn't train. I used given weight file, and that is test(inference) mode.
I tested with the command
./darknet detector demo ./cfg/coco.data ./cfg/yolov3.cfg ./yolov3.weights test/240_bicubic_short.mp4 -i 0 -thresh 0.5 -dont_show

**Comment by WEITINGLIN32** [comment]
@xvyaward 
you need to add -gpus 0,1,2,3
like ./darknet detector demo ./cfg/coco.data ./cfg/yolov3.cfg ./yolov3.weights test/240_bicubic_short.mp4 -i 0 -thresh 0.5 -gpus 0,1,2,3 -dont_show
can you try it?

**Comment by AlexeyAB** [comment]
@xvyaward Hi,

Flag `-i 1` is for using GPU-1 instead of GPU-0

So just use:
`./darknet detector demo ./cfg/coco.data ./cfg/yolov3.cfg ./yolov3.weights test/240_bicubic_short.mp4 -i 1 -thresh 0.5 -dont_show`

----

https://github.com/AlexeyAB/darknet#how-to-use-on-the-command-line

> Yolo v3 Tiny on GPU #0: darknet.exe detector demo cfg/coco.data cfg/yolov3-tiny.cfg yolov3-tiny.weights -i 0 test.mp4

**Comment by yingzhec** [comment]
Where did you guys find the option '-i', I didn't see it in file 'detector.c'
