### ISSUE TITLE
segmentation error (core dumped ) 

### ISSUE THREAD

**Issue by adouwitti** [AlexeyAB/darknet#2547]
hi , when i try to test , am getting segmentation error , it doesn't detect completely .  you can see  here 
![image](https://user-images.githubusercontent.com/44825125/53931059-947a6280-40ce-11e9-9bdb-a38f1947b33c.png).  
thanks in advance.

**Comment by wonchulSon** [comment]
same issue

**Comment by AlexeyAB** [comment]
@adouwitti Hi,

* What parameters do you use in the Makefile?

* Try to do `dos2unix ./head.names` command for your `head.names` and `head.data` files
May be previously you should install `sudo apt-get install dos2unix`

**Comment by adouwitti** [comment]
@AlexeyAB   thanks for your response , 


1. These are the parameters that i set in the makefile : 
     .GPU = 1 
       .CUDNN = 0
      .OPENCV= 0
        .CUDNN_HALF=0 
when i tried to compile with opencv = 1 or cudnn = 1 , some errors have occurred, so i set only GPU to 1. 
 2. i have converted to unix format, the segmentation error has disappeared , but another error has occurred . " not compiled with opencv , saving to prediction.png instead . 
i didn't compile darknet with opencv , does the error occur because of that ? 
thanks

**Comment by AlexeyAB** [comment]
@adouwitti 

> i have converted to unix format, the segmentation error has disappeared , but another error has occurred . " not compiled with opencv , saving to prediction.png instead .
> i didn't compile darknet with opencv , does the error occur because of that ?

It isn't an error.
It is just information message, that without OpenCV it can't show this image in the Window.

**Comment by adouwitti** [comment]
ok got it thank you @AlexeyAB
