### ISSUE TITLE
Image Cannot Loaded During Training Custom Dataset

### ISSUE THREAD

**Issue by amar-mustaqim** [AlexeyAB/darknet#2550]
Hi. I'm still new to Darknet and YOLO. I'm trying to train my own dataset that consist of 9000 images(3 classes) on Windows 10 with Geforce 920M. But unfortunately this error appeared. Any suggestion on how to solve it? 
![training error2](https://user-images.githubusercontent.com/31053816/53941569-61969580-40f3-11e9-8685-972bd36862d3.PNG)

**Comment by yxwLearn** [comment]
@amar-mustaqim 
you image road is wrong，try  to find these image in the dir "/data/img",make sure it is exist.
and your gpu RAM is to small ,so you should modify yolo-obj.cfg ,set subvision=32 or 64,if it doesn't work,set  random =0.

**Comment by amar-mustaqim** [comment]
Thank you. It works! Just need to make sure that the images and the other files are in the right path
