### ISSUE TITLE
Where can I find IMTYPE?

### ISSUE THREAD

**Issue by gameon67** [AlexeyAB/darknet#2558]
Hi again @AlexeyAB , in `image.c` I need to make modification in order to add more extension option like this 
```
void save_image_options(image im, const char *name, IMTYPE f, int quality)
{
    char buff[256];
    //sprintf(buff, "%s (%d)", name, windows);
    if (f == PNG)       sprintf(buff, "%s.png", name);
    else if (f == BMP) sprintf(buff, "%s.bmp", name);
    else if (f == TGA) sprintf(buff, "%s.tga", name);
    else if (f == JPG) sprintf(buff, "%s.jpg", name);
    else if (f == NOEXT) sprintf(buff, "%s", name)
    else               sprintf(buff, "%s.png", name);
```
But it shows error : 
`error: ‘NOEXT’ was not declared in this scope` 

I couldn't find a class or a file that define `IMTYPE`. Can you help me with this?

**Comment by AlexeyAB** [comment]
@gameon67 Hi,

https://github.com/AlexeyAB/darknet/blob/b751bac17505a742f149ada81d75689b5e692cde/include/darknet.h#L105-L108

**Comment by gameon67** [comment]
@AlexeyAB Thanks so much
