### ISSUE TITLE
Multiple detected classes on same object

### ISSUE THREAD

**Issue by gameon67** [AlexeyAB/darknet#2571]
Hi again @AlexeyAB , I've trained my own custom dataset successfully without any big problem. But there are some rare cases when I try to detect test image, it will draw 2 bounding boxes (different label) on the same object, like this 

Isn't in YoloV3, each class score is predicted using logistic regression and a threshold is used to filter multiple classes detection at the same object?

**Comment by AlexeyAB** [comment]
@gameon67 Hi,

Logistic (sigmoid) regreassion in the Yolo v3 can detect several different objects for the one anchor box (multi label classification) https://github.com/AlexeyAB/darknet/issues/1695#issuecomment-426016524
So it write several object names for the one bbox: https://www.youtube.com/watch?v=69Ii3HjUiTM

But in your case, there are 2 bboxes, so it just detected 2 objects in 2 different anchors. If they are wrong - then this is False Positive.

**Comment by gameon67** [comment]
@AlexeyAB Okay thanks for the clarification
