### ISSUE TITLE
Lots of nans when training with channel=1

### ISSUE THREAD

**Issue by readicculus** [AlexeyAB/darknet#2576]
I have 8-bit single channel grayscale .tif images that I''m trying to train with yolov3 cfg.
If I make all the images 3 channel it works great but when I try to train with single channel I just get a lot of nans in the training results and even after a few hundred iterations doesnt change.

I'm training with the yolov3 pretrained weights and only changes to the yolov3 cfg are removing random from the yolo layers, routing -1, 11 w/ stride=4 instead of -1, 360, channels=1, hue=0

Any advice would be  appreciated.  Do I need to partition the pretrained weights differently for a single channel input?

Input dims: 512x640
batch 64
subdiv 32

**Comment by AlexeyAB** [comment]
> If I make all the images 3 channel it works great

* Did you train the model by using  3-channels Tiff or JPG images?

* Did you add here line for Tiff-image? https://github.com/AlexeyAB/darknet/blob/dd27d67f58f563bb6bb2af7bb6374f8a59cebcde/src/utils.c#L245-L254

* Do you get any warning messages during Training?

----

> Do I need to partition the pretrained weights differently for a single channel input?

* You should train the model without pre-trained weights files

**Comment by readicculus** [comment]
ok, no did not add a line.  I've trained with 3 channel jpg worked very well, training with single channel with channel=3 also did not work.  No warnings or anything.  I just remade the dataset as single channel png files ill update this in a bit.

**Comment by AlexeyAB** [comment]
* Try to add the line `find_replace_extension(output_path, ".tiff", ".txt", output_path); ` 
recompile and try to train again.
If it will help, I will add this fix to the code.

* Also can you show screenshot of training process?
