### ISSUE TITLE
The command MAP just does nothing for me

### ISSUE THREAD

**Issue by MarviB16** [AlexeyAB/darknet#2596]
Hi,

when i run the command map:

> ./darknet detector map x64/Release/data/obj.data cfg/yolov3_efr.cfg backup/yolov3_efr_10000.weights -thresh 0.25

Nothing happens:

marvin@mangup: /darknet$ ./darknet detector map x64/Release/data/obj.data cfg/yolov3_efr.cfg backup/yolov3_efr_10000.weights -thresh 0.25
marvin@mangup: /darknet$ 

What am i doing wrong or is it a bug?

**Comment by AlexeyAB** [comment]
@MarviB16 Hi,

Use this repository https://github.com/AlexeyAB/darknet instead of this https://github.com/pjreddie/darknet
