### ISSUE TITLE
why need to change  return EXIT_FAILURE to exit(EXIT_FAILURE) in demo.c

### ISSUE THREAD

**Issue by VonSdite** [AlexeyAB/darknet#2601]
In [release version](https://github.com/AlexeyAB/darknet/releases), in `demo.c` line 80

![image](https://user-images.githubusercontent.com/25704948/54332004-4679d780-4657-11e9-9d41-dead9112c50c.png)

In [the lastest version](https://github.com/AlexeyAB/darknet/blob/master/src/demo.c#L78), in `demo.c`  line  78

![image](https://user-images.githubusercontent.com/25704948/54332030-5ee9f200-4657-11e9-8cc7-b9088986da94.png)

I want to know, why need to change  `return EXIT_FAILURE;` to `exit(EXIT_FAILURE);` ?

![image](https://user-images.githubusercontent.com/25704948/54329565-20e7d080-464d-11e9-81ad-69c13d56df60.png)

# Recently, I have a problem while saving my video.
## The passing of things
when I use opencv 3.4.5, I type the command line like this:
```
darknet.exe detector demo cfg/coco.data cfg/yolov3-tiny.cfg weights/yolov3-tiny.weights data/1.mp4 -out_filename res.avi
```
As a result, the video I got was empty.
![image](https://user-images.githubusercontent.com/25704948/54329710-c8fd9980-464d-11e9-9fe0-ffc5abe4bbf0.png)

I tried to find a solution， but nothing was found.(opencv_world345.dll and opencv_ffmpeg345_64.dll were placed near with darknet.exe)

![image](https://user-images.githubusercontent.com/25704948/54329800-45907800-464e-11e9-9e99-988ee86b3e87.png)

Then, I saw the command output `"Stream closed."`. I found it in the `demo.c`.

But, first, I suspect the problem with opencv345, so I delete my opencv 3.4.5， and download opencv 3.4.0， and recompile the `darknet.exe`.

It worked, but something wrong.
There is no time displayed below the video, and the time bar cannot be dragged.
![image](https://user-images.githubusercontent.com/25704948/54331542-67412d80-4655-11e9-8212-2db7f75da52c.png)

**This is too desperate！**

And I found the `release darknet.exe`, [there](https://github.com/AlexeyAB/darknet/releases)

I download it, and try it to save video, and ..... it worked and succeeded.
![image](https://user-images.githubusercontent.com/25704948/54331703-239af380-4656-11e9-842c-6376290b3c11.png)

And I want to know what different between **my darknet.exe** and **release darknet.exe**, 
so I open the `demo.c`, and diff them. 
I got like the pic.

![image](https://user-images.githubusercontent.com/25704948/54329565-20e7d080-464d-11e9-81ad-69c13d56df60.png)

So I change the `exit(EXIT_FAILURE);` to `return (void *)EXIT_FAILURE;`. And recompile `darknet.exe`, finally it solved my problem.

And I just want to know, What is the reason for doing this ( `exit(EXIT_FAILURE);` )? Is there any wrong to `return (void *)EXIT_FAILURE;`?

![image](https://user-images.githubusercontent.com/25704948/54331817-9ad08780-4656-11e9-9abb-c8e2eefdd8bf.png)

**Comment by AlexeyAB** [comment]
@VonSdite Hi, Thanks!

I fixed it: https://github.com/AlexeyAB/darknet/commit/790de0543560bcd846a1a5e62137c59e97122f5a

**Comment by VonSdite** [comment]
Thank you!!!
