### ISSUE TITLE
Yolov3-Tiny vs Yolov3-Tiny-Xnor [Comparison]

### ISSUE THREAD

**Issue by dexception** [AlexeyAB/darknet#2605]
Yolov3-Tiny-XNOR
After 2K Iterations
![image](https://user-images.githubusercontent.com/31848222/54341139-1c2c1800-465f-11e9-9ca6-c5d92a3d477b.png)

 
After 8K Iterations
 
![image](https://user-images.githubusercontent.com/31848222/54341143-20583580-465f-11e9-9152-817c25091988.png)

After 10k iterations
 
![image](https://user-images.githubusercontent.com/31848222/54341150-264e1680-465f-11e9-9e74-036bcce0f3cf.png)

Yolov3-Tiny
After 1,76,000 Iterations 
![image](https://user-images.githubusercontent.com/31848222/54341161-2b12ca80-465f-11e9-89a0-c2d02d38e093.png)

I have a couple of queries:
1. The bounding boxes of XNOR model don't seem to be accurate enough.
2. The performance improvement is only marginal on recorded video 40 FPS vs 50 FPS on the same gpu.

Thanks.

**Comment by AlexeyAB** [comment]
@dexception Hi,

> Yolov3-Tiny-XNOR
> After 10k iterations

> Yolov3-Tiny
> After 1,76,000 Iterations


* Did you train Yolov3-Tiny-XNOR - `10k` iterations and train Yolov3-Tiny `176k` iterations?

* What result do you get after training Yolov3-Tiny-XNOR the same 176k iterations?

* What GPU do you use?

* yolov3-tiny is too small, so there is a bottleneck on the 1st and last layers that should be FP32. Also on modern GPUs yolov3-tiny too small so there is added bottleneck on CPU. So on modern GPU better to use `yolov3-spp_xnor_obj.cfg`  https://github.com/AlexeyAB/darknet/issues/2365#issuecomment-462923756

**Comment by dexception** [comment]
1. Xnor was giving me plenty of false detections. So i stopped the training after 10K iterations and added an additional 40K negative dataset. 
2. I will share the results of Yolov3-Tiny with 40 K negative images after 176K iterations. It is still running.
![image](https://user-images.githubusercontent.com/31848222/54408766-33274480-4709-11e9-849d-2d70cc7aaf31.png)


3. Training GPU is 1080 TI. Inference on my laptop Nvidia 940 MX
4. Thanks for this info. It is for this reason(High CPU) i not been able to scale the solution and forced to use other detectors. Let me retrain this on my current dataset and will post the results.

**Comment by dexception** [comment]
Xnor Output after 176K iterations with 40K Negative Dataset. 
As you can see it is not Accurate in complex situations.

Will post a day after tomorrow about yolov3-spp_xnor_obj.cfg.

![image](https://user-images.githubusercontent.com/31848222/54414299-b1daac80-471e-11e9-973e-aeb432ebe621.png)

**Comment by AlexeyAB** [comment]
@dexception 

> Will post a day after tomorrow about yolov3-spp_xnor_obj.cfg.

Try to train `yolov3-spp_xnor_obj.cfg.` with this exactly this `
darknet53_448_xnor.conv.74` pre-trained weights: https://drive.google.com/open?id=1IT-vvyxRLlxY5g9rJp_G2U3TXYphjBv8

**Comment by dexception** [comment]
I will retrain with the new file and get back to you in a couple of days.

**Comment by deimsdeutsch** [comment]
@AlexeyAB 
After training for about 50K iterations. The detection is definitely better but the bounding boxes are all over the place. I am getting better intersection accuracy with yolov3-tiny then xnor variants. 

The only issue with yolov3-tiny is that it is always consuming more than 2 cores Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz which means that i will have to have scalable xeons on machine which increases the cost of the solution 5 times.

**Comment by dexception** [comment]
@AlexeyAB 
After training for about 50K iterations. The detection is definitely better but the bounding boxes are all over the place. I am getting better intersection accuracy with yolov3-tiny then xnor variants.

The only issue with yolov3-tiny is that it is always consuming more than 2 cores Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz which means that i will have to have scalable xeons on machine which increases the cost of the solution 5 times.

**Comment by AlexeyAB** [comment]
@dexception 

> After training for about 50K iterations. The **detection is definitely better** but the bounding boxes are all over the place. I am getting better intersection accuracy with yolov3-tiny then xnor variants.

Do you mean that `yolov3-spp_xnor_obj.cfg` has more True Positives, byt `yolov3-tiny.cfg` has higher IoU?
What mAP do you have for `yolov3-spp_xnor_obj.cfg`, `yolov3-tiny-xnor.cfg`  and `yolov3-tiny.cfg` ?

> The only issue with yolov3-tiny is that it **is always consuming more than 2 cores** Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz which means that i will have to have scalable xeons on machine which increases the cost of the solution 5 times.

Do you use `yolov3-tiny.cfg` on CPU instead of GPU?

----

In your case with many small object (faces) may be it's better to train the model with higher resolution `width=832 height=832` in cfg-file or 1024x1024.

**Comment by deimsdeutsch** [comment]
yolov3-tiny.cfg@416 is giving me better  accuracy both in terms of detection and correct intersection than yolov3-spp_xnor_obj.cfg.

I am ignoring the map results and instead verifying the output manually on the test dataset of 100 images  because IOU accuracy is more important to me.

I have trained yolov3-tiny.cfg on the exact same GPU machine.
I don't know the internals of how xnor is working but the results are not good. 

If you can release the C++ wrapper for yolo2_light i would like to compare the TensorRT performance with yolo2_light of yolov3-tiny vs OpenVino.

**Comment by dexception** [comment]
yolov3-tiny.cfg@416 is giving me better  accuracy both in terms of detection and correct intersection than yolov3-spp_xnor_obj.cfg.

I am ignoring the map results and instead verifying the output manually on the test dataset of 100 images  because IOU accuracy is more important to me.

I have trained yolov3-tiny.cfg on the exact same GPU machine.
I don't know the internals of how xnor is working but the results are not good. 

If you can release the C++ wrapper for yolo2_light i would like to compare the TensorRT performance with yolo2_light of yolov3-tiny vs OpenVino.

**Comment by AlexeyAB** [comment]
@dexception Can you show example of detection by using yolov3-spp_xnor_obj.cfg on your image?

**Comment by dexception** [comment]
![image](https://user-images.githubusercontent.com/31848222/54490766-d2516500-48de-11e9-8adc-0eabc2341495.png)

**Comment by dexception** [comment]
Can you share your plans to release the c++ wrapper for yolo2_light ?

**Comment by AlexeyAB** [comment]
Do you mean C++ API for DLL/SO library that is based on yolo2_light?

Currently there is no plans to add C++ wrapper for yolo2_light. May be I just will make it possible to compile yolo2_light in both C and C++, so you wil can add these files to your code - to built-in it to your C/C++ code.

**Comment by dexception** [comment]
@AlexeyAB Any update on how can i use yolo2_light with c++ ?
