### ISSUE TITLE
Multi-GPUs training failed

### ISSUE THREAD

**Issue by phonygene** [AlexeyAB/darknet#2606]
win10
Rtx2080ti x 2
Driver Version: 419.35       CUDA Version: 10.1
I'm using yolov3, master-branch downloaded on 2019/03/05.

trying to train with command : 
darknet.exe detector train breakkk.data yolov3.cfg yolov3_1000.weights -gpus0,1

But always only single working, another idle.
I can train with either gpu0 or gpu1 by use flag -gpus0  or  -gpus1, but can't use both.

I've read some issues here or article from internet but seems there's no one has same problem.

**Comment by AlexeyAB** [comment]
@phonygene Hi,

Try to add space between `-gpus` and `0,1`
For example,
`darknet.exe detector train breakkk.data yolov3.cfg yolov3_1000.weights -gpus 0,1`

If it doesn't help, then show screenshot of output of this cmd-file?
[nvidia-smi .cmd.txt](https://github.com/AlexeyAB/darknet/files/2967048/nvidia-smi.cmd.txt)

**Comment by phonygene** [comment]
@AlexeyAB thanks for your help,

Yes I added the space and it works fine now.
