### ISSUE TITLE
problem with yolo_console_dll.exe

### ISSUE THREAD

**Issue by hadi-ghnd** [AlexeyAB/darknet#2614]
I ran the **yolo_console_dll.exe** for tracking on custom data, but the results are strange looking.

This is the original video:

![test mp4_snapshot_06 41_ 2019 03 14_16 43 01](https://user-images.githubusercontent.com/24352869/54390279-7685a280-4678-11e9-8d1b-922370bfc35a.jpg)

and this is the resulting video:

![result avi_snapshot_00 03_ 2019 03 14_16 42 23](https://user-images.githubusercontent.com/24352869/54390292-800f0a80-4678-11e9-83a4-835bfe53ed78.jpg)

What parameters do I have to fix before running the program?

**Comment by AlexeyAB** [comment]
Try to comment this line: https://github.com/AlexeyAB/darknet/blob/7a854302efb7adba80d5e8a747ad5e5ec384a226/src/yolo_console_dll.cpp#L410

----

And change here `2` to `1`: https://github.com/AlexeyAB/darknet/blob/7a854302efb7adba80d5e8a747ad5e5ec384a226/src/yolo_console_dll.cpp#L188

**Comment by hadi-ghnd** [comment]
@AlexeyAB Thank you for the advice.

I tried your changes, but the result is still not good:

![result avi_snapshot_00 05_ 2019 03 14_17 17 21](https://user-images.githubusercontent.com/24352869/54392099-1e9d6a80-467d-11e9-84cf-2a7f05cbd698.jpg)


I can reduce the font size, but I think I need to change the threshold or nms somewhere.

**Comment by AlexeyAB** [comment]
Comment this line: 
https://github.com/AlexeyAB/darknet/blob/7a854302efb7adba80d5e8a747ad5e5ec384a226/src/yolo_console_dll.cpp#L278

**Comment by hadi-ghnd** [comment]
@AlexeyAB I commented that line but still the same results are showing:

![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/24352869/54393436-8b663400-4680-11e9-984a-fc4b4886d735.gif)

I also increased the `detector.nms` to 0.5 but didn't help. The results were the same. Maybe the threshold should be higher.

**Comment by AlexeyAB** [comment]
@hadi-ghnd 


* Did you change anything else in the source code?

* Do you use the latest version of Darknet?

* Can you share your files: cfg, weights, mp4 ?

**Comment by hadi-ghnd** [comment]
@AlexeyAB 

- No I just changed the font size for "FPS Detection label"
- Yes I downloaded it 2 days ago
- These are the files:

-- ### cfg

[yolov3-tiny_obj.cfg.txt](https://github.com/AlexeyAB/darknet/files/2968691/yolov3-tiny_obj.cfg.txt)

--###weights
https://drive.google.com/file/d/1IcSyIfMYU_eglz63jpwuoUKwaOohslP5/view?usp=sharing

--###mp4

https://drive.google.com/file/d/1HadtfE-7ym0EHkEtvtSlLEhgQNqOvbnd/view?usp=sharing



I tested on a higher quality video, but the detection seems not to be working. Is there any other part that I can modify for this to work like the **detect** program?


![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/24352869/54394883-8d31f680-4684-11e9-88a3-f5894f7d1092.gif)

**Comment by AlexeyAB** [comment]
* What repository did you use for training?

* What params did you use in the Makefile?

* **Do you use corect cfg-file which corresponds to your weights-file?**

* What mAP can you get?

* Can you detect cars on the images?

----

I just run this command:

`./darknet detector demo cfg/coco.data yolov3-tiny_obj.cfg yolov3-tiny_obj_14600.weights test1.mp4 -out_filename result.mp4`

And get this result:

![result](https://user-images.githubusercontent.com/4096485/54395742-c2106e80-46c1-11e9-9e87-912657018085.gif)

**Comment by hadi-ghnd** [comment]
@AlexeyAB 
I used the same repository. Actually I used these files instead of the coco ones:

[obj.data.txt](https://github.com/AlexeyAB/darknet/files/2968763/obj.data.txt)
[obj.names.txt](https://github.com/AlexeyAB/darknet/files/2968764/obj.names.txt)

but for the weight and cfg files I used the same as the sent ones.

![output_1_20161015_080000-081559 avi_snapshot_00 06_ 2019 03 14_18 51 58](https://user-images.githubusercontent.com/24352869/54396729-5959cf80-468a-11e9-8a54-45ed4fbfa85a.jpg)

However there might be some other changes, because I cloned the repository again from scratch. I will try to run it again and let you know about the results.

**Comment by AlexeyAB** [comment]
In your `obj.data` file there is `classes= 6`
but in your `yolov3-tiny_obj.cfg` file there is `classes= 80` and filters=255 for 80 classes.

After that I changed `filters=33 classes=6` in both `[yolo]` layers, as described here: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects
the detection works well in both `darknet.exe` and `yolo_console_dll.exe`

**Comment by hadi-ghnd** [comment]
@AlexeyAB Thank you for your kind help! I corrected the cfg file as you said and it worked.
Just one more quick question. Is it possible to build **darknet.sln** after building **yolo_console_dll**? Or should it be in a different directory?

**Comment by AlexeyAB** [comment]
@hadi-ghnd Yes you can.

**Comment by arnaud-nt2i** [comment]
@AlexeyAB
How is it possible to use yolo_console_dll on video file but capping frame reading (FPS capture) to 25 fps (and not maximum speed ~126)?
I would like to use yolo on very high-resolution MP4 but doing detection every 10 frames or so, using Optiflow tracking in between.

Appar from this pb (videos are played too fast), everything is fine, I'm on W10, OpenCV 4.5 compiled with CUDA.
