### ISSUE TITLE
Class activation maps

### ISSUE THREAD

**Issue by kocica** [AlexeyAB/darknet#2623]
Hi all,

I am currently training models on real and synthetic datasets and I would like to visually compare activation maps of each model like one can do with keras and tensorflow (eg. [click](https://towardsdatascience.com/live-visualisations-of-cnns-activation-maps-using-tensorflow-js-27353cfffb43))

Is there any way how can I visualize class activation maps from weights?
Thanks for any help.

**Comment by kocica** [comment]
This tool was very helpful: https://gfycat.com/pleasinglonelyhackee.

**Comment by tylertroy** [comment]
HI @kocica , Any further info on where we can find the tool visualized in your link?

**Comment by SaraPiresNobrega** [comment]
Hy @tylertroy and @kocica ,

Did you find how to observe class activation maps from weight files ?
