### ISSUE TITLE
Windows Training - no GPU

### ISSUE THREAD

**Issue by ed-spatialsauce** [AlexeyAB/darknet#2625]
Hey,

I just setup an environment following the instructions on the ReadMe. The process was pretty smooth, no errors, and I made sure I am meeting all of the latest requirements. The only problem I have is when training it seems to only be using the CPU. Maybe the only step I didn't understand exactly was:

`8. [necessary only with CUDA] Customize the CMakeLists.txt with the preferred compute capability`

I couldn't work out exactly what I had to change or if I had to change anything at all.

I did run ` .\vcpkg install pthreads opencv[cuda]` as well.

Any ideas what I need to do to get training working with my GPU?

I'm using all of the latest requirements, and I built darknet running build.ps1 instead of opening it with VS2017.

Thanks!

**Comment by ed-spatialsauce** [comment]
A side note, but could be related to why the GPU is not being used. The ReadMe talks a lot about working out of `darknet\build\darknet\x64` directory, especially around training your own custom data. I actually found myself

**Comment by AlexeyAB** [comment]
@ed-spatialsauce Hi,

* Did you install the CUDA after you have installed the MSVS?

* Can you open your Darknet folder in Cmake-gui and show screenshot?

* Is there enabled CUDA?

![image](https://user-images.githubusercontent.com/4096485/54489678-d7eb8280-48bf-11e9-87de-9724a0e6852c.png)


> I'm using all of the latest requirements, and I built darknet running build.ps1 instead of opening it with VS2017.

* Try to build Darknet by using VS, does it help?

**Comment by ed-spatialsauce** [comment]
CUDA wasn't enabled when I checked Cmake gui. The compiler wasn't being found, so I just uninstalled CUDA and did a clean reinstall. I then used the Cmake-gui to check and setup everything, and then ran the build.ps1 script again. 

I am retraining now and it's using the GPU.

Thank you!

**Comment by naufil601** [comment]
@ed-spatialsauce do you have CUDA 10 ?
I'm trying to train on GPU with Cuda 9.2. 
**.\vcpkg install pthreads opencv[cuda]** gives error, hence I ran the other command.
But I guess the training is still happening on CPU.
![image](https://user-images.githubusercontent.com/18327182/54754582-a1866e00-4c05-11e9-88c2-e97e6a88e92e.png)
This is the screenshot of what I get after loading of network

**Comment by ed-spatialsauce** [comment]
@naufil601 I installed CUDA 10 and the latest cuDNN.

When I reinstalled everything I followed this OpenCV guide to make sure I did it right. Maybe it's worth following this as well: https://www.learnopencv.com/install-opencv3-on-windows/

**Comment by naufil601** [comment]
@AlexeyAB I made clean installation of CUDA 10.
When I open the directory using cmake gui, to enable CUDA before building the project with build.ps1, I get the following error.
![image](https://user-images.githubusercontent.com/18327182/54912647-ddc21300-4f12-11e9-8662-3047ba2fcff4.png)

Any help is appreciated

**Comment by AlexeyAB** [comment]
@naufil601 Hi,

There is no error. It is just a information message.
Continue installation: Configure -> Generate -> Open Project -> x64 & Release -> Build ALL

**Comment by naufil601** [comment]
Thanks for reply. As mentioned in my comment, when I click Configure button, the above output is what I get.
I do not understand why the CUDA enable options gets unchecked if there is no error

**Comment by AlexeyAB** [comment]
@naufil601 

Set `grouped` checkbox at the top pannel of Cmake
Set `ENABLED_CUDA`
And set compute model = 6.1

What Windows version do you use?

**Comment by naufil601** [comment]
@AlexeyAB  I'm using windows 10.

I set the compute model number to '61' in CMakeLists.txt file. 

I solved the error of ENABLED_CUDA by selecting visual studio 64 compiler before Configuring.

Now when I run darknet.exe from the Release folder I get error of cuda (*..64_100.dll) errors. I did search for them in lib directory of CUDA, but the dlls that were present there had same names except '64_100' in their names. 
I'll be thankful if you can guide me through this.

**Comment by AlexeyAB** [comment]
@naufil601 

Can you show screenshot of files there? C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin

Also it may require `cudnn64_7.dll` from cuDNN archive.

**Comment by naufil601** [comment]
here's the screen shot of my CUDA's bin directory
![image](https://user-images.githubusercontent.com/18327182/55131779-d16fcd00-5141-11e9-8d2b-c4038f5a829b.png)

**Comment by naufil601** [comment]
@AlexeyAB 

darknet.exe requires the dlls that I have in my CUDA's bin folder, and other than that it also requires dlls with *_100.dll names.
So i renamed those dlls and copy pasted in the same directory. Finally executable showed something but ofcourse it is erroneous 😃 

![image](https://user-images.githubusercontent.com/18327182/55152691-bb2e3500-5172-11e9-817e-dc0be5bf6913.png)

If you have these dlls with you, it is appreciated if you can share
 - nppc64_100.dll     - nppidei64_100.dll    - nppial64_100.dll      - nppif64_100.dll    -nppisu64_100.dll

**Comment by naufil601** [comment]
@AlexeyAB , waiting for your response.

I have tried to reinstall CUDA and copy pasted cudnn files to it, still I get the same error
![image](https://user-images.githubusercontent.com/18327182/55272723-9953c000-52e2-11e9-9e25-3d6255ccde81.png)

**Comment by naufil601** [comment]
I just downgraded my Cudnn to 7.1.4 and it solved this error for me. 
Training on GPU now 😎 

Thanks a lot for help @AlexeyAB
