### ISSUE TITLE
No detection with standard weigths

### ISSUE THREAD

**Issue by EnricoBeltramo** [AlexeyAB/darknet#263]
I built Darknet on Win10 using
Visual Studio 2015
Cuda 8.0
cuDNN 6.0
OpenCV 3.2

dowloaded yolo-voc.weights

and start the follow command as test (the pic is the dog.jpg provided in the repository):
darknet.exe detector test data/voc.data yolo-voc.cfg yolo-voc.weights -i 0 -thresh 0.1 dogr.jpg
But it looks not be able to detect anything. What do I do wrong?

Thank you

**Comment by AlexeyAB** [comment]
Try this: `darknet.exe detector test data/voc.data yolo-voc.cfg yolo-voc.weights dog.jpg -i 0`

**Comment by EnricoBeltramo** [comment]
Thank you, but unfortunately, still no detection. What I find strange is that if I do a training of a new network following instruction in read me, it seems to work and I have convergence more or less as expected. I tryed to debug, but is no much clear what happens: it looks find any classes as probability 0. May be do I have to change voc.data or names file to match with yolo-voc.cfg and yolo-voc.weights?

**Comment by EnricoBeltramo** [comment]
If can help, I found that if I execute same code in Linux version (Ubuntu 16.04, no CUDA, no openCV) the detection works perfectly. Anyway, if is possible, I would do in Windows..

**Comment by AlexeyAB** [comment]
Try to use release: https://github.com/AlexeyAB/darknet/releases
I tested it on both Windows and Linux.

**Comment by EnricoBeltramo** [comment]
I tried to make a clean installation on Windows of all involved tools (opencv, CUDA, etc..) and using your zip files: it works! I tried with a standard network and one trained by myself (with 4 classes): both of them detect as expected.
Thank you for your support!
