### ISSUE TITLE
Custom Dataset Question - Mirroring/Flip

### ISSUE THREAD

**Issue by daylanc** [AlexeyAB/darknet#2630]
I am creating my own dataset to recognize handwritten numbers. I've noticed that some number "2" look like flipped/mirrored number "6". Example:
![IMG_2616](https://user-images.githubusercontent.com/34255535/54498331-3443a780-48aa-11e9-8854-091a82afe10c.jpg)
![IMG_2617](https://user-images.githubusercontent.com/34255535/54498334-36a60180-48aa-11e9-9c34-a42d35251fcb.jpg)

Do I need to add `flip=0` in the `yolov3.cfg` file?

**Comment by AlexeyAB** [comment]
@daylanc Hi

You should set `flip=0` in the `[net]` section in cfg-file.

**Comment by daylanc** [comment]
@AlexeyAB 
Thanks!
