### ISSUE TITLE
Possible bug in CMakeLists and Build process

### ISSUE THREAD

**Issue by JakupGuven** [AlexeyAB/darknet#2643]
I'm trying to install darknet following the vcpkg approach on Windows.
I'm at the step where I'm editing the CMakeLists to match the Compute Capability of my graphics card (61 & GTX 1080) and I'm setting it as such:

set(CUDA_COMPUTE_MODEL_61 "61") #Compute capability for Tesla P40

I run build.ps1 and get CMake Errors:

 "CUDA_COMPUTE_MODEL" "VERSION_GREATER_EQUAL" "AND" "CMAKE_CUDA_COMPILER_VERSION" "VERSION_LESS_EQUAL" "9"

  Unknown arguments specified

Which comes from this code:

  if(CUDA_COMPUTE_MODEL VERSION_GREATER_EQUAL ${CUDA_COMPUTE_MODEL_75} AND CMAKE_CUDA_COMPILER_VERSION VERSION_LESS_EQUAL 9)

    message(STATUS "CUDA 10 is required for Compute Model 7.5 - Lowering settings to 7.0")

    set(CUDA_COMPUTE_MODEL ${CUDA_COMPUTE_MODEL_70})

  endif()

As I'm absolutely positive that my compute model is 61 and my cuda compiler version is 10.0 I comment this code. I run into a similar clause further down the code that I comment out. 

Now my build process can go on but I get these fatal errors which stops me from being able to use darknet:

LINK : fatal error LNK1104: cannot open file 'optimized;C:\Users\Cybercom\vcpkg\installed\x64
-windows\lib\pthreadVC2.lib;debug;C:\Users\Cybercom\vcpkg\installed\x64-windows\debug\lib\pthreadVC2d.lib' [C:\Users\Cybercom\darknet\build_win_release\uselib_track.vcxproj]
LINK : fatal error LNK1104: cannot open file 'optimized;C:\Users\Cybercom\vcpkg\installed\x64
-windows\lib\pthreadVC2.lib;debug;C:\Users\Cybercom\vcpkg\installed\x64windows\debug\lib\pthreadVC2d.lib' [C:\Users\Cybercom\darknet\build_win_release\uselib.vcxproj]
LINK : fatal error LNK1104: cannot open file 'optimized;C:\Users\Cybercom\vcpkg\installed\x64
-windows\lib\pthreadVC2.lib;debug;C:\Users\Cybercom\vcpkg\installed\x64windows\debug\lib\pthreadVC2d.lib' [C:\Users\Cybercom\darknet\build_win_release\darknet.vcxproj]

I can manually find these files in the specific folders, I don't know why "optimized;" is added as a prefix to the path in my CMakeCache files: 

//Details about finding PThreads_windows
FIND_PACKAGE_MESSAGE_DETAILS_PThreads_windows:INTERNAL=[optimized;C:/Users/Cybercom/vcpkg/installed/x64-windows/lib/pthreadVC2.lib;debug;C:/Users/Cybercom/vcpkg/installed/x64-windows/debug/lib/pthreadVC2d.lib][C:/Users/Cybercom/vcpkg/installed/x64-windows/include][v()]

I'm looking for where this comes from but I'd greatly appreciate some support here.

**Comment by AlexeyAB** [comment]
@JakupGuven Hi,

Can you successfully build Darknet by using default Cmakelist.txt and by using Cmake-gui instead of build.ps1?

**Comment by JakupGuven** [comment]
No, provided I did everything correctly I get the following errors:

CMake Error at C:/Program Files/CMake/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:99 (message):
  Could not find toolchain file: /scripts/buildsystems/vcpkg.cmake
Call Stack (most recent call first):
  CMakeLists.txt:27 (project)


Configuring incomplete, errors occurred!

I can find the file here though:
C:\Users\Cybercom\vcpkg\scripts\buildsystems

**Comment by AlexeyAB** [comment]
@JakupGuven 



Do you get this error even if you set to `USE_INTEGRATED_LIBS`?

![image](https://user-images.githubusercontent.com/4096485/54533889-4a319500-499c-11e9-9f93-5c236e854518.png)

**Comment by JakupGuven** [comment]
@AlexeyAB 
I have no such option:

![image](https://user-images.githubusercontent.com/17982889/54534083-ebfcb600-498b-11e9-9cdf-868e3dff2e9a.png)

**Comment by JakupGuven** [comment]
Even with the default CMakeLists running the Powershell script there's something that makes the paths to my OpenCV/Pthreads dependencies look like this:

 'optimized;C:\Users\Cybercom\vcpkg\installed\x64-windows\lib\pthreadVC2.lib;debug;C:\Users\Cybercom\vcpkg\installed\x64-windows\debug\lib\pthreadVC2d.lib' 

It appears like that in my CMakeCache files and in uselib_t
rack.vcxproj

**Comment by JakupGuven** [comment]
[CMakeCache.txt](https://github.com/AlexeyAB/darknet/files/2978419/CMakeCache.txt)
[uselib_track.txt](https://github.com/AlexeyAB/darknet/files/2978434/uselib_track.txt)

**Comment by JakupGuven** [comment]
I've gotten it to work with and without "USE_INTEGRATED_LIBS". However I can't find any darknet executable

![image](https://user-images.githubusercontent.com/17982889/54536271-b0181f80-4990-11e9-9557-65a1e64af8b9.png)

**Comment by AlexeyAB** [comment]
> However I can't find any darknet executable

You should press: Configure -> Generate -> Open Project -> set x64 & Release -> Build all

**Comment by JakupGuven** [comment]
@AlexeyAB Thank you.
Is there any simple way to check that it's working?

**Comment by AlexeyAB** [comment]
@JakupGuven What do you mean?

Just compile it, download https://pjreddie.com/media/files/yolov3.weights and run detection:

`darknet.exe detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg`

**Comment by JakupGuven** [comment]
Now I get a new error:
CUDA status Error: file: C:\Users\Cybercom\darknet\src\dark_cuda.c : cuda_set_device() : line: 31 : build time: Mar 18 2019 - 15:24:41
CUDA Error: unknown error

CUDA Error: unknown error: No error

On this code:
void cuda_set_device(int n)
{
    gpu_index = n;
    cudaError_t status = cudaSetDevice(n);
    if(status != cudaSuccess) CHECK_CUDA(status); //this is line 31
}

**Comment by JakupGuven** [comment]
My bad. Some where along the way there my GPU drivers had been corrupted and my computer was having trouble even detecting it. I reinstalled the drivers and it works beautifully.
Thanks for your help.

**Comment by AlexeyAB** [comment]
@JakupGuven 

So you can build Darknet by using Cmake.

But you can't build it by using `build.ps1`?

**Comment by JakupGuven** [comment]
@AlexeyAB
That's correct. 
I've managed to install darknet the "legacy" way three times before without problems.
