### ISSUE TITLE
Linkage error using CMake

### ISSUE THREAD

**Issue by agirbau** [AlexeyAB/darknet#2646]
Hello!

I have an issue when compiling the code with CMake. 

```
In file included from Desktop/darknet_alexey/src/connected_layer.c:6:0:
Desktop/darknet_alexey/src/blas.h:82:75: error: conflicting declaration of ‘void add_bias_gpu(float*, float*, int, int, int)’ with ‘C’ linkage
 void add_bias_gpu(float *output, float *biases, int batch, int n, int size);
```
Do you know why this could be happening? Thank you very much!

**Comment by AlexeyAB** [comment]
@agirbau Hi,

* What versions of OS, Compiler and Cmake do you use?

* Do you use Cmake-gui, cmake.exe or build.ps1?

* Try to update your code from GitHub, with the latest commits.

**Comment by agirbau** [comment]
Hello!

OS: UBUNTU 16.04
gcc version: 5.4.0
cmake version: 3.14.0

I use the cmake-gui

I have the last version of the code I believe.

**Comment by agirbau** [comment]
I've rebased the project and it seems to not to have this issue (I don't know why it didn't correctly pull the project).

Now I'm facing another issue:
1. When directly compiling this occurs:
```
[ 83%] Building CXX object CMakeFiles/darknet.dir/src/http_stream.cpp.o
[ 83%] Building CUDA object CMakeFiles/darknet.dir/src/activation_kernels.cu.o
nvcc fatal   : Unknown option 'fopenmp'
CMakeFiles/darknet.dir/build.make:1622: recipe for target 'CMakeFiles/darknet.dir/src/activation_kernels.cu.o' failed
make[3]: *** [CMakeFiles/darknet.dir/src/activation_kernels.cu.o] Error 1
```

2. If I remove "find_package(OpenMP)" in line 202 it correctly compiles but, in the end:
```
[ 97%] Linking CUDA device code CMakeFiles/darknet.dir/cmake_device_link.o
[100%] Linking CXX executable darknet
CMakeFiles/darknet.dir/src/activation_kernels.cu.o: In function `__device_stub__Z28binary_gradient_array_kernelPfS_ii17BINARY_ACTIVATIONS_(float*, float*, int, int, BINARY_ACTIVATION, float*)':
/tmp/tmpxft_00005ab7_00000000-5_activation_kernels.cudafe1.stub.c:23: undefined reference to `__cudaPopCallConfiguration'
CMakeFiles/darknet.dir/src/activation_kernels.cu.o: In function `cudaLaunchKernel<char>':
/usr/local/cuda-10.0/include/cuda_runtime.h:202: undefined reference to `cudaLaunchKernel'
```

Seems that it's not correctly linking CUDA or something?

**Comment by AlexeyAB** [comment]
@agirbau 

* What GPU, CUDA and cuDNN versions do you have?

* Can you show output of commands?
```
nvcc --version
nvidia-smi
```

* Try to download Darknet to another **empty** directory and do there
```
cmake .
make
```

**Comment by agirbau** [comment]
Hello Alexey,

I was able to build it when applying the changes I mentioned in #2665

I will do a pull request with the changes, thank you very much!
