### ISSUE TITLE
How to calculate MAC instead of FLOPS ?

### ISSUE THREAD

**Issue by Sudhakar17** [AlexeyAB/darknet#2658]
I would like to do know for YOLO-V3 and YOLO-V3-tiny. In the case of YOLO, I found in netscope using prototxt file.

https://dgschwend.github.io/netscope/#/preset/YOLO

**Comment by AlexeyAB** [comment]
In convolutional layers:
`MACCs (multiply-accumulate operations) also known as MADDs` ~= `FLOPS / 2`

So just divide FLOPS by 2.

**Comment by Sudhakar17** [comment]
https://github.com/AlexeyAB/darknet/issues/1134
