### ISSUE TITLE
About the data dimensions, is this a bug or not?

### ISSUE THREAD

**Issue by tabsun** [AlexeyAB/darknet#2667]
In src/yolo_layer.c, line 367. The code is like below:

```
void avg_flipped_yolo(layer l)
{
    int i,j,n,z;
    float *flip = l.output + l.outputs;
    for (j = 0; j < l.h; ++j) {
        for (i = 0; i < l.w/2; ++i) {
            for (n = 0; n < l.n; ++n) {
                for(z = 0; z < l.classes + 4 + 1; ++z){
                    int i1 = z*l.w*l.h*l.n + n*l.w*l.h + j*l.w + i;
                    int i2 = z*l.w*l.h*l.n + n*l.w*l.h + j*l.w + (l.w - i - 1);
                    float swap = flip[i1];
                    flip[i1] = flip[i2];
                    flip[i2] = swap;
                    if(z == 0){
                        flip[i1] = -flip[i1];
                        flip[i2] = -flip[i2];
                    }
                }
            }
        }
    }
    for(i = 0; i < l.outputs; ++i){
        l.output[i] = (l.output[i] + flip[i])/2.;
    }
}
```

We can see the index is `z*l.w*l.h*l.n + n*l.w*l.h + j*l.w + i` which means **### the dimension is [classes+4+1, n, h, w]**.
But also in src/yolo_layer.c, line 186, in the function entry_index. We can see the following code:
```
return batch*l.outputs + n*l.w*l.h*(4+l.classes+1) + entry*l.w*l.h + loc;
```

This means **### the dimension is [n, classes+4+1, h, w]**.

So what's the correct dimension? As in my experiment, the latter one should be correct. It's a bug or sth I haven't noticed?

**Comment by AlexeyAB** [comment]
@tabsun Hi,

This is the correct way: https://github.com/AlexeyAB/darknet/blob/1cd332e4cac001ffcc12a24c72640fe02b69a8a0/src/yolo_layer.c#L186-L191

**Comment by tabsun** [comment]
Much thanks to you and for your work!
