### ISSUE TITLE
make: *** No rule to make target 'obj/cuda.o', needed by 'darknet'.  Stop.

### ISSUE THREAD

**Issue by Arsiirasheed** [AlexeyAB/darknet#2668]
When i try to build darknet on googleb colab got this error 

> make: *** No rule to make target 'obj/cuda.o', needed by 'darknet'.  Stop.

**with**
GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=1
AVX=1
OPENMP=1
LIBSO=1

**output** 

chmod +x *.sh
g++ -std=c++11 -Iinclude/  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN -DCUDNN_HALF -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -DCUDNN_HALF -c ./src/http_stream.cpp -o obj/http_stream.o
./src/http_stream.cpp: In member function ‘bool JSON_sender::write(const char*)’:
./src/http_stream.cpp:228:21: warning: unused variable ‘n’ [-Wunused-variable]
                 int n = _write(client, outputbuf, outlen);
                     ^
./src/http_stream.cpp: In member function ‘bool MJPG_sender::write(const cv::Mat&)’:
./src/http_stream.cpp:475:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 if (n < outlen)
                     ~~^~~~~~~~
gcc -Iinclude/  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN -DCUDNN_HALF -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -DCUDNN_HALF -c ./src/gemm.c -o obj/gemm.o
./src/gemm.c: In function ‘convolution_2d’:
./src/gemm.c:2016:15: warning: unused variable ‘out_w’ [-Wunused-variable]
     const int out_w = (w + 2 * pad - ksize) / stride + 1;    // output_width=input_width for stride=1 and pad=1
               ^~~~~
./src/gemm.c:2015:15: warning: unused variable ‘out_h’ [-Wunused-variable]
     const int out_h = (h + 2 * pad - ksize) / stride + 1;    // output_height=input_height for stride=1 and pad=1
               ^~~~~
gcc -Iinclude/  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN -DCUDNN_HALF -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -DCUDNN_HALF -c ./src/utils.c -o obj/utils.o
make: *** No rule to make target 'obj/cuda.o', needed by 'darknet'.  Stop.

**Comment by AlexeyAB** [comment]
@Arsiirasheed Try to download the last version of Darknet to the empty folder and build it again.

**Comment by Arsiirasheed** [comment]
tried many times but same issue

**Comment by AlexeyAB** [comment]
* What command do you use for downloading?

* Try to download this archive: https://github.com/AlexeyAB/darknet/archive/master.zip

**Comment by Arsiirasheed** [comment]
@AlexeyAB  i used git clone https://github.com/AlexeyAB/darknet

**Comment by Arsiirasheed** [comment]
@AlexeyAB building with master.zip as you ...still same error

**output**
mkdir -p obj
mkdir -p backup
mkdir -p results
chmod +x *.sh
g++ -std=c++11 -Iinclude/  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN -DCUDNN_HALF -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -ffp-contract=fast -mavx -mavx2 -msse3 -msse4.1 -msse4.2 -msse4a -Ofast -DOPENCV -fopenmp -DGPU -DCUDNN -I/usr/local/cudnn/include -DCUDNN_HALF -fPIC -c ./src/http_stream.cpp -o obj/http_stream.o
./src/http_stream.cpp: In member function ‘bool JSON_sender::write(const char*)’:
./src/http_stream.cpp:228:21: warning: unused variable ‘n’ [-Wunused-variable]
                 int n = _write(client, outputbuf, outlen);
                     ^
./src/http_stream.cpp: In member function ‘bool MJPG_sender::write(const cv::Mat&)’:
./src/http_stream.cpp:475:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 if (n < outlen)
                     ~~^~~~~~~~
gcc -Iinclude/  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN -DCUDNN_HALF -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -ffp-contract=fast -mavx -mavx2 -msse3 -msse4.1 -msse4.2 -msse4a -Ofast -DOPENCV -fopenmp -DGPU -DCUDNN -I/usr/local/cudnn/include -DCUDNN_HALF -fPIC -c ./src/gemm.c -o obj/gemm.o
./src/gemm.c: In function ‘_castu32_f32’:
./src/gemm.c:549:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     return *((float *)&a);
     ^~~~~~
./src/gemm.c: In function ‘convolution_2d’:
./src/gemm.c:1046:27: warning: unused variable ‘sum’ [-Wunused-variable]
                     float sum = 0;
                           ^~~
./src/gemm.c:1026:13: warning: unused variable ‘all256i_one’ [-Wunused-variable]
     __m256i all256i_one = _mm256_set1_epi32(1);
             ^~~~~~~~~~~
./src/gemm.c:1025:12: warning: unused variable ‘all256_one’ [-Wunused-variable]
     __m256 all256_one = _mm256_set1_ps(1);
            ^~~~~~~~~~
./src/gemm.c:1023:13: warning: unused variable ‘idx256’ [-Wunused-variable]
     __m256i idx256 = _mm256_set_epi32(0, 7, 6, 5, 4, 3, 2, 1);
             ^~~~~~
./src/gemm.c:1020:13: warning: unused variable ‘all256_last_zero’ [-Wunused-variable]
     __m256i all256_last_zero =
             ^~~~~~~~~~~~~~~~
./src/gemm.c: In function ‘im2col_cpu_custom_bin’:
./src/gemm.c:1622:17: warning: unused variable ‘all256_sing1’ [-Wunused-variable]
         __m256i all256_sing1 = _mm256_set_epi32(0x80000000, 0x80000000, 0x80000000, 0x80000000, 0x80000000, 0x80000000, 0x80000000, 0x80000000);
                 ^~~~~~~~~~~~
gcc -Iinclude/  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN -DCUDNN_HALF -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -ffp-contract=fast -mavx -mavx2 -msse3 -msse4.1 -msse4.2 -msse4a -Ofast -DOPENCV -fopenmp -DGPU -DCUDNN -I/usr/local/cudnn/include -DCUDNN_HALF -fPIC -c ./src/utils.c -o obj/utils.o
make: *** No rule to make target 'obj/cuda.o', needed by 'darknet'.  Stop.

**Comment by AlexeyAB** [comment]
> make: *** No rule to make target 'obj/cuda.o', needed by 'darknet'. Stop.

This is very strange, because there is no `cuda.o` in the Makefile: https://github.com/AlexeyAB/darknet/blob/master/Makefile

It means that you are using an old Makefile.

I would recommend you to delete all old Darknets.
