### ISSUE TITLE
Is libdarknet.so generated with the Cmake build?

### ISSUE THREAD

**Issue by agirbau** [AlexeyAB/darknet#2670]
Hello Alexey,

When using the makefile we could compile the project with several options:
```
GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=1
AVX=0
OPENMP=0
LIBSO=1
ZED_CAMERA=0
DEBUG=0
```
In the CMake file are we able to play with these also? Concretely I'm interested in how to generate the libdarknet.so with the CMake compilation. Thank you very much!

**Comment by cudanexus** [comment]
@agirbau if the reference link solved your problem please close the issue

**Comment by agirbau** [comment]
I guess it's generated when doing make install? In that case it generates an error:
```
CMake Error at cmake_install.cmake:129 (file):
  file INSTALL cannot find
  "/home/agirbau/darknet_alexey_master/uselib".

Makefile:61: recipe for target 'install' failed
make: *** [install] Error 1
```

**Comment by agirbau** [comment]
#2727 Solved the problem. Thx!
