### ISSUE TITLE
Guidance on custom training

### ISSUE THREAD

**Issue by HamzahNizami** [AlexeyAB/darknet#2676]
Hi, I'm pretty new to the computer vision scene and wanted to test out YOLOv3. Before I get started I was hoping to get any sort of advice to help me in the long run. Thanks in advance.

**The problem:**
The work I'm currently doing is on the detection of multiple strawberries growing in a field. These strawberries normally grow in clusters so being able to distinguish between them is important. The other issue is that strawberries are relatively small, so I was wondering in terms of those two things how I can ensure the best results and what settings I could use with YOLOv3.

The other problem is that my dataset is small (850 images in total). Any advice on how to split this between training, validation and testing data, and how many iterations I should run would be highly appreciated. 

Edit: 

I currently have my dataset annotated in COCO dataset style. I currently have both a train.json and val.json file. I previously used this to train with "Facebooks DeepMask", so I was wondering if I can use this annotation style directly? It isn't annotated with bounding boxes but "masks". Will YOLOv3 accept this form of annotation and produce bounding boxes as results? 

**My hardware + software specs:**
i5-7600K
GTX 1060 6GB

Running Ubuntu 18.04
CUDA 9.0
CUDNN v7

With that in mind, I was wondering if I should use YOLOv3 or YOLOv3 tiny. 

Thanks in advance, any help would be awesome!

@AlexeyAB

**Comment by AlexeyAB** [comment]
@HamzahNizami Hi,

In your case I think the best result you can achive by using https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov3-tiny_3l.cfg with `width=832 height=832` or `width=1024 height=1024`

What is the resolution of your images?

> The other problem is that my dataset is small (850 images in total). Any advice on how to split this between training, validation and testing data, and how many iterations I should run would be highly appreciated.

You should train `max(4000, classes * 2000)` iterations, or just train while mAP is increasing: https://github.com/AlexeyAB/darknet#when-should-i-stop-training

You shouldn't have Test dataset. Just divide Training:Validation as 90% / 10%.
Train by using Training dataset.
And check mAP by using Validation dataset.


----

> I currently have my dataset annotated in COCO dataset style. I currently have both a train.json and val.json file. I previously used this to train with "Facebooks DeepMask", so I was wondering if I can use this annotation style directly? It isn't annotated with bounding boxes but "masks". Will YOLOv3 accept this form of annotation and produce bounding boxes as results?

No. You should convert your labels to Yolo format that is described here: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

**Comment by HamzahNizami** [comment]
Thank you so much for the fast response. 

My images are mostly 4032 x 3024 and 3024 x 4032 72 DPI, but range significantly to images as small as 196 pixels x 160 pixels with 96 DPI, and a few other pictures at 300 DPI.

I was also wondering how to decrease training speed for greater accuracy (not too much, wouldn't want it to take more than a day to train if possible) 

Again thank you so much for the fast response, and thank in advance.

**Comment by cudanexus** [comment]
@HamzahNizami after your problem is solved please close the issue mention alexeyAb only once.

**Comment by AlexeyAB** [comment]
So width=832 height=832 will be enough.

You can try to train yolov3-tiny_3l.cfg or yolov3.cfg and compare mAP.

> Does YOLOv3 tiny work with CUDA 9 and CUDDN 7

Yes.


> Are there any tips you'd give when annotating images that overlap. Should I assume where the object (strawberry) ends when overlapped, or should I only annotate what is clearly visible?

You can annotate as you want.
Yolo will detect objects in the same way as you labeled it.

**Comment by HamzahNizami** [comment]
Thank you so much. I think that's all for now! I'll be closing the issue now
