### ISSUE TITLE
set system variable `OpenCV_ROOT_DIR`

### ISSUE THREAD

**Issue by VonSdite** [AlexeyAB/darknet#2679]
![image](https://user-images.githubusercontent.com/25704948/54731138-741acf80-4bc7-11e9-8d86-5bf00e3ef254.png)

![image](https://user-images.githubusercontent.com/25704948/54731190-c8be4a80-4bc7-11e9-9b08-c2d9c497829a.png)

Also, should set system variable `OpenCV_ROOT_DIR`

**Comment by VonSdite** [comment]
Sorry, I make a mistake。

I saw it there.

https://github.com/AlexeyAB/darknet/blob/1cd332e4cac001ffcc12a24c72640fe02b69a8a0/build/darknet/darknet.vcxproj#L91

@AlexeyAB

**Comment by AlexeyAB** [comment]
@VonSdite I fixed it in .vcxproj-files.

**Comment by VonSdite** [comment]
WOW, you are very nice !!!
