### ISSUE TITLE
Resume a trained network with additional data (negative data)

### ISSUE THREAD

**Issue by MartyEz** [AlexeyAB/darknet#2687]
Hello,

I would like to know if it's useful to resume a trained network with additional data.
These additional data are negative detected as false positive by the network.

Steps could be :
1) train a pedestrian detector.
2) Use this network 
3) Notice there are some false positive. And keep theses images with theses false-positive
4) Resume the training with original data already used in step 1 + data grabbed in step 3

Could these steps improve accuracy without destroying the train made in step 1 ?

Thanks

**Comment by AlexeyAB** [comment]
@MartyEz Hi,

If you will continue training with both Old_images + New_images (negative samples) - it will increase accuracy.

**Comment by MartyEz** [comment]
Thanks
