### ISSUE TITLE
Plans to build Tiny YOLO for Windows?

### ISSUE THREAD

**Issue by rtrahms** [AlexeyAB/darknet#269]
Just curious, any plans to create a project for Tiny YOLO, either as a DLL or console?  If so, it would be interesting to build both GPU and non-GPU versions as well.
Thanks!
Rob

**Comment by rtrahms** [comment]
I think I answered my own question.  I just can use the tiny-yolo.cfg file with existing yolo build, correct?

**Comment by AlexeyAB** [comment]
> I think I answered my own question. I just can use the tiny-yolo.cfg file with existing yolo build, correct?

Yes
