### ISSUE TITLE
not founder version GPU card  issue？

### ISSUE THREAD

**Issue by ericwang321** [AlexeyAB/darknet#2690]
I want to assemble a GPU workstation i9 9900k or i7/64G/SSD/, the sellers  recommends
 *RTX2080ti wf3 giga*,

> 1.This graphics card is not a founder  version, userd to compiled darknet/yolov3, is there a problem?

> 2.Single card is not cold with water, it is said that the time is long?

> 3.Is the i9 cpu high and the heat dissipation is not good?

Confused, sincerely hope to answer.thanks for any suggestion.

**Comment by AlexeyAB** [comment]
1. No problem

2. What do you mean? If T in your room is not higher than 40, then I think this is no problem )

3. It's not hot, it's only 95 Watt: https://ark.intel.com/content/www/us/en/ark/products/186605/intel-core-i9-9900k-processor-16m-cache-up-to-5-00-ghz.html

**Comment by ericwang321** [comment]
thanks.

> The following configuration of the overall compilation yolov3 no problem? What improvements are there?

`CPU | i9 9900k 8 core 16 threads`
`Radiator | Antec Mercury 360 3 fan water cooling row`
**Motherboard | GIGABYTE z390 E-sports Elite**
`Memory | Corsair 16G DDR4 3200 *4, a total of 64G`
Hard Disk 1 | Samsung 2TB 2.5" SSD (860 EVO)
`Graphics Card | GIGABYTE RTX2080ti wf3`
`Chassis | Antec S101 silent tower chassis`
Power | Pirate Ship 1000W Gold Power Supply

**Comment by AlexeyAB** [comment]
@ericwang321 It's good solution.

**Comment by ericwang321** [comment]
thanks.I am going to try

**Comment by ericwang321** [comment]
GIGABYTE RTX2080ti wf3 works with cuda10.1+cudnn，  thanks

**Comment by ericwang321** [comment]
close the issue temporarily and wait for time to show run result.
