### ISSUE TITLE
problem while saving video

### ISSUE THREAD

**Issue by wisdomk** [AlexeyAB/darknet#2692]
I am trying to use darknet_video.py file alone by executing it from command line and editing few parameters inside the file such as <cfg, data, weights and video file paths>

it works alright and shows me live the detection process successfully. however, when it comes to save the result it throws an error related to opencv `cv2` as shown below
![image](https://user-images.githubusercontent.com/47982574/54757506-a7228a80-4bea-11e9-8865-931ef3406a93.png)

could someone please point out why and how to save the resultant video after the detection?

**Comment by wisdomk** [comment]
I am sorry for opening such a silly problem .... it is solved could you please delete it!!

**Comment by SafaaDaf** [comment]
wisdomk have you solved this problem ? if yes please how cause I'm facing it too. Thanks

**Comment by HuiXiangLanChaiXi** [comment]
@wisdomk I also meet this problem. May I ask you how to solve it?Thanks!
