### ISSUE TITLE
How do I train without  pretrained weights?

### ISSUE THREAD

**Issue by wdma** [AlexeyAB/darknet#2696]
I would like to train the YOLOv3 model on custom input starting from a naieve model (without pretrained weights).  Can you tell me the command to do this or are there instructions somewhere on how to create weights for a naieve model?

**Comment by AlexeyAB** [comment]
`./darknet detector train cfg/coco.data yolov3.cfg `

**Comment by wdma** [comment]
Awesome!  Thank you.

I am running baseline tests.  So far all is going very well!  Can you tell me approximately how many epochs I should run to attain the level of performance seen in the pretrained model?

**Comment by AlexeyAB** [comment]
@wdma You should train more than 500 000 iterations. And you should use Classification-pre-trained weights-file `darknet53.conv.74`
