### ISSUE TITLE
MJPEG Loss Chart Server not loading full chart

### ISSUE THREAD

**Issue by darknet-researcher** [AlexeyAB/darknet#2698]
When training on cloud server, accessing the loss chart via http://ipaddress:8090 does not load full chart. 

Sometimes half the image is received, and sometimes even less.

See attached screenshot below.

![Screen Shot 2019-03-22 at 9 33 38 am](https://user-images.githubusercontent.com/48811704/54791510-f5389c00-4c85-11e9-929c-d5f91128685b.png)

**Comment by darknet-researcher** [comment]
Issue is the same when running detector demo on video file. Only half the image is streamed

**Comment by AlexeyAB** [comment]
@darknet-researcher Hi,

* Do you use Amazon Cloud server or your own server?

* Does it always load only half of image or only sometimes?

* Do you use here `500000` for training (you can try to increase it)? https://github.com/AlexeyAB/darknet/blob/9815012a01c13f70806381e0c5d556599117c76b/src/image.c#L832

----

* Try to change `100` to `30` in this line, recompile, and run training: https://github.com/AlexeyAB/darknet/blob/9815012a01c13f70806381e0c5d556599117c76b/src/image.c#L832

**Comment by darknet-researcher** [comment]
Problem solved. Thanks very much for your help!

**Comment by AlexeyAB** [comment]
@darknet-researcher 
What helped you, 
* increasing timeout more than `500000` ?
* or decreasing quality lower than `100`?

**Comment by darknet-researcher** [comment]
Both. I also transferred to a cloud server that is closer to my physical location. Thus reducing timeout errors.

**Comment by darknet-researcher** [comment]
@AlexeyAB 
Both. I also transferred to a cloud server that is closer to my physical location. Thus reducing timeout errors.
