### ISSUE TITLE
Which ports open for MJPEG server

### ISSUE THREAD

**Issue by DarylWM** [AlexeyAB/darknet#2699]
Hello. Thank you for all the work you've done on this project.

I'm training my model on an AWS EC2 instance, and can't access the MJPEG server (I cloned the repo this morning). I've opened port 8090 inbound, so I'm wondering if there are other ports I should have open.

**Comment by AlexeyAB** [comment]
@DarylWM Hi,

* You should open only port 8090
* What Darknet command do you use?
* What date of repository do you use?
* Do you try to open `http://<ip>:8090` in the Chrome web-browser?

**Comment by DarylWM** [comment]
Thanks @AlexeyAB. The command I'm using:

./darknet detector train data/peptides/peptides-obj.data cfg/yolov3-peptides.cfg darknet53.conv.74 -dont_show -mjpeg_port 8090 -map

I cloned the repo yesterday, March 23. Using Chrome as the client, pointing to http://<ip>:8090. Darknet is running on an AWS EC2 instance.

I haven't modified line 832 in darknet/src/image.c as you've suggested in other questions about MJPEG server not working as expected so maybe I could try that.

**Comment by AlexeyAB** [comment]
@DarylWM Hi,

You must build Darknet with OpenCV. OpenCV must be installed. 
And set `OPENCV=1` in the Makefile if you don't use Cmake.

Yes, you can try to increase timeout more than `500000` and decrease quality less than `100` https://github.com/AlexeyAB/darknet/blob/9815012a01c13f70806381e0c5d556599117c76b/src/image.c#L832


Also check that port `8090` is opened - f.e. look what group is set for your instance `EC2 Dashboard->Instaces` then for this group `EC2 Dashboard->Security Groups`  set `Custom TCP Rule TCP 8090 Anywhere 0.0.0.0/0`

**Comment by DarylWM** [comment]
I appreciate your rapid response @AlexeyAB. The problem was I didn't have OpenCV installed. All good now.
