### ISSUE TITLE
C++ port for this windows port

### ISSUE THREAD

**Issue by bassamarshad** [AlexeyAB/darknet#27]
First off, great effort in porting this code to windows development environment. 

I would like to know if there is a c++ port for this code, I plan to use it on VS2015. There are c++ ports for the linux env : like this one : https://github.com/for-aiur/yolo_cpp .

What do you think ?

**Comment by AlexeyAB** [comment]
@bassamarshad 

I added support to use Yolo v2 as **C++** `yolo_cpp_dll.dll`-file: https://github.com/AlexeyAB/darknet#how-to-use-yolo-as-dll

* You simple should build `build\darknet\yolo_cpp_dll.sln` to create `yolo_cpp_dll.dll`-file

* And build simple C++-example which uses this  `yolo_cpp_dll.dll` - open & build `build\darknet\yolo_console_dll.sln`

    * `.cpp`-example is here: https://github.com/AlexeyAB/darknet/blob/master/src/yolo_console_dll.cpp
    * it supports both usage: **console** (without OpenCV) & **GUI** (with OpenCV) 

--------

Class `Detector` has constructor and 3 `detect()`-functions:
* `std::vector<bbox_t> detect(std::string image_filename, float thresh = 0.2);` - takes the image file name
* `std::vector<bbox_t> detect(image_t img, float thresh = 0.2);` - takes already loaded image `image_t`
* `std::vector<bbox_t> detect(cv::Mat mat, float thresh = 0.2);` - takes already loaded image of type `cv::Mat` by using OpenCV-function `cv::imread(filename);`

```
class Detector {
public:
	Detector(std::string cfg_filename, std::string weight_filename, int gpu_id = 0);
	~Detector();

	std::vector<bbox_t> detect(std::string image_filename, float thresh = 0.2);
	std::vector<bbox_t> detect(image_t img, float thresh = 0.2);

#ifdef OPENCV
	std::vector<bbox_t> detect(cv::Mat mat, float thresh = 0.2);
#endif
};

```

![console_yolo_dll](https://cloud.githubusercontent.com/assets/4096485/23971239/2c5ccb44-09de-11e7-8a9e-5a0c23cd515f.jpg)

**Comment by bassamarshad** [comment]
Amazing! Highly appreciated.

**Comment by VanitarNordic** [comment]
@AlexeyAB 

Thank you very very much.

**Comment by VanitarNordic** [comment]
@AlexeyAB 

is it possible to use this DLL in other platforms such as .Net (VB.net)? because we can use .Net internal commands to draw rectangles or bounding boxes or similar.

**Comment by AlexeyAB** [comment]
@VanitarNordic 
In general yes: https://msdn.microsoft.com/en-us/library/dt232c9t.aspx
But I don't know, is it possible to use `class` from DLL in VB.net.

**Comment by VanitarNordic** [comment]
@AlexeyAB 

Suppose we have an unknown Windows machine and we want that our .exe file run as it runs in our system, then what prerequisite should be installed on the target machine?

**Comment by VanitarNordic** [comment]
@AlexeyAB 

And also is it possible to draw a different color for each detected class object? for example green for class A, blue for Class B ... and so on

**Comment by AlexeyAB** [comment]
@VanitarNordic 

> Suppose we have an unknown Windows machine and we want that our .exe file run as it runs in our system, then what prerequisite should be installed on the target machine?

Requires:

1. `yolo_cpp_dll.dll`

2. Put all required dll-s (bottom): https://github.com/AlexeyAB/darknet#how-to-compile-custom

> `pthreadVC2.dll, pthreadGC2.dll` from \3rdparty\dll\x64
> 
> `cusolver64_80.dll, curand64_80.dll, cudart64_80.dll, cublas64_80.dll` - 80 for CUDA 8.0 or your version, from C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin
> 
> `opencv_core249.dll`, `opencv_highgui249.dll` and `opencv_ffmpeg249_64.dll` in `C:\opencv_2.4.9\opencv\build\x64\vc12\bin` or `vc14\bin`
>

**Comment by AlexeyAB** [comment]
@VanitarNordic  You can implement it: http://www.rubydoc.info/github/gonzedge/ruby-opencv/OpenCV/CvScalar
```
cv::Scalar color;

switch (obj_id) {
 case 0: color = cv::Scalar(0x0,0x80,0x0); break; // green
 case 1: color = cv::Scalar(0x0,0xff,0xff); break; // yellow

 default: color = cv::Scalar(0, 0, 0); 
}
cv::rectangle(mat_img, cv::Rect(i.x, i.y, i.w, i.h), color, 3);
```

**Comment by VanitarNordic** [comment]
@AlexeyAB 

Which parameters reflect the "class name" and confidence?

**Comment by AlexeyAB** [comment]
@VanitarNordic I added in last commit:
* class names: https://github.com/AlexeyAB/darknet/blob/master/src/yolo_console_dll.cpp#L48
* confidence: https://github.com/AlexeyAB/darknet/blob/master/src/yolo_v2_class.hpp#L19

**Comment by sqyangg** [comment]
@AlexeyAB could you show me how to get detected object number? I'm fail by using
 int obj_num = result_vec.size;
and also the code of tracking, how to use another tracker.
Thank you in advance.

**Comment by AlexeyAB** [comment]
@sqyangg 
int obj_num = result_vec.size();

What do you mean about "another tracking"?
You can change this function `YOLODLL_API std::vector<bbox_t> Detector::tracking(std::vector<bbox_t> cur_bbox_vec, int const frames_story)` in the file yolo_v2_class.cpp: 
 https://github.com/AlexeyAB/darknet/blob/master/src/yolo_v2_class.cpp#L220

**Comment by sqyangg** [comment]
@AlexeyAB  Thank you very very much. That is what I want exactly.
