### ISSUE TITLE
NMS problem

### ISSUE THREAD

**Issue by zhangyang1997** [AlexeyAB/darknet#2700]
Hi!
I used yolov2-tiny to do test.
why my "nms" dont have effect?

![N MHCY6AU6II5P4QNLLXV59](https://user-images.githubusercontent.com/22254602/54798766-194fa980-4c95-11e9-9869-0cd07ce3f00b.png)

Why nms=0.45 but the last obj have 2 overlap bbox?
I hope 1 obj have 1 high confidence bbox,thank you.

And when i adjust nms=0.05,it always have 2 bbox.
Where  should i to adjust ?

**Comment by zhangyang1997** [comment]
Hi!,I write some codes to solve this problem in box.c do_nms_sort function,and it likely true.
Do you think it is true? 

`   for (i = 0; i < classes; ++i) {
        for (j = i + 1; j < classes; ++j) {
            for (k = 0; k < total; ++k) {
                for (l = k + 1; l < total; ++l) {
                    if (box_iou(dets[k].bbox,dets[l].bbox)>thresh) {
                        if (dets[k].prob[i] >= dets[l].prob[j]) {
                            dets[l].prob[j] = 0;
                        }
                        else {
                            dets[k].prob[i] = 0;
                        }
                    }
                }
            }
        }
    }`

**Comment by zhangyang1997** [comment]
Although it takes effect but it becomes too slow! help me,thanks.

**Comment by zhangyang1997** [comment]
how I modify this do _nms_sort funcition in box.c?
```
void do_nms_sort(detection *dets, int total, int classes, float thresh)
{
    int i, j, k,l;
    k = total - 1;
    for (i = 0; i <= k; ++i) {
        if (dets[i].objectness == 0) {
            detection swap = dets[i];
            dets[i] = dets[k];
            dets[k] = swap;
            --k;
            --i;
        }
    }
    total = k + 1;

    for (k = 0; k < classes; ++k) {
        for (i = 0; i < total; ++i) {
            dets[i].sort_class = k;
        }
        qsort(dets, total, sizeof(detection), nms_comparator_v3);
        for (i = 0; i < total; ++i) {
            if (dets[i].prob[k] == 0) continue;
            box a = dets[i].bbox;
            for (j = i + 1; j < total; ++j) {
                box b = dets[j].bbox;
                if (box_iou(a, b) > thresh) {
                    dets[j].prob[k] = 0;
                }
            }
        }
    }
}
```

**Comment by zhangyang1997** [comment]
This my modify.
Do you think it it correct?
```
void do_nms_sort(detection *dets, int total, int classes, float thresh)
{
    int i, j, k,l;
    k = total - 1;
    for (i = 0; i <= k; ++i) {
        if (dets[i].objectness == 0) {
            detection swap = dets[i];
            dets[i] = dets[k];
            dets[k] = swap;
            --k;
            --i;
        }
    }
    total = k + 1;
    for (k = 0; k < classes; ++k) {
        for (i = 0; i < total; ++i) {
            dets[i].sort_class = k;
        }
        qsort(dets, total, sizeof(detection), nms_comparator_v3);
        for (i = 0; i < total; ++i) {
            if (dets[i].prob[k] == 0) continue;
            box a = dets[i].bbox;
            for (j = i + 1; j < total; ++j) {
                box b = dets[j].bbox;
                if (box_iou(a, b) > thresh) {
                    dets[j].prob[k] = 0;
                    for (l = k + 1; l < classes; l++) {
                        if (dets[i].prob[k] >= dets[j].prob[l]) {
                            dets[j].prob[l] = 0;
                        }
                        else {
                            dets[i].prob[k] = 0;
                        }
                    }
                   
                }
            }
        }
    }
}
```

**Comment by zhangyang1997** [comment]
And I have another problem, why the right one althought dont have obj,but have pre-bbox and pre-class?

**Comment by zhangyang1997** [comment]
Can I write a algorithm in do_nms_sort function from box.c?
 if bbox-nums>5, then delete that deviation from average's bbox util bbox-nums=5.

**Comment by AlexeyAB** [comment]
@zhangyang1997 Hi,

> why my "nms" dont have effect?

NMS has effect only on several detections with the **same class_id**.

There is no NMS problem. There is False-Positive problem.
Train with more images. Train more iterations at least `max(4000, 2000*classes)`.
Use yolov3-tiny.cfg instead of yolov2-tiny.cfg
Train with random=1 in cfg-file.

----

> And I have another problem, why the final in the pic althought dont have obj,but have pre-bbox and pre-class?

What do you mean? What is the pre-bbox and pre-class?

----

If you want you can rewrite NMS algorithm as you want.

**Comment by zhangyang1997** [comment]
I know where I am wrong because of your answer,Thank you very much!The problem because there is not any false sample in my data set, so I will add some false sample to train again.

**Comment by TaihuLight** [comment]
@zhangyang1997 @AlexeyAB 
Does this repo has implemented soft-NMS ()

**Comment by barzan-hayati** [comment]
> 
> 
> I know where I am wrong because of your answer,Thank you very much!
> The first problem I have solved because my modify.
> The second problem because there is not any negative sample in my data set, so I will add some negative sample to train again.
> 
> And pre-box is meaning predicted box, sorry I abbreviatated it.


What's **negative sample in my data set**  for  object detection via yolo?
