### ISSUE TITLE
Modifying custom dataset using calc_anchors

### ISSUE THREAD

**Issue by nbkhuong** [AlexeyAB/darknet#2701]
Hello,

I am trying to train yolov3 to detect only one class of small object for my project and I have collected a relatively huge dataset with many irrelevant large objects. And I just wanted to use calc_anchors to filter these images off the set. My question is:

Which part of the code in calc_anchors where all of the size clustering is calculated, should I modify to add my code in there to remove the irrelevant big object?

Thank you very much!

**Comment by AlexeyAB** [comment]
@nbkhuong 

> Which part of the code in calc_anchors where all of the size clustering is calculated, should I modify to add my code in there to remove the irrelevant big object?

You shouldn't do this.
* or just remove images with irrelevant objects from training dataset
* or just keep it, calculate anchors and train as usuall
