### ISSUE TITLE
Can i continue to train same model?

### ISSUE THREAD

**Issue by HungLearner** [AlexeyAB/darknet#2719]
If i already train once model, and need to add some new label.

Can i use this old model to continue training?

**Comment by drapado** [comment]
Yes, but not with the whole model. Adding a new class means that you have to change the number of classes and filters in the yolo layers of the .cfg file, so you can't use your previous yolo layers with your new cfg with more classes. However, you can still use the rest of the layers.

Given your weights files you can generate a partial weight file to continue training with the convolutional layers (no yolo layers as explained before)

./darknet partial cfg/yolov3.cfg yolov3.weights yolov3.conv.81 81

This command will generate a file called yolov3.conv.81, use it as initial weights for your new model

**Comment by HungLearner** [comment]
> Yes, but not with the whole model. Adding a new class means that you have to change the number of classes and filters in the yolo layers of the .cfg file, so you can't use your previous yolo layers with your new cfg with more classes. However, you can still use the rest of the layers.
> 
> Given your weights files you can generate a partial weight file to continue training with the convolutional layers (no yolo layers as explained before)
> 
> ./darknet partial cfg/yolov3.cfg yolov3.weights yolov3.conv.81 81
> 
> This command will generate a file called yolov3.conv.81, use it as initial weights for your new model

You means i can take final weight file to use "partial" command to get "yolov3.conv.81" of the output.

And then use it to continue traing new model?

If that true, the class of the previous mark labels object are alive?

**Comment by drapado** [comment]
> If that true, the class of the previous mark labels object are alive?
No, the classes are generated in the yolo layers, and if you change the number of classes you can't re-use the old yolo layers. Doing the partial command you delete the yolo layers from the weights. 

All this means that you can't re-use the information the network learn in the yolo layers for your old classes, but you can still use the information stored in all previous layers which will help in your new training process.

Hope my explanation is clear.

**Comment by HungLearner** [comment]
> > If that true, the class of the previous mark labels object are alive?
> > No, the classes are generated in the yolo layers, and if you change the number of classes you can't re-use the old yolo layers. Doing the partial command you delete the yolo layers from the weights.
> 
> All this means that you can't re-use the information the network learn in the yolo layers for your old classes, but you can still use the information stored in all previous layers which will help in your new training process.
> 
> Hope my explanation is clear.

Okay, thanks for your reply!

I will try to do it.

**Comment by kenrubiooo** [comment]
Hi, @drapado  

Thank you for explaining this. Was trying to have an answer with what the partial command does. I also encountered a similar query in #2642 but AlexeyAB told to use 94 instead of 81. Can you explain the reason behind? Thank you!

**Comment by drapado** [comment]
Then probably you can use 94 as well, which is even better since you re-use more knowledge from your previous model. Just try with 94 and if it doesn't give you any error from inconsistency between .cfg and .weights you can go on
