### ISSUE TITLE
Compiling on windows without GPU error, "LNK2001: unresolved external symbol ..."

### ISSUE THREAD

**Issue by azim92** [AlexeyAB/darknet#275]
1>------ Build started: Project: darknet_no_gpu, Configuration: Release x64 ------
1>captcha.obj : error LNK2001: unresolved external symbol __imp_pthread_join
1>data.obj : error LNK2001: unresolved external symbol __imp_pthread_mutex_unlock
1>data.obj : error LNK2001: unresolved external symbol __imp_pthread_create
1>data.obj : error LNK2001: unresolved external symbol __imp_pthread_mutex_lock
1>C:\Users\User\Desktop\YOLO\darknet\build\darknet\x64\\darknet_no_gpu.exe : fatal error LNK1120: 4 unresolved externals
1>Done building project "darknet_no_gpu.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

I've followed all instruction, finally it leads me to this.
Did i do something wrong somewhere?

**Comment by AlexeyAB** [comment]
@azim92 Do you compile **x64 & Release**?

Open `darknet_no_gpu.sln` and do:
 (right click on project) -> properties -> Linker -> Input -> Additional dependecies, check here:
`..\..\3rdparty\lib\x64\pthreadVC2.lib`

Do you have `pthreadVC2.lib` by path `3rdparty\dll\x64\`?

**Comment by azim92** [comment]
Thank you @AlexeyAB 
pthreadVC2.lib were missing from my Linker -> Input
Compilation success.
