### ISSUE TITLE
unable to compile darknet on Ubuntu 16.04

### ISSUE THREAD

**Issue by wdma** [AlexeyAB/darknet#2754]
I am attempting to compile a new download of darknet and am getting the following errors on compile.  What am I doing wrong?  Background, I have an older version darknet installed and working properly with opencv and cuDNN.  I am attempting to install the new version in a parallel directory, same virtualenv with the same packages.

Failed Compile with Error messages:

mkdir -p obj
mkdir -p backup
mkdir -p results
chmod +x *.sh
g++ -std=c++11 -Iinclude/ -I3rdparty/stb/include -DOPENCV `pkg-config --cflags opencv` -DCUDNN -DCUDNN_HALF -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -DCUDNN -I/usr/local/cudnn/include -DCUDNN_HALF -c ./src/http_stream.cpp -o obj/http_stream.o
./src/http_stream.cpp: In member function ‘bool JSON_sender::write(const char*)’:
./src/http_stream.cpp:228:21: warning: unused variable ‘n’ [-Wunused-variable]
                 int n = _write(client, outputbuf, outlen);
                     ^
./src/http_stream.cpp: In member function ‘bool MJPG_sender::write(const cv::Mat&)’:
./src/http_stream.cpp:475:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 if (n < outlen)
                       ^
gcc -Iinclude/ -I3rdparty/stb/include -DOPENCV `pkg-config --cflags opencv` -DCUDNN -DCUDNN_HALF -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -DCUDNN -I/usr/local/cudnn/include -DCUDNN_HALF -c ./src/gemm.c -o obj/gemm.o
./src/gemm.c: In function ‘convolution_2d’:
./src/gemm.c:2016:15: warning: unused variable ‘out_w’ [-Wunused-variable]
     const int out_w = (w + 2 * pad - ksize) / stride + 1;    // output_width=input_width for stride=1 and pad=1
               ^
./src/gemm.c:2015:15: warning: unused variable ‘out_h’ [-Wunused-variable]
     const int out_h = (h + 2 * pad - ksize) / stride + 1;    // output_height=input_height for stride=1 and pad=1
               ^
gcc -Iinclude/ -I3rdparty/stb/include -DOPENCV `pkg-config --cflags opencv` -DCUDNN -DCUDNN_HALF -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -DCUDNN -I/usr/local/cudnn/include -DCUDNN_HALF -c ./src/utils.c -o obj/utils.o
gcc -Iinclude/ -I3rdparty/stb/include -DOPENCV `pkg-config --cflags opencv` -DCUDNN -DCUDNN_HALF -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -DCUDNN -I/usr/local/cudnn/include -DCUDNN_HALF -c ./src/dark_cuda.c -o obj/dark_cuda.o
gcc -Iinclude/ -I3rdparty/stb/include -DOPENCV `pkg-config --cflags opencv` -DCUDNN -DCUDNN_HALF -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -DCUDNN -I/usr/local/cudnn/include -DCUDNN_HALF -c ./src/convolutional_layer.c -o obj/convolutional_layer.o
./src/convolutional_layer.c: In function ‘get_workspace_size32’:
./src/convolutional_layer.c:110:9: warning: implicit declaration of function ‘CHECK_CUDNN’ [-Wimplicit-function-declaration]
         CHECK_CUDNN(cudnnGetConvolutionForwardWorkspaceSize(cudnn_handle(),
         ^
./src/convolutional_layer.c:110:21: warning: implicit declaration of function ‘cudnnGetConvolutionForwardWorkspaceSize’ [-Wimplicit-function-declaration]
         CHECK_CUDNN(cudnnGetConvolutionForwardWorkspaceSize(cudnn_handle(),
                     ^
./src/convolutional_layer.c:110:61: warning: implicit declaration of function ‘cudnn_handle’ [-Wimplicit-function-declaration]
         CHECK_CUDNN(cudnnGetConvolutionForwardWorkspaceSize(cudnn_handle(),
                                                             ^
./src/convolutional_layer.c:111:18: error: ‘layer {aka struct layer}’ has no member named ‘srcTensorDesc’
                 l.srcTensorDesc,
                  ^
compilation terminated due to -Wfatal-errors.
Makefile:146: recipe for target 'obj/convolutional_layer.o' failed
make: *** [obj/convolutional_layer.o] Error 1

**Comment by AlexeyAB** [comment]
@wdma 

Do you use `make` or `cmake` for compiling?

What parameters did you set in the Makefile?

**Comment by pjspillai** [comment]
Seems like a CUDA/CUDNN incompatibility error.

Does it compile if you set the following in your Makefile?
GPU=1
CUDNN=0

**Comment by wdma** [comment]
@AlexeyAB  I was using make, but @pjspillai was right.  I removed cuDNN and the compile worked - thank you!!  closed
