### ISSUE TITLE
Save 1 image only per detection

### ISSUE THREAD

**Issue by ivder** [AlexeyAB/darknet#2757]
@AlexeyAB Hi again, I'm using your repo and integrated with my C++ project very well. I'm able to save detection results to images as well. But I want to save only 1 image per detected object. I don't want to have multiple duplicated image of same object. Any idea how to do that? Thank you

**Comment by drapado** [comment]
You can create a script to read every detected object (position, width and height) and draw each one in separate images

**Comment by ivder** [comment]
@drapado thanks for the idea, but not every detected image will have the same position, size, color, etc. The object is same but due to lighting, object movement, the position and size could be slightly different. I'm thinking about using template matching feature from opencv, but if there's other better solution or advice I'll be glad to hear it.

**Comment by ivder** [comment]
This is probably can be solved using object tracking

**Comment by Mahaaveer** [comment]
Hi,

i am having difficulty to acheive this .
were you able to do it with object tracking ?
if so, how do i do it ?
right now, i have a region of interest line drawn ( 20 pixels thick) and if center of detected object comes inside, it saves an image.
it is not as efficient as i would want it to be... it saves about 2-5 images of the detection depending of the speed of the object in the frame.
It'll be helpful if you can share how to acheive this using object tracking ?
Thanks.

**Comment by ivder** [comment]
@Mahaaveer Alexey provides 3 methods to do object tracking : kalman filter, track optical flow and custom tracking function (see the C++ example).
Kalman filter and track optical flow didn't work last time, so I used the custom tracking function which performed better but of course not perfect. So using that custom function, each detection will return the `track_id`. So if another detection occurs with the same `track_id`, it won't be saved. But once again, it is not perfect, especially if you have multiple similar objects that move quickly at the same time
