### ISSUE TITLE
OpenCV 4 compatibility

### ISSUE THREAD

**Issue by cenit** [AlexeyAB/darknet#2766]
Since vcpkg is quickly moving towards OpenCV 4 (https://github.com/Microsoft/vcpkg/pull/5169), we may be soon in a dangerous situation. At the moment darknet is the only port (project) still requiring OpenCV 3, all the others are completely ported to the new library. 

Because of mutual exclusivity you cannot have both libraries installed at the same time. This means that any other project requiring OpenCV would not be installable under vcpkg if you have darknet installed, or vice versa, you cannot install darknet if you already have any other project installed.

We should think about implementing something along the lines of https://github.com/pjreddie/darknet/commit/810d7f797bdb2f021dbe65d2524c2ff6b8ab5c8b + https://github.com/pjreddie/darknet/pull/1348 also here, what do you think?

**Comment by AlexeyAB** [comment]
Yes, next week I will fix the usage of OpenCV 4.0 by using C++ API.

**Comment by cenit** [comment]
darknet is OpenCV 4 ready since 1cad888641804b1ddddf03ad316aa3a6e9e679ad
yay!
