### ISSUE TITLE
Time discrepancies between  "detector test" and darknet.py

### ISSUE THREAD

**Issue by RyanCodes44** [AlexeyAB/darknet#2767]
Hi all, 

I'm running darknet on Ubuntu 18.04, python 3.6.7, OpenCV 3.4.0, Titan Xp GPU

When I run darknet using the command below it runs at 100 FPS or 0.01 seconds:
`./darknet detector test ...`

When I use darknet.py on the same image it runs at approximately 45 FPS or 0.025 seconds. 

I tried the issue in #1225 but still doesn't seem to work. Is there suppose to be a time difference between the two? Note my images are 720x405. I know the resizing may have an effect but as stated in #1225, the opencv processing should fix this? 

Any help would be much appreciated. Let me know if any more info is required!

**Comment by RyanCodes44** [comment]
@AlexeyAB any suggestions?

**Comment by AlexeyAB** [comment]
` ./darknet detector test ...` measures time only for Detection, without pre and post processing.

`./darknet detector demo ...` uses CPU-multithreading for pre and post processing, to hide CPU bottleneck.

Python examples are made only just as examples, you should implement it by yourself.

**Comment by RyanCodes44** [comment]
`./darknet detector test ...` doesn't include time for loading image then? Is this the reason for the time discrepancy between this command and detecting using 'darknet.py' python script?

**Comment by AlexeyAB** [comment]
Yes.

**Comment by RyanCodes44** [comment]
Okay I'll fix it for my application in the .c code to also include time to load image for correct FPS reports.

**Comment by AlexeyAB** [comment]
Correct FPS should be measured by using `./darknet detector demo ...`

**Comment by RyanCodes44** [comment]
If I wanted to use `./darknet detector test ...` could I just move `double time = get_time_point();` on line 1298 of src/detector.c above `image im = load_image(input, 0, 0, net.c);` on line 1285 to also include loading the image in FPS calculation? 

I'm defining my FPS as image loading time and detection time as I don't want to do any post-processing.

**Comment by AlexeyAB** [comment]
Yes, you can do it.

**Comment by RyanCodes44** [comment]
Thanks for your help!
