### ISSUE TITLE
Unable to open stream to internet camera

### ISSUE THREAD

**Issue by Arcticold** [AlexeyAB/darknet#2777]
The command for opening stream to internet camera uses HTTP
`darknet.exe detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights http://192.168.0.80:8080/video?dummy=param.mjpg`
however, I don't have stream over HTTP. I have RTSP. With http://pjreddie.com/darknet/ solution I was able to use the following command: `darknet.exe detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights rtsp://user:password@192.168.1.64:554`. It doesn't work with this darknet.exe though, giving the following error:
```
 Allocate additional workspace_size = 52.43 MB
Loading weights from yolov3.weights...
 seen 64
Done!
video file: rtsp://user:password@192.168.1.64:554
 Video-stream stopped!
Stream closed.
 Video-stream stopped!
Stream closed.
```

The end goal is to have uselib_track.exe eat the stream from the internet camera, but that only seems to accept image or video.
```
 try to allocate additional workspace_size = 52.43 MB
 CUDA allocate done!
object names loaded
input image or video filename: rtsp://user:password@192.168.1.64:554

 Video size: [0 x 0]
 exit_flag: detection_data.cap_frame.size = [0 x 0]
 t_cap exit
 t_write exit
 t_network exit
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(3.4.3) Error: Assertion failed (src.channels() == 3) in `anonymous-namespace'::BGR_to_GRAY, file C:\vcpkg\buildtrees\opencv\src\3.4.3-701a6234df\modules\cudaimgproc\src\color.cpp, line 496
```
 The reason I'm mentioning darknet.exe, is because even if uselib_track.exe would accept internet camera stream, I suspect there is another underlying problem in darknet.

**Comment by AlexeyAB** [comment]
I successfully use this command with HikVision RTSP camera:
`darknet.exe detector demo data/coco.data cfg/yolov3-tiny.cfg yolov3-tiny.weights -i 0 -thresh 0.25 rtsp://login:pass@192.168.0.228:554`

Can you use `rtsp://user:password@192.168.1.64:554` with `uselib.exe` instead of `uselib_track.exe` ?

**Comment by Arcticold** [comment]
I tried this command now: 
```
.\darknet.exe detector demo data/coco.data cfg/yolov3.cfg yolov3.weights -i 0 -thresh 0.25 rtsp://user:password@192.168.1.64:554
```
but it yields exactly the same result. My camera is HikVision IR Mini Bullet Network Camera.

Trying `rtsp://user:password@192.168.1.64:554` with uselib.exe does not work either.
Error with uselib.exe:
```
 try to allocate additional workspace_size = 52.43 MB
 CUDA allocate done!
object names loaded
input image or video filename: rtsp://user:password@192.168.1.64:554

 Video size: [0 x 0]
 exit_flag: detection_data.cap_frame.size = [0 x 0]
 t_cap exit
 t_write exit
 t_draw exit
 t_network exit
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(3.4.3) Error: Assertion failed (size.width>0 && size.height>0) in cv::imshow, file C:\vcpkg\buildtrees\opencv\src\3.4.3-701a6234df\modules\highgui\src\window.cpp, line 364
```
Error with uselib_track.exe:
```
 try to allocate additional workspace_size = 52.43 MB
 CUDA allocate done!
object names loaded
input image or video filename: rtsp://admin:yoloswag01@192.168.1.64:554

 Video size: [0 x 0]
 exit_flag: detection_data.cap_frame.size = [0 x 0]
 t_cap exit
 t_write exit
OpenCV: terminate handler is called! The last OpenCV error is:
 t_network exit
OpenCV(3.4.3) Error: Assertion failed (src.channels() == 3) in `anonymous-namespace'::BGR_to_GRAY, file C:\vcpkg\buildtrees\opencv\src\3.4.3-701a6234df\modules\cudaimgproc\src\color.cpp, line 496
```

**Comment by AlexeyAB** [comment]
Do you have `opencv_ffmpeg345_64.dll` near with `darknet.exe`?

Can you open your URL `rtsp://user:password@192.168.1.64:554` by using VLC media player on the same PC and the same Windows? https://www.videolan.org/vlc/index.ru.html

**Comment by Arcticold** [comment]
Hi!

I do not have `opencv_ffmpeg345_64.dll` near `darknet.exe`. I searched and it does exist in the separately downloaded opencv pack, but there isn't one in the opencv installation that came with `vcpkg`. What would be the correct way of getting this? (Also, just for testing, I copied that file from separately downloaded opencv next to `darknet.exe`, but it didn't change anything).

The RTSP stream does open in VLC on the same Windows installation.

**Comment by AlexeyAB** [comment]
> The RTSP stream does open in VLC on the same Windows installation.

It seems something wrong with your RTSP url, or with Firewall.


> I searched and it does exist in the separately downloaded opencv pack, but there isn't one in the opencv installation that came with vcpkg.


Did you install OpenCV by using vcpkg as `opencv[ffmpeg,cuda]` (or `opencv[ffmpeg]`) instead of `opencv` ?

**Comment by Arcticold** [comment]
Hi!

I might have worded it bad - I meant that it works fine with VLC.

Anyways, I installed OpenCV[ffmpeg,cuda] with VCPKG, placed the `opencv_ffmpeg345_64.dll` into the Release folder, recompiled darknet and now it works fine with darknet.exe, uselib.exe and uselib_track.exe.
