### ISSUE TITLE
FPS_CAPTURE (video playing speed) too fast with TRACK_OPTFLOW

### ISSUE THREAD

**Issue by ivder** [AlexeyAB/darknet#2788]
@AlexeyAB Hi, I have problem detecting video using yolo_console_dll.cpp with `TRACK_OPTFLOW` on. Without track_optflow the detection on video works well, when I compile it using track_optflow the `FPS_CAPTURE` is very high and the video playing speed becomes super fast up  to 500 ms. 
![image](https://user-images.githubusercontent.com/32887298/55298561-6425aa00-5469-11e9-8c4c-c35ad1be9abd.png)

It won't detect anything because it's too fast. I'm using opencv330 with cuda support and it has cudaoptflow.dll

**Comment by AlexeyAB** [comment]
@ivder Hi,

If you want to track ID of objects, then it will be tracked even without TRACK_OPTFLOW.

TRACK_OPTFLOW can be used to increase FPS for detection from Video camera in real-time, when your GPU isn't fast enough - so in this case FPS capture will be limited by FPS of Camera (~30-60 FPS).

There is not much point in using TRACK_OPTFLOW for a video file.

**Comment by ivder** [comment]
@AlexeyAB Thank you, yes I see that you have custom function for tracking, really great work!
