### ISSUE TITLE
Save weigths with best mAP as yolov3-obj_best.weigths

### ISSUE THREAD

**Issue by drapado** [AlexeyAB/darknet#2790]
Hi, I was thinking that keeping a file to save the weights with best mAP calculation during training might be handy. Specially since the weights are just saved every 1000 iterations and sometimes you get a very good mAP calculation at an intermediate point which weights will be deleted when you reach the next 100 iterations (yolov3-obj_last.weigths)

**Comment by ivder** [comment]
Great idea, having same thought for a while
