### ISSUE TITLE
Segmentation Fault (Core Dumped)

### ISSUE THREAD

**Issue by keko950** [AlexeyAB/darknet#2793]
Hello!

I've been using Darknet since a few months ago with any problem till now. Last days i pulled my darknet to the upstream version in the repo. However now im receving a seg fault core dumped while detecting! I managed to debug a bit and i found the seg fault happens when it tries to free dets (LINE 713: src/network.c) 

We are using Darknet to online detect using frames from a stream. We had been using an old version of darknet during all this time (2-3 months ago) and worked pretty well, but last changes seems to broke it somehow.

Any ideas?

**Comment by AlexeyAB** [comment]
@keko950 Hi,

Try to do clean installation of Darknet in the separate empty folder.

Can you provide the simplest reproducable test for this issue?

Also can you provide more information, what command and params in Makefile do you use, what CUDA, cuDNN and GPU do you use?

**Comment by keko950** [comment]
Thanks for the fast response @AlexeyAB !

Im trying right now with the a clean darknet, so i will let you know if it crashes again.

Sadly i can not reproduce it whenever i want. As i said, we are getting frames from a streaming, we crop and resize it to fit darknet needs, but sometimes at a random moment, it just crashes with a seg fault when it reachs the line i commented in my first comment and tries to free dets. We use the darknet.py functions to load those frames. We didn't change any function or code of darknet. It seems more like a memory management problem. Also, I dont know if it matters but we are running it from a crontab.

Here it is the parameters we are using:

> GPU=1
> CUDNN=1
> CUDNN_HALF=1
> OPENCV=1
> AVX=1
> OPENMP=1
> LIBSO=1
> ZED_CAMERA=0

I'm using a RTX 2070 with cuda 10, and cudnn 7.5

**Comment by AlexeyAB** [comment]
Also try to set `AVX=0 OPENMP=0`

**Comment by keko950** [comment]
Done. Trying with a clean install and AVX=0 and OPENMP=0.

However, avx and openmp are only used when is used cpu detection right?

**Comment by AlexeyAB** [comment]
> However, avx and openmp are only used when is used cpu detection right?

It improves speed of the network only when CPU is used. 
But some side effect can be even when GPU is used.

**Comment by keko950** [comment]
Still getting seg fault, same line, at a random moment.

**Comment by MateuszKlimas** [comment]
Im getting the same problem as you, when I try to run a detection on an image, it loads the weights and everything, but at the end I get a segmentation fault. I have tried reinstalling and everything, but the same happens.

**Comment by keko950** [comment]
> Im getting the same problem as you, when I try to run a detection on an image, it loads the weights and everything, but at the end I get a segmentation fault. I have tried reinstalling and everything, but the same happens.

But it happens at random moments? If you cant event detect on a image, maybe its a bug in your code.
Did you commented the free_image in darknet.py?

**Comment by AlexeyAB** [comment]
@keko950 

> We use the darknet.py functions to load those frames.

Do you use the default `darknet.py` or `darknet_video.py` example or did you change it?

**Comment by MateuszKlimas** [comment]
> > Im getting the same problem as you, when I try to run a detection on an image, it loads the weights and everything, but at the end I get a segmentation fault. I have tried reinstalling and everything, but the same happens.
> 
> But it happens at random moments? If you cant event detect on a image, maybe its a bug in your code.
> Did you comment the free_image in darknet.py?

It happens always after saying that all predictions has been done in X time.

`Total BFLOPS 115.513 
 Allocate additional workspace_size = 22.04 MB 
Loading weights from yolov3-person_3200.weights...
 seen 64 
Done!
../darknet/config/frame140.jpg: Predicted in 134.219000 milli-seconds.
Segmentation fault (core dumped)`

**Comment by keko950** [comment]
> @keko950
> 
> > We use the darknet.py functions to load those frames.
> 
> Do you use the default `darknet.py` or `darknet_video.py` example or did you change it?

Yeah, i changed it, but to make it work with our software. I can actually show you the code itself since its not very changed. I removed some little code parts that are sensitive and refers to our software, but this would be our darknetdetector.py class

> 
> #!python3
> """
> Python 3 wrapper for identifying objects in images
> 
> Requires DLL compilation
> 
> Both the GPU and no-GPU version should be compiled; the no-GPU version should be renamed "yolo_cpp_dll_nogpu.dll".
> 
> On a GPU system, you can force CPU evaluation by any of:
> 
> - Set global variable DARKNET_FORCE_CPU to True
> - Set environment variable CUDA_VISIBLE_DEVICES to -1
> - Set environment variable "FORCE_CPU" to "true"
> 
> 
> To use, either run performDetect() after import, or modify the end of this file.
> 
> See the docstring of performDetect() for parameters.
> 
> Directly viewing or returning bounding-boxed images requires scikit-image to be installed (`pip install scikit-image`)
> 
> 
> Original *nix 2.7: https://github.com/pjreddie/darknet/blob/0f110834f4e18b30d5f101bf8f1724c34b7b83db/python/darknet.py
> Windows Python 2.7 version: https://github.com/AlexeyAB/darknet/blob/fc496d52bf22a0bb257300d3c79be9cd80e722cb/build/darknet/x64/darknet.py
> 
> @author: Philip Kahn
> @date: 20180503
> """
> #pylint: disable=R, W0401, W0614, W0703
> from ctypes import *
> import math
> import random
> import os
> import logging
> import os
> import threading
> import cv2
> import numpy
> def sample(probs):
>     s = sum(probs)
>     probs = [a/s for a in probs]
>     r = random.uniform(0, 1)
>     for i in range(len(probs)):
>         r = r - probs[i]
>         if r <= 0:
>             return i
>     return len(probs)-1
> 
> def c_array(ctype, values):
>     arr = (ctype*len(values))()
>     arr[:] = values
>     return arr
> 
> class BOX(Structure):
>     _fields_ = [("x", c_float),
>                 ("y", c_float),
>                 ("w", c_float),
>                 ("h", c_float)]
> 
> class DETECTION(Structure):
>     _fields_ = [("bbox", BOX),
>                 ("classes", c_int),
>                 ("prob", POINTER(c_float)),
>                 ("mask", POINTER(c_float)),
>                 ("objectness", c_float),
>                 ("sort_class", c_int)]
> 
> 
> class IMAGE(Structure):
>     _fields_ = [("w", c_int),
>                 ("h", c_int),
>                 ("c", c_int),
>                 ("data", POINTER(c_float))]
> 
> class METADATA(Structure):
>     _fields_ = [("classes", c_int),
>                 ("names", POINTER(c_char_p))]
> 
> 
> 
> #lib = CDLL("/home/pjreddie/documents/darknet/libdarknet.so", RTLD_GLOBAL)
> #lib = CDLL("libdarknet.so", RTLD_GLOBAL)
> hasGPU = True
> if os.name == "nt":
>     cwd = os.path.dirname(__file__)
>     os.environ['PATH'] = cwd + ';' + os.environ['PATH']
>     winGPUdll = os.path.join(cwd, "yolo_cpp_dll.dll")
>     winNoGPUdll = os.path.join(cwd, "yolo_cpp_dll_nogpu.dll")
>     envKeys = list()
>     for k, v in os.environ.items():
>         envKeys.append(k)
>     try:
>         try:
>             tmp = os.environ["FORCE_CPU"].lower()
>             if tmp in ["1", "true", "yes", "on"]:
>                 raise ValueError("ForceCPU")
>             else:
>                 print("Flag value '"+tmp+"' not forcing CPU mode")
>         except KeyError:
>             # We never set the flag
>             if 'CUDA_VISIBLE_DEVICES' in envKeys:
>                 if int(os.environ['CUDA_VISIBLE_DEVICES']) < 0:
>                     raise ValueError("ForceCPU")
>             try:
>                 global DARKNET_FORCE_CPU
>                 if DARKNET_FORCE_CPU:
>                     raise ValueError("ForceCPU")
>             except NameError:
>                 pass
>             # print(os.environ.keys())
>             # print("FORCE_CPU flag undefined, proceeding with GPU")
>         if not os.path.exists(winGPUdll):
>             raise ValueError("NoDLL")
>         lib = CDLL(winGPUdll, RTLD_GLOBAL)
>     except (KeyError, ValueError):
>         hasGPU = False
>         if os.path.exists(winNoGPUdll):
>             lib = CDLL(winNoGPUdll, RTLD_GLOBAL)
>             print("Notice: CPU-only mode")
>         else:
>             # Try the other way, in case no_gpu was
>             # compile but not renamed
>             lib = CDLL(winGPUdll, RTLD_GLOBAL)
>             print("Environment variables indicated a CPU run, but we didn't find `"+winNoGPUdll+"`. Trying a GPU run anyway.")
> else:
>     lib = CDLL("./libdarknet.so", RTLD_GLOBAL)
> lib.network_width.argtypes = [c_void_p]
> lib.network_width.restype = c_int
> lib.network_height.argtypes = [c_void_p]
> lib.network_height.restype = c_int
> 
> copy_image_from_bytes = lib.copy_image_from_bytes
> copy_image_from_bytes.argtypes = [IMAGE,c_char_p]
> 
> def network_width(net):
>     return lib.network_width(net)
> 
> def network_height(net):
>     return lib.network_height(net)
> 
> predict = lib.network_predict_ptr
> predict.argtypes = [c_void_p, POINTER(c_float)]
> predict.restype = POINTER(c_float)
> 
> if hasGPU:
>     set_gpu = lib.cuda_set_device
>     set_gpu.argtypes = [c_int]
> 
> make_image = lib.make_image
> make_image.argtypes = [c_int, c_int, c_int]
> make_image.restype = IMAGE
> 
> get_network_boxes = lib.get_network_boxes
> get_network_boxes.argtypes = [c_void_p, c_int, c_int, c_float, c_float, POINTER(c_int), c_int, POINTER(c_int), c_int]
> get_network_boxes.restype = POINTER(DETECTION)
> 
> make_network_boxes = lib.make_network_boxes
> make_network_boxes.argtypes = [c_void_p]
> make_network_boxes.restype = POINTER(DETECTION)
> 
> free_detections = lib.free_detections
> free_detections.argtypes = [POINTER(DETECTION), c_int]
> 
> free_ptrs = lib.free_ptrs
> free_ptrs.argtypes = [POINTER(c_void_p), c_int]
> 
> network_predict = lib.network_predict_ptr
> network_predict.argtypes = [c_void_p, POINTER(c_float)]
> 
> reset_rnn = lib.reset_rnn
> reset_rnn.argtypes = [c_void_p]
> 
> load_net = lib.load_network
> load_net.argtypes = [c_char_p, c_char_p, c_int]
> load_net.restype = c_void_p
> 
> load_net_custom = lib.load_network_custom
> load_net_custom.argtypes = [c_char_p, c_char_p, c_int, c_int]
> load_net_custom.restype = c_void_p
> 
> do_nms_obj = lib.do_nms_obj
> do_nms_obj.argtypes = [POINTER(DETECTION), c_int, c_int, c_float]
> 
> do_nms_sort = lib.do_nms_sort
> do_nms_sort.argtypes = [POINTER(DETECTION), c_int, c_int, c_float]
> 
> free_image = lib.free_image
> free_image.argtypes = [IMAGE]
> 
> letterbox_image = lib.letterbox_image
> letterbox_image.argtypes = [IMAGE, c_int, c_int]
> letterbox_image.restype = IMAGE
> 
> load_meta = lib.get_metadata
> lib.get_metadata.argtypes = [c_char_p]
> lib.get_metadata.restype = METADATA
> 
> load_image = lib.load_image_color
> load_image.argtypes = [c_char_p, c_int, c_int]
> load_image.restype = IMAGE
> 
> rgbgr_image = lib.rgbgr_image
> rgbgr_image.argtypes = [IMAGE]
> 
> predict_image = lib.network_predict_image
> predict_image.argtypes = [c_void_p, IMAGE]
> predict_image.restype = POINTER(c_float)
> 
> netMain = None
> metaMain = None
> 
> def array_to_image(arr):
>     # need to return old values to avoid python freeing memory
>     print("starting conv array to image")
>     arr = arr.transpose(2,0,1)
>     c = arr.shape[0]
>     h = arr.shape[1]
>     w = arr.shape[2]
>     arr = numpy.ascontiguousarray(arr.flat, dtype=numpy.float32) / 255.0
>     data = arr.ctypes.data_as(POINTER(c_float))
>     im = IMAGE(w,h,c,data)
>     print("finished array to image")
>     return im, arr
> 
> 
> 
> def classify(net, meta, im):
>     out = predict_image(net, im)
>     res = []
>     for i in range(meta.classes):
>         nameTag = meta.names[i]
>         res.append((nameTag, out[i]))
>     res = sorted(res, key=lambda x: -x[1])
>     return res
> 
> 
> class DarknetDetector:
>     """docstring for DarknetDetector."""
>     def __init__(self, w_f, cfg_f, meta_f, roi, debug, thresh=.6, **kwargs):
>         super(DarknetDetector, self).__init__()
>         self.debug = debug
>         self.network = load_net(cfg_f.encode('utf-8'), w_f.encode('utf-8'), 0)
>         self.meta = load_meta(meta_f.encode('utf-8'))
>         self.roi = roi
>         self.thresh = thresh
> 
> 
>     def _detect(self,net, meta, im, thresh=.5, hier_thresh=.5, nms=.45):
>         #import cv2
>         #custom_image_bgr = cv2.imread(image) # use: detect(,,imagePath,)
>         #custom_image = cv2.cvtColor(custom_image_bgr, cv2.COLOR_BGR2RGB)
>         #custom_image = cv2.resize(custom_image,(lib.network_width(net), lib.network_height(net)), interpolation = cv2.INTER_LINEAR)
>         #import scipy.misc
>         #custom_image = scipy.misc.imread(image)
>         #im, arr = array_to_image(custom_image)		# you should comment line below: free_image(im)
>         num = c_int(0)
>         print("Assigned num")
>         pnum = pointer(num)
>         print("Assigned pnum")
>         predict_image(net, im)
>         print("did prediction")
>         #dets = get_network_boxes(net, custom_image_bgr.shape[1], custom_image_bgr.shape[0], thresh, hier_thresh, None, 0, pnum, 0) # OpenCV
>         dets = get_network_boxes(self.network, im.w, im.h, self.thresh, hier_thresh, None, 0, pnum, 0)
>         print("Got dets")
>         num = pnum[0]
>         print("got zeroth index of pnum")
>         
>         if nms:
>             do_nms_sort(dets, num, meta.classes, nms)
>         print("did sort")
>         #Como va haber dos clases: balón y jugador se crea una lista de listas
>         #De esta manera podemos separar las detecciones por clases
>         res = [[],[]]
>         print("about to range")
>         for j in range(num):
>             for i in range(meta.classes):
>                 if dets[j].prob[i] > 0:
>                     b = dets[j].bbox
>                     nameTag = meta.names[i]
>                     detection = [nameTag, dets[j].prob[i], [(b.x - b.w/2)  + (windowIndex * self.step) + start_position, (b.y - b.h/2), b.w, b.h]]
>                     res[i].append(detection)
>         print("did range")
>         res[0] = sorted(res[0], key=lambda x: -x[1])
>         print("did sort after range")
>         #free_image(im)
>         free_detections(dets, num)
>         print("freed detections")
>         return res[0], res[1]
> 
>     def predict(self, frames):
>         windowIndex = 0
>         class1 = []
>         class0 = []
>         for f in frames:
>             class0_dets, class1_dets = self._detect(self.network, self.meta, array_to_image(f)[0], thresh=self.thresh)
>             if ballList_left != []:
>                 class1.append(ballList_left[0])
>             class0.extend(playerList_left)
> 
>         #Descartamos extremos
>         if len(players) > 3:
>             class0 = sorted(class0, key = lambda x: x[2][0], reverse=True)
>             class0.pop(0)
>             class0.pop(len(class0)-1)
>         else:
>             class0 = []
>         return  class1, class0

**Comment by keko950** [comment]
I think we may found what is going on @AlexeyAB .

We have been using a modified version of a ffmpeg decoder which has a memory leak, to solve it, we call manually the python garbage collector a few times every second. So, maybe the garbage collector are also deleting some important data for darknet? Anyway, for some reason, seg fault is not happening on olds version of darknet..

**Comment by MateuszKlimas** [comment]
> I think we may found what is going on @AlexeyAB .
> 
> We have been using a modified version of a ffmpeg decoder which has a memory leak, to solve it, we call manually the python garbage collector a few times every second. So, maybe the garbage collector are also deleting some important data for darknet? Anyway, for some reason, seg fault is not happening on olds version of darknet..

That's true, and older version I was doing the same call and it worked all the time. But I have to say that I get this error using this call: 

`./darknet detector test data/coco.data cfg/yolov3.cfg yolov3.weights test1.jpg`

I'm not using the darknet.py script

**Comment by AlexeyAB** [comment]
@MateuszKlimas 

> ./darknet detector test data/coco.data cfg/yolov3.cfg yolov3.weights test1.jpg

I can use this command without any issue.

**Comment by AlexeyAB** [comment]
@keko950 

> I think we may found what is going on @AlexeyAB .
> 
> We have been using a modified version of a ffmpeg decoder which has a memory leak, to solve it, we call manually the python garbage collector a few times every second. So, maybe the garbage collector are also deleting some important data for darknet? Anyway, for some reason, seg fault is not happening on olds version of darknet..

Try to reproduce this issue with default ffmpeg and without manual using of garbage collector.

**Comment by keko950** [comment]
> @keko950
> 
> > I think we may found what is going on @AlexeyAB .
> > We have been using a modified version of a ffmpeg decoder which has a memory leak, to solve it, we call manually the python garbage collector a few times every second. So, maybe the garbage collector are also deleting some important data for darknet? Anyway, for some reason, seg fault is not happening on olds version of darknet..
> 
> Try to reproduce this issue with default ffmpeg and without manual using of garbage collector.

Im testing right now darknet last official release (18 feb), i will test without the garbage collector next. I will update this to you asap

**Comment by keko950** [comment]
Latest release fails aswell, apparently does not crash without garbage collection, but we can not remove the garbage collection because we run out of memory veeeery fast..

**Comment by MateuszKlimas** [comment]
> @MateuszKlimas
> 
> > ./darknet detector test data/coco.data cfg/yolov3.cfg yolov3.weights test1.jpg
> 
> I can use this command without any issue.

Quite strange. I tried deactivating cuDNN in case this was the fault, but I continue having the same issue.

**Comment by AlexeyAB** [comment]
@keko950 

> Latest release fails aswell, **apparently does not crash without garbage collection**, but we can not remove the garbage collection because we run out of memory veeeery fast..

So the issue isn't in the Darknet.

Try to enable garbage collector and comment this line in your Python code `free_detections(dets, num)`
Will it work sucessfully without memory leaks, and will garbage collector free this memory area?

**Comment by keko950** [comment]
> @keko950
> 
> > Latest release fails aswell, **apparently does not crash without garbage collection**, but we can not remove the garbage collection because we run out of memory veeeery fast..
> 
> So the issue isn't in the Darknet.
> 
> Try to enable garbage collector and comment this line in your Python code `free_detections(dets, num)`
> Will it work sucessfully without memory leaks, and will garbage collector free this memory area?

I said apparently because without the garbage collector i run out of memory in a few minutes so i cant say at all it is working :( 

I will try your advice now!

**Comment by keko950** [comment]
Also, why does the last upstream of darknet fails but not a older one? Hmm... i will try to debug it with pdb

**Comment by keko950** [comment]
Cannot comment free_detections, garbage collector doesnt manage to free with exit that memory area.

**Comment by AlexeyAB** [comment]
@keko950 

Try to do these changes:

* `num_obj = pnum[0]` instead of https://github.com/AlexeyAB/darknet/blob/6231b748c44e2007b5c3cbf765a50b122782c5a2/darknet.py#L258

----

* `if debug: print("Ranging on "+str(j)+" of "+str(num_obj))` instead of https://github.com/AlexeyAB/darknet/blob/6231b748c44e2007b5c3cbf765a50b122782c5a2/darknet.py#L266

----

* `for j in range(num_obj):` instead of https://github.com/AlexeyAB/darknet/blob/6231b748c44e2007b5c3cbf765a50b122782c5a2/darknet.py#L265

----


If it doesn't help, then try to debug `free_detections()` function. Try to comment some lines and check which cause an error: https://github.com/AlexeyAB/darknet/blob/6231b748c44e2007b5c3cbf765a50b122782c5a2/src/network.c#L717

**Comment by MateuszKlimas** [comment]
Did you manages to solve the problem @keko950 ?

**Comment by keko950** [comment]
Sadly didn't work @AlexeyAB .

No @MateuszKlimas , I'm still looking for what is making this happen. 
I will update when i found something.

**Comment by keko950** [comment]
Hey @AlexeyAB , in the array_to_image func (in darknet.py) you wrote the following comment:

> # need to return old values to avoid python freeing memory

Why do we need to save return arr? I mean, why python would try to free it and why it is important?
I think this was my issue, i wasnt saving the return of that func, i just passed it directly as array_to_image(frame)[0] so i get the image. Now i changed it, storing the values just like this:

`            for f in frames:
                im, **arr** = array_to_image(f)
                class0, class1 = self._detect(self.network, self.meta, **im** , thresh=self.thresh)
`

And seems to be working right now, i will make more tests

**Comment by AlexeyAB** [comment]
@keko950 Does it solve you problem?

By fixing this incorrect line in your code:
`class0_dets, class1_dets = self._detect(self.network, self.meta, array_to_image(f)[0], thresh=self.thresh)`

**Comment by keko950** [comment]
> @keko950 Does it solve you problem?
> 
> By fixing this incorrect line in your code:
> `class0_dets, class1_dets = self._detect(self.network, self.meta, array_to_image(f)[0], thresh=self.thresh)`

Yes! I tested it during more than 12 hours and didn't crash, so its fine :)

**Comment by MateuszKlimas** [comment]
I think I have found the issue on my case. At image.c I wrote this at the beggining of the function `draw_detections_v3`.
`printf("DETECTED OBJECTS: %d\n", selected_detections_num);`
`FILE *f;`
`f = open("number_detections.txt","a");`
`fprintf(f,"%d\n", selected_detections_num);`
`fclose(f);`
This is for saving the number of detected objects on a file. Any idea why does it fails?

**Comment by MateuszKlimas** [comment]
> I think I have found the issue on my case. At image.c I wrote this at the beginning of the function `draw_detections_v3`.
> `printf("DETECTED OBJECTS: %d\n", selected_detections_num);`
> `FILE *f;`
> `f = open("number_detections.txt","a");`
> `fprintf(f,"%d\n", selected_detections_num);`
> `fclose(f);`
> This is for saving the number of detected objects on a file. Any idea why does it fails?

Well, it's related with fprintf().

**Comment by mrkieumy** [comment]
Hi @keko950 
where do you change that command? I didn't find the class0 and class1.
Thanks.

**Comment by keko950** [comment]
> Hi @keko950
> where do you change that command? I didn't find the class0 and class1.
> Thanks.

Hi! What you mean? Class0 and Class1 objects belong to my own changes in the code.
The real trouble was **arr** object. You need to save the returned value by array_to_image to avoid python freeing it.

`
im, arr = array_to_image(f)
`
