### ISSUE TITLE
Failed to load dynlib/dll with darknet as dll on windows 10

### ISSUE THREAD

**Issue by acker-t** [AlexeyAB/darknet#2794]
Using darknet as a dll with a pyinstaller compiled program, this works fine on my pc but when i try to use it on another pc i get PyInstallerImportError: Failed to load dynlib/dll 'yolo_cpp_dll.dll'. Most probably this dynlib/dll was not found when the application was frozen.

From what i found it's suppose to mean that the dll is calling another dll that can't be found, but in my file i have all the dll needed from darknet (opencv and pthread) and i have cuda and cudnn installed.

The only thing i don't have is VS installed on the second pc, but the build tools are.

**Comment by AlexeyAB** [comment]
May be you should copy CUDA, cuDNN, pthreads and OpenCV dlls.

Also may be you should install (if you used MSVS 2015): https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145&6B49FDFB-8E5B-4B07-BC31-15695C5A2143=1

**Comment by acker-t** [comment]
My work is now working with the yolo_cpp_dll_nogpu.dll after installing visual c++ 2010 redistribuable. But i can't use yolo_cpp_dll.dll on another pc, even with all the dll and the visual c++ 2015 installed.

The error may be from cuda since the nogpu is working fine but the installation are the same and the paths are all set.

I tried with dll generated from msvs 2015 and 2017 too.

**Comment by AlexeyAB** [comment]
So copy cudart_...dll cublas_..dll, ... cudnn...dll

**Comment by acker-t** [comment]
Thanks, the copy of this dlls fixed it

**Comment by taoting0722** [comment]
Hello! I also encountered the same problem, but it has not been resolved. I can run exe on some computers, but I will report the above error (the CPU version I use) when running on some computers. May I ask what is the cause of this problem?

**Comment by yungongzi** [comment]
Hi, May i ask that the other computer must have cuda and cudnn installed?
