### ISSUE TITLE
Tag Dataset By using Existing Model

### ISSUE THREAD

**Issue by mdv3101** [AlexeyAB/darknet#2795]
I have already trained a model using 3,000 images. Now i want to use this model to tag 20,000 images. Is there an option to tag these images automatically ? 

After this i will just check these images in yolo_mark.

Regards.

**Comment by AlexeyAB** [comment]
@mdv3101 Hi,

Yes, this is called `pseudo labeling` https://github.com/AlexeyAB/darknet#how-to-use-on-the-command-line

Pseudo-lableing - to process a list of images `data/new_train.txt` and save results of detection in Yolo training format for each image as label `<image_name>.txt` (in this way you can increase the amount of training data) use: 

`./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights -thresh 0.25 -dont_show -save_labels < data/new_train.txt`
