### ISSUE TITLE
What's the meaning of this paragraph?

### ISSUE THREAD

**Issue by panovr** [AlexeyAB/darknet#28]
There is a paragraph in readme written as:
> Download The Pascal VOC Data and unpack it to directory build\darknet\x64\data\voc: http://pjreddie.com/projects/pascal-voc-dataset-mirror/ will be created file voc_label.py and \VOCdevkit\ dir

May I ask what's meaning of this paragraph?

**Comment by AlexeyAB** [comment]
@panovr 

This paragraph means that you should download images of Pascal VOC dataset, and also download file `voc_label.py` which will convert labels of objects from VOC-format to Yolo-format.

And I changed this part of the manual that to be more understandable.

> 2. Download The Pascal VOC Data and unpack it to directory `build\darknet\x64\data\voc` will be created dir `build\darknet\x64\data\voc\VOCdevkit\`:
>     * http://pjreddie.com/media/files/VOCtrainval_11-May-2012.tar
>     * http://pjreddie.com/media/files/VOCtrainval_06-Nov-2007.tar
>     * http://pjreddie.com/media/files/VOCtest_06-Nov-2007.tar
>     
>     2.1 Download file `voc_label.py` to dir `build\darknet\x64\data\voc`: http://pjreddie.com/media/files/voc_label.py
>

**Comment by panovr** [comment]
Thanks :+1:
