### ISSUE TITLE
What is the unit for anchors?

### ISSUE THREAD

**Issue by jimgros** [AlexeyAB/darknet#280]
Hi,
First off, thanks for this! It's really great!
I am trying to use it on images which have both small and very large objects (objects taking more than 50% of the image size either in height or width).
I would like to modify and add anchors, but I'm wondering what does the values stand for? What unit is it? Is there a maximum?
Thanks!

**Comment by AlexeyAB** [comment]
Hi,

As you can see:
* input resolution is 416 x 416
* output resolution is 13 x 13
![image](https://user-images.githubusercontent.com/4096485/33239284-6d56f486-d2af-11e7-9a98-c31da712f665.png)

So anchors is the `width, height` of the objects for output resolution `13 x 13`, here are 5 anchors with 2 values (`width, height`) for each anchor, i.e. 10 values: https://github.com/AlexeyAB/darknet/blob/c1904068afc431ca54771e5dc20f2c588e876956/cfg/yolo-voc.cfg#L242

**Comment by jimgros** [comment]
Thanks for the prompt answer! 
I thought it was that, but wasn't sure.

**Comment by szm2015** [comment]
Hi @AlexeyAB , I know it's a closed issue but I hope you answer this. Does what you said, mean that in calculating the anchors for a custom data I should first scale the original width and height of my objects by 32 and then use them in k-means clustering (I don't think the order really matters what I mean is the 32 factor). From what I get of studying yolo.cfg model, it downsamples the input images by a factor of 32 (regardless of input size, so a 320x320 image will lead to 10x10 output) and so the cells have a fixed size of 32x32 and the anchors should be relative to those cell sizes.

**Comment by AlexeyAB** [comment]
@szm2015 As input of network you have `img_width, img_height` and output of netowrk: `img_width/32, img_height/32`. Also you have object sizes (width and height) from `0.0` to `1.0`.

* So you can at first calculate k-means width=`(0.0 - 1.0)` and height=`(0.0 - 1.0)` and then multiply them by `img_width/32` and `img_height/32`
* Or at first multiply object sizes by `img_width/32` and `img_height/32` and then calculate k-means.

This is true if you are using the standard neural network, without deleting or adding: max-pool or reorg layers.

**Comment by szm2015** [comment]
Thank you very much for this complete explanation :)
