### ISSUE TITLE
Training on 2 GPU's work fine - On 3 GPU's training stops randomly

### ISSUE THREAD

**Issue by flowzen1337** [AlexeyAB/darknet#2807]
Hi @AlexeyAB ,

I hope you can help me!
I am trying to train a custom dataset on multi-gpu (3x GPU's 1080TI GTX) but it still stops working after 10min - 1h in the middle of nowhere. Only rebooting the system helps to restart the training and the same problem occurs over and over again.

When i just use 2x GPU's it is working fine and runs forever. I've already switched and replaced every GPU to make sure that the GPU isnt the problem, nothing helped so far.

**Command i use:**
`./darknet detector train cfg/names.data cfg/yolov3.cfg  ../screenshots/saved/yolov3_last.weights darknet53.conv.74 -dont_show -gpus 0,1,2`

**My Makefile:**
`....
....
GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=1
AVX=0
OPENMP=0
LIBSO=1
ZED_CAMERA=0

DEBUG=0

ARCH= -gencode arch=compute_30,code=sm_30 \
      -gencode arch=compute_35,code=sm_35 \
      -gencode arch=compute_50,code=[sm_50,compute_50] \
      -gencode arch=compute_52,code=[sm_52,compute_52] \
          -gencode arch=compute_61,code=[sm_61,compute_61]

OS := $(shell uname)
ARCH= -gencode arch=compute_61,code=sm_61 -gencode arch=compute_61,code=compute_61
....
....
`

**My yolov3.cfg file:**
`....
....
[net]
batch=64
subdivisions=48
#width=608
#height=608
width=416
height=416
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
burn_in=1000
max_batches = 500200
policy=steps
steps=400000,450000
scales=.1,.1

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=3
stride=2
pad=1
....
....`

A example where the training stops:
**OS Version:**
`Ubuntu 18.04
`

**nvidia components:**
`CUDA Version: 10.1
Nvidia Driver Version: 418.43
cuDNN: 7.4.2.24-1+cuda10.0
`
**nvidia-smi output: (darknet is running but GPU-Util says 0% after a while)**
`+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.43       Driver Version: 418.43       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:05:00.0 Off |                  N/A |
|  0%   43C    P8    10W / 280W |   2370MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:08:00.0 Off |                  N/A |
|  0%   48C    P2    53W / 280W |   2233MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:09:00.0 Off |                  N/A |
|  0%   44C    P8    11W / 280W |   2233MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1807      C   ./darknet                                   2360MiB |
|    1      1807      C   ./darknet                                   2223MiB |
|    2      1807      C   ./darknet                                   2223MiB |
+-----------------------------------------------------------------------------+
`

**darknet output:**
`Region 106 Avg IOU: 0.784762, Class: 0.999917, Obj: 0.994157, No Obj: 0.002142, .5R: 0.925926, .75R: 0.740741,  count: 27
Region 106 Avg IOU: 0.896280, Class: 0.999531, Obj: 0.998841, No Obj: 0.000975, .5R: 1.000000, .75R: 1.000000,  count: 6
Region 82 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000001, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000641, .5R: -nan, .75R: -nan,  count: 0
Region 94 Avg IOU: 0.899091, Class: 0.999924, Obj: 0.999944, No Obj: 0.000811, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 94 Avg IOU: 0.832841, Class: 0.998665, Obj: 0.999570, No Obj: 0.000315, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 106 Avg IOU: 0.884317, Class: 0.998268, Obj: 0.999731, No Obj: 0.000147, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 106 Avg IOU: 0.909685, Class: 0.999947, Obj: 0.999059, No Obj: 0.002178, .5R: 1.000000, .75R: 1.000000,  count: 18
Region 82 Avg IOU: 0.923131, Class: 0.999842, Obj: 0.999967, No Obj: 0.001171, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 82 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.001086, .5R: -nan, .75R: -nan,  count: 0
Region 94 Avg IOU: 0.809855, Class: 0.999990, Obj: 0.999998, No Obj: 0.000579, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 94 Avg IOU: 0.856910, Class: 0.999226, Obj: 0.999208, No Obj: 0.003637, .5R: 1.000000, .75R: 1.000000,  count: 7
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: 0.873692, Class: 0.999889, Obj: 0.999417, No Obj: 0.000502, .5R: 1.000000, .75R: 1.000000,  count: 4
Region 82 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000001, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.868530, Class: 0.999995, Obj: 0.999961, No Obj: 0.002085, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 94 Avg IOU: 0.868961, Class: 0.999970, Obj: 0.999872, No Obj: 0.001741, .5R: 1.000000, .75R: 1.000000,  count: 4
Region 94 Avg IOU: 0.902101, Class: 0.999970, Obj: 0.999941, No Obj: 0.000850, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 106 Avg IOU: 0.894554, Class: 0.999878, Obj: 0.999828, No Obj: 0.000269, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000001, .5R: -nan, .
`

**Comment by flowzen1337** [comment]
Can be closed, was an issue of the GPU 3 connected to slower pci express port which caused the issue.

**Comment by AlexeyAB** [comment]
> was an issue of the **GPU 3 connected to slower pci express port** which caused the issue.

Did you solve it by reconnecting GPU to faster PCI-e slots (16x/8x)?

**Comment by flowzen1337** [comment]
@AlexeyAB yes, 2 of the 4 gpu's where connected to the white pci-express slots via riser cards on the ASRock H110 Pro BTC+ Motherboard.

[https://images-na.ssl-images-amazon.com/images/I/A1UAmi1O2WL._SL1500_.jpg](url)

After i switched all gpu's to the black pci-express slots, it's working fine with 4x GPU's (GTX 1080TI) :-)
