### ISSUE TITLE
training stops in the first minute without error msg

### ISSUE THREAD

**Issue by romanoss** [AlexeyAB/darknet#2814]
gfx1060, win10, cuda10.0
build with cmake-gui and vs2017;
flags:GPU=1
CUDNN=1
OPENCV=1
CUDNN_HALF=0
dont remember if I selected compute_model
darknet.exe detector train cfg/batliner1.data cfg/yolov3-tiny_obj_batliner.cfg yolov3-tiny.conv.15

I get this in my bad.list:   ‹¯¨C:\Users\roman\ml\darknet\data\batliner1\images\000200034.jpg
which is the name of the first entry in train.txt with 3 weird characters at the start of the filename.

I tried yolo-v3 and yolov3-tiny with 21 custom classes and over  1000 images.
annotations were generated by RectLabel and copied from the mac to the windows machine.
I increased subdivisions-did not help. Running with dont_show prolongs the life of the process a small bit. 
rerun with random=0 entries in cfg file  -> no change
Any ideas?

kind regards
Roman

**Comment by romanoss** [comment]
update:
filename problem still exists -but training works now when compiled without using OPENCV
with OPENCV and progress chart: early death with strange filename entries in bad.list
without OPENCV: training goes well but with some entries of the first file in train.txt in bad.list, like described above.
current settings: CUDA 10.0 CUDNN 7.5 compute_model 61

does noone else have this problem with the filename?

**Comment by AlexeyAB** [comment]
Try to open your `train.txt` in HexEditor or in the MSVS 2017.
It seems there are some special characters at the beginning of the file.

**Comment by romanoss** [comment]
you are right!!!
now I have to find out how this can happen :)

thx a lot
