### ISSUE TITLE
Build on compute capability 2.x hardware without cuDNN

### ISSUE THREAD

**Issue by kbitr** [AlexeyAB/darknet#282]
Hey @AlexeyAB, great work!

Can you provide me information on,
- if it is possible to build on compute capability 2.x hardware or is this now deprecated for real?
  - if yes, can you tell me how to change the solution this way in Visual Studio?
  - If yes, can I disable cuDNN since it is not yet supported? 

(Using Unix, I would just change the Makefile, but no idea in Visual Studio. 🙃 )

**Comment by AlexeyAB** [comment]
@kbitr Hi,

Yes, just do 2 steps:

1. open `\darknet.sln` -> (right click on project) -> properties -> C/C++ -> Preprocessor -> Preprocessor Definitions, and remove: `CUDNN;`
 
2. open `\darknet.sln` -> (right click on project) -> properties -> CUDA C++ -> Device -> Code Generation, and set: `compute_20,sm_20;`

![compute-capability](https://user-images.githubusercontent.com/4096485/33314189-f0244c08-d43d-11e7-9d71-e614d554a7fe.png)
