### ISSUE TITLE
when running the yolo_console_dll.exe, no respose of the imshow window 

### ISSUE THREAD

**Issue by MerlotQ** [AlexeyAB/darknet#2824]
I am running the  yolo_console_dll.exe test.mp4, but no response on the window. If I comment the 'std::thread' and just show the cam, it gives the cam image view.

**Comment by MerlotQ** [comment]
I suppose it is a multi-thread related problem.

**Comment by AlexeyAB** [comment]
What OpenCV version do you use?
Did you change anything in the source code?
Can you show screenshot of this issue?

**Comment by MerlotQ** [comment]
I am using opencv 3.40. I add the lib path of opencv3.40 to vs 2015, which is built from source. Now everything of yolo_console_dll.exe works perfect. 

I guess it may or may not be the cause of not using installed 'opencv_world340.lib', instead using libs built from source.
Or I left the pc idle for a while and the memory or gpu mem frees up.

**Comment by MerlotQ** [comment]
Btw, i am using a webcam, conneted via usb to pc. And I uncomment the lines of
`#define TRACK_OPTFLOW
#define GPU`
