### ISSUE TITLE
RTX 2070 cuDNN Error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by tomyc** [AlexeyAB/darknet#2836]
Hi,
Starting development with the example: 
`darknet.exe detector train cfg/voc.data cfg/yolov3-voc.cfg darknet53.conv.74 -dont`
On the setup with GTX 1050Ti, everything works perfectly. Yet, when I switch to RTX 2070 card, I've got the following error: 
```
Total BFLOPS 65.428
 Allocate additional workspace_size = 52.43 MB
Loading weights from darknet53.conv.74...
 seen 64
Done!
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Resizing
608 x 608
 try to allocate additional workspace_size = 55.45 MB
 CUDA allocate done!
Loaded: 0.000000 seconds

 cuDNN status Error in: file: d:/tests/darknet/src/convolutional_kernels.cu : forward_convolutional_layer_gpu() : line: 538 : build time: Apr  4 2019 - 09:02:02
cuDNN Error: CUDNN_STATUS_EXECUTION_FAILED
```
I follow instructions from the post: https://github.com/AlexeyAB/darknet/issues/2493
But with no success.
Software versions:
- Windows 10
- VS2015 update 3
- CUDA 9.0.176
- cuDNN 7.2
- OpenCV 3.4.5
- Nvidia driver 419.67

Thanks in advance

Regards,
Tom

**Comment by AlexeyAB** [comment]
@tomyc Hi,

Try to install `CUDA 10.0`

**Comment by StevenLei2017** [comment]
@tomyc oh my god, my graphics card is also RTX2070. I have spent 2 days to slove the problem but not success 3 weeks ago,  i am very happy to see your success message, i will try your method. Thank you for your inspiration!!

**Comment by dselivanov** [comment]
same here - I've reinstalled cuda and cudnn and problem has gone.
