### ISSUE TITLE
loading weights from a different model

### ISSUE THREAD

**Issue by buzdarbalooch** [AlexeyAB/darknet#2839]
hello,

when i try to execute the script for tracking , the system loads the weight file for one old model the system was trained for, and for which i ran tracking. despite carefully checking the paths, as input these weights are provided 
 **Backup1/yolov2_3700.weights** 

after running the scipt it loads these weights below for old model.

**Loading weights from backup/yolo_10100.weights...**

LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./uselib data/obj2.names cfg/yolov2.cfg Backup1/yolov2_3700.weights experi.jpg

Used GPU 0
layer filters size input output
0 conv 32 3 x 3 / 1 416 x 416 x 3 -> 416 x 416 x 32 0.299 BF
1 max 2 x 2 / 2 416 x 416 x 32 -> 208 x 208 x 32 0.006 BF
2 conv 64 3 x 3 / 1 208 x 208 x 32 -> 208 x 208 x 64 1.595 BF
3 max 2 x 2 / 2 208 x 208 x 64 -> 104 x 104 x 64 0.003 BF
4 conv 128 3 x 3 / 1 104 x 104 x 64 -> 104 x 104 x 128 1.595 BF
5 conv 64 1 x 1 / 1 104 x 104 x 128 -> 104 x 104 x 64 0.177 BF
6 conv 128 3 x 3 / 1 104 x 104 x 64 -> 104 x 104 x 128 1.595 BF
7 max 2 x 2 / 2 104 x 104 x 128 -> 52 x 52 x 128 0.001 BF
8 conv 256 3 x 3 / 1 52 x 52 x 128 -> 52 x 52 x 256 1.595 BF
9 conv 128 1 x 1 / 1 52 x 52 x 256 -> 52 x 52 x 128 0.177 BF
10 conv 256 3 x 3 / 1 52 x 52 x 128 -> 52 x 52 x 256 1.595 BF
11 max 2 x 2 / 2 52 x 52 x 256 -> 26 x 26 x 256 0.001 BF
12 conv 512 3 x 3 / 1 26 x 26 x 256 -> 26 x 26 x 512 1.595 BF
13 conv 256 1 x 1 / 1 26 x 26 x 512 -> 26 x 26 x 256 0.177 BF
14 conv 512 3 x 3 / 1 26 x 26 x 256 -> 26 x 26 x 512 1.595 BF
15 conv 256 1 x 1 / 1 26 x 26 x 512 -> 26 x 26 x 256 0.177 BF
16 conv 512 3 x 3 / 1 26 x 26 x 256 -> 26 x 26 x 512 1.595 BF
17 max 2 x 2 / 2 26 x 26 x 512 -> 13 x 13 x 512 0.000 BF
18 conv 1024 3 x 3 / 1 13 x 13 x 512 -> 13 x 13 x1024 1.595 BF
19 conv 512 1 x 1 / 1 13 x 13 x1024 -> 13 x 13 x 512 0.177 BF
20 conv 1024 3 x 3 / 1 13 x 13 x 512 -> 13 x 13 x1024 1.595 BF
21 conv 512 1 x 1 / 1 13 x 13 x1024 -> 13 x 13 x 512 0.177 BF
22 conv 1024 3 x 3 / 1 13 x 13 x 512 -> 13 x 13 x1024 1.595 BF
23 conv 1024 3 x 3 / 1 13 x 13 x1024 -> 13 x 13 x1024 3.190 BF
24 conv 1024 3 x 3 / 1 13 x 13 x1024 -> 13 x 13 x1024 3.190 BF
25 route 16
26 conv 64 1 x 1 / 1 26 x 26 x 512 -> 26 x 26 x 64 0.044 BF
27 reorg / 2 26 x 26 x 64 -> 13 x 13 x 256
28 route 27 24
29 conv 1024 3 x 3 / 1 13 x 13 x1280 -> 13 x 13 x1024 3.987 BF
30 conv 45 1 x 1 / 1 13 x 13 x1024 -> 13 x 13 x 45 0.016 BF
31 detection
mask_scale: Using default '1.000000'
Total BFLOPS 29.343
Loading weights from backup/yolo_10100.weights...
seen 64
Done!
input image or video filename: Time: 0.200338 sec

Hence resulting in inaccurate tracking. 

frame_id = 184
track_id = 441, obj_id = 3, x = 57, y = 235, w = 6, h = 143, prob = 0.316
track_id = 446, obj_id = 3, x = 244, y = 103, w = 3, h = 268, prob = 0.273
track_id = 276, obj_id = 3, x = 51, y = 116, w = 0, h = 156, prob = 0.254
track_id = 297, obj_id = 3, x = 55, y = 333, w = 0, h = 167, prob = 0.254
track_id = 443, obj_id = 3, x = 251, y = 174, w = 67, h = 149, prob = 0.253
track_id = 540, obj_id = 3, x = 244, y = 9, w = 0, h = 245, prob = 0.252
track_id = 263, obj_id = 1, x = 251, y = 301, w = 0, h = 120, prob = 0.262
track_id = 409, obj_id = 3, x = 154, y = 356, w = 0, h = 119, prob = 0.247
track_id = 270, obj_id = 1, x = 152, y = 172, w = 0, h = 250, prob = 0.285
track_id = 277, obj_id = 1, x = 156, y = 272, w = 0, h = 178, prob = 0.292
track_id = 535, obj_id = 3, x = 152, y = 69, w = 0, h = 250, prob = 0.227
track_id = 1503, obj_id = 0, x = 1168, y = 77, w = 167, h = 0, prob = 0.271
track_id = 542, obj_id = 3, x = 933, y = 32, w = 0, h = 208, prob = 0.221
track_id = 572, obj_id = 3, x = 464, y = 186, w = 175, h = 0, prob = 0.221
track_id = 95, obj_id = 3, x = 251, y = 57, w = 0, h = 282, prob = 0.217
track_id = 1516, obj_id = 0, x = 867, y = 131, w = 168, h = 0, prob = 0.314
track_id = 1509, obj_id = 0, x = 767, y = 131, w = 164, h = 0, prob = 0.295
track_id = 444, obj_id = 3, x = 48, y = 81, w = 0, h = 118, prob = 0.212
track_id = 1671, obj_id = 0, x = 760, y = 408, w = 73, h = 79, prob = 0.23
track_id = 543, obj_id = 3, x = 146, y = 38, w = 0, h = 212, prob = 0.211
track_id = 573, obj_id = 3, x = 245, y = 429, w = 0, h = 83, prob = 0.208
track_id = 1795, obj_id = 0, x = 48, y = 188, w = 224, h = 0, prob = 0.214
track_id = 1052, obj_id = 0, x = 1077, y = 635, w = 130, h = 35, prob = 0.415
track_id = 1733, obj_id = 0, x = 1042, y = 186, w = 187, h = 0, prob = 0.218
track_id = 266, obj_id = 2, x = 1039, y = 11, w = 0, h = 145, prob = 0.201
track_id = 278, obj_id = 1, x = 648, y = 233, w = 0, h = 135, prob = 0.278

**Comment by buzdarbalooch** [comment]
@AlexeyAB sorry for disturbnce and multiple posts , actaully i am on certain deadlines, and i shall be really greatful, if you can give any suggestion regarding the issue. Like what can be possibly wrong.


if you notice for detection system works perfectly fine as i discussed, but as u aware we are not able to save detection result frame by frame.  when it comes to tracking, it shows the issue above. This is the  weight file i am saving in the folder , Backup1 folder    **Backup1/yolov2_3700.weights**, But after executing the script system load weights from the folder backup which is for another datasset.
**Loading weights from backup/yolo_10100.weights...**

**Comment by buzdarbalooch** [comment]
i just changed the names of folders above **Backup1** with **backup** and ran the script.  the system always looks for these weights. **backup/yolo_10100.weights...**


<img width="960" alt="Screenshot 2019-04-04 21 45 30" src="https://user-images.githubusercontent.com/19202445/55583943-6024b100-5723-11e9-9cc7-766cdb1c93a1.png">

**Comment by buzdarbalooch** [comment]
@AlexeyAB  finally resolved the issue, now its working fine for as i can successfully see the script running.

only issue was resolved with **make** again.  and the errors while compiling **make** were resolved by this single line **PATH=/usr/local/cuda/bin:$PATH make**. It might be helpful for other.

now only issue is the system is not saving the result for tracking in the **result.avi** file, and bounding box coordinates in the **result.txt** file . If you see i can successfully execute the script.

<img width="1920" alt="Screenshot 2019-04-05 10 16 50" src="https://user-images.githubusercontent.com/19202445/55615025-a95e1a80-578e-11e9-80b5-53a915ee5938.png">

**Comment by AlexeyAB** [comment]
Set there `true` instead of `false` https://github.com/AlexeyAB/darknet/blob/f19d1440cb85331f4d5ce40b3dccd4582c690687/src/yolo_console_dll.cpp#L288

Recompile `make`

And run:
`LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./uselib data/obj2.names cfg/yolov2.cfg Backup1/yolov2_3700.weights test.mp4 | tee -a result.txt`


Then look at `result.avi` and `result.txt` files.

**Comment by buzdarbalooch** [comment]
Thanks alot @AlexeyAB . problem is resolved. Tough i am not getting very great tracking results. i might train the model from the scratch and then again re-try it. as currently i am just testing it after 3700 itertations.  Just a curiousity, i was reading some of your comments here. 

https://github.com/AlexeyAB/darknet/issues/2808 

which is a better option to use (Optical flow or Kalman filtering ) as i have two use-case one is for **car park** where videos are made by normal mobile camera. Second is random **soccer videos**  where for certain points in the video there is abrupt camera movement. Hence in most cases system(tracking) ends up producing multiple labelling of the same object, incorrect disappearence of objects) resulting in unclean data

**Comment by AlexeyAB** [comment]
Here a lot of parameters affect the choice. Just try one and the other on a specific model and video to choose (Optical flow or Kalman filtering ).

**Comment by buzdarbalooch** [comment]
Ok thanks alot. And every time we move from one model to another once compile with **make**
