### ISSUE TITLE
Detect Anchors unclear output

### ISSUE THREAD

**Issue by JakupGuven** [AlexeyAB/darknet#2842]
Hi @AlexeyAB ,

I'm detecting anchors on my dataset with the command: 
./darknet.exe detector calc_anchors data/obj.data -num_of_clusters 9 -width 832 -height 832

I get the following output which I would say is unclear.

anchors =  90,416, 152,485, 126,612,  97,813, 167,748, 225,616, 310,672, 407,725, 561,778

Are the anchors: 90,416,152,485...etc
Or are they: 90.416, 152.485, 126.612, 97.813...etc

**Comment by AlexeyAB** [comment]
@JakupGuven Hi,

anchors: 90,416,152,485...etc

I.e. just copy this line
`anchors = 90,416, 152,485, 126,612, 97,813, 167,748, 225,616, 310,672, 407,725, 561,778`
to the yolo-layers in cfg-file

**Comment by JakupGuven** [comment]
Great as I suspected @AlexeyAB , I propose for clarification purposes to either always print a white space after each comma or not at all.
