### ISSUE TITLE
Extremely inaccurate reading.

### ISSUE THREAD

**Issue by Soccer9001** [AlexeyAB/darknet#2843]
I been trying to train YOLO to read image of fast food trash, but YOLO constantly makes prediction in places that doesn't really make any sense whatsoever. And the more I train, the more crazier YOLO becomes.
![Overload](https://user-images.githubusercontent.com/49284598/55571980-36768480-5739-11e9-8b27-1e7f38a465d6.PNG)
![OverPie](https://user-images.githubusercontent.com/49284598/55572270-d0d6c800-5739-11e9-9683-536535b74dc0.PNG)
This is with an avg loss of 0.09 and over 4000+ iteration.

I do have to mention I used 128 x 128 image to train, but this issue still pops up when I used high resolution image.

**Comment by AlexeyAB** [comment]
Check your dataset by using Yolo_mark.

**Comment by Soccer9001** [comment]
My dataset seems to be fine and mostly accurate, though is item overlapping a problem?
![marker](https://user-images.githubusercontent.com/49284598/55576199-501cc980-5743-11e9-9caa-5be7aedbaa17.PNG)

**Comment by AlexeyAB** [comment]
1. What mAP can you get on Training dataset?
2. What mAP can you get on Validation dataset?
3. Can you rename cfg-file to txt and attach it?
4. If you use Linux, then what parameters did you use in the Makefile?

**Comment by Soccer9001** [comment]
I am using Windows.
Can I ask how to get mAP for the dataset?
And I do not understand Question 3.

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet#when-should-i-stop-training
`darknet.exe detector map data/obj.data yolo-obj.cfg backup\yolo-obj_7000.weights`

1. set `valid=train.txt` in `obj.data` file and do this command
2. set `valid=valid.txt` in `obj.data` file and do this command
3. show your cfg-file

**Comment by Soccer9001** [comment]
IoU threshold = 50 %
 mean average precision (mAP@0.50) = 0.323183, or 32.32 %
 IoU threshold = 50 %
 mean average precision (mAP@0.50) = 0.323183, or 32.32 %

![cfg1](https://user-images.githubusercontent.com/49284598/55580036-35028780-574c-11e9-948f-17ae2688dde1.PNG)
![cfg2](https://user-images.githubusercontent.com/49284598/55580037-359b1e00-574c-11e9-8bf9-034b8e550be2.PNG)

**Comment by AlexeyAB** [comment]
> IoU threshold = 50 %
> mean average precision (mAP@0.50) = 0.323183, or 32.32 %

This is not very bad accuracy for Yolo v2.

1. What command did you use for training?
2. What command do you use for detection?
3. Can you show several images with results of detection on Training images?

**Comment by Soccer9001** [comment]
1. 
darknet.exe detector train cfg/obj.data cfg/yolo-obj.cfg yolo-obj_last.weights
2.
darknet.exe detector test cfg/obj.data cfg/yolo-obj.cfg yolo-obj_last.weights data/i/20.jpg
3.
![B1](https://user-images.githubusercontent.com/49284598/55598897-a6136080-5787-11e9-989a-0b9ab1fe998f.jpg)
![B2](https://user-images.githubusercontent.com/49284598/55598900-ac094180-5787-11e9-923d-a1e38aa99d61.jpg)
![B3](https://user-images.githubusercontent.com/49284598/55598904-b1ff2280-5787-11e9-8cc8-7d4e1c81eafb.jpg)
![B4](https://user-images.githubusercontent.com/49284598/55598906-b4fa1300-5787-11e9-93f1-2c811c5eba1b.jpg)

**Comment by Soccer9001** [comment]
Hello? Are you still there? I don't want to be pushy, but I really need to do this right.

**Comment by AlexeyAB** [comment]
Can you share your dataset (images, labels, train.txt, obj.data, obj.names) and your cfg-file? For example, by using Google disk?

**Comment by Soccer9001** [comment]
https://drive.google.com/drive/folders/1hA1q94x0iba1hpvbyb2z4DxbqudTWaJX?usp=sharing

**Comment by Soccer9001** [comment]
Is there anything wrong with the data I have, or do I just need to train ever longer (though I feel Yolo gets crazier when I train it for a long time)

**Comment by Soccer9001** [comment]
@AlexeyAB are you available now?

**Comment by AlexeyAB** [comment]
@Soccer9001 Hi,

Yes, your Yolo v2 model trained very bad.

Also I didn't find `test.txt` with Test/Valid images. And your `train.txt` containes much more images than you send me in the zip-archive. So i created my own `mixset_train.txt`

**To avoid overfitting you should use 2x-4x more images, with higher resolution and use separate validation dataset to check the mAP.**

----

I just trained `yolov3.cfg` **Yolo v3** model with `width=192 height=192`, with recalculated anchors and pre-trained weights `darknet53.conv.74`  for only 1300 iterations and get **mAP = 98.32%** that is very high.

cfg-file, commands and `mixset_train.txt`: [YoloStuff.zip](https://github.com/AlexeyAB/darknet/files/3050576/YoloStuff.zip)



![chart](https://user-images.githubusercontent.com/4096485/55670905-5c636c80-5892-11e9-9979-2f2112053d3a.png)

![cloud](https://user-images.githubusercontent.com/4096485/55670906-5f5e5d00-5892-11e9-8dc0-85fd6fde1bb8.png)

Detection results are pretty good:

![predictions](https://user-images.githubusercontent.com/4096485/55670875-22926600-5892-11e9-8e17-aea477fc152f.jpg)
![predictions](https://user-images.githubusercontent.com/4096485/55670880-27571a00-5892-11e9-8f35-468c65d4fe37.jpg)
![predictions](https://user-images.githubusercontent.com/4096485/55670883-2c1bce00-5892-11e9-9baa-62636aaaa6d5.jpg)
![predictions](https://user-images.githubusercontent.com/4096485/55670884-31791880-5892-11e9-9532-a9b1e94fe00a.jpg)
![predictions](https://user-images.githubusercontent.com/4096485/55670885-35a53600-5892-11e9-820a-f6dfa54b0ed7.jpg)
![predictions](https://user-images.githubusercontent.com/4096485/55670889-3d64da80-5892-11e9-8f8f-b1ca987a6b2f.jpg)
![predictions](https://user-images.githubusercontent.com/4096485/55670893-45247f00-5892-11e9-883a-7664ab80dae9.jpg)
![predictions](https://user-images.githubusercontent.com/4096485/55670899-4e155080-5892-11e9-85de-5a2624c5c0ef.jpg)
![predictions](https://user-images.githubusercontent.com/4096485/55670902-58374f00-5892-11e9-9feb-051165d4494d.jpg)





![image](https://user-images.githubusercontent.com/4096485/55670866-0e4e6900-5892-11e9-8fda-6203c5c0872b.png)
![image](https://user-images.githubusercontent.com/4096485/55670870-18706780-5892-11e9-9d69-cf6bd474daad.png)

**Comment by Soccer9001** [comment]
I am trying to re-train my data with better image quality, but I will check out the data you gave me. I will let you know if things work out.

Thank you for your help btw, I am super confused about everything and felt very useless.

**Comment by Soccer9001** [comment]
Actually, I am trying out your stuff with a 640 x 640 image now. Should I consider increasing width and height of the cfg file to something higher?

**Comment by AlexeyAB** [comment]
@Soccer9001 

Yes, set `batch=64 subdivisions=32 width=416 height=416` in `yolov3-obj.cfg`

**Comment by Soccer9001** [comment]
When I tried to run with a higher width and height, my computer ran out of memory despite setting it to subdiv 64 already, so I kept it at 192 x 192. Still, here is my result.
![chart](https://user-images.githubusercontent.com/49284598/55677390-e6561880-5918-11e9-87ee-9ee052443d74.png)
![AlexBetter](https://user-images.githubusercontent.com/49284598/55677401-21f0e280-5919-11e9-8308-13744d54b519.PNG)
![AlexBetter2](https://user-images.githubusercontent.com/49284598/55677402-23220f80-5919-11e9-8d0f-35414d6950eb.PNG)
There are still some misread burger boxes, but overall much more stable. What should I do at this point to further improve? Should I try increasing subdiv even more so that I can increase width and height? Or do I just run Yolo for longer?

Thank you for your help as always.

**Comment by AlexeyAB** [comment]
Start training **from the begining** with batch=64 subdivisions=64 width=320 height=320 in yolov3-obj.cfg

**And train at least 6000 iterations.**

**Comment by Soccer9001** [comment]
Okay, I will do that when I get the chance.

**Comment by Soccer9001** [comment]
It is possible for me to run your yolo on a Jupyter notebook? My computer isn't the best but I have access to a good Jupyter notebook. 

If so, can you teach me how to run it there? I am very new to Jupyter.

**Comment by Soccer9001** [comment]
Hey @AlexeyAB , I am trying to integrate Yolo into a html to run, so I am wondering if it is possible to run yolo detector via a python script instead of having to run it from commard prompt everytime.

**Comment by AlexeyAB** [comment]
@Soccer9001 

https://github.com/AlexeyAB/darknet/blob/master/darknet.py

https://github.com/AlexeyAB/darknet/blob/master/darknet_video.py

**Comment by Soccer9001** [comment]
Hi @AlexeyAB , sorry for the long wait, I hope you are still getting this. Here is my results. I couldn't run the training program even at 320 x 320, so I went to 256 x 256 instead. The results are somewhat mixed. It is better than v2 training, but it is still making a lot of mistakes and missing a lot of objects.
![chart](https://user-images.githubusercontent.com/49284598/56454298-24bfee80-6381-11e9-83d4-a4df85b6b314.png)
![P4](https://user-images.githubusercontent.com/49284598/56454382-5eddc000-6382-11e9-9b6e-5d0ac5b06155.jpg)
![P5](https://user-images.githubusercontent.com/49284598/56454383-5eddc000-6382-11e9-85b7-b0f07290248a.jpg)
![P6](https://user-images.githubusercontent.com/49284598/56454384-5f765680-6382-11e9-8bb1-88cf77661fbd.jpg)
![P8](https://user-images.githubusercontent.com/49284598/56454385-5f765680-6382-11e9-9fdd-3e3e5dbdceb8.jpg)
![P9](https://user-images.githubusercontent.com/49284598/56454386-5f765680-6382-11e9-84b3-e49af116a503.jpg)
![P10](https://user-images.githubusercontent.com/49284598/56454387-600eed00-6382-11e9-914d-663d8041cc37.jpg)
![P121](https://user-images.githubusercontent.com/49284598/56454388-600eed00-6382-11e9-9f22-eec670b45869.jpg)
![P1](https://user-images.githubusercontent.com/49284598/56454389-600eed00-6382-11e9-9813-8699d0e7dd4e.jpg)
![P2](https://user-images.githubusercontent.com/49284598/56454390-60a78380-6382-11e9-8c75-96cf1d39a075.jpg)
![P3](https://user-images.githubusercontent.com/49284598/56454391-60a78380-6382-11e9-8ccc-626f1258e8c1.jpg)

**Comment by Soccer9001** [comment]
What should I do now to further improve the model?

**Comment by Soccer9001** [comment]
Here is the sample data I used to train.

https://drive.google.com/file/d/1K3Ry86WUabhH9gRsXxiyFhAf-xhmULHN/view?usp=sharing

**Comment by Soccer9001** [comment]
Hello @AlexeyAB? Are you still there?

**Comment by Soccer9001** [comment]
@AlexeyAB  Hello? Maybe I should close this thread and create a new one?

**Comment by AlexeyAB** [comment]
@Soccer9001 Hi,

* Can you attach cfg-file that you used?

* Did you use `random=1` for training?

* Did you use default anchors, your calculated anchors, or anchors from  cfg-file from archive `YoloStuff.zip` https://github.com/AlexeyAB/darknet/issues/2843#issuecomment-480509467 ? 

* What command did you use for training?

* What params did you use in Makefile?

**Comment by Soccer9001** [comment]
Hello @AlexeyAB 

1. Here.
[ABzip.zip](https://github.com/AlexeyAB/darknet/files/3101210/ABzip.zip)

2. I believe I did. But to be specific, which random are you talking about?

3. The only thing I touched from the cfg was subdiv, height and width.

4. darknet detector train obj.data yolov3-obj.cfg darknet53.conv.74 -map

5. What is a Makefile?

**Comment by AlexeyAB** [comment]
* What GPU do you use?

* Try to train with default anchors  https://github.com/AlexeyAB/darknet/blob/099b71d1de6b992ce8f9d7ff585c84efd0d4bf94/cfg/yolov3.cfg#L782

**Comment by Soccer9001** [comment]
![MyRig](https://user-images.githubusercontent.com/49284598/56471420-e90e4d00-6484-11e9-90a3-53bedef2b44c.PNG)

So all I have to do is replace line 782 with the line you provided me then run the training program again?

**Comment by AlexeyAB** [comment]
Do you have GTX 1050 with only 3GB GPU-RAM?

Change all 3 lines:

1. https://github.com/AlexeyAB/darknet/blob/099b71d1de6b992ce8f9d7ff585c84efd0d4bf94/cfg/yolov3.cfg#L609

2. https://github.com/AlexeyAB/darknet/blob/099b71d1de6b992ce8f9d7ff585c84efd0d4bf94/cfg/yolov3.cfg#L695

3. https://github.com/AlexeyAB/darknet/blob/099b71d1de6b992ce8f9d7ff585c84efd0d4bf94/cfg/yolov3.cfg#L782

**Comment by Soccer9001** [comment]
![GPUram](https://user-images.githubusercontent.com/49284598/56472045-596c9c80-648c-11e9-9fdb-1ef1ab247038.PNG)
So only those three lines need to change, anything else?

**Comment by AlexeyAB** [comment]
Only these 3 lines

**Comment by Soccer9001** [comment]
Okay, should I continue with the 6000 int weight or start from the beginning

**Comment by AlexeyAB** [comment]
Start from the begining

**Comment by Soccer9001** [comment]
@AlexeyAB Hello again. The result is slightly better, but still have some error. Anything else I can do to improve?
![chart](https://user-images.githubusercontent.com/49284598/56503173-4539a580-6547-11e9-8d2e-bccf6b4e6f46.png)
![predictions](https://user-images.githubusercontent.com/49284598/56503234-6e5a3600-6547-11e9-85fb-0eda7aaf988e.jpg)
![predictions](https://user-images.githubusercontent.com/49284598/56503247-7dd97f00-6547-11e9-9fed-bcce2e8cb4d7.jpg)
![predictions](https://user-images.githubusercontent.com/49284598/56503267-8c279b00-6547-11e9-9e7c-919be5b47c39.jpg)
![predictions](https://user-images.githubusercontent.com/49284598/56503287-9ba6e400-6547-11e9-9815-04a871073acc.jpg)
![predictions](https://user-images.githubusercontent.com/49284598/56503343-b8431c00-6547-11e9-8948-9030f265ccc8.jpg)
![predictions](https://user-images.githubusercontent.com/49284598/56503371-c729ce80-6547-11e9-901d-6446a6e91d69.jpg)
![predictions](https://user-images.githubusercontent.com/49284598/56503392-de68bc00-6547-11e9-9d59-7bf7b46c4512.jpg)
![predictions](https://user-images.githubusercontent.com/49284598/56503429-fd674e00-6547-11e9-92c9-82388dc7669a.jpg)

**Comment by AlexeyAB** [comment]
@Soccer9001 Hi,

* You can add images with **slightly** randomly rotated an empty tray (and empty txt label files)

* You can set:
```
max_batches = 10000
policy=steps
steps=8000,9000
```

----

* What soft did you use to get cropped objects (like `cv::grabCut()`)? 
![N8C019v2](https://user-images.githubusercontent.com/4096485/56518342-df015280-6547-11e9-9ef5-cca9dea25050.jpg)


* Latter I will add features: rotation and bluring for Training Yolo, so it will help too:
```
angles=
blur=
```

**Comment by Soccer9001** [comment]
I used "medibang paint pro" to crop the pictures. I will try to take pictures of an empty tray later.

Those data is meant to be in the cfg file right? 

You are adding new features? Will I have to re download everything to take advantage of it? When will it be out? I have a deadline within about 2 weeks.

What should I do now? Should I restart train again or wait for your new features?

**Comment by AlexeyAB** [comment]
@Soccer9001 

> Those data is meant to be in the cfg file right?

Yes.


> You are adding new features? Will I have to re download everything to take advantage of it? When will it be out? I have a deadline within about 2 weeks.
> 
> What should I do now? Should I restart training again or wait for your new features?

If I add this feature this week, I will tell you.

Now you can try to train by using `yolov3-spp.cfg` with default anchors instead of `yolov3.cfg`. 
* Just change filters= and classes= for your number of objects in all 3 [yolo]-layers in cfg
* And set in cfg in [net] section
```
max_batches = 12000
policy=steps
steps=10000,11000
```
* Add images with empty tray 
* And train from the begining with pre-trained weights http://pjreddie.com/media/files/darknet53.conv.74
And show Loss & mAP chart.

**Comment by Soccer9001** [comment]
Is there anything I need to change in the yolov3-spp.cfg file?
Just three class and filter, then max_batch + step? 
Anything about anchor needs change?

**Comment by AlexeyAB** [comment]
> Is there anything I need to change in the yolov3-spp.cfg file?
> Just three class and filter, then max_batch + step?


Yes

> Anything about anchor needs change?

Use default

**Comment by Soccer9001** [comment]
The train process is taking a while (it is gonna take about two days to run the entire thing), but I want to make a quick update. Still has a mAp ceiling, but I haven't used the weight yet.
![chart](https://user-images.githubusercontent.com/49284598/56969675-434f9200-6b98-11e9-8d56-bdeda4b4f805.png)

**Comment by Soccer9001** [comment]
Here is a link to the data set I am using. 
https://drive.google.com/file/d/1xupf7i-In_PSnJjMMRqp4eiJYdNSsafq/view?usp=sharing

**Comment by Soccer9001** [comment]
Hi @AlexeyAB , bad news. I tried out the new weight, and this is overall a steo backwards. The result is similar to the one before, but now missing french fries and circling more non existent burger boxes.
![chart](https://user-images.githubusercontent.com/49284598/57014651-a4806f80-6c43-11e9-8291-3d55ef8f6a64.png)
![predictions](https://user-images.githubusercontent.com/49284598/57014656-a77b6000-6c43-11e9-8721-d10da5af9afc.jpg)
![predictions](https://user-images.githubusercontent.com/49284598/57014675-b8c46c80-6c43-11e9-9e9b-efaf20e93a3b.jpg)

**Comment by Soccer9001** [comment]
Hello @AlexeyAB, are you there? Any update on your new feature as well as what I should do from here?

**Comment by AlexeyAB** [comment]
@Soccer9001 Did you train yolov3-spp.cfg width=608 height=608 with default anchors?

**Comment by Soccer9001** [comment]
I didn't try 608x608 because I ran out of memeory with the other one. I only set to 256x256. I could try it later.

I didn't touch the anchors, do you want me to replace the anchors in the file with the one you gave me previously?

**Comment by Soccer9001** [comment]
@AlexeyAB Hello. I have tried to train with 608 x 608, unfortunately, it says Cuda is out of memory and recommend me to set subdivision to 64 even though I have already set it to 64.

**Comment by Soccer9001** [comment]
@AlexeyAB Hello? Is there anything else I can do?

**Comment by AlexeyAB** [comment]
@Soccer9001 Hi,

Download the latest version of Darknet, compile it with GPU, cuDNN and OpenCV. 
Take the best cfg-file that you got previously, add `blur=1` parameter in the `[net]` section and train it from the begining.

**Comment by Soccer9001** [comment]
Hi, I am done with Yolo right now for the most part. The accuracy wasn't the best but it was acceptable at the end. If I ever need your help again, I will contact you again. Thank you for your help and I will be closing this thread now.

**Comment by AlexeyAB** [comment]
Hi, What mAP did you get at the end?
