### ISSUE TITLE
compile darknet on Linux

### ISSUE THREAD

**Issue by essalahsouad** [AlexeyAB/darknet#2844]
I was trying to compile darknet in ubuntu but I got this error 
`make` 

> error: incompatible types when returning type ‘int’ but ‘IplImage {aka struct _IplImage}’ was expected

**Comment by AlexeyAB** [comment]
What OpenCV version do you use?
Can you show screenshot of this error?

**Comment by essalahsouad** [comment]
@AlexeyAB  
![Capture du 2019-04-04 21-16-56](https://user-images.githubusercontent.com/34586193/55585618-015d3880-571f-11e9-9839-5c635ed9e1dc.png)
i use cv 3.2.0 even with 3.4.4 i got the same error
![Capture du 2019-04-04 21-20-21](https://user-images.githubusercontent.com/34586193/55585832-77fa3600-571f-11e9-847d-254c3f2dd1b6.png)

**Comment by AlexeyAB** [comment]
Try to use the latest version of Darknet. I made a commit just now.

If it doesn't help, then try to install OpenCV 3.4.5 from source: https://github.com/opencv/opencv/archive/3.4.5.zip

**Comment by essalahsouad** [comment]
@AlexeyAB 
It works now, thanks

**Comment by alexanderfrey** [comment]
Hi,

when I run make it throws me ''yolo_console_dll.cpp:(.text+0x4b11): undefined reference to `_IplImage::_IplImage(cv::Mat const&)'

**Comment by AlexeyAB** [comment]
@alexanderfrey Hi, Do you use the latest version of Darknet  https://github.com/AlexeyAB/darknet/archive/master.zip ?
