### ISSUE TITLE
Where is the chart file saved at?

### ISSUE THREAD

**Issue by spchuang** [AlexeyAB/darknet#2845]
I'm able to train succesfully on a Linux machine. However, I can't seem to find where the charts.png file is saved at. I am using a training platform and I set a output folder for the checkpoint weights to be saved, which is fine but I don't see the map file saved at the same folder.

This is the training command

./darknet detector train test/test.data
      test/yolov3-608-test.cfg darknet53.conv.74 -dont_show -map

**Comment by adriacabeza** [comment]
hey @spchuang did you find out where the chart is saved? I am using an screen session for the training so I do need to check the map afterwards the training is finished.

**Comment by AlexeyAB** [comment]
@adriacabeza You must compile this repo https://github.com/AlexeyAB/darknet with OpenCV, and `chart.png` will be created automatically for each 100 iterations near with executable `./darknet` file.

**Comment by adriacabeza** [comment]
Ahh gotcha @AlexeyAB, I did not have OpenCV activated in the Makefile. Perfect thank you.
