### ISSUE TITLE
Using separate directories for images and labels

### ISSUE THREAD

**Issue by willbattel** [AlexeyAB/darknet#2850]
I noticed the default training configuration for image and labels is to have them in the same directory. COCO and VOC seem to use two directories, one for images and the other for their label counterparts.

I tired using separate directories, but unsurprisingly I was getting the error
```
Can't open label file. (This can be normal only if you use MSCOCO): /path/to/darknet/data/mydataset/images/somelabelfile.txt
```
which I resolved by dumping the txt files into the images directory.

For my dataset, **I would ideally like to keep them in separate directories**, like how COCO does it. Is there a way I can tell darknet to do it this way, or am I forced to merge the directories?

Thanks.

**Comment by AlexeyAB** [comment]
In general you have to merge the directories.

Because different dataset uses different directories names, so Darknet supports different directories only for PascalVOC and MS COCO 2014: https://github.com/AlexeyAB/darknet/blob/71d20264d17366ca3179078c42b731bf94a8e71b/src/utils.c#L229-L267

**Comment by willbattel** [comment]
Okay, thank you!
