### ISSUE TITLE
Training error after compiling with OpenCV

### ISSUE THREAD

**Issue by willbattel** [AlexeyAB/darknet#2852]
### My Environment:
- OS: Ubuntu 18.04 Server
- GCC: 7.3.0
- GPU: 1x Tesla V100
- CUDA: 10.0
- cuDNN: 7.4.2 for CUDA 10.0

I'd previously trained successfully with the following Makefile settings (full Makefile [here](https://pastebin.com/4L0YwpMT)):
```
GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=0
AVX=1
OPENMP=1
LIBSO=0
ZED_CAMERA=0
```

Then I installed OpenCV 3.4.0 (using [this method](https://github.com/jayrambhia/Install-OpenCV)), and it seemed to install without problems.

Then changed my Makefile to
```
GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=1
AVX=1
OPENMP=1
LIBSO=0
ZED_CAMERA=0
```

and re-made darknet. Again, no issues compiling.

However, now when I train, I'm getting an error.
```
./darknet detector train data/mydataset/data.txt cfg/yolov3-mydataset.cfg darknet53.conv.74 -dont_show
```
```
Total BFLOPS 65.290 
 Allocate additional workspace_size = 1213.50 MB 
Loading weights from darknet53.conv.74...
 seen 64 
Done!
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Resizing
608 x 608 
 try to allocate additional workspace_size = 428.08 MB 
 CUDA allocate done! 
Loaded: 0.000070 seconds
darknet: ./src/network_kernels.cu:164: void forward_backward_network_gpu(network, float*, float*): Assertion `(l.c*l.n*l.size*l.size) > 0' failed.
Aborted (core dumped)
```

I then re-set OPENCV to 0, ran `make clean` and `make` again, but am now getting the error even with my original settings.

Any idea what this is about? Thanks.

**Comment by AlexeyAB** [comment]
@willbattel Hi,

* Try to download the latest version of Darknet and recompile it.

* Rename `yolov3-mydataset.cfg` to `yolov3-mydataset.txt` and drag-n-drop here to your message.

> I then re-set OPENCV to 0, ran make clean and make again, but am now getting the error even with my original settings.

* Do you get the same error?

**Comment by willbattel** [comment]
@AlexeyAB okay, I pulled latest and remade Darknet. I changed my cfg file to txt and tried again.

Still getting the error:
```
Total BFLOPS 65.290 
 Allocate additional workspace_size = 1213.50 MB 
Loading weights from darknet53.conv.74...
 seen 64 
Done!
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Resizing
608 x 608 
 try to allocate additional workspace_size = 428.08 MB 
 CUDA allocate done! 
Loaded: 0.000079 seconds
darknet: ./src/network_kernels.cu:164: void forward_backward_network_gpu(network, float*, float*): Assertion `(l.c*l.n*l.size*l.size) > 0' failed.
Aborted (core dumped)
```

However, I think I might have been wrong about this being caused by my OpenCV installation. I forgot that I had also pulled 8 commits yesterday, and I think one of those is responsible. It had been working when I was on 6231b748c44e2007b5c3cbf765a50b122782c5a2, but when I pulled the commits from April 4th and 5th, then I started getting this error.

**Comment by AlexeyAB** [comment]
@willbattel I fixed this bug. Use the latest version of Darknet.

**Comment by willbattel** [comment]
Yep, that fixed it. Thanks!
