### ISSUE TITLE
Save every image used in the training process

### ISSUE THREAD

**Issue by drapado** [AlexeyAB/darknet#2853]
Hi, I would like to save the data augmented images generated by darknet while training. Is it possible?

**Comment by AlexeyAB** [comment]
@drapado Hi,

Yes.

Use flag `-show_imgs` so each augmented images will be saved near with executable file `./darknet` and will be showed in the Window - to see next window press ESC button.

Use both flag `-dont_show -show_imgs` so each augmented images will be saved, but willn't be showed, so you shouldn't press ESC button to continue. Also you can use it on remote servers like Amazon EC2 cloud for example with flag `-mjpeg_port 8090` to see Loss & mAP chart in Web-browser: 

Examples:

`./darknet detector train data/full_occlusion.data yolov3-tiny_occlusion_track.cfg backup/yolov3-tiny_occlusion_track_9000.weights -show_imgs`

----


`./darknet detector train data/full_occlusion.data yolov3-tiny_occlusion_track.cfg backup/yolov3-tiny_occlusion_track_9000.weights -show_imgs -dont_show`

----

`./darknet detector train data/full_occlusion.data yolov3-tiny_occlusion_track.cfg backup/yolov3-tiny_occlusion_track_9000.weights -map -mjpeg_port 8090 -show_imgs -dont_show`

**Comment by drapado** [comment]
Thanks for adding the feature so quickly!

I updated the code but I'm having errors while I'm trying to use it: 

If I train with `-show_imgs -dont_show`, I get the error: darknet: `./src/network_kernels.cu:164: void forward_backward_network_gpu(network, float*, float*): Assertion '(l.c*l.n*l.size*l.size) > 0' failed.`

And if I just use `-show_imgs`: `Gdk-Message: 15:39:08.256: average loss: Fatal IO error 2 (No such file or directory) on X server :0.`

**Comment by AlexeyAB** [comment]
What params do you use in the Makefile?
What command do you use?
And can you attach cfg-file renamed to txt-file?

**Comment by drapado** [comment]
```
GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=1
AVX=0
OPENMP=0
LIBSO=0
ZED_CAMERA=0
```
I was using the command:
`./darknet detector train data/obj.data sprouts-cfg/yolov3-5l-j1.cfg backup/yolov3-5l-j1_last.weights -map -show_imgs`

[yolov3-5l-j1.cfg.txt](https://github.com/AlexeyAB/darknet/files/3050739/yolov3-5l-j1.cfg.txt)

**Comment by AlexeyAB** [comment]
@drapado I fixed this bug. Use the latest version of Darknet.

**Comment by drapado** [comment]
Great, thanks a lot!!
