### ISSUE TITLE
load_network in darknet.py takes a long time in python

### ISSUE THREAD

**Issue by seanthegreat7** [AlexeyAB/darknet#2856]
I have a few questions:
1 - My problem is that it takes a very long time to load the network when I load it using load_net or load_net_custom in python. 

I run the same network on the command line in Linux command line and it loads very fast. It doesn't happen with the load_net from the pjreddie load_net function. 

2- Also how can we choose which gpu to load the network on? more specifically there was a set_gpu function in the pjreddie version of darknet.py. is there an equivalent in your version? 
3 - Can you point me to the load_network and  load_network_custom function source code?

I'm using python3

**Comment by seanthegreat7** [comment]
I found it works fine in python 2. Do you have any clue what the problem is?

**Comment by seanthegreat7** [comment]
well, it seems that the problem was with my environment but still I appreciate if you answer my other questions

**Comment by AlexeyAB** [comment]
1. On my copmuter both darknet.py and darknet_video.py loads model in 15 seconds (first time) 5 seconds (second and subsequent times)

2. There is set_gpu() function in darknet.py that is imported to darknet_video.py: https://github.com/AlexeyAB/darknet/blob/b6a824df39d1a79f15916d2c11133ce27bc0ab06/darknet.py#L141-L143

3. https://github.com/AlexeyAB/darknet/blob/b6a824df39d1a79f15916d2c11133ce27bc0ab06/src/parser.c#L1321-L1345
