### ISSUE TITLE
recall, f1 in map chart

### ISSUE THREAD

**Issue by readicculus** [AlexeyAB/darknet#2862]
I wrote some code to add recall and f1 to map graph.  Is there a reason it wasn't included initially?  I'm happy to clean it up and make a pr if it would be useful to add.  Currently only works for detector but could make it work for classifier as well

**Comment by AlexeyAB** [comment]
This would be misleading for users; they do not understand which indicator to pay attention to: Loss, mAP/TopK, Recall, F1, ...

So we remain only Training-Loss and Validation-mAP.
