### ISSUE TITLE
How to use the GPU for computation in darknet.py

### ISSUE THREAD

**Issue by gjm24** [AlexeyAB/darknet#2869]
Hi. I have been developing my own Python code that uses functions from darknet.py. In particular, my code gets frames in real time from a camera video feed using OpenCV, and then feeds each frame into YOLO darknet for object detection using a function in darknet.py called detect_image(netMain, metaMain, im, thresh=0.25). The problem is, I have noticed from Task Manager (and the fact that the stream is very laggy) that my CPU usage shoots up to 100% while my GPUs (I have 2 NVIDIA GeForce RTX2080) are idle. I suspect my code is not utilising the GPUs.

I have also called the function set_gpu(0), which is also imported from darknet.py, in my code. I have tried all sorts of integer numbers as the argument of set_gpu() to no avail. If I understand it right, set_gpu() is equivalent to cuda_set_device which is supposed to set the GPU to use.

I have been able to build darknet.sln, yolo_cpp_dll.sln, yolo_cpp_dll_no_gpu.sln. I have installed CUDA 10.0, Microsoft Visual Studio 2017, cuDNN, transferred opencv_world330.dll and opencv_ffmpeg330_64.dll into the darknet/x64 directory. I can use darknet for object detection for jpg pictures from the command prompt. I am able to train YOLO darknet on my own custom data using my GPUs. But I cannot seem to get the GPU to work in a Python code.

Any help would be greatly appreciated.

Just in case it's important, here are my specs:
Python 3.7 (64 bit)
Processor: Intel Core i7-9700K CPU @ 3.60 GHz
RAM: 32GB
OS: 64 bit OS, Windows 10
GPU: 2 x NVIDIA GeForce RTX2080

Thanks.

**Comment by AlexeyAB** [comment]
@gjm24 Hi,

You should rebuild `yolo_cpp_dll.sln`. **And you should not build `yolo_cpp_dll_no_gpu.sln.`**

So `darknet_video.py` uses GPU by default.

You must use GPU-Z or nvidia-smi only to check GPU-usage.

What GPU-usage in GPU-Z do you have by using https://github.com/AlexeyAB/darknet/blob/master/darknet_video.py ?


> The problem is, I have noticed from Task Manager (and the fact that the stream is very laggy) that my CPU usage shoots up to 100% while my GPUs (I have 2 NVIDIA GeForce RTX2080) are idle. I suspect my code is not utilising the GPUs.

Task Manager shows wrong gpu-usage.

You must implement multi-thread pre and post-processing in Python:
1. thread-1 capture frame and resize
2. thread-2 detection using Yolo
3. thread-3 draw bboxes and show in the window

Or just use `./darknet` or `./uselib` where it is implemented.

**Comment by gjm24** [comment]
Hi @AlexeyAB 
Thank you so much for your help! I redownloaded a fresh copy of your darknet ZIP file and compiled darknet.sln and yolo_cpp_dll.sln only. It worked and now my code works like a charm with no lag. I know you said Task Manager is inaccurate, but now even Task Manager is saying that my GPU is working.

The reason why i compiled yolo_cpp_no_gpu.sln as well in the past was because of the comments at the start of darknet.py which says:

"Both the GPU and no-GPU version should be compiled; the no-GPU version should be renamed "yolo_cpp_dll_nogpu.dll"."

I took that to mean I needed to compile both yolo_cpp_dll files. If we are not meant to compile the no-GPU version on a machine with a GPU, you may want to consider changing the wording of the comments slightly to avoid confusion for others in the future. Nevertheless, thank you for answering my question. I am very grateful.

**Comment by Khasmamad** [comment]
What is the solution for Linux case? I also added the line set_gpu(0), but inference is too slow and nvidia-smi shows that gpu is not used. Any help is appreciated @AlexeyAB
