### ISSUE TITLE
"-dont_show" don't work

### ISSUE THREAD

**Issue by stakanich** [AlexeyAB/darknet#2874]
I want to test model on video file in cloud without display. I use this comand:
`./darknet detector demo cfg/obj.data cfg/tempCfgDetect.cfg backup/tempCfg_last.weights /content/test1.mp4 -dont_show -out_filename res.avi`
Input file has 1.97 Mb size. Output - 8.44 Kb and cannot be opened.
Command at the end gives me gtk:warning: cannot open display.
Here all text output:
`Demo
layer     filters    size              input                output
   0 conv     16  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  16 0.150 BF
   1 max          2 x 2 / 2   416 x 416 x  16   ->   208 x 208 x  16 0.003 BF
   2 conv     32  3 x 3 / 1   208 x 208 x  16   ->   208 x 208 x  32 0.399 BF
   3 max          2 x 2 / 2   208 x 208 x  32   ->   104 x 104 x  32 0.001 BF
   4 conv     64  3 x 3 / 1   104 x 104 x  32   ->   104 x 104 x  64 0.399 BF
   5 max          2 x 2 / 2   104 x 104 x  64   ->    52 x  52 x  64 0.001 BF
   6 conv    128  3 x 3 / 1    52 x  52 x  64   ->    52 x  52 x 128 0.399 BF
   7 max          2 x 2 / 2    52 x  52 x 128   ->    26 x  26 x 128 0.000 BF
   8 conv    256  3 x 3 / 1    26 x  26 x 128   ->    26 x  26 x 256 0.399 BF
   9 max          2 x 2 / 2    26 x  26 x 256   ->    13 x  13 x 256 0.000 BF
  10 conv    512  3 x 3 / 1    13 x  13 x 256   ->    13 x  13 x 512 0.399 BF
  11 max          2 x 2 / 1    13 x  13 x 512   ->    13 x  13 x 512 0.000 BF
  12 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024 1.595 BF
  13 conv    256  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 256 0.089 BF
  14 conv    512  3 x 3 / 1    13 x  13 x 256   ->    13 x  13 x 512 0.399 BF
  15 conv     18  1 x 1 / 1    13 x  13 x 512   ->    13 x  13 x  18 0.003 BF
  16 yolo
  17 route  13
  18 conv    128  1 x 1 / 1    13 x  13 x 256   ->    13 x  13 x 128 0.011 BF
  19 upsample            2x    13 x  13 x 128   ->    26 x  26 x 128
  20 route  19 8
  21 conv    256  3 x 3 / 1    26 x  26 x 384   ->    26 x  26 x 256 1.196 BF
  22 conv     18  1 x 1 / 1    26 x  26 x 256   ->    26 x  26 x  18 0.006 BF
  23 yolo
Total BFLOPS 5.448 
 Allocate additional workspace_size = 24.92 MB 
Loading weights from backup/tempCfg_last.weights...
 seen 64 
Done!
video file: /content/test1.mp4
[h264 @ 0x55fb29a5f700] mmco: unref short failure
[h264 @ 0x55fb29a5f700] mmco: unref short failure
Video stream: 1920 x 1080 
Objects:

FPS:0.0
Objects:

FPS:0.0
Unable to init server: Could not connect: Connection refused

(mat:21617): Gtk-WARNING **: 16:26:53.686: cannot open display: `

**Comment by stakanich** [comment]
I don't know what is wrong. I hardcoded dont_show = 1 in run_detector function in detector.c because after `int dont_show = find_arg(argc, argv, "-dont_show");` it was 0. But it steel shows me `Unable to init server: Could not connect: Connection refused

(mat:1694): Gtk-WARNING **: 09:57:53.109: cannot open display: `
I don't understand.

**Comment by AlexeyAB** [comment]
@stakanich 

* Do you use the latest version of Darknet?
* Did you change anything in the source code?

**Comment by stakanich** [comment]
I used `git clone https://github.com/AlexeyAB/darknet` for downloading it just today.
I changed GPU to 1 and OPENCV to 1 in Makefile.
I tried to add `printf("%.1f",dont_show); dont_show = 1;` to 1389 string of detector.c and it prints that dont_show is 0.0. But even after this hardcode of the dont_show parameter it gives such error.

**Comment by stakanich** [comment]
I don't know did you fix something or I just did something wrong(but I didn't change anything from yesterday), but today it works fine with adding `dont_show = 1` in run_detector in detector.c (didn't try today without that). Thanks a lot.

**Comment by AlexeyAB** [comment]
There was a bug: https://github.com/AlexeyAB/darknet/commit/8c970498a296ed129ffef7d872ccc25d42d1afda#diff-0a05be69077d8e58b5d714758b75c77fL488

I forgot to remove the line `show_image_mat(mat, "mat");` (for Output Video Writer) while testing OpenCV 4.0. Now with the last commit everything should work well without changing the source code.
