### ISSUE TITLE
Run image classifier predict on VOC

### ISSUE THREAD

**Issue by jefersonf** [AlexeyAB/darknet#2875]
Привет, @AlexeyAB 

I'm trying to execute an image classification as it follows:
`./darknet classifier predict data/voc.data cfg/yolo-voc.cfg yolo-voc.weights data/dog.jpg`

I have created a file named `yolo-voc.data`. It contains the following:
```
classes= 20
train  = /home/jeferson/darknet/data/train.txt
valid  = /home/jeferson/darknet/data/2007_test.txt
names = data/voc.names
backup = /home/jeferson/darknet/backup/

```
I have both the `.txt` files and I've got them by following [this](https://github.com/AlexeyAB/darknet/tree/47c7af1cea5bbdedf1184963355e6418cb8b1b4f#how-to-train-pascal-voc-data). 

But I'm getting the following error:  `Segmentation fault (core dumped)`

![image](https://user-images.githubusercontent.com/3049540/55746986-85f6d200-5a11-11e9-8d50-f6d2542fa348.png)

Do you have any suggestions on what I'm doing wrong?

**Comment by AlexeyAB** [comment]
@jefersonf Hi,

Yolo is Detector, not Classifier. So you can't use it for Classification.

For Classification use these models: https://pjreddie.com/darknet/imagenet/

**Comment by jefersonf** [comment]
@AlexeyAB, Thank you for the clarification.
