### ISSUE TITLE
Custom object detection:

### ISSUE THREAD

**Issue by lehador1** [AlexeyAB/darknet#2887]
Alexey thank you very much for this repo. I have many images, over 200k
for example 
![708](https://user-images.githubusercontent.com/47855450/55852129-bef78980-5b6c-11e9-8183-7278504f0555.jpg)
![1457](https://user-images.githubusercontent.com/47855450/55852258-4218df80-5b6d-11e9-8fb7-830cc65be694.jpg)
![2138](https://user-images.githubusercontent.com/47855450/55852307-742a4180-5b6d-11e9-96b7-36e81481e923.jpg)
Can I train yolo on this dataset?
or I should have full frame with this cars?

**Comment by AlexeyAB** [comment]
If you want to Detect cars on full frames, then you should Train on full frames.
