### ISSUE TITLE
training stop automaticaly

### ISSUE THREAD

**Issue by sepulm01** [AlexeyAB/darknet#2891]
Hi Alexey,
I'm training my own data set with only one class. The training was OK, but stop exactly al 2K iterations with a 0,9 error average. I would like to continue but it doesn't work. When I try to re start with 2000.weight the program save the final .weights instead of start training again:

 ~/darknet/darknet detector train data/obj.data yolo-obj.cfg backup/yolo-obj_2000.weights
......
 105 conv     18  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x  18 0.025 BF
 106 yolo
Total BFLOPS 65.290 
 Allocate additional workspace_size = 52.43 MB 
Loading weights from backup/yolo-obj_2000.weights...
 seen 64 
Done!
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Saving weights to backup//yolo-obj_final.weights

I had to re strat form 1000.weights. It is normal o I can configure the number of iteration.
best regards.

**Comment by sepulm01** [comment]
ups... please close this... I just realize that is manage in max batch...

**Comment by NoraJiang** [comment]
I met the same problem, how did you solve it?

**Comment by NoraJiang** [comment]
I met the same problem, how did you solve it?

**Comment by NoraJiang** [comment]
Hello, how did you solve this problem?

**Comment by AlexeyAB** [comment]
@NoraJiang Increase `max_batches=` in your cfg-file

**Comment by NoraJiang** [comment]
> @NoraJiang Increase `max_batches=` in your cfg-file

Thanks you for your reply. I found that the 'nan' appear during training, my image=416x416 , class=100, my original max_batches=80200, I've tried to increase it to 200,000. But it still doesn't work.

**Comment by OrangeVulture** [comment]
> > @NoraJiang Increase `max_batches=` in your cfg-file
> 
> Thanks you for your reply. I found that the 'nan' appear during training, my image=416x416 , class=100, my original max_batches=80200, I've tried to increase it to 200,000. But it still doesn't work.

So were you able to figure it out??
