### ISSUE TITLE
cpu gpu usage

### ISSUE THREAD

**Issue by romanoss** [AlexeyAB/darknet#2895]
Hey Alexey,
System: core i7, gtx 1060
As it seems when training my cpu usage is about 50-70% and gpu between 0-30% 
This changes only a bit when I use different values for subdivisions

am i cpu bound? why is my gpu usage so low?

@AlexeyAB
Hey I am visiting Moskow. Do you have some off mainstream tips, where I should go?

**Comment by romanoss** [comment]
ahh this was the copy value , the cuda value is 40% on average. not too much either. is that normal?

**Comment by AlexeyAB** [comment]
@romanoss Hi,

What command do you use? darknet_video.py is slow. Try to use ./darknet detector demo...

----

> Hey I am visiting Moskow. Do you have some off mainstream tips, where I should go?

It depends on what you prefer to see: ride bicycles in the Gorky Park or VDNH, visit the historical museum on Red Square or the Tretyakov Gallery, have a drink in the City Space Bar, or ride on a boat to see whole center of Moscow...

**Comment by romanoss** [comment]
darknet: I am talking about gpu usage during training
![cpugpu](https://user-images.githubusercontent.com/2591631/55922091-f6634600-5bff-11e9-93e8-45a516277be4.JPG)

Moscow: girlfriend would like to ride bicycles best - I like all the suggestions. What are the things that muscovite prefer?

**Comment by AlexeyAB** [comment]
@romanoss Use only GPU-Z or nvidia-smi to get GPU-usage.
