### ISSUE TITLE
bbox annotations will be loaded automatically if txt file has the same name as image file? 

### ISSUE THREAD

**Issue by panovr** [AlexeyAB/darknet#29]
The step 5 in the section _**How to train (to detect your custom objects)**_ written as:

> Create .txt-file for each .jpg-image-file - in the same directory and with the same name, but with .txt-extension, 

When training, the detector can find the images from **train.txt**. If I understand correctly, as long as one create the bbox txt file as the same  name as the image file, for example, 

- image file name: car_001.jpg
- bbox txt file name: car_001.txt

Then the detector can find the corresponding bbox txt file automatically, is it?

**Comment by AlexeyAB** [comment]
@panovr Yes, exactly.
