### ISSUE TITLE
Tiny YOLOv3 at 608 resolution has lower mAP than 416

### ISSUE THREAD

**Issue by willbattel** [AlexeyAB/darknet#2903]
I just trained my custom dataset on 4 different models to compare accuracy:
- `yolov3` at 416x416
- `yolov3-spp` at 416x416
- `yolov3-tiny` at 416x416
- `yolov3-tiny` at 608x608

These are their charts (I trained for way longer than I had to but I was curious what would happen)

`yolov3` at 416x416
![image](https://user-images.githubusercontent.com/13490339/55987363-03ffe680-5c67-11e9-8a2e-4e6af4cb986a.png)

`yolov3-spp` at 416x416
![image](https://user-images.githubusercontent.com/13490339/55987368-095d3100-5c67-11e9-9514-e24d6cb88cfa.png)

`yolov3-tiny` at 416x416
![image](https://user-images.githubusercontent.com/13490339/55987375-0e21e500-5c67-11e9-8a9f-292dbe1de85a.png)

`yolov3-tiny` at 608x608
![image](https://user-images.githubusercontent.com/13490339/55987385-12e69900-5c67-11e9-9fc1-5676f220bf02.png)

I thought `yolov3-tiny` at 608x608 would have a higher mAP than `yolov3-tiny` at 416x416, but that didn't seem to happen. All other model parameters were the same between these. SPP being better than normal v3 makes sense, and the full models being better than tiny makes sense, but I can't figure out why 608 was worse than 416, or why the mAP of 608 fluctuated so much.

Any idea why 416 was more accurate than 608?

**Comment by AlexeyAB** [comment]
@willbattel Hi,

* Can you show your custom anchors?

* How many Training and Validation images do you have?

**Comment by willbattel** [comment]
@AlexeyAB we’re not using any custom anchors, just those provided in `yolov3-tiny.cfg`. We have 1 class with 630 training and 70 validation images.

**Comment by AlexeyAB** [comment]
May be your object are very large and it doesn't require high resolution.

**Comment by willbattel** [comment]
Some of the training images are macro images where the object appears much larger, but normally the objects are small. I guess I'll just have to experiment some more, but I wanted to check and see what you thought. Thanks.

**Comment by willbattel** [comment]
Nevermind, I messed up the anchors on the 608 version.

**Comment by Micky-123** [comment]
> Nevermind, I messed up the anchors on the 608 version.

Hi, 
So, eventually, you got better results with 608 as compared to 416?
