### ISSUE TITLE
Show more information about test results?

### ISSUE THREAD

**Issue by xiaohai12** [AlexeyAB/darknet#2905]
I would like to ask whether it is possible to show more information in test result.
For example, we can know the TP and FP for a class, but can we show a true  class corresponding the predicted class(like we predict a object as dog, but actually it is a cat.)
So that it can help me to compute the Confusion matrix.
(I am sorry that this question may show that I am a lazy guy, but I will do it by myself if it is impossible to show more information.)

**Comment by Leon-S-Kenndy** [comment]
Hi have you done it successfully

**Comment by gaurang19990412** [comment]
How can we generate confusion matrix using darknet for yolov3 trained moded
