### ISSUE TITLE
Using -dont_show parameter still causes (mat:19060): Gtk-WARNING **: cannot open display:

### ISSUE THREAD

**Issue by DarylWM** [AlexeyAB/darknet#2910]
Hi @AlexeyAB .

I'm trying to run my trained model on a video and save the results in a video. The computer is a headless Ubuntu box.

The command is:
./darknet detector demo ~/yolo-train/peptides-obj.data yolov3-tiny_3l-peptides.cfg ~/darknet/backup/yolov3-tiny_3l-peptides_last.weights ~/tile-33-mz-700-718.mp4 -out_filename predictions.avi -dont_show

but I get:

...
Loading weights from /home/daryl/darknet/backup/yolov3-tiny_3l-peptides_last.weights...
 seen 64 
Done!
video file: /home/daryl/tile-33-mz-700-718.mp4
Video stream: 910 x 910 
Objects:

FPS:0.0
Objects:

charge-4: 100% 
charge-4: 100% 
charge-3: 100% 
charge-3: 91% 
charge-3: 86% 
charge-3: 59% 
charge-2: 100% 
charge-2: 100% 
charge-2: 100% 
charge-2: 100% 
charge-2: 100% 
charge-2: 99% 
charge-2: 96% 
charge-2: 88% 
charge-2: 70% 
charge-2: 27% 
charge-1: 100% 
charge-1: 99% 
charge-1: 78% 
charge-1: 74% 

FPS:0.0

(mat:19060): Gtk-WARNING **: cannot open display: 

and no predictions video.

I thought dont_show would work. Any idea what's happening?

**Comment by DarylWM** [comment]
Fixed the same way as in issue #2874 , by adding `int dont_show = 1;` at line 1385 in src/detector.c.

**Comment by AlexeyAB** [comment]
There was a bug: https://github.com/AlexeyAB/darknet/commit/8c970498a296ed129ffef7d872ccc25d42d1afda#diff-0a05be69077d8e58b5d714758b75c77fL488

I forgot to remove the line `show_image_mat(mat, "mat");` (for Output Video Writer) while testing OpenCV 4.0. Now with the last commit everything should work well without changing the source code.
