### ISSUE TITLE
Compiling with CUDNN_HALF 

### ISSUE THREAD

**Issue by ttdd11** [AlexeyAB/darknet#2915]
Hey Alex,

I've compiled with CUDNN_HALF = 1 and am testing on a machine that doesn't have the compute capability. I get an error when loading the graph: 

Used GPU 0
 compute_capability = 610, cudnn_half = 0
layer     filters    size              input                output
   0 conv     32  3 x 3 / 1   320 x 320 x   3   ->   320 x 320 x  32 0.177 BF
   1 conv     64  3 x 3 / 2   320 x 320 x  32   ->   160 x 160 x  64 0.944 BF
   2 conv     32  1 x 1 / 1   160 x 160 x  64   ->   160 x 160 x  32 0.105 BF
   3 conv     64  3 x 3 / 1   160 x 160 x  32   ->   160 x 160 x  64 0.944 BF
   4 Shortcut Layer: 1
   5 conv    128  3 x 3 / 2   160 x 160 x  64   ->    80 x  80 x 128 0.944 BF
   6 conv     64  1 x 1 / 1    80 x  80 x 128   ->    80 x  80 x  64 0.105 BF
   7 conv    128  3 x 3 / 1    80 x  80 x  64   ->    80 x  80 x 128 0.944 BF
   8 Shortcut Layer: 5
   9 conv     64  1 x 1 / 1    80 x  80 x 128   ->    80 x  80 x  64 0.105 BF
  10 conv    128  3 x 3 / 1    80 x  80 x  64   ->    80 x  80 x 128 0.944 BF
  11 Shortcut Layer: 8
  12 conv    256  3 x 3 / 2    80 x  80 x 128   ->    40 x  40 x 256 0.944 BF
  13 conv    128  1 x 1 / 1    40 x  40 x 256   ->    40 x  40 x 128 0.105 BF
  14 conv    256  3 x 3 / 1    40 x  40 x 128   ->    40 x  40 x 256 0.944 BF
  15 Shortcut Layer: 12
  16 conv    128  1 x 1 / 1    40 x  40 x 256   ->    40 x  40 x 128 0.105 BF
  17 conv    256  3 x 3 / 1    40 x  40 x 128   ->    40 x  40 x 256 0.944 BF
  18 Shortcut Layer: 15
  19 conv    128  1 x 1 / 1    40 x  40 x 256   ->    40 x  40 x 128 0.105 BF
  20 conv    256  3 x 3 / 1    40 x  40 x 128   ->    40 x  40 x 256 0.944 BF
  21 Shortcut Layer: 18
  22 conv    128  1 x 1 / 1    40 x  40 x 256   ->    40 x  40 x 128 0.105 BF
  23 conv    256  3 x 3 / 1    40 x  40 x 128   ->    40 x  40 x 256 0.944 BF
  24 Shortcut Layer: 21
  25 conv    128  1 x 1 / 1    40 x  40 x 256   ->    40 x  40 x 128 0.105 BF
  26 conv    256  3 x 3 / 1    40 x  40 x 128   ->    40 x  40 x 256 0.944 BF
  27 Shortcut Layer: 24
  28 conv    128  1 x 1 / 1    40 x  40 x 256   ->    40 x  40 x 128 0.105 BF
  29 conv    256  3 x 3 / 1    40 x  40 x 128   ->    40 x  40 x 256 0.944 BF
  30 Shortcut Layer: 27
  31 conv    128  1 x 1 / 1    40 x  40 x 256   ->    40 x  40 x 128 0.105 BF
  32 conv    256  3 x 3 / 1    40 x  40 x 128   ->    40 x  40 x 256 0.944 BF
  33 Shortcut Layer: 30
  34 conv    128  1 x 1 / 1    40 x  40 x 256   ->    40 x  40 x 128 0.105 BF
  35 conv    256  3 x 3 / 1    40 x  40 x 128   ->    40 x  40 x 256 0.944 BF
  36 Shortcut Layer: 33
  37 conv    512  3 x 3 / 2    40 x  40 x 256   ->    20 x  20 x 512 0.944 BF
  38 conv    256  1 x 1 / 1    20 x  20 x 512   ->    20 x  20 x 256 0.105 BF
  39 conv    512  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 512 0.944 BF
  40 Shortcut Layer: 37
  41 conv    256  1 x 1 / 1    20 x  20 x 512   ->    20 x  20 x 256 0.105 BF
  42 conv    512  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 512 0.944 BF
  43 Shortcut Layer: 40
  44 conv    256  1 x 1 / 1    20 x  20 x 512   ->    20 x  20 x 256 0.105 BF
  45 conv    512  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 512 0.944 BF
  46 Shortcut Layer: 43
  47 conv    256  1 x 1 / 1    20 x  20 x 512   ->    20 x  20 x 256 0.105 BF
  48 conv    512  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 512 0.944 BF
  49 Shortcut Layer: 46
  50 conv    256  1 x 1 / 1    20 x  20 x 512   ->    20 x  20 x 256 0.105 BF
  51 conv    512  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 512 0.944 BF
  52 Shortcut Layer: 49
  53 conv    256  1 x 1 / 1    20 x  20 x 512   ->    20 x  20 x 256 0.105 BF
  54 conv    512  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 512 0.944 BF
  55 Shortcut Layer: 52
  56 conv    256  1 x 1 / 1    20 x  20 x 512   ->    20 x  20 x 256 0.105 BF
  57 conv    512  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 512 0.944 BF
  58 Shortcut Layer: 55
  59 conv    256  1 x 1 / 1    20 x  20 x 512   ->    20 x  20 x 256 0.105 BF
  60 conv    512  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 512 0.944 BF
  61 Shortcut Layer: 58
  62 conv   1024  3 x 3 / 2    20 x  20 x 512   ->    10 x  10 x1024 0.944 BF
  63 conv    512  1 x 1 / 1    10 x  10 x1024   ->    10 x  10 x 512 0.105 BF
  64 conv   1024  3 x 3 / 1    10 x  10 x 512   ->    10 x  10 x1024 0.944 BF
  65 Shortcut Layer: 62
  66 conv    512  1 x 1 / 1    10 x  10 x1024   ->    10 x  10 x 512 0.105 BF
  67 conv   1024  3 x 3 / 1    10 x  10 x 512   ->    10 x  10 x1024 0.944 BF
  68 Shortcut Layer: 65
  69 conv    512  1 x 1 / 1    10 x  10 x1024   ->    10 x  10 x 512 0.105 BF
  70 conv   1024  3 x 3 / 1    10 x  10 x 512   ->    10 x  10 x1024 0.944 BF
  71 Shortcut Layer: 68
  72 conv    512  1 x 1 / 1    10 x  10 x1024   ->    10 x  10 x 512 0.105 BF
  73 conv   1024  3 x 3 / 1    10 x  10 x 512   ->    10 x  10 x1024 0.944 BF
  74 Shortcut Layer: 71
  75 conv    512  1 x 1 / 1    10 x  10 x1024   ->    10 x  10 x 512 0.105 BF
  76 conv   1024  3 x 3 / 1    10 x  10 x 512   ->    10 x  10 x1024 0.944 BF
  77 conv    512  1 x 1 / 1    10 x  10 x1024   ->    10 x  10 x 512 0.105 BF
  78 conv   1024  3 x 3 / 1    10 x  10 x 512   ->    10 x  10 x1024 0.944 BF
  79 conv    512  1 x 1 / 1    10 x  10 x1024   ->    10 x  10 x 512 0.105 BF
  80 conv   1024  3 x 3 / 1    10 x  10 x 512   ->    10 x  10 x1024 0.944 BF
  81 conv    255  1 x 1 / 1    10 x  10 x1024   ->    10 x  10 x 255 0.052 BF
  82 yolo
  83 route  79
  84 conv    256  1 x 1 / 1    10 x  10 x 512   ->    10 x  10 x 256 0.026 BF
  85 upsample            2x    10 x  10 x 256   ->    20 x  20 x 256
  86 route  85 61
  87 conv    256  1 x 1 / 1    20 x  20 x 768   ->    20 x  20 x 256 0.157 BF
  88 conv    512  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 512 0.944 BF
  89 conv    256  1 x 1 / 1    20 x  20 x 512   ->    20 x  20 x 256 0.105 BF
  90 conv    512  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 512 0.944 BF
  91 conv    256  1 x 1 / 1    20 x  20 x 512   ->    20 x  20 x 256 0.105 BF
  92 conv    512  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 512 0.944 BF
  93 conv    255  1 x 1 / 1    20 x  20 x 512   ->    20 x  20 x 255 0.104 BF
  94 yolo
  95 route  91
  96 conv    128  1 x 1 / 1    20 x  20 x 256   ->    20 x  20 x 128 0.026 BF
  97 upsample            2x    20 x  20 x 128   ->    40 x  40 x 128
  98 route  97 36
  99 conv    128  1 x 1 / 1    40 x  40 x 384   ->    40 x  40 x 128 0.157 BF
 100 conv    256  3 x 3 / 1    40 x  40 x 128   ->    40 x  40 x 256 0.944 BF
 101 conv    128  1 x 1 / 1    40 x  40 x 256   ->    40 x  40 x 128 0.105 BF
 102 conv    256  3 x 3 / 1    40 x  40 x 128   ->    40 x  40 x 256 0.944 BF
 103 conv    128  1 x 1 / 1    40 x  40 x 256   ->    40 x  40 x 128 0.105 BF
 104 conv    256  3 x 3 / 1    40 x  40 x 128   ->    40 x  40 x 256 0.944 BF
 105 conv    255  1 x 1 / 1    40 x  40 x 256   ->    40 x  40 x 255 0.209 BF
 106 yolo
Total BFLOPS 38.973
 Allocate additional workspace_size = 52.43 MB
Loading weights from C:/yolov3.weights...
 seen 64
CUDA status Error: file: D:/darknet_rebuild/darknet-master/src/convolutional_kernels.cu : cuda_convert_f32_to_f16() : line: 137 : build time: Apr  1 2019 - 13:59:33
CUDA Error: invalid device function

Do I have to compile with CUDNN_HALF = 0 when building the lib for the graph to load on a non-compatible card? I thought based on the initial output (cudnn_half = 0 seen above) that it would account for that.

**Comment by AlexeyAB** [comment]
@ttdd11 Hi,

It should work fine on CC 6.1 even if CUDNN_HALF=1.

Does it work successfully with CUDNN_HALF=0?

Do you use the latest version of Darknet?

-----


I just tested on several GPUs with CC 3.0 (Quadro K2100M) and CC 6.1 (Quadro P5000) and it works fine with `GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=1`, CUDA 9.1, OpenCV 3.x on Debian by using this command:



![image](https://user-images.githubusercontent.com/4096485/56046426-e0fb3280-5d4b-11e9-91b2-396109e64400.png)


![image](https://user-images.githubusercontent.com/4096485/56046314-a4c7d200-5d4b-11e9-8459-5f92cfe2213f.png)

![image](https://user-images.githubusercontent.com/4096485/56046375-c1fca080-5d4b-11e9-8ec9-23c7324d521c.png)

**Comment by ttdd11** [comment]
@AlexeyAB Not the latest version, but a version from April 1 or something close. 

What I did was build a lib with cudnn_half=1 with compute capabilities 7.5 for my titan rtx. This is from the same lib with geforce 1080ti. The compute capability 6 is a bit odd for those cards. I'm just a little confused why I would get this error if cudnn_half = 0 in the output from the net.

**Comment by AlexeyAB** [comment]
Try to rebuild Darknet with CUDNN_HALF=1 and default CC https://github.com/AlexeyAB/darknet/blob/master/Makefile#L16-L20

don't uncomment other compute capabilities.

**Comment by ttdd11** [comment]
Okay I'll give this a try.

I'm building with Visual studio so I will add them there. Is there a problem with having the other as well as 7.5?

**Comment by AlexeyAB** [comment]
On windows use `compute_30,sm_30;compute_75,sm_75` it should work well.

**Comment by ttdd11** [comment]
This can be closed, that seems to have fixed it. Thanks as always.
