### ISSUE TITLE
Change in model output between now and summer of 2018

### ISSUE THREAD

**Issue by JakupGuven** [AlexeyAB/darknet#2922]
Hi @AlexeyAB 
I'm writing a general issue here as I'm not sure what exactly is causing my problem.
As late as in the summer of 2018 using your repo I was able to create custom object detection models using yolov2-tiny architecture and convert them to keras using https://github.com/allanzelener/YAD2K and then subsequently to CoreML format using Apple's coremltools. Last month I installed your version of darknet once again on another computer and repeated this process. However now something goes wrong some where in the conversion because I am unable to detect anything when I embed the model on a mobile device.

My question to you is if you've made any changes that could stop yolov2-tiny from working in my use case during this time?

**Comment by AlexeyAB** [comment]
@JakupGuven Hi,

* Can you succesfully convert default model yolov2-tiny.cfg (43 MB COCO Yolo v2) RAM: https://pjreddie.com/media/files/yolov2-tiny.weights ?

* Do you use OS 64 bit for convertion?

**Comment by JakupGuven** [comment]
@AlexeyAB  I am able to take that weight and yolov2-tiny.cfg in your repo, convert it and have it working in an iOS app. 

I don't know what you mean by OS 64 bit for conversion. I'm using a 64-bit Ubuntu system when I convert it.

**Comment by AlexeyAB** [comment]
Try to change `uint64_t` to `uint32_t` https://github.com/AlexeyAB/darknet/blob/8c970498a296ed129ffef7d872ccc25d42d1afda/src/parser.c#L1048

set
```
 int major = 0; 
 int minor = 1; 
 int revision = 1; 
```
https://github.com/AlexeyAB/darknet/blob/8c970498a296ed129ffef7d872ccc25d42d1afda/src/parser.c#L1042-L1044


recompile
and train at least 100 iterations to get `yolov2_tiny_last.weights` that try to convert.

**Comment by JakupGuven** [comment]
@AlexeyAB I don't have access to the training machine now I will get back to you on monday.

**Comment by JakupGuven** [comment]
@AlexeyAB 
This solved my issue.

**Comment by AlexeyAB** [comment]
@JakupGuven Just wondering what was the reason?

**Comment by JakupGuven** [comment]
@AlexeyAB CoreML uses 32 bit weights. I would guess it has something to do with that since changing  fwrite(net.seen, sizeof(uint64_t), 1, fp);  to uint32_t did the trick.

Can I ask you one more question regarding your Yolo_mark repo?
The txt output files are they organised in this way: Class number XMin XMax YMin YMax? 
I'm asking about the floats which is which

**Comment by AlexeyAB** [comment]
@JakupGuven 

> Can I ask you one more question regarding your Yolo_mark repo?
> The txt output files are they organised in this way: Class number XMin XMax YMin YMax?
> I'm asking about the floats which is which

No. x & y are center of bbox: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

> <object-class> <x_center> <y_center> <width> <height>

**Comment by JakupGuven** [comment]
@AlexeyAB 
I mean the annotation files here
https://github.com/AlexeyAB/Yolo_mark/blob/master/x64/Release/data/img/air1.txt

What does each number there represent?

**Comment by AlexeyAB** [comment]
@JakupGuven 

`0 0.498437 0.479861 0.117188 0.168056`

`<object-class> <x_center> <y_center> <width> <height>`

**Comment by JakupGuven** [comment]
That's a shame, it's not the same format as https://storage.googleapis.com/openimages/web/index.html annotations which uses min and max

**Comment by AlexeyAB** [comment]
> That's a shame, it's not the same format as https://storage.googleapis.com/openimages/web/index.html annotations which uses min and max

Yes, Yolo uses it's own format.

You can get datasets with Yolo format by using these scripts:
* OpenImages: https://github.com/AlexeyAB/darknet/blob/master/scripts/get_openimages_dataset.py
* MS COCO: https://github.com/AlexeyAB/darknet/blob/master/scripts/get_coco_dataset.sh
* PascalVOC: https://github.com/AlexeyAB/darknet/blob/master/scripts/voc_label.py

**Comment by JakupGuven** [comment]
Wow, that's great, you're a life saver!
