### ISSUE TITLE
Max number of detected objects

### ISSUE THREAD

**Issue by drapado** [AlexeyAB/darknet#2930]
Hi, I've seen that to calculate the max number of objects that yolo can detect in one picture you need to use this equation: `0,0615234375*(width*height)`. With 416 it gives yo around 10000 objects.

This doesn't make sense to me given the output of yolov3. You have 3 yolo layers, each yolo layer gives output for 3 anchors per grid cell. Then if 416/32=13 --> 13x13 grids, you have 3 (yolo layers) x 3 (anchors per yolo layer), which means a total number of objects of 13x13x3x3=1521.

How is this possible?

**Comment by AlexeyAB** [comment]
@drapado Hi,

1st yolo layer has 13x13 size
2nd yolo layer has 26x26 size
3rd yolo layer has 52x52 size

**Comment by drapado** [comment]
Oh, now I get it. Thanks a lot @AlexeyAB!!!
