### ISSUE TITLE
mAP output meaning

### ISSUE THREAD

**Issue by asvath** [AlexeyAB/darknet#2933]
Hello, 

I ran map using two different weights and I'm confused by the output.

Iteration 11,000:
 detections_count = 30566, unique_truth_count = 7246  
 for thresh = 0.25, TP = 4114, FP = 945, FN = 3132, average IoU = 62.06 % 

Iteration 12,000:
 detections_count = 37270, unique_truth_count = 7246  
 for thresh = 0.25, TP = 4438, FP = 1535, FN = 2808, average IoU = 55.96 % 

TP+FP do not add up to the detection count. 
TP+FP+FN doesn't add up to it either.
What is the meaning of detection count? 
Thanks.

**Comment by AlexeyAB** [comment]
@asvath Hi,

TP+FN = unique_truth_count = 7246

> for thresh = 0.25, TP = 4114, FP = 945, FN = 3132, average IoU = 62.06 %

TP/FP/FN are calculated for threshold `0.25`, while detections_count = 30566 for threshold = `0.0`

**Comment by asvath** [comment]
Thank you!
