### ISSUE TITLE
test using mAP?

### ISSUE THREAD

**Issue by asvath** [AlexeyAB/darknet#2936]
Hi again,

I have a question regarding testing my model.

I tried:
#!./darknet detector test data/obj.data_test.txt yolov3-tiny-obj.cfg backup_832/yolov3-tiny-obj_11000.weights -dont_show -ext_output < data/test.txt > test_result.txt 

Where:
 obj.data_test.txt : val points to my test.txt file that contains the path to the test images

The result looks like this:
Enter Image Path: nu_test_images/1526915246547295.jpg
: Predicted in 213.198000 milli-seconds.

I'm confused as to what's going on with this test, it just tells me the time taken for prediction but nothing else. Also does it matter that I put data/test.txt instead of train.txt here: 
-ext_output < data/test.txt >

In addition, I tried using mAP for my test:
!./darknet detector map data/obj.data_test.txt yolov3-tiny-obj.cfg backup/yolov3-tiny-obj_11000.weights >> result.txt

Again where obj.data_test.txt has val = test.txt

The results make sense by using mAP for testing, is this the correct way to test? 

Thanks again.

**Comment by AlexeyAB** [comment]
> #!./darknet detector test data/obj.data_test.txt yolov3-tiny-obj.cfg backup_832/yolov3-tiny-obj_11000.weights -dont_show -ext_output < data/test.txt > test_result.txt

It gives you file `test_result.txt` with coordinates of detected objects

----

> !./darknet detector map data/obj.data_test.txt yolov3-tiny-obj.cfg backup/yolov3-tiny-obj_11000.weights >> result.txt

It gives you `result.txt` with accuracy parameters - use it to compare the models and weights files as described: https://github.com/AlexeyAB/darknet#when-should-i-stop-training

**Comment by asvath** [comment]
Thank you Alexey. Just a follow up question, is it possible to get the loss info for validation? I was only able to do a mAP for validation.

I managed to get the loss for training via ext_output < data/train.txt > train.txt.

**Comment by AlexeyAB** [comment]
> Thank you Alexey. Just a follow up question, is it possible to get the loss info for validation? 

No.

You get Loss for training, and mAP for validation.

**Comment by asvath** [comment]
Cheers!

**Comment by asvath** [comment]
Cheers!
