### ISSUE TITLE
Predict only custom class from pre-train weights 

### ISSUE THREAD

**Issue by syedmustafa54** [AlexeyAB/darknet#2943]
Hello @AlexeyAB,
I have pre-train weights yolov3.weights which is having 80 class what i need is when i run detector command its should show only one class not all classes
example:-
I have an image of a person with the dog what I am trying to get is the only person not the dog in the prediction is there something I can do instead of training the model again to detect only person

**Comment by AlexeyAB** [comment]
@syedmustafa54 Hi,

Yes, just add `dont_show ` before each line except `person` in the `data/coco.names` file

**Comment by syedmustafa54** [comment]
Thanks for the quickest reply
