### ISSUE TITLE
darknet.sln doesn't build successfully in Release ×64 mode but can be build in Debug ×64

### ISSUE THREAD

**Issue by SHADOWMOOON** [AlexeyAB/darknet#2944]
Hello 
I try to compile darknet following your intructions on VS2015 but when I build darknet.sln in Release×64 mode,the error happen.  However in Debug ×64 Mode,it's work and do create darknet.exe,then I run the darknet_yolo_v3.cmd test and it works successfully.

Environment:
Windows10  opencv3.4.0  VS2015  CUDA9.0  Cudnn7.4.2.

here are the errors while building  solution in Release×64：
![1555464102(1)](https://user-images.githubusercontent.com/44594124/56254801-cbdc2600-60f4-11e9-83b9-b3f555387236.png)
![1555464125(1)](https://user-images.githubusercontent.com/44594124/56254804-d0084380-60f4-11e9-9716-6991cafd0637.png)

and here are my configuration with Release×64:
![1555464680(1)](https://user-images.githubusercontent.com/44594124/56254851-fb8b2e00-60f4-11e9-972d-48af020557c7.png)
![1555464691(1)](https://user-images.githubusercontent.com/44594124/56254856-fe861e80-60f4-11e9-8333-f42132a73da4.png)
![1555464734(1)](https://user-images.githubusercontent.com/44594124/56254858-004fe200-60f5-11e9-8ca9-bc88c26bfc8c.png)
![1555464756(1)](https://user-images.githubusercontent.com/44594124/56254861-034ad280-60f5-11e9-99e0-4a35866124b7.png)
![1555464793(1)](https://user-images.githubusercontent.com/44594124/56254864-05149600-60f5-11e9-83cd-9757e3f0bd6b.png)

**Comment by AlexeyAB** [comment]
@SHADOWMOOON Hi,

> I try to compile darknet following your intructions on VS2015 but when I build darknet.sln in Release×64 mode,the error happen. However in Debug ×64 Mode,it's work and do create darknet.exe,then I run the darknet_yolo_v3.cmd test and it works successfully.

It seems that you compiled OpenCV library only in Debug mode. You should compile OpenCV in Debug & Release modes, or just download https://sourceforge.net/projects/opencvlibrary/files/4.1.0/opencv-4.1.0-vc14_vc15.exe/download

**Comment by SHADOWMOOON** [comment]
@AlexeyAB OK.thanks.
But I didn't compile OpenCV library.I just download the opencv3.4.0 (Win pack Version),Then I configure the opencv on VS2015. So what am I supposed to do now? could u give me some advice. Appreciate that!

**Comment by AlexeyAB** [comment]
@SHADOWMOOON 

Try to use **default** `darknet.sln` without changes
just set system variables

* system variable `OpenCV_DIR = C:\opencv\build` - where are the include and x64 folders https://user-images.githubusercontent.com/4096485/53249516-5130f480-36c9-11e9-8238-a6e82e48c6f2.png

* system variable CUDNN with path to CUDNN: https://user-images.githubusercontent.com/4096485/53249764-019ef880-36ca-11e9-8ffe-d9cf47e7e462.jpg

May be you will need to install CUDA 10.0 (or If you have other version of CUDA (not 10.0) then open build\darknet\darknet.vcxproj by using Notepad, find 2 places with "CUDA 10.0" and change it to your CUDA-version. Then open \darknet.sln -> (right click on project) -> properties -> CUDA C/C++ -> Device and remove there ;compute_75,sm_75. )


----

Or install Cmake: https://github.com/AlexeyAB/darknet#requirements

And compile Darknet by using Cmake-gui: 
Compiling on Windows by using C:\Program Files\CMake\bin\cmake-gui.exe as on this IMAGE https://user-images.githubusercontent.com/4096485/55107892-6becf380-50e3-11e9-9a0a-556a943c429a.png : Configure -> Optional platform for generator (Set: x64) -> Finish -> Generate -> Open Project -> x64 & Release -> Build -> Build solution

**Comment by SHADOWMOOON** [comment]
@AlexeyAB OK.I'll try to do that by using default darknet.sln. and I want to know the CUDNN path cause my CUDNN's files(which have bin, include and lib folders) are already covered to CUDA. so what's the specific address of CUDNN?(I can not see it completely in the jpg u mention above)  
is't like this :  CUDNN=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0

**Comment by AlexeyAB** [comment]
@SHADOWMOOON 
> and I want to know the CUDNN path cause my CUDNN's files(which have bin, include and lib folders) are already covered to CUDA. 

If you already have copied cuDNN files to the CUDA folders then in this case you shouldn't specify CUDNN system variable.

**Comment by SHADOWMOOON** [comment]
@AlexeyAB so I should  just specify CUDA system variable?

**Comment by SHADOWMOOON** [comment]
@AlexeyAB 
so I've try to use Cmake-gui to compile Darknet.But when I configure,the error happen 
![1555576824(1)](https://user-images.githubusercontent.com/44594124/56348327-c405aa00-61f8-11e9-926d-a57ed52c39fd.jpg)
could u give me some advice?  thx!

**Comment by AlexeyAB** [comment]
@SHADOWMOOON 

> @AlexeyAB so I should just specify CUDA system variable?

You even should specify CUDA variable. CUDA system variable is specified automatically by CUDA-installator.

----

> so I've try to use Cmake-gui to compile Darknet.But when I configure,the error happen

Delete CmakeCache.txt and re-run Cmake-gui. Then show me screenshot: 
![image](https://user-images.githubusercontent.com/4096485/56363784-a08d3000-61f5-11e9-8c7d-d1eb037b95e7.png)

**Comment by SHADOWMOOON** [comment]
@AlexeyAB OK! I'll give it a try. Thanks a lotttt!!!!
Before that,now I am using the debug×64 version instead of Release to start traning. Will this version of darknet.exe cause any problems?

**Comment by AlexeyAB** [comment]
It may be very slow. But it should work.

**Comment by SHADOWMOOON** [comment]
@AlexeyAB when I am training. I wonder if the program use CUDA to speed up training or not.Because I found it is too slow and the usage rate of CPU is too high(almost reach to 99%) while gpu is too low(about 1%-5%).However I see the output  log show the words CUDA allocate done! now I am confused.
PS:my gpu is GTX 1080Ti    
here are the output log and pics about usage rate of cpu and gpu （I Screenshot the pics when it's training）
![1](https://user-images.githubusercontent.com/44594124/56367062-0645e000-6227-11e9-8743-21166c192fad.png)
![2](https://user-images.githubusercontent.com/44594124/56367078-0c3bc100-6227-11e9-9a59-d86fbf501482.png)
![3](https://user-images.githubusercontent.com/44594124/56367091-0fcf4800-6227-11e9-9678-a89f67fd9628.png)

**Comment by AlexeyAB** [comment]
That is why you should build it with Release.

Or just try to remove `DEBUG;` definintion in the `darknet.sln`

**Comment by SHADOWMOOON** [comment]
@AlexeyAB about the cmake compiling.This is the screenshot:
![1555638548(1)](https://user-images.githubusercontent.com/44594124/56400845-90726080-6288-11e9-97a6-35cd198b5530.png)

**Comment by AlexeyAB** [comment]
@SHADOWMOOON Check that your MSVS 2015 compiled with C/C++ support, otherwise reinstall MSVS.

**Comment by SHADOWMOOON** [comment]
@AlexeyAB 
now I fix the problem through upgrade the VS2015.Now the darknet.sln can be complie on Release x64 mode.
I’m truly grateful for your help! thx a lot!
