### ISSUE TITLE
How to invoke darknet from arbitrary location but still use relative path to .names file (wrt. to location of darknet, rather than wrt. to $PWD)

### ISSUE THREAD

**Issue by LukeAI** [AlexeyAB/darknet#2951]
I have wrapped libdarknet.so in python using an adapted derivative of the reference ctypes wrapper provided in this repo. This is then used as a library by a (python) ROS node. This node is probably not going to be invoked from within the same directory as the source code and might be placed in different places on different machines so I have adapted configPath, weightPath and metaPath to be dynamically discovered as follows:

```
src_path = os.path.dirname(__file__)
configPath = os.path.join(src_path, 'cfg', 'yolov3-spp.cfg')
weightPath = os.path.join(src_path, 'yolov3-spp.weights')
metaPath = os.path.join(src_path, 'cfg', 'coco.data') 
```
This works fine for reading weights, .cfg and .data - the problem is that reading the .names file with `metaMain = load_meta(metaPath.encode("ascii"))` uses the path to the .names file defined in coco.data - this works if the absolute path to .names is written in coco.data OR if the relative path is used and the whole package is invoked from the same directory at libdarknet.so. So it seems that darknet resolves the path to the .names file with respect to the current directory.

I would like some way for the names file to be read by libdarknet.so that does not require that the script is invoked from the same directory or that the absolute path to the .names is known ahead of runtime and specified in .data. Maybe I could even 'trick' darknet into thinking that the current directory is actually the location of the .so ?

**Comment by kylemcdonald** [comment]
Not ideal, but in my case I made symlinks to all the relevant files:

```
ln -sf ./runs/2019_07_06/yolov3.cfg yolov3.cfg
ln -sf ./runs/2019_07_06/yolov3.data yolov3.data
ln -sf ./runs/2019_07_06/yolov3.names yolov3.names
ln -sf ./runs/2019_07_06/backup/yolov3_best.weights yolov3.weights
```

**Comment by Shame-fight** [comment]
Do you think of darknet as a ros node and publish related coordinate messages? I tried using the C-based darknet_ros package, but it is more python. Is the python-based darknet_ros package you write open source? I look forward to hearing from you.
@LukeAI @kylemcdonald

**Comment by LukeAI** [comment]
unfortunately I am not able to release the code but it is very straightforward - the example darknet_video.py in this repo. but with subscribe/publish and [opencv bridge](http://wiki.ros.org/cv_bridge/Tutorials/ConvertingBetweenROSImagesAndOpenCVImagesPython).
