### ISSUE TITLE
stb_image.h: no such file or directory

### ISSUE THREAD

**Issue by xiaohai12** [AlexeyAB/darknet#2953]
how to solve this problem?
![image](https://user-images.githubusercontent.com/27256068/56297715-28f5cd00-6131-11e9-90dd-690deca16e8f.png)

**Comment by AlexeyAB** [comment]
Check that you have `3rdparty/stb/include/stb_image.h` file

Do you use `make` or `cmake` or `vcpkg` for compiling?

**Comment by xiaohai12** [comment]
> Check that you have `3rdparty/stb/include/stb_image.h` file
> 
> Do you use `make` or `cmake` or `vcpkg` for compiling?

Actually, I just changed the server from my company to AWS and I used the same Dockerfile to create image and it worked in my company's server but did not work on AWS. 
I used make for compiling.
I attached my dockerfile 
![image](https://user-images.githubusercontent.com/27256068/56298588-aec64800-6132-11e9-9ec9-25fd0902efa9.png)

**Comment by AlexeyAB** [comment]
Check that you have 3rdparty/stb/include/stb_image.h file

Do you use the latest version of Darknet?

**Comment by xiaohai12** [comment]
> Check that you have 3rdparty/stb/include/stb_image.h file
I don't have stb_image.h file.
> Do you use the latest version of Darknet?
Yes, I used the new version.

**Comment by xiaohai12** [comment]
Sorry I just upload the 3rdparty dictionary to the server and it worked well now.
I don't know why it has not  3rdparty dictionary before.
Thanks.
