### ISSUE TITLE
How does yolo train without annotations?

### ISSUE THREAD

**Issue by joaolcaas** [AlexeyAB/darknet#2954]
I'm trying to make some modifications on yolo and, in one of these, more specif knowlodge destilation, i have to retrain yolo with probablities that come from another model. And, checking on voc.data, i saw that we dont use annotations to train yolo. So, how yolo know witch object he draw? How he learn it whit no labe to tell it to him? 

I alredy know the pretrained models come from imagenet. Maybe that helps but i'm not sure yet. Can anyone help me on it?

**Comment by AlexeyAB** [comment]
> And, checking on voc.data, **i saw that we dont use annotations** to train yolo.

Can you show screenshot?

Yolo can't be trained without annotations.

**Comment by joaolcaas** [comment]
Sorry @AlexeyAB , i made a mess here. I thought, how we dont pass the annotations path, YOLO did not use this to train, but the issue [#1931](https://github.com/AlexeyAB/darknet/issues/1931)  helped me on it.
