### ISSUE TITLE
Right settings for retraining models with new params for small objects detection

### ISSUE THREAD

**Issue by Lepiloff** [AlexeyAB/darknet#2976]
Hi, Alex! Could you get me some advise for training custom models?

I trained my one class model using yolov3_5l.cfg for detection both big and small objects based on yolov3-openimages.weights

`./darknet partial cfg/yolov3-openimages.cfg yolov3-openimages.weights yolov3-openimages.conv.81 81`

 set `stopbackword=1`

and start training with new weights

The sample of training picture:
![39672681_1302d204d1](https://user-images.githubusercontent.com/28572064/56413004-b0a51e00-628e-11e9-9cf7-19de5d0e0549.jpg)

And I got good result for single object detection. 

My next point - detection  a large count of identical objects (class are same as early) at one picture (from 50 to 300 per picture) like this:

![BeeFrame](https://user-images.githubusercontent.com/28572064/56413058-d5999100-628e-11e9-9ecf-6a025689d6e5.jpg)

Is my plan good or bad? Maybe any other suggestion?

1. For next training just used my **yolov3_5l.weight** from previous train . Could I need only set  `stopbackword=1` in my cfg file. What other settigs I can setup for this?

2. Using 3 yolo-layers file **yolo-obj.cfg**.

3. Change **max_batches to 4000**

4. Change line steps to 80% and 90% of max_batches

5. Change **classes=1** and **filters=18**

6. set flag **random=1**

7. increase height/width to 608/608 (or maybe better 832/832?)

8. add parameter **max=300** to each yolo layer

9. set **layers = -1, 11** and **stride=4**

10. recalculate anchors

I really hope for your help! Thanks!

**Comment by AlexeyAB** [comment]
@Lepiloff Hi,

Yes, all is ok.

Just you should train on images that are similar to your test images.

And about 10, be careful if you change anchors, and read: https://github.com/AlexeyAB/darknet#how-to-improve-object-detection


> recalculate anchors for your dataset for width and height from cfg-file: darknet.exe detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416 then set the same 9 anchors in each of 3 [yolo]-layers in your cfg-file. But you should change indexes of anchors masks= for each [yolo]-layer, so that 1st-[yolo]-layer has anchors larger than 60x60, 2nd larger than 30x30, 3rd remaining. Also you should change the filters=(classes + 5)*<number of mask> before each [yolo]-layer. If many of the calculated anchors do not fit under the appropriate layers - then just try using all the default anchors.

**Comment by Lepiloff** [comment]
@AlexeyAB Thank you so much!

**Comment by AlexeyAB** [comment]
> And that about 7 , is will improve accuracy increase network size?

Yes, for small objects.

> And does this parameter depend on the resolution with which I will test the trained network? I mean maybe they should be the same?

In general Train and Test network resolutions should be the same - if your Train and Test images have the same size, and aproximately the same objects sizes.
