### ISSUE TITLE
Fast/Precise Detection for small objects (30ms at max)

### ISSUE THREAD

**Issue by WadRex** [AlexeyAB/darknet#2980]
Hi everybody, I wanted to ask a question, which model should I use. I have a project in school and I want to do a bot for the game with help of object detection. All it has to detect is player model (Simple Human), so the question is, which model will be the best for it? The main problem is, that sometimes object is too far away OR is too close to me and my current model (Yolo V3-Spp 320x320(Working at ~20-22ms)) has a hard time at detecting these objects. Is there any other model I can use? But I guess the only way to somehow improve detection is to bump up the resolution up to 416×416, which is going to put me around these 30ms, but I actually haven't seen any improvement in detection while trying this. Btw I have an 1080ti and if you got any ideas, I would very appreciate to hear them.
Sorry for mistakes, English is not my native language. Thanks in advance.

**Comment by AlexeyAB** [comment]
@WadRex 
Try to use 
* `yolov3_5l.cfg` and width=416 height=416
* or `yolov3_3l.cfg` and width=832 height=832

Train with flag `-map` and compare mAP.

**Comment by WadRex** [comment]
@AlexeyAB 
Thanks, I will try to train those and will tell you the results.
