### ISSUE TITLE
Aws EC2 : Impossible to detecting .mp4 file

### ISSUE THREAD

**Issue by lucaspojo** [AlexeyAB/darknet#2985]
Hi, 
I try to use darknet on aws EC2 with Nvidia tesla M60.
I can predict a jpg with GPU, but i can't predict mp4 video downloaded from youtube ( youtube-dl ).

Thx !

```
NVRM version: NVIDIA UNIX x86_64 Kernel Module  390.116  Sun Jan 27 07:21:36 PST 2019
GCC version:  gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)
```

```
ubuntu@ip-172-31-80-248:~/darknet$ ./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights data/WhatCarCanYouGetForAGrand.mp4
CUDA status Error: file: ./src/dark_cuda.c : () : line: 36 : build time: Apr 20 2019 - 21:59:32
CUDA Error: no CUDA-capable device is detected
CUDA Error: no CUDA-capable device is detected: No such file or directory
darknet: ./src/utils.c:293: error: Assertion `0' failed.
Aborted (core dumped)
```

A this time, nvidia-smi dont work and i found this : https://stackoverflow.com/questions/43022843/nvidia-nvml-driver-library-version-mismatch

```
sudo rmmod nvidia_drm
sudo rmmod nvidia_modeset
sudo rmmod nvidia_uvm
sudo rmmod nvidia
```

Now if i retry to start darknet with .mp4 : 

`Demo needs OpenCV for webcam images.`

I don't know what else is going on. Need help, thx

CUDA : 10.1
OPENCV : 3.4.2

**Comment by AlexeyAB** [comment]
@lucaspojo Hi,

You must compile with OpenCV to detect on video stream (OPENCV=1 in the Makefile, or just use cmake)


Also use flag `-dont_show`

`./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights data/WhatCarCanYouGetForAGrand.mp4 -dont_show`

**Comment by lucaspojo** [comment]
Thx ! `-dont_show` work ! I should have thought of that!
