### ISSUE TITLE
no chart.png 

### ISSUE THREAD

**Issue by passion3394** [AlexeyAB/darknet#2993]
I use "git pull" command to update the newest code from this project, and I have successfully made the code. I use the following command to train the whole network, and I want to get the map chart when the training is going on, but I found no chart.png after the first weights file generated, why?

nohup ./darknet detector train cfg/spp_sign_v3.data cfg/yolov3-spp_sign_v3.cfg yolov3-spp.conv.85 -dont_show -gpus 0,1,2 -map &

**Comment by AlexeyAB** [comment]
You should compile Darknet with OPENCV=1

**Comment by passion3394** [comment]
Hi AlexeyAB, thanks for your quick reply. I am sure I have enable OPENCV=1 in the Makefile. I have tested the opencv environment and it runs normally. the following is the output of command "pkg-config --cflags --libs opencv"

[hs@m2 opencv_test]$ pkg-config --cflags --libs opencv
-I/usr/local/include/opencv -I/usr/local/include  /usr/local/lib/libopencv_calib3d.so /usr/local/lib/libopencv_contrib.so /usr/local/lib/libopencv_core.so /usr/local/lib/libopencv_features2d.so /usr/local/lib/libopencv_flann.so /usr/local/lib/libopencv_gpu.so /usr/local/lib/libopencv_highgui.so /usr/local/lib/libopencv_imgproc.so /usr/local/lib/libopencv_legacy.so /usr/local/lib/libopencv_ml.so /usr/local/lib/libopencv_nonfree.so /usr/local/lib/libopencv_objdetect.so /usr/local/lib/libopencv_ocl.so /usr/local/lib/libopencv_photo.so /usr/local/lib/libopencv_stitching.so /usr/local/lib/libopencv_superres.so /usr/local/lib/libopencv_ts.a /usr/local/lib/libopencv_video.so /usr/local/lib/libopencv_videostab.so -lrt -lpthread -lm -ldl

**Comment by passion3394** [comment]
@AlexeyAB the opencv version is 2.4.9     Is that the key point of this question?

**Comment by AlexeyAB** [comment]
There is just a minor bug: https://github.com/AlexeyAB/darknet/blob/099b71d1de6b992ce8f9d7ff585c84efd0d4bf94/src/image_opencv.cpp#L1101

For training with 3 x GPUs it will save chart.png for each 300 iterations instead of 100 iterations.

I will fix it.

**Comment by passion3394** [comment]
@AlexeyAB sorry, its my mistake, I use an old version of this project. But after I use the newest code to run the training process, I see an message from the terminal:

 (next mAP calculation at 2454 iterations)

Why it says next mAP at 2454 iterations? not 300

**Comment by AlexeyAB** [comment]
* mAP will be calculated for each 4 Epochs
* chart.png will be saved for each 100 iterations (or 300 iterations for 3 GPUs)

**Comment by passion3394** [comment]
@AlexeyAB thanks for your help.

**Comment by passion3394** [comment]
I have got the chart.png, but the y axis is about the loss, how can I get the mAP info?
![chart](https://user-images.githubusercontent.com/14256482/56482239-9325bd80-64f5-11e9-95d9-34e495321b7f.png)

**Comment by passion3394** [comment]
I have seen the mAP, no more question.

**Comment by wangzizhe** [comment]
> I have seen the mAP, no more question.

@passion3394 hi, how did you solve this problem. I can't see mAP in my chart, it is the same as your chart attached here, how you managed to see the mAP chart? Thanks in advance.

**Comment by passion3394** [comment]
@wangzizhe firstly, use this repo's newest code, secondly you must build darknet with opencv=1 in Makefile, thirdly, when you train darknet you must specify the -map flag in the command.
