### ISSUE TITLE
Questions about testing the YOLOV3 model 

### ISSUE THREAD

**Issue by SHADOWMOOON** [AlexeyAB/darknet#2994]
@AlexeyAB Hi ! may I ask for a favor?
After the trainning step is completed. now I'd like to test the model.
I wonder is there a way that I can test the model like when I compile the darknet.sln the VS2015 will generate the Console Application(like the pic below) to do the test instead of  using the command line (darknet.exe detector test data/obj.data yolo-obj.cfg yolo-obj_final.weights).
![1555856784(1)](https://user-images.githubusercontent.com/44594124/56471402-a187c100-6484-11e9-8adf-e9cfc79a1300.png)
In another words ,I don't want to use the darknet.exe file which was generated to do the test.So which part of the darknet.sln project do I need to do some change so that I can test the model 
through the VS2015 Console Application?

**Comment by AlexeyAB** [comment]
@SHADOWMOOON Hi,
I don't uderstand what do you want.

**Comment by SHADOWMOOON** [comment]
@AlexeyAB HI,thanks for the reply.
I mean is there a way that I can use the detection function of the darknet.sln Individually?And How?
Because I want to transfer the darknet's detection function to my own project for image processing(Continue processing for the output BBOXs of YOLOV3). For now I know a way that is to use opencv DNN module to do the detection on my own project.

As for opencvDNN ,for my own pics, I found it is slower than darknet when do the detection
For a 640*480 pic darknet is 22ms while Opencv is 480ms and the Opencv use openCL and gpu to speed up like the pics below:  pic 1 is by Opencv DNN, pic 2 is by darknet(by using command line darknet.exe detector test data/obj.data yolo-obj.cfg yolo-obj_final.weights )
![1555899247(1)](https://user-images.githubusercontent.com/44594124/56479391-ce20f480-64e7-11e9-80d7-119940353de1.png)
![1555899374(1)](https://user-images.githubusercontent.com/44594124/56479395-cf522180-64e7-11e9-9334-7351e4095c05.png)
So my thought is to use the darknet's detection function in my own C++ project for image process rather than Opencv DNN module. Is there a way to do that and how?

**Comment by AlexeyAB** [comment]
@SHADOWMOOON 

* OpenCV-dnn modul is the fast way to detect using CPU (x86/ARM)

* Darknet is the fast way to detect by using GPU(CUDA+cuDNN):

1. you can compile Darknte as DLL/SO-library - and use one of API C https://github.com/AlexeyAB/darknet/blob/master/include/darknet.h or C++ https://github.com/AlexeyAB/darknet/blob/master/include/yolo_v2_class.hpp (C++ API is used in this example https://github.com/AlexeyAB/darknet/blob/master/src/yolo_console_dll.cpp )   
    * compile `yolo_cpp_dll.sln` to get `yolo_cpp_dll.dll` Library
    * or just compile Darknet by using Cmake-GUI: Compiling on Windows by using Cmake-GUI as on this https://user-images.githubusercontent.com/4096485/55107892-6becf380-50e3-11e9-9a0a-556a943c429a.png : Configure -> Optional platform for generator (Set: x64) -> Finish -> Generate -> Open Project -> x64 & Release -> Build -> Build solution: you will get `darklib.dll`

2. Another way - you can use these C++ files in your probject: 
https://github.com/AlexeyAB/yolo2_light/blob/master/src/yolov2_forward_network.c
https://github.com/AlexeyAB/yolo2_light/blob/master/src/yolov2_forward_network_gpu.cu
https://github.com/AlexeyAB/yolo2_light/blob/master/src/gpu.cu
https://github.com/AlexeyAB/yolo2_light/blob/master/src/gpu.h
https://github.com/AlexeyAB/yolo2_light/blob/master/src/additionally.c
https://github.com/AlexeyAB/yolo2_light/blob/master/src/additionally.h
https://github.com/AlexeyAB/yolo2_light/blob/master/src/box.c
https://github.com/AlexeyAB/yolo2_light/blob/master/src/box.h
And use Darknet as in this file: https://github.com/AlexeyAB/yolo2_light/blob/master/src/main.c

**Comment by SHADOWMOOON** [comment]
@AlexeyAB Thank you so much! !
I will try the method 2! 
By the way,so through the method 2(Add those header files and source files in my project,and use the main.c u mentioned above) I may do the object detection in my VS c++ project by using Darknet's detection function(GPU version) .Am I understand that correctly?

**Comment by AlexeyAB** [comment]
@SHADOWMOOON Yes.

**Comment by SHADOWMOOON** [comment]
@SHADOWMOOON thx!
and I'd like to know where to add the .cu files, In the Header Files or Source files?
the screenshot is about my Yolov3 detection  project(which is builded on WIN32 Console Application) of Solution Explorer.
![1556070656(1)](https://user-images.githubusercontent.com/44594124/56627039-cb083e80-6676-11e9-8e01-f7f323f020b7.png)

**Comment by AlexeyAB** [comment]
Add c/h to source code.

**Comment by SHADOWMOOON** [comment]
@SHADOWMOOON thx for the reply.
and what about the .cu files?like gpu.cu and yolov2_forward_network_gpu.cu you mentioned above.
also add to source code?

**Comment by SHADOWMOOON** [comment]
@AlexeyAB Hi
- when I use the method 2 u mentioned above.I met a lot of problems.I can't read the code of those files(the pic below is  yolov2_forward_network.c files) 
![1556162165(1)](https://user-images.githubusercontent.com/44594124/56707471-90bca100-674b-11e9-8f4b-44bb057f2b9c.jpg)
So I turn to method 1 and I find it is easier for me to understand .

- so now I bulid the yolo_cpp_dll.sln(in Release x64 mode)and get the Library files.(like the pic below)
![1556162697(1)](https://user-images.githubusercontent.com/44594124/56707762-cada7280-674c-11e9-9fe8-a6c1387b2d31.jpg)
now I try to run the example u mentioned above(yolo_console_dll.cpp),so I bulid a new project(Win32 Console Application) and add yolo_v2_class.hpp to the Header Files and add yolo_console_dll.cpp to the Source Files(like the pic below)
![1556163015(1)](https://user-images.githubusercontent.com/44594124/56708366-0413e200-674f-11e9-9b8e-aee777aa1f1f.jpg)

-Then  when I build the project.The errors happen like the pic below:
![1556163749(1)](https://user-images.githubusercontent.com/44594124/56708440-39b8cb00-674f-11e9-8dc6-704ec52461d1.jpg)
It's releated to the configuration of the dll?if so,how should I configure?

**Comment by SHADOWMOOON** [comment]
> @AlexeyAB Hi
> 
> * when I use the method 2 u mentioned above.I met a lot of problems.I can't read the code of those files(the pic below is  yolov2_forward_network.c files)
>   ![1556162165(1)](https://user-images.githubusercontent.com/44594124/56707471-90bca100-674b-11e9-8f4b-44bb057f2b9c.jpg)
>   So I turn to method 1 and I find it is easier for me to understand .
> * so now I bulid the yolo_cpp_dll.sln(in Release x64 mode)and get the Library files and lib file and others.(like the pic sbelow)
>   ![1556162697(1)](https://user-images.githubusercontent.com/44594124/56707762-cada7280-674c-11e9-9fe8-a6c1387b2d31.jpg)
>   ![1556175844(1)](https://user-images.githubusercontent.com/44594124/56715858-68449f00-676b-11e9-8018-18db341ebcb3.jpg)
> 
> now I try to run the example u mentioned above(yolo_console_dll.cpp),so I bulid a new project(Win32 Console Application) and add yolo_v2_class.hpp to the Header Files and add yolo_console_dll.cpp to the Source Files(like the pic below)
> ![1556163015(1)](https://user-images.githubusercontent.com/44594124/56708366-0413e200-674f-11e9-9b8e-aee777aa1f1f.jpg)
> 
> -Then when I build the project(Release x64).The errors happen like the pic below:
> ![1556163749(1)](https://user-images.githubusercontent.com/44594124/56708440-39b8cb00-674f-11e9-8dc6-704ec52461d1.jpg)
> It's releated to the configuration of the dll?if so,how should I configure?

@AlexeyAB Hi. Thx for your tutorial !
I solve this problem by add yolo_cpp_dll.lib to my D:\opencv3.4.0\opencv\build\x64\vc14\lib folder:
![1556177401(1)](https://user-images.githubusercontent.com/44594124/56717338-02f2ad00-676f-11e9-857e-70f5196286f4.png)
Then in order to build it on Debug x64,I copy these files to my project Debug folder: cusolver64_91.dll, curand64_91.dll, cudart64_91.dll, cublas64_91.dll,pthreadVC2.dll, pthreadGC2.dll,opencv_world340.dll ,opencv_ffmpeg320_64.dll 
Now I can do my detection on my own project by using YoloV3_console_dll.cpp. Thx a lot!

**Comment by AlexeyAB** [comment]
> when I use the method 2 u mentioned above.I met a lot of problems.I can't read the code of those files(the pic below is yolov2_forward_network.c files)

All files: https://github.com/AlexeyAB/yolo2_light/archive/master.zip

----

> Now I can do my detection on my own project by using YoloV3_console_dll.cpp and it's really fast.
> Thx a lot!

:+1:

**Comment by SHADOWMOOON** [comment]
> > when I use the method 2 u mentioned above.I met a lot of problems.I can't read the code of those files(the pic below is yolov2_forward_network.c files)
> 
> All files: https://github.com/AlexeyAB/yolo2_light/archive/master.zip

Thank you so much!

**Comment by SHADOWMOOON** [comment]
@AlexeyAB Hi.
when I use Yolo as DLL. In the yolo_v2_class.hpp,I want to see the function of LIB_API std::vector<bbox_t> detect(like the pic below)
![1556532986(1)](https://user-images.githubusercontent.com/44594124/56890055-ede98700-6aaa-11e9-9e7a-eb63408e4860.jpg)
In which file can I fine the Definition of the LIB_API std::vector<bbox_t> detect function?
