### ISSUE TITLE
Error while trainning

### ISSUE THREAD

**Issue by qasimz** [AlexeyAB/darknet#2996]
I get the  following error while trainning. I am not using any gpu. I start training by the following command.

`./darknet detector train cfg/obj.data cfg/tiny-yolo1.cfg darknet19_448.conv.23`

`70: 2.096784, 2.734118 avg loss, 0.000100 rate, 23.980093 seconds, 1680 images
Resizing
608 x 608 
Loaded: 0.147326 seconds
Region Avg IOU: 0.735355, Class: 1.000000, Obj: 0.202906, No Obj: 0.201810, Avg Recall: 1.000000,  count: 1
Region Avg IOU: 0.685519, Class: 1.000000, Obj: 0.204355, No Obj: 0.201792, Avg Recall: 1.000000,  count: 2
Region Avg IOU: 0.596906, Class: 1.000000, Obj: 0.201310, No Obj: 0.201801, Avg Recall: 1.000000,  count: 2
Region Avg IOU: 0.503340, Class: 1.000000, Obj: 0.201234, No Obj: 0.201787, Avg Recall: 0.333333,  count: 3
Region Avg IOU: 0.553824, Class: 1.000000, Obj: 0.199211, No Obj: 0.201813, Avg Recall: 0.500000,  count: 2
Region Avg IOU: 0.258413, Class: 1.000000, Obj: 0.203142, No Obj: 0.201806, Avg Recall: 0.000000,  count: 2
Region Avg IOU: 0.349347, Class: 1.000000, Obj: 0.202449, No Obj: 0.201801, Avg Recall: 0.500000,  count: 2
Region Avg IOU: 0.365876, Class: 1.000000, Obj: 0.201961, No Obj: 0.201795, Avg Recall: 0.500000,  count: 2
Region Avg IOU: 0.540573, Class: 1.000000, Obj: 0.200822, No Obj: 0.201803, Avg Recall: 0.500000,  count: 2
Region Avg IOU: 0.478258, Class: 1.000000, Obj: 0.204984, No Obj: 0.201788, Avg Recall: 0.500000,  count: 2
Region Avg IOU: 0.641338, Class: 1.000000, Obj: 0.200722, No Obj: 0.201808, Avg Recall: 1.000000,  count: 2
Region Avg IOU: 0.601531, Class: 1.000000, Obj: 0.204102, No Obj: 0.201781, Avg Recall: 1.000000,  count: 2

 71: 2.358698, 2.696576 avg loss, 0.000100 rate, 40.906493 seconds, 1704 images
Loaded: 0.000037 seconds
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: -nan, Avg Recall: 0.000000,  count: 3
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: -nan, Avg Recall: 0.000000,  count: 10
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: -nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: -nan, Avg Recall: 0.000000,  count: 5
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: -nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: -nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: -nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: -nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: -nan, Avg Recall: 0.000000,  count: 3
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: -nan, Avg Recall: 0.000000,  count: 6
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: -nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: -nan, Avg Recall: 0.000000,  count: 3

 72: -nan, -nan avg loss, 0.000100 rate, 37.113196 seconds, 1728 images
Loaded: 0.000088 seconds
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 1
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2

 73: -nan, -nan avg loss, 0.000100 rate, 37.598329 seconds, 1752 images
Loaded: 0.000087 seconds
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 3
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2

 74: -nan, -nan avg loss, 0.000100 rate, 39.074849 seconds, 1776 images
Loaded: 0.000095 seconds
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 4
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 3
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2

 75: -nan, -nan avg loss, 0.000100 rate, 40.009583 seconds, 1800 images
Loaded: 0.000060 seconds
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 5
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 3
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 5
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2

 76: -nan, -nan avg loss, 0.000100 rate, 37.421554 seconds, 1824 images
Loaded: 0.000032 seconds
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 3
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 3
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2

 77: -nan, -nan avg loss, 0.000100 rate, 39.893767 seconds, 1848 images
Loaded: 0.000083 seconds
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 3
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 1

 78: -nan, -nan avg loss, 0.000100 rate, 37.715463 seconds, 1872 images
Loaded: 0.000040 seconds
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 3
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 3
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2

 79: -nan, -nan avg loss, 0.000100 rate, 39.221418 seconds, 1896 images
Loaded: 0.000081 seconds
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 7
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 4
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 3
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 2
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 3
Region Avg IOU: nan, Class: nan, Obj: -nan, No Obj: nan, Avg Recall: 0.000000,  count: 2

 80: -nan, -nan avg loss, 0.000100 rate, 37.712028 seconds, 1920 images
Resizing
448 x 448 
*** Error in `./darknet': realloc(): invalid next size: 0x0000000004e3b760 ***
`

**Comment by AlexeyAB** [comment]
Can you attach your cfg-file?

**Comment by qasimz** [comment]
`[net]
batch=24
subdivisions=12
width=416
height=416
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
max_batches = 120000
policy=steps
steps=-1,100,80000,100000
scales=.1,10,.1,.1

[convolutional]
batch_normalize=1
filters=16
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=1

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky

###########

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=30
activation=linear

[region]
anchors = 0.738768,0.874946,  2.42204,2.65704,  4.30971,7.04493,  10.246,4.59428,  12.6868,11.8741
bias_match=1
classes=1
coords=4
num=5
softmax=1
jitter=.2
rescore=1

object_scale=5
noobject_scale=1
class_scale=1
coord_scale=1

absolute=1
thresh = .6
random=1`

**Comment by qasimz** [comment]
It is now solved by solving issue 
Duplicate of 2995#
