### ISSUE TITLE
how to compile the code using vs2013

### ISSUE THREAD

**Issue by kingvision** [AlexeyAB/darknet#3]
Hi:
    how to compile the code using vs2013. can you give a project?

Thanks

**Comment by AlexeyAB** [comment]
@kingvision 

Hi,

It can be compiled on MSVS 2013 (12.0.40629.00 update 5), but not on MSVS 2013 (12.0.21005.1). I.e. your MSVS should supports C99 standard.

If you have MSVS 2013 (12.0.40629.00 update 5) and CUDA 8.0 then simply open `build/darknet/darknet.sln` and build it.
