### ISSUE TITLE
the testing images are transformed from the original images in 6 freedom

### ISSUE THREAD

**Issue by passion3394** [AlexeyAB/darknet#3000]
hello @AlexeyAB, my training dataset is from the original images captured by camera, my testing images are transformed from the original images in 6 freedom, and crop the transformed result from the height direction. how can I get more mAP on the testing images? thanks very much.

**Comment by AlexeyAB** [comment]
@passion3394 Hi,

Just add "transformed from the original images in 6 freedom and crop the transformed result from the height direction" to the training images. The more images with the same changes as in test-dataset - the higher mAP.

**Comment by passion3394** [comment]
@AlexeyAB thanks, I will try it.
