### ISSUE TITLE
How to ignore some specific ground truth?

### ISSUE THREAD

**Issue by lxlhh** [AlexeyAB/darknet#3002]
Hi, @AlexeyAB . I want to improve performance for objects of specific size and ignore others, for example, I only care samples with height exceeds 100 pixels. In the dataset, we have labeled objects of all size. So, in order to ignore the influence of samples which fail to meet the condition when training, how can i modify the loss to not take into account these samples?

**Comment by AlexeyAB** [comment]
@lxlhh Hi,

You can just use `yolov3.cfg` with removed these layers: https://github.com/AlexeyAB/darknet/blob/099b71d1de6b992ce8f9d7ff585c84efd0d4bf94/cfg/yolov3.cfg#L618-L788

----

And with changed these anchors: https://github.com/AlexeyAB/darknet/blob/099b71d1de6b992ce8f9d7ff585c84efd0d4bf94/cfg/yolov3.cfg#L609

to:
```
anchors = 10,13,  16,30,  33,23,  30,61,  62,45,  99,99,       100,100,  156,198,  373,326 
```

**Comment by lxlhh** [comment]
@AlexeyAB Thanks for your reply , I will have a try.

**Comment by minhtcai** [comment]
Hi, could you please explain the mechanism behind this change?
Can I do the same with other anchor boxes and layers?
