### ISSUE TITLE
Randomly create Train and Test dataset

### ISSUE THREAD

**Issue by bhargavravat** [AlexeyAB/darknet#3003]
Hi @AlexeyAB ,

I am presently training Yolo V3 with Almost 4M images with single class. 
Is there any script / tool / method available for randomly splitting my train and test data set ?

**Comment by yangulei** [comment]
Here is a tiny python script refer to your needs:
```python
import os
import glob
import random

testRatio = 0.2    # set the test ratio (number of test images over total number of images)
imgNames = glob.glob("images/*.jpg")    # get the list of your dataset
list_test = open("data/image_list_test.txt", 'w')    # file to store the test dataset
list_train  = open("data/image_list_train.txt", 'w')    # file to store the train dataset

numImg = len(imgNames)
randomIndx = list(range(numImg))
random.shuffle(randomIndx)
testImgIndx = randomIndx[:int(numImg*testRatio)]
trainImgIndx = randomIndx[int(numImg*testRatio):]

for imgIndx in testImgIndx:
    imgName = imgNames[imgIndx]
    list_test.write(os.path.abspath(imgName)+"\n")
list_test.close()

for imgIndx in trainImgIndx:
    imgName = imgNames[imgIndx]
    list_train.write(os.path.abspath(imgName)+"\n")
list_train.close()
```
You just need to modify the paths.

**Comment by JakupGuven** [comment]
This is what I use
`import glob, os

# Current directory
current_dir = os.path.dirname(os.path.abspath(__file__))

# Directory where the data will reside, relative to 'darknet.exe'
path_data = 'data/'

# Percentage of images to be used for the test set
percentage_test = 20;

# Create and/or truncate train.txt and test.txt
file_train = open('train.txt', 'w')  
file_test = open('test.txt', 'w')

# Populate train.txt and test.txt
counter = 1  
index_test = round(100 / percentage_test)  
for pathAndFilename in glob.iglob(os.path.join(path_data, "*.jpg")):  
    title, ext = os.path.splitext(os.path.basename(pathAndFilename))

    if counter == index_test:
        counter = 1
        file_test.write(path_data + title + '.jpg+ "\n")
    else:
        file_train.write(path_data + title + '.jpg+ "\n")
        counter = counter + 1
`
