### ISSUE TITLE
average loss nan

### ISSUE THREAD

**Issue by leiyaohui** [AlexeyAB/darknet#3005]
Hello, I use yolov3.cfg to train my data set. Average loss is nan, only after iteration or not convergence. Do you know what this is?

**Comment by leiyaohui** [comment]
My database is self-annotated, a total of three categories, two of which are less samples, I wonder if this is the cause of this problem? I look forward to your reply, thank you!

**Comment by AlexeyAB** [comment]
@leiyaohui Hi,

Check your dataset by using Yolo_mark: https://github.com/AlexeyAB/Yolo_mark

Do you use training with GPU and cuDNN?

**Comment by leiyaohui** [comment]
Thank you for your quick reply. I trained on GPU and cuDNN. The annotation is also marked with YOLO_mark. I don't know why this happens.

**Comment by AlexeyAB** [comment]
What parameter do you set in the Makefile?

Can you show screenshot of console output?

Can you attach your chart.png?

Can you attach your cfg-file?

**Comment by leiyaohui** [comment]
Thank you for your patient reply! I trained only one type of car. Here are some of my configuration files:
![chart](https://user-images.githubusercontent.com/42469241/56624974-b96e6900-666d-11e9-8b22-1bca2f0104b5.jpg)
![chart2](https://user-images.githubusercontent.com/42469241/56624975-b96e6900-666d-11e9-9ed7-5981c44fd745.jpg)
![console](https://user-images.githubusercontent.com/42469241/56624977-ba06ff80-666d-11e9-8a7d-939f07c17f40.jpg)

[yolov3_cfg.txt](https://github.com/AlexeyAB/darknet/files/3110103/yolov3_cfg.txt)
Thank you again.

**Comment by AlexeyAB** [comment]
You should use default anchors in your cfg-file.
