### ISSUE TITLE
OpenCV assertion failed for video detection

### ISSUE THREAD

**Issue by tantra-anthony** [AlexeyAB/darknet#3012]
Command used:
`darknet_no_gpu.exe detector demo sample.data sample.cfg sample.weights sample2.mp4`

Error output:
`OpenCV Error: Assertion failed (src.type() == dst.type()) in cvResize, file C:\build\master_winpack-build-win64-vc14\opencv\modules\imgproc\src\imgwarp.cpp, line 6436`

OpenCV version used: **3.0**

I assumed that the video stream will just pop up like the image detection ones (the image detection is working fine btw) but it gave me this error instead.

Any ideas why this is happening? The stack trace shows this fails at function `get_image_from_stream_resize` at the second `cvResize` when `src` is resized to `new_img`.

**Comment by AlexeyAB** [comment]
@tantra-anthony 

Try to use the latest version of Darknet.

If it doesn't help, can you share your videofile (for example by using GoogleDisk) ?

**Comment by tantra-anthony** [comment]
@AlexeyAB 

Thanks for the reply. Just realised that you changed the implementation for this method not too long ago and my version was updated about 2 months ago.

The video stream is working fine now after pulling for the latest change, but the single image detection shows another OpenCV assertion error:
```OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cv::cvtColor, file C:\build\master_winpack-build-win64-vc14\opencv\modules\imgproc\src\color.cpp, line 10606```

Should I open another issue for this?

Thanks for the help!

**Comment by AlexeyAB** [comment]
@tantra-anthony Can you send zip/... archive with this image and your cfg-file?

**Comment by tantra-anthony** [comment]
@AlexeyAB 

Sure, I have invited you to a private repo here https://github.com/tantra-anthony/AlexeyAB-darknet-issue-3012 with all the files required (`.names`, `.cfg`, `.data`, and latest `.weights` including both the image and the video).

As it's still a closed project, please help me delete everything when the issue is resolved.

**Comment by AlexeyAB** [comment]
@tantra-anthony 

I fixed this bug. 
I deleted your data.

**Comment by tantra-anthony** [comment]
Thank you, closing this issue!
