### ISSUE TITLE
Make bounding box blurring

### ISSUE THREAD

**Issue by ghost** [AlexeyAB/darknet#3025]
Hello, 

I want to blurring somes objects, do you think it is possible to make this blurring directly in the treatment, instead of show bounding box, label and pourcent.

Thanks,

**Comment by AlexeyAB** [comment]
@novsub Hi,

For detection on **Video**:
You can blur content of bbox by adding this line:
`cv::GaussianBlur(*show_img, *show_img, cv::Size(9,9), 0);`

there:  https://github.com/AlexeyAB/darknet/blob/bc95ce3c250233c380633c4ef6ee98cfe74eeecd/src/image_opencv.cpp#L965

**Comment by novsub** [comment]
Thank's @AlexeyAB,

I have tried and it's work but the blurring is on all the video (and not just the content of bbox were objects are present). 

I search but if you have any idea ..

Thank's

**Comment by AlexeyAB** [comment]
@novsub Yes, my mistake, try to use
```cpp
                cv::Rect roi(pt1, pt2);
                cv::GaussianBlur((*show_img)(roi), (*show_img)(roi), cv::Size(9, 9), 0);
```

**Comment by novsub** [comment]
@AlexeyAB  Nice, It's great ! Thank's :-)
