### ISSUE TITLE
Windows 10; CMake: CUDA compiler not found

### ISSUE THREAD

**Issue by DarLador** [AlexeyAB/darknet#3028]
Hi,

I did setup Visual Studio 2017 community edition(v. 15.9.11), downloaded CUDA 10.0, cuDNN 7.4.2 (and copied the relevant cuDNN files to CUDA), opencv (3.4.6 from opencv.org) and CMake 3.14.3. I also added hundreds of environment system variables.

Here is darknet CMake Configure output:
```
The C compiler identification is MSVC 19.16.27030.1
The CXX compiler identification is MSVC 19.16.27030.1
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Looking for a CUDA compiler
Looking for a CUDA compiler - NOTFOUND
OpenCV ARCH: x64
OpenCV RUNTIME: vc15
OpenCV STATIC: OFF
Found OpenCV: C:/opencv_3.4/opencv/build (found version "3.4.6") 
Found OpenCV 3.4.6 in C:/opencv_3.4/opencv/build/x64/vc15/lib
You might need to add C:\opencv_3.4\opencv\build\x64\vc15\bin to your PATH to be able to run your applications.
Found Stb: C:/Users/User/darknet/3rdparty/stb/include  
ZED SDK not enabled, since it requires CUDA
Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE  
Found PThreads_windows: C:/Users/User/darknet/3rdparty/pthreads/lib/pthreadVC2.lib  
Found OpenMP_C: -openmp (found version "2.0") 
Found OpenMP_CXX: -openmp (found version "2.0") 
Found OpenMP: TRUE (found version "2.0")  
Configuring done
```
I tried to compile it anyway, and it compiled but then, when I tried to execute
`darknet.exe detector train cfg/obj.data cfg/yolo-obj.cfg yolo-obj_2000.weights`
I got errors about missing `pthreadVC2.dll` and `opencv_world346.dll`.

So, back to the first problem `Looking for a CUDA compiler - NOTFOUND`. I did find similar issues here, I tried to uninstall VS and CUDA. I also completely removed everything - Nvidia, VS, CUDA, opencv, CMake... installed windows updates, and then installed everything again. I reboot after every installation. But it didn't work. 

I'm stuck with no idea what to do and I would really appreciate any help.

**Comment by AlexeyAB** [comment]
@DarLador Hi,

May be it is related to: https://github.com/AlexeyAB/darknet/issues/2971

**Comment by DarLador** [comment]
Hi @AlexeyAB I just checked this issue.

I can't find `CUDA 10.0.props` in
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\BuildCustomizations`

In the last days I removed everything (including temp files, keys etc.), made sure I had W10 updated, reboot several times, reinstalled everything (+ reboot after every installation). I did it 3 or 4 times.

Also, I couldn't make vcpkg work on my PC, so I use the CMacke (though I did clone vcpkg to install OpenCV at first, but I failed to compile it, so I downloaded OpenCV from opencv.org, and CMake seems to "recognize" opencv).

I wonder if I miss something here...

**Comment by DarLador** [comment]
Do I miss something here?
![win_env](https://user-images.githubusercontent.com/17408143/56662353-6ff13e80-66ac-11e9-9666-dc98a9670762.PNG)

**Comment by cenit** [comment]
are you using the `build.ps1` script from a Powershell?

**Comment by DarLador** [comment]
No, I used the first option (compile with CMake):
> ### How to compile on Windows (using vcpkg)
> If you have already installed Visual Studio 2015/2017/2019, CUDA > 10.0, cuDNN > 7.0, OpenCV > 2.4, then compile Darknet by using C:\Program Files\CMake\bin\cmake-gui.exe as on this IMAGE: Configure -> Optional platform for generator (Set: x64) -> Finish -> Generate -> Open Project -> x64 & Release -> Build -> Build solution
I have CUDA 10.0 (because I want it to work with TensorFlow-GPU).

**Comment by JoeRu** [comment]
Hi @DarLador - my issue were with the installation of CUDA; You should remove it with even checking for folders in Program-folder after deinstallation and then reinstall; When the Props-File are not there - the whole thing goes bogus.

I did also write up everything with the close in the issue marked by @AlexeyAB some hours ago.

**Comment by DarLador** [comment]
Thanks @JoeRu 
I've done it like 3 or 4 times, and now I'm going to do that again. Who knows, maybe this time it will work (:

**Comment by DarLador** [comment]
OK, this is weird. I uninstalled Nvidia, and then tried to remove the folders in Program Files. This is the last folder. 
![image](https://user-images.githubusercontent.com/17408143/56677166-9ae98b80-66c8-11e9-880b-334044edd683.png)

**Comment by cenit** [comment]
@darlador please try also build.ps1
The script itself make sure to setup many things in order to ease cmake work.

**Comment by DarLador** [comment]
@cenit Thanks! I will definitely try it!

**Comment by DarLador** [comment]
Hi @JoeRu , I just reinstalled CUDA, tested it with the MSVS with provided samples, and now I can find the `CUDA 10.0.props` file.

@cenit following your advice, I try to build darknet in PS using vcpg. But before the `build.ps1`, I need to run `.\vcpkg install pthreads opencv[ffmpeg]`, but it fails:
![image](https://user-images.githubusercontent.com/17408143/56734028-6f1ee200-676a-11e9-95e0-16757ce8c22c.png)

I opened the log file and saw this: 
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
``` 
And then huge lists. [Here is the full log file](https://github.com/AlexeyAB/darknet/files/3116759/config-x86-windows-out.log). What does it mean?

**Comment by cenit** [comment]
@DarLador using `build.ps1` create a custom install based on your cloned repository
using `vcpkg install darknet[opencv-cuda]` is another approach, but different. You don't have to do both!

Maybe we have too many install options 🤣

**Comment by DarLador** [comment]
@cenit 😂 hahaha no it's great you put many options, because if your current choice doesn't work out, you can try the others. I was talking about the first approach with `vcpkg install pthread opencv[cuda,ffmpeg]`.

So I customized the `build.ps1` and set `my_cuda_compute_model = 61` , and then built it in PowerShell.
And it worked!

I added this variable to my path: `%VCPKG_ROOT%\installed\%VCPKG_DEFAULT_TRIPLET%\bin`, downloaded the *yolov3.weights* file and executed 
`darknet.exe detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg`

Then I got an error **CUDA Error: unknown error: No error**
![p14](https://user-images.githubusercontent.com/17408143/56809981-d3f73c80-683d-11e9-915b-bc7345543e22.PNG)
So, I checked my *Display adapter* and guess what? **Code 52** Error
![p15_err](https://user-images.githubusercontent.com/17408143/56810221-6d265300-683e-11e9-8630-51df7118f273.PNG)

It turns out [I'm not the only one](https://devtalk.nvidia.com/default/topic/1046327/cuda-setup-and-installation/problem-when-trying-to-install-cuda-10-on-windows/) who has a problem installing CUDA on a laptop with NVIDIA GPU running Windows 10. One person says that [CUDA 10.0 installation kills Windows 10](https://devtalk.nvidia.com/default/topic/1045792/cuda-setup-and-installation/cuda-10-0-installation-kills-windows-10/). 

I feel lucky it didn't kill my MSI. I found a simple solution though. I just opened "GeForce Experience" app, and selected custom installation - made sure I didn't need to install the graphic driver, but just the others (i.e. PhysX and HD Audio). It fixed this problem :)

Now I can start darknet.exe!

I'm closing this issue, but just need to remember that **laptops with NVIDIA GPU running Windows 10** need:
1. Uninstall all NVIDIA drivers + delete Nvidia folders in Program files + clear temp files 
2. Install MSVS 2017 (+Desktop development with C++)
3. Install the the right CUDA version
4. Test that CUDA works properly by building a test project.
5. Open NVIDIA driver's app and install the driver.

**Comment by cenit** [comment]
I’m very proud of `build.ps1` :)
