### ISSUE TITLE
how to load the model once, use it multiple times

### ISSUE THREAD

**Issue by ericwang321** [AlexeyAB/darknet#3035]
Use the bash script， invoke follow command，  to periodically use the processed image folder,

    ./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights -dont_show < a1.txt > r1.txt

how to load the model once, use it multiple times ，speed up processing time？

reference issue https://github.com/AlexeyAB/darknet/issues/3023

**Comment by LukeAI** [comment]
You might have to write your own wrapper. I load once and use multiple times using a variation on the provided specimen python script.

**Comment by ericwang321** [comment]
thanks,it works.
close the issue temporarily .

**Comment by MindSightTH** [comment]
@ericwang321  Could you please explain more how to do so?

**Comment by stephanecharette** [comment]
For anyone else who ends up here, also see #5930.
