### ISSUE TITLE
Detection issue after modifying the filters in the yolo layer

### ISSUE THREAD

**Issue by damonlian** [AlexeyAB/darknet#3037]
Hi @AlexeyAB :
I modified the yolo layer with the filters ( (classes + 4 + 1) to (classes + 4 + 1 +2 ) ) to train a sequence video dataset.
After training on yolov3-tiny.cfg , demo video ran perfectly, but training on yolov3-tiny_occlusion_track.cfg, demo video can only detect successfully the first frame, cannot detect any object after the first frame.
Do crnn layer has to modify in this case to fit my case.
Thanks

**Comment by AlexeyAB** [comment]
@damonlian Hi,

* Did you train `yolov3-tiny_occlusion_track.cfg` on sequentiall frames from video?

* What mAP can you get on `valid=train.txt` and `valid=valid.txt` in `obj.data` file?

* Can you attach both cfg-files?

**Comment by damonlian** [comment]
> @damonlian Hi,
> 
> * Did you train `yolov3-tiny_occlusion_track.cfg` on sequentiall frames from video?
> * What mAP can you get on `valid=train.txt` and `valid=valid.txt` in `obj.data` file?
> * Can you attach both cfg-files?

1.Yes, I trained `yolov3-tiny_occlusion_track.cfg` on sequentiall frames.
2.I got 0% from training `yolov3-tiny_occlusion_track.cfg` on both files.
3. 
 `yolov3-tiny.cfg` 
[yolov3-tiny.txt](https://github.com/AlexeyAB/darknet/files/3119599/yolov3-tiny.txt)

 `yolov3-tiny_occlusion_track.cfg` 
[yolov3-tiny_occlusion_track.txt](https://github.com/AlexeyAB/darknet/files/3119604/yolov3-tiny_occlusion_track.txt)

**Comment by AlexeyAB** [comment]
You should use default params
https://github.com/AlexeyAB/darknet/blob/cce34712f6928495f1fbc5d69332162fc23491b9/cfg/yolov3-tiny_occlusion_track.cfg#L18-L20

Just you can reduce in this way:
```
 track=1 
 time_steps=16 
 augment_speed=2
```
