### ISSUE TITLE
Question on Labeling Strategy

### ISSUE THREAD

**Issue by holger-prause** [AlexeyAB/darknet#3044]
Hello,
I have seen various datasets and i have seen some label strategies - i would like to discuss them if possible.

-S1:Label Parts of the object as the object itself 
 I have seen that parts of the object are labeled as  the object itself (i.e label a hand as a person )

-S2:Label Crowds of objects as one
 I have seen this from time to time that multiple objects(crowd) are labeled as one object(i.e label a crowd of persons as a single person with one big bounding box)

Well i personally think S1 makes sense and leads to good results as these features leads to the class you want to detect .

About S2 - I am not sure about this. I guess its more or less the same idea like in S1. Maybe it makes sense to label a person crowd, which is far away in the pictures and has few features for this reason, as a single instance. But if you do this for person which are together but you could clearly seperate them, i am afraid this would hurt my training?
I think this happened to me when i trained on coco first(I ignored isCrowd attribute) 

Anyways , anny thought or comments on this would be helpful.
Thank you very much.

**Comment by AlexeyAB** [comment]
@holger-prause Hi,

In both cases, you should label in such a way as you want to detect.

If you dont want to detect hand as person, or dont want to detect crowd as person, then you shouldn't label in such a way.
Otherwise, you should label in such a way.

**Comment by holger-prause** [comment]
Well this is so easy it makes a lot of sense. I was tending to think statistically about this whole stuff but in the end - just labeling what you want to detect is fine too :-)

Thank you very much - closed.
