### ISSUE TITLE
Uniform compiling of the Darknet 

### ISSUE THREAD

**Issue by AlexeyAB** [AlexeyAB/darknet#3051]
Uniform compiling of the Darknet with the same names of the executable file and the library (for Windows and Linux, for Legacy and New ways):

Generated files are in the `/darknet/` folder:

* `./darknet` and `darknet.exe`
* `libdark.so` and `libdark.dll`
* `./uselib` and `uselib.exe`
* `./uselib_track` and `uselib_track.exe`

**Comment by AlexeyAB** [comment]
@cenit Will all of these be fixed in https://github.com/AlexeyAB/darknet/pull/5717 ?

**Comment by cenit** [comment]
Apart from the dlls from the legacy vs solution, yes now makefile and cmake are aligned
