### ISSUE TITLE
Can the Yolo-Windows v1 program be compiled in VS2010 (v100) Platform Toolset? Thank you!

### ISSUE THREAD

**Issue by shuimoshusheng** [AlexeyAB/darknet#306]

**Comment by AlexeyAB** [comment]
Yolo v1 here, so try to compile it in VS2010: https://github.com/AlexeyAB/yolo-windows

**Comment by shuimoshusheng** [comment]
Yesterday I received your email,thank you very much! And i was tried to deploy yolo windows v2 in VS 2010,there are a lot of mistakes in head file and source file.
I hope to find out which standard you used to write the program,why there is a difference between vs 2010 and vs 2015.Can you give me some suggestions？
I will try yolo v1 can run on vs 2010.Thank you very much!
