### ISSUE TITLE
does yolo detector demo resize frames before detection?

### ISSUE THREAD

**Issue by IbrahimBond** [AlexeyAB/darknet#3068]
Hi, 

i would like to know if there is frame resize or skipping before detection when using this command : "./darknet detector demo custom/trainer.data custom/yolov3-tiny.cfg backup/yolov3-tiny_final.weights test_input.mkv"

i am trying to achieve the same result as the command above with python. but the command above is doing better and smoother unless i resize the frames to lower resolution at first. 

currently i am using https://github.com/madhawav/YOLO3-4-Py python wrapper that uses opencv to get the frames and then process the image to be yolo compatible before forwarding it to the network. 

precisely processing the frame to be yolo compatible is what takes more time with higher resolution. 

this is the piece of code responsible for the processing : 

 # Code adapted from https://github.com/solivr/cython_opencvMat
            assert ary.ndim==3 and ary.shape[2]==3, "ASSERT::3channel RGB only!!"

            # Re-arrange to suite Darknet input format
            ary = ary.transpose(2, 0, 1)

            # BGR to RGB
            ary = ary[::-1,:,:]

            # 0..1 Range
            ary = ary/255.0

            # To c_array
            cdef np.ndarray[np.float32_t, ndim=3, mode ='c'] np_buff = np.ascontiguousarray(ary, dtype=np.float32)
            cdef int c = ary.shape[0]
            cdef int h = ary.shape[1]
            cdef int w = ary.shape[2]

            # Copy to Darknet image
            self.img.w = w
            self.img.h = h
            self.img.c = c
            self.img.data = <float*>malloc(h*w*c*4)
            memcpy(self.img.data, np_buff.data, h*w*c*4)

is that the same way demo detector works? as in lowering the resolution before making the frames yolo compatible? 

i have also realized that lowering frames resolutions to for example 832 in prior would significantly decrease detection performance. can someone explain the reason, because  i thought that yolo resizes the frames anyway?   

current video resolution 2592,1520 
current network size : 832 

how would i achieve the exact result with python?

GPU and cudnn are enabled.   

sorry for the many questions, i am new to this and trying to get a hold of how it works.

**Comment by AlexeyAB** [comment]
Yes, both https://github.com/pjreddie/darknet and https://github.com/AlexeyAB/darknet and OpenCV-dnn uses 3 different approaching of resizing before Training/Detection: https://github.com/AlexeyAB/darknet/issues/232#issuecomment-336955485
