### ISSUE TITLE
Getting hughe average loss

### ISSUE THREAD

**Issue by snphnolt** [AlexeyAB/darknet#3069]
Hello Guys, 
I am trying to train darknet on one class (followed the detailed description). I used the  [Open Image Dataset V4](https://github.com/openimages/dataset) and converted the given annotations to the yolo format:

Example: 
0 0.46193300000000004 0.49901449999999997 0.523524 0.25164299999999995

So far so good. When I tried to train darknet I got an insanely high loss:
![grafik](https://user-images.githubusercontent.com/31032797/56895436-6dfef500-6a89-11e9-8dec-afb88643e6e6.png)
I have not been able to train on GPU yet, due to some  missing libaries. That fact shouldnt be the cause though right?

I tried using different cfg files (and modified those as well) and results. Do you have any ideas? 
Your help is highly appriciated :)

**Comment by AlexeyAB** [comment]
@snphnolt Hi,
The first 500-1000 iterations will have very high loss, it's normal.
To train the model on Open Image Dataset V4 on CPU you should wait for a years )

**Comment by snphnolt** [comment]
@AlexeyAB  Thanks for the quick response.
I am training on my Institutes GPU Server and I havent solved the issues with cuda. As soon as I find a solution I hope to speed up the process :)
