### ISSUE TITLE
Compiling Darknet on Windows with MSMV2019 and CUDA 10.0

### ISSUE THREAD

**Issue by felixwolff** [AlexeyAB/darknet#3071]
Dear all,

Versions: Windows 10, MSVS2019, OpenCV 3.4.0, CUDA 10.0, cuDNN 7.5.1

I cloned AlexeyABs repo and followed compiling steps as described for GPU installation on Windows and got compilation errors. However previous warnings already popped up when installing CUDA about integration with MSVS2019. 
Do you know if CUDA 10.0 and MSVS 2019 are compatible?

![image](https://user-images.githubusercontent.com/13048329/56902741-34cf8080-6a9b-11e9-9bbe-e145c9130946.png)

Then I follwed the instructions: 
-	Installed OpenCV 3.4.0; created folder C:\opencv_3.0 with C:\opencv_3.0\build\include and C:\opencv_3.0\build\x64\vc14\lib
-	confirmed, that both entries for CUDA version in \build\darknet\darknet.vcxproj are set to 10.0

The next error occurs, when opening build\darknet\darknet.sln in MSVS2019 and setting “x64” and “Release”. Note that the "Designtime" error pops up already when opening the project before clicking the build button. 

![image](https://user-images.githubusercontent.com/13048329/56902983-b1625f00-6a9b-11e9-8a59-e11a76a6f320.png)

Your help is much appreciated!

**Comment by AlexeyAB** [comment]
@felixwolff Hi,
Try to install CUDA 10.1 instead of CUDA 10.0.

https://devblogs.microsoft.com/cppblog/cuda-10-1-available-now-with-support-for-latest-microsoft-visual-studio-2019-versions/

> CUDA 10.1 available now, with support for latest Microsoft Visual Studio 2019 versions

**Comment by felixwolff** [comment]
@AlexeyAB 
Thanks your the quick reply!
Unfortunately, after installing CUDA 10.1 ( and the appropriate cuDNN version) and updating darknet.vcxproj to "10.1" the same "Designtime" error occurs in MSVS2019 when opening darknet.sln. However, the no-integration warning  with MSVS during CUDA installation doesn't show up any more.

![cuda_warning_no_support_MSVS](https://user-images.githubusercontent.com/13048329/56908750-3737d780-6aa7-11e9-91d9-1a48efeb0898.PNG)

(Don't know if it helps, but compiling darknet_no_gpu.sdl worked)

**Comment by prdas31** [comment]
I found that CUDA 10.1 for windows 10 did work for the MSVS 2019 16.0 preview versions, but not for version 16.0.2.
Thanks.

**Comment by AlexeyAB** [comment]
@prdas31 So, it looks like a bug in CUDA 10.1/10.0 (or MSVS2019(16.0.2)).

**Comment by wahyubram82** [comment]
MSVS2019 developer is Microsoft, so it different with CUDA developer (NVIDIA).
use previous MSVS, recommended is 2015 for sure working...you can use MSVS 2017, but I forget which version is working.
