### ISSUE TITLE
learning voc data

### ISSUE THREAD

**Issue by minjuprinces1004** [AlexeyAB/darknet#308]
hi, i'm a beginner of deep learning.
i have a fundamental problem in learning VOC data.
i copyed the VOC Datas to voc subdirectory as follow:

build\darknet\x64\data\voc
   VOCtest_06-Nov-2007
   VOCtrainval_06-Nov-2007
   VOCtrainval_11-May-2012
   voc_label.py

when i run voc_label.py occurs following error:
   FileNotFoundError: [Errno 2] No such file or directory: 'VOCdevkit/VOC2012/ImageSets/Main/train.txt'

i'd appreciate it if you cound teach me how to solve it.
thanks.

**Comment by AlexeyAB** [comment]
Hi, 
* you should copy `VOCtest_06-Nov-2007\VOCdevkit`, `VOCtrainval_06-Nov-2007\VOCdevkit` and `VOCtrainval_11-May-2012\VOCdevkit` to the single `VOCdevkit` directory.
* you should put `voc_label.py` near with `VOCdevkit` directory.
```
VOCdevkit
voc_label.py
```

* Then run ` voc_label.py` 
    or on Windows `C:\Users\Alex\AppData\Local\Programs\Python\Python36\python.exe voc_label.py`

**Comment by minjuprinces1004** [comment]
thank you.
