### ISSUE TITLE
Understanding the ouput of classifier test

### ISSUE THREAD

**Issue by BeeMargarida** [AlexeyAB/darknet#3083]
Hi! 
I'm trying to compare some models that I tried with different quality of images and for that I ran `classifier test` and valid. What are the meaning of the values that appear?

For example, here is some results I got from `classifier test`:

/334_6088189.png	8.99842e-06	2.22698e-09	9.76773e-09	0.999991
/335_6088189.png	4.12883e-06	3.45621e-09	1.81184e-08	0.999996
/336_6088189.png	1.35129e-05	1.84679e-09	1.70528e-08	0.999986
/337_6088189.png	3.9155e-06	5.74634e-09	3.20875e-08	0.999996
/338_6088189.png	1.22602e-05	1.87513e-09	1.73196e-08	0.999988
/339_6088189.png	7.86686e-06	1.41854e-09	1.01614e-08	0.999992
/340_6088189.png	7.65574e-06	4.06723e-09	2.14195e-08	0.999992
/341_6088189.png	1.09586e-05	9.78416e-10	1.09295e-08	0.999989
/342_6088189.png	3.99052e-06	2.32743e-09	3.81951e-08	0.999996
/343_6088189.png	6.90794e-06	6.99193e-10	1.08795e-08	0.999993
/344_6088189.png	4.09814e-06	3.71509e-09	3.07848e-08	0.999996
/345_6088189.png	1.24336e-05	1.0375e-09	2.01228e-08	0.999988

**Comment by AlexeyAB** [comment]
@BeeMargarida Hi,

Can you show complete command?

**Comment by BeeMargarida** [comment]
./darknet classifier test cfg/removebg/product.data cfg/removebg/products.cfg backup/removebg/products_111.weights

It has 4 classes...I'm inclined to think it is probabilities for those 4 classes, but how do I know which is one?

**Comment by AlexeyAB** [comment]
Show content of your `cfg/removebg/product.data` file.

----

> It has 4 classes...I'm inclined to think it is probabilities for those 4 classes

Yes.

> , but how do I know which is one?

Just look at your `labels` file

**Comment by BeeMargarida** [comment]
Thank you!
