### ISSUE TITLE
Error when calculating mAP

### ISSUE THREAD

**Issue by nezygis** [AlexeyAB/darknet#3087]
I got this error when trying to calculate mAP after training a model. 

``` 
Loading weights from backup_scratch_full/yolov3_900.weights...
 seen 64
Done!

 calculation mAP (mean average precision)...
100
 detections_count = 6283, unique_truth_count = 131
class_id = 0, name = bline, ap = 0.23%   	 (TP = 0, FP = 0)
class_id = 1, name = (null), ap = 0.00%   	 (TP = 0, FP = 0)
class_id = 2, name = (null), ap = 0.00%   	 (TP = 0, FP = 0)
class_id = 3, name = (null), ap = 0.00%   	 (TP = 0, FP = 0)
class_id = 4, name = (null), ap = 0.00%   	 (TP = 0, FP = 0)
Segmentation fault
```

The model only has one class, maybe the problem could be related to that?

The command that I ran was:
./darknet detector map blines_scratch_full.data yolov3.cfg backup_scratch_full/yolov3_900.weights

I tried running train command with -map flag and came into the same issue. Has anyone came into this issue before? Any help will be greatly appreciated

**Comment by AlexeyAB** [comment]
You didn't set classes=1 in all 3 [yolo] layers in cfg-file.

**Comment by nezygis** [comment]
> You didn't set classes=1 in all 3 [yolo] layers in cfg-file.

@AlexeyAB thanks a lot for you response. I did that and now I get

```
Error: l.outputs == params.inputs
filters= in the [convolutional]-layer doesn't correspond to classes= or mask= in [yolo]-layer```

Could you please tell me what additional changes are needed for properly training a model with one class?

**Comment by AlexeyAB** [comment]
Read this: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

**Comment by nezygis** [comment]
> Read this: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

Thanks a lot. You're a god send for keeping this repo alive
