### ISSUE TITLE
mAP changing in very high percentages.

### ISSUE THREAD

**Issue by nezygis** [AlexeyAB/darknet#3096]
Hello, I've been having issues training yolov3 for one class model. The loss has progressively been going down but every 100 iterations mAP ranges from 10% to 30%. I would expect it to increase until model starts overtraining but it seems to be... random? Has anyone came into this issue before?

For reference I have one training class, all images are same resolution 365x798 and greyscale. I used the default configuration (yolov3.cfg) with minor edits. Changed channels to 1 and updated classes to 1. Data set contains around 800 images with 400 being images without objects and 400 with images containing 1-3 bounding boxes.

**Comment by AlexeyAB** [comment]
@nezygis Hi,

Do you use separate validation dataset?
How many images in validation dataset?

**Comment by nezygis** [comment]
> @nezygis Hi,
> 
> Do you use separate validation dataset?
> How many images in validation dataset?

I defined a file with 100 images for validation and pointed to it in the .data file. If I understand correctly that means it will be used for validation. 

`classes= 1
train  = blines_train.txt
valid  = blines_val.txt
names = blines.names
backup = backup_scratch_full`

**Comment by AlexeyAB** [comment]
* Can you show Loss & mAP chart.png?
* Can you show one image from Training dataset and on from Validation dataset?

**Comment by nezygis** [comment]
> * Can you show Loss & mAP chart.png?
> * Can you show one image from Training dataset and on from Validation dataset?

![chart](https://user-images.githubusercontent.com/13337751/57184852-adcf3d80-6eca-11e9-9601-dea6aae1923b.png)
![ID4_3_1](https://user-images.githubusercontent.com/13337751/57184853-af990100-6eca-11e9-8bca-5a0e1eeb1339.png)
![ID38_1_34](https://user-images.githubusercontent.com/13337751/57184854-b32c8800-6eca-11e9-843f-ea6a333b4824.png)


Detection is searching for lines going straight down. They're a bit difficult to spot in the first picture

**Comment by AlexeyAB** [comment]
Did you compile Darknet with OPENCV?

If you set `channels=1` then you should train without pre-trained weights-file.


Try to train with params in cfg-file:
```
width=384
height=800

channels=1

hue=0
saturation=0
exposure=1.8


# in the last yolo layer
[yolo]
jitter=0.1
random=0
```

**Comment by nezygis** [comment]
> Did you compile Darknet with OPENCV?
> 
> If you set `channels=1` then you should train without pre-trained weights-file.
> 
> Try to train with params in cfg-file:
> 
> ```
> width=384
> height=800
> 
> channels=1
> 
> hue=0
> saturation=0
> exposure=1.8
> 
> 
> # in the last yolo layer
> [yolo]
> jitter=0.1
> random=0
> ```

I did compile it with OPENCV. I tested with your suggestions and result is the same.

**Comment by AlexeyAB** [comment]
@nezygis If this is not a private data, can you give your dataset? I will try to train.

**Comment by nezygis** [comment]
> @nezygis If this is not a private data, can you give your dataset? I will try to train.

Yes, that would be great. Is there a way to contact you?

**Comment by AlexeyAB** [comment]
alexeyab84@gmail.com or just share your dataset by using GoogleDisk

**Comment by nezygis** [comment]
> [alexeyab84@gmail.com](mailto:alexeyab84@gmail.com) or just share your dataset by using GoogleDisk

Sent you an email.

**Comment by LemonRain21** [comment]
> > * Can you show Loss & mAP chart.png?
> > * Can you show one image from Training dataset and on from Validation dataset?
> 
> ![chart](https://user-images.githubusercontent.com/13337751/57184852-adcf3d80-6eca-11e9-9601-dea6aae1923b.png)
> ![ID4_3_1](https://user-images.githubusercontent.com/13337751/57184853-af990100-6eca-11e9-8bca-5a0e1eeb1339.png)
> ![ID38_1_34](https://user-images.githubusercontent.com/13337751/57184854-b32c8800-6eca-11e9-843f-ea6a333b4824.png)
> 
> Detection is searching for lines going straight down. They're a bit difficult to spot in the first picture

Can you tell me how to get Loss & mAP chart.png？thanks！

**Comment by nezygis** [comment]
> > > * Can you show Loss & mAP chart.png?
> > > * Can you show one image from Training dataset and on from Validation dataset?
> > 
> > 
> > ![chart](https://user-images.githubusercontent.com/13337751/57184852-adcf3d80-6eca-11e9-9601-dea6aae1923b.png)
> > ![ID4_3_1](https://user-images.githubusercontent.com/13337751/57184853-af990100-6eca-11e9-8bca-5a0e1eeb1339.png)
> > ![ID38_1_34](https://user-images.githubusercontent.com/13337751/57184854-b32c8800-6eca-11e9-843f-ea6a333b4824.png)
> > Detection is searching for lines going straight down. They're a bit difficult to spot in the first picture
> 
> Can you tell me how to get Loss & mAP chart.png？thanks！

I trained with -map flag using this forked repo and compiled it with OPENCV=1. Then it saves chart.png automatically in the current directory.

**Comment by AlexeyAB** [comment]
@nezygis Can you show new mAP chart with mAP ~=70%?

**Comment by nezygis** [comment]
![chart](https://user-images.githubusercontent.com/13337751/57297441-48509c00-70d8-11e9-80ef-047f64392df6.png)

Its quite ugly because my max steps are set to 500k... 

I have a new idea about the possible issue which I will test later. My dataset was created from videos for which I extracted each frame and it was labeled. The problem was that after that train and validate lists were created from random frames. So it could be that train list has one frame from a video and the validate list has the second. They are almost identical and I saw that in another issue you mentioned that when validate and train datasets overlap you might get these results. 

So I will try to recreate the lists with no overlapping and test again.

**Comment by LemonRain21** [comment]
> @nezygis Can you show new mAP chart with mAP ~=70%?

![image](https://user-images.githubusercontent.com/30193815/57345388-3f65d600-717d-11e9-9fb2-63cbe15e2e3d.png)
![image](https://user-images.githubusercontent.com/30193815/57345410-50164c00-717d-11e9-9641-e278c2ad2666.png)
I try to use vgg16.cfg as the backbone to predict objects. but i don't know hou to use. I have tried and failed in the pictures above。So，would you please show me how to use it？ thanks  a lot !

**Comment by nezygis** [comment]
> I try to use vgg16.cfg as the backbone to predict objects. but i don't know hou to use. I have tried and failed in the pictures above。So，would you please show me how to use it？ thanks a lot !

Could you please create a separate issue? This is completely unrelated. That being said the README states that you should try increasing subdivision size if you are getting out of memory error. 

https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects 

Check last note

**Comment by LemonRain21** [comment]
> > I try to use vgg16.cfg as the backbone to predict objects. but i don't know hou to use. I have tried and failed in the pictures above。So，would you please show me how to use it？ thanks a lot !
> 
> Could you please create a separate issue? This is completely unrelated. That being said the README states that you should try increasing subdivision size if you are getting out of memory error.
> 
> https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects
> 
> Check last note

That's not the problem with increasing subdivision size。I‘ll create a separate issue。I apologize for the unhappiness of this incident.

**Comment by nezygis** [comment]
Closing this because things are as good as they could be right now. Thank you for your help Alexey.

**Comment by AlexeyAB** [comment]
@nezygis 
Just can you attach the latest cfg-file that gives you such good mAP? Is it 
[yolov3-tiny.cfg.txt](https://github.com/AlexeyAB/darknet/files/3169255/yolov3-tiny.cfg.txt)

**Comment by nezygis** [comment]
> @nezygis
> Just can you attach the latest cfg-file that gives you such good mAP? Is it
> [yolov3-tiny.cfg.txt](https://github.com/AlexeyAB/darknet/files/3169255/yolov3-tiny.cfg.txt)

It was the one you sent me. That being said my mAP was a result of overfitting because my validation and training sets were too similar. After I properly split it between different videos my results were much worse. As expected..

**Comment by AlexeyAB** [comment]
@nezygis So you should increase to `jitter=0.3` and train by using more images.

**Comment by nezygis** [comment]
> @nezygis So you should increase to `jitter=0.3` and train by using more images.

I will try that today, thanks.
