### ISSUE TITLE
After training for a period of time, stop training, modify the cfg file yolo-obj.cfg

### ISSUE THREAD

**Issue by VonSdite** [AlexeyAB/darknet#3100]
Is it OK? After training for a period of time, stop training, modify the cfg file `yolo-obj.cfg`

And retrain the model:
```
darknet.exe detector test data/obj.data yolo-obj.cfg yolo-obj_8000.weights
```

**Comment by VonSdite** [comment]
I just want to improve the maP of  the trained model..

**Comment by VonSdite** [comment]
for example, I change the `width=416` to `width=608` and `height=416` to `height=608`.
Is it OK ?

**Comment by VonSdite** [comment]
Should I need to retrain the model?

**Comment by AlexeyAB** [comment]
> for example, I change the width=416 to width=608 and height=416 to height=608.
> Is it OK ?

It is OK, you can continue training
`darknet.exe detector train data/obj.data yolo-obj.cfg yolo-obj_8000.weights`

**Comment by VonSdite** [comment]
OK，thank you
