### ISSUE TITLE
For training with mAP (mean average precisions) calculation problem

### ISSUE THREAD

**Issue by ldhai** [AlexeyAB/darknet#3101]
Hi,
![image](https://user-images.githubusercontent.com/9911239/57187379-388e5780-6f20-11e9-92f8-94cdb97c26a9.png)
someone can tell me how to fix this problem.
my train is:   ./darknet detector train cfg/rpc.data cfg/rpc-voc.cfg darknet53.conv.74 -map -gpus 0,1 2>1 | tee train_yolov3.log
Software suddenly stops while training.

but I can successfully do the command: 
./darknet detector map cfg/rpc.data cfg/rpc-voc.cfg backup/rpc-voc_6000.weights

**Comment by ldhai** [comment]
my environment : cuda-8.0  ; cudnn 5.1;
![image](https://user-images.githubusercontent.com/9911239/57188809-210e9900-6f37-11e9-91cd-f1839623930e.png)

**Comment by AlexeyAB** [comment]
@ldhai Hi,

Does it successfully work for 1 GPU?
`./darknet detector train cfg/rpc.data cfg/rpc-voc.cfg darknet53.conv.74 -map -gpus 0 2>1 | tee train_yolov3.log`

**Comment by ldhai** [comment]
No. The training was fine. But to calculate the map, the errors occur.

**Comment by AlexeyAB** [comment]
Can you attach your cfg-file?
What GPU do you use?
Try to use CUDA 10.0 and cuDNN 7.x

**Comment by ldhai** [comment]
my map result : [tt.txt](https://github.com/AlexeyAB/darknet/files/3145538/tt.txt)

cfg-file : [rpc-voc.cfg.txt](https://github.com/AlexeyAB/darknet/files/3145539/rpc-voc.cfg.txt)

GPU: GeForce GTX TITAN X

I use a lab server and can't just change the environment。Hopefully there are other solutions

**Comment by AlexeyAB** [comment]
Try to set `random=0` in the last `[yolo]` layer in cfg-file, and train with `-map` flag, does it work?

**Comment by ldhai** [comment]
Thank you.  I try to set `random=0` in the last `[yolo]` layer in cfg-file, and train with `-map` flag, but it doesn't work. And I borrowed someone else's server, his environment is `cuda: 8.0` and `cudnn: 7.1.3`.  The error didn't happen again, so the reason may be cudnn version problem.

**Comment by AlexeyAB** [comment]
Yes, it seems an issue is in old cuDNN.
