### ISSUE TITLE
mAP is low. 

### ISSUE THREAD

**Issue by R06921096Yen** [AlexeyAB/darknet#3103]
Hi,@AlexeyAB
I've been training for few hours, and I got low loss but low mAP(42%)

Here is my mAP after train for 4000 iterations.
![image](https://user-images.githubusercontent.com/37581765/57204092-db5dd900-6fe7-11e9-817b-f457a119b199.png)

During the last part of training, I still got lots of -nan.
Not sure if the problem is come from here??
![image](https://user-images.githubusercontent.com/37581765/57204111-0ea06800-6fe8-11e9-9bc1-bf967b2a1e8f.png)

![image](https://user-images.githubusercontent.com/37581765/57203892-3e4e7080-6fe6-11e9-8d87-fa48fb35f905.png)

Appreciate for any help!

**Comment by R06921096Yen** [comment]
I've already solve the problem mAP is too low 
but I still got lots of -nan after 4000 iterations
Thanks!

**Comment by AlexeyAB** [comment]
@R06921096Yen Hi,

> I've already solve the problem mAP is too low

It is just because you don't have any training images with class=wall. So actually your mAP=84% that is good.

> but I still got lots of -nan after 4000 iterations

It is normal: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

> Note: If during training you see nan values for avg (loss) field - then training goes wrong, but if nan is in some other lines - then training goes well.

**Comment by R06921096Yen** [comment]
OK! Thanks!
I also recalculate the anchors, and it got better!
![image](https://user-images.githubusercontent.com/37581765/57273396-323bdf00-70ca-11e9-8551-90ab860420c6.png)

**Comment by SHADOWMOOON** [comment]
> I've already solve the problem mAP is too low

@R06921096Yen Hi.
Could you tell me How did you solve the low mAP problem? Any ideas?

**Comment by SHADOWMOOON** [comment]
> > I've already solve the problem mAP is too low
> 
> @R06921096Yen Hi.
> Could you tell me How did you solve the low mAP problem? Any ideas?
looking forward to your reply!

**Comment by R06921096** [comment]
> > I've already solve the problem mAP is too low
> 
> @R06921096Yen Hi.
> Could you tell me How did you solve the low mAP problem? Any ideas?
> looking forward to your reply.

If your problem is like mine, you can try to recalculate the anchors in this repo. 
By this line -->
![image](https://user-images.githubusercontent.com/37615975/58384038-c802c400-800f-11e9-9ced-c7f3c23cb8a0.png)

Then modify your .cfg file with this anchors.
After it's done , I train my own object with pretrain model

**Comment by mey1k** [comment]
i think labeling is important regarding the issue
