### ISSUE TITLE
How to print TP/FP/TN per class in mAP calculation?

### ISSUE THREAD

**Issue by jisheng047** [AlexeyAB/darknet#3108]
Hi Alex, i have been seen a lot of question that related to this issues but no answer. I tried to print TP/FP/TN per class to output mAP calculation but everything is so complicated for me and i am not familiar with C. What is rank in pr[class_id][rank]? 
Thanks you

**Comment by joehoeller** [comment]
Did you get an answer for this?

**Comment by jisheng047** [comment]
@joehoeller I don't get any answer to this issue, but i have written code in this source to solve this problem.
