### ISSUE TITLE
darknet_video.py

### ISSUE THREAD

**Issue by cyrineee** [AlexeyAB/darknet#3124]

**Comment by cyrineee** [comment]
Can i use darknet_video.py to test the model i trained with darknet(.c) in this repo ?

**Comment by Mghobadid** [comment]
> Can i use darknet_video.py to test the model i trained with darknet(.c) in this repo ?

yes

**Comment by cyrineee** [comment]
is there any changes to do , i want to test it with my own video ?

**Comment by cyrineee** [comment]
because when i change all the paths to my own files : i have this error 
OSError : ./libdarknet.so : cannot open shared object files : No such file or directory

**Comment by mufaddal12** [comment]
> because when i change all the paths to my own files : i have this error
> OSError : ./libdarknet.so : cannot open shared object files : No such file or directory

please tell me how to solve that problem coz it seems you have solved that issue
