### ISSUE TITLE
The predictions are not as good as opencv and pjreddie/darknet

### ISSUE THREAD

**Issue by xinsuinizhuan** [AlexeyAB/darknet#3134]
I use your darknet to train, then use to prediction，but i find the predictions is 15， but i use your darknet tarin result .cfg and weight and use opencv or pjreddie/darknet to predict, the predictions id 22, and 22 is right.,15 is leak detection.

**Comment by AlexeyAB** [comment]
Can you show example of image with detections?

**Comment by xinsuinizhuan** [comment]
![darknet](https://user-images.githubusercontent.com/40679769/58064126-827b6c80-7bb3-11e9-9e7e-825678bbdda5.jpg)
![opencv](https://user-images.githubusercontent.com/40679769/58064128-83140300-7bb3-11e9-9fb0-159a1827b4c6.jpg)
I user coco.names,yolov3.cfg and yolov3.weights to recogine the same picture,but the opencv-dnn is better then your darknet。

**Comment by xinsuinizhuan** [comment]
your darknet the truck is recognise two, and not recognise the ber

**Comment by xinsuinizhuan** [comment]
as same as this，I use the same with pjreddie/darknet, the accuracy is as good as opencv-dnn.

**Comment by AlexeyAB** [comment]
1. Download the latest version of Darknet.

2. Run detection with flag ` -letter_box`
`./darknet detector test cfg/coco.data yolov3.cfg yolov3.weights dog.jpg -letter_box`

**Comment by xinsuinizhuan** [comment]
Hello， this is my model，I use same model to detecte picture, but the result is not good. yolo is not good as opencv-dnn。






At 2019-05-22 04:49:48, "Alexey" <notifications@github.com> wrote:


Download the latest version of Darknet.

Run detection with flag -letter_box
./darknet detector test cfg/coco.data yolov3.cfg yolov3.weights dog.jpg -letter_box

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

从网易163邮箱发来的云附件
Detection of contrast.rar (34.09M, 2019年6月6日 11:36 到期)
下载

**Comment by AlexeyAB** [comment]
Don't duplicate issues: https://github.com/AlexeyAB/darknet/issues/3199#issuecomment-494631729


Why didn't you do?
`./darknet detector test cfg/coco.data yolov3.cfg yolov3.weights dog.jpg -letter_box`
