### ISSUE TITLE
Detect only part of classes of objects

### ISSUE THREAD

**Issue by fanfancy** [AlexeyAB/darknet#3135]
Hello, I am training yolov2 tiny on KITTI dataset, which contains 8 classes. 
In the readme ,@AlexeyAB says "check that each object is mandatory labeled in your dataset - no one object in your data set should not be without label. " 
I only need detect three classes of them. I am confused that should I keep all annotations of the 8 classes to train the network, or I only keep annotations of 3 classes？
Thanks a lot.

**Comment by AlexeyAB** [comment]
@fanfancy Hi,

You should keep annotations only for 3 classes (only for objects that you want to detect).

I will fix readme.

**Comment by fanfancy** [comment]
Thanks.
