### ISSUE TITLE
How to realize MobileNet in Darknet?

### ISSUE THREAD

**Issue by ChenCong7375** [AlexeyAB/darknet#3136]
How should I add depthwise separable convolutions in darknet?

**Comment by xujunjie96** [comment]
+1

**Comment by PhilipWu526** [comment]
@AlexeyAB  please help us :cry:

**Comment by MichaelCong** [comment]
+1

**Comment by AlexeyAB** [comment]
@ChenCong7375 @xujunjie96 @MichaelCong 

There is already grouped-convolutional and it supports MobileNet v2: #1730

You can train this cfg file https://github.com/AlexeyAB/darknet/files/3310574/mobilenet_v2.cfg.txt 

EfficientNet: https://github.com/AlexeyAB/darknet/issues/3380
MobileNet: https://github.com/AlexeyAB/darknet/issues/3453
