### ISSUE TITLE
Testing on a list of videos/images

### ISSUE THREAD

**Issue by nezygis** [AlexeyAB/darknet#3145]
Hello, 

is there a way to test on a list of videos? I am interested in getting the max amount of objects found in one video. What would be the easiest way to do that? 

I could also work with just a list of images by writing some scripts around that. Is it possible to test a list of images at the same time, get output BB for all of them and then save to file? 

Thanks in advance

**Comment by AlexeyAB** [comment]
@nezygis Hi,

If you have list of images `data/train.txt` then run this command:

`./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights -dont_show -ext_output -out result.json < data/train.txt > result.txt`

Then you will get 2 files with results in 2 different formats:
1. `result.txt` - text result
2. `result.json` - JSON result

----

If you have one Video:
`./darknet detector demo  cfg/coco.data cfg/yolov3.cfg yolov3.weights -ext_output -out_filename result.avi video.mp4 > result.txt`

You will get:
1. `result.txt` - text result
2. `result.avi` - video-file result


Other commands: https://github.com/AlexeyAB/darknet#how-to-use-on-the-command-line

**Comment by nezygis** [comment]
@AlexeyAB thanks. is it possible to remove the output from loading the cfg and weights? I wrote a bash script that does what I wanted but I wanted to print the progress to std and its difficult to track with all the information that is being outputted.

**Comment by AlexeyAB** [comment]
Try to use something like this:

`./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights -dont_show -ext_output -out result.json < data/train.txt > result.txt 2>trash.txt`

**Comment by yuyifan1991** [comment]
@AlexeyAB How can I  get the output BB for all images and them save to the file? And now I just get the .txt file.
