### ISSUE TITLE
Slow speeds on Window

### ISSUE THREAD

**Issue by Dvdhyh** [AlexeyAB/darknet#317]
I am getting slow speeds on Window 10.

I saw advice you mentioned on another post
https://github.com/pjreddie/darknet/issues/80

He used Video 1980*1080 .mp4 
darknet detector demo cfg/coco.data cfg/yolo.cfg yolo.weights test.mp4
He got 3fps
I mimic'ed his video choice and settings

You recommended
Video 960*540
cfg width and height  288*288 and use tiny
darknet detector demo cfg/coco.data cfg/tiny-yolo.cfg tiny-yolo.weights test.mp4

They were using 
Environment
Ubuntu 16.04
CUDA Version 8.0.61
OpenCV 3.2
GPU: GeForce 840M (2GB)
Driver: NVIDIA 375.66

He started at 3 fps and got up to ~25

My setup is:
Environment
Windows 10
CUDA Version 9.1
OpenCV 3.3.1
GPU: GeForce 980M (4GB)
Driver: NVIDIA 388.59

Went from 1fps up to 3fps after your recommendation

I thought Window port would be slower, but this is it bit much.
Not using Cudnn. I can't get it to compile with cudnn

Wasn't sure if this was how fast it's suppose to be on Windows

**Comment by AlexeyAB** [comment]
* Windows port faster then original repo, especially for high resolution video
* He got 25 fps using Tiny-Yolo instead of Yolo and with `width=288 height=288` in the cfg-file, by command: `./darknet detector demo cfg/coco.data cfg/tiny-yolo.cfg tiny-yolo.weights` 
* How many fps can you get using Tiny-yolo 288x288 on Windows?
* How many fps can you get using Tiny-yolo 288x288 on Linux using origina repo https://github.com/pjreddie/darknet ?

**Comment by Dvdhyh** [comment]
I was getting 1fps without tiny
Then I was getting 3fps using Tiny-yolo 288x288 on Windows
I don't have Linux system to test on
The video I used was
https://videos.pexels.com/videos/video-of-people-walking-2326, I used a few
tv shows as well (Still 1 fps)
I used a video editor to convert it down to 940*540

**Comment by AlexeyAB** [comment]
So:
* you get 1 fps using `darknet.exe detector demo data/coco.data yolo.cfg yolo.weights 708213662.mp4`
* you get 3 fps using `darknet.exe detector demo data/coco.data tiny-yolo.cfg tiny-yolo.weights 708213662.mp4`

----

I have nVidia GeForce 970 (3494 Gflops): https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units#GeForce_900_series
that **olny 9% faster** than your nVidia GeForce GTX 980M (3189 Gflops): https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units#GeForce_900M_(9xxM)_series

Right now I compiled `build\darknet\darknet.sln` using CUDA 8.0 and OpenCV 3.2.0, **without cuDNN**:

* I get 33 fps using `darknet.exe detector demo data/coco.data yolo.cfg yolo.weights 708213662.mp4`
* I get 50-100 fps using `darknet.exe detector demo data/coco.data tiny-yolo.cfg tiny-yolo.weights 708213662.mp4`

Those. you are doing something wrong.

**Comment by Dvdhyh** [comment]
My GPU remains "inactive" when I run darknet.exe in cmd. Which is why it's slow 

I downloaded repo .zip
Extracted it to my desktop

I am creating my own new project with VS,
Then jump straight to "How to compile (custom):" section and follow each step
 
My guess is there was an extra step I was suppose to do?
(Note. I have compiled cuda example on their site so I know it's installed properly and working. I can see my gpu turn active when I run .exe from example)

**Comment by Dvdhyh** [comment]
I need to c++ preprocessor add GPU (Also CUDNN if you want cudnn)
