### ISSUE TITLE
Setting IOU threshold?

### ISSUE THREAD

**Issue by rtrahms** [AlexeyAB/darknet#3180]
How does one actually set the IOU threshold for mAP calculation in YOLO?  Is it one of the parameters in the cfg, or a map parameter?
Thanks,
Rob

**Comment by AlexeyAB** [comment]
It is mAP parameter.
Just use `-iou_thresh 0.3` in the command: https://github.com/AlexeyAB/darknet#how-to-use-on-the-command-line
To check accuracy mAP@IoU=75: `darknet.exe detector map data/obj.data yolo-obj.cfg backup\yolo-obj_7000.weights -iou_thresh 0.75`

**Comment by rtrahms** [comment]
Perfect!  Thanks again.
Rob
