### ISSUE TITLE
Can't generate libdarknet.so

### ISSUE THREAD

**Issue by syedmustafa54** [AlexeyAB/darknet#3183]
Hello @AlexeyAB  i tried your way to generate `libdarknet.so` as you mention in this  [issue](https://github.com/AlexeyAB/darknet/issues/2727#issuecomment-476410989) but there is no file `CMakeCache.txt` so i have deleted the binary file of darknet and remake it but still did not find libdarknet.so what i am doing wrong

**Comment by AlexeyAB** [comment]
@syedmustafa54 Hi,


What do you mean? it is here: https://github.com/AlexeyAB/darknet/blob/master/CMakeLists.txt

just do
```
cmake .
make
```

**Comment by syedmustafa54** [comment]
@AlexeyAB than for the relpy,
 I am on ubuntu 16 need libdarknet.so this file to run python script but after make command the file is not present in dir so search on issues found that you have said  Try to change `add_library(darklib` to `add_library(darklib SHARED`  even i tried that but still did not got the libdarknet.so file

**Comment by syedmustafa54** [comment]
I tried `cmake .` and `make` now i am getting errors 
```[  0%] Building CUDA object CMakeFiles/darklib.dir/src/activation_kernels.cu.o
nvcc fatal   : Unknown option 'fopenmp'
CMakeFiles/darklib.dir/build.make:1646: recipe for target 'CMakeFiles/darklib.dir/src/activation_kernels.cu.o' failed
make[2]: *** [CMakeFiles/darklib.dir/src/activation_kernels.cu.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/darklib.dir/all' failed
make[1]: *** [CMakeFiles/darklib.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2```

**Comment by AlexeyAB** [comment]
Download the latest version of Darknet? https://github.com/AlexeyAB/darknet/archive/master.zip

Then set GPU=1 CUDNN=1 OPENCV= LIBSO=1 in the Makefile
and do
`make`

**Comment by syedmustafa54** [comment]
thanks again its working
