### ISSUE TITLE
Improve detection with adding misdetection examples 

### ISSUE THREAD

**Issue by cyrineee** [AlexeyAB/darknet#3200]
I want to enhance the detection of yolov3 with adding some correct labels to the images that was misdetected or detected wrong while testing the model .
 My question is that should i train from scratch with the addition of these images or should i train with the previous weights and a new txt file for train(which contain only the images that were misdetected ) with maintaining same validation data ?
Thanks in advance .

**Comment by AlexeyAB** [comment]
It's better to continue training with previous weights and train.txt that contains old+new labeled images.

**Comment by cyrineee** [comment]
@AlexeyAB  okay thanks .
