### ISSUE TITLE
Using YoloV3-Tiny with 8-bit input images (instead of 24-bit)

### ISSUE THREAD

**Issue by rtrahms** [AlexeyAB/darknet#3203]
Hi!
Great work on latest version of darknet - works great for us!  We've trained YoloV3-Tiny on image samples that are 24-bit with great results, but realized we only need grayscale images, so are interested in the potential performance boost that an 8-bit (1-channel) version of Yolo would offer.  The CFG file specifies channels=3 by default, is there anything else we would need to modify besides this to use 8-bit images?  (We'll be converting our JPGs to 8-bit as well).
Thanks!
Rob

**Comment by AlexeyAB** [comment]
@rtrahms Hi,

Just set `channels=1` in the cfg-file.
So the input layer will have 1 channel - it will work faster.

Then you can train and detect by using any RGB-24-bit or GrayScale-8-bit images.

**Comment by rtrahms** [comment]
Thanks!  We'll try that.
Rob
