### ISSUE TITLE
Couldn't open file: backup//yolo-obj_last.weights

### ISSUE THREAD

**Issue by ztyMCR** [AlexeyAB/darknet#3209]
Hi,
I got this error "Couldn't open file: backup//yolo-obj_last.weights" at the end of the 100 iteration of training. 
I was training my custom object of only one class. 

The output is:
![QQ截图20190522172717](https://user-images.githubusercontent.com/35747047/58163626-e470ca80-7cb6-11e9-8358-f46aabc2d500.png)

Very grateful to your work and hope you can help me with this.

Thanks

**Comment by ztyMCR** [comment]
BTW, I ran on Ubuntu and I use the command : ./darknet detector train data/obj.data yolo-obj.cfg darknet53.conv.74

**Comment by AlexeyAB** [comment]
* Do you have `/backup/` folder in your darknet folder?

* Do you have file-write permissions?

**Comment by ztyMCR** [comment]
> * Do you have `/backup/` folder in your darknet folder?
> * Do you have file-write permissions?

Hi, It's the permission thing. I figured it out. Thanks!

**Comment by SHADOWMOOON** [comment]
@ztyMCR HI!
How did you fix the problem? I am facing it too.
Thanks in advance.

**Comment by silviasanna** [comment]
Hi, how can I change file-write permission?
Once i tried training but I had the same problem, I've created the folder backup, put the correctly path in the obj.data file and just in the first iteration it made me the .weights file. For some errors I had to retrained so I've deleted the .weights file, made another backup directory but I haven't the file. What is the problem? Thanks
