### ISSUE TITLE
why this version of darknet couldn't support GPU with compute capability 2.1

### ISSUE THREAD

**Issue by robosina** [AlexeyAB/darknet#321]
Hello,
I'm using this fork of darknet,which seems faster for training and testing, but I want to compile darknet with CUDA but in the output I see below error

    nvcc fatal   : Unsupported gpu architecture 'compute_21'

I know this compute capability will be deprecated in future, but I need to run it in my system, so I test the source of darknet with cuda [via this link ](https://github.com/pjreddie/darknet/blob/master/Makefile)and seems that it's okay with c.c=2.1

my question: how it is possible one source accept c.c=2.1 and another don't. your fork has better performance but why don't support c.c=2.1? Is there anyway to handle with this source and c.c=2.1?

Thanks for your project and Help

**Comment by AlexeyAB** [comment]
Hi,
* Did you want to compile this frok on Windows or Linux?
* What CUDA version do you use for original repo on Linux, and for this fork?

---- 

> nvcc fatal   : Unsupported gpu architecture 'compute_21'

* Did get this error while try to compile this fork on Linux with modified Makefile? - changed line ot this: `ARCH= -gencode arch=compute_21,code=sm_21 \` https://github.com/AlexeyAB/darknet/blob/ee87f4b649115e5aaed2f08450ab57eae5870913/Makefile#L8

**Comment by robosina** [comment]
thanks for your reply

compile on Linux ubuntu-16.04.3
my nvcc output is 

    nvcc --version

    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2016 NVIDIA Corporation
    Built on Sun_Sep__4_22:14:01_CDT_2016 
    Cuda compilation tools, release 8.0, V8.0.44

and I changed architecture in MAKEFILE but this fork doesn't work but for source it's working if you want I can attach output of compile of them.

**Comment by robosina** [comment]
sorry, I can't say anything because I waste your valuable time
I see my graphic c.c=2.1 in `nvidia-site` so I put `arch=compute_21` in my `MAKEFILE` but when I set it to 20 it's compile properly
