### ISSUE TITLE
How to argue for better performance with fewer classes?

### ISSUE THREAD

**Issue by jonasmuriboe** [AlexeyAB/darknet#3212]
I currently achieve extremely high results on object detection of a single class when using yolov3.cfg, mAP@50 of >99. Why is it that it performs so much better on a single class as opposed to the results shown in YOLOv3 paper of 57.9? Is it simply due to the fact that there are less features to learn and look for when only using a single class? 

I have 500 images for training (50:50 split with and without occurences), and 344 for validation. Images are technically from a data series taken within 2 seconds of each other, and I know that this likely affects my mAP@50 positively.

**Comment by AlexeyAB** [comment]
> Is it simply due to the fact that there are less features to learn and look for when only using a single class?

This is the 1st reason.

The 2nd is because (if you train for 1 class) then Yolo can't confuse the class_id.

The 3rd - mAP is an average value of APs, so may be for this class was AP ~= 99% too. 

* What is the class?
* And what AP for this class did you get when you trained the model for many classes?

**Comment by jonasmuriboe** [comment]
I have sheep as a superclass, and [white, black, brown] as subclasses. The superclass achieved a top score or 99 mAP@50, and the subclasses 93.2. There is a substantial difference in class distribution, 82%, 13% and 5% respectively and I assume this is the main culprit

**Comment by AlexeyAB** [comment]
Do you use multilabel training for 4 classes [sheep, white, black, brown]?

**Comment by jonasmuriboe** [comment]
No, two different sets of labels for two different configurations, one with one class, sheep, and one with three classes, white, black and brown.

**Comment by AlexeyAB** [comment]
Also if you want to distinguish colors, you should decrease `hue= `, and set `saturation=` closer to `1` in cfg-file.

**Comment by jonasmuriboe** [comment]
I really appreciate the help, thanks.
