### ISSUE TITLE
Dark label when testing images

### ISSUE THREAD

**Issue by hhn1n15** [AlexeyAB/darknet#3214]
Hello, 

After I finish training, I use the network to test on an image. The trained network works fine however, on the prediction image, all labels are dark. 

Can you help me solve this? Thanks

![predictions](https://user-images.githubusercontent.com/32955308/58218745-f7869900-7cbc-11e9-85eb-70f4bdebe1b9.jpg)

**Comment by AlexeyAB** [comment]
@hhn1n15 Hi,

You deleted this folder: https://github.com/AlexeyAB/darknet/tree/master/data/labels
Download it again.
