### ISSUE TITLE
learning parameters

### ISSUE THREAD

**Issue by minjuprinces1004** [AlexeyAB/darknet#322]
![learning](https://user-images.githubusercontent.com/30395809/34358188-cf5eda42-ea90-11e7-832d-36e4e95b1bc0.png)

i don't know anything, so i always ask questions.
the attached file is a log message of the parameters in the learning of the VOC data.
at 20,000 iteration avg recall is between 0.84 and 1.0. 

but, if i check using the command: darknet detector recall data/voc.data yolo-voc.2.0.cfg d:\Darknet\voc2.0\yolo-voc_20000.weights
RPs/Img = 3.11, IOU = 63.46, Recall = 76.22

the Recall value appears to be too low. 
is this right? if its'wrong, why is this happening?

the below is voc.data
===================================================================
classes= 20
train  = data/voc/train.txt
valid  = data/voc/2007_test.txt
names = data/voc.names
backup = D:\Darknet\voc2.0\
===================================================================

thank you.

**Comment by AlexeyAB** [comment]
@minjuprinces1004 

* `darknet detector train...` uses `train = data/voc/train.txt`, when `darknet detector recall...` uses `valid = data/voc/2007_test.txt` correspond to your `voc.data` file. So on training dataset it usually gives you better result than on validation/test-datasets, according to this image: https://github.com/AlexeyAB/darknet#when-should-i-stop-training
![68747470733a2f2f6873746f2e6f72672f66696c65732f3564632f3761652f3766612f35646337616537666164396434653365623361343834633538626663316666352e706e67](https://user-images.githubusercontent.com/4096485/34358888-84311ce6-ea64-11e7-89f0-f31430210745.png)
Validation has higher error and lower Recall, IoU, mAP.

Also, this parameter is calculated slightly differently during training and recall-validation.

**Comment by minjuprinces1004** [comment]
thank you alexy.

the attached results were obtained using darknet detector recall...
so, is this right? is the Recall vlaue not too low?

![parameter](https://user-images.githubusercontent.com/30395809/34359128-a1e9efe0-ea98-11e7-998c-8fc97ef12b06.png)

**Comment by AlexeyAB** [comment]
No, Recall isn't too low, but better to see on IoU.

**Comment by minjuprinces1004** [comment]
okay, alexy.

sincerely thank you for your answer.
