### ISSUE TITLE
cuDNN Error: CUDNN_STATUS_BAD_PARAM: File exists

### ISSUE THREAD

**Issue by sudharavali** [AlexeyAB/darknet#3226]
Hello @AlexeyAB,

My code trains well when I set only GPU =1, but after I set openCV =1 and use the commands cmake . and make, the build is 100% successful but when I give a command to train I get the following error :

cuDNN status Error in: file: /home/sudharavali/darknetalex/darknet/src/convolutional_layer.c : () : line: 295 : build time: May 24 2019 - 13:01:10
cuDNN Error: CUDNN_STATUS_BAD_PARAM
cuDNN Error: CUDNN_STATUS_BAD_PARAM: File exists
darknet: /home/sudharavali/darknetalex/darknet/src/utils.c:293: void error(const char*): Assertion `0' failed.
Aborted (core dumped)

Aborted (core dumped)I used opencv 3.4 using pip install.  
Please let me know how to overcome this error. Is there anyway to get loss curves pictures/graphs or chart.png without setting opencv=1 ?
Please let me know .
thanks in advance !

**Comment by AlexeyAB** [comment]
If you set GPU=1 or/and OPENCV=1 then you should use just `make` instead of `cmake .  & make`

**Comment by sudharavali** [comment]
I just tried that and I got this error : 


chmod +x *.sh
g++ -std=c++11 -Iinclude/ -I3rdparty/stb/include -DOPENCV `pkg-config --cflags opencv` -DGPU -I/usr/local/cuda-9.2/include/ -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -DGPU -c ./src/image_opencv.cpp -o obj/image_opencv.o
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
./src/image_opencv.cpp:14:36: fatal error: opencv2/core/version.hpp: No such file or directory
compilation terminated.
Makefile:149: recipe for target 'obj/image_opencv.o' failed
make: *** [obj/image_opencv.o] Error 1 


Please let me know what to do.

**Comment by AlexeyAB** [comment]
> I used opencv 3.4 using pip install.

Try to install OpenCV from source: https://github.com/opencv/opencv/archive/4.1.0.zip

```
cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..
make -j7
sudo make install
```

or read: https://docs.opencv.org/3.3.0/d7/d9f/tutorial_linux_install.html

**Comment by sudharavali** [comment]
Thanks alot I will try that !
