### ISSUE TITLE
differences in confidence between this fork and pjreddie

### ISSUE THREAD

**Issue by rxjx** [AlexeyAB/darknet#3227]
If I use weights trained from the original pjreddie repo and detect with that repo as well as this one, I get very different confidence values. I would like to understand why this happens. I tried re-compiling with CUDNN_HALF = 0 but saw barely any changes. Both repos are running on an AWS p3.x2large. The numbers are like this (pjreddie vs alexeyab):

92% vs 81%
99% vs 75%
98% vs 88%.

I can upload the weights and the images if you'd like. All the other files, cfg, data are exactly the same.

**Comment by AlexeyAB** [comment]
try to use flag `-letter_box` in the command for this repo.

**Comment by rxjx** [comment]
Had to pull to update from 099b71d..3aca0b7. Compiling fails with:

obj/network.o: In function `free_network_recurrent_state':
network.c:(.text+0x456e): undefined reference to `free_state_conv_lstm'
obj/network.o: In function `randomize_network_recurrent_state':
network.c:(.text+0x461e): undefined reference to `randomize_state_conv_lstm'
obj/network.o: In function `remember_network_recurrent_state':
network.c:(.text+0x46ce): undefined reference to `remember_state_conv_lstm'
obj/network.o: In function `restore_network_recurrent_state':
network.c:(.text+0x474e): undefined reference to `restore_state_conv_lstm'
obj/parser.o: In function `parse_conv_lstm':
parser.c:(.text+0xf1c): undefined reference to `make_conv_lstm_layer'
collect2: error: ld returned 1 exit status
Makefile:143: recipe for target 'darknet' failed
make: *** [darknet] Error 1

even after a 'make clean'. Didn't find anything in issues for that so I'm looking into it. Will keep you posted...

**Comment by AlexeyAB** [comment]
Download the latest version of Darknet to another folder. Do the clean installation.

**Comment by rxjx** [comment]
I was using my old Makefile instead of the new one. Fixing that resolved the compilation errors. And -letter_box accounted for the discrepancy, exactly as you suggested. Thank you for the excellent support!

**Comment by rxjx** [comment]
I would suggest adding this to the Readme.
