### ISSUE TITLE
Error: Floating point exception (core dumped)

### ISSUE THREAD

**Issue by hardik22317** [AlexeyAB/darknet#3231]
I am getting an issue of floating point exception. I have tried to debug the code and what I found is the file "parser.c", there is one function "load_weights_upto", in that I am getting this error near fflush(stdout) statement.

**Comment by AlexeyAB** [comment]
What params do you use in the Makefile?
What command do you use and can you show a screenshot?

**Comment by hardik22317** [comment]
![Screenshot from 2019-05-25 17-27-15](https://user-images.githubusercontent.com/22682878/58369021-6f013600-7f12-11e9-8c46-bcf4103281d5.png)
I have use yolov2-tiny-voc.cfg, voc.names and yolov2-tiny.weights.

Actually, it is running well and good on my machine, but when I am testing on the Amazon aws ec2 instance, it shows floating point exception (core dumped) error, after loading weights near "fflush(stdout)" line. If I am dragging this "fflush(stdout)" line below, then my error also shifts below. I have built an app which uses libdarknet.so and for calling libdarknet.so file, I have written CMakeLists.txt file and run my application through cmake.

**Comment by AlexeyAB** [comment]
> Actually, it is running well and good on my machine,

* What OS do you use on your machine?
* Do you build `libdarknet.so` on the Amazon EC2 server or do you upload compiled `libdarknet.so` file?
* Do you have the same CUDA, cuDNN and OpenCV on EC2?
* What AMI do you use on EC2?
* Can you successfully run `./darknet detector test` ... on the EC2?
