### ISSUE TITLE
different bflops for same model and config

### ISSUE THREAD

**Issue by sruteesh-pivot** [AlexeyAB/darknet#3232]
Hi,
I am trying to use the default yolov3.weights and yolov3.cfg. I came across this strange observation of different bflops and hence different fps while running object detection using `darknet_video.py`

When i run `darknet_video.py` from the root folder `./darknet` i get `fps=13 bflops = 65` on `k80 tesla gpu` after compiling with `CuDNN=1 OPENCV=1 OPENMP=1 LIBSO=1`
But when i run the same `darknet_video.py` from a different folder i get `fps=7 bflops = 140`. I have copied the `libdarknet.so` and `darknet.py` to this folder.
 
I haven't made any changes to the file. Also the memory occupied is more when running from different folder other than the root folder. Any ideas why this is happening.
Thanks.

**Comment by AlexeyAB** [comment]
@sruteesh-pivot Hi,

May be it uses different cfg-files with different width= and height=, or even different models yolov3 / yolov3-spp?

Check that it uses absolutely the same cfg-file.

**Comment by sruteesh-pivot** [comment]
@AlexeyAB 
Found the issue. The height and width were different even though the filenames were same.
Thanks.
