### ISSUE TITLE
Regarding precision recall curves

### ISSUE THREAD

**Issue by sudharavali** [AlexeyAB/darknet#3236]
Hi @AlexeyAB, 

Can you tell me a way to collect data and calculate precision-recall graphs from the log files without having to use openCV ? Please let me know where I can obtain the required data. It will be of alot of help. 

Thanks in advance.

**Comment by AlexeyAB** [comment]
un-comment this line: https://github.com/AlexeyAB/darknet/blob/3aca0b71666bac0dd5760833aea036e7bd897c8a/src/detector.c#L1032

recompile
`make`


Run command:
`./darknet detector map data/obj.data yolo-obj.cfg backup\yolo-obj_7000.weights -points 11`

You will see 11 points of Precision-Recall for each class.
