### ISSUE TITLE
it's weird !  cannot load image "data/xxx.jpg"

### ISSUE THREAD

**Issue by goodtogood** [AlexeyAB/darknet#325]
Hi, there

firstly I trained darknet on local windows PC, all works well.
now I want to resume training on Amazon,  after modified all related config

I came accross this problem when running the commad below, 

> ./darknet detector train data/person.data ./yolo-person.cfg  ./yolo-person.weights

![train](https://user-images.githubusercontent.com/10088733/34404225-912d110a-ebe7-11e7-80b5-358cf871744b.png)

current directory is  **/root/syt/dn**  
directory tree 

> cfg
> data
>------backup
>------person
>------person.data
>------2007_train.txt
>------2007_val.txt 
> darknet
>darknet.so  
> yolo-person.cfg
> yolo-person.weights

content of  person.data

> classes= 1
> train  = data/2007_train.txt
> valid  = data/2007_val.txt
> names = data/person.names
> backup = data/backup/

I checked  permission of directories and files

![py](https://user-images.githubusercontent.com/10088733/34404234-9d1f60f8-ebe7-11e7-95ad-7656350bcb14.png)

and I checked again using python

> 
> import cv2
> import os
> file_name = 'data/person/15_09_40_17713.jpg'
> img = cv2.imread(file_name)
> print (file_name)
> print ('exist ',os.path.exists(file_name))
> print ('img shape',img.shape)

the result after running 

![py](https://user-images.githubusercontent.com/10088733/34403775-4e3baf02-ebe5-11e7-8b57-018c29852a5d.png)

so permisson is ok.
and I tried this fork and [original fork ](https://github.com/pjreddie/darknet) 
and I also tried absolute path in person.data
but finally got same error .

please help me , thanks!

**Comment by lzwhard** [comment]
I have encountered the same problem
`Loading weights from darknet19_448.conv.23...
 seen 32 
Done!
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Resizing
480
"annot load image "data/head_data/0/1_f/65.jpg
STB Reason: can't fopen
"annot load image "data/head_data/8/4_f/5.jpg
STB Reason: can't fopen
"annot load image "data/head_data/5/6_f/12.jpg
STB Reason: can't fopen
"annot load image "data/head_data/5/2_f/17.jpg
STB Reason: can't fopen
"annot load image "data/head_data/8/3_f/9.jpg
STB Reason: can't fopen
"annot load image "data/head_data/8/2_f/1.jpg
STB Reason: can't fopen
"annot load image "data/head_data/5/3_f/1.jpg
STB Reason: can't fopen
"annot load image "data/head_data/6/4_f/2.jpg
STB Reason: can't fopen
Segmentation fault (core dumped)`

**Comment by AlexeyAB** [comment]
* Did you prepare your `2007_train.txt` file on Windows?
* Try to do `dos2unix 2007_train.txt` **on Amazon** and then run training
* Can you run Darknet Yolo for detection **on Amazon** using command `./darknet detector test data/person.data ./yolo-person.cfg ./yolo-person.weights data/person/2_12700.jpg` ?
* Or using this `./darknet detector test data/person.data ./yolo-person.cfg ./yolo-person.weights ./data/person/2_12700.jpg` ?

**Comment by Adesun** [comment]
AlexeyAB is right, it's the problem of EOL.
It seemes that darknet can't handle the \r\n  EOL,
you can transfer your txt into Unix format by Notepad++,
add one line according to [this](https://github.com/Adesun/darknet/blob/EOL/src/utils.c#L289) and recompile darknet.

**Comment by goodtogood** [comment]
@AlexeyAB 
yes, I made txt file on windows. 
Darknet works well in detection on Amazon.
according to @Adesun , I tried transfering txt into unix EOL by NPP
training works well now on Amazon.
@AlexeyAB  @Adesun  thanks a lot for your help !

**Comment by AlexeyAB** [comment]
@goodtogood Now it is fixed. Thanks for @Adesun !

**Comment by goodtogood** [comment]
Got it . 
thanks you guys for your great work !

**Comment by lzwhard** [comment]
thanks a lot

**Comment by caihaocong** [comment]
thanks a lot!!!

**Comment by lx19970310** [comment]
thanks a lot

**Comment by caihaocong** [comment]
You are welcome.




在 2019-03-05 10:39:31，"lx19970310" <notifications@github.com> 写道：


thanks a lot
