### ISSUE TITLE
Error when trying to train YOLOv2 with random=1

### ISSUE THREAD

**Issue by raysonlaroca** [AlexeyAB/darknet#3250]
The following error is shown when I try to train **YOLOv2** with random=1:

Resizing
608 x 608 
**Resizing type 27 
Cannot resize this type of layer: File exists
darknet: ./src/utils.c:293: error: Assertion `0' failed.
Aborted (core dumped)**

When using random=0 or YOLOv3 variants, there are no problems.

Thanks in advance

**Comment by AlexeyAB** [comment]
@raysonlaroca Hi,

I fixed it.
