### ISSUE TITLE
compare the C api vs. opencv's cv2.dnn.readNetFromDarknet

### ISSUE THREAD

**Issue by aniketvartak** [AlexeyAB/darknet#3273]
Hi @AlexeyAB , I am trying to see if there is any benefit in using the C api from your fork vs. opencv's cv2.dnn.readNetFromDarknet for deployment.
before doing extensive testing, I wanted to see if you know any differences (run time, perf.) etc. that I should keep in mind between the two so I can use your knowledge and save some experiment time?!
thanks

**Comment by AlexeyAB** [comment]
@aniketvartak Hi,

* My repo is fast on GPU
* cv2.dnn.readNetFromDarknet is fast on CPU

Also there is difference in: https://github.com/AlexeyAB/darknet/issues/232#issuecomment-336955485
