### ISSUE TITLE
CUDA driver problem. Need help!

### ISSUE THREAD

**Issue by martisaju** [AlexeyAB/darknet#3286]
Hi, 

I need some help. I have compiled darknet with GPU and when I want to test it doing: darknet.exe detect cfg/yolov3.cfg yolov3.weights data/horses.jpg I get the following error:

![cuda](https://user-images.githubusercontent.com/29142274/58655076-9e041700-8319-11e9-8104-6a253bdf9656.JPG)

I have tried everything: update Windows, update NVIDIA drivers (but it gives me an error)... What can I do?
My GPU version is: GeForce GT 730
Thank you so much!

**Comment by Franksign** [comment]
which version of CUDA do you have?  Also paste your Makefile here.
