### ISSUE TITLE
How to get the detection result of a specific yolo layer?

### ISSUE THREAD

**Issue by ZHI-ANG** [AlexeyAB/darknet#3287]
For example, I want to compare the performance of YOLO v3 with only the first yolo layer responsible for the largest objects and YOLO v3 with all the three yolo layers. How can I mask the other two layers and get the result of the specific one?

**Comment by AlexeyAB** [comment]
Just copy yolov3.cfg to yolov3_custom.cfg in which all last layers after the first yolo layer are cut off

**Comment by ZHI-ANG** [comment]
@AlexeyAB Thanks a lot for answering my question. I've tested the net with only first yolo layer and of course, the net can hardly predict any objects smaller than the three largest anchors. SO is it meaningless to test the performance of the first yolo layer on smaller objects? 
What's more, If I want to do ablation experiment like the one in Feature Pyramid Network to certify the feature pyramid improves the recall of YOLO v3, what should I do? 
Thanks again!

**Comment by AlexeyAB** [comment]
> SO is it meaningless to test the performance of the first yolo layer on smaller objects?

Yes.

> What's more, If I want to do ablation experiment like the one in Feature Pyramid Network to certify the feature pyramid improves the recall of YOLO v3, what should I do?

Can you clarify, what do you mean?
