### ISSUE TITLE
question of prepare train image

### ISSUE THREAD

**Issue by mck0225** [AlexeyAB/darknet#329]
hi. i have question.

1.
![1](https://user-images.githubusercontent.com/26892666/34592019-9f11afc4-f204-11e7-86e8-2076dd50ca9a.jpg)

For example, I want to training people.
There are a total of 6 people in the prepared image.
A'', B' and B'` are the same person but not included in the training data.
Can this data be used for training?
Or should I must*1000 include all the objects that exist in the image?  

2.
My cfg is:
[net]
batch = 54
subdivisions = 8
width = 416
height = 416
channels = 3
momentum = 0.9
decay = 0.0005
angle = 0
saturation = 1.5
exposure = 1.5
hue = .1

If width and height are 416, should the width and height of the image used for learning be must*1000 greater than 416?

3.
![111](https://user-images.githubusercontent.com/26892666/34602079-cf4e1c44-f241-11e7-9f2f-d90f23418f23.jpg)

When people in the picture were all slightly different,
Can I attach image fragments randomly and use it for learning as shown in the picture?

**Comment by AlexeyAB** [comment]
@mck0225 

* You should include all objects that present on the training images
* Desirable (but not necessary) that the resolution of the image is equal to or greater than the resolution of the network
* Do you mean - cut out objects from different images, and paste them in one image for training? I did not do it, it might work well.

**Comment by mck0225** [comment]
Thank you very much
