### ISSUE TITLE
Shufflenetv2 better than yolov3-tiny

### ISSUE THREAD

**Issue by mdv3101** [AlexeyAB/darknet#3299]
As per my experiments with the same resolution and same dataset.
Shufflenetv2 object detector is twice as fast as yolov3-tiny and 20% more accurate.

Can we have some implementations of shufflenetv2 or Attonets (A-B-C-D) ?

 https://syncedreview.com/2019/03/21/attonets-compact-and-efficient-dnns-realized-via-human-machine-collaborative/

**Comment by AlexeyAB** [comment]
> Shufflenetv2 object detector is twice as fast as yolov3-tiny and 20% more accurate.

1. What dataset do you use? 
2. Can you show results of your experiments?
3. What repositories did you use for shufflenetv2, Attonets  and Yolov3-tiny?
4. Did you use them for detection or semantic/instance segmentation?

**Comment by LukeAI** [comment]
@mdv3101 I'm interested but can you tell us about it?

**Comment by mdv3101** [comment]
1. Dataset : private
2. Results are based on 1250 images we tested in the wild.
3. Yolov3-Tiny: This repository, ShuffleNetV2: Tensorflow
4. Only used for detection

**Comment by AlexeyAB** [comment]
@mdv3101 Thanks, what `mAP@0.5` did you get by using Shufflenetv2 and yolov3-tiny?

**Comment by mdv3101** [comment]
yolov3-tiny: 58.76
shufflenetv2: 69.39

**Comment by AlexeyAB** [comment]
@mdv3101 
Since shufflenetv2 is a classifier. Did you use detector-head `light-weight detector-Light-Head RCNN` or `SSD` at the top of shufflenetv2?

**Comment by mdv3101** [comment]
Detector was yolo in Tensorflow.
