### ISSUE TITLE
How to calculate mAP with thresh 0.5?

### ISSUE THREAD

**Issue by SHADOWMOOON** [AlexeyAB/darknet#3300]
@AlexeyAB Hi.
When I use the command to calculate the mAP(darknet.exe detector map data/obj.data yolo-obj.cfg backup\yolo-obj_10000.weights -iou_thresh 0.5)
![WeChat Image_20190602173134](https://user-images.githubusercontent.com/44594124/58759433-69cc6880-855c-11e9-934d-f2cf20ed21e5.png)
The pic show that: FOR thresh 0.25. What's the command to calculate mAP with thresh 0.5?

**Comment by AlexeyAB** [comment]
Hi,
There is no mAP on your screenshot.

If you want to calc P/R/F1... for confidence_threshold=0.5, then use `-thresh 0.5`

**Comment by SHADOWMOOON** [comment]
@AlexeyAB I Screenshoot one part of it.This is the full pic.
![6000](https://user-images.githubusercontent.com/44594124/58759795-6340ef80-8562-11e9-8215-a3ef09edec9b.jpg)

**Comment by AlexeyAB** [comment]
As you can see the mAP is calculated for IoU threshold = 50%, not 25%.

**Comment by SHADOWMOOON** [comment]
@AlexeyAB 
Thanks so much.

**Comment by SHADOWMOOON** [comment]
@AlexeyAB 
And I want to know why didn't I get the trainning log,I use the command like this :
darknet.exe detector train data/obj.data yolo-obj.cfg darknet53.conv.74 > log.txt .
The trainning is running but without any txt generated.
