### ISSUE TITLE
Difference between compiling yolo_cpp_dll.sln and yolo_console_dll.sln

### ISSUE THREAD

**Issue by CookingCookie** [AlexeyAB/darknet#3301]
Hey,

I want to use yolo as a .dll in my C++ project. I build my .dll with yolo_cpp_dll.sln and am able to use it in my code. But I am wondering, what is the difference to using yolo_console_dll.sln?

**Comment by AlexeyAB** [comment]
*  yolo_cpp_dll.sln - it is Darknet DLL-library

* yolo_console_dll.sln - it is your own application, that just uses this Darknet DLL-library `yolo_cpp_dll.dll`

**Comment by CookingCookie** [comment]
Oh ok, thanks!
