### ISSUE TITLE
Can't get the trainning log.

### ISSUE THREAD

**Issue by SHADOWMOOON** [AlexeyAB/darknet#3302]
@AlexeyAB Dear Alexey,
when I use the command like this below:
darknet.exe detector train data/obj.data yolo-obj.cfg darknet53.conv.74 > log.txt 
The training can run but didn't generate any log.txt file,Why？
now my training is still running.

**Comment by sotrik** [comment]
@AlexeyAB
please explain this.

**Comment by yrc08** [comment]
@Look4-you 
Hi!
Have you taken the liberty to solve the above problems? I also encountered this problem now.thanks!
