### ISSUE TITLE
i want to run the darknet pjreddie in cygwin terminal in windows

### ISSUE THREAD

**Issue by Roy-developer** [AlexeyAB/darknet#3308]
Couldn't open file: data/train.list not able to open train.txt while running ./darknet detector train trainer.data cfg/yolov3.cfg darknet53.conv.74
Installed cygwin in windows to run the train detector function in shell after running make

![image](https://user-images.githubusercontent.com/21329674/58803062-759f4580-85c3-11e9-9221-d8bf97f5b943.png)

Loading weights from darknet53.conv.74...Done!
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Couldn't open file: C:/Darknet_old/darknet/custom/train.txt

**Comment by AlexeyAB** [comment]
pjreddie's Darknet doesn't support Window.

----

Try to build https://github.com/AlexeyAB/darknet on Windows by using: Cmake, MSVS `darknet.sln` or Cygwin make.

Did you use such command for compile?
`c:\cygwin64\bin\bash -l -c "cd %CD:\=/%/; echo $PWD; make clean; make LIBSO=1 AVX=1 OPENMP=1"`

Do you have file `C:/Darknet_old/darknet/custom/train.txt` ?

**Comment by Roy-developer** [comment]
yes i have train.txt and cygwin but i only used make command to build the darknet
Please give me descri
![hardHat_1](https://user-images.githubusercontent.com/21329674/58904178-a2b73980-8724-11e9-9585-2e234806ca54.jpg)
![hel](https://user-images.githubusercontent.com/21329674/58904179-a2b73980-8724-11e9-9640-879b884fb7b9.jpg)
![hel2](https://user-images.githubusercontent.com/21329674/58904180-a34fd000-8724-11e9-89d9-ba4d44526c49.jpg)
![hel3](https://user-images.githubusercontent.com/21329674/58904181-a34fd000-8724-11e9-85ce-7fdcd2dacba3.jpg)
![hel4](https://user-images.githubusercontent.com/21329674/58904182-a34fd000-8724-11e9-9591-76501b59c617.jpg)
![hojo](https://user-images.githubusercontent.com/21329674/58904184-a3e86680-8724-11e9-8b90-335f0f64e6fc.jpg)
![images](https://user-images.githubusercontent.com/21329674/58904185-a3e86680-8724-11e9-949a-2611d6bec66a.jpg)
![images1](https://user-images.githubusercontent.com/21329674/58904187-a480fd00-8724-11e9-8d25-5327ceb78abc.jpg)
![person](https://user-images.githubusercontent.com/21329674/58904188-a480fd00-8724-11e9-80ed-3cd4359b39bc.jpg)
![s1](https://user-images.githubusercontent.com/21329674/58904190-a480fd00-8724-11e9-82a8-cc5cd2028623.jpg)
![s2](https://user-images.githubusercontent.com/21329674/58904191-a480fd00-8724-11e9-8236-a73f66ae808e.jpg)
![s11](https://user-images.githubusercontent.com/21329674/58904193-a5199380-8724-11e9-91d8-f7643bb2173b.jpg)
[test.txt](https://github.com/AlexeyAB/darknet/files/3253984/test.txt)
[train.txt](https://github.com/AlexeyAB/darknet/files/3253985/train.txt)
![trump](https://user-images.githubusercontent.com/21329674/58904194-a5b22a00-8724-11e9-84b6-c15bf2f846cb.jpg)
![trump2](https://user-images.githubusercontent.com/21329674/58904195-a5b22a00-8724-11e9-8443-c58c2dbc186c.jpg)
![WITH_HELMET-118](https://user-images.githubusercontent.com/21329674/58904196-a5b22a00-8724-11e9-8bbb-42e7ca0a33b3.jpg)
















bed process the build it using darknet.
