### ISSUE TITLE
Potential typo/swapped variable assignment in cost_layer.c

### ISSUE THREAD

**Issue by robertc-git** [AlexeyAB/darknet#3318]
Lines 54-55 of src/cost_layer.c are currently:

l.delta_gpu = cuda_make_array(l.output, inputs*batch);
l.output_gpu = cuda_make_array(l.delta, inputs*batch);

Perhaps this isn't a problem at the moment given that the arrays are the same size, but to avoid potential future issues, should "l.output" and "l.delta" be swapped, or is this cross-assignment intentional?

**Comment by AlexeyAB** [comment]
@robertc-git Thanks, I fixed it!
