### ISSUE TITLE
How to improve precision - dolphin detection project

### ISSUE THREAD

**Issue by pullmyleg** [AlexeyAB/darknet#3321]
Hi @AlexeyAB, 

Thanks again for your repo and hard work. This repo and all your documentation / work in answering peoples questions has been a huge help to a non for profit project I am working. We are trying to find and protect the Maui dolphins in New Zealand (only 57 left). We are using real time object detection paired with 6 hour autonomous UAVs. The goal is to find and follow these animals to learn more about why and how they are dying so we can further protect them. 

I was hoping for some advice from you and or the community on how to tweak my configuration / tagging to improve the model. 

### Summarised Questions from below 
	1. Does the tagging process look sound? Any recommendations on how to improve? 
	2. Should I utilise the non-aerial photos with different angles to train?
	3. Any config improvement suggestions to increase accuracy?
	4. Do I have sufficient empty photos?

Note; I am relatively new to deep learning & real-time object detection. I successfully trained an initial model. But I want to further improve the precision. 

### Setup
	- Intel I7 4770 3.9GHZ
	- 16GB memory
	- 1 x Nvidia EVGA 1080ti 
	- Windows 10
	- Source compiled with build script CUDA 10.1, CUDnn 7.6, OpenCV 3.4.4 set for compute_61.
	- Current config is at bottom of this post. 
	- 2 classes, Maui dolphin, boat. 

I would like to improve detection so I can increase the threshold for the Drone and output of when there is a Maui Dolphin. Examples of the current state:

![image](https://user-images.githubusercontent.com/42484083/58919093-f5beda00-8780-11e9-853d-986cdf3293b6.png)

![image](https://user-images.githubusercontent.com/42484083/58919098-fa838e00-8780-11e9-956d-05bf7d5c3482.png)

I am also not sure why the AP for class1 (boat) is 0%?

![image](https://user-images.githubusercontent.com/42484083/58919111-04a58c80-8781-11e9-84dc-0a5ce11bb03c.png)

Training with 9000 images and 500 test images for mAP. All tagged with YoloMark. Examples: 

![image](https://user-images.githubusercontent.com/42484083/58919131-171fc600-8781-11e9-9295-0befd867c260.png)

![image](https://user-images.githubusercontent.com/42484083/58919136-1b4be380-8781-11e9-94c7-ece2cafeb3e4.png)

![image](https://user-images.githubusercontent.com/42484083/58919141-1edf6a80-8781-11e9-9388-193ff3dd72db.png)

![image](https://user-images.githubusercontent.com/42484083/58919145-2141c480-8781-11e9-996c-e5b0b8bcfc4a.png)

One potential issue that I think may be causing the low detection & map score is what dolphins in the imagery have been tagged and what haven't. The theory here has been from the point of view that it needs to be distinguishable on its own as a dolphin, if its to submerged or not clear it has not been tagged. Here are some examples:

![image](https://user-images.githubusercontent.com/42484083/58919165-361e5800-8781-11e9-87f3-053e928270a9.png)

![image](https://user-images.githubusercontent.com/42484083/58919167-3880b200-8781-11e9-8b2d-b19d13d099d4.png)

![image](https://user-images.githubusercontent.com/42484083/58919176-3b7ba280-8781-11e9-8a77-86573768c6c6.png)

![image](https://user-images.githubusercontent.com/42484083/58919188-45050a80-8781-11e9-9525-7b3e0ca00004.png)

Above without tags: 

![image](https://user-images.githubusercontent.com/42484083/58919193-4a625500-8781-11e9-9775-15145f5afeba.png)

Would be interested if you think these should or should not be tagged? The test dataset is a subset of this data and has the same potential issue. 

The data set also includes about 2000 images like this that have no dolphins or boats in them, examples:
![image](https://user-images.githubusercontent.com/42484083/58919215-5bab6180-8781-11e9-9a95-b4a54dfdbe42.png)

![image](https://user-images.githubusercontent.com/42484083/58919219-5f3ee880-8781-11e9-8592-10143ad0fec6.png)

Is this sufficient untagged images? Or do i need something else / completely different? 

Should I include non aerial footage when training the model to detect these dolphins? I have a library of about 4000 additional images of close up / side angle dolphin shots I am not currently using. E.g.: 

![image](https://user-images.githubusercontent.com/42484083/58919230-6bc34100-8781-11e9-9311-b3a460d1b9d8.png)

![image](https://user-images.githubusercontent.com/42484083/58919233-6f56c800-8781-11e9-825d-aaedb140fbcf.png)

When random testing the model also detects people as boats, probably because there were people on the boat in the picture? Would you retrain to include people or just increase detection threshold? 

![image](https://user-images.githubusercontent.com/42484083/58919246-7bdb2080-8781-11e9-9e4a-9af832f53b33.png)

current config below open to suggestions / improvements: 

Note last 8000 iterations of training was done with below anchors (all other config exactly the same: 
12, 21,  20, 42,  41, 38,  32, 67,  67, 74,  44,119,  87,140,  94,271, 213,312

Config: 

[net]
# Testing
#batch=1
#subdivisions=1
# Training
batch=64
subdivisions=32
width=608
height=608
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
burn_in=1000
max_batches = 10000
policy=steps
steps=8000,9000
scales=.1,.1

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

# Downsample

[convolutional]
batch_normalize=1
filters=64
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=32
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

# Downsample

[convolutional]
batch_normalize=1
filters=128
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

# Downsample

[convolutional]
batch_normalize=1
filters=256
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

# Downsample

[convolutional]
batch_normalize=1
filters=512
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

# Downsample

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky

[shortcut]
from=-3
activation=linear

######################

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=21
activation=linear

[yolo]
mask = 6,7,8
anchors = 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326
classes=2
num=9
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1

[route]
layers = -4

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[upsample]
stride=2

[route]
layers = -1, 61

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=512
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=512
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=512
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=21
activation=linear

[yolo]
mask = 3,4,5
anchors = 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326
classes=2
num=9
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1

[route]
layers = -4

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[upsample]
stride=2

[route]
layers = -1, 36

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=256
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=256
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=256
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=21
activation=linear

[yolo]
mask = 0,1,2
anchors = 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326
classes=2
num=9
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1

**Comment by AlexeyAB** [comment]
@pullmyleg Hi,

> We are using real time object detection paired with 6 hour autonomous UAVs. 

1. What GPU do you use for Detection on UAV?

2. What framework will you use for Detection: Darknet (original, this), TensorFlow, PyTorch, OpenCV-dnn, OpenVINO?

3. Try to train SPP-model: https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov3-spp.cfg

4. Try to train with higher network resolution `width=832 height=832` if your GPU-memroy is enough, and if Training and Detection is not very slow for you

5. If you will use only this repository for detection, then you can try to train new model: https://github.com/AlexeyAB/darknet/files/3253820/yolo_v3_spp_pan_scale.cfg.txt you can train it as usual just by using this pre-trained weights-file  http://pjreddie.com/media/files/darknet53.conv.74 It has better performance https://github.com/AlexeyAB/darknet/issues/3114#issuecomment-494148968 But any other frameworks don't support this model

6. Read: https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

for each object which you want to detect - there must be at least 1 similar object in the Training dataset with about the same: shape, side of object, relative size, angle of rotation, tilt, illumination. So desirable that your training dataset include images with objects at diffrent: scales, rotations, lightings, from different sides, on different backgrounds - you should preferably have 2000 different images for each class or more, and you should train 2000*classes iterations or more

----

![58919176-3b7ba280-8781-11e9-8a77-86573768c6c6](https://user-images.githubusercontent.com/4096485/58920045-0c414300-8739-11e9-9b62-82ec07a87bd9.png)

if it is a dolphin - then yes, it should be marked

----

![58919193-4a625500-8781-11e9-9775-15145f5afeba](https://user-images.githubusercontent.com/4096485/58920056-18c59b80-8739-11e9-91a2-522889707f56.png)

label in such a way, as you want to detect it

----

![58919246-7bdb2080-8781-11e9-9e4a-9af832f53b33](https://user-images.githubusercontent.com/4096485/58920067-2549f400-8739-11e9-9f38-96dcdea95957.png)

It doesn't matter that it has False Detection on such images, since your UAV will not see such images. So you shouldn't include such images and shouldn't worry about this.

**Comment by pullmyleg** [comment]
Hi @AlexeyAB - thanks for the quick response and answers. I will give all the suggestions a go and revert back. A couple of answers to your questions below: 

1) UAV is currently using a Jetson TX1 but potentially will upgrade to TX2
2) Likely Darknet, but potentially Tensorflow due to previous implementations.  

4) Will have a go at higher resolution, should I start training again or continue with current weights? I will likely need to increase subdivisions to 64. 

Tane

**Comment by pullmyleg** [comment]
Hi @AlexeyAB, a summary of results to date based on your suggestions and also a couple of questions. 

2. We have decided to use darknet for detection framework for the final detection. 
3. I have trained with SPP model and have had some pretty good results. Although I am getting weird spikes with the MAP. See below. 

![chart1](https://user-images.githubusercontent.com/42484083/60158133-86e71500-9844-11e9-8dde-b9b781dc1c66.png)

![chart 5](https://user-images.githubusercontent.com/42484083/60158163-ad0cb500-9844-11e9-8b98-037a16e6ded6.png)

![chart](https://user-images.githubusercontent.com/42484083/60158169-b269ff80-9844-11e9-9f6d-5f35c2d06e72.png)

4. SPP model was trained at 832 resolution. Subdivision 64. 
5. I am currently training with SPP_Pan_Scale as suggested with a resolution of 544. I am using video frame grabs in order and settings as per [#3114](Https://github.com/AlexeyAB/darknet/issues/3114#issuecomment-494148968). 
Again the map jumps up and down all the time quite a lot, unsure why? Note this is still currently training. 

![2019-06-26_18-56-29](https://user-images.githubusercontent.com/42484083/60158346-0248c680-9845-11e9-8fd6-6d0861c1deb7.png)

6. I have read and made all adjustments as suggested - thanks.

7. I am going to re run through the images and ensure all even partial views are tagged and re run SPP_Pan_Scale. 

Any suggestions on why the MAP jumps around so violently would be great. When tested the models from each of the runs work quite well! The overall map has increased significantly, I also realised I had no example test data for one of the classes which was an issue. 

Thanks again! 

Tane

**Comment by AlexeyAB** [comment]
@pullmyleg Hi,

> Again the map jumps up and down all the time quite a lot, unsure why? Note this is still currently training.

This is normal for small datasets (less than 10 000 - 20 000 images). Or if test and train images are very different.


1. So you got mAP ~= 90% for SPP-model, that is good.


> SPP model was trained at 832 resolution. Subdivision 64.
> I am currently training with SPP_Pan_Scale as suggested with a resolution of 544. I am using video frame grabs in order and settings as per #3114.

2. `SPP_Pan_Scale` can be trained on random images, not necessary frames from video.
    Only `LSTM` models must be trained on frames from video, like `yolo_v3_tiny_pan_lstm.cfg.txt` or `yolo_v3_spp_lstm.cfg.txt` ...

Since you got better result on SPP (832x832) than SPP_PAN (544x544), then it seems that network resolution is important for your dataset, so you should train with `width=832 height=832` if you have enough GPU-VRAM.

**Comment by pullmyleg** [comment]
Thanks! Closing.
