### ISSUE TITLE
Good Labeling but Bad Locations

### ISSUE THREAD

**Issue by ToniRadoiu** [AlexeyAB/darknet#3322]
Hi,
I am trying to train yolov3 with 6 classes of vehicles. During the training I reached 2000+ iterations with 0.04 avg loss as in the image below:
![2000 iter](https://user-images.githubusercontent.com/44031436/58936826-5c3ffa00-8779-11e9-8bed-025db9473a0c.png)

My training data are images like the following with text files like "<class> 0.5 0.5 1.0 1.0". I was thinking that the images are already cropped so I can use the entire image as training data.
![bus_2](https://user-images.githubusercontent.com/44031436/58937219-70382b80-877a-11e9-9596-ee2c49ecb0a0.jpg)

The labels from test are good, but the bounding boxes are around the entire image like in the next picture:
![result](https://user-images.githubusercontent.com/44031436/58936999-cfe20700-8779-11e9-9b03-98cea2503cd8.jpg)

What can be the problem? The bounding boxes will get better if I train more?
I will train more anyway but I it looks like I'm doing something wrong.

Thank you!

**Comment by HagegeR** [comment]
look at the readme, object in training and in detect should look alike in size too.

either you train with images that look like in your training dataset or you detect object first and send the cropped image to the network.

the anchors became too big and can't give smaller object for the bounding box

**Comment by AlexeyAB** [comment]
**for each object which you want to detect - there must be at least 1 similar object in the Training dataset with about the same:** shape, side of object, **relative size**, angle of rotation, tilt, illumination. So desirable that your training dataset include images with objects at diffrent: scales, rotations, lightings, from different sides, on different backgrounds - you should preferably have 2000 different images for each class or more, and you should train 2000*classes iterations or more

https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

**Comment by ToniRadoiu** [comment]
Thank you for answering!
I will close the issue because the detection got a lot better after more iterations.
