### ISSUE TITLE
about "darknet with GIoU"

### ISSUE THREAD

**Issue by anguoyang** [AlexeyAB/darknet#3323]
Hi @AlexeyAB , I found you forked the "darknet with GIoU" today, do you have plan to port g-darknet into your repository?

**Comment by LukeAI** [comment]
https://github.com/AlexeyAB/darknet/issues/3249

**Comment by AlexeyAB** [comment]
@anguoyang Hi, just use the last commit with this cfg-file: https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov3.coco-giou-12.cfg

**Comment by anguoyang** [comment]
hi @LukeAI @AlexeyAB  thank you!
