### ISSUE TITLE
How to use multi-labelling?

### ISSUE THREAD

**Issue by LukeAI** [AlexeyAB/darknet#3325]
I understand that Yolov3-family ODs can be labelled with multi-tier annotations such as: "Woman, Person" "Boy, Person" "Bus, Vehicle" etc.
My questions are:
(1) How exactly do you do this?
Is it just like:
woman person 0.3231232 0.5454 0.212 0.89

(2) Is there an advantage? Does encoding this hierarchical organisation of your data into the annotations give your OD a hint that ultimately improves performance?

**Comment by AlexeyAB** [comment]
1. Labels should be
```
person 0.3231232 0.5454 0.212 0.89
woman 0.3231232 0.5454 0.212 0.89
```

2. No. It just can give advantage for many different closely located objects, when there are more objects than anchors, so one bbox (one anchor) can predict many objects at the same time - this increases mAP on OpenImage dataset.

Theoretically the hierarchical organisation with multi-labeling can improve accuracy for cvon-LSTM models which remember previous frames, if on the prevous frame was predicted "Woman, Person", and now is predicted "Person", then highly likely it is a Woman too.

**Comment by LukeAI** [comment]
So doing this multilabelling would then increase the computational cost if you are adding new classes?

**Comment by EtheneXiang** [comment]
hello @AlexeyAB , i have same question about "How to use multi-labeling? ", I understand that Yolov3  can be labelled with multi-tier annotations such as: "Woman, Person" "Boy, Person" "Bus, Vehicle" etc from paper and i understand how to train custom model with one label for classifying and object detecting. 
i really want to konw How to use multi-labeling?because there are no examples in official GitHub(https://github.com/pjreddie/darknet),  so i have two questions: 
(1)how to modify the cfg file for  multi-labeling??
(2)how to modify the txt file(label file for training)  for multi-labeling??

**Comment by LukeAI** [comment]
> hello @AlexeyAB , i have same question about "How to use multi-labeling? ", I understand that Yolov3 can be labelled with multi-tier annotations such as: "Woman, Person" "Boy, Person" "Bus, Vehicle" etc from paper and i understand how to train custom model with one label for classifying and object detecting.
> i really want to konw How to use multi-labeling?because there are no examples in official GitHub(https://github.com/pjreddie/darknet), so i have two questions:
> (1)how to modify the cfg file for multi-labeling??
> (2)how to modify the txt file(label file for training) for multi-labeling??

the answer to your question is right there already.

**Comment by EtheneXiang** [comment]
> > hello @AlexeyAB , i have same question about "How to use multi-labeling? ", I understand that Yolov3 can be labelled with multi-tier annotations such as: "Woman, Person" "Boy, Person" "Bus, Vehicle" etc from paper and i understand how to train custom model with one label for classifying and object detecting.
> > i really want to konw How to use multi-labeling?because there are no examples in official GitHub(https://github.com/pjreddie/darknet), so i have two questions:
> > (1)how to modify the cfg file for multi-labeling??
> > (2)how to modify the txt file(label file for training) for multi-labeling??
> 
> the answer to your question is right there already.

this answer is for lable, i really want to konw how to modify the cfg file for multi-labeling??
