### ISSUE TITLE
darknet_no_gpu.exe stopped running

### ISSUE THREAD

**Issue by sinchana-eshwar** [AlexeyAB/darknet#3330]
Hi,
I am using darknet_no_gpu to train my custom dataset  on my windows machinel. The compilation was succesful but when I start "darknet_no_gpu" to train, it displayed "darknet_no_gpu.exe stop running".

![image](https://user-images.githubusercontent.com/44646405/58983970-f0c05180-87a5-11e9-846b-7baaba115890.png)

![image](https://user-images.githubusercontent.com/44646405/58984092-2cf3b200-87a6-11e9-98f5-74bf827b1105.png)

Could you please help me out with this, thanks a lot!!!!

**Comment by sinchana-eshwar** [comment]
@AlexeyAB Could you please me resolve this issue?

**Comment by AlexeyAB** [comment]
@sinchana-eshwar Hi,
You should train by using CUDA+cuDNN on GPU.
Otherwise it can take several years.

**Comment by MarcPoulin1** [comment]
@AlexeyAB  I am having the same issue at the exact same place there seem to be an access violation with data_im

**Comment by MarcPoulin1** [comment]
@AlexeyAB here are 2 screenshots : ![image](https://user-images.githubusercontent.com/51760941/59380119-5a040f80-8d26-11e9-892f-b9c52794a460.png)
![image](https://user-images.githubusercontent.com/51760941/59380166-7dc75580-8d26-11e9-8f00-51417793e92d.png)

data_im is 0 and seems to be the reason why there is the error. I also noted that data_im is of type const float* and data_col is of type float*. Not sure why they have different types... Hopefully we can find a fix to this problem. Thank you!

**Comment by AlexeyAB** [comment]
@sinchana-eshwar @MarcPoulin1 
I fixed this bug.
