### ISSUE TITLE
Inconsistency or potential bug in forward_shortcut_layer_gpu()

### ISSUE THREAD

**Issue by robertc-git** [AlexeyAB/darknet#3333]
It appears that a change committed to this repository on January 16, 2019 introduced an inconsistency or bug in how shortcut layers are handled when the GPU is enabled. Here are the details:

When running "darknet classifier predict cfg/imagenet1k.data cfg/resnet50.cfg weights/resnet50.weights data/eagle.jpg" compiled with GPU=1 in the Makefile, I get unusually low results:
   bald eagle: 0.280216
   ruddy turnstone: 0.119954
   coyote: 0.050394
   grey whale: 0.044617
   aircraft carrier: 0.029981

 However, when running with GPU=0, I get the expected results:
    bald eagle: 0.681118
    kite: 0.195551
    ruddy turnstone: 0.052156
    vulture: 0.033736
    albatross: 0.003236

After testing this on earlier versions of the software, I narrowed down this issue to the changes that were committed on January 16, 2019 (SHA-1: 5343aa423563c107e0071b1427ad5defc27b56d2, "CUDA minor performance improvement").

Before that commit, forward_shortcut_layer_gpu() first copied all input elements to the output using copy_ongpu(), and then it applied the shortcut using shortcut_gpu(). After that commit, the copy_ongpu() was removed, and instead the shortcut was applied using input_shortcut_gpu(). In other words, the shortcut layer behaved as follows:
   before January 16: Copy all input to output, then subset of output += earlier_layer
   after January 16: Output is zero, then subset of output = input + earlier_layer

The issue occurs when the earlier layer has fewer elements than the current and output layers. For example, in resnet50, layer 5 is a shortcut layer with output size 64x64x256, which adds the outputs of layer 4 (64x64x256) and layer 1 (64x64x64). Before January 16, all 64x64x256 elements from layer 4 were copied to the layer 5 output, and then the 64x64x64 elements from layer 1 were added to the beginning of the layer 5 output. The net effect was that layer 1 was added to the beginning of layer 4, and the remaining elements from layer 4 were copied forward. However, after the January 16 commit, the remaining elements from layer 4 were in effect set to zero. The CPU version (GPU=0) of the software wasn't affected by this change; it always did the full copy of input to output.

Currently, shortcut_layer.c has:
```
void forward_shortcut_layer_gpu(const layer l, network_state state)
{
    //copy_ongpu(l.outputs*l.batch, state.input, 1, l.output_gpu, 1);
    //simple_copy_ongpu(l.outputs*l.batch, state.input, l.output_gpu);
    //shortcut_gpu(l.batch, l.w, l.h, l.c, state.net.layers[l.index].output_gpu, l.out_w, l.out_h, l.out_c, l.output_gpu);
    input_shortcut_gpu(state.input, l.batch, l.w, l.h, l.c, state.net.layers[l.index].output_gpu, l.out_w, l.out_h, l.out_c, l.output_gpu);
    activate_array_ongpu(l.output_gpu, l.outputs*l.batch, l.activation);
}
```

I tested a few fixes, namely uncommenting the call above to copy_ongpu() or alternatively uncommenting simple_copy_ongpu(), and then the classifier then worked as expected. However, if the intent of the January 16 and some subsequent changes were to eliminate performing the full copy, perhaps a better fix would be to add some code to just to copy over any remaining unmodified elements, if they're contiguous. Note also that in the above ResNet example, the layer 4 output was larger than the layer 1 output, so perhaps some additional testing would be needed if for example layer 4 were smaller than than layer 1.

**Comment by AlexeyAB** [comment]
@robertc-git Hi,
Thanks! I fixed it.
