### ISSUE TITLE
Random factor scaling

### ISSUE THREAD

**Issue by ilkarman** [AlexeyAB/darknet#334]
It seems the random factor is hard-coded somewhere in the source-code. Is it possible to alter this somewhere so that instead of scaling from e.g 0.25 to 2 we scale from 2 to 4

**Comment by AlexeyAB** [comment]
Do you mean `random=1` in the cfg-file?

Yes, random-range of the network resolution is hardcoded [320 - 608] here:
https://github.com/AlexeyAB/darknet/blob/ea09a6e0b38e1ddf43ffcd81d27f0506411eb8e4/src/detector.c#L98
Just change this line.
