### ISSUE TITLE
GPU issues (compilation errors) all info provided

### ISSUE THREAD

**Issue by buzdarbalooch** [AlexeyAB/darknet#3340]
Hi i am using a GPU (GTX 1080ti) via VPN.

this is the version of nvcc i am using 
<img width="846" alt="error1" src="https://user-images.githubusercontent.com/19202445/59016891-9923f380-8842-11e9-9540-b0ab9edde505.png">

whereas, the nvidia-smi yields the following. i installed them after checking the system compatibility.

<img width="509" alt="error-nvidia-version" src="https://user-images.githubusercontent.com/19202445/59017523-008e7300-8844-11e9-95cc-ca4a51387bef.png">

when i try to "make" after commenting these lines in the make file  "-gencode arch=compute_61,code=[sm_61,compute_61]". i get the following error.

<img width="894" alt="error3" src="https://user-images.githubusercontent.com/19202445/59017648-582cde80-8844-11e9-95ab-366e34bd607c.png">

whereas, when i try to "make" after un-commenting these lines in the make file  "-gencode arch=compute_61,code=[sm_61,compute_61]". i get the following error.

<img width="960" alt="error-with-compute-61" src="https://user-images.githubusercontent.com/19202445/59017679-6ed33580-8844-11e9-8ef4-b0cfa19d9a18.png">

i shall be greatful, if you can suggest any solution. @AlexeyAB . i already read the available solutions but somehow still not able to solve.

**Comment by AlexeyAB** [comment]
@buzdarbalooch Hi,
Try to update your CUDA to 10.0

**Comment by buzdarbalooch** [comment]
thanks i updated to CUDA 8.0 its fine now
