### ISSUE TITLE
Bounding box coordinates without compiling darknet with opencv?

### ISSUE THREAD

**Issue by shantanuctech** [AlexeyAB/darknet#3341]
Hi Alexey, How can I get bounding box coordinates of detections if I havent compiled darknet with opencv during training? I am using cluster in my college and it doesnt allow changing lot of file configurations and hence had to disable opencv flag.

**Comment by AlexeyAB** [comment]
@shantanuctech Hi,
Just use `-ext_output` in your detection command: https://github.com/AlexeyAB/darknet#how-to-use-on-the-command-line

**Comment by shantanuctech** [comment]
Thanks for sweet reply
