### ISSUE TITLE
Linux Packages

### ISSUE THREAD

**Issue by acxz** [AlexeyAB/darknet#3343]
Some great work has been done in this fork of darknet. Are there plans for releasing linux packages for this fork? It would make the installation process much smoother. Maybe like a Ubuntu PPA or an ArchLinux AUR package?

**Comment by AlexeyAB** [comment]
@cenit Hi, What do you think about it?

**Comment by cenit** [comment]
Hi @acxz. All the work has been made towards this goal. So yes I hope together with @alexeyab to release packages for the most important package managers (it is already published on vcpkg which is available on Mac/windows/ubuntu), like brew and a ppa, and also a container

**Comment by acxz** [comment]
Nice! Looking forward to it. I would be interested in helping maintain an ArchLinux AUR package.
(That is once I figure out how to install this repo ;p)

**Comment by cenit** [comment]
@acxz if you are starting out, I suggest using vcpkg ;)

./vcpkg install darknet[opencv]

**Comment by acxz** [comment]
haha I meant installation via source. Since making package build recipes start from there.

**Comment by cenit** [comment]
Vcpkg builds packages from sources, directly on your pc. It contains also the recipe it uses to build it, driving CMake and the compiler

**Comment by acxz** [comment]
That would definitely be helpful to see then.

**Comment by cenit** [comment]
I wrote the recipe also there (and is under review an update), so it’s my fault if it doesn’t work :rofl:

You find it on github.com/Microsoft/vcpkg

**Comment by acxz** [comment]
I finally got around to creating and ArchLinux package for this repo. Here it is: https://aur.archlinux.org/packages/darknet-alexeyab-git/

**Comment by AlexeyAB** [comment]
@acxz Thanks!

**Comment by acxz** [comment]
np. I was wondering about adding a section on the readme that lists all ports, but right now it would be pretty bare with only vcpkg and the archlinux package. Maybe once there is a ubuntu package, having such a section would be helpful.

**Comment by cenit** [comment]
in any case, the linux package was and is provided by continuous daily

**Comment by cenit** [comment]
in any case, the linux package was and is provided by continuous integration daily (and for each release)
