### ISSUE TITLE
`make install` errors

### ISSUE THREAD

**Issue by acxz** [AlexeyAB/darknet#3345]
OS: ArchLinux
GCC: 8.3
master branch

Running the recommended commands to build the project (`cmake . && make`) works fine, but when I attempt to perform `make install` I get the following error:
```
[ 48%] Built target dark
[ 50%] Built target uselib_track
[ 51%] Built target uselib
[100%] Built target darknet
Install the project...
-- Install configuration: ""
-- Installing: /home/acxz/Desktop/darknet/include/darknet/darknet.h
-- Installing: /home/acxz/Desktop/darknet/include/darknet/yolo_v2_class.hpp
CMake Error at cmake_install.cmake:97 (file):
  file INSTALL cannot find
  "/home/acxz/Desktop/darknet/uselib".

make: *** [Makefile:86: install] Error 1
```

However, when I create a build like `mkdir build-release` and `cmake .. && make` in there, I can successfully `make install`. Note performing the procedure in the given `build` directory does not work either.

**Comment by AlexeyAB** [comment]
After `cmake . && make` do you have file `/home/acxz/Desktop/darknet/uselib` ?

**Comment by acxz** [comment]
Ah sorry I probably shouldve mentioned that mb.
Yeah I do. After cloning the repo and `cmake . && make` ing this is what the output of `ls` is:
```
3rdparty                    LICENSE       cfg                  image_yolov2.sh        src
CMakeCache.txt              Makefile      cmake                image_yolov3.sh        uselib
CMakeFiles                  README.md     cmake_install.cmake  include                uselib_track
CMakeLists.txt              appveyor.yml  darknet              json_mjpeg_streams.sh  video_v2.sh
DarknetConfig.cmake         build         darknet.py           libdark.so             video_yolov3.sh
DarknetConfig.cmake.in      build.ps1     darknet_video.py     net_cam_v3.sh
DarknetConfigVersion.cmake  build.sh      data                 scripts

```

**Comment by AlexeyAB** [comment]
@cenit Hi,

Is this normal behavior of cmake?

> Note how uselib is not there now, even when make install errored out. It seems as tho make install might be removing uselib and then trying to reference/use it later causing the file not found error.

**Comment by cenit** [comment]
Nope. CMake can build “inside the source tree”, as it is called when you launch “build&&install” inside the root folder or another non-dedicated folder. Anyway it is a best practice to never do that. I have to admit that I never build inside source folder so maybe I wrote some rules that conflict with this configuration

**Comment by acxz** [comment]
I see, well then it seems like the simple fix would just be to modify the README.md to say
`mkdir -p build-release && cd build-release && cmake .. && make` instead of just `cmake . && make`

**Comment by AlexeyAB** [comment]
@acxz @cenit 
Yes, readme says `cmake . && make` to get `./darknet` in the same folder as by using `make` (legacy way), since all examples from training and detection manuals are written for `./darknet` in the root folder with relative paths `./cfg/yolov3`, `./data/coco.names`, ...

At the very beginning, it is very important for users to have simple relative paths and a simple command for testing in order to understand that the darknet is installed correctly.

**Comment by acxz** [comment]
so when running `make install` from a build directory it copies the libraries (libdark.so) and executables over to the root directory of the repo which means that the all the examples with the same paths would work.

**Comment by acxz** [comment]
I went ahead and submitted #3348 to modify the readme. If @cenit could verify it it would be much appreciated.

**Comment by cenit** [comment]
@alexeyab build.sh and build.ps1 use CMake and give the user the executables and the libraries in the root folder, without much trouble of env variable setup, just like any novice user would expect ;)

**Comment by acxz** [comment]
Closing this issue since #3375 got merged.
