### ISSUE TITLE
Regarding the AUC value for custom dataset

### ISSUE THREAD

**Issue by sudharavali** [AlexeyAB/darknet#3349]
Hello @AlexeyAB ,

I am using a custom dataset for training my object detection model on two different datasets. I want to compare which model performs better. I am tabulating the mAP values and along with it, I also want to calculate the AUC values for both under the PR curve. 

Can you tell me if there is a way to get the AUC value as I read that for ImageNet, and custom dataset mAP is calculated through AUC values but I am not able to understand it properly. Can you please expand on it. 

Also, please let me know if there are better ways of comparing performance on two datasets. 

Thanks in advance !

**Comment by AlexeyAB** [comment]
@sudharavali Hi,

> Can you tell me if there is a way to get the AUC value as I read that for ImageNet, and custom dataset mAP is calculated through AUC values but I am not able to understand it properly. Can you please expand on it.

Yes, default mAP calculation is equal to AUC of PR-curve.

> Also, please let me know if there are better ways of comparing performance on two datasets.

Just compare mAP of two models.

**Comment by sudharavali** [comment]
Thank you for the clarification Alexey. I will close the issue now

**Comment by sudharavali** [comment]
Hello @AlexeyAB , 

I just have a followup question. In this case, is it a rule the the curve with largest area, ie,  AUC should have the largest mAP value as well ? 

Please let me know how it works if thats not the case as I am looking at a graph with higher AUC but comparitvely lower mAP score.

**Comment by AlexeyAB** [comment]
@sudharavali Hi,
> Please let me know how it works if thats not the case as I am looking at a graph with higher AUC but comparitively lower mAP score.

mAP === AUC. 
There can be no situation when: higher AUC and lower mAP.

**Comment by sudharavali** [comment]
Alright, that helps. Thanks alot !
