### ISSUE TITLE
How to detector with multi-GPU when i use yolo as dll on linux

### ISSUE THREAD

**Issue by wenku1992abc** [AlexeyAB/darknet#335]
HI 
Alex
   I use YOLO as dll on linux,and it sucess!but i want to speed up when it detector .What should i do ?

**Comment by AlexeyAB** [comment]
@wenku1992abc Hi,

* There is not easy way to use multi-GPU for detection on the single video-stream
* You can use 2nd GPU for Tracking:
    1. just uncomment this line: https://github.com/AlexeyAB/darknet/blob/ea09a6e0b38e1ddf43ffcd81d27f0506411eb8e4/src/yolo_console_dll.cpp#L16
    2. and change this line to `Tracker_optflow tracker_flow(1);`: https://github.com/AlexeyAB/darknet/blob/ea09a6e0b38e1ddf43ffcd81d27f0506411eb8e4/src/yolo_console_dll.cpp#L112

So Detection will be on the GPU#0, and Tracking will be on the GPU#1.

**Comment by wenku1992abc** [comment]
OK ,I got it .Thanks very much, Alex!
