### ISSUE TITLE
Will unlabelled instances of classes of interest in the dataset affect performance?

### ISSUE THREAD

**Issue by LukeAI** [AlexeyAB/darknet#3354]
I wish to be able to detect: pedestrians, cars, traffic lights

I have two large datasets:
 - One contains instances and labels of all three classes.
 - The other contains instances of all three but only labels for pedestrians and cars. ie. there are many unlabelled traffic lights.

I want to combine the two datasets and train Yolov3 on it. Will the unlabelled presence of objects of interest significantly affect detection performance of that category?

**Comment by AlexeyAB** [comment]
>  Will the unlabelled presence of objects of interest significantly affect detection performance of that category?

Yes
