### ISSUE TITLE
Classify gives totally different results due to compression

### ISSUE THREAD

**Issue by JasonRuan5** [AlexeyAB/darknet#3368]
Hi @AlexeyAB, Thank you again for helping me to get issue #3086 resolved.  I have another very critical issue.  We have tested the classifier we trained on 128x128 images.  For one set of images, it gives pretty good results (close to 75% of accuracy as validation shows).  However, for another almost identical set, the classifier gives total wrong results (accuracy less than 10%).  The main difference of the two sets is their compression ratio or algorithm.  Here is the configuration file I used.  
[darknet_128.txt](https://github.com/AlexeyAB/darknet/files/3270371/darknet_128.txt)
My questions are:
1.	Do you know what could cause this type of problem and what we can do to resolve that?  
2.	We currently set hue = 0.3, saturation = 1.5, and exposure = 1.5 in the .cfg file. Should we change any of them and is there any compression related setting can we use?
3.	Should we use different compression of images to train the classifier?

**Comment by JasonRuan5** [comment]
We found the image set that give good results are compressed with subsampling yuv420 and the other are compressed with yuv444.  I guess that most our train set were compressed with yuv420.  Should we train with images that are compressed yuv444, yuv422, and yun420 or could we set in the configuration file?  Any suggestions will be greatly appreciated.  Is there any other model better suited for this type of classification?

**Comment by AlexeyAB** [comment]
@JasonRuan5 Hi,

>  For one set of images, it gives pretty good results (close to 75% of accuracy as validation shows). However, for another almost identical set, the classifier gives total wrong results (accuracy less than 10%). 
> ...
> good results are compressed with subsampling yuv420 and the other are compressed with yuv444. I guess that most our train set were compressed with yuv420. 

I didn't meet with such problem.
So may be the problem is that objects look different in the new dataset rather than compression method.

Can you show objects from old_dataset and from new_dataset?

What format and extension of image-files do you use?

**Comment by JasonRuan5** [comment]
Hi @AlexeyAB, 
You can view or download the two image sets along with the five class classification results from the link below. 
http://www.vigenetech.com/plugin/Details.html
We have trained with both 96x96 and 128x128 images and the results are similar.  The results in the State column has 6 values, the first one is predicated class (0 to 4), and the rest 5 values are probabilities.  The most images should be belong to class 2, 3, or 4 as shown in good.png. For the bad set, predicated class for most images are 0 or 1.  The good and bad set of images were saved out as .png from big-Tiff with YUV420 and YUV444 sub sampling, respectively.  As you can see, the two sets look very close visually, but the results are very different. Any advices you have will be greatly appreciated.

**Comment by JasonRuan5** [comment]
Hi @AlexeyAB,
Just wonder if you are able to view or download the images?  Any advises?  I've noticed that there is void distort_image(image im, float hue, float sat, float val) in draknet.  Do you think that we should do similar in yuv instead of hsv spaces?  If so, what values do you recommend?

**Comment by AlexeyAB** [comment]
@JasonRuan5 Hi,

Yes, I can download. I just don't know why it happens.

Just train with both types of images yuv444 and yuv422.


In any cases every loaded image will be converted to RGB image:

* https://github.com/AlexeyAB/darknet/blob/c9129c207823a96f0a1b3a840883a6c510073347/src/image_opencv.cpp#L130-L139

* https://github.com/AlexeyAB/darknet/blob/c9129c207823a96f0a1b3a840883a6c510073347/src/image_opencv.cpp#L101-L117

**Comment by JasonRuan5** [comment]
Hi @AlexeyAB,
Thanks much for your help.  We will look into if we can have data augmentation via yuv color space.
