### ISSUE TITLE
Make command has errors for linux mint 18

### ISSUE THREAD

**Issue by yustiks** [AlexeyAB/darknet#3384]
I tried to run make for darknet, and I had an error:
`chmod +x *.sh
g++ -std=c++11 -Iinclude/ -I3rdparty/stb/include -DOPENCV `pkg-config --cflags opencv` -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -c ./src/image_opencv.cpp -o obj/image_opencv.o
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
./src/image_opencv.cpp:15:10: fatal error: opencv2/core/version.hpp: Нет такого файла или каталога
 #include <opencv2/core/version.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:149: recipe for target 'obj/image_opencv.o' failed
make: *** [obj/image_opencv.o] Error 1
`

I guess the problem is with opencv version, but I can't find what exactly. 
Would be nice if anyone helps. Thank You.

**Comment by acxz** [comment]
Can you post the options you used for your `Makefile`?

**Comment by AlexeyAB** [comment]
* What OpenCV version do you use?

* Did you install OpenCV from source? https://opencv.org/releases/

**Comment by yustiks** [comment]
Solved the issue by installing the latest version of opencv. Should update opencv by this link.
https://github.com/jayrambhia/Install-OpenCV

**Comment by yustiks** [comment]
> * What OpenCV version do you use?
> * Did you install OpenCV from source? https://opencv.org/releases/

Thank You, I guess the problem was connected with opencv old version
