### ISSUE TITLE
error while loading shared libraries: api-ms-win-crt-locale-l1-1-0.dll

### ISSUE THREAD

**Issue by daylanc** [AlexeyAB/darknet#3385]
@AlexeyAB 
I am trying to install darknet on my windows laptop. I was successfully able to follow the install it using the vcpkg method. After installing all the dependencies (cuda, cudnn, git, cmake, etc.) I tried to test the installation by running `./darknet.exe` in the `/c/darknet/` directory in gitbash. However, when running it, I receive the following error:
![Capture](https://user-images.githubusercontent.com/34255535/59303543-4768d800-8c4b-11e9-9f77-cb0e7b281623.PNG)

I'm not sure if I am missing something for this install. Any help would be appreciated.

Thanks!

**Comment by AlexeyAB** [comment]
Did you build Darknet by using Cmake-GUI and MSVS ? https://github.com/AlexeyAB/darknet#how-to-compile-on-windows-using-vcpkg

Try to create `dark.cmd` with such content: 
`darknet.exe detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights dog.jpg -ext_output`

and run it.

Download https://pjreddie.com/media/files/yolov3.weights

**Comment by daylanc** [comment]
@AlexeyAB 
What do you mean by the Cmake-GUI? Should I use that instead of the git-bash GUI when running `.\build.ps1`? In your Readme, it states to run all the commands in Powershell. I chose git-bash because I am more familiar with linux than windows.
I installed MS-Visual Studio 2019 community version, cuda 10.1, cudnn 7.6, git, cmake, and vcpkg. I tested vcpkg with `vcpkg install opengl`.

**Comment by AlexeyAB** [comment]
> What do you mean by the Cmake-GUI? 

https://github.com/AlexeyAB/darknet#how-to-compile-on-windows-using-vcpkg

> If you have already installed Visual Studio 2015/2017/2019, CUDA > 10.0, cuDNN > 7.0, OpenCV > 2.4, then compile Darknet by using **C:\Program Files\CMake\bin\cmake-gui.exe** as on this IMAGE: Configure -> Optional platform for generator (Set: x64) -> Finish -> Generate -> Open Project -> x64 & Release -> Build -> Build solution
> 
> ### Otherwise, follow these steps:

----

> I tried to test the installation by running ./darknet.exe in the /c/darknet/ directory in gitbash. 


Use Windows-CMD instead of Git-bash.

**Comment by daylanc** [comment]
@AlexeyAB 
I was able to compile it using Visual Studio 2019. I don't have a `darknet.exe` file in my /darknet folder though. When I try to run `darknet.exe detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights dog.jpg -ext_output` inside of the darknet folder, I get:
'darknet.exe' is not recognized as an internal or external command, operable program, or batch file.
On linux, I'm able to run darknet using `./darknet .....`. Shouldn't it be the same way in Windows?

**Comment by daylanc** [comment]
@AlexeyAB 
I tried compiling again with the `build.ps1` script in PowerShell. It seems to have completed successfully, but when trying to run `darknet.exe detector test cfg\coco.data cfg\yolov3.cfg data\yolov3.weights data\dog.jpg -ext_output` in the windows command prompt, I get several pop-up errors:

error 1: pthreadVC3.dll was not found
error 2: opencv_highfui343.dll was not found
error 3: opencv_videoio343.dll was not found
error 4: opencv_imgcodecs343.dll was not found

I believe it may be related to your install ReadMe:
> [necessary only with CUDA] Customize the build.ps1 script enabling the appropriate my_cuda_compute_model line. If not manually defined, CMake toolchain will automatically use the very low 3.0 CUDA compute model

Where can i find the `my_cuda_compute_model` line you talk about in the `build.ps1` script? 
FYI, I have cuda 10.1 and OpenCV 4.1

Thanks.

**Comment by AlexeyAB** [comment]
@cenit Does `build.ps1` use integrated pthread-library or install it by using vcpkg? And does `build.ps1` copy `pthreadVC3.dll` to the Darknet-folder (near with darknet.exe file)?

**Comment by AlexeyAB** [comment]
@daylanc You should specify path to OpenCV dlls in your environment variables in Windows, or copy this file from OpenCV-folder to the Darknet-folder (where is darknet.exe file).

> Where can i find the my_cuda_compute_model line you talk about in the build.ps1 script?
> FYI, I have cuda 10.1 and OpenCV 4.1

Look at Compute Capability field
https://en.wikipedia.org/wiki/CUDA#GPUs_supported

**Comment by daylanc** [comment]
@AlexeyAB 
I don't have those openCV dlls on my computer. Since I installed openCV 4.10, I don't have the "opencv_highgui343.dll" or "opencv-videoio343.dll" or "opencv-imgcodecs343.dll". Do I need to install version 3.43 for openCV?
Also, what environment variables do I need to add? I only added:
1. CUDA_PATH
2. CUDA_PATH_V10_1
3. VCPKG_ROOT
4. VCPKG_DEFAULT_TRIPLET
Are there any more paths that I need to add?

**Comment by AlexeyAB** [comment]
@cenit This is very strange that Darknet requires OpenCV-3.4.3 dlls after compiling by using `build.ps1`, while there is already installed openCV 4.1.0.

@daylanc Try to install Darknet by using CMake-GUI instead of build.ps1

If you have already installed Visual Studio 2015/2017/2019, CUDA > 10.0, cuDNN > 7.0, OpenCV > 2.4, then compile Darknet by using C:\Program Files\CMake\bin\cmake-gui.exe as on this https://user-images.githubusercontent.com/4096485/55107892-6becf380-50e3-11e9-9a0a-556a943c429a.png : Configure -> Optional platform for generator (Set: x64) -> Finish -> Generate -> Open Project -> x64 & Release -> Build -> Build solution

**Comment by cenit** [comment]
Hi! If the executable requests those dlls, it means that it found them during build on your computer.
In #3371 there is a small fix related to dll automatic copying, which was moved and was not working anymore. When merged (it is ready) please retry running build.ps1, I hope your problems will be fixed

**Comment by cenit** [comment]
Please pull from master and retry with build.ps1

**Comment by daylanc** [comment]
@cenit @AlexeyAB 
Thank you for the assistance on this issue. I re-downloaded from master, built with build.ps1, and tried running `darknet.exe`. Everything seems to be working with the new repository.
Closing for now.
Thanks.

**Comment by cenit** [comment]
good :)
Thank you too for reporting the problem!
