### ISSUE TITLE
Getting nan values for avg (loss) field after 5 minutes training

### ISSUE THREAD

**Issue by Lepiloff** [AlexeyAB/darknet#3390]
At the initial stage, all values ​​were normal, 

![1](https://user-images.githubusercontent.com/28572064/59332528-25c92880-8cff-11e9-8724-6ab61467e976.png)

after 5 minutes of training, the values ​​of los began to increase 
![2](https://user-images.githubusercontent.com/28572064/59332558-35487180-8cff-11e9-9619-6fa81a24af30.png)
![3](https://user-images.githubusercontent.com/28572064/59332564-37aacb80-8cff-11e9-89a1-be72b480dce9.png)

and eventually became a **nan**
![4](https://user-images.githubusercontent.com/28572064/59332592-472a1480-8cff-11e9-9852-53df07ddc309.png)

My cfg file
https://github.com/Lepiloff/pyolo/blob/master/pyolo/cfg/yolov3.cfg

I'm using my own recalculated anchor 
anchors = 14,30,  25,25,  22,49,  38,37,  30,73,  50,54,  45,97,  77,73,  73,133

My dataset consist of aboute 1000 labeled images and same quantly of unlabled (with empty txt file). 
And non-empty images contain from 1 to 600 identical objects of the same class. Training with GPU.  
What could be the cause of the problem?

**Comment by AlexeyAB** [comment]
Do you use this repository for training?

What params do you use in Makefile?

Try to use default anchors.

Do you get bad.list or bad_label.list files?

**Comment by Lepiloff** [comment]
@AlexeyAB hello
1. I trained on this repository more than 5 times with another cfg files and datasets, all it was good.
2. makefile
```
GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=0
AVX=0
OPENMP=1
LIBSO=1
```
3.The result is same
4. I have bad.list file, but it contains except new files  links to old txt files , and I removed it for for the purity of the experiment and start new train. After that new file didnt created.

**Comment by Lepiloff** [comment]
I tried running train with default yolov3.cfg file and cant got any errors. I think the problem is in my own cfg file. 
Here are the changes I made
https://github.com/AlexeyAB/darknet/issues/2976#issue-435082515
