### ISSUE TITLE
CUDA Error: out of memory

### ISSUE THREAD

**Issue by yy2yy** [AlexeyAB/darknet#3397]
When i try load many network(6,7,8..) for different object(one object has one network) detect, this error will occur. I want to know how to free network's memory. Can someone help me?Thank you

**Comment by alexanderfrey** [comment]
Restart your computer and start the detector for one image/video and make sure the resolution is not too high in the cfg file you are using.

**Comment by keko950** [comment]
What gpu are you using? Are you using full yolo model?

**Comment by yy2yy** [comment]
Thank you for your reply，but it can't solve my problem.The cfg file is right, my application scenario is that in the same program use load_network() many times(one object has one .weights file),  when use load_network() many times, it will occur CUDA Error: out of memory. I want to know how to free load_network's memory?

The pseudocode is as follows：
for i in range(20):
    net = load_net(i.cfg, i.weights, 0)
    meta = load_meta(metafile)
    img = load_image("1.jpg", 0, 0)
    res = detect(net, meta, img)
    Is there a ****release(net) or free(net)?**** method to close the net？

After several executions, CUDA out of memory
    


> Restart your computer and start the detector for one image/video and make sure the resolution is not too high in the cfg file you are using.

**Comment by yy2yy** [comment]
> What gpu are you using? Are you using full yolo model?

GTX1080， yes,  i use the yolov3-voc.cfg

**Comment by keko950** [comment]
if you are using python try deleting the object, with del keyword
https://www.programiz.com/python-programming/keyword-list#del

**Comment by yy2yy** [comment]
> if you are using python try deleting the object, with del keyword
> https://www.programiz.com/python-programming/keyword-list#del

Thank you. Too bad, it still doesn't work.

**Comment by keko950** [comment]
Delete the object, then call the garbage collector.
import gc
gc.collect()

**Comment by yy2yy** [comment]
> Delete the object, then call the garbage collector.
> import gc
> gc.collect()

oh, What should I do? It still doesn't work.

**Comment by keko950** [comment]
import gc

load network
delete network

gc.collect()

**Comment by yy2yy** [comment]
> import gc
> 
> load network
> delete network
> 
> gc.collect()

yes, i do this, but it still doesn't work.

**Comment by yy2yy** [comment]
Thank you very much, now i know how to solve it, the `void free_network(network *net)` can solve this problem. @keko950 @alexanderfrey
