### ISSUE TITLE
Problem with running the darknet in the "demo" mode

### ISSUE THREAD

**Issue by VanitarNordic** [AlexeyAB/darknet#34]
Hi,

I tried many times to connect the camera through network and IP address exactly like tutorial, but no success. I use SmartWebCam application, and when I copy-paste the address ( `http://192.168.1.2:8080/video?dummy=param.mjpg` ) in the browser, **it works and it shows the live video** but I always get the below error with darknet.

> video file: http://192.168.1.2:8080/video?dummy=param.mjpg
> Couldn't connect to webcam.
> : No error

**Comment by AlexeyAB** [comment]
@VanitarNordic Hi,

I think you used  `-c 0` in command line. You should use `-c 0` only for WebCamera (USB/V4L), but not for Network-camera: https://github.com/AlexeyAB/darknet#how-to-use-on-the-command-line

Try to use this command such as for simple video-file: `darknet.exe detector demo data/voc.data yolo-voc.cfg yolo-voc.weights http://192.168.1.2:8080/video?dummy=param.mjpg`

**Comment by VanitarNordic** [comment]
I use exactly your command but still the same error:

`darknet.exe detector demo data/obj.data yolo-obj.cfg backup/yolo-obj_2000.weights http://192.168.1.2:8080/video?dummy=param.mjpg`

**Comment by VanitarNordic** [comment]
also, long time no seen man, at least two weeks. personally I had missed you and worry to what happened, counting day and night for you to come back and find answers to some problems.

**Comment by AlexeyAB** [comment]
@VanitarNordic It's okay, it was the holidays and work.

I get this error only if I write wrong IP.
Did you build OpenCV with FFMPEG?

![FFMPEG](https://hsto.org/files/f66/49f/220/f6649f22053c45468d523f2bf8ec46ad.jpg)

**Comment by VanitarNordic** [comment]
I did not built the OPENCV. I just put it in the suitable directory to be detectable by darknet and compiled.

**Comment by AlexeyAB** [comment]
@VanitarNordic 

When you use simple mpeg video-**files**, did you get this error?

And when you try to use SmartWebCam did you get the same error as on image?

![error_webcam](https://cloud.githubusercontent.com/assets/4096485/23436100/683a6c5e-fe1a-11e6-968e-a66c51eff39b.jpg)

**Comment by VanitarNordic** [comment]
This is the error. I have not tried a video file yet. let me do that and tell you.

![error](https://cloud.githubusercontent.com/assets/18719591/23436371/7e1dc87c-fe1f-11e6-9347-86eb76a0ed0c.jpg)

**Comment by VanitarNordic** [comment]
Alright, I did that for a file either. the same error as above.

![2](https://cloud.githubusercontent.com/assets/18719591/23436599/5e7627e8-fe20-11e6-85d4-87befb37097f.jpg)

**Comment by AlexeyAB** [comment]
@VanitarNordic 

* Or you haven't the required video-codec: http://files2.codecguide.com/K-Lite_Codec_Pack_1295_Mega.exe
     * or download it from mirrors: http://codecguide.com/download_k-lite_codec_pack_mega.htm

* Or you should build OpenCV with flag WITH_FFMPEG by using cmake: https://cmake.org/files/v3.8/cmake-3.8.0-rc1-win64-x64.msi

Example how to build: http://www.codepool.biz/building-opencv-with-cmake-on-windows.html

But set WITH_FFMPEG:
![FFMPEG](https://hsto.org/files/f66/49f/220/f6649f22053c45468d523f2bf8ec46ad.jpg)

**Comment by VanitarNordic** [comment]
@AlexeyAB 

Okay, I had not built it for VC14, because in the ReadMe you had mentioned: 

> If you have MSVS 2015, CUDA 8.0 and OpenCV 2.4.9 (with paths: C:\opencv_2.4.9\opencv\build\include & C:\opencv_2.4.9\opencv\build\x64\vc12\lib **or** vc14\lib), then start MSVS, open build\darknet\darknet.sln, set x64 and Release, and do the: Build -> Build darknet


change something in Visual Studio to get vc14 folder instead of vc12?

**Comment by VanitarNordic** [comment]
I got these two errors while I decided to CMake for vc14 on OpenCV-2.4.9 and build it using VS2015:

![2017-03-01_3-06-34](https://cloud.githubusercontent.com/assets/18719591/23439533/548fa072-fe2c-11e6-92bf-d2ca73b069ee.jpg)

![2017-03-01_3-07-07](https://cloud.githubusercontent.com/assets/18719591/23439536/59a12fcc-fe2c-11e6-943f-e9e985ac1f2d.jpg)

**Comment by VanitarNordic** [comment]
also one thing, this is trained on a custom dataset, not original VOC. that would cause an issue?

**Comment by AlexeyAB** [comment]
@VanitarNordic No, it does not matter - VOC or custom.

Check, is there `opencv_ffmpeg249_64.dll` in folders:
 * `C:\opencv_2.4.9\opencv\build\x64\vc12\bin`
 * `C:\opencv_2.4.9\opencv\build\x64\vc14\bin`

If this file is present, then copy it to near with `darknet.exe`

If is not present, then you can try simply to download `opencv_ffmpeg249_64.dll` and put it near with exe-file: https://drive.google.com/open?id=0BwRgzHpNbsWBTEhYTV9BY29yNDA
Can you now detect on video: `darknet.exe detector demo data/voc.data yolo-voc.cfg yolo-voc.weights test.mp4`

--------

If nothing above does not work, then build OpenCV with cmake.

> Should I change something in Visual Studio for the darknet to get vc14 folder instead of vc12?

Now in darknet-project used both vc14 and vc12 folders for lib. I think you should not change it.

**Comment by VanitarNordic** [comment]
Yesss, That worked, bingoo. 

The file `opencv_ffmpeg249_64.dll` had existed in the vc12 folder, just copy-paste it near `darknet.exe` and it worked. it is amazing why I was not getting any `.dll` absence error.

**Comment by VanitarNordic** [comment]
one thing I noticed is when I change the input video resolution of the camera/network camera, the darknet demo window size does not change, always it hold a fixed size. 

I mean the window size changes when we test the stream in a web browser, but Darknet shows the same window size with whatever camera resolution.
