### ISSUE TITLE
c++ wrapper?

### ISSUE THREAD

**Issue by keko950** [AlexeyAB/darknet#3401]
Hi @AlexeyAB , is yolo_v2_class.hpp the correct header to use with c++?

**Comment by acxz** [comment]
That is the correct header to use for C++ api, although you should also be able to use the C api (darknet.h) within C++. C++ allows the use of C code to be called and used, if certain conditions are met, such as wrapping C function prototypes with `extern "C"`.

**Comment by keko950** [comment]
Yes, i just tested it right now, thanks!
