### ISSUE TITLE
Adjusting Detection Bounding Box Size and Label Size on Windows

### ISSUE THREAD

**Issue by daylanc** [AlexeyAB/darknet#3404]
@AlexeyAB 
I am trying to adjust the bounding box and label sizes for the results from testing. I was able to do this on Linux successfully by modifying the `image.c` file and running `make` in the `/darknet` directory to build the changes to `image.c`.
In Windows 10, I copied the exact same `image.c` file over to Windows and tried to build with `build.ps1` in PowerShell. After running the detector test, the resulting predictions.png file does not seem to have smaller line-widths or smaller label font size. 
Is running the `build.ps1` script the correct way to push changes make to any of the `*.c` files?
Thanks.

**Comment by cenit** [comment]
Yes it is. Can you describe which lines you changed and if you enabled or not opencv?
