### ISSUE TITLE
Detecting contiguous existence of objects through frames

### ISSUE THREAD

**Issue by ianshmean** [AlexeyAB/darknet#342]
Is there a means in this fork to detect the age of the objects detected in a video? i.e. number of frames that the object has been detected. Or perhaps an easily implemented change to do so?

I asked the same question in the original git, detailing one strategy https://github.com/pjreddie/darknet/issues/420

**Comment by AlexeyAB** [comment]
@ianshmean Hi,

It isn't implemented, but it's easy to do.

For this you should use Darknet Yolo as DDL/SO-library:
* **Linux**: set `LIBSO=1` in the `Makefile` to build a library darknet.so and binary runable file `uselib` that uses this library. Or you can try to run so LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./uselib data/voc.names cfg/yolo-voc.cfg yolo-voc.weights test.mp4`

* **Windows**: at first compile `build\darknet\yolo_cpp_dll.sln` and then compile `build\darknet\yolo_console_dll.sln` then you can use `yolo_console_dll.exe data/voc.names cfg/yolo-voc.cfg yolo-voc.weights test.mp4`

But before this - you should do **4 changes in the source code** - I could forget something, but the general plan of action is:

1. add here counter for each object `unsigned int frame_counter;` https://github.com/AlexeyAB/darknet/blob/54f83e153549dd1a63bcc8fa5e55fb171621a989/src/yolo_v2_class.hpp#L31
2. add here increasing of this counter `cur_bbox_vec[cur_index].frame_counter= i.frame_counter+1;` https://github.com/AlexeyAB/darknet/blob/54f83e153549dd1a63bcc8fa5e55fb171621a989/src/yolo_v2_class.cpp#L293

3. Add in 2 places the initializing this counter:
* here: https://github.com/AlexeyAB/darknet/blob/54f83e153549dd1a63bcc8fa5e55fb171621a989/src/yolo_v2_class.cpp#L264-L265
```cpp
		for (size_t i = 0; i < cur_bbox_vec.size(); ++i) {
			cur_bbox_vec[i].track_id = det_gpu.track_id[cur_bbox_vec[i].obj_id]++;
			cur_bbox_vec[i].frame_counter = 0;
		}
```

* and here: https://github.com/AlexeyAB/darknet/blob/54f83e153549dd1a63bcc8fa5e55fb171621a989/src/yolo_v2_class.cpp#L300-L302
```cpp
	for (size_t i = 0; i < cur_bbox_vec.size(); ++i)
		if (cur_bbox_vec[i].track_id == 0) {
			cur_bbox_vec[i].track_id = det_gpu.track_id[cur_bbox_vec[i].obj_id]++;
			cur_bbox_vec[i].frame_counter = 0;
		}
```

4. change this line: https://github.com/AlexeyAB/darknet/blob/54f83e153549dd1a63bcc8fa5e55fb171621a989/src/yolo_console_dll.cpp#L54
to this: 
```cpp
if (i.track_id > 0) {
    obj_name += " - " + std::to_string(i.track_id) + " - " + std::to_string(i.frame_counter);
}
```

**Comment by ianshmean** [comment]
Wonderful, thanks!

**Comment by ianshmean** [comment]
For anyone wanting a version with these changes implemented: https://github.com/ianshmean/darknet/commit/17d9525148ecf30e7cde765a480f60ce757fba43
