### ISSUE TITLE
How to crop and save only detected object on single image

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [AlexeyAB/darknet#3432]
Hello, 
         I am running the YOLO model for the single object detection in the image and it detects my target object successfully and save the output but I want to crop and save only detected part rather than full image again, How can I do this? Can anyone help me with this problem?  I am detecting LCD from a given image. Please note I am using Single Image and detect a single object.  I am using this github repo for YOLLO.  https://github.com/AlexeyAB/darknet

**Comment by dreambit** [comment]
1) Compile darknet dll
2) Use darknet.py in this repo, that uses this dll, adjust script a little bit to crop detection by detection box coordinates.

**Comment by MuhammadAsadJaved** [comment]
@dreambit  The darknet is also compiled,  I am not expert about darknet backend operations, can you point out specific changes in the darknet.py file?

**Comment by MuhammadAsadJaved** [comment]
https://github.com/AlexeyAB/darknet/issues/954

This solution works for me, read the comments by nwthilina .
