### ISSUE TITLE
Pruned Yolo weights and fixed point

### ISSUE THREAD

**Issue by johnnydept** [AlexeyAB/darknet#344]
Hi @AlexeyAB , Have you tried pruned yolo weights? it has fewer parameters and expect less operations. Also, Alex have you tried implement fixed point gemm for Yolo?

**Comment by AlexeyAB** [comment]
@johnnydept Hi, no I havn't tried pruned yolo or fixed point, but I plan to use `int8` in the future.

**Comment by johnnydept** [comment]
duly noted
