### ISSUE TITLE
can i train qauntization-aware??

### ISSUE THREAD

**Issue by hwijune** [AlexeyAB/darknet#3440]
I want to do 8-bit training.

Can I use the -quantized option while training?

./darknet detector train cfg/yolov3.data cfg/yolov3.cfg darknet53.conv.74 -gpus 0,1 -map -dont_show -quantized

https://www.tensorflow.org/lite/performance/model_optimization

**Comment by AlexeyAB** [comment]
No.

**Comment by hwijune** [comment]
thank you

**Comment by abhigoku10** [comment]
@AlexeyAB  after quantization can re-train the model  and the model size is not reducing after quantization
