### ISSUE TITLE
Want to test Trident on DOTA Dataset but Rotation is not implemented

### ISSUE THREAD

**Issue by mdv3101** [AlexeyAB/darknet#3457]
There are a couple of issues with running yolo or trident on DOTA dataset.

1. Since these are satellite images rotation in data augmentation is a must... but it is missing in this repo.

2. Also the coordinates in the DOTA are x1,y2, x2,y2, x3,y3, x4,y4 tagged clockwise. 
This same issue is encountered in case of using yolo as a text detector because the angle of detection is not always a rectangle.

Thanks

**Comment by suman-19** [comment]
+1 
@AlexeyAB 
Can you tell me what changes are required for 8 point coordinates ? I would like to fork and make changes myself. I am also interested in using TridentNet on DOTA.

**Comment by dexception** [comment]
@mdv3101 @suman-19 
Checkout this repo:

The training format is same:

https://github.com/JKBox/YOLOv3-quadrangle
