### ISSUE TITLE
Unable to load weights from backup

### ISSUE THREAD

**Issue by GioLomia** [AlexeyAB/darknet#3458]
I am training on my custom data set, I followed all the instructions and it all seems to be working appropriately, loss and accuracy is also decreasing how it should. However every 100 iterations it throws an error:
Saving weights to backup//yolo-obj_last.weights
Couldn't open file: backup//yolo-obj_last.weights 
I can restart training with the weights manually and do that over and over again, but the problem is at 3000 iterations it does not save every 100.  So I can not move beyond 3000 iterations of training. I have deleted backup folder and created it again and all that however it is still not working.

**Comment by AlexeyAB** [comment]
It seems that you don't have permissions to save files to /backup/ folder.

Run darknet as `sudo `

**Comment by GioLomia** [comment]
> It seems that you don't have permissions to save files to /backup/ folder.
> 
> Run darknet as `sudo `

I will try, and post my response. Thank you very much!

**Comment by GioLomia** [comment]
I worked great!

**Comment by patrikszepesi** [comment]
Hi, I am having a similar issues, and I will try running it with sudo. however I do have one question. I started training again with the sudo permission, but I still dont have a backup folder. Will the backup folder be created on the fly after 100 iterations or should that already have been created before the training starts? thanks in advance.
