### ISSUE TITLE
Darknet does not output image

### ISSUE THREAD

**Issue by scrapmecanic3000** [AlexeyAB/darknet#3461]
I tried to run this test commmand: `./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg`

but in the end i got this: 

[yolo] params: iou loss: mse, iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
Total BFLOPS 65.864 
Loading weights from yolov3.weights...
 seen 64 
Done!
 Used AVX 
 Used FMA & AVX2 
data/dog.jpg: Predicted in 2807.262000 milli-seconds.
bicycle: 99%
dog: 100%
truck: 94%
OpenCV exception: show_image_cv 
OpenCV exception: wait_key_cv 
OpenCV exception: destroy_all_windows_cv 

**So i'm interested why this opencv exceptions happend and how to solve them?**

i'm running on : Ubuntu 19.04 and Opencv 4.1.0

**Comment by keko950** [comment]
How did you compile OpenCV? Can you show your Makefile?

**Comment by scrapmecanic3000** [comment]
this is darknet makefile: [https://pastebin.com/MCv1PX8N](url),
this how i compiled opencv: [https://towardsdatascience.com/how-to-install-opencv-and-extra-modules-from-source-using-cmake-and-then-set-it-up-in-your-pycharm-7e6ae25dbac5](url)

**Comment by keko950** [comment]
Are you running it in your own pc or in a server?

**Comment by scrapmecanic3000** [comment]
i'm running it on my own pc

**Comment by keko950** [comment]
Did you change any code in darknet?
Seems more like a problem with your OpenCV compilation

**Comment by scrapmecanic3000** [comment]
yes, reinstalled OpenCV and all worked!

**Comment by keko950** [comment]
Great!
