### ISSUE TITLE
Image Preprocessing for Training and Testing

### ISSUE THREAD

**Issue by nseidl** [AlexeyAB/darknet#3469]
Where can I find in the source preprocessing for images in training?
Are images scaled to 416x416 maintaining aspect ratio then padded with gray 128 to make up missing space, in training?

What is the Python Pillow / opencv implementation of resize_image that is used in test_detector?

**Comment by hitle451997** [comment]
you can see it in src/detector.c

**Comment by nseidl** [comment]
> you can see it in src/detector.c

Would you mind directing me to the specific lines where preprocessing during training happens?

**Comment by nseidl** [comment]
**First question:**
I can see that when running `detector test ...`, images by default (without `-letter_box`) are preprocessed using the `resize_image` function.

https://github.com/AlexeyAB/darknet/blob/aeb9da6918eaa5330a27803f8176a6314c716a7f/src/detector.c#L1322

https://github.com/AlexeyAB/darknet/blob/aeb9da6918eaa5330a27803f8176a6314c716a7f/src/image.c#L1276

What is a **similar python (opencv or pillow) implementation** of this `resize_image` methodology?

**Second question:**
**During training, what preprocessing is applied?** Is `letterbox_image` or `resize_image` used? Where in the source can I see how images are preprocessed during training? I've looked over `train_detector` several times but can't find where images are preprocessed during training.

**Comment by bakaryfayad** [comment]
hello @nseidl did obtain an answer to your question please?

**Comment by nseidl** [comment]
> hello @nseidl did obtain an answer to your question please?

https://github.com/AlexeyAB/darknet/issues/3119#issuecomment-506673120

**By default in this repo, images are stretched in training and in inference**.

Python (pillow) code:

```
from PIL import Image
image = Image.open(image_path)
image = image.resize((416, 416), Image.BICUBIC).convert('RGB)
return image
```
