### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by tuteming** [AlexeyAB/darknet#3472]
I compile the new (1 hour) darknet.sln, I get darknet.exe is ok.
but compile the yolo_cpp_dll.sln, I get one error, that is
Parser.obj : error LNK2001: Unresolved external symbol make_scale_channels_layer.
please check, thanks.

**Comment by AlexeyAB** [comment]
I just fixed it.
Download the latest Darknet.

**Comment by tuteming** [comment]
thanks
