### ISSUE TITLE
"darknet.exe has stopped working"

### ISSUE THREAD

**Issue by jobim3d** [AlexeyAB/darknet#348]
Hi, 
I'm trying to train tiny yolo with a FDDB database subset (faces)  taken from https://github.com/quanhua92/darknet/ (the mega.nz link), but after a while the program stops with no error, just the "darknet.exe has stopped working" popup.
The same happens training classical yolo.
This is my cfg file:
https://pastebin.com/eBwTMAXG
Can someone help?
Thank you very much.

**Comment by AlexeyAB** [comment]
@jobim3d Hi,
1. What command line do you use for training?
2. Do you `use subset_FDDB_for_darknet_yolo.zip` or `yolo_face_detection_fddb_v1.zip`?
3. Show your .data-file and first lines of train.txt 
4. Do you have images by the paths in the train.txt?

**Comment by jobim3d** [comment]
Hi,
I use the command
`darknet.exe detector train data\objtinyyolo.data tiny-yolo-voc.cfg darknet19_448.conv.23
`![screenshot](https://user-images.githubusercontent.com/19202880/35229690-505ca4f4-ff94-11e7-94ea-d8fd341416d2.png)


I use the `subset_FDDB_for_darknet_yolo.zip` file with Windows
my datafile:
```
classes= 1
train  = data/train.txt
valid  = data/test.txt
names = data/obj.names
backup = backuptinyyolo
```
my train file:
```
C:\Users\User\Desktop\JPEGImages\2002\07\19\big\img_130.jpg
C:\Users\User\Desktop\JPEGImages\2002\07\19\big\img_135.jpg
C:\Users\User\Desktop\JPEGImages\2002\07\19\big\img_141.jpg
```
Thanks for your help!

**Comment by AlexeyAB** [comment]
1. In your data-file `classes= 1`, but in your cfg-file there are 2 classes and filters=30 for two classes:
```
[convolutional]
size=1
stride=1
pad=1
filters=35
activation=linear
 
[region]
anchors = 1.08,1.19,  3.42,4.41,  6.63,11.38,  9.42,5.11,  16.62,10.52
bias_match=1
classes=2
```

2. If this problem can't be solved, then try to put all images `jpg-files` and labels `txt-files` in the one the same directory that hasn't in path such words as `JPEGImages`, `images` or `labels`.

And using this utility https://github.com/AlexeyAB/Yolo_mark create `train.txt` file - just run Yolo-mark with correct arguments, scroll at the end of images, and press `ESC` - train.txt will be creatd.

**Comment by jobim3d** [comment]
Hi,
I followed your suggestions and now I have labels and images in the same directory, config files are correct, but it crashes again.
Here's a debug screenshot that shows where the execution stops:
![imm](https://user-images.githubusercontent.com/19202880/35272930-183395c6-0037-11e8-99c0-fa4190aec850.png)
Can you understand what is the error?
Thank you again.

**Comment by Sennevds** [comment]
DId you fix this I have the same problem

**Comment by jobim3d** [comment]
Be sure you don't have 0.0000 or 0.000001 near values.

**Comment by Sennevds** [comment]
hhm I have more then 60000 labels will create a a python script to check

**Comment by VisionEp1** [comment]
what do you mean with "near values in the labels", Like values which are close to zero in the txt files?
