### ISSUE TITLE
Open Images v5 dataset Trained Model

### ISSUE THREAD

**Issue by uday60** [AlexeyAB/darknet#3485]
Please update.

**Comment by AlexeyAB** [comment]
@uday60 What do you mean?

**Comment by uday60** [comment]
A Pre Trained model for Open Images v5 is not available as the dataset has been updated by Google. 

https://pjreddie.com/media/files/yolov3-openimages.weights
I believe this model was trained on openimagesv4

https://github.com/pjreddie/darknet/blob/master/cfg/openimages.data

**Comment by LukeAI** [comment]
@uday60 you're being a little entitled, anyway it wouldn't make any difference - V5 and V4 are the same wrt. bounding box annotations.

**Comment by uday60** [comment]
@LukeAI No interested in model anymore. You guys don't worry about it.
