### ISSUE TITLE
Unable to disable CUDA in CMake

### ISSUE THREAD

**Issue by liuxingbaoyu** [AlexeyAB/darknet#3493]
It will be automatically enabled in https://github.com/AlexeyAB/darknet/blob/5ec35922d5215e11466a9bb1602f81d1746ccbe5/CMakeLists.txt#L59

**Comment by AlexeyAB** [comment]
Yes, I confirm, I also can not turn off the GPU when I use CMake-GUI. After pressing Configure or Generate button CUDA will be enabled forcibly, and in MSVS will be `GPU;CUDNN;CUDNN_HALF` definitions.

**Comment by AlexeyAB** [comment]
@cenit Hi, Can we solve this issue?

**Comment by cenit** [comment]
Yes sure. Sorry :)
I will open a PR asap

**Comment by AlexeyAB** [comment]
@liuxingbaoyu It seems this bug is fixed.
