### ISSUE TITLE
darknet: ./src/utils.c:293: error: Assertion `0' failed.  on two Tesla k80

### ISSUE THREAD

**Issue by Leo16112** [AlexeyAB/darknet#3496]
Hello Alexey,

I am trying to train the spp-scale model on two gpus K80 in cloud, but after some iterations in first epoch I get such errors (they output is different everytime) :
1)
CUDA status Error: file: ./src/dark_cuda.c : () : line: 309 : build time: Jun 22 2019 - 11:13:30 
CUDA status Error: file: ./src/dark_cuda.c : () : line: 309 : build time: Jun 22 2019 - 11:13:30 
CUDA Error: uncorrectable ECC error encountered
CUDA Error: uncorrectable ECC error encountered
CUDA Error: uncorrectable ECC error encountered: Success
CUDA Error: uncorrectable ECC error encountered: Cannot allocate memory
darknet: ./src/utils.c:293: error: Assertion `0' failed.
darknet: ./src/utils.c:293: error: Assertion `0' failed.

2)
 CUDA Error Prev: uncorrectable ECC error encountered
CUDA Error Prev: uncorrectable ECC error encountered: Success
darknet: ./src/utils.c:293: error: Assertion `0' failed.
CUDA Error Prev: uncorrectable ECC error encountered
CUDA Error Prev: uncorrectable ECC error encountered: Success

3)
CUDA Error Prev: uncorrectable ECC error encountered
CUDA Error Prev: uncorrectable ECC error encountered: Success
darknet: ./src/utils.c:293: error: Assertion `0' failed.

My nvcc --version :
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

nvidia-smi
Tue Jun 25 22:19:47 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 0000A357:00:00.0 Off |                    0 |
| N/A   42C    P0    73W / 149W |      2MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 0000C987:00:00.0 Off |                    0 |
| N/A   46C    P0    67W / 149W |      0MiB / 11441MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|

 I also can not change the GCards, because they provided for free though support program.  

Thank you very much,
Kind Regards,
Anton.

**Comment by AlexeyAB** [comment]
@Leo16112 Hi,

There are two reasons:

* Bug in driver - try to re-install CUDA, cuDNN and GPU-drivers. Read: https://stackoverflow.com/questions/21109792/wrong-results-of-a-cuda-dynamic-parallelism-code#comment31768648_21109792

* Bug in GPU - VRAM on your GPU cards are broken. Read: https://stackoverflow.com/a/11839929/1558037

Also:

You can try to increase `subdivisions` for example `batch=64 subdivisions=64` in cfg-file, so it will consume the minimum VRAM on GPU.

Or just try to use only 1 GPU by using flag in training command `-gpus 0` or `-gpus 1` instead of both GPUs.

**Comment by Leo16112** [comment]
@AlexeyAB 
Thank you very much for answer, Alexey. 

I think it was really hardware bug. Reinstall/use different version of Cuda/cudnn or change subdevision didn't help. But redeploying  of Vertual Machine helped.

Kind Regards,
Anton.
