### ISSUE TITLE
cannot open inlcude file pthread.h error in VS 2015

### ISSUE THREAD

**Issue by ddurgaprasad** [AlexeyAB/darknet#351]
Cloned git repository on Jan 25,2017 - master. Getting below error.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'pthread.h': No such file or directory	darknet	d:\sai\darknet\src\data.h	3	
```

**Comment by AlexeyAB** [comment]
* Try to update code from this repo, today there were made some fixes
* Check is there file `pthread.h` in the `d:\sai\darknet\3rdparty\include\`
* Try to check path to the `pthread.h` in MSVS 2015
(right click on project) -> properties -> C/C++ -> General -> Additional Include Directories, put here:
`C:\opencv_3.0\opencv\build\include;..\..\3rdparty\include;%(AdditionalIncludeDirectories);$(CudaToolkitIncludeDir);$(cudnn)\include`

**Comment by ddurgaprasad** [comment]
Setting include path to ..\..\3rdparty\include worked for me
