### ISSUE TITLE
Multiple images in one Darknet process

### ISSUE THREAD

**Issue by martisaju** [AlexeyAB/darknet#3510]
Hello, 
There is any manner to just execute one Darknet process and test multiple images (one at each iteration)?

I have a loop iteration where at each iteration a new image is taken. I just want to test each image avoiding to re-run Darknet.

Thank you so much!

**Comment by AlexeyAB** [comment]
To process a list of images data/train.txt and save results of detection to result.txt use:
`darknet.exe detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights -dont_show -ext_output < data/train.txt > result.txt`

**Comment by martisaju** [comment]
Thanks @AlexeyAB , but maybe I have not written it correctly. My problem is that I have a python loop that at each iteration it produces a new image. So, I would like to test this image (that overwrites the previous one) at each iteration by avoiding to re-run the Darknet model, just run darknet one time at the first iteration and then reuse it to evaluate the other images at each iteration.

**Comment by martisaju** [comment]
Hi @AlexeyAB I finally have achieved it.
I use the library 'pexpect' that allows to launch a program inside a python script with the function process = popen_spawn.PopenSpawn. Then, a function from that library called 'send' allows to pass an argument to that running process (process.send(arg)), in my case the image path.
In my case, I launch the program (.exe) at the beginning of the script defining that instance as a global variable. Then I just have to execute the send function at each iteration.
