### ISSUE TITLE
Problems About Tiny-YoloV2

### ISSUE THREAD

**Issue by PhilipWu526** [AlexeyAB/darknet#3519]
Hello, @AlexeyAB , Sorry for so many questions and my poor English.

1. Does the **General Rule** Suitable for Tiny-Yolov2, or changed the Tiny-Yolov2 architecture of the **Pooling Layer**?

    Ex.  **General Rule**
    > train_network_width * train_obj_width / train_image_width ~= detection_network_width * detection_obj_width / detection_image_width
    > train_network_height * train_obj_height / train_image_height ~= detection_network_height * detection_obj_height / detection_image_height

   1.1 train_obj_width and train_obj_height is talking about **real obj width&height** or **Label Box (Ground Truth) width&height** ?
2. The picture in my study are  1920x1080 images taken at different angles and at different distances. Do I need to turn on **multiscale-training** to improve the accuracy?

   2.1 While **multiscale-training** sometimes scales the image **too smaller**, does it affect the overall accuracy or something else?

    Ex. When I training, I set the training cfg width&height to 1216x512, so after scaling from 1920x1080 to 1216x512. According to 
    #292
   > After the image is resized to 416x416, the size of the object should be more than 1 pixel. So if you have image 832x832 and network width=416 height=416 (in the cfg-file), then object size on the image should be more than 4x4.
Good detection will be if your object size more than 32x32 after the image is resized to 416x416.

    #1475
    > detection object - you can see black point 1x1 pixels on the sky, and you can see where is it (coordinates), but you can’t see what is it: airplane, bird, quadrocopter, …
    > well recognizing object - you can see that this is a bird, because it’s size is 32x32 pixels so the contours and outlines of the object are visible

    If I want to have good accuracy, My object must have at least 50.5x67.5 pixel size in the 1216x512 image to be well recognized.
And my object pixel size in 1920x1080 images are about 30x50 ~ 180x800(Only category number one) & 52x70 ~ 400x800(Other categories). 
I have set the object label box(Ground Truth) about 70x90 ~ 400x800 pixels, but in the case of multiscale-training, sometimes the image is resized to 960x384 so that the object needs to be larger than 64x90 pixels to be well recognized.

3. Because my research is to instantly **recognize the characters** on the license plate on the mobile device, I want to strike a balance between the amount of calculation and the accuracy, and I am thinking about the fixed object size, image size , training size and detection size. Can the **big label box (Ground Truth)** and the **small label box (Ground Truth)** get the same accuracy?
[My research example](https://github.com/AlexeyAB/Yolo_mark/issues/138#issue-447127777)

    Ex. In my research, I used 1920x1080 images. The object I want to identify in the image is only about 50 pixels. If I upgrade the label box from 55 pixel to 75 pixel, will it affect the accuracy and positioning? Or is there some other problems?

4. In setting the number of Grid and Anchor Box, is it necessary to give priority to the number of Grids or the number of Anchor Boxes in order to have good accuracy and low computation?

Thanks for reading my question, if u have any suggestions or questions are welcome.

**Comment by PhilipWu526** [comment]
@AlexeyAB 

For Question 3
I am trying to train these two different box models to compare the results.

**Comment by AlexeyAB** [comment]
@PhilipWu526 Hi,

1. General rule suitable for any Yolo models

* All in pixels, then the rule
    `train_network_width * train_obj_width / train_image_width ~= detection_network_width * detection_obj_width / detection_image_width`

* Or `train_network_width` in pixels from cfg-file, and `train_obj_width_label ` from labels (0 - 1)
    then the rule
    `train_network_width * train_obj_width_label ~= detection_network_width * detection_obj_width_label`

2. random=1 can improve accuracy if you will train much more iterations or if you will use this model at different width, height than during training

> 2.1 While multiscale-training sometimes scales the image too smaller, does it affect the overall accuracy or something else?

This is normal.

> If I want to have good accuracy, My object must have at least 50.5x67.5 pixel size in the 1216x512 image to be well recognized.

This rule is basically necessary to observe when it is detected (and to a lesser extent when learning)

> If I upgrade the label box from 55 pixel to 75 pixel, will it affect the accuracy and positioning? Or is there some other problems?

If you just label with more padding to achieve 75 pixels, then it doesn't increase accuracy. You should increase width and height in cfg-file.


> In setting the number of Grid and Anchor Box, is it necessary to give priority to the number of Grids or the number of Anchor Boxes in order to have good accuracy and low computation?

I think, if in both cases you use absolutely the same layers and network resolution then
* if all objects have ~ the same size, then it's better to use higher number of cells in Grid
* if objects have different sizes, then better to use higher number of anchors

**Comment by PhilipWu526** [comment]
@AlexeyAB , Thank you very much, it helps me a lot!

But I also have some questions about your answer, please help me to solve these problems.

1.
> Or train_network_width in pixels from cfg-file, and train_obj_width_label from labels (0 - 1)
then the rule
train_network_width * train_obj_width_label ~= detection_network_width * detection_obj_width_label

What is **(0 - 1)** mean ?
Is this talking about ratio ?
Ex. 
train_obj_width = 50 pixel, train_obj_width_label = 60 pixel
train_obj_width / train_obj_width_label = 0.83 

2.
> If I want to have good accuracy, My object must have at least 50.5x67.5 pixel size in the 1216x512 image to be well recognized.
And my object pixel size in 1920x1080 images are about 30x50 ~ 180x800(Only category number one) & 52x70 ~ 400x800(Other categories).

If i want good accuracy, i should increase width and height in cfg-file bigger than 1216x512, maybe is 1760x704 ? 
If this is the case i use 1760x704 in cfg-file, Just like using the original image without resize?
3.
> This rule is basically necessary to observe when it is detected (and to a lesser extent when learning)

What is **and to a lesser extent when learning** mean ?

**Comment by PhilipWu526** [comment]
Hello, @AlexeyAB.
After the experiment

> For Question 3
I am trying to train these two different box models to compare the results.

As you said, Small Box is better than Big Box.

**Comment by PhilipWu526** [comment]
![image](https://user-images.githubusercontent.com/35833760/60656621-59245080-9e82-11e9-80a5-dffd2d25f6eb.png)

**Comment by PhilipWu526** [comment]
@AlexeyAB please help me to solve my questions.

**Comment by PhilipWu526** [comment]
@AlexeyAB , Thank you very much, it helps me a lot!

But I also have some questions about your answer, please help me to solve these problems.

1.
> Or train_network_width in pixels from cfg-file, and train_obj_width_label from labels (0 - 1)
then the rule
train_network_width * train_obj_width_label ~= detection_network_width * detection_obj_width_label

What is **(0 - 1)** mean ?
Is this talking about ratio ?
Ex. 
train_obj_width = 50 pixel, train_obj_width_label = 60 pixel
train_obj_width / train_obj_width_label = 0.83 

2.
> If I want to have good accuracy, My object must have at least 50.5x67.5 pixel size in the 1216x512 image to be well recognized.
And my object pixel size in 1920x1080 images are about 30x50 ~ 180x800(Only category number one) & 52x70 ~ 400x800(Other categories).

If i want good accuracy, i should increase width and height in cfg-file bigger than 1216x512, maybe is 1760x704 ? 
If this is the case i use 1760x704 in cfg-file, Just like using the original image without resize?
3.
> This rule is basically necessary to observe when it is detected (and to a lesser extent when learning)

What is **and to a lesser extent when learning** mean ?

**Comment by AlexeyAB** [comment]
> What is (0 - 1) mean ?
> Is this talking about ratio ?

This is range of values
