### ISSUE TITLE
what's the better way to use valid ?

### ISSUE THREAD

**Issue by goodtogood** [AlexeyAB/darknet#353]
Hi, there
    currently I just have 20k images and two classes,  for darknet which way is better to improve IoU ?

1. all 20k images were used for training and validating 

```
classes= 2
train  = data/train.txt
valid  = data/train.txt
names = data/obj.names
backup = data/obj/
```

2.  spliting 20k images into train and val , 18k for training and 2k for validating 

```
classes= 2
train  = data/train.txt
valid  = data/val.txt
names = data/obj.names
backup = data/obj/
```

thanks !

**Comment by AlexeyAB** [comment]
@goodtogood Hi,

* If you want to get the highest IoU for valid, then you should use 1
* If you want to get the highest IoU for images that aren't in train.txt or valid.txt, and want to avoid overfitting, then you should use 2

**Comment by goodtogood** [comment]
very clear, thank you so much !
