### ISSUE TITLE
Please help me! I need the tracking function

### ISSUE THREAD

**Issue by nxsf8023** [AlexeyAB/darknet#3545]
Now I have make the libdarknet.so but I can't find tracking function I used to use.
Could anyone tell me where I can find it,please.

**Comment by nxsf8023** [comment]
OK I find the function track_id in a cpp file. So I learn it and write it by python.

**Comment by xjohnxjohn** [comment]
@nxsf8023 Can you use track_id parameter with python ready?

**Comment by nxsf8023** [comment]
> 
> 
> @nxsf8023 Can you use track_id parameter with python ready?

Yes, I reproduction this algorithm use python

**Comment by xjohnxjohn** [comment]
@nxsf8023 you pull request ready? or independent.

**Comment by nxsf8023** [comment]
> 
> 
> @nxsf8023 you pull request ready? or independent.

It's independent in myself project.

**Comment by xjohnxjohn** [comment]
@nxsf8023 What the program you modified and how to show track_id in python? thanks you.

**Comment by nxsf8023** [comment]
> 
> 
> @nxsf8023 What the program you modified and how to show track_id in python? thanks you.
Sorry, the python code belong to my last company, and I can't share it.
But I think you can find the C code in yolo_v2_class.hpp.

**Comment by xjohnxjohn** [comment]
Thanks, @nxsf8023.

**Comment by xjohnxjohn** [comment]
@nxsf8023 i get track_id equal 0. How to set track_id to on?

**Comment by nxsf8023** [comment]
> 
> 
> @nxsf8023 i get track_id equal 0. How to set track_id to on?

U use python or C ?

**Comment by xjohnxjohn** [comment]
python

**Comment by nxsf8023** [comment]
> 
> 
> python

Do you find the track algorithm in  yolo_v2_class.hpp ? If you want to us track_id you must implementation it by yourself I think.

**Comment by xjohnxjohn** [comment]
I have some question to u. How about the accuracy that you modify with the SORT algorithm?

**Comment by nxsf8023** [comment]
> 
> 
> I have some question to u. How about the accuracy that you modify compare with the SORT algorithm?

In my scene it is useful, but I think if you want to use it in some complex scene, you should use other algorithm.
