### ISSUE TITLE
can i use the weights file on this project that i train on an other darknet?

### ISSUE THREAD

**Issue by TEOEFW** [AlexeyAB/darknet#3553]
hi @AlexeyAB
    i have trained the yolov3 with my own data,but i am not trained with your project. now i want to use the weihgts on your project with ZED. Can you tell me what should i do?  thank you！

**Comment by LukeAI** [comment]
Your weights trained with PJReddies implementation will work with AlexeyAB's

**Comment by TEOEFW** [comment]
Thanks so much! I did trained with PJReddies implementation and only trained to detect person. how can use it on this project i tried put the weights in cfg file and it didnt work

**Comment by LukeAI** [comment]
Not totally sure what you mean - what exactly did you try and do? What didn't work? Can you post the exact command and output?

**Comment by TEOEFW** [comment]
i am trying to work this project https://github.com/stereolabs/zed-yolo/tree/legacy/zed_cpp_sample. and i compile your project and it can work on the zed camera， then i want to use the weights that i trained then it can detect nothing.  i

**Comment by LukeAI** [comment]
Please post the exact command and output.

**Comment by TEOEFW** [comment]
like i said i am trying to work https://github.com/stereolabs/zed-yolo/tree/legacy/zed_cpp_sample.  i followed his readme. when i use this command ./darknet_zed ../../libdarknet/data/voc.names ../../libdarknet/cfg/yolov3.cfg ../../libdarknet/cfg/yolov3.weights
 i can get 
![image](https://user-images.githubusercontent.com/44308389/60707160-afa29500-9f3d-11e9-9cf1-77b7be8800c7.png)  then i want to use the weights i trained i change the command to./darknet_zed ../../libdarknet/data/voc.names ../../libdarknet/cfg/yolov3-voc-change.cfg ../../libdarknet/cfg/yolov3-voc_final.weights  then   i got this 
![image](https://user-images.githubusercontent.com/44308389/60707511-7e769480-9f3e-11e9-80ef-3ff76917bb41.png)
