### ISSUE TITLE
Change Epoch value

### ISSUE THREAD

**Issue by suravijayjilla** [AlexeyAB/darknet#3554]
Hi,

I am facing issue in darknet.
I am unable to change the epoch value.
Please give me the idea about this.

**Comment by suravijayjilla** [comment]
Hi,

Please tell me how to set the number of iterations.
In which i need to change..

**Comment by AlexeyAB** [comment]
@suravijayjilla Hi,

Read about `max_batches =` https://github.com/AlexeyAB/darknet/wiki/CFG-Parameters-in-the-%5Bnet%5D-section

**Comment by suravijayjilla** [comment]
@AlexeyAB  Hi,

Thanks..
