### ISSUE TITLE
dump training images

### ISSUE THREAD

**Issue by Arfinul** [AlexeyAB/darknet#3559]

**Comment by Arfinul** [comment]
is it possible to dump the images getting augmented while training?
which parameters in yolo.cfg are related to augmentation when I do training?

**Comment by AlexeyAB** [comment]
Use flag ` -show_imgs` at the end of training command

**Comment by Arfinul** [comment]
that's great.
can I dump in a specific directory?

**Comment by AlexeyAB** [comment]
Only by changing source code, since it is done for debugging: https://github.com/AlexeyAB/darknet/blob/5a6afe96d3aa8aed19405577db7dba0ff173c848/src/data.c#L940

`"specific_directory/aug_%d_%d_%s_%d"`
