### ISSUE TITLE
Darknet for regression

### ISSUE THREAD

**Issue by minhtcai** [AlexeyAB/darknet#3563]
Hi guys,

How can we use Darknet for regressions task such as house price predicting or ages predicting with confidence levels?

Thank you!

**Comment by drapado** [comment]
Hi @minhtcai,
In Darknet is almost impossible/extremely complicated since you'll have to change a lot of the code in the repo.
I suggest you go to a pytorch/tensorflow implementation of YOLOv3 an there you'll be able to change the output layers to your required output very easily.

**Comment by minhtcai** [comment]
Thank you very much!
