### ISSUE TITLE
CUDA error : ZED cam application dependency on libdarknet.so 

### ISSUE THREAD

**Issue by sriinnovasea** [AlexeyAB/darknet#3577]
I built libdarknet.so by enabling cuda, cudnn, opencv, libso and zed camera flags and built an independent ZED SVO reader C++ CMake application by linking it with libdarknet library. When I launch the app I am running into below CUDNN issue.

I have also initialized ZED cam with below params similar to yolo console dll application. 
initParams.sdk_gpu_id = detector.cur_gpu_id;
initParams.camera_buffer_count_linux = 2;  

Build environment:
CUDA - 10.0
CUDNN - 7.0
Ubuntu - 16.04

cuDNN status Error in: file: ./src/convolutional_kernels.cu : () : line: 539 : build time: Jul 10 2019 - 02:45:08 
cuDNN Error: CUDNN_STATUS_EXECUTION_FAILED
cuDNN Error: CUDNN_STATUS_EXECUTION_FAILED: Resource temporarily unavailable
biomass: ./src/utils.c:293: error: Assertion `0' failed

Please let me know if I need to set any other parameter to share CUDA context.

**Comment by AlexeyAB** [comment]
Also try to un-comment this line: https://github.com/AlexeyAB/darknet/blob/5a6afe96d3aa8aed19405577db7dba0ff173c848/src/yolo_console_dll.cpp#L340

**Comment by sriinnovasea** [comment]
@AlexeyAB  Thanks a lot for the pointer. Disabling the cuda context line fixed the issue.
