### ISSUE TITLE
estimate the train time

### ISSUE THREAD

**Issue by shuimoshusheng** [AlexeyAB/darknet#358]
Excuse me, how do I estimate the time spent using Yolo to train your own sample

**Comment by sivagnanamn** [comment]
At the end of every iteration, the bathch loss, avg.loss & timing metrics are logged.

**Comment by shuimoshusheng** [comment]
@sivagnanamn Thank you very much，but I have other questions！What type of GPU do you use and  how many pictures you have？What is the size of each picture？How to configure your cfg file？I hope you can tell me a little. Thank you very much.
ありがとうございますが、他の問題はありません。あなたはどんなジャンルのGPUを使いますか？写真は何枚ありますか。画像のサイズはどれくらいですか。どのようにあなたのCFG配置ファイル？教えていただき、ありがとうございます。

**Comment by sivagnanamn** [comment]
> What type of GPU do you use and how many pictures you have？

NVIDIA 1080 Ti

> how many pictures you have？

It depends on what you would like to do. More the number of images is better. For object detection I would suggest a minimum of 500-1000 images per object for a decent performance. Again this  changes according to the problem that you're trying to solve.

> What is the size of each picture？

Whatever may be the size of the train/test image, YOLO V2(default) configuration resizes it to 416x416. So any image size > 416x416 is better. I use 960x540 images.

For other information, you can refer 
[https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects](https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects)
[https://timebutt.github.io/static/how-to-train-yolov2-to-detect-custom-objects/](https://timebutt.github.io/static/how-to-train-yolov2-to-detect-custom-objects/)

**Comment by shuimoshusheng** [comment]
@sivagnanamn Thank you very much！

**Comment by shuimoshusheng** [comment]
@sivagnanamn 3: 38.326675, 137.756531 avg, 0.001000 rate, 2.843971 seconds, 192 images，Oh, and the last question. For this output log, how many pictures do you pick up each time, and how much is the total number of pictures?

**Comment by sivagnanamn** [comment]
The term that you're refering to is called "batch size". For every iteration, I used 64 images. This can be change in the cfg file (and you can configure it based on the memory size of your GPU). I use for openly available datasets like Imagenet, COCO etc & few custom datasets where I had ~1000 images per object.
