### ISSUE TITLE
Slow training/inferencing speed when using depthwise convolution

### ISSUE THREAD

**Issue by gmayday1997** [AlexeyAB/darknet#3580]
Hi, @AlexeyAB , I  trained three models ,based on different backbones, which are darknet-tiny-conv.14, mobilenetv2 and effcientNet-b0.
I found the performance of yolov3 based on mobilenetV2 or efficentNet-b0 are  better than yolov3-tiny, but those models are trained/inferenced at slow speed.
How can I enhance the inferencing/training speed? 
Thank you very much!!!

|Model        | Training Chart | FPS(1080Ti) | mAP% |
| ------------- |:-------------:| :-------------:| --------|
| darknet-tiny |![chart](https://user-images.githubusercontent.com/9024194/60972947-cf7cf300-a359-11e9-98a9-16692336eade.png)  | 100 | 68 |
| mobilenetv2 | ![mobilenet_chart](https://user-images.githubusercontent.com/9024194/60972935-c855e500-a359-11e9-83ff-82e75eba3e0a.png) | 8 | 72 |
| efficientNet-bo | ![effic_chart](https://user-images.githubusercontent.com/9024194/60972770-7d3bd200-a359-11e9-87b6-ce51b234b410.png)  | 9 | 72 |

**Comment by AlexeyAB** [comment]
The bottleneck is in the cuDNN-library and GPU, so only nVidia can solve this issue.

I think XNOR-net may be much better than Depth-wise and Pruning approaches.

**Comment by gmayday1997** [comment]
@AlexeyAB Thanks for your great suggestions. I will give a try. Thank you again!!

**Comment by hwijune** [comment]
can you share your cfg and weights file??
I want to test it.

**Comment by MichaelCong** [comment]
Hello, I'd like to change Darknet 53 to Mobilenet feature extraction. Now I have the cfg file ready. Where should I modify it? Thank you very much. Thank you for your code.@ @gmayday1997
