### ISSUE TITLE
Learning the Backgrounds, not the Objects. (Only 1 Class) Will this work?

### ISSUE THREAD

**Issue by WadRex** [AlexeyAB/darknet#3589]
So, I've tried to create a bot based on Object Detection (Enemy Players) and until now it works the way I wanted. The main problem is that the distance in the game between enemies and my bot can be very big, so the enemy model is very small. Because of that YOLO can't recognize anything in that area. I am wondering if this could work. ->If I record a 30 minute video, where I run over the whole map times and times again and try to capture every single corner of the map. This map is the only enviroment I am going to use, so it's not a big problem to capture every single pixel on the map. Will this work? Can I setup YOLO the way, that it learns the background and separates it from Enemy Model?

**Comment by AlexeyAB** [comment]
Yes, Yolo works in just that way.

Just Yolo resizes every image to the network size (width= height= in cfg file), so after resizing object can be smaller than 1x1 pixel, so Yolo can't detect it. You should traing and detect with higher width & height.
