### ISSUE TITLE
question -- How to implement the following requirements (Conv1D, Sum Layer, Branching) without the need to reinventing the wheel?

### ISSUE THREAD

**Issue by arefasvadi** [AlexeyAB/darknet#3594]
I am not very aware of the details of the darknet and different layers. I would like to know if I can achieve the following requirements if possible with minimal implementation. I have also attached some part of the network I am trying to implement and this network will be used for 1D data.

1. First, Is there a way to achieve **Conv1D**? I thought if the kernel is of size (k,1) instead of (k,k) I should be able to get Conv1D functionality out of Conv2D implementation. But I think in the config files it only accepts size parameters and it duplicates it for both heigh and width of the window. What do you recommend to get Conv1D functionality?

2. Is it possible to get a **sum layer** that sums the outputs of two layers say A and B? I know this one is really simple to implement but I was thinking maybe I can use a shortcut layer right after the layer B and in the shortcut, it references to layer A to be summed.

3. I guess merging layers outputs can be done via a route layer. But, how to proceed **when a layer's output will be used by multiple coming layers as their input**? Is there any easy way to approach branching?

![image](https://user-images.githubusercontent.com/4344792/61189833-8c23cc80-a658-11e9-9e0d-0e26f61a0504.png)

**Comment by AlexeyAB** [comment]
1. Currently darknet takes only kernel_size, so `w=h=size`, so you can't use Conv1D without code modification

2. Yes, `[shortcut]` does `out[i]=in[i]+from[i]`, adds the outputs of the previous layer with the outputs of another layer (from=)

> I guess merging layers outputs can be done via a route layer. But, how to proceed when a layer's output will be used by multiple coming layers as their input? Is there any easy way to approach branching?

3. In both cases use [route] layer
```
# for example this layer with index = 5
[route]
layers = -1, -3 # concatenates outputs of layer-4 and layer=2

....

# use output of layer-5
[route]
layers = 5

....

# use output of layer-5
[route]
layers = 5
```
