### ISSUE TITLE
how to use Win32 compile the project?

### ISSUE THREAD

**Issue by LpfML** [AlexeyAB/darknet#36]
hello ,I have compiled the project with x64 successful. but now , I want to use Win32 to compile the project , my environment is VS2013 that have update5, CUDA 8.0 . I changed the 3rdparty path to x86  as corresponded.  but when I compile the project. there is some errors about CUDA. can you help me ? thank you very much.

**Comment by AlexeyAB** [comment]
I never tried to compile Yolo for Win32, so I think it can't be compiled to use Win32 with CUDA 7.0 and greater.

Yolo uses `cublas.lib` and `curand.lib` but Win32-versions of these libraries are not available in CUDA 7.0 or greater: http://developer.download.nvidia.com/compute/cuda/7_0/Prod/doc/CUDA_Toolkit_Release_Notes.pdf
> The CUDA Toolkit no longer supports 32-bit Windows operating systems. Furthermore, the Windows CUDA Driver no longer supports Tesla and Quadro products on 32-bit Windows operating systems. Additionally, on 64-bit Windows operating systems, the following features are no longer supported by the CUDA driver or CUDA toolkit:
> ‣ Running 32-bit applications on Tesla and Quadro products
> ‣ Using the Thrust library from 32-bit applications
> ‣ 32-bit versions of the CUDA Toolkit scientific libraries, including **cuBLAS**, cuSPARSE, cuFFT, **cuRAND**, and NPP
> ‣ 32-bit versions of the CUDA samples

**Comment by LpfML** [comment]
thank you very much for your answer. Because some Dependency Library,  my project have to compile with win32.  Today, after seeing your answer,   I try to compile the  project with CUDA 6.5 and the win32 environment, and  successfully at last. thank you.

**Comment by xilongWang** [comment]
how to use yolov2 on Win32,I want to use yolov2 on CPU X86,but i failed!please provide some idea!

**Comment by Arctanxy** [comment]
I have some problem in compiling with cuda 6.5 and win32, could you help me ?
