### ISSUE TITLE
Cannot load image on linux!

### ISSUE THREAD

**Issue by TEOEFW** [AlexeyAB/darknet#3602]
hi Alex:
           when i train the yolov3 wtih VOC format data.when i run ./darknet detector train build/darknet/x64/cfg/voc.data build/darknet/x64/cfg/yolov3-voc.cfg darknet53.conv.74
it shows "cannot load image"
![image](https://user-images.githubusercontent.com/44308389/61294382-43ab1100-a808-11e9-9de5-4ff20f0515aa.png)
![image](https://user-images.githubusercontent.com/44308389/61294400-4e65a600-a808-11e9-916b-4ba30b84e630.png)
 can you help me out with it ? Thanks.

**Comment by ZhuangRogan** [comment]
How do you solve this problem?

**Comment by TEOEFW** [comment]
its the path. your train.txt should be like this 
![image](https://user-images.githubusercontent.com/44308389/61590753-2f905680-abf0-11e9-8639-1cc5ff183ac4.png)

**Comment by yojayc** [comment]
I solved by referenced https://blog.csdn.net/qcy1026/article/details/98957693

**Comment by KDcx35** [comment]
> I solved this problem by referenced https://blog.csdn.net/qcy1026/article/details/98957693
Thank you！
