### ISSUE TITLE
Darknet Yolo on QtCreator QT5

### ISSUE THREAD

**Issue by dedetuga** [AlexeyAB/darknet#3615]
Hi,
some one is able to build darknet yolo on QTcreator  with gui???

I'm trying do it, but I have no idea how to user the Import "Include/darknet.h"

Some one can help?
Thanks

**Comment by dsgh2** [comment]
Windows? Linux?
If I had much time, I would manage to make it.

I think if you only plan to do inference something in windows, you may use darknet as dll like below,
https://github.com/AlexeyAB/darknet#how-to-use-yolo-as-dll-and-so-libraries 

And then it can be used into Qt code just like a C++.

Also, I found this one. It may help.
https://github.com/dnzzcn/darknetGUI

**Comment by dedetuga** [comment]
Hi, @dsgh2 
Thanks for reply

> Windows? Linux?
In Linux I'm running qtcreator in linux 

I already load the C API: [darknet.h](https://github.com/AlexeyAB/darknet/blob/master/include/darknet.h) to my project but now what? I have no clue what to do with it and how to use it.

My idea is use my webcam with darknet and show the image and preditions list and percentages on my GUI, something like a GUI version of the next command:
`./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights
`

> And then it can be used into Qt code just like a C++.

Yes, I already got there but what code I use, where to get examples or info how to use the the darknet.h file?

 
> Also, I found this one. It may help.
> https://github.com/dnzzcn/darknetGUI
I will check


Thanks for reply

**Comment by cenit** [comment]
I think the best way to use darknet as a library is installing it though vcpkg.
Then in a CMake project, you just need to do `find_package(Darknet)` and then `target_link_libraries(myproject PRIVATE Darknet) and everything *should* work...

I think I should add to the readme a very minimal example

**Comment by dedetuga** [comment]
Hi @cenit,
I Found a project that uses the library directly from source, [check here](https://bitbucket.org/ChernyshovYuriy/darknetapp/src/master/), and I'm trying to build my own around this one, but, I want add more functionalities, for that I need  to know what  code do what and what code I must use to do something, I think It was very useful a list of commands and implementations like:

Load network
apply to network from image fille
or from video
examples will help a lot too

this kind of stuff ....this will be very useful, especially for noobs on neural network like me
thanks

**Comment by dedetuga** [comment]
I'm starting from [here](https://bitbucket.org/ChernyshovYuriy/darknetapp/src/master/)

**Comment by cenit** [comment]
@dedetuga I also have this minimal example on how to work with this repository (even better if using vcpkg to install darknet!) 
https://github.com/cenit/darkapp
