### ISSUE TITLE
What's the difference between this repo and pjreddie/darknet?

### ISSUE THREAD

**Issue by chwangteng** [AlexeyAB/darknet#3623]

**Comment by chwangteng** [comment]
What's the relationship between you and the author of darknet?

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet#improvements-in-this-repository

**Comment by chwangteng** [comment]
> https://github.com/AlexeyAB/darknet#improvements-in-this-repository

Are you in the same organization or you are separate developers? Many say that this repo is the offical document for darknet.

**Comment by AlexeyAB** [comment]
Joseph stopped working on the original repository https://github.com/pjreddie/darknet and suggested that I further develop the project.

**Comment by AlexeyAB** [comment]
Also new features: https://github.com/AlexeyAB/darknet/projects
