### ISSUE TITLE
Using YOLO with small input size for small images

### ISSUE THREAD

**Issue by zrion** [AlexeyAB/darknet#3635]
Hey there,

So I attempt to use YOLO for a time-restricted application. Therefore, I want to ask if YOLO can be used with a small input size (much smaller than the common size -416, 608, etc.), says, 32 x n with n = 1 or 3 or some acceptable values around that, if my input images are also very small, for example, 32x32? The purpose is to (possibly) speed up the prediction step.

Thanks!

**Comment by AlexeyAB** [comment]
Yes, Yolo v3 can be used for 32x32 input. 
I think its enough to use yolov3-tiny.cfg for 32x32 network size.
