### ISSUE TITLE
FPS for LSTM model training?

### ISSUE THREAD

**Issue by WadRex** [AlexeyAB/darknet#3645]
Hello,
I have 2 questions to ask, before starting gathering my dataset.
1) In this comment https://github.com/AlexeyAB/darknet/issues/3114#issuecomment-494148968 you stated that "YoloV3-Tiny-Pan-LSTM" is outperforming common "YoloV3-SPP" both in Speed and mAP. Those models were trained on 250 train + test images. Will  "YoloV3-Tiny-Pan-LSTM" outperform SPP model with much higher Train/Test Images?
2) What Video FPS should I be using for LSTM model? 15/30/60?
Or should I just see, what FPS will I get on small dataset with this model and then collect dataset with this FPS?

**Comment by AlexeyAB** [comment]
@WadRex Hi,

>  Will "YoloV3-Tiny-Pan-LSTM" outperform SPP model with much higher Train/Test Images?

Yes.

> Or should I just see, what FPS will I get on small dataset with this model and then collect dataset with this FPS?

Yes. You should see how much FPS you will get with this model on any video, and grab the same number of frames per second.

Also there is `augment_speed=3` parameter that randomly skeeps 0 to 2 frames in the training dataset for one sequence. So if you train on all frames from 60 FPS video, then your model will detect objects if it will work with 60, 30 or 20 detection0FPS on the same 60 FPS video.

**Comment by WadRex** [comment]
> Also there is `augment_speed=3` parameter that randomly skeeps 0 to 2 frames in the training dataset for one sequence. So if you train on all frames from 60 FPS video, then your model will detect objects if it will work with 60, 30 or 20 detection0FPS on the same 60 FPS video.

So if I know exact FPS I will be running my model on, should I just remove that parameter?

**Comment by AlexeyAB** [comment]
@WadRex 

> So if I know exact FPS I will be running my model on, should I just remove that parameter?

Yes.

But I would recommend you to leave it. Because model will learn to detect objects with different movement speed.

**Comment by WadRex** [comment]
Perfect. Thank you
