### ISSUE TITLE
test a custom trained data set

### ISSUE THREAD

**Issue by YeetMasterYeet** [AlexeyAB/darknet#3662]
hello everyone, after speding hours on training yolov3 tiny model to detect a custom dataset, i have reached a correct avg loss, but wheni try to test out my new weights file on a test image i do not get satisfactory results, i get my image filled with all of the possible stuff that darknet is allready pre trained for.
is this the wright command to test out a weights file? :  "darknet.exe detect cfg/yolov3-tiny.cfg yolov3-tiny-obj_last.weights data/testimage.jpg"

**Comment by AllenCaoo** [comment]
I believe the command should be "darknet.exe detector test cfg/yolov3-tiny.cfg yolov3-tiny-obj_last.weights data/testimage.jpg"

You can also use "darknet.exe detector test cfg/yolov3-tiny.cfg yolov3-tiny-obj_last.weights -thresh 0.25". Then you type in the path of your desired image.

Also, it seems like you are using "yolov3-tiny.cfg", which was from the original code. It should work if you use the cfg file you trained your model with, unless you used "yolov3-tiny.cfg" for your training.

**Comment by YeetMasterYeet** [comment]
Thanks AllenCaoo.
