### ISSUE TITLE
Transfer learning in YOLOv3 using darknet

### ISSUE THREAD

**Issue by SambuddhaX** [AlexeyAB/darknet#3669]
@AlexeyAB  could you please help me out on how to implement Transfer learning using YOLOv3 and darknet. And I would like to do that without updating the weights of the initial layers trained previously. Any help will be appreciated. Its urgent.

**Comment by SambuddhaX** [comment]
@AlexeyAB @cenit  Please help me out with this: https://github.com/AlexeyAB/darknet/issues/3669#issue-473712259

**Comment by fadili101** [comment]
can i retrain my modified tiny cfg file width darknet53.conv.74

**Comment by SambuddhaX** [comment]
Yes you can. If you have already trained a model, you can save it in your own .conv file and train on further data using new subsequent layers. There is a separate section in the details of the repository for increasing accuracy. Please go through them minutely.

**Comment by spaul13** [comment]
can u plz tell me how to do transfer learning using this repo. I have a classification model (.cfg) file I have already trained that for 10K iterations, now I want to keep all other layers except the last twos as frozen layers and train for 1K iterations on my new dataset. Can u plz help me saying how to achieve that?

Here I am attaching the .cfg file also.
[myconvnet_yolo_tiny.cfg.txt](https://github.com/AlexeyAB/darknet/files/4200906/myconvnet_yolo_tiny.cfg.txt)
