### ISSUE TITLE
Detections are Shifted along the Direction of Motion on Videos

### ISSUE THREAD

**Issue by laclouis5** [AlexeyAB/darknet#3675]
Hi,

I ran some detectors on videos (`yolov3-tiny_3l` and `yolo_v3_tiny_pan_lstm` and noticed that detections seem to be shifted from their true positions, this occurs only when the "speed" is great.

My videos consist of crop fields seen from above (about 40 cm perpendicular to the ground) and the camera is moving parallel to the ground (1 km/h) along the row. The network learnt to detect stems (boxes are not optimal for this purpose as the size is not meaningful but I gave it a try).

The first screenshot is when the camera is still with respect to the crops and the second one is at about 1 km/h. Detections are slightly shifted to the left (the camera is moving to the right i.e. the image is moving to the left).

![Screenshot from 2019-07-29 11-29-36](https://user-images.githubusercontent.com/19164542/62038640-68cf5480-b1f6-11e9-9994-81dbb3973295.png)

![Screenshot from 2019-07-29 11-30-23](https://user-images.githubusercontent.com/19164542/62038658-6ec53580-b1f6-11e9-8fc7-6a46e94c3025.png)

Here is the command I ran (using the last repo update): 
`./darknet detector demo results/yolov3-tiny_pan_lstm_2/obj.data results/yolov3-tiny_pan_lstm_2/yolo_v3_tiny_pan_lstm.cfg results/yolov3-tiny_pan_lstm_2/yolo_v3_tiny_pan_lstm_best.weights GOPR1243.m4v -out_filename output.avi -thresh 0.15`

This issue does not occur when detecting on images (for instance images extracted from the video, during motion).

**Comment by AlexeyAB** [comment]
@laclouis5 Hi,

Set here `1` instead of 3 https://github.com/AlexeyAB/darknet/blob/4384065158d50924339c1fdec545b28188b6d635/src/demo.c#L40

and recompile

**Comment by lsd1994** [comment]
Hi @AlexeyAB Can you tell me what this parameter means, or in which cases I should change this parameter from 3 to 1. Thanks.
