### ISSUE TITLE
How can i get pre-trained weights in the format of conv?

### ISSUE THREAD

**Issue by dasmehdix** [AlexeyAB/darknet#3695]
Hi,
I already trained Yolo-V3 and Yolov3-tiny with my dataset.I want to train with other weights like Yolov3-spp etc.But I can not find `Yolov3-spp.conv.` file.

I can find `Yolov3-spp.weights` but i am looking for conv folder of its.(like darknet53.conv.74)
Where can i get weights to train and test my custom dataset?

**Comment by sexyHongGi** [comment]
./darknet partial cfg/yolov3-spp.cfg Yolov3-spp.weight yolov3-spp.conv.15 15

**Comment by dasmehdix** [comment]
> ./darknet partial cfg/yolov3-spp.cfg Yolov3-spp.weight yolov3-spp.conv.15 15

Where can i get` yolov3-spp.conv.15` file?

Or I just place weight file to the correctfolder and add path of the Yolov3-spp.conv.15 while i want to train?

Thanks, you are the man!

**Comment by futureflsl** [comment]
I used following command 
./darknet partial cfg/yolov3-spp.cfg Yolov3-spp.weight yolov3-spp.conv.15 15
but yolov3-spp.conv.15 size just 3.6M,Is it right?
