### ISSUE TITLE
How to add new files (header and source to project)

### ISSUE THREAD

**Issue by Jumabek** [AlexeyAB/darknet#37]
Hi, sorry if my question is trivial, but I am new to windows and visual C.

I wanted to add some additional functions. Therefore, when I added below two Files and then compile, VS is not compiling.

 temp_header.h
```
#pragma once
void some_function();

```

and 
temp_source.cpp
```

#include <iostream>
#include "temp_header.h"
void some_function() {
	printf("hey I am a definition of the function in temp_header");
}
```

After adding this, it is not building and giving me a lot of errors.

So I was thinking, maybe I need to perform some extra step when I add new source.

Could you guyz help me out, Alex?

Thanks!

**Comment by AlexeyAB** [comment]
I fixed it. Try to update last commits.

**Comment by Jumabek** [comment]
Works like a Charm, Thanks a lot!
