### ISSUE TITLE
CUDA error : out of memory : No erro

### ISSUE THREAD

**Issue by SJRogue** [AlexeyAB/darknet#370]
[EDIT: Turned down the batch parameter to 16 and it seems to work]

Hi Alexey,

Do you have the time to look into this or answer this?
Currently I have gotten to the point where everything is installed, and everything works, i can get the existing cmd's to run, and I'm running with cuDNN.

I have also made a structure (1 .names file, 1 .data file, 1 training.txt file, 1 directory with 170 images with .txt file for each image with coördinates inside [made with the yolo_mark] )

I implemented my model in the correct folder near darknet.exe (put the correct files in the data folder etc..)

But, i get the following error: 

Can you help me out as to where to look? Am I supposed to decrease the batch parameter, are my image files the wrong sizes (does this even matter?) ? 

I can see the problem is somewhere during step 6 of the .ckg file. 

Thanks a lot.

CMD error:
![afbeelding](https://user-images.githubusercontent.com/10557456/35781349-4e637dc6-09e9-11e8-93ad-f8c2b116bae2.png)

CKG File:
[net]
batch=64
subdivisions=8
height=416
width=416
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.0001
max_batches = 45000
policy=steps
steps=100,25000,35000
scales=10,.1,.1

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky

#######

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[route]
layers=-9

[reorg]
stride=2

[route]
layers=-1,-3

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=30
activation=linear

[region]
anchors = 1.08,1.19,  3.42,4.41,  6.63,11.38,  9.42,5.11,  16.62,10.52
bias_match=1
classes=1
coords=4
num=5
softmax=1
jitter=.2
rescore=1

object_scale=5
noobject_scale=1
class_scale=1
coord_scale=1

absolute=1
thresh = .6
random=0

**Comment by AlexeyAB** [comment]
Just try to increase `subdivision=16` or `32`.
Let this parameter remain the same: `batch=64`

The consumption of the GPU's memory is proportional ~ `batch / subdivision`

**Comment by SinghJorawar** [comment]
Thanks for the quick reply, Alexey

It worked with decreasing the batch but I will now do it the way you say. I have another question though but will ask this in a new post.
