### ISSUE TITLE
Transfer Learning using YOLOv3

### ISSUE THREAD

**Issue by SambuddhaX** [AlexeyAB/darknet#3711]
@AlexeyAB @cenit Could you please help me out in how to implement Transfer learning using Darknet while keeping the initial layer weights the same. Any link or other code sample will be helpful.

**Comment by rod-hendricks** [comment]
Are you referring to fine-tuning? There is a bullet point on how to do it in the how to improve object detection section.

**Comment by spaul13** [comment]
@SambuddhaX @rod-hendricks  can u plz tell me how to do transfer learning using this repo. I have a classification model (.cfg) file I have already trained that for 10K iterations, now I want to keep all other layers except the last twos as frozen layers and train for 1K iterations on my new dataset. Can u plz help me saying how to achieve that?

Here I am attaching the .cfg file also.
[myconvnet_yolo_tiny.cfg.txt](https://github.com/AlexeyAB/darknet/files/4200902/myconvnet_yolo_tiny.cfg.txt)

**Comment by SambuddhaX** [comment]
@spaul13  Hey, sorry for the late reply. I found a link that helped me with the work. I dont know if you have tried this so here's the link: [https://stackoverflow.com/questions/57574922/how-to-do-transfer-learning-in-darknet-for-yolov3](url)
