### ISSUE TITLE
How to train yolov3 to improve accuracy of one class in COCO?

### ISSUE THREAD

**Issue by rod-hendricks** [AlexeyAB/darknet#3719]
Hi Alexey,

Wanted to ask for your advice on how I should approach on training to improve just a single class of the existing yolov3 on COCO. For example i just want to improve bicycle detection and have access to bicycle data that i label in yolo format that is not part of the COCO dataset. What should I change in the cfg files to still maintain the accuracy of the 79 classes while just improving the bicycle class?

**Comment by LukeAI** [comment]
I think you should download the original coco dataset and train with all of the original data plus your new data. Just make sure that if there is other stuff in your new photos that it is labelled properly as well.
You could extract the 53 darknet layers from the coco weights if you want to train with it quickly. Or you could start from scratch if you have the GPU time.

**Comment by rod-hendricks** [comment]
Thanks a lot Luke! I did start training it the way you suggested but using only the val data of the coco dataset since it is smaller just to see how it behaves. So far it looks like the learning of the fine-tuning approach is stable but training does take a while since training is still being done on the full 80 classes. 
I'm glad to hear that at least my approach wasn't that far off. I guess you can never really pinpoint training at a class level without breaking the other existing trained classes or removing them altogether.
