### ISSUE TITLE
Slow start of the training on EC2 - 15 minutes first iteration

### ISSUE THREAD

**Issue by SlavaKeshkov** [AlexeyAB/darknet#3726]
Hello @AlexeyAB, I am running into the time issue when using an AWS p3.x2large instance with the instructions you suggested in https://github.com/AlexeyAB/darknet/issues/1380#issuecomment-412333942.

Upon the start of the training it goes extremely slow. It took more than 15 minutes to perform the first iteration.

See the screenshot of the training process:
 (next mAP calculation at 1000 iterations)
 1: 869.385681, 869.385681 avg loss, 0.000000 rate, 1150.092304 seconds, 64 images
Loaded: 0.000033 seconds

![time training](https://user-images.githubusercontent.com/44873863/62627436-b69c3900-b929-11e9-958a-3f48a2a8c45e.PNG)

I compiled make file with `GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=1
AVX=0
OPENMP=0
LIBSO=0
ZED_CAMERA=0`

I am not sure if that is normal. My dataset size is only about 1300 images and I am using the following command to start training `
./darknet detector train data/obj.data cfg/yolov3-tiny-kitchen.cfg yolov3-tiny.conv.15 -dont_show -map
`

**Comment by AlexeyAB** [comment]
Set again `GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=1 AVX=0 OPENMP=0 LIBSO=0 ZED_CAMERA=0`

Do

```
make clean
make
```

And don't use cmake.

**Comment by SlavaKeshkov** [comment]
Thanks @AlexeyAB, I got it fixed this way. Training super fast now
