### ISSUE TITLE
Makefile:92: recipe for target 'obj/convolutional_kernels.o' failed

### ISSUE THREAD

**Issue by Pratosha-29** [AlexeyAB/darknet#374]
Hi ,
I ran the command $ sudo make clean
$ sudo make all
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -c ./src/batchnorm_layer.c -o obj/batchnorm_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -c ./src/art.c -o obj/art.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -c ./src/region_layer.c -o obj/region_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -c ./src/reorg_layer.c -o obj/reorg_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -c ./src/super.c -o obj/super.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -c ./src/voxel.c -o obj/voxel.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -c ./src/tree.c -o obj/tree.o
nvcc  -gencode arch=compute_52,code=compute_52  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include" -c ./src/convolutional_kernels.cu -o obj/convolutional_kernels.o
/bin/sh: 1: nvcc: not found
Makefile:92: recipe for target 'obj/convolutional_kernels.o' failed
make: *** [obj/convolutional_kernels.o] Error 127

Facing this error.
Kindly help

**Comment by Pratosha-29** [comment]
The change that needs to be made is as follows:
If we are using Jetson Tx2 then:
 ARCH=  -gencode arch=compute_62,code=[sm_62,compute_62]
If we are using Jetson Tx1 then:
ARCH=  -gencode arch=compute_51,code=[sm_51,compute_51]

When these changes are made the object files get generated and hence the error is resolved.

**Comment by AlexeyAB** [comment]
@Pratosha-29 Thanks!

To solve this problem, should we use `ARCH= -gencode arch=compute_62,code=[sm_62,compute_62]` without any other CC in the Makefile?

Or can we just add CC6.2 at the end of ARCH in the Makefile?
```
ARCH= -gencode arch=compute_30,code=sm_30 \
      -gencode arch=compute_35,code=sm_35 \
      -gencode arch=compute_50,code=[sm_50,compute_50] \
      -gencode arch=compute_51,code=[sm_51,compute_51] \
      -gencode arch=compute_52,code=[sm_52,compute_52] \
      -gencode arch=compute_61,code=[sm_61,compute_61] \
      -gencode arch=compute_62,code=[sm_62,compute_62]
```

**Comment by Pratosha-29** [comment]
@AlexeyAB - 
Well these are the changes I made since I was trying to run the algorithm on Jetson TX2 . 
#ARCH= #-gencode arch=compute_20,code=[sm_20,sm_21] \
      #-gencode arch=compute_30,code=sm_30 \
      #-gencode arch=compute_35,code=sm_35 \
      #-gencode arch=compute_50,code=[sm_50,compute_50] \
ARCH=  -gencode arch=compute_62,code=[sm_62,compute_62]

**Comment by AlexeyAB** [comment]
@Pratosha-29 Thanks!
