### ISSUE TITLE
TensorRT in Readme

### ISSUE THREAD

**Issue by Nuzhny007** [AlexeyAB/darknet#3741]
In Readme:
> TensorRT for YOLOv3 (-70% faster inference): TensorRT & DeepStream

But Yolo was removed from this repository: https://github.com/NVIDIA-AI-IOT/deepstream_reference_apps/commit/1de58b59d11c13763085c9a3ece83092887177bd
The news: https://news.developer.nvidia.com/deepstream-sdk-4-now-available/

**Comment by AlexeyAB** [comment]
Yes. Yolo is removed. 
Yolo is natively supported in DeepStream 4.0

**Comment by AlexeyAB** [comment]
I changed Readme https://github.com/AlexeyAB/darknet#yolo-v3-in-other-frameworks
