### ISSUE TITLE
LSTM model. Same sequence, different FPS.

### ISSUE THREAD

**Issue by WadRex** [AlexeyAB/darknet#3747]
Hello,
Sometime ago I asked you about what FPS should I use on LSTM model. The answer was to get the same framerate I will get with the model.
I spent quite a bit of time to create script for automatic labeling. Now I basically only need to record a video, run a script, make minor correction and that's it. I can use it in NN.
My question is, since it's no problem to just create a lot of training data, with only limit being disk space, will it make sense to record a 240 fps footage and then train NN on 240/120/60/30/15 fps version of same footage? 
I know the LSTM model already has some sort of augmentation for FPS, but I guess my method combined with augmentation built in model will give me best results. Or will the model just overfit?

**Comment by AlexeyAB** [comment]
Yes, you can try.
