### ISSUE TITLE
Which model is the backbone for the tiny models?

### ISSUE THREAD

**Issue by LukeAI** [AlexeyAB/darknet#3751]
Which model is the backbone for the tiny models? I've been training darknet19 on imagenet with style transfer but I just read that darknet19 is the backbone for yolov2 - which is the .cfg for imagenet pretraining to transfer to the tiny-yolov3 series?

**Comment by LukeAI** [comment]
Oh, I see it's tiny.cfg ?
https://github.com/AlexeyAB/darknet/blob/master/cfg/tiny.cfg

**Comment by dexception** [comment]
I think darknet19 is being used for yolov3-tiny.

**Comment by LukeAI** [comment]
I believe that darknet19 is the backbone of Yolov2

**Comment by LukeAI** [comment]
it's actually apparently one the oncalled darknet.cfg not darknet19 or tiny
