### ISSUE TITLE
Inference time for different network size.

### ISSUE THREAD

**Issue by wolflion521** [AlexeyAB/darknet#3752]
Hi, I build two networks with the same configuration except the width and height. The first one is 224 x 224 and the second one is 96 x 96. But when I call these two networks using Opencv, their inference time is the same. I want to know why the smaller one is not fast, how should I speed up my model when the network size is small? Thanks a lot.

**Comment by sealedtx** [comment]
@wolflion521 Please share both of your cfg [net] section and your code to measure inference time

**Comment by AlexeyAB** [comment]
May be the bottleneck is in your code, which slows down inference time in both cases.

**Comment by wolflion521** [comment]
@sealedtx @AlexeyAB Hi, thanks for your response.  About the inference time, today I measure the mean of inference time of different networksize. Below is my code to measure. 
`        st=clk::now();
        cv::dnn::blobFromImage(frame,blob,1/255.0,cv::Size(inpWidth,inpHeight), Scalar(), true, false);
        net.setInput(blob);
        vector<cv::Mat> outs;
        net.forward(outs,getOutputNames(net));
        postprocess(frame,outs);
        ed=clk::now();`
And the result shows:
96 * 96 : time is 3.3 ms
192 * 192 : time is 4.3 ms
224 * 224: time is 5.3 ms
I suppose that 96 * 96 input should be one quarter of 224*224 inference time. Am I measuring in a wrong way?

By the way, below is the code to implement NMS, I copy it from other's tutorial, but the bbox from this piece of code will always shift to the left of the object, even though I detect from darknet demo the bounding box can be perfect. Where can I find proper NMS for yolo? Thanks to you all.
`void postprocess(cv::Mat& frame,const vector<cv::Mat>& outs){
    Mat outFrame = frame.clone();
    vector<int> classIds;
    vector<float> confidences;
    vector<cv::Rect> boxes;

    for(size_t i=0;i<outs.size();i++){
        
        float* data = (float*)outs[i].data;
        for(int j=0;j<outs[i].rows;j++,data+=outs[i].cols){
            cv::Mat scores = outs[i].row(j).colRange(5,outs[i].cols);
            cv::Point classIdPoint;
            double confidence;
            cv::minMaxLoc(scores,0,&confidence,0,&classIdPoint);
            if(confidence>confThreshold){
                int centerX = (int)(data[0]*frame.cols);
                int centerY = (int)(data[1]*frame.rows);
                int width = (int)(data[2]*frame.cols);
                int height = (int)(data[3]*frame.rows);
                int left = centerX-width/2;
                int top = centerY-height/2;

                classIds.push_back(classIdPoint.x);
                confidences.push_back((float)confidence);
                boxes.push_back(cv::Rect(left, top, width, height));
            }

        }

    }`

**Comment by AlexeyAB** [comment]
The higher network resolution - the more SIMD and Multithreading optimizations can be applied.

Also try to measure time only for inference, not for pre/post-processing:

```cpp
cv::dnn::blobFromImage(frame,blob,1/255.0,cv::Size(inpWidth,inpHeight), Scalar(), true, false); net.setInput(blob); 

st=clk::now();
vector<cv::Mat> outs; net.forward(outs,getOutputNames(net)); 
ed=clk::now();

postprocess(frame,outs); 
```

**Comment by wolflion521** [comment]
Thank you very much, this answer help a lot in understanding the inference timing.
