### ISSUE TITLE
detect image by calling yolo-cpp-dll

### ISSUE THREAD

**Issue by mama110** [AlexeyAB/darknet#3758]
I'm trying to detect image by calling yolo-cpp-dll.dll. And I meet an error in yolo_v2_class.hpp:
auto detection_boxes = detect(img, thresh, use_mean);

![webwxgetmsgimg](https://user-images.githubusercontent.com/40822074/62924712-4129e000-bde3-11e9-9be1-42877ca35663.jpeg)

my code is as follows:

main.cpp
int main() {

	yoloDetection *yd = new yoloDetection; 

	string  names_rgb_file = "E:/YOLOConfigFiles/voc.names";
	string  cfg_rgb_file = "E:/YOLOConfigFiles/yolov3-voc.cfg";
	string  weights_rgb_file = "E:/weights/yolov3.weights";

	Mat frame2 = imread("F:/darknet-master-dll/data/dog.jpg");
	vector<bbox_t> result_rgb_coordinate;
	

	result_rgb_coordinate = yd->detected_img(names_rgb_file, cfg_rgb_file, weights_rgb_file, frame2);
	yd->draw_boxes(frame2, result_rgb_coordinate, yd->objects_names_from_file(names_rgb_file));	
	imshow("img",frame2);
	waitKey(0);

	return 0;
}

utils.cpp:
vector<string> yoloDetection::objects_names_from_file(string const filename) {

	ifstream file(filename);
	vector<string> file_lines;
	if (!file.is_open()) return file_lines;
	for (string line; getline(file, line);) file_lines.push_back(line);
	file.close();
	return file_lines;
}

vector<bbox_t> yoloDetection::detected_img(string names_file, string cfg_file, string weights_file, Mat  img_file) { 

	Detector detector(cfg_file, weights_file);//³õÊŒ»¯Œì²âÆ÷
	auto obj_names = objects_names_from_file(names_file);//»ñµÃ·ÖÀà¶ÔÏóÃû³Æ
	vector<bbox_t> result_vec = detector.detect(img_file); //»ñµÃŒì²âœá¹û
	return result_vec;
}

void yoloDetection::draw_boxes(Mat mat_img, vector<bbox_t> result_vec, vector<string> obj_names) {

	int const colors[6][3] = { { 1,0,1 },{ 0,0,1 },{ 0,1,1 },{ 0,1,0 },{ 1,1,0 },{ 1,0,0 } };
	for (auto &i : result_vec) {
		Scalar color = obj_id_to_color(i.obj_id);
		rectangle(mat_img, Rect(i.x, i.y, i.w, i.h), color, 2);
		if (obj_names.size() > i.obj_id) {
			string obj_name = obj_names[i.obj_id];
			if (i.track_id > 0) obj_name += " - " + to_string(i.track_id);
			Size const text_size = getTextSize(obj_name, FONT_HERSHEY_COMPLEX_SMALL, 1.2, 2, 0);
			int const max_width = (text_size.width > i.w + 2) ? text_size.width : (i.w + 2);
			rectangle(mat_img, Point2f(max((int)i.x - 1, 0), max((int)i.y - 30, 0)),
				Point2f(min((int)i.x + max_width, mat_img.cols - 1), min((int)i.y, mat_img.rows - 1)),
				color, CV_FILLED, 8, 0);
			putText(mat_img, obj_name, Point2f(i.x, i.y - 10), FONT_HERSHEY_COMPLEX_SMALL, 1.2, Scalar(0, 0, 0), 2);
		}
	}
}

**Comment by Tony-TF** [comment]
Ye! The same thing happened to me,But i solved it .In Attribute manager ->VS Linker->input->Additional dependencies delete opencv_world345d.lib or opencv_world345.lib。This method can be solved
