### ISSUE TITLE
darknet.exe: command not found error

### ISSUE THREAD

**Issue by nirajvermafcb** [AlexeyAB/darknet#376]
I am running this on my ubuntu 16.04 system.Whenever I run the command mentioned "darknet.exe detector train data/obj.data yolo-obj.cfg darknet19_448.conv.23" from my terminal i get this error

darknet.exe: command not found error.

Do I need to go to a specific folder to run this command or is there anything I am missing?

**Comment by AlexeyAB** [comment]
On Linux use `./darknet` instead of `darknet.exe`

**Comment by nirajvermafcb** [comment]
@AlexeyAB  Now it is showing 

`bash: ./darknet: No such file or directory. 
`
Do I need to go to a specific path to run this?

**Comment by TheMikeyR** [comment]
@nirajvermafcb you need to build the system by running make, you can see all the details [here](https://github.com/AlexeyAB/darknet#how-to-compile-on-linux)

**Comment by nirajvermafcb** [comment]
Okay thanks it's done
