### ISSUE TITLE
9 channel training and detection

### ISSUE THREAD

**Issue by ycelik** [AlexeyAB/darknet#3780]
I couldn't find related issues to this so I wanted to ask you guys about your experience with 9 channel image training with this repo. How does it affect training, detection quality and inference time? When do you recommend using 9 channel instead of 3 channel?

**Comment by AlexeyAB** [comment]
What is in your additional 6 channels?
Is it Ifra-Red image or Depth-map from Stereo-camera?

**Comment by LukeAI** [comment]
How well does Yolo work on a 4 channel RGB-Depth image?

**Comment by ycelik** [comment]
My question is obsolete thank you. Closing.
