### ISSUE TITLE
About generate VOC label file

### ISSUE THREAD

**Issue by DoriHp** [AlexeyAB/darknet#3788]
I'm going to use [WIDER FACE dataset](http://shuoyang1213.me/WIDERFACE/) to train a face detector model in VOC format. But in dataset, some images have no object to detect, and they are described `<x> <y> <width> <height>` as 0 0 0 0. So with those cases, I should generate an empty file or a file containing `<class> <x> <y> <w> <h>` as 0 0 0 0 0?

I'm new with training yolo, smb help me :(

**Comment by lsd1994** [comment]
empty txt file

**Comment by DoriHp** [comment]
thanks for help
