### ISSUE TITLE
Couldn't open file: data/obj.data error

### ISSUE THREAD

**Issue by nirajvermafcb** [AlexeyAB/darknet#379]
I am using Ubuntu 16.04 system and I am trying to do detection on my own custom dataset. I am doing detection on only one single class. I did all the necessary changes mentioned in the configuration file and also I created **obj.names** and **obj.data**  and put them in their respective directories.Also I downloaded pretrained weights and put it in the directory mentioned and then when i run the command 
**./darknet detector train data/obj.data yolo-obj.cfg darknet19_448.conv.23 ** I get this error.

**Couldn't open file: data/obj.data error**

I am pretty sure I have created the file but still it is not able to locate it?
Am I missing out on something

**Comment by sivagnanamn** [comment]
Could you please double check and share the tree structure of your darknet directory? Are you executing the command from the root level?

**Comment by cvDreamer** [comment]
You need to make sure your compiled darknet binary is at the same level as data folder

**Comment by nirajvermafcb** [comment]
@cvDreamer  there is one data folder which is at the same level as compiled darket binary file but the instructions are for darknet/build/x64/data folder where I have to put all the images and configuration files.Which data folder are you talking about?

**Comment by nirajvermafcb** [comment]
@sivagnanamn  No I am executing the command by going inside the darknet folder where I have compiled darket binary file

**Comment by nirajvermafcb** [comment]
@AlexeyAB  @TheMikeyR

**Comment by cvDreamer** [comment]
You need to make sure the binary "darknet" is the same level of folder "data", such that when you are running command:
./darknet data/obj.data xxxxxx

your darknet binary knows where to find file obj.data; otherwise, your program will ask for the location, e.g. "Couldn't open file: data/obj.data error"

**Comment by devb2020** [comment]
Encountered the error: Couldn't open file: data/obj.data while training with yolov3 in windows, 
>darknet.exe detector train data/obj.data yolo-obj.cfg darknet53.conv.74

The obj.data is stored at the same level as darknet binaries at -->...\darknet\build\darknet\x64\data as per the guidelines "How to train (to detect your custom objects):"

Any ideas to resolve this error...?
