### ISSUE TITLE
Do non-labeled objects with empty txt files generate an wrong annotation warning?

### ISSUE THREAD

**Issue by cesarandreslopez** [AlexeyAB/darknet#3798]
And if so, is this OK or should the non-labeled pictures be "annotated" somehow else? 

From https://github.com/AlexeyAB/darknet#how-to-improve-object-detection it states that negative samples should have an empty txt. Not really sure if the occasional "wrong annotation warning" would be coming from the negative samples.

**Comment by iaixuexi** [comment]
Is it completely empty in the txt file?

**Comment by AlexeyAB** [comment]
> Do non-labeled objects with empty txt files generate an wrong annotation warning?

No.

**Comment by cesarandreslopez** [comment]
Got it. Thank you.
