### ISSUE TITLE
No Bounding box coordinates

### ISSUE THREAD

**Issue by another-dark-knight** [AlexeyAB/darknet#3802]
` if(bot > im.h-1) bot = im.h-1;
              printf("%s: %.0f%%", names[class_id], prob * 100);
              printf("\n - id: %d, x_start: %d, y_start: %d, x_end: %d, y_end: %d",
                class_id, left, top, right , bot);
`
I did the changes and then I did make clean followed by make. But the changes are not reflected. I still cannot see the bounding boxes. I had trained the model for single class classification prior to this. Do I need to retrain the model just to get the coordinates?

**Comment by another-dark-knight** [comment]
I also used a printf statement in image_opencv.cpp but it had no effect. I am unable to get the coordinates

**Comment by mehio** [comment]
Any luck???
I did the same! Still nothing! 
I noticed that it works for people with pjreddies image.c. The image.c in alexeyAB is different and this modification you are talking about is not working.

**Comment by mehio** [comment]
@another-dark-knight Let me know please

**Comment by another-dark-knight** [comment]
@mehio No luck on the .c file. I used the python API to print out the coordinates.

**Comment by mehio** [comment]
Hey i managed to print the coordinates using a darknet command .  No need to use the .c file .

Im using alexeyAB fork, not pjreddies

**Comment by shachitaku** [comment]
https://github.com/AlexeyAB/darknet#how-to-use-on-the-command-line
Output coordinates of objects: darknet.exe detector test cfg/coco.data yolov3.cfg yolov3.weights -ext_output dog.jpg

is this not the answer?
when i do it on mine i get things that look like this:
test2.png: Predicted in 11.823000 milli-seconds.
Kanji_Ten: 81%	(left_x:    2   top_y:  181   width:   10   height:   13)
Kanji_Ten: 90%	(left_x:   94   top_y:  398   width:   11   height:   10)
Kanji_Ten: 99%	(left_x:  272   top_y:  430   width:   12   height:   12)
Kanji_Ten: 94%	(left_x:  23   top_y:  633   width:   17   height:   18)
Kanji_Ten: 98%	(left_x:  371   top_y:  234   width:   10   height:   18)
Kanji_Ten: 60%	(left_x:  432   top_y:  410   width:   16   height:   17)
Kanji_Ten: 100%	(left_x:  700   top_y:  558   width:   21   height:   21)
Kanji_Ten: 100%	(left_x:  719   top_y:  240   width:   11   height:   12)

@mehio thanks i could output to .txt file using your way :)
