### ISSUE TITLE
How can I get anchors when random=1?

### ISSUE THREAD

**Issue by dsgh2** [AlexeyAB/darknet#3804]
Hi, everyone.
This may be a just simple question but I could not find the answer so far. 

How can I get anchors when random=1?
I understand that anchors should be calculated depending on input size.
However, I do not know what should I do when input varies by random=1, the input size varies not only in training but also testing depending on the situation.

Thanks in advance.

**Comment by lsd1994** [comment]
random=0 or 1 is only used in training.

**Comment by dsgh2** [comment]
> random=0 or 1 is only used in training.

Thank you. But I would like to know what anchor should be used.
The anchor in 320 differs from in  608. But input size varies like 320, 416, 608( or x1.4 random scale like this repo). What anchor should I use in training?

**Comment by lsd1994** [comment]
Use this to calculate anchors: 
darknet.exe detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416
-weight and -height are image size you want to train. Different size has different anchors and you can recalculate them.
BTW, you can train in 416x416 while test in 608x608 without changing the anchors, but the performance is not the best. If you want to test in 608x608, you'd better train same size.
