### ISSUE TITLE
Train YOLO with epoch number not batches ? 

### ISSUE THREAD

**Issue by phongnhhn92** [AlexeyAB/darknet#381]
This is from the original paper of YOLO:
We train the network for about 135 epochs on the training and validation data sets from PASCAL VOC 2007 and 2012. When testing on 2012 we also include the VOC 2007 test data for training. Throughout training we use a batch size of 64, a momentum of 0:9 and a decay of 0:0005

My question is when i look at the yolo-voc.2.0.cfg, I only see the max_batches declaration:
learning_rate=0.0001
max_batches = 45000
policy=steps
steps=100,25000,35000
scales=10,.1,.1

Is there anyways to train VOC pascal with the exact 135 epochs like the original paper ?

**Comment by AlexeyAB** [comment]
No, there is no way to set how many epochs to train yolo. But you can calculate it manualy.

* If we do this script, we can get 16 551 images in the train.txt
```
C:\Users\Alex\AppData\Local\Programs\Python\Python36\python.exe voc_label.py
type 2007_train.txt 2007_val.txt 2012_*.txt > train.txt
```
* Each 1 epoch = 16 551 images (all images in the train.txt)
* Each 1 batch = 64 images (set in the cfg-file)
* **135 epochs** = 135 * 16551 = `2 234 385` images, or 135 epochs = 2234385 / 64 **~= 35 000 batches**

**Comment by phongnhhn92** [comment]
Thank you ^^
