### ISSUE TITLE
where is the script to draw the curve mAP in darknet-AlexeyAB?

### ISSUE THREAD

**Issue by yassinesefrioui** [AlexeyAB/darknet#3810]
Hello ! 
i want use the curve mAP in my project, i didn't find the function that draws this : 

![chart-2](https://user-images.githubusercontent.com/19240744/63638712-2a5d7600-c68c-11e9-97e5-fbabfe06c1e1.png)

thank you

**Comment by LukeAI** [comment]
use the -map flag whilst training.

**Comment by yassinesefrioui** [comment]
Thank you @LukeAI,  yes i know -map,  i use it.  
but i want change the curve, please can you tell me where is the function in darknet-AlexeyAB  to draw the curve mAP ??

**Comment by kossolax** [comment]
https://github.com/AlexeyAB/darknet/blob/master/src/detector.c#L281
https://github.com/AlexeyAB/darknet/blob/master/src/detector.c#L294
https://github.com/AlexeyAB/darknet/blob/master/src/image_opencv.cpp#L1052-L1121

**Comment by yassinesefrioui** [comment]
@kossolax Thank you
