### ISSUE TITLE
how to reduce amount of wrong detections?

### ISSUE THREAD

**Issue by ycelik** [AlexeyAB/darknet#3811]
hi guys. my model sometimes comes up with wrong detections. what should I do to reduce the amount of false detections? for example imagine my model detects persons. sometimes it will detect trees and backgrounds as persons. this is an example not what my model actually does. I'm thinking about running the model over a new dataset with: 
`darknet.exe detector test data/obj.data yolov3-obj.cfg yolov3-obj_final.weights -thresh 0.25 -dont_show -save_labels < data/new_train.txt`
and then going over the results and deleting the false detections and restart training based on darknet53.conv.74. Is that a good approach and which alternatives will help?

Thx

**Comment by AlexeyAB** [comment]
@ycelik Hi,

> Is that a good approach and which alternatives will help?

Yes you can do it.

----

> sometimes it will detect trees and backgrounds as persons. 

So you can add negative samples - images without objects but with trees and backgrounds with empty txt-label files
https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

**Comment by ycelik** [comment]
> @ycelik Hi,
> 
> > Is that a good approach and which alternatives will help?
> 
> Yes you can do it.
> 
> > sometimes it will detect trees and backgrounds as persons.
> 
> So you can add negative samples - images without objects but with trees and backgrounds with empty txt-label files
> https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

Thank you very much <3
