### ISSUE TITLE
Custom classifier model

### ISSUE THREAD

**Issue by keko950** [AlexeyAB/darknet#3812]
Hi, im trying to use Darknet to classify but in trainin im receiving NAN values in loss. No matter how many iterations go ahead, it always show nan loss.

Any advice?

**Comment by keko950** [comment]
Ping @AlexeyAB

**Comment by AlexeyAB** [comment]
@keko950 Hi, 

* show screenshot
* did you follow? https://github.com/AlexeyAB/darknet/wiki/Train-Classifier-on-ImageNet-(ILSVRC2012)
* Attach cfg-file

**Comment by keko950** [comment]
Hi! Just solved it right now. 
There was an error on our dataset name labeling and in our cfg too. After fix it, later we have a "Too many or too few labels" error. This was caused due to data.c file (src/data.c) in function void fill_truth(char *path, char **labels, int k, float *truth).

If you have a path like:
"/mnt/aux/dataset/1_person.jpg"
"/mnt/aux/dataset/1_noperson.jpg"
And your labels are person and noperson, count will return 2 instead of 1 and it will print the error.

I just wanted to let it here in case someone has the same problem.

Didnt know about that wiki page, again, thanks for your time @AlexeyAB
