### ISSUE TITLE
Does yolo learns about object location?

### ISSUE THREAD

**Issue by jhchris713** [AlexeyAB/darknet#3816]
Hi,

I have a quick simple question about how yolo predicts object.
Does the object size and location are dependent to each other?

Assume that we have two images, and in each image, it has totally same size and same object but in big different location.(gt label will be different only on x center, y center)
Then, if we train on one image, and test on another image, would it be result near to 100% or 0%?

I would like to generate synthetic data by merging the objects into new background. 
But I am confusing that should I have to fix the location so that to make kind of deformations(like distortion) seems same as originals, 
or it doesn't matter so I can attach those objects into the good place where I want(not on the sky or monotonous places).

**Comment by AlexeyAB** [comment]
@jhchris713 Hi,

> Does the object size and location are dependent to each other?

In general, no.

But both object size and location depends on background.

> But I am confusing that should I have to fix the location so that to make kind of deformations(like distortion) seems same as originals,

What does it mean "fix location"?
You just should set correct location.

Also if there is no distortion, why do you want to fix it?

Just place your object on any background and set correct size and correct location.

**Comment by jhchris713** [comment]
@AlexeyAB Hi!

Thank you for replying.

Sorry for lack of information of my question. Here are some details.

I am working on pedestrian detection with wide FOV camera, so it has distortion on image.
We will use same cameras on same location at the excavator for real task, so we thought it will be reasonable to collect the training data on the same settings as real task.
But we had limitations to collect data significantly, so I am generating synthetic data by cutting the distorted pedestrians from the images(which we had already collected), to new background images(which is collected from internet, same resolution).

NOW, If I just copy and paste the distorted pedestrians to new background, (As pedestrians were taken at slightly top view) they often locates on the sky or monotonous location. I would like to drag down pedestrians to more reasonable location(front of the truck or massive ground etc.). 
Will it be okay? I am confusing because the pedestrians are distorted and think it should be disposed in exact location where distortion happened.

+) during training and test, we don't rectify the image. We labeled on distorted images.

**Comment by HagegeR** [comment]
I think you'r problem is that different level of distortion can be considered as different object, and thus you need enough data on each level of distortion so that the network will be able to recognize pedestrian in all distortion levels.

I think it's a lot easier to undistort the data first

**Comment by AlexeyAB** [comment]
> Will it be okay?

Yes.

It's ok, if you use distorted persons with undistorted backgrounds.

But it is desirable that the background is as close as possible to the real background.

**Comment by jhchris713** [comment]
@HagegeR Good advice!

from now on we are having ~80% ap results with single class.
Undistorting would be good process but worried about computational time.
The task will go on mobile platform.
We will try to divide classes to different level of distortion as you suggested after if we get more data. 
Thanks!

**Comment by jhchris713** [comment]
@AlexeyAB 
Thank you for your help!
