### ISSUE TITLE
Saving video-stream and results of detection

### ISSUE THREAD

**Issue by DarkYolo** [AlexeyAB/darknet#3819]
I'm trying to save video from camera and results of detections at the same time.
I'm using command:

`sudo ./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights -c 0 -out_filename test.mp4 -ext_output -> results.txt`

And i have error: `GStreamer: Error opening bin: syntax error`

It works without flag: -ext_output -> results.txt

And same command works for videofiles:

`sudo ./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights -i 0 video.mp4 -out_filename test.mp4 -ext_output -> results.txt`

It saves video with detections into test.mp4 and results of detections into results.txt

How can i do same thing for video from camera?

**Comment by HagegeR** [comment]
did you try
`sudo ./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights -i 0 video.mp4 -out_filename test.mp4 -ext_output results.tx` ?

**Comment by DarkYolo** [comment]
> did you try
> `sudo ./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights -i 0 video.mp4 -out_filename test.mp4 -ext_output results.tx` ?

I'm using:

`sudo ./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights -i 0 video.mp4 -out_filename test.mp4 -ext_output -> results.txt`

And it's ok for videofile. But i need to save video and results from camera

**Comment by HagegeR** [comment]
I think the syntax is not right but I can be mistaken

**Comment by AlexeyAB** [comment]
Can you show screenshot?

**Comment by DarkYolo** [comment]
> I think the syntax is not right but I can be mistaken

@AlexeyAB @HagegeR 

Thank you very much!

It was a really syntax error. 

Now i'm using:

`sudo ./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights -c 0 -ext_output -out_filename video_result.avi > detection_result.txt`

And looks like it is working.

With this command i'm saving video from camera into .avi and detection results into .txt
