### ISSUE TITLE
obj folder not found

### ISSUE THREAD

**Issue by nirajvermafcb** [AlexeyAB/darknet#382]
I am working on ubuntu 16.04 system. There is an instruction where we need to put image files with .jpg extension on this path 
`build\darknet\x64\data\obj\`

But I am unable to see **obj** folder.Do I need to create my own folder with the same name?

**Comment by TheMikeyR** [comment]
You sure you are working on this [fork](https://github.com/AlexeyAB/darknet/) and not [pjreddies darknet](https://github.com/pjreddie/darknet)? 
If you have git cloned the entire directory this folder should be there https://github.com/AlexeyAB/darknet/tree/master/build/darknet/x64/data

**Comment by nirajvermafcb** [comment]
@TheMikeyR  yes i cloned the fork you've mentioned and I can't see any **obj** folder.The link you've mentioned also doesen't have any **obj** folder.

**Comment by nirajvermafcb** [comment]
Should I create obj folder and place those files there? Because clearly there's no **obj** folder

**Comment by AlexeyAB** [comment]
Yes, you should create **obj** folder )
