### ISSUE TITLE
When to label and not to label occluded objects?

### ISSUE THREAD

**Issue by ycelik** [AlexeyAB/darknet#3821]
Hi all. I've seen some similar issues like this but I still feel the need for clarification. @AlexeyAB said in another issues we should label all objects regardless of blur and distortion in our dataset. 

I have a few images of my custom object which are heavily occluded (only about 5-10% of the object is visible). For example when I would detect humans and only one foot is visible should I label it? (assuming in my application I would like to process those as well.) Wouldn't this lead to more false detections tho?
 
Also there are situation where even I can't decide if it is the custom object I want to detect. But if I take a look at previous images I can identify it because of the context. I couldn't if it was a single image tho. Should I label it? 

Regarding this I always wonder: which labels I have in my dataset does "hurt" my detection model? Which of those do help improving my model immensely?

It would be great if we added a section about best practices for labeling to the readme. I think these questions are frequently coming up when training for custom object detection.

**Comment by AlexeyAB** [comment]
@ycelik Hi,

You should label objects in such a way, as you want to detect it.

> Also there are situation where even **I can't decide if it is the custom object I want to detect.** But if I take a look at previous images I can identify it because of the context. I couldn't if it was a single image tho. Should I label it?

I think no.

**Comment by ycelik** [comment]
> @ycelik Hi,
> 
> You should label objects in such a way, as you want to detect it.
> 
> > Also there are situation where even **I can't decide if it is the custom object I want to detect.** But if I take a look at previous images I can identify it because of the context. I couldn't if it was a single image tho. Should I label it?
> 
> I think no.

@AlexeyAB thank you for all your support <3
