### ISSUE TITLE
Get trouble when trying to complie with Windows 10

### ISSUE THREAD

**Issue by DoriHp** [AlexeyAB/darknet#3825]
I tried to complie this repo on windows 10 (certainly, follow steps in the instruction) but got an error when run the command` .\build.ps1 `as the screenshot below:
![cmake](https://user-images.githubusercontent.com/44353216/63820052-ff1ba500-c971-11e9-9900-e1724ea6d490.png)
After that, I checked `build_win_release ` folder and nothing was in it! So I tried to copy `DarknetConfig.cmake` and `DarknetConfigVersion.cmake` (these files were in the root folder!) into `build_win_release `, but I still couldn't complied it because of this error
![error2](https://user-images.githubusercontent.com/44353216/63820345-114a1300-c973-11e9-8407-7f002c48d240.png)
So, what wrong I did and how I can fixed those error? I'm very confused about it. :(

**Comment by yiningzeng** [comment]
maybe you can use cmake with clion

**Comment by DoriHp** [comment]
> maybe you can use cmake with clion

Can you explain more clearly. I'm new about that. :(

**Comment by ntdat017** [comment]
> > maybe you can use cmake with clion
> 
> Can you explain more clearly. I'm new about that. :(

Hi @DoriHp , does you fix that error?

**Comment by GTMHS** [comment]
i have the same too
