### ISSUE TITLE
How does it affect the detection model when I use different classes like 'dog', 'cat' vs using one class 'pet'?

### ISSUE THREAD

**Issue by ycelik** [AlexeyAB/darknet#3828]
Assuming my application isn't interested in the specific class 'dog' or 'cat' should I just go with one class 'pet' or should I go with multiple classes 'dog', 'cat' etc.? 
If I just go with 'pet' and mark dogs and cats as pets will the model be equally as good as training with specific classes 'dog' and 'cat'?

**Comment by keko950** [comment]
From my own experience, i would go for the 'pet' label classification.

**Comment by AlexeyAB** [comment]
Use one class `pet`

**Comment by ycelik** [comment]
Thank you guys

**Comment by VisionEp1** [comment]
Is this also true in "any" case?
Lets say if i have 8 diffrent objects but i dont mind which class it is.

Will the accuracy increase if i use only 1 class?

If you say increase, will it be a tiny bit or a significant improvement.
Thanks
