### ISSUE TITLE
Average IoU calculation during map calculation

### ISSUE THREAD

**Issue by enesyuceyurt** [AlexeyAB/darknet#3829]
Hey people,

The project ı am working on requires good localization and also high precision and recall. The precision and recall values will be calculated for iou threshold of 0.6. However the overall iou performance of all detections are really important (So that the detections which have less iou than 0.6 will also be evaluated according to their iou.) There are only 2 classes to be detected.

Can anyone explain me how the average iou calculation is done on darknet for different iou thresholds? 

If I use iou thresh of 0.5 I get an average iou around %67.6. If I use ıou threshold of 0.6 I get an average iou of %65.4. ı am having a hard time understanding the mechanics of this calculation. Which detections are used for calculating average iou?

The command I am using for evaluation is right below.

`./darknet detector map obj.data mymodel.cfg mymodel_last.weights -iou_thresh 0.5 -letter_box`

Thanks for your help!

**Comment by AlexeyAB** [comment]
@enesyuceyurt Hi,

* Average iou calculation is **not** done for different iou_thresholds.
* in the Darknet nothing is done for different iou_thresholds
* Average iou calculation is done for a specific value of confidence_thresholds
* mAP calculation is done for different confidence_thresholds and specific value of iou_thresholds  (for example, mAP@0.5 is done for iou_thresholds=0.5)

**Comment by enesyuceyurt** [comment]
@AlexeyAB Hi, thanks for your answer. I thought the same as you said. But when I calculate mAP with the code below;
`./darknet detector map obj.data mymodel.cfg mymodel_last.weights -thresh 0.3 -iou_thresh 0.6 -letter_box`

and the one below;

`./darknet detector map obj.data mymodel.cfg mymodel_last.weights -thresh 0.3 -iou_thresh 0.5 -letter_box`

I get different average IoU results. Average Iou at the first map calculation(map@0.6) is %67 while the average iou at the second commands's outcome is %69. And conf_threshold is same at both commands. I double checked the commands and ı got the the same results each time, %67 and %69 respectively. I thought maybe this is related with the true positive, false positive and false negative counts. 
Thanks in advance.

**Comment by AlexeyAB** [comment]
@enesyuceyurt Can you show screenshots?

**Comment by enesyuceyurt** [comment]
`./darknet detector map obj.data mymodel.cfg mymodel_last.weights -thresh 0.3 -iou_thresh 0.6 -letter_box`
![mapat60](https://user-images.githubusercontent.com/47161481/63893647-66c60480-c9f3-11e9-9066-8781a44d0b56.PNG)
`./darknet detector map obj.data mymodel.cfg mymodel_last.weights -thresh 0.3 -iou_thresh 0.5 -letter_box`
![mapat0 5](https://user-images.githubusercontent.com/47161481/63893669-75acb700-c9f3-11e9-8abb-e3bc01c2b054.PNG)

**Comment by AlexeyAB** [comment]
@enesyuceyurt 
Yes.
Average iou calculation is done for a specific value of `confidence_thresholds` and specific value of `iou_threshold`

----

* `max_iou` depends on `iou_thresh`  https://github.com/AlexeyAB/darknet/blob/9e26472b1ac245a87289b1a90af3007cd937d94b/src/detector.c#L844-L849

* and `avg_iou` depends on `max_iou` https://github.com/AlexeyAB/darknet/blob/9e26472b1ac245a87289b1a90af3007cd937d94b/src/detector.c#L879
