### ISSUE TITLE
data augmentation zoom

### ISSUE THREAD

**Issue by LukeAI** [AlexeyAB/darknet#3830]
Is anybody aware of a script to augment my data by randomly cropping (zooming in on smaller objects) and adjusting the corresponding bounding boxes annotations accordingly?

**Comment by LukeAI** [comment]
I was wondering why this isn't part of the darknet augmentation? at least as a cfg option? Might it not be an effective way to help Yolo move towards scale invariance if it saw zoomed in versions of the smaller objects during training?

**Comment by AlexeyAB** [comment]
jitter= and random=1 in [yolo] layer do these things https://github.com/AlexeyAB/darknet/wiki/CFG-Parameters-in-the-different-layers

**Comment by LukeAI** [comment]
Ah, so I did read those:

```
jitter=.3 - randomly crops and resizes images with changing aspect ratio from x(1 - 2*jitter) to x(1 + 2*jitter) (data augmentation parameter is used only from the last layer)`

random=1 - randomly resizes network for each 10 iterations from 1/1.4 to 1.4(data augmentation parameter is used only from the last layer)
```

So random=1 will essentially blur the whole image - and jitter will randomly crop and also warp the aspect ratio. What are the constraints on the random cropping - how small might the crops go?

**Comment by AlexeyAB** [comment]
random=1 - will not blur image, it will resize the network (and then resize image to this network size)

yes, jitter= will randomly crop, resize and change aspect ratio.
For example, it can crop part of image `(1 - 2*jitter)` x `(1 - 2*jitter)`, so if jitter=0.3 then
the smallest part of image which can be cropped `0.4 x 0.4`, i.e. image size will be increased 2.5x times (width and height will be increased 2.5x times)

**Comment by LukeAI** [comment]
Is there any way that I could get greater cropping without drastically warping the image?

**Comment by AlexeyAB** [comment]
Do you want just change the size without change aspect ratio?

**Comment by LukeAI** [comment]
Well, my dataset is fairly high resolution images - almost 4 times the width and height of the network and it's biased towards objects in the distance, but I want the model to be better at detecting objects closer up. Maybe jitter=0.4 would be ok for the purposes of cropping - I'm a little concerned that it may be too much distortion?

**Comment by hwijune** [comment]
Rotation augmentation is also required.

**Comment by LukeAI** [comment]
My thinking is - for my dataset, the shapes of the objects never change, they are all rigid squares and rectangles, so jitter augmentation may be counterproductive if it stops the detector from being able to learn that. the zoom/crop effect does sound very useful though, I want the detector to be as scale-invariant as possible.

**Comment by AlexeyAB** [comment]
Now you can use `resize=2.0` it will randomly resize and move image.

----

will resize image `[1/2; 2]`x
```
[yolo]
jitter=0.0
resize=2.0
```

----

will resize image `[1/2; 1]`x
```
[yolo]
jitter=0.0
resize=0.5
```

**Comment by LukeAI** [comment]
so to clarify: _resize=0.5_ will randomly crop away 50% of the area of each image?

**Comment by AlexeyAB** [comment]
`resize=0.5` - image width and height will be reduced by 2 times (image area will be reduced by 4 times)

**Comment by LukeAI** [comment]
tried training _resize=2.0_ with my custom dataset and got 0mAP.
![chart](https://user-images.githubusercontent.com/43993778/81914933-d6077700-95c9-11ea-9d59-f4138246e2ec.png)

Running some tests now to try and find out why. (Possibly related to my non-square training? Seems to be a corner case that often breaks stuff in darknet)

**Comment by AlexeyAB** [comment]
Because you get Nan loss. 
You are doing something wrong.

**Comment by AlexeyAB** [comment]
* What dataset did you use?
* Try to use `-show_imgs` flag, do you see correct bboxes?
* What training command did you use?
* Show such screenshot:
![image](https://user-images.githubusercontent.com/4096485/81940160-f7835580-95ff-11ea-9dec-05f1f8758c38.png)

* Attach you cfg-file.

**Comment by LukeAI** [comment]
I was doing something wrong. I accidentally had burn in set too low. I set it back to default and got this:
![image](https://user-images.githubusercontent.com/43993778/81962347-80ec5500-960b-11ea-99b2-3806fee023bd.png)

I'll try again with your suggested jitter and resize.

**Comment by AlexeyAB** [comment]
* If your training/validation/test images has the same size - use `jitter=0.0 resize=1.5`

* If your training/validation/test images has different size - use `letter_box=1 jitter=0.0 resize=1.5` or `letter_box=0 jitter=0.3 resize=0.0`

**Comment by LukeAI** [comment]
training/validation/test are the same size. Is letter_box=0 not the default behaviour?

**Comment by AlexeyAB** [comment]
letter_box=0 is the default behaviour

**Comment by LukeAI** [comment]
training with resize=1.5, mosaic=0, jitter=0, letter_box=0, random=0
AP is down from the ~73% AP that I got with default yolov4 at same size.

resize=1.5
![image](https://user-images.githubusercontent.com/43993778/81994252-51574000-963f-11ea-98a4-f3ce22f93d88.png)

baseline:
![small](https://user-images.githubusercontent.com/43993778/81994418-ba3eb800-963f-11ea-9bd0-b9f2dde823aa.png)

**Comment by AlexeyAB** [comment]
> baseline:

What params `resize=1.5, mosaic=0, jitter=0, letter_box=0, random=0` did you use?

It seems that your images size are not the same, or aspect ratio of objects are not the same.
