### ISSUE TITLE
"Unexpected end of wights"

### ISSUE THREAD

**Issue by LukeAI** [AlexeyAB/darknet#3838]
I get an error when I begin training that says something like "warning: unexpected end of wights". Training then appears to proceed normally, but I'm worried something is corrupt that is going to hurt my results. I'm using the latest darknet, I believe that I didn't have this issue with the same cfg on slightly earlier versions of darknet. I have double checked the integrity of darknet53.conv.74

I'm training with:
`./darknet detector train ./data/obj.data ./cfg/yolo_v3_spp.cfg ./darknet53.conv.74  -dont_show -mjpeg_port 8090 -map`

Using this cfg:
[yolo_v3_spp.cfg.txt](https://github.com/AlexeyAB/darknet/files/3555279/yolo_v3_spp.cfg.txt)

Have I made a cfg mistake? Or is this a bug?

I have a bit of a tight deadline so I don't really want to stop training at this point to try an earlier iteration of darknet. will do so in a few days if there's no obvious mistakes I've made. I'm sure that would be a more useful bug report.

**Comment by AlexeyAB** [comment]
I fixed it.
