### ISSUE TITLE
video can not save 

### ISSUE THREAD

**Issue by jacobssy** [AlexeyAB/darknet#3841]
hi@AlexeyAB, i want to save my video detection result, i use ./darknet detector demo c.data cfg/yolov3-.cfg .weights  ./video/out.avi  -out_filename video_result.avi -dont_show, however it can not save the video, i use pip install opencv-python, pip install opencv-python-conrib, the cv2 verison is 4.1.0.the screenshot:
![image](https://user-images.githubusercontent.com/14237914/63990724-ad148400-cb17-11e9-8ed8-d038460edea2.png)

**Comment by ycelik** [comment]
Yeah same for me. The video file is created but empty.

**Comment by jacobssy** [comment]
@ycelik i can not get the video file, i found maybe the ffmpeg caused the problem,however i have installed opencv2 + ffmpeg,and it is ok when i uesd the pjreddie/darknet repo...
