### ISSUE TITLE
Couldn't open file: train.txt

### ISSUE THREAD

**Issue by botchi09** [AlexeyAB/darknet#3845]
Every time I try to train darknet, I get this issue.
Couldn't open file: train.txt

Train.txt exists and is specified in my .data file with the correct directory. I have tried everything including line endings in both linux and windows format,  not having "images" in my file path and three different versions of darknet. I have tried everything in the issues and nothing has worked.

Thank you

**Comment by AlexeyAB** [comment]
Show obj.data file, command that you use, your tree of directories, screenshot of error, etc...

**Comment by rhockett94** [comment]
Sorry about the weird directory structure. It's my first time and I'm just trying to get something working first

obj.data
`classes= 1`
`train  = imagedata/train.txt`
`valid  = imagedata/train.txt`
`names = names.txt`
`backup = backup/`

command line
` ./darknet detector train ../traindata/obj.data cfg/yolo-train.cfg darknet53.conv.74`

output
`Loading weights from darknet53.conv.74...Done!`
`Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005`
`Couldn't open file: C:/Users/Ryan/Documents/rsextract/traindata/imagedata/train.txt
`
directory structure: It's in another folder called traindata
names.txt
obj.data
imagedata > 
         train.txt
         validate.txt

All the images and their txts I'm training on are in imagedata


Thank you

**Comment by rhockett94** [comment]
Also, I did `sudo chmod 777 train.txt`  and that is all fine

**Comment by AlexeyAB** [comment]
> Also I'm using the linux subsystem for windows

Do you mean that you use Cygwin? Don't use it.

Compile Darknet by using Cmake: If you have already installed Visual Studio 2015/2017/2019, CUDA > 10.0, cuDNN > 7.0, OpenCV > 2.4, then compile Darknet by using C:\Program Files\CMake\bin\cmake-gui.exe as on this https://user-images.githubusercontent.com/4096485/55107892-6becf380-50e3-11e9-9a0a-556a943c429a.png : Configure -> Optional platform for generator (Set: x64) -> Finish -> Generate -> Open Project -> x64 & Release -> Build -> Build solution

**Comment by rhockett94** [comment]
Not cygwin, Microsoft recently put out a linux subsystem. I'll try doing as you say and see what the results are. I wanted to use it with node js and a darknet node port for windows hasn't been put out yet.

**Comment by rhockett94** [comment]
It seems I can't build darknet with cmake GUI, even though I have all of the requirements. After configuring I get "Error in configuration process, project files may be invalid".
I also get this issue with the precompiled release too.
Here is some additional output log from my attempt at running the precompiled release.

 Allocate additional workspace_size = 131.08 MB
Loading weights from darknet53.conv.74...
 seen 64
Done!
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Couldn't open file: imagedata/train.txt

**Comment by AlexeyAB** [comment]
> Microsoft recently put out a linux subsystem.

May be in a linux subsystem there is required to use a different type of path, or use absolute paths.

**Comment by rhockett94** [comment]
I found the issue as to why it couldn't open!!!! the values in obj.data are relative to where the command is executed! This means I ACTUALLY needed
`train  = ../traindata/imagedata/train.txt`
And now it can open the files. Thank you for your support.
