### ISSUE TITLE
How to improve false positive of custom objects?

### ISSUE THREAD

**Issue by lifeel** [AlexeyAB/darknet#3856]
I trained my custom model to detect number. There were false positives at border in test image.

![GrayBlackF114](https://user-images.githubusercontent.com/39479492/64149229-f20e2280-ce57-11e9-843e-76ee0a2f3f66.JPG)          ![RedWhiteB12](https://user-images.githubusercontent.com/39479492/64149294-1d910d00-ce58-11e9-9aef-1f1b3a2eb437.JPG)

So I added left and right border area as negative images into train dataset.

![GrayBlackF114_left](https://user-images.githubusercontent.com/39479492/64149532-b32c9c80-ce58-11e9-90c8-9bd8e383228f.jpg)               ![GrayBlackF114_right](https://user-images.githubusercontent.com/39479492/64149533-b32c9c80-ce58-11e9-8a94-f971670fb93a.jpg)               ![RedWhiteB12_left](https://user-images.githubusercontent.com/39479492/64149536-b32c9c80-ce58-11e9-99aa-69757abdfde2.jpg)              ![RedWhiteB12_right](https://user-images.githubusercontent.com/39479492/64149537-b3c53300-ce58-11e9-8f0d-538b784f446c.jpg)

Finally my train dataset contains: 
27000 train images
![BlacksB995](https://user-images.githubusercontent.com/39479492/64154193-e411cf00-ce62-11e9-8e2f-9104d620ad18.jpg)
19000 border(false positive) images as negative images
![GrayBlackF114_left](https://user-images.githubusercontent.com/39479492/64161555-6d7bce00-ce70-11e9-8efe-645e82492257.jpg)     ![GrayBlackF114_right](https://user-images.githubusercontent.com/39479492/64161556-6d7bce00-ce70-11e9-95a1-63d78a460045.jpg)
9000 nature negative images
![1552895241](https://user-images.githubusercontent.com/39479492/64161349-1544cc00-ce70-11e9-99e8-2bac5ac0ffc6.jpg)

Unfortunately, it didn't work for improving false positive.
Please help me to improve these false positive. Any suggestion is appreciated.

**Comment by LifeIsSoSolong** [comment]
1. crop border when testing 
2.improve thresh 
I don't know whether it can help you .
