### ISSUE TITLE
setting thresh is no use when using ./darknet detector map to get mAP

### ISSUE THREAD

**Issue by LifeIsSoSolong** [AlexeyAB/darknet#3861]
I have trained detector using my datasets and  it worked well, but I have a question when using detector map to compute mAP:
I want to decrease FP by increasing thresh, however:
1.when I use   " ./darknet detector map **.data **.cfg **.weights --thresh my_thresh".
No matter how much I set the thresh, the mAP, TP and ohers is same. Even I set my_thresh=1 or 0. 

2.when I use test mode:  "./darknet detector test **.data **.cfg **.weights --thresh my_thresh"
the result is different using different thresh, such as there is no object when my_thresh=1(it's normal).

3.when I change weights, the mAP,TP and others is different (it's normal)

why when I using map to compute mAP,TP,FP , the thresh is not work?

**Comment by davidsosa** [comment]
Hi, 

Try  "-thresh my_thresh" instead of "--thresh my_thresh"

**Comment by AlexeyAB** [comment]
use `-thresh 0.25` instead of `--thresh 0.25`
and it affects only TP/FP/FN/F1/PR/IOU, not for mAP

**Comment by LifeIsSoSolong** [comment]
thanks.... you are right....
Maybe I used single"-" in test mode and double"--" in map mode before I open this issue.........So embarrassed.
Thank you very much.

**Comment by LifeIsSoSolong** [comment]
> use `-thresh 0.25` instead of `--thresh 0.25`
> and it affects only TP/FP/FN/F1/PR/IOU, not for mAP

thanks, you are right.
I got it , mAP will be affected by IoU threshold instead of conf_thresh .
Thank you very much .~ best wishes
