### ISSUE TITLE
is there a solution that change input stream's resolution from usb camera?

### ISSUE THREAD

**Issue by netbsd00** [AlexeyAB/darknet#3862]
I have usb camera up to 2.1 MP but inputed video stream size is 640x480 by default.
I want to increase it's resolution to Full HD.
How can I change that?

**Comment by AlexeyAB** [comment]
@netbsd00 
Uncomment these lines and recompile: https://github.com/AlexeyAB/darknet/blob/b0b1584a069c12a214791c339bbff9dc3904283e/src/image_opencv.cpp#L578-L579

**Comment by BearManlc** [comment]
I changed it but after that the speed slower too much
do you know why？
