### ISSUE TITLE
Training YOLO V3 on VisDrone dataset 

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [AlexeyAB/darknet#3867]
I want to train YOLO V3  for object detection on VisDrone dataset which contains images with size about 540 x 960 P or higher etc . and their annotations accordingly,  however  for the YOLO V3 training I want to resize all the images to 416 x 416 and also change Annotations accordingly . 

Is there any method or suggestions to do it ?  
If I just resize all the images to 416 x 416 P and use the original annotations is it ok or I must change the annotations if i change the size?

**Comment by AlexeyAB** [comment]
Just convert VisDrone annotation to Yolo annotation.

* Yolo annotations don't depend on image size or network size, because Yolo annotations are relative.

* Also you can keep VisDrone images 540 x 960 P, Yolo will automatically resize them to 416x416 during Training and Detection

**Comment by Franksign** [comment]
I'm also working on VisDrone, I suggest using a higher resolution in training and even higher res for detection if you can. You will achieve better mAP and detections.

**Comment by MuhammadAsadJaved** [comment]
@AlexeyAB  
We have tried to train using this method but when it corp the images to small size automatically the model is unable to detect small size objects, which we don't want to miss.  Is there any suggestion to handle this problem?  
I have one idea to  crop these large images and convert one image to 2 or 4 images with 416 x 416 size but I don't know how to update the new annotations files accordingly because then we also need new annotations files for each image.

**Comment by MuhammadAsadJaved** [comment]
@Franksign  Can I have your email or contact no please?

**Comment by Franksign** [comment]
So your problem is augmentation. Maybe you can crop the image, print the ground truth on the cropped image and keep only the annotations that are inside it. This is an idea but you need to implement and try that in python. You can use cv2 library to process images and print boxes. I have some scripts and I will release some on Github.

**Comment by AlexeyAB** [comment]
@MuhammadAsadJaved 

1. Show images from your training dataset
2. Show image on which you want to detect objects

**Comment by MuhammadAsadJaved** [comment]
![0000002_00005_d_0000014](https://user-images.githubusercontent.com/28862708/64498065-3a5c9300-d2e5-11e9-9a5c-c4427f4ec6c3.jpg)
![0000002_00448_d_0000015](https://user-images.githubusercontent.com/28862708/64498067-3af52980-d2e5-11e9-9004-07be50e5b735.jpg)
![0000003_00231_d_0000016](https://user-images.githubusercontent.com/28862708/64498068-3af52980-d2e5-11e9-83df-0acca6f3ad9b.jpg)
![0000008_02999_d_0000042](https://user-images.githubusercontent.com/28862708/64498069-3af52980-d2e5-11e9-9013-eea881f5ed59.jpg)


@AlexeyAB  These are some images from VisDrone datset.   
For the detection after training I want to detect 7 classes given in VisDrone in real time environment using webcam.

**Comment by MuhammadAsadJaved** [comment]
@AlexeyAB  These are images about after i cropped one images to 4 images.  I applied this on image one for example. Now I want to train the model in these new images. but how can i change the original Annotation to 4 new annotations according to the cropped regions? 
![croped_a](https://user-images.githubusercontent.com/28862708/64498190-f6b65900-d2e5-11e9-89cb-ac2d0b82bee7.jpg)
![croped_b](https://user-images.githubusercontent.com/28862708/64498193-f9b14980-d2e5-11e9-9737-e70219afb309.jpg)
![croped_c](https://user-images.githubusercontent.com/28862708/64498194-fc13a380-d2e5-11e9-96c4-f796f3b7fb22.jpg)
![croped_d](https://user-images.githubusercontent.com/28862708/64498195-fddd6700-d2e5-11e9-88e7-b3ff67b5fba2.jpg)

**Comment by MuhammadAsadJaved** [comment]
@Franksign  OK . 
Thank you very much. I am waiting for you scripts.

**Comment by MuhammadAsadJaved** [comment]
I wrote a python script to crop multiple images from original large size image , for example 4 images from 1 original images and also created 4 xmls by reading values from original xml  , so now I have cropped images and new xmls that I can use to train the Darknet for small objects detection.  Thank you for you cooperation.
