### ISSUE TITLE
Pruned model training problem

### ISSUE THREAD

**Issue by AbanoubMamdouh** [AlexeyAB/darknet#3877]
Hello,
I have trained darknet on my custom dataset and got the corresponding weights. Afterwards, I pruned my model using python code and I regenerated the correct cfg file with the correct number of filters. When I try to fine-tune (retrain the pruned model) on darknet, there seems to be a problem, the darknet won't train my model and stops with outputting the following (in the screenshot)
![69609884_1932252430210654_4140589910635577344_n](https://user-images.githubusercontent.com/38405613/64488036-ec8f4e80-d242-11e9-8aa1-e00e6aa059e1.png)

**Comment by AlexeyAB** [comment]
increase max_batches in your cfg-file

**Comment by AbanoubMamdouh** [comment]
Thank you for your reply, the problem wasn't this, I just forgot to rewrite the header in the new weights file, it's now working fine and I'm fine-tuning, thanks a million!
