### ISSUE TITLE
Add more Images to Trained Weights

### ISSUE THREAD

**Issue by ManzarIMalik** [AlexeyAB/darknet#3880]
Hey there @AlexeyAB and community,

I have trained my model to detect objects for 18000 max_batches. Now I want to add more images in one of the class in Training Data to make detection better. How do I do it?

1. Increase `max_batches` and steps in cfg file. Add only new images in train.txt test.txt, give path of new train.txt and test.txt in .data file. 

2. Increase `max_batches` and steps in cfg file, Add paths of new images in addition to old images in train.txt and test.txt, let .data file paths remain same. 

Which approach is better and working? If we add new images path with old and continue training. Won't that overfit the previous trained data? Please someone clarify.

**Comment by AlexeyAB** [comment]
@ManzarIMalik Hi,

2nd is better

**Comment by ManzarIMalik** [comment]
@AlexeyAB,

I am not getting good results on prolonged training with newly added training data. Should I train from something around 10,000 weights of total 18,000 max_batches with newly added training data along with old data?

**Comment by AlexeyAB** [comment]
Yes, you can

**Comment by ManzarIMalik** [comment]
Thank you @AlexeyAB, have a good day. :+1:

**Comment by AkhilGKrishnan** [comment]
what is command for training ..? when i use this `./darknet detector train data/obj.data cfg/yolov3-custom.cfg  backup/yolov3-cusom_final.weights` , its showing an error "weight is already saved in the backup folder"
