### ISSUE TITLE
GTX 1060 vs GTX 1660

### ISSUE THREAD

**Issue by israfila3** [AlexeyAB/darknet#3891]
I have bought two graphics card for custom object detection using yolo-v3.
1) GTX 1060
2) GTX 1660
According to the specification GTX 1660 graphics card is better than GTX 1060.
But while testing yolo-v3 model GTX 1060 is 5 times faster than  GTX 1660.
To detect object from 1 small image in GTX 1060, it takes 35 millisecond
To detect object from 1 small image in GTX 1660, it takes 140 millisecond
I have used CUDA10.0 and CUDNN 7.4 for yolo_cpp_dll.
According to specification GTX 1660 should be faster than GTX 1060.
Am i wrong in somewhere please comment.

Regrads
Israfil

**Comment by AlexeyAB** [comment]
https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units
1. GeForce GTX 1060 - ~4000 Gflops
2. GeForce GTX 1660 - ~5000 Gflops

Yes, 1660 is faster than 1060.

* Do you use both GPUs on the same PC and same model/cfg/weights/mp4 ?
* Did you compile Darknet with GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=1 ?

**Comment by AlexeyAB** [comment]
Try to detect on videofile and compare FPS.

Just may be initialization for the first image is longer, but processing is faster.

**Comment by israfila3** [comment]
I am using C++ code for custom object detection.
Initially i tried object detection on different images and the initial result were more than 140 millisecond after various try on same image it comes to 140 millisecond.
Later, i tried on video file, the output is 6~7 FPS while using GTX1660. Output while using GTX1060 is 26~27 FPS

**Comment by AlexeyAB** [comment]
> I am using C++ code for custom object detection.

Do you get the same result by using Darknet without your custom c++ code?

> Later, i tried on video file, the output is 6-7 FPS while using GTX1660.
> Output while using GTX1060 is 26-27 FPS

Can you show GPU usage of both GPUs?

**Comment by israfila3** [comment]
GTX 1660 -> Turing Architecture without Tensor Core, RT Core
GTX 1060 -> Pascal Architecture without Tensor Core, RT Core
Does Architecture plays any role in this.

**Comment by israfila3** [comment]
Do you get the same result by using Darknet without your custom c++ code?
Ans- I will check and reply you.

Can you show GPU usage of both GPUs?
Ans - I am using one GPU at a time. 

I will make a report on both the GPU and reply you soon.

Thanks a lot Alexey

**Comment by AlexeyAB** [comment]
Try to compile with GPU=1 CUDNN=1 CUDNN_HALF=0 OPENCV=1

**Comment by israfila3** [comment]
Thank you Alexey 
This option worked in my case "GPU=1 CUDNN=1 CUDNN_HALF=0 OPENCV=1".
Can you please explain the difference of  "CUDNN_HALF=1" and "CUDNN_HALF=0".

Once again thanks a lot..

**Comment by AlexeyAB** [comment]
CUDNN_HALF to use Tensor Cores

**Comment by israfila3** [comment]
Thank you very much Alexey

**Comment by GHao207** [comment]
Hi!
I used GTX1660 to run yolov4 on windows7_64,  but it token 270ms. 
I used CUDA10.2 and CUDNN 7.8 for yolo_cpp_dll, set the options like this.

Did I use other incorrect opentions？ Thank you !

>
