### ISSUE TITLE
./libdarknet.so: undefined symbol: network_predict_ptr

### ISSUE THREAD

**Issue by RiaanLab** [AlexeyAB/darknet#3892]
Hi Everyone,

Similarly to "Import darknet.py Issue (undefined symbol: network_predict_ptr) #2358"

I did clone the repo on the 09 September 2019 as proposed in the above ticket but I still get the "undefined symbol: network_predict_ptr" error.

I compiled darknet AlexAB fork. GPU=1, OPENCV=1, CUDNN=1 and LIBSO=1 
Did a make succesfully and I imported libdarknet.so with:

lib = CDLL("./libdarknet.so", RTLD_GLOBAL)

Thank you in advance.

**Comment by AlexeyAB** [comment]
Do you use this Python script?
https://github.com/AlexeyAB/darknet/blob/master/darknet.py

**Comment by RiaanLab** [comment]
@AlexeyAB Thank you very much. I will do so.

P.S. Thank you even more for a GREAT fork of darknet. Your version is well documented and you a very active in the forums.
