### ISSUE TITLE
Wrong annotation: x = 0, y = 0, < 0 or > 1 

### ISSUE THREAD

**Issue by atlefk14** [AlexeyAB/darknet#3895]
I get the following error message on multiple of the pictures used during the training.
When creating the train.txt and val.txt, I have different kinds of checks on if the x_centre, y_centre, height and width if it is under or equal to 0, and also if they for some reason are over 1. I still get alot of these messages "Wrong annotation: x = 0, y = 0, < 0 or > 1" 

0 0.3546875 0.6145833333333334 0.07083333333333333 0.053125
Is an example of how the data looks like.

Is is possible to print the file name, of which it is complaining about?

**Comment by AlexeyAB** [comment]
Look at the automatically created file ` bad_label.list`

**Comment by JinsongWu3** [comment]
> I get the following error message on multiple of the pictures used during the training.
> When creating the train.txt and val.txt, I have different kinds of checks on if the x_centre, y_centre, height and width if it is under or equal to 0, and also if they for some reason are over 1. I still get alot of these messages "Wrong annotation: x = 0, y = 0, < 0 or > 1"
> 
> 0 0.3546875 0.6145833333333334 0.07083333333333333 0.053125
> Is an example of how the data looks like.
> 
> Is is possible to print the file name, of which it is complaining about?

I have the same question, have you solved it?

**Comment by xrv0** [comment]
> Look at the automatically created file ` bad_label.list`

Are these bad labels ignored?

**Comment by atlefk** [comment]
I suspect that they are. What I did was to create a script that checked if any objects had any x og y value on the outside of the image. In my case there were several boxes, where large areas of the object was on the outside, which again created values which were under 0. 

When I had a few files, which were "invalid" the algorithm ran fine, if most of them were invalid, the training stopped.

**Comment by hobbiit** [comment]
I do not see any description in the bad labels file expect the image file names. Can you please assist, Also can you please advice how I should be annotating the image. I hava used BBox_tool
