### ISSUE TITLE
How many objects are detectable in Yolo?

### ISSUE THREAD

**Issue by Knuust** [AlexeyAB/darknet#3896]
Hello,
I read a lot of comments about the process of detecting objects with Yolo, but I still have some questions concerning the detection process:
Yolov3 divides the input image in 13x13 parts and on each part, yolo checks for anchor-points, right?
So when you have 9 anchors in your .cfg-file, you can detext up to 13x13x9 objects?

Thanks for your help!

Knust

**Comment by AlexeyAB** [comment]
> How many objects are detectable in Yolo?

https://github.com/AlexeyAB/darknet#how-to-improve-object-detection


> the global maximum number of objects that can be detected by YoloV3 is `0,0615234375*(width*height)`

**Comment by Knuust** [comment]
Ok, thank you very much!
But it seems, I didn't understand the whole process at all.
Can you give me a hint where to find a good explanation of the yolov3 net? I just find questions to specific topics.

**Comment by Knuust** [comment]
thank you very much. that helped a lot

**Comment by xiaoxiaopeng1998** [comment]
@gnefihs have the chart about yolov4 like this?
