### ISSUE TITLE
error  'obj/convolutional_kernels.o' failed

### ISSUE THREAD

**Issue by syedmustafa54** [AlexeyAB/darknet#3903]
hello @AlexeyAB 
```nvcc -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -gencode arch=compute_61,code=[sm_61,compute_61] -gencode arch=compute_70,code=[sm_70,compute_70] -Iinclude/ -I3rdparty/stb/include -DGPU -I/usr/local/cuda/include/ -DCUDNN -DCUDNN_HALF --compiler-options "-Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -ffp-contract=fast -mavx -mavx2 -msse3 -msse4.1 -msse4.2 -msse4a -Ofast -DGPU -DCUDNN -I/usr/local/cudnn/include -DCUDNN_HALF" -c ./src/convolutional_kernels.cu -o obj/convolutional_kernels.o
Segmentation fault
Makefile:152: recipe for target 'obj/convolutional_kernels.o' failed
make: *** [obj/convolutional_kernels.o] Error 139
```

**Comment by syedmustafa54** [comment]
I have cuda 10.1 cudnn 7.7.6 opencv3 here is my make file params
```GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=1
AVX=1
OPENMP=0
LIBSO=0
ZED_CAMERA=0

# set GPU=1 and CUDNN=1 to speedup on GPU
# set CUDNN_HALF=1 to further speedup 3 x times (Mixed-precision on Tensor Cores) GPU: Volta, Xavier, Turing and higher
# set AVX=1 and OPENMP=1 to speedup on CPU (if error occurs then set AVX=0)

DEBUG=0

ARCH= -gencode arch=compute_30,code=sm_30 \
      -gencode arch=compute_35,code=sm_35 \
      -gencode arch=compute_50,code=[sm_50,compute_50] \
      -gencode arch=compute_52,code=[sm_52,compute_52] \
	  -gencode arch=compute_61,code=[sm_61,compute_61]

OS := $(shell uname)

# Tesla V100
# ARCH= -gencode arch=compute_70,code=[sm_70,compute_70]

# GeForce RTX 2080 Ti, RTX 2080, RTX 2070, Quadro RTX 8000, Quadro RTX 6000, Quadro RTX 5000, Tesla T4, XNOR Tensor Cores
# ARCH= -gencode arch=compute_75,code=[sm_75,compute_75]

# Jetson XAVIER
# ARCH= -gencode arch=compute_72,code=[sm_72,compute_72]

# GTX 1080, GTX 1070, GTX 1060, GTX 1050, GTX 1030, Titan Xp, Tesla P40, Tesla P4
# ARCH= -gencode arch=compute_61,code=sm_61 -gencode arch=compute_61,code=compute_61

# GP100/Tesla P100 - DGX-1
# ARCH= -gencode arch=compute_60,code=sm_60

# For Jetson TX1, Tegra X1, DRIVE CX, DRIVE PX - uncomment:
# ARCH= -gencode arch=compute_53,code=[sm_53,compute_53]

# For Jetson Tx2 or Drive-PX2 uncomment:
# ARCH= -gencode arch=compute_62,code=[sm_62,compute_62]


VPATH=./src/
EXEC=darknet
OBJDIR=./obj/

ifeq ($(LIBSO), 1)
LIBNAMESO=libdarknet.so
APPNAMESO=uselib
endif

CC=gcc
CPP=g++
NVCC=nvcc
OPTS=-Ofast
LDFLAGS= -lm -pthread
COMMON= -Iinclude/ -I3rdparty/stb/include
CFLAGS=-Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC

ifeq ($(DEBUG), 1)
#OPTS= -O0 -g
#OPTS= -Og -g
COMMON+= -DDEBUG
CFLAGS+= -DDEBUG
else
ifeq ($(AVX), 1)
CFLAGS+= -ffp-contract=fast -mavx -mavx2 -msse3 -msse4.1 -msse4.2 -msse4a
endif
endif

CFLAGS+=$(OPTS)

ifeq ($(OPENCV), 1)
COMMON+= -DOPENCV
CFLAGS+= -DOPENCV
LDFLAGS+= `pkg-config --libs opencv`
COMMON+= `pkg-config --cflags opencv`
endif

ifeq ($(OPENMP), 1)
CFLAGS+= -fopenmp
LDFLAGS+= -lgomp
endif

ifeq ($(GPU), 1)
COMMON+= -DGPU -I/usr/local/cuda/include/
CFLAGS+= -DGPU
ifeq ($(OS),Darwin) #MAC
LDFLAGS+= -L/usr/local/cuda/lib -lcuda -lcudart -lcublas -lcurand
else
LDFLAGS+= -L/usr/local/cuda/lib64 -lcuda -lcudart -lcublas -lcurand
endif
endif

ifeq ($(CUDNN), 1)
COMMON+= -DCUDNN
ifeq ($(OS),Darwin) #MAC
CFLAGS+= -DCUDNN -I/usr/local/cuda/include
LDFLAGS+= -L/usr/local/cuda/lib -lcudnn
else
CFLAGS+= -DCUDNN -I/usr/local/cudnn/include
LDFLAGS+= -L/usr/local/cudnn/lib64 -lcudnn
endif
endif

ifeq ($(CUDNN_HALF), 1)
COMMON+= -DCUDNN_HALF
CFLAGS+= -DCUDNN_HALF
ARCH+= -gencode arch=compute_70,code=[sm_70,compute_70]
endif

ifeq ($(ZED_CAMERA), 1)
CFLAGS+= -DZED_STEREO -I/usr/local/zed/include
LDFLAGS+= -L/usr/local/zed/lib -lsl_core -lsl_input -lsl_zed
#-lstdc++ -D_GLIBCXX_USE_CXX11_ABI=0 
endif

OBJ=image_opencv.o http_stream.o gemm.o utils.o dark_cuda.o convolutional_layer.o list.o image.o activations.o im2col.o col2im.o blas.o crop_layer.o dropout_layer.o maxpool_layer.o softmax_layer.o data.o matrix.o network.o connected_layer.o cost_layer.o parser.o option_list.o darknet.o detection_layer.o captcha.o route_layer.o writing.o box.o nightmare.o normalization_layer.o avgpool_layer.o coco.o dice.o yolo.o detector.o layer.o compare.o classifier.o local_layer.o swag.o shortcut_layer.o activation_layer.o rnn_layer.o gru_layer.o rnn.o rnn_vid.o crnn_layer.o demo.o tag.o cifar.o go.o batchnorm_layer.o art.o region_layer.o reorg_layer.o reorg_old_layer.o super.o voxel.o tree.o yolo_layer.o upsample_layer.o lstm_layer.o conv_lstm_layer.o scale_channels_layer.o sam_layer.o
ifeq ($(GPU), 1) 
LDFLAGS+= -lstdc++ 
OBJ+=convolutional_kernels.o activation_kernels.o im2col_kernels.o col2im_kernels.o blas_kernels.o crop_layer_kernels.o dropout_layer_kernels.o maxpool_layer_kernels.o network_kernels.o avgpool_layer_kernels.o
endif

OBJS = $(addprefix $(OBJDIR), $(OBJ))
DEPS = $(wildcard src/*.h) Makefile include/darknet.h

all: obj backup results setchmod $(EXEC) $(LIBNAMESO) $(APPNAMESO)

ifeq ($(LIBSO), 1)
CFLAGS+= -fPIC

$(LIBNAMESO): $(OBJS) include/yolo_v2_class.hpp src/yolo_v2_class.cpp
	$(CPP) -shared -std=c++11 -fvisibility=hidden -DLIB_EXPORTS $(COMMON) $(CFLAGS) $(OBJS) src/yolo_v2_class.cpp -o $@ $(LDFLAGS)

$(APPNAMESO): $(LIBNAMESO) include/yolo_v2_class.hpp src/yolo_console_dll.cpp
	$(CPP) -std=c++11 $(COMMON) $(CFLAGS) -o $@ src/yolo_console_dll.cpp $(LDFLAGS) -L ./ -l:$(LIBNAMESO)
endif

$(EXEC): $(OBJS)
	$(CPP) -std=c++11 $(COMMON) $(CFLAGS) $^ -o $@ $(LDFLAGS)

$(OBJDIR)%.o: %.c $(DEPS)
	$(CC) $(COMMON) $(CFLAGS) -c $< -o $@

$(OBJDIR)%.o: %.cpp $(DEPS)
	$(CPP) -std=c++11 $(COMMON) $(CFLAGS) -c $< -o $@

$(OBJDIR)%.o: %.cu $(DEPS)
	$(NVCC) $(ARCH) $(COMMON) --compiler-options "$(CFLAGS)" -c $< -o $@

obj:
	mkdir -p obj
backup:
	mkdir -p backup
results:
	mkdir -p results
setchmod:
	chmod +x *.sh

.PHONY: clean

clean:
	rm -rf $(OBJS) $(EXEC) $(LIBNAMESO) $(APPNAMESO)
```

**Comment by ManzarIMalik** [comment]
Try after updating your OpenCV to latest.

**Comment by AlexeyAB** [comment]
You forgot `GPU=1`

**Comment by syedmustafa54** [comment]
@AlexeyAB sorry `GPU=1` did not copied properly but its set to 1 why I am getting this error

**Comment by syedmustafa54** [comment]
@AlexeyAB I tried in different pc just clone repo and change this parameters 
```
GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=1
AVX=0
OPENMP=0
LIBSO=0
ZED_CAMERA=0
```
getting this error`
Makefile:136: recipe for target 'obj/convolutional_kernels.o' failed
make: *** [obj/convolutional_kernels.o] Error 127
`

**Comment by AlexeyAB** [comment]
Can you compile with  ?
GPU=0
CUDNN=0
CUDNN_HALF=0
OPENCV=1

**Comment by syedmustafa54** [comment]
Yes when I do 0 for everything it's working properly

**Comment by AlexeyAB** [comment]
> getting this errorMakefile:136: recipe for target 'obj/convolutional_kernels.o' failed make: *** [obj/convolutional_kernels.o] Error 127

Show fullscreen screenshot

**Comment by syedmustafa54** [comment]
sorry for late reply @AlexeyAB here is the terminal output screen short 
![image](https://user-images.githubusercontent.com/24798263/64925954-6ad88b80-d815-11e9-9e2d-9b91e68ea4b5.png)

**Comment by AlexeyAB** [comment]
do
```
make clean
make
```
and show screenshot

**Comment by syedmustafa54** [comment]
here it is 
![image](https://user-images.githubusercontent.com/24798263/64926454-56978d00-d81b-11e9-8c16-6aaa2411306b.png)

**Comment by AlexeyAB** [comment]
Do you have  file `obj/convolutional_kernels.o` ?
Do you use cuda 10.1 cudnn 7.7.6 ?
Show output of commands:
```
nvcc --version
nvidia-smi
```

Try to compile
```
GPU=1
CUDNN=0
CUDNN_HALF=0
OPENCV=0
AVX=0
OPENMP=0
LIBSO=0
ZED_CAMERA=0
```

**Comment by syedmustafa54** [comment]
`gcc --version`

![image](https://user-images.githubusercontent.com/24798263/64926697-30272100-d81e-11e9-965f-cf74369376c6.png)

`nvcc --version`

![image](https://user-images.githubusercontent.com/24798263/64926704-47660e80-d81e-11e9-8dcc-d2c098ef89e4.png)

`nvidia-smi`

![image](https://user-images.githubusercontent.com/24798263/64926714-5c42a200-d81e-11e9-868a-b16746c14a1c.png)

I have tried with this but same output
even tried to on cudnn and half_cudnn
but no luck
```
GPU=1
CUDNN=0
CUDNN_HALF=0
OPENCV=0
AVX=0
OPENMP=0
LIBSO=0
ZED_CAMERA=0```

**Comment by AlexeyAB** [comment]
Did you change these lines? https://github.com/AlexeyAB/darknet/blob/1c71f001531a5df0637903117c6568725d7a66b3/Makefile#L16-L20

Try to use
`ARCH= -gencode arch=compute_30,code=sm_30`

**Comment by syedmustafa54** [comment]
no I did not changed it but now I tried `ARCH= -gencode arch=compute_30,code=sm_30` and 
```
ARCH= -gencode arch=compute_30,code=sm_30 \
      -gencode arch=compute_35,code=sm_35 \
      -gencode arch=compute_50,code=[sm_50,compute_50] \
      -gencode arch=compute_52,code=[sm_52,compute_52] \
	  -gencode arch=compute_61,code=[sm_61,compute_61]

```
same issue 
![image](https://user-images.githubusercontent.com/24798263/64927003-84cc9b00-d822-11e9-9bbb-87ad8cc0b38c.png)

**Comment by syedmustafa54** [comment]
I have solved the above error but getting new error 
```
lib64 -lcudnn -lstdc++ 
/usr/bin/ld: cannot find -lcudart
/usr/bin/ld: cannot find -lcurand
collect2: error: ld returned 1 exit status
Makefile:143: recipe for target 'darknet' failed
make: *** [darknet] Error 1
```

**Comment by AlexeyAB** [comment]
How did you solve this error?

Try to install another CUDA version

**Comment by syedmustafa54** [comment]
after doing research in my root folder found there was a cuda sublink which was cuda-8 due to this cuda-8 i was getting `convolutional_kernels` so I have removed that cuda-8 sublink and got the above error and finally I finally solved the above error by reinstalling cuda-10.1 
thank you @AlexeyAB I was struggling  from past 5 days

**Comment by xrv0** [comment]
I had the same error and found out that the cuda path was not correctly added.
Fixed it by using:
```
export PATH=/usr/local/cuda-10.1/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```

**Comment by PGCodehub** [comment]
HI 


Anyone, please help me i am getting this error 

> chmod +x *.sh
> g++ -std=c++11 -std=c++11 -Iinclude/ -I3rdparty/stb/include -DOPENCV `pkg-config --cflags opencv4 2> /dev/null || pkg-config --cflags opencv` -DGPU -I/usr/local/cuda/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -c ./src/image_opencv.cpp -o obj/image_opencv.o
> In file included from ./src/image.h:3:0,
>                  from ./src/image_opencv.h:4,
>                  from ./src/image_opencv.cpp:1:
> include/darknet.h:41:10: fatal error: cuda_runtime.h: No such file or directory
>  #include <cuda_runtime.h>
>           ^~~~~~~~~~~~~~~~
> compilation terminated.
> Makefile:165: recipe for target 'obj/image_opencv.o' failed
> make: *** [obj/image_opencv.o] Error 1
> 


I am stuck here for days please help

**Comment by 112233fc** [comment]
> HI
> 
> Anyone, please help me i am getting this error
> 
> > chmod +x *.sh
> > g++ -std=c++11 -std=c++11 -Iinclude/ -I3rdparty/stb/include -DOPENCV `pkg-config --cflags opencv4 2> /dev/null || pkg-config --cflags opencv` -DGPU -I/usr/local/cuda/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -c ./src/image_opencv.cpp -o obj/image_opencv.o
> > In file included from ./src/image.h:3:0,
> > from ./src/image_opencv.h:4,
> > from ./src/image_opencv.cpp:1:
> > include/darknet.h:41:10: fatal error: cuda_runtime.h: No such file or directory
> > #include <cuda_runtime.h>
> > ^~~~~~~~~~~~~~~~
> > compilation terminated.
> > Makefile:165: recipe for target 'obj/image_opencv.o' failed
> > make: *** [obj/image_opencv.o] Error 1
> 
> I am stuck here for days please help

Hi， do you solve this error？ I have the same error
