### ISSUE TITLE
Changing the save location of chart.png

### ISSUE THREAD

**Issue by enesyuceyurt** [AlexeyAB/darknet#3905]
I am using google colab so every once in a while the virtual machine shuts down. I can redirect the backup directory to my drive for the weights but I dont know how to change the saving folder of chart.png. Do anyone know how can ı change the saving directory of chart.png to the backup directory that is written in obj.data?

**Comment by J-Thunderbolt** [comment]
Did u find any solution?

**Comment by enesyuceyurt** [comment]
> 
> 
> It saves the chat.png file into current directory. So use `%cd "/content/gdrive/My Drive/backup/" ` command before `!/home/AlexeyAB/darknet/darknet detector train /home/AlexeyAB/darknet /build/darknet/x64/data/obj.data /home/AlexeyAB/darknet/yolo-obj.cfg /home/AlexeyAB/darknet/darknet53.conv.74 -map -dont_show | grep avg`

This will try to execute darknet on drive folder, which is not applicable. Instead I had used these pieces of commands. First, you have to create a folder in your drive then link it in colab to a spesific name.
`!ln -s "/content/darknet/drive/My Drive/charts" charts`

Then you can change the saving path with this piece of command below. It will look for the string 'chart.png' in image_opencv.cpp file and change it to charts/chart.png. Charts is the directory that we linked in the previous command.

!sed -i 's/chart.png/charts\/chart.png/g' src/image_opencv.cpp

**Comment by WellML** [comment]
The !sed function does not work for me - it changes the location in image_opencv.cpp, however the chart.png will be still saved in root during training.

Any other suggestions?

**Comment by enesyuceyurt** [comment]
> The !sed function does not work for me - it changes the location in image_opencv.cpp, however the chart.png will be still saved in root during training.
> 
> Any other suggestions?

You should do it before compiling darknet (Before !make command)

**Comment by WellML** [comment]
Yeah I noticed it earlier today. Thanks for your help!
