### ISSUE TITLE
transfer learning

### ISSUE THREAD

**Issue by SouradipBh** [AlexeyAB/darknet#3909]

**Comment by spaul13** [comment]
@SouradipBh @AlexeyAB can u plz tell me how to do transfer learning using this repo. I have a classification model (.cfg) file I have already trained that for 10K iterations, now I want to keep all other layers except the last twos as frozen layers and train for 1K iterations on my new dataset. Can u plz help me saying how to achieve that?

Here I am attaching the .cfg file also.
[myconvnet_yolo_tiny.cfg.txt](https://github.com/AlexeyAB/darknet/files/4200896/myconvnet_yolo_tiny.cfg.txt)

**Comment by HosseinMohammadii** [comment]
hello. Could you solve your problem?
