### ISSUE TITLE
Fast detection during map calculation but slow on test command

### ISSUE THREAD

**Issue by enesyuceyurt** [AlexeyAB/darknet#3928]
Hey people,

When I run the map calculation command
`darknet detector map obj.data model.cfg model_best.weights -thresh 0.25 -iou_thresh 0.6 -letter_box`
The validation is really quick. It finished all 1190 photographs in 2 minutes.
However when ı run the following command to process a list of images(which is exactly the same photos with my validation set)
`darknet detector test obj.data model.cfg model_best.weights -ext_output -letter_box -dont_show -out result.json < final_test.txt`
It takes around 6 minutes for the same 1190 photographs.
The inference time in both of these cases are very close, around 80ms but 'test' command takes much more time then map calculation. I thought maybe the bottleneck is writing the output detections to the disk. But all of this happens on SSD. Another thing I realize that map calculation goes 4 by 4 each time. But 'test' command goes one by one. Maybe its related with this.

Any recommendations on how to improve the time for processing a list of images? I need to process a list of images as fast as ı can and acquire some kind of a numerical output file with detections.

Thanks in advance

**Comment by AlexeyAB** [comment]
@enesyuceyurt Hi,

1. Try to comment these 2 lines and recompile: https://github.com/AlexeyAB/darknet/blob/1c71f001531a5df0637903117c6568725d7a66b3/src/detector.c#L1343-L1344

2. In the mAP - Resizing and Detection are overlaped.

**Comment by enesyuceyurt** [comment]
@AlexeyAB 
That worked out very well, thanks!
