### ISSUE TITLE
"Cuda malloc failed : No error" in tiny-yolo-voc training

### ISSUE THREAD

**Issue by primat000** [AlexeyAB/darknet#393]
I tried to train yolo-voc, but out of memory. Now i want try to train tiny-yolo, but "Cuda malloc failed". I would be grateful if you tell me is it the same problem(i haven't enough memory) or the reason is different?
C:\Users\key\Desktop\YOLO\darknet\build\darknet\x64>darknet.exe detector train data/voc.data yolo-voc.2.0.cfg darknet19_448.conv.23
yolo-voc
layer filters size input output
0 conv 32 3 x 3 / 1 416 x 416 x 3 -> 416 x 416 x 32
1 max 2 x 2 / 2 416 x 416 x 32 -> 208 x 208 x 32
2 conv 64 3 x 3 / 1 208 x 208 x 32 -> 208 x 208 x 64
3 max 2 x 2 / 2 208 x 208 x 64 -> 104 x 104 x 64
4 conv 128 3 x 3 / 1 104 x 104 x 64 -> 104 x 104 x 128
5 conv 64 1 x 1 / 1 104 x 104 x 128 -> 104 x 104 x 64
6 conv 128 3 x 3 / 1 104 x 104 x 64 -> 104 x 104 x 128
7 max 2 x 2 / 2 104 x 104 x 128 -> 52 x 52 x 128
8 CUDA Error: out of memory
CUDA Error: out of memory: No error

C:\Users\key\Desktop\YOLO\darknet\build\darknet\x64>darknet.exe detector train data/voc.data tiny-yolo-voc.cfg darknet19_448.conv.23
tiny-yolo-voc
layer filters size input output
0 conv 16 3 x 3 / 1 416 x 416 x 3 -> 416 x 416 x 16
1 max 2 x 2 / 2 416 x 416 x 16 -> 208 x 208 x 16
2 conv 32 3 x 3 / 1 208 x 208 x 16 -> 208 x 208 x 32
3 max 2 x 2 / 2 208 x 208 x 32 -> 104 x 104 x 32
4 conv 64 3 x 3 / 1 104 x 104 x 32 -> 104 x 104 x 64
5 max 2 x 2 / 2 104 x 104 x 64 -> 52 x 52 x 64
6 conv 128 3 x 3 / 1 52 x 52 x 64 -> 52 x 52 x 128
7 max 2 x 2 / 2 52 x 52 x 128 -> 26 x 26 x 128
8 conv 256 3 x 3 / 1 26 x 26 x 128 -> 26 x 26 x 256
9 max 2 x 2 / 2 26 x 26 x 256 -> 13 x 13 x 256
10 conv 512 3 x 3 / 1 13 x 13 x 256 -> 13 x 13 x 512
11 max 2 x 2 / 1 13 x 13 x 512 -> 13 x 13 x 512
12 conv 1024 3 x 3 / 1 13 x 13 x 512 -> 13 x 13 x1024
13 conv 1024 3 x 3 / 1 13 x 13 x1024 -> 13 x 13 x1024
14 conv 125 1 x 1 / 1 13 x 13 x1024 -> 13 x 13 x 125
15 detection
Loading weights from darknet19_448.conv.23...
seen 32
Done!
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Resizing
352
Cuda malloc failed
: No error

**Comment by AlexeyAB** [comment]
Try this: https://github.com/AlexeyAB/darknet/issues/392#issuecomment-365922894

**Comment by primat000** [comment]
I changed tiny-yolo-voc.cfg, but still the same "Cuda malloc failed". I have a NVIDIA GeForce 610M with 2GB.

**Comment by AlexeyAB** [comment]
* What `batch` and `subdivision` do you use?
* Do you use Desktop-PC or Notebook?

**Comment by primat000** [comment]
I use Notebook,  firstly I tried with batch=64 and subdivisions=32, after that with other values.
Unfortunately when I was monitoring my windows performance monitor GPU dedicated memory was always fully with different combination batch & subdivisions. Probably I really haven't enough memory.

**Comment by AlexeyAB** [comment]
try to use batch=64 subdivision=64

**Comment by primat000** [comment]
Thanks a lot for help
Unfortunately with batch=64 subdivision=64 problem still the same

**Comment by AlexeyAB** [comment]
As I see you use `random=1` in the tiny-yolo-voc.cfg.
Try to use `random=0`

**Comment by primat000** [comment]
Now I have 
C:\Users\key\Desktop\YOLO\darknet\build\darknet\x64>darknet.exe detector train data/voc.data tiny-yolo-voc.cfg darknet19_448.conv.23
tiny-yolo-voc
layer     filters    size              input                output
    0 conv     16  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  16
    1 max          2 x 2 / 2   416 x 416 x  16   ->   208 x 208 x  16
    2 conv     32  3 x 3 / 1   208 x 208 x  16   ->   208 x 208 x  32
    3 max          2 x 2 / 2   208 x 208 x  32   ->   104 x 104 x  32
    4 conv     64  3 x 3 / 1   104 x 104 x  32   ->   104 x 104 x  64
    5 max          2 x 2 / 2   104 x 104 x  64   ->    52 x  52 x  64
    6 conv    128  3 x 3 / 1    52 x  52 x  64   ->    52 x  52 x 128
    7 max          2 x 2 / 2    52 x  52 x 128   ->    26 x  26 x 128
    8 conv    256  3 x 3 / 1    26 x  26 x 128   ->    26 x  26 x 256
    9 max          2 x 2 / 2    26 x  26 x 256   ->    13 x  13 x 256
   10 conv    512  3 x 3 / 1    13 x  13 x 256   ->    13 x  13 x 512
   11 max          2 x 2 / 1    13 x  13 x 512   ->    13 x  13 x 512
   12 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   13 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   14 conv    125  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 125
   15 detection
Loading weights from darknet19_448.conv.23...
 seen 32
Done!
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Loaded: 1.927000 seconds
CUDA Error: invalid device function
CUDA Error: invalid device function: No error

**Comment by primat000** [comment]
After rebuild I got namy errors such as
C:\Users\key\Desktop\YOLO\darknet\build\darknet>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe" -gencode=arch=compute_21,code=\"sm_21,compute_21\" --use-local-env --cl-version 2015 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64"  -IC:\opencv_3.0\opencv\build\include -I..\..\3rdparty\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static     -DOPENCV -D_TIMESPEC_DEFINED -D_CRT_SECURE_NO_WARNINGS -D_CRT_RAND_S -DGPU -DWIN32 -DNDEBUG -D_CONSOLE -D_LIB -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /FS /Zi  /MD " -o x64\Release\network_kernels.cu.obj "C:\Users\key\Desktop\YOLO\darknet\src\network_kernels.cu"
1>  nvcc fatal   : Unsupported gpu architecture 'compute_21'

**Comment by AlexeyAB** [comment]
Try this `compute_20,sm_21;` instead of `compute_21,sm_21;`

**Comment by primat000** [comment]
Thank you very much! It's working.
