### ISSUE TITLE
Training Image Aspect Ratio

### ISSUE THREAD

**Issue by BernoGreyling** [AlexeyAB/darknet#3936]
Hi,
First just want to say thanks for an awesome repo!

I am training a yolo_v3_tiny_pan3 model to detect a single class (small object). I am getting good results but I'm just wondering if it would help if all training images are the same aspect ratio as well? The current model is 832x832 and the training images do not always have a 1:1 aspect ratio but somewhat square. The objects I want to detect are all round.

Would it beneficial to crop all images to a 1:1 aspect ratio as the network input is square, or does the framework handle the cropping?

Thanks!

**Comment by AlexeyAB** [comment]
Just set `letter_box=1` in [net] section in cfg-file. And train. https://github.com/AlexeyAB/darknet/wiki/CFG-Parameters-in-the-%5Bnet%5D-section

**Comment by BernoGreyling** [comment]
Hi @AlexeyAB 

Thanks for the recommendation. Started training again from scratch with `letter_box=1` but i keep getting a mAP of 0% while the loss goes down.

Also using the detector map command with the `-letter_box` flag gives 0%

![Capture](https://user-images.githubusercontent.com/14345568/65146486-3387fb80-da1c-11e9-8472-7a4ff0ab9285.PNG)

**Comment by AlexeyAB** [comment]
Try to train with ` -show_imgs` flag, does it show correct image and bounded boxes?

**Comment by BernoGreyling** [comment]
Everything seems fine. For example: 

![Capture1](https://user-images.githubusercontent.com/14345568/65149888-40f4b400-da23-11e9-9cc7-6202e02e9934.PNG)

**Comment by AlexeyAB** [comment]
Do you get good Loss and mAP chart if you train without `-letter_box=1` in cfg-file?

**Comment by BernoGreyling** [comment]
I had a bit of an older repo and trained the model to where it got to around 4 loss and 82% accuracy. Realized that there were model compilation errors on that repo and that it gave me a `unused field` on `antialiasing`, `assisted_excitation, `stride_x` and `stride_y`.

I then got the newest repo and started training again. No errors this time but got the problems with the `letter_box`. Retraining now without `letter_box` and will report back on the results.

Thanks!

**Comment by BernoGreyling** [comment]
Hi @AlexeyAB ,

Seems there is something not right with my yolo_v3_tiny_pan3.cfg file. I used the same one that you used with the car tracking in the LSTM thread. I trained a new model using the tiny-l3.cfg with `letter_box` enabled and everything worked perfectly.
