### ISSUE TITLE
Load Random Images in Darknet to train Yolo

### ISSUE THREAD

**Issue by JasonRuan5** [AlexeyAB/darknet#3947]
I am trying to understand how images are loaded and trained in darknet.  I’ve noticed there is a method called
char **get_random_paths(char **paths, int n, int m)
which selects n files among total of m files and will be called in max_batches of times.  I just wonder if this will cause some files are selected many times while others are only selected few times (even not at all)?  Is this by design or would be better to have similar number of times that each image is selected?

**Comment by AlexeyAB** [comment]
Yes, in other frameworks is used uniform loading of images, so for 1 epoch will be loaded each image 1 time. So may be we should add this fix and try to train with it.

**Comment by JasonRuan5** [comment]
@AlexeyAB 
Thanks so much!  It would be great if we could have the uniform loading option.  I am not good with C.  If you could advise us what needs to be done in order to have the uniform loading option, we would be greatly appreciated.  I am afraid it would be very hard for us to implement. In case it is not hard, we could try and see if it  makes any better for detection.

**Comment by JasonRuan5** [comment]
I think I got uniform random load and the results seems indeed a bit better.  Basically, I added two global variables and two methods in data.c as below:
```
int g_i0 = 0;
int* g_index = 0; 
int RandomIndex(int i, int m) {
    if (i >= m) {
        i = 0;
        GenerateRandomIndex(m);
    }

    if (!g_index)
        GenerateRandomIndex(m);

    return g_index[i];
}

void GenerateRandomIndex(int m) {
    if (g_index)
        free(g_index);

    g_index = (int*)calloc(m, sizeof(int));
    for (int i = 0; i < m; i++)
        g_index[i] = i;

    // Shuffle Index
    for (int i = 0; i < m; i++) {
        int n = random_gen() % m;
        // swap between i and n
        int tmp = g_index[n];
        g_index[n] = g_index[i];
        g_index[i] = tmp;
    }
}
```
In method of 
`char **get_random_paths(char **paths, int n, int m)`
I replaced 
`int index = random_gen() % m;`
with 
`int index = RandomIndex(g_i0++, m);`

Am I doing correctly?

**Comment by AlexeyAB** [comment]
@JasonRuan5 
Yes.
But there are simultaneously running multiple concurrent functions `load_data_in_thread()` in several threads, so **your implementation should be thread-safety**: https://github.com/AlexeyAB/darknet/blob/2fa539779f4e12e264b9e1b2fc463ac7edec165c/src/detector.c#L130


https://github.com/AlexeyAB/darknet/blob/2fa539779f4e12e264b9e1b2fc463ac7edec165c/src/data.c#L1199-L1227

**Comment by JasonRuan5** [comment]
@AlexeyAB 

Great and thanks!
