### ISSUE TITLE
Filtering logs

### ISSUE THREAD

**Issue by halvomez** [AlexeyAB/darknet#3950]
Hi, Alexey!

During training I need to see only green border logs without red border. 
Is it possible to off print red border logs?

![logs](https://user-images.githubusercontent.com/25098030/65222837-91721d00-dac8-11e9-9da8-d575501ccdd2.jpg)

**Comment by AlexeyAB** [comment]
Try to comment this line: https://github.com/AlexeyAB/darknet/blob/b918bf0329c06ae67d9e00c8bcaf845f292b9d62/src/yolo_layer.c#L406
