### ISSUE TITLE
Object Depth

### ISSUE THREAD

**Issue by johnnydept** [AlexeyAB/darknet#396]
Hi @AlexeyAB , I understand Object detection in Darknet able Computer to detect moving object and classify it.  But can it detect the depth of the object from the camera? 
Like how far is the object from the camera.

**Comment by AlexeyAB** [comment]
@johnnydept Hi, do you mean distance to the object?
Do you have only 1 camera, or 2 camera as stereo-vision?
Both ways are very inaccurate in determining the distance, so many companies use active radiating cameras: https://github.com/AlexeyAB/darknet/issues/73#issuecomment-299217141

Probably you can try to train network to get distance as additional 5-th coords.

----

The simplest way is:
If you have only 1 simple camera, and if your object has fixed physical size - the distance to the object will be proportional to the size in pixels (width or height) of this object. For this you should find coefficient for each pair of object_class and camera.
If your object has fixed physical size, but different size from different sides, then you should train network to detect different size of the single object as different objects with the same name, and different sides will have coefficients (distance/width_pixel).

**Comment by johnnydept** [comment]
@AlexeyAB  thanks Alex, thats what i need. im sorry for this novice question :)
