### ISSUE TITLE
table OCR with YOLO

### ISSUE THREAD

**Issue by halvomez** [AlexeyAB/darknet#3962]
Hi, Alexey!
Big thank for your work, it’s looking amazing!

I have a few questions about YOLO and Darknet.
I work with OCR project and digitization of a table documents. 
I want to extract certain fields from tables. For example extracting class1, class2, class3.

![table](https://user-images.githubusercontent.com/25098030/65331074-ad5ae900-dbc4-11e9-97c4-2d201c3869d7.jpg)

Is it possible with Yolo?

If yes, so:

1. How to mark images better if I want to extract 1360 info, do I need to capture field with static code for more precise definition (one common bbox for static 1300 and dynamic 1360 together) or only bbox with 1360?

![field1](https://user-images.githubusercontent.com/25098030/65331087-b8157e00-dbc4-11e9-9e31-b30a21a5481e.jpg)
or
![field2](https://user-images.githubusercontent.com/25098030/65331092-bb106e80-dbc4-11e9-929b-65faab40b19d.jpg)

2. Do I need to mark field if field is empty?

3. Docs are usually A4 format with different orientation. Is better to use the flag -letter_box?

4. Can I use 416x416 network or better to increase width x height?

5. Is better to recalc anchors for my dataset or take default anchors from yolov3.cfg?

6. Does it make sense to preprocess images: convert to grayscale or correct an orientation?

Thank you for your time!

**Comment by AlexeyAB** [comment]
1. mark one common bbox for static 1300 and dynamic 1360 together. If I understand correctly what do you want.

2. Yes, if you want to detect empty field

3. If there are only 2 aspect ratios then don't use letter_box

4. It depends on relative size of object. May be better 608x608

5. Don't recalculate anchors

6. It isn't necessary, but if you can - do it.
