### ISSUE TITLE
Can my trained model be converted to ONNX?

### ISSUE THREAD

**Issue by monocongo** [AlexeyAB/darknet#3963]
I am attempting to use this model in NVIDIA DeepStream, which (as far as I can tell, this is my first attempt) will require converting this model, and perhaps the corresponding weights after training, to ONNX format so I can then feed that into TensorRT for use by a DeepStream inference plugin.

I have successfully trained the model on my custom dataset and have the weights and *.cfg file. Can anyone advise how I can use these to get a corresponding model in ONNX format?

Thanks in advance for any suggestions or insight.

**Comment by AlexeyAB** [comment]
With the last version of TensorRT you can use Yolo v3 models directly without converting.

Yolo is natively supported in DeepStream 4.0 https://news.developer.nvidia.com/deepstream-sdk-4-now-available/

**Comment by monocongo** [comment]
Thanks, Alexey. And thanks in general for all of your hard work and support on this repository, I'm standing on the shoulders of a giant.

**Comment by betegon** [comment]
I monocongo, How did you finally convert the model into ONNX format? I am trying to do it for using Yolov3 on Jetson nano, as it is quite slow.

Thanks a lot.

**Comment by betegon** [comment]
I @monocongo How did you finally convert the model into ONNX format? I am trying to do it for using Yolov3 on Jetson nano, as it is quite slow.

Thanks a lot.
