### ISSUE TITLE
Cannot detect objects after trainning

### ISSUE THREAD

**Issue by Lavistas** [AlexeyAB/darknet#3968]
Hello,
I 've done everything as instructed from the guide. I used tiny yolov3, i trained around 1000 images with opencv. The average loss after 6000 iterations is 0.838325. I change the filters and steps accordingly to the instructions. During training, non bad.list text is created. I created darknet.exe using build.ps1 and also with cmake.  I trained my images with yolo mark. 
Even after that, when i try to test my images, boxes are not drawn on the objects. 
Have anyone had a similar problem?

[yolov3-tiny-obj.txt](https://github.com/AlexeyAB/darknet/files/3639546/yolov3-tiny-obj.txt)

**Comment by AlexeyAB** [comment]
@Lavistas Hi,

What mAP do you get on Training or/and Validation datasets?

**Comment by Lavistas** [comment]
Thank you for your answer.

with the command "darknet.exe detector map data\objects.data cfg\yolov3-tiny-obj-test.cfg backup\yolov3-tiny-obj_final.weights", i get the results:

detections_count = 577, unique_truth_count = 349
class_id = 0, name = knife, ap = 16.08%          (TP = 0, FP = 1)
class_id = 1, name = rifle, ap = 50.00%          (TP = 0, FP = 0)
class_id = 2, name = pistol, ap = 62.12%         (TP = 4, FP = 0)

 for conf_thresh = 0.25, precision = 0.80, recall = 0.01, F1-score = 0.02
 for conf_thresh = 0.25, TP = 4, FP = 1, FN = 345, average IoU = 60.16 %

 IoU threshold = 50 %, used Area-Under-Curve for each unique Recall
 mean average precision (mAP@0.50) = 0.427346, or 42.73 %
Total Detection Time: 21.000000 Seconds

**Comment by AlexeyAB** [comment]
@Lavistas 
What mAP for Training dataset?

**Comment by Lavistas** [comment]
@AlexeyAB 
Is these the mAP:"6000: 0.862153, 0.838325 avg loss, 0.000005 rate, 19.782000 seconds, 384000 images"?
I cannot find any command for calculate the mAP other the one you give in your project.

**Comment by AlexeyAB** [comment]
show content of `data\objects.data` file

**Comment by Lavistas** [comment]
These are the contents of data\objects.data:
classes= 3
train  = C:/Users/silav/Desktop/darknet/data/train.txt
valid  = C:/Users/silav/Desktop/darknet/data/test.txt
names  = C:/Users/silav/Desktop/darknet/data/objects.names
backup = C:/Users/silav/Desktop/darknet/backup

These are the contents of data\objects.name:
knife
rifle
pistol

**Comment by AlexeyAB** [comment]
set `valid = C:/Users/silav/Desktop/darknet/data/train.txt`
and check mAP again

**Comment by Lavistas** [comment]
@AlexeyAB 
Thank you once more.
These are the results:

detections_count = 2764, unique_truth_count = 1171
class_id = 0, name = knife, ap = 36.11%          (TP = 1, FP = 3)
class_id = 1, name = rifle, ap = 61.89%          (TP = 27, FP = 9)
class_id = 2, name = pistol, ap = 72.99%         (TP = 109, FP = 11)

 for conf_thresh = 0.25, precision = 0.86, recall = 0.12, F1-score = 0.21
 for conf_thresh = 0.25, TP = 137, FP = 23, FN = 1034, average IoU = 61.48 %

 IoU threshold = 50 %, used 11 Recall-points
 mean average precision (mAP@0.50) = 0.569959, or 57.00 %
Total Detection Time: 159.000000 Seconds

**Comment by AlexeyAB** [comment]
Train with default anchors from the begining.
And train with flag `-map` at the end of training command.

**Comment by Lavistas** [comment]
@AlexeyAB 
I will do and I will let u know!
Thank u for your time!

**Comment by AlexeyAB** [comment]
> When i trained the network without opencv, i had better results, as shown below:

In this case without OpenCV you use `final` weights and `00017.jpg` file.
While in case with OpenCV you use `best` weights and `0003.jpg` file. 
This is a wrong comparison.

----

Try to use `final` weights and `00017.jpg` file. with OpenCV.

Also try to use `-thresh 0.15` at the end of detection command

**Comment by Lavistas** [comment]
@AlexeyAB 
I have the same problem:
![unsuccess](https://user-images.githubusercontent.com/51375624/65520059-a9de9f00-deef-11e9-88c7-d82525aa2b05.jpg)

But I tried with another image and I had a satisfying result:
![success](https://user-images.githubusercontent.com/51375624/65520150-d0043f00-deef-11e9-98f4-f46d3fb7edd9.jpg)

Maybe there is something wrong with some images?

**Comment by AlexeyAB** [comment]
What mAP can you get with the model which is trained without OpenCV?

**Comment by Lavistas** [comment]
This is the mAP without OpenCV. I don't think this is a good prediction:

calculation mAP (mean average precision)...
52
 detections_count = 136, unique_truth_count = 57
class_id = 0, name = rifle, ap = 3.13%           (TP = 0, FP = 5)
class_id = 1, name = knife, ap = 1.39%           (TP = 0, FP = 3)
class_id = 2, name = pistol, ap = 53.82%         (TP = 5, FP = 0)

 for conf_thresh = 0.25, precision = 0.38, recall = 0.09, F1-score = 0.14
 for conf_thresh = 0.25, TP = 5, FP = 8, FN = 52, average IoU = 28.46 %

 IoU threshold = 50 %, used Area-Under-Curve for each unique Recall
 mean average precision (mAP@0.50) = 0.194442, or 19.44 %
Total Detection Time: 5.000000 Seconds

Set -points flag:
 `-points 101` for MS COCO
 `-points 11` for PascalVOC 2007 (uncomment `difficult` in voc.data)
 `-points 0` (AUC) for ImageNet, PascalVOC 2010-2012, your custom dataset

**Comment by AlexeyAB** [comment]
> When i trained the network without opencv, i had **better results**, as shown below:

> This is the mAP without OpenCV. I **don't think this is a good prediction**:

This is very strange how do you get `better result` with this low 19.44% mAP without OpenCV.

**Comment by Lavistas** [comment]
@AlexeyAB 
please check the following image(trained with opencv):
![check](https://user-images.githubusercontent.com/51375624/65607103-a4975800-dfb4-11e9-926a-12bf2ebf2eb1.jpg)

What I meant with "better result" is that with opencv boxes are not drawn on the image but without opencv boxes are drawn as they should. Is there any explanation for this? Should  I change something to my cfg or the cmake file?

**Comment by AlexeyAB** [comment]
> What I meant with "better result" is that with opencv boxes are not drawn on the image but without opencv boxes are drawn as they should. Is there any explanation for this?

On Training and Validation images the model with OpenCV should work much better.

As I see you get good result with OpenCV.
So use this model.

**Comment by Lavistas** [comment]
@AlexeyAB 
Thank you.
This is the model i want to use for live detection. The thing is that a class(pistols) are recognised and the boxes are drawn for these images. But for the rest of them (rifle-knives) i cannot see any box, even for those i have trained. It is very strange because i trained the same number of images for the 3 classes. Maybe I have to increase iterations above 6000. Nevermind, I thank you for your time!

**Comment by AlexeyAB** [comment]
Try to train more.
Or try to use `-thresh 0.15` at the end of detection command.

**Comment by Lavistas** [comment]
@AlexeyAB 
Thank you very much!!
I will train more with these parameters!
