### ISSUE TITLE
Video memory consumption on different devices

### ISSUE THREAD

**Issue by sealedtx** [AlexeyAB/darknet#3974]
Hi, why does my network have different video mem consumption on 1080ti and 2080ti:
1080 - 800mb
2080 - 1000mb

My makefile:
GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=1
AVX=1
OPENMP=0
LIBSO=1
ZED_CAMERA=0
DEBUG=0

ARCH= -gencode arch=compute_61,code=[sm_61,compute_61] -gencode arch=compute_75,code=[sm_75,compute_75]

**Comment by sealedtx** [comment]
@AlexeyAB Any thoughts?

**Comment by AlexeyAB** [comment]
1. Show initial memory consumption before Darknet is launched

2. cuDNN can allocate addition memory, so try to compile with CUDNN=0

**Comment by sealedtx** [comment]
@AlexeyAB 
1.  I tried it on empty gpu, so initial memory is free
2. Yes cuDNN allocates additional memory, but why it allocates different on those devices? I don't want to disable it, because performance will suffer

**Comment by AlexeyAB** [comment]
1. Often initial memory isn't free
2. Different architecture require different CUDA-functions which occupy different memory sizes

**Comment by sealedtx** [comment]
Understand. I hoped that new gpu card would be more perfomant and would take less memory :(
