### ISSUE TITLE
Customer Object Detect error: names: Using default 'data/names.list' Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by piggybit** [AlexeyAB/darknet#3978]
I am trying to detect custom object and got this error:
----------------------------------
./darknet detector test cfg/yolov3-thang.cfg cfg/thang.data yolov3-thang_4000.weights data/thangvid.mp4 
names: Using default 'data/names.list'
Segmentation fault (core dumped)
----------------------------------
yolo cfg content:
[convolutional]
filters=18
..
[yolo]
classes=1

--------------
cat cfg/thang.data 
classes= 1
#train  = data/train.txt
#valid  = data/test.txt
#valid = data/coco_val_5k.list
names = data/thang.names
#backup = backup/
#eval=coco

--------------------
cat Makefile | more
GPU=1
CUDNN=0
CUDNN_HALF=0
OPENCV=1
AVX=0
OPENMP=0
LIBSO=0
ZED_CAMERA=0

**Comment by lsd1994** [comment]
It seems something wrong on your data/thang.names.

**Comment by piggybit** [comment]
yeah, i dont know, but seems the script is using the default names.list, dont know why, i pointed out in the command line but no idea why it's happening.

**Comment by piggybit** [comment]
Even i use the same with original yolov3 it has the same symptom.

**Comment by AlexeyAB** [comment]
Use
`./darknet detector test cfg/thang.data cfg/yolov3-thang.cfg yolov3-thang_4000.weights data/thangvid.mp4`

instead of
`./darknet detector test cfg/yolov3-thang.cfg cfg/thang.data yolov3-thang_4000.weights data/thangvid.mp4`

**Comment by piggybit** [comment]
> Use
> `./darknet detector test cfg/thang.data cfg/yolov3-thang.cfg yolov3-thang_4000.weights data/thangvid.mp4`
> 
> instead of
> `./darknet detector test cfg/yolov3-thang.cfg cfg/thang.data yolov3-thang_4000.weights data/thangvid.mp4`

still the same:
./darknet detector test cfg/yolo-obj.cfg cfg/thang.data yolov3-thang_4000.weights data/thangvid.mp4 
names: Using default 'data/names.list'
Segmentation fault (core dumped)
--------------
cat cfg/thang.data 
classes= 1
train  = data/train.txt
#valid  = data/test.txt
#valid = data/coco_val_5k.list
names = /home/alexdarknet/darknet/data/thang.names
backup = backup/
#eval=coco
-----------
Is that because when i trained, i saw this?
./darknet detector train data/thang.data cfg/yolo-obj.cfg darknet53.conv.74
............
384 x 384 
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
Invalid SOS parameters for sequential JPEG
............

**Comment by piggybit** [comment]
Use the right syntax:
./darknet detector test cfg/obj.data cfg/yolov3-obj.cfg yolov3-thang_4000.weights data/thangvid.mp4
