### ISSUE TITLE
Calculate PR values with 30 points

### ISSUE THREAD

**Issue by ani16** [AlexeyAB/darknet#3986]
Hi Alex

Hi Alex

I used following command still gives 11 points

./darknet detector map data/obj.data yolo-obj.cfg backup/yolo-obj_7000.weight -points 30

Please tell me what to use for 30 points.

2. one more thing if I want to find PR values at different iou-threshold. what is the criteria for that? Do I need to make changes in code.

**Comment by AlexeyAB** [comment]
@ani16 Hi,

I uncommented this line: https://github.com/AlexeyAB/darknet/blob/05545b260784cb5ce9b27f85462c4a31137b684b/src/detector.c#L1035

I used this command:
`./darknet detector map cfg/coco.data cfg/yolov3-tiny.cfg yolov3-tiny.weights -points 30`

and get this result with 30 points:
![image](https://user-images.githubusercontent.com/4096485/65593274-cbe02c00-df98-11e9-9213-3d7fc855c87a.png)

**Comment by ani16** [comment]
Hi Alex... In your results too, after few points you are also getting 0
value in precision as the case was mine..

**Comment by AlexeyAB** [comment]
No, in your result you get `Recall=1.1` > `1.0` that is wrong:  https://github.com/AlexeyAB/darknet/issues/3938#issuecomment-533409742

----

For 10 points after few points you are also getting 0.
This is normal, this is how PR-curve works.

**Comment by ani16** [comment]
Hi Alex. How to rectify that. I used the same command as you used. Please
help me with this.

**Comment by ani16** [comment]
Yes Alex You are right there is something wrong in recall calculation. But I un comment the said line , it is not giving 30 points.

Thanks alot.
