### ISSUE TITLE
Problem when custorm train with yolo_v3_tiny_pan3.cfg.txt

### ISSUE THREAD

**Issue by agutuyen** [AlexeyAB/darknet#3990]
Hi Alexey,
When i custom train with yolo_v3_tiny_pan3.cfg.txt on GTX 1070
Error:
 cuDNN status Error in: file: ./src/convolutional_layer.c : () : line: 249 : build time: Sep 26 2019 - 10:38:59
cuDNN Error: CUDNN_STATUS_BAD_PARAM
cuDNN Error: CUDNN_STATUS_BAD_PARAM: File exists
darknet: ./src/utils.c:293: error: Assertion `0' failed.
Aborted (core dumped)

**Comment by AlexeyAB** [comment]
Do you use the latest version of Darknet?
What CUDA, cuDNN and OpenCV versions do you use?
Show output of command
```
nvcc --version
nvidia-smi
```

**Comment by agutuyen** [comment]
I used the latest version of Darknet
**iblab@ibl:~$ nvcc --version**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

**iblab@ibl:~$ nvidia-smi**
Thu Sep 26 17:30:22 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.26       Driver Version: 430.26       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:01:00.0  On |                  N/A |
| 49%   37C    P8    10W / 180W |     93MiB /  8118MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  P106-100            Off  | 00000000:03:00.0 Off |                  N/A |
| 36%   32C    P8     5W / 120W |      0MiB /  6080MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1507      G   /usr/lib/xorg/Xorg                            27MiB |
|    0      1562      G   /usr/bin/gnome-shell                          63MiB |
+-----------------------------------------------------------------------------+

**Comment by AlexeyAB** [comment]
attach your cfg-file

**Comment by agutuyen** [comment]
[
[yolo_v3_tiny_pan3.cfg.txt](https://github.com/AlexeyAB/darknet/files/3657429/yolo_v3_tiny_pan3.cfg.txt)

](url)

**Comment by AlexeyAB** [comment]
Yes, PAN3 model doesn't work with `random=1`

Try to use `random=0`

**Comment by agutuyen** [comment]
OK, it work. Thanks
