### ISSUE TITLE
Train without data augmentation

### ISSUE THREAD

**Issue by chtouroumahdi** [AlexeyAB/darknet#3997]
Hi,

Please how can i train without using any data augmentation ( no augmentation at all).

**Comment by AlexeyAB** [comment]
Set `flip=0` and `angle=0` in [net] in cfg-file.
Set `jitter=0` in [yolo] in cfg-file

And comment all lines in cfg-file with params:
random=
hue=
saturation=
exposure=
mixup=
blur=
