### ISSUE TITLE
Training ended immediately after loading weights

### ISSUE THREAD

**Issue by xxzl0130** [AlexeyAB/darknet#4001]
I'm using yolov3.cfg and yolov3.weights, and when I start training command the program shows saving final weights and end. It never enter training program.
![Snipaste_2019-09-28_10-23-07](https://user-images.githubusercontent.com/9150038/65810205-0be22180-e1da-11e9-8d70-f4227334c8ab.jpg)

**Comment by Chimpola** [comment]
Hi xxzl0130,
I'm getting this also, did you solve it?
best,
J

**Comment by lsd1994** [comment]
@Chimpola 
It seems the batch of training reach the max batches so training stop.
