### ISSUE TITLE
Is it possible to put a cap on or control FPS ?

### ISSUE THREAD

**Issue by bagminer** [AlexeyAB/darknet#4005]
Hi, I am getting FPS on videos ranging from 16 to 25 FPS. Is it possible to put a cap on FPS and maintain it to 16 FPS? In the end, I want to synchronize the output video with the streaming audio.

**Comment by haviduck** [comment]
Im working on an approach for this, but its handled by a third party client that reads the json stream. My idea is to count all frames within a 2000ms interval. Since i know the input videos framerate i should be able to figure out the variable fpss actual second count. I dont want to cap the fps as i want yolo to run at full capacity.

**Comment by LukeAI** [comment]
why not have a circular buffer for your input video stream and as soon as yolo is available, pass it the most recent image in the buffer, whatever it is. You can also improve FPS by having two (or three?) instances of darknet running and passing the latest image to whichever instance is next available.

**Comment by bagminer** [comment]
@haviduck and @LukeAI, thanks for the help.
Right now I am trying to store the 25 frames into a buffer, and once the 25 frames are stored I am releasing them together in the output stream for synchronization. But not sure if the logic and code is correct or not.

In Demo.c,
I am doing following additions after,

`// save video file
if (output_video_writer && show_img) {
write_frame_cv(output_video_writer, show_img);
printf("\n cvWriteFrame \n");
}`

`mat_cv* image_buffer[25];  //image buffer declaration`

` image_array[count_frames] = show_img;   //storing the show_img `

Not sure how to release it to RTSP or RTMP stream.

**Comment by haviduck** [comment]
What do you do if the framerate drops? U gonna need a buffer upfront or something.. Ive added datetime and a seconds counter to the json array output. Im using the data alongside a realtime videofeed (using a js player supporting realtime fps changes) and streamer charts. This takes mimimum math clientside and ensures a synced experience while yolo does what it does best. U could check out the cap.set(cv2.cv.CV_CAP_PROP_FPS, 60) function, imagecpp should be the playground

**Comment by haviduck** [comment]
know this is closed, but ive had to try and do like you and i thought about this: 

in demo.c at the while loop around 225:

`int now;
int lastFrame = time(0);
    while (1) {
     now = time(0);
    int delta = now - lastFrame;
    lastFrame = now;

    if(delta < 33)
    {
        Sleep(33 - delta);
    }`

its nowhere near perfect, but atleast im not pulling 80fps anymore!
