### ISSUE TITLE
Visualization of training progress is truncated at bottom of graph

### ISSUE THREAD

**Issue by monocongo** [AlexeyAB/darknet#4013]
On several occasions, I have had the visualization of training progress (loss and mAP graph) become truncated towards the bottom of the image (see attached image), often the entire lower half. This renders the visualization useless since most of the information, especially after a number of iterations, is at the bottom of the page. 

![Screenshot from 2019-10-02 02-30-42](https://user-images.githubusercontent.com/1328158/66022699-cb75f280-e4bc-11e9-9bdc-aad0dffe218e.png)

This is happening when I run training on an EC2 instance using a command such as this:
```
$ nohup ./darknet detector train build/darknet/x64/data/obj.data cfg/yolov3-tiny-608.cfg backup/yolov3-tiny-608_last.weights -mjpeg_port 8090 -map -dont_show -gpus 0,1,2,3,4,5,6,7 2>&1 >> log_yolov3_tiny_20191002.txt
```
I am viewing the visualization on my local machine (Ubuntu 18.04) using Firefox browser.

This can be rectified if I stop and resume the training, but this is problematic because the images shown after a resumption only include the loss and mAP measurements from the most recent starting point (historical data from earlier iterations are lost).

Can anyone comment as to why this may be happening and/or how I can prevent this behavior? Thanks in advance for any suggestions or insight.

**Comment by AlexeyAB** [comment]
Try to use `5000000` instead of `500000`
there: https://github.com/AlexeyAB/darknet/blob/2fa539779f4e12e264b9e1b2fc463ac7edec165c/src/image_opencv.cpp#L1116

**Comment by monocongo** [comment]
Thank you, @AlexeyAB. This problem is intermittent, it comes and goes, and I'm not convinced that it's a result of the code. Nevertheless, I will give the proposed fix above a whirl and I really appreciate the quick help.

**Comment by yrc08** [comment]
@monocongo 
Hi！
How to solve the image displayed after stopping the training recovery only includes the loss of the nearest starting point and the mAP measurement value (the historical data of early iterations will be lost).

**Comment by monocongo** [comment]
Yes, @yrc08 , that was my experience as well. I'm not sure where the results are kept but it seems that it might be trivial to store these somehow (in a CSV file, etc.) but I'm only loosely familiar with the project and have no real insight as to the inner workings. Maybe this is a reasonable feature request?
