### ISSUE TITLE
Negative Coordinates during detection!

### ISSUE THREAD

**Issue by MhmdDimassi** [AlexeyAB/darknet#4018]
@AlexeyAB 
Hello,
I did my training using Yolov3 algorithm and based on Alexey/darknet framework,
And during the detection i am running the command below in order to generate a .txt file contains the detection over a directory of images

"**./darknet detector test  ~/.../obj.data ~/.../yolov3.cfg ~/.../yolov3_8000.weights -dont_show -ext_output < data/train.txt > result.txt**"

The problem is the result.txt contains coordinates out of the image:
- Negative coordinates
- Coordinates greater than image dimensions

So, anyone have an idea about these values?

Example from result.txt:

73%	(left_x:   28   **top_y: -170**   width:  646   height: 1392)

**Comment by AlexeyAB** [comment]
It may be true that the left corner of the object is outside the image.
