### ISSUE TITLE
Very poor detection performance with 1,000 images

### ISSUE THREAD

**Issue by rgov** [AlexeyAB/darknet#4023]
I am trying to use YOLO to detect fish in video frames. I have pre-processed all the video frames to perform foreground extraction (in the green channel) and motion detection (in the blue channel), which results in fish appearing as elliptical blobs that are generally easy for humans to spot. [Here's one](https://user-images.githubusercontent.com/108767/66129270-91d8e080-e5bd-11e9-9e7d-8d68389f8330.jpg). (And [here is the original image](https://user-images.githubusercontent.com/108767/66129648-568ae180-e5be-11e9-9ba5-35901e287917.jpg), which is not what I'm training on.)

I have 1,066 training images containing objects (all of a single class), as well as an additional 1,059 training images which do not contain objects. My test image set contains 115 images with objects and 122 without.

I am using `darknet53.conv.74` as my initial network weights but if there is a better one to use for this data set, please let me know.

I have modified the configuration file to change `classes=1` and `filters=18` and `steps=1600,1800` as suggested, and increased `width` and `height` to 608 each.

As recommended, I train on a single GPU for 1,000 iterations and then stop and pick up training with multiple GPUs. It does a total of 2,000 iterations:

```
 2000: 1.445988, 1.344122 avg loss, 0.000020 rate, 9.937896 seconds, 256000 images
```

The results are very poor, and I need to set my detection threshold to something like 1% to get in the vague region of my object. [Here are the predictions](https://user-images.githubusercontent.com/108767/66129363-c2207f00-e5bd-11e9-8f14-c7faee3f301a.jpg) when I drop the threshold. It detects 7 objects that might be fish with 1-2% confidence. The objects are at least generally in the right vicinity.

Is there anything more that I can do to improve detection quality significantly?

**Comment by AlexeyAB** [comment]
Train at least 4000 iterations, set max_batches=4000 steps=3200,3600

Run training with `-show_imgs` flag at the end of training command and show screenshots of images with boxes.

Your Training images must be very similar to Test images: https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

**Comment by rgov** [comment]
Thanks, I will increase the iteration count.

> Your Training images must be very similar to Test images

They are randomly selected from frames of the same video. I hope that is similar enough.

**Comment by AlexeyAB** [comment]
> Your Training images must be very similar to Test images
> 
> They are randomly selected from frames of the same video. I hope that is similar enough.

Do you use pre-processed images for Training, and non-pre-processed images for Detection? So the are not similar.

**Comment by rgov** [comment]
All the images are pre-processed, I'm not running it on the raw original video frames at all. I understand what you mean.

**Comment by AlexeyAB** [comment]
Just train 4000 - 6000 iterations

**Comment by rgov** [comment]
Is there an ideal split between training and testing set sizes? Right now I'm shooting for about 90% training and 10% testing.

**Comment by rgov** [comment]
Also could you clarify what `-show_imgs` does? I'm running the training on a headless server, so it cannot display a GUI window or anything. Can I run this later with the trained weights somehow?

**Comment by AlexeyAB** [comment]
Usually 90/10 - 80/20

**Comment by rgov** [comment]
Indeed, this was my fault—my input images and labels were off by one. After correcting the issue, I have much lower loss after only 1000 iterations and labels start to make more sense. Kind of remarkable it worked even a little bit when things were not correlated!
