### ISSUE TITLE
Avg Loss = 1.75 after 50,000 iterations (Tiny Yolo)

### ISSUE THREAD

**Issue by naivoder** [AlexeyAB/darknet#4024]
Is it safe to assume that there is something going wrong with training? Most examples I've seen show loss dropping below 1 within a few thousand iterations. Should I stop the training now or let it run for a few more days?
![chart](https://user-images.githubusercontent.com/50840311/66134416-4d057780-e5c6-11e9-99ef-72f7d7c9d09f.png)

**Comment by AlexeyAB** [comment]
What cfg-file and what dataset do you use?

https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

> my Loss is very high and mAP is very low, is training wrong? Run training with `-show_imgs` flag at the end of training command, do you see correct bounded boxes of objects (in windows or in files aug_...jpg)? If no - your training dataset is wrong.

**Comment by naivoder** [comment]
@AlexeyAB thank you for the response. I am using a .cfg file based on yolov3-tiny.cfg, my dataset was pulled from google images and has about 2000 images for each of three classes.

![aug_1266752695_0_00e465d9d57512d5_455162742](https://user-images.githubusercontent.com/50840311/66136347-50e6c900-e5c9-11e9-911f-5d5294d01a7f.jpg)

Yes, when I run training with -show_imgs I do see images with the bounding boxes, however they are not exactly correct.

**Comment by AlexeyAB** [comment]
Your dataset is wrong.

In Yolo x and y is ceneter of object, is not left-top-corner.

**Comment by naivoder** [comment]
Thanks again Alexey, I must've gotten the the formats mixed up in one of my scripts.
