### ISSUE TITLE
Multiclass labeling on YOLOV3-SPP-LSTM?

### ISSUE THREAD

**Issue by WadRex** [AlexeyAB/darknet#4029]
Hello, 
Is it possible to create a superclass and a subclass using LSTM version of yolov3-spp? For example superclass ("person") and subclasses ("jumping" or "standing")
Thanks in advance!

**Comment by AlexeyAB** [comment]
@WadRex Hi,

There is multiclass rather than subclasses. In Yolo v3.

Just mark two bboxes with the same x,y,w,h and different class_id.

**Comment by WadRex** [comment]
@AlexeyAB 

Will I get 2 predictions as output? 
First with "person" and second with either of two variants?

**Comment by AlexeyAB** [comment]
Yes.
You will get two detections with the same `x,y,w,h,probabiliry` but with different class id

**Comment by WadRex** [comment]
Ok, thanks a lot
