### ISSUE TITLE
Training finishes too fast, empty chart

### ISSUE THREAD

**Issue by VZcoding** [AlexeyAB/darknet#4035]
Finally compiled the project with cuda successfully. Now trying to train some simple custom data, using Vott labeling tool. Just some images with numbers from 1 to 5. And once again training finishes in seconds, empty graph window appears for breaf moment and closes. Also no weight file gets created in backup folder. As I understand the training should loop forever until I stop it and output something in the graph?? Sorry for newbie questions, but I really want to get in to this...

![Untitled](https://user-images.githubusercontent.com/35932738/66303429-a8f03900-e903-11e9-8eb9-84a7b45d4c9b.png)

**Comment by AlexeyAB** [comment]
Read error messages.

**Comment by VZcoding** [comment]
Which is one causing this? Which labeling tool is best to use than, that it would annotate correctly?

**Comment by AlexeyAB** [comment]
Look at the train.txt file

Also read
https://github.com/AlexeyAB/darknet#how-to-mark-bounded-boxes-of-objects-and-create-annotation-files

and
https://github.com/AlexeyAB/Yolo_mark

**Comment by VZcoding** [comment]
Thank you. Okey now I deleted the files from the list it could not find. Now it was working fine, repeated the training for 100 times, while doing so the chart opened was still empty. Still getting wrong annotation errors, why is that? And still no weights file being created in backup folder....

![Untitled](https://user-images.githubusercontent.com/35932738/66343608-ae29a400-e954-11e9-85ae-866a0fe603c4.png)

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet#when-should-i-stop-training

Usually sufficient 2000 iterations for each class(object), but **not less than 4000 iterations in total.**

**Comment by VZcoding** [comment]
How can I increase number of iterations ?

**Comment by VZcoding** [comment]
Now it is saving, but backup folder has to be in same directory as darknet.exe
