### ISSUE TITLE
Images and Annotations in one file?

### ISSUE THREAD

**Issue by WadRex** [AlexeyAB/darknet#4058]
Hi,
I wanted to ask if it's possible to somehow compress images and annotations in one file. Something like numpy array? Because when dataset is small it's not big deal, but when dataset is big (in my case >150k images + 150k annotations) it becomes a real pain to work with.

+Completely unrelated. Is Partial for SPP-LSTM same as for SPP?
darknet.exe partial cfg/yolov3-spp.cfg yolov3-spp.weights yolov3-spp.conv.85 85

Thanks in advance!

**Comment by AlexeyAB** [comment]
No.
What is the problem of working with 100k images?

> +Completely unrelated. Is Partial for SPP-LSTM same as for SPP?
> darknet.exe partial cfg/yolov3-spp.cfg yolov3-spp.weights yolov3-spp.conv.85 85

Yes.

**Comment by WadRex** [comment]
I am not home right now, so I can't reach my main PC. The specifications of laptop I have rn are very bad. HDD is slow + I got very low amount of RAM, so when I try to move images from one folder to another it takes ages. (I need to do this after automatic annotation to check if labels are correct in "Yolo-Mark") + My dataset is constantly growing.
It is not a problem with my main PC
