### ISSUE TITLE
Training runs fine but detector valid raises segmentation fault

### ISSUE THREAD

**Issue by guischmitd** [AlexeyAB/darknet#4060]
I've compiled with GPU and OPENCV support, I've already ran the examples and my custom trained model runs fine on single images and video (even 4K on realtime), but when I try to run `./darknet detector valid` I get segmentation fault (Core dumped). I usually assume that means not enough memory... So I already tried reducing image size and batch=1, subdivisions=1. My model was trained on pjreddie's darknet but I've tested resuming training from my weights file and it runs fine with batches up to 64 images with 4 subdivisions on my GTX 1660

I'm running on Ubuntu 18.04 with opencv 3.4.0 compiled from source, CUDA 10 and CUDNN 7.5.

**Comment by AlexeyAB** [comment]
Do you use this  https://github.com/AlexeyAB/darknet or original https://github.com/pjreddie/darknet  repo ?

Try to run `./darknet detector map`... instead of valid

Show your obj.data file

**Comment by guischmitd** [comment]
That solved it, I was so used to `detector valid` that I didn't even check if there was a different evaluation method, thanks for the quick reply, your repo rocks! hahaha
