### ISSUE TITLE
Working with greyscale images

### ISSUE THREAD

**Issue by DoriHp** [AlexeyAB/darknet#4061]
I'm dealing with detecting faces in greyscale images. So I'm having two following question: first, whether yolov3 perform better with greyscale than color images (in both speed and accurracy) , and what must I do if I want training yolov3 using a greyscale dataset?
Thanks in advance.

**Comment by lsd1994** [comment]
speed:a little faster(may 1%?not sure)
accurracy:decrease
should do:change channels=1 in cfg file
