### ISSUE TITLE
Tiny-yolov3 not detecting on high-res images

### ISSUE THREAD

**Issue by jesusatgar** [AlexeyAB/darknet#4064]
Hello,
I have been training my model with relatively small images (416x416) with smaller objects in them. When using a webcam, the detections are shown correctly with a nice FPS(~20), but, when using a high-res camera these detections are not show, or shown in incorrect places. 

What should I do? I have tried changing the height and width settings in the .cfg file, as well as lowering the resolution of the input image, with no positive results. 

Any thoughts on this?
Thanks!

**Comment by AlexeyAB** [comment]
Did you change width= height= in cfg-file after training?

Show screenshots of incorrect detections.

**Comment by jesusatgar** [comment]
Yes, I did change width and height after training, and with different sizes (higher and smaller). I will try to post pictures of the detections as soon as I can. But, in short, if the object is at the upper left corner of the image, the detection box extends almost all over the image.

**Comment by jesusatgar** [comment]
It seems there was some problem with the anchors. Retraining on a higher res and calculating 9 clusters for the dataset solved the issue.
