### ISSUE TITLE
Question: Temporary Files

### ISSUE THREAD

**Issue by Universalis4** [AlexeyAB/darknet#4070]
Hello guys!

Recently I was playing around a lot with analyzing video live-streams and wondered about the process behind it.

Does Yolo (or OpenCV) save frames in temporary files? I checked my Temp folder while analyzing but didn't see anything of the sort. Could it be that the frames are only loaded to the RAM? 

I don't really know how these things work but I'd be glad if someone could give me a brief explanation!

Thanks in advance!

**Comment by AlexeyAB** [comment]
The frames are only loaded to the RAM

**Comment by Universalis4** [comment]
Thanks for the fast answer! Thats amazing!
