### ISSUE TITLE
Incorrect Bounding boxes in video of moving object

### ISSUE THREAD

**Issue by razanabdulla** [AlexeyAB/darknet#4083]
Hi @AlexeyAB,
I'm getting incorrect bounding boxes in video(moving object) while  the same object in  single frames(jpg image from the same video) is correctly detected. The bounding boxes are present in output video but not in the correct places with greater than 60% accuracy. It seems like bounding boxes lags or leads the object.

Model - yolov3 tiny
mAP - 80
avg_loss < 1
OS - ubuntu 16.04
GPU - GTX 1660
Is moving speed is affecting the detection?
Any help is appreciated.

**Comment by laclouis5** [comment]
Hi,

Your question was answered in a previous issue I opened [here](https://github.com/AlexeyAB/darknet/issues/3675).

**Comment by razanabdulla** [comment]
Thanks @laclouis5 .
Its working fine now.
Can you please tell me parameter  `NFRAMES` means? 
Or what is the criteria of changing this parameter?

**Comment by laclouis5** [comment]
`NFRAME` is the period in frames at which Darknet framework performs inference. `NFRAME=1` means that every images of the video stream is processed while `NFRAME=3` means only 1 frame is processed every 3 frames, the two remaining ones are deducted from the last inference and Optical Flow.
You should increase `NFRAME` if `NFRAME=1` is not fast enough for your application.

**Comment by razanabdulla** [comment]
Thank you @laclouis5
