### ISSUE TITLE
why darknet-yolov3 in AlexeyAB is not fast like darknet-yolov3 in pjreddie ? 

### ISSUE THREAD

**Issue by yassinesefrioui** [AlexeyAB/darknet#4084]
Hello ! 
I use tesla K80 with 4 GPU,  when i use darknet-yolov3 in pjreddie  with batch = 112 & subdivision = 16. work normaly and it is very fast. 
BUT,  
when i use darknet-yolov3 in AlexeyAB, it is too slow, and i can't change the batch. I can just execute YOLOv3 with batch= 64 & subdivision = 32. 

### How can i execute YOLOv3 in AlexeyAB fast with high batch ? 

**Makefile** :

```
GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=1
AVX=0
OPENMP=0
LIBSO=0
ZED_CAMERA=0
DEBUG=0

ARCH= -gencode arch=compute_30,code=sm_30 \
             -gencode arch=compute_37,code=sm_37 \
             -gencode arch=compute_50,code=[sm_50,compute_50] \
             -gencode arch=compute_52,code=[sm_52,compute_52] \
	     -gencode arch=compute_61,code=[sm_61,compute_61]

```
thank you !!

**Comment by AlexeyAB** [comment]
Use width=416 height=416 random=0 in both cases.

**Comment by yassinesefrioui** [comment]
Thank you @AlexeyAB 
when i change random from 1 to 0, it is work for me. 
But, using random =0 , it will decrease precision ?

**Comment by AlexeyAB** [comment]
What width= and height= do you use in both cases?

**Comment by yassinesefrioui** [comment]
i use 608*608

**Comment by AlexeyAB** [comment]
> i use 608*608

The reason for slowdown, because pjreddie ignores your 608x608 resolution in cfg-file and uses 416/1.4 - 416x1.4 random resolution, while AlexeyAB read your cfg-file and uses 608/1.4 - 608x1.4 random resolution.

**Comment by yassinesefrioui** [comment]
you saved my day  .. thank you :D
