### ISSUE TITLE
yolo training stop with "OpenCV exception: load_image_mat_cv " message

### ISSUE THREAD

**Issue by meisamjam** [AlexeyAB/darknet#4087]
@AlexeyAB 
I am training yolov3 on KITTI dataset images in google colab notebook I prepared cfg and train.data based on instructions in https://github.com/AlexeyAB/darkne. my dataset is stored in my google drive and I use it with mounting the drive on colab but the training stops with this massage:
(next mAP calculation at 1000 iterations) 
 401: 5.578282, 5.578282 avg loss, 0.000026 rate, 48.170466 seconds, 25664 images
Loaded: 0.000047 seconds
OpenCV exception: load_image_mat_cv 

 (next mAP calculation at 1000 iterations) 
 402: 5.484603, 5.568914 avg loss, 0.000026 rate, 49.727370 seconds, 25728 images
Loaded: 0.000083 seconds

I don't know what is the problem I saw in the similar problems' issues that it may be because of 
abnormality in train.txt or validation.txt but I checked them I didn't find any obvious problem

**Comment by AlexeyAB** [comment]
Look at the files
bad.list and bad_label.list

**Comment by meisamjam** [comment]
> Look at the files
> bad.list and bad_label.list

thanks. Actually I ran another training but it stopped at a different point 
I couldn't find bad.list and bad_label.list

**Comment by meisamjam** [comment]
I found the problem. Actually there was a broken image in my dataset so I found that and I just remove the path of that image from train.txt and the problem resolved

**Comment by nancyshaji** [comment]
@meisamjam  Is it possible for you to share the training code on Google colab?
I am doing a project where I need to train a custom dataset and I do not have access to a GPU, other than colab
