### ISSUE TITLE
CPU utilization exceeds 100 in cpu mode

### ISSUE THREAD

**Issue by ericwang321** [AlexeyAB/darknet#4088]
CPU utilization exceeds 100 in cpu mode

ubuntu16.04   64bit/CPU：i3-4150@3.50Ghz/MEM: 8G/intel haswell
**make file:**

> OPENCV=1 LIBSO=1 AVX=0 

**run:**

> (py36)user1@bogon$ ./darknet  detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights -thresh 0.25 ./data/person.jpg

**then run top in other terminal:**
![Snap2](https://user-images.githubusercontent.com/25045112/66810349-ade76500-ef61-11e9-9846-66ad53f10997.jpg)

_where is the problem?
Is it related to opencv3.40, or anaconda  ?_

**Comment by AlexeyAB** [comment]
There is no problem.

**Comment by dexception** [comment]
There is no problem. This is like this only.

**Comment by ericwang321** [comment]
thanks.
I think it was mentioned in the previous issue.record it

> By default, top displays CPU usage as a percentage of a single CPU. On multi-core systems, you can see percentages of CPU usage are greater than 100%. You can toggle this behavior by hitting Shift + i while top is running to show The overall percentage of available CPUs in use.
> 
> Htop is a better alternative of top. In htop, you can see how your programs consuming all of the 32 cores.

Https://askubuntu.com/questions/707203/top-command-on-ubuntu-multicore-cpu-shows-cpu-usage-100
