### ISSUE TITLE
Should you include images without any objects in it?

### ISSUE THREAD

**Issue by xrv0** [AlexeyAB/darknet#4095]
I am hoping this would help me get better accuracy on longer range and decrease false positives.
It is recommended to use images that don’t include any of my objects to increase accuracy?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lsd1994** [comment]
Yes

**Comment by bagminer** [comment]
Please refer https://github.com/AlexeyAB/darknet/issues/4093#issuecomment-542205293

**Comment by xrv0** [comment]
~~~~
>Please refer https://github.com/AlexeyAB/darknet/issues/4093#issuecomment-542205293

@bagminer Thanks. Apologies for the duplicate.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
