### ISSUE TITLE
Impact of increasing number of classes on object detection rate/speed  

### ISSUE THREAD

**Issue by bagminer** [AlexeyAB/darknet#4096]
I am trying to build a model to detect custom objects. Initially, in the testing phase for 50 objects with tiny yolo, I am getting 35 FPS speed. If I increase the number of objects to 800-1000, will be there any significant impact on the detection rate FPS. Also, if please let me know if there is any research paper related to this to understand better.

P.S.- I have already referred #4020 (for training speed).

**Comment by lsd1994** [comment]
> I am trying to build a model to detect custom objects. Initially, in the testing phase for 50 objects with tiny yolo, I am getting 35 FPS speed. If I increase the number of objects to 800-1000, will be there any significant impact on the detection rate FPS. 

No, very little. Because number of objects only influence yolo layer.

**Comment by bagminer** [comment]
Hey, do you mean 'yolo layer' as 'last layer (detection layer)' in YOLO architecture? Can you please explain this ?

**Comment by lsd1994** [comment]
> @lsd1994 Hey, do you mean 'yolo layer' as 'last layer (detection layer)' in YOLO architecture? Can you please explain this ?

Yes
