### ISSUE TITLE
What is command option "-i"

### ISSUE THREAD

**Issue by shinfo001** [AlexeyAB/darknet#4097]
This readme sample into

Yolo v3 Tiny on GPU #1: darknet.exe detector demo cfg/coco.data cfg/yolov3-tiny.cfg yolov3-tiny.weights -i 1 test.mp4

What is mean this option
-i 1

**Comment by AlexeyAB** [comment]
GPU number:
`-i 1` will use GPU-1

**Comment by shinfo001** [comment]
Thanks responce, i fix it.
