### ISSUE TITLE
Some problems about training tiny yolo to detect custom object

### ISSUE THREAD

**Issue by Teoge** [AlexeyAB/darknet#41]
1. Is it correct to change line #114 filters=125 and line #120 classes=20 in the tiny-yolo-voc.cfg?
2. Should I use darknet19_448.conv.23 as pre-trained weights or something else instead?
3. Is there anything else different from training normal yolo?
Thanks a lot for your work.

**Comment by AlexeyAB** [comment]
1. Yes. For example `filters=55` in the last layer `[convolutional]` 
    and `classes=6` in the region layer `[region]`

2. Yes. `darknet.exe detector train data/obj.data tiny-yolo-obj.cfg darknet19_448.conv.23`

3. No. Use as original: `darknet.exe detector test data/obj.data tiny-yolo-obj.cfg tiny-yolo-obj_3000.weights -thresh 0.02`
