### ISSUE TITLE
Darknet cuts the processed videos

### ISSUE THREAD

**Issue by mbayog02** [AlexeyAB/darknet#410]
I am trying to process a bunch of videos using darknet-yolo and the following command
`./darknet detector demo cfg/coco.data cfg/yolo.cfg yolo.weights input.mp4 -out_filename output.avi`
But when I check the output videos them have been cut in the end. Sometimes just a few seconds and other times up to two or three minutes.
Why is this happening?
I would also like to know the meaning of this error when the processing ends.
![screenshot from 2018-02-26 17-32-23](https://user-images.githubusercontent.com/17453296/36682324-165fb5f0-1b1b-11e8-8fe1-95eddd00c81f.png)
The "progreso"% is a personal customization that displays the actual frame / the total amounts of frames of the video.
This was just a test of few seconds and the progress percentage just displays 62%, but in larger videos it comes up to 99%.

Could the core dumped error being cutting the output video by not allowing it to correctly saves?
In this case, how could I fix this error to get a safety exit of the application

**Comment by AlexeyAB** [comment]
@mbayog02 I fixed it, maybe now it will work correctly. Just update your code from this repo and recompile.

**Comment by mbayog02** [comment]
Just tried it.
The errors about the stram closed has desapear but the video looks like it's still cut a few seconds in the end
Maybe lees cut than previous version
Thank you

**Comment by AlexeyAB** [comment]
@mbayog02 Do you see message `output_video_writer closed.` in the console at the end of detection?

It should cut only about 2 frames at the end, due this line: https://github.com/AlexeyAB/darknet/blob/490d02505b42701d9682591631c61d40e6cddeb4/src/demo.c#L18

**Comment by mbayog02** [comment]
Yes, in the console the code shows "output_video_writer closed" but my output video is much sorter than just 2 frames (I counted up to 25 and stop counting)
Not sure why
I have also try changing FRAME constant but it seems not have any effect in the video cut

**Comment by AlexeyAB** [comment]
Try to use other output video formats - comment line with `'D', 'I', 'V', 'X'` and un-comment other: https://github.com/AlexeyAB/darknet/blob/490d02505b42701d9682591631c61d40e6cddeb4/src/demo.c#L200-L206

**Comment by mbayog02** [comment]
I have tryied all the formats and the result is the same 
I have added this two lines just before here:
https://github.com/AlexeyAB/darknet/blob/490d02505b42701d9682591631c61d40e6cddeb4/src/demo.c#L270
`printf("Last frame was: %d\n",count);`
`printf("Total frames: %d\n",(int)cvGetCaptureProperty(cap,CV_CAP_PROP_FRAME_COUNT));`
And the result was this
![screenshot from 2018-02-27 18-39-36](https://user-images.githubusercontent.com/17453296/36744611-97f1bae6-1bed-11e8-9090-b81ef10a28cd.png)

**Comment by AlexeyAB** [comment]
@mbayog02 This is strange.

Try to put here: https://github.com/AlexeyAB/darknet/blob/490d02505b42701d9682591631c61d40e6cddeb4/src/demo.c#L72
this code:
```
static int count_cap_frames = 0;
printf(" last cap frame = %d \n", ++count_cap_frames);
```

What value of `last cap frame =` will be showed at the end?

**Comment by mbayog02** [comment]
@AlexeyAB My last cap frame output was 103 altough my input video was 115 frames
A you can see the "last cap frame" output is not in the last frame processed, it is 3 frames before

Could you explain how is Darknet processing the diferent frames?

`FPS:11.7
Progress:86%
Objects:

traffic light: 51% (919,307 961,366)
traffic light: 39% (1179,519 1207,557)
truck: 49% (3,468 273,725)
car: 64% (481,582 658,684)
car: 28% (763,625 811,658)
car: 78% (959,616 1160,708)
car: 24% (1064,629 1170,718)
car: 84% (1465,475 1918,915)
 last cap frame = 103

 cvWriteFrame 



















FPS:11.5
Progress:87%
Objects:

traffic light: 57% (914,291 960,364)
traffic light: 27% (1178,526 1208,564)
truck: 56% (0,467 217,721)
car: 52% (464,583 659,687)
car: 82% (972,617 1173,708)
car: 81% (1548,474 1919,924)

 cvWriteFrame 






















FPS:11.8
Progress:88%
Objects:

traffic light: 55% (913,293 956,355)
traffic light: 40% (1179,516 1213,558)
truck: 52% (0,477 169,718)
car: 67% (454,582 654,686)
car: 76% (996,614 1190,710)
car: 82% (1644,496 1895,964)
Last frame was: 102
total frames: 115
Input video stream closed.
output_video_writer closed. 


Thank you so much

**Comment by AlexeyAB** [comment]
> My last cap frame output was 103 altough my input video was 115 frames

So problem is not in the Darknet, this problem is in the OpenCV function `cvQueryFrame()` https://github.com/AlexeyAB/darknet/blob/490d02505b42701d9682591631c61d40e6cddeb4/src/image.c#L631

Or problem in the video file - broken or cut off at the end - if videofile hasn't final I-frame, so that a bi-directional B-frame can not rely on the final I-frame: https://en.wikipedia.org/wiki/Video_compression_picture_types

----

> A you can see the "last cap frame" output is not in the last frame processed, it is 3 frames before
> Could you explain how is Darknet processing the diferent frames?

Darknet has lag 2 frames between capture and detection if `#define FRAMES 1`: capture_thread -> main_thread -> detection_thread. 
And lag 4 frames if `#define FRAMES 3`
 https://github.com/AlexeyAB/darknet/issues/412#issuecomment-368994606
