### ISSUE TITLE
about 'demo' bounding box offset form video

### ISSUE THREAD

**Issue by leehao178** [AlexeyAB/darknet#4100]
Originally, when i use "demo" option , i get the result like
![img_00000005](https://user-images.githubusercontent.com/23611223/66902101-a6dc5780-f032-11e9-8fbc-e004908d3c26.jpg)

ubuntu 16.04
CPU i7-8700k
GPU RTX 2080Ti
cuda 10.0
cudnn 7.5.1
opencv 3.4.7

Do you have any idea what could be the issue?  Is it wrong frame?

and thank you @AlexeyAB  :)

**Comment by AlexeyAB** [comment]
Change `3` to `1` there and recompile: https://github.com/AlexeyAB/darknet/blob/53160fa6662ea7e8c4095588db56cac7b339b917/src/demo.c#L40

Does it help?

**Comment by leehao178** [comment]
> 更改`3`到`1`那裡，並重新編譯：
> 
> https://github.com/AlexeyAB/darknet/blob/53160fa6662ea7e8c4095588db56cac7b339b917/src/demo.c#L40
> 
> 有幫助嗎？

yep~
it's work!!!  Thank you so much!!
