### ISSUE TITLE
Multi-GPU with different CUDA Compute Capability Training Error

### ISSUE THREAD

**Issue by ivder** [AlexeyAB/darknet#4101]
I don't have any trouble training with my GTX-1080 ti. But when I tried to use multi-gpu using gtx-1080 ti and gtx 980 ti I got  CUDA Error. I built darknet when I only used gtx-1080 which has Compute Capability 6.1, meanwhile gtx-980 has Compute Capability 5.2 . Is it possible to use different GPU with different compute capability?

After following the instruction here https://github.com/AlexeyAB/darknet#how-to-train-with-multi-gpu , I  executed the training using : 
`./darknet detector train data/obj.data cfg/objtiny.cfg backup/objtinydamage_1000.weights -gpus 0,1 -map`

I got the following error : 
```
Resizing
608 x 608 
 try to allocate additional workspace_size = 52.43 MB 
 CUDA allocate done! 
 try to allocate additional workspace_size = 52.43 MB 
 CUDA allocate done! 
Loaded: 0.096167 seconds
CUDA status Error: file: /ssd/darknet/src/blas_kernels.cu : () : line: 668 : build time: Oct 16 2019 - 09:04:40 
CUDA Error: no kernel image is available for execution on the device
CUDA Error: no kernel image is available for execution on the device: Success
darknet: /ssd/darknet/src/utils.c:293: error: Assertion `0' failed.
Aborted (core dumped)
```
Any help will be appreciated. Thanks

**Comment by AlexeyAB** [comment]
* Did you compile by using just `make` or `cmake + make` ?

* try to recompile Darknet
```
make clean
make
```

**Comment by ivder** [comment]
@AlexeyAB  yes I built darknet using `cmake .` and `make`

**Comment by AlexeyAB** [comment]
Try to download https://raw.githubusercontent.com/AlexeyAB/darknet/53160fa6662ea7e8c4095588db56cac7b339b917/Makefile

Set GPU=1 CUDNN=1 OPENCV=1 in this Makefile

and compile without Cmake:
```
make clean
make
```
