### ISSUE TITLE
Monitor loss for values more than 4.5

### ISSUE THREAD

**Issue by orcund** [AlexeyAB/darknet#4108]
Convergence in my training is going kinda slow so I want to monitor high loss situations at the beginning of the training too. However, as you know, -map flag outputs graph with max value 4.5 in the y axis. Is there a way to change this?

**Comment by AlexeyAB** [comment]
Change this line and recompile: https://github.com/AlexeyAB/darknet/blob/53160fa6662ea7e8c4095588db56cac7b339b917/src/detector.c#L146
