### ISSUE TITLE
CUDA Error: unspecified launch failure

### ISSUE THREAD

**Issue by primat000** [AlexeyAB/darknet#411]
Hi AlexeyAB,
Thanks for the help with https://github.com/AlexeyAB/darknet/issues/393. I was trying to train tiny-yolo-voc and in the first times everything works well, but suddenly I began to receive another error. I tried with different params batch, subdivision and random but it doesn't help. It would be greatly appreciated if you could help me this time too)
![2bf_fwcj94c](https://user-images.githubusercontent.com/10787723/36690571-bd165868-1b43-11e8-9abe-6d47c03ffdfd.jpg)

**Comment by AlexeyAB** [comment]
@primat000 Hi,

* When did you download this repository? I.e. what is the date of the last commit in your local copy of repository, approximately?

* Do you use CUDNN? If yes - then try to update your code from this repo. I optimized memory allocation for the network resizing (random=1), when used cuDNN.

* Do you get this error if you train with `random=0`?

**Comment by primat000** [comment]
- Last commit on my local copy was 10.02.2018

- I dont use CUDNN

- With random=0 I have the same error

**Comment by AlexeyAB** [comment]
This is strange. Your GPU GeForce 610M is CC 2.0/2.1 so you can't use cuDNN, but there isn't problem with CUDA-stream, so it should work.

Those, out of GPU-memory you do not observe, isn't it?

Try to download this version of Darknet Yolo for Windows, without CUDA-stream: https://github.com/AlexeyAB/darknet/archive/83d9b0b6d81755ce3f7b856b56a485b0abb34f81.zip

Then remove `CUDNN;` and set here `compute_20,sm_21;` as described: https://github.com/AlexeyAB/darknet/issues/393#issuecomment-366366537

**Comment by primat000** [comment]
I didn't observe out of memory error, but today besides previous error I recieved another one:

![launch](https://user-images.githubusercontent.com/10787723/36734304-1e936d60-1be4-11e8-9f77-5721f690e155.jpg)

I tried version without CUDA-stream, unfortunately nothing has changed.

**Comment by AlexeyAB** [comment]
There is time-limit in the nVidia GPU driver, thoose, one CUDA-function can not be executed longer than N seconds. So it looks like your GPU too slow to execute the longest-CUDA-function in this time.

Do you use batch=64 subdivision=64 and tiny-yolo?
So you should use tiny-yolo, set `random=0`, `batch=16 subdivision=16`, also remove this conv lyaer: https://github.com/AlexeyAB/darknet/blob/490d02505b42701d9682591631c61d40e6cddeb4/cfg/tiny-yolo-voc.cfg#L102-L108
And train in this way: `darknet.exe detector train data/obj.data tiny-yolo-obj.cfg`

**Comment by primat000** [comment]
I tried with batch=64 subdivision=64 too, it does'n effect.
Thanks a lot for advice, but after a few iterations I have "CUDA Error: unspecified launch failure" again.

**Comment by AlexeyAB** [comment]
@primat000 Time to buy new GPU :)

**Comment by primat000** [comment]
Yes it seems this is the only way)
