### ISSUE TITLE
Jazzing up bounding boxes

### ISSUE THREAD

**Issue by haviduck** [AlexeyAB/darknet#4114]
This isnt really an issue but Im trying to make the bounding boxes a little snazzier. I see some of the object detection implementations Have an amazing look and feel to them and i want to has it! 

I use your repo actively in My work and i absolutely love it. Fast, efficient and very easy to use, but presenting the bounding boxes the way they are in applications with hard colors and square labels are Just not doing you and pjreddies work justice. Crawling through the code i found in one of the image files what appears to be manually drawn boxes. Tried tinkering with canny and contour but without any luck. If its resourceheavy to do that stuff in a 30+fps scenario i get it. But id Just love to see more modern designs on todays object detection libraries. I know its not the focus of this repo, but technology like this is so COOL and it should be reflected in its design. Fills, contours, labels, patterns, overlays and color control to really make the apps pop! Nvidia and visionworks for example are doing some Nice stuff with their Soft directional arrow overlays. 

![Screenshot_20191018_050242_com google android youtube](https://user-images.githubusercontent.com/4920887/67062748-93310e00-f164-11e9-88ba-7ca81240db22.jpg)

Im gonna continue tinkering until im able to change it Even the slightest bit,  but this being My first go at C and make its a steep learning curve.

Ive sketched up some ideas trying to find a sweetspot between practical and design but i need a nudge in the right direction as to where im editing.  Anyone?

**Comment by xrv0** [comment]
The purpose of this repo is definitly not to use it in an production enviroment. If you want fancier boxes and layout use the dll and build your own ui for it.
https://github.com/AlexeyAB/darknet#how-to-use-yolo-as-dll-and-so-libraries
https://github.com/AlexeyAB/darknet/blob/master/src/yolo_console_dll.cpp

**Comment by haviduck** [comment]
will try! i was able to play around with it abit, but it severely degraded detection (tried transparency on cv_filled rectangles). i dont really have any issues with this in a prod env, but im gnna look into the dll approach. gotta learn some day anyway, right? :)
