### ISSUE TITLE
build C API using cmake

### ISSUE THREAD

**Issue by albertchristianto** [AlexeyAB/darknet#4115]
Hi @AlexeyAB,

i have look for yolo_cpp_dll.cpp files in the entire project and couldn't find anything. 
is yolo_cpp_dll.dll features deprecated?

best regards,
Albert

**Comment by AlexeyAB** [comment]
There are 2 APIs https://github.com/AlexeyAB/darknet/tree/master/include
* C: https://github.com/AlexeyAB/darknet/blob/master/include/darknet.h
* C++: https://github.com/AlexeyAB/darknet/blob/master/include/yolo_v2_class.hpp

**Comment by albertchristianto** [comment]
thank you for the response, @AlexeyAB . 
I have realized that yolo_cpp_dll.dll (yolo_cpp_dll.cpp) have been merged inside dark project (dark.dll).

for additional information,  
the python code didn't work, so need to change a few line in darknet.py to make it work. in my case, i change line (81-83):
cwd = os.path.dirname(__file__)
os.environ['PATH'] = cwd + ';' + os.environ['PATH']
winGPUdll = os.path.join(cwd, "yolo_cpp_dll.dll")
to:
cwd = os.getcwd()
os.environ['PATH'] = cwd + '\\build\\Release;' + os.environ['PATH']
winGPUdll = os.path.join(cwd, "dark.dll")

thank you once again @AlexeyAB .

best regards,
Albert Christianto
