### ISSUE TITLE
Can not get maP & Loss  Chart on browser.

### ISSUE THREAD

**Issue by miteshgithub** [AlexeyAB/darknet#4116]
I have compiled your repo with GPU=1, CUDNN=1 and OPENCV=1 .
I have amazon ec2 instance. 
I have fired this command for training 

**./darknet detector train ../yolo/darknet.data ../yolo/darknet-yolov3.cfg ../yolo/weights_scales/darknet-yolov3_last.weights -gpus 0,1,2,3 -letter_box -dont_show -mjpeg_port 8090 -map >> ../yolo/train_full_scales.log &** 

My train_full_scales.log 

 **(next mAP calculation at 4000 iterations)
 403: 491.547485, 911.329041 avg loss, 0.000000 rate, 17.527661 seconds, 103168 images
 MJPEG-stream sent.
Loaded: 0.000134 seconds**

I tried on browser but it does not respond.

**Comment by AlexeyAB** [comment]
It seems you should open port `8090` in your Amazon EC2 instance: https://postmarkapp.com/support/article/1026-resolving-aws-port-25-throttling

<img width="1000" alt="s_A04D6F58B05B8B3E550A2A277B33D47FD793ED4EB2385C64E12471633A3A3622_1463172638016_Add+Additional+Ports" src="https://user-images.githubusercontent.com/4096485/67084870-7caba680-f1a6-11e9-8785-a0c41c6feee4.png">

**Comment by ambr89** [comment]
Hi, 
I train my dataset with this code on my own pc:

```
./darknet detector train data/my.data cfg/my_yolov3-tiny-brav.cfg data/brav/darknet53.conv.74 -map
```

How can I see the chart? Where I found it?

**Comment by AlexeyAB** [comment]
@ambr89 
It will create `chart.png` file for each 100 iterations

**Comment by aluds123** [comment]
@AlexeyAB 
Hi, I have already train my model on my PC.
But I miss my chart.png, can I recreate it by doing something?

Thanks.

**Comment by AlexeyAB** [comment]
@aluds123 No.

**Comment by Sharon507** [comment]
> It seems you should open port `8090` in your Amazon EC2 instance: https://postmarkapp.com/support/article/1026-resolving-aws-port-25-throttling
> 
> <img alt="s_A04D6F58B05B8B3E550A2A277B33D47FD793ED4EB2385C64E12471633A3A3622_1463172638016_Add+Additional+Ports" width="1000" src="https://user-images.githubusercontent.com/4096485/67084870-7caba680-f1a6-11e9-8785-a0c41c6feee4.png">

I was having the same issue and this advice fixed it for me. Thank you! It might be worth adding it to the instructions here: https://github.com/AlexeyAB/darknet/issues/1380#issuecomment-412333942.

Sharon

**Comment by AlexeyAB** [comment]
@Sharon507 I added it.

**Comment by Sharon507** [comment]
> @Sharon507 I added it.

Thank you!

**Comment by ZambranoAd** [comment]
I have opened an EC2 instance (GPU p3.2x large), but when I try to run the make command on the Makefile for OPENCV=1, it states that the OPENCV package is missing. 

I am focused on tinyYOLOv3 training and testing. If I can compile Darknet with OPENCV on the remote GPU, then I would be able to check the loss chart and mAP values. 

I would appreciate your help and assistance on this matter

**Comment by Sharon507** [comment]
Hi @ZambranoAd . Which AMI are you using? I used Deep Learning Base AMI (Ubuntu 16.04). See here for details (including the openCV version installed): https://aws.amazon.com/marketplace/pp/B077GCZ4GR?ref=cns_srchrow.

I had no problems building with GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=1.

**Comment by ZambranoAd** [comment]
> Hi @ZambranoAd . Which AMI are you using? I used Deep Learning Base AMI (Ubuntu 16.04). See here for details (including the openCV version installed): https://aws.amazon.com/marketplace/pp/B077GCZ4GR?ref=cns_srchrow.
> 
> I had no problems building with GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=1.

Thank you very much Sharon507, I was compiling OpenCV through CMake on a Linux Instance but it would have taken so much time. Once again thank you for your quick response
