### ISSUE TITLE
Training Killed after 9100 iterations

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [AlexeyAB/darknet#4117]
I am training darknet on VOC+Another dataset. My dataset contains about 61000 images.   Training goes well till 9100 iterations then suddenly killed and stopped. Also retried several times.  I also deleted bad.list and bad_label.list file. I use batch=64
subdivisions=16
I am using GeForce GTX 1080 Ti GPU.   
![darknetKIlled](https://user-images.githubusercontent.com/28862708/67091586-9ae1c880-f1df-11e9-9f47-20823d16be41.png)

**Comment by AlexeyAB** [comment]
Do you have bad.list and bad_label.list file?

**Comment by MuhammadAsadJaved** [comment]
Already tried that solution

**Comment by MuhammadAsadJaved** [comment]
Deleting bad.list and bad_label.list  then restart the system and start training again from saved weights resolved the issue. @AlexeyAB Thank you .
