### ISSUE TITLE
I am training yolov3 for custom images. My first weight file was generated at 100 iteration and now its 430 and no other weight file is generated. I have read that yolo generates weight after every 100 iterations until 10,000. What can be the issue?

### ISSUE THREAD

**Issue by vaibhavnayak30** [AlexeyAB/darknet#4118]

**Comment by xrv0** [comment]
This fork only generates an weight file every 1000 iterations. Pijeddries official repo generates these at the rate you stated above.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jesusatgar** [comment]
The weights are saved in the _last.weights file each 100 iterations (the file is overwritten). They are also saved in different files each 1000 iterations.

**Comment by vaibhavnayak30** [comment]
thanks a lot for reply
