### ISSUE TITLE
darknet_video.py detect nothing

### ISSUE THREAD

**Issue by M-Younus** [AlexeyAB/darknet#4120]
I am trying to detect objects in video using darknet_video.py with darknet19.cfg,darknet19.weights and imagenet1k.data but it produces output with no detection.

**Comment by AlexeyAB** [comment]
darknet19.cfg,darknet19.weights is Classifier, not Detector. It can't detect anything https://pjreddie.com/darknet/imagenet/

**Comment by M-Younus** [comment]
Oh,Thank you man,I misunderstood it.
Can you please help if I wanna detect objects related to imagenet classes.
