### ISSUE TITLE
Color Detection

### ISSUE THREAD

**Issue by Sexpistrolls** [AlexeyAB/darknet#413]
Hello, I've been asked to recognize objects from different colours and I was wondering if it was possible. I have to recognize blue/red/yellow helmet/gloves/shirt for example. Is it possible ?

**Comment by AlexeyAB** [comment]
Hi, yes. 


If you have very close to each other colors, which you must distinguish as different, then you should decrease `hue=0.05` and `saturation=0.5` https://github.com/AlexeyAB/darknet/blob/490d02505b42701d9682591631c61d40e6cddeb4/cfg/yolo-voc.2.0.cfg#L10-L12

**Comment by Sexpistrolls** [comment]
Ok, so we don't have to change anything from here I guess ! I'll try it like that and I'll see. Thanks for your precisions and your time
