### ISSUE TITLE
Training with png

### ISSUE THREAD

**Issue by holger-prause** [AlexeyAB/darknet#4131]
Hello,

I want to train on png images - if i set channels = 4 -the training wont even start and crash. 
Do i missing something obvious? I thought a png has4 channels (r,g,b,opacity)?
In worst case i can covert to jpg with imagemagik.

Any insight on this is highly welcome.
Greetings,
Holger

**Comment by lsd1994** [comment]
Maybe reference this #2094

**Comment by holger-prause** [comment]
Thank you man for the link!
I read this - and i think ill just convert to jpg.
