### ISSUE TITLE
convolutional layer "size=1,stride=1,pad=1" 

### ISSUE THREAD

**Issue by alyssa121** [AlexeyAB/darknet#4155]
Hi, in the cfg file, the convolutional layer like this:

[convolutional]
batch_normalize=1
filters=32
size=1
stride=1
pad=1
activation=leaky

takes 52x52 as input, if we follow the formula  **out_w = (l.w + 2*l.pad - l.size) / l.stride_x + 1,** then the output should be 54x54. Why couldn't we set **pad=0** here to get 52x52?

**Comment by AlexeyAB** [comment]
If(`pad=1`) then actually `l.pad = size/2 = 1/2 = 0`
so
`out_w = (l.w + 2*l.pad - l.size) / l.stride_x + 1 = 52 + 0 - 1 + 1 = 52`


https://github.com/AlexeyAB/darknet/blob/bb7d69941cbce4f67f10406395d685ea92be9478/src/parser.c#L166-L168

----

You can set pad=0 with the same result.

**Comment by alyssa121** [comment]
> If(`pad=1`) then actually `l.pad = size/2 = 1/2 = 0`
> so
> `out_w = (l.w + 2*l.pad - l.size) / l.stride_x + 1 = 52 + 0 - 1 + 1 = 52`
> 
> https://github.com/AlexeyAB/darknet/blob/bb7d69941cbce4f67f10406395d685ea92be9478/src/parser.c#L166-L168
> 
> You can set pad=0 with the same result.

Thanks for your quickly reply. Now I figure out. You're so kind!!!

**Comment by alyssa121** [comment]
Sorry again for troubling you. If I use the deconvolutional layer, would the following be correct?
`[deconvolutional]
batch_normalize=1
size=1
stride=2
filters=256
activation=leaky`

or remove the batch_normalize line && activation line
`[deconvolutional]
size=1
stride=2
filters=256`
