### ISSUE TITLE
initialization network in which darknet source file?

### ISSUE THREAD

**Issue by ericwang321** [AlexeyAB/darknet#4157]
when run  
 

> ./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights -dont_show < 1.txt > 2.txt

 **In the darknet source file, which part is the initialization network?**

 **Similar to the functionality in _darknet.py  (initonly)_** 
https://github.com/AlexeyAB/darknet/blob/bb7d69941cbce4f67f10406395d685ea92be9478/darknet.py#L301

**Is the function of loading the network in below statement?**  
 _detector.c_
https://github.com/AlexeyAB/darknet/blob/bb7d69941cbce4f67f10406395d685ea92be9478/src/detector.c#L534; 

**thanks**

**Comment by ericwang321** [comment]
Seems to be the role of the following parts, not sure, try
{
    list *options = read_data_cfg(datacfg);
    char *name_list = option_find_str(options, "names", "data/names.list");
    int names_size = 0;
    char **names = get_labels_custom(name_list, &names_size); //get_labels(name_list);

    image **alphabet = load_alphabet();
    network net = parse_network_cfg_custom(cfgfile, 1, 1); // set batch=1
    if (weightfile) {
        load_weights(&net, weightfile);
    }
    fuse_conv_batchnorm(net);
    calculate_binary_weights(net);
    if (net.layers[net.n - 1].classes != names_size) {
        printf(" Error: in the file %s number of names %d that isn't equal to classes=%d in the file %s \n",
            name_list, names_size, net.layers[net.n - 1].classes, cfgfile);
        if (net.layers[net.n - 1].classes > names_size) getchar();
    }

**Comment by AlexeyAB** [comment]
`network net = parse_network_cfg_custom(cfgfile, 1, 1); // set batch=1`
this line creates and initializes the network.

**Comment by ericwang321** [comment]
thanks. 
i will try to load.
