### ISSUE TITLE
Segmentation fault while runnnig yolo on multiple images and try to save it in text file.

### ISSUE THREAD

**Issue by mechamrit** [AlexeyAB/darknet#4162]
Although its detecting fine on single images but gives error when try on multiple images. 

Used this command  to run the yolo on multiple images
`!./darknet detector test data/obj.data yolo-obj.cfg backup/yolo-obj_1000.weights -dont_show  -ext_output < data/train.txt > result.txt`

error shown
`layer   filters  size/strd(dil)      input                output
   0 conv     32       3 x 3/ 1    416 x 416 x   3 ->  416 x 416 x  32 0.299 BF
   1 max                2x 2/ 2    416 x 416 x  32 ->  208 x 208 x  32 0.006 BF
   2 conv     64       3 x 3/ 1    208 x 208 x  32 ->  208 x 208 x  64 1.595 BF
   3 max                2x 2/ 2    208 x 208 x  64 ->  104 x 104 x  64 0.003 BF
   4 conv    128       3 x 3/ 1    104 x 104 x  64 ->  104 x 104 x 128 1.595 BF
   5 conv     64       1 x 1/ 1    104 x 104 x 128 ->  104 x 104 x  64 0.177 BF
   6 conv    128       3 x 3/ 1    104 x 104 x  64 ->  104 x 104 x 128 1.595 BF
   7 max                2x 2/ 2    104 x 104 x 128 ->   52 x  52 x 128 0.001 BF
   8 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
   9 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
  10 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
  11 max                2x 2/ 2     52 x  52 x 256 ->   26 x  26 x 256 0.001 BF
  12 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  13 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  14 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  15 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  16 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  17 max                2x 2/ 2     26 x  26 x 512 ->   13 x  13 x 512 0.000 BF
  18 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  19 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF
  20 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  21 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF
  22 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  23 conv   1024       3 x 3/ 1     13 x  13 x1024 ->   13 x  13 x1024 3.190 BF
  24 conv   1024       3 x 3/ 1     13 x  13 x1024 ->   13 x  13 x1024 3.190 BF
  25 route  16
  26 reorg_old              / 2    26 x  26 x 512   ->    13 x  13 x2048
  27 route  26 24
  28 conv   1024       3 x 3/ 1     13 x  13 x3072 ->   13 x  13 x1024 9.569 BF
  29 conv     50       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x  50 0.017 BF
  30 detection
mask_scale: Using default '1.000000'
Total BFLOPS 34.883 
 Allocate additional workspace_size = 49.84 MB 
Loading weights from backup/yolo-obj_1000.weights...Done! Loaded 31 layers from weights-file 
/bin/bash: line 1: 15869 Segmentation fault      (core dumped) ./darknet detector test data/obj.data yolo-obj.cfg backup/yolo-obj_1000.weights -dont_show -ext_output < data/train.txt > result.txt
`

The images in train.txt files are separated by the \n.
"Output in result.txt is 

 reorg_old 

 seen 64 
Enter Image Path: "

![rsz_2screenshot_from_2019-10-24_15-31-03](https://user-images.githubusercontent.com/35134704/67475355-a87dcf00-f673-11e9-9039-3f425ca89a2f.png)

**Comment by orcund** [comment]
Sounds like a memory issue.

**Comment by mechamrit** [comment]
> Sounds like a memory issue.

But the GPU and RAM are free..

**Comment by orcund** [comment]
Are you sure, did you monitor them simultaneously while you are running the code. Maybe they're free before you start but then you might be draining all sources as the process stands up, just guessing.
