### ISSUE TITLE
nvcc fatal   : Microsoft Visual Studio configuration file 'vcvars64.bat' could not be found for installation

### ISSUE THREAD

**Issue by ArnaudNorel95** [AlexeyAB/darknet#4163]
Hi 
I try to make darknet with GPU = 1, before I had a problem because it didn't find cuda.h, now its solved because I gave him the correct path and set my environment variables.
I'm working on Windows, but I use a cygwin terminal to work as on a linux project

My problem now when I try to "make" with GPU = 1 is the following :
`nvcc fatal   : " Microsoft Visual Studio configuration file 'vcvars64.bat' could not be found for installation at 'C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/SDK/ScopeCppSDK/VC/bin/../.. "`

So I Ctrl+F this file vcvars64.bat (I found it in `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\`) and then I copy pasted it to the expecting path But it still doesn't work and displays the same error message !

I don't understand

Could someone help me please ?

Thank you for reading

**Comment by AlexeyAB** [comment]
On Windows use Windows approaches for compiling rather than Unix approaches: https://github.com/AlexeyAB/darknet#how-to-compile-on-windows-using-cmake-gui

**Comment by ArnaudNorel95** [comment]
thank you , I tried with CMake but I get 
"CMake Error at CMakeLists.txt:28 (project):
  No CMAKE_C_COMPILER could be found."

And when I inspect the CMakeError.log I see error in ClCompile  like "... cannot open source file 'C:\Program' ... cannot open source file 'Files' ..." as if it didn't understand the path of something

(Despite the fact that I set the path of cl.exe in my environment variables)

**Comment by AlexeyAB** [comment]
Can you show screenshot?

**Comment by ArnaudNorel95** [comment]
Yes of course : here is the problem and the log file

![pbCMAKE](https://user-images.githubusercontent.com/46846856/67498740-46779680-f680-11e9-98c0-77e92c76a3d7.PNG)

**Comment by AlexeyAB** [comment]
What MS Visual Studio version did you install?

**Comment by AlexeyAB** [comment]
@cenit Hi, what could be the reason?

**Comment by cenit** [comment]
@ArnaudNorel95 could you please try to run .\build.ps1 in a powershell from the main darknet folder and copy/paste the messages (and errors, in case there are)?
Thanks

**Comment by ArnaudNorel95** [comment]
Thanks for your help
I got a big txt file :
[output.txt](https://github.com/AlexeyAB/darknet/files/3770929/output.txt)

**Comment by ArnaudNorel95** [comment]
Hi,
Does someone have an idea how to solve it ? I am really blocked with this step in my train
thanks

**Comment by cenit** [comment]
Sorry totally lost notification of your previous reply. You didn’t run the script, you just copied the script before.....
Please, open a Powershell, go to darknet folder and then run

.\build.ps1

Then copy the output from the shell

**Comment by ArnaudNorel95** [comment]
oh thanks there is an error :
`Skipping vcpkg-enabled builds because the VCPKG_ROOT environment variable is not defined or you requested to avoid VCPKG, using self-distributed libs

No default triplet has been set-up for vcpkg. Defaulting to x64-windows
Setting up environment to use CMake generator: Visual Studio 16 2019
Added missing env variable CUDA_TOOLKIT_ROOT_DIR`

and after that :
`CMake Error: Error: generator toolset: host=x64
Does not match the toolset used previously:
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
Error: could not load cache
Remove-Item : Cannot find path 'C:\Users\ronar\ASnowman\ACarreCMKE\darknet\build_win_release\DarknetConfig.cmake'
because it does not exist.
At C:\Users\ronar\ASnowman\ACarreCMKE\darknet\build.ps1:193 char:3
+   Remove-Item DarknetConfig.cmake
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\ronar\...netConfig.cmake:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Remove-Item : Cannot find path
'C:\Users\ronar\ASnowman\ACarreCMKE\darknet\build_win_release\DarknetConfigVersion.cmake' because it does not exist.
At C:\Users\ronar\ASnowman\ACarreCMKE\darknet\build.ps1:194 char:3
+   Remove-Item DarknetConfigVersion.cmake
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\ronar\...igVersion.cmake:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Get-ChildItem : Cannot find path 'C:\Users\ronar\ASnowman\ACarreCMKE\darknet\build_win_release\Release' because it
does not exist.
At C:\Users\ronar\ASnowman\ACarreCMKE\darknet\build.ps1:195 char:15
+   $dllfiles = Get-ChildItem ${dllfolder}\*.dll
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\ronar\...release\Release:String) [Get-ChildItem], ItemNotFound
   Exception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

Copy-Item : Could not find a part of the path 'C:\Users\ronar\ASnowman\ACarreCMKE\darknet\share\darknet\'.
At C:\Users\ronar\ASnowman\ACarreCMKE\darknet\build.ps1:200 char:3
+   Copy-Item cmake\Modules\*.cmake share\darknet\
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.CopyItemCommand`

**Comment by ArnaudNorel95** [comment]
I dont know exactly what I did but I dont get the first error anymore
However I still have the second one (`No default triplet...`)

And after this error I get other :

`Remove-Item : Cannot find path
'...absolute\path\darknet\build_win_release\DarknetConfig.cmake' because it does not exist.`

the same for DarknetConfigVersion.cmake

`Get-ChildItem : Cannot find path
'....myAbsolute\path\darknet\build_win_release\Release' because it does not exist.`

`Copy-Item : Could not find a part of the path
'...myAbsolute\path\darknet\share\darknet\'.`

**Comment by cenit** [comment]
please copy the whole log. Without it is not clear enough

**Comment by ArnaudNorel95** [comment]
[CMakeError.log](https://github.com/AlexeyAB/darknet/files/3782405/CMakeError.log)

**Comment by cenit** [comment]
I think you made a mess in your computer setup, which is highlighted also from the logs above. You should never copy-paste scripts from their default paths to another location, because internally they contains relative paths which become broken afterwards.
Please try to restore your computer, then install vcpkg using its guide, then just launching 
./vcpkg install darknet[full]:x64-windows
will install darknet with CUDA/cudnn support, using sources from this repository, in the (at the moment) easiest way

**Comment by ArnaudNorel95** [comment]
ok thank you
