### ISSUE TITLE
Getting Output Coordinates in YOLO Format

### ISSUE THREAD

**Issue by orcund** [AlexeyAB/darknet#4168]
Is there a way to save detection boxes in the label format. F.e,
If I process sample.jpg with one class i want my coordinate outputs like;
0 0.43422 0.577 0.233 0.3525

Or do i need to write a script myself?

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet#how-to-use-on-the-command-line


Pseudo-lableing - to process a list of images data/new_train.txt and save results of detection in Yolo training format for each image as label <image_name>.txt (in this way you can increase the amount of training data) use: `darknet.exe detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights -thresh 0.25 -dont_show -save_labels < data/new_train.txt`

**Comment by orcund** [comment]
Seems like I missed that in readme. Thanks !
