### ISSUE TITLE
Why does my MacBook freeze after 2000 iterations in google collab?

### ISSUE THREAD

**Issue by idelyan** [AlexeyAB/darknet#4170]
Hi @AlexeyAB . I'm trying to train a yolo on google colab, after about 2000 iteration, a sign appears on my computer that my RAM computer has finished working, everything starts to freeze, the browser freezes too and everything closes.

**Comment by OrangeVulture** [comment]
Hey,
I am working with 2 solutions for the same issue.
1. Keep clearing the output after every iteration or few iterations
2. Run the training command with 
     %%capture
     ./darknet detector train data/obj..................

**Comment by idelyan** [comment]
Thanks)

**Comment by OrangeVulture** [comment]
> Thanks)

Is the solution working for you??

**Comment by gogoIsComing** [comment]
@OrangeVulture can you tell me how to open `map and loss graph` on google colab ??? 
i execute the following command 
`!./darknet detector train data/obj.data cfg/yolo-obj.cfg weights/darknet53.conv.74 -dont_show -mjpeg_port 8090 -map`

but how to open the remote server on google colab ?? plz help

**Comment by AlexeyAB** [comment]
Open file `chart.png`

**Comment by gogoIsComing** [comment]
@AlexeyAB i trained darknet for 50 iteration `max_batches = 50`, but i can't see `chart.png` file, where i can find it exactly ???

**Comment by AlexeyAB** [comment]
Train on GPU, for at least 4000 iterationns
