### ISSUE TITLE
darknet.py Segmentation fault error

### ISSUE THREAD

**Issue by phongphuhanam** [AlexeyAB/darknet#4174]
Hello guys, I encounter the segmentation error when running darknet.py today.
```
~/Project/alex_darknet$ python darknet.py 
 Try to load cfg: ./cfg/yolov3.cfg, weights: yolov3.weights, clear = 0 
   ...
Class-ranging on 78 of 80= 0.0 
Class-ranging on 79 of 80= 0.0 
Ranging on 1 of 17
Classes: <__main__.METADATA object at 0x7f2d1d5c3b00> 80 <__main__.LP_c_char_p object at 0x7f2cec83dcb0>
Segmentation fault (core dumped)
```
I dont have any issue running image_yolov3.sh.

I built darknet with these options
```
GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=0
AVX=0
OPENMP=0
LIBSO=1
ZED_CAMERA=0
```

Here is my system:
* Ubuntu 16.04.6 LTS
* nvcc Cuda compilation tools, release 10.0, V10.0.130
* gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)
* Nvidia Driver Version: 418.56    CUDA Version: 10.1 
* NVIDIA GeForce 1080 ti
* Python 3.7.4 (default, Aug 13 2019, 20:35:49)  [GCC 7.3.0] :: Anaconda, Inc. on linux
I would appreciate it if you help me solve this problem.

**Comment by phongphuhanam** [comment]
Updated: I rolled back to [bb7d699](https://github.com/AlexeyAB/darknet/commit/bb7d69941cbce4f67f10406395d685ea92be9478) and darknet.py is running just fine with the same environment.

**Comment by irvingzhang0512** [comment]
same issue here

**Comment by QuentinBoul** [comment]
Same problem

**Comment by muduimushui** [comment]
same problem here,and reinstall old version,problem solved. @AlexeyAB ,hope you  fix it soon.Thank You!

**Comment by AlexeyAB** [comment]
I fixed it.
