### ISSUE TITLE
BFLOPS in 5-layers YOLO?

### ISSUE THREAD

**Issue by WadRex** [AlexeyAB/darknet#4177]
Hello,
I found your explanation of that number of BFLOPS at the end of initialisation.

_**Usually CPU and GPU has real performance ~40% of theoretical performance.
For example, Yolo v3 416x416 has Total BFLOPS 65.8.
GPU nVidia GeForce GTX 970 has 3494 Gflops
So GTX 970 should get about ~21 FPS = (40%/100%) * 3494 / 65.8**_

Using this I tried to calculate FPS for 5-layers YOLO.
I have an 1080ti ->**10608.6 Gflops**. My model gives me total of **43.665 BFLOPS** 
Using formula **(40%/100%) * 10608.6 / 43.665** gives me **97,19 FPS**
In reality I get only around 35 FPS. Is the calculation method for non standard YOLO is different?
Thanks in advance!

**Comment by AlexeyAB** [comment]
> In reality I get only around 35 FPS.

What command do you use?
What video resolution do you use?
What params do you use in the Makefile?

**Comment by WadRex** [comment]
1) **darknet.exe detector demo** without **-ext_output** and with **-dont_show**
2) Video and network resolution is the same -> **384x256**
3) Wasn't using Makefile, since I am on Windows. When compiling using .sln, I checked and I was using **CUDNN and CUDNN_HALF** in Preprocessor Definitions.

**Comment by AlexeyAB** [comment]
How many FPS do you get for default yolov3.cfg/weights?

[yolo] layer has low BFlops, but the most logic should be performed on CPU, so it can be slow.

----

Also even if layer can be executed on GPU, f.e. depth-wise conv-layer has Bflops lower than common conv-layer, but cuDNN and GPU isn't optimized for depth-wise layers, so conv-layer can be faster than depth-wise conv-layer.


As you can see there  BFLOPS are not always proportional to Inference time (sec): https://github.com/AlexeyAB/darknet/issues/3114#issuecomment-494148968

F.e. `yolo_v3_tiny_comparison.cfg.txt` 20 BFlops and 10 ms
while `yolo_v3_tiny_lstm.cfg.txt` 19 BFlops and 12 ms

**Comment by WadRex** [comment]
Using default yolo with the same resolution I get around 90 FPS.
Actually 30+ FPS is good enough for my task. I was just curious why is perfomance of 5l-yolo is that much worse compared to default yolo. Thanks for the explanation.

Btw, what is your opinion, will I benefit by using 5 layers yolo over default, if the resolution of network and video is the same. I know that 2 additional layers help detect small object after resizing the input image to the network resolution.
Will it be as helpful for small objects (sometimes only a couple of pixels) without resizing the input?

**Comment by AlexeyAB** [comment]
> Will it be as helpful for small objects (sometimes only a couple of pixels) without resizing the input?

What does it mean " without resizing the input" ?

The 5-yolo-layers can detect 1x1 px object (f.e. air in the sky) after resizing the input image to the network resolution.

If the object smaller than 1x1 px after resizing the input image to the network resolution, then it can't be detected at all, because it absent in the image.

**Comment by WadRex** [comment]
> What does it mean " without resizing the input" ?

My input image is the same resolution as the network -> 384x256, that way I am not losing any information at all

**Comment by WadRex** [comment]
So, what do you think about using 5layers-yolo in this case?

**Comment by AlexeyAB** [comment]
> Will it be as helpful for small objects (sometimes only a couple of pixels) without resizing the input?

It doesn't matter what size of object without resizing.
If some of objects less than 8x8 px after resizing, then use 5layers-yolo.
Just try both and compare the mAP.

**Comment by WadRex** [comment]
Thanks
