### ISSUE TITLE
gaussian_yolo_layer.c is missing in yolo_cpp_dll.vcxproj, commit: 69b7a19

### ISSUE THREAD

**Issue by dsgh2** [AlexeyAB/darknet#4185]
Hi,

In the latest commit(69b7a19f),
I have found that these header and source code about gaussian yolo layer are missing in yolo_cpp_dll.vcxproj

<ClCompile Include="..\..\src\gaussian_yolo_layer.c" />
<ClInclude Include="..\..\src\gaussian_yolo_layer.h" />

Please check this if there are errors like below.

error LNK2019: unresolved external symbol resize_gaussian_yolo_layer
error LNK2019: unresolved external symbol gaussian_yolo_num_detections
error LNK2019: unresolved external symbol get_gaussian_yolo_detections
error LNK2019: unresolved external symbol make_gaussian_yolo_layer

**Comment by AlexeyAB** [comment]
I fixed it.

**Comment by dsgh2** [comment]
> I fixed it.

Thank you so much!
