### ISSUE TITLE
How I could save the result into API or MySQL database of real-time object detection? 

### ISSUE THREAD

**Issue by saraAlsiyat1** [AlexeyAB/darknet#4186]
I need to save the below data into API for MySQL database to use them later in reporting.
<img width="545" alt="Screen Shot 2019-10-29 at 12 08 13 PM" src="https://user-images.githubusercontent.com/36037392/67761829-fb70d100-fa3b-11e9-9dc2-b19c79ece8ee.png">

**Comment by AlexeyAB** [comment]
You can use Darknet as DLL and use write your own C++ or Python application that saves data to MY SQL.
DLL/SO library with such API:
* C / Python: https://github.com/AlexeyAB/darknet/blob/master/include/darknet.h
* C++: https://github.com/AlexeyAB/darknet/blob/master/include/yolo_v2_class.hpp

Python examples:
1.  https://github.com/AlexeyAB/darknet/blob/master/darknet.py
2. https://github.com/AlexeyAB/darknet/blob/master/darknet_video.py

C++ example: https://github.com/AlexeyAB/darknet/blob/master/src/yolo_console_dll.cpp


----

Or use Darknet as JSON server, and use your own application that connects to TCP port 8070, read JSON and write it to My SQL db: https://github.com/AlexeyAB/darknet#how-to-use-on-the-command-line

JSON and MJPEG server that allows multiple connections from your soft or Web-browser ip-address:8070 and 8090: `./darknet detector demo ./cfg/coco.data ./cfg/yolov3.cfg ./yolov3.weights test50.mp4 -json_port 8070 -mjpeg_port 8090 -ext_output`

**Comment by saraAlsiyat1** [comment]
@AlexeyAB Thank you!
