### ISSUE TITLE
AttributeError: darknet/libdarknet.so: undefined symbol: copy_image_from_bytes

### ISSUE THREAD

**Issue by evdokimos** [AlexeyAB/darknet#4189]
hello, guys i try to implement yolov3-tiny with my webcam but an error **AttributeError: /home/evdo/darknet/libdarknet.so: undefined symbol: copy_image_from_bytes** occurs every time i try to run darknet.py file. Why does this error occurs? Thank you very much for your effort!

**Comment by AlexeyAB** [comment]
> i try to implement yolov3-tiny with my webcam

What command do you use?


This is strange.

It is there:
* https://github.com/AlexeyAB/darknet/blob/4d9addedd719cfb5d68cb3b39d5c7f9193071c0d/include/darknet.h#L860
* https://github.com/AlexeyAB/darknet/blob/4d9addedd719cfb5d68cb3b39d5c7f9193071c0d/src/image.c#L1575-L1592
* https://github.com/AlexeyAB/darknet/blob/4d9addedd719cfb5d68cb3b39d5c7f9193071c0d/darknet.py#L128-L129
* https://github.com/AlexeyAB/darknet/blob/4d9addedd719cfb5d68cb3b39d5c7f9193071c0d/darknet.py#L65-L69

**Comment by evdokimos** [comment]
All these things exist. I'll try to rebuild it and try to run it. But i would like to ask the steps I have to do in order to use my yolov3-tiny custom configuration with webcam. Do I have to change anything else except the insertion of the needed files (cfg, .data, .weights)? Thank you for your support!

**Comment by evdokimos** [comment]
My bad, something happened with the build. Thanks again, you're doing great job!

**Comment by imohamadhoseins** [comment]
> hello, guys i try to implement yolov3-tiny with my webcam but an error **AttributeError: /home/evdo/darknet/libdarknet.so: undefined symbol: copy_image_from_bytes** occurs every time i try to run darknet.py file. Why does this error occurs? Thank you very much for your effort!

Same Error while everything exists correctly!
