### ISSUE TITLE
I'm facing the follwoing error when I try to run darknet_video "OSError: ./libdarknet.so: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by saraAlsiyat1** [AlexeyAB/darknet#4191]

**Comment by saraAlsiyat1** [comment]
I try the bellow solution but nothing works: 

I import os on top of the code and then replace that line with:
lib = CDLL(os.path.join(os.getcwd(), "libdark.so"), [RTLD_GLOBAL)](url
![Screenshot_20191030_051208](https://user-images.githubusercontent.com/36037392/67831031-d41a1280-fad4-11e9-8c73-2ce940a939d5.png)
)

**Comment by DoriHp** [comment]
@saraAlsiyat1 how did you resolve that error? I recently faced it and haven't address :(

**Comment by canuck6ix** [comment]
@DoriHp @saraAlsiyat1 the file seems to have been renamed to `libdark.so`

**Comment by stephanecharette** [comment]
I just did a git pull, and when I build, it is definitely still called `libdarknet.so`.  Not sure why you'd see `libdark.so`.

Did you remember to set `LIBSO=1` near the top of darknet's `Makefile`?

**Comment by canuck6ix** [comment]
@stephanecharette Did you build via make or cmake? I used followed the instruction of cmake and get `libdark.so`
When I try to run `darknet_video.py` I get the following error:
``` 
 compute_capability = 750, cudnn_half = 1 
   layer   filters  size/strd(dil)      input                output
   0 net.optimized_memory = 0 
batch = 1, time_steps = 1, train = 0 

 cuDNN status Error in: file: [...]/src/dark_cuda.c : () : line: 165 : build time: Jan 29 2020 - 17:08:58 
cuDNN Error: CUDNN_STATUS_BAD_PARAM```

**Comment by stephanecharette** [comment]
I always build darknet with `make`.  Don't think I've ever tried to build it with `cmake`.

**Comment by canuck6ix** [comment]
Could you try building following [cmake installation](https://github.com/AlexeyAB/darknet#how-to-compile-on-linux-using-cmake) and check whether you get `libdark.so` or `libdarknet.so`?

**Comment by stephanecharette** [comment]
Yes, looks like the library is named differently when I follow those build steps:

```
> mkdir build-release
> cd build-release/
> cmake ..
> make -j
> find . | grep libdark
./libdark.so
```

I have no idea why.  If you need `libdarknet.so` either rename it, or follow the usual `make` instructions.  I'll leave this here for @AlexeyAB as a bug.
