### ISSUE TITLE
Darknet_video.py, Error below: 

### ISSUE THREAD

**Issue by saraAlsiyat1** [AlexeyAB/darknet#4199]
Loading weights from ./yolov3-spp.weights...Done! Loaded 73 layers from weights-file 
Traceback (most recent call last):
  File "darknet_video.py", line 116, in <module>
    YOLO()
  File "darknet_video.py", line 106, in YOLO
    detections = darknet.detect_image(netMain, metaMain, darknet_image, thresh=0.25)
  File "/home/marduk/darknet/darknet.py", line 278, in detect_image
    if dets[j].prob[i] > 0:
ValueError: NULL pointer access

![Screenshot_20191031_075957](https://user-images.githubusercontent.com/36037392/67935804-85e33d00-fbc2-11e9-962c-4619f420b70a.png)

**Comment by muduimushui** [comment]
maybe I meet this too. it costed me one day to solve this problem.It seems to be a new version bug.I reinstalled this version https://github.com/AlexeyAB/darknet/tree/bb7d69941cbce4f67f10406395d685ea92be9478.And problem solved.Hope to help U.

**Comment by AlexeyAB** [comment]
@saraAlsiyat1 @muduimushui I fixed it.

**Comment by saraAlsiyat1** [comment]
@muduimushui @AlexeyAB Thank you!
