### ISSUE TITLE
yolo-small with yolo_console_dll

### ISSUE THREAD

**Issue by manncyam** [AlexeyAB/darknet#420]
Hi Alexey,
I'd like to use yolo-small.cfg coco.names and yolo-small.weights with yolo_console_dll. but the application crashed after seeing only one frame or before detecting any object in the frame.
Is there any thing that I need to change to get it to work?

Thanks.

**Comment by AlexeyAB** [comment]
@manncyam Hi,
yolo-small.cfg is for Yolo v1. 
But yolo_console_dll supports only Yolo v2 (tiny-yolo.cfg, tiny-yolo-voc.cfg, yolo.cfg, yolo-voc.cfg, resnet152_yolo.cfg, densenet201_yolo.cfg, ...)
