### ISSUE TITLE
which  method more efficient when reading images 

### ISSUE THREAD

**Issue by ericwang321** [AlexeyAB/darknet#4200]
In src/image.c, 
which  methods are **more efficient when reading images** ?
```

1. Load_image_cv (filename,c);
2. Load_image_stb (filename, c).
```

thanks

**Comment by AlexeyAB** [comment]
I didn't compare, but I think `Load_image_cv (filename,c);` is more efficient. 
But it can be used only if Darknet is compiled with OpenCV.

**Comment by ericwang321** [comment]
thanks.i will try.
