### ISSUE TITLE
How do resize work when training?

### ISSUE THREAD

**Issue by shartoo** [AlexeyAB/darknet#4205]
An unrelated question about input size of network: how did resize work in training yolov3?I've tried this when training a keras model but failed. What i have done:

1. make a base model not sensitive to input size by adding some global average pooling before full connection layers.
2. train the model with a small input size such as 224x224
3. load the pretrained model weights by step 2,change the input image size to 448x448.

Step 3 failed caused by "Excepted input size of 224x224 but got 448x448"

What a progressive learning procedure should be? Just a not important and urgent question.

**Comment by AlexeyAB** [comment]
If you increased image size 2x, then you should increase size of each layer 2x (except full connected layer, since it has size 1x1 always).

**Comment by shartoo** [comment]
Why do darknet can do increase input size from 416 to 832 when training without any modify on network architecture ? Adding global avgpooling or maxpooling layer in network created by keras can make feature output parameters fixed before full connection layers , which i thought may helpful to adjust any input size.

**Comment by AlexeyAB** [comment]
Only weights of Full Connection layers are depends on the layer size. But Yolo doesn't use full connection layers.

**Comment by shartoo** [comment]
Soga(that's it!), which means i could do this by replacing the full connection layer by conv 1x1 ,i'll try!

**Comment by shartoo** [comment]
I've tried conv1x1 to replace the full connection layer  in keras,but it cannot work  with dimsion unmatch error(sth like [32,2] vs [1,1,,7,1024]). There must be a flatten layer in a cnn network.

And i found that,yolov3 cannot handle arbitrary input shape but three fixed shape 320x320,406x406 and 608x608, any other input shape would be resize into these three ones.I'll keep reading the darknet code ,thank you for your patient expain.

**Comment by AlexeyAB** [comment]
Yolo v3 in the Darknet can handle any input shape that is multiple of 32, f.e. 1024x2048

**Comment by shartoo** [comment]
**Not a emergency question**

Today i tried a transfer learning on MobileNet v1,which completely composed by conv2d and a critial global average pooling layer to map all features into same shape before output . 

![519](https://user-images.githubusercontent.com/5716282/68838643-fed1b100-06f9-11ea-8e38-4fcb7b5fa9d6.png)


It could handle all size of input, but another question raise, how could those parameters be shared between different weights shape in the same layer.For example if i trained a model with input shape 130x130x3 and load the parameters, then changed the input shape into 448x448, the shape of weights of conv2d were totaly different ,how did the parameters spread from work?

**Comment by AlexeyAB** [comment]
> the shape of weights of conv2d were totaly different 

What is the "shape of weights"?

Convolutional-weights doesn't depend on input or output size.

**Comment by shartoo** [comment]
Oh, i made a mistake ,it should be the shape of feature map .I got it! However the input size varies, it makes no difference on weights matrixes but feauture maps.Thank you very much, i got the detail of this question finally!

**Comment by shartoo** [comment]
The reason of resize not woring on keras 2.4.2 on MobileNet was proved a bug of Tensorflow2.0.0 [here](https://github.com/tensorflow/tensorflow/issues/34264) ,Thank you again,your answer help me so much!
