### ISSUE TITLE
Traceback (most recent call last): File "darknet_video.py", line 116, in YOLO() File "darknet_video.py", line 106, in YOLO detections = darknet.detect_image(netMain, metaMain, darknet_image, thresh=0.25) File "/home/marduk/darknet/darknet.py", line 278, in detect_image if dets[j].prob[i] > 0: ValueError: NULL pointer access

### ISSUE THREAD

**Issue by saraAlsiyat1** [AlexeyAB/darknet#4207]

**Comment by muduimushui** [comment]
may be I have the same problem with you. when j=1,it just crashed and nothing output.Did you solve your problem?

**Comment by saraAlsiyat1** [comment]
> may be I have the same problem with you. when j=1,it just crashed and nothing output.Did you solve your problem?

I download the new version of darknet and the problem is solved
