### ISSUE TITLE
Run Tiny-YOLOv3 on Jetson Nano

### ISSUE THREAD

**Issue by DoriHp** [AlexeyAB/darknet#4209]
I trained a yolov3-tiny model for face detection and ran it on Jetson Nano. I used YOLO to detect face in stream I got from my IP camera by running command: `./darknet detector demo cfg/coco.data cfg/yolov3-tiny.cfg yolov3-tiny.weights <my camera's connect string>`. 224x224 is the input I used for the model. YOLO detected well, and FPS is arround 12 fps, what was lower than I expected. I have some question:
- Is that FPS normal? If not, what can I do to improve it?
- What importances two flags "-i" and "1" in your example command : `darknet.exe detector demo cfg/coco.data cfg/yolov3-tiny.cfg yolov3-tiny.weights -i 1 test.mp4` are? What diff between with and without them?
- If I want to crop frame I get from my IP camera and recieve not only displaying from cv2 but also YOLO's result (bounding boxes,... etc), what should I do?

Jetson nano's specs from NVIDIA's homepage:
- NVIDIA Maxwell™ architecture with 128 NVIDIA CUDA® cores
0.5 TFLOPs (FP16)
- Quad-core ARM® Cortex®-A57 MPCore processor
- OS: Ubuntu 18.04
Thanks in advance.

**Comment by AlexeyAB** [comment]
> Is that FPS normal? If not, what can I do to improve it?

Yes, for 0.5 TFlops

>  -i 1

It will use GPU-1 instead of GPU-0



> If I want to crop frame I get from my IP camera and recieve not only displaying from cv2 but also YOLO's result (bounding boxes,... etc), what should I do?

What do you mean?

**Comment by DoriHp** [comment]
I only want to detect from a region of the frame I get from IP camera. And with the result, I want to get the coordinate of all bouding box that YOLO predicted to use for other processes, such as send to my Web API.

**Comment by AlexeyAB** [comment]
> I only want to detect from a region of the frame I get from IP camera.

You should implement it by yourselft, f.e. there: https://github.com/AlexeyAB/darknet/blob/4d9addedd719cfb5d68cb3b39d5c7f9193071c0d/src/image_opencv.cpp#L766
like:
```cpp
cv::Rect rt(...);
cv::Mat roi = (*src)(rt);
...
```

> And with the result, I want to get the coordinate of all bouding box that YOLO predicted to use for other processes, such as send to my Web API.

https://github.com/AlexeyAB/darknet#how-to-use-on-the-command-line

JSON and MJPEG server that allows multiple connections from your soft or Web-browser ip-address:8070 and 8090: `./darknet detector demo ./cfg/coco.data ./cfg/yolov3.cfg ./yolov3.weights test50.mp4 -json_port 8070 -mjpeg_port 8090 -ext_output`

**Comment by DoriHp** [comment]
Thank for your help :3

**Comment by DoriHp** [comment]
Sorry for disturbing you again. But I recently read about YOLO Nano at [](https://arxiv.org/abs/1910.01271) but I couldn't find out any other document about it. Can you share me something about it?

**Comment by socratesishere** [comment]
>  I recently read about YOLO Nano at https://arxiv.org/abs/1910.01271 but I couldn't find out any other document about it. Can you share me something about it?

I am currently working on trying to implement and see how the results from this paper help and compare with other latest tiny yolo models (eg tinyyolov3-prn). will keep you updated

**Comment by AlexeyAB** [comment]
@DoriHp No. Read this thread about Yolo nano: https://github.com/AlexeyAB/darknet/issues/4037
