### ISSUE TITLE
Can I train yolo_v2 as input image, 1280x960 ?

### ISSUE THREAD

**Issue by zed654** [AlexeyAB/darknet#422]
my training setting is that
  1. yolo v2
  2. training option is batch=256 / subdivision = 16 / height = 416 / width = 416 / randam = 1
  3. input image size is 1280x960
  4. classes = 10 / last conv's filters = 75
  5. anchors =  1.3221, 1.73145, 3.19275, 4.00944, 5.05587, 8.09892, 9.47112, 4.84053, 11.2364, 10.0071

other options is equal to default of yolo v2.

Is it a right method to train 1280x960 image...?
(or.. do i have to change training option height = 416 / width = 416 to height = 960 / width = 1280 ?)

**Comment by TheMikeyR** [comment]
You should keep yolo network at square format and dividable by 32. If you should increase the network or not depends on how big your objects are in the images? You should check if the objects are at least 1 pixel big when the image is resized to 416x416. If they are not visible you will gain from increasing the network size.

**Comment by AlexeyAB** [comment]
@zed654 

You can use for training any of this options, even if your images 1280x960

* You can use height = 416 / width = 416
* Or you can use height = 832 / width = 832 - model will have more precision, but detection will be slower
* You can use height = 960 / width = 1280, but for this you should re-calculate anchors: `darknet.exe detector calc_anchors data/obj.data -num_of_clusters 5 -final_width 40 -final_heigh 30`
where `40 = 1280/32` and `30 = 960/32` - but sometimes training with non-square neural network can be either better or worse than square 960x960.
