### ISSUE TITLE
make error:/usr/bin/ld: cannot find  -lcuda

### ISSUE THREAD

**Issue by thinkyang88** [AlexeyAB/darknet#4224]
I have installed CUDA10.1 sussfully,but inside darknet ,I run "make" and an error occured: /usr/bin/ld: cannot find  -lcuda,what's the reason？

**Comment by AlexeyAB** [comment]
May be 7. Post-installation Actions

https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#post-installation-actions

**Comment by thinkyang88** [comment]
I uninstall 10.1 and install 10.0,then it works!
