### ISSUE TITLE
cfg and pretrained weight

### ISSUE THREAD

**Issue by aluds123** [AlexeyAB/darknet#4225]
Hi, I am new in darknet, and I have question about pretrained weight(like darknet53.conv.74).
1. If I modify the yolov3.cfg (add maxpooling layer and change the numbers of layers), can I use the same pretrained weights (darknet53.con.74) or what can I do??

And I also wondering how does pretrained weights work :
2. cfg is not same to yolov3 and object is not same to coco
3. cfg is same to yolov3 but object is not same to coco

Sorry, my English is not good.

**Comment by AlexeyAB** [comment]
`darknet53.conv.74` here 74 means that it containes the weights from the first 74 layers. So if you modified the first 74 layers in your cfg-file, then you can't use `darknet53.conv.74` file.

**Comment by aluds123** [comment]
Thanks for your reply.

**Comment by aluds123** [comment]
@AlexeyAB 
I want to know if my thoughts are right.
When I’m training, if my cfg is not same to yolov3, but I choose darknet53.conv.74, then the initial weights will not apply darknet53.conv.74.The initial weight will be zero or random.
Is it right?

**Comment by AlexeyAB** [comment]
If you don't use pre-trained weights - your weights will be random

**Comment by aluds123** [comment]
Thanks for your answer.
