### ISSUE TITLE
Decreasing the threshold in inference results into segmentation fault

### ISSUE THREAD

**Issue by agirbau** [AlexeyAB/darknet#423]
Hello,
I was playing with YOLO and I realized that, for the same video, by just decreasing the detection threshold (from 0.4 to 0.1) results into a segmentation fault. 
As far from I've seen, it seems that the data for that low threshold is not correctly parsed into the variable "show_img" in "draw_detections_cv". 
Any clue why? 
FYI it depends on the input video (some videos work with even thresh=0.01).
Thanks!

**Comment by AlexeyAB** [comment]
Hi, ok I will test it. Do you use the default model yolo-voc.cfg & yolo-voc.weights?

Can you upload the video-file wich occurs error? (using google-disk or something)

**Comment by agirbau** [comment]
Hello, 
I use a custom .cfg (and custom weights). I'm afraid I can't upload the video or the files I'm using. I'll try to reproduce the error using standard yolo files and I'll post them here. Thank you!

**Comment by agirbau** [comment]
BTW it works using draw_detections (it has a variable "image" associated to it)
https://github.com/AlexeyAB/darknet/blob/a6c51e3b758aee7fd3a6f1d37daa8dcad4891e52/src/demo.c#L108 works
https://github.com/AlexeyAB/darknet/blob/a6c51e3b758aee7fd3a6f1d37daa8dcad4891e52/src/demo.c#L109 doesn't work 

A thing I've noticed is that the variable `ipl_images` has both 3 positions filled using `thresh = 0.4` 

![image](https://user-images.githubusercontent.com/23292221/37207848-22498d46-239f-11e8-92ea-bd3f8cfbdb86.png)

but only 1 position filled with `thresh=0.05`

![image](https://user-images.githubusercontent.com/23292221/37207864-361c7036-239f-11e8-9f59-7f0624f01b6a.png)

The code is in demo.c:
https://github.com/AlexeyAB/darknet/blob/a6c51e3b758aee7fd3a6f1d37daa8dcad4891e52/src/demo.c#L102-L109

Maybe it has something to do with the multi-threading (by having a lower threshold more objects should appear in the image, generating a delay that makes the variable enter the next function incomplete).

**Comment by agirbau** [comment]
For anyone who has the same issue, if you change:
https://github.com/AlexeyAB/darknet/blob/8f1f5cbf8321b6b313d8f455d596290e7b8bb3f7/src/demo.c#L18
to 1 it doesn't crash.
