### ISSUE TITLE
Couldn't open file: yolo-voc.weights

### ISSUE THREAD

**Issue by wbq330** [AlexeyAB/darknet#4234]
I have no GPU ,so I used 
          darknet_no_gpu detector test data/voc.data yolo-voc.cfg yolo-voc.weights
and then it told me：
         Loading weights from yolo-voc.weights...Couldn't open file: yolo-voc.weights
how can I solve the problem?

**Comment by AlexeyAB** [comment]
http://pjreddie.com/media/files/yolo-voc.weights
