### ISSUE TITLE
Training interrupt on Colab

### ISSUE THREAD

**Issue by Dauriel** [AlexeyAB/darknet#4235]
Trying to train Yolov3 with a custom dataset on Google Colab, the execution simply stops in the middle of a random batch & epoch without an error code. I'm using the -dont_show flag to avoid getting the "Gtk-WARNING **: cannot open display:" interrupt, so that might be why it doesn't show an error code. Reduced batch and subdivisions without luck. Don't really know what else to try.

**Comment by AlexeyAB** [comment]
try flag `-dont_show` at the end of training command

**Comment by Dauriel** [comment]
> try flag `-dont_show` at the end of training command
> I'm using the -dont_show flag to avoid getting the "Gtk-WARNING **: cannot open display:" interrupt, so that might be why it doesn't show an error code.

I am using "-dont_show" already.

**Comment by AlexeyAB** [comment]
* Show content of bad.list and bad_label.list
* What cfg-file do you use?
* What params in Makefile do you use?
* How many iterations did you train before the error occurred?
* How many free CPU RAM was before the error occurred?

**Comment by Dauriel** [comment]
> * Show content of bad.list and bad_label.list
I don't have those files. I think the dataset is correct.
> * What cfg-file do you
I'm using the cfg [YOLOV3-608](https://github.com/pjreddie/darknet/blob/master/cfg/yolov3.cfg)
> * What params in Makefile do you use?
Running CUDA and OpenCV
> * How many iterations did you train before the error occurred?
No fix number. 
> * How many free CPU RAM was before the error occurred?
Google Colab showed 9GB free RAM

**Comment by ycelik** [comment]
I'm interested in this topic as well. Going to order Colab soon. @Dauriel can you share your experience so far?

**Comment by Dauriel** [comment]
> I'm interested in this topic as well. Going to order Colab soon. @Dauriel can you share your experience so far?

Aside from the problem I have that doesn't let me train the net properly, I haven't had complaints. Works really good and Yolov3+darknet is pretty easy to deploy. (You do need to keep in mind the 12h restriction.)

**Comment by Dauriel** [comment]
I believe I solved the issue. For some reason one image was not uploading properly and was crashing the training whenever it was used. Deleted it and working smooth now.

**Comment by AlexeyAB** [comment]
@Dauriel Did you find it in `bad.list` file?

**Comment by Dauriel** [comment]
> @Dauriel Did you find it in `bad.list` file?

No, "bad.list" file didn't generate. I recreated my dataset and it didn't crash, then managed to find the file that was causing it.

**Comment by AlexeyAB** [comment]
If you can find this bad image, can you attach it in zip-archive?

**Comment by Dauriel** [comment]
> If you can find this bad image, can you attach it in zip-archive?

[000248.zip](https://github.com/AlexeyAB/darknet/files/3811880/000248.zip)

**Comment by ycelik** [comment]
> > I'm interested in this topic as well. Going to order Colab soon. @Dauriel can you share your experience so far?
> 
> Aside from the problem I have that doesn't let me train the net properly, I haven't had complaints. Works really good and Yolov3+darknet is pretty easy to deploy. (You do need to keep in mind the 12h restriction.)

Can you also share some stats about the performance and please? Gratz on finding the bad image

**Comment by nancyshaji** [comment]
@Dauriel Is it possible for you to share the training code on Google colab?
I am doing a project where I need to train a custom dataset and I do not have access to a GPU, other than colab.

**Comment by Dauriel** [comment]
@nancyshaji I'm not sure I understand your question. You can share your code with others on Colab. If what you are asking for is mine, I just followed the guideline for darknet, not much I can help you with there.
