### ISSUE TITLE
Training stops before 100 iteration

### ISSUE THREAD

**Issue by KimalIsaev** [AlexeyAB/darknet#4245]
It stops unexpectedly, without any error, but always at different iteration:
at 13
![2019-11-07_02-13-17](https://user-images.githubusercontent.com/27774041/68330686-4195f680-0106-11ea-8926-f530975f48cb.png)
at 47
![2019-11-07_02-42-48](https://user-images.githubusercontent.com/27774041/68331962-7e62ed00-0108-11ea-9c17-f4194e9c6855.png)
at 4
![2019-11-07_02-54-05](https://user-images.githubusercontent.com/27774041/68332823-f41b8880-0109-11ea-85b0-304cca8fd730.png)

I'm training on 1 class, at the beginning I used in .cfg:
```
max_batches = 4000
policy=steps
steps=3200, 3600
```
then I thought that problem was in max_batches, and changed cfg:
```
max_batches = 12000
policy=steps
steps=9600, 10800
```
it didn't help

I'm using:
Windows 10
Visual Studio 2017
GeForce GTX TITAN Black
CUDA v10.0
cuDNN v7.6.4
 
I would be very grateful, if you told me any ideas, which can help.

**Comment by AlexeyAB** [comment]
Show content of files: bad.list and bad_label.list

**Comment by KimalIsaev** [comment]
Thanks a lot, after deleting name of bad image in "train.txt" everything is working.
