### ISSUE TITLE
which card are people using who have not met the problem of out of memory

### ISSUE THREAD

**Issue by HydroRifle** [AlexeyAB/darknet#4247]
I frequently faces the problem of  "CUDA Error: out of memory" after I followed the tutorial of the author who said that we should set the batch and subvision to 64 and 8 individually.

I am running this on a 1080ti, 11GB GDDR5

which cards can suppress this problem?
Tesla M40 M60 P100 ?
Quadro M/P6000 24GB?

**Comment by tianfengyijiu** [comment]
@HydroRifle you can turn up subdivision, such as 16 or 32 instead of 8.

**Comment by HydroRifle** [comment]
> @HydroRifle you can turn up subdivision, such as 16 or 32 instead of 8.

yes, I tried batch=16 and sub=8, it works.

I really want to ask whether there is a card that don't need to do some tricks like this.

**Comment by AlexeyAB** [comment]
Use Quadro RTX 8000 (48 GB) or Quadro GV100 (32 GB) or TITAN RTX (24 GB)
Or just use batch=64 subdivisions=64

**Comment by HydroRifle** [comment]
Okay, glad to know that.
Thank you guys all.
