### ISSUE TITLE
Getting error while modify the yolov3_tiny.cfg for convolution layer with stride = 2

### ISSUE THREAD

**Issue by spaul13** [AlexeyAB/darknet#4248]
While implementing the strided convolution (convolution with stride >1, here stride = 2) instead of convolution+maxpool for yolov3 tiny model. I am getting the following error

![image](https://user-images.githubusercontent.com/20827182/68358687-3e3f4280-00e7-11ea-81ae-2ade09230e6c.png)

Basically I modified the stride of convolution layer from 1 to 2 and removed the maxpool layer 
I am also attaching the cfg file

[yolo_cfg.txt](https://github.com/AlexeyAB/darknet/files/3817800/yolo_cfg.txt)

Even if I have tried to keep the maxpool layer with stride 1 but I am still getting the error. Can anyone please tell me how to resolve this error?

**Comment by AlexeyAB** [comment]
You can't concatenate layers with different sizes.
Just remove layer-13 [upsample]

**Comment by spaul13** [comment]
Thanks a lot @AlexyAB. It worked perfectly fine.
