### ISSUE TITLE
Train bottle same brand different height with Yolo

### ISSUE THREAD

**Issue by xjohnxjohn** [AlexeyAB/darknet#4258]
Hi AlexeyAB,
   How to train the bottle that same brand different height and can detect it with different result. See the example 
![image](https://user-images.githubusercontent.com/7420735/68486622-0d404880-0274-11ea-9e10-ef2129161955.png)

**Comment by AlexeyAB** [comment]
It seems that you should set jitter=0 random=1 in all [yolo] layers.

And mark different bottles as different objects, then train.

**Comment by xjohnxjohn** [comment]
Thank you, AlexeyAB.
