### ISSUE TITLE
 Assertion failed ((flags & FIXED_TYPE) != 0) in cv::_InputArray::type

### ISSUE THREAD

**Issue by RiyadhB** [AlexeyAB/darknet#426]
Hello,
I got an Opencv related error when I tried to test darknet_coco_9000 example. The error message is OpenCV(3.4.1) Error: Assertion failed ((flags & FIXED_TYPE) != 0) in cv::_InputArray::type, file C:\build\master_winpack-build-win64-vc14\opencv\modules\core\src\matrix_wrap.cpp, line 807.

I don't know if it caused by an error during the building process.
Thank you for your help
Bests,

**Comment by AlexeyAB** [comment]
@RiyadhB Did you successfully compiled Darknet with OpenCV 3.4.1?
It seems that Darknet can't be compiled with 3.4.1: https://github.com/AlexeyAB/darknet/issues/414
Try to use OpenCV 3.4.0

**Comment by RiyadhB** [comment]
Now, it works. The problem was the version of OpenCV. I compiled Darknet with OpenCV 3.4.0 and it works fine.
Thank you @AlexeyAB
