### ISSUE TITLE
Error of "Too many or too few labels" while training a classification model

### ISSUE THREAD

**Issue by spaul13** [AlexeyAB/darknet#4263]
I am trying to train a classification model (resnet18) on my custom dataset but getting the error

**_Too many or too few labels: 2, C:\yolo\darknet\build\darknet\x64\data\obj_200\27_dog.png_**

I have renamed the training image file as index_label.png and store the filepaths at train.list and put this train.list location to the train.data folder.

Can anyone please tell me why this error is coming and how to get rid of this error?

**Comment by AlexeyAB** [comment]
Show content of `imagenet.shortnames.list` and `imagenet.labels.list`

**Comment by spaul13** [comment]
I dont have a shortnames.list where to put the shortnames.list.

This is my labels.txt file (its some customized labels)
[labels_new.txt](https://github.com/AlexeyAB/darknet/files/3827682/labels_new.txt)

Here is my train.list (path to each image files renamed as index_label.png, not using imagenet)
[train_new.txt](https://github.com/AlexeyAB/darknet/files/3827686/train_new.txt)

in the train.data file I gave train_new.txt as a List file where labels as text file.

@AlexeyAB plz let me know what I am missing?

**Comment by AlexeyAB** [comment]
Show your obj.data file

**Comment by spaul13** [comment]
_classes=68
train  = data\\cifar\\train_new.list
valid  = data\\cifar\\train_new.list
labels = data\\cifar\\labels_new.txt
backup = backup_exp\\
top=1_


This is the content of the obj.data file

**Comment by AlexeyAB** [comment]
one of label from this file `labels = data\cifar\labels_new.txt`
should be in the image filename.

> Too many or too few labels: 2, C:\yolo\darknet\build\darknet\x64\data\obj_200\27_dog.png

There is no `dog` in your labels `data\cifar\labels_new.txt`

**Comment by spaul13** [comment]
If u see the image files 27_reso480jpegencode20.png, I don't have the dog label either in image file name or in label file.

I just put that in order to show the nomenclature conveniently. 

what other errors might be there?

**Comment by AlexeyAB** [comment]
Show screenshot of your error

**Comment by spaul13** [comment]
This is the screenshot of the error

![image](https://user-images.githubusercontent.com/20827182/68535374-948eca00-030f-11ea-8f03-ca6bcd8a6015.png)

"I just put that in order to show the nomenclature conveniently" - what I want to convey is that
in order to make the labels short and understandable in issue I put dog there. But I am not using dog.

Plz help me to get rid of this problem. thanks in advance.

**Comment by AlexeyAB** [comment]
One of your label shouldn't include another label, like this:
```
reso320jpeg
reso320jpegencode24
```

so in file `reso320jpegencode24.jpg`

will be found both these labels.

**Comment by spaul13** [comment]
@AlexeyAB, I have changed the labels so that no such condition can happen as u mentioned in ur last reply. Still I am getting this error. can u plz help me on this?

Screenshot of error
![image](https://user-images.githubusercontent.com/20827182/68536517-433c0600-0322-11ea-9777-901fd0d45fb5.png)

labels.txt file
[labels.txt](https://github.com/AlexeyAB/darknet/files/3827885/labels.txt)

train.txt
[train_map.txt](https://github.com/AlexeyAB/darknet/files/3827887/train_map.txt)

Content of obj.data is
classes=68
train  = data\\cifar\\train_map.list
valid  = data\\cifar\\train_map.list
labels = data\\cifar\\labels.txt
backup = backup_exp\\
top=1

Can u plz help me why still I am getting the same error?

Thanks in advance.

**Comment by AlexeyAB** [comment]
>  I have changed the labels so that no such condition can happen as u mentioned in ur last reply. Still I am getting this error. 

`car` and `carrot`


Thats why imagenet uses unique identifiers instead of labels in filenames: https://github.com/AlexeyAB/darknet/blob/master/data/imagenet.labels.list

**Comment by spaul13** [comment]
Ok. Thanks a lot @AlexeyAB
