### ISSUE TITLE
performance issue ??? 

### ISSUE THREAD

**Issue by TheHidden1** [AlexeyAB/darknet#427]
hello 
i managed to compile with Cuda8.0 & opencv 3.2  

when  i test  it  with the  coco dataset   "darknet.exe detector demo data/coco.data yolo.cfg yolo.weights test.mp4 -i 0" 

it lags & i am not seeing much GPU usage 

i am new to this so please excuse my Ignorance 😸 
i will be glad if you  could explain to me the problem  
thank you
![screenshot 3](https://user-images.githubusercontent.com/31354864/37035760-d5914186-214d-11e8-9a84-e5ffcd177bd1.png)

**Comment by AlexeyAB** [comment]
Hi, I just curn this command and it works well with ~90-100 % GPU uase. It seems that by default the CUDA compute сapability (CC) is not selected for your GPU architecture.

* What GPU do you have?
* What CPU do you have?
* Is it Desktop PC or Notebook?
* What is the resolution of video?

* Try to compile it with CUDNN as desctibed: https://github.com/AlexeyAB/darknet#how-to-compile-on-windows
* Or try toopen `\darknet.sln` ->(right click on project) -> properties -> CUDA C/C++ -> Device -> Code generation:
    Change this line `compute_30,sm_30;compute_52,sm_52` to that corresponded to your GPU: https://en.wikipedia.org/wiki/CUDA#GPUs_supported

**Comment by TheHidden1** [comment]
thanks for replying, 
it seems that the Task Manger on windows 10 doesn't report GPU activity correctly , when i used inspector i got a different result .

sorry to bother you  ,
![screenshot 4](https://user-images.githubusercontent.com/31354864/37040940-471f3f3a-215b-11e8-9991-0d6dd8870357.png)
