### ISSUE TITLE
Modify darknet code for epoches, boudaries format and video reading

### ISSUE THREAD

**Issue by Wazaki-Ou** [AlexeyAB/darknet#4276]
Hello there,

This isn't really an issue, but if I can have an answer it will make my life much easier. I'm sorry if the title is confusing, I just did not want to open 3 different issues for questions all related to modifying/handling the code.

1. For some reason, my code always stops after 4000 epochs and saves the final weight at the same time. I thought that it was supposed to run for much longer than that. Is there a file where that can be controlled. (This actually isn't very important as the loss already reaches a very low point by then)

2. (This is to be applied on video files) So I would like to use the results from the detection in my own script and I am a wondering if there is already a good available way to do so. I tried saving the results in a text file to use later in my own code, but the format is just making it more complicated and hence I am wondering how I could do one of the two following things:

a- modify the format used to save to make it easier for me to parse the text file later and get the bounding boxes.
b- get the bounding boxes directly when they are detected by the model after detecting in a specific frame of the video and add my own script to that part of the code.

(b) sounds like a more complicated process with many things that can go wrong, so I personally prefer going with (a). However, I can't seem to find the exact file or files that need to be modified to do that.

Thank you in advance 👍

**Comment by AlexeyAB** [comment]
1. change max_batches=4000 in your cfg-file https://github.com/AlexeyAB/darknet/wiki/CFG-Parameters-in-the-%5Bnet%5D-section

2. Use darknet as DLL/SO-library (compile with LIBSO=1 in the Makefile) and use it as in this example: https://github.com/AlexeyAB/darknet/blob/master/src/yolo_console_dll.cpp

Or use Darknet as JSON-server: https://github.com/AlexeyAB/darknet#how-to-use-on-the-command-line

JSON and MJPEG server that allows multiple connections from your soft or Web-browser ip-address:8070 and 8090: `./darknet detector demo ./cfg/coco.data ./cfg/yolov3.cfg ./yolov3.weights test50.mp4 -json_port 8070 -mjpeg_port 8090 -ext_output`

F.e. run this command and open in your Chrome-webbrowser URL: http://127.0.0.1:8070 or http://127.0.0.1:8090

**Comment by Wazaki-Ou** [comment]
> 
> 
>     1. change max_batches=4000 in your cfg-file https://github.com/AlexeyAB/darknet/wiki/CFG-Parameters-in-the-%5Bnet%5D-section
> 
>     2. Use darknet as DLL/SO-library (compile with LIBSO=1 in the Makefile) and use it as in this example: https://github.com/AlexeyAB/darknet/blob/master/src/yolo_console_dll.cpp
> 
> 

Thank you !! using the DLL library and building up on the sample python file has helped me achieve exactly what I wanted !!!
