### ISSUE TITLE
Training new models from actual code (no CLI)

### ISSUE THREAD

**Issue by tejashah88** [AlexeyAB/darknet#428]
Is there a way to train new models from C++ or any other language? Most of the code from [yolo_console_dll.cpp](https://github.com/AlexeyAB/darknet/blob/master/src/yolo_console_dll.cpp) is just for the detection part.

**Comment by AlexeyAB** [comment]
If you want to change process of training, you can change this function: https://github.com/AlexeyAB/darknet/blob/master/src/detector.c#L34

Or you can add here: https://github.com/AlexeyAB/darknet/blob/master/src/yolo_v2_class.hpp#L26
line `YOLODLL_API void train_detector(char *datacfg, char *cfgfile, char *weightfile, int *gpus, int ngpus, int clear, int dont_show);`

And then use this function in the `yolo_console_dll.cpp` (it will use `train_detector()` from the `yolo_cpp_dll.dll`)

**Comment by tejashah88** [comment]
Thank you for the quick response. Would it be possible to integrate it into this repo?

**Comment by AlexeyAB** [comment]
I added this fix. Compile `darknet/build/darknet/yolo_cpp_dll.sln` and use can use function 
`void train_detector(char *datacfg, char *cfgfile, char *weightfile, int *gpus, int ngpus, int clear, int dont_show);` 
from `yolo_cpp_dll.dll`
