### ISSUE TITLE
Custom Object Detection

### ISSUE THREAD

**Issue by shubham3git** [AlexeyAB/darknet#4284]
Hi, 

Can we train model again n again with different data set?

For Example - 

I have trained a model for 1000 iteration with 1000 images and again i want to train the model for 3000 iteration with another 2000 images. is it possible?

**Comment by ntd94** [comment]
I believe it is doable. Just change the content of the `.data` file and continue training. But, just curious, why?

**Comment by shubham3git** [comment]
@ntd94 

I am getting very less predictions from yolov3_1000.weight but nothing after 3000 iteration(yolov3_3000.weight). 

After 1000 iteration i have stopped training and added 2000 more labelled images and updated .data , train.txt and test.txt.

**Comment by haviduck** [comment]
I think pseudo labeling Will do that for ya, havent tried it myself but it is right there in the readme
