### ISSUE TITLE
Guidance - train data preperation

### ISSUE THREAD

**Issue by arfin-agnext** [AlexeyAB/darknet#4288]
The testing video is having a resolution of 640 x 480 and has distinct classes.

**1. Which case mentioned below is better to follow, for annotation using Yolo Mark?
2. Is it better to record training videos having resolution 640 x 480 or 1280 x 720 ?**

Case1:
record video1 having only class1, video2 having only class2, so on...
Case2:
record video1, video2, video3, so on.. having distinct classes, randomly.

There are 8 classes, using tiny yolo3

**Comment by AlexeyAB** [comment]
> Case2:
> record video1, video2, video3, so on.. having distinct classes, randomly.

It's better.
Better if there are many classes in one image.

> 2. Is it better to record training videos having resolution 640 x 480 or 1280 x 720 ?

It's better to use the same resolution during training and detection, so 640x480.
But more important to have the same relative sizes of objects during training and detection.

**Comment by arfin-agnext** [comment]
Thanks
