### ISSUE TITLE
support yolo v1 or not?

### ISSUE THREAD

**Issue by 123liluky** [AlexeyAB/darknet#429]
1、While I conducted yolo-v1: darknet.exe detector train data/obj.data cfg/yolov1/yolo-small-obj.cfg, the result was: 
Detection Avg IOU: 1.#QNAN0, Pos Cat: 1.#QNAN0, All Cat: 1.#QNAN0, Pos Obj: 1.#QNAN0, Any Obj: 1.#QNAN0, count: 92
1.#QNAN0 loss, -1.#QNAN0 avg loss, 0.001000 rate, 6.230000 seconds, /64 images
2、And I conducted yolo-v2, results are normal:  
Region Avg IOU: 0.181871, Class: 1.000000, Obj: 0.510740, No Obj: 0.490451, Avg Recall: 0.000000,  count: 4
14.205628 loss, 14.205628 avg loss, 0.000100 rate, 2.090000 seconds, 64 images
Region Avg IOU: 0.295255, Class: 1.000000, Obj: 0.419536, No Obj: 0.436419, Avg Recall: 0.250000,  count: 4
...
Does this mean yolo-v1 is not supported?

**Comment by sivagnanamn** [comment]
YOLO V1 is supported in @AlexeyAB's [repo](https://github.com/AlexeyAB/darknet/). You may face Nan in the [original darknet repo](https://github.com/pjreddie/darknet) for YOLO V1.

Which repo are you using currently?

There could be many reasons for nan:

1. Even when every configuration is proper, still few runs produce Nan's. Try reducing your batch size & re-train again
2. Does any of your annotation contains 0?

**Comment by 123liluky** [comment]
@sivagnanamn  Thanks for your reply. I am using AlexeyAB's repo.  
I have checked my annotation files. I labeled a true box in each image. 
I just revised classes=1 in [detection] in cfg/yolov1/yolo-small. And run darknet.exe detector train data/obj.data cfg/yolov1/yolo-small.cfg. Are there any other things I should do before training?

**Comment by sivagnanamn** [comment]
**For training YOLO V1 use:**

./darkent yolo train .....

**For training YOLO V2:**

./darknet detector train ....

You're trying to train an V1 network using V2 command. Could you please try the V1 train command?

**Comment by 123liluky** [comment]
@sivagnanamn , I have tried, the result looks normal now. Thank you very much.

**Comment by groot-1313** [comment]
@sivagnanamn , upon using `./darknet yolo train data/obj.data cfg/yolov1.cfg` I get a segmentation fault. Is there something I can do about this?

**Comment by sivagnanamn** [comment]
@groot-1313 you've to use `./darknet yolo train cfg/yolov1.cfg` for training YOLO V1. 

The .data file is required only for YOLO V2 & V3.

**Comment by groot-1313** [comment]
@sivagnanamn thanks that worked for me.

**Comment by groot-1313** [comment]
@sivagnanamn , I would like to port this YOLO model (.cfg and .weights of a YOLO v1 model) that has been trained on Linux to a windows application. Is there a way to do so, because from the documentation I see that the dll solution is available only for YOLO v2. @AlexeyAB , any help will be very much appreciated. Thanks
