### ISSUE TITLE
Performance difference ./darknet vs ./uselib

### ISSUE THREAD

**Issue by rcwinder** [AlexeyAB/darknet#4292]
Is the performance of ./darknet and ./uselib supposed to be the same?
I installed darknet on a system with a nvidia 2080 Ti, using the makefile with flags GPU=1, CUDNN=1, CUDNN_HALF=1, OPENCV=1 and LIBSO=1 to create the darknet libraries to be able to use it in another c++ program. However, after running make, I tested the inference time of a single image, using ./darknet ./uselib and a c++ program based on the example file yolo_console_dll.cpp using yolo_v2_class.hpp

using darknet results in 11ms inference time
using uselib results in ~80ms inference time
using own c++ file results in ~80ms inference time

Is the use of the library supposed to be slower, or am I doing something wrong?

**Comment by AlexeyAB** [comment]
Try to use new version of ./uselib
I added these changes: https://github.com/AlexeyAB/darknet/commit/a4012895c16aacf82416b3383b567fc143532c51

**Comment by rcwinder** [comment]
After rerunning make, ./uselib and my own c++ file both resulted in 12ms inference time, thanks for your quick response!

**Comment by oreo-lp** [comment]
thank you very much!
