### ISSUE TITLE
Turn off data augmentation

### ISSUE THREAD

**Issue by marcheseV** [AlexeyAB/darknet#4297]
Hi, 

Would it be possible to remove the data augmentation steps during detection training? We currently implement our own data augmentation pipeline to our dataset and would like to speed up training by removing this unnecessary step in the training process. 

Thanks

**Comment by AlexeyAB** [comment]
It will not speedup training if you compiled Darknet with OPENCV=1

You just can set `flip=0` in the [net] section and comment all other data-augmentation params:
hue, exposure, saturation, jitter, random, angle, max_crop, min_crop, angle, aspect, blur 

More: https://github.com/AlexeyAB/darknet/wiki/CFG-Parameters-in-the-%5Bnet%5D-section

**Comment by marcheseV** [comment]
Thanks @AlexeyAB ,

Could you further elaborate on why it would not speedup training, or perhaps point me in the right direction in terms of documentation on how I might find out. :)

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet#improvements-in-this-repository

> improved performance 3.5 X times of data augmentation for training (using OpenCV SSE/AVX functions instead of hand-written functions) - **removes bottleneck for training on multi-GPU or GPU Volta**

**Comment by AlexeyAB** [comment]
If some problems with performance will occur (for example on AMD CPU), then just increase this value from 3 to 6 and recompile https://github.com/AlexeyAB/darknet/blob/509ba13acf9b6738d9838eb1553a2f40e36c0c2e/src/detector.c#L143
