### ISSUE TITLE
Problem with multi-threading in detector.c 

### ISSUE THREAD

**Issue by Jumabek** [AlexeyAB/darknet#43]
Hi @AlexeyAB , 
I am trying to validate face detector that I trained on WIDER dataset
The problem is validation set contains 3226 images, but when I call validate_detector function, it processes sometimes all the 3226 images, sometimes 1044 and sometimes 1956.
For example, in this screenshoot it is 1956 images
![image](https://cloud.githubusercontent.com/assets/4343873/24182856/ebd4069e-0f07-11e7-8ab3-ac7bf07a4aba.png)
****

Could you help me to figure out the problem? I think it has something to do with threading, but I am not sure since I myself never had experience with multi-threading.

When I process 3226 with single thread (nthreads = 1), it is only processing first 1044 images.

only modification I did is in the for block as below, plus adding print_wider_detections function.  
```
for(i = nthreads; i < m+nthreads; i += nthreads){
        fprintf(stderr, "%d\n", i);
        for(t = 0; t < nthreads && i+t-nthreads < m; ++t){
            pthread_join(thr[t], 0);
            val[t] = buf[t];
            val_resized[t] = buf_resized[t];
        }
        for(t = 0; t < nthreads && i+t < m; ++t){		
	    args.path = paths[i+t];
            args.im = &buf[t];
            args.resized = &buf_resized[t];
            thr[t] = load_data_in_thread(args);
        }
        for(t = 0; t < nthreads && i+t-nthreads < m; ++t){
            char *path = paths[i+t-nthreads];
	    printf("m = %d,\ti = %d \titer = %d\n\n",m,i, i + t - nthreads);
            char *id = basecfg(path);
            float *X = val_resized[t].data;
            network_predict(net, X);
            int w = val[t].w;
            int h = val[t].h;
            get_region_boxes(l, w, h, thresh, probs, boxes, 0, map);
            if (nms) do_nms_sort(boxes, probs, l.w*l.h*l.n, classes, nms);
			
	    if (coco){
                print_cocos(fp, path, boxes, probs, l.w*l.h*l.n, classes, w, h);
            } else if (imagenet){
                print_imagenet_detections(fp, i+t-nthreads+1, boxes, probs, l.w*l.h*l.n, classes, w, h);
	    }
	    else if (wider) {
	        print_wider_detections(id, boxes, probs, l.w*l.h*l.n, classes, w, h);
	    }
	    else {
                print_detector_detections(fps, id, boxes, probs, l.w*l.h*l.n, classes, w, h);
            }
            free(id);
            free_image(val[t]);
            free_image(val_resized[t]);
        }
    }
```

**Comment by AlexeyAB** [comment]
@Jumabek 

At the end of the validation you should get this message `Total Detection Time:`: https://github.com/AlexeyAB/darknet/blob/master/src/detector.c#L358

![good](https://cloud.githubusercontent.com/assets/4096485/24201651/c07dffe4-0f21-11e7-8daf-e1ceccb31454.jpg)


So if you didn't get this message, then your program was crushed.

If without your changes you can get the message `Total Detection Time:` , then problem in your changes: `print_wider_detections(id, boxes, probs, l.w*l.h*l.n, classes, w, h);`

**Comment by Jumabek** [comment]
Thanks for the quick response @AlexeyAB.
This problem is occurring even when I train, it trains some time 1000 or 2000 then stops without any prompt. This happened with both the clean version of YOLO from your repo and my modified version.
I think it has something to do with my gpus. 

I will try to reinstall nvidia drivers.
