### ISSUE TITLE
I would like to know some changes to Yolo's learning part.

### ISSUE THREAD

**Issue by HYEYOONOH525** [AlexeyAB/darknet#430]
I would like to know some changes to Yolo's learning part.
There were updates to increase awareness of small objects, and we found that there were changes in the learning part, not the perception. However, I would like to know how the changes made to increase the recognition of small objects.

**Comment by TheMikeyR** [comment]
https://github.com/AlexeyAB/darknet/issues/397#issuecomment-366663984
