### ISSUE TITLE
python darknet_video.py : CUDA Error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by flowzen1337** [AlexeyAB/darknet#4300]
Hi @AlexeyAB ,

I've got the following weird issue that "darknet detector demo...." is working out of the box without problems **BUT** darknet_video.py doesnt work:

The computer i use:

`System:` ubuntu-1804
`Memory:` 15 GB
`CPU:` 4 vCPU (Intel(R) Xeon(R) CPU @ 2.30GHz)
`GPU:` 1x NVIDIA Tesla K80
`GPU Memory:` 11441MiB
`NVIDIA-SMI:` 418.87.00
`Driver Version:` 418.87.00
`CUDA Version:` 10.1

It's a Google Compute Engine instance I'm working on.

After make (which runs through without any problems) I successfully can use:

`./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights -ext_output video.mp4`

---

**BUT** when i try to use the provided python script "darknet_video.py" it ends up with the follwoing output:
`...`
`...`
`CUDA status = cudaDeviceSynchronize() Error: file: ./src/blas_kernels.cu : () : line: 576 : build time: Nov 14 2019 - 12:37:57`
`CUDA Error: an illegal memory access was encountered`
`python3.6: : Unknown error 620404015`

---

Any help would be greatly appreciated!

**Here is the full output:**

`python3.6 ./darknet_video.py` 
`Try to load cfg: ./cfg/yolov3.cfg, weights: ./yolov3.weights, clear = 0`
`compute_capability = 370, cudnn_half = 0`
`layer   filters  size/strd(dil)      input                output`
`0 conv     32       3 x 3/ 1    416 x 416 x   3 ->  416 x 416 x  32 0.299 BF`
`1 conv     64       3 x 3/ 2    416 x 416 x  32 ->  208 x 208 x  64 1.595 BF`
`2 conv     32       1 x 1/ 1    208 x 208 x  64 ->  208 x 208 x  32 0.177 BF`
`3 conv     64       3 x 3/ 1    208 x 208 x  32 ->  208 x 208 x  64 1.595 BF`
`4 Shortcut Layer: 1`
`5 conv    128       3 x 3/ 2    208 x 208 x  64 ->  104 x 104 x 128 1.595 BF`
`6 conv     64       1 x 1/ 1    104 x 104 x 128 ->  104 x 104 x  64 0.177 BF`
`7 conv    128       3 x 3/ 1    104 x 104 x  64 ->  104 x 104 x 128 1.595 BF`
`8 Shortcut Layer: 5`
`9 conv     64       1 x 1/ 1    104 x 104 x 128 ->  104 x 104 x  64 0.177 BF`
`10 conv    128       3 x 3/ 1    104 x 104 x  64 ->  104 x 104 x 128 1.595 BF`
`11 Shortcut Layer: 8`
`12 conv    256       3 x 3/ 2    104 x 104 x 128 ->   52 x  52 x 256 1.595 BF`
`13 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF`
`14 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF`
`15 Shortcut Layer: 12`
`16 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF`
`17 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF`
`18 Shortcut Layer: 15`
`19 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF`
`20 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF`
`21 Shortcut Layer: 18`
`22 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF`
`23 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF`
`24 Shortcut Layer: 21`
`25 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF`
`26 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF`
`27 Shortcut Layer: 24`
`28 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF`
`29 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF`
`30 Shortcut Layer: 27`
`31 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF`
`32 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF`
`33 Shortcut Layer: 30`
`34 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF`
`35 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF`
`36 Shortcut Layer: 33`
`37 conv    512       3 x 3/ 2     52 x  52 x 256 ->   26 x  26 x 512 1.595 BF`
`38 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF`
`39 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF`
`40 Shortcut Layer: 37`
`41 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF`
`42 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF`
`43 Shortcut Layer: 40`
`44 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF`
`45 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF`
`46 Shortcut Layer: 43`
`47 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF`
`48 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF`
`49 Shortcut Layer: 46`
`50 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF`
`51 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF`
`52 Shortcut Layer: 49`
`53 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF`
`54 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF`
`55 Shortcut Layer: 52`
`56 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF`
`57 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF`
`58 Shortcut Layer: 55`
`59 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF`
`60 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF`
`61 Shortcut Layer: 58`
`62 conv   1024       3 x 3/ 2     26 x  26 x 512 ->   13 x  13 x1024 1.595 BF`
`63 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF`
`64 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF`
`65 Shortcut Layer: 62`
`66 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF`
`67 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF`
`68 Shortcut Layer: 65`
`69 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF`
`70 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF`
`71 Shortcut Layer: 68`
`72 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF`
`73 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF`
`74 Shortcut Layer: 71`
`75 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF`
`76 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF`
`77 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF`
`78 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF`
`79 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF`
`80 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF`
`81 conv    255       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 255 0.088 BF`
`82 yolo`
`[yolo] params: iou loss: mse, iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00`
`83 route  79                                     ->   13 x  13 x 512`
`84 conv    256       1 x 1/ 1     13 x  13 x 512 ->   13 x  13 x 256 0.044 BF`
`85 upsample                 2x    13 x  13 x 256 ->   26 x  26 x 256`
`86 route  85 61                                  ->   26 x  26 x 768`
`87 conv    256       1 x 1/ 1     26 x  26 x 768 ->   26 x  26 x 256 0.266 BF`
`88 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF`
`89 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF`
`90 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF`
`91 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF`
`92 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF`
`93 conv    255       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 255 0.177 BF`
`94 yolo`
`[yolo] params: iou loss: mse, iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00`
`95 route  91                                     ->   26 x  26 x 256`
`96 conv    128       1 x 1/ 1     26 x  26 x 256 ->   26 x  26 x 128 0.044 BF`
`97 upsample                 2x    26 x  26 x 128 ->   52 x  52 x 128`
`98 route  97 36                                  ->   52 x  52 x 384`
`99 conv    128       1 x 1/ 1     52 x  52 x 384 ->   52 x  52 x 128 0.266 BF`
`100 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF`
`101 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF`
`102 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF`
`103 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF`
`104 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF`
`105 conv    255       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 255 0.353 BF`
`106 yolo`
`[yolo] params: iou loss: mse, iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00`
`Total BFLOPS 65.864`
`Allocate additional workspace_size = 12.46 MB`
`Loading weights from ./yolov3.weights...`
`seen 64`
`Done! Loaded 107 layers from weights-file`
`Loaded - names_list: data/coco.names, classes = 80`
`Starting the YOLO loop...`
`CUDA status = cudaDeviceSynchronize() Error: file: ./src/blas_kernels.cu : () : line: 576 : build time: Nov 14 2019 - 12:37:57`
`CUDA Error: an illegal memory access was encountered`
`python3.6: : Unknown error 620404015`

----------------------

**Makefile:**
`GPU=1`
`CUDNN=1`
`CUDNN_HALF=1`
`OPENCV=1`
`AVX=0`
`OPENMP=0`
`LIBSO=1`
`ZED_CAMERA=0`
`DEBUG=1`
`ARCH= -gencode arch=compute_30,code=sm_30       -gencode arch=compute_35,code=sm_35       -gencode arch=compute_50,code=[sm_50,compute_50]       -gencode arch=compute_52,code=[sm_52,compute_52]        -gencode arch=compute_61,code=[sm_61,compute_61]`
`...`
`...`

**nvcc --version:**
`nvcc: NVIDIA (R) Cuda compiler driver`
`Copyright (c) 2005-2019 NVIDIA Corporation`
`Built on Sun_Jul_28_19:07:16_PDT_2019`
`Cuda compilation tools, release 10.1, V10.1.243`

**nvidia-smi:**
`Thu Nov 14 12:43:21 2019`
`+-----------------------------------------------------------------------------+`
`| NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |`
`|-------------------------------+----------------------+----------------------+`
`| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |`
`| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |`
`|===============================+======================+======================|`
`|   0  Tesla K80           On   | 00000000:00:04.0 Off |                    0 |`
`| N/A   36C    P8    25W / 149W |      0MiB / 11441MiB |      0%      Default |`
`+-------------------------------+----------------------+----------------------+`
`+-----------------------------------------------------------------------------+`
`| Processes:                                                       GPU Memory |`
`|  GPU       PID   Type   Process name                             Usage      |`
`|=============================================================================|`
`|  No running processes found                                                 |`
`+-----------------------------------------------------------------------------+`

**Comment by AlexeyAB** [comment]
Try to use the latest Darknet version, there was fixed a bug yesterday

**Comment by flowzen1337** [comment]
> Try to use the latest Darknet version, there was fixed a bug yesterday

You are a Champions mate! Thank you so much, solved the problem out of the box :-)

Funny thing, i cloned darknet yesterday, it seems i just jused the clone some minutes before you released the new version. So... timing is everything i guess :-) Thank you again champ!
