### ISSUE TITLE
Relation between GPU and fps 

### ISSUE THREAD

**Issue by anavc94** [AlexeyAB/darknet#4308]
Hi everyone,

how is the GPU used and the fps related? It depends on the amoung of memory or operations per second?

Thanks!

**Comment by AlexeyAB** [comment]
It depends on operations per second `GFLOPS` 
 https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units

**Comment by anavc94** [comment]
thank you so much @AlexeyAB
