### ISSUE TITLE
explain the -clear flag in training command

### ISSUE THREAD

**Issue by M-Younus** [AlexeyAB/darknet#4310]
Hi can anyone give details what does the _-clear_ command do,Thanks

**Comment by lsd1994** [comment]
https://github.com/AlexeyAB/darknet/blob/10c40551dcadec68050befa6a1cecc6f69049d0d/src/detector.c#L78
Maybe set the iterations to 0.

**Comment by M-Younus** [comment]
for answer check this
https://github.com/AlexeyAB/darknet/issues/4353
