### ISSUE TITLE
what is the number at end of partial command

### ISSUE THREAD

**Issue by M-Younus** [AlexeyAB/darknet#4311]
Please can anyone explain what is the number at end of partial command,like
`darknet.exe partial cfg/yolov2.cfg yolov2.weights yolov2.conv.23 23`
what and why is _23_ ?
Thanks

**Comment by LukeAI** [comment]
it's number of layers to extract. you can extract however many layers you like

**Comment by M-Younus** [comment]
> it's number of layers to extract. you can extract however many layers you like

right,so is there any rule of thumb to calculate how many layers we will use for darknet?

**Comment by LukeAI** [comment]
depends on the model - generally you extract the number of layers that make up the backbone feature extractor. I think in Yolov2 it's 19. But don't use Yolov2, it's more or less redundant IMO. If yolov3-spp isn't fast enough for you, try it at a lower resolution or try tiny-yolo

**Comment by M-Younus** [comment]
> depends on the model - generally you extract the number of layers that make up the backbone feature extractor. I think in Yolov2 it's 19. But don't use Yolov2, it's more or less redundant IMO. If yolov3-spp isn't fast enough for you, try it at a lower resolution or try tiny-yolo

thank you for reply,but I still did not get it, what is the use of partial and on what basis we should decide the number(number at the end of partial command).

**Comment by LukeAI** [comment]
The point is for leveraging features learned on one dataset for use in a different but related task https://machinelearningmastery.com/transfer-learning-for-deep-learning/

choose the number of layers in the backbone feature extractor.
