### ISSUE TITLE
Generate Confusion Matrix

### ISSUE THREAD

**Issue by Andropogon** [AlexeyAB/darknet#4312]
I have trained Yolov3 on my custom dataset, now I want to present results. Is there easy way to generate Confusion Matrix or we can get only mAP and avg?

**Comment by priyankasinghvi** [comment]
did you find a way of doing this?

**Comment by Andropogon** [comment]
I found that it doesn't have sense to use Confusion Matrix in object
detection 😄 Because it is hard to define True Negatives:
https://stackoverflow.com/q/16271603/9738227

śr., 18 gru 2019, 18:13 użytkownik priyankasinghvi <notifications@github.com>
napisał:

**Comment by priyankasinghvi** [comment]
Well even if it doesnt make sense. I would like to plot it because I have the data. But I am unable to plot it. So if you have any recommendations on this. I am grateful!

**Comment by Hrishkesh** [comment]
Hello @priyankasinghvi  did you try it out to generate a confusion matrix ??
If so, can you please let me know!
