### ISSUE TITLE
How do I interpret this chart?

### ISSUE THREAD

**Issue by ycelik** [AlexeyAB/darknet#4316]
- Does my training go well?
- What are these spikes in loss and map?
- What else can you see from this chart?

[![loss-map-24k.png](https://i.postimg.cc/xChXkLWZ/loss-map-24k.png)](https://postimg.cc/LYk9wg4k)

**Comment by lsd1994** [comment]
Do you use sgdr policy? It's normal.

**Comment by ycelik** [comment]
> sgdr policy

No I use normal steps

**Comment by orcund** [comment]
I've been seeing that type of graph kinda frequently and all my models worked fine, so it seems normal to me but on the other hand there might be some minor problems and adjustments to fix.

**Comment by ycelik** [comment]
> I've been seeing that type of graph kinda frequently and all my models worked fine, so it seems normal to me but on the other hand there might be some minor problems and adjustments to fix.

Thank you very much for your feedback. I'll close this issue then :)

**Comment by AlexeyAB** [comment]
Yes, training goes well, but may be there is slightly controversial training data.
