### ISSUE TITLE
Need Help!! No CNN cfg file is working with [connected] layer in it

### ISSUE THREAD

**Issue by spaul13** [AlexeyAB/darknet#4326]
First I have tried alexnet.cfg and lstm.train.cfg which has a [connected] layer in their CNN configuration file. But are showing the error of 

 **_cuDNN status Error in: file: c:\yolo\darknet\src\convolutional_layer.c : cudnn_convolutional_setup() : line: 234 : build time: Nov 18 2019 - 22:21:34
cuDNN Error: CUDNN_STATUS_BAD_PARAM_**

I am also finding difficult while executing my own cfg with [connected] layer.
In order to train simple autoencoder with one hidden layer along with tiny yolov3. I have added one [connected] & [dropuout] layer for encoder and one [connected] & [dropuout] layer for decoder following are all yolov3-tiny layers. Here I am attaching the .cfg file also. But while starting the training  using darknet, I getting exited from the printing the feature size in layer 0 and layer 0 is a connected (fully connected) layer for dimensionality reduction.

**_C:\yolo\darknet\build\darknet\x64>darknet.exe detector train data\yolo_50img.data cfg\autoencoder_tinyyolov3.cfg yolov3-tiny.conv.15 -dont_show_**

 _compute_capability = 610, cudnn_half = 0
   layer   filters  size/strd(dil)      input                output
   0_

I found the its giving problem while creating fully connected layers at the function below
**connected_layer layer = make_connected_layer(params.batch, 1, params.inputs, output, activation, batch_normalize);**

Program execution exited from make_connected_layer() function.

**can anyone plz tell me why its not executing the training after adding the fully connected layer as the encoder-decoder of autoencoder?**

[autoencoder_tinyyolov3.txt](https://github.com/AlexeyAB/darknet/files/3860665/autoencoder_tinyyolov3.txt)

**Comment by hajlyx** [comment]
same problem, how did you fix this?

**Comment by AlexeyAB** [comment]
@spaul13 @hajlyx I fixed it: https://github.com/AlexeyAB/darknet/commit/7bf83018e48ffaf3883f2020dedebb98929acf4f

**Comment by hajlyx** [comment]
Thanks for this fix! I'll pull and try it later.

Best.

**Comment by spaul13** [comment]
Thanks a lot for the fix. I just pulled it and tried it. working properly.
