### ISSUE TITLE
Stopping the training programmatically in C code

### ISSUE THREAD

**Issue by androuino** [AlexeyAB/darknet#4328]
Hi, I would like to ask if there's a way I could stop the training without hitting the CTRL+C on the keyboard and instead do it programmatically using C code. I hope you could share some code for me to get it started. Thanks guys...

**Comment by AlexeyAB** [comment]
Just do `break;` between these 2 lines: https://github.com/AlexeyAB/darknet/blob/10c40551dcadec68050befa6a1cecc6f69049d0d/src/detector.c#L318-L319

**Comment by AGrosserHH** [comment]
Is there any opportunity to do early stopping in C? E.g. if there is no improvement from one step to another with a difference smaller than 0.001.

**Comment by marcheseV** [comment]
@AlexeyAB could you please explain how adding a `break` statement would enable early stopping.

> 
> 
> Just do `break;` between these 2 lines:
> 
> https://github.com/AlexeyAB/darknet/blob/10c40551dcadec68050befa6a1cecc6f69049d0d/src/detector.c#L318-L319

**Comment by sealedtx** [comment]
@marcheseV that `break` will exit main training loop:
https://github.com/AlexeyAB/darknet/blob/10c40551dcadec68050befa6a1cecc6f69049d0d/src/detector.c#L165
just implement your own logic to check if you need to stop training loop:

```
while (get_current_batch(net) < net.max_batches) {
    # trainin code
    # .....
    free_data(train);

    # e.g of early stopping code:
    int improvement = prev_loss - loss;
    if (improvement < 0.001) {
        break;
    }
}
```

**Comment by androuino** [comment]
Hi, @sealedtx, thanks for the response, however, that's the exact same method that am using, am putting the break at the end of while loop after freeing what the code needs to free before I stop or get out of the loop but it causing me some memory corruption but I already fixed it. Thanks for the help. Am gonna close this issue now.
