### ISSUE TITLE
How to show one label only even though it detects all the objects

### ISSUE THREAD

**Issue by rezaabdullah** [AlexeyAB/darknet#433]
Hi AlexeyAB,

How to show only one label? Let's say for example, 
I am using tiny-yolo model which detects 20 object classes. However instead of showing bounding box i.e. labels for all the object classes, is it possible to show only one object class? Let's say a picture contains Persons, dog, bicycle and cars. Once done it only shows bounding box for the person although it detects all the other objects.

**Comment by TheMikeyR** [comment]
Not sure if this will solve your issue but check it out https://github.com/AlexeyAB/darknet/issues/385#issuecomment-366102993

**Comment by AlexeyAB** [comment]
@rezaabdullah 

Also the simplest way is to do these changes, if you want to detect persons only:
1. Change this line: https://github.com/AlexeyAB/darknet/blob/100d6f78011f0a773442411e2882a0203d390585/src/image.c#L193
2. And this line: https://github.com/AlexeyAB/darknet/blob/100d6f78011f0a773442411e2882a0203d390585/src/image.c#L251

* to this `if (prob > thresh && class_id == 14) {` if you use yolo-voc.weights (14 is number of line in the file `voc.names` where is **person**)

* or to this `if (prob > thresh && class_id == 0) {` if you use yolo.weights (0 is number of line in the file `coco.names` where is **person**)

**Comment by VanitarNordic** [comment]
@AlexeyAB 

When we hide/show detected objects by their tracking number?

For example, in a frame we have 10 detected apples and we decides to show just number 6, and rest of the boxes should disappear.

**Comment by rezaabdullah** [comment]
Tq

________________________________
