### ISSUE TITLE
Writing Text onto the video with detected objects

### ISSUE THREAD

**Issue by Ashwin-Ramesh2607** [AlexeyAB/darknet#4330]
Hello,
Thanks for the valuable work @AlexeyAB 
I am working on a code to count the number of people in each frame of the video. I have retrained yolov3 to detect only people and the model is doing pretty good. The last functionality i need is to write the person count onto the video using cv2.putText (or some other approach). I am unable to locate the appropriate location to add this code snippet. Please Help!

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet/blob/10c40551dcadec68050befa6a1cecc6f69049d0d/src/image_opencv.cpp#L864

**Comment by Ashwin-Ramesh2607** [comment]
@AlexeyAB thanks, i was able to modify the code
However, there is another small issue. I have been able to add the head count onto the video using cv::putText. However, the count of people is changing so fast, that the number is just a blur (numbers being super imposed on top of each other). This make it impossible to read the number. Could u help me with where i might be going wrong?
![Screenshot from 2019-11-20 10-51-48](https://user-images.githubusercontent.com/51472801/69211357-d88d9480-0b83-11ea-8089-a058f4e93c17.png)
![Screenshot from 2019-11-20 10-52-09](https://user-images.githubusercontent.com/51472801/69211358-d9262b00-0b83-11ea-9155-6fbe54909ff2.png)

**Comment by aditya-droid** [comment]
There's a simple tweak you can for this. Check the number of detections in each frame. If there is a change in number persons detected, update the headcount otherwise use the headcount from the previous frame. 

Also, are you going to track the total number of persons through the entire video?

**Comment by Ashwin-Ramesh2607** [comment]
Thanks @aditya-droid , I have solved the issue.
I had actually added the cv.putText code inside a for loop, due to which it was writing (1,2,3,...) on top of each other. Placing it outside the for loop block had solved it.
