### ISSUE TITLE
Improving detection for same object shape and size but with different colors?

### ISSUE THREAD

**Issue by ycelik** [AlexeyAB/darknet#4331]
Hello guys, I wish you all a wonderful day :blush:

I'm currently working on a model to identify circles with different fill colors. They look like this:

[![brown.png](https://i.postimg.cc/Dy8kc1Pt/brown.png)](https://postimg.cc/RN5DS68R)
[![black.png](https://i.postimg.cc/FR4NW1H0/black.png)](https://postimg.cc/McdCX6RG)
[![orange.png](https://i.postimg.cc/c42qk6D6/orange.png)](https://postimg.cc/zVCPVDY1)

Unfortunately they are sometimes very blurred with different oppacity and look almost identical like brown and orange like in this example:
[![brown-blurred.png](https://i.postimg.cc/pdNHry83/brown-blurred.png)](https://postimg.cc/ZWLgDbwL)
[![black-blurred.png](https://i.postimg.cc/4NSZCW3f/black-blurred.png)](https://postimg.cc/56LDLqvT)
[![orange-blurred.png](https://i.postimg.cc/QMprTsJC/orange-blurred.png)](https://postimg.cc/wtTrCCPY)

The circles are almost the same size but can be occupied by other shapes like triangles crosses or other colored circles.

I'm here to ask you guys for tips to get the ideal detection results (cfg, train set size, train set images) etc. Any recommendation and idea is welcome. I also asked this question which is directly related to this issue: #4316

Thank you very much for your time and effort!

edit: I'm using the same labels for brown and blurred brown or orange and blurred orange. I could use different labels for them if it helps for the training and detection that wouldn't be a problem. Is that a good idea tho?

**Comment by ycelik** [comment]
@AlexeyAB Do you have any tips for me? Should I use different labels for the blurred and normal colors? Are there any cfg changes that would improve detection?

**Comment by AlexeyAB** [comment]
> I'm using the same labels for brown and blurred brown or orange and blurred orange. 

* this is ok.

* set `hue=0.01` in cfg-file

**Comment by ycelik** [comment]
> > I'm using the same labels for brown and blurred brown or orange and blurred orange.
> 
> * this is ok.
> * set `hue=0.01` in cfg-file

Thank you @AlexeyAB the detection improved indead but still it detects brown and orange as orange if it is blurred. On non blurred images I feel like it can distinguish the colors much better with hue=0.01. Any further tips? Do I just need more training examples? Any ideas are welcome.

**Comment by AlexeyAB** [comment]
Use 

saturation = 1.05
exposure = 1.3
hue=.01
