### ISSUE TITLE
Bug with inference optimization?

### ISSUE THREAD

**Issue by sealedtx** [AlexeyAB/darknet#4338]
Hi @AlexeyAB, thank you for great optimization of video memory consumption! I have question, when I load network with batch 0, i expect network to be intited for detection only, and when batch > 0 - for training. But this lines of code seems to do different?
https://github.com/AlexeyAB/darknet/blob/10c40551dcadec68050befa6a1cecc6f69049d0d/src/parser.c#L977-L978 
Why training is disabled if batch > 0?

**Comment by AlexeyAB** [comment]
> Why training is disabled if batch > 0?

* if you use parse_network_cfg_custom(batch>1) then it uses batch that you pass to the function and training is disabled

* if you use parse_network_cfg_custom(batch==0) then it uses batch from cfg-file and training is enabled

**Comment by sealedtx** [comment]
Thank you, it was not clear at first look

**Comment by AlexeyAB** [comment]
Yes, may be I will add additional param
`network parse_network_cfg_custom(char *filename, int batch, int time_steps, int train)`
