### ISSUE TITLE
How do we print mAP, FN/FP and loss?

### ISSUE THREAD

**Issue by joehoeller** [AlexeyAB/darknet#4339]
How do we print mAP, FN/FP and loss?

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet#when-should-i-stop-training


darknet.exe detector map data/obj.data yolo-obj.cfg backup\yolo-obj_9000.weights

darknet.exe detector train data/obj.data yolo-obj.cfg darknet53.conv.74 -map

**Comment by joehoeller** [comment]
Ok my command needs to look something like this, bc I am using yolo-spp:

```./darknet detector test cfg/coco.data cfg/yolov3-spp.cfg weights/yolov3-spp.weights```

Also, how do I output a batch of images w/ bounding boxes along with mAP?

**Comment by joehoeller** [comment]
@AlexeyAB - plz see above, i am not sure how to make it work with yolov3-spp.

**Comment by AlexeyAB** [comment]
You should get MS COCO dataset by using: https://github.com/AlexeyAB/darknet#datasets
Then you should specify correct path in `coco.data` file to the train and valid datasets
in my case:
```
classes= 80
train  = E:/MSCOCO/trainvalno5k.txt
valid  = E:/MSCOCO/5k.txt
names = data/coco.names
backup = backup
eval=coco
```

**Comment by joehoeller** [comment]
Thank you, I will try this.

**Comment by joehoeller** [comment]
Thank you for that, it worked fine up until it got to these text files under ```/labels/val2014/COCO``:

```

Can't open label file. (This can be normal only if you use MSCOCO): /labels/val2014/COCO_val2014_000000316400.txt 

```

**Which contain this data:**
```
0 0.055220 0.651230 0.107080 0.689037 
0 0.068920 0.582019 0.137840 0.835963 
23 0.349740 0.648984 0.371480 0.675615 
23 0.761480 0.572072 0.256080 0.439171 
```

**Comment by joehoeller** [comment]
Btw... I supported this project via sponsor link on PayPal.

**Comment by joehoeller** [comment]
Please close this out. I have gone to a diff Yolo/COCO solution.

**Comment by AlexeyAB** [comment]
> i am on linux, obviously

Run on your custom dataset:

`./darknet detector train data/obj.data yolo-obj.cfg darknet53.conv.74 -map`


> Can't open label file. (This can be normal only if you use MSCOCO): /labels/val2014/COCO_val2014_000000581899.txt 

Find files like `COCO_val2014_000000581899.txt` and put them to the directory:
`/labels/val2014/`
