### ISSUE TITLE
This is a problem question after building with cudnn 7.0 or 7.1.

### ISSUE THREAD

**Issue by mck0225** [AlexeyAB/darknet#434]
The following problems were encountered when building using cuDNN 7.0.

Could not load "cfg" file due to divideByZeroException in cudnnGetConvolutionBackwardFilterWorkspaceSize when initializing via yolo_cpp_dll.

There is no problem when using cuDNN 5.1.
Are there any cautions when building with cuDNN 7.0?

**Comment by AlexeyAB** [comment]
@mck0225 Check that you are using the cuDNN that corresponds to your CUDA-version.

I successfully compiled and used `yolo_cpp_dll.sln` with CUDA 9.1 (`cuda_9.1.85_windows.exe`) and cuDNN v7.0.5 (Dec 11, 2017), for CUDA 9.1: https://developer.nvidia.com/rdp/cudnn-download

* What CUDA version did you use for cuDNN 5.1?
* What CUDA version did you use for cuDNN 7.0
