### ISSUE TITLE
Reason for choosing the maxpool (size = 2, stride=1) in yolov3-tiny?

### ISSUE THREAD

**Issue by Sudhakar17** [AlexeyAB/darknet#4351]
@AlexeyAB : Max Pool is for reducing the feature map size but if we choose stride=1, it retains the same size. I am talking about the final maxpool layer of yolov3-tiny. Is there any purpose for this operation?

https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov3-tiny.cfg#L93

**Comment by AlexeyAB** [comment]
* `stride=2` in any layer (maxpool, convolutional, reorg, ...) is for reducing the feature map size
* `[maxpool]` layer is for reducing the spatial dependence of features (it doesn’t matter which of the 4 cells contains the maximum feature) - this allows you to detect compressed / stretched / elastic / slightly rotated objects


You are about - it gives +~2-4 mAP points: https://github.com/AlexeyAB/darknet/blob/ba6c35ac8965cd70804020fb4810133b3d32a5ad/cfg/yolov3-tiny.cfg#L93-L95

This is a smaller version of SPP-block: 
You can read about Spatial Pyramid Pooling: https://arxiv.org/abs/1406.4729v4

https://github.com/AlexeyAB/darknet/blob/ba6c35ac8965cd70804020fb4810133b3d32a5ad/cfg/yolov3-spp.cfg#L575-L597

![52151356-e5d4a380-2683-11e9-9d7d-ac7bc192c477](https://user-images.githubusercontent.com/4096485/69357948-19c29900-0c97-11ea-9de7-6add67106def.jpg)
