### ISSUE TITLE
difference between partial and -clear command

### ISSUE THREAD

**Issue by M-Younus** [AlexeyAB/darknet#4353]
What is the difference between partial and -clear command?

**Comment by M-Younus** [comment]
@AlexeyAB can you please help.Thanks

**Comment by AlexeyAB** [comment]
Partial takes weights from the first N layers.
-clear - just sets `iterations_counter=0`

**Comment by M-Younus** [comment]
> iterations_counter

right,thank you for reply.So please can you more elaborate effect of iterations_counter.

**Comment by AlexeyAB** [comment]
Just if in your cfg-file there is max_batch=10000 and weights is already trained 10000 iteration, then you can't train more.
Increase max_batches or use -clear flag.

**Comment by M-Younus** [comment]
> Just if in your cfg-file there is max_batch=10000 and weights is already trained 10000 iteration, then you can't train more.
> Increase max_batches or use -clear flag.
got it,Thanks you :)
