### ISSUE TITLE
How to use pan2_structure in yolov3 not yolov3 tiny?

### ISSUE THREAD

**Issue by Chenmi08** [AlexeyAB/darknet#4365]
I have tried to use pan2_structure in yolov3, but it failed, gives me an error, CUDA Error Prev: an illegal memory access was encountered. Here are the Network structure, I just add the pan2_structure.
layer   filters  size/strd(dil)      input                output
   0 conv     32       3 x 3/ 1    416 x 416 x   3 ->  416 x 416 x  32 0.299 BF
   1 conv     64       3 x 3/ 2    416 x 416 x  32 ->  208 x 208 x  64 1.595 BF
   2 conv     32       1 x 1/ 1    208 x 208 x  64 ->  208 x 208 x  32 0.177 BF
   3 conv     64       3 x 3/ 1    208 x 208 x  32 ->  208 x 208 x  64 1.595 BF
   4 Shortcut Layer: 1
   5 conv    128       3 x 3/ 2    208 x 208 x  64 ->  104 x 104 x 128 1.595 BF
   6 conv     64       1 x 1/ 1    104 x 104 x 128 ->  104 x 104 x  64 0.177 BF
   7 conv    128       3 x 3/ 1    104 x 104 x  64 ->  104 x 104 x 128 1.595 BF
   8 Shortcut Layer: 5
   9 conv     64       1 x 1/ 1    104 x 104 x 128 ->  104 x 104 x  64 0.177 BF
  10 conv    128       3 x 3/ 1    104 x 104 x  64 ->  104 x 104 x 128 1.595 BF
  11 Shortcut Layer: 8
  12 conv    256       3 x 3/ 2    104 x 104 x 128 ->   52 x  52 x 256 1.595 BF
  13 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
  14 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
  15 Shortcut Layer: 12
  16 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
  17 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
  18 Shortcut Layer: 15
  19 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
  20 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
  21 Shortcut Layer: 18
  22 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
  23 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
  24 Shortcut Layer: 21
  25 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
  26 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
  27 Shortcut Layer: 24
  28 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
  29 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
  30 Shortcut Layer: 27
  31 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
  32 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
  33 Shortcut Layer: 30
  34 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
  35 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
  36 Shortcut Layer: 33
  37 conv    512       3 x 3/ 2     52 x  52 x 256 ->   26 x  26 x 512 1.595 BF
  38 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  39 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  40 Shortcut Layer: 37
  41 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  42 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  43 Shortcut Layer: 40
  44 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  45 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  46 Shortcut Layer: 43
  47 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  48 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  49 Shortcut Layer: 46
  50 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  51 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  52 Shortcut Layer: 49
  53 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  54 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  55 Shortcut Layer: 52
  56 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  57 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  58 Shortcut Layer: 55
  59 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  60 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  61 Shortcut Layer: 58
  62 conv   1024       3 x 3/ 2     26 x  26 x 512 ->   13 x  13 x1024 1.595 BF
  63 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF
  64 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  65 Shortcut Layer: 62
  66 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF
  67 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  68 Shortcut Layer: 65
  69 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF
  70 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  71 Shortcut Layer: 68
  72 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF
  73 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  74 Shortcut Layer: 71
  75 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF
  76 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  77 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF
  78 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  79 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF
  80 upsample                 2x    13 x  13 x 512 ->   26 x  26 x 512
  81 route  80 61
  82 conv    256       1 x 1/ 1     26 x  26 x1024 ->   26 x  26 x 256 0.354 BF
  83 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  84 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  85 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  86 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  87 upsample                 2x    26 x  26 x 256 ->   52 x  52 x 256
  88 route  87 36
  89 conv    128       1 x 1/ 1     52 x  52 x 512 ->   52 x  52 x 128 0.354 BF
  90 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
  91 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
  92 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
  93 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
  94 route  1
  95 max               16x16/16    208 x 208 x  64 ->   13 x  13 x  64 0.003 BF
  96 conv     64       1 x 1/ 1     13 x  13 x  64 ->   13 x  13 x  64 0.001 BF
  97 route  5
  98 max                8x 8/ 8    104 x 104 x 128 ->   13 x  13 x 128 0.001 BF
  99 conv     64       1 x 1/ 1     13 x  13 x 128 ->   13 x  13 x  64 0.003 BF
 100 route  5
 101 max               8x 8/ 4x 8  104 x 104 x 128 ->   26 x  13 x 128 0.003 BF
 102 conv     64       1x 1/ 2x 1   26 x  13 x 128 ->   13 x  13 x  64 0.003 BF
 103 route  5
 104 max               8x 8/ 8x 4  104 x 104 x 128 ->   13 x  26 x 128 0.003 BF
 105 conv     64       1x 1/ 1x 2   13 x  26 x 128 ->   13 x  13 x  64 0.003 BF
 106 route  12
 107 max                4x 4/ 4     52 x  52 x 256 ->   13 x  13 x 256 0.001 BF
 108 conv     64       1 x 1/ 1     13 x  13 x 256 ->   13 x  13 x  64 0.006 BF
 109 route  12
 110 max               4x 4/ 2x 4   52 x  52 x 256 ->   26 x  13 x 256 0.001 BF
 111 conv     64       1x 1/ 2x 1   26 x  13 x 256 ->   13 x  13 x  64 0.006 BF
 112 route  12
 113 max               4x 4/ 4x 2   52 x  52 x 256 ->   13 x  26 x 256 0.001 BF
 114 conv     64       1x 1/ 1x 2   13 x  26 x 256 ->   13 x  13 x  64 0.006 BF
 115 route  64
 116 conv     64       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x  64 0.022 BF
 117 route  116 114 111 108 105 102 99 96
 118 max-depth          1x 1/ 1     13 x  13 x 512 ->   13 x  13 x  64 0.000 BF
 119 upsample                 4x    13 x  13 x  64 ->   52 x  52 x  64
 120 route  119 93
 121 conv    256       3 x 3/ 1     52 x  52 x 192 ->   52 x  52 x 256 2.392 BF
 122 conv     24       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x  24 0.033 BF
 123 yolo
[yolo] params: iou loss: giou, iou_norm: 0.50, cls_norm: 1.00, scale_x_y: 1.00
 124 route  118
 125 upsample                 2x    13 x  13 x  64 ->   26 x  26 x  64
 126 route  125 86
 127 conv    512       3 x 3/ 1     26 x  26 x 320 ->   26 x  26 x 512 1.994 BF
 128 conv     24       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x  24 0.017 BF
 129 yolo
[yolo] params: iou loss: giou, iou_norm: 0.50, cls_norm: 1.00, scale_x_y: 1.00
 130 route  118
 131 route  130 79
 132 conv   1024       3 x 3/ 1     13 x  13 x 576 ->   13 x  13 x1024 1.794 BF
 133 conv     24       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x  24 0.008 BF
 134 yolo
[yolo] params: iou loss: giou, iou_norm: 0.50, cls_norm: 1.00, scale_x_y: 1.00
Total BFLOPS 66.850 
 Allocate additional workspace_size = 58.99 MB 
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
 If error occurs - run training with flag: -dont_show 
Resizing
608 x 608 
 try to allocate additional workspace_size = 58.99 MB 
 CUDA allocate done! 
Loaded: 0.000041 seconds
CUDA Error Prev: an illegal memory access was encountered
CUDA Error Prev: an illegal memory access was encountered: Resource temporarily unavailable
darknet: ./src/utils.c:293: error: Assertion `0' failed.
Aborted (core dumped)

**Comment by AlexeyAB** [comment]
Try to set random=0 in the last yolo-layer
