### ISSUE TITLE
after change darknet.py to use opencv,but speed slower than  original ?  

### ISSUE THREAD

**Issue by ericwang321** [AlexeyAB/darknet#4367]
**1. os environment:**

ubuntu 18.04 64bit  i3+4G
darknet Make file:
GPU=0
CUDNN=0
CUDNN_HALF=0
OPENCV=1
AVX=1
OPENMP=1
LIBSO=1
use python2.7.15/gcc 7.4 

**2.question** 

After **changing the darknet.py file** according to the instructions in the file, **_to enable the opencv_** function,when run command _**time python darknet.py,**_

**_The result_** appears about 5 seconds _**slower than running the original darknet.py file.**_

What is the cause of the slowness, _**is there a problem with the change?**_
**Thanks for any suggestion.** 

**3. below is  the changes .**

https://github.com/AlexeyAB/darknet/blob/3abbd858084c9f3634a30307f36a0d23303796b6/darknet.py#L240-L242
```
--> #im = load_image(image, 0, 0)
--> ret = detect_image(net, meta, image, thresh, hier_thresh, nms, debug)
-->#free_image(im)
```

https://github.com/AlexeyAB/darknet/blob/3abbd858084c9f3634a30307f36a0d23303796b6/darknet.py#L247-L254
```
    def detect_image(net, meta, im, thresh=.5, hier_thresh=.5, nms=.45, debug= False): 
-->def detect_image(net, meta, image, thresh=.5, hier_thresh=.5, nms=.45, debug= False): 
--> comment L247 to L254 
```

https://github.com/AlexeyAB/darknet/blob/3abbd858084c9f3634a30307f36a0d23303796b6/darknet.py#L261-L262
```
-->predict_image_letterbox(net, im)
--> letter_box = 1
```

https://github.com/AlexeyAB/darknet/blob/3abbd858084c9f3634a30307f36a0d23303796b6/darknet.py#L264-L265
`-->comment L264，use L265`

https://github.com/AlexeyAB/darknet/blob/3abbd858084c9f3634a30307f36a0d23303796b6/darknet.py#L390-L391
`-->comment L390，use L391`

**Comment by AlexeyAB** [comment]
Can you attach your changed darknet.py ?

**Comment by ericwang321** [comment]
Slow 5 seconds is my problem, there is _no comment following the statement._

https://github.com/AlexeyAB/darknet/blob/3abbd858084c9f3634a30307f36a0d23303796b6/darknet.py#L259
**_After the change,  many comparisons. it is about 0.2 ~3 seconds slow,very unstable.
_** **_Is this normal?_**
![2](https://user-images.githubusercontent.com/25045112/69515545-df544700-0f89-11ea-9136-9ad854d5ff9c.png)
**_The attachment is a modified version of darknet opecv._**
（In order to meet the upload requirements, the extension py is changed to log）

[darknet.opencv11.log](https://github.com/AlexeyAB/darknet/files/3884992/darknet.opencv11.log)

**Comment by AlexeyAB** [comment]
```python
##################################################2019-11 change  detect image im to image
    import cv2
    custom_image_bgr = cv2.imread(image) # use: detect(,,imagePath,)
    custom_image = cv2.cvtColor(custom_image_bgr, cv2.COLOR_BGR2RGB)
    custom_image = cv2.resize(custom_image,(lib.network_width(net), lib.network_height(net)), interpolation = cv2.INTER_LINEAR)
    import scipy.misc
    custom_image = scipy.misc.imread(image)
    im, arr = array_to_image(custom_image)		# you should comment line below: free_image(im)
    num = c_int(0)
    if debug: print("Assigned num")
    pnum = pointer(num)
    if debug: print("Assigned pnum")
    #predict_image(net, im)
    #letter_box = 0
     ##################################################2019-11  comment
    predict_image_letterbox(net, im)
    letter_box = 1
    if debug: print("did prediction")
    dets = get_network_boxes(net, custom_image_bgr.shape[1], custom_image_bgr.shape[0], thresh, hier_thresh, None, 0, pnum, letter_box) # OpenCV
```

Why do you load the same image twice?

Use only OpenCV or SCIPY. But not both together.

There are 3 ways to load image:
* Darknet
* OpenCV
* scipy

Use only 1 of 3.

**Comment by ericwang321** [comment]
Thank you for your patience.

After the correction, the result shows the processing speed, opencv and the original file is no different.
