### ISSUE TITLE
Average Precision in training not going below 10

### ISSUE THREAD

**Issue by ahsan856jalal** [AlexeyAB/darknet#437]
Hello everyone,
I trained yolo with coco+cityscapes dataset. After 240,000 iterations, avg_error was still above 10. 
Rough estimate for the total number of iterations was (2000*92=184,000) . Did anyone perform training on COCO dataset? How many iterations it will take to reach the avg_error of ~ 0.06

**Comment by ahsan856jalal** [comment]
I am using this command
./darknet detector train data/obj.data cfg/file.cfg pre_trained.backup -gpus 0,1,2

**Comment by AlexeyAB** [comment]
@ahsan856jalal Hi,

MS COCO dataset is more difficult than Pascal VOC, so it will be harder to train. May be you will not reach 0.06 avg_error.

* Do you use this fork or original repo?

* Did you base your cfg-file on `yolo.2.0.cfg` or `yolo.cfg`, not on yolo-voc.2.0.cfg?

* Did you train frist 1000 iterations using only 1 GPU? https://github.com/AlexeyAB/darknet#how-to-train-with-multi-gpu

* How did you get your pre-trained weights `pre_trained.backup`?

* What mAP and IoU can your get using ./darknet detector map data/obj.data cfg/file.cfg file.weights  ?

* Also you can try to change this line: https://github.com/AlexeyAB/darknet/blob/880cf187d87c904f5fe574802ecff99118643f2d/src/detector.c#L91
to `args.type = REGION_DATA;`

Or you can try to train using: `./darknet coco train data/obj.data cfg/file.cfg pre_trained.backup` - but it doesn't support multi-gpu

**Comment by ahsan856jalal** [comment]
@AlexeyAB 
I was sick so couldn't reply earlier but thanks for the feedback

1.  Yes, I used the original repo of pjreddie but now I will try yours
2. I used yolo-voc.2.0.cfg
3. No I did it on Multiple GPUs
4. Currently I am working on fish classification so I pre-trained a fish detector and then extracted its first 23 layers as  pre-trained weight to fish classification training
5. I guess detector map is not in pjreddie's repo
6. I will clone your repo and do this REGION_DATA change and re-train the model
Once I am done with these changes, I will let you know about any change in the performance.
Thanks

**Comment by AlexeyAB** [comment]
> avg_error reduces to ~1 in first 100 iterations (thumbs up) but meanwhile obj paramter also reduces to ~0.0001 (which is not good) 

After ~2000 iterations obj-param will increase. So just train more.

**Comment by ahsan856jalal** [comment]
You are right . At the moment
obj is increasing, no obj is decreasing and avg_error is less than 0.2.
Thank you very much. Hope this time avg_error will converge to ~0.06.

**Comment by AlexeyAB** [comment]
Just know that 0.06 is not necessary. Very much depends on the complexity of the dataset.

**Comment by ahsan856jalal** [comment]
Yes, you're right . I mean that this time it will converge to way lower value than the previous one
