### ISSUE TITLE
Setting "random=1" causes error

### ISSUE THREAD

**Issue by yinruiying** [AlexeyAB/darknet#4373]
Thanks for your hard work to update the project so quickly!
 Now it supports Gaussian-yolov3、Gaussian-yolov3+giou、Mish\Swish activation、assisted excitation.  When i set "random=0" in my cfg, these new added operations works well. But when "random=1"，it reports the following error:
![image](https://user-images.githubusercontent.com/21331073/69512814-787e6000-0f80-11ea-91a7-223ab209074a.png)

**Comment by AlexeyAB** [comment]
Did you try Darknet after this PR https://github.com/AlexeyAB/darknet/pull/4302 ?

Also it supports Gaussian-yolov3+ciou

**Comment by yinruiying** [comment]
I try it. Except “assisted excitation”, the others work well with "random=1".

**Comment by dccho** [comment]
@AlexeyAB @yinruiying 
maybe need to add below code in resize function in convolutional_layer.c

`if (l.assisted_excitation) {
    const int size = l->out_w * l->out_h * l->batch;
    cuda_free(l->gt_gpu);
    cuda_free(l->a_avg_gpu);
    l->gt_gpu = cuda_make_array(NULL, size);
    l->a_avg_gpu = cuda_make_array(NULL, size);
}`

**Comment by AlexeyAB** [comment]
@dccho @yinruiying I added such fix: https://github.com/AlexeyAB/darknet/commit/b832c727dc23e8daaf9f5a20dff6522f949b56b0
