### ISSUE TITLE
After initializing darknet by initOnly,processing time of the first picture is always greater than others pic ？

### ISSUE THREAD

**Issue by ericwang321** [AlexeyAB/darknet#4375]
### **1. os environment:**
ubuntu 18.04 64bit i3+4G
darknet Make file:
GPU=0
CUDNN=0
CUDNN_HALF=0
OPENCV=1
AVX=1
OPENMP=1
LIBSO=1
use python2.7.15/gcc 7.4
### **2.question**
 Use the original darknet.py file,After initializing darknet by initOnly= True，
 the **_processing time of the first picture_** is always **_greater than_** the processing time of the **_latter pictures_**.

- _Is it wrong to write the revised part,does this conflict with the original text?_
- Why is 【Used AVX Used FMA & AVX2】 only displayed when the first image is processed?

**Thanks for any suggestion.**

### **3. Attachment**
time result  compare and modification darknet.py
![3](https://user-images.githubusercontent.com/25045112/69518809-68bc4700-0f93-11ea-9725-8d3cdd408ac7.png)

**Comment by AlexeyAB** [comment]
There functions are called only once for the first detection: https://github.com/AlexeyAB/darknet/blob/dd4dcf20b4886f4cfedb82e6d205a93c3a4c1034/src/gemm.c#L684-L704

**Comment by ericwang321** [comment]
thanks for the reply

1. **_In the GPU environment_**, are **_these functions also called_** when image are detected **_for the first time_**?

2. If so, **_is there a way to call these functions_**      **before the first image is detected**, 
similar to initonly=true, in order to maximize the picture detection time?

**Comment by AlexeyAB** [comment]
1. No.

2. I added function `init_cpu()` to `darknet.py` https://github.com/AlexeyAB/darknet/commit/48914023da1656c5494deda77b0c683a64401ede

**Comment by ericwang321** [comment]
Thank you for your professional reply.


According to the instructions, make the following changes
https://github.com/AlexeyAB/darknet/blob/b832c727dc23e8daaf9f5a20dff6522f949b56b0/darknet.py#L386-L388

**1. Is this  below change correct?**
```
    if initOnly:
        init_cpu()
        print("Initialized detector") 
        return None
```


**2. **_Is this normal?_****

Multiple results show that the average **_processing speed of the first image_** **_is still greater than the latter images._**Is this related to low hardware configuration?


Attachment: Processing time results
![4](https://user-images.githubusercontent.com/25045112/69557541-bb245480-0fe1-11ea-9a38-4e4e59235456.png)


I  will go to the GPU environment as soon as possible.    thanks again

**Comment by ericwang321** [comment]
temp close issue.
