### ISSUE TITLE
Requirements of darknet

### ISSUE THREAD

**Issue by pranith246** [AlexeyAB/darknet#438]
Is there any way to make darknet work without visual studio and CUDA ?
I need to train a custom object detection classifier.
Any help is much appreciated.

**Comment by AlexeyAB** [comment]
* Without CUDA you can compile `darknet_no_gpu.sln` using Visual Studio.
* Without Visual Studio, what C compiler do you want to use?
* What do you want to use Detector or Classifier?

**Comment by pranith246** [comment]
Can I do it using codeblocks ?
I want to build an objector.

**Comment by pranith246** [comment]
I use windows 10 and tried installing darknet using the directions mentioned in [](https://pjreddie.com/darknet/install/) but faced problems in make.

**Comment by AlexeyAB** [comment]
codeblocks isn't compiler. You should use Visual Studio compiler on Windows.
