### ISSUE TITLE
how to convert the ‘groups’ to h5?

### ISSUE THREAD

**Issue by xautzxc** [AlexeyAB/darknet#4380]
I used depthwise convolution to train a weight, how to convert this weight to keras, that is how to convert the ‘groups’ in [convert.py](https://github.com/qqwweee/keras-yolo3/blob/master/convert.py)?

eg. *.cfg
[convolutional]
groups=256
filters=256
size=3
stride=1
pad=1
batch_normalize=1
activation=leaky

**Comment by KuoEuran** [comment]
Hello, have you solved the problem about covnersion?
