### ISSUE TITLE
Best weights overwriting

### ISSUE THREAD

**Issue by WadRex** [AlexeyAB/darknet#4387]
Hello,
Is there any way of having best weights in memory after training restart?
Because as for now, every time I start the network using "last weights", it overrides the best on the first MAP check. Easiest solution would be to copy best weights in another folder, but it would be way more convenient to load them in memory aswell and overwrite only if the "new best weights" are found.

**Comment by HagegeR** [comment]
that would mean saving the accuracy of the weights within the weights themselves or in a separate file somehow
