### ISSUE TITLE
How to run YOLO on specific GPU

### ISSUE THREAD

**Issue by inafi** [AlexeyAB/darknet#4389]
I have 3 2080s and when I run yolo it always runs on the first one. However, I want to have something else running simultaneously with yolo but the gpu runs out of memory. How can I specify yolo to run with another GPU, like the second or third one instead of the first?

-CUDA 10.0
-CUDNN 7.4.2
-OpenCV - 3.2.0
-OS: Ubuntu 18.04.3 LTS

|   0  GeForce RTX 2080    Off  | 00000000:09:00.0 Off |                  N/A |
|  0%   35C    P0    48W / 215W |      0MiB /  7982MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 2080    Off  | 00000000:0A:00.0 Off |                  N/A |
|  0%   41C    P0    51W / 215W |      0MiB /  7982MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 2080    Off  | 00000000:41:00.0 Off |                  N/A |
|  0%   43C    P0    N/A /  N/A |      0MiB /  7974MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by lsd1994** [comment]
Add -gpus 1 to specify GPU 1, the default is 0.

**Comment by inafi** [comment]
Thanks for the reply, but it still runs on the same gpu. Isn't '-gpus' more geared towards training?

Here's the nvidia-smi output after running with '-gpus 1', '-gpus 2', repsectively:

| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2080    Off  | 00000000:09:00.0 Off |                  N/A |
|  0%   38C    P2    49W / 215W |   1939MiB /  7982MiB |     15%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 2080    Off  | 00000000:0A:00.0 Off |                  N/A |
|  6%   48C    P0    52W / 215W |     10MiB /  7982MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 2080    Off  | 00000000:41:00.0 Off |                  N/A |
| 10%   48C    P0    45W / 215W |     10MiB /  7974MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2080    Off  | 00000000:09:00.0 Off |                  N/A |
|  0%   39C    P2    50W / 215W |   2163MiB /  7982MiB |     21%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 2080    Off  | 00000000:0A:00.0 Off |                  N/A |
|  0%   48C    P0    52W / 215W |     10MiB /  7982MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 2080    Off  | 00000000:41:00.0 Off |                  N/A |
|  6%   49C    P0    45W / 215W |     10MiB /  7974MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by AlexeyAB** [comment]
`-i 1` for detection on GPU1
`-gpus 1,2` for training (for train on GPU1 and GPU2)

**Comment by inafi** [comment]
Thanks! This was the solution.

**Comment by QuntuamLoop** [comment]
Is there a  way setting the gpus in python API?
