### ISSUE TITLE
trying to build yolo_console_dll

### ISSUE THREAD

**Issue by Sennevds** [AlexeyAB/darknet#439]
i'm trying to build yolo_console_dll but getting following error
`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'opencv_cudaoptflow340.lib'	yolo_console_dll	C:\Users\Senne\darknet\build\darknet\LINK	1	
`
I can't find any info about this lib where can i find it?

**Comment by AlexeyAB** [comment]
@Sennevds I fixed it. Now it requires only `opencv_world340.lib` that should be in the OpenCV.

**Comment by sushant1727** [comment]
I am having the simillar issue. Even after mentioning the path explicitly it keep saying 
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'opencv_world340.lib'	darknet_no_gpu	E:\Darknet\darknet-master\build\darknet\LINK	1

**Comment by AlexeyAB** [comment]
@sushant1727 

1. Did you installed OpenCV 3.4.0? https://sourceforge.net/projects/opencvlibrary/files/opencv-win/3.4.0/opencv-3.4.0-vc14_vc15.exe/download

2. Do you have `opencv_world340.lib` in the folder `C:\opencv_3.0\opencv\build\x64\vc14\lib` ?

3. Can you show screenshot, what string do you have in the `(right click on project) -> properties -> Linker -> General -> Additional Library Directories` in the MSVS?

**Comment by sushant1727** [comment]
Thanks for the quick reply.
I was able to successfully able to build the darknet by adding path to Linker.
Now when I run the command line I get this error:- [Screenshot](https://ibb.co/hQJKOJ)

**Comment by sushant1727** [comment]
I have following paths:
In c/c++
C:\opencv\build\include\
C:\opencv\build\x64\vc14\lib\
..\..\3rdparty\include\
In linker:
C:\opencv\build\x64\vc14\lib\

**Comment by AlexeyAB** [comment]
@sushant1727 

https://github.com/AlexeyAB/darknet#how-to-compile-on-windows

> 1.1. Find files opencv_world320.dll and opencv_ffmpeg320_64.dll (or opencv_world340.dll and opencv_ffmpeg340_64.dll) in C:\opencv_3.0\opencv\build\x64\vc14\bin and put it near with darknet.exe
