### ISSUE TITLE
Image resolution matters how much?

### ISSUE THREAD

**Issue by WadRex** [AlexeyAB/darknet#4393]
Hello, 
I have a question, if we take 2 images. 1 with high resolution, e.c (416x416). 2 is downsampled to 160x160.
For the first image I use network with resolution 416. For second 160.
Will those additional details on high res image improve network? I tried with small dataset, but the difference was ~0.1. Is it the same with bigger dataset or was it only limitation with mine small dataset (5000 img).
Both networks were trained from scratch with 416 and 160 resolution.

**Comment by sealedtx** [comment]
@WadRex It is nice decision to reduce network input size if your objects on images don't lose their features (the most important ones to classify) after resize

**Comment by AlexeyAB** [comment]
> but the difference was ~0.1.

What is the difference? Confidence_score, Loss, mAP@0.5, mAP@0.5...0.95, F1, ...?

**Comment by WadRex** [comment]
> > but the difference was ~0.1.
> 
> What is the difference? Confidence_score, Loss, mAP@0.5, mAP@0.5...0.95, F1, ...?

Basically everything was almost the same, loss was fluctuating more with lower resolution, but at the end converged on the same value. IOU was higher on high res. 83 vs 80. Difference I was talking about is MAP 0.5, but I would consider it an error due to random weights initialization.
