### ISSUE TITLE
Cannot load image "-ext_output" STB Reason: can't fopen

### ISSUE THREAD

**Issue by sbind29893** [AlexeyAB/darknet#4394]
./darknet detector test darknet.data darknet-yolov3.cfg darknet-yolov3_final.weights -thresh 0.25 -ext_output -dont_show

When i am trying to run above command, it is giving me below error. Please anyone help me in this issue.

Cannot load image "-ext_output"
STB Reason: can't fopen

**Comment by AlexeyAB** [comment]
Use this code https://github.com/AlexeyAB/darknet instead of https://github.com/pjreddie/darknet

**Comment by sbind29893** [comment]
> Use this code https://github.com/AlexeyAB/darknet instead of https://github.com/pjreddie/darknet

Thank you soo much @AlexeyAB ... i got the desired output after using you given repo.
