### ISSUE TITLE
Need left_x, top_y, width, height with the class prediction. 

### ISSUE THREAD

**Issue by sbind29893** [AlexeyAB/darknet#4396]
After Running the detector i am getting below type of output. I need the second kind of output when i run my detector.
Can someone please help me in this scenario.

**CURRENT OUTPUT :**

pancards/BATCH_1_1.jpg
pancards/BATCH_1_1.jpg: Predicted in 0.260724 seconds.
Pan: 78%
Date: 46%
FathersName: 78%
Name: 82%
Pancard: 40%

**DESIRED OUTPUT :**

pancards/BATCH_1_1.jpg: Predicted in 37.062380 seconds.
Pancard: 76%	(left_x:  282   top_y:   41   width:  969   height:  662)
FathersName: 98%	(left_x:  286   top_y:  319   width:  426   height:   56)
Pan: 52%	(left_x:  299   top_y:  489   width:  260   height:   67)
Date: 84%	(left_x:  307   top_y:  396   width:  203   height:   57)
Name: 57%	(left_x:  309   top_y:  232   width:  273   height:   68)

**Comment by humbicho** [comment]
Are you running WebCam command line?
Any way, you need to add `-ext_output` at the end of the command line.
for example: `darknet.exe detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights -c 0 -ext_output`

**Comment by sbind29893** [comment]
> Are you running WebCam command line?
> Any way, you need to add `-ext_output` at the end of the command line.
> for example: `darknet.exe detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights -c 0 -ext_output`

if i add then it gives me

./darknet detector test darknet.data darknet-yolov3.cfg darknet-yolov3_final.weights -thresh 0.25 -ext_output -dont_show

When i am trying to run above command, it is giving me below error. Please anyone help me in this issue.

Cannot load image "-ext_output"
STB Reason: can't fopen

**Comment by humbicho** [comment]
Try to add the path of the image before `-ext_output`
like this: `./darknet detector test darknet.data darknet-yolov3.cfg darknet-yolov3_final.weights -thresh 0.25 "image_path" -ext_output -dont_show`

I did it that way, and works for me.

**Comment by AlexeyAB** [comment]
Use this Darknet version https://github.com/AlexeyAB/darknet instead of https://github.com/pjreddie/darknet

**Comment by sbind29893** [comment]
> Use this Darknet version https://github.com/AlexeyAB/darknet instead of https://github.com/pjreddie/darknet

Thank you soo much @AlexeyAB ... i got the desired output after using you given repo.
