### ISSUE TITLE
Segmentation fault (core dumped)!

### ISSUE THREAD

**Issue by smitshilu** [AlexeyAB/darknet#440]
Hello,
I am using original repo on my linux system. Trying to train tiny yolo model but it gives following error after some steps. Number is not consistent sometime it throws error at 2nd step some time at 40th. Can you please help me with it?

`41: 107.253304, 415.541656 avg, 0.001000 rate, 4.394401 seconds, 1312 images
Loaded: 0.000124 seconds`
`Region Avg IOU: 0.018014, Class: 1.000000, Obj: 0.002887, No Obj: 0.003492, Avg Recall: 0.000000,  count: 18`
`Region Avg IOU: 0.401208, Class: 1.000000, Obj: 0.007435, No Obj: 0.007720, Avg Recall: 0.500000,  count: 4`
`Region Avg IOU: 0.107763, Class: 1.000000, Obj: 0.003388, No Obj: 0.004642, Avg Recall: 0.142857,  count: 7`
`Segmentation fault (core dumped)`

Using following command 

`./darknet detector train data/obj.data cfg/tiny-yolo-voc-obj.cfg tiny-yolo-voc.conv.13`

**Comment by AlexeyAB** [comment]
Hi, may be something wrong with your dataset.

* Do you use OpenCV, CUDA and cuDNN? 
* What OpenCV version do you use?
* Do you get this error if you use this repo to training on Linux?

**Comment by smitshilu** [comment]
It starts training with these steps

`1: 206.234924, 206.234924 avg, 0.001000 rate, 0.910286 seconds, 12 images`
`Loaded: 0.000072 seconds`
`Region Avg IOU: 0.002696, Class: 1.000000, Obj: 0.091525, No Obj: 0.225260, Avg Recall: 0.000000,  count: 17`
`Region Avg IOU: 0.002618, Class: 1.000000, Obj: 0.264026, No Obj: 0.211167, Avg Recall: 0.000000,  count: 33`
`Region Avg IOU: 0.000733, Class: 1.000000, Obj: 0.263204, No Obj: 0.214708, Avg Recall: 0.000000,  count: 32`
`Region Avg IOU: 0.000000, Class: 1.000000, Obj: 0.147834, No Obj: 0.221345, Avg Recall: 0.000000,  count: 11`

but in last steps before it fails it shows data like this

`10: nan, nan avg, 0.001000 rate, 1.093313 seconds, 120 images`
`Resizing`
`544`
`Loaded: 0.000286 seconds`
`Region Avg IOU: 0.000000, Class: nan, Obj: 0.000000, No Obj: nan, Avg Recall: 0.000000,  count: 30`
`Region Avg IOU: 0.000000, Class: nan, Obj: nan, No Obj: nan, Avg Recall: 0.000000,  count: 20`
`Region Avg IOU: 0.000000, Class: nan, Obj: 0.000000, No Obj: nan, Avg Recall: 0.000000,  count: 20`
`Region Avg IOU: 0.000000, Class: nan, Obj: 0.000000, No Obj: nan, Avg Recall: 0.000000,  count: 23`

**Comment by smitshilu** [comment]
I tried setting these 2 but the error is similar.

**Comment by AlexeyAB** [comment]
This is trange. Try to use CUDNN=0 or use this repo. Sometimes people are faced with a problem when used CUDNN on TX2: https://github.com/AlexeyAB/darknet/issues/436
If the error still occur, then problem might be in your dataset.

**Comment by smitshilu** [comment]
It's not working either. Can you tell me how can I change batch and subdivision? Is there any relation between these 2? 

In terms of dataset I have done something like this

**obj.dat**
`classes=0`
`train  = data/train.txt`
`valid  = data/test.txt`
`names = data/obj.names`
`backup = backup/`


**train.txt file contains**
`data/obj/img1.jpg`
`data/obj/img2.jpg`
`data/obj/img3.jpg`
              .
              .
`data/obj/img500.jpg`


**cfg file**
`[convolutional]`
`filters=30`

`[region]`
`classes=1`


**img1.txt** 
`0  0.66  0.5  0.3  0.2`


**obj.names**
`face`

**Comment by AlexeyAB** [comment]
Everything looks correct, except for 

> obj.dat
> classes=0

There should be `classes=1`

----

Did you get your img1.txt using Yolo_mark tool? https://github.com/AlexeyAB/Yolo_mark

----

Your can try to change batch and subdivision in your cfg-file: https://github.com/AlexeyAB/darknet/blob/880cf187d87c904f5fe574802ecff99118643f2d/cfg/yolo-voc.2.0.cfg#L2-L3

Memory consumption proportionally ~= batch/subdivision

**Comment by smitshilu** [comment]
I have not used Yolo_mark tool. I had all of my coordinates so I just converted it to text file.

**Comment by AlexeyAB** [comment]
You should check that each your `imgX.txt` file contains correct values `0< x,y,w,h <1 or ` and `x+w < 1` , `y+w < 1`
Also that no one `imgX.txt` file contains empty extra lines.

**Comment by smitshilu** [comment]
Just to make sure 
X and Y here are top left co-ordinates relative to width and height OR rectangle center point relative to width and height?
I mean is it 
"top left x"/width , "top left y"/height 
OR
"rectangle center x"/width , "rectangle center y"/height?

and W and H are rectangle size relative to width and height.

**Comment by AlexeyAB** [comment]
>"rectangle center x"/width , "rectangle center y"/height?
Yes, x, y is center of object relative to image size. I fixed answer.

**Comment by smitshilu** [comment]
Hello,
I managed to run training (in Mac book with 1080ti). But now it is saving weights till 900 only. Can you please let me know how to change that?

Thank you

**Comment by AlexeyAB** [comment]
@smitshilu Change this line: https://github.com/pjreddie/darknet/blob/80d9bec20f0a44ab07616215c6eadb2d633492fe/examples/detector.c#L136
to this `if( i%100 == 0 ){`

Or use this fork: https://github.com/AlexeyAB/darknet

**Comment by smitshilu** [comment]
I think the reason behind the segmentation fault or Bus error is big data. I tried using almost 3000, 2000, 1000 and 500 images but I got error. When I tried with 50 it worked and ran for around 6000 steps. I am now using MacBook with 12GB NVIDIA GTX 1080Ti and facing same problem.

**Comment by smitshilu** [comment]
Is there any solution to this problem? What to do if I want to train on 3000 images??

**Comment by AlexeyAB** [comment]
I train with 10 000 and 40 000 images, and it works well. 

1. Try to do `./darknet detector recall data/obj.data yolo-obj.cfg backup\yolo-obj_7000.weights` for your data, cfg and weights files, when train.txt file contains all 3000 images. Will it work out to the end successfully?

2. What CUDA and cuDNN versions do you use?

**Comment by smitshilu** [comment]
I am using CUDA 9 and cuDNN 7 and running that command gives me this error:

Smit-Shilu:darknet smitshilu$ ./darknet detector recall data/faces.data cfg/tiny-yolo-voc-faces.cfg backup/tiny-yolo-voc-faces_10000.weights 
layer     filters    size              input                output
    0 conv     16  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  16
    1 max          2 x 2 / 2   416 x 416 x  16   ->   208 x 208 x  16
    2 conv     32  3 x 3 / 1   208 x 208 x  16   ->   208 x 208 x  32
    3 max          2 x 2 / 2   208 x 208 x  32   ->   104 x 104 x  32
    4 conv     64  3 x 3 / 1   104 x 104 x  32   ->   104 x 104 x  64
    5 max          2 x 2 / 2   104 x 104 x  64   ->    52 x  52 x  64
    6 conv    128  3 x 3 / 1    52 x  52 x  64   ->    52 x  52 x 128
    7 max          2 x 2 / 2    52 x  52 x 128   ->    26 x  26 x 128
    8 conv    256  3 x 3 / 1    26 x  26 x 128   ->    26 x  26 x 256
    9 max          2 x 2 / 2    26 x  26 x 256   ->    13 x  13 x 256
   10 conv    512  3 x 3 / 1    13 x  13 x 256   ->    13 x  13 x 512
   11 max          2 x 2 / 1    13 x  13 x 512   ->    13 x  13 x 512
   12 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   13 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   14 conv     30  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x  30
   15 detection
mask_scale: Using default '1.000000'
Loading weights from backup/tiny-yolo-voc-faces_10000.weights...Done!
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Couldn't open file: data/coco_val_5k.list

**Comment by smitshilu** [comment]
Downloading coco fails with following errors

Smit-Shilu:darknet smitshilu$ sudo ./scripts/get_coco_dataset.sh 
fatal: destination path 'coco' already exists and is not an empty directory.
mkdir: images: File exists
--2018-03-15 08:57:02--  https://pjreddie.com/media/files/train2014.zip
Resolving pjreddie.com... 128.208.3.39
Connecting to pjreddie.com|128.208.3.39|:443... connected.
ERROR: cannot verify pjreddie.com's certificate, issued by 'CN=Let\'s Encrypt Authority X3,O=Let\'s Encrypt,C=US':
  Issued certificate has expired.
To connect to pjreddie.com insecurely, use `--no-check-certificate'.
--2018-03-15 08:57:02--  https://pjreddie.com/media/files/val2014.zip
Resolving pjreddie.com... 128.208.3.39
Connecting to pjreddie.com|128.208.3.39|:443... connected.
ERROR: cannot verify pjreddie.com's certificate, issued by 'CN=Let\'s Encrypt Authority X3,O=Let\'s Encrypt,C=US':
  Issued certificate has expired.
To connect to pjreddie.com insecurely, use `--no-check-certificate'.
unzip:  cannot find or open train2014.zip, train2014.zip.zip or train2014.zip.ZIP.
unzip:  cannot find or open val2014.zip, val2014.zip.zip or val2014.zip.ZIP.
--2018-03-15 08:57:03--  https://pjreddie.com/media/files/instances_train-val2014.zip
Resolving pjreddie.com... 128.208.3.39
Connecting to pjreddie.com|128.208.3.39|:443... connected.
ERROR: cannot verify pjreddie.com's certificate, issued by 'CN=Let\'s Encrypt Authority X3,O=Let\'s Encrypt,C=US':
  Issued certificate has expired.
To connect to pjreddie.com insecurely, use `--no-check-certificate'.
--2018-03-15 08:57:03--  https://pjreddie.com/media/files/coco/5k.part
Resolving pjreddie.com... 128.208.3.39
Connecting to pjreddie.com|128.208.3.39|:443... connected.
ERROR: cannot verify pjreddie.com's certificate, issued by 'CN=Let\'s Encrypt Authority X3,O=Let\'s Encrypt,C=US':
  Issued certificate has expired.
To connect to pjreddie.com insecurely, use `--no-check-certificate'.
--2018-03-15 08:57:03--  https://pjreddie.com/media/files/coco/trainvalno5k.part
Resolving pjreddie.com... 128.208.3.39
Connecting to pjreddie.com|128.208.3.39|:443... connected.
ERROR: cannot verify pjreddie.com's certificate, issued by 'CN=Let\'s Encrypt Authority X3,O=Let\'s Encrypt,C=US':
  Issued certificate has expired.
To connect to pjreddie.com insecurely, use `--no-check-certificate'.
--2018-03-15 08:57:04--  https://pjreddie.com/media/files/coco/labels.tgz
Resolving pjreddie.com... 128.208.3.39
Connecting to pjreddie.com|128.208.3.39|:443... connected.
ERROR: cannot verify pjreddie.com's certificate, issued by 'CN=Let\'s Encrypt Authority X3,O=Let\'s Encrypt,C=US':
  Issued certificate has expired.
To connect to pjreddie.com insecurely, use `--no-check-certificate'.
tar: Error opening archive: Failed to open 'labels.tgz'
unzip:  cannot find or open instances_train-val2014.zip, instances_train-val2014.zip.zip or instances_train-val2014.zip.ZIP.
./scripts/get_coco_dataset.sh: line 29: 5k.part: No such file or directory
paste: 5k.part: No such file or directory
./scripts/get_coco_dataset.sh: line 30: trainvalno5k.part: No such file or directory
paste: trainvalno5k.part: No such file or directory

**Comment by smitshilu** [comment]
1. Yes it work out successfully.
2. I am using CUDA 9 and cuDNN 7

**Comment by AlexeyAB** [comment]
Try to use my repository: https://github.com/AlexeyAB/darknet
Is there a segmentation error during training?

**Comment by smitshilu** [comment]
Yes on Linux I am getting Segmentation Fault

**Comment by AlexeyAB** [comment]
This is very strange. Probably something wrong with CUDA, cuDNN or nVidia GPU driver.

**Comment by smitshilu** [comment]
I used your repo and getting same error.

**Comment by smitshilu** [comment]
That issue is still there but when I trained with your repo I got results in 400 epocs only. Thank you very much for this repo and all the help. If you can please help me with training with more data as this model is not much accurate

**Comment by smitshilu** [comment]
Thank you for all the help. I found the problem there were 3 photos with bounding box as 0 0 0 0. It was creating problem.
