### ISSUE TITLE
Weights and cfg did not work on darknet.js (trained on your repo)

### ISSUE THREAD

**Issue by josebenitezg** [AlexeyAB/darknet#4401]
Hi @AlexeyAB ,
I trying to compile darknet with nodejs and for that I use this repository: https://github.com/bennetthardwick/darknet.js

When I test my Yolov3 weights and cfg (trained with  your repo the results is good) but when I try to run the same weights and cfg files on darknet.js (based on pjreddie) repo detect nothing or wrong.

You know why is that?

**AlexeyAB output (correct preddiction):**
```
Loading weights from /home/ubuntu/darknet/data_train/models/yolov3-gondolas_final.weights...
 seen 64 
Done! Loaded 107 layers from weights-file 
Enter Image Path: /home/ubuntu/darknet/data_train/prueba.png
/home/ubuntu/darknet/data_train/prueba.png: Predicted in 86.983000 milli-seconds.
sprite_can: 100%
coca_can: 100%

(predictions:16977): Gtk-WARNING **: cannot open display
```
**pjreddie ouput (wrong preddiction):**
```
Loading weights from /home/ubuntu/darknet/data_train/models/yolov3-gondolas_final.weights...Done!
Enter Image Path: /home/ubuntu/darknet/data_train/prueba.png
/home/ubuntu/darknet/data_train/prueba.png: Predicted in 0.113931 seconds.
: 61%de_los_toros_pomelo
: 67%de_los_toros_tonica
: 51%
: 64%_light
: 72%_can
: 64%e_can
: 63%
: 57%
: 58%
: 51%
Segmentation fault (core dumped)

```

I upload here the files trained in AlexeyAB darknet

https://drive.google.com/drive/folders/1SiAEBiJ_ghUUUrdaU-NeUaQhTpIzINPN?usp=sharing

**Comment by AlexeyAB** [comment]
What model do you use?
What command do you use for detection?

**Comment by joseware** [comment]
I use the model uploaded in the comment above. I train my own model with cuda on windows 10 with your repository and instructions. And the weights works greats and windows or ubuntu with your repository. 
Now I running on EC2 instance.

The command I use for both results show above (AlexeyAB and pjreddie) is the same:

`./darknet detector test /home/ubuntu/darknet/data_train/data/gondolas.data /home/ubuntu/darknet/data_train/yolov3-gondolas.cfg /home/ubuntu/darknet/data_train/models/yolov3-gondolas_final.weights`

When I use the darknet.js library based on pjreddie darknet the result also is wrong. I thing that it should be the library issue, but when I try to run the model in pjreddie (without darknet.js) with the command above (same as yours) the results is wrong.
**Node js code with darknet.js**
`import { Darknet } from 'darknet';

// Init
let darknet = new Darknet({
    weights: '/home/ubuntu/darknet/data_train/models/yolov3-gondolas_final.weights',
    config: '/home/ubuntu/darknet/data_train/yolov3-gondolas.cfg',
    names.files: '/home/ubuntu/darknet/data_train/data/gondolas.names'
});

// Detect
console.log(darknet.detect('/home/ubuntu/darknet/data_train/prueba.png'));`

Results:
 
Several wrong detection.

I can't compile darknet.js with AlexeyAB darknet, also show errors.

I Thought my model (trained on your repository) should be work on pjreddie also but I can figure out what is wrong.

Thanks

**Comment by AlexeyAB** [comment]
try to do  on linux before detection
```
sudo apt-get install dos2unix
dos2unix yolov3-gondolas.cfg

```

**Comment by dreambit** [comment]
@joseware Hi

Did u compare performance of darknet.js and original pjreddie darknet? 
What is detection time?
Thanks.

**Comment by joseware** [comment]
@AlexeyAB When I trying to test on pjreddie I have problemas with files, I use dos2unix but nothing happens then I create a new cfg and data files with the same contente but now I create from linux and its working, but the result is diferente in pjreddie

I cannot understand why

@dreambit Yes,  I do. Actually in pjreddie detection time is around 100ms and AlexeyAB is around 89 ms

The model it should work great on both repositories right? I think cfg files could be a problema but i can understand why.

**Comment by AlexeyAB** [comment]
https://github.com/pjreddie/darknet can't work with Windows `/r/n` characters.

You should use `dos2unix` for all text-files (cfg/data/names/...) that you use with https://github.com/pjreddie/darknet if you created them on Windows.

**Comment by dreambit** [comment]
@joseware 
I mean detection time between pjreddie and darknetjs wrapper.

**Comment by joseware** [comment]
I make it again, trying to use pjreddie and AlexeyAB for models trained in windows.
I use dos2unix for text files
Then I run the following commands

`./darknet detector test /home/ubuntu/darknet/data_train/data/gondolas.data /home/ubuntu/darknet/data_train/yolov3-gondolas.cfg /home/ubuntu/darknet/data_train/models/yolov3-gondolas_final.weights -dont_show`

Then I introduce an image path

`/home/ubuntu/vending-fridge-api/pizza.png`

**AlexeyAB results:**
` Allocate additional workspace_size = 12.46 MB 
Loading weights from /home/ubuntu/darknet/data_train/models/yolov3-gondolas_final.weights...
 seen 64 
Done! Loaded 107 layers from weights-file 
Enter Image Path: /home/ubuntu/vending-fridge-api/pizza.png
/home/ubuntu/vending-fridge-api/pizza.png: Predicted in 88.800000 milli-seconds.
pizza: 100%
pizza: 80%`

**pjreddie results** shows nothing

`Loading weights from /home/ubuntu/darknet/data_train/models/yolov3-gondolas_final.weights...Done!
Enter Image Path: /home/ubuntu/vending-fridge-api/pizza.png
/home/ubuntu/vending-fridge-api/pizza.png: Predicted in 0.105887 seconds.`

**Comment by AlexeyAB** [comment]
> AlexeyAB results:
> Allocate additional workspace_size = 12.46 MB Loading weights from /home/ubuntu/darknet/data_train/models/yolov3-gondolas_final.weights... seen 64 Done! Loaded 107 layers from weights-file Enter Image Path: /home/ubuntu/vending-fridge-api/pizza.png /home/ubuntu/vending-fridge-api/pizza.png: Predicted in 88.800000 milli-seconds. pizza: 100% pizza: 80%

Try to run detection with flag `-letter_box` in my repo.

> pjreddie results shows nothing

Show screenshot.

**Comment by joseware** [comment]
<img width="679" alt="Captura de Pantalla 2019-11-28 a la(s) 15 55 22" src="https://user-images.githubusercontent.com/58047828/69827786-b0dba380-11f7-11ea-930d-5a153a4157ee.png">

**Comment by AlexeyAB** [comment]
Is this screenshot in my repo https://github.com/AlexeyAB/darknet  with flag **-letter_box** ?

> pjreddie results shows nothing


I mean show screenshot where is https://github.com/pjreddie/darknet results shows nothing

**Comment by joseware** [comment]
<img width="618" alt="Captura de Pantalla 2019-11-28 a la(s) 15 47 43" src="https://user-images.githubusercontent.com/58047828/69836391-3165c880-1227-11ea-86f9-071a0bdec1c7.png">

This is witch pjreddie showing wrong results

**Comment by AlexeyAB** [comment]
Did you set `batch=1 subdivisions=1` in cfg-file before Detection?
It is necessary for https://github.com/pjreddie/darknet

**Comment by joseware** [comment]
Yes, I do.

[net]
# Testing
#batch=1
#subdivisions=1
# Training
batch=64
subdivisions=32
width=416
height=416
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
burn_in=1000
max_batches = 22000
policy=steps
steps=17600,19800
scales=.1,.1

**Comment by AlexeyAB** [comment]
No you didn't. You use 64 and 32

Should be
```
[net]
# Testing
batch=1
subdivisions=1
# Training
#batch=64
#subdivisions=32
```

**Comment by josebenitezg** [comment]
Now is working great with modifications above
Thank you so much.
