### ISSUE TITLE
one class of map?

### ISSUE THREAD

**Issue by leiyaohui** [AlexeyAB/darknet#4411]
![image](https://user-images.githubusercontent.com/42469241/69847802-25bfe380-12b3-11ea-9eab-0f32af54f7bc.png)
Hello! When there is a type of target running, why is the result of calculating the map not in the picture below? Such as TP =, FP =, averagr IOU = and so on.

![image](https://user-images.githubusercontent.com/42469241/69847856-4d16b080-12b3-11ea-8d45-e751a06b232f.png)
I look forward to your reply!

**Comment by AlexeyAB** [comment]
Something wrong with your dataset.
Check the mAP on train and val datasets.
Check bad_label.list and bad.list

**Comment by holger-prause** [comment]
And also check if map goes further up when u train a bit more.
