### ISSUE TITLE
Pre-trained weights for More than one class 

### ISSUE THREAD

**Issue by shubham3git** [AlexeyAB/darknet#4412]
Hi @AlexeyAB , 

Thanks for your great work!

Should i use pre-trained YOLOv3 darknet-53 model for training 4 classes?

**Comment by AlexeyAB** [comment]
Yes. You can use it for any number of any classes

**Comment by shubham3git** [comment]
Thanks for your quick reply @AlexeyAB

**Comment by shubham3git** [comment]
Hi @AlexeyAB ,

Thanks for solving my previous problem. I have one more doubt related to this, I want to retrain my custom model so for that should i use old data-set also with new data-set or i can retrain with new data-set without using old data-set.

For improvement
