### ISSUE TITLE
Question::What pretrained weights to use for yolov3-tiny_3l.cfg

### ISSUE THREAD

**Issue by holger-prause** [AlexeyAB/darknet#4415]
Hello,

**Introduction**
I want to train a text segmentation model using yolo.
As my words are sometimes very small (< 16*16) - i want to use config yolov3-tiny_3l.cfg with a high network resolution.

**Now my question**
What is the weight file i should start on training?
darknet53.conv.74 (because yolov3-tiny_3l.cfg has 3 yolo layer in contrast to tiny?) or
yolov3-tiny.conv.15 (because its used for tiny configs)

Thank you very much.
Greetings,
Holger

**Comment by AlexeyAB** [comment]
Use `yolov3-tiny.conv.15` for any tiny models.

**Comment by holger-prause** [comment]
Thank you!
