### ISSUE TITLE
Show/hide the detected objects by their tracking number

### ISSUE THREAD

**Issue by VanitarNordic** [AlexeyAB/darknet#442]
How can we hide/show detected objects by their tracking number?

For example, suppose in a frame we have 10 detected apples and we decide to show just number 6, and rest of the detected boxes should disappear (visually) to clean the screen except the desired object.

The favorite number could be written in the code for now, but later on in the application can be imported from somewhere else such as keyboard, but for a test, inside the code is enough.

**Comment by AlexeyAB** [comment]
The track number is only present if you use Yolo as SO/DLL from yolo_console.cpp.

Just add between these 2 lines: https://github.com/AlexeyAB/darknet/blob/880cf187d87c904f5fe574802ecff99118643f2d/src/yolo_console_dll.cpp#L182-L183
this line:
`if(i.track_id != 6) continue;`
Then only the object with track number 6 will be displayed.
