### ISSUE TITLE
Cdll error in python examples

### ISSUE THREAD

**Issue by haviduck** [AlexeyAB/darknet#4423]
Hey, ive compiled both the nogpu and gpu and renamed as instructed and place it in the folder near darknet. But when i try to run darknet_video it throws an error of not finding the dlls.

`File "E:\Eel\darknet.py", line 117, in <module>
    lib = CDLL(winGPUdll, RTLD_GLOBAL)
  File "C:\Python27\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found`

Is there an environmental or something causing this? Im on win 10 and compiled the cpp project from the build dir.  Ive Googled ny butt off but cant find a solution

**Comment by AlexeyAB** [comment]
* Check that you use the latest Darknet version.
* Show screenshot of Windows Explorer with DLL-file `yolo_cpp_dll.dll`


Right now I compiled `yolo_cpp_dll_no_gpu.dll`  and run darknet.py

![image](https://user-images.githubusercontent.com/4096485/69921741-00df9200-14a6-11ea-91b2-f193b1b55e7a.png)


----

and compiled `yolo_cpp_dll.dll` and run darknet.py

![image](https://user-images.githubusercontent.com/4096485/69921755-5320b300-14a6-11ea-8818-35163402ba47.png)

**Comment by haviduck** [comment]
Im using the last version. 
Ive only copied the Main dll files not the Additional ones with similar names. Tried again now with same error. 
![Screenshot_20191202_001345_com microsoft rdc android](https://user-images.githubusercontent.com/4920887/69922047-b7d51100-1498-11ea-8d77-4f5a946059f8.jpg)

**Comment by AlexeyAB** [comment]
Try double click on darknet.py in Windows Explorer

**Comment by haviduck** [comment]
Instantly closes. Im meant to build from the build dir, right? Cause the release dir doesnt have those dll slns..

**Comment by haviduck** [comment]
got it working :) had a couple of things i did wrong for anyone who got stuck like i did. 
First of, as alexey writes: start completely fresh.  add the cudnn and opencv dlls to the x64 dir and build it. if you, like me, have both python 2 and 3 installed make sure you enforce python 3 and have image scikit installed.  
Thanks for the push, alexey!

**Comment by RohitSingh1226** [comment]
I only have python3 installed, I am using the latest darknet, still isn't working. I am still getting the DLL error @haviduck @AlexeyAB

**Comment by haviduck** [comment]
> I only have python3 installed, I am using the latest darknet, still isn't working. I am still getting the DLL error @haviduck @AlexeyAB

this is from 2019, i think you should open a ticket for your current situation.  those dlls are no longer required, only darknet.dll.
