### ISSUE TITLE
darknet.exe classifier predict:RAM Out of Memory

### ISSUE THREAD

**Issue by aql315** [AlexeyAB/darknet#4425]
hi @AlexeyAB  thanks for the awesome work.
i think there is a small bug in classify predict.
i have 5000 images with  612×121 pixel when i predict them my computer RAM memory goes to 100% and crashes. pls can you give me a solution to this?.
os-windows10
RAM-32GB
CUDA-8
OpenCV 3.4
i`m using the latest version of Darknet

**Comment by AlexeyAB** [comment]
Check that you compiled with CUDA and cuDNN.
Show screenshot of the error.
Show cfg-file

**Comment by aql315** [comment]
Hi @AlexeyAB this is the cfg file and yes i have compiled using  CUDA and cuDNN.
[cfg and confirming cuda.zip](https://github.com/AlexeyAB/darknet/files/3910894/cfg.and.confirming.cuda.zip)

**Comment by AlexeyAB** [comment]
Why do you use height=121 width=612 while you have 5 x stride=2 layers? so your network resolution should be multiple of 32

**Comment by aql315** [comment]
thanks @AlexeyAB  for the reply i tries it with 256×128 pixel i still got the problem.
And also im not shure what does this NDBUG means
![Darknet preprocss](https://user-images.githubusercontent.com/44859951/69955247-99c2eb80-1540-11ea-9cbf-ab48e8338f3c.PNG)

**Comment by AlexeyAB** [comment]
Can you show screenshot of the error?

**Comment by aql315** [comment]
@AlexeyAB  there is no error code just my ram goes to 100% and the computer freezes
![Darknet ERROR1](https://user-images.githubusercontent.com/44859951/69956354-18b92380-1543-11ea-9631-4da7b2c28d70.PNG)

**Comment by AlexeyAB** [comment]
What command do you use?

**Comment by aql315** [comment]
darknet.exe classifier predict cfg/GoogLeNet.data SAisin/GoogLeNet.cfg backup/GoogLeNet_SAisin/GoogLeNet_1000.weights -gpus 0 <SAisin/test.list>ClassifyPred.txt

**Comment by aql315** [comment]
@AlexeyAB the above command is the one i use

**Comment by AlexeyAB** [comment]
@aql315 I fixed this memory leak: https://github.com/AlexeyAB/darknet/commit/a95bc3f5b69cfec0c82ff4ba7ae182cedc77a9e9

**Comment by aql315** [comment]
@AlexeyAB  Thanks Alexy
