### ISSUE TITLE
Classifier trainin - Mosaic data augmentation

### ISSUE THREAD

**Issue by AlexeyAB** [AlexeyAB/darknet#4432]
Related to: https://github.com/AlexeyAB/darknet/issues/4264

Use for **Classifier** training:
* `cutmix=1` - will be used CutMix (36%-91%, 9%-64%) https://github.com/AlexeyAB/darknet/issues/4419
* **`mosaic=1` - will be used Mosaic data augmentation (4%-64%, 4%-64%, 4%-64%, 4%-64%)**
* will be used randomly CutMix and Mosaic if set:
    ```
    [net]
    cutmix=1
    mosaic=1
    ```

Run training with flag `-show_imgs` to see how images are changed (in separate windows and saved to files `aug_... .jpg`) and how labels are changed (see the console).

![image](https://user-images.githubusercontent.com/4096485/69968376-54e08a00-152b-11ea-84aa-665463bb05b4.png)

**Comment by AlexeyAB** [comment]
@WongKinYiu I also implemented Mosaic data augmentation for Classifier.

**Comment by WongKinYiu** [comment]
@AlexeyAB no available gpu :penguin::penguin::penguin:

**Comment by Look4-you** [comment]
@AlexeyAB Hi.   
1. Is it to randomly select one of these data enhancement methods (like hue, mosaic, saturation) to process each batch of images when training?     

2. Besides, the jitter is set in [yolo] layer, is it aim at feature map?

**Comment by AlexeyAB** [comment]
@WongKinYiu 

May be `cutmix=1 mosaic=1`

----

I would recommend to train the **smallest** model (for quick comparison) using alternately one approach and compare accuracy %Top1 gain:
* mixup=1
* cutmix=1
* mosaic=1
* cutmix=1 mosaic=1

**Comment by AlexeyAB** [comment]
@Look4-you 

> Is it to randomly select one of these data enhancement methods (like hue, mosaic, saturation) to process each batch of images when training?

Every data augmentation method occurs randomly if enabled.

----

> Besides, the jitter is set at each [yolo] layer, is it aim at feature map?

random= and jitter= are used ony from the last [yolo]-layer. 
jitter - resizes input image
random - resizes network

**Comment by Look4-you** [comment]
@AlexeyAB  Thanks a lot!

**Comment by WongKinYiu** [comment]
> I would recommend to train the **smallest** model (for quick comparison) using alternately one approach and compare accuracy %Top1 gain:

@AlexeyAB OK,

I will do experiments for **smallest** model first. 
Thanks for your suggestion.

**Comment by AlexeyAB** [comment]
@WongKinYiu Also you can try to train with large mini_batch (if you have 32-256 GB CPU-RAM) https://github.com/AlexeyAB/darknet/issues/4386

**Comment by WongKinYiu** [comment]
@AlexeyAB Hmm... I think my GPU scheduling are full until next year.

I will do more comparison if I can borrow more gpus/machines.
Currently I borrow a Titan RTX and a Tesla V100 to compare with the results of my Titan X and 1080 ti of different mini batch size.

**Comment by AlexeyAB** [comment]
@WongKinYiu If you use CPU-RAM https://github.com/AlexeyAB/darknet/issues/4386 for increasing mini_batch size, then there is a bottleneck in PCIe, so it doesn't require high-end GPU, **you can use GTX 1060/1070**. So if you have 128-256 GB CPU-RAM then you can set **mini_batch size 4-8x large than on Titan RTX 24 GB or Tesla V100 16/32 GB.**

**Comment by WongKinYiu** [comment]
@AlexeyAB I know, but I would like to make it has only one control factor.

**Comment by AlexeyAB** [comment]
@WongKinYiu 
>  I know, but I would like to make it has only one control factor.

What is the control factor?

**Comment by WongKinYiu** [comment]
@AlexeyAB I hope the only difference is mini_batch size, so I want to run the experiment on same machine, same gpu, ....

**Comment by AlexeyAB** [comment]
@WongKinYiu 
> I hope the only difference is mini_batch size, so I want to run the experiment on same machine, same gpu, .... (maybe it is controlled variable?)

Yes.
Also if you use CPU-RAM + GPU-processing then this is still a controllable factor.

**Comment by AlexeyAB** [comment]
@WongKinYiu Also I added `blur=1` for training Classifier: https://github.com/AlexeyAB/darknet/issues/3320

**Comment by Look4-you** [comment]
@AlexeyAB Hi.
How random works to resizing the network in the last [yolo]-layer.
I know that  random=1 - randomly resizes network for each 10 iterations from 1/1.4 to 1.4(data augmentation parameter is used only from the last layer)   but how?

**Comment by AlexeyAB** [comment]
@Look4-you This thread is for Mosaic data augmentation for Classifier, not for random=, which can be used only for Detector. Create new issue.

**Comment by WongKinYiu** [comment]
@AlexeyAB 

Can I set
```
mosaic=1
cutmix=1
blur=1
lable_smooth_eps=0.1
```

**Comment by AlexeyAB** [comment]
@WongKinYiu Yes.

You can set:
* for Classifier:
```
mosaic=1
cutmix=1
blur=1
lable_smooth_eps=0.1
```

* for Detector:
```
mosaic=1
blur=1
lable_smooth_eps=0.1
```

**Comment by WongKinYiu** [comment]
@AlexeyAB thank u very much.

**Comment by AlexeyAB** [comment]
@WongKinYiu 

Also try to train Classifier with
```
[net]
mosaic=1
```

but change this line: https://github.com/AlexeyAB/darknet/blob/b2749c9e97c2485fd6b4a33d7f6de02226437674/src/data.c#L1631
to these 2 lines and recompile:
```cpp
const float max_s = max_val_cmp(s1, max_val_cmp(s2, max_val_cmp(s3, s4)));
d.y.vals[i][j] = d.y.vals[i][j] * s1 / max_s + d2.y.vals[i][j] * s2 / max_s + d3.y.vals[i][j] * s3 / max_s + d4.y.vals[i][j] * s4 / max_s;
```

**Comment by WongKinYiu** [comment]
@AlexeyAB 

Hello, 

The memory leak problem is very serious when i set
```
mosaic=1
cutmix=1
blur=1
lable_smooth_eps=0.1
```
or even
```
mosaic=1
cutmix=1
```
or even disable OPENCV with above setting

i try to modify the code https://github.com/AlexeyAB/darknet/blob/master/src/data.c#L1510
but not solve the problem.

**Comment by WongKinYiu** [comment]
https://github.com/AlexeyAB/darknet/blob/master/src/data.c#L1531
this line will check if mixup mode is set as:
 * mosaic = 1 (mixup mode 3)
 * mosaic = 1, cutmix = 1 (mixup mode 4)

however, https://github.com/AlexeyAB/darknet/blob/master/src/data.c#L1548
this line will re-assign mixup mode:
* mosaic = 1 (mixup mode 3)
* cutmix = 1 (mixup mode 2)

https://github.com/AlexeyAB/darknet/blob/master/src/data.c#L1640
so the `free_data` in this line is not expected:
* d3 and d4 have content even though mixup mode is re-assigned as 2

so i change this part from
```
        if (mixup == 3) {
            free_data(d3);
            free_data(d4);
        }
```
to
```
        free_data(d3);
        free_data(d4);
```

but I think the better way is to make a copy of original mixup mode.

**Comment by AlexeyAB** [comment]
@WongKinYiu Hi, Thanks!

I fixed this bug: https://github.com/AlexeyAB/darknet/commit/b8605bda1e1665eaa7649ac944efb57f38a2e2dd

It seems that mosaic give Top1/Top2 improvement: https://github.com/WongKinYiu/CrossStagePartialNetworks


Also did you try to use mosaic with such modification? https://github.com/AlexeyAB/darknet/issues/4432#issuecomment-568256391

**Comment by WongKinYiu** [comment]
not yet, i m trying to solve the problem of `optimized_memory = 1`.

the memory usage of `optimized_memory = 1` is as follows:
![image](https://user-images.githubusercontent.com/12152972/71513026-aafae000-28d3-11ea-8d50-81e41f5faa06.png)
however, the expected is:
![image](https://user-images.githubusercontent.com/12152972/71513052-c1a13700-28d3-11ea-9308-4829de58754f.png)

**Comment by AlexeyAB** [comment]
@WongKinYiu 

Are you planning to use `optimized_memory = 1`, or `optimized_memory = 3` ?

----

I didn't find very **simple** solution for this.
* or we should pass `net.optimized_memory` parameter to the `make_...()` function **of each layer** (`make_convolutional(), make_shortcut(), ...`) to suppress memory allocation for `output_gpu, delta_gpu, activation_input_gpu`

* or we just can free these arrays after these make_...() functions - but there **will be such a surge in memory consumption:** https://github.com/AlexeyAB/darknet/blob/b8605bda1e1665eaa7649ac944efb57f38a2e2dd/src/parser.c#L1263-L1294

**Comment by WongKinYiu** [comment]
@AlexeyAB Thanks,

currently i also do not find a good way to deal with it.
ok, i ll take a look modified mosaic first.

**Comment by AlexeyAB** [comment]
@WongKinYiu 

`optimized_memory = 1` optimizes memory consumption very poorly.

Anyway, for significant optimization, you should use `optimized_memory = 3` and in this case, the CPU-memory consumption will be much more important than the GPU-memory consumption, and this issue (surge in consumption) will not be so significant.

**Comment by WongKinYiu** [comment]
https://github.com/AlexeyAB/darknet/issues/4432#issuecomment-568256391 got nan

**Comment by BernoGreyling** [comment]
Hi @AlexeyAB,

I think there might be a bug with `mosaic` flag on a Detector with the combination of settings I might be using. The bounding boxes overlap from one image to another for example : 

![image](https://user-images.githubusercontent.com/14345568/71771299-7de8a600-2f41-11ea-8325-5aecc5f35b36.png)

My config has the following `[net]` params:
`[net]
# Testing
#batch=1
#subdivisions=1
# Training
batch=64
subdivisions=16
width=736
height=1280
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1
mixup=0
mosaic=1
#blur=1
letter_box=1`

Is mosaic supposed to work with detectors or only for classifiers? From the top discussion it looks like it should work?

Thanks!

**Comment by AlexeyAB** [comment]
@BernoGreyling 

* Do you use the latest repository?
* Do you get this issue for all images or only for some images?
* mosiac=1 is supported for both Classifier and Detector and it improves accuracy
