### ISSUE TITLE
Precision Metrics

### ISSUE THREAD

**Issue by Dimitrios-Ar** [AlexeyAB/darknet#4433]
Hi, i have been using this repo for quite a while, but I just noticed that my precision metrics don't seem right. 

![map](https://user-images.githubusercontent.com/18186069/69986765-52d3f680-153e-11ea-88fa-0279cc32048c.png)

As seen here, for example on the class 'A', the precision calculated is 49,62%, but according to the TP/(TP+FP) ratio it should be 196/(196+73) = 72,86%. What could I be missing? Any ideas on how to further explore this metric?

Thank you

**Comment by AlexeyAB** [comment]
AP is calculated as area under Precision-Recall curve. Not at one point. https://medium.com/@jonathan_hui/map-mean-average-precision-for-object-detection-45c121a31173
