### ISSUE TITLE
Error when trying to use Python wrapper

### ISSUE THREAD

**Issue by DoriHp** [AlexeyAB/darknet#4436]
I cloned and complied the lastest version of this repo with this values for Makefile:
`GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=1
AVX=1
OPENMP=1
LIBSO=1
ZED_CAMERA=0`
and set `add_library(dark SHARED  ` by these command:
`make clean`
`cmake .`
`make`
But after all, there is no generated 'libdarknet.so' file and I failed to run detect.py.
`OSError: ./libdarknet.so: cannot open shared object file: No such file or directory`
How can I resolve it?

**Comment by DoriHp** [comment]
All of output:
[yolo_make_output.txt](https://github.com/AlexeyAB/darknet/files/3914628/yolo_make_output.txt)

**Comment by AlexeyAB** [comment]
Try to rename `libdark.so` to `libdarknet.so`

**Comment by DoriHp** [comment]
@AlexeyAB where I can find and replace it?

**Comment by AlexeyAB** [comment]
in the same folder where did you do this
```
cmake .
make
```

**Comment by DoriHp** [comment]
Sorry but after make, I didn't find any "libdark.so" file. What did I do wrong?
OS: Ubuntu 18.04
cuda 10.0

**Comment by naebolo** [comment]
> I cloned and complied the lastest version of this repo with this values for Makefile:
> `GPU=1 CUDNN=1 CUDNN_HALF=0 OPENCV=1 AVX=1 OPENMP=1 LIBSO=1 ZED_CAMERA=0`
> and set `add_library(dark SHARED ` by these command:
> `make clean`
> `cmake .`
> `make`
> But after all, there is no generated 'libdarknet.so' file and I failed to run detect.py.
> `OSError: ./libdarknet.so: cannot open shared object file: No such file or directory`
> How can I resolve it?

If you follow this.

> 
How to compile on Linux (using cmake)
The CMakeLists.txt will attempt to find installed optional dependencies like CUDA, cudnn, ZED and build against those. It will also create a shared object library file to use darknet for code development.

Do inside the cloned repository:

mkdir build-release
cd build-release
cmake ..
make
make install
> 

You can find libdark.so in build-release folde. After that you rename this file to libdarknet.so

**Comment by DoriHp** [comment]
@naebolo Thank for your response. I'll try it
