### ISSUE TITLE
Class ID wrongly defined in annotation text file.

### ISSUE THREAD

**Issue by sbind29893** [AlexeyAB/darknet#4439]
Hi @AlexeyAB 
I have trained my weight file for 7 classes accoring to your given instructions in how to train custom objects. This is the simple use case for detecting indian pancard. While i run the detection everything gets detected except 'PanLogo2'. I think it is the issue with the annotation file where i have mentioned 11 in place of 6. Can you help me out in this scenario where i can still use the generated weight file and detect PanLogo2.

**This is my annotation text file :** 
0 0.548183 0.339275 0.318089 0.284592
1 0.451409 0.300000 0.085341 0.023565
2 0.466109 0.333233 0.110657 0.024773
3 0.441609 0.368278 0.063291 0.021148
4 0.453859 0.405136 0.085341 0.021148
5 0.463659 0.257100 0.131074 0.054985
11 0.630257 0.246526 0.112291 0.058006

**This is my classes.names file**
Pancard
Name
FathersName
Date
Pan
PanLogo1
PanLogo2

**Comment by AlexeyAB** [comment]
You should fix annotations and start training again with already trained weights file and -clear flag

**Comment by sbind29893** [comment]
> You should fix annotations and start training again with already trained weights file and -clear flag

thanks for your reply...can you please guide on how to do this **-clear flag**

**Comment by AlexeyAB** [comment]
./darknet detector train ... -clear

**Comment by sbind29893** [comment]
> ./darknet detector train ... -clear

Okay i have run the darkent command with -clear flag...I have only one last question on this issue.
Now my weight file will be from 8000 onwards or it will start from the beginning
