### ISSUE TITLE
Higher network resolution decreases precision

### ISSUE THREAD

**Issue by fabito** [AlexeyAB/darknet#444]
Hi,

I'm increasing the network-resolution but the more I increase the lower is the precision ( I was expecting the exact opposite).
I'm using the `detector map` command to calculate the mAP. The table below summarizes my results:

Resolution | mAP | IoU
--- | ---: | :---:
416x416 | 84.04 |55.83
544x544 | 78.72 |53.12
608x608 | 75.23 |50.84
832x832 | 64.40 |44.93

Does anyone know what could cause such behavior ?

See below the output from the `map` command:
```
416x416

detections_count = 64962, unique_truth_count = 5171
class_id = 0, name = face, 962   ap = 80.04 %
 for thresh = 0.24, precision = 0.81, recall = 0.82, F1-score = 0.81
 for thresh = 0.24, TP = 4221, FP = 974, FN = 950, average IoU = 55.83 %

 mean average precision (mAP) = 0.800352, or 80.04 %
Total Detection Time: 110.000000 Seconds
```

```
544x544

detections_count = 95539, unique_truth_count = 5171
class_id = 0, name = face, 539   ap = 78.72 %
 for thresh = 0.24, precision = 0.78, recall = 0.80, F1-score = 0.79
 for thresh = 0.24, TP = 4143, FP = 1157, FN = 1028, average IoU = 53.12 %

 mean average precision (mAP) = 0.787250, or 78.72 %
```

```
608x608

detections_count = 114942, unique_truth_count = 5171
class_id = 0, name = face, 14942 ap = 75.23 %
 for thresh = 0.24, precision = 0.75, recall = 0.77, F1-score = 0.76
 for thresh = 0.24, TP = 3998, FP = 1329, FN = 1173, average IoU = 50.84 %

 mean average precision (mAP) = 0.752281, or 75.23 %
Total Detection Time: 221.000000 Seconds
```

```
832x832

detections_count = 204247, unique_truth_count = 5171
class_id = 0, name = face, 04247 ap = 64.40 %
 for thresh = 0.24, precision = 0.67, recall = 0.66, F1-score = 0.67
 for thresh = 0.24, TP = 3428, FP = 1709, FN = 1743, average IoU = 44.93 %

 mean average precision (mAP) = 0.643958, or 64.40 %
Total Detection Time: 372.000000 Seconds
```

**Comment by AlexeyAB** [comment]
Hi,

* Try multiplying the anchors x 2 in your cfg-file. For example if you have `anchors = 1,1, 2,2, ...` then change it to `anchors = 2,2, 4,4, ...` and calculate mAP for 832x832.

* High resolution of newtork greatly help to detect small objects, little help to detect medium objects, and almost do not help to detect large objects.

* Increasing of resolution often help more, if you trained network with `random=1` and if you trained with high resolution.

**Comment by fabito** [comment]
Hi,

I did train with `random=1`. 
I tried multiplying the anchors by 2 but the results were way worse.

```
detections_count = 162347, unique_truth_count = 5171  
class_id = 0, name = face, 62347 ap = 3.57 % 
 for thresh = 0.24, precision = 0.09, recall = 0.09, F1-score = 0.09 
 for thresh = 0.24, TP = 479, FP = 4592, FN = 4692, average IoU = 5.47 % 

 mean average precision (mAP) = 0.035665, or 3.57 % 
Total Detection Time: 360.000000 Seconds
```

**Comment by sivagnanamn** [comment]
- Are you using your own custom dataset?
    - If so, are you using the default anchors provided in the cfg? Did you try generating custom anchors for your dataset?
- How did you decide to stop training for each resolution? Do you have the training loss information?

**Comment by AlexeyAB** [comment]
@fabito Can you do this command and pin here result picture?
`darknet.exe detector calc_anchors data/obj.data -num_of_clusters 10 -final_width 13 -final_heigh 13 -show`

**Comment by fabito** [comment]
@AlexeyAB ,

Check below the output of `calc_anchors` and the generated image:

```
root@1d7cefed31ec:/datasets/WIDER/darknet# /darknet/darknet detector calc_anchors obj.data -num_of_clusters 10 -final_width 13 -final_heigh 13 -show

 num_of_clusters = 10, final_width = 13, final_height = 13 
 read labels from 12876 images 
 loaded 	 image: 12876    box: 156994
 all loaded. 

 calculating k-means++ ...
 avg IoU = 62.89 % 

Saving anchors to the file: anchors.txt 
anchors = 0.1237,0.2139, 3.3918,3.2933, 0.5158,0.9282, 5.7341,5.5534, 0.9130,1.4979, 1.8795,3.9325, 5.7922,9.8223, 3.0771,6.3908, 0.2784,0.5064, 1.4157,2.3773, 
```

![calc_anchors_10](https://user-images.githubusercontent.com/308613/37734494-223b4dbe-2d2a-11e8-9702-852cfb777616.png)

**Comment by AlexeyAB** [comment]
@fabito As I understand you try to train Yolo on 12800 training images from WIDER face dataset: http://mmlab.ie.cuhk.edu.hk/projects/WIDERFace/

I recommend:

1. Set `width=832 height=832` and `random=0` in the cfg-file
2. Then run:
`./darknet detector calc_anchors obj.data -num_of_clusters 10 -final_width 26 -final_heigh 26 -show`

3. Then change in the cfg-file:
    * `num=10` https://github.com/AlexeyAB/darknet/blob/101de2b07aa2feefa74f7e73876fd5cc8fc696cf/cfg/yolo-voc.2.0.cfg#L232
    * `anchors=` anchors from file anchors.txt: https://github.com/AlexeyAB/darknet/blob/101de2b07aa2feefa74f7e73876fd5cc8fc696cf/cfg/yolo-voc.2.0.cfg#L228
    * `steps=100,10000,14000`  https://github.com/AlexeyAB/darknet/blob/101de2b07aa2feefa74f7e73876fd5cc8fc696cf/cfg/yolo-voc.2.0.cfg#L17
    * add here `max=50` https://github.com/AlexeyAB/darknet/blob/101de2b07aa2feefa74f7e73876fd5cc8fc696cf/cfg/yolo-voc.2.0.cfg#L236


4. And train at least 15 000 iterations:
`./darknet detector train data/obj.data yolo-obj.cfg darknet19_448.conv.23`

5. Then try to check mAP for different resolutions 416, 832, 1024

Also try to check mAP on: training, validation and testing datasets.

**Comment by fabito** [comment]
Hi @AlexeyAB ,

You are right, I'm training a face detector.

I'll have to change `filters` too, right:  `(classes + coords + 1) * num`  ? 
Which in my case is: `(1 + 4 + 1) * 10 = 600`

`filters=600`
https://github.com/AlexeyAB/darknet/blob/48586c8d4db5c00d3d4b9dabcc9a5d2294c5b15d/cfg/yolo-voc.cfg#L237

**Comment by AlexeyAB** [comment]
@fabito Hi,

Yes, you should set `filters=60`

`small_object=1` this is not necessary in your case.

**Comment by fabito** [comment]
Hi @AlexeyAB ,

Would you recommend similar settings for Tiny YOLO ?

**Comment by AlexeyAB** [comment]
@fabito Yes.

**Comment by fabito** [comment]
Hi @AlexeyAB , 

Still at 4k out of 15k iterations. Average loss seems to be stuck at ~0.55 in the last 2k iterations:

![yolo_widerface_training_loss](https://user-images.githubusercontent.com/308613/37806305-06d51a60-2e1e-11e8-8c38-d0e9f9341550.png)

What do you think ? Is it common ?

**Comment by AlexeyAB** [comment]
@fabito Hi,

Now try to check `detector map` for 3000, 10000, 15000 iterations.

**Comment by fabito** [comment]
Check below the results on the FDDB dataset benchmark:

YOLOv2 | Tiny YOLO
------------ | -------------
![YOLOv2 mAP](https://user-images.githubusercontent.com/308613/37978743-26d9c458-31bd-11e8-853d-4f4ca85e2ec3.png) | ![Tiny YOLO mAP](https://user-images.githubusercontent.com/308613/37978749-2aae0594-31bd-11e8-8212-09cc7636e8d3.png)

Still performing better at lower resolutions though.

**Comment by AlexeyAB** [comment]
@fabito Thanks for results. This is very strange, I don't know why higher resulotuion gives lower precision even when many objects are small.

**Comment by fabito** [comment]
No worries @AlexeyAB .
Thanks a lot for your help, really appreciated!
