### ISSUE TITLE
What is the best system configuration to train seamlessly on yolov3

### ISSUE THREAD

**Issue by sbind29893** [AlexeyAB/darknet#4441]
Hi @AlexeyAB 

First of all thanks for all your help earlier.
I just wanted to know what will be the best system configurations which is required to train datasets in darknet.
Eg : ram, graphics, etc.

**Comment by AlexeyAB** [comment]
* x86 CPU 8 Cores (f.e. Core i7) and 32 GB RAM
* GeForce RTX 2080 Ti or Titan RTX (or Quadro RTX8000)

**Comment by sbind29893** [comment]
> * x86 CPU 8 Cores (f.e. Core i7) and 32 GB RAM
> * GeForce RTX 2080 Ti or Titan RTX (or Quadro RTX8000)

Thanks for replying

i am working on below configurations.
x86 CPU 8 Cores (f.e. Core i7) and 16 GB RAM
GeForce GTX 1070

After running the training command after sometime, my ubuntu system freezes and i have to again reboot it. Is there any way to continue working on same given system ??
