### ISSUE TITLE
How to modify yolo_console_dll.cpp to output only single class?

### ISSUE THREAD

**Issue by ericwang321** [AlexeyAB/darknet#4442]
###  :one:. os
ubuntu 18.04 64bit
python 3.6.8
darknet make file option:
OPENCV=1
AVX=1
OPENMP=1
LIBSO=1

###  :two:.question
**_How to modify only_** src/yolo_console_dll.cpp,
to achieve the function of **displaying only a single class of people** 
and **_calculating the total number._**

Did  make **_changes in the  show_console_result:arrow_down:  section_** :question:

**Thanks for any suggestion.**

https://github.com/AlexeyAB/darknet/blob/5d0352f961f4dc3db8ccad0570481c69305c0143/src/yolo_console_dll.cpp#L218-L227

**Comment by AlexeyAB** [comment]
add between these 2 lines: https://github.com/AlexeyAB/darknet/blob/5d0352f961f4dc3db8ccad0570481c69305c0143/src/yolo_console_dll.cpp#L219-L220
```cpp
std::vector<bbox_t> tmp_vec;
for (auto &i : result_vec) if(obj_names[i.obj_id] == "person") tmp_vec.push_back(i);
std::cout << "\n num of persons = " << tmp_vec.size() << std::endl;
result_vec = tmp_vec;
```

**Comment by ericwang321** [comment]
**thanks for your replay.**
add the code,**_output below error_** messsage:
![555](https://user-images.githubusercontent.com/25045112/70116933-17047280-169f-11ea-9d82-c1fad53a6a7f.png)
**_The problem is_** that  
```python
result_vec = tmp_vec  ;
```
it seems that the contents of the const vector result_vec  cannot be changed.
**_how to fix it?_**

**Comment by AlexeyAB** [comment]
change `std::vector<bbox_t> const result_vec` to `std::vector<bbox_t> result_vec`

https://github.com/AlexeyAB/darknet/blob/5d0352f961f4dc3db8ccad0570481c69305c0143/src/yolo_console_dll.cpp#L218

**Comment by ericwang321** [comment]
:thumbsup: works. Thanks!

**Comment by AerithFarr0n** [comment]
more later  but  
those code should be added to draw boxes module
