### ISSUE TITLE
I don't know what to do here ...

### ISSUE THREAD

**Issue by joelmatt** [AlexeyAB/darknet#4445]
/usr/bin/ld: cannot find -lcudnn
collect2: error: ld returned 1 exit status
Makefile:143: recipe for target 'darknet' failed
make: *** [darknet] Error 1
Is this error due to some Symbolic linking of some sort ???? Please help me out here :'(

**Comment by AlexeyAB** [comment]
Install cuDNN library: https://github.com/AlexeyAB/darknet#requirements

cuDNN >= 7.0 for CUDA 10.0 https://developer.nvidia.com/rdp/cudnn-archive (on Linux copy cudnn.h,libcudnn.so... as desribed here https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html#installlinux-tar , on Windows copy cudnn.h,cudnn64_7.dll, cudnn64_7.lib as desribed here https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html#installwindows )

**Comment by joelmatt** [comment]
t

**Comment by joelmatt** [comment]
thank you. It did work
