### ISSUE TITLE
Question about ignore_thresh and truth_thresh 

### ISSUE THREAD

**Issue by lsd1994** [AlexeyAB/darknet#4448]
After reading #1814, I still don't understand how parameters ignore_thresh and truth_thresh really work. Only the bbox which has max iou with ground truth will generate loss. So in my understanding:

If(iou<ignore_thresh)  seen as negative sample and only generate objectness loss.
If(iou>ignore_thresh and iou<truth_thresh)  seen as OK sample and doesn't generate any loss.(NOT sure)
If(iou>truth_thresh)  seen as positive sample and generate objectness loss,class loss and iou loss.

Is that right?Thanks for help.

**Comment by AlexeyAB** [comment]
Yes.

**Comment by lsd1994** [comment]
That's fine, thank you for your help. @AlexeyAB
