### ISSUE TITLE
Training restart issue. (iteration jump issue)

### ISSUE THREAD

**Issue by zed654** [AlexeyAB/darknet#445]
when I restart training, my backup folder file's naming is not a normal.
![default](https://user-images.githubusercontent.com/15728230/37263266-ac844724-25ea-11e8-8c5e-ce0b59f744a4.JPG)

The picture is when I restart training at 800 iter. the iteration of file name is jump 800 to 3600.
I wonder It is real 3600 iter weight data.. or 1200 iter weight data.
Can you help me?

**Comment by AlexeyAB** [comment]
* Usually yes, `yolo-v2-obj_3600.weights` is a real 3600 iter weight data.
* Do you use this fork or original repo?
* Do you use 1 GPU or multi-GPU?

**Comment by zed654** [comment]
Thanks for your answer!!
I use 4 GPU(1080ti) to train!
and I don't know What is mean of fork, original repo...

**Comment by TheMikeyR** [comment]
Original darknet: https://github.com/pjreddie/darknet the creator of darknet's repository
@AlexeyAB made a fork (copy) https://github.com/AlexeyAB/darknet/ of the original darknet and made many changes to make it more stable and easier to train. It is important to know which repository you are using to be able to provide you with links to which lines to change. 

Furthermore it is a good idea (when training on multiple gpu) to train on one gpu for 1000 iterations, stop the training and then restart it with the new weights with multiple gpus. It is adviced in the readme for this repository, I've copied the instructions:

> Train it first on 1 GPU for like 1000 iterations: darknet.exe detector train data/voc.data yolo-voc.2.0.cfg darknet19_448.conv.23
> 
> Then stop and by using partially-trained model /backup/yolo-voc_1000.weights run training with multigpu (up to 4 GPUs): darknet.exe detector train data/voc.data yolo-voc.2.0.cfg /backup/yolo-voc_1000.weights -gpus 0,1,2,3
>
