### ISSUE TITLE
How do i resize yolov3-tiny from 416x416 to 208x208

### ISSUE THREAD

**Issue by Mixy1** [AlexeyAB/darknet#4464]
just changing the width and height doesn't work. what else do i need to change?
also is it possible to resize the neural network into a rectangle shape?

in specific i want to take a quarter of the neural network resolution at 208*208

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet#how-to-improve-object-detection


> increase network resolution in your .cfg-file (height=608, width=608 or **any value multiple of 32**) - it will increase precision

**Comment by Mixy1** [comment]
But i want to decrease the resolution because the pictures i am using are of the resolution 206x156
