### ISSUE TITLE
Error while making this repo

### ISSUE THREAD

**Issue by ahsan856jalal** [AlexeyAB/darknet#447]
@AlexeyAB 
I am getting this error while making this repo

g++  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors -Ofast -DOPENCV -fopenmp -DGPU -DCUDNN -I/usr/local/cudnn/include -c ./src/http_stream.cpp -o obj/http_stream.o
./src/http_stream.cpp: In member function ‘bool MJPGWriter::write(const cv::Mat&)’:
./src/http_stream.cpp:173:101: error: ‘sprintf’ was not declared in this scope
 pegstream\r\nContent-Type: image/jpeg\r\nContent-Length: %zu\r\n\r\n", outlen);
                                                                              ^
compilation terminated due to -Wfatal-errors.
Makefile:105: recipe for target 'obj/http_stream.o' failed
make: *** [obj/http_stream.o] Error 1

Opencv:3.3.0
pjreddie's repo was making fine before so I am assuming all required things are installed

**Comment by ahsan856jalal** [comment]
After commenting this line , it works fine . But does this make any problem in future?
`sprintf(head, "--mjpegstream\r\nContent-Type: image/jpeg\r\nContent-Length: %zu\r\n\r\n", outlen);`
line 173, http_stream.cpp

**Comment by AlexeyAB** [comment]
@ahsan856jalal I fixed it: https://github.com/AlexeyAB/darknet/commit/15c89e7a714e7e37c13618eace9325a06f0642fc

----

> After commenting this line , it works fine . But does this make any problem in future?

Then you just can not watch the detection result on the video over the network (for example in the WebBrowser).

Using `darknet.exe detector demo data/voc.data yolo-voc.cfg yolo-voc.weights test.mp4 -http_port 8090`
And open in your WebBrowser: `http://127.0.0.1:8090`

**Comment by ahsan856jalal** [comment]
but can I see and save detection results using 
`./darknet detector demo -i 2data/obj.data cfg/yolo-obj.cfg custom.weights test.mp4`

**Comment by AlexeyAB** [comment]
@ahsan856jalal Yes you can.

**Comment by ahsan856jalal** [comment]
Thanks @AlexeyAB , including #include <cstdio> worked.
