### ISSUE TITLE
malloc(): smallbin double linked list corrupted Aborted (core dumped)

### ISSUE THREAD

**Issue by Adaverse** [AlexeyAB/darknet#4472]
I get this error when I run darknet_video.py on Xavier. Whenever object is detected in the image, this error pops up.

**Comment by AlexeyAB** [comment]
Show screenshot of the error.
What params do you use in the Makefile?
What versions of CUDA, cuDNN, OpenCV do you use?
Show output of commands:
```
nvcc --version
nvidia-smi
```

**Comment by 2akash111998** [comment]
> Show screenshot of the error.
> What params do you use in the Makefile?
> What versions of CUDA, cuDNN, OpenCV do you use?
> Show output of commands:
> 
> ```
> nvcc --version
> nvidia-smi
> ```

Thank you for your fast reply @AlexeyAB 
nvcc version
![Screenshot from 2019-12-08 16-27-49](https://user-images.githubusercontent.com/35839624/70388459-f9554700-19d7-11ea-8c31-bccb09c919e7.png)

cuda version
![Screenshot from 2019-12-08 16-28-33](https://user-images.githubusercontent.com/35839624/70388463-03774580-19d8-11ea-96c9-8f34a8c160f1.png)

cuDNN verison
![Screenshot from 2019-12-08 16-34-30](https://user-images.githubusercontent.com/35839624/70388508-be9fde80-19d8-11ea-8b0b-ddb2a331aee1.png)

OpenCV version: '3.3.1'
Makefile:
    GPU=1
    CUDNN=1
    CUDNN_HALF=1
    OPENCV=1
    AVX=0
    OPENMP=0
    LIBSO=1
    ZED_CAMERA=0

Unfortunately nvidia-smi does not work in this device.

**Comment by AlexeyAB** [comment]
Can you show full screenshots of the error (with previous messages)?

**Comment by 2akash111998** [comment]
> Can you show full screenshots of the error (with previous messages)?
> Can you run successfully ./darknet detector test or demo?

I ran ./darknet detector and demo and both of it runs completely fine.
This is full screenshot, they just contain the fps value before the error.
![Screenshot from 2019-12-08 18-05-59](https://user-images.githubusercontent.com/35839624/70389457-83f07300-19e5-11ea-94d0-33d0eb757abc.png)

**Comment by AlexeyAB** [comment]
Do you try to use python_video.py on videofile or videocamera?

**Comment by 2akash111998** [comment]
> Do you try to use python_video.py on videofile or videocamera?

I'm using darknet_video.py and reading the feed from the camera using VideoCapture()

**Comment by AlexeyAB** [comment]
Is it web-camera or rtsp/http-mjpeg camera?

Apparently the video stream from the camera is interrupted periodically.

> I ran ./darknet detector and demo and both of it runs completely fine.

Did you try to detect from the same camera by using?
./darknet detector demo ....

**Comment by 2akash111998** [comment]
> Is it web-camera or rtsp/http-mjpeg camera?
> 
> Apparently the video stream from the camera is interrupted periodically.
> 
> > I ran ./darknet detector and demo and both of it runs completely fine.
> 
> Did you try to detect from the same camera by using?
> ./darknet detector demo ....

Its a web camera from logitech (model C310). Yes, I'm using the same camera for ./darknet detector demo

**Comment by AlexeyAB** [comment]
Try to output captured framesize after this line: https://github.com/AlexeyAB/darknet/blob/master/darknet_video.py#L96
`print(frame_read.dtype.name + " " + str(frame_read.shape))`

And show screenshot of output with the error

**Comment by 2akash111998** [comment]
> Try to output captured framesize after this line: https://github.com/AlexeyAB/darknet/blob/master/darknet_video.py#L96
> `print(frame_read.dtype.name + " " + str(frame_read.shape))`
> 
> And show screenshot of output with the error
![Screenshot from 2019-12-08 19-07-42](https://user-images.githubusercontent.com/35839624/70390105-1a289700-19ee-11ea-934a-5ff4ceb7ef67.png)

![Screenshot from 2019-12-08 19-10-03](https://user-images.githubusercontent.com/35839624/70390172-a33fce00-19ee-11ea-82c1-6788fa76a438.png)


There is one more absurd thing,there is only one box detected but the text seems to be off. The detection runs for some seconds before its dumped
![Screenshot from 2019-12-08 19-10-42](https://user-images.githubusercontent.com/35839624/70390176-ab980900-19ee-11ea-821a-f48f53d5f658.png)

**Comment by AlexeyAB** [comment]
* Share your datknet_video.py file
* Do you use default yolov3.cfg/weights or your trained model?
* Try to use default yolov3.cfg/weights and coco.data

**Comment by 2akash111998** [comment]
1)code file
https://drive.google.com/file/d/1TL8XLHrYjxSq-7Fc754GXPKYcf4Lv-4h/view?usp=sharing

2)No, I'm not using the default one, I have changed the cfg file a little like anchor boxes values and the masks values. I'm using custom trained model. When I'm testing the custom trained model, then this error is thrown.

3)It ran perfectly fine with the default files.

I compared the config files and I'm using one class and 6 anchors 
anchors = 28,39, 55,79, 106,118, 213,204, 447,429, 869,860
This is the link of the cfg file:
https://drive.google.com/file/d/1TVA5UVjT4RZPpvcplHGehv2ZSPJoclBW/view?usp=sharing

**Comment by AlexeyAB** [comment]
cfg-file is ok.

share darknet_video.py rather than darknet.py

It seems that you incorrectly changed darknet_video.py, or use bad obj.data file

**Comment by 2akash111998** [comment]
I'm extremely sorry. I mistakenly uploaded the wrong file.
This is the darknet_video.py file :
https://drive.google.com/file/d/1msCZq76EvhchYOUlvOuWS9cmAyY4Kd8i/view?usp=sharing

This is obj.data file:
classes = 1
train  = data/train.txt
valid  = data/test.txt
names = data/obj.names
backup = backup/

**Comment by AlexeyAB** [comment]
change line in darknet_video.py `metaPath = "./cfg/coco.data"` to `metaPath = "./cfg/obj.data"`

Also comment these lines: 
```
    cap.set(3, 416)
    cap.set(4, 416)
```

And show content of `obj.names`


----

Also check does your model with darknet_video.py works well with video file instead of web-cam?

**Comment by 2akash111998** [comment]
Thanks, @AlexeyAB was a silly error in file. Actually I trained by moving 'darknet' shared lib file to  'build/darknet/x64/' and then moved it back to ~/darknet/.
Thanks love you 1000!
