### ISSUE TITLE
What's the parameter max_epochs = 300 means in the [net] of the Gaussian_yolov3_BDD.cfg?

### ISSUE THREAD

**Issue by Look4-you** [AlexeyAB/darknet#4474]
@AlexeyAB Hi.
What's the parameter max_epochs = 300 means in the [net] of the Gaussian_yolov3_BDD.cfg?

**Comment by AlexeyAB** [comment]
They added max_epoch= instead of max_batches=.
May be I will add it too.

`epoch_size = num_of_images_int_train_txt / batch_size`

**Comment by Look4-you** [comment]
@AlexeyAB THANKS.
