### ISSUE TITLE
obj and no obj parameters are going low during training

### ISSUE THREAD

**Issue by ahsan856jalal** [AlexeyAB/darknet#448]
During training obj and no obj becomes ~ 0.000001 while avg_loss approaches 0.25 in 300 iterations . Is it good?
My dataset have 16 classes and ~18k objects.

**Comment by AlexeyAB** [comment]
Usually, first the object is decreases (until ~300 iterations), and then increases (~2000 iterations).

**Comment by ahsan856jalal** [comment]
You are right , no obj has increased to 0.7-0.8 and no_obj is ~0.001 and avg_error is reduced to ~ 0.2
