### ISSUE TITLE
Problems when calculating anchors generated by clustering

### ISSUE THREAD

**Issue by yrc08** [AlexeyAB/darknet#4482]
@AlexeyAB 
Hi! When I use this command darknet.exe detector calc_anchors data / obj.data -num_of_clusters 12 -width 608 -height 608, the following problems occur when calculating the anchor box generated by clustering:
![216f92268b2b1be2e60725665e6c957](https://user-images.githubusercontent.com/56901677/70440337-ebcdb900-1acc-11ea-9b3c-30453a69aaf7.png)

**Comment by AlexeyAB** [comment]
Show content of file `data/obj/34.txt`

**Comment by yrc08** [comment]
@AlexeyAB 
Sorry, I found my problem and it's been solved。
