### ISSUE TITLE
detection box outputted at wrong scale for small objects in image

### ISSUE THREAD

**Issue by BootcutBandit** [AlexeyAB/darknet#4485]
Using Tiny Yolov3 default weights to detect people in an image, I'm having difficulties with the boxes for objects that are smaller in the frame. 

The smaller objects are detected, but it seems like the box is just drawn at the wrong scale so it comes out very small. 

Here's an image I'm using for testing: 
![office](https://user-images.githubusercontent.com/58610925/70481365-5b817b00-1ab0-11ea-859a-baeac3810ba5.jpg)

Here's the output with the correct box sizes from PJ Reddie's Darknet 
![Tiny Yolo Darknet output](https://user-images.githubusercontent.com/58610925/70481307-24ab6500-1ab0-11ea-888d-2bab9475f299.png)

And here's the output from the AlexeyAB fork
![Tiny Yolo  Darknet AlexeyAB Fork output](https://user-images.githubusercontent.com/58610925/70481342-44428d80-1ab0-11ea-8ecf-32de9c762f0a.png)

As you can see, the PJ Reddie version is outputting the image correctly, but in the last image the bodies on the left and right are drawn too small, but to the right scale. Both versions are using the same settings and same weights. 

Cropping the image to make the object larger in the frame corrects the detection and provides the proper box size
![Screenshot from 2019-12-09 18-27-14](https://user-images.githubusercontent.com/58610925/70481749-93d58900-1ab1-11ea-91f5-918088679f44.png)

I've tried this same image on another system and the output was the same.

**Comment by AlexeyAB** [comment]
Which repo did you use for training?

**Comment by BootcutBandit** [comment]
This is the most recent repo of darknet, and the up to date pre-trained tiny yolo model from PJ Reddie

**Comment by AlexeyAB** [comment]
Set `mask = 1,2,3` instead of https://github.com/AlexeyAB/darknet/blob/dbe34d78658746fcfc9548ebab759895ea05a70c/cfg/yolov3-tiny.cfg#L175

and test again.

**Comment by BootcutBandit** [comment]
This has fixed it, thanks Alexey
