### ISSUE TITLE
problem in saving video using darknet demo

### ISSUE THREAD

**Issue by ahsan856jalal** [AlexeyAB/darknet#449]
@AlexeyAB 
when I am using ./darknet demo .... command , it is showing me results but it is not saving any results in res.avi 
I tried to add your suggested code in image.c after "cvShowImage(buff, disp);" but that also couldn't save results in test_dnn.avi

**Comment by AlexeyAB** [comment]
Hi,

Just use flag in command: `-out_filename res.avi`

For example
`./darknet detector demo data/coco.data yolo.cfg yolo.weights test.mp4 -i 0 -out_filename res.avi`

**Comment by ahsan856jalal** [comment]
I did but that also doesn't work. predictions of the ./darknet detector test ... are saved though.

**Comment by AlexeyAB** [comment]
Do you use this repo: https://github.com/AlexeyAB/darknet
Or  this: https://github.com/pjreddie/darknet
?

**Comment by ahsan856jalal** [comment]
I am using https://github.com/AlexeyAB/darknet
Everything except saving video is working like a charm

**Comment by AlexeyAB** [comment]
Try to run as `sudo`

----

If it doesn't help - probably you didn't installed `ffmpeg` on Linux, or compiled OpenCV without ffmpeg `-D WITH_FFMPEG=ON`.

`sudo apt-get install ffmpeg libopencv-dev libgtk-3-dev python-numpy python3-numpy libdc1394-22 libdc1394-22-dev libjpeg-dev libpng12-dev libtiff5-dev libjasper-dev libavcodec-dev libavformat-dev libswscale-dev libxine2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libv4l-dev libtbb-dev qtbase5-dev libfaac-dev libmp3lame-dev libopencore-amrnb-dev libopencore-amrwb-dev libtheora-dev libvorbis-dev libxvidcore-dev x264 v4l-utils unzip`

----

If it doesn't help, probably you should reinstall OpenCV
```
mkdir build
cd build/
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_CUDA=ON -D WITH_V4L=ON -D WITH_GTK=ON -D WITH_FFMPEG=ON ..
make
```

**Comment by ahsan856jalal** [comment]
After this 
`sudo apt-get install ffmpeg libopencv-dev libgtk-3-dev python-numpy python3-numpy libdc1394-22 libdc1394-22-dev libjpeg-dev libpng12-dev libtiff5-dev libjasper-dev libavcodec-dev libavformat-dev libswscale-dev libxine2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libv4l-dev libtbb-dev qtbase5-dev libfaac-dev libmp3lame-dev libopencore-amrnb-dev libopencore-amrwb-dev libtheora-dev libvorbis-dev libxvidcore-dev x264 v4l-utils unzip

`
./darknet detector demo .......  -out_filename res.avi 
saved video in res.avi
Thanks @AlexeyAB
