### ISSUE TITLE
chmod + x * .sh make: *** There are no rules to make the target "obj / image_opencv.o", required by "darknet". stop. make: *** is waiting for unfinished tasks ...

### ISSUE THREAD

**Issue by lizhensong** [AlexeyAB/darknet#4490]
chmod + x * .sh
make: *** There are no rules to make the target "obj / image_opencv.o", required by "darknet". stop.
make: *** is waiting for unfinished tasks ...

**Comment by SangerY** [comment]
> chmod + x * .sh
> make: *** There are no rules to make the target "obj / image_opencv.o", required by "darknet". stop.
> make: *** is waiting for unfinished tasks ...

How did you solve this problem？
