### ISSUE TITLE
YoloV3-tiny Custom Anchors

### ISSUE THREAD

**Issue by istranic** [AlexeyAB/darknet#4496]
I'm looking for help creating custom anchors for yoloV3-tiny. In the "How to Improve Object Detection" Section, is says:

"Only if you are an expert in neural detection networks - recalculate anchors for your dataset for width and height from cfg-file: darknet.exe detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416 then set the same 9 anchors in each of 3 [yolo]-layers in your cfg-file. But you should change indexes of anchors masks= for each [yolo]-layer, so that 1st-[yolo]-layer has anchors larger than 60x60, 2nd larger than 30x30, 3rd remaining. Also you should change the filters=(classes + 5)* before each [yolo]-layer. If many of the calculated anchors do not fit under the appropriate layers - then just try using all the default anchors."

I assume the anchor sizes above apply only to YoloV3, not YoloV3 tiny? Do you have similar guidance for YoloV3 tiny? Do you have broader guidance that would apply for various image resolutions, numbers of yolo layers, etc.?

For background information, I'm detecting objects that have similar size/shape and significant overlap. What's the best way to deal with this scenario? I assumed it would help to add more anchors. Is that correct?

Thank you

**Comment by AlexeyAB** [comment]
> I assume the anchor sizes above apply only to YoloV3, not YoloV3 tiny? Do you have similar guidance for YoloV3 tiny? Do you have broader guidance that would apply for various image resolutions, numbers of yolo layers, etc.?

The same for any model: v3, tiny, ...

> For background information, I'm detecting objects that have similar size/shape and significant overlap. What's the best way to deal with this scenario? I assumed it would help to add more anchors. Is that correct?

Yes.
Or set higher width=832 height=832

**Comment by istranic** [comment]
Thanks!

**Comment by istranic** [comment]
One more question. I understand why adding more anchors helps to detect overlapping objects with similar size. However, I don't understand why increasing resolution helps. Could you pls elaborate on that?

**Comment by AlexeyAB** [comment]
Higher resolution - more final activations in [yolo] layers
