### ISSUE TITLE
Mixnet - yet another efficient classifier backbone 78.9% top-1 (better than mobilenetv3, ghostnet)

### ISSUE THREAD

**Issue by LukeAI** [AlexeyAB/darknet#4503]
https://arxiv.org/abs/1907.09595
[TPU implementation](https://github.com/tensorflow/tpu/tree/master/models/official/mnasnet/mixnet) 
[Pytorch Implementation](https://github.com/romulus0914/MixNet-Pytorch)
![image](https://user-images.githubusercontent.com/43993778/70615842-102cb100-1c05-11ea-9b94-5392c8ba311f.png)
![image](https://user-images.githubusercontent.com/43993778/70615881-220e5400-1c05-11ea-8536-9992b42ba28a.png)
![image](https://user-images.githubusercontent.com/43993778/70615982-5b46c400-1c05-11ea-9fc9-4ddd935c81a5.png)
![image](https://user-images.githubusercontent.com/43993778/70616005-67cb1c80-1c05-11ea-9322-67f2efff5eb0.png)

**Comment by AlexeyAB** [comment]
@LukeAI 

It is alread implemented, trained and compared :)  https://github.com/AlexeyAB/darknet/issues/4203#issuecomment-548955416
