### ISSUE TITLE
RFB-block: Receptive Field Block Net for Accurate and Fast Object Detection

### ISSUE THREAD

**Issue by AlexeyAB** [AlexeyAB/darknet#4507]
**RFB-block**: Receptive Field Block Net for Accurate and Fast Object Detection
* paper: https://arxiv.org/abs/1711.07767v3
* source: https://github.com/ruinmessi/RFBNet
* is used with Yolov3-ASFF: https://arxiv.org/abs/1911.09516v2

Soruce code: https://github.com/ruinmessi/ASFF/blob/c74e08591b2756e5f773892628dd9a6d605f4b77/models/network_blocks.py#L134-L165

RFB-block (filters= depends on input channels):
(receptieve filed size = 11x11)
```
// if input channels = 256
// then inter_c = 64

# receptieve field size = 1x1
[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=linear


# receptieve field size = 3x3
[route]
layers = -2

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=linear

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=linear

# receptieve field size = 7x7
[route]
layers = -5

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=linear

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=linear

[convolutional]
batch_normalize=1
filters=64
size=3
dilation=2
stride=1
pad=1
activation=linear

# receptieve field size = 11x11
[route]
layers = -9

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=linear

[convolutional]
batch_normalize=1
filters=64
size=5
stride=1
pad=1
activation=linear

[convolutional]
batch_normalize=1
filters=64
size=3
dilation=3
stride=1
pad=1
activation=linear

[route]
layers = -1,-5,-9,-12

[shortcut]
from=-14
activation=leaky
```

----

or Head as in original RFB-paper:
```
[route]
layers = -1,-5,-9,-12

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=linear

[shortcut]
from=-15
activation=leaky
```

----

![image](https://user-images.githubusercontent.com/4096485/70647931-13eb2280-1c5b-11ea-99f1-6890451e7396.png)

**Comment by uday60** [comment]
Can you look at this repo too :
https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB

So the RFB-640 version it is giving me 13 FPS on CPU(i3 5th gen) taking only 2 CPU cores including video  playback via python so C version should be faster.

As per my understanding they have modified the anchor policy, network params to make work only for single class. Now i was thinking may be you can modify it here and we can all use it for multiple classes.

**Comment by uday60** [comment]
@AlexeyAB 
Please share the network configuration file when your ready.

**Comment by uday60** [comment]
@AlexeyAB 
Any update regarding yolo-rfb file for object detection ?

**Comment by AlexeyAB** [comment]
RFB-block (filters= depends on input channels) 
with **flexible receptive field** from 1x1 to 11x11:
```
// if input channels = 256
// then inter_c = 64

# receptieve field size = 1x1
[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=leaky


# receptieve field size = 3x3
[route]
layers = -2

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

# receptieve field size = 7x7
[route]
layers = -5

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=3
dilation=2
stride=1
pad=1
activation=leaky

# receptieve field size = 11x11
[route]
layers = -9

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=5
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=3
dilation=3
stride=1
pad=1
activation=leaky

[route]
layers = -1,-5,-9,-12

[maxpool]
maxpool_depth=1
out_channels=64
size=1
stride=1

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[shortcut]
from=-16
activation=leaky
```

**Comment by deimsdeutsch** [comment]
I am also interested in this. 

@AlexeyAB 
Can you be kind enough to share the entire configuration file ?

**Comment by uday60** [comment]
@AlexeyAB 
Can you share a cfg file so that i can train for object detection ?

Thank you.

**Comment by AlexeyAB** [comment]
@uday60 

[yolov3-spp-asff-it-rfb.cfg.txt](https://github.com/AlexeyAB/darknet/files/4064702/yolov3-spp-asff-it-rfb.cfg.txt)

**Comment by uday60** [comment]
@AlexeyAB 
Thanks for replying.
I thought RFB-Block based architecture was light weight. It is showing 
Total BFLOPS 131.388 

Can you share yolov3-tiny based rfb configuration file ?

 CUDA-version: 9000 (9000), cuDNN: 7.0.5, GPU count: 2  
 OpenCV version: 3.4.0
   layer   filters  size/strd(dil)      input                output
   0 conv     32       3 x 3/ 1    544 x 544 x   3 ->  544 x 544 x  32 0.511 BF
   1 conv     64       3 x 3/ 2    544 x 544 x  32 ->  272 x 272 x  64 2.727 BF
   2 conv     32       1 x 1/ 1    272 x 272 x  64 ->  272 x 272 x  32 0.303 BF
   3 conv     64       3 x 3/ 1    272 x 272 x  32 ->  272 x 272 x  64 2.727 BF
   4 Shortcut Layer: 1,  wt = 0, wn = 0, outputs: 272 x 272 x  64 0.005 BF
   5 conv    128       3 x 3/ 2    272 x 272 x  64 ->  136 x 136 x 128 2.727 BF
   6 conv     64       1 x 1/ 1    136 x 136 x 128 ->  136 x 136 x  64 0.303 BF
   7 conv    128       3 x 3/ 1    136 x 136 x  64 ->  136 x 136 x 128 2.727 BF
   8 Shortcut Layer: 5,  wt = 0, wn = 0, outputs: 136 x 136 x 128 0.002 BF
   9 conv     64       1 x 1/ 1    136 x 136 x 128 ->  136 x 136 x  64 0.303 BF
  10 conv    128       3 x 3/ 1    136 x 136 x  64 ->  136 x 136 x 128 2.727 BF
  11 Shortcut Layer: 8,  wt = 0, wn = 0, outputs: 136 x 136 x 128 0.002 BF
  12 conv    256       3 x 3/ 2    136 x 136 x 128 ->   68 x  68 x 256 2.727 BF
  13 conv    128       1 x 1/ 1     68 x  68 x 256 ->   68 x  68 x 128 0.303 BF
  14 conv    256       3 x 3/ 1     68 x  68 x 128 ->   68 x  68 x 256 2.727 BF
  15 Shortcut Layer: 12,  wt = 0, wn = 0, outputs:  68 x  68 x 256 0.001 BF
  16 conv    128       1 x 1/ 1     68 x  68 x 256 ->   68 x  68 x 128 0.303 BF
  17 conv    256       3 x 3/ 1     68 x  68 x 128 ->   68 x  68 x 256 2.727 BF
  18 Shortcut Layer: 15,  wt = 0, wn = 0, outputs:  68 x  68 x 256 0.001 BF
  19 conv    128       1 x 1/ 1     68 x  68 x 256 ->   68 x  68 x 128 0.303 BF
  20 conv    256       3 x 3/ 1     68 x  68 x 128 ->   68 x  68 x 256 2.727 BF
  21 Shortcut Layer: 18,  wt = 0, wn = 0, outputs:  68 x  68 x 256 0.001 BF
  22 conv    128       1 x 1/ 1     68 x  68 x 256 ->   68 x  68 x 128 0.303 BF
  23 conv    256       3 x 3/ 1     68 x  68 x 128 ->   68 x  68 x 256 2.727 BF
  24 Shortcut Layer: 21,  wt = 0, wn = 0, outputs:  68 x  68 x 256 0.001 BF
  25 conv    128       1 x 1/ 1     68 x  68 x 256 ->   68 x  68 x 128 0.303 BF
  26 conv    256       3 x 3/ 1     68 x  68 x 128 ->   68 x  68 x 256 2.727 BF
  27 Shortcut Layer: 24,  wt = 0, wn = 0, outputs:  68 x  68 x 256 0.001 BF
  28 conv    128       1 x 1/ 1     68 x  68 x 256 ->   68 x  68 x 128 0.303 BF
  29 conv    256       3 x 3/ 1     68 x  68 x 128 ->   68 x  68 x 256 2.727 BF
  30 Shortcut Layer: 27,  wt = 0, wn = 0, outputs:  68 x  68 x 256 0.001 BF
  31 conv    128       1 x 1/ 1     68 x  68 x 256 ->   68 x  68 x 128 0.303 BF
  32 conv    256       3 x 3/ 1     68 x  68 x 128 ->   68 x  68 x 256 2.727 BF
  33 Shortcut Layer: 30,  wt = 0, wn = 0, outputs:  68 x  68 x 256 0.001 BF
  34 conv    128       1 x 1/ 1     68 x  68 x 256 ->   68 x  68 x 128 0.303 BF
  35 conv    256       3 x 3/ 1     68 x  68 x 128 ->   68 x  68 x 256 2.727 BF
  36 Shortcut Layer: 33,  wt = 0, wn = 0, outputs:  68 x  68 x 256 0.001 BF
  37 conv    512       3 x 3/ 2     68 x  68 x 256 ->   34 x  34 x 512 2.727 BF
  38 conv    256       1 x 1/ 1     34 x  34 x 512 ->   34 x  34 x 256 0.303 BF
  39 conv    512       3 x 3/ 1     34 x  34 x 256 ->   34 x  34 x 512 2.727 BF
  40 Shortcut Layer: 37,  wt = 0, wn = 0, outputs:  34 x  34 x 512 0.001 BF
  41 conv    256       1 x 1/ 1     34 x  34 x 512 ->   34 x  34 x 256 0.303 BF
  42 conv    512       3 x 3/ 1     34 x  34 x 256 ->   34 x  34 x 512 2.727 BF
  43 Shortcut Layer: 40,  wt = 0, wn = 0, outputs:  34 x  34 x 512 0.001 BF
  44 conv    256       1 x 1/ 1     34 x  34 x 512 ->   34 x  34 x 256 0.303 BF
  45 conv    512       3 x 3/ 1     34 x  34 x 256 ->   34 x  34 x 512 2.727 BF
  46 Shortcut Layer: 43,  wt = 0, wn = 0, outputs:  34 x  34 x 512 0.001 BF
  47 conv    256       1 x 1/ 1     34 x  34 x 512 ->   34 x  34 x 256 0.303 BF
  48 conv    512       3 x 3/ 1     34 x  34 x 256 ->   34 x  34 x 512 2.727 BF
  49 Shortcut Layer: 46,  wt = 0, wn = 0, outputs:  34 x  34 x 512 0.001 BF
  50 conv    256       1 x 1/ 1     34 x  34 x 512 ->   34 x  34 x 256 0.303 BF
  51 conv    512       3 x 3/ 1     34 x  34 x 256 ->   34 x  34 x 512 2.727 BF
  52 Shortcut Layer: 49,  wt = 0, wn = 0, outputs:  34 x  34 x 512 0.001 BF
  53 conv    256       1 x 1/ 1     34 x  34 x 512 ->   34 x  34 x 256 0.303 BF
  54 conv    512       3 x 3/ 1     34 x  34 x 256 ->   34 x  34 x 512 2.727 BF
  55 Shortcut Layer: 52,  wt = 0, wn = 0, outputs:  34 x  34 x 512 0.001 BF
  56 conv    256       1 x 1/ 1     34 x  34 x 512 ->   34 x  34 x 256 0.303 BF
  57 conv    512       3 x 3/ 1     34 x  34 x 256 ->   34 x  34 x 512 2.727 BF
  58 Shortcut Layer: 55,  wt = 0, wn = 0, outputs:  34 x  34 x 512 0.001 BF
  59 conv    256       1 x 1/ 1     34 x  34 x 512 ->   34 x  34 x 256 0.303 BF
  60 conv    512       3 x 3/ 1     34 x  34 x 256 ->   34 x  34 x 512 2.727 BF
  61 Shortcut Layer: 58,  wt = 0, wn = 0, outputs:  34 x  34 x 512 0.001 BF
  62 conv   1024       3 x 3/ 2     34 x  34 x 512 ->   17 x  17 x1024 2.727 BF
  63 conv    512       1 x 1/ 1     17 x  17 x1024 ->   17 x  17 x 512 0.303 BF
  64 conv   1024       3 x 3/ 1     17 x  17 x 512 ->   17 x  17 x1024 2.727 BF
  65 Shortcut Layer: 62,  wt = 0, wn = 0, outputs:  17 x  17 x1024 0.000 BF
  66 conv    512       1 x 1/ 1     17 x  17 x1024 ->   17 x  17 x 512 0.303 BF
  67 conv   1024       3 x 3/ 1     17 x  17 x 512 ->   17 x  17 x1024 2.727 BF
  68 Shortcut Layer: 65,  wt = 0, wn = 0, outputs:  17 x  17 x1024 0.000 BF
  69 conv    512       1 x 1/ 1     17 x  17 x1024 ->   17 x  17 x 512 0.303 BF
  70 conv   1024       3 x 3/ 1     17 x  17 x 512 ->   17 x  17 x1024 2.727 BF
  71 Shortcut Layer: 68,  wt = 0, wn = 0, outputs:  17 x  17 x1024 0.000 BF
  72 conv    512       1 x 1/ 1     17 x  17 x1024 ->   17 x  17 x 512 0.303 BF
  73 conv   1024       3 x 3/ 1     17 x  17 x 512 ->   17 x  17 x1024 2.727 BF
  74 Shortcut Layer: 71,  wt = 0, wn = 0, outputs:  17 x  17 x1024 0.000 BF
  75 conv    512       1 x 1/ 1     17 x  17 x1024 ->   17 x  17 x 512 0.303 BF
  76 conv   1024       3 x 3/ 1     17 x  17 x 512 ->   17 x  17 x1024 2.727 BF
  77 conv    512       1 x 1/ 1     17 x  17 x1024 ->   17 x  17 x 512 0.303 BF
  78 max                5x 5/ 1     17 x  17 x 512 ->   17 x  17 x 512 0.004 BF
  79 route  77 		                           ->   17 x  17 x 512 
  80 max                9x 9/ 1     17 x  17 x 512 ->   17 x  17 x 512 0.012 BF
  81 route  77 		                           ->   17 x  17 x 512 
  82 max               13x13/ 1     17 x  17 x 512 ->   17 x  17 x 512 0.025 BF
  83 route  82 80 78 77 	                   ->   17 x  17 x2048 
  84 conv    512       1 x 1/ 1     17 x  17 x2048 ->   17 x  17 x 512 0.606 BF
  85 conv   1024       3 x 3/ 1     17 x  17 x 512 ->   17 x  17 x1024 2.727 BF
  86 conv    512       1 x 1/ 1     17 x  17 x1024 ->   17 x  17 x 512 0.303 BF
  87 conv    256       1 x 1/ 1     17 x  17 x 512 ->   17 x  17 x 256 0.076 BF
  88 upsample                 2x    17 x  17 x 256 ->   34 x  34 x 256
  89 route  88 61 	                           ->   34 x  34 x 768 
  90 conv    256       1 x 1/ 1     34 x  34 x 768 ->   34 x  34 x 256 0.455 BF
  91 conv    512       3 x 3/ 1     34 x  34 x 256 ->   34 x  34 x 512 2.727 BF
  92 conv    256       1 x 1/ 1     34 x  34 x 512 ->   34 x  34 x 256 0.303 BF
  93 conv    512       3 x 3/ 1     34 x  34 x 256 ->   34 x  34 x 512 2.727 BF
  94 conv    256       1 x 1/ 1     34 x  34 x 512 ->   34 x  34 x 256 0.303 BF
  95 conv    128       1 x 1/ 1     34 x  34 x 256 ->   34 x  34 x 128 0.076 BF
  96 upsample                 2x    34 x  34 x 128 ->   68 x  68 x 128
  97 route  96 36 	                           ->   68 x  68 x 384 
  98 conv    128       1 x 1/ 1     68 x  68 x 384 ->   68 x  68 x 128 0.455 BF
  99 conv    256       3 x 3/ 1     68 x  68 x 128 ->   68 x  68 x 256 2.727 BF
 100 conv    128       1 x 1/ 1     68 x  68 x 256 ->   68 x  68 x 128 0.303 BF
 101 conv    256       3 x 3/ 1     68 x  68 x 128 ->   68 x  68 x 256 2.727 BF
 102 conv    128       1 x 1/ 1     68 x  68 x 256 ->   68 x  68 x 128 0.303 BF
 103 conv    256       3 x 3/ 1     68 x  68 x 128 ->   68 x  68 x 256 2.727 BF
 104 route  86 		                           ->   17 x  17 x 512 
 105 conv     16       1 x 1/ 1     17 x  17 x 512 ->   17 x  17 x  16 0.005 BF
 106 route  94 		                           ->   34 x  34 x 256 
 107 conv    512       3 x 3/ 2     34 x  34 x 256 ->   17 x  17 x 512 0.682 BF
 108 conv     16       1 x 1/ 1     17 x  17 x 512 ->   17 x  17 x  16 0.005 BF
 109 route  103 		                           ->   68 x  68 x 256 
 110 max                2x 2/ 2     68 x  68 x 256 ->   34 x  34 x 256 0.001 BF
 111 conv    512       3 x 3/ 2     34 x  34 x 256 ->   17 x  17 x 512 0.682 BF
 112 conv     16       1 x 1/ 1     17 x  17 x 512 ->   17 x  17 x  16 0.005 BF
 113 route  105 108 112 	                           ->   17 x  17 x  48 
 114 conv      3       1 x 1/ 1     17 x  17 x  48 ->   17 x  17 x   3 0.000 BF
 115 route  114 		                       0/3 ->   17 x  17 x   1 
 116 scale Layer: 104
 117 route  114 		                       1/3 ->   17 x  17 x   1 
 118 scale Layer: 107
 119 route  114 		                       2/3 ->   17 x  17 x   1 
 120 scale Layer: 111
 121 Shortcut Layer: 118,  wt = 0, wn = 0, outputs:  17 x  17 x 512 0.000 BF
 122 Shortcut Layer: 116,  wt = 0, wn = 0, outputs:  17 x  17 x 512 0.000 BF
 123 conv   1024       3 x 3/ 1     17 x  17 x 512 ->   17 x  17 x1024 2.727 BF
 124 conv    256       1 x 1/ 1     17 x  17 x1024 ->   17 x  17 x 256 0.152 BF
 125 route  123 		                           ->   17 x  17 x1024 
 126 conv    256       1 x 1/ 1     17 x  17 x1024 ->   17 x  17 x 256 0.152 BF
 127 conv    256       3 x 3/ 1     17 x  17 x 256 ->   17 x  17 x 256 0.341 BF
 128 route  123 		                           ->   17 x  17 x1024 
 129 conv    256       1 x 1/ 1     17 x  17 x1024 ->   17 x  17 x 256 0.152 BF
 130 conv    256       3 x 3/ 1     17 x  17 x 256 ->   17 x  17 x 256 0.341 BF
 131 conv    256       3 x 3/ 1(2)  17 x  17 x 256 ->   17 x  17 x 256 0.341 BF
 132 route  123 		                           ->   17 x  17 x1024 
 133 conv    256       1 x 1/ 1     17 x  17 x1024 ->   17 x  17 x 256 0.152 BF
 134 conv    256       5 x 5/ 1     17 x  17 x 256 ->   17 x  17 x 256 0.947 BF
 135 conv    256       3 x 3/ 1(3)  17 x  17 x 256 ->   17 x  17 x 256 0.341 BF
 136 route  135 131 127 124 	                   ->   17 x  17 x1024 
 137 conv   1024       1 x 1/ 1     17 x  17 x1024 ->   17 x  17 x1024 0.606 BF
 138 Shortcut Layer: 123,  wt = 0, wn = 0, outputs:  17 x  17 x1024 0.000 BF
 139 conv     18       1 x 1/ 1     17 x  17 x1024 ->   17 x  17 x  18 0.011 BF
 140 yolo
[yolo] params: iou loss: giou (1), iou_norm: 0.50, cls_norm: 1.00, scale_x_y: 1.00
 141 route  86 		                           ->   17 x  17 x 512 
 142 conv    256       1 x 1/ 1     17 x  17 x 512 ->   17 x  17 x 256 0.076 BF
 143 upsample                 2x    17 x  17 x 256 ->   34 x  34 x 256
 144 conv     16       1 x 1/ 1     34 x  34 x 256 ->   34 x  34 x  16 0.009 BF
 145 route  94 		                           ->   34 x  34 x 256 
 146 conv     16       1 x 1/ 1     34 x  34 x 256 ->   34 x  34 x  16 0.009 BF
 147 route  103 		                           ->   68 x  68 x 256 
 148 conv    256       3 x 3/ 2     68 x  68 x 256 ->   34 x  34 x 256 1.364 BF
 149 conv     16       1 x 1/ 1     34 x  34 x 256 ->   34 x  34 x  16 0.009 BF
 150 route  144 146 149 	                           ->   34 x  34 x  48 
 151 conv      3       1 x 1/ 1     34 x  34 x  48 ->   34 x  34 x   3 0.000 BF
 152 route  151 		                       0/3 ->   34 x  34 x   1 
 153 scale Layer: 143
 154 route  151 		                       1/3 ->   34 x  34 x   1 
 155 scale Layer: 145
 156 route  151 		                       2/3 ->   34 x  34 x   1 
 157 scale Layer: 148
 158 Shortcut Layer: 155,  wt = 0, wn = 0, outputs:  34 x  34 x 256 0.000 BF
 159 Shortcut Layer: 153,  wt = 0, wn = 0, outputs:  34 x  34 x 256 0.000 BF
 160 conv    512       3 x 3/ 1     34 x  34 x 256 ->   34 x  34 x 512 2.727 BF
 161 conv    128       1 x 1/ 1     34 x  34 x 512 ->   34 x  34 x 128 0.152 BF
 162 route  160 		                           ->   34 x  34 x 512 
 163 conv    128       1 x 1/ 1     34 x  34 x 512 ->   34 x  34 x 128 0.152 BF
 164 conv    128       3 x 3/ 1     34 x  34 x 128 ->   34 x  34 x 128 0.341 BF
 165 route  160 		                           ->   34 x  34 x 512 
 166 conv    128       1 x 1/ 1     34 x  34 x 512 ->   34 x  34 x 128 0.152 BF
 167 conv    128       3 x 3/ 1     34 x  34 x 128 ->   34 x  34 x 128 0.341 BF
 168 conv    128       3 x 3/ 1(2)  34 x  34 x 128 ->   34 x  34 x 128 0.341 BF
 169 route  160 		                           ->   34 x  34 x 512 
 170 conv    128       1 x 1/ 1     34 x  34 x 512 ->   34 x  34 x 128 0.152 BF
 171 conv    128       5 x 5/ 1     34 x  34 x 128 ->   34 x  34 x 128 0.947 BF
 172 conv    128       3 x 3/ 1(3)  34 x  34 x 128 ->   34 x  34 x 128 0.341 BF
 173 route  172 168 164 161 	                   ->   34 x  34 x 512 
 174 conv    512       1 x 1/ 1     34 x  34 x 512 ->   34 x  34 x 512 0.606 BF
 175 Shortcut Layer: 160,  wt = 0, wn = 0, outputs:  34 x  34 x 512 0.001 BF
 176 conv     18       1 x 1/ 1     34 x  34 x 512 ->   34 x  34 x  18 0.021 BF
 177 yolo
[yolo] params: iou loss: giou (1), iou_norm: 0.50, cls_norm: 1.00, scale_x_y: 1.00
 178 route  86 		                           ->   17 x  17 x 512 
 179 conv    256       1 x 1/ 1     17 x  17 x 512 ->   17 x  17 x 256 0.076 BF
 180 upsample                 4x    17 x  17 x 256 ->   68 x  68 x 256
 181 conv     16       1 x 1/ 1     68 x  68 x 256 ->   68 x  68 x  16 0.038 BF
 182 route  94 		                           ->   34 x  34 x 256 
 183 upsample                 2x    34 x  34 x 256 ->   68 x  68 x 256
 184 conv     16       1 x 1/ 1     68 x  68 x 256 ->   68 x  68 x  16 0.038 BF
 185 route  103 		                           ->   68 x  68 x 256 
 186 conv     16       1 x 1/ 1     68 x  68 x 256 ->   68 x  68 x  16 0.038 BF
 187 route  181 184 186 	                           ->   68 x  68 x  48 
 188 conv      3       1 x 1/ 1     68 x  68 x  48 ->   68 x  68 x   3 0.001 BF
 189 route  188 		                       0/3 ->   68 x  68 x   1 
 190 scale Layer: 180
 191 route  188 		                       1/3 ->   68 x  68 x   1 
 192 scale Layer: 183
 193 route  188 		                       2/3 ->   68 x  68 x   1 
 194 scale Layer: 185
 195 Shortcut Layer: 192,  wt = 0, wn = 0, outputs:  68 x  68 x 256 0.001 BF
 196 Shortcut Layer: 190,  wt = 0, wn = 0, outputs:  68 x  68 x 256 0.001 BF
 197 conv    256       3 x 3/ 1     68 x  68 x 256 ->   68 x  68 x 256 5.455 BF
 198 conv     64       1 x 1/ 1     68 x  68 x 256 ->   68 x  68 x  64 0.152 BF
 199 route  197 		                           ->   68 x  68 x 256 
 200 conv     64       1 x 1/ 1     68 x  68 x 256 ->   68 x  68 x  64 0.152 BF
 201 conv     64       3 x 3/ 1     68 x  68 x  64 ->   68 x  68 x  64 0.341 BF
 202 route  197 		                           ->   68 x  68 x 256 
 203 conv     64       1 x 1/ 1     68 x  68 x 256 ->   68 x  68 x  64 0.152 BF
 204 conv     64       3 x 3/ 1     68 x  68 x  64 ->   68 x  68 x  64 0.341 BF
 205 conv     64       3 x 3/ 1(2)  68 x  68 x  64 ->   68 x  68 x  64 0.341 BF
 206 route  197 		                           ->   68 x  68 x 256 
 207 conv     64       1 x 1/ 1     68 x  68 x 256 ->   68 x  68 x  64 0.152 BF
 208 conv     64       5 x 5/ 1     68 x  68 x  64 ->   68 x  68 x  64 0.947 BF
 209 conv     64       3 x 3/ 1(3)  68 x  68 x  64 ->   68 x  68 x  64 0.341 BF
 210 route  209 205 201 198 	                   ->   68 x  68 x 256 
 211 conv    256       1 x 1/ 1     68 x  68 x 256 ->   68 x  68 x 256 0.606 BF
 212 Shortcut Layer: 197,  wt = 0, wn = 0, outputs:  68 x  68 x 256 0.001 BF
 213 conv     18       1 x 1/ 1     68 x  68 x 256 ->   68 x  68 x  18 0.043 BF
 214 yolo
[yolo] params: iou loss: giou (1), iou_norm: 0.50, cls_norm: 1.00, scale_x_y: 1.00
Total BFLOPS 131.388
