### ISSUE TITLE
How to output bounding box coordinates while testing darknet detection?

### ISSUE THREAD

**Issue by FilipaRamos** [AlexeyAB/darknet#452]
Hello @AlexeyAB ! 

Sorry to bother you again!

I wanted to print the width, height and centre coordinates of the bounding boxes predicted when I run:

```
darknet detector test ...
```

Where should I look into the code in order to do this?

Thanks a lot!

**Comment by johnnydept** [comment]
printf("x_center = %d, y_center = %d, width = %d, height = %d \n", (int)(b.x*im.w), (int)(b.y*im.h), (int)(b.w*im.w), (int)(b.h*im.h));

**Comment by AlexeyAB** [comment]
@FilipaRamos Hi,

Do as @johnnydept wrote or update your code and un-comment these 2 lines: https://github.com/AlexeyAB/darknet/blob/df076653e00db69c6fb57869981f5196a8f55e70/src/image.c#L234-L235
