### ISSUE TITLE
darknet training hang?

### ISSUE THREAD

**Issue by sexyHongGi** [AlexeyAB/darknet#4529]
Training does not proceed
It looks like hang

If end an training process and retrain, the results are the same.

#ps -ef | grep train
root         31      8  0 Dec13 pts/1    00:00:00 /bin/sh ./custom_train.sh
root         32     31 99 Dec13 pts/1    17-19:10:16 ./darknet detector train custom.data yolov3_custom.cfg yolov3_custom_540000.weights -gpus 0,1,2,3

# std out log..
736883: 0.045114, 0.051117 avg, 0.000040 rate, 3.514875 seconds, 188642048 images
Loaded: 0.000060 seconds
Region 82 Avg IOU: 0.935601, Class: 0.999992, Obj: 0.999901, No Obj: 0.004356, .5R: 1.000000, .75R: 1.000000,  count: 3
Region 82 Avg IOU: 0.935896, Class: 0.999890, Obj: 0.999700, No Obj: 0.005602, .5R: 1.000000, .75R: 1.000000,  count: 3
Region 94 Avg IOU: 0.915980, Class: 0.999999, Obj: 0.999972, No Obj: 0.000470, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: 0.760007, Class: 0.999986, Obj: 0.931501, No Obj: 0.000099, .5R: 1.000000, .75R: 0.666667,  count: 3
Region 106 Avg IOU: 0.677943, Class: 0.999964, Obj: 0.131598, No Obj: 0.000031, .5R: 1.000000, .75R: 0.000000,  count: 1
Region 82 Avg IOU: 0.986165, Class: 1.000000, Obj: 1.000000, No Obj: 0.000431, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: 0.868651, Class: 0.999992, Obj: 0.484120, No Obj: 0.000037, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 82 Avg IOU: 0.900611, Class: 0.999963, Obj: 0.937547, No Obj: 0.006049, .5R: 1.000000, .75R: 1.000000,  count: 5
Region 82 Avg IOU: 0.928563, Class: 0.999999, Obj: 0.999964, No Obj: 0.001020, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 94 Avg IOU: 0.939584, Class: 0.999997, Obj: 0.998767, No Obj: 0.000412, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 94 Avg IOU: 0.841465, Class: 1.000000, Obj: 0.999994, No Obj: 0.000108, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 106 Avg IOU: 0.860708, Class: 0.999992, Obj: 0.999631, No Obj: 0.000126, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 106 Avg IOU: 0.910834, Class: 0.999995, Obj: 0.999501, No Obj: 0.000098, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 82 Avg IOU: 0.959039, Class: 0.999997, Obj: 0.999968, No Obj: 0.002684, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 94 Avg IOU: 0.918991, Class: 0.999997, Obj: 0.998904, No Obj: 0.000730, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 106 Avg IOU: 0.777404, Class: 0.999997, Obj: 0.999510, No Obj: 0.000027, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 82 Avg IOU: 0.813456, Class: 0.999989, Obj: 0.999979, No Obj: 0.001235, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 82 Avg IOU: 0.911251, Class: 0.999990, Obj: 0.999996, No Obj: 0.003136, .5R: 1.000000, .75R: 1.000000,  count: 5
Region 94 Avg IOU: 0.914666, Class: 0.999991, Obj: 0.999455, No Obj: 0.000248, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 94 Avg IOU: 0.890865, Class: 0.998799, Obj: 0.996977, No Obj: 0.002101, .5R: 1.000000, .75R: 1.000000,  count: 9
Region 106 Avg IOU: 0.814981, Class: 0.999991, Obj: 0.997541, No Obj: 0.000085, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 94 Avg IOU: 0.890865, Class: 0.998799, Obj: 0.996977, No Obj: 0.002101, .5R: 1.000000, .75R: 1.000000,  count: 9
Region 106 Avg IOU: 0.814981, Class: 0.999991, Obj: 0.997541, No Obj: 0.000085, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 106 Avg IOU: 0.892103, Class: 0.998688, Obj: 0.966723, No Obj: 0.000786, .5R: 1.000000, .75R: 1.000000,  count: 12
Region 82 Avg IOU: 0.925098, Class: 0.999999, Obj: 0.999584, No Obj: 0.003814, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 94 Avg IOU: 0.903688, Class: 0.996780, Obj: 0.693736, No Obj: 0.001351, .5R: 1.000000, .75R: 1.000000,  count: 8
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.912251, Class: 0.999960, Obj: 0.996676, No Obj: 0.003515, .5R: 1.000000, .75R: 1.000000,  count: 3
Region 82 Avg IOU: 0.943466, Class: 0.999999, Obj: 1.000000, No Obj: 0.000426, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 94 Avg IOU: 0.888396, Class: 0.999995, Obj: 0.881111, No Obj: 0.001648, .5R: 1.000000, .75R: 1.000000,  count: 5
Region 94 Avg IOU: 0.902291, Class: 0.999989, Obj: 0.999945, No Obj: 0.000814, .5R: 1.000000, .75R: 1.000000,  count: 3
Region 106 Avg IOU: 0.894383, Class: 1.000000, Obj: 0.893080, No Obj: 0.000051, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 106 Avg IOU: 0.840587, Class: 0.999929, Obj: 0.927933, No Obj: 0.000356, .5R: 1.000000, .75R: 0.857143,  count: 7
Region 82 Avg IOU: 0.898207, Class: 0.999725, Obj: 0.999362, No Obj: 0.006792, .5R: 1.000000, .75R: 1.000000,  count: 4
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.904326, Class: 0.999992, Obj: 0.999974, No Obj: 0.003066, .5R: 1.000000, .75R: 1.000000,  count: 3
Region 82 Avg IOU: 0.942923, Class: 0.999988, Obj: 0.999760, No Obj: 0.003346, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: 0.817688, Class: 0.999999, Obj: 0.996603, No Obj: 0.000092, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 106 Avg IOU: 0.876522, Class: 0.999998, Obj: 0.999859, No Obj: 0.000035, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 82 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000057, .5R: -nan, .75R: -nan,  count: 0
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000015, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.939229, Class: 0.999994, Obj: 0.999977, No Obj: 0.004694, .5R: 1.000000, .75R: 1.000000,  count: 3
Region 94 Avg IOU: 0.867952, Class: 0.999996, Obj: 0.999620, No Obj: 0.000212, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 106 Avg IOU: 0.951718, Class: 0.999999, Obj: 0.999995, No Obj: 0.000053, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 82 Avg IOU: 0.935714, Class: 0.999990, Obj: 0.999511, No Obj: 0.006448, .5R: 1.000000, .75R: 1.000000,  count: 4
Region 106 Avg IOU: 0.846649, Class: 0.999997, Obj: 0.885557, No Obj: 0.000083, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.925068, Class: 0.999997, Obj: 0.999961, No Obj: 0.001319, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000119, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: 0.889720, Class: 0.999999, Obj: 0.999852, No Obj: 0.000036, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 82 Avg IOU: 0.899808, Class: 0.999377, Obj: 0.999739, No Obj: 0.009326, .5R: 1.000000, .75R: 1.000000,  count: 8
Region 94 Avg IOU: 0.864704, Class: 0.999996, Obj: 0.987185, No Obj: 0.000162, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000001, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.964013, Class: 0.999997, Obj: 0.999997, No Obj: 0.001818, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 94 Avg IOU: 0.935675, Class: 0.999997, Obj: 0.999477, No Obj: 0.000319, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 106 Avg IOU: 0.826276, Class: 0.999995, Obj: 0.984826, No Obj: 0.000097, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 82 Avg IOU: 0.962141, Class: 0.999997, Obj: 0.999977, No Obj: 0.002615, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 94 Avg IOU: 0.962522, Class: 0.999989, Obj: 0.999980, No Obj: 0.000193, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 106 Avg IOU: 0.867849, Class: 0.999980, Obj: 0.916318, No Obj: 0.000418, .5R: 1.000000, .75R: 0.888889,  count: 9
Region 82 Avg IOU: 0.974002, Class: 1.000000, Obj: 1.000000, No Obj: 0.001310, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 94 Avg IOU: 0.881318, Class: 0.999892, Obj: 0.981914, No Obj: 0.002703, .5R: 1.000000, .75R: 1.000000,  count: 11
Region 106 Avg IOU: 0.890295, Class: 0.999978, Obj: 0.994832, No Obj: 0.000400, .5R: 1.000000, .75R: 1.000000,  count: 4
Region 82 Avg IOU: 0.950550, Class: 0.999955, Obj: 0.999834, No Obj: 0.007129, .5R: 1.000000, .75R: 1.000000,  count: 4
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.982608, Class: 0.999993, Obj: 0.999964, No Obj: 0.001701, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.915239, Class: 0.999981, Obj: 0.999948, No Obj: 0.003520, .5R: 1.000000, .75R: 1.000000,  count: 3
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.935009, Class: 0.999995, Obj: 0.999990, No Obj: 0.001818, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 94 Avg IOU: 0.892916, Class: 0.999925, Obj: 0.999031, No Obj: 0.003599, .5R: 1.000000, .75R: 1.000000,  count: 14
Region 106 Avg IOU: 0.909941, Class: 0.999999, Obj: 0.993925, No Obj: 0.000088, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000083, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.959041, Class: 0.999986, Obj: 0.989416, No Obj: 0.001839, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000148, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.947483, Class: 0.999965, Obj: 0.999477, No Obj: 0.004105, .5R: 1.000000, .75R: 1.000000,  count: 4
Region 94 Avg IOU: 0.875464, Class: 0.999997, Obj: 0.998640, No Obj: 0.000372, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 106 Avg IOU: 0.874144, Class: 0.999970, Obj: 0.992693, No Obj: 0.000090, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 82 Avg IOU: 0.923646, Class: 0.999985, Obj: 0.999999, No Obj: 0.000850, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 94 Avg IOU: 0.968071, Class: 0.999893, Obj: 0.997637, No Obj: 0.000623, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 106 Avg IOU: 0.931530, Class: 0.999998, Obj: 0.999687, No Obj: 0.000156, .5R: 1.000000, .75R: 1.000000,  count: 3
Region 82 Avg IOU: 0.932937, Class: 0.999998, Obj: 0.999926, No Obj: 0.003291, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000101, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: 0.922801, Class: 0.999992, Obj: 0.998468, No Obj: 0.000089, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 82 Avg IOU: 0.949989, Class: 0.999997, Obj: 0.999989, No Obj: 0.003294, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: 0.878912, Class: 0.999994, Obj: 0.999534, No Obj: 0.000185, .5R: 1.000000, .75R: 1.000000,  count: 4
Region 82 Avg IOU: 0.955641, Class: 0.999764, Obj: 0.999995, No Obj: 0.001560, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 94 Avg IOU: 0.901274, Class: 0.999654, Obj: 0.999346, No Obj: 0.004089, .5R: 1.000000, .75R: 1.000000,  count: 19
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000133, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.869731, Class: 0.999990, Obj: 0.998334, No Obj: 0.000896, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 94 Avg IOU: 0.948198, Class: 0.999988, Obj: 0.999602, No Obj: 0.001349, .5R: 1.000000, .75R: 1.000000,  count: 3
Region 106 Avg IOU: 0.847978, Class: 0.999993, Obj: 0.819828, No Obj: 0.000120, .5R: 1.000000, .75R: 1.000000,  count: 3
Region 82 Avg IOU: 0.913302, Class: 0.999933, Obj: 0.999966, No Obj: 0.000897, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 94 Avg IOU: 0.883346, Class: 0.999990, Obj: 0.999891, No Obj: 0.000796, .5R: 1.000000, .75R: 1.000000,  count: 3
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.963318, Class: 0.999995, Obj: 0.999998, No Obj: 0.000808, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 94 Avg IOU: 0.797093, Class: 0.999998, Obj: 0.999947, No Obj: 0.000209, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 106 Avg IOU: 0.818328, Class: 0.999947, Obj: 0.609029, No Obj: 0.000076, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 82 Avg IOU: 0.956508, Class: 0.999999, Obj: 1.000000, No Obj: 0.000935, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000089, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: 0.780519, Class: 0.999993, Obj: 0.977365, No Obj: 0.000179, .5R: 1.000000, .75R: 0.500000,  count: 4
Region 82 Avg IOU: 0.977720, Class: 0.999987, Obj: 0.999998, No Obj: 0.000892, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000002, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: 0.823528, Class: 0.999998, Obj: 0.997527, No Obj: 0.000144, .5R: 1.000000, .75R: 0.750000,  count: 4
Region 82 Avg IOU: 0.886136, Class: 0.999984, Obj: 0.999970, No Obj: 0.003893, .5R: 1.000000, .75R: 1.000000,  count: 5
Region 94 Avg IOU: 0.904900, Class: 0.999992, Obj: 0.999907, No Obj: 0.000928, .5R: 1.000000, .75R: 1.000000,  count: 3
Region 106 Avg IOU: 0.865541, Class: 0.999975, Obj: 0.998804, No Obj: 0.000068, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 82 Avg IOU: 0.925569, Class: 0.999994, Obj: 0.999906, No Obj: 0.006755, .5R: 1.000000, .75R: 1.000000,  count: 3
Region 94 Avg IOU: 0.889068, Class: 0.999977, Obj: 0.999514, No Obj: 0.000378, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 106 Avg IOU: 0.784887, Class: 0.999987, Obj: 0.972072, No Obj: 0.000346, .5R: 1.000000, .75R: 0.750000,  count: 8
Region 82 Avg IOU: 0.927076, Class: 0.999973, Obj: 0.999986, No Obj: 0.004152, .5R: 1.000000, .75R: 1.000000,  count: 3
Region 94 Avg IOU: 0.860546, Class: 0.999991, Obj: 0.994895, No Obj: 0.000454, .5R: 1.000000, .75R: 1.000000,  count: 2
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.920986, Class: 0.999994, Obj: 0.999999, No Obj: 0.001683, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000000, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: 0.922217, Class: 0.999999, Obj: 0.995512, No Obj: 0.000027, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 82 Av

top - 14:33:49 up 2 days, 23:02,  0 users,  load average: 0.12, 0.19, 0.23
Tasks:  17 total,   1 running,  16 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.5 us,  0.5 sy,  0.0 ni, 98.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:  13165744+total, 46507684 used, 85149752 free,  6462388 buffers
KiB Swap: 13386316+total,        0 used, 13386316+free. 19284868 cached Mem

   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
    32 root      20   0  0.109t 0.013t 406088 S  0.0 10.6  25630:16 darknet

# nvidia-smi
Mon Dec 16 14:33:00 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN Xp            Off  | 00000000:18:00.0 Off |                  N/A |
| 31%   52C    P2    60W / 250W |   5735MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN Xp            Off  | 00000000:3B:00.0 Off |                  N/A |
| 23%   31C    P8     9W / 250W |   5409MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  TITAN Xp            Off  | 00000000:5E:00.0 Off |                  N/A |
| 23%   34C    P8     8W / 250W |   5409MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  TITAN Xp            Off  | 00000000:86:00.0 Off |                  N/A |
| 23%   38C    P8     9W / 250W |   5409MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  TITAN Xp            Off  | 00000000:D8:00.0 Off |                  N/A |
| 23%   35C    P8     9W / 250W |     10MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

Thank you..

**Comment by AlexeyAB** [comment]
* What parameters do you use in the Makefile?
* What versions of CUDA, cuDNN and OpenCV do you use?
* What dataset do you use?
* Can you attach your cfg-file?

**Comment by sexyHongGi** [comment]
[Makefile]
GPU=1
CUDNN=1
OPENCV=1
OPENMP=0
DEBUG=0

[version]
CUDA 8.0
cuDNN 5.1
OpenCV 3.2.0

[dataset]
custom food 6 class images

[yolov3_custom.txt](https://github.com/AlexeyAB/darknet/files/3971593/yolov3_custom.txt)

**Comment by AlexeyAB** [comment]
Do you use this code https://github.com/pjreddie/darknet or this https://github.com/AlexeyAB/darknet ?

**Comment by sexyHongGi** [comment]
I used https://github.com/pjreddie/darknet

**Comment by AlexeyAB** [comment]
Use this repository: https://github.com/AlexeyAB/darknet

**Comment by sexyHongGi** [comment]
Are you saying that using this repository will solve my problems?
Can you tell me the difference between the repository?

Thank you!!!
