### ISSUE TITLE
Loss and mAP curve only show a half

### ISSUE THREAD

**Issue by josebenitezg** [AlexeyAB/darknet#4539]
I train with my own data with your repo on p3.16xlarge aws instance, everything going well but the Loss and mAP curve show just a half like the image.

Can you guess what happens?

<img width="752" alt="Captura de Pantalla 2019-12-17 a la(s) 10 50 32" src="https://user-images.githubusercontent.com/58047828/71001128-5bd6d300-20bb-11ea-94cc-bc955c6b7f9a.png">

**Comment by AlexeyAB** [comment]
Try to set there https://github.com/AlexeyAB/darknet/blob/63396082d7e77f4b460bdb2540469f5f1a3c7c48/src/image_opencv.cpp#L1128

or
`if (mjpeg_port > 0) send_mjpeg((mat_cv *)&img, mjpeg_port, 500000, 30); `

or
`if (mjpeg_port > 0) send_mjpeg((mat_cv *)&img, mjpeg_port, 1000000, 100); `

and recompile

**Comment by josebenitezg** [comment]
Works great with 
`if (mjpeg_port > 0) send_mjpeg((mat_cv *)&img, mjpeg_port, 500000, 30);`

Thanks
