### ISSUE TITLE
Yolo trained VGG-16

### ISSUE THREAD

**Issue by jesuspicazo** [AlexeyAB/darknet#454]
Hi, 
I'm doing some study about how certain networks perform in the different frameworks existing. In this paper, https://pjreddie.com/media/files/papers/yolo_1.pdf, we find that yolo was trained using VGG-16 as the network base. I'm aware that in the official yolo page we can find both the VGG-16 .weights and .cfg files to train the classifier, but, would it be possible to download those same files to train yolo detector?  

Thank you very much.

Best regards,

jpicazo

**Comment by AlexeyAB** [comment]
Hi,

First N layers are the same for VGG and Yolo v1.

You can run this command to cut off first 16 layers, that can be used as pre-trained weights from both 
Classifier and Detector:
`darknet.exe partial cfg/vgg-16.cfg vgg-16.weights vgg-16.conv.16 16`

Then you can use weights file `vgg-16.conv.16` to train Classifier or Detector.

But to train very old yolo v1 you should use this very old fork: https://github.com/AlexeyAB/yolo-windows

**Comment by jesuspicazo** [comment]
Hi,
Thanks for your answer. I've used the command you suggested to cut off the first 16 layers of the vgg-16 but the weights file I obtain is very small comared to the original VGG-16 weights file. Is that normal?

Thank you,
