### ISSUE TITLE
Change in Box Probability

### ISSUE THREAD

**Issue by israfila3** [AlexeyAB/darknet#4541]
I am working on custom object detection using YOLO-V3.
Detection rate is very good.
I am detecting small object in ROI from a large image. If ROI is shifted(around 2-10 pixel) in the same image, the detection probability of same object is different.
But when the same object is shifted in different location, the detection probability changes.
Is there any option to maintain same detection probability of a object in different location.

Thank you

**Comment by AlexeyAB** [comment]
Yes, use more training images.

**Comment by HagegeR** [comment]
I think it's linked to #3293, scale_x_y is the fix for that problem

**Comment by AlexeyAB** [comment]
scale_x_y affects on bbox-coordinates (x,y,w,h), but doesn't affect on probability (obj,prob).

**Comment by lsd1994** [comment]
#3672 This may help.

**Comment by israfila3** [comment]
> Yes, use more training images.

I have used 3000 images for one class.
Should i add some more in training data.

**Comment by israfila3** [comment]
My Question is not to increase the probability rate.
But to maintain same probability of same object in different location.
For better understanding i have drawn an image 


![preview](https://user-images.githubusercontent.com/20577227/71155492-3267a400-2281-11ea-805d-56001ea29dd4.png)

- Object detection in ROI of a full Image. In case A,B,C the object is detected correctly with different probability.
- Here Object “Class A” is in same position in A,B,C.
- Only ROI is shifted in different location.
- When the ROI is shifted the Detection Probability changes for same Object.
- Is there any way to maintain the same Detection probability of same object in different location.

NOTE : The Object is same in all the ROI.

**Comment by AlexeyAB** [comment]
Why do you want the same probability?

The only important thing is the probability is above or below the threshold.

**Comment by israfila3** [comment]
Detection Probability of same object in different area in image.
Little Shift in ROI, the detection probability of same object changes.

**Comment by AlexeyAB** [comment]
> Detection Probability of same object in different area in image.
> Little Shift in ROI, the detection probability of same object changes.

This is normal.
