### ISSUE TITLE
SpineNet: Learning Scale-Permuted Backbone for Recognition and Localization

### ISSUE THREAD

**Issue by Kyuuki93** [AlexeyAB/darknet#4547]
I'm trying to implement `SpineNet-49` which based on `Resnet50-FPN`, it's seems only changed order of different scale layers, but I got confused what exactly op is this arrow represent?
<img width="531" alt="image" src="https://user-images.githubusercontent.com/26849480/71152306-004e4600-2271-11ea-95aa-0e4d7e0fbe9a.png">

When parent block size no match to target block, it used a `Resampling operations`,
<img width="252" alt="image" src="https://user-images.githubusercontent.com/26849480/71152350-283da980-2271-11ea-86e0-094709b5ad80.png">

if two blocks was matched, should I simply add to feature map?

**Comment by Kyuuki93** [comment]
For comparison of `spinenet`(fixed, 5 yolo-layers) and `yolov3-spp`(3 yolo-layers), training from scratch with same settings
```
width = 384
height = 384
batch = 96
subdivisions = 16
learning_rate = 0.00025
burn_in = 1000
max_batches = 30200
policy = steps
steps = 15000, 20000, 25000
scales = .1,.1,.1
...
random = 0
iou_loss = giou
iou_normalizer = 0.5
iou_thresh = 0.213
```

| Network | AP@.5 | AP.75 |precision(.7) | recall(.7)|Inference time |
| --- | --- | --- | --- | --- | --- |
| spinenet49-5l|90.46%|53.80%|0.93|0.71|32.17ms|
| spinenet49s-5l|
| spinenet49-3l|
| spinenet49s-3l|
| yolov3-spp|89.98%|54.47%|0.96|0.53|11.77ms|

Fell free to test on your dataset

**Comment by Kyuuki93** [comment]
@AlexeyAB I have fulfill the Table, I think `SpineNet` was searched based on  `RetinaNet`, maybe this network are more suite for `RetinaNet-head` other than `Yolo-head`

**Comment by AlexeyAB** [comment]
@Kyuuki93 Yes, may be, or may be SpineNet will be suitable for more difficult dataset, like MS COCO or ImageNet.

> but I got confused what exactly op is this arrow represent?

I think you did it right, because in FPN these connections are route(concat), then in SpineNet it is also route(concat).

**Comment by RoboEvangelist** [comment]
How is it going? Is SpineNet fully inplemented with YOLOv3? Is there a tensorflow version? If not, is there an opensource version of SpineNet implemented anywhere online? Thanks,

**Comment by hellboy5** [comment]
thanks for the cfg files i was wondering if you have a spinenet-49 version with yolov4-custom.cfg ?

**Comment by AlexeyAB** [comment]
@hellboy5 
Try this: [spinenet49-5l-mish.cfg.txt](https://github.com/AlexeyAB/darknet/files/5081392/spinenet49-5l-mish.cfg.txt)

**Comment by hellboy5** [comment]
> @hellboy5
> Try this: [spinenet49-5l-mish.cfg.txt](https://github.com/AlexeyAB/darknet/files/5081392/spinenet49-5l-mish.cfg.txt)

thanks
