### ISSUE TITLE
unknown error in running yolo_console_dll.exe

### ISSUE THREAD

**Issue by artemSSSS** [AlexeyAB/darknet#455]
I compiled YOLO as dll and tried to run it with yolo_console_dll.exe. But I have this message. 
I used this [simple version](https://github.com/AlexeyAB/darknet/blob/ab1c5f9e57b4175f29a6ef39e7e68987d3e98704/src/yolo_console_dll.cpp#L75) of yolo_console_dll.exe 

It crushes in this line

`Detector detector("yolo-voc.cfg", "yolo-voc.weights");`

I tried different config files with correct weights files from [here](https://pjreddie.com/darknet/yolo/). And it didn't help.

cuda 9.1/opencv242

Please help

![image](https://user-images.githubusercontent.com/37380834/37422819-948141da-27d5-11e8-896c-4fb3fa20c929.png)

**Comment by AlexeyAB** [comment]
1. If you use all files from the last commit, does it work successfully?

----

2. Do you use new last commit, but change only old this `yolo_console_dll.cpp`? https://github.com/AlexeyAB/darknet/blob/ab1c5f9e57b4175f29a6ef39e7e68987d3e98704/src/yolo_console_dll.cpp#L75

Or do you use all files from that old commit? https://github.com/AlexeyAB/darknet/tree/ab1c5f9e57b4175f29a6ef39e7e68987d3e98704

**Comment by artemSSSS** [comment]
thanks
I used last version of yolo_console_dll and it worked just fine
