### ISSUE TITLE
Fine Tuning

### ISSUE THREAD

**Issue by aql315** [AlexeyAB/darknet#4554]
Hi @AlexeyAB A quick question : How do i do fine tuning with classifier ? can you please explain me the steps? Thank you!

**Comment by aql315** [comment]
Hi @AlexeyAB  A quick question : How do i do fine tuning with classifier ? can you please explain me the steps? Thank you!

**Comment by AlexeyAB** [comment]
Just use pre-trained weights.

And read: https://github.com/AlexeyAB/darknet/issues/2139

**Comment by aql315** [comment]
Thank You Very Much @AlexeyAB
