### ISSUE TITLE
why csresnext50-panet-spp is slower than yolov3-spp ?

### ISSUE THREAD

**Issue by syjeon121** [AlexeyAB/darknet#4558]
result(fps)
-----------------
| input | csresnext50-panet-spp | yolov3-spp |
|------| ------| ------| 
| 416 | 43.61 | 61.01 |
| 512 | 35.96 | 50.03 |
| 608 | 29.13 | 37 |

  * Makefile
~~~ 
  1 GPU=1
  2 CUDNN=1
  3 CUDNN_HALF=0
  4 OPENCV=1
  5 AVX=1
  6 OPENMP=1
  7 LIBSO=0
  8 ZED_CAMERA=0

 14 USE_CPP=1
 15 DEBUG=0
 16 
 17 ARCH= -gencode arch=compute_30,code=sm_30 \
 18       -gencode arch=compute_35,code=sm_35 \
 19       -gencode arch=compute_50,code=[sm_50,compute_50] \
 20       -gencode arch=compute_52,code=[sm_52,compute_52] \
 21       -gencode arch=compute_61,code=[sm_61,compute_61]
~~~

* cfg files
[csresnext50-panet-spp.cfg.txt](https://github.com/AlexeyAB/darknet/files/3987703/csresnext50-panet-spp.cfg.txt)
[yolov3-spp.cfg.txt](https://github.com/AlexeyAB/darknet/files/3987704/yolov3-spp.cfg.txt)

* result logs
[csresnext50-panet-spp.txt](https://github.com/AlexeyAB/darknet/files/3987708/csresnext50-panet-spp.txt)
[yolov3-spp.txt](https://github.com/AlexeyAB/darknet/files/3987710/yolov3-spp.txt)

* system info
gpu: gtx titan xp
cpu: AMD Ryzen Threadripper 1950X 16-Core Processor
os: ubuntu

**Comment by WongKinYiu** [comment]
what is ur cudnn version, is it >= 7?

**Comment by syjeon121** [comment]
@WongKinYiu i don't have desktop right now, so i don't know the exact version but it is >= 7

**Comment by WongKinYiu** [comment]
@syjeon121 thanks, 

@AlexeyAB add fix of the code https://github.com/AlexeyAB/darknet/issues/4406#issuecomment-567919052

**Comment by syjeon121** [comment]
@WongKinYiu @AlexeyAB  thanks!

**Comment by ou525** [comment]
![1](https://user-images.githubusercontent.com/23331359/71305645-0e879800-2412-11ea-86ba-c6b3d9597726.png)
How does the shortcut layer handle in different dimensions？@WongKinYiu @AlexeyAB

**Comment by AlexeyAB** [comment]
@ou525 

* The first 64 channels - element wise adding - as for residual-connection (shortcut)
* The last 64 channels - concatenation

**Comment by WongKinYiu** [comment]
@ou525 

there are two common implementations for this case.

The First one:

1. split `-1 layer` into `{ part1:128x128x64, part2:128x128x64 }`.
2. add `from layer` to `part1`.
3. concatenate `part1` and `part2`.

The Second one:

1. do zero padding for `from layer` to make its shape as `128x128x128`.
2. add `padded from layer` to `-1 layer`.

**Comment by dreambit** [comment]
@syjeon121 Hi

I've tested csresnext50-panet-spp and yolov3-spp on CPU, and in my case csresnext50-panet-spp is 20% faster with the same accuracy.

I will test it on GPU, i expect to have the same results(i hope so :)).

**Comment by dreambit** [comment]
@WongKinYiu Yes, on GPU csresnext50-panet-spp is slower

**Comment by AlexeyAB** [comment]
It seems that Grouped/DW-convolutional cannot be well parallelized on hardware-level: 
*  since there is at least XNOR-net optimization on the Tensor Cores with **~5x acceleration**: https://github.com/AlexeyAB/darknet/blob/5f6dced3ce5a4e96224a7974c802a7fde19cc166/src/im2col_kernels.cu#L1316

* but there isn't good acceleration of Grouped/DW-convolution on nVidia Tensor Cores or Google TPU

**Comment by syjeon121** [comment]
@AlexeyAB hi, thank you for your modification

i updated repository for the code you fixed and i tested

i used `./darknet detector test .. -dont_show < images.txt`
text file includes 60 images path and i used last inference time
(input size=608x608, CUDNN_HALF=0, cudnn version=7.6)

csresnext50-panet-spp : 28.4 ms
yolov3-spp: 22.7 ms

is this result okay? i think this result seems to be different from yours 
https://github.com/AlexeyAB/darknet/issues/4406#issuecomment-567919052

**Comment by WongKinYiu** [comment]
@syjeon121 hello,

your inference time of csresnext50-panet-spp is same as the inference time in our report (35 FPS).
i think the result is ok.

maybe u can run several times to take a look the dynamic range of inference time on ur machine.

**Comment by AlexeyAB** [comment]
Check that width=608 height=608 in both cfg-files.

Run several times
`./darknet detector test .. -dont_show < images.txt > log.txt`

Attach log-file for the 2nd run.

Show output of command
`nvidia-smi`

**Comment by syjeon121** [comment]
width=608, height=608 in cfg files 

**csresnext50spp**
[log_csresnext50spp.txt](https://github.com/AlexeyAB/darknet/files/3996994/log_csresnext50spp.txt)
![nvidia-smi-csresnext50spp](https://user-images.githubusercontent.com/43084198/71389998-e7afa880-2641-11ea-82eb-6e9df0f52209.png)

* * *
**yolov3spp**
[log_yolov3spp.txt](https://github.com/AlexeyAB/darknet/files/3996993/log_yolov3spp.txt)
![nvidia-smi-yolov3spp](https://user-images.githubusercontent.com/43084198/71389997-e7afa880-2641-11ea-9a8e-7f99ed3b3200.png)

**Comment by WongKinYiu** [comment]
@syjeon121 wow, the yolov3-spp run really fast on ur machine.

could u help me for test the speed of this model: [csresnet50c-panet-spp.cfg.txt](https://github.com/AlexeyAB/darknet/files/3997217/csresnet50c-panet-spp.cfg.txt).
this model use backbone without group convolution and with panet-spp head.
the computation of this model is similar to csresnext50-panet-spp (105 vs 100 BFLOPs).
i would like to make sure if the speed difference on ur machine and @AlexeyAB 's machine is from group convolution or not.

i have no trained weights for this cfg, so u can just put yolov3-spp.weights for testing the speed of this model.

thanks

**Comment by syjeon121** [comment]
@WongKinYiu thank you for your answer

this model seems to be faster than yolov3spp

[log_csresnext50cspp.txt](https://github.com/AlexeyAB/darknet/files/3997248/log_csresnext50cspp.txt)
![nvidia-smi-csresnext50cspp](https://user-images.githubusercontent.com/43084198/71394614-a2957180-2655-11ea-80ed-ccbb041f9421.png)

**Comment by WongKinYiu** [comment]
@syjeon121 thanks a lot.

well, i think the main difference may be optimization of group convolution for different cuda/cudnn version. the result of yolov3-spp on my machine (1080ti):
![image](https://user-images.githubusercontent.com/12152972/71394866-7296a000-264e-11ea-9970-7143ca90e0cb.png)

**Comment by AlexeyAB** [comment]
@WongKinYiu 

It seems we should not use group convolutions, or should use groups not more than  2 - 4 (may be maximum `groups=8`) for all new GPUs (with Tensor Cores) and newer. 

Most likely the same applies to neurochips and mobile neurochips in smartphones, at least for future neurochips. It should be tested on: https://github.com/ultralytics/yolov3#darknet-conversion

Very wide SIMD-instructions can't accelerate DW/Grouped-convolutions.

Also try to test csresnext50spp on GPU with `Tensor Cores` + `HMB` Tesla/Quadro RTX, if csresnext50spp  will work faster than yolov3-spp then the reason in the low VRAM-bandwidth (disbalance - too high performance of Tensor Cores and too low bandwidth of GPU-VRAM).
