### ISSUE TITLE
can we run video demo without opencv?

### ISSUE THREAD

**Issue by anandkoirala** [AlexeyAB/darknet#456]
@AlexeyAB 
i am on red-hat linux and built opencv with ffmpeg support but still i get the error of function (cvNamedWindow) not implemented which comes from opencv-3.4.0/modules/highgui/src/window.cpp, line 593.  
I also tried to just save the detection video but the same error...
Is it possible to run the demo video without OpenCV support?
Thanks
Anand

**Comment by sivagnanamn** [comment]
Currently, it is not possible to run the demo without OpenCV.

Looks like you've built OpenCV without GTK. 

Could you please confirm whether you enabled the following while installing OpenCV?

`-D WITH_QT=ON -D WITH_GTK=ON -D WITH_OPENGL=ON`

Before doing the above, make sure you have gtk-dev (`libgtk2.0-dev` package) installed.

**Comment by AlexeyAB** [comment]
@anandkoirala You can't run video demo without opencv. 

You should compile OpenCV: `WITH_GTK=ON` or `WITH_QT=ON`
