### ISSUE TITLE
multiple detections

### ISSUE THREAD

**Issue by stephanecharette** [AlexeyAB/darknet#4569]
I updated darknet for the first time in maybe 2 months, and I'm seeing something new that didn't used to happen before.  In nearly all the images and projects, I get several overlapping bounding boxes.  Sometimes only 2, but often 3 or more, like this:

![image](https://user-images.githubusercontent.com/5061352/71326859-63c8b580-24b5-11ea-8b7a-ae9906728aa5.png)

Is there something obvious that you know which has changed in the last 2 months that would cause this?

**Comment by AlexeyAB** [comment]
* It seems for some reason NMS does not work for you, did you disable it?
* What did you chage in the code?
* Did you train with old or new repo?
* What cfg-file do you use?

**Comment by stephanecharette** [comment]
No, I'm still using the same nms I've always used.  Looking at that code, the last time I modified it was back in August:

```
r2802 2019-08-21 03:49:34 (Wed, 21 Aug 2019) 	// pick some reasonable default values
r2802 2019-08-21 03:49:34 (Wed, 21 Aug 2019) 	threshold = 0.5f;
r2802 2019-08-21 03:49:34 (Wed, 21 Aug 2019) 	hierchy_threshold = 0.5f;
r2802 2019-08-21 03:49:34 (Wed, 21 Aug 2019) 	non_maximal_suppression_threshold = 0.45f;
```

The only change I've made to darknet is to the makefile.

On the computer where I'm doing the training with the GPU:
```
-GPU=0
-CUDNN=0
-CUDNN_HALF=0
-OPENCV=0
+GPU=1
+CUDNN=1
+CUDNN_HALF=1
+OPENCV=1
 AVX=0
-OPENMP=0
-LIBSO=0
+OPENMP=1
+LIBSO=1
```

On the computer where I'm viewing the results (which has no GPU):
```
 GPU=0
 CUDNN=0
 CUDNN_HALF=0
-OPENCV=0
+OPENCV=1
 AVX=0
-OPENMP=0
-LIBSO=0
+OPENMP=1
+LIBSO=1
 ZED_CAMERA=0
```
I trained with the new repo.
Cfg is based on yolov3-tiny.  Will attach the .cfg.

[dogs-vs-cats_yolov3-tiny.cfg.txt](https://github.com/AlexeyAB/darknet/files/3993058/dogs-vs-cats_yolov3-tiny.cfg.txt)

**Comment by AlexeyAB** [comment]
It seems that some of your changes conflict with my changes.
Look at NMS.

> Is there something obvious that you know which has changed in the last 2 months that would cause this?


A huge number of changes were made here, new nms algorithms, new training parameters (iou_thresh= to use more than 1 anchor per 1 object), and much more were added. But all of them should influence only if you explicitly specify them in the cfg file.

**Comment by stephanecharette** [comment]
I'm confused as to what you mean.  I've not changed the darknet code, except for the makefile where I enable/disable the GPU.  I'm linking against libdarknet.so.

What NMS are you telling me to look at?  Is there some example code to show how it should be called?  The `darknet.h` file has no comments, just this one line:

```
LIB_API detection *get_network_boxes(network *net, int w, int h, float thresh, float hier, int *map, int relative, int *num, int letter);
```

I can see this being called from 4 source files:  detector.c, demo.c, yolo_v2_class.cpp, network.c.

Is there something better/different I should be calling, or have the meaning/usage of the parameters changed?  Sorry for the trouble, Alexey.  Thanks in advance for pointing me to the correct code.

**Comment by AlexeyAB** [comment]
Since you use Darknet as library so you should call NMS in your code, just as in examples: https://github.com/AlexeyAB/darknet/blob/master/darknet.py#L271-L272

**Comment by stephanecharette** [comment]
Yes, my code already has that, it isn't new.  This is how the code has been since mid-August:

```
	image img = convert_opencv_mat_to_darknet_image(resized_image);
	float * X = img.data;
	network_predict(*nw, X);
	int nboxes = 0;
	const int use_letterbox = 0;
	auto darknet_results = get_network_boxes(nw, original_image.cols, original_image.rows, threshold, hierarchy_threshold, 0, 1, &nboxes, use_letterbox);
	if (non_maximal_suppression_threshold)
	{
		auto nw_layer = nw->layers[nw->n - 1];
		do_nms_sort(darknet_results, nboxes, nw_layer.classes, non_maximal_suppression_threshold);
	}
```

This seems to match the code in detector.c (around lines 1496-1504).  Unless I misunderstood your previous message and you're telling me I should use `diounms_sort()` instead of `do_nms_sort()`?

Note this code used to work until I did a git pull.

**Comment by AlexeyAB** [comment]
Just run the same model by using Darknet without your code. If result is good, then the issue is in your code.

**Comment by stephanecharette** [comment]
Trying to debug into the code.  In `draw_detections_v3()`, one of the first calls is to a function `get_actual_detections()`.  This returns the number of results to consider.  So for example with the image at the start of this post, of the 3 results from `get_network_boxes()`, the function `get_actual_detections()` returns 1.

But this function isn't exposed in darknet.h.  So I'm curious to know how callers know that of the 3 results, only 1 should be considered.  The other thing I'm thinking is maybe I'm calling this incorrectly, and there is a different set of APIs I should be calling instead.

**Comment by stephanecharette** [comment]
Nevermind, this can be closed, I found a way to get this working.
