### ISSUE TITLE
YOLOv3 CPU detection dosen't works from the December 23

### ISSUE THREAD

**Issue by shinfo001** [AlexeyAB/darknet#4577]
making "libdarknet.so" use CPU=0　and make,and run "darknet.py" 

ex.
result=darknet.performDetect(...
　

result case1  ,using git master-blanch source cloned on December 18

result=[('open_flower', 0.8256576061248779, (857.5316772460938, 435.72723388671875, 443.58740234375, 256.4634094238281)), ('open_flower', 0.4159958064556122, (1166.4818115234375, 717.420166015625, 259.23468017578125, 225.4882354736328))]

result case2 , using git master-blanch source cloned on December 23

result=[]

**Comment by AlexeyAB** [comment]
@shinfo001 I fixed it: https://github.com/AlexeyAB/darknet/commit/f64746107d057a958d96cc0b118ad3eae78a2a91
