### ISSUE TITLE
warning about parse cfg file

### ISSUE THREAD

**Issue by lq0104** [AlexeyAB/darknet#4599]
Hi @AlexeyAB 
In parse.c file and parse_network_cfg_custom function there is a if condition statement:
https://github.com/AlexeyAB/darknet/blob/dcfeea30f195e0ca1210d580cac8b91b6beaf3f7/src/parser.c#L1404-L1406
I want to know if my network is just downsample 4 scale(reduce 16 times), then should I need to set network width and height as 32 multiple or not? Thank you!

**Comment by AlexeyAB** [comment]
> I want to know if my network is just downsample 4 scale(reduce 16 times), then should I need to set network width and height as 32 multiple or not?

No.

There is message only for **default** Yolo v1/v2/v3.

**Comment by lq0104** [comment]
I get it, thank you again!
