### ISSUE TITLE
-nogpu not work

### ISSUE THREAD

**Issue by gino0717** [AlexeyAB/darknet#46]
if i call
`darknet_no_gpu.exe detector test data/coco.data tiny-yolo-voc.cfg tiny-yolo-voc.weights data/person.jpg -i 10.0
`

![predictions](https://cloud.githubusercontent.com/assets/14192168/24282739/6c88f58e-109c-11e7-9f41-9a2869784a8a.jpg)

The result is good, however,since my gpu can work in training but alway out of memory when detection, I build the darknet in gpu. If I call the nogpu function in normal darknet:

`darknet.exe -nogpu detector test data/coco.data tiny-yolo-voc.cfg tiny-yolo-voc.weights data/person.jpg -i 10.0`
it would be all miserable
![predictions2](https://cloud.githubusercontent.com/assets/14192168/24282863/0771b19e-109d-11e7-8b76-3270ad1080d4.jpg)

**Comment by AlexeyAB** [comment]
This is strange: `darknet.exe -nogpu detector test data/coco.data tiny-yolo-voc.cfg tiny-yolo-voc.weights data/person.jpg -i 10.0`

* -i 10.0` - this is number of GPU, why do you use float value 10.0?
* `data/coco.data` - this is `.data`-file for COCO cfg & weight, but you use it together with VOC-`.cfg` & `.weights` files
* if Out of memory occurs, then increase `subdivision=64`: https://github.com/AlexeyAB/darknet/blob/47409529d0eb935fa7bafbe2b3484431117269f5/cfg/yolo-voc.cfg#L3

**Comment by AlexeyAB** [comment]
Parameter `-nogpu` doesn't work.

* To detect without GPU use: `darknet.exe detector test data/coco.data yolo.cfg yolo.weights -i 0 -thresh 0.5 data/dog.jpg`

* To detect with GPU use: `darknet_no_gpu.exe detector test data/coco.data yolo.cfg yolo.weights -thresh 0.5 data/dog.jpg`
