### ISSUE TITLE
URL http://ip-address:8090 is not opening

### ISSUE THREAD

**Issue by adavradou** [AlexeyAB/darknet#4602]
I am trying to train YoloV3 using mAP on Colab. I am using the following command: 
`! ./darknet detector train data/obj.data cfg/yolo-obj.cfg darknet53.conv.74 -dont_show -mjpeg_port 8090 -map`

However, when I try to open the URL http://ip-address:8090 on chrome, it says "This site can't be reached". I tried firefox as well. 
The chart.png is saved without a problem. 
Do you know how to solve this? 

Thanks in advance.

**Comment by bagminer** [comment]
Just checking, if you are using correct IP address. Usually IP addresses for colab are in range of `35.*.*.*`

**Comment by adavradou** [comment]
You were right, I wasn't! 
I used the command `!curl ipecho.net/plain` and I got the IP address: 34.90.143.197.

However, I still cannot reach http://ip-address:34.90.143.197.

Thanks a lot for response.

**Comment by AlexeyAB** [comment]
Use http://34.90.143.197:8090

**Comment by adavradou** [comment]
@AlexeyAB I tried multiple times before answering, in order to be sure.. Unfortunately I still get the message "This site can't be reached".

**Comment by AlexeyAB** [comment]
Show 2 screenshots:

> I used the command !curl ipecho.net/plain and I got the IP address: 34.90.143.197.

1. Show screenshot

> Unfortunately I still get the message "This site can't be reached".

2. Show screenshot

**Comment by AlexeyAB** [comment]
> Colab backends are firewalled and cannot be directly contacted from the public Internet. 

https://stackoverflow.com/questions/56473719/open-port-on-google-colaboratory-machine

**Comment by adavradou** [comment]
I didn't know. Thank you very much for your help!
