### ISSUE TITLE
how to setup "csresnext50-panet-spp.cfg" file for the training of custom objects? 

### ISSUE THREAD

**Issue by DhruvGamdha** [AlexeyAB/darknet#4604]

**Comment by AlexeyAB** [comment]
All the same: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

Use this pre-trained weights-file: https://drive.google.com/file/d/16yMYCLQTY_oDlCIZPfn_sab6KD3zgzGq/view?usp=sharing

**Comment by DhruvGamdha** [comment]
Thank you for the help!
