### ISSUE TITLE
Detecting images on android? how to process the output?

### ISSUE THREAD

**Issue by khushit-shah** [AlexeyAB/darknet#4609]
I wanted to run yolov3-tiny on android so, I converted into TensorFlow lite model.
I am passing the `416 x 416` image buffer as input.
As the output, I got an array of `215475` elements and output shape of `[1, 2535, 85]`.
What do I do now? What do `215475` elements contain?

Thanks.

**Comment by AlexeyAB** [comment]
You should get `[batch, anchors, (num_of_classes + 5) x height x width]`

```cpp
int class0_probability_index = entry_index(l, b, n*l.w*l.h + j*l.w + i, 4 + 1); // class-0 probability
int objectness_index = entry_index(l, b, n*l.w*l.h + j*l.w + i, 4); // objectness
int box_index = entry_index(l, b, n*l.w*l.h + j*l.w + i, 0); // x,y,w,h
```

```cpp
static int entry_index(layer l, int batch, int location, int entry)
{
    int n =   location / (l.w*l.h);
    int loc = location % (l.w*l.h);
    return batch*l.outputs + n*l.w*l.h*(4+l.classes+1) + entry*l.w*l.h + loc;
}
```

----

How to get detections: https://github.com/AlexeyAB/darknet/blob/489ea7fdce771144c3ef39d870926c71a1587af5/src/yolo_layer.c#L692-L725
https://github.com/AlexeyAB/darknet/blob/489ea7fdce771144c3ef39d870926c71a1587af5/src/yolo_layer.c#L116-L129

**Comment by xinyee1997** [comment]
@khushit-shah  do you solve the problem? I run use tensorflow android to run yolo tiny too. But there is no result at all. Do u know why ?

**Comment by khushit-shah** [comment]
I used SSD mobilenet, it works and even faster than yolo on mobile, with inference of only 150ms. There is a tensorflow example for it in tensorflows "example" GitHub repo

**Comment by xinyee1997** [comment]
@khushit-shah  did you train ur custom model?
