### ISSUE TITLE
Which models are supported in opencv?

### ISSUE THREAD

**Issue by arnoldhoward** [AlexeyAB/darknet#4619]
Many new cfg files have been updated recently in this repository.
Can you tell me whether opencv supports them or not?
If yes, how to implements it with opencv ? Is it same with using yolov3 ?
For example, csresnext50-panet-spp.cfg, yolov3-tiny-prn.cfg, enet-coco.cfg (EfficientNetB0-Yolov3) and so on. 
I need your opinion.
Thanks.

**Comment by AlexeyAB** [comment]
Only yolov3-tiny-prn.cfg is supported by OpenCV-dnn currently.

**Comment by arnoldhoward** [comment]
which opencv version ?
I tried yolov3-tiny-prn in 3.4.5, but failed.

**Comment by AlexeyAB** [comment]
OpenCV 4.2.0 https://opencv.org/releases/

**Comment by arnoldhoward** [comment]
ok, thanks.
have u any plan to integrate new models in opencv ?

**Comment by AlexeyAB** [comment]
Yes, but first I plan to add even newer models.

**Comment by arnoldhoward** [comment]
Thanks for your helpness.
