### ISSUE TITLE
use particular classes from pre-trained model 

### ISSUE THREAD

**Issue by artemSSSS** [AlexeyAB/darknet#462]
It is possible to detect only 4-5 classes of objects in video using pre-trained model? I know that I can modify yolo_console_dll.exe and ignore objects that I don't need but it isn't optimal. Maybe I can change config file somehow and detect objects that I need and will work faster. Is it possible or I can do this only with my trained model? Answer please

**Comment by AlexeyAB** [comment]
* No, you can't change cfg-file without changing weights file.
* Speed doesn't depend on number of classes
* Only precision depends on number of classes and only if you will train from the begining (using or not using pre-trained weights)

**Comment by artemSSSS** [comment]
ok
thanks a lot
