### ISSUE TITLE
Detecting Four corners

### ISSUE THREAD

**Issue by LukeAI** [AlexeyAB/darknet#4621]
Does anybody know of some algorithm or detection head that can detect, not just a rectangular bounding box perpendicular to the edge of the frame (x,y,w,h) but four corners of an arbitrary quadrilateral? (x0,y0,x1,y1,x2,y2,x3,y3)

How difficult might it be to adapt YOLO to do this?

I have a large dataset with such a labelling scheme which I would love to be able to detect with.

**Comment by blackwool** [comment]
I think you need to write a program to change for each label files

**Comment by haviduck** [comment]
Opencv can handle that. Found a Quick c++ example
[Quadrilateral detection](https://www.opencv-srf.com/2011/09/object-detection-tracking-using-contours.html?m=1)
