### ISSUE TITLE
How to calculate various model speed in FPS for my GPU?

### ISSUE THREAD

**Issue by Andropogon** [AlexeyAB/darknet#4627]
Hello,

I want to create a similar chart like this:
![image](https://user-images.githubusercontent.com/37939170/71768556-4a912180-2f17-11ea-9feb-042884775714.png)

For my GPU and various models. How can I calculate the speed of the model in FPS? 
I have tried to do this that way, but I don't know that it has sense and is correct:

I run mAP calculation for my validation-set and get this information in the output: 
![image](https://user-images.githubusercontent.com/37939170/71768612-d60ab280-2f17-11ea-88b2-2aef0737d101.png)

So if I have in my validation-set 300 of images, that model speed = 300/28 = 10,71 FPS

Is it correct or not :D ?

**Comment by AlexeyAB** [comment]
@Andropogon Hi,

> Is it correct or not :D ?

No, it is limited by your HDD/SSD-disk and many other features.

The simplest way - run detection on low-resolution video with flag `-dont_show`.
Just get any test.mp4 / test.avi file with resolution lower than FullHD (1920x1080)
and run command:
`./darknet detector demo obj.data yolo.cfg yolo.weights test.mp4 -dont_show`
And look at the FPS

----

Later I will add another flag for benchmarking models - for more accurate FPS measurement

**Comment by Andropogon** [comment]
> @Andropogon Hi,
> 
> > Is it correct or not :D ?
> 
> No, it is limited by your HDD/SSD-disk and many other features.
> 
> The simplest way - run detection on low-resolution video with flag `-dont_show`.
> Just get any test.mp4 / test.avi file with resolution lower than FullHD (1920x1080)
> and run command:
> `./darknet detector demo obj.data yolo.cfg yolo.weights test.mp4 -dont_show`
> And look at the FPS
> 
> Later I will add another flag for benchmarking models - for more accurate FPS measurement

Ok, thanks. I was trying to do that this way but the results were for example from 8FPS to 32FPS, so I was wondering that maybe is there any more "averaged" method. But as I understand it is in "to do".

**Comment by AlexeyAB** [comment]
@Andropogon 
I added `-benchmark` flag for detector demo, now you can use command https://github.com/AlexeyAB/darknet/commit/2652263727a7036dfb587fbda98bd30181d8a616

`./darknet detector demo obj.data yolo.cfg yolo.weights test.mp4 -benchmark`

But for very fast models the bottleneck will be in the Video Capturing from file/camera, or in Video Showing (you can disable showing by using `-dont_show` flag).

**Comment by Andropogon** [comment]
Thanks @AlexeyAB you are really fast :) like YOLO-Tiny! 🥇

**Comment by Andropogon** [comment]
@AlexeyAB 
I think that something is wrong with this `-benchmark` flag because when I am using it I am not getting any detections:
`./darknet detector demo .\data\obj_cl.data .\yolo-obj_cl.cfg .\backup_cl\yolo-obj_cl_best.weights .\video\zatoka2.MP4 -benchmark`

Fragment of output (the whole output is without detections, not only this example frames):
![image](https://user-images.githubusercontent.com/37939170/71896520-49990380-3154-11ea-8c94-d729fd00868c.png)

But without this flag, after your last update, we are getting always in demo AVG_FPS. By normal command:
`./darknet detector demo .\data\obj_cl.data .\yolo-obj_cl.cfg .\backup_cl\yolo-obj_cl_best.weights .\video\zatoka2.MP4`

Output for this cmd:
![image](https://user-images.githubusercontent.com/37939170/71896653-a5638c80-3154-11ea-8a80-4da185a6e27e.png)

So for me, everything is fine (I am getting AVG_FPS), but I don't know what this `-benchmark` flag should do and I think that it is not working correctly.

**Comment by AlexeyAB** [comment]
This is normal. Benchamrk disables the most features (video-capturing, drawing, showing, ...) except network-inference.

**Comment by karthika95** [comment]
How do I find the FPS while testing any general object detection model on a dataset?

**Comment by nisarggandhewar** [comment]
I would like to share my experience on YOLOv4, I have run YOLOv4 on Google colab platform.

I train SVT dataset for text detection over my laptop with GTX 1650 GPU with 4GB VRAM and got result as

MAP=52 and AP=59.

I train same SVT dataset for text detection over google colab with Tesla K80 GPU with 12GB VRAM and got result as

MAP=52 and AP=65.93.

here my Question is as i have only 1 class, so MAP=AP but in actual why it is different.

as MAP for YOLOV3 and YOLOV4 is same, so for my dataset, can i say accuracy for V3 and V4 are same.

But when I tested same image on V3 and V4 then confidence in V4 is better than V3.

So I confused which one is better V3 or V4 for my dataset.

**Comment by AlexeyAB** [comment]
> here my Question is as i have only 1 class, so MAP=AP but in actual why it is different.

Show fullscreen screenshot

**Comment by nisarggandhewar** [comment]
Ist YOLOV3
![yolov3](https://user-images.githubusercontent.com/43102697/82815460-e0bde800-9eb6-11ea-95be-80031ad68c8a.png)

Its YOLOV4
![yolov4](https://user-images.githubusercontent.com/43102697/82815513-f6331200-9eb6-11ea-8a0a-77d39c9a45f3.png)

**Comment by AlexeyAB** [comment]
Where do you see mAP=52?


> MAP=52 and AP=65.93.
> 
> here my Question is as i have only 1 class, so MAP=AP but in actual why it is different.

> Its YOLOV4
> ![yolov4](https://user-images.githubusercontent.com/43102697/82815513-f6331200-9eb6-11ea-8a0a-77d39c9a45f3.png)

**Comment by nisarggandhewar** [comment]
> 
> 
> Where do you see mAP=52?
> 
> > MAP=52 and AP=65.93.
> > here my Question is as i have only 1 class, so MAP=AP but in actual why it is different.
> 
> > Its YOLOV4
> > ![yolov4](https://user-images.githubusercontent.com/43102697/82815513-f6331200-9eb6-11ea-8a0a-77d39c9a45f3.png)

![yolov4](https://user-images.githubusercontent.com/43102697/82819539-27fba700-9ebe-11ea-892a-195ee1d03ac0.png)

**Comment by AlexeyAB** [comment]
52 is a number of images in your validation dataset

![82819539-27fba700-9ebe-11ea-892a-195ee1d03ac0](https://user-images.githubusercontent.com/4096485/82820367-b2d2a680-9eaa-11ea-9a1c-fabbb8d94a6f.png)

**Comment by nisarggandhewar** [comment]
Yes sir, its my mistake, I referred different value. It's 65.93%.
Thanks for correcting me.
