### ISSUE TITLE
video upside down

### ISSUE THREAD

**Issue by jackwei0117** [AlexeyAB/darknet#463]
Hi AlexyeAB,

Some of my video are recorded upside down, I'm able to rotate them by other software.
However, they're still upside down in darknet.
I guess this is probably because of the metadata in video.
Would you please show me where to fix this?
Thank you.

**Comment by AlexeyAB** [comment]
Hi @jackwei0117,

Try to add this line `cvFlip(new_img, new_img, 1);`
after this line: https://github.com/AlexeyAB/darknet/blob/371f21171a2606b4ad5f60651ed6f63cb8d08d99/src/image.c#L689
