### ISSUE TITLE
How to use newly proposed SlimYOLOv3?

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [AlexeyAB/darknet#4635]
Hi,
    have you tried to run newly proposed SlimYOLOv3 in this repo? They have explained to use it in the original darknet repo but I am not sure weather it can use in the repo or not?  Have you tried it? if yes then can you explain the procedure please? 

https://github.com/PengyiZhang/SlimYOLOv3

**Comment by zpmmehrdad** [comment]
@MuhammadAsadJaved Hi,

You can read about it: [3732](https://github.com/AlexeyAB/darknet/issues/3732)

**Comment by MuhammadAsadJaved** [comment]
@zpmmehrdad   Thank you so much. stay blessed.
