### ISSUE TITLE
How did YOLO resize images ?

### ISSUE THREAD

**Issue by phongnhhn92** [AlexeyAB/darknet#464]
Hello guys, I have a question, not a issue though.
I am wondering how did YOLO resize images ? For example, if the my input image's size is 1280 x 720 px and the input size of YOLO is 640x640 px. Then what kind a technique did YOLO use to resize not a square image to a square one ? In this case the aspect ratio between the original image and resized image will be different then how did YOLO resize the ground-truth bounding box as well. I hope you guys can help me to understand it clearly. Thanks

**Comment by AlexeyAB** [comment]
In general, there are 3 ways how to do resize - and each of them has advantages and disadvantages: https://github.com/AlexeyAB/darknet/issues/232#issuecomment-336955485

For example, if all your training and test images have a resolution of 1920x1080, then they will be resized to 416x416 with identical distortions, so keeping aspect ratios is not required - detection will work fine.

I will add keeping aspect ratio.
