### ISSUE TITLE
 training classification by multi gpus error :invalid device ordinal: File exists

### ISSUE THREAD

**Issue by lunasdejavu** [AlexeyAB/darknet#4641]
I am trying to train classificaion of a custom darknet.
the cfg is:
https://gist.github.com/lunasdejavu/a59c61c2960ed5111d4df052e356aff5
I want to train on multi gpus by  -gpus 0,1,2,3,4
then the errors shows up:
seen 64
Done! Loaded 16 layers from weights-file
CUDA status Error: file: ./src/dark_cuda.c : () : line: 36 : build time: Jan  6 2020 - 10:28:56
CUDA Error: invalid device ordinal
CUDA Error: invalid device ordinal: File exists
darknet: ./src/utils.c:297: error: Assertion `0' failed.
Aborted

**Comment by lunasdejavu** [comment]
I used the command `unset CUDA_VISIBLE_DEVICES` first
for the first training, but it is not working for the second training.

**Comment by AlexeyAB** [comment]
Show output of command
`nvidia-smi`

**Comment by lunasdejavu** [comment]
> Show output of command
> `nvidia-smi`

thanks ! one of the gpus is broken....

**Comment by aidamanzano** [comment]
Hi I have this same issue. When I run `./darknet detector train data/obj.data cfg/yolo-obj.cfg cfg/yolov4.conv.137 -gpus 0,1
`
I get: `[yolo] params: iou loss: ciou (4), iou_norm: 0.07, cls_norm: 1.00, scale_x_y: 1.05
nms_kind: greedynms (1), beta = 0.600000 
Total BFLOPS 128.148 
avg_outputs = 1062779 
 Allocate additional workspace_size = 106.46 MB 
Loading weights from cfg/yolov4.conv.137...
 seen 64, trained: 0 K-images (0 Kilo-batches_64) 
Done! Loaded 137 layers from weights-file 
CUDA status Error: file: /home/aida/darknet/src/dark_cuda.c : () : line: 39 : build time: May 20 2020 - 20:13:37 

 CUDA Error: invalid device ordinal
CUDA Error: invalid device ordinal: File exists`

my output of the command `nvidia-smi` is `Wed May 20 21:36:59 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 440.82       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 207...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   44C    P8     5W /  N/A |   1229MiB /  7982MiB |      9%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1544      G   /usr/lib/xorg/Xorg                           685MiB |
|    0      1719      G   /usr/bin/gnome-shell                         529MiB |
|    0      3745      G   /usr/lib/firefox/firefox                       2MiB |
|    0      6691      G   /usr/bin/python3                               3MiB |
|    0     21208      G   /usr/lib/firefox/firefox                       2MiB |
|    0     24127      G   /usr/bin/python3                               3MiB |
+-----------------------------------------------------------------------------+
`
How do I fix this please?

**Comment by AlexeyAB** [comment]
@aidamanzano You have only 1 GPU )

**Comment by ald2004** [comment]
only u can buy o qu xi jing...
