### ISSUE TITLE
In training

### ISSUE THREAD

**Issue by yehaizi1995** [AlexeyAB/darknet#4653]
when i train my own dataset,the dataset'size is 640*640,when i use the random,it will occur this erro:CUDA Error Prev: an illegal memory access was encountered .but when i close random,set it to 0,it  can train.i don't know how to solve it.please give me some advice ,thank you very much first.

**Comment by AlexeyAB** [comment]
This bug is fixed: https://github.com/AlexeyAB/darknet/issues/4647

**Comment by yehaizi1995** [comment]
> This bug is fixed: #4647

 With your help I have solved this problem, thank you very much!
