### ISSUE TITLE
uDNN Error: CUDNN_STATUS_BAD_PARAM | current version

### ISSUE THREAD

**Issue by VisionEp1** [AlexeyAB/darknet#4656]
Hi i just downloaded and recompilled the current repo.

I still get a error:
Resizing
480 x 480
15 15, 16 16

 cuDNN status Error in: file: C:\...\darknet-master\src\convolutional_layer.c : cudnn_convolutional_setup() : line: 250 : build time: Jan  9 2020 - 11:40:26
cuDNN Error: CUDNN_STATUS_BAD_PARAM
cuDNN Error: CUDNN_STATUS_BAD_PARAM: No error

**Comment by AlexeyAB** [comment]
Attach your cfg-file
What command do you use?
And show screenshot of this error

**Comment by VisionEp1** [comment]
Sure i use the standard train command:
(darknet.exe detector train ..data ..cfg -map) with no pretrained weights.

I attached the cfg file
[yolov3-tiny2-costum.cfg.txt](https://github.com/AlexeyAB/darknet/files/4040041/yolov3-tiny2-costum.cfg.txt)
(i tested random = 0 or =1 the previus error is with random=1 you have to re set it)


Some more infos:
**If i remove random=1 i can train for a bit and then it throws another error:**

>  calculation mAP (mean average precision)...
> 4CUDA Error Prev: an illegal memory access was encountered
> 
> CUDA Error Prev: an illegal memory access was encountered: No error

If i change the network size it wont load the network ? Is there something wrong with the config file?
But even then it should not crash with random =0 

I used this config file previuosly with success.

error with random=1: (direct at start)
![image](https://user-images.githubusercontent.com/19327424/72062680-90b00180-32d8-11ea-8d5e-c947a7374a10.png)

error with random = 0 (after some time/at map calculation):
![image](https://user-images.githubusercontent.com/19327424/72062730-a9201c00-32d8-11ea-8efd-d4a342a180c4.png)

**Comment by VisionEp1** [comment]
i tested with 1 gpu and with 4 (all 2080ti) no differences

**Comment by VisionEp1** [comment]
if i can help you with any testing let me know

**Comment by AlexeyAB** [comment]
Download new Darknet version.
Also set
```
[net]
batch=64
subdivisions=2
width=384
height=384
```

since you use 7 subsampling layers (with stride=2) the you the network resolution should be multiple of `128` = pow(2, 7)

**Comment by VisionEp1** [comment]
Hi i used the new code + changed the cfg.

It now starts to train (with random=1) but crashes after few min with:

![image](https://user-images.githubusercontent.com/19327424/72088748-19e02c00-330b-11ea-92a5-c56ed75da388.png)

so it's better but not "fixed" i think

**Comment by VisionEp1** [comment]
i see that it says resizing 352 which is also not a multiple of 128?
(i changed the newtork cfg to batch=64
subdivisions=2
width=384
height=384
maybe thats a hint)

**Comment by AlexeyAB** [comment]
Yes, also set 
```
[net]
resize_step=128
```

**Comment by VisionEp1** [comment]
thanks a lot like always! your're the best.

it's training now and works so far i think you can close the issue

btw.
Is there any way to support your work? (donation)

**Comment by AlexeyAB** [comment]
`Sponsor` button at the top
