### ISSUE TITLE
Referencing netron tool

### ISSUE THREAD

**Issue by HagegeR** [AlexeyAB/darknet#4660]
Hi @AlexeyAB ,

After a period of inactivity I've seen that the tool by @lutzroeder has greatly improved and features almost all of the additions you've made over the original darknet.

I think it would benefit a lot of users to know about the visualization tool, so maybe you can refer to it in the readme?

also If you think about any new feature that isn't in the tool, hopefully I can help to add it...

**Comment by AlexeyAB** [comment]
@HagegeR Hi,

It is already there: https://github.com/AlexeyAB/darknet#yolo-v3-in-other-frameworks

**Comment by HagegeR** [comment]
sorry, didn't see that, what about features?

**Comment by AlexeyAB** [comment]
@HagegeR Thanks! I will test it later.

**Comment by HagegeR** [comment]
can you test it now? the new shortcut feature has been implemented, please tell if something is wrong
