### ISSUE TITLE
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""

### ISSUE THREAD

**Issue by brian208579** [AlexeyAB/darknet#4661]
Hi @AlexeyAB 
When I execute :
darknet.exe detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg
I got this error :
**qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.**

![problem](https://user-images.githubusercontent.com/43407888/72101940-cac4e600-3360-11ea-84b0-0f9c52b5392c.png)

Could you please give me some suggestions 
Thank you

**Comment by AlexeyAB** [comment]
* Do you use this repository?
* Did you use for building Darknet
    * vcpkg?
    * or cmake?
    * or darknet.sln with MSVS?
* How did you install OpenCV?

**Comment by brian208579** [comment]
@AlexeyAB
Because of your reminder , I reinstall the opencv and ues cmake building Darknet
I have figured out the problem
Thanks so much ...
