### ISSUE TITLE
Floating point exception (core dumped) after "weighted [shortcut] layer" commit 

### ISSUE THREAD

**Issue by KEGustafsson** [AlexeyAB/darknet#4663]
Yolov3 gives "Floating point exception (core dumped)" after "weighted [shortcut] layer" commit [9bd88d7](https://github.com/AlexeyAB/darknet/commit/9bd88d7fd7cef872998aa931f8280a1ba1578822).

E.g. following test fails.
 ./darknet detect cfg/yolov3.cfg yolov3.weights data/dog.jpg

Before that commit everything is OK.

**Comment by AlexeyAB** [comment]
Try to use the latest commit.

I can't reproduce this issue:

![image](https://user-images.githubusercontent.com/4096485/72112845-e4a9fd00-334f-11ea-9b19-fc2807addbff.png)

**Comment by KEGustafsson** [comment]
I tried and last working is the one before that commit. I tested with Ubuntu 18.04 LTS and latest Alpine linux.

**Comment by AlexeyAB** [comment]
Did you try this commit? https://github.com/AlexeyAB/darknet/commit/2116cba1ed123b38b432d7d8b9a2c235372fd553

Can you show screenshot of the error with this commit?

What params do you use in the Makefile?

**Comment by KEGustafsson** [comment]
With the latest commit I got following results with Alpine Linux (OPENMP=1 and LIBSO=1).

- Trial 1
Loading weights from /root/yolov3.weights...
 seen 64
Done! Loaded 107 layers from weights-file
Arithmetic exception (core dumped)

- Trial 2
Loading weights from /root/yolov3-tiny.weights...
 seen 64
Done! Loaded 24 layers from weights-file
data/dog.jpg: Predicted in 220.242000 milli-seconds.
dog: 81%
bicycle: 38%
car: 71%
truck: 42%
truck: 62%
car: 40%
Not compiled with OpenCV, saving to predictions.png instead

**Comment by qwe7922142** [comment]
I have a similar problem，in shortcut_multilayer_cpu will meet"0xC0000094: Integer division by zero。"

**Comment by AlexeyAB** [comment]
@KEGustafsson @qwe7922142 I fixed this bug: https://github.com/AlexeyAB/darknet/commit/619e39fc71a7c65f9d33aaca8ec05167796e88aa

**Comment by KEGustafsson** [comment]
Tested and working!
