### ISSUE TITLE
Training with mAP, but it is not shown on chart.png

### ISSUE THREAD

**Issue by adavradou** [AlexeyAB/darknet#4670]
Dear all, 

I training YoloV3 using mAP on Colab. I am using the following command:
! ./darknet detector train data/obj.data cfg/yolo-obj.cfg darknet53.conv.74 -dont_show -mjpeg_port 8090 -map

However, the graph only shows the loss.
Why does this happen and how can I fix it? 
![chart](https://user-images.githubusercontent.com/30274421/72180385-c1cf2580-33ef-11ea-9e35-090d3c2f0f7c.png)

Thanks in advance!

**Comment by adavradou** [comment]
1000 iterations needed to pass and then it shows up. 
Sorry for my mistake.

**Comment by rushipatel7** [comment]
Hi, can you tell me how to view this chart?? I've tried opening the VM ip on my machine's chrome browser with the mentioned port but no success... Thank you
