### ISSUE TITLE
Different mAP with the same model and weights on different machines

### ISSUE THREAD

**Issue by zxl19** [AlexeyAB/darknet#4681]
Hi, Alexey:
I trained YOLOv3 and YOLOv3-tiny in April, 2019 with then the latest version of darknet. Then I saved the .cfg files and .weights files. However, when I calculated mAP with **exactly the same dataset, model and weights** this month with the latest version of darknet on another machine, I saw the **mAP dropped by about 2~4%.** I noticed that for the same .weights file I can get the **same TP, FP, FN but different APs**. I wonder if the version of darknet, CUDA, or GPU result in such differences. It would be great if you can help me with this issue. The setup of the two machines are listed below.

Sincerely
Lucas

1  RTX 2080Ti *1  CUDA 10.0
2  RTX 1080Ti *3  CUDA 8.0

**Comment by AlexeyAB** [comment]
About a year ago a bug with mAP calculation was fixed.

**Comment by zxl19** [comment]
Oh I see. Thanks a lot.
