### ISSUE TITLE
RAM usage constantly increasing (内存占用持续上升)

### ISSUE THREAD

**Issue by ts1669** [AlexeyAB/darknet#4683]
I have trained my data set and get my weights file. run single-picture test successfully as well.
But when I use it in Windows(VS2017) to detect many pictures, I found the physical memory usage increasing constantly, about 400M/s, which makes it hard to apply in the video test or something else.
Did I do anything wrong? Or it's a normal cost? If so, how much RAM should I have? Please let me know~~~
（我已经完成了数据集的训练并且获得权重文件，也可以跑通测试，但是我在调用以解决多图检测的时候发现，计算机内存占用在不断上升，大概400mb/s，内存很快被消耗光，这是为什么？）

**Comment by ts1669** [comment]
Just very simple codes like this:
	
for (int i = 0; i < 150; i++ )
{
	char imgname_ch[50] = { 0 };

	sprintf(imgname_ch, "G:\\ML\\11.22\\%04d.jpg", i);
	string imgname_st = imgname_ch;

	auto image = Detector::load_image(imgname_st);

	TickMeter t;
	t.start();
	auto res = yolo_detector.detect(image);
	t.stop();
	cout << "YOLO-v3_cost=" << t.getTimeSec() << "sec" << " - "<< i << endl;
}

**Comment by AlexeyAB** [comment]
Do you get this issue if you don't change the source code?

Try to compile Darknet with LIBSO=1 in the Makefile, and run

`LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./uselib data/coco.names cfg/yolov3.cfg yolov3.weights list_of_images.txt`

where is `list_of_images.txt` file with list of images (you can use the same 1 image in all lines in this file)


Also run
`LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./uselib data/coco.names cfg/yolov3.cfg yolov3.weights test.mp4`

**Comment by ts1669** [comment]
> Do you get this issue if you don't change the source code?
> 
> Try to compile Darknet with LIBSO=1 in the Makefile, and run
> 
> `LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./uselib data/coco.names cfg/yolov3.cfg yolov3.weights list_of_images.txt`
> 
> where is `list_of_images.txt` file with list of images (you can use the same 1 image in all lines in this file)
> 
> Also run
> `LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./uselib data/coco.names cfg/yolov3.cfg yolov3.weights test.mp4`

Thanks a lot for your reply! I use another computer and get everything rebuilded, nothing wired happens again lol! Maybe I changed codes incorrectly before~

**Comment by LGBluesky** [comment]
Thanks for AlexeyAB's advice. However, when I use the python inference to test, the RAM usage constantly increasing.So what can i do for this problem, or free something?
