### ISSUE TITLE
Questions regarding training - pausing unexpectedly

### ISSUE THREAD

**Issue by nishanthcgit** [AlexeyAB/darknet#4685]
So this seems like a bit of a silly question but I am using yolov3 to train on my custom objects and everything works fine but it randomly stops and pauses waiting for user input on some iterations(I press enter and it continues training just fine), I am having to run this on computing power I am paying for and cant keep constantly monitoring training to keep resuming it. I haven't found anyone else facing this issue so i feel a bit stupid, can someone help me out please? I am using yolov3 exactly as mentioned, I just made a small mistake while setting number of classes (I have 25, I set 25 not realising yolo takes it as 0 to 24) but I don't think that part will be a problem.. It seems to automatically resolve it too.
EDIT: Might help to mention that it pauses right at the loading stage after it prints average IOU. Usually loading takes 0.00x seconds but sometimes it seems to randomly pause and wait for my input, (loading time is appropriately updated - amount of time I take to get to my system and press enter)

**Comment by AlexeyAB** [comment]
Show screenshot of this issue.

>  Usually loading takes 0.00x seconds but sometimes it seems to randomly pause and wait for my input, 

it seems, or for sure?

>  (I have 25, I set 25 not realising yolo takes it as 0 to 24)

All is correct, you set classes=25 in cfg, and in labels you must use from 0 to 24. What is the problem?

**Comment by nishanthcgit** [comment]
@AlexeyAB Sorry for getting back so late, I have been quite busy. I tried but could not replicate this issue to post screenshots, it is training fine now. The only thing I can think of is that I was running it with sudo to skirt some user permissions which I didn't try otherwise. Working great for me thank you very much!
