### ISSUE TITLE
smallest and largest objects in training dataset and adjusting network size

### ISSUE THREAD

**Issue by k00r** [AlexeyAB/darknet#4697]
Hello,i have small objects in my training dataset,for example like 9x15 and also large objects,what is our definition of small and large objects? like an object smaller than this width and height is a small object and larger than this width and height is a large object,and also my training images' resolutions are all different,is this a problem? and how should i adjust my network size?

i've read that spp has improved accuracy and decided to use yolov3-spp.cfg,but i've also read in the main page that gaussian-yolo also has improved accuracy,can they be used together? if not which one is better?

**Comment by AlexeyAB** [comment]
Small object is smaller than 8x8 pixels after that your image is resized to the network size (width & height in cfg-file).

Better to use `csresnext50-panet-spp-original-optimal.cfg`

For small objects try to use `yolov3_5l.cfg`
