### ISSUE TITLE
ENABLE_CUDNN_HALF not enabled for CUDA capabilites 7.2

### ISSUE THREAD

**Issue by andreyhristov** [AlexeyAB/darknet#4698]
Hi,
the CMakeLists.txt enabled half precision only for 7.5 (RTX, GTX 1660*). The GV10B on Xavier AGX has 64 Tensor Cores. Was this intentional or?

Cheers,
Andrey

**Comment by AlexeyAB** [comment]
@cenit Hi, Yes, CUDNN_HALF should be enabled for CC >= 7.0 instead of CC >= 7.5 https://github.com/AlexeyAB/darknet/blob/14172d42b68cf9c81ca1150020475f3e79c82fab/CMakeLists.txt#L68-L71

**Comment by cenit** [comment]
fixed by https://github.com/AlexeyAB/darknet/commit/893b889b2f62bff91d9c63931787d553ee19512f
