### ISSUE TITLE
A bug in the dll API

### ISSUE THREAD

**Issue by Teoge** [AlexeyAB/darknet#47]
When I use the API and destroy a "Detector" object, the program broke down.
After debugging I found out it got problem at line #84 in yolo_v2_class.cpp:
line #83: [`free(detector_gpu.probs);`](https://github.com/AlexeyAB/darknet/blob/master/src/yolo_v2_class.cpp#L83)
line #84: [`for (int j = 0; j < l.w*l.h*l.n; ++j) free(detector_gpu.probs[j]);`](https://github.com/AlexeyAB/darknet/blob/master/src/yolo_v2_class.cpp#L84)
So I think you got the wrong sequence. You should free the `detector_gpu.probs[j]` before freeing `detector_gpu.probs`. Just swap these two lines will do.
Thanks for your work.

**Comment by AlexeyAB** [comment]
@Teoge Thank you!

I fixed it: https://github.com/AlexeyAB/darknet/blob/master/src/yolo_v2_class.cpp#L84
