### ISSUE TITLE
NVCC fatal unsupported gpu architecture compute 61

### ISSUE THREAD

**Issue by haritsahm** [AlexeyAB/darknet#471]
Hi, i got this error when i try to make the darknet

![image](https://user-images.githubusercontent.com/26606913/37561885-e1041578-2a8c-11e8-9e90-d35a3862100e.png)
nvcc fatal   : Unsupported gpu architecture 'compute_61'

i use GTX 1060 with nvidia driver 390 and CUDA 9.1

**Comment by AlexeyAB** [comment]
Hi, type `nvcc -v` or `nvcc --version`, what version of nvcc do you use?

It seems that there is still old CUDA < 8.0 on your computer: https://github.com/BVLC/caffe/issues/5141#issuecomment-278889343

**Comment by kooscode** [comment]
Having the same issue compiling on a NVidia Jetson TX1 with latest Jetpack 3.2

Cuda 9.0

`nvcc fatal   : Unsupported gpu architecture 'compute_51'`

and Cuda version is 9.0

`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Sun_Nov_19_03:16:56_CST_2017
Cuda compilation tools, release 9.0, V9.0.252
`

**Comment by AlexeyAB** [comment]
@kooscode 
Try to use as described here: https://en.wikipedia.org/wiki/CUDA#GPUs_supported
`ARCH= -gencode arch=compute_53,code=[sm_53,compute_53]`
