### ISSUE TITLE
Test not working after training on Pascal VOC

### ISSUE THREAD

**Issue by lorenzomonto** [AlexeyAB/darknet#4714]
Hi, I have used your implementation of the darknet on colab, and it's working correctly using the net with default settings for detecting object. For a university project we have to train the network on Pascal VOC, and I have followed your instructions to achieve this. I have trained the net for 40'000 iterations, and saved the weights every 1000 iterations (as the net does by default). I have tested the detection on an image using weights obtained after 25'000 iterations, and it worked quite well. So, I restarted the training and I have made it work till 40'000 iterations. At this point I tried testing detection using these final weights (40'000 iterations) and the network didn't detect anything, even by putting very low threshold. So I tried again with the weights obtained after 25'000 iterations, and it kept not working, giving back the image as given in input, without detection. Reverting back to default cfg and weights (the ones given as default once installed the network) the net is working correctly. Any idea what may be the problem? If you need further details (like cfg used) just let me know.

Thanks in davance for the help.

**Comment by AlexeyAB** [comment]
Show chart.png with Loss and mAP

**Comment by lorenzomonto** [comment]
We found out we were using a wrong cfg file for testing. So problem solved. Thanks for the fast response and for sharing your darknet implementation.
