### ISSUE TITLE
Bug of mosaic augmentation

### ISSUE THREAD

**Issue by kungkungpanda** [AlexeyAB/darknet#4718]
Hi, 
Thanks for your great work!
I downloaded your latest repo, and trained my model using mosaic augmentation you implemented.
I used darknet53.conv.74 backbone, and trained YOLOv3 detector not classifier.

However, it seems that there is an overlap issue in the code.
As shown in this figure, red marks show several bugs in mosaic augmentatoin.

![image](https://user-images.githubusercontent.com/43112571/72615669-9660b380-3978-11ea-8bdf-417c674d33eb.png)

I checked my image and label data, but there is no problem.
In addition, the problem occures randomly, so i think it is a bug.
How can I fix it?
Or is it a normal case?

**Comment by AlexeyAB** [comment]
Do you use `letter_box=1` in cfg-file?

**Comment by kungkungpanda** [comment]
@AlexeyAB 
Thanks for your quick response!
I didn't use letter_box = 1.
This problem does not only occur with certain images. It seems to be occurring in various images.

**Comment by 1027663760** [comment]
> * Do you use `letter_box=1` in cfg-file?
> * Do you get this issue for each image, or only for some images?

I also encountered this problem

**Comment by AlexeyAB** [comment]
I will fix it in a few days.

**Comment by 1027663760** [comment]
> I will fix it in a few days.

I downloaded the repaired source code on June 8, 2020 and recompiled the test results: this problem has been solved

**Comment by AlexeyAB** [comment]
@1027663760 

I added param `mosaic_bound=1` to solve this issue.


It depends on task, sometimes my application should detect bbox of the whole object, even if we see only part of object.

**Comment by 1027663760** [comment]
@AlexeyAB 
I don’t quite understand. Do you mean that after using mosaic_bound=1, the network will consider the picture object enhanced by mosaic data as a part of the whole object?

**Comment by AlexeyAB** [comment]
* mosaic_bound=0  - Bbox of object can be in many images (Bbox includes the invisible part of the object)

* mosaic_bound=1  - Bbox of object can only be inside 1 of 4 images

**Comment by 1027663760** [comment]
Oh I see
