### ISSUE TITLE
Impact of building openCV with CUDA support

### ISSUE THREAD

**Issue by niemiaszek** [AlexeyAB/darknet#4719]
How much of difference does using OpenCV built from sources with CUDA support make in performance of detection with Python? I want to run yolov3 trained on my own dataset on Jetson TX2, HD camera as an input. 
Bonus question: Is it now more optimal to use csresnext50-panet-spp instead of standard yolov3?

**Comment by AlexeyAB** [comment]
If you use Darknet framework, the there is no different OpenCV is compiled with CUDA or without.

Use https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/csresnext50-panet-spp-original-optimal.cfg  instead of standard yolov3

**Comment by niemiaszek** [comment]
Thank you very much
