### ISSUE TITLE
Can training be "Paused"

### ISSUE THREAD

**Issue by golars497** [AlexeyAB/darknet#472]
Hi,

I am a university student. I am working on a project and am using YOLO for object detection. I want to know if it is possible to "Pause and save state" when training the YOLO network. This is because the computers at the labs in my university automatically restarts during midnight. I am currently trying to find a computer which I can use continuously for more than 24 hours, but in the meantime I wanted to find out if there was a way of pausing the training phase, saving the current "state" and running it again next time I have access to a computer.

p.s. apologies if I have posted this in the wrong place. I am happy to move it if desired.

Many Thanks

**Comment by AlexeyAB** [comment]
Hi,

Yes you can.
weights-file is saved for each 100 iterations in the `/backup/` folder.

You can start training `./darknet detector train data/voc.data yolo-voc.2.0.cfg darknet19_448.conv.23` and after 100 or for example 1500 iterations stop and then continue training using command
`./darknet detector train data/voc.data yolo-voc.2.0.cfg /backup/yolo-voc.2.0_1500.weights`

**Comment by golars497** [comment]
Thanks for the quick reply! I didn't realise it was this simple haha
