### ISSUE TITLE
diffrent fps on the same system

### ISSUE THREAD

**Issue by kopebryant** [AlexeyAB/darknet#4720]
Hi. I am using yolov3-tiny with my custom cfg and weight files. The system that i am using is a i7 6700TE, gtx 1050ti with ubuntu 16.04. If i use my own python code i get ~10 fps, but if i use the command ./darknet detector demo data/obj.data cfg/yolov3-tiny.cfg yolov3-tiny.weights test.mp4      
 i get ~90 fps. 
Network:
net = cv2.dnn.readNetFromDarknet('yolov3-tiny_obj.cfg','yolov3-tiny_obj_best.weights')
net.setPreferableTarget(cv2.dnn.DNN_TARGET_OPENCL_FP16)
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_OPENCV)

The function net.forward() takes 0.052 seconds per image.
Is it normal that the network is slower if it gets the images live from a camera, instead of using the predefined function?

**Comment by BernoGreyling** [comment]
The dnn function in opencv that you are using in the lines above is not GPU accelerated like the native yolo command. Use the darknet.py and darknet_video.py files in the repo to interface python with yolo. 

Also compile with the code with `LIBSO=1` in your Makefile

**Comment by kopebryant** [comment]
Ok. Thank you for your answer. I will try it on Monday. The system is at my work

**Comment by AlexeyAB** [comment]
Since OpeCV 4.0 there is CUDA DNN implementation, for yolov3: https://docs.opencv.org/master/d6/d0f/group__dnn.html#ga709af7692ba29788182cf573531b0ff5
* `cv.dnn.DNN_TARGET_CUDA`
* `cv.dnn.DNN_TARGET_CUDA_FP16`

**Comment by BernoGreyling** [comment]
For interest sake, I tested the opencv4.2 dnn cuda implementation. 

On a yolov3-spp model (w:576, h:1024) I got around 5fps, while the native yolo darknet_video.py gave around 8 fps. The CPU opencv backend gave around 1.2 FPS

This was on a laptop GTX1060 6gb. Will test ons a RTX2070 Super later and post results.

**Comment by AlexeyAB** [comment]
@BernoGreyling Did you compile OpenCV and Darknet with CUDA and cuDNN?

**Comment by BernoGreyling** [comment]
@AlexeyAB ,

Yes. Are you expecting better performance?

Using the `./darknet detector test` command ofcourse gives better performance.

**Comment by kopebryant** [comment]
Hi. I implemented the darknet_video.py in my own script and get 30fps. 
Thank you very much
