### ISSUE TITLE
how to iteratively train with new data, without again starting the training from scratch

### ISSUE THREAD

**Issue by BabuTango** [AlexeyAB/darknet#4722]
Hi @AlexeyAB , 

Say suppose I train the model with 1000 images.
Then I want  to train the model with another 200 images.

Now should I train the model from scratch adding new images (1000+200), 
or can I train the existing model with just new 200 images without starting from scratch, if we can, can you please explain how to proceed with. 

Thanks

**Comment by AlexeyAB** [comment]
You can train **existing** model adding new **images (1000+200)**

**Comment by BabuTango** [comment]
So I should train the new images with already **trained model** instead of **darknet53.conv.74**. Is that right @AlexeyAB

**Comment by Rajasekhar06** [comment]
Yes you have to use that weights

**Comment by AlexeyAB** [comment]
> So I should train the new images 

No, you should use: (1000+200)

**Comment by BabuTango** [comment]
@AlexeyAB Understood. Thanks

**Comment by renziver** [comment]
Hi @BabuTango @AlexeyAB , just to clarify things:

Model A: 1000 Images
** get new 200 images
Use Model A weights to fine tune with 200 images to generate Model B (1000+200)

Now if I have another new set of 100 images, I will be using Model B (1000+200) and retrain it to get Model C (1000+200+100)?

I do not essentially have to keep the first 1000 images to train Model B, and second 1200 Images for Model C?
