### ISSUE TITLE
Non Maximum Suppression IoU_threshold in Yolov2-Tiny

### ISSUE THREAD

**Issue by barzan-hayati** [AlexeyAB/darknet#4723]
Hi @AlexeyAB .

Is it possible to set IoU_threshold parameter in order to use NMS(Non Maximum Suppression) during training Yolov2-tiny network? As you know defining IoU_threshold increases map result, because it utilizing non-maximum suppression to ignore redundant, overlapping bounding boxes. [
Non-Maximum Suppression for Object Detection in Python
](https://www.pyimagesearch.com/2014/11/17/non-maximum-suppression-object-detection-python/)

**Comment by AlexeyAB** [comment]
NMS is used in Yolo v2/v3 by default during Detection - currently this value is hardcoded in the source code:  https://github.com/AlexeyAB/darknet/blob/2a9fe045f3fd385ec61a38c8225945482d0ad7c7/src/detector.c#L1485

Why do you want to use it during Training?

**Comment by barzan-hayati** [comment]
> 
> 
> NMS is used in Yolo v2/v3 by default during Detection - currently this value is hardcoded in the source code:
> 
> https://github.com/AlexeyAB/darknet/blob/2a9fe045f3fd385ec61a38c8225945482d0ad7c7/src/detector.c#L1485
> 
> Why do you want to use it during Training?

Thanks. In order to decreasing FP's it's necessary to disregard them via NMS (remove multiple choices in one grid). It's possible to using NMS in training procedure?

**Comment by AlexeyAB** [comment]
> Thanks. In order to decreasing FP's it's necessary to disregard them via NMS (remove multiple choices in one grid).

It is already done during Detection.

Why do you want to use NMS **during Training instead of during Detection**?

**Comment by barzan-hayati** [comment]
> 
> 
> > Thanks. In order to decreasing FP's it's necessary to disregard them via NMS (remove multiple choices in one grid).
> 
> It is already done during Detection.
> 
> Why do you want to use NMS **during Training instead of during Detection**?

For test results of training we could use `test `or `map` command :

`./darknet detector map Data.data Config.cfg Config_best.weights `

` ./darknet detector test  Data.data Config.cfg Config_best.weights 077.jpg -thresh 0.7`

Is there any way to change `nms ` parameter without changing it in darknet source code?

**Comment by AlexeyAB** [comment]
Currently, No.

**Comment by barzan-hayati** [comment]
> 
> 
> Currently, No.

Thanks.

**Comment by abhigoku10** [comment]
@AlexeyAB we thought adding nms during training process helps in getting accurate detections and inturn the model learning more details
