### ISSUE TITLE
How to use TensorRT file for inference on video

### ISSUE THREAD

**Issue by shweta-agnext** [AlexeyAB/darknet#4732]
Hello,
I have converted `yolov3.weights` to `yolov3.onnx` and then to `yolov3.trt` by using TensorRT 5.0.2.6.
In second step, it takes image of a dog and make prediction on it. If I make changes in those python files to work for video, the inference is very slow.

If I directly use `yolov3.trt` instead of `yolov3.weights` in `LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./uselib data/coco.names cfg/yolov3.cfg yolov3.weights test.mp4` command, then no object is detected. How can I use trt file for inference on videos? 

Please help.

**Comment by AlexeyAB** [comment]
>  If I make changes in those python files to work for video, the inference is very slow.

In what python file?

Darknet doesn't use TRT. 
So you should use `yolov3.trt` file in TRT:
* example: https://github.com/NVIDIA-AI-IOT/deepstream_reference_apps/blob/restructure/yolo/apps/trt-yolo/trt-yolo-app.cpp
* description: https://news.developer.nvidia.com/deepstream-sdk-4-now-available/

**Comment by shweta-agnext** [comment]
Thanks for your quick response.

I was trying to make changes in TensorRT files. Thanks for the links as well.
