### ISSUE TITLE
Error:  Zero-divisor

### ISSUE THREAD

**Issue by dzbwhut** [AlexeyAB/darknet#4739]
There is a error :  Zero-divisor,  because nweights may be 0  in shortcut_layer. 
    I propose to comment out these two lines: 839 & 840, because they are used only for tracing and debugging.

extern "C" void backward_shortcut_multilayer_gpu(... , int nweights, ...)
{
(L839)     const int layer_step = nweights / (n + 1);    // 1 or l.c or (l.c * l.h * l.w)
(L840)     const int step = src_outputs / layer_step; // (l.c * l.h * l.w) or (l.w*l.h) or 1
            //printf(" nweights = %d, n = %d, layer_step = %d, step = %d \n", nweights, n, layer_step, step);
     ...
}

**Comment by AlexeyAB** [comment]
Thanks! I fixed it: https://github.com/AlexeyAB/darknet/commit/678ba01335913efa809b1e8ddf1a01eeea61d578
