### ISSUE TITLE
Precision-recall curve source code

### ISSUE THREAD

**Issue by lixiangchun** [AlexeyAB/darknet#474]
@AlexeyAB I found the code to generate PR curve has been implemented in [EAVISE/darknet](https://gitlab.com/EAVISE/darknet/blob/master/examples/detector.c). It would be helpful if you could incorporate this code.

**Comment by AlexeyAB** [comment]
@lixiangchun There is already code for PR-curve for each class - it printf 11 points on PR-curve, just uncomment this line: https://github.com/AlexeyAB/darknet/blob/2f52cfeb07e11fce8275496164293cf30b732907/src/detector.c#L800

And then do `./darknet detector map data/obj.data yolo-obj.cfg backup\yolo-obj_7000.weights`
