### ISSUE TITLE
Is there any coco_pretrained model for yolov3? And is there any trick to improve mAP?

### ISSUE THREAD

**Issue by clw5180** [AlexeyAB/darknet#4741]
just as above, really thanks!!

**Comment by AlexeyAB** [comment]
There are many MS COCO pre-trained models:

https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov3.cfg
https://pjreddie.com/media/files/yolov3.weights

More: https://github.com/AlexeyAB/darknet#pre-trained-models

**Comment by clw5180** [comment]
> There are many MS COCO pre-trained models:
> 
> https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov3.cfg
> https://pjreddie.com/media/files/yolov3.weights
> 
> More: https://github.com/AlexeyAB/darknet#pre-trained-models

Thanks a lot! I thought it was ImageNet pretrained models. And I saw that csresnext50-panet-spp-original-optimal.cfg can get 65.4% mAP@0.5, but in paper it can only get 60.6% mAP, same as YOLOv3-spp, what's the reason of ~5 mAP?

**Comment by clw5180** [comment]
> There are many MS COCO pre-trained models:
> 
> https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov3.cfg
> https://pjreddie.com/media/files/yolov3.weights
> 
> More: https://github.com/AlexeyAB/darknet#pre-trained-models

sorry to disturb you, I already got the answer ---- https://github.com/AlexeyAB/darknet/issues/4652
