### ISSUE TITLE
 How can I save the detected objects in a video?

### ISSUE THREAD

**Issue by anthonymg1994** [AlexeyAB/darknet#4744]
I was looking at the issues in the repository and found this #954 ,
I am trying to uncomment certain lines in the image_opencv.cpp file but I have a problem with this 

`cvCreateImage (cvSize (show_img-> width, show_img-> height), show_img-> depth, show_img-> nChannels);`

it throws me that show_img doesn't have the 'width' or 'height' properties

**Comment by xinyee1997** [comment]
did u solved the problem?
