### ISSUE TITLE
Better predictions with smaller image size than in the training cfg size ?

### ISSUE THREAD

**Issue by aquadzn** [AlexeyAB/darknet#4747]
I trained for 6000 iterations a model on custom images and left 416 for width and height of images.

I then trained again the model with new images and I increased width and height to 832.

And then, when I make predictions with the last model, I get better results with the flag -size 620 (so with lower width and height) than with original size of 832. I got more bounding boxes on the tested image.

Is it normal?

Thanks

**Comment by AlexeyAB** [comment]
> flag -size 620

What is the `flag -size 620` ?

> I then trained again the model with new images and I increased width and height to 832.

Did you train from scratch or by using prevous trained weights file?
Did you train with only new images or with old+new images?
What images do you use for testing, old, new, or somethin else?

**Comment by aquadzn** [comment]
> > flag -size 620
> 
> What is the `flag -size 620` ?
> 
> > I then trained again the model with new images and I increased width and height to 832.
> 
> Did you train from scratch or by using prevous trained weights file?
> Did you train with only new images or with old+new images?
> What images do you use for testing, old, new, or somethin else?

There is no -size or -img_size argument with `detector test` ? 
Maybe I confused with something else.

Anyway I first used darknet53.conv.74 with around 150-200 images and then with the output model I trained again on same images + 100 new images
For the new images, I did as written in the README, I changed W, H to 832, increased subdivision to 64, and added ignore_thresh = .9 iou_normalizer=0.5 iou_loss=giou to each [yolo] layer.

Unseen images for test set. Objects to detect are small-medium sized.

Thanks!

**Comment by AlexeyAB** [comment]
> There is no -size or -img_size argument with detector test ?


No
