### ISSUE TITLE
what did the consumed flag stand for in the yolo_console_dll file?

### ISSUE THREAD

**Issue by qunsorber** [AlexeyAB/darknet#475]
just as the question, when a inputed video file was processed, I can barely understand the codes before the 292 line, but after that,  especially the consumed flag, I was completely confused. I need someone who has time and patience to help me understand the part of the code. I will appreciate for even a little help @AlexeyAB

**Comment by AlexeyAB** [comment]
* `if(consumed == true)` then detectection completed, so we can get detection result From the detector and copy new frame To the detector. At this time, the detector waits.

* `if(consumed == false)` then results are taken and new frame copied, so detector can continue to detect.

**Comment by qunsorber** [comment]
thank you @AlexeyAB,  could you explain me how the class extrapolate_coods_t works？I was confused with so many variables and what they actually did.

**Comment by AlexeyAB** [comment]
`class extrapolate_coods_t` just stores linear speed of objects (how many pixels the object moves per frame), and stores last frame_id_old.

So when you pass current_frame_id, it calculates new place of object 
`x_cur = x_old + speed_obj * (frame_id_cur - frame_id_old)`
