### ISSUE TITLE
 mean average precision (mAP) = 0.000007, or 0.00 % 

### ISSUE THREAD

**Issue by thakoreneelabh** [AlexeyAB/darknet#4752]
@AlexeyAB 
Hi,
This is the issue I am facing
I have trained my model using around 5K images and testing on 1 K
Tried to calculate MAP using below command
./darknet detector map obj.data yolov3-tiny-obj-WithTinyY3Changes.cfg yolov3-tiny-obj_last.weights
it gives following output
batch = 1, time_steps = 1, train = 0 
   layer   filters  size/strd(dil)      input                output
   0 conv     16       3 x 3/ 1    416 x 416 x   3 ->  416 x 416 x  16 0.150 BF
   1 max                2x 2/ 2    416 x 416 x  16 ->  208 x 208 x  16 0.003 BF
   2 conv     32       3 x 3/ 1    208 x 208 x  16 ->  208 x 208 x  32 0.399 BF
   3 max                2x 2/ 2    208 x 208 x  32 ->  104 x 104 x  32 0.001 BF
   4 conv     64       3 x 3/ 1    104 x 104 x  32 ->  104 x 104 x  64 0.399 BF
   5 max                2x 2/ 2    104 x 104 x  64 ->   52 x  52 x  64 0.001 BF
   6 conv    128       3 x 3/ 1     52 x  52 x  64 ->   52 x  52 x 128 0.399 BF
   7 max                2x 2/ 2     52 x  52 x 128 ->   26 x  26 x 128 0.000 BF
   8 conv    256       3 x 3/ 1     26 x  26 x 128 ->   26 x  26 x 256 0.399 BF
   9 max                2x 2/ 2     26 x  26 x 256 ->   13 x  13 x 256 0.000 BF
  10 conv    512       3 x 3/ 1     13 x  13 x 256 ->   13 x  13 x 512 0.399 BF
  11 max                2x 2/ 1     13 x  13 x 512 ->   13 x  13 x 512 0.000 BF
  12 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  13 conv    256       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 256 0.089 BF
  14 conv    512       3 x 3/ 1     13 x  13 x 256 ->   13 x  13 x 512 0.399 BF
  15 conv     66       1 x 1/ 1     13 x  13 x 512 ->   13 x  13 x  66 0.011 BF
  16 yolo
[yolo] params: iou loss: mse (2), iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
  17 route  13 		                           ->   13 x  13 x 256 
  18 conv    128       1 x 1/ 1     13 x  13 x 256 ->   13 x  13 x 128 0.011 BF
  19 upsample                 2x    13 x  13 x 128 ->   26 x  26 x 128
  20 route  19 8 	                           ->   26 x  26 x 384 
  21 conv    256       3 x 3/ 1     26 x  26 x 384 ->   26 x  26 x 256 1.196 BF
  22 conv     66       1 x 1/ 1     26 x  26 x 256 ->   26 x  26 x  66 0.023 BF
  23 yolo
[yolo] params: iou loss: mse (2), iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
Total BFLOPS 5.473 
 Allocate additional workspace_size = 24.92 MB 
Loading weights from yolov3-tiny-obj_last.weights...
 seen 64 
Done! Loaded 24 layers from weights-file 

 calculation mAP (mean average precision)...
**920**
 detections_count = 764604, unique_truth_count = 7656  
class_id = 0, name = bag, ap = 0.00%   	 (TP = 0, FP = 0) 
class_id = 1, name = bicycle, ap = 0.00%   	 (TP = 0, FP = 0) 
class_id = 2, name = bus, ap = 0.00%   	 (TP = 0, FP = 0) 
class_id = 3, name = car, ap = 0.00%   	 (TP = 0, FP = 0) 
class_id = 4, name = cat, ap = 0.00%   	 (TP = 0, FP = 0) 
class_id = 5, name = cow, ap = 0.00%   	 (TP = 0, FP = 0) 
class_id = 6, name = dog, ap = 0.00%   	 (TP = 0, FP = 0) 
class_id = 7, name = gun, ap = 0.00%   	 (TP = 0, FP = 0) 
class_id = 8, name = helmet, ap = 0.00%   	 (TP = 0, FP = 0) 
class_id = 9, name = horse, ap = 0.00%   	 (TP = 0, FP = 0) 
class_id = 10, name = mask, ap = 0.00%   	 (TP = 0, FP = 0) 
class_id = 11, name = motorcycle, ap = 0.00%   	 (TP = 0, FP = 0) 
class_id = 12, name = person, ap = 0.00%   	 (TP = 0, FP = 0) 
class_id = 13, name = rickshaw, ap = 0.00%   	 (TP = 0, FP = 0) 
class_id = 14, name = threat, ap = 0.00%   	 (TP = 0, FP = 0) 
class_id = 15, name = truck, ap = 0.00%   	 (TP = 0, FP = 0) 
class_id = 16, name = umbrella, ap = 0.00%   	 (TP = 0, FP = 0) 

 for conf_thresh = 0.25, precision = -nan, recall = 0.00, F1-score = -nan 
 for conf_thresh = 0.25, TP = 0, FP = 0, FN = 7656, average IoU = 0.00 % 

 IoU threshold = 50 %, used Area-Under-Curve for each unique Recall 
 mean average precision (mAP@0.50) = 0.000000, or 0.00 % 
Total Detection Time: 9.000000 Seconds

I am sure the weights generated are detecting objects effectively, however map is getting calculated as 0. Your help is very much appreciated :)

Regards
Neelabh

**Comment by thakoreneelabh** [comment]
Ah Looks like I was using incorrect .weights file..
Finally getting some numbers

detections_count = 57096, unique_truth_count = 7656  
class_id = 0, name = bag, 7096   ap = 18.48 % 
class_id = 1, name = bicycle, 	 ap = 22.91 % 
class_id = 2, name = bus, 	 ap = 31.99 % 
class_id = 3, name = car, 	 ap = 37.03 % 
class_id = 4, name = cat, 	 ap = 50.55 % 
class_id = 5, name = cow, 	 ap = 43.64 % 
class_id = 6, name = dog, 	 ap = 39.29 % 
class_id = 7, name = gun, 	 ap = 15.19 % 
class_id = 8, name = helmet, 	 ap = 44.99 % 
class_id = 9, name = horse, 	 ap = 50.11 % 
class_id = 10, name = mask, 	 ap = 43.89 % 
class_id = 11, name = motorcycle, 	 ap = 34.13 % 
class_id = 12, name = person, 	 ap = 49.77 % 
class_id = 13, name = rickshaw, 	 ap = 44.61 % 
class_id = 14, name = threat, 	 ap = 55.84 % 
class_id = 15, name = truck, 	 ap = 41.64 % 
class_id = 16, name = umbrella, 	 ap = 6.92 % 
 for thresh = 0.25, precision = 0.59, recall = 0.47, F1-score = 0.52 
 for thresh = 0.25, TP = 3628, FP = 2542, FN = 4028, average IoU = 40.78 % 

 mean average precision (mAP) = 0.371170, or 37.12 % 
Total Detection Time: 646.000000 Seconds

Regards
Neelabh

**Comment by thakoreneelabh** [comment]
@AlexeyAB 
Now the issue is that it is not working on my Tiny YOLO2 model and throwing core dump issue.
Do we have any other process to calculate on Tiny YOLO 2?
layer     filters    size              input                output
    0 conv     16  3 x 3 / 1   608 x 608 x   3   ->   608 x 608 x  16
    1 max          2 x 2 / 2   608 x 608 x  16   ->   304 x 304 x  16
    2 conv     32  3 x 3 / 1   304 x 304 x  16   ->   304 x 304 x  32
    3 max          2 x 2 / 2   304 x 304 x  32   ->   152 x 152 x  32
    4 conv     64  3 x 3 / 1   152 x 152 x  32   ->   152 x 152 x  64
    5 max          2 x 2 / 2   152 x 152 x  64   ->    76 x  76 x  64
    6 conv    128  3 x 3 / 1    76 x  76 x  64   ->    76 x  76 x 128
    7 max          2 x 2 / 2    76 x  76 x 128   ->    38 x  38 x 128
    8 conv    256  3 x 3 / 1    38 x  38 x 128   ->    38 x  38 x 256
    9 max          2 x 2 / 2    38 x  38 x 256   ->    19 x  19 x 256
   10 conv    512  3 x 3 / 1    19 x  19 x 256   ->    19 x  19 x 512
   11 max          2 x 2 / 1    19 x  19 x 512   ->    19 x  19 x 512
   12 conv   1024  3 x 3 / 1    19 x  19 x 512   ->    19 x  19 x1024
   13 conv   1024  3 x 3 / 1    19 x  19 x1024   ->    19 x  19 x1024
   14 conv     35  1 x 1 / 1    19 x  19 x1024   ->    19 x  19 x  35
   15 detection
mask_scale: Using default '1.000000'
Loading weights from headPersonDetection_fromSuraksha/tinyYoloHeadPerson_50400.weights...
 seen 64 
Done!
4
*** Error in `./darknet': free(): invalid next size (fast): 0x00000000018d75d0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fe57ebf07e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7fe57ebf937a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fe57ebfd53c]
./darknet[0x448c68]
./darknet[0x4648c5]
./darknet[0x465992]
./darknet[0x401e48]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fe57eb99830]
./darknet[0x4022c9]
======= Memory map: ========
00400000-0049c000 r-xp 00000000 08:04 7615153                            /home/gpu/develop/darknet/darknetMAP/darknet-3fc3fd0f1f1924acb7195fe98fe68648e4056a09/darknet
0069b000-0069c000 r--p 0009b000 08:04 7615153                            /home/gpu/develop/darknet/darknetMAP/darknet-3fc3fd0f1f1924acb7195fe98fe68648e4056a09/darknet
0069c000-0069d000 rw-p 0009c000 08:04 7615153                            /home/gpu/develop/darknet/darknetMAP/darknet-3fc3fd0f1f1924acb7195fe98fe68648e4056a09/darknet
018ca000-01a0c000 rw-p 00000000 00:00 0                                  [heap]
7fe54e844000-7fe550000000 rw-p 00000000 00:00 0 
7fe550000000-7fe550bee000 rw-p 00000000 00:00 0 
7fe550bee000-7fe554000000 ---p 00000000 00:00 0 
7fe5542bd000-7fe555a79000 rw-p 00000000 00:00 0 
7fe556950000-7fe556d8c000 rw-p 00000000 00:00 0 
7fe557027000-7fe5579a8000 rw-p 00000000 00:00 0 
7fe558000000-7fe558e53000 rw-p 00000000 00:00 0 
7fe558e53000-7fe55c000000 ---p 00000000 00:00 0 
7fe55c000000-7fe55caf6000 rw-p 00000000 00:00 0 
7fe55caf6000-7fe560000000 ---p 00000000 00:00 0 
7fe560000000-7fe56111a000 rw-p 00000000 00:00 0 
7fe56111a000-7fe564000000 ---p 00000000 00:00 0 
7fe564026000-7fe56403c000 r-xp 00000000 08:04 1184397                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fe56403c000-7fe56423b000 ---p 00016000 08:04 1184397                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fe56423b000-7fe56423c000 rw-p 00015000 08:04 1184397                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fe56425c000-7fe56425d000 ---p 00000000 00:00 0 
7fe56425d000-7fe564a5d000 rw-p 00000000 00:00 0 
7fe564a5d000-7fe564a5e000 ---p 00000000 00:00 0 
7fe564a5e000-7fe56525e000 rw-p 00000000 00:00 0 
7fe56525e000-7fe56525f000 ---p 00000000 00:00 0 
7fe56525f000-7fe565a5f000 rw-p 00000000 00:00 0 
7fe565a5f000-7fe565a60000 ---p 00000000 00:00 0 
7fe565a60000-7fe57eb79000 rw-p 00000000 00:00 0 
7fe57eb79000-7fe57ed39000 r-xp 00000000 08:04 1179745                    /lib/x86_64-linux-gnu/libc-2.23.so
7fe57ed39000-7fe57ef39000 ---p 001c0000 08:04 1179745                    /lib/x86_64-linux-gnu/libc-2.23.so
7fe57ef39000-7fe57ef3d000 r--p 001c0000 08:04 1179745                    /lib/x86_64-linux-gnu/libc-2.23.so
7fe57ef3d000-7fe57ef3f000 rw-p 001c4000 08:04 1179745                    /lib/x86_64-linux-gnu/libc-2.23.so
7fe57ef3f000-7fe57ef43000 rw-p 00000000 00:00 0 
7fe57ef43000-7fe57ef5b000 r-xp 00000000 08:04 1179732                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fe57ef5b000-7fe57f15a000 ---p 00018000 08:04 1179732                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fe57f15a000-7fe57f15b000 r--p 00017000 08:04 1179732                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fe57f15b000-7fe57f15c000 rw-p 00018000 08:04 1179732                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fe57f15c000-7fe57f160000 rw-p 00000000 00:00 0 
7fe57f160000-7fe57f268000 r-xp 00000000 08:04 1184377                    /lib/x86_64-linux-gnu/libm-2.23.so
7fe57f268000-7fe57f467000 ---p 00108000 08:04 1184377                    /lib/x86_64-linux-gnu/libm-2.23.so
7fe57f467000-7fe57f468000 r--p 00107000 08:04 1184377                    /lib/x86_64-linux-gnu/libm-2.23.so
7fe57f468000-7fe57f469000 rw-p 00108000 08:04 1184377                    /lib/x86_64-linux-gnu/libm-2.23.so
7fe57f469000-7fe57f48f000 r-xp 00000000 08:04 1179731                    /lib/x86_64-linux-gnu/ld-2.23.so
7fe57f493000-7fe57f66e000 rw-p 00000000 00:00 0 
7fe57f68d000-7fe57f68e000 rw-p 00000000 00:00 0 
7fe57f68e000-7fe57f68f000 r--p 00025000 08:04 1179731                    /lib/x86_64-linux-gnu/ld-2.23.so
7fe57f68f000-7fe57f690000 rw-p 00026000 08:04 1179731                    /lib/x86_64-linux-gnu/ld-2.23.so
7fe57f690000-7fe57f691000 rw-p 00000000 00:00 0 
7fff3586d000-7fff3588e000 rw-p 00000000 00:00 0                          [stack]
7fff3594a000-7fff3594d000 r--p 00000000 00:00 0                          [vvar]
7fff3594d000-7fff3594f000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
**Aborted (core dumped)**

**Comment by AlexeyAB** [comment]
Try to use the latest Darknet.

If it doesn't help, share your cfg and weights files by using Google-disk

**Comment by thakoreneelabh** [comment]
Thanks a lot.
Let me try the latest version and will get back.

**Comment by thakoreneelabh** [comment]
Can you please help me with the link to latest version?

**Comment by thakoreneelabh** [comment]
@AlexeyAB 
Got the latest version and it works fine now.
Thanks for your advise :)

Regards
Neelabh

**Comment by thakoreneelabh** [comment]
@AlexeyAB 
The one which I got works fine for 10 images but throws error if my .txt has more than 10 mages
