### ISSUE TITLE
Worse FPS with enet-coco.cfg than with csresnext50-panet-spp-original-optimal.cfg

### ISSUE THREAD

**Issue by isra60** [AlexeyAB/darknet#4753]
With a 1060 NVIDIA I have more detection time with enet.cfg than with the cresnet50 cfg.. 
(like 2x)

It should have better FPS the enet cfg as it is a small model.

I'm using the darknet as a library maybe is a problem with this.

**Comment by dexception** [comment]
Please go through this:
https://github.com/AlexeyAB/darknet/issues/3380

**Comment by isra60** [comment]
Ok. I understand this kind of model works worse on GPU mode.
Thanks
