### ISSUE TITLE
Darknet Windows Webcam Trouble...

### ISSUE THREAD

**Issue by junghwa96** [AlexeyAB/darknet#477]
I am working on Darknet as a window Visual Studio 2015.
However, the Darknet webcam code will not work if the webcam that worked well in Ubuntu is running in Windows.
Webcam problem, my webcam works well when I run the default webcam project..
The webcam does not work only when I run the Darknet program. Do you know why?
Please help me......

**Comment by AlexeyAB** [comment]
Probably your web-cam ins't compatible with OpenCV.
Can you use your web-cam with any OpenCV application?

**Comment by junghwa96** [comment]
I did that.. But web-cam apply with OpenCV very well!!
But Darknet Window project does not apply with my Web Cam..
Is this Darknet problem???

**Comment by sivagnanamn** [comment]
> The webcam does not work only when I run the Darknet program. Do you know why?

- Could you please provide more details? 
- By any chance, do you have more than 1 camera connected to your system?
- Do you see any error while running darknet demo?

**Comment by junghwa96** [comment]
![image](https://user-images.githubusercontent.com/37541471/37598450-930175b6-2bc5-11e8-82f9-9a8e58b34578.png)

**Comment by junghwa96** [comment]
![image](https://user-images.githubusercontent.com/37541471/37598464-9cb1541e-2bc5-11e8-8ce0-634415982b2b.png)
Infinite Loading...
![image](https://user-images.githubusercontent.com/37541471/37598473-a3237304-2bc5-11e8-9cf0-a59b5449b822.png)
It does not work.!

**Comment by junghwa96** [comment]
cuda: 9.1 cudnn : 7.0 / opencv :3.2

**Comment by junghwa96** [comment]
vs14 compile

**Comment by AlexeyAB** [comment]
@junghwa96 I fixed it.
Just update your code from this repo.
It was C API bug in OpenCV 3.x again.

**Comment by AlexeyAB** [comment]
I added another fix for Web cam.

Use `darknet.exe detector demo data/coco.data cfg/yolov3.cfg yolov3.weights -c 0`

**Comment by vinjn** [comment]
I find `classifier` still use the C API, can you upgrade it?
Thx

**Comment by vinjn** [comment]
You are so responsive! thx
