### ISSUE TITLE
Different bounding box size using Darknet, Pytorch implementation and opencv dnn

### ISSUE THREAD

**Issue by sbanerj2** [AlexeyAB/darknet#4779]
Hi,
I trained YOLO on my custom dataset (resized to 416 x 416 as some images are pretty small in comparison to 1920 × 1080)and while testing with similar type of test images (1920 × 1080), the bounding box coordinates when drawn on the test images using opencv dnn or pytorch code do not sync with the results of the darknet detector in test mode. As for example please look at the attached images.
DI-female3-yes_350_yolo_out_py.jpg --> opencv dnn
DI-female3-yes_350-det.jpg --> using pytorch with padding to take care of aspect ratio
predictions-350.jpg --> using darknet test
I trained my model on darknet.
I am following these tutorials for generating these images:
1)https://github.com/spmallick/learnopencv/blob/master/ObjectDetection-YOLO/object_detection_yolo.py
2) https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/master/detect.py
![predictions-350](https://user-images.githubusercontent.com/14826210/73504213-a1660b80-439c-11ea-8b2d-78ed833286fd.jpg)
![DI-female3-yes_350_yolo_out_py](https://user-images.githubusercontent.com/14826210/73504239-ba6ebc80-439c-11ea-9bff-4b51ebc7e858.jpg)
![DI-female3-yes_350-det](https://user-images.githubusercontent.com/14826210/73504278-d83c2180-439c-11ea-907c-2e2966ba3862.jpg)

**Comment by AlexeyAB** [comment]
1. Attach your cfg-file in zip
2. Show your source image with padding. Do you use the same image with padding for all 3 cases?

**Comment by sbanerj2** [comment]
Hi Alexey,
Thanks for the reply. I think I was using a different .cfg file for the other programs(opencv, pytorch) with different anchor sizes. Its working fine now. Thanks
