### ISSUE TITLE
Bug in blas.c smooth_l1_cpu

### ISSUE THREAD

**Issue by wilstro** [AlexeyAB/darknet#478]
Hi I believe there is a bug in 

In file: blas.c 
function:  void smooth_l1_cpu(int n, float *pred, float *truth, float *delta, float *error)
line:        delta[i] = (diff < 0) ? 1 : -1;

this line should read: 
            **delta[i] = (diff < 0) ? -1 : 1;**

**Comment by AlexeyAB** [comment]
Hi,

This is trange:

CPU:
For `smooth_l1_cpu()` initially `delta[i] = (diff < 0) ? -1 : 1;`
But then it was changed to `delta[i] = (diff < 0) ? 1 : -1;`
https://github.com/pjreddie/darknet/commit/60e952ba694e3e0811db5868d70ad7ebfe676836#diff-0c461530f46c81f7013a6eaec297ebcfR182

GPU:
But for `smooth_l1_kernel()` initially `delta[i] = (diff < 0) ? -1 : 1;`
But then it was changed to `delta[i] = (diff > 0) ? 1 : -1;`
https://github.com/pjreddie/darknet/commit/60e952ba694e3e0811db5868d70ad7ebfe676836#diff-14ecc558a5571a7cffc7b588b155d013R681


So yes, I think correct is `delta[i] = (diff > 0) ? 1 : -1;` or ~ the same `delta[i] = (diff < 0) ? -1 : 1;`

**Comment by wilstro** [comment]
Hi, 

It looks inconsistent.

_l1_cpu_, and _smooth_l1_kernel_ have a 'greater then',  and _smooth_l1_cpu_ has a
'smaller then'  operator.


`void smooth_l1_cpu(int n, float *pred, float *truth, float *delta, float *error)
            delta[i] = (diff < 0) ? 1 : -1;

void l1_cpu(int n, float *pred, float *truth, float *delta, float *error)
        delta[i] = diff > 0 ? 1 : -1;

__global__ void smooth_l1_kernel(int n, float *pred, float *truth, float *delta, float *error)
            delta[i] = (diff > 0) ? 1 : -1;
