### ISSUE TITLE
yolov3: add detection layer 

### ISSUE THREAD

**Issue by jay-master** [AlexeyAB/darknet#4790]
I want to detect small object and I read a paper which says the fourth detection layer helps to detect more objects in the frame.
I have a problem that some objects are detected but others are not detected.
So I want to try to add one more detection layer. I saw that someone says it could be easily added in .cfg file but I have no idea how. Would someone help me?

**Comment by AlexeyAB** [comment]
Use https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov3_5l.cfg

**Comment by jay-master** [comment]
@AlexeyAB Thanks a lot!

**Comment by jay-master** [comment]
@AlexeyAB I am using that confidence file. During training it is interrupted after several hundreds of iterations and print message like this:

/bin/bash: line 1:  2892 Killed                  ./darknet detector train /mydrive/obj.data /mydrive/cfg/yolov3_5d.cfg /mydrive/weights/darknet53.conv.74 -dont_show > /mydrive/backup/train.log

I am running it in google colab. What kind of problem is this?
