### ISSUE TITLE
Segmentation fault when training yolo v2 with VOC dataset

### ISSUE THREAD

**Issue by khunglongs73** [AlexeyAB/darknet#48]
Hi,

Currently I got problem when trying to train the darknet with original voc 2007-2012 following the guide in this repo.

My error is always segmentation fault like below:

```
./darknet detector train cfg/voc.data cfg/yolo-voc.cfg darknet19_448.conv.23
yolo-voc
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  32
   ....
   30 detection
Loading weights from darknet19_448.conv.20...mj = 0, mn = 1, *(net->seen) = 0
load_convolutional_weights: l.n*l.c*l.size*l.size = 864
...
load_convolutional_weights: l.n*l.c*l.size*l.size = 128000
Done!
Learning Rate: 0.0001, Momentum: 0.9, Decay: 0.0005
Segmentation fault (core dumped)
```
In more detail, gdb shows this related error:

```
Core was generated by `./darknet detector train cfg/voc.data cfg/yolo-voc.cfg darknet19_448.conv.23'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  ipl_to_image (src=0xffffffffa0007dc0) at ./src/image.c:461
```
any hint to resolve this issue?

**Comment by AlexeyAB** [comment]
As I see you use Linux-Yolo-version.
So may be error - is wrong pointer `(src=0xffffffffa0007dc0)` passed to the function ` ipl_to_image()` in `./src/image.c`: https://github.com/pjreddie/darknet/blob/master/src/image.c#L456

1. Do you use last commit? from: https://github.com/pjreddie/darknet
2. Did you compile with or without OpenCV?
3. Did you change the source code?

* If you compile with OpenCV, then try to find an error there in function `load_image_cv()`: https://github.com/pjreddie/darknet/blob/master/src/image.c#L476

* If you compile **without** OpenCV, then try to find an error there in function `load_image_stb()`: https://github.com/pjreddie/darknet/blob/master/src/image.c#L1261

**Comment by khunglongs73** [comment]
Thank you for your quick reply Alex.
1. Yes I used latest commit from the repo you gave.
2. I compiled with opencv 3.1. also GPU=1,CUDNN=1 and DEBUG=1 (with gcc -O4)
3. I changed on file that related to opencv 3.1 videoio_c.h missing ( art.c,classifier.c,demo.c,go.c,image.c,rnn.c,rnn_vid.c,regressor.c,voxel.c)

I cleaned everything, download from the repo again, compile with above setting and edit then run the train again. This time it shows

```
./darknet detector train cfg/voc.data cfg/yolo-voc.cfg darknet19_448.conv.23
yolo-voc
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  32
   ...
   31 detection
Loading weights from darknet19_448.conv.23...Done!
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Saving weights to backup/yolo-voc_final.weights
Segmentation fault (core dumped)
```
gdb still shows the error from ipl_to_image:

I checked the weights file in backup folder, just 41kb. So I don't know what problem is now.

**Comment by khunglongs73** [comment]
Hi Alex,
Just found the problem, it's opencv compatible error. Solved with opencv=0 flag.
Thank you for your support Alex.

**Comment by AlexeyAB** [comment]
Darknet Yolo currently doesn't support OpenCV 3.x. Yolo supports only OpenCV 2.x.x versions.

To use OpenCV 3.x try this: https://github.com/adroit91/darknet

Or look at his pull-request: https://github.com/pjreddie/darknet/pull/35

**Comment by AlexeyAB** [comment]
@khunglongs73 
Now this repository supports:

* both Windows and Linux
* both OpenCV 3.x and OpenCV 2.4.13
* both cuDNN 5 and cuDNN 6
* CUDA >= 7.5
* also create SO-library on Linux and DLL-library on Windows

----

Also such bug as  wrong pointer `(src=0xffffffffa0007dc0)` passed to the function `ipl_to_image()` now is fixed by using `load_image_stb(filename, c);` instead of `load_image_cv(filename, c);` for OpenCV 3.x: https://github.com/AlexeyAB/darknet/blob/37259078f02b797ece6bf67aa6179cb05ba92d47/src/image.c#L1310
