### ISSUE TITLE
Can be object detection and image classification done at the same time?

### ISSUE THREAD

**Issue by agirbau** [AlexeyAB/darknet#480]
I know that darknet can perform object detection and image classification separately, but is it prepared to do them both at the same time? I assume that it is not, because it would need 2 different outputs (one using convolutional layers, and the other a set of fully connected layers to perform the classification).
Anyway, I just ask if it this is actually feasible. Thanks!

**Comment by AlexeyAB** [comment]
Why you don't want to do just detection? https://www.youtube.com/watch?v=llBhBSgoWPs

Or for example use Yolo 9000 that can detect about 9000 classes? https://www.youtube.com/watch?v=OLw6F3eJ5FU

**Comment by agirbau** [comment]
Hello! 
I wanted to do some very basic action recognition by just classifying an image, while having the object detection for other purposes, and I wanted to be using the same inference in order to have both tasks completed and not to have them running in parallel. 
Like learning the same weights for the initial layers (in order to detect basic shapes and so) and having 2 parallel outputs, one for detection and the other for classification.

**Comment by AlexeyAB** [comment]
So do you want to train one model with two output: detector and classifier - for example train Detector, and the Fine-tune Classifier? It would require many changes in the source code.

Or you can just detect that objects which you want to classify, and use only `class_id` and `prob` from the detector (and dont use x,y,w,h).
