### ISSUE TITLE
^c interrupt 

### ISSUE THREAD

**Issue by FarzadAvari** [AlexeyAB/darknet#4820]
I was running the below line of code 
" !./darknet detector train /content/darknet/data/obj.data cfg/yolov3-tiny_obj.cfg yolov3-tiny.conv.15 "

and the console started to print the model output and finally it stopped as below. 

-Done! Loaded 15 layers from weights-file 
-Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
-Resizing
-608 x 608 
-^C
-----------------------------------
The ^C stops the processing and there is no error but the model learning doesn't start. I checked online for the same but iddn't find any solution. My GPU is enabled and I ran this code  on Google colab. Can you help ?

**Comment by sambo55** [comment]
try adding -clear 1 at the end

**Comment by FarzadAvari** [comment]
Hi ,

I added the command as you said but it didn't work.
- !./darknet detector train /content/darknet/data/obj.data cfg/yolov3-tiny_obj.cfg yolov3-tiny.conv.15 -clear 1

**Comment by sambo55** [comment]
Ok, the other time this happened for me there was something wrong with my train/test.txt files. Have you double checked all the paths are pointing to the right places? If you can share the setup files it might be easier to see what's happening.

**Comment by AlexeyAB** [comment]
Try to add flag `-dont_show`
Also check that you compiled Darknet with GPU=1 CUDNN=1
And check files bad.list bad_label.list

**Comment by FarzadAvari** [comment]
@sambo55 : yes i have double checked the paths in  the train.txt. Which files would you like me to share with you ? 

@AlexeyAB : I tried adding the flag and also I changed the CUDNN value to 1 in the makefile. Still didn't work :(

**Comment by FarzadAvari** [comment]
I can share the notebook and the data.zip file if that helps
[pynbWithData.zip](https://github.com/AlexeyAB/darknet/files/4174895/pynbWithData.zip)

**Comment by stephanecharette** [comment]
Note one of your images is incorrectly tagged:

![image](https://user-images.githubusercontent.com/5061352/74090941-9aa75a80-4a66-11ea-8594-f249872ec5a1.png)

Note your images are quite huge (3023x2989) for what you are trying to do.  I just tested it with this command on my GPU rig which doesn't have X, and it is working fine for me:

`darknet detector -map -dont_show train FarzadAvari.data FarzadAvari_yolov3-tiny.cfg`

Note the use of `-dont_show` so it doesn't try to open a X window.

Anything show up in dmesg when you see ^C?

**Comment by FarzadAvari** [comment]
@stephanecharette : Thank you for pointing out the mistake in the label file. I corrected the same but the code still fails to work. As mentioned by you i tried the below command : 
-  !./darknet detector -map -dont_show train /content/darknet/data/obj.data cfg/yolov3-tiny_obj.cfg yolov3-tiny.conv.15 

I don't see any error after the ^c line. Do you think reducing the size of the images to a standard resolution would work ? 

![screenshot](https://user-images.githubusercontent.com/43061951/74129911-c6614680-4c06-11ea-9e76-91ca47c4c75f.PNG)

**Comment by stephanecharette** [comment]
> I don't see any error after the ^c line.

I had asked if there was anything logged in dmesg when darknet fails.

> Do you think reducing the size of the images to a standard resolution would work ?

No, I don't think changing your image size will help you with this problem.  First, you need to get more details on what is failing.  In my case, I have a computer where if I enable GPU in darknet then it segfaults.  Looking at it now, it isn't dmesg that logs the segfault, it is /var/log/apport.log.

In one window, run this command:

```
sudo tail -F /var/log/*log
```

In another window, run darknet like you usually do and see if anything gets logged when darknet quits.

**Comment by AlexeyAB** [comment]
Try to set random=0 in the last [yolo] layer in yolov3-tiny_obj.cfg

**Comment by FarzadAvari** [comment]
Guys, I standardized the image sizes and it started working. The command I used was : 

- !./darknet detector -map train /content/darknet/data/obj.data cfg/yolov3-tiny_obj.cfg yolov3-tiny.conv.15 -dont_show

Thank you very much @sambo55 , @AlexeyAB  and @stephanecharette for all your help :)

**Comment by AlexeyAB** [comment]
> Guys, I **standardized** the image sizes and it started working. 

What does it mean?

**Comment by FarzadAvari** [comment]
I resized the image dimensions to 600 x 600 and then ran the code with new label points and that did the trick.

**Comment by FarzadAvari** [comment]
they were of similar sizes but not exactly the same.

**Comment by Luxato** [comment]
@FarzadAvari
I've run into exactly the same issue. The resolution of the images shouldn't matter because YOLO itself is resizing them.
I'm also training on Google Colab and there is no bad.list or bad_label.list generated.
There has to be some error message instead of just "^C".

**Comment by FarzadAvari** [comment]
@Luxato actually you are right. Even I was of the same opinion as I saw the resizing of the images in the code. But when I normalized all the images to one particular size, it started to work. You can try that too.
