### ISSUE TITLE
What is the correct way of annotating when there is a class inside another class (box within a box)

### ISSUE THREAD

**Issue by kmsravindra** [AlexeyAB/darknet#4834]
Hi @AlexeyAB,

A quick annotation question - 

I have a scenario similar to the image I have attached here wherein I have to annotate a different class inside another class for some set of images (Circle class has to be bounded within a triangle class bounding box). At the same time, I have images where circles appear individually as well. But whenever triangle appears, circle is always inside it. 

Can I do the annotation as in the below image whenever triangle and circle appear together?
![class_inside_class](https://user-images.githubusercontent.com/3147499/74160874-11e61580-4c44-11ea-8b90-308e5f6d9c71.jpg)

Thanks!

**Comment by AlexeyAB** [comment]
> Can I do the annotation as in the below image whenever triangle and circle appear together?

Yes.
