### ISSUE TITLE
gpu memory leak

### ISSUE THREAD

**Issue by dohu337** [AlexeyAB/darknet#4841]
when calling free_network(network net), I think some gpu memory is not released.

For example yolov3, ROUTE layer delta_gpu is allocated but it is not released.(l.keep_delta_gpu flag)
I did a workaround, but i think it is not the original solution. Please check this issue.

```
void free_layer_custom(layer l, int keep_cudnn_desc)
{

   ...

    if (l.delta_gpu && l.keep_delta_gpu && l.optimized_memory < 3) cuda_free(l.delta_gpu), l.delta_gpu = NULL;

  ...

}

route_layer make_route_layer(int batch, int n, int *input_layers, int *input_sizes, int groups, int group_id)
{
 ...
   #ifdef GPU
    l.forward_gpu = forward_route_layer_gpu;
    l.backward_gpu = backward_route_layer_gpu;

    l.delta_gpu =  cuda_make_array(l.delta, outputs*batch);
    l.output_gpu = cuda_make_array(l.output, outputs*batch);
    #endif
 ...
}
```

**Comment by AlexeyAB** [comment]
I fixed it: https://github.com/AlexeyAB/darknet/commit/03eee3092f5084fd58b97cba8d1734db2f29022b

Because l.optimized_memory==0 by default, then all GPU-memory will be freed.
