### ISSUE TITLE
where to find cmake configuration 

### ISSUE THREAD

**Issue by gogoIsComing** [AlexeyAB/darknet#4852]
i have installed all the dependencies and i want to compile darknet on windows using cmake ,
but i was wondering should i have to write all configurations showing here in image :

![55107892-6becf380-50e3-11e9-9a0a-556a943c429a](https://user-images.githubusercontent.com/33967218/74319955-76aa8880-4d88-11ea-9a1b-af0ad09fe20e.png)

or there is place where all these configs already written
P.S
i am new to darknet and cmake

**Comment by AlexeyAB** [comment]
> or there is place where all these configs already written

Yes.

**Comment by gogoIsComing** [comment]
@AlexeyAB where ???

**Comment by CatHas4Paw** [comment]
@gogoIsComing i think i have the same errors. 
How do you fixes this?

**Comment by gogoIsComing** [comment]
> @gogoIsComing i think i have the same errors.
> How do you fixes this?

i followed [this](https://github.com/AlexeyAB/darknet#how-to-compile-on-windows-using-cmake)

**Comment by CatHas4Paw** [comment]
@gogoIsComing thank you for your reply. 
I have followed [this](https://github.com/AlexeyAB/darknet#how-to-compile-on-windows-using-cmake), but i get the following error: 
![image](https://user-images.githubusercontent.com/82372482/133760681-45c76c99-ac85-4c6a-b0bd-98e8ab5ab3a4.png)

According to the error list, CMake can't find any instance of VS. 
I have installed Microsoft Visual Studio Community 2019 Version 16.11.3

**Comment by CatHas4Paw** [comment]
i have fixed the problem with a repair on VS2019.
