### ISSUE TITLE
Custom yolov3-spp weights very slow on vanilla yolov3

### ISSUE THREAD

**Issue by mmartin56** [AlexeyAB/darknet#4860]
Hi @AlexeyAB ,

I trained yolov3-spp 416x416 on my custom dataset with your fork. Training & testing are all working as expected. Demoing on video works nicely - it runs @35FPS and uses only ~1.7GiB on GPU-RAM, out of 8GiB on my RTX2070.

I have tried to test & demo the resulting trained cfg/weights on pjreddie's master branch (because I'd prefer if my new weights run on that version of yolo, too). It runs @1-2 FPS only. Also, it uses almost all of the GPU-RAM (7Gib). Any idea why?

On pjreddie's yolo, Yolov3-spp 416x416 runs @30FPS with the original coco weights (yolov3-spp.weights). So it seems that training with your fork might change the structure of the weights something.

I noticed yolov3-spp.weights is 252209544 bytes while the weights I get by training with your fork are 250572504 bytes. Could it be the reason why pjreddie's yolov3 goes wrong with the new weights?

Thanks in advance!

**Comment by AlexeyAB** [comment]
set batch=1 in cfg-file if you use https://github.com/pjreddie/darknet

**Comment by mmartin56** [comment]
Thanks @AlexeyAB, that does fix the GPU-RAM issue (now using 1.7GiB just like in your fork) but it still runs at 1-2 FPS vs 35 FPS for your fork. Any idea why?

I also have some issues with other networks (CSResNext50, yolo_tiny_3l). With yolo_tiny_3l cfg and weights file downloaded from #3114 , I run:
`./darknet detector demo one_class.data yolov3-tiny_3l.cfg yolov3-tiny_3l_last.weights video.mkv`
and I get, on pjreddie's branch:
```
Demo
First section must be [net] or [network]: No such file or directory
darknet: ./src/utils.c:256: error: Assertion `0' failed.
Aborted (core dumped)
```
yolov3-tiny_3l.cfg's first lines are:
```
[net]
# Testing
batch=1
subdivisions=1
# Training
#batch=64
#subdivisions=4
width=544
height=544
channels=3
momentum=0.9
```

That same command line runs fine with your yolo (130 FPS).

**Comment by mmartin56** [comment]
Hi @AlexeyAB , do you have any idea why a model trained on your fork does not run properly on the master branch? Do you usually try to ensure compatibility with the older code?

Thank you in advance

**Comment by AlexeyAB** [comment]
yolov3-spp.cfg/weights with batch=1 subdivisions=1 works fast on https://github.com/pjreddie/darknet that is compiled with GPU=1 CUDNN=1 OPENCV=1
make clean
make

**Comment by mmartin56** [comment]
Thanks @AlexeyAB , I think I've figured it out. I think I owe you an explanation :)

In my trained models, because of implementation choices, a lot of objects get objectness scores close to 100%. Class scores are the real decider, with a lot of class scores close to 0. That's not a problem on your fork, because right after the GPU returns the weights, all objects for which [ objectness * class < threshold ] are removed so everything works fast as expected. 

In contrast, after the GPU returns the weights, I remember that pjreddie's darknet deals with objects (non-max suppression, etc - not sure about all the details here) based on the objectness scores for a little while. With my model that outputs lots of high objectness scores, that's a problem: darknet deals with thousands of objects with the CPU. GPU usage is ~10% and FPS is super low.

Apart from that detail, I think compatibility is great with pjreddie's darknet. Great work!

**Comment by AlexeyAB** [comment]
What command do you use for detection?
Do you use detection on video file?
What resolution of videofile?
What resolution of network (width= height in cfg)?

**Comment by mmartin56** [comment]
Hi Alexey, I fixed the problem, thank you. Nothing wrong with your code :)

**Comment by AlexeyAB** [comment]
@mmartin56 
What was the reason?
