### ISSUE TITLE
Erros when trying to build darknet

### ISSUE THREAD

**Issue by thug1705** [AlexeyAB/darknet#488]
Hi All,

I am getting errors shown on the screenshot below. I am trying to build darknet, using Visual Studio 2015, Cuda 9.1 and cudnn 7.0. Version of OpenCV is 3.4.0 and it's Windows 10.

Any ideas how I could solve it ? 

Thanks!

![image](https://user-images.githubusercontent.com/29228328/37663801-e9fb72ea-2c51-11e8-8316-4667879d7f89.png)

**Comment by thug1705** [comment]
@AlexeyAB  any ideas I tried things installing Windows SDK but didn't help ? Thanks in advance

**Comment by AlexeyAB** [comment]
@thug1705 Do you build **x64 & Release**?
Can you show screenshot of the whole MSVS when darknet.sln is opened?

**Comment by thug1705** [comment]
Hi @AlexeyAB  thanks for your respond, you can find screenshot of whole MSVS below.

![image](https://user-images.githubusercontent.com/29228328/37935174-7c45c8ee-3148-11e8-8b4f-ddaea0fb71d3.png)

**Comment by AlexeyAB** [comment]
Did you open existing `darknet/build/darknet/darknet.sln`? 
Or did you create own solution manually?

**Comment by thug1705** [comment]
I opened existing solution from darknet\build\darknet folder.

**Comment by AlexeyAB** [comment]
Can you successfully compile `darknet/build/darknet/darknet_no_gpu.sln`?

**Comment by thug1705** [comment]
No it is failing as well. It looks like because opencv, although I have opnecv installed on this pc and it is under C:\opencv_3.0 folder as you described in installation document. 

Probably I did something wrong but not sure what.. ?

![darknet_no_gpu_msvs](https://user-images.githubusercontent.com/29228328/37937197-7e2f4538-3150-11e8-958e-c3cc4178a49a.png)

**Comment by AlexeyAB** [comment]
Do you use OpenCV 3.4.1? There is C API bug in the OpenCV 3.4.1.
Try to use OpenCV 3.4.0 or earlier.

**Comment by thug1705** [comment]
I am using opencv-3.4.0-vc14_vc15

**Comment by AlexeyAB** [comment]
Try to build Release & x64

**Comment by thug1705** [comment]
Yes that worked.

**Comment by AlexeyAB** [comment]
So now try to update your code from this repo, then open `darknet.sln` and build it Release & x64.

**Comment by thug1705** [comment]
Sorry I didn't understand, which code should I update ?

**Comment by AlexeyAB** [comment]
Try to download this code again: https://github.com/AlexeyAB/darknet/archive/master.zip
then open darknet.sln and build it Release & x64.

**Comment by thug1705** [comment]
I tried but same errors.

![darknet_msvs](https://user-images.githubusercontent.com/29228328/37938921-199e458a-3158-11e8-929a-9e80ab36ae1a.png)

**Comment by thug1705** [comment]
@AlexeyAB  I fixed by creating another user account without special character as previous account was R&D and because '&' was treated as special character it couldn't execute Cuda commands. Anyway thanks for help.
