### ISSUE TITLE
Running 'darknet.exe' on Windows CMD Error

### ISSUE THREAD

**Issue by AlainMindana** [AlexeyAB/darknet#4889]
When I try running this line on Windows CMD:

darknet.exe detector train data/obj.data yolo-obj.cfg darknet53.conv.74

This error shows:

'darknet.exe' is not recognized as an internal or external command,
operable program or batch file.

How can I solve this?

**Comment by stephanecharette** [comment]
Did you build it?  Cause when you clone the repo, you typically only have the source code, it then needs to be built.  If you did build it, the check your path/directory to make sure where you built it is where you're attempting to run.
