### ISSUE TITLE
About the license

### ISSUE THREAD

**Issue by lyqqhgzj** [AlexeyAB/darknet#4892]
hi@AlexeyAB ,What kind of license is this work?
LPGP, Mozilla, GPL, BSD, MIT, Apache,?

**Comment by stephanecharette** [comment]
See the `LICENSE` file in the source code:  https://github.com/AlexeyAB/darknet/blob/master/LICENSE

**Comment by lyqqhgzj** [comment]
> See the `LICENSE` file in the source code: https://github.com/AlexeyAB/darknet/blob/master/LICENSE

In fact, the first paragraph says we can't use it, but later it says we can use it freely. I need to enter a competition and use only open source projects that are licensed.（Apache，MIT，BSD）

**Comment by stephanecharette** [comment]
> In fact, the first paragraph says we can't use it

I kindly suggest you re-read it if you think that is what it says.

**Comment by BernoGreyling** [comment]
Not sure where you read that you can't use it? First paragraph is supposed to be humorous... 

The takeaway still remains: 

> 0. Darknet is public domain.
> 1. Do whatever you want with it.
> 2. Stop emailing me about it!

**Comment by lyqqhgzj** [comment]
> Not sure where you read that you can't use it? First paragraph is supposed to be humorous...
> 
> The takeaway still remains:
> 
> > 1. Darknet is public domain.
> > 2. Do whatever you want with it.
> > 3. Stop emailing me about it!

I don't know the Chinese meaning of ALL CAP. YOU DON'T MESS AROUND WITH COPYRIGHT LAW BECAUSE YOU WILL GET IN. I don't want to GET IN. The competition organizers also don't know how the code will be used in the future, possibly commercially.

**Comment by BernoGreyling** [comment]
I am not a lawyer of any kind so anyone might have a more clear answer. But as far as the license is concerned with what is available, it is in the public domain and you can do with it whatever you want. Commercial or otherwise.

**Comment by AlexeyAB** [comment]
@lyqqhgzj There are several mutually exclusive licenses in the original repository: GPL vs MIT https://github.com/pjreddie/darknet

But the main license: https://github.com/pjreddie/darknet/blob/master/LICENSE

> ALL CAP. YOU DON'T MESS AROUND WITH COPYRIGHT LAW BECAUSE YOU WILL GET IN.

"Don't break the law, otherwise you will have problems" This is just a general phrase. The law works regardless of the presence of this phrase.

> Do whatever you want with it.

This is what you can do.

**Comment by lyqqhgzj** [comment]
> @lyqqhgzj There are several mutually exclusive licenses in the original repository: GPL vs MIT https://github.com/pjreddie/darknet
> 
> But the main license: https://github.com/pjreddie/darknet/blob/master/LICENSE
> 
> > ALL CAP. YOU DON'T MESS AROUND WITH COPYRIGHT LAW BECAUSE YOU WILL GET IN.
> 
> "Don't break the law, otherwise you will have problems" This is just a general phrase. The law works regardless of the presence of this phrase.
> 
> > Do whatever you want with it.
> 
> This is what you can do.

Does that mean I can use its MIT license?

**Comment by AlexeyAB** [comment]
> Does that mean I can use its MIT license?

Yes.

**Comment by lyqqhgzj** [comment]
thank you

**Comment by SpaceDigi** [comment]
this license relates to darknet framework only or it can be used for yolov4, yolov7 in cfg folder free absolutely? Can it be used in commercial or only custom models based on darknet or from cfg too? Thanks

**Comment by SpaceDigi** [comment]
> this license relates to darknet framework only or it can be used for yolov4, yolov7 in cfg folder free absolutely? Can it be used in commercial or only custom models based on darknet or from cfg too? Thanks

this license relates to darknet framework only or it can be used for yolov4, yolov7 in cfg folder free absolutely? Can it be used in commercial or only custom models based on darknet or from cfg too? Thanks

**Comment by SpaceDigi** [comment]
> > Does that mean I can use its MIT license?
> 
> Yes.

this license relates to darknet framework only or it can be used for yolov4, yolov7 in cfg folder free absolutely? Can it be used in commercial or only custom models based on darknet or from cfg too? Thanks
