### ISSUE TITLE
blur seems not to be worked.

### ISSUE THREAD

**Issue by dsgh2** [AlexeyAB/darknet#4900]
Hi, Alexey!

According to below an instruction, This darknet repository supports two types of blur. The one is blur background except for objects, the other one is blur on whole image.

blur=1 - will be used Gaussian blur with kernel=31x31 only for background except objects
blur=2 and higher 3,4... - will be used Gaussian blur with kernel=blur X blur (blur-value will be increased up to odd value) for whole image.

However, blur seems not to be worked even though blur=2 and blur=17, blur=31 was set when I tried.

Am I doing wrong? Please let me know about this if you do not mind.

**Comment by AlexeyAB** [comment]
> However, blur seems not to be worked even though blur=2 and blur=17, blur=31 was set when I tried.

How did you check it?

Show screenshot of training with flag `-show_imgs` at the end of training command.

**Comment by dsgh2** [comment]
Thank you!

I have updated latest commit just before and run with -show_imgs

[net]
# Testing
#batch=1
#subdivisions=1
batch=64
subdivisions=16
width=512
height=512
channels=3
momentum=0.9
decay=0.0005
angle=0
#saturation = 1.5
#exposure = 1.5
#hue=.1
**blur=2**

like above, I have only changed "blur". and also jitter=.0

I have checked with blur=0, blur=1, blur=2, ... blur=64
[blur.zip](https://github.com/AlexeyAB/darknet/files/4236629/blur.zip)

There was no whole blur on image, I think.

**Comment by AlexeyAB** [comment]
The full-image blur will be applied, only if `blur_size < (minimal_size_of_object / 8)` in the current image, to avoid losing infromation about this object. 
You can comment `//` thes line to disable such behavior and recompile: 
https://github.com/AlexeyAB/darknet/blob/0ee9c8668f787ddaa6ab51dc3b71bb87f521007f/src/data.c#L1081

**Comment by dsgh2** [comment]
> The full-image blur will be applied, only if `blur_size < (minimal_size_of_object / 8)` in the current image, to avoid losing infromation about this object.
> You can comment `//` thes line to disable such behavior and recompile:
> https://github.com/AlexeyAB/darknet/blob/0ee9c8668f787ddaa6ab51dc3b71bb87f521007f/src/data.c#L1081

Thank you so much! Now it works!
![aug_1187155336_0_1172995706](https://user-images.githubusercontent.com/42986646/75123527-8cef0780-56eb-11ea-9771-e929561dfab4.jpg)
![aug_2029900519_0_687090290](https://user-images.githubusercontent.com/42986646/75123529-8d879e00-56eb-11ea-80ef-86059d4c764b.jpg)
