### ISSUE TITLE
How to use horizontal flip? 

### ISSUE THREAD

**Issue by maykulkarni** [AlexeyAB/darknet#4904]
Hi! 

I am training a detector where I'd like to use horizontal flip. I was browsing through the issues but couldn't find a `flip=1` switch which does that. However after reading the code [there's](https://github.com/AlexeyAB/darknet/blob/0ee9c8668f787ddaa6ab51dc3b71bb87f521007f/src/data.c#L160) a region that does flipping. How would I use it ?

**Comment by AlexeyAB** [comment]
use 
```
[net]
flip=1
```

**Comment by maykulkarni** [comment]
Thanks. FYI it's not mentioned in the [wiki](https://github.com/AlexeyAB/darknet/wiki/CFG-Parameters-in-the-%5Bnet%5D-section).
