### ISSUE TITLE
saving weights after 10 iterations

### ISSUE THREAD

**Issue by gogoIsComing** [AlexeyAB/darknet#4909]
hi @AlexeyAB , thanx for this implementation, but i have the following case : 
i am using google colab to train darknet , so i have about 12h of session before it is recycled , and every iterations is take about 1h on my dataset , so i want to save my weights after 10 iteration for example, where to modify this in code ???
and is it okay for each iteration to take 1h on google colab ????

P.S.
Dataset = 1000 image
batch = 64
subdivisions=16
google colab GPU : Tesla K80 GPU
cuda : 10
cudnn : 7

**Comment by WongKinYiu** [comment]
https://github.com/AlexeyAB/darknet/blob/master/src/detector.c#L308
