### ISSUE TITLE
Getting error while using mAP command.

### ISSUE THREAD

**Issue by zahidhussaina2l** [AlexeyAB/darknet#4910]
I am getting "Couldn't open file: data/train.txt" while executing mAP command for darknet from your rep. But when I use train command, it works fine and 13000 steps are done with the training with the following comand,
!./darknet detector train "obj.data" "yolov3.cfg" "backup/yolov3_last.weights" -dont_show
This does not give error but when I use 
!./darknet detector map "obj.data" "yolov3.cfg" "backup/yolov3_last.weights"
Above error occurs.

Please help me in this issue.
![image](https://user-images.githubusercontent.com/56002453/75181968-3ae8c900-5761-11ea-8484-f86f88dfeb90.png)

**Comment by zahidhussaina2l** [comment]
Hi, I think I solved this issue and got some validation output but still not getting graph for the valition like you have in your documentation which has a red line for validation.

**Comment by zahidhussaina2l** [comment]
@AlexeyAB Please help bro....

**Comment by zahidhussaina2l** [comment]
The output of map command is 
![image](https://user-images.githubusercontent.com/56002453/75196865-a7be8c00-577e-11ea-9750-b8ddab96e4ef.png)
But the graph still looks like this one
![image](https://user-images.githubusercontent.com/56002453/75196893-bad15c00-577e-11ea-9a27-f917127f6771.png)
 @AlexeyAB  is there anything that I am missing in it?

**Comment by AlexeyAB** [comment]
Look at the console, there is written when mAP will be calculated.

**Comment by zahidhussaina2l** [comment]
Hi @AlexeyAB I can't find it on console, can you please point it in the screenshot above which is the console output.

**Comment by AlexeyAB** [comment]
In the same line where is Avg loss.

Run training with `-map` flag at the end. And mAP will be calculated for each 4 epoch (`4 x number_of_images / 64` iterations)

**Comment by zahidhussaina2l** [comment]
I am using google Colab for training purpose, so is there any way I can generate graph from there without a monitor because on Colab it gives monitor related error when using - map flag.

**Comment by AlexeyAB** [comment]
Compile with OpenCV
Ad Use `-map -dont_show`

**Comment by zahidhussaina2l** [comment]
Will try it, Thanks..

**Comment by zahidhussaina2l** [comment]
It worked like a charm. Thanks
