### ISSUE TITLE
training time on google colab

### ISSUE THREAD

**Issue by gogoIsComing** [AlexeyAB/darknet#4920]
hi @AlexeyAB , thanx for this implementation, but i have the following case : 
i am using google colab to train darknet , and every iterations is take about 1h on my dataset, is it okay for a single iteration to take 1h ???

P.S.
Dataset = 1000 image
batch = 64
subdivisions=16
google colab GPU : Tesla K80 GPU
cuda : 10
cudnn : 7

**Comment by AlexeyAB** [comment]
> and every iterations is take about 1h 

Compile Darknet with GPU=1 CUDNN=1 in the Makefile
