### ISSUE TITLE
open ( mAP & Loss-chart ) remote server on google colab

### ISSUE THREAD

**Issue by gogoIsComing** [AlexeyAB/darknet#4922]
hi @AlexeyAB ,
i executed the following command on google colab to start training and to see `mAP & Loss-chart` during training :
`!./darknet detector train data/obj.data cfg/yolo-obj.cfg weights/darknet53.conv.74 -dont_show -mjpeg_port 8090 -map`
but the problem is how to open this remote server on colab.
for example my colab VM `ip address` is xxxx and when i open `http://xxxx:8090` in chrome , no thing is shown , Any Help.

**Comment by rushipatel7** [comment]
Yes i am having the same problem, if anyone knows the solution it would be of much help. Thank you.

**Comment by hbiserinska** [comment]
Does anyone know how to avoid losing  mAP & Loss-chart due to Colab disconnection.

**Comment by gogoIsComing** [comment]
@hbiserinska here is what i did : 

1. i put my darknet project folder in google drive 
2. copy the `darknet` file to colab
3. start training using `darknet` file

so the `chart.png` will save on the root of darknet project  witch is in google drive , and by this no thing will be lost.

**Comment by gogoIsComing** [comment]
@rushipatel7 it turns out you can't open `mAP & loss-chart` remote server , but there is `chart.png` that you can see your progress in it.
