### ISSUE TITLE
Looking for a CUDA compiler - NOTFOUND

### ISSUE THREAD

**Issue by kimchicanh** [AlexeyAB/darknet#4927]
I use cuda 10, when I run nvcc --version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

I use GPU titan V

Thanks

**Comment by haviduck** [comment]
Whats your cuda env paths?

**Comment by kimchicanh** [comment]
@haviduck usr/local/cuda
I tried: cmake -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.0 .. But it does not work

**Comment by uday60** [comment]
export cuda in /etc/bash.bashrc

**Comment by cenit** [comment]
Please post 
1) system details (os, version, ...)
2) full log from console during a fresh build 
3) CMakeCache.txt 
in case you still have problems.

**Comment by kimchicanh** [comment]
Thanks all. I re-instal cuda and it can run now

**Comment by cenit** [comment]
perfect
