### ISSUE TITLE
Help in understanding draw_detections_cv_v3 function in 'image_opencv.cpp' file

### ISSUE THREAD

**Issue by bagminer** [AlexeyAB/darknet#4930]
Hi,
Can you help in understanding the purpose of `else` in the `draw_detections_cv_v3` function ([Line 889](https://github.com/AlexeyAB/darknet/blob/f6baa62c9b6151b9f615a1e56434d237553fd4af/src/image_opencv.cpp#L889) - [Line 893](https://github.com/AlexeyAB/darknet/blob/f6baa62c9b6151b9f615a1e56434d237553fd4af/src/image_opencv.cpp#L893) ?

What I have understood is that if the model is getting two detection with probability higher than the mentioned threshold it will go to `else `statement. Let me know if this is correct.

**Comment by sambo55** [comment]
Yes if there are two classes predicted for that specific bounding box then we will add both to the label string.
