### ISSUE TITLE
Possible bug in fill_network_boxes?

### ISSUE THREAD

**Issue by Alex18947** [AlexeyAB/darknet#4942]
Hi all, either there's a bug in the code or I simply cannot understand the following line:

https://github.com/AlexeyAB/darknet/blob/master/src/network.c#L786

Adding the result of get_yolo_detections to the *pointer* seems to be wrong. Instead of 

`dets += count;`

shouldn't we add

`dets += count * sizeof(detection)`

Provided this is a bug, I don't understand why things go well with this ;).

A.

**Comment by AlexeyAB** [comment]
There is no error: https://ideone.com/tZqEsM

stdout 
`0, 0x64`

https://www.viva64.com/en/t/0005/

> Pointer arithmetic provides the programmer with a single way of dealing with different types: adding and subtracting the number of elements required instead of the actual offset in bytes. In particular, the C definition explicitly declares that **the syntax A[i], which is the i-th element of the array A, is equivalent to *(A+i)**, which is the content of the element pointed by A+i. This also implies that i[A] is equivalent to A[i].

**Comment by Alex18947** [comment]
Thanks, oops, of course, forgot about pointer arithemtics.
