### ISSUE TITLE
./src/network.c:1136:17: error: ‘for’ loop initial declarations are only allowed in C99 mode

### ISSUE THREAD

**Issue by chouxianyu** [AlexeyAB/darknet#4959]
i use `make` to build the repo, found this error
>./src/network.c: In function ‘fuse_conv_batchnorm’:
./src/network.c:1136:17: error: ‘for’ loop initial declarations are only allowed in C99 mode
                 for (int i = 0; i < l->nweights; ++i) printf(" w = %f,", l->weights[i]);
                 ^
compilation terminated due to -Wfatal-errors.
make: *** [obj/network.o] Error 1

**Comment by stephanecharette** [comment]
How exactly are you building?  On what platform, what OS, and what compiler?

**Comment by wangm27** [comment]
you can change the 
for (int i = 0; i < l->nweights; ++i) printf(" w = %f,", `l->weights[i]); to
int i; 
for (i = 0; i < l->nweights; ++i) printf(" w = %f,", l->weights[i]);

**Comment by chouxianyu** [comment]
I downloaded the latest repository today, and this error disappeared.
It seems that it has been solved by the author.
