### ISSUE TITLE
Detection extremely slow on MacOS

### ISSUE THREAD

**Issue by stuartrexking** [AlexeyAB/darknet#4960]
When I run detect on my AWS GPU instance I'm get a prediction time of **10.5 Milliseconds**:

```bash
[yolo] params: iou loss: mse (2), iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
Total BFLOPS 65.312 
avg_outputs = 516922 
 Allocate additional workspace_size = 52.43 MB 
Loading weights from backup/dandy-yolov3_final.weights...
 seen 64, trained: 256 K-images (4 Kilo-batches_64) 
Done! Loaded 107 layers from weights-file 
images/4995e7a5-2cf1-4e2e-8a6e-febca680694a.png: Predicted in 10.520000 milli-seconds.
```

When I run detection on my 2017 MBP it takes **25 seconds**:

```
[yolo] params: iou loss: mse (2), iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
Total BFLOPS 65.312 
avg_outputs = 516922 
Loading weights from weights/dandy-yolov3_final.weights...
 seen 64, trained: 256 K-images (4 Kilo-batches_64) 
Done! Loaded 107 layers from weights-file 
images/4995e7a5-2cf1-4e2e-8a6e-febca680694a.png: Predicted in 24898.415000 milli-seconds.
```

I've compiled for CPU with and without OpenCV for both the GPU instance and MBP and I get the same consistent results.

* Any idea why I'm seeing such a slow inference time on the MBP? 
* I've compiled with DEBUG=1 on the MBP but there is no difference in the output.
* Detect produces a prediction.jpg. Is it possible to disable this?

**Comment by AlexeyAB** [comment]
Because MacBook Pro doesnt have nVidia GPU and doesn't support CUDA and cuDNN.

**Comment by stuartrexking** [comment]
Ok thank you. I expected some slower performance but not 25seconds.

**Comment by AlexeyAB** [comment]
Compile with AVX=1 OPENMP=1

**Comment by stuartrexking** [comment]
Silly me. 

With AVX=1 and OPENMP=1 the detection is down to under a second. I had seen this in the documentation. Thought I had already tried it.

Thanks @AlexeyAB
