### ISSUE TITLE
extracting list of detections from YOLOv3

### ISSUE THREAD

**Issue by AhmedMohamedBehwashi** [AlexeyAB/darknet#4964]
Hello Guys,
I'm working on an object detection app using YOLOv3 I retrained the model to detect two classes and it was done successfully so far thanks to the creators of the Repo.
Now I have to deploy the model on a jetson nano kit and it should run continuously and extract the list of detections specifying classes, confidence and bounding boxes coordinates then I should do some processing on the previously mentioned parameters then send it using any communication protocol to another ECU, anyway How to extract the mentioned parameters from YOLOv3 and make that code run continuously ?

**Comment by PaserSRL** [comment]
You need just to write python/c++ application and use darknet library in order to execute detection and obtain detection results.
I did the same on a jetson nano :)

**Comment by PaserSRL** [comment]
I can give you an help only about Python.

Before to compile darknet, set LIBSO=1 in Makefile.
You will obtain **libdarknet.so**, in this repo you have already:
- darknet.py -> wrapper for libdarknet.so library
- darknet_video.py -> a working exemple of how to use darknet wrapper, objtain detections and draw bounding boxed on frame analized

**Comment by AhmedMohamedBehwashi** [comment]
so should I create my own file to capture a video stream from an attached camera the same way these two files were made or should I edit these two files?

**Comment by stephanecharette** [comment]
I just got my Jetson Nano working last night.  Key is to use a power cable, because if you try to power it over USB it will shut itself down as soon as you try to use the GPU on it.  Once you have adequate power hooked up to it, put it into 10W mode with `sudo nvpmodel -m 0`.

In my case, the entire project is in C++.  It loads the network once and then repeatedly examines images from a camera, logging the results to a database on the network.  Loading the neural network (yolov3-tiny in my case) takes 4060 milliseconds, but every 640x480 image then takes 56 or 57 milliseconds, which lets me do about 10fps.

**Comment by AhmedMohamedBehwashi** [comment]
I need a starting point to write my code to read a video stream from the camera and do inferencing and do the detections then sending it to another ECU, so is there a recommended point should I start from?

**Comment by stephanecharette** [comment]
If it helps, this is the library I personally use (open source project I wrote) to talk to Darknet:  https://www.ccoderun.ca/darkhelp/api/API.html

To get the images (frames) from the video, I would personally use OpenCV.  Lots of OpenCV example code to read frames.  Maybe start with https://www.ccoderun.ca/programming/doxygen/opencv/classcv_1_1VideoCapture.html ?

**Comment by PaserSRL** [comment]
With my code (python) I'm able to run detection on 2 streams at the same time at 8-9 fps each.
With a single stream I'm able to reach 18-20 fps.

**Comment by PaserSRL** [comment]
With my code (python) I'm able to run detection on 2 streams at the same time at 8-9 fps each.
With a single stream I'm able to reach 18-20 fps.

Using yolov3-tiny-prn.
