### ISSUE TITLE
Failed to compile on GPU=1 (Makefile:155: recipe for target 'obj/im2col_kernels.o' )

### ISSUE THREAD

**Issue by Ujang24** [AlexeyAB/darknet#4969]
I got this error:
=== BEGIN
```
/usr/local/cuda/include/cuda_fp16.hpp(2054): error: invalid redeclaration of type name "half2"
/usr/include/cuda_fp16.h(94): here

21 errors detected in the compilation of "/tmp/tmpxft_0000089d_00000000-10_im2col_kernels.compute_61.cpp1.ii".
Makefile:155: recipe for target 'obj/im2col_kernels.o' failed
make: *** [obj/im2col_kernels.o] Error 1
```
=== END

As a background,
For a reason, I reinstalled my PC with Ubuntu 16.04 LTS, NVIDIA Driver 418.43, CUDA 10.1, CuDNN 7.5.
I used the same way as before when I could build darknet smoothly.
I used an NVIDIA RTX 2070.
I have just (5 March 2020) cloned the last version of this repo.
Somehow, I could not build darknet using make when turn the GPU=1 in the Makefile.
I used the original Makefile. Only the GPU=1 gives error.

I have tried:
```
export PATH=/usr/local/cuda-10.1/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
sudo make
```
But the error still occurs.

These are the result of `nvidia-smi, nvcc --version,` and `gcc --version`
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.39       Driver Version: 418.39       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   41C    P0    45W / 225W |    319MiB /  7951MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1081      G   /usr/lib/xorg/Xorg                           189MiB |
|    0      1902      G   compiz                                       128MiB |
+-----------------------------------------------------------------------------+

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

uname -r
4.15.0-88-generic

**Comment by uzairrizwan** [comment]
I am unable to resolve a similar issue:

`Makefile:168: recipe for target 'obj/convolutional_kernels.o' failed
make: *** [obj/convolutional_kernels.o] Error 127`

**Comment by AlexeyAB** [comment]
> Cuda compilation tools, release 7.5, V7.5.17

Remove CUDA 7.5 and install CUDA 10

**Comment by Ujang24** [comment]
> > Cuda compilation tools, release 7.5, V7.5.17
> 
> Remove CUDA 7.5 and install CUDA 10

Yes, that is correct. It's working now. Thank you.

So what I did, I remove cuda 7.5 toolkit (only) by: 
`sudo apt-get remove --auto-remove nvidia-cuda-toolkit`

Then I reinstall cuda-toolkit 10.1 using (simplified):
```
wget http://developer.download.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.243_418.87.00_linux.run 
sudo sh cuda_10.1.243_418.87.00_linux.run
```
Tick toolkit only because I already have driver and cuda base installed.

The detail guide is here:
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
