### ISSUE TITLE
Face Identification in video 

### ISSUE THREAD

**Issue by deepkshikha** [AlexeyAB/darknet#497]
I have done face detection. If I need to identify some of the faces among all In my case 5 out of 23 face then is it possible if I annotate 5 faces by their identity and for rest label as unknown faces?? I am annotating 500 for each face is it sufficient?? Thanks for response in advance

**Comment by AlexeyAB** [comment]
Yes, you can use 6 classes: 5 required faces + 1 rest faces.

500 images per class is sufficient, but for the best result, it is better to use 2000 images per class.

**Comment by deepkshikha** [comment]
Thanks a lot AlexeyAB  I have to do the same for for video I am annotating video frames and annotating  way as frames using labelImg tool and then applying testing Is it correct method for video or  some other way are used to annotate video directly???

**Comment by lesreaper** [comment]
I followed this guide and it does a pretty good job or explaining the steps. Alexey always recommends Yolo Mark, which I've used to good effect. I also follow this too: https://timebutt.github.io/static/how-to-train-yolov2-to-detect-custom-objects/

I'm using RectLabel on a mac, and modifying for the program. I'm going to do a post on it soon.

**Comment by AlexeyAB** [comment]
@deepkshikha Yes, you can annotate images (frames) from the videofile.

I use Yolo_mark for this: https://github.com/AlexeyAB/Yolo_mark
* to slice video to frames: `./yolo_mark x64/Release/data/img cap_video test.mp4 10`
* to annotate these frames: `./yolo_mark x64/Release/data/img x64/Release/data/train.txt x64/Release/data/obj.names`

**Comment by deepkshikha** [comment]
Thanks a lot @AlexeyAB , @lesreaper
