### ISSUE TITLE
Different prediction results between this branch and original pjreddie branch

### ISSUE THREAD

**Issue by ymtsang** [AlexeyAB/darknet#4981]
I have some old models trained on darknet version in pjreddie branch. Since AlexeyAB branch is faster in training and inference, I am planning to port all my old models to this branch. But I found that there are different prediction results on two branches on the exactly same image, model and cfg. Here is an example:

I downloaded the stock pre-trained yolov2-tiny weights from https://pjreddie.com/media/files/yolov2-tiny.weights

I am showing the results in yolov2-tiny because it is the simplest. I checked the detector.c. The processing in input images look the same. The forward_paths for convolutional layer and maxpool layer are also the same between two branches. I am not sure why I got different results. Would you shed some lights on why we have such differences? 

command:
```
./darknet detector test cfg/coco.data cfg/yolov2-tiny.cfg yolov2-tiny.weights data/dog.jpg -thresh 0.25
```
The outputs are:
pjreddie branch:
```
dog: 82%
car: 74%
car: 38%
car: 30%
bicycle: 59%
person: 27%
person: 26%
```
AlexeyAB branch:
``` 
dog: 28%
bicycle: 84%
motorbike: 50%
person: 28%
person: 43%
dog: 52%
car: 67%
```

**Comment by AlexeyAB** [comment]
Use flag `-letter_box` at the end of command

**Comment by ymtsang** [comment]
Thanks @AlexeyAB. It works!!!
