### ISSUE TITLE
Resume Training From Last Backup

### ISSUE THREAD

**Issue by P0pzi** [AlexeyAB/darknet#4987]
Hi there,

I'd accidentally shut my PC down like a nonce halfway through alot of training.

Is there any way to resume training using the checkpoints / latest backups in /build/darknet/x64/backup ?

**Comment by WongKinYiu** [comment]
`darknet.exe detector train data/obj.data cfg/model.cfg backup/model_last.weights`

**Comment by P0pzi** [comment]
@WongKinYiu Thank you ❤️ life saver
