### ISSUE TITLE
how to save only the coordinates of the bounding box of yolo darknet in a txt file? 

### ISSUE THREAD

**Issue by arthurlopesds** [AlexeyAB/darknet#4991]
I can save all video detection output in a txt file, but I just wanted the value of the coordinates of the bounding box in the txt.

**Comment by stephanecharette** [comment]
Do you mean something similar to these 2 bullets from the readme?

- To process a list of images data/train.txt and save results of detection to result.json file use: `darknet.exe detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights -ext_output -dont_show -out result.json < data/train.txt`
- To process a list of images data/train.txt and save results of detection to result.txt use:
`darknet.exe detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights -dont_show -ext_output < data/train.txt > result.txt`

**Comment by arthurlopesds** [comment]
Yes @stephanecharette , but I wanted a way to save only the coordinate data of the bounding box.

**Comment by stephanecharette** [comment]
In that case I would look into using the API instead of the command-line tool.

**Comment by arthurlopesds** [comment]
ok, but in what way?
Using some form of file manipulation?

**Comment by stephanecharette** [comment]
> ok, but in what way?

One possible way is with the libdarknet.so API.  Another is with the DarkHelp C++ API:  https://www.ccoderun.ca/darkhelp/api/API.html

Yet another is with the JSON output:  https://www.ccoderun.ca/darkhelp/api/ShellScripting.html

**Comment by arthurlopesds** [comment]
Thank you @stephanecharette !
