### ISSUE TITLE
how to get a visualization image of the model?

### ISSUE THREAD

**Issue by Jmx5200** [AlexeyAB/darknet#5]
I just want to know what is the differences between the model of v1 and v2, if we can see the image of the model architecture, will be better.

**Comment by AlexeyAB** [comment]
@Jmx5200 

* Yolo v1 network file: https://github.com/pjreddie/darknet/blob/8f1b4e0962857d402f9d017fcbf387ef0eceb7c4/cfg/yolo.cfg
* Yolo v2 network file: https://github.com/pjreddie/darknet/blob/c6afc7ff1499fbbe64069e1843d7929bd7ae2eaa/cfg/yolo.cfg
* split diff v1 -> v2: https://github.com/pjreddie/darknet/commit/c6afc7ff1499fbbe64069e1843d7929bd7ae2eaa?diff=split#diff-4a34e423192b561bc5553ce2c11a6668

You can see the picture of neural network in the article: https://arxiv.org/pdf/1506.02640v5.pdf

**Comment by Jmx5200** [comment]
@AlexeyAB 
OK, thanks very much. I will focus on these files.
