### ISSUE TITLE
Syntax errors in C librarys when trying to compile with VS2015, WIN10

### ISSUE THREAD

**Issue by FaBeyyy** [AlexeyAB/darknet#500]
Compiling with cudnn 7, cuda 3
![unbenannt](https://user-images.githubusercontent.com/22794105/37863697-bf170cd8-2f62-11e8-86c2-eabdd09cfa64.png)

**Comment by AlexeyAB** [comment]
@FaBeyyy Hi,

> Compiling with cudnn 7, cuda 3

* CUDA 3 was released 8 years ago - you are not mistaken?

* What OpenCV version do you use?

**Comment by FaBeyyy** [comment]
Yeah sorry my mistake  havent slept all night... so:

OpenCv: 3.4.1
Cuda: 9.1

What i tried: Setting the compilation settings from C to C++ which resultet into the C library errors going away but new conversion errors popping up as it is probably not the way to go.
![unbenannt](https://user-images.githubusercontent.com/22794105/37869337-1c02ecd4-2fb6-11e8-8b89-cad37c97d682.png)

A weird warning that i get is : **"'cuda_gridsize' has C-linkage specified, but returns UDT 'dim3' which is incompatible with C"**

**Comment by AlexeyAB** [comment]
This is a bug in OpenCV 3.4.1 in the C API: https://github.com/opencv/opencv/issues/10963

Use OpenCV 3.4.0 or earlier.

**Comment by FaBeyyy** [comment]
Worked, thank you so much for the quick help.

**Comment by ruin1990** [comment]
tks a lot, i was also met this problem and solve it now by this issue.

**Comment by arshiana** [comment]
Can't fix this problem...... iam using OpenCv 3.4.0
![screenshot 1](https://user-images.githubusercontent.com/20219739/44275841-ccde5000-a213-11e8-8297-6e98d0e06174.png)

**Comment by AlexeyAB** [comment]
@arshiana Try to use this OpenCV version: https://sourceforge.net/projects/opencvlibrary/files/opencv-win/3.3.0/opencv-3.3.0-vc14.exe/download

**Comment by arshiana** [comment]
![screenshot 2](https://user-images.githubusercontent.com/20219739/44300120-ada4f880-a2cf-11e8-972a-1326bea63427.png)
Same errors.... i am using CUDA 9.2 Will it be a problem?? i can't find CUDA 9.1

**Comment by wadaxy** [comment]
What is a recommended version of OpenCV at this moment for the Darknet environment?
Thank you in advance.
