### ISSUE TITLE
10 weeks to train yolov3 on coco

### ISSUE THREAD

**Issue by skywo1f** [AlexeyAB/darknet#5004]
I have been running the yolov3.cfg training script on a titan rtx for the last week (on the coco dataset). I have only reached step 50k out of 500k. Looking at the results so far, they show something, but it is pretty bad (had to set -thresh to 0.05). Is it true that this should take 9 more weeks? or am I doing something wrong?

**Comment by stephanecharette** [comment]
I'm not familiar with coco.  But when I train my own networks, it takes just over 9 hours to reach 40K.  Things that make a difference:

- Darknet compiled with OpenCV, GPU, CUDNN, CUDDN_HALF
- The actual GPU hardware

My GPU is the RTX 2070.  I know little about hardware, but I believe the Titan RTX is a higher end card than what I have.  Did you enable the ARCH=... line at the top of Darknet's makefile for the RTX?

**Comment by AlexeyAB** [comment]
* What `width height batch subdivisions` did you use in cfg-file?
* Show such screenshot
![image](https://user-images.githubusercontent.com/4096485/76416672-909db200-63ac-11ea-80a8-0f6f64e538d4.png)

**Comment by skywo1f** [comment]
batch=224
subdivisions=64
width=608
height=608


~/neural-nets/alexDark$ ./darknet detector train coco.data yolov3.cfg backup/yolov3.backup  -gpus 0
 CUDA-version: 10020 (10020), cuDNN: 7.6.5, CUDNN_HALF=1, GPU count: 1  
 OpenCV version: 4.2.0
0
yolov3
 compute_capability = 750, cudnn_half = 1 
net.optimized_memory = 0 
batch = 3, time_steps = 1, train = 1 
   layer   filters  size/strd(dil)      input                output
   0 conv     32       3 x 3/ 1    608 x 608 x   3 ->  608 x 608 x  32 0.639 BF

**Comment by skywo1f** [comment]
> I'm not familiar with coco. But when I train my own networks, it takes just over 9 hours to reach 40K. Things that make a difference:
> 
>     * Darknet compiled with OpenCV, GPU, CUDNN, CUDDN_HALF
> 
>     * The actual GPU hardware
> 
> 
> My GPU is the RTX 2070. I know little about hardware, but I believe the Titan RTX is a higher end card than what I have. Did you enable the ARCH=... line at the top of Darknet's makefile for the RTX?

**Comment by AlexeyAB** [comment]
Read: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

> change line batch to batch=64
> change line subdivisions to subdivisions=16


Why did you increase batch-size?
If you want to increase mini_batch-size, then just decrease `subdivisions=8` or 4 or 2

----

If you increase `batch=256`, then you should decrease `max_batches=125000`
batch/subdivisions - should be an integer value, so use `subdivisions=64` or better to use  `subdivisions=32`

----

Also, do you use random=1 in the last [yolo]-layer?
And do you use dynamic_minibatch=1?
```
[net]
dynamic_minibatch=1
```

----

> Did you enable the ARCH=... line at the top of Darknet's makefile for the RTX?

If you compiled Darknet with cuDNN, then in the most cases it isn't necessary to change ARCH=

**Comment by skywo1f** [comment]
I increased the batch size because I thought that if the gpu has more memory, then it can train on more pictures at a time, increasing training efficiency. I switched it back to batch=64 and subdivisions= 16. I was using random=1, but not dynamic_minibatch. That is now set to 1 as well. I will continue the training and report back if it sped up at all (or if I see a decrease in loss).

**Comment by AlexeyAB** [comment]
> I thought that if the gpu has more memory, then it can train on more pictures at a time, increasing training efficiency. 

mini_batch = batch / subdivisions

so set subdivisions=8 or 4 or 2 the lower the better

And set dynamic_minibatch=1

**Comment by skywo1f** [comment]
So with all of these settings in place, it managed to move 10k steps in one night. (Out of the total 500k). This makes me think that either coco is just a large bad dataset, or yolov3 just takes that long to train well.

**Comment by AlexeyAB** [comment]
> So with all of these settings in place, it managed to move 10k steps in one night.

With which settings?

I think your settings are bad.

Use
```
batch=64
subdivisions=4
width=416
height=416
```

**Comment by skywo1f** [comment]
Ok just to make sure there was nothing else wrong, I re-downloaded the yolov3.cfg from the repo. I then replaced those 4 lines you suggested, plus the random and dynamic_minibatch lines. In one day, it went 18k out of the total 500k steps.

**Comment by AlexeyAB** [comment]
* dynamic_minibatch=1 will slowdown your training
* Do you use SSD disk?


* Show such screenshot
![image](https://user-images.githubusercontent.com/4096485/76621103-b14a4100-653f-11ea-90e3-224c80465b93.png)

**Comment by skywo1f** [comment]
Tensor Cores are disabled until the first 3000 iterations are reached.
 1: 2077.635254, 2077.635254 avg loss, 0.000000 rate, 4.095489 seconds, 64 images
Loaded: 0.000032 seconds
v3 (mse loss, Normalizer: (iou: 0.75, cls: 1.00) Region 82 Avg (IOU: 0.419288, GIOU: 0.334226), Class: 0.566027, Obj: 0.482023, No Obj: 0.482471, .5R: 0.380000, .75R: 0.020000, count: 50, class_loss = 329.557098, iou_loss = 10.447968, total_loss = 340.005066

**Comment by AlexeyAB** [comment]
Try to set - it will speed up training and increase accuracy
```
batch=64 
subdivisions=2
```

Also try to set - it will speed up training **but decrease accuracy**
```
dynamic_minibatch=0
```

**Comment by AlexeyAB** [comment]
Also set
```
[net]
loss_scale=128
```

remove ` && !state.train` from these two lines:
1.  https://github.com/AlexeyAB/darknet/blob/d79d2815b9b8f9172b988406bd2a4ccb3a2dff15/src/convolutional_kernels.cu#L424
2. https://github.com/AlexeyAB/darknet/blob/d79d2815b9b8f9172b988406bd2a4ccb3a2dff15/src/convolutional_kernels.cu#L676
  
recompile Darknet and train your model - it will use Tensor Cores for training.

**Comment by skywo1f** [comment]
I ran out of memory with those settings. I will try it again with subdivisions at 4. Another odd thing, is that the webcam demo only seems to run at 2fps. I don't know if that helps with the puzzle.

**Comment by skywo1f** [comment]
removing those two lines seems to have caused other problems
` Tensor Cores are used.
 3001: 5.973927, 5.354743 avg loss, 0.001000 rate, 1.426614 seconds, 192064 images
Loaded: 0.000036 seconds
v3 (mse loss, Normalizer: (iou: 0.75, cls: 1.00) Region 82 Avg (IOU: 0.744720, GIOU: 0.732317), Class: 0.422651, Obj: 0.134352, No Obj: 0.005611, .5R: 0.967742, .75R: 0.548387, count: 31, class_loss = 2.588073, iou_loss = 0.627562, total_loss = 3.215635 
v3 (mse loss, Normalizer: (iou: 0.75, cls: 1.00) Region 94 Avg (IOU: 0.653122, GIOU: 0.635186), Class: 0.267854, Obj: 0.063319, No Obj: 0.001324, .5R: 0.928571, .75R: 0.285714, count: 42, class_loss = 4.269115, iou_loss = 1.562771, total_loss = 5.831886 
v3 (mse loss, Normalizer: (iou: 0.75, cls: 1.00) Region 106 Avg (IOU: 0.580962, GIOU: 0.558252), Class: 0.252975, Obj: 0.017030, No Obj: 0.000436, .5R: 0.708333, .75R: 0.125000, count: 24, class_loss = 2.611742, iou_loss = 1.018955, total_loss = 3.630697 

 cuDNN status Error in: file: ./src/convolutional_kernels.cu : () : line: 727 : build time: Mar 15 2020 - 11:15:18 

 cuDNN Error: CUDNN_STATUS_BAD_PARAM
cuDNN Error: CUDNN_STATUS_BAD_PARAM: Resource temporarily unavailable
darknet: ./src/utils.c:325: error: Assertion `0' failed.
Aborted (core dumped)
`

**Comment by AlexeyAB** [comment]
@skywo1f Try to train with flag `-cuda_debug_sync -benchmark_layers` and with the latest Darknet code. And show eerror mesage.

**Comment by skywo1f** [comment]
~/neural-nets/alexDark$ git config --get remote.origin.url
https://github.com/AlexeyAB/darknet.git
~/neural-nets/alexDark$ git pull
Already up to date.
~/neural-nets/alexDark$ ./darknet detector train ../openCvDarknet/cfg/coco.data yolov3.cfg -gpus 0 -clear -cuda_debug_sync -benchmark_layers
 CUDA-version: 10020 (10020), cuDNN: 7.6.5, CUDNN_HALF=1, GPU count: 1  
 OpenCV version: 4.2.0
0
yolov3
 compute_capability = 750, cudnn_half = 1 
net.optimized_memory = 0 
batch = 16, time_steps = 1, train = 1 
   layer   filters  size/strd(dil)      input                output
   0 conv     32       3 x 3/ 1    416 x 416 x   3 ->  416 x 416 x  32 0.299 BF
...
 105 conv    255       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 255 0.353 BF
 106 yolo
[yolo] params: iou loss: mse (2), iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
Total BFLOPS 65.879 
avg_outputs = 532444 
 Allocate additional workspace_size = 677.43 MB 
Loading weights from -cuda_debug_sync...Couldn't open file: -cuda_debug_sync

**Comment by AlexeyAB** [comment]
Do you use the latest Darknet version?

https://github.com/AlexeyAB/darknet/blob/92e6e8eece3b789616430cad51a5afdb5a3153fc/src/darknet.c#L469

**Comment by skywo1f** [comment]
oh, it looks like I forgot to re-make after downloading the new version... Though now I am getting a make error:
/usr/bin/ld: cannot find -lcuda

**Comment by AlexeyAB** [comment]
Do you have cuda.so in the `/usr/local/cuda/lib` ?
Did you enable symbolic link creation during CUDA installation?
Try to change path to CUDA in the Makefile:
* so-files https://github.com/AlexeyAB/darknet/blob/master/Makefile#L105
* h-files https://github.com/AlexeyAB/darknet/blob/master/Makefile#L100

**Comment by skywo1f** [comment]
Ok, I was able to fix it, the key is to remove the -lcuda flag. I ran with the "-cuda_debug_sync -benchmark_layers" flags and reached step 19k (out of 500k) in one night with the updated code. I will try the updated code with the new flags and the (&& !state.train) removals today.

**Comment by AlexeyAB** [comment]
Just to know, flags `-cuda_debug_sync -benchmark_layers` allow you to more specifically catch the place of error, but slow down training.

Also show output of commands
```
nvcc --version
nvidia-smi
gcc --version
```


Also there was a simial issue, the problem was in incompatible CUDA/cuDNN/GPU-Driver versions for training with Tensor Cores FP16 on Tesla T4/Titan V : https://github.com/AlexeyAB/darknet/issues/5007#issuecomment-600056662

**Comment by skywo1f** [comment]
~/neural-nets/alexDark$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

~/neural-nets/alexDark$ nvidia-smi
Tue Mar 17 13:21:36 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.48.02    Driver Version: 440.48.02    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN RTX           Off  | 00000000:01:00.0  On |                  N/A |
| 50%   70C    P2   116W / 280W |  10500MiB / 24212MiB |     51%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1309      G   /usr/lib/xorg/Xorg                            16MiB |
|    0      1452      G   /usr/bin/gnome-shell                          50MiB |
|    0      2171      G   /usr/lib/xorg/Xorg                           106MiB |
|    0      2331      G   /usr/bin/gnome-shell                         139MiB |
|    0     13589      C   ./darknet                                  10181MiB |
+-----------------------------------------------------------------------------+

~/neural-nets/alexDark$ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by skywo1f** [comment]
this time the program did not crash at 3k steps. I will try rerunning it over the weekend (without the-cuda_debug_sync -benchmark_layers flags) to see how far it can get.

**Comment by skywo1f** [comment]
Ok, With the suggestions, I was able to go ~50k steps in a day. That would mean that it would take about 10 days to train yolov3 on coco. Does that sound right?

**Comment by AlexeyAB** [comment]
> Ok, With the suggestions, I was able to go ~50k steps in a day. That would mean that it would take about 10 days to train yolov3 on coco. Does that sound right?

Yes.

**Comment by AlexeyAB** [comment]
@skywo1f 

Did you successfully trained yolov3.cfg on MSCOCO by using RTX Titan?
* with CUDNN_HALF=1 in the Makefile
* and with `[net] batch=64 subdivisions=4 dynamic_minibatch=0 loss_scale=128` and `[yolo] random=1` 

What mAP (accuracy) did you get?

Or can you show generated `chart.png` with Loss?

----

In the latest code for taining by using FP32/16-TensorCores you should just set CUDNN_HALF=1 in the Makefile and  `[net] loss_scale=128` in cfg-file, without changing source code.
