### ISSUE TITLE
using darknet as dll failed

### ISSUE THREAD

**Issue by wisdomk** [AlexeyAB/darknet#5015]
I am trying, after compiling and building "yolo_cpp_dll.sln" to generate the required dll, to add it to a new empty C++ project in VIsualStudio however I am getting an exception of "reading violation due to too long string" thrown when parsing/reading cfg and weight file as their pointers apparently got lost and point at random memory address for one reason or another!!
(maybe I am missing some libraries or dependencies to include yet even though I tried to get sure to include every necessary directory and file e.g. OpenCV, yolo_v2_class.hpp, darknet.h; otherwise it won't compile :/ )

it works with no problem if I run the "yolo_console_dll.sln" project though!

any ideas or reference on how to use the NN detector on an empty project?

please check the picture below...before calling the Detector the names were assigned rightly but after entering the function suddenly they got random values!
![image](https://user-images.githubusercontent.com/47982574/76534203-d7a9a700-6481-11ea-8082-3225178b6774.png)

**Comment by AlexeyAB** [comment]
I think you buld your project in Debug-mode. Try to build in Release.
Or you are doing something wrong.

**Comment by wisdomk** [comment]
yeah great... now it works ^_^
(it drove me crazy for few hours though... thanks)
