### ISSUE TITLE
Different Result between Image and Video

### ISSUE THREAD

**Issue by sweptdown** [AlexeyAB/darknet#5017]
Hello,

I test Yolov3 with images(*.jpg) and Video(avi) file after learning.
The images are extracted from the Video file.
However, result is something different.

When I used images, detection result is so good(perfectly).
But, video file, detection result is bad(miss or wrong detection).

Why is it so different? Please help me if you know. 
Have a nice day~!

**Comment by AlexeyAB** [comment]
Set `1` there and recompile: https://github.com/AlexeyAB/darknet/blob/d79d2815b9b8f9172b988406bd2a4ccb3a2dff15/src/demo.c#L41

**Comment by sweptdown** [comment]
I set 1 in the file and recompiled. But not solved it.

**Comment by sweptdown** [comment]
Oh! sorry. It was video file problem. I put a wrong video file(but it's similar) into the Yolov3.
Yolov3 is always right. 

Thank you for your quick and kind answer. I got inspiration from your answer even you don't know.
Have a really  nice day~!
