### ISSUE TITLE
streaming the result to external server (via url)

### ISSUE THREAD

**Issue by iceman-k** [AlexeyAB/darknet#502]
Hi, I'm now working on it with ubuntu(on ec2) . I want to send the result realtime from the ec2-ubuntu server to external server via url. Is there a way to live-stream to a specified url?

**Comment by AlexeyAB** [comment]
Hi, yes you can do it:

* Windows: `darknet.exe detector demo data/voc.data yolo-voc.cfg yolo-voc.weights test.mp4 -i 0 -http_port 8090 -dont_show`

* Linux: `./darknet detector demo data/voc.data yolo-voc.cfg yolo-voc.weights test.mp4 -i 0 -http_port 8090 -dont_show`

Then open in the Web-browser (FireFox, Chrome, but not in the IE) or in the OpenCV `cv::VideoCapture cap(url)` this url: `http://localhost:8090` or `http://<remoteIP>:8090`

----

But **on the Linux it can be unstable**, it uses this code to send HTTP-mjpeg traffic: https://github.com/AlexeyAB/darknet/blob/8f1f5cbf8321b6b313d8f455d596290e7b8bb3f7/src/http_stream.cpp#L53-L196

**Comment by iceman-k** [comment]
thank you very much!
