### ISSUE TITLE
Auto resize during testing? 

### ISSUE THREAD

**Issue by maykulkarni** [AlexeyAB/darknet#5024]
I know YOLO will resize the image size to the one in the configuration file during training. But I'd like to ask how should I have the same behaviour while testing? Or does it also resize the image during test time? I'm trying to run YOLOv3 on a 1400p video and it is very slow on NVIDIA 2070.

**Comment by AlexeyAB** [comment]
It resized image during training and testing.

**Comment by maykulkarni** [comment]
Thanks!
