### ISSUE TITLE
How to run darknet.exe from a different folder?

### ISSUE THREAD

**Issue by RobertAndreiGit** [AlexeyAB/darknet#5027]
If I try to run in cmd `F:\yolov3\darknet\darknet.exe detect cfg/yolov3.cfg yolov3.weights -ext_output data/dog.jpg` I get a `Couldn't open file: cfg/coco.data`

How can I achieve this? I guess there's a config file somewhere where I can set the absolute path for everything? But I can't find that.

And sorry if this doesn't qualify as an issues, I've been struggling for hours to run darknet from a java program.

**Comment by RobertAndreiGit** [comment]
I found where I had to change this, but now I get `Couldn't open file: data/coco.names` even after changing the file where I find that 'data/coco.names' (yolo_console_dll.cpp)

**Comment by yustaub** [comment]
> I found where I had to change this, but now I get `Couldn't open file: data/coco.names` even after changing the file where I find that 'data/coco.names' (yolo_console_dll.cpp)

hello, I meet the same problem, may I ask you how to solve it?? @RobertAndreiGit @AlexeyAB

**Comment by stephanecharette** [comment]
You can run darknet from any folder.  It doesn't need any particular directory structure, especially if your configuration files have absolute paths in them.

For example, see the darknet files that are generated by DarkMark: https://www.ccoderun.ca/darkmark/Summary.html#DarkMarkDarknet

**Comment by yustaub** [comment]
> You can run darknet from any folder. It doesn't need any particular directory structure, especially if your configuration files have absolute paths in them.
> 
> For example, see the darknet files that are generated by DarkMark: https://www.ccoderun.ca/darkmark/Summary.html#DarkMarkDarknet

thk , I know how to solve it, very appreciate!!
