### ISSUE TITLE
Error: Training with Gaussian_yolov3

### ISSUE THREAD

**Issue by BahaaMansour** [AlexeyAB/darknet#5031]
![image](https://user-images.githubusercontent.com/44228249/76696468-c87c6080-66f0-11ea-92a1-b4f392f9a932.png)

I was trying to train my weights using Gaussian_yolov3 and faced this error.

**Comment by AlexeyAB** [comment]
Use this repo https://github.com/AlexeyAB/darknet instead of https://github.com/pjreddie/darknet

**Comment by BahaaMansour** [comment]
I have done that, and i got this new error.

**Comment by BahaaMansour** [comment]
![image](https://user-images.githubusercontent.com/44228249/76712476-57838a00-677e-11ea-8958-eab1f9e1c3cf.png)

**Comment by WongKinYiu** [comment]
you route layer 93, 90, 87, and 84 where layer 93 has size 6x6 and the other layers have size 7x7.

**Comment by BahaaMansour** [comment]
[yolo_v3_tiny_pan5_matrix_gaussian_GIoU_aa_ae_mixup.cfg.txt](https://github.com/AlexeyAB/darknet/files/4335505/yolo_v3_tiny_pan5_matrix_gaussian_GIoU_aa_ae_mixup.cfg.txt)

this is my cfg

**Comment by BahaaMansour** [comment]
Ok I fixed, the issue. What i had to do is to follow this 
https://github.com/AlexeyAB/darknet/issues/3114#issuecomment-494148968
