### ISSUE TITLE
How does shortcut layer work?

### ISSUE THREAD

**Issue by lzyyzlwsldx** [AlexeyAB/darknet#5040]
Hi @AlexeyAB ,

When I tried to convert csresnext50 weights to tensorflow, I got an error about mismatching size of channel. So I looked up the cfg, I found they are different in filters in line 55 and line 82. 

<img width="257" alt="Screen Shot 2020-03-16 at 11 19 21 PM" src="https://user-images.githubusercontent.com/24862987/76773721-e83d8280-67dd-11ea-942e-305e4170396e.png">

I used to use yolov3.cfg and I think the shortcut is just an operation of adding, to add -1 layer and -4 layer that with same shape. But now I'm confused if there is an implicit operation in shortcut? Like conv 1*1 or some other ways to merge 2 layers.

**Comment by AlexeyAB** [comment]
> is just an operation of adding, to add -1 layer and -4 layer that with same shape

Yes.

But if shapes are not the same: https://github.com/AlexeyAB/darknet/issues/4662

![72104147-d225c880-333b-11ea-8692-b0b1b1b86bb8](https://user-images.githubusercontent.com/4096485/76779731-df888480-67bc-11ea-9bf8-4ab73ee4adf2.png)

**Comment by lzyyzlwsldx** [comment]
Thank you, it's very clear.
