### ISSUE TITLE
extracting list of detections from YOLOv3

### ISSUE THREAD

**Issue by AhmedMohamedBehwashi** [AlexeyAB/darknet#5058]
Hello Guys,
I'm working on an object detection app using YOLOv3 I retrained the model to detect two classes and it was done successfully so far.
Now I have to deploy the model on a jetson nano kit and it should run continuously and extract the list of detections specifying classes, confidence and bounding boxes coordinates then I should do some processing on the previously mentioned parameters then send it using any communication protocol to another ECU, anyway, I need to know the location of detected classes and bounding box variables in the code.

**Comment by Ahmedmostafa595** [comment]
@AlexeyAB i have exactly the same problem!
