### ISSUE TITLE
Use captured image from C++ (Windows GDI or directX) instead of load from file

### ISSUE THREAD

**Issue by FaBeyyy** [AlexeyAB/darknet#506]
I am currently using 
```auto img = detector.load_image(filename);```
to load an image file from my directory, but would like to capture the screen with the windows gdi in my console application which returns me a HBITMAP from the following code:
```
Void captureScreen()
{
    int nScreenWidth = GetSystemMetrics(SM_CXSCREEN);
    int nScreenHeight = GetSystemMetrics(SM_CYSCREEN);
    HWND hDesktopWnd = GetDesktopWindow();
    HDC hDesktopDC = GetDC(hDesktopWnd);
    HDC hCaptureDC = CreateCompatibleDC(hDesktopDC);
    HBITMAP hCaptureBitmap =CreateCompatibleBitmap(hDesktopDC, 
                            nScreenWidth, nScreenHeight);
    SelectObject(hCaptureDC,hCaptureBitmap); 
    BitBlt(hCaptureDC,0,0,nScreenWidth,nScreenHeight,
           hDesktopDC,0,0,SRCCOPY|CAPTUREBLT); 
   //function to convert bitmap here
    ReleaseDC(hDesktopWnd,hDesktopDC);
    DeleteDC(hCaptureDC);
    DeleteObject(hCaptureBitmap);
}
```

The problem i have now is trying to convert the HBITMAP to a useable image object that is normally being returned by load_image(filename);

Has anyone ever achieved something like this?
EDIT: Or has anyone managed to get a live video recording instead of a webcam to work? Like with using OBS or something cause i dont know how that should be working.

**Comment by FaBeyyy** [comment]
Ok i managed to get it done after 8 hours of non stop searching and working...

**Comment by ryanalexmartin** [comment]
> 
> 
> Ok i managed to get it done after 8 hours of non stop searching and working...

Would you mind sharing us how you did it?
