### ISSUE TITLE
Create xyolo

### ISSUE THREAD

**Issue by ZheQU-somfy** [AlexeyAB/darknet#5067]
Hi everyone, I have created xyolo.cfg like this,
[net]
# Testing
#batch=1
#subdivisions=1
# Training
batch=64
subdivisions=8
width=256
height=256
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
burn_in=1000
max_batches = 40000
policy=steps
steps=128000,216000
scales=.1,.1

[convolutional]
batch_normalize=1
filters=2
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
bin_output=1
batch_normalize=1
filters=4
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
bin_output=1
batch_normalize=1
filters=8
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
bin_output=1
batch_normalize=1
filters=16
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
bin_output=1
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=1

[convolutional]
xnor=1
bin_output=1
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

###########

[convolutional]
xnor=1
batch_normalize=1
filters=32
size=1
stride=1
pad=1
activation=leaky

[convolutional]
xnor=1
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[convolutional]
xnor=1
size=1
stride=1
pad=1
filters=75
activation=leaky

[yolo]
mask = 3,4,5
anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
classes=20
num=6
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1

[route]
layers = -4

[convolutional]
batch_normalize=1
filters=16
size=1
stride=1
pad=1
activation=leaky

[upsample]
stride=2

[route]
layers = -1, 8

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=75
activation=linear

[yolo]
mask = 0,1,2
anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
classes=20
num=6
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1
When I trainned the model with PASCAL VOC by using the commande: ./darknet detector train cfg/voc.data cfg/xyolo.cfg -dont_show
There is some segmentation errors in function binarize_weights ().
Can you help me to figure out what's going on?

**Comment by lsd1994** [comment]
Show screenshots

**Comment by ZheQU-somfy** [comment]
Hi, this is the screenshots of the error
./darknet detector train cfg/voc.data cfg/xyolo.cfg -dont_show
 GPU isn't used
 OpenCV version: 4.2.0
xyolo
mini_batch = 8, batch = 64, time_steps = 1, train = 1
   layer   filters  size/strd(dil)      input                output
   0 conv      2       3 x 3/ 1    256 x 256 x   3 ->  256 x 256 x   2 0.007 BF
   1 max                2x 2/ 2    256 x 256 x   2 ->  128 x 128 x   2 0.000 BF
   2 conv      4       3 x 3/ 1    128 x 128 x   2 ->  128 x 128 x   4 0.002 BF
   3 max                2x 2/ 2    128 x 128 x   4 ->   64 x  64 x   4 0.000 BF
   4 conv      8       3 x 3/ 1     64 x  64 x   4 ->   64 x  64 x   8 0.002 BF
   5 max                2x 2/ 2     64 x  64 x   8 ->   32 x  32 x   8 0.000 BF
   6 conv     16       3 x 3/ 1     32 x  32 x   8 ->   32 x  32 x  16 0.002 BF
   7 max                2x 2/ 2     32 x  32 x  16 ->   16 x  16 x  16 0.000 BF
   8 conv     32       3 x 3/ 1     16 x  16 x  16 ->   16 x  16 x  32 0.002 BF
   9 max                2x 2/ 2     16 x  16 x  32 ->    8 x   8 x  32 0.000 BF
  10 conv     64       3 x 3/ 1      8 x   8 x  32 ->    8 x   8 x  64 0.002 BF
  11 max                2x 2/ 1      8 x   8 x  64 ->    8 x   8 x  64 0.000 BF
  12 convXB  128       3 x 3/ 1      8 x   8 x  64 ->    8 x   8 x 128 0.000 BF
  13 convX    32       1 x 1/ 1      8 x   8 x 128 ->    8 x   8 x  32 0.000 BF
  14 convX    64       3 x 3/ 1      8 x   8 x  32 ->    8 x   8 x  64 0.000 BF
  15 convX    75       1 x 1/ 1      8 x   8 x  64 ->    8 x   8 x  75 0.000 BF
  16 yolo
[yolo] params: iou loss: mse (2), iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
  17 route  13 		                           ->    8 x   8 x  32
  18 conv     16       1 x 1/ 1      8 x   8 x  32 ->    8 x   8 x  16 0.000 BF
  19 upsample                 2x     8 x   8 x  16 ->   16 x  16 x  16
  20 route  19 8 	                           ->   16 x  16 x  48
  21 conv     32       3 x 3/ 1     16 x  16 x  48 ->   16 x  16 x  32 0.007 BF
  22 conv     75       1 x 1/ 1     16 x  16 x  32 ->   16 x  16 x  75 0.001 BF
  23 yolo
[yolo] params: iou loss: mse (2), iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
Total BFLOPS 0.028
avg_outputs = 17317
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Resizing, random_coef = 1.40
 384 x 384
Loaded: 0.209521 seconds
[1]    16610 segmentation fault (core dumped)  ./darknet detector train cfg/voc.data cfg/xyolo.cfg -dont_show

**Comment by lsd1994** [comment]
I tried with your cfg and trained normally. Maybe you should use GPU.

**Comment by ZheQU-somfy** [comment]
OK, i'll try it

**Comment by ZheQU-somfy** [comment]
You used same commande as me?

**Comment by ZheQU-somfy** [comment]
Ok, thanks, with GPU mode, it works very well.

**Comment by ZheQU-somfy** [comment]
I finished trainning of xyolo with Pascal VOC data set, i calculated map of this network, I've got this result with ./darknet detector map cfg/voc.data cfg/xyolo.cfg build/darknet/x64/backup/xyolo_last.weights -points 11:

calculation mAP (mean average precision)...
5824
 detections_count = 76829, unique_truth_count = 13841
class_id = 0, name = aeroplane, ap = 4.55%   	 (TP = 0, FP = 0)
class_id = 1, name = bicycle, ap = 2.27%   	 (TP = 0, FP = 0)
class_id = 2, name = bird, ap = 1.52%   	 (TP = 0, FP = 0)
class_id = 3, name = boat, ap = 2.60%   	 (TP = 0, FP = 0)
class_id = 4, name = bottle, ap = 0.43%   	 (TP = 0, FP = 0)
class_id = 5, name = bus, ap = 0.23%   	 (TP = 0, FP = 0)
class_id = 6, name = car, ap = 5.04%   	 (TP = 0, FP = 0)
class_id = 7, name = cat, ap = 0.12%   	 (TP = 0, FP = 0)
class_id = 8, name = chair, ap = 1.31%   	 (TP = 0, FP = 0)
class_id = 9, name = cow, ap = 2.27%   	 (TP = 0, FP = 0)
class_id = 10, name = diningtable, ap = 0.36%   	 (TP = 0, FP = 0)
class_id = 11, name = dog, ap = 0.22%   	 (TP = 0, FP = 0)
class_id = 12, name = horse, ap = 9.09%   	 (TP = 0, FP = 0)
class_id = 13, name = motorbike, ap = 9.09%   	 (TP = 0, FP = 0)
class_id = 14, name = person, ap = 13.36%   	 (TP = 1, FP = 0)
class_id = 15, name = pottedplant, ap = 0.13%   	 (TP = 0, FP = 0)
class_id = 16, name = sheep, ap = 9.99%   	 (TP = 4, FP = 3)
class_id = 17, name = sofa, ap = 0.19%   	 (TP = 0, FP = 0)
class_id = 18, name = train, ap = 0.10%   	 (TP = 0, FP = 0)
class_id = 19, name = tvmonitor, ap = 2.39%   	 (TP = 0, FP = 0)
 for conf_thresh = 0.25, precision = 0.62, recall = 0.00, F1-score = 0.00
 for conf_thresh = 0.25, TP = 5, FP = 3, FN = 13836, average IoU = 41.84 %
 IoU threshold = 50 %, used 11 Recall-points
 mean average precision (mAP@0.50) = 0.032627, or 3.26 %
Total Detection Time: 17 Seconds

Almost of TP and FP are 0. 
Can you help me to figure out what's going on?

**Comment by lsd1994** [comment]
I think this network is too simple, so it can not learn the pattern in the image.

**Comment by ZheQU-somfy** [comment]
I do what they wrote in this paper: https://arxiv.org/abs/1910.03159

**Comment by AlexeyAB** [comment]
You must use either `xnor=1 bin_output=1` or `xnor=1` but not `bin_output=1`.
You must use
```
[convolutional]
xnor=1
bin_output=1
batch_normalize=1
filters=8
size=3
stride=1
pad=1
activation=leaky
```

instead of
```
[convolutional]
bin_output=1
batch_normalize=1
filters=8
size=3
stride=1
pad=1
activation=leaky
```

**Comment by ZheQU-somfy** [comment]
I'va modified xyolo network like this:
And i trained this net work on machine of aws with coco image dataset with command ./darknet detector train cfg/coco.data cfg/xyolo.cfg -dont_show
[net] 
# Testing
#batch=1
#subdivisions=1
# Training
batch=64
subdivisions=16
width=256
height=256
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
burn_in=1000
max_batches = 160000
policy=steps
steps=512000,864000
scales=.1,.1

[convolutional]
batch_normalize=1
filters=2
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=4
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=8
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=16
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=1

[convolutional]
xnor=1
bin_output=1
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

###########

[convolutional]
xnor=1
bin_output=1
batch_normalize=1
filters=32
size=1
stride=1
pad=1
activation=leaky

[convolutional]
xnor=1
bin_output=1
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[convolutional]
xnor=1
size=1
stride=1
pad=1
filters=255
activation=leaky


[yolo]
mask = 3,4,5
anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
classes=80
num=6
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1

[route]
layers = -4

[convolutional]
batch_normalize=1
filters=16
size=1
stride=1
pad=1
activation=leaky

[upsample]
stride=2

[route]
layers = -1, 8

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky


[convolutional]
size=1
stride=1
pad=1
filters=255
activation=linear

[yolo]
mask = 0,1,2
anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
classes=80
num=6
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1

When i use ./darknet detector test cfg/coco.data cfg/xyolo.cfg data/person.jpg,
Nothing is detected. Could you please help me to solve this problem?

**Comment by AlexeyAB** [comment]
Conv layer before yolo layer shouldn't use `xnor=1`

> [convolutional]
> xnor=1
> size=1
> stride=1
> pad=1
> filters=255
> activation=leaky
> 
> [yolo]

**Comment by ZheQU-somfy** [comment]
Thanks for your answer, i'll try it.

**Comment by ZheQU-somfy** [comment]
I modified the net like this:
[net]
# Testing
#batch=1
#subdivisions=1
# Training
batch=64
subdivisions=16
width=256
height=256
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
burn_in=1000
max_batches = 160000
policy=steps
steps=512000,864000
scales=.1,.1

[convolutional]
batch_normalize=1
filters=2
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=4
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=8
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=16
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=1

[convolutional]
xnor=1
bin_output=1
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

###########

[convolutional]
xnor=1
bin_output=1
batch_normalize=1
filters=32
size=1
stride=1
pad=1
activation=leaky

[convolutional]
xnor=1
bin_output=1
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=75
activation=leaky


[yolo]
mask = 3,4,5
anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
classes=20
num=6
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1

[route]
layers = -4

[convolutional]
batch_normalize=1
filters=16
size=1
stride=1
pad=1
activation=leaky

[upsample]
stride=2

[route]
layers = -1, 8

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky


[convolutional]
size=1
stride=1
pad=1
filters=75
activation=linear

[yolo]
mask = 0,1,2
anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
classes=20
num=6
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1

And i trained it with VOC data set:
With the weight obtained, i want to mesure map of this net by using **./darknet detector map cfg/voc.data cfg/xyolo.cfg backup/xyolo_final.weights -points 11**

The result is below:
 CUDA-version: 10000 (10020), cuDNN: 7.5.1, CUDNN_HALF=1, GPU count: 1  
 CUDNN_HALF=1 
 OpenCV version: 3.2.0
 compute_capability = 750, cudnn_half = 1 
net.optimized_memory = 0 
mini_batch = 1, batch = 16, time_steps = 1, train = 0 
   layer   filters  size/strd(dil)      input                output
   0 conv      2       3 x 3/ 1    256 x 256 x   3 ->  256 x 256 x   2 0.007 BF
   1 max                2x 2/ 2    256 x 256 x   2 ->  128 x 128 x   2 0.000 BF
   2 conv      4       3 x 3/ 1    128 x 128 x   2 ->  128 x 128 x   4 0.002 BF
   3 max                2x 2/ 2    128 x 128 x   4 ->   64 x  64 x   4 0.000 BF
   4 conv      8       3 x 3/ 1     64 x  64 x   4 ->   64 x  64 x   8 0.002 BF
   5 max                2x 2/ 2     64 x  64 x   8 ->   32 x  32 x   8 0.000 BF
   6 conv     16       3 x 3/ 1     32 x  32 x   8 ->   32 x  32 x  16 0.002 BF
   7 max                2x 2/ 2     32 x  32 x  16 ->   16 x  16 x  16 0.000 BF
   8 conv     32       3 x 3/ 1     16 x  16 x  16 ->   16 x  16 x  32 0.002 BF
   9 max                2x 2/ 2     16 x  16 x  32 ->    8 x   8 x  32 0.000 BF
  10 conv     64       3 x 3/ 1      8 x   8 x  32 ->    8 x   8 x  64 0.002 BF
  11 max                2x 2/ 1      8 x   8 x  64 ->    8 x   8 x  64 0.000 BF
  12 convXB  128       3 x 3/ 1      8 x   8 x  64 ->    8 x   8 x 128 0.000 BF
  13 convXB   32       1 x 1/ 1      8 x   8 x 128 ->    8 x   8 x  32 0.000 BF
  14 convXB   64       3 x 3/ 1      8 x   8 x  32 ->    8 x   8 x  64 0.000 BF
  15 conv     75       1 x 1/ 1      8 x   8 x  64 ->    8 x   8 x  75 0.001 BF
  16 yolo
[yolo] params: iou loss: mse (2), iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
  17 route  13 		                           ->    8 x   8 x  32 
  18 conv     16       1 x 1/ 1      8 x   8 x  32 ->    8 x   8 x  16 0.000 BF
  19 upsample                 2x     8 x   8 x  16 ->   16 x  16 x  16
  20 route  19 8 	                           ->   16 x  16 x  48 
  21 conv     32       3 x 3/ 1     16 x  16 x  48 ->   16 x  16 x  32 0.007 BF
  22 conv     75       1 x 1/ 1     16 x  16 x  32 ->   16 x  16 x  75 0.001 BF
  23 yolo
[yolo] params: iou loss: mse (2), iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
Total BFLOPS 0.029 
avg_outputs = 17317 
 Allocate additional workspace_size = 2.49 MB 
Loading weights from backup/xyolo_final.weights...
 seen 64, trained: 10240 K-images (160 Kilo-batches_64) 
Done! Loaded 24 layers from weights-file 

 calculation mAP (mean average precision)...
5824
 detections_count = 637077, unique_truth_count = 13841  
class_id = 0, name = aeroplane, ap = 3.39%   	 (TP = 5, FP = 56) 
class_id = 1, name = bicycle, ap = 5.84%   	 (TP = 19, FP = 324) 
class_id = 2, name = bird, ap = 2.27%   	 (TP = 0, FP = 0) 
class_id = 3, name = boat, ap = 0.59%   	 (TP = 0, FP = 9) 
class_id = 4, name = bottle, ap = 0.13%   	 (TP = 0, FP = 0) 
class_id = 5, name = bus, ap = 2.77%   	 (TP = 15, FP = 255) 
class_id = 6, name = car, ap = 10.05%   	 (TP = 41, FP = 471) 
class_id = 7, name = cat, ap = 4.73%   	 (TP = 8, FP = 23) 
class_id = 8, name = chair, ap = 0.70%   	 (TP = 1, FP = 73) 
class_id = 9, name = cow, ap = 1.76%   	 (TP = 2, FP = 73) 
class_id = 10, name = diningtable, ap = 9.47%   	 (TP = 3, FP = 9) 
class_id = 11, name = dog, ap = 4.38%   	 (TP = 10, FP = 84) 
class_id = 12, name = horse, ap = 0.90%   	 (TP = 5, FP = 148) 
class_id = 13, name = motorbike, ap = 3.83%   	 (TP = 50, FP = 554) 
class_id = 14, name = person, ap = 1.60%   	 (TP = 169, FP = 4568) 
class_id = 15, name = pottedplant, ap = 0.18%   	 (TP = 0, FP = 0) 
class_id = 16, name = sheep, ap = 6.03%   	 (TP = 9, FP = 94) 
class_id = 17, name = sofa, ap = 1.13%   	 (TP = 0, FP = 0) 
class_id = 18, name = train, ap = 2.27%   	 (TP = 4, FP = 70) 
class_id = 19, name = tvmonitor, ap = 5.35%   	 (TP = 6, FP = 18) 

 for conf_thresh = 0.25, precision = 0.05, recall = 0.03, F1-score = 0.03 
 for conf_thresh = 0.25, TP = 347, FP = 6829, FN = 13494, average IoU = 2.99 % 

 IoU threshold = 50 %, used 11 Recall-points 
 mean average precision (mAP@0.50) = 0.033691, or 3.37 % 
Total Detection Time: 20 Seconds

I think that the map is too low?
Could you please help me?

**Comment by AlexeyAB** [comment]
Why do you use so small number of filters?


Also try to use
```
[net]
# Testing
#batch=1
#subdivisions=1
# Training
batch=64
subdivisions=16
width=256
height=256
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
burn_in=1000
max_batches = 160000
policy=steps
steps=512000,864000
scales=.1,.1

[convolutional]
batch_normalize=1
filters=8
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
xnor=1
bin_output=1
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
xnor=1
bin_output=1
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
xnor=1
bin_output=1
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
xnor=1
bin_output=1
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
xnor=1
bin_output=1
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=1

[convolutional]
xnor=1
bin_output=1
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

###########

[convolutional]
xnor=1
batch_normalize=1
filters=32
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=75
activation=leaky


[yolo]
mask = 3,4,5
anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
classes=20
num=6
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1

[route]
layers = -4

[convolutional]
batch_normalize=1
filters=16
size=1
stride=1
pad=1
activation=leaky

[upsample]
stride=2

[route]
layers = -1, 8

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky


[convolutional]
size=1
stride=1
pad=1
filters=75
activation=linear

[yolo]
mask = 0,1,2
anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
classes=20
num=6
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1
```

**Comment by ZheQU-somfy** [comment]
I use the number of filters in this paper:https://arxiv.org/abs/1910.03159.
![image](https://user-images.githubusercontent.com/61002672/77527499-84295700-6e8c-11ea-8463-3e12eeeb0a1c.png)

Ok, i'll try this new net.

**Comment by AlexeyAB** [comment]
Also I would suggest you to use
batch=64
subdivisions=1 or 2

**Comment by ZheQU-somfy** [comment]
OK, i'm trainning it, thank you

**Comment by attiamohammed** [comment]
> OK, i'm trainning it, thank you

I am following your thread. Any updates as I am facing the same issues. I have not detections at all.

**Comment by ZheQU-somfy** [comment]
Me neither, I think that the network is too simple. Do you have some updates for it?
