### ISSUE TITLE
IoU calculated by recall is different from average IoU calculated by mAP, there's just one class 

### ISSUE THREAD

**Issue by goodtogood** [AlexeyAB/darknet#507]
Hi, there
I trained one model and there's only one class.
I found IoU is different calculated by recall and mAP.
Is it normal?
please see attached images .

![map](https://user-images.githubusercontent.com/10088733/37899548-6e703102-311e-11e8-8c12-75feeb6aeeed.jpg)

![recall](https://user-images.githubusercontent.com/10088733/37899712-e6595fe0-311e-11e8-8482-2dcb857d81dc.jpg)

**Comment by AlexeyAB** [comment]
Hi, yes, this is normal, correct IoU is in result of command `darknet detector map`...

`darknet detector recall` gives IoU independent on class_id, that isn't correct.

**Comment by goodtogood** [comment]
got it!
thanks!
