### ISSUE TITLE
Saving cropped JPEGs of detected objects.

### ISSUE THREAD

**Issue by TheNarrator** [AlexeyAB/darknet#508]
Hey there, @AlexeyAB!

It's been wonderful to see the progress you've been making with this fork (I first came across it July, 2017). I have a question regarding performance. My goal is as stated in the title: To save detected objects as pictures for later use. 

I hacked together something to achieve this but this brings the performance down to 2FPS/sec. Basically what I tried was to take this block from **image.c**:
```
image ipl_to_image(IplImage* src)
{
    unsigned char *data = (unsigned char *)src->imageData;
    int h = src->height;
    int w = src->width;
    int c = src->nChannels;
    int step = src->widthStep;
    image out = make_image(w, h, c);
    int i, j, k, count=0;;

    for(k= 0; k < c; ++k){
        for(i = 0; i < h; ++i){
            for(j = 0; j < w; ++j){
                out.data[count++] = data[i*step + j*c + k]/255.;
            }
        }
    }
    return out;
```

and add it to the top of **demo.c** with a different name (to get over the VARIABLE WITH SAME NAME compiling hump), and then use it inside the _detect_in_thread_ function. Anyway, I'm 100% sure this isn't ideal since I had never written a line of C before trying this.

Is saving all detected objects as images feasible? What are some things I can try to do to increase the **general** performance at detect time? 
I've tried saving the result as video file without displaying, or just writing the results straight to a text file but it doesn't seem to speed up by any substantial amount. 

`#define FRAMES 3` 
Changing this line also came to mind, but I have no clue how this would affect accuracy. I'm trying all this on a custom model trained using **tiny-yolo-voc.cfg** with 21 classes. The number of classes will be much more in the future.

Thank you.

**Comment by goodtogood** [comment]
If you wanna high detection performance, you should not save deetected objects in main detection thread.  you can put detection result and image path into cache or queue,
and then saving objects one by one .
