### ISSUE TITLE
Windows 10 darknet.exe error

### ISSUE THREAD

**Issue by furkanaydinoz** [AlexeyAB/darknet#5081]
$ ./darknet.exe detect cfg/yolov3.cfg yolov3.weights data/dog.jpg

C:/Users/furka/darknet/darknet.exe: error while loading shared libraries: api-ms-win-crt-locale-l1-1-0.dll: cannot open shared object file: No such file or directory

Please help me.

**Comment by furkanaydinoz** [comment]
This is an error you can fix by adding "C:\Windows\System32\downlevel" to your PATH system variable. 

Thanks https://github.com/theAIGuysCode
@theAIGuysCode

**Comment by 9ghtX** [comment]
How I can add this PATH?
