### ISSUE TITLE
display remaining training time

### ISSUE THREAD

**Issue by zpmmehrdad** [AlexeyAB/darknet#5097]
@AlexeyAB  Hi,

please add remaining training time and left time on the chart.

Thanks

**Comment by AlexeyAB** [comment]
What is the different between: remaining training time and left time?

There is already remaining training time:

![chart](https://user-images.githubusercontent.com/4096485/77337068-7616f180-6d39-11ea-9f2b-1822d155de38.png)

**Comment by zpmmehrdad** [comment]
@AlexeyAB  Hi,

Sorry, I haven't updated to the latest version yet. Thanks for the reply and I close the issue.
