### ISSUE TITLE
Confusing about which weights should I use for train yolov3-tiny

### ISSUE THREAD

**Issue by marcoslucianops** [AlexeyAB/darknet#5103]
Hi, i'm find the best weights to train my custom yolov3-tiny model to detect license plates and ocr.

I'm confusing because have two differents informations about how to train a model for **yolov3-tiny**:

> Download pre-trained weights for the convolutional layers and put to the directory build\darknet\x64
> 
> for csresnext50-panet-spp.cfg (133 MB): csresnext50-panet-spp.conv.112
> for yolov3.cfg, yolov3-spp.cfg (154 MB): darknet53.conv.74
> for yolov3-tiny-prn.cfg , **yolov3-tiny.cfg** (6 MB): **yolov3-tiny.conv.11**
> for enet-coco.cfg (EfficientNetB0-Yolov3) (14 MB): enetb0-coco.conv.132

and

> - Download default weights file for **yolov3-tiny**: https://pjreddie.com/media/files/yolov3-tiny.weights
> - Get pre-trained weights **yolov3-tiny.conv.15** using command: darknet.exe partial cfg/**yolov3-tiny.cfg** yolov3-tiny.weights **yolov3-tiny.conv.15** 15
> - Make your custom model **yolov3-tiny-obj.cfg** based on cfg/**yolov3-tiny_obj.cfg** instead of yolov3.cfg
> - Start training: darknet.exe detector train data/obj.data **yolov3-tiny-obj.cfg** **yolov3-tiny.conv.15**

Which I need to use for train my model? What's the difference between **yolov3-tiny.conv.11** and **yolov3-tiny.conv.15**?

Thanks.

**Comment by marcoslucianops** [comment]
conv.11:
![image](https://user-images.githubusercontent.com/47423225/77496097-f49e8c80-6e28-11ea-9507-23f0271fab4a.png)

conv.15:
![image](https://user-images.githubusercontent.com/47423225/77496132-097b2000-6e29-11ea-899b-59aace541597.png)

What's the best?

**Comment by marcoslucianops** [comment]
@AlexeyAB, can you explain me?

**Comment by AlexeyAB** [comment]
> What's the best?

The higher mAP the better.

In your case, the results are approximately equal.
