### ISSUE TITLE
[Questions] Looking for some informations about object detection

### ISSUE THREAD

**Issue by elementdl** [AlexeyAB/darknet#5107]
Hi, 
I'm an engineer student in Electronics, and for the intership of my last year I'm working on autonomous Vehicles, especially on object detection.

My goal is to use real-time object detection on a prototype (a size of the remote car toy (30cm), not a real car) to make him partially autonomous. I will use a Jetson Nano from Nvidia
For now I working on YOLO, and I have some questions :

There is many many algorithms for object detection and sometimes I struggle to see the differences between them.
For now, what is the better algorithm to use in my case? (real-time detection, prototype of the size of a remote car toy (30cm), using jetson nano) I'm thinking about yolov3-tiny. Will Yolov3 will be too "heavy" in order to have real-time detection?

About the many algorithms, in this project what is yolov3-spp, yolov3-tiny-prn and yolov3-openimages?

Would you recommand any dataset besides COCO? 

Is it possible to change the output resolution of an algorithm? I suppose I can change the ouput resolution of yolov3-tiny but I don't know how, I suppose It's related to the number of the convolutionnal layers? 
Anyway knowing that the prototype will be way smaller than a car maybe a resolution of 416*416 is enough? 

My goal is to use object detection to control the prototype, so I have to use the results of the algorithm of object detection to control the motors of the prototype. Is it possible with the framework darknet? Or do I have to change the framework in order to be able to modify the code more easily?

Thanks by advance for your response.

**Comment by AlexeyAB** [comment]
* Jetson Nano - 0.5 TFlops
* GTX 1080Ti - 10 TFlops

So divide the FPS by 20.


I would suggest you to use Intel Myriad X Neurochip 2 Watt with `enet-coco.cfg (EfficientNetB0-Yolov3) ` model: https://github.com/AlexeyAB/darknet#pre-trained-models

Comparison of different models on Intel Myriad X Neurochip: https://github.com/AlexeyAB/darknet/issues/5079

Comparison of different models on GTX 1080Ti:

![71702416-6645dc00-2de0-11ea-8d65-de7d4b604021](https://user-images.githubusercontent.com/4096485/77529900-8ea21b80-6ea1-11ea-9271-120448c73b3a.png)

**Comment by elementdl** [comment]
Hi,

This comparison of different models are based on algorithm using how much classes?
I would like to know how the number of classes would impact the performance of my algorithm. 
If I use a custom Yolov3-tiny on a jetson nano with 10 classes maximum, how much would it impact the FPS?

Sincerely,

**Comment by AlexeyAB** [comment]
Speed of network doesnt depend on number of classes.
Accuracy depends on number of classes.
All these models are trained on MS COCO dataset with 80 classes.
