### ISSUE TITLE
training yolov3

### ISSUE THREAD

**Issue by RushNuts** [AlexeyAB/darknet#511]

**Comment by TaihuLight** [comment]
Yes
https://github.com/AlexeyAB/darknet/issues/432

**Comment by fabito** [comment]
It's not implemented in this fork yet: https://github.com/AlexeyAB/darknet/issues/504
Check the upstream repo in the meanwhile.

**Comment by RushNuts** [comment]
@fabito thanks

**Comment by TheMikeyR** [comment]
@RushNuts It just got added https://github.com/AlexeyAB/darknet/commit/d9ae3dd681ed1c98e807ff937dbbb9cfc4d19fe0 you should pull the latest commit though, seems there have been multiple fixes for compiling issues. 
I can see Alexey added two yolov3 scripts in root which shows you how to issue a command using yolov3.

**Comment by RushNuts** [comment]
@TheMikeyR Okay, maybe you can help me. look, i try run tiny weights on coco dataset. download from pjreddie

i make: ./darknet detector test cfg/coco.data cfg/tiny-yolo.cfg yolov2-tiny.weights data/dog.jpg

and get this. boxes wrong:
![predictions](https://user-images.githubusercontent.com/11484847/38015347-2aedc924-3274-11e8-8840-83f0dfd4aa72.jpg)

**Comment by RushNuts** [comment]
one more question)

how i can train using yolov2-tiny.cfg (coco set) train tiny weights?
Where i get pre-trained model?

yolov2-tiny.cfg and tiny-yolo.cfg Is different configs. thanks!

**Comment by TheMikeyR** [comment]
Seems to be an issue regarding the yolov3 update https://github.com/AlexeyAB/darknet/issues/522 

You can revert back to an earlier commit https://github.com/AlexeyAB/darknet/commit/47c7af1cea5bbdedf1184963355e6418cb8b1b4f with this command while being in the directory `
git checkout 47c7af1cea5bbdedf1184963355e6418cb8b1b4f
`

**Comment by AlexeyAB** [comment]
@RushNuts @fabito @TheMikeyR 

I fixed it.
Try to update your code from this repo and re-compile from scratch:
```
make clean
make -j8
```

I've already tested the detection of Yolo v2 and Yolo v3: https://github.com/AlexeyAB/darknet/issues/522#issuecomment-376865263
But have not yet tested the training of Yolo v3.
If something goes wrong with the training, let me know.

**Comment by RushNuts** [comment]
If I correctly understood in v3 changed the files demo.c and image.c?

**Comment by AlexeyAB** [comment]
@RushNuts @fabito @TheMikeyR 
Now you can try to train Yolo v3. But I have not tested it yet.

**Comment by AlexeyAB** [comment]
@RushNuts Yolo v3 affects approximately 20 files, including these files: demo.c and image.c

**Comment by RushNuts** [comment]
@AlexeyAB

I tried to start train. the training took up all the video memory and I got the error cuda.
my parameters:
batch - 64
subvisions - 16
width - 416
height - 416

i have videomemory 8gb and that's not enough oO

**Comment by VanitarNordic** [comment]
@AlexeyAB 

Does the repo support training of the V3? the initial weights of the V3 is different.

**Comment by sivagnanamn** [comment]
From @AlexeyAB 's latest commits, it should support training YOLO V3. Please check out the latest repo.

**Comment by AlexeyAB** [comment]
@RushNuts Try to use `subvisions=32` or `subvisions=64`

**Comment by AlexeyAB** [comment]
Yolo v3 can be succesfully trained using this repo: https://github.com/AlexeyAB/darknet/issues/504#issuecomment-377290060

**Comment by VanitarNordic** [comment]
@AlexeyAB 

So it seems you tested it yourself now isn't it?

**Comment by AlexeyAB** [comment]
@sonalambwani 
Yolo v3 shows `nan` up to 1000 iterations - this is the normal behavior of Yolo v3. Just train more.

**Comment by sonalambwani** [comment]
Phew! Thanks

**Comment by RushNuts** [comment]
@AlexeyAB i'm still try train :D 
Now i'm using some classes from COCO and my classes. Now i will train tiny weights, and i have question:

use yolov2-tiny.cfg like configuration with 416x416. So i need model for start training. So if i take **yolov2-tiny.weights** and run command ... partial cfg/yolov2-tiny.cfg yolov2-tiny.weights tiny-yolo-voc.conv.13 13 - it's right? 

Thanks!

**Comment by VanitarNordic** [comment]
> Yolo v3 shows nan up to 1000 iterations - this is the normal behavior of Yolo v3. Just train more.

usually `-nan` is a result of nu-normal images in the augmentation phase, and when we have `-nan` that iteration does not add any value. But you know better. Would you please double check more?

**Comment by RushNuts** [comment]
@AlexeyAB i test standart tiny weights with command `./darknet detector test cfg/coco.data cfg/yolov2-tiny.cfg yolov2-tiny.weights data/dog.jpg `
i get results: 
![predictions](https://user-images.githubusercontent.com/11484847/38130218-cbd342aa-340a-11e8-86b1-d765ceb24403.jpg)

**Comment by AlexeyAB** [comment]
@VanitarNordic 
This is the beginning of normal training of Yolo v3, as you can see there are many `-nan` here:
But final result is good - mAP = 90.69 %

Also check Joseph's answer: https://github.com/pjreddie/darknet/issues/566#issuecomment-376193026
**If there are only some `nan` then training goes well, but if there are all `nan` then training goes wrong.**

```
D:\Darknet2\darknet\build\darknet\x64>darknet.exe detector train data/obj.data y
olov3_obj.cfg darknet53.conv.74
yolov3_obj
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   224 x 224 x   3   ->   224 x 224 x  32
...
  105 conv     33  1 x 1 / 1    28 x  28 x 256   ->    28 x  28 x  33
  106 detection
Loading weights from darknet53.conv.74...
 seen 64
Done!
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
 If error occurs - run training with flag: -dont_show
Loaded: 2.353000 seconds
Region 82 Avg IOU: -nan(ind), Class: -nan(ind), Obj: -nan(ind), No Obj: 0.502225
, .5R: -nan(ind), .75R: -nan(ind),  count: 0
Region 94 Avg IOU: 0.389245, Class: 0.435512, Obj: 0.600462, No Obj: 0.503660, .
5R: 0.285714, .75R: 0.000000,  count: 7
Region 106 Avg IOU: 0.239299, Class: 0.475226, Obj: 0.402887, No Obj: 0.535192,
.5R: 0.000000, .75R: 0.000000,  count: 2
Region 82 Avg IOU: 0.476170, Class: 0.571396, Obj: 0.444353, No Obj: 0.500995, .
5R: 0.000000, .75R: 0.000000,  count: 1
Region 94 Avg IOU: 0.447275, Class: 0.400346, Obj: 0.520463, No Obj: 0.502764, .
5R: 0.250000, .75R: 0.000000,  count: 4
Region 106 Avg IOU: -nan(ind), Class: -nan(ind), Obj: -nan(ind), No Obj: 0.53334
2, .5R: -nan(ind), .75R: -nan(ind),  count: 0
Region 82 Avg IOU: 0.335612, Class: 0.549323, Obj: 0.332219, No Obj: 0.501743, .
5R: 0.333333, .75R: 0.000000,  count: 3
Region 94 Avg IOU: 0.427187, Class: 0.675035, Obj: 0.660047, No Obj: 0.503516, .
5R: 0.500000, .75R: 0.000000,  count: 2
Region 106 Avg IOU: -nan(ind), Class: -nan(ind), Obj: -nan(ind), No Obj: 0.53282
2, .5R: -nan(ind), .75R: -nan(ind),  count: 0
Region 82 Avg IOU: -nan(ind), Class: -nan(ind), Obj: -nan(ind), No Obj: 0.500734
, .5R: -nan(ind), .75R: -nan(ind),  count: 0
Region 94 Avg IOU: 0.298235, Class: 0.441220, Obj: 0.485503, No Obj: 0.503760, .
5R: 0.142857, .75R: 0.000000,  count: 7
Region 106 Avg IOU: 0.335862, Class: 0.463578, Obj: 0.650037, No Obj: 0.534691,
.5R: 0.000000, .75R: 0.000000,  count: 2
Region 82 Avg IOU: 0.598648, Class: 0.375109, Obj: 0.701654, No Obj: 0.499867, .
5R: 1.000000, .75R: 0.000000,  count: 1
Region 94 Avg IOU: 0.454718, Class: 0.392864, Obj: 0.518321, No Obj: 0.503738, .
5R: 0.333333, .75R: 0.000000,  count: 3
Region 106 Avg IOU: -nan(ind), Class: -nan(ind), Obj: -nan(ind), No Obj: 0.53504
2, .5R: -nan(ind), .75R: -nan(ind),  count: 0
Region 82 Avg IOU: 0.372241, Class: 0.425744, Obj: 0.557666, No Obj: 0.500633, .
5R: 0.000000, .75R: 0.000000,  count: 2
Region 94 Avg IOU: 0.258128, Class: 0.338691, Obj: 0.472565, No Obj: 0.503493, .
5R: 0.000000, .75R: 0.000000,  count: 1
Region 106 Avg IOU: -nan(ind), Class: -nan(ind), Obj: -nan(ind), No Obj: 0.53494
3, .5R: -nan(ind), .75R: -nan(ind),  count: 0
Region 82 Avg IOU: -nan(ind), Class: -nan(ind), Obj: -nan(ind), No Obj: 0.501154
, .5R: -nan(ind), .75R: -nan(ind),  count: 0
Region 94 Avg IOU: 0.325241, Class: 0.471191, Obj: 0.614726, No Obj: 0.503628, .
5R: 0.000000, .75R: 0.000000,  count: 3
Region 106 Avg IOU: -nan(ind), Class: -nan(ind), Obj: -nan(ind), No Obj: 0.53531
0, .5R: -nan(ind), .75R: -nan(ind),  count: 0
Region 82 Avg IOU: -nan(ind), Class: -nan(ind), Obj: -nan(ind), No Obj: 0.502855
, .5R: -nan(ind), .75R: -nan(ind),  count: 0
Region 94 Avg IOU: 0.357644, Class: 0.474404, Obj: 0.508615, No Obj: 0.503468, .
5R: 0.166667, .75R: 0.000000,  count: 6
Region 106 Avg IOU: 0.286589, Class: 0.459594, Obj: 0.583236, No Obj: 0.534190,
.5R: 0.000000, .75R: 0.000000,  count: 1

 1: 302.202576, 302.202576 avg, 0.000000 rate, 4.474000 seconds, 64 images
Loaded: 0.002000 seconds
Region 82 Avg IOU: -nan(ind), Class: -nan(ind), Obj: -nan(ind), No Obj: 0.500461
, .5R: -nan(ind), .75R: -nan(ind),  count: 0
```

Good detection: 
![predictions](https://user-images.githubusercontent.com/4096485/38099578-ab2b6dc0-3383-11e8-90f7-2fb44022431a.jpg)

**Comment by AlexeyAB** [comment]
@RushNuts Tiny yolo has a low precision.
Try to do the same with original repo, do you get the same result for yolov2-tiny.cfg?
`./darknet detector test cfg/coco.data cfg/yolov2-tiny.cfg yolov2-tiny.weights data/dog.jpg`

**Comment by RushNuts** [comment]
@AlexeyAB Yes, same result.
![predictions](https://user-images.githubusercontent.com/11484847/38136981-92049446-342a-11e8-8349-e37e5c046dc1.jpg)

but if i add thresh .5, result on screen:
`./darknet detector test cfg/coco.data cfg/yolov2-tiny.cfg yolov2-tiny.weights data/dog.jpg -thresh .5
`

**Comment by AlexeyAB** [comment]
I have the same result using my repo. So may be `yolov2-tiny.weight` badly trained, or required high threshold. You can ask about this issue in Joseph's repo: https://github.com/pjreddie/darknet

![predictions](https://user-images.githubusercontent.com/4096485/38137112-6f59b0a6-342b-11e8-9aa1-134ab3775825.jpg)

**Comment by RushNuts** [comment]
@AlexeyAB okay, thank you. Um, tiny train? :D I wanna know how i get pre-trained model for training? command ... `partial cfg/yolov2-tiny.cfg yolov2-tiny.weights tiny-yolo.conv.13 13` - it's right?

**Comment by AlexeyAB** [comment]
@RushNuts Yes

**Comment by RushNuts** [comment]
@AlexeyAB Thank you, I hope there will be no problems.

Btw, on 608x608 i get good detection for car and person. But my classes sometime detect a false objects, i think, problem is my data quality. Example, i have car data ~20000 images and my class ~1100

**Comment by i-chaochen** [comment]
@AlexeyAB I wonder when should this train will stop? If I don't stop it manually, would be always training ?
