### ISSUE TITLE
GPU Usage is LOW

### ISSUE THREAD

**Issue by RollingIsland** [AlexeyAB/darknet#5110]
Hi @AlexeyAB , I trained YOLOv3 with 2x 1080Ti on Windows 10. I use nvidia-sim to check the GPU usage and the screenshot is as follow:
![NBRRXRUT XD9_AM9Z2ZE0FE](https://user-images.githubusercontent.com/36465854/77580172-7cae9000-6f16-11ea-9366-156c05d04dfd.png)
The process is using GPU, however the usage is TOO LOW. 
command l use: darknet detector train bdd100k/bdd100k.data bdd100k/yolov3_5l-bdd100k.cfg bdd100k/backup/yolov3_5l-bdd100k_last.weights -map -gpus 0,1
Is there any way to make full use of my GPUs?

**Comment by AlexeyAB** [comment]
Show such screenshot

![image](https://user-images.githubusercontent.com/4096485/77584720-5bd54300-6ef4-11ea-988e-c4691a969774.png)

**Comment by RollingIsland** [comment]
@AlexeyAB 
Sorry the train is so slow that the model haven't reach the first mAP calc iterations. It has been training for around six hours. What I can offer is this:
![LG17~T4T% K_5V57W9KAN2K](https://user-images.githubusercontent.com/36465854/77602935-b9e04580-6f49-11ea-9c59-b80c1233127f.png)
Is that enough for you to figure out the reason? Or is there any way to reduce the iterations needed for calculate mAP? Let me know if there any other information I should offer. 
By the way, I don't think the problem is on my CPU for it's usage is also low. This is the screenshot of task manager, hope it can help.
![NBRRXRUT XD9_AM9Z2ZE0FE](https://user-images.githubusercontent.com/36465854/77603553-5820db00-6f4b-11ea-83a2-80c27b55d780.png)

**Comment by RollingIsland** [comment]
I did several test and found the main problem maybe I set 5 yolo layers in cfg file(modified from yolov3_5l.cfg). I tried to use cfg file modified from yolov3.cfg and everything seems went well.
![JUO$L9{7X_FJFV~SLYGP_{O](https://user-images.githubusercontent.com/36465854/77637816-35191a00-6f91-11ea-9998-6e408abfe9af.png)
Though there is still a lot of idle period, it's much better. However I have no idea what the reason is.

**Comment by AlexeyAB** [comment]
> Though there is still a lot of idle period, it's much better. However I have no idea what the reason is.

Show again two screenshots:


![image](https://user-images.githubusercontent.com/4096485/77584720-5bd54300-6ef4-11ea-988e-c4691a969774.png)

![image](https://user-images.githubusercontent.com/4096485/77647976-6cc79800-6f78-11ea-97bd-937de76bbd40.png)

**Comment by RollingIsland** [comment]
Thanks for your reply and patience. I finally find out the reason. This machine is rented for a temporary use and I didn't notice that the memory is DDR3 before. The situation is because the low speed of memory. I shouldn't have been so careless.

**Comment by raedbenz** [comment]
@RollingIsland what is the recommended spec for memory?
Many Thanks

**Comment by RollingIsland** [comment]
@raedbenz  The higher frequency, the better
