### ISSUE TITLE
by try to run darknet.exe it gets an runtime issues in cuda version

### ISSUE THREAD

**Issue by vijay180396** [AlexeyAB/darknet#5115]
cuda_set_device() : line: 39 : build time: Mar 26 2020 - 15:31:56

 CUDA Error: CUDA driver version is insufficient for CUDA runtime version

**Comment by vijay180396** [comment]
and i using 
Platform:Windows 10
nvidia drive: GeForce GT 720M
CUDA:10.0
cudnn:7.4.1

**Comment by AlexeyAB** [comment]
Install new GPU driver

**Comment by vijay180396** [comment]
my nvidia current drive version is : 385.89 
and Compute capability(version) is :2.1
where it's any possible to update drive.
