### ISSUE TITLE
Modify "detector.c" to return the anchor of the true positives

### ISSUE THREAD

**Issue by Sunfl4wer** [AlexeyAB/darknet#5126]
**This is not actually an issue but something I want to share. For those who want to train their custom object detector and tuning it.** 
When I try to gain more insight for my model I just think that It would be cool If I can collect the statistic of the size of anchors of the true positive results. So I modify the `validate_detector_map()` function in `detector.c` source code so that It will return the labels according to true positive results in a text file.

Here is the [link](https://github.com/Sunfl4wer/darknet_change) to the `detector.c` file. After download the file, **replace** the `detector.c` it in the `src` folder with this file and **recompile darknet**. Then whenever you use `./darknet detector map ...` the `true_positive_stat.txt` will be automatically created in the current working directory.
Note:
- You don't have to retrain the model to use this.
- This might slow down `map` calculation.
- You might need to manually delete the `true_positive_stat.txt` file to get new result.
- To find the line of code that I added. Use the find function in your text editor or IDE and type `// added by Son Nguyen` this will take you to all the lines that I added.

You can use python to read the file and parse it to list or something like that and get the height and width of the anchors of the classes accordingly then plot it to see how your model perform on different anchor sizes. I also have a python [file](https://github.com/Sunfl4wer/darknet_change/blob/master/detection_statistic.py) to do this.  Just change these line to your path accordingly:
`path_to_label_file = "data/objects/" # path to your images and label folder
true_positive_stat_file = "true_positive_stat.txt" # text file that return the true positive anchors
obj_names = "obj.names" # label file`
Here is an image of my model:
[true_positve](https://github.com/Sunfl4wer/darknet_change/blob/master/Figure_1.png)

If you want to see the false negatives (false_negative) just take all the labels in your valid label files (unique_truth) and exclude the one that is true positive (truth_positive). The logic will be: _**false_positive** = [**label** for **label** in **unique_truth** if label not in **true_positive**]_

**Comment by teocns** [comment]
Hey, sorry for the naive question, but I am wondering if this is the correct process for editing and re-compiling detector.c:

EDIT `vcpkg\buildtrees\darknet\src\13bb90133d-a4584e7461\src\detector.c`

and then...

RUN `vcpkg\installed\x64-windows\tools\darknet\build.ps1`

Please correct me if I'm wrong :) I am using vcpkg and I am not familiar with the environment.

**Comment by Sunfl4wer** [comment]
I'm not familiar with `vcpkg` either as I only run `darknet` on Google Colab which is Linux based. But if that is the only `src` folder that you can find then probably that is the right one. You only have one source to build in C/C++ so no fuzzy here.
