### ISSUE TITLE
Error at last step of data training using Google Colab

### ISSUE THREAD

**Issue by Nazrindino97** [AlexeyAB/darknet#5130]
The last step for data training and got error

`!./darknet detector train data/obj.data yolov3-palmoil.cfg darknet53.conv.74 -dont_show`

> CUDA Error: no CUDA-capable device is detected
> darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.

Please help me.

**Comment by Sunfl4wer** [comment]
You would need to change Colab's runtime to GPU to use the GPU. In **Colab** chooses **Runtime** then **Change runtime type** then change **Hardware accelerator** to _GPU_ and click **Save**
If you set the `CUDNN=1` in your `MAKEFILE` then you should set it to `CUDNN=0`. And recompile darknet. This run fine for me on Colab.
`GPU=1`
`CUDNN=0`
`CUDNN_HALF=0`
`OPENCV=1`
`AVX=0`
`OPENMP=0`
`LIBSO=0`
`ZED_CAMERA=0 # ZED SDK 3.0 and above`
`ZED_CAMERA_v2_8=0 # ZED SDK 2.X`

**Comment by Nazrindino97** [comment]
Got It! Thanks!
