### ISSUE TITLE
Darknet on Jetson Nano with Sony IMX219 green screen problem

### ISSUE THREAD

**Issue by crazzynko** [AlexeyAB/darknet#5137]
I am currently trying to run object detection on Jetson Nano with sony IMX219 camera
<https://www.waveshare.com/imx219-170-camera.htm>

I am trying to run darknet with camera 0:

    ./darknet detector demo cfg/coco_znacenie.data cfg/yolov3-tiny_znacenie.cfg znacenie1.weights -c 0

And output is:

    CUDA-version: 10000 (10000), cuDNN: 7.6.3, GPU count: 1  
     OpenCV version: 4.1.1
    Demo
     compute_capability = 530, cudnn_half = 0 
    net.optimized_memory = 0 
    mini_batch = 1, batch = 2, time_steps = 1, train = 0 
       layer   filters  size/strd(dil)      input                output
       0 conv     16       3 x 3/ 1    416 x 416 x   3 ->  416 x 416 x  16 0.150 BF
       1 max                2x 2/ 2    416 x 416 x  16 ->  208 x 208 x  16 0.003 BF
       2 conv     32       3 x 3/ 1    208 x 208 x  16 ->  208 x 208 x  32 0.399 BF
       3 max                2x 2/ 2    208 x 208 x  32 ->  104 x 104 x  32 0.001 BF
       4 conv     64       3 x 3/ 1    104 x 104 x  32 ->  104 x 104 x  64 0.399 BF
       5 max                2x 2/ 2    104 x 104 x  64 ->   52 x  52 x  64 0.001 BF
       6 conv    128       3 x 3/ 1     52 x  52 x  64 ->   52 x  52 x 128 0.399 BF
       7 max                2x 2/ 2     52 x  52 x 128 ->   26 x  26 x 128 0.000 BF
       8 conv    256       3 x 3/ 1     26 x  26 x 128 ->   26 x  26 x 256 0.399 BF
       9 max                2x 2/ 2     26 x  26 x 256 ->   13 x  13 x 256 0.000 BF
      10 conv    512       3 x 3/ 1     13 x  13 x 256 ->   13 x  13 x 512 0.399 BF
      11 max                2x 2/ 1     13 x  13 x 512 ->   13 x  13 x 512 0.000 BF
      12 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
      13 conv    256       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 256 0.089 BF
      14 conv    512       3 x 3/ 1     13 x  13 x 256 ->   13 x  13 x 512 0.399 BF
      15 conv     18       1 x 1/ 1     13 x  13 x 512 ->   13 x  13 x  18 0.003 BF
      16 yolo
    [yolo] params: iou loss: mse (2), iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
      17 route  13 		                           ->   13 x  13 x 256 
      18 conv    128       1 x 1/ 1     13 x  13 x 256 ->   13 x  13 x 128 0.011 BF
      19 upsample                 2x    13 x  13 x 128 ->   26 x  26 x 128
      20 route  19 8 	                           ->   26 x  26 x 384 
      21 conv    256       3 x 3/ 1     26 x  26 x 384 ->   26 x  26 x 256 1.196 BF
      22 conv     18       1 x 1/ 1     26 x  26 x 256 ->   26 x  26 x  18 0.006 BF
      23 yolo
    [yolo] params: iou loss: mse (2), iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
    Total BFLOPS 5.448 
    avg_outputs = 324846 
     Allocate additional workspace_size = 13.11 MB 
    Loading weights from znacenie1.weights...
     seen 64, trained: 320 K-images (5 Kilo-batches_64) 
    Done! Loaded 24 layers from weights-file 
    Webcam index: 0
    [ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (1757) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src0 reported: Internal data stream error.
    [ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (886) open OpenCV | GStreamer warning: unable to start pipeline
    [ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
    Video stream: 3264 x 2464 

But input from camera is green:

[![https://i.imgur.com/lw67z0F.png][1]][1]

Camera is working when I run it by:

    gst-launch-1.0 nvarguscamerasrc sensor_mode=0 ! 'video/x-raw(memory:NVMM),width=3280, height=2464, framerate=21/1, format=NV12' ! nvvidconv flip-method=0 ! 'video/x-raw,width=3280, height=2464' ! nvvidconv flip-method=2 ! nvegltransform ! nveglglessink -e

I was trying to test my camera in chromium but chromium wasn't able to detect camera:
[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/Wx0On.png
  [2]: https://i.stack.imgur.com/pJ3bg.png

I am using clean installation of latest image for my Jetson Nano and everything is up to date. I've already tried different versions of OpenCv but without any progress.

Anybody know what should I try?

**Comment by AlexeyAB** [comment]
This is the issue between OpenCV + Your-camera. 
Try to find the solution on https://answers.opencv.org/questions/ or https://stackoverflow.com/

**Comment by crazzynko** [comment]
Just found how to solve it:

    ./darknet detector demo cfg/coco_znacenie.data cfg/yolov3-tiny_znacenie.cfg znacenie1.weights "nvarguscamerasrc ! video/x-raw(memory:NVMM), width=1920, height=1080, format=(string)NV12, framerate=(fraction)30/1 ! nvvidconv flip-method=2  ! video/x-raw, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink"
