### ISSUE TITLE
Calculating scores for different confidence thresholds 

### ISSUE THREAD

**Issue by frankbrewer** [AlexeyAB/darknet#5142]
Hi,

Is it possible to calculate mAP, TP, FP, FN scores for different confidence threshold from the command line?

Something like:

`./darknet detector map -conf_thresh=0.7 data/obj.data yolo-obj.cfg backup\yolo-obj.weights`

Or even a better thing could be the ability to try a few different confidence thresholds.

**Comment by lsd1994** [comment]
./darknet detector map data/obj.data yolo-obj.cfg backup\yolo-obj.weights -thresh 0.7
