### ISSUE TITLE
Cannot build yolo_cpp_dll.dll

### ISSUE THREAD

**Issue by lsgcv** [AlexeyAB/darknet#5148]
Hi, 

I tried to generate the "yolo_cpp_dll.dll" on Windows by using cmake, but there is no dll-file generated.
I also tried the other method by compiling "build\darknet\yolo_cpp_dll.sln" but when I open that file I get this error message:
error : Designtime build failed for project 'C:\Users\U720469\Desktop\YOLO\AlexeyAB\darknet\build\darknet\yolo_cpp_dll.vcxproj' configuration 'Release|x64'. IntelliSense might be unavailable.
	Check *.designtime.log files in your %TEMP% directory.
I couldn't find the designtime.log file in order to check the error.

Any advice on how I can build the yolo_cpp_dll.dll?

As an alternative, I also tried to create the dll-file on google colab. I changed the makefile with LIBSO=1 and did make again. But also in this case, no dll-file is generated.

Thank you!

**Comment by AlexeyAB** [comment]
> As an alternative, I also tried to create the dll-file on google colab. I changed the makefile with LIBSO=1 and did make again. But also in this case, no dll-file is generated.

On Linux will be generated `libdarknet.so` library file

**Comment by lsgcv** [comment]
Hi AlexeyAB, thank you.
do you also have a clue, what is going wrong for me on Windows?

Thank you!

**Comment by lsgcv** [comment]
Hi @AlexeyAB 
where will the libdarknet.so be generated?
I just did "make" with LIBSO = 1, however I couldn't find that library.
when I run darknet.py in the build/darknet/x64 folder, I also get the error, that this library file cannot be found.
