### ISSUE TITLE
Darknet or Deepstream?

### ISSUE THREAD

**Issue by elementdl** [AlexeyAB/darknet#5149]
Hi, 

I'm an engineer student working on my final internship on real-time object detection/recognition. I use a jetson nano.
I am a beginner in the domain of computer vision and AI.

I want to implement a program on the jetson nano who can do object detection/recognition in real-time AND use the data (objects founds) to send order to motors (control a prototype).

I trained myself on a computer with darknet and use YOLOv3 for object detection/recognition. But I just saw that YOLO can be available on deepstream, who works on the jetson nano.

Knowing that I'm a beginner and that I want to modify the program to use the datas, what is the best solution for me?

Is it better/faster/easier to use Darknet or Deepstream for YOLO on the jetson nano?

I also have a laptop with a Nvidia Quadro RTX3000, if I use deepstream on the jetson nano, is it possible to train my YOLO on the laptop then transfer the weights and cfg on the jetson nano?

Sincerely,

**Comment by AlexeyAB** [comment]
> Is it better/faster/easier to use Darknet or Deepstream for YOLO on the jetson nano?

Deepstream is better and more stable for Detection than Darknet

* Use Deepstream or OpenCV-dnn for Detection.
* Use Darknet for Training


> I also have a laptop with a Nvidia Quadro RTX3000, if I use deepstream on the jetson nano, is it possible to train my YOLO on the laptop then transfer the weights and cfg on the jetson nano?

Yes.

**Comment by elementdl** [comment]
Thanks a lot!

**Comment by marcoslucianops** [comment]
I’m testing yolov3-tiny-prn on DeepStream and it is absurdly fast (with my custom objects).

**Comment by alexanderfrey** [comment]
@marcoslucianops Any special setup for converting model to deepstream or how do you run the trained model ? Thanks !

**Comment by marcoslucianops** [comment]
> @marcoslucianops Any special setup for converting model to deepstream or how do you run the trained model ? Thanks !

My [repository](https://github.com/marcoslucianops/DeepStream-Yolo) have a simple tutoral.
