### ISSUE TITLE
-clear function not resetting iterations?

### ISSUE THREAD

**Issue by iamnotramon** [AlexeyAB/darknet#5153]
Hello, 

I'm trying to continue training with weights from prior training and resetting the iterations.

I use the following command:
`darknet.exe detector train custom_data/detector.data custom_data/cfg/yolov3-custom.cfg backup/yolov3-custom_last.weights -clear 1 -map 0.1 `

However, when the graph pops up, it shows iteration at 43001 instead of 1.

Why is this? Does it reset the learning rate regardless or is it using the learning rate as if it was in the 43001st iteration?

Thanks!

**Comment by AlexeyAB** [comment]
* Do you use the latest Darknet version?

* Can you share your cfg/weights files by using Google-Disk?

**Comment by iamnotramon** [comment]
Thanks for your quick reply. 

- I see that you made some minor changes, my version is from March 09 2020. Can try to install latest version, but am in middle of training right now (and it seems to be working, only the -clear thing didn't work). 

-If you want to have a look at the files, they can be found here:
https://drive.google.com/open?id=1ZdzbOh-HlddoSDlKr3PWCEE28tCk08N9

Ps. Thanks for all your work! Besides this minor issue it seems to be working great!

**Comment by AlexeyAB** [comment]
Currently flag `-clear` works well:

You can download new Darknet version if you want to train with -clear flag

![image](https://user-images.githubusercontent.com/4096485/78181793-9c413d80-746d-11ea-90c9-cca5170f3ece.png)


![image](https://user-images.githubusercontent.com/4096485/78181757-8cc1f480-746d-11ea-97b6-ea63b1349c02.png)

**Comment by iamnotramon** [comment]
Thank you so much! Will update!
