### ISSUE TITLE
Multiscale (set random = 1) during training

### ISSUE THREAD

**Issue by brian208579** [AlexeyAB/darknet#5157]
For application speed ( fps ), my custom model have to (yolov3) inference at 288 * 288 resolutions, if I using multiscale (set random = 1) during training, is it helpful to detection ? If the answer is no, it mean just use 288 * 288 resolution during training ? or any suggestions ?
Appreciate

**Comment by lsd1994** [comment]
> is it helpful to detection ?

Yes

**Comment by lsd1994** [comment]
> is it helpful to detection ?

Yes
