### ISSUE TITLE
mAP is zero and get no detection while training yolov2-tiny-voc 

### ISSUE THREAD

**Issue by bonne658** [AlexeyAB/darknet#5158]
### I encounter some problems while while training yolov2-tiny-voc.My steps is:
**1**.get yolov2-tiny-voc.weights from the site (http://pjreddie.com/media/files/yolov2-tiny-voc.weights )
**2**.get pretrain weight: `./darknet partial cfg/yolov2-tiny-voc.cfg yolov2-tiny-voc.weights yolov2-tiny.conv.13 13`
**3**.train:`./darknet detector train data/voc.data cfg/tiny-yolo-voc.cfg tiny-yolo-voc.conv.13`
**4**.I get these output:
_(next mAP calculation at 1034 iterations) 
 1033: 0.676192, 0.829539 avg loss, 0.001000 rate, 0.708630 seconds, 66112 images, 9.791308 hours left
Loaded: 0.000028 seconds
Region Avg IOU: 0.585991, Class: 0.811754, Obj: 0.000007, No Obj: 0.000234, Avg Recall: 0.681818,  count: 22
Region Avg IOU: 0.600015, Class: 0.838479, Obj: 0.000010, No Obj: 0.000213, Avg Recall: 0.750000,  count: 12
Region Avg IOU: 0.628523, Class: 0.885861, Obj: 0.000003, No Obj: 0.000200, Avg Recall: 0.764706,  count: 17
Region Avg IOU: 0.556156, Class: 0.724914, Obj: 0.000005, No Obj: 0.000189, Avg Recall: 0.666667,  count: 21
Region Avg IOU: 0.621064, Class: 0.729896, Obj: 0.000048, No Obj: 0.000300, Avg Recall: 0.714286,  count: 21
Region Avg IOU: 0.607111, Class: 0.868842, Obj: 0.000001, No Obj: 0.000284, Avg Recall: 0.800000,  count: 15
Region Avg IOU: 0.650445, Class: 0.938456, Obj: 0.000003, No Obj: 0.000228, Avg Recall: 0.909091,  count: 22
Region Avg IOU: 0.658239, Class: 0.800705, Obj: 0.000004, No Obj: 0.000249, Avg Recall: 0.882353,  count: 17

 (next mAP calculation at 1034 iterations)
**5**.mAP is:
for conf_thresh = 0.25, precision = -nan, recall = 0.00, F1-score = -nan 
 for conf_thresh = 0.25, TP = 0, FP = 0, FN = 12032, average IoU = 0.00 % 

 IoU threshold = 50 %, used Area-Under-Curve for each unique Recall 
 mean average precision (mAP@0.50) = 0.000000, or 0.00 %
**6**.I do something:
- check train and valid dataset:`./darknet detector calc_anchors data/voc.data -width 416 -height 416`
- use `-show_imgs`
- ues different value of random
- change batch to 256, subdivisions to 32
**7**. Finally, I don't know what goes wrong

**Comment by AlexeyAB** [comment]
Train 50 000 iterations, or at least 10 000 iterations

**Comment by bonne658** [comment]
Thank you a lot @AlexeyAB 
I got 55.58% mAP around 22000  iterations.
