### ISSUE TITLE
Yolov3 having confusion between two classes.

### ISSUE THREAD

**Issue by poornimajd** [AlexeyAB/darknet#5165]
Hello
Great work @AlexeyAB !
I am using Yolov3-spp for detecting 8 classes on the indian driving dataset.I have got a confusion matrix as shown below , at iou=50%.
![confu_9_further](https://user-images.githubusercontent.com/31023599/78353076-1802cd80-75c7-11ea-9ec2-2e11689d2b76.png)
As seen from the matrix there is  a lot of confusion between person and motorcycle.
How do I eliminate this?
The sample annotation of image is as shown
![show_alex](https://user-images.githubusercontent.com/31023599/78353806-53ea6280-75c8-11ea-8191-7910ff61de1f.png)
(The person on the bike is labeled as person and the bike is labeled as motorcycle.)
Is this confusion because of the way it is annotated , like a huge portion of the person annotation also overlaps with that of the motorcycle?
Or how do I try to reduce the confusion?
Can you please help me out?

**Comment by AlexeyAB** [comment]
> I am using Yolov3-spp for detecting 8 classes on the indian driving dataset.I have got a confusion matrix as shown below , at iou=50%.

* Check that you have built the confusion matrix correctly. Not only should be IoU>50%, but also should be matched only the best IoU(detection, truth).

* What mAP50 do you get?

**Comment by poornimajd** [comment]
Thanks for the quick reply!
I got a mAP of 70.97% .This is the small snipet of the code I used to calculate the confusion matrix 
Compute iou is the function which calculates the iou 
IOU_THRESHOLD=0.5
for i in range(len(groundtruth_boxes)):
			for j in range(len(detection_boxes)):
				groundtruth_box = groundtruth_boxes[i].split()
				detection_box = detection_boxes[j].split()
				iou = compute_iou(groundtruth_box, detection_box)
				   
				if iou > IOU_THRESHOLD:
					confusion_matrix[int(class_dict[groundtruth_box[0]])][int(class_dict[detection_box[0]])] += 1
					break
According to the code it just breaks as sson as it gets the iou above 0.5 , may be this is the place where I am going wrong.

**Comment by gaurang19990412** [comment]
I have trained my model using darknet. Now how can i generate confution matrix for this.
