### ISSUE TITLE
shortcut layer

### ISSUE THREAD

**Issue by pfeatherstone** [AlexeyAB/darknet#5166]
What is the computation for a shortcut layer taking two inputs with dimensions:
(104 x 104 x 128) and (104 x 104 x 64).
I thought a shortcut layer was a residual connection, so addition. Addition requires all dimensions to be the same. Is there an implicit conversion from (104 x 104 x 64) to (104 x 104 x 128) ?

**Comment by pfeatherstone** [comment]
Zero padding for example?

**Comment by AlexeyAB** [comment]
> Zero padding for example?

Yes.

**Comment by pfeatherstone** [comment]
Thanks

**Comment by pfeatherstone** [comment]
Do you always pad to the maximum number of features or do you take whichever number of features the previous layer had?
