### ISSUE TITLE
Pseudo-Lableing for specific class

### ISSUE THREAD

**Issue by WadRex** [AlexeyAB/darknet#5176]
Hello,
I wanted to ask if it is possible to select specific class for "pseudo labeling" using the command below

> Pseudo-lableing - to process a list of images data/new_train.txt and save results of detection in Yolo training format for each image as label <image_name>.txt (in this way you can increase the amount of training data) use: **_darknet.exe detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights -thresh 0.25 -dont_show -save_labels < data/new_train.txt_**

I want to use already good trained model for pseudo-labeling, for example **`yolov3`**, but it was trained on 80 classes. Is it possible to save labels of only for example `humans`, even if there are cars and other objects on screen?

Thanks in advance!

**Comment by lsd1994** [comment]
The 'person' has id=0 in coco names, so you can set if(detect.id==0) then save labels.

**Comment by nguyenanhtuan1008** [comment]
> The 'person' has id=0 in coco names, so you can set if(detect.id==0) then save labels.

I have same question. your idea I think for detector.c, but how to do like this by command: darknet.exe detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights -thresh 0.25 -dont_show -save_labels < data/new_train.txt ?

**Comment by lsd1994** [comment]
@nguyenanhtuan1008 Maybe you should modify code if you use this command

**Comment by WadRex** [comment]
Unfortunately there is no native way to do it without changing "detector.h".
I didn't want to change anything in source code so I wrote a simple program to remove all of the not needed classes from .txt files.
If you want to use this. All you need is to enter the path to the folder with .txt files and the class number you want to keep.
```
#include <string>
#include <iostream>
#include <fstream>
#include <experimental/filesystem>
namespace fs = std::experimental::filesystem;
using namespace std;

void main() {
    std::string path = "ENTER YOUR PATH TO .txt FILES";
    for (const auto& entry : fs::directory_iterator(path))
    {
        string STRING; ifstream infile; ofstream temp;
        temp.open("temp.txt");
        infile.open(entry.path());
        while (!infile.eof()) // To get you all the lines.
        {
            getline(infile, STRING); // Saves the line in STRING.
            string deleteline = "0 ";  <--------- CHANGE TO THE CLASS NUMBER YOU WANT TO KEEP
            if (STRING.find(deleteline) == NULL)
                temp << STRING << endl;
        }
        temp.close();
        infile.close();
        remove(entry.path());
        rename("temp.txt", entry.path());
    }
}
```
