### ISSUE TITLE
How to calculate or  verify FPS of video detection

### ISSUE THREAD

**Issue by kaikaisun** [AlexeyAB/darknet#5177]
Hello, I just learned yolov3. I am verifying the real-time performance of video detection and how to calculate / verify the FPS of video detection

**Comment by AlexeyAB** [comment]
Run and look at AVG FPS:
`./darknet detector demo cfg/coco.data yolov3.cfg yolov3.weights -benchmark test.mp4`

**Comment by kaikaisun** [comment]
> 运行并查看AVG FPS：
> `./darknet detector demo cfg/coco.data yolov3.cfg yolov3.weights -benchmark test.mp4`
thank you！but，this command cannot test the average FPS value of the entire video.
The results are as follows：
 command（1）
./darknet detector demo names_data/voc.data names_data/yolo-obj4l.cfg names_data/yolo-obj4l_best.weights -benchmark test.mp4

 Video-stream stopped! 
 Video-stream stopped! 
 Video-stream stopped! 
 Video-stream stopped!

 command（2）
./darknet detector demo names_data/voc.data names_data/yolo-obj4l.cfg names_data/yolo-obj4l_best.weights 4.mp4

FPS:21.9
OpenCV exception: show_image_mat 
OpenCV exception: wait_key_cv 
Objects:
train: 100% 

FPS:23.4
OpenCV exception: show_image_mat 
OpenCV exception: wait_key_cv 
Objects:
train: 100%

**Comment by kaikaisun** [comment]
> > 运行并查看AVG FPS：
> > `./darknet detector demo cfg/coco.data yolov3.cfg yolov3.weights -benchmark test.mp4`
> > thank you！but，this command cannot test the average FPS value of the entire video.
> > The results are as follows：
> > command（1）
> > ./darknet detector demo names_data/voc.data names_data/yolo-obj4l.cfg names_data/yolo-obj4l_best.weights -benchmark test.mp4
> 
> Video-stream stopped!
> Video-stream stopped!
> Video-stream stopped!
> Video-stream stopped!
> 
> command（2）
> ./darknet detector demo names_data/voc.data names_data/yolo-obj4l.cfg names_data/yolo-obj4l_best.weights 4.mp4
> 
> FPS:21.9
> OpenCV exception: show_image_mat
> OpenCV exception: wait_key_cv
> Objects:
> train: 100%
> 
> FPS:23.4
> OpenCV exception: show_image_mat
> OpenCV exception: wait_key_cv
> Objects:
> train: 100%
sorry，both tests use the same test video file: test.mp4. The above 4.mp4 is wrong. In fact, it is test.mp4

**Comment by AlexeyAB** [comment]
Do you use the latest code?


Try 
./darknet detector demo cfg/coco.data yolov3.cfg yolov3.weights test.mp4 -dont_show

./darknet detector demo cfg/coco.data yolov3.cfg yolov3.weights test.mp4 -benchmark

./darknet detector demo cfg/coco.data yolov3.cfg yolov3.weights test.mp4 -benchmark -dont_show

Also check that you OpenCV library installed correctly.

Check that you set in the Makefile GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=1 all other 0.

**Comment by kaikaisun** [comment]
> Do you use the latest code?
> 
> Try
> ./darknet detector demo cfg/coco.data yolov3.cfg yolov3.weights test.mp4 -dont_show
> 
> ./darknet detector demo cfg/coco.data yolov3.cfg yolov3.weights test.mp4 -benchmark
> 
> ./darknet detector demo cfg/coco.data yolov3.cfg yolov3.weights test.mp4 -benchmark -dont_show
> 
> Also check that you OpenCV library installed correctly.
> 
> Check that you set in the Makefile GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=1 all other 0.

ok,thank you very much!The problem has been solved.

**Comment by kaikaisun** [comment]
> Do you use the latest code?
> 
> Try
> ./darknet detector demo cfg/coco.data yolov3.cfg yolov3.weights test.mp4 -dont_show
> 
> ./darknet detector demo cfg/coco.data yolov3.cfg yolov3.weights test.mp4 -benchmark
> 
> ./darknet detector demo cfg/coco.data yolov3.cfg yolov3.weights test.mp4 -benchmark -dont_show
> 
> Also check that you OpenCV library installed correctly.
> 
> Check that you set in the Makefile GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=1 all other 0.

Hello, there is a problem with my OpenCV. It can't be displayed when testing FPS. So, my question is: is FPS ： 31.4 in the last line the average FPS of the whole video?
FPS:23.6
Objects:
train: 48% 

FPS:25.9
Objects:
train: 25% 

FPS:25.8
Objects:
train: 26% 

FPS:31.4
Stream closed.
input video stream closed. 

Because I have to measure the average FPS of the algorithm to verify the real-time performance of the algorithm. Thank you very much！

**Comment by AlexeyAB** [comment]
Use this repository https://github.com/AlexeyAB/darknet instead of https://github.com/pjreddie/darknet to get AVG FPS

**Comment by kaikaisun** [comment]
> Use this repository https://github.com/AlexeyAB/darknet instead of https://github.com/pjreddie/darknet to get AVG FPS

Hello, I am using this  repository . Probably downloaded in July 2019.

**Comment by pedbrgs** [comment]
Hi, guys! When you run the darknet demo command with the `-benchmark` flag does the execution end? When I do this, the detection keeps running and never stops. So, I never have the `AVG_FPS` estimate.
