### ISSUE TITLE
Can´t run yolo_console_dll with Yolo9000 classifier on Visual Studio

### ISSUE THREAD

**Issue by fmgracias** [AlexeyAB/darknet#518]
Hi all,

I'm trying to **run yolo_console_dll with yolo9000 classifier** by changing this lines on **_yolo_console_dll.cpp_**:

![pic1_git](https://user-images.githubusercontent.com/32511760/37977963-ce9038ac-31dc-11e8-8888-b261c59efa39.png)

It build successfully but I keep getting the following error: _**Unhandled exception at 0x00007FFFC269A508 (ucrtbase.dll) in yolo_console_dll.exe: An invalid parameter was passed to a function that considers invalid parameters fatal.**_

![image](https://user-images.githubusercontent.com/32511760/37978187-63added0-31dd-11e8-8034-56d0e34ecea1.png)

This happens in both Visual Studio 2017 and 2015 Community. I've tried to run without debugging but the outcome is the same.

Interestingly:

1. **If I run yolo_console_dll directly from the console it works fine**:
**_"yolo_console_dll.exe data/9k.names yolo9000.cfg yolo9000.weights teste2.png"_**

![image](https://user-images.githubusercontent.com/32511760/37978606-515bcc32-31de-11e8-84cf-69edb63ea3d1.png)

2. **If I use data\voc.names + yolo-voc.cfg + yolo-voc.weights it also works:**

![image](https://user-images.githubusercontent.com/32511760/37979175-cda0e592-31df-11e8-9d0c-8824aa91253f.png)

Any help to fix this error is appreciated and I thank you in advance for that!

**Comment by fmgracias** [comment]
Apparently it was due to this lines in yolo9000.cfg:
```
tree=data/9k.tree
map = data/coco9k.map
```
If I remove them it runs successfully on Visual Studio 2017/2015

Does this impact the classifier?

**Comment by AlexeyAB** [comment]
Probably something wrong with paths.

Can you show screenshot from MSVS: (right click on project) -> properties -> Debugging ?
In the **Working Directory** should be `$(ProjectDir)\x64`

**Comment by fmgracias** [comment]
Thank you for your prompt reply @AlexeyAB 

In fact I had the working Directory wrong (set to $(ProjectDir)) but **it is fixed now**:
![image](https://user-images.githubusercontent.com/32511760/37981359-6e624cbe-31e5-11e8-9939-3609e912e5ab.png)

Now it runs successfuly with the yolo.cfg file containing:
```
tree=data/9k.tree
map = data/coco9k.map
```
Thank you so much for you help and work

**Comment by CodeForWuyu** [comment]
@fmgracias  thanks a lot, it worked
