### ISSUE TITLE
Build Yolo as DLL

### ISSUE THREAD

**Issue by shadmreese** [AlexeyAB/darknet#5193]
Hi, 

I'm trying to build Yolo as DLL to use as a Windows console application.  When I build: build\darknet\yolo_console_dll.sln

I receive the attached error. I have tried to add Additional OpenCV Directories but with not success
![buildError](https://user-images.githubusercontent.com/55153024/78743032-80d1a900-792b-11ea-916a-2a95ecf40ed2.jpg)

**Comment by AlexeyAB** [comment]
Do you use Legacey way, CMake-GUI or vcpkg? https://github.com/AlexeyAB/darknet#how-to-compile-on-windows-using-cmake-gui

Did you install OpenCV and set Windows set system variable `OpenCV_DIR`? https://github.com/AlexeyAB/darknet#requirements

**Comment by shadmreese** [comment]
AlexeyAB, First off thanks for all you do!  To answer your question I used  CMake-GUI to build CMake-GUI.

**Comment by AlexeyAB** [comment]
If you use Cmake-GUI, then compile and use `uselib` project instead of `yolo_console_dll` project, this is the same.

![image](https://user-images.githubusercontent.com/4096485/78778752-730c3a00-79a4-11ea-8b0a-b27cf7e334d0.png)

**Comment by shadmreese** [comment]
AlexeyAB,  Thanks!
uselib.exe worked but I'm not sure its working properly.  The inference of a three minute video only took took 15 seconds.  Is it possible to save results of the the uselib.exe command to .avi video?  I think the darknet switch '-out_filename res.avi' but it did not work.

Also, what is the difference between 'uselibe' and  'uselib_tracker.exe' 

Thanks again for your support!
