### ISSUE TITLE
Network width, height

### ISSUE THREAD

**Issue by mey1k** [AlexeyAB/darknet#5196]
I use 100x100 img and network width : 96, height : 96

I trained and it worked fine.

But I heard that Network widt,height usually use 416 or 608..

if i use 96 size. is it some disadvantages??

**Comment by brian208579** [comment]
Larger resolution usually leads to better results
Why are your picture resolutions all 100 * 100 ?
Have you set flag random=1 in your .cfg-file for training ? like this [link](https://github.com/AlexeyAB/darknet/blob/0039fd26786ab5f71d5af725fc18b3f521e7acfd/cfg/yolov3.cfg#L788)
It will increase precision by training Yolo for different resolutions
