### ISSUE TITLE
Probably bug with net.seen field

### ISSUE THREAD

**Issue by xevolesi** [AlexeyAB/darknet#5198]
Hi, @AlexeyAB !
The situation is as follows: started to train YOLOv3, trained the first 4000 iterations on 1 GPU, then continued to train on 4 GPUs. So the network was trained up to 997,000 iterations, after which the training crashed due to problems with the local network. I tried to continue training but when I try to load the **..._997000.weights** I get this:

![first](https://user-images.githubusercontent.com/17986847/78866513-3003a280-7a48-11ea-93da-bc74da44e81b.png)

I got into the code where I found that this could happen in a function **train_detector(...)** [here](https://github.com/AlexeyAB/darknet/blob/3d9aa2af4718a3bd5bbe23de2022987cb767e9c5/src/detector.c#L383) if the loop condition is not met [here](https://github.com/AlexeyAB/darknet/blob/3d9aa2af4718a3bd5bbe23de2022987cb767e9c5/src/detector.c#L177). 

I slightly modified the darknet code so that the following values ​​are output to the console:

- net.cur_iteration;
- net.seen;
- net.batch;
- net.subdivisions.
and began to load the weights obtained at various iterations. Here are the results:

1000'th iteration:
![second](https://user-images.githubusercontent.com/17986847/78868331-6989dd00-7a4b-11ea-906b-4445bb38ef43.png)

2000'th iteration:
![third](https://user-images.githubusercontent.com/17986847/78868448-a05ff300-7a4b-11ea-8df9-d24c70443f8f.png)

3000'th iteration:
![fourth](https://user-images.githubusercontent.com/17986847/78868622-ec129c80-7a4b-11ea-9d92-6c8fa1615114.png)

4000'th iteration:
![fifth](https://user-images.githubusercontent.com/17986847/78868745-1fedc200-7a4c-11ea-92dd-3e58af177c80.png)

5000'th iteration:
![sixth](https://user-images.githubusercontent.com/17986847/78868870-4f043380-7a4c-11ea-92cf-c88555505510.png)

6000'th iteration:
![seventh](https://user-images.githubusercontent.com/17986847/78868954-73f8a680-7a4c-11ea-955c-6e59c5396146.png)

As you can see when loading the **_5000.weights** and **_6000.weights**, the **net.cur_iteration** value does not correspond to 5000 and 6000, respectively. 

Probably the issue is in the net.seen update procedure, or in the calculation of the [get_current_batch()](https://github.com/AlexeyAB/darknet/blob/3d9aa2af4718a3bd5bbe23de2022987cb767e9c5/src/network.c#L65) function (i'm not a strong C\C++ programmer so it's just an assumption).

Also, it should be noted that if I continue to train the network with 4000 iterations now, I will get this:

5000'th:
![eight](https://user-images.githubusercontent.com/17986847/78870007-1f562b00-7a4e-11ea-82b4-0b02d7735a81.png)

6000'th:
![nineth](https://user-images.githubusercontent.com/17986847/78870101-43b20780-7a4e-11ea-8fcc-60ab2f1868c9.png)

So, cur_iteration value is proper now. This issue happens. Not often but it happens.
My darknet is on this [commit](https://github.com/AlexeyAB/darknet/commit/a9bae4f0326b4a841756d5b1a6ed37821f6a9467) 
Could you deal with this situation, please?

You can get access to all mentioned .weights files and .cfg file via this [link](https://drive.google.com/open?id=1Ob2XYptyhussmVre2Sh6EvWKarrAA6hl)

**Comment by AlexeyAB** [comment]
* Did you change batch= or subdivisions= in cfg-file between running?
* What command do you use for training?

**Comment by xevolesi** [comment]
@AlexeyAB ,

I did not change neither the batch nor the subdivision parameters in .cfg file.

For training first 4000 iterations i used:
`./darknet detector train %path to .data file% %path to .cfg file% %path to partial 74 weights% -map -dont_show -mjpeg_port 8091`
To continue training (4000 iteration and further) i used:
`./darknet detector train %path to .data file% %path to .cfg file% %path to ..._4000.weights% -map -dont_show -mjpeg_port 8091 -gpus 0,1,2,3 -chart %path to previous chart.png file%`

**Comment by AlexeyAB** [comment]
@xevolesi I added fix: https://github.com/AlexeyAB/darknet/commit/08b1c20e2666ce8813054cfed6243ad48feaac1d

Do you get this issue with the latest Darknet code?

**Comment by xevolesi** [comment]
Hi, @AlexeyAB !
Do you want me to try to train some models with the latest darknet or ... ? I can train some models if you want, it's not a problem, but will it be helpful? This issue occures sometimes and sometimes not.

**Comment by AlexeyAB** [comment]
@xevolesi Hi, yes, try to train, at least 10 000 iterations.

**Comment by xevolesi** [comment]
@AlexeyAB ,
Ok. Started to train same model. It will be trained 4k iterations on 1 GPU and the i'll switch it to 4 GPUs.

![tt](https://user-images.githubusercontent.com/17986847/79044146-32aef500-7c0c-11ea-8744-48d009fa3ade.png)

**Comment by xevolesi** [comment]
@AlexeyAB ,
Trained ~12k iteration. Checked all weights from 1k up to 12k and _last.weights. All seems good.

![ttt](https://user-images.githubusercontent.com/17986847/79056165-205ca780-7c5c-11ea-9645-1f0370a666b1.png)
