### ISSUE TITLE
Make fails after modifying detector.c

### ISSUE THREAD

**Issue by sindhurau2009** [AlexeyAB/darknet#520]
I get the following error upon running 'make', after making some changes to the detector.c file at /src. 
So, I undid the changes and found that this issue continues even though the file is same as when downloaded. Turns out, even if a tab is entered in the original detector.c file, make fails with this error. Can anyone point me as to why this is happening and how to resolve this?

./src/detector.c: In function ‘calc_anchors’:
./src/detector.c:942:11: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘double’ [-Wformat=]
    printf(" i = %d, box_w = %d, box_h = %d, anchor_w = %d, anchor_h = %d, iou = %f \n",
           ^
./src/detector.c:942:11: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘double’ [-Wformat=]
./src/detector.c:942:11: warning: format ‘%d’ expects argument of type ‘int’, but argument 5 has type ‘double’ [-Wformat=]
./src/detector.c:942:11: warning: format ‘%d’ expects argument of type ‘int’, but argument 6 has type ‘double’ [-Wformat=]
./src/detector.c: In function ‘test_detector’:
./src/detector.c:1050:3: error: unknown type name ‘detection’
   detection *dets = get_network_boxes(&net, im.w, im.h, thresh, hier_thresh, 0, 1, &nboxes, letter);
   ^
compilation terminated due to -Wfatal-errors.
Makefile:102: recipe for target 'obj/detector.o' failed

**Comment by AlexeyAB** [comment]
Try to update your code from this repo and do
```
make clean
make -j8
```

**Comment by sindhurau2009** [comment]
I was using new version of detector.c with older versions of all the other files. Worked after updating, thanks!
