### ISSUE TITLE
About random problem

### ISSUE THREAD

**Issue by brian208579** [AlexeyAB/darknet#5200]
Hi @AlexeyAB 
I have a project always using 320*320 resolution to detect object
Do you think `random = 0` will be better than `random = 1` ?
Could you give me some suggestion ?
Appreciate

**Comment by pullmyleg** [comment]
1. What size are the objects you are trying to detect? 
2. What size are the images in the training data? 
3. Have you tried to retrain the model with random = 0 and compared the map? 

It's hard to know without more information about your training data and what you are trying to detect.
