### ISSUE TITLE
iterations counter jumped after continue by multi GPUs.

### ISSUE THREAD

**Issue by keita-honsho** [AlexeyAB/darknet#5204]
Hi @AlexeyAB.

I tried training a custom yolov3.

Windows 10
OpenCV 4.2.0
CUDA 10.2
cuDNN 7.6.5
Darknet.exe built on March 25

Set 416x416.
max_batches = 50200
subdivisions = 20
classes = 4
and fix filter and anchors values.

"GTX1080 x1" was a success.

$ darknet.exe hoge.data hoge.cfg darknet53.conv.74 -map

However, on "GTX1080 x2", memory error and "iterations" jump occur.

$ darknet.exe hoge.data hoge_1000.cfg darknet53.conv.74 -map
$ darknet.exe hoge.data hoge.cfg hoge_1000_last.weights -map -gpus 0,1

>  (next mAP calculation at 11344 iterations) 
>  Last accuracy mAP@0.5 = 95.71 %, best = 95.71 % 
>  10496: 0.216763, 0.183333 avg loss, 0.002000 rate, 3.681000 seconds, 1259520 images, 54.566813 time left
> Loaded: 0.000000 seconds
> 
>  (next mAP calculation at 11344 iterations) 
>  Last accuracy mAP@0.5 = 95.71 %, best = 95.71 % 
>  10498: 0.232956, 0.188295 avg loss, 0.002000 rate, 3.285000 seconds, 1259760 images, 54.427119 time left
> Loaded: 0.000000 seconds
> Syncing... Saving weights to data/backup/hoge_last.weights
>  Try to set subdivisions=64 in your cfg-file. 
>  Try to set subdivisions=64 in your cfg-file. 
> CUDA Error: out of memory: No error
> Done!
> 
>  (next mAP calculation at 11344 iterations) 
>  Last accuracy mAP@0.5 = 95.71 %, best = 95.71 % 
>  10500: 0.228214, 0.192287 avg loss, 0.002000 rate, 3.684000 seconds, 1260000 images, 54.245128 time left
> Resizing, random_coef = 1.40 
> 
>  384 x 384 
>  try to allocate additional workspace_size = 52.43 MB 
>  CUDA allocate done! 
>  try to allocate additional workspace_size = 52.43 MB 
>  CUDA allocate done! 
> Loaded: 3.610000 seconds - performance bottleneck on CPU or Disk HDD/SSD
> CUDA status Error: file: C:\local\darknet\src\dark_cuda.c : cuda_make_array() : line: 373 : build time: Mar 25 2020 - 12:35:16 
> CUDA status Error: file: C:\local\darknet\src\dark_cuda.c : cuda_make_array() : line: 373 : build time: Mar 25 2020 - 12:35:16 
> 
>  CUDA Error: out of memory
> 
>  CUDA Error: out of memory

Can I get an error if I have multiple GPUs on the same GPU with the same subdivisions?

It's resumed.

$ darknet.exe hoge.data hoge.cfg hoge_last.weights -map -chart chart.png -gpus 0,1

>  (next mAP calculation at 16974 iterations) 
>  15252: 0.109478, 0.109478 avg loss, 0.002000 rate, 7.773000 seconds, 1830240 images, -1.000000 time left
> Loaded: 0.000000 seconds
>
>  (next mAP calculation at 16974 iterations) 
>  15254: 0.137196, 0.112249 avg loss, 0.002000 rate, 7.809000 seconds, 1830480 images, 75.458557 time left
> Loaded: 0.001000 seconds

The iterations on error are 10500.
At the time of the resumption, the iterations are now 15252.

What's wrong with that?

Thanks.

**Comment by keita-honsho** [comment]
Will this be resolved when #5198 is fixed?

**Comment by AlexeyAB** [comment]
I added fix: https://github.com/AlexeyAB/darknet/issues/5198#issuecomment-612404565

**Comment by keita-honsho** [comment]
Thanks @AlexeyAB.

I tried build #5198.

first 1000 iterations on single GPU. (darknet53.conv.74 -map)
>
>  (next mAP calculation at 1724 iterations) 
>  998: 0.770821, 0.713171 avg loss, 0.000992 rate, 7.423000 seconds, 59880 images, 0.150092 hours left
> Loaded: 0.000000 seconds
>
>  (next mAP calculation at 1724 iterations) 
>  999: 0.928582, 0.734712 avg loss, 0.000996 rate, 7.429000 seconds, 59940 images, 0.148632 hours left
> Loaded: 0.000000 seconds
>
>  (next mAP calculation at 1724 iterations) 
>  1000: 0.729303, 0.734171 avg loss, 0.001000 rate, 7.297000 seconds, 60000 images, 0.147167 hours left
> Resizing to initial size: 416 x 416  try to allocate additional workspace_size = 52.43 MB 
>  CUDA allocate done! 
>

ok.
restart on two GPUs. (1000_final.weights -map -gpus 0,1)
>
>  (next mAP calculation at 3714 iterations) 
>  1365: 0.588389, 0.588389 avg loss, 0.002000 rate, 5.676000 seconds, 120120 images, -1.000000 hours left
> Loaded: 0.000000 seconds
>
>  (next mAP calculation at 3714 iterations) 
>  1367: 0.725108, 0.602061 avg loss, 0.002000 rate, 5.668000 seconds, 120296 images, 76.996518 hours left
> Loaded: 0.000000 seconds
>
>  (next mAP calculation at 3714 iterations) 
 > 1369: 0.623591, 0.604214 avg loss, 0.002000 rate, 5.865000 seconds, 120472 images, 76.995402 hours left
> Loaded: 0.000000 seconds
>

and outputs _2363.weghts, _3363.weights, _4363.weights...


(1) The first iteration count ended at 1000 and restarted at 1365(1363?).

(2) The output weights is not a multiple of 1000. 

(3) For a single GPU, there is a setting to complete the training.
    Under the same conditions, the two GPUs may give an error.
    Is there such a thing?

GTX1080 8GB: yolov3 416x416 batch=64 subdivbisions=22
>
>  (next mAP calculation at 17826 iterations) 
>  Last accuracy mAP@0.5 = 95.67 %, best = 95.67 % 
>  15503: 0.139174, 0.171379 avg loss, 0.002000 rate, 2.956000 seconds, 1364264 images, 46.350291 hours left
> Resizing, random_coef = 1.40 
>
>  512 x 512 
>  try to allocate additional workspace_size = 52.43 MB 
>  CUDA allocate done! 
>  try to allocate additional workspace_size = 52.43 MB 
>  CUDA allocate done! 
> Loaded: 0.000000 seconds
>  CUDA status Error: file: C:\local\darknet\src\dark_cuda.c : cuda_make_array() : line: 373 : build time: Apr 13 2020 - 12:33:34 
> CUDA status Error: file: C:\local\darknet\src\dark_cuda.c : cuda_make_array() : line: 373 : build time: Apr 13 2020 - 12:33:34 
>
>  CUDA Error: out of memory
>
>  CUDA Error: out of memory
>

regards.

**Comment by AlexeyAB** [comment]
> GTX1080 8GB: yolov3 416x416 batch=64 subdivbisions=22

* Why do you use 22 instead of 32?

* Check that you deleted old version of Darknet

**Comment by keita-honsho** [comment]
This is because I feel that the more subdivisions there are, the longer the calculation time per iteration will be.
Isn't this correct?


and, sorry.
old darknet tried subdivisions = 20.
and change subdivisions to 22, by memory error.
new darknet first 1000 config's subdivisions = 20,
The rest of the study, subdivisions = 22.
train images = 25864
batch = 64
25864 / 64 = 404.125
25864 / (64 * 20) = 20.20625
25864 / (64 * 22) = 18.3693181818
404 / 20 * 18 = 363

If I get "memory alloc error" and change subdivisions, should I start from the beginning instead of continuing with _last.weights?

**Comment by AlexeyAB** [comment]
> new darknet first 1000 config's subdivisions = 20,
> The rest of the study, subdivisions = 22.

* Do you use the same batch=64 in both cases?

* So the reason - `batch/subdivisions` isn't integer value.

* Do you get this issue if `batch/subdivisions` is **integer** value? like 64/32 or 64/16

**Comment by keita-honsho** [comment]
Yes, batch=64 in both cases.

OK.
batch should (must?) be an integer multiple of subdivisions.

My cfg's batch is 64, but looking at the logs, it seems to have been modified and learned to 44.
>
> net.optimized_memory = 0 
> mini_batch = 2, batch = 44, time_steps = 1, train = 1 
> Done! Loaded 107 layers from weights-file 
>

It will take some time, but I'll try "64/32" when I'm done with the current training.

thanks.

**Comment by keita-honsho** [comment]
thanks, @AlexeyAB 

I have confirmed that there is no problem with restarting the training with batch 64 and subdivisions 32.

Issue #5301 was issued for a problem that caused CUDA errors only when using multiple GPUs.
