### ISSUE TITLE
have troube in running darknet_video.py

### ISSUE THREAD

**Issue by zhiha** [AlexeyAB/darknet#5211]
23.82748199150135
23.961153068336323
23.812466290827132
23.693955485255902
23.639870367761027
23.265369062740945
23.617773423202753
23.14354135628759
Traceback (most recent call last):
  File "darknet_video.py", line 114, in <module>
    YOLO()
  File "darknet_video.py", line 97, in YOLO
    frame_rgb = cv2.cvtColor(frame_read, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

It seems like it always get wrong with this message in the last.I run this video test in the Cloud server,so I wander which reason may cause that.Can you give me some idea or suggestions?

I will be thankful to your help!(I guess it may have problem in Video decoder,but I'm not sure)Do you know how I can solve this problem?
I would appreciate it very much if I could get your help

**Comment by Wazaki-Ou** [comment]
@zhiha Can you please give some feedback about this ? Did you manage to solve it? I am experiencing the same error and wondering if this is caused by the video reaching its last frame or a different issue.
