### ISSUE TITLE
memory leak in jetson nano.

### ISSUE THREAD

**Issue by yacad** [AlexeyAB/darknet#5214]
Hello @AlexeyAB.

Not long ago, I asked a question about a memory leak.(#4996)
Thank you very much for your many good answers.
For a question similar to me, you gave an answer similar to the one you told me.(#4453)

"It seems this in an internal error in the interaction of two 3rd party libraries Pthread + OpenCV, which only happens on some platforms/versions of OS, Pthread, OpenCV."

I thought that the compilation environment(some platforms/versions of OS...)  I created might have been wrong, so I tested it by restarting it when the memory increases over a certain amount.
However, I recently bought a jetson nono and downloaded the jetson Nano Developer Kit SD card image to test it, but a memory leak also occurred. It is an compilation environment provided by NVIDIA, not an environment I created ...
![image](https://user-images.githubusercontent.com/53897615/79062482-d1ebef00-7cd5-11ea-9f59-ce1a042d8f03.png)

Many people around me are having trouble testing because of this problem.
Do you have a plan to revise the memory growth in ./darknet detector demo?
Can you tell me your compilation environment if you don't have this problem?

I'm clumsy in English, and I hope my question was delivered.

**Comment by AlexeyAB** [comment]
@yacad 

1. I don't have this issue on all Windows systems
2. I don't have this issue on some Linux Ubuntu OS
3. I don't have this issue if I don't use OpenCV
4. I don't have this issue if entire my code uses C++ instead of C + C++

I have the same issue on the same Linux/Libraries/Drivers/Hardware if I use Xeon CPU instead of Core i7 CPU.
It seems the problem is for OpenCV and CPUs: Xeon CPU, ARM CPU.

The problem isn't in your compilation environment.
Most likely a bug in OpenCV, more specific is in the interaction of `OpenCV<->CPU` and/or `OpenCV<->Pthread` and/or `gcc<->g++`

-----

> Do you have a plan to revise the memory growth in ./darknet detector demo?

1. Yes, I have a plane to rewrite Pthread to `thrd_t` from C-standard. And may be use C++ instead of C.

2. Currently you can use `./uselib coco.names yolov3.cfg yolov3.weights test.mp4` instead of `./darknet demo ...`

**Comment by yacad** [comment]
Thanks AlexeyAB

**Comment by AlexeyAB** [comment]
@yacad Hi,

I added a fix.

1. Try to download latest version of Darknet and recompile
```
make clean
make
```

2. If it doesn't help, then try to replace `demo.c` file by this file [demo.c.txt](https://github.com/AlexeyAB/darknet/files/4471620/demo.c.txt)

and recompile:
```
make clean
make
```

----

Does 1 or 2 solve memory leak issue?

**Comment by AlexeyAB** [comment]
@yacad Is the problem resolved?

**Comment by yacad** [comment]
Thanks @AlexeyAB.

Today I will tell you the results of both methods after testing.

**Comment by yacad** [comment]
@AlexeyAB Hi,

A. Test environment
GPU: NVIDIA RTX 2070
OS: Ubuntu 18.04
GCC: 7.4.0
CUDA: 10.0
CUDNN: 7.5.0
OPENCV : 3.4.0

B. Edit Makefile
GPU = 1
CUDNN = 1
CUDNN_HALF = 1
OPENCV=1
USE_CPP=1

ARCH= -gencode arch=compute_75,code=[sm_75,compute_75]

ifeq ($(CUDNN_HALF), 1)
COMMON+= -DCUDNN_HALF
CFLAGS+= -DCUDNN_HALF
ARCH+= -gencode arch=compute_75,code=[sm_75,compute_75]
endif

C. Test result
I tested 40 minutes per sample.
The memory leak caused by the process in the system was confirmed by the VSZ value.

1. Old version (git clone 2020/03/18)
  - Memory(VSZ value) : 14,478,032 => 14,744,276 (**266,244 increase**)
  - Avg FPS : **67.6** fps (not use CUDNN_HALF : **51.8** fps)

2. New version (git clone 2020/04/17) : solution 1
  - Memory(VSZ value) : 14,481,144 => 14,612,216 (**131,072 increase**)
  - Avg FPS : **51.2** fps (not use CUDNN_HALF : **51.2** fps)

3. New version (git clone 2020/04/17) : solution 2 (replace demo.c file by this file demo.c.txt)
  - Memory(VSZ value) : 14,365,752 => 14,365,752 (**no memory leak**)
  - Avg FPS : **40.0** fps (not use CUDNN_HALF : **40.0** fps)

It is amazing!!!
In the proposed solution 2, there was no memory leak problem.

In the proposed solution 1 that committed, a memory leak occurred.
In the proposed solutions 1 and 2, FPS decreased more than before when CUDNN_HALF was used. FPS was the same when CUDNN_HALF was used and not.
Perhaps CUDNN_HALF doesn't apply. I do not know the reason.

**Comment by AlexeyAB** [comment]
@yacad Thanks!

1. So replacing `pthread` by `std::thread` doesn't solve the issue.

2. A complete rejection of multithreading solves this problem

I will think about how I can fix this with minimal changes.

**Comment by yacad** [comment]
Thanks @AlexeyAB.

I know the cause of the problem clearly, so I will try to solve it.
If I solve this problem, I will share it with you.

I have one questions for you. Please.

As can be seen from the test results, unlike the old version, the CUDNN_HALF value in the new version has no speed difference both 0 and 1.

- Old version (git clone 2020/03/18) : Avg FPS : **67.6 fps** (not use CUDNN_HALF : **51.8 fps**)
- New version (git clone 2020/04/17) : Avg FPS : **51.2 fps** (not use CUDNN_HALF : **51.2 fps**)

I want to know the reason. Can you explain to me?

**Comment by AlexeyAB** [comment]
@yacad I fixed it.

@WongKinYiu

There was a bug - Tensor Cores was not used for inference (Detection)
* from Mar 27, 2020 - Fixed adversarial attack and training: https://github.com/AlexeyAB/darknet/commit/4f62a01cd338f4a9039559eba45b293264b6dbd8
* to Apr 18, 2020 - Tensor Cores fixed: https://github.com/AlexeyAB/darknet/commit/5dc7d8074d47347eff515f03a80c2d1e97eda95e

**Comment by yacad** [comment]
Thanks @AlexeyAB.

**Comment by AlexeyAB** [comment]
@yacad 
I fixed `./darknet detector demo ...` commits https://github.com/AlexeyAB/darknet/commit/56a7ccf07e21776c8f58f41c7cfc14d99a71dd26 and https://github.com/AlexeyAB/darknet/commit/66c809fe78d9b2b0f51d5d65bdc8f83a1f530694
It should be +10% faster and without memory leak. Check it.

**Comment by yacad** [comment]
Thanks @AlexeyAB.

Wow!!!! It's great.

I tested for 2 hours.
Memory increased slightly during the first 10 minutes(VSZ value : 14,460,376=>14,463,456), and then there was no more memory growth.

**Comment by yacad** [comment]
Memory increased slightly during the first 10 minutes, and then there was no more memory increase.

The problematic CUDNN_HALF (Tensor Core) also works fine.

**Comment by AlexeyAB** [comment]
@yacad Hi,

> The speed was as follows.
> Old version (git clone 2020/03/18) : Avg FPS : **67.6 fps** (not use CUDNN_HALF : 51.8 fps)
> New version (git clone 2020/04/19) : Avg FPS : **62.6 fps** (not use CUDNN_HALF : 51.2 fps)

Do  you mean that new version slower than old version?
Can you check it again, since new version should be +10% faster.

**Comment by yacad** [comment]
I checked it again.(CUDNN_HALF = 1)

- Old version (git clone 2020/03/18) => AVG_FPS : 63.0
![image](https://user-images.githubusercontent.com/53897615/79689123-ba8ca300-828d-11ea-8182-ae701f75aad2.png)

- New version (git clone 2020/04/19) => AVG_FPS : 61.6 
![image](https://user-images.githubusercontent.com/53897615/79689083-8add9b00-828d-11ea-90f7-bcdf02ff5c5f.png)

**Comment by AlexeyAB** [comment]
@yacad Thanks!
So memory leak issue is solved.
But performance -3% slower on Jetson Nano (ARM CPU)


----

You can try to tune this param, set 3 instead of 1
https://github.com/AlexeyAB/darknet/blob/4786d557f9ac7452ded74ce2f3df06fbe991924e/src/demo.c#L54

and recompile.

----

If it doesn't help - also try to set `this_thread_sleep_for(thread_wait_ms);` 
instead of
1. https://github.com/AlexeyAB/darknet/blob/4786d557f9ac7452ded74ce2f3df06fbe991924e/src/demo.c#L64
2. https://github.com/AlexeyAB/darknet/blob/4786d557f9ac7452ded74ce2f3df06fbe991924e/src/demo.c#L96

----

If it will help, may be I will add these fixes.

**Comment by yacad** [comment]
@AlexeyAB Hi.

> So memory leak issue is solved.
> But performance -3% slower on Jetson Nano (ARM CPU)

The memory leak problem occurred on both the development PC and the Jetson nano.
Test was conducted with a development PC that was easy to debug.
Tested on Jetson nano today.
The result was the same, and there was no memory leak, and the speed did not increase by 10%.

> You can try to tune this param, set 3 instead of 1
> darknet/src/demo.c
> static const int thread_wait_ms = 1; 
> and recompile.
> If it doesn't help - also try to set this_thread_sleep_for(thread_wait_ms);
> instead this_thread_yield(); 

Speed did not increase. Decreased or equal.

Thanks @AlexeyAB.

**Comment by AlexeyAB** [comment]
@yacad 

> The **memory leak problem occurred on both** the development PC and the Jetson nano.
> Test was conducted with a development PC that was easy to debug.
> Tested on Jetson nano today.
> The result was the same, and there was **no memory leak**, and the speed did not increase by 10%.

So there is now a memory leak or not?

**Comment by yacad** [comment]
@AlexeyAB

There is no memory leak.
