### ISSUE TITLE
Error: Couldn't open file: data/obj.data while training

### ISSUE THREAD

**Issue by devb2020** [AlexeyAB/darknet#5217]
Encountered the error: Couldn't open file: data/obj.data while training with yolov3 in windows,

darknet.exe detector train data/obj.data yolo-obj.cfg darknet53.conv.74

The obj.data is stored at the same level as darknet binaries at -->...\darknet\build\darknet\x64\data as per the guidelines "How to train (to detect your custom objects):"

I'd visited Issue #379  for same error but it didn't help.

Any ideas to resolve this error...? I'm stuck 'coz of this...  :(

**Comment by devb2020** [comment]
Resolved the error. Added .txt to obj.data so as to pass obj.data.txt in the entire command
darknet.exe detector train data/obj.data.txt yolo-obj.cfg darknet53.conv.74

**Comment by PGCodehub** [comment]
@devb2020 

I changed the file name to obj.data.txt and called as you said 

darknet.exe detector train data/obj.data.txt  .......

But still, I am getting  `Couldn't open file: data/obj.data.txt

In setting up I followed guidelines given exactly, I do not know where I am going wrong 

Please please help

**Comment by devb2020** [comment]
> @devb2020
> 
> I changed the file name to obj.data.txt and called as you said
> 
> darknet.exe detector train data/obj.data.txt .......
> 
> But still, I am getting `Couldn't open file: data/obj.data.txt
> 
> In setting up I followed guidelines given exactly, I do not know where I am going wrong
> 
> Please please help

Hi Pramod,
This was one of the workaround that worked for me..
This error usually occurs when your txt file is generated automatically using Python (Not Sure Why this happens).

As another workaround you can try manually addding paths to your txt file. This may sound cumbersome for a large set of paths but works most of the times.
Also ensure that you use absolute paths rather than relative paths in your txt file.

**Comment by PGCodehub** [comment]
HI @devb2020 

Thank you for you help 

By providing absolute path to files  , it started training 

Thanks
