### ISSUE TITLE
Can I reuse the weights file of  pjreddie's darknet

### ISSUE THREAD

**Issue by linex-cd** [AlexeyAB/darknet#5219]
Hi AlexeyAB,
I found the yolov3 model can be use on both versions(pjreddie's  and yours)
So, if i have trained my data on pjreddie's, can I just use the model to detect and classify with yours?

**Comment by AlexeyAB** [comment]
Yes, just there is temporary issue with ResNet models.

**Comment by linex-cd** [comment]
Thanks
