### ISSUE TITLE
YOLOv2 detections wrong due to YOLOv3 update

### ISSUE THREAD

**Issue by TheMikeyR** [AlexeyAB/darknet#522]
Command used: 
```/darknet detector test ./cfg/coco.data ./cfg/yolo.cfg ./yolov2.weights data/dog.jpg -i 0 -thresh 0.25```

Weights downloaded from [pjreddie](https://pjreddie.com/media/files/yolov2.weights)
No difference in the cfg used, used https://github.com/AlexeyAB/darknet/blob/master/cfg/yolo.cfg. 

https://github.com/AlexeyAB/darknet/commit/991a24016794f3412d668919a94e9994711874d2
![predictions](https://user-images.githubusercontent.com/1436625/38017990-f2bdb474-3273-11e8-9ded-de921e751558.png)
```
Loading weights from ./yolov2.weights...
 seen 32 
Done!
data/dog.jpg: Predicted in 0.061057 seconds.
pottedplant: 25%
dog: 82%
truck: 73%
bicycle: 82%
bicycle: 25%
```

https://github.com/AlexeyAB/darknet/commit/47c7af1cea5bbdedf1184963355e6418cb8b1b4f
![predictions](https://user-images.githubusercontent.com/1436625/38018017-0869cd1c-3274-11e8-91cb-b72fa463c3fb.png)

```
Loading weights from ./yolov2.weights...
 seen 32 
Done!
data/dog.jpg: Predicted in 0.061166 seconds.
truck: 77%
bicycle: 84%
dog: 79%
```

YOLOv3 seems to work pretty great `./image-yolov3.sh`, I had a run where it didn't detect a car at 26% though.
![predictions](https://user-images.githubusercontent.com/1436625/38018268-b6e75b34-3274-11e8-9172-da0fa61fbc39.png)

```
Loading weights from ./yolov3.weights...
 seen 64 
Done!
data/dog.jpg: Predicted in 0.132577 seconds.
dog: 99%
truck: 92%
car: 26%
bicycle: 99%
```

**Comment by AlexeyAB** [comment]
I fixed it: https://github.com/AlexeyAB/darknet/commit/d014f7530f3043da5fe2030666e07aefa2efc71a
Just tested on **Linux Debian 8 x64, CUDA 8.0.44, cuDNN 6, OpenCV 3.2.0**:
Makefile:
```
GPU=1
CUDNN=1
OPENCV=1
DEBUG=0
OPENMP=1
LIBSO=1
```


`./darknet detector test ./cfg/coco.data ./cfg/yolo.cfg ./yolov2.weights data/dog.jpg -i 0 -thresh 0.25`
```
dog: 79%
truck: 78%
bicycle: 84%
```
![predictions](https://user-images.githubusercontent.com/4096485/38027650-1a89075e-3299-11e8-9cc0-8335067ec324.jpg)

----

`./image-yolov3.sh`
```
data/dog.jpg: Predicted in 0.052932 seconds.
dog: 100%
truck: 93%
bicycle: 99%
```
![predictions](https://user-images.githubusercontent.com/4096485/38027710-50fd944e-3299-11e8-9a1c-d504f56557fe.jpg)

----

**Windows 7 x64, CUDA 9.1, cuDNN 7, OpenCV 3.4.0:**
`darknet.exe detector test ./cfg/coco.data ./cfg/yolo.cfg ./yolov2.weights data/dog.jpg -i 0 -thresh 0.25`
```
data/dog.jpg: Predicted in 0.026000 seconds.
dog: 79%
bicycle: 84%
truck: 79%
```
![predictions](https://user-images.githubusercontent.com/4096485/38028145-a611b13a-329a-11e8-8336-8e5b783bf8a9.jpg)


----

`darknet_yolo_v3.cmd`
```
dog.jpg: Predicted in 0.057000 seconds.
dog: 100%
bicycle: 99%
truck: 94%
```
![predictions](https://user-images.githubusercontent.com/4096485/38028030-488bebca-329a-11e8-991d-bbaa498b917b.jpg)

**Comment by TheMikeyR** [comment]
@AlexeyAB Thanks, I can confirm it is fixed now!

My results yolov2:
![predictions](https://user-images.githubusercontent.com/1436625/38029040-0c994522-3295-11e8-806b-b6a4651e90e5.png)


yolov3 also works, no more car detection at 26%
![predictions](https://user-images.githubusercontent.com/1436625/38029015-f4ee71cc-3294-11e8-891a-dca6a1eb6759.png)
