### ISSUE TITLE
Non-zero class AP even TP = FP = 0

### ISSUE THREAD

**Issue by minhduc0711** [AlexeyAB/darknet#5224]
Hi, after running the `detector map` command, I'm wondering why would AP for a certain class be non-zero even when TP = FP = 0. Thanks in advance!
```
class_id = 3, name = damaged_heat, ap = 7.86%   	 (TP = 0, FP = 0)
```

**Comment by lsd1994** [comment]
TP and FP is for certain threshold (default 0.25), but mAP is for all detection results (prob>0.005).
So maybe you can detect some objects satisfied IOU>0.5 but prob<0.25.

**Comment by minhduc0711** [comment]
Ah I see, thanks. 
It's a bit confusing for me since these results are put next to each other but the thresholds are different.
