### ISSUE TITLE
Yolov3 pre-trained weights/config with latest coco dataset

### ISSUE THREAD

**Issue by pliablepixels** [AlexeyAB/darknet#5238]
Hello, it looks like in https://github.com/AlexeyAB/darknet#pre-trained-models we are linking to a 2014 snapshot of coco. Are there any pre-trained weights/configs that leverage more recent updates to the coco database that can work with darknet? I don't have enough resources to re-train from scratch. Thanks.

**Comment by AlexeyAB** [comment]
Based on http://cocodataset.org/#download the 2014 - 2019 train+val datasets are equal.
`train2014+val2014 === train2019+val2019`

> **2019 Update: All data for all challenges stays unchanged.**
> 
> **2018 Update: Detection and keypoint data is unchanged.** New in 2018, complete stuff and panoptic annotations for all 2017 images are available. Note: if you downloaded the stuff annotations prior to 06/17/2018, please re-download.
> 
> **2017 Update:** The main change in 2017 is that instead of an 83K/41K train/val split, based on community feedback the split is now 118K/5K for train/val. **The same exact images are used, and no new annotations for detection/keypoints are provided.**

**Comment by pliablepixels** [comment]
sounds good, thanks
