### ISSUE TITLE
CSI camera with darknet

### ISSUE THREAD

**Issue by elementdl** [AlexeyAB/darknet#5246]
Hi @AlexeyAB , 

I want to use a CSI Camera with darknet, but I don't know how he can recognize this camera.

When I try a simple "./darknet detector demo" with yolov3-tiny, I get 3 warnings telling me about cap_gstreamer.cpp :
-module v4l2src0 reported : internalt data stream error
-unable to start pipeline
-pipelin have not been created

then a million lines of : 
VIDIOC_QBUF: Invalid argument.

Sincerely,

**Comment by AlexeyAB** [comment]
Try to find in Google `csi camera opencv`

**Comment by elementdl** [comment]
Hi @AlexeyAB , I already searched and found this from jetson hacks : https://github.com/JetsonHacksNano/CSI-Camera

But I don't know how to do it with darknet.

Let's say I want to enter this command : 

darknet.exe detector demo cfg/coco.data cfg/yolov3-tiny.cfg yolov3-tiny.weights 

What do I have to add on this command in order to use the csi camera?
Or is there a file I need to modify before?

Sincerely,

**Comment by AlexeyAB** [comment]
Try to use it as default v4l web-camera
`./darknet detector demo cfg/coco.data cfg/yolov3-tiny.cfg yolov3-tiny.weights -c 0`

or with `-c 1`

**Comment by elementdl** [comment]
I already did, with -c 1 I thinks there is no camera connected so it says the stream stopped.
With -c 0 I got the sames errors I showed in my first message. 
Is there a file I need to modify to adjust something about openCV, or maybe GStreamer?
