### ISSUE TITLE
YoloV3 Training Problem

### ISSUE THREAD

**Issue by hnhuang** [AlexeyAB/darknet#525]
Hi Alexey,

I can train YoloV2 in my own dataset without problem. Today I tried YoloV3 and I got the following errors with random = 1:

Loading weights from models/darknet53.conv.74...
 seen 64 
Done!
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Resizing
320
Resizing type 22 
Cannot resize this type of layer: File exists
darknet: ./src/utils.c:199: error: Assertion `0' failed.
Aborted (core dumped)
**********************************************************
I thus changed from random=1 to random=0. Then I got

Loading weights from models/darknet53.conv.74...
 seen 64 
Done!
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Loaded: 1.433929 seconds
Segmentation fault (core dumped)

Can you please help?

**Comment by AlexeyAB** [comment]
@hnhuang I fixed it.
Update your code and try again.

**Comment by hnhuang** [comment]
It is working now. Thanks.
