### ISSUE TITLE
detect object's color using yolov3

### ISSUE THREAD

**Issue by Nazrindino97** [AlexeyAB/darknet#5254]
Does yolov3 capable of detecting the maturity of a fruit (example: mangos)? 
can it differentiate colors?

**Comment by AlexeyAB** [comment]
Yes, just comment `hue=` and `saturation=` in cfg-file before training.

**Comment by Nazrindino97** [comment]
thank you :)

**Comment by Nazrindino97** [comment]
can it be applied in yolov3-Keras?

**Comment by AlexeyAB** [comment]
I think yes.
It depends on implementation, does it get hue= saturation= params from cfg-file, or are they hardcoded in python.

**Comment by Nazrindino97** [comment]
let's try it first
