### ISSUE TITLE
CUDA + CuDNN + Python = Low GPU Usage

### ISSUE THREAD

**Issue by lucaspojo** [AlexeyAB/darknet#5255]
Hi ! 
Sorry if I don't ask about the right github, I use so much different techno that I don't know who to talk to anymore.

I made a python object recognition script with my webcam. I use Yolov3.weight and a 416x416 detection. I stay at **16/20FPS** but my GPU is only used at **20%** ! If it was used at 80/90% it would be great!

I tried it with 60 fps video and I have the same problem. Do you have a solution or idea ? Thanks a lot!
LOOK THE VIDEO -> **https://www.youtube.com/watch?v=FOPb0mqhIKE**
Code : https://gist.github.com/lucaspojo/0e3f9d9577fe7d3fad4de2efb8fad4b6

**Comment by AlexeyAB** [comment]
How many FPS do you get with C Darknet with the same model and the same videofile?
`./darknet detector demo ... `


You should write asynchronous Python-code for runing in 3 different CPU-threads:
1. pre-processing + videocapture
2. network inference
3. post-processing + show results

**Comment by lucaspojo** [comment]
It's done ! I run the detection on multiple threads. It was an optimization of my code. That's all it was. Thank you!

**Comment by AlexeyAB** [comment]
@lucaspojo If your implementation is not very complicated, you can do a Pull Request to change https://github.com/AlexeyAB/darknet/blob/master/darknet_video.py so that other users do not have such problems.

**Comment by tanmayj000** [comment]
Hi @lucaspojo  & @AlexeyAB , has the pull request to optimize darknet_video.py been made? I am still facing the error of slow inference speed. Using ./darknet I get an fps of around 27 whereas using darknet_video.py it goes to only around 8-10 FPS.
