### ISSUE TITLE
Cannot train on my custom objects (seg fault)

### ISSUE THREAD

**Issue by Spain2394** [AlexeyAB/darknet#5263]
I am using a NVIDIA Tesla V100, and have been unable to get my custom object configuration working on this hardware.  Additional system specs: CUDA-version: (10000), cuDNN: 7.1.4, CUDNN_HALF=1, GPU count: 1, with OpenCV version: 3.4.7

I have been able to validate that everything works on this hardware for training, and detection on the out of the box tests like the following: 

1) train: coco dataset using yolov3-tiny.cfg and yolov3-tiny.conv.15
1) test: detection of coco objects using yolov3-tiny.weights and yolov3-tiny.cfg

however whenever I use my custom configuration file `plant-weed-yolov3-tiny.cfg ` on my dataset, it seg faults each time.  I went through the steps in the Readme for configuring custom config files, but haven't been able to solve this issue. 

Note: 
[plant-weed-yolov3-tiny.txt](https://github.com/AlexeyAB/darknet/files/4500471/plant-weed-yolov3-tiny.txt)

I have tried using random=0, and random=1 in my config file.

Thank you

Error msg:
<img width="1375" alt="seg_fault" src="https://user-images.githubusercontent.com/18317669/79702700-d172cb80-8274-11ea-915a-b33b057e3b81.png">

**Comment by AlexeyAB** [comment]
1. Use `channels=3` in cfg-file

2. Also don't change to `filters=21` for conv-layers with leaky activation

**Comment by Spain2394** [comment]
Glad I asked. Thank you
