### ISSUE TITLE
No output in Ubuntu

### ISSUE THREAD

**Issue by vfbsilva** [AlexeyAB/darknet#5271]
Seems after some update darknet is no longer finishing. It simply hangs:
`./darknet detector test data/obj.data yolo-obj.cfg yolo-obj_10000.weights data/img/rg_-_wellington_silva_fonseca.jpg -i 0 -thresh 0.20.`

```
CNH: 100%
data_emissao_CNH: 100%
local_emissao_CNH: 100%
pri_habilitacao_CNH: 100%
validade_CNH: 100%
registro_CNH: 100%
filiacao_CNH: 100%
nascimento_CNH: 100%
cpf_CNH: 100%
identidade_CNH: 100%
nome_CNH: 100%
```
But the process does not end.

**Comment by vfbsilva** [comment]
It does end but is very very slow, maybe because my model has 10000 iterations?

**Comment by AlexeyAB** [comment]
No.

It's because you compiled Darknet without GPU or OPENMP/AVX.
