### ISSUE TITLE
Low accuracy when I use jitter=0 

### ISSUE THREAD

**Issue by marcoslucianops** [AlexeyAB/darknet#5274]
Hi,

I'm training letters using YoloV3-Tiny-PRN. I have great object detection (all 7 letters are detected) using jitter=0.3 but sometimes the detection is incorrect. When I use jitter=0 it can't detect the letters, only 2-3 letters are detected.

How I can solve this?

**Comment by AlexeyAB** [comment]
1. Or use `jitter=0.3`

2. Or use `[net] letter_box=1` and `[yolo] jitter=0` for training, and run detection with flag at the end of detection command `-letter_box`
