### ISSUE TITLE
I can't use YOLO v3 in my console application

### ISSUE THREAD

**Issue by RDIgor** [AlexeyAB/darknet#528]
I use the code in follow link : 

https://github.com/AlexeyAB/darknet/blob/a6cbaeecde40f91ddc3ea09aa26a03ab5bbf8ba8/src/yolo_console_dll.cpp.

When create object of class Detector, I pass yolov3.cfg and yolov3.weights. Then I run my application, programm running and load yolov3. But in one moment console crash because don't load yolov3. 

Can you help me?

**Comment by AlexeyAB** [comment]
I fixed it.
