### ISSUE TITLE
Loss graph after training is stopped

### ISSUE THREAD

**Issue by vedgya** [AlexeyAB/darknet#5280]
Is there a way to get loss graph from the starting if my training gets stopped for some reason and I resume it.

**Comment by AlexeyAB** [comment]
You should resume training with flag `-chart chart.png` at the end of training command. https://github.com/AlexeyAB/darknet/pull/4783

**Comment by vedgya** [comment]
Thanks, Kudos to you and @pjreddie on such a great work.
