### ISSUE TITLE
Corrupt JPEG data  problem

### ISSUE THREAD

**Issue by brian208579** [AlexeyAB/darknet#5293]
Hi @AlexeyAB 
When I trained the yolov3 model , I got this information.

`Corrupt JPEG data: 2 extraneous bytes before marker 0xdb`

![corrupt problem](https://user-images.githubusercontent.com/43407888/80093252-b961bb80-8596-11ea-8059-c42144596a02.png)

**What does this informatiom mean ?** and **How can I fix it ?**

Appreciate

**Comment by procule** [comment]
It means there is a file listed as a jpeg in your training/val set that is not. 
On Linux, you can use `file -i image.jpg` to be sure the mime-type is `image/jpeg`
