### ISSUE TITLE
Output file is not created?

### ISSUE THREAD

**Issue by apiszcz** [AlexeyAB/darknet#53]
Example on Ubuntu works.

Windows10/YoloV2
However I'm not seeing an output file with the bounding rectangle for a single file or mp4. The mp4 mode writes the avi, however no bounding boxes, and no output prediction file from what I am seeing.

darknet detector test data/coco.data yolo.cfg yolo.weights -nogpu -thresh 0.1 data/dog.jpg
Loading weights from yolo.weights...Done!
data/dog.jpg: Predicted in 4.567000 seconds.
 SRC output_video = 0000000000000000
 cvCreateVideoWriter, DST output_video = 0000020AF3073660
 cvWriteFrame

**Comment by AlexeyAB** [comment]
@apiszcz 

Parameter ` -nogpu` doesn't work.
Try to compile `build/darknet/darknet_no_gpu.sln` https://github.com/AlexeyAB/darknet/tree/master/build/darknet

And use `darknet.exe detector test data/coco.data yolo.cfg yolo.weights -thresh 0.24 data/dog.jpg`

Will be created file `predictions.jpg` with predictions:

![predictions](https://cloud.githubusercontent.com/assets/4096485/24802759/c7827c6a-1bb1-11e7-9294-ee4439b41068.jpg)

**Comment by apiszcz** [comment]
Tested, darknet_no_gpu.sln same result, no bounding boxes drawn.
I tested with a GPU build and have same result.
Is there a brief description of the command line options besides yolo.c?
Interested in getting the json or text output of the detections.

**Comment by AlexeyAB** [comment]
Try to compile without OpenCV:

> To compile without OpenCV - remove define OPENCV from: Visual Studio->Project->Properties->C/C++->Preprocessor

----

> Is there a brief description of the command line options besides yolo.c?

Most here: https://github.com/AlexeyAB/darknet#how-to-use

> Interested in getting the json or text output of the detections.

There are 3 ways:

1. In file `data/coco.data` change path `valid  = data/coco_testdev` to .txt-file with jpg-images which you want to predict
    * if this is absent - you should create directory `darknet/build/darknet/x64/results/`
    * then run `darknet.exe detector valid data/coco.data yolo.cfg yolo.weights -thresh 0.24`
    * in the directory `darknet/build/darknet/x64/results/` will be created txt-files with obj_id and coordinates

2. You can add at this line your code to output predictions in your own any format: https://github.com/AlexeyAB/darknet/blob/9c63bd33ada8656a6eedccafbd468c56f3103f5f/src/image.c#L219


3. You can compile darknet as DLL-library `build\darknet\yolo_cpp_dll.sln` https://github.com/AlexeyAB/darknet#how-to-use-yolo-as-dll
   * and use it in your own applications `build\darknet\yolo_console_dll.sln`
   * where you can implement code for output predictions in your own any format: https://github.com/AlexeyAB/darknet/blob/master/src/yolo_console_dll.cpp#L51

**Comment by AlexeyAB** [comment]
@apiszcz 

You never should not use parameter `-nogpu`:

> darknet_no_gpu detector test data/coco.data yolo.cfg yolo.weights **-nogpu** -thresh 0.24 data/dog.jpg

**Comment by apiszcz** [comment]
I am not using -nogpu as a command line argument. It seems like it needs to be included to set gpu_index=-1 for the CPU only build.

darknet.c
    gpu_index = find_int_arg(argc, argv, "-i", 0);
    if(find_arg(argc, argv, "-nogpu")) {
        gpu_index = -1;
    }

If I add it as a function I get an argument error.

**Comment by AlexeyAB** [comment]
@apiszcz Try to update darknet from github. I have fixed cfg-files for new weights.

Or download it by links:
* `yolo.cfg`: https://github.com/AlexeyAB/darknet/raw/master/build/darknet/x64/yolo.cfg
* `yolo-voc.cfg`: https://raw.githubusercontent.com/AlexeyAB/darknet/master/build/darknet/x64/yolo-voc.cfg

**Comment by apiszcz** [comment]
Awesome, so for it once it was not me :)
UPDATE WOKRED!!!!!!!!
So it seems not a lot of people are looking at this yet...

This produced the detections, will test GPU and then with mp4 input files.

Thank you

More questions later I'm guessing now that it is producing output.

 ```
build/darknet/x64/darknet_coco.cmd  |  2 +-
 build/darknet/x64/darknet_voc.cmd   |  2 +-
 build/darknet/x64/results/tmp.txt   |  0
 build/darknet/x64/tiny-yolo-voc.cfg |  2 +-
 build/darknet/x64/yolo-voc.cfg      | 35 +++++++++++++++++++++++++----------
 build/darknet/x64/yolo.cfg          | 31 +++++++++++++++++++++++--------
 cfg/tiny-yolo-voc.cfg               |  2 +-
 cfg/yolo-voc.cfg                    | 34 ++++++++++++++++++++++++----------
 cfg/yolo.cfg                        | 30 ++++++++++++++++++++++--------


```

**Comment by AlexeyAB** [comment]
@apiszcz Excellent.

About output to different formats, use any of the 3 wyas: https://github.com/AlexeyAB/darknet/issues/53#issuecomment-292550242

**Comment by apiszcz** [comment]
So i thought this was a port of the LINUX code/? However it seems like you are improving/adding functionality? I see the DLL option with some text output. JSON would be great, including the frame # for video.

**Comment by apiszcz** [comment]
Did some testing, 1920x1080, 480x270, both with CPU 0.3 FPS
GPU 10.3 and 11.5 FPS
I thought there would be larger difference, The input data is 30FPS

**Comment by AlexeyAB** [comment]
Yes, there some additions to initial code. DLL and application which uses Differntiating the detected objects: https://github.com/AlexeyAB/darknet/issues/49#issuecomment-290813368

I'll think latter about any other output formats or wrapers to Python.

> I thought there would be larger difference,

Did you change resolution of input image or network-resolution in cfg-file?
Input resolution has no much affect, because all input resizes to the network size 416x416.

**Comment by apiszcz** [comment]
No i did not, ok, I'll need to cover the original input coordinates by
scaling from 416. Thanks.

**Comment by apiszcz** [comment]
it may be handy (in the future) to have argparse parameter flags, and allow relative paths

> lib\yolo_gpu\darknet detector demo lib/yolo_gpu/data/coco.data lib/yolo_gpu/cfg/yolo.cfg data/model/yolo/yolo.weights -i 0 -thresh 0.1 test.mp4

Couldn't open file: data/coco.names

**Comment by apiszcz** [comment]
CONSOLE and any mode need to add FRAME and time if possible.
after launching your console application and entering the image file name - you will see info for each object: <obj_id> <left_x> <top_y> <width> <height> <probability>

object: <frame> <time_ms> <obj_id> <left_x> <top_y> <width> <height> <probability>

**Comment by AlexeyAB** [comment]
@apiszcz 

The application that uses the library made as **simple example** - only to show features of DLL. This is done so that anyone can easily understand this example.

Any other functionality can be added by yourself.
