### ISSUE TITLE
We all known that train a self weights file is expensive, My question is how should I share my trained weights file to others?

### ISSUE THREAD

**Issue by gangyahaidao** [AlexeyAB/darknet#530]
Now I am training a weights file for detecting hands, i downloads the original pictures from here,
http://vision.soic.indiana.edu/projects/egohands/
Then i must spend a lot of time and energy to train it, so if i finally get a well trained weights file, how can i share it to others from here?

**Comment by AlexeyAB** [comment]
There is no special repository for this.

Just use https://www.google.com/drive/using-drive/
And share your link everywhere:
* https://github.com/pjreddie/darknet
* https://github.com/AlexeyAB/darknet
* https://groups.google.com/forum/#!forum/darknet

**Comment by gangyahaidao** [comment]
i will try after my training
