### ISSUE TITLE
How to enable data augmentation? 

### ISSUE THREAD

**Issue by hanlinniu** [AlexeyAB/darknet#5303]
Nice work @AlexeyAB , I have a question, how to enable data augmentation, like cutout, mixup, cutmix? Do I need to set cutout=1, mixup=1, cutmix=1 in the cfg file? or is it already enabled by default in yolov4?

**Comment by AlexeyAB** [comment]
set one of the lines in cfg
```
[net]
cutmix=1
mixup=1
mosaic=1
```

Cutout isn't implemented.

To check how this works, use the ` -show_imgs`  flag at the end of the training command.

**Comment by hanlinniu** [comment]
@AlexeyAB , thank you very much for the reply, can I set cutxmix=1, mixup=1, mosaic=1 at the same time? I found when I set cutxmix=1, it said segmentation fault (core dumped), and mixup=1 and mosaic=1 works. By the way, my training images has multiple objects in each image.

**Comment by AlexeyAB** [comment]
Possible combinations:

For Classifier:
* mixup=1
* cutmix=1
* mosaic=1
* cutmix=1 mosaic=1

For Detector:
* mixup=1
* mosaic=1 (only if compiled with OpenCV)

**Comment by hanlinniu** [comment]
@AlexeyAB , get it, thank you very much!
