### ISSUE TITLE
What is the difference between the cmake-gui method and the legacy way? 

### ISSUE THREAD

**Issue by Eve66666** [AlexeyAB/darknet#5305]
hi, What is the difference between the cmake-gui method and the legacy way?
Will legacy way affect the training speed of YOLOv4 after successful compilation?

I had never studied cmake and opencv before, and I always had problems when compiling Darknet using cmake-gui, so I used legacy way, which worked,But I don't know if legacy way has any effect on YOLOv4 training.
So I was wondering if legacy way had an impact on training?

**Comment by AlexeyAB** [comment]
You can use any way for Darknet compilation. Accuracy and speed of YOLOv4 will be the same, just should be enabled (GPU, CUDNN, CUDNN_HALF, OPENCV).

> hi, What is the difference between the cmake-gui method and the legacy way?

Someone is more comfortable with Make, and someone is more comfortable with a Cmake. Differet ways for the same result.

**Comment by Eve66666** [comment]
Tks!
