### ISSUE TITLE
Anyone managed to download the paper?

### ISSUE THREAD

**Issue by vfbsilva** [AlexeyAB/darknet#5306]
The link seems broken.

**Comment by AlexeyAB** [comment]
Can you show screenshot? https://arxiv.org/abs/2004.10934

**Comment by vfbsilva** [comment]
Too many downloads my friend! Now it is working!
![overflow](https://user-images.githubusercontent.com/874774/80248931-4bc19800-8647-11ea-8585-0175e3995371.png)
