### ISSUE TITLE
CSPDarknet-53 

### ISSUE THREAD

**Issue by furkanaydinoz** [AlexeyAB/darknet#5309]
Hello, I want to train my own object detection weights with Yolov4. However, I could not find the CSPDarknet-53 convolutional weights mentioned in the article(https://arxiv.org/pdf/2004.10934.pdf page:12). Should I use the darknet53.conv.74 weights in Yolov3? Or is it still not released for yolov4?

**Comment by Eve66666** [comment]
In readme.md, use CTRL +F to search for "yolov4.conv.137"

**Comment by DataXujing** [comment]
U should use `"yolov4.conv.137`

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

https://drive.google.com/open?id=1JKF-bdIklxOOVy-2Cr5qdvjgGpmGfcbp


> Download pre-trained weights for the convolutional layers and put to the directory build\darknet\x64
> 
> for yolov4.cfg, yolov4-custom.cfg (162 MB): yolov4.conv.137
> for csresnext50-panet-spp.cfg (133 MB): csresnext50-panet-spp.conv.112
> for yolov3.cfg, yolov3-spp.cfg (154 MB): darknet53.conv.74
> for yolov3-tiny-prn.cfg , yolov3-tiny.cfg (6 MB): yolov3-tiny.conv.11
> for enet-coco.cfg (EfficientNetB0-Yolov3) (14 MB): enetb0-coco.conv.132

**Comment by furkanaydinoz** [comment]
Thank you for your feedback
