### ISSUE TITLE
CMake build question

### ISSUE THREAD

**Issue by aldragan0** [AlexeyAB/darknet#5314]
Hi @AlexeyAB, thank you for your work.

I've noticed that cmake disables CUDNN_HALF although I use a V100, it states that CC >= 7.5, shouldn't it have been CC >= 7.0?
This is the line which checks if it can enable CUDNN_HALF:
https://github.com/AlexeyAB/darknet/blob/2fc7fbbc0ea001170b12d39b840b9f4d34905dd4/CMakeLists.txt#L68

**Comment by AlexeyAB** [comment]
@cenit Hi, What is the reason, that V100 disables CUDNN_HALF? It should work for V100 CC == 7.0

**Comment by AlexeyAB** [comment]
@aldragan0 Try to change this line https://github.com/AlexeyAB/darknet/blob/2fc7fbbc0ea001170b12d39b840b9f4d34905dd4/CMakeLists.txt#L68

to 
` if (NOT "arch=compute_70,code=sm_70" IN_LIST CUDA_ARCH_FLAGS) `

does it work well?

**Comment by aldragan0** [comment]
Changing the line fixes the problem.

**Comment by cenit** [comment]
> @cenit Hi, What is the reason, that V100 disables CUDNN_HALF? It should work for V100 CC == 7.0

not sure anymore on the reasons I had to choose 7.5... 
same problem was exposed on #4698 and I forgot to answer also there.

Shall I do a PR for that or do you modify it, @AlexeyAB ?

**Comment by cenit** [comment]
Sorry I didn't notice you already fixed that. Thanks!

Fixed by https://github.com/AlexeyAB/darknet/commit/893b889b2f62bff91d9c63931787d553ee19512f

**Comment by cenit** [comment]
Also, finally https://gitlab.kitware.com/cmake/cmake/-/merge_requests/4568 is merged. This will allow a modern management of CUDA archs in CMake. I will do a PR as soon as CMake 3.18 is released
