### ISSUE TITLE
bounding box issue with yolov4

### ISSUE THREAD

**Issue by kaishijeng** [AlexeyAB/darknet#5315]
I use yolov4-custom.cfg to train my own datatset. Just modify # of classes and # of filters per instruction. The training is running OK, but it seems width of detected bounding box is wrong (always too wide) as  below. Anything else I need to change in the yolov4-custom.cfg. I have trained yolov3 with the same dataset and doesn't have this problem.

![image](https://user-images.githubusercontent.com/12689630/80273591-48023580-8688-11ea-8006-e2c8b893bec4.png)

Thanks,

**Comment by AlexeyAB** [comment]
I think you also changed max_batches and something else, right?
How many iterations did you train?
Show chart.png with Loss and mAP and attach cfg-file.

**Comment by kaishijeng** [comment]
Yes, I did other changes according to the instruction .
I found the root cause of this issue is due to incorrect labelling.
Thanks,

**Comment by yjhuasheng** [comment]
hi，i have same issue, the bounding box is always too wide or too big.
