### ISSUE TITLE
training error with yolov4

### ISSUE THREAD

**Issue by JackeyGuo** [AlexeyAB/darknet#5318]
Hello, when I train yolov4, this line of information appears "Create 64 permanent cpu-threads", it will automatically stop afterwards, and return nothing. Then I query the number of CPU cores, only 8 cores. How can i resolve this problem, thanks.

**Comment by AlexeyAB** [comment]
Provide more information:
Show screenshot of the error.
What params do you use in the Make/Cmake file?
What versions of CUDA, cuDNN, OpenCV, OS do you use?
Show such screenshot
![image](https://user-images.githubusercontent.com/4096485/80279435-5d1da980-8706-11ea-9080-90053d4448b8.png)

**Comment by JackeyGuo** [comment]
thank for your response. this is the error information:
![错误](https://user-images.githubusercontent.com/10000640/80279552-05e0fe80-8731-11ea-9fea-b2a3222deaae.png)
In the makefile, i set GPU=1;CUDNN=1;CUDNN_HALF=1;OPENCV=1;USE_CPP=0;DEBUG=1; My os is centos7, cuda version is 9.0, cudnn version is 7.4.1.

**Comment by JackeyGuo** [comment]
And, the following is the information of start running:
![开始](https://user-images.githubusercontent.com/10000640/80279704-d67ec180-8731-11ea-807e-ba15ba8aa64c.png), thanks!

**Comment by AlexeyAB** [comment]
Don't use `yolov4.weights` file for training.

Read: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

**Comment by JackeyGuo** [comment]
Thanks, i think the following information shows that training has been successfully started:
![正常](https://user-images.githubusercontent.com/10000640/80280154-e0ee8a80-8734-11ea-9e68-229a3c812c58.png)

**Comment by AlexeyAB** [comment]
What command do you use for training?
Do you use yolov4.cfg or yolov4-custom.cfg?
Why did you compile Darknet without OpenCV?

**Comment by JackeyGuo** [comment]
Yes, i modified the yolov4-custom.cfg to match the category of my training set. And the command for training like this: "./darknet detector train data/obj.data yolo-obj.cfg yolov4.conv.137 -map". For the opencv, in my centos7, there is a unusual problem appeared. I haven't found a solution yet, so I can only compile darknet without opencv. 
![opencv错误](https://user-images.githubusercontent.com/10000640/80280664-029d4100-8738-11ea-874e-6638b4b554c2.png)

**Comment by AlexeyAB** [comment]
This issue - you can't install OpenCV on Centos7?
Did you try to install the latest OpenCV version by using Cmake?

**Comment by JackeyGuo** [comment]
Yes, for now, i have not solved this problem. I tried the OpenCV version 4.3.0 and 3.4.3 and got the same error. The way to install OpenCV also uses cmake and make at the same time. And the command like this:
![opencv安装](https://user-images.githubusercontent.com/10000640/80280893-c539b300-8739-11ea-97c1-41894b050964.png)

**Comment by maohu-96** [comment]
@JackeyGuo  我用以下命令进行训练
./darknet detector train data/obj.data cfg/yolo-obj.cfg yolov4.conv.137
出现错误： Create 64 permanent cpu-threads 
段错误 (核心已转储)
我该怎么解决，谢谢

**Comment by JackeyGuo** [comment]
我之前遇到这个问题是因为我使用了yolov4.weight，最后我改为yolo4.cov.137，训练就可以使用了。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"mh96"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月28日(星期二) 下午4:10
收件人:&nbsp;"AlexeyAB/darknet"<darknet@noreply.github.com&gt;;
抄送:&nbsp;"伴你长路 "<1051347391@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [AlexeyAB/darknet] training error with yolov4 (#5318)





 
@JackeyGuo  我用以下命令进行训练
 ./darknet detector train data/obj.data cfg/yolo-obj.cfg yolov4.conv.137
 出现错误： Create 64 permanent cpu-threads
 段错误 (核心已转储)
 我该怎么解决，谢谢

**Comment by maohu-96** [comment]
@JackeyGuo 感谢您的回复，我用的是yolo4.conv.137，但还是会出现这个错误，我看到您修改了.cfg中的训练类别，我的训练集只有一个类别，class=1是正确的吗
谢谢

**Comment by JackeyGuo** [comment]
是的，你再仔细核对一个class的情况下，filter的个数和其他需要修改的地方



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"mh96"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月28日(星期二) 下午4:28
收件人:&nbsp;"AlexeyAB/darknet"<darknet@noreply.github.com&gt;;
抄送:&nbsp;"伴你长路 "<1051347391@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [AlexeyAB/darknet] training error with yolov4 (#5318)





 
@JackeyGuo 感谢您的回复，我用的是yolo4.conv.137，但还是会出现这个错误，我看到您修改了.cfg中的训练类别，我的训练集只有一个类别，class=1是正确的吗
 谢谢
