### ISSUE TITLE
"STB Reason: can't fopen" on a .txt list of images

### ISSUE THREAD

**Issue by RobertAndreiGit** [AlexeyAB/darknet#5322]
When I try to run using   darknet.exe detector test ./cfg/coco.data ./cfg/yolov4.cfg ./yolov4.weights -dont_show < data/train.txt > result.txt on a list of images it doesn't work, giving the error from below, except for the last image. On that one it works.
I took the train.txt text from the example (using newline between each entry)
```
"annot load image "data/dog.jpg
STB Reason: can't fopen
"annot load image "data/dog.jpg
STB Reason: can't fopen
```
I know the path is valid because the last line from the file works. So what's wrong? Am I using the newline badly?

**Comment by RobertAndreiGit** [comment]
If anyone encounters this, use linux style of newline

**Comment by ywt0226** [comment]
what's linux style of newline mean ?

**Comment by stephanecharette** [comment]
> what's linux style of newline mean ?

https://www.google.com/search?q=linux+newline

**Comment by NikolaAndro** [comment]
Does the path for each image consider the path to the image from the same directory as darknet.exe?

**Comment by NikolaAndro** [comment]
> 

The answer to it is yes.
