### ISSUE TITLE
how to convert image_t to cv::Mat?

### ISSUE THREAD

**Issue by LifeIsSoSolong** [AlexeyAB/darknet#5323]
I convert image_t to cv::Mat like this “cv::Mat frame(image.h, image.w, CV_32F, image.data);” and got a gray mat;
then I convert image_t to cv::Mat like this “cv::Mat frame(image.h, image.w, CV_32F, image.data);” and I got nine same mat;

how to transform 3 channels image_t to a color cv Mat?

**Comment by procule** [comment]
Assuming you have 3 channels with normalized colour (0.0 to 1.0), you have to use the `CV_32FC3` definition (C3 is for 3 Channels).
For 3 channels with 8bits colours (0 to 255), you would use `CV_8UC3`.

You can take a look at all the definitions in `opencv2/core/hal/interface.h `

**Comment by AlexeyAB** [comment]
```cpp
extern "C" cv::Mat image_to_mat(image img)
{
    int channels = img.c;
    int width = img.w;
    int height = img.h;
    cv::Mat mat = cv::Mat(height, width, CV_8UC(channels));
    int step = mat.step;

    for (int y = 0; y < img.h; ++y) {
        for (int x = 0; x < img.w; ++x) {
            for (int c = 0; c < img.c; ++c) {
                float val = img.data[c*img.h*img.w + y*img.w + x];
                mat.data[y*step + x*img.c + c] = (unsigned char)(val * 255);
            }
        }
    }
    return mat;
}
// ----------------------------------------

extern "C" image mat_to_image(cv::Mat mat)
{
    int w = mat.cols;
    int h = mat.rows;
    int c = mat.channels();
    image im = make_image(w, h, c);
    unsigned char *data = (unsigned char *)mat.data;
    int step = mat.step;
    for (int y = 0; y < h; ++y) {
        for (int k = 0; k < c; ++k) {
            for (int x = 0; x < w; ++x) {
                //uint8_t val = mat.ptr<uint8_t>(y)[c * x + k];
                //uint8_t val = mat.at<Vec3b>(y, x).val[k];
                //im.data[k*w*h + y*w + x] = val / 255.0f;

                im.data[k*w*h + y*w + x] = data[y*step + x*c + k] / 255.0f;
            }
        }
    }
    return im;
}
```

**Comment by procule** [comment]
@AlexeyAB 
In the same order of idea:

I have made a _ffmpeg_ filter to use Darknet model with `libdarknet.so` and it's working nicely.
Since the _ffmpeg_ input stream is using `yuvj420p`, I'm converting each frame to RGB to pass it to `libdarknet.so` and to draw the results, I use that RGB frame and use OpenCV drawing functions.

However, I have to reconverted it back to `yuvj420p` format at the output of the filter. This creates a bottleneck and when viewing hi-def videos with high FPS, I can't get the real FPS and I have to drop some frames.

Do you know if it's possible to draw the results from `get_network_boxes` directly unto the YUV frame, without having to do that double conversion ?

O.

**Comment by stephanecharette** [comment]
Be careful if you use the code Alexey posted 2 comments above.  Remember that OpenCV famously uses BGR format and not RGB.

Thus, there are 2 critical lines that I think might be missing from that code.  When you convert from darknet image to cv::Mat, you'll probably want to call this on the mat AFTER it is created:

```
cv::cvtColor(mat, mat, cv::COLOR_RGB2BGR);
```

Likewise, when you convert from cv::Mat to a darknet image, you'll want to reverse that PRIOR to running the conversion code:

```
cv::cvtColor(mat, mat, cv::COLOR_BGR2RGB);
```

**Comment by procule** [comment]
> Be careful if you use the code Alexey posted 2 comments above. Remember that OpenCV famously uses BGR format and not RGB.
> 
> Thus, there are 2 critical lines that I think might be missing from that code. When you convert from darknet image to cv::Mat, you'll probably want to call this on the mat AFTER it is created:
> 
> ```
> cv::cvtColor(mat, mat, cv::COLOR_RGB2BGR);
> ```
> 
> Likewise, when you convert from cv::Mat to a darknet image, you'll want to reverse that PRIOR to running the conversion code:
> 
> ```
> cv::cvtColor(mat, mat, cv::COLOR_BGR2RGB);
> ```

Of course.

**Comment by LifeIsSoSolong** [comment]
> ```c++
> extern "C" cv::Mat image_to_mat(image img)
> {
>     int channels = img.c;
>     int width = img.w;
>     int height = img.h;
>     cv::Mat mat = cv::Mat(height, width, CV_8UC(channels));
>     int step = mat.step;
> 
>     for (int y = 0; y < img.h; ++y) {
>         for (int x = 0; x < img.w; ++x) {
>             for (int c = 0; c < img.c; ++c) {
>                 float val = img.data[c*img.h*img.w + y*img.w + x];
>                 mat.data[y*step + x*img.c + c] = (unsigned char)(val * 255);
>             }
>         }
>     }
>     return mat;
> }
> // ----------------------------------------
> 
> extern "C" image mat_to_image(cv::Mat mat)
> {
>     int w = mat.cols;
>     int h = mat.rows;
>     int c = mat.channels();
>     image im = make_image(w, h, c);
>     unsigned char *data = (unsigned char *)mat.data;
>     int step = mat.step;
>     for (int y = 0; y < h; ++y) {
>         for (int k = 0; k < c; ++k) {
>             for (int x = 0; x < w; ++x) {
>                 //uint8_t val = mat.ptr<uint8_t>(y)[c * x + k];
>                 //uint8_t val = mat.at<Vec3b>(y, x).val[k];
>                 //im.data[k*w*h + y*w + x] = val / 255.0f;
> 
>                 im.data[k*w*h + y*w + x] = data[y*step + x*c + k] / 255.0f;
>             }
>         }
>     }
>     return im;
> }
> ```

thank you ~ It works~

**Comment by LifeIsSoSolong** [comment]
> Assuming you have 3 channels with normalized colour (0.0 to 1.0), you have to use the `CV_32FC3` definition (C3 is for 3 Channels).
> For 3 channels with 8bits colours (0 to 255), you would use `CV_8UC3`.
> 
> You can take a look at all the definitions in `opencv2/core/hal/interface.h `

thanks for your advice ,it's useful for me ~
