### ISSUE TITLE
Weight Graph

### ISSUE THREAD

**Issue by furkanaydinoz** [AlexeyAB/darknet#5325]
I want to create a chart of the trained weights. However, I did not find such a thing in other repo. Is there a way to do this? I would be very glad if you could help.

**Comment by AlexeyAB** [comment]
What is the weights chart?

`chart.png` file with Loss will be created automatically
if you train with `-map` flag, then there also will be AP50 / Top5 chart

**Comment by furkanaydinoz** [comment]
./darknet detector train data/obj.data cfg/yolov2_custom.cfg darknet19_448.conv.23 -dont_show -map
is this correct ?
