### ISSUE TITLE
yolov4.weights download

### ISSUE THREAD

**Issue by opentld** [AlexeyAB/darknet#5335]
谷歌云盘下载太慢了，哪位兄弟能提供一下百度云盘的下载？
多谢~

**Comment by jy1023408440** [comment]
https://72k.us/file/26468910-439532813    提取密码： 446792

**Comment by jy1023408440** [comment]
https://blog.csdn.net/jy1023408440/article/details/105736611

**Comment by lhlong** [comment]
Try at [yolov4 ggdrive](https://drive.google.com/file/d/1cewMfusmPjYWbrnuJRuKhPMwRe_b9PaT/view)

**Comment by opentld** [comment]
https://github.com/msnh2012/yolov4-weights-for-CN

需要下载的自取~~~
