### ISSUE TITLE
Improvement on accuracy and mAP

### ISSUE THREAD

**Issue by poornimajd** [AlexeyAB/darknet#5339]
Hey @AlexeyAB  Great work!!
I have trained yolov3 with the following yolov3-spp.cfg

[yolov3-spp.txt](https://github.com/AlexeyAB/darknet/files/4535019/yolov3-spp.txt)
I have used iou loss =giou and resolution of 608x608.Here are a few samples of the images used for training.(It is from Indian Driving Dataset(IDD)).
https://github.com/poornimajd/show
I have 8 classes in the dataset .I gave around 23k training images and 4k validation images with data augmentation and  I got a MAP(@0.5) of 74% on training data and MAP(@0.5) of 71% on test data with the following loss graph.
![chart_9_further](https://user-images.githubusercontent.com/31023599/80304037-54de7080-87d1-11ea-92d8-4a0de1e0344e.png)

But when I calculate the accuracy of detection using confusion matrix, I get around 57%.
This is the result of confusion matrix (at a IOU of 50%.)
![best_aug_8c_area_9](https://user-images.githubusercontent.com/31023599/80304232-417fd500-87d2-11ea-8264-f001a378431e.png)

Can you please suggest as to how can I improve the accuracy further or MAP.I also referred 
https://github.com/AlexeyAB/darknet#how-to-improve-object-detection
Any suggestion is greatly appreciated.
Thank you

**Comment by AlexeyAB** [comment]
Try to train yolov4: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

**Comment by poornimajd** [comment]
Thanks a lot for the quick reply!I will check out yolov4.
