### ISSUE TITLE
Why no Gaussian in Yolov4?

### ISSUE THREAD

**Issue by LukeAI** [AlexeyAB/darknet#5341]
Congratulations on yolov4! Amazing SOTA results. I was wondering why the Gaussian Yolov4 head was not used? It's always given better results for me, is the performance cost too high?

**Comment by AlexeyAB** [comment]
G - is a Gaussian-YOLO

This gives no improvement for CSPResNext, but may be it will give improvement for CSDarknet53 or with other features: https://arxiv.org/abs/2004.10934

![image](https://user-images.githubusercontent.com/4096485/80308196-3464e500-87d6-11ea-8145-e4026578eeec.png)

----

Many experiments are still ongoing, and some show good results for different features.

**Comment by Amore-HDU** [comment]
Hello, Can you supply yolov4_gaussian cfg, Thanks @AlexeyAB
