### ISSUE TITLE
Number of classes includes background or not? Thanks

### ISSUE THREAD

**Issue by junyongyou** [AlexeyAB/darknet#5348]
There are several parameters in cfg file that are related to the number of classes. I am wondering if the number of classes should include background as one class or not? For example, if my goal is to detect cat and god as 2 classes, should I set the classes=2 or classes=3? I would guess that classes=2 is correct, because COCO has 80 classes excluding background. But just want to double check. Thanks a lot.

**Comment by procule** [comment]
Background is not included as a class, except if you want an "all others" class and tag all things not related to cats and gods(dogs?) with that class.

**Comment by junyongyou** [comment]
Thanks a lot @procule
