### ISSUE TITLE
Where can I see a description of the config parameter?for example :mosaic=1

### ISSUE THREAD

**Issue by jy1023408440** [AlexeyAB/darknet#5357]
like title

**Comment by marcoslucianops** [comment]
Refer to [Wiki](https://github.com/AlexeyAB/darknet/wiki) and [ToDo](https://github.com/AlexeyAB/darknet/labels/ToDo)/[enhancement](https://github.com/AlexeyAB/darknet/labels/enhancement).

Mosaic: [#4432](https://github.com/AlexeyAB/darknet/issues/4432)
Cutmix: [#4419](https://github.com/AlexeyAB/darknet/issues/4419)
Mixup: [#3372](https://github.com/AlexeyAB/darknet/issues/3272)
