### ISSUE TITLE
yolov4 detection on video and save result can't end correctly

### ISSUE THREAD

**Issue by buptdbj** [AlexeyAB/darknet#5359]
Hi Alexey,
  I found when I run yolov4 to detect video file, when it runs to the last frame, the detection cannot quit and stop correctly. But in some fomer darknet project, It can stop correctly. Can you help me with this? Thank you

**Comment by AlexeyAB** [comment]
> detection cannot quit and stop correctly.

What does it mean? Can you show screenshot or provide more information?

**Comment by buptdbj** [comment]
I mean when the program runs to the last frame, the process is still running, it seems the program is waiting for a new frame. I need to press Ctrl+C to end the process. But in previous version, it will automatically end the process and return to the command line.

screenshot after the last frame detection
![image](https://user-images.githubusercontent.com/32626344/80373790-2db69a80-88c8-11ea-910c-ce5e0737129f.png)

screenshot after I press Ctrl+C
![image](https://user-images.githubusercontent.com/32626344/80373945-779f8080-88c8-11ea-835d-6d6c9021277e.png)

**Comment by AlexeyAB** [comment]
What command do you use?

**Comment by AlexeyAB** [comment]
I just fixed it.

**Comment by waelausy** [comment]
> 
> 
> I mean when the program runs to the last frame, the process is still running, it seems the program is waiting for a new frame. I need to press Ctrl+C to end the process. But in previous version, it will automatically end the process and return to the command line.
> 
> screenshot after the last frame detection
> ![image](https://user-images.githubusercontent.com/32626344/80373790-2db69a80-88c8-11ea-910c-ce5e0737129f.png)
> 
> screenshot after I press Ctrl+C
> ![image](https://user-images.githubusercontent.com/32626344/80373945-779f8080-88c8-11ea-835d-6d6c9021277e.png)

Hello, to close stream automatically in the end, you must modify the variable in this line in the demo.c file from 0 to 1

https://github.com/AlexeyAB/darknet/blob/master/src/demo.c#L66
