### ISSUE TITLE
Download yolov4 weights from CLI

### ISSUE THREAD

**Issue by cenit** [AlexeyAB/darknet#5360]
Hi @AlexeyAB! First of all congratulations for the new Yolov4 milestone.
Then I would like also to ask you one thing: at the moment it is very difficult to download your weights from command line interfaces due to the fact that google drive hides "heavy" files (>100MB) under the google docs umbrella, which requires cookies and so on to work.

There is a hack to make it work on bash, but to perform it in a portable way it is much more difficult.
DO you have any other option for weights file distribution, maybe more CLI friendly?

**Comment by AlexeyAB** [comment]
@cenit Hi, Thanks!

I just uploaded yolov4.weights directly to GitHub: https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights
Do you have any suggestions on where to upload the weight file?


----

And yes, I think we should disable `macOS - clang - vcpkg` in TravisCI currently.

**Comment by waelausy** [comment]
> 
> 
> @cenit Hi, Thanks!
> 
> I just uploaded yolov4.weights directly to GitHub: https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights
> Do you have any suggestions on where to upload the weight file?
> 
> And yes, I think we should disable `macOS - clang - vcpkg` in TravisCI currently (without any other changes).

Great !! Thanks you for your fantastic work !
using this link we can use the wget function on linux !

`wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights`
