### ISSUE TITLE
Why GPU is not used in training? Thanks

### ISSUE THREAD

**Issue by junyongyou** [AlexeyAB/darknet#5365]
I have followed every step in Readme: Win10, Opencv 3.4.10, Cuda10, cuDNN, 1080Ti. I also compiled using Cmake-GUI, and then built solution in VS2019, and darknet.exe was also generated.

Then I started training on my own dataset with the suggested modifications in cfg file. The training is ongoing without any problems. However, in command window it says "GPU isn't used".

I am sure my graphic card is normal, as I am using it to train some TF models.

Could anybody tell me what I did wrong? Thanks a lot.

**Comment by junyongyou** [comment]
I checked my CMake windown, and found "Looking for a CUDA compiler - NOTFOUND". And then even if I tried to check ENABLE_CUDA, and then Generate, it was not successful. How should I solve this problem. I have both CUDA9 and CUDA10 on my PC, and in environmental variables. Is that the reason?

**Comment by junyongyou** [comment]
My solution:
1. Removing environmental variables for CUDA9 NOT working.
2. Uninstalling CUDA9 (CUDA10 kept) NOT working.
3. Uninstalling CUDA10 and then reinstall working.

**Comment by natures66** [comment]
您好，我想问以下您最后的解决方案是卸掉了cuda9重装cuda10然后重新cmake编译了吗

**Comment by junyongyou** [comment]
Yep.

**Comment by junyongyou** [comment]
> 
> 
> 您好，我想问以下您最后的解决方案是卸掉了cuda9重装cuda10然后重新cmake编译了吗

Yep.

**Comment by natures66** [comment]
> 
> 
> > 您好，我想问以下您最后的解决方案是卸掉了cuda9重装cuda10然后重新cmake编译了吗
> 
> Yep.

do you change the Makefile ? GPU=0,CUDNN=0 to GPU=1and CUDNN=1?

**Comment by junyongyou** [comment]
> 
> 
> > > 您好，我想问以下您最后的解决方案是卸掉了cuda9重装cuda10然后重新cmake编译了吗
> > 
> > 
> > Yep.
> 
> do you change the Makefile ? GPU=0,CUDNN=0 to GPU=1and CUDNN=1?

I don't think necessary.

**Comment by natures66** [comment]
> 
> 
> > > > 您好，我想问以下您最后的解决方案是卸掉了cuda9重装cuda10然后重新cmake编译了吗
> > > 
> > > 
> > > Yep.
> > 
> > 
> > do you change the Makefile ? GPU=0,CUDNN=0 to GPU=1and CUDNN=1?
> 
> I don't think necessary.

At first I just uninstalled the CUDA10 and reinstall it(but still keep CUDA9) , it's not working. So I follow your solution, uninstalled CUDA9 and CUDA10, then reinstall CUDA10, it's WORKING!!!!!!!!THANKS!!!!!!!
btw, it seems that VS must be installed before CUDA...

**Comment by natures66** [comment]
wait... there is no GPU isn't used , and shows CUDA-version and compute_capability, I think it's using GPU now. 
But when I tried to train on my own dataset, I use nvidia-smi to see gpu-util, it shows 1% and cpu-util is high. What's wrong...
