### ISSUE TITLE
 Create 64 permanent cpu-threads  段错误 (核心已转储)

### ISSUE THREAD

**Issue by maohu-96** [AlexeyAB/darknet#5374]
how to deal this bug

**Comment by fhjjack** [comment]
同问

**Comment by LoryMANG** [comment]
Same problem

**Comment by AlexeyAB** [comment]
Show full screenshot of the error.

**Comment by LoryMANG** [comment]
> Show full screenshot of the error.

![image](https://user-images.githubusercontent.com/22808297/80489114-f3193480-8991-11ea-9026-ceb3f871e703.png)

**Comment by AlexeyAB** [comment]
* Or compile Darknet with `OPENCV=1`
* Or set `mosaic=0` in cfg-file, but the final accuracy will be 1-2% lower

**Comment by LoryMANG** [comment]
> * Or compile Darknet with `OPENCV=1`
> * Or set `mosaic=0` in cfg-file, but the final accuracy will be 1-2% lower

Thank u!
The second way worked!
Tomorrow i will try the first way.If it works,i will reply in this issue.

**Comment by LoryMANG** [comment]
The two ways both work!
Thank u very much!

**Comment by yqs666** [comment]
![image](https://user-images.githubusercontent.com/59189543/97383144-dc837400-1907-11eb-8487-58fd4445f7cf.png)

how to deal this bug
