### ISSUE TITLE
Yolo v3 vs Yolo v4, v4 slower, why?

### ISSUE THREAD

**Issue by LorenRd** [AlexeyAB/darknet#5387]
I did this quick test on the same image with Yolo v3 - 320 (width/height) and Yolo v4 with the same network size. The .cfg was edited following the repo instructions. I did a completed trainning on v3 with 15k steps and on v4 only 1000 to do this test.

Yolo v4 is 3ms slower than v3, and it loads more layers from .weights, why? Shouldn't it be faster?

![Yolo v3 vs v4](https://user-images.githubusercontent.com/11414362/80502234-a709c800-8970-11ea-8fb2-834da63f9a8e.png)

**Comment by AlexeyAB** [comment]
To get an increase in AP and FPS compared to Yolov3, use YOLOv4 with a slightly lower resolution than in Yolov3 - read: https://github.com/AlexeyAB/darknet/issues/5308

**Comment by LorenRd** [comment]
That's why, thanks @AlexeyAB 
![image](https://user-images.githubusercontent.com/11414362/80505623-d9b5bf80-8974-11ea-8201-a8dbfa3ee1ea.png)
