### ISSUE TITLE
yolov4  Training questions  nan nan nan nan nan

### ISSUE THREAD

**Issue by yzh1527** [AlexeyAB/darknet#5395]
It's normal at the beginning of training. After a while of training, the loss value suddenly increases, and then it's all Nan.  
According to the current check, there is no problem with the data set, and the learning rate is set to 0.001,who can help me?thanks
![image](https://user-images.githubusercontent.com/45789648/80555044-9fdeca80-8a01-11ea-98bf-b163825f4ac4.png)
![image](https://user-images.githubusercontent.com/45789648/80555062-b8e77b80-8a01-11ea-993d-7025882604a6.png)

**Comment by AlexeyAB** [comment]
What cfg-file do you use?
What training command do you use?

>  learning rate is set to 0.001

If you use 4x GPUs,  then use 4/ less `learning_rate=0.00025`

https://github.com/AlexeyAB/darknet#how-to-train-with-multi-gpu

**Comment by deep-practice** [comment]
still got nan using learning_rate=0.00025@AlexeyAB

**Comment by AlexeyAB** [comment]
@deep-practice 

> still got nan using learning_rate=0.0002

Show screenshot.
What dataset do you use?
What cfg-file do you use?
What training command do you use?

**Comment by samux87** [comment]
I have a similar issue when I train in a p2.xlarge with a modified COCO dataset

**Comment by AlexeyAB** [comment]
Did you follow? https://github.com/AlexeyAB/darknet#how-to-train-with-multi-gpu

**Comment by samux87** [comment]
I trained 1000 epochs on my pc and pushed everything on an ec2 instance. I think p2.xlarge is not a multi GPU instance anymore. 
Do I need to reduce the Learning rate due to the nan "issue" anyway?

**Comment by AlexeyAB** [comment]
>  with a modified COCO dataset

1. Did you check that your changes are correct?
2. What command do you use for training, which cfg and pre-trained weights do you use?
3. Do you follow manual and use https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4-custom.cfg ?
4. Try to train with 
* learning_rate=0.001 https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4-custom.cfg#L18
* max_delta=5 for **each** [yolo] layer https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4-custom.cfg#L1158
* also try to add `stopbackward=800` there https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4-custom.cfg#L744 or there https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4-custom.cfg#L947

**Comment by samux87** [comment]
1. yes
2. ./darknet detector train obj.data yolov4.cfg yolov4_1000.weights -map
3. I used yolov4.cfg, I will try with the custom one; thank you for the suggestion.
4. I will try this setting after a try with yolov4-custom.cfg; thank you again.

After having configured batch=32 and subdivisions=16, the training start but after a few iterations, NAN appears xD.

I also used a p3.2xlarge instance; same issue.

**Comment by AlexeyAB** [comment]
1. In the manual said that you should use yolov4-custom.cfg for your custom dataset

2. In the manual said that you should set batch=64. And if OOM error occurs, then increase subdivisions=16,32,64

3. What pre-trained weights file do you use initially?

**Comment by samux87** [comment]
yolov4.conv.137

**Comment by AlexeyAB** [comment]
I just fixed `yolov4-custom.cfg`, try to use it.

Change `batch=64 subdivisions=32` or 64/64 if OOM error occurs.

And train:
`./darknet detector train obj.data yolov4.cfg yolov4.conv.137 -map`

**Comment by samux87** [comment]
It works now, thank you @AlexeyAB !

**Comment by beizhengren** [comment]
@AlexeyAB 
In [build/darknet/x64/cfg/yolov4-custom.cfg](https://github.com/AlexeyAB/darknet/commit/6cbb75d10b43a95f11326a2475d64500b11fa64e)
`stopbackward=800`
In https://github.com/AlexeyAB/darknet/issues/4728#issuecomment-576233901 `stopbackward=1`
I think put stopbackward=1 before some layer meaning that all the layers' weights before current layer will not be updated.
https://github.com/AlexeyAB/darknet/issues/5253#issuecomment-615330068 `stopbackward=6000`
so, how to understand  `stopbackward=800` `stopbackward=6000`?
Thanks!

**Comment by AlexeyAB** [comment]
put stopbackward=800 before some layer meaning that all the layers' weights before current layer will not be updated only for the first 800 iterations.

**Comment by beizhengren** [comment]
@AlexeyAB 
Thanks!
So stopbackward=1 means that all the layers' weights before current layer will not be updated all the time ? In another words, only when stopbackward isn't 1, such as 2,  represent iterations?

**Comment by AlexeyAB** [comment]
@beizhengren Yes!

**Comment by beizhengren** [comment]
@AlexeyAB Thanks!

**Comment by Li505358678** [comment]
@AlexeyAB 
I trained detector on MS COCO (trainvalno5k 2014) dataset
I just did as [https://github.com/AlexeyAB/darknet/wiki/Train-Detector-on-MS-COCO-(trainvalno5k-2014)-dataset](url)

I followed it .all parameters in yolov4.cfg by default, except for width=512 height=512

Training command:
./darknet detector train cfg/coco.data cfg/yolov4.cfg csdarknet53-omega.conv.105

but NAN happened at 10000 iteration.I use 32G GPU
![image](https://user-images.githubusercontent.com/51314795/82726081-5ccbfa80-9d14-11ea-8184-e03ef2692448.png)

What's wrong with it?

**Comment by AlexeyAB** [comment]
@Li505358678 

> but NAN happened at 10000 iteration.

Show screenshot.

**Comment by Li505358678** [comment]
> @Li505358678
> 
> > but NAN happened at 10000 iteration.
> 
> Show screenshot.
> 
> And attach cfg-file.

![image](https://user-images.githubusercontent.com/51314795/82732215-75e9a100-9d3e-11ea-8f03-b1ed192bfe5f.png)
just like this .

chart.png,loss is always Greater than 10 .So it is a line
![image](https://user-images.githubusercontent.com/51314795/82732242-931e6f80-9d3e-11ea-8e75-72582e888f62.png)

cfg-file:
[net]
batch=64
subdivisions=8
# Training
width=512
height=512
#width=608
#height=608
channels=3
momentum=0.949
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.00261
burn_in=1000
max_batches = 500500
policy=steps
steps=400000,450000
scales=.1,.1

#cutmix=1
mosaic=1

#:104x104 54:52x52 85:26x26 104:13x13 for 416

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=mish

# Downsample

[convolutional]
batch_normalize=1
filters=64
size=3
stride=2
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=mish

[route]
layers = -2

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=32
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=mish

[route]
layers = -1,-7

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=mish

# Downsample

[convolutional]
batch_normalize=1
filters=128
size=3
stride=2
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=mish

[route]
layers = -2

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=mish

[route]
layers = -1,-10

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=mish

# Downsample

[convolutional]
batch_normalize=1
filters=256
size=3
stride=2
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=mish

[route]
layers = -2

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear


[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=mish

[route]
layers = -1,-28

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=mish

# Downsample

[convolutional]
batch_normalize=1
filters=512
size=3
stride=2
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=mish

[route]
layers = -2

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear


[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear


[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear


[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear


[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear


[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear


[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=mish

[route]
layers = -1,-28

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=mish

# Downsample

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=2
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=mish

[route]
layers = -2

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=mish

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=mish

[shortcut]
from=-3
activation=linear

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=mish

[route]
layers = -1,-16

[convolutional]
batch_normalize=1
filters=1024
size=1
stride=1
pad=1
activation=mish

##########################

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

### SPP ###
[maxpool]
stride=1
size=5

[route]
layers=-2

[maxpool]
stride=1
size=9

[route]
layers=-4

[maxpool]
stride=1
size=13

[route]
layers=-1,-3,-5,-6
### End SPP ###

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[upsample]
stride=2

[route]
layers = 85

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[route]
layers = -1, -3

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=512
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=512
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[upsample]
stride=2

[route]
layers = 54

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[route]
layers = -1, -3

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=256
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=256
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

##########################

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=256
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=255
activation=linear


[yolo]
mask = 0,1,2
anchors = 12, 16, 19, 36, 40, 28, 36, 75, 76, 55, 72, 146, 142, 110, 192, 243, 459, 401
classes=80
num=9
jitter=.3
ignore_thresh = .7
truth_thresh = 1
scale_x_y = 1.2
iou_thresh=0.213
cls_normalizer=1.0
iou_normalizer=0.07
iou_loss=ciou
nms_kind=greedynms
beta_nms=0.6


[route]
layers = -4

[convolutional]
batch_normalize=1
size=3
stride=2
pad=1
filters=256
activation=leaky

[route]
layers = -1, -16

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=512
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=512
activation=leaky

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=512
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=255
activation=linear


[yolo]
mask = 3,4,5
anchors = 12, 16, 19, 36, 40, 28, 36, 75, 76, 55, 72, 146, 142, 110, 192, 243, 459, 401
classes=80
num=9
jitter=.3
ignore_thresh = .7
truth_thresh = 1
scale_x_y = 1.1
iou_thresh=0.213
cls_normalizer=1.0
iou_normalizer=0.07
iou_loss=ciou
nms_kind=greedynms
beta_nms=0.6


[route]
layers = -4

[convolutional]
batch_normalize=1
size=3
stride=2
pad=1
filters=512
activation=leaky

[route]
layers = -1, -37

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=1024
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=255
activation=linear


[yolo]
mask = 6,7,8
anchors = 12, 16, 19, 36, 40, 28, 36, 75, 76, 55, 72, 146, 142, 110, 192, 243, 459, 401
classes=80
num=9
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1
scale_x_y = 1.05
iou_thresh=0.213
cls_normalizer=1.0
iou_normalizer=0.07
iou_loss=ciou
nms_kind=greedynms
beta_nms=0.6

**Comment by AlexeyAB** [comment]
@Li505358678 

* What date of Darknet do you use?
* Try to use the latest version of Darknet.
* Were there generated bad.list or bad_label.list files?

**Comment by Li505358678** [comment]
> @Li505358678
> 
> * What date of Darknet do you use?
> * Try to use the latest version of Darknet.
> * Were there generated bad.list or bad_label.list files?

1.   5.13，There should be no problem with the code. Have you modified it recently?
2.   every label I download from the internet on the links like trainvalno5k.txt[.just](https://pjreddie.com/media/files/coco/trainvalno5k.part)

**Comment by Li505358678** [comment]
https://pjreddie.com/media/files/coco/trainvalno5k.part

**Comment by AlexeyAB** [comment]
@Li505358678 I fixed yolov4.cfg for stable training without Nan, it will have almost the same AP: https://github.com/AlexeyAB/darknet/commit/c0d6b81a78e204c04c9bf4277974e0dadad0c4e2 

change `width=512 height=512` and train: https://raw.githubusercontent.com/AlexeyAB/darknet/c0d6b81a78e204c04c9bf4277974e0dadad0c4e2/cfg/yolov4.cfg

**Comment by Li505358678** [comment]
I will try.What's mean about have almost the same AP?the AP will not decrease and bad?

**Comment by Li505358678** [comment]
Increase instead of decrease

**Comment by AlexeyAB** [comment]
Accuracy will be the same.

**Comment by Li505358678** [comment]
> 准确性是一样的。

Thanks!I will try it.

**Comment by Li505358678** [comment]
> Accuracy will be the same.

@AlexeyAB 

I have another question. 
Why yolov4.cfg need to change width=512 height=512 with csdarknet53-omega.conv.105 . 
But train with yolov4.conv.137 need to change width=608 height=608

I want to get a model just like yolov4(yolov4.conv.137),Will this training lead to a different model from yolov4?

if I want is a model close to yolov4, including the configuration of the cfg file. What should I do?

**Comment by AlexeyAB** [comment]
> Why yolov4.cfg need to change width=512 height=512 with csdarknet53-omega.conv.105 

Just if you want to reproduce our results from the paper. 


> But train with yolov4.conv.137 need to change width=608 height=608

`yolov4.conv.137` is already trained on MSCOCO, so you should use only for custom object training, so you can use any width and height that are multiple of 32.


> I want to get a model just like yolov4(yolov4.conv.137),Will this training lead to a different model from yolov4?
> if I want is a model close to yolov4, including the configuration of the cfg file. What should I do?

I don't understand. Do you want to check our results from paper, or do you want to train your different model on MSCOCO, or do you want to train your own model for your custom objects, ...?

**Comment by Li505358678** [comment]
> > Why yolov4.cfg need to change width=512 height=512 with csdarknet53-omega.conv.105
> 
> Just if you want to reproduce our results from the paper.
> 
> > But train with yolov4.conv.137 need to change width=608 height=608
> 
> `yolov4.conv.137` is already trained on MSCOCO, so you should use only for custom object training, so you can use any width and height that are multiple of 32.
> 
> > I want to get a model just like yolov4(yolov4.conv.137),Will this training lead to a different model from yolov4? if I want is a model close to yolov4, including the configuration of the cfg file. What should I do?
> 
> I don't understand. Do you want to check our results from paper, or do you want to train your different model on MSCOCO, or do you want to train your own model for your custom objects, ...?

 I want to reproduce your results from the paper.I want to get the same model as yolov4.conv.137.

Now the question is, if I follow the [ https://github.com/AlexeyAB/darknet/wiki/Train-Detector-on-MS-COCO-(trainvalno5k-2014)-dataset](url). Can I get the model close to yolov4.conv.137?

The reason why I have this problem is that the height and width in the cfg-file must be set to 512 during training, but if I directly use yolov4.conv.137 for custom object training or evaluating MSCOCO, I can use any width and height that are multiple of 32. If I train according to the above link(just train on MSCOCO), can the resulting model also be used to evaluate by using any width and height that are multiple of 32

**Comment by AlexeyAB** [comment]
> Now the question is, if I follow the https://github.com/AlexeyAB/darknet/wiki/Train-Detector-on-MS-COCO-(trainvalno5k-2014)-dataset. Can I get the model close to yolov4.conv.137?

Yes.
You will get `yolov4_final.weights` then you can do
`./darknet partial cfg/yolov4.cfg backup/yolov4_final.weights yolov4.conv.137 137`
to save weights of only the first 137 layers into file `yolov4.conv.137`

> The reason why I have this problem is that the height and width in the cfg-file must be set to 512 during training, but if I directly use yolov4.conv.137 for custom object training or evaluating MSCOCO, I can use any width and height that are multiple of 32.

To reproduce paper results:
* you should use 512x512 for Training
* any resolution (multiple of 32) for Detection/Evaluation

**Comment by Li505358678** [comment]
> @Li505358678 I fixed yolov4.cfg for stable training without Nan, it will have almost the same AP: [c0d6b81](https://github.com/AlexeyAB/darknet/commit/c0d6b81a78e204c04c9bf4277974e0dadad0c4e2)
> 
> change `width=512 height=512` and train: https://raw.githubusercontent.com/AlexeyAB/darknet/c0d6b81a78e204c04c9bf4277974e0dadad0c4e2/cfg/yolov4.cfg

for the new code ?If I want to train with multi-GPU on MS COCO.Do I need to change the learning_rate and burn_in of the yolov4.cfg

**Comment by Li505358678** [comment]
> @Li505358678 I fixed yolov4.cfg for stable training without Nan, it will have almost the same AP: [c0d6b81](https://github.com/AlexeyAB/darknet/commit/c0d6b81a78e204c04c9bf4277974e0dadad0c4e2)
> 
> change `width=512 height=512` and train: https://raw.githubusercontent.com/AlexeyAB/darknet/c0d6b81a78e204c04c9bf4277974e0dadad0c4e2/cfg/yolov4.cfg

Training has been more than 10000 times, why the loss is still hundreds

**Comment by AlexeyAB** [comment]
> Training has been more than 10000 times, why the loss is still hundreds

Show chart.png
What command do you use?

> for the new code ?If I want to train with multi-GPU on MS COCO.Do I need to change the learning_rate and burn_in of the yolov4.cfg

I would recommend to use for 4xGPUs 
`batch=16 subdivisios=2 max_batches=2000000 steps=1600000, 1800000`

**Comment by Li505358678** [comment]
> > Training has been more than 10000 times, why the loss is still hundreds
> 
> Show chart.png
> What command do you use?
> 
> > for the new code ?If I want to train with multi-GPU on MS COCO.Do I need to change the learning_rate and burn_in of the yolov4.cfg
> 
> I would recommend to use for 4xGPUs
> `batch=16 subdivisios=2 max_batches=2000000 steps=1600000, 1800000`

the chart.png just can see a line on the top

command:./darknet detector train cfg/coco.data cfg/yolov4.cfg csdarknet53-omega.conv.105

just train on MSCOCO follow [https://github.com/AlexeyAB/darknet/wiki/Train-Detector-on-MS-COCO-(trainvalno5k-2014)-dataset](url)

If I just have 1GPU. What should I do?

**Comment by AlexeyAB** [comment]
> just train on MSCOCO follow https://github.com/AlexeyAB/darknet/wiki/Train-Detector-on-MS-COCO-(trainvalno5k-2014)-dataset
> 
> If I just have 1GPU. What should I do?

Just follow: https://github.com/AlexeyAB/darknet/wiki/Train-Detector-on-MS-COCO-(trainvalno5k-2014)-dataset

**Comment by Li505358678** [comment]
> > just train on MSCOCO follow https://github.com/AlexeyAB/darknet/wiki/Train-Detector-on-MS-COCO-(trainvalno5k-2014)-dataset
> > If I just have 1GPU. What should I do?
> 
> Just follow: https://github.com/AlexeyAB/darknet/wiki/Train-Detector-on-MS-COCO-(trainvalno5k-2014)-dataset

Yes.I follow it . and after 10000 times. the loss was also high that over 100. is this normal?

**Comment by Li505358678** [comment]
![image](https://user-images.githubusercontent.com/51314795/83275010-26edb100-a201-11ea-983e-4da41ca07147.png)
![image](https://user-images.githubusercontent.com/51314795/83275005-23f2c080-a201-11ea-9d38-73b3e862c6bb.png)

I I stopped halfway. Before, due to my carelessness, I didn't decompress the label, but only two txts. The loss of training was normally reduced. I found the error, and then I followed get_ coco_ dataset.sh I did it once again, but now the training loss has been very high

**Comment by AlexeyAB** [comment]
* Check you dataset - run training with flag `-show_imgs` do you see correct bboxes?

* Run training from the begining.

**Comment by Li505358678** [comment]
![image](https://user-images.githubusercontent.com/51314795/83276663-88168400-a203-11ea-9ef2-0dd0a37249b0.png)
![image](https://user-images.githubusercontent.com/51314795/83276692-9795cd00-a203-11ea-8a77-0a983dad7908.png)

the bboxes looks good.

Run training from the begining can work?I will try next time .Because of time. Now I train with custom data. loss looks good. 

I wonder why this happens. When I didn't unzip the label of coco, I only had two txt files. Why can I also achieve a good loss
