### ISSUE TITLE
Low FPS issue in yolo-v4 windows

### ISSUE THREAD

**Issue by parthphoenix** [AlexeyAB/darknet#5399]
Hi, 
@AlexeyAB 
Everyone, 

I'm facing an issue with the low FPS while running this snippet:
`darknet.exe detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights test.mp4 -dont_show -ext_output`

FYI: Following are the steps I followed:
- build your repository with VS19 with all the requirements.
-- Windows 10 with i7 x64 based
-- Added opencv libraries in project property
-- Added Cuda path in project property
-- And build with release x64
- downloaded yolo4.weights from your repository
- Run the upper snippet. All I get is, **6.8FPS**, **6.6AvgFPS**

Same is running perfect with expected FPS in Yolo-v3.

For the inference I have, _GPU: 1080Ti 1660Ti_

Any help would be appreciated.

**Comment by AlexeyAB** [comment]
What resolution of your video test.mp4?
Did you try to run with flag `-i 0` and `-i 1` ?
Show such screenshot when you run on 1080Ti:
![image](https://user-images.githubusercontent.com/4096485/80588996-070c7700-8a22-11ea-85d8-11a9be94bcb6.png)

**Comment by parthphoenix** [comment]
- Resolution is 640x360.
- I have checked with 0th GPU.
PFA for screenshot.
![issue](https://user-images.githubusercontent.com/64201651/80592335-e867a980-8a3c-11ea-9742-a9fe12149fd7.PNG)

**Comment by AlexeyAB** [comment]
Try to compile with `CUDNN_HALF=0`

**Comment by parthphoenix** [comment]
It's increase to **19.5 Fps**. But not getting required.

**Comment by AlexeyAB** [comment]
Do you get 19.5 FPS for `-i 0` ?
How many FPS do you get with `-i 1` ?

**Comment by parthphoenix** [comment]
19.5 FPS with -i 0.
28.2 FPS with -i 1.

**Comment by AlexeyAB** [comment]
For yolov4.cfg with `width=608 height=608` in cfg-file:

* 1660 Ti - 19.5 FPS with -i 0
* 1080 Ti - 28.2 FPS with -i 1.
* RTX 2070 - 34 FPS
* Telsa V100 - 62 FPS

![modern_gpus](https://user-images.githubusercontent.com/4096485/80601147-18f81500-8a36-11ea-8b01-9705dcc87a7b.png)

**Comment by parth-sankhavara** [comment]
Thanks Alexey for your guidance.
