### ISSUE TITLE
yolo_console.dll

### ISSUE THREAD

**Issue by apiszcz** [AlexeyAB/darknet#54]
I am getting the following BUILD ERROR:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file 'x64\yolo_cpp_dll.lib'	yolo_console_dll	C:\g\darknet\build\darknet\LINK	1	
```

**Comment by AlexeyAB** [comment]
At first you should compile DLL - this will create 'x64\yolo_cpp_dll.lib': https://github.com/AlexeyAB/darknet#how-to-use-yolo-as-dll

> To compile Yolo as C++ DLL-file yolo_cpp_dll.dll - open in MSVS2015 file build\darknet\yolo_cpp_dll.sln, set x64 and Release, and do the: Build -> Build yolo_cpp_dll

* Did you this?
* Where do you find `yolo_cpp_dll.lib` after this?

**Comment by apiszcz** [comment]
​I followed your steps. however I'm getting LNK1181
I'll recheck my paths

​Severity Code Description Project File Line Suppression State
Error LNK1181 cannot open input file 'x64\yolo_cpp_dll.lib' yolo_console_dll
C:\g\darknet\build\darknet\LINK 1

**Comment by apiszcz** [comment]
My error one of the paths not set correctly, yolo_cpp_dll and yolo_console_dll build correctly.
