### ISSUE TITLE
cMake issues on half-precision & OpenCV re-build

### ISSUE THREAD

**Issue by awaisbajwaml** [AlexeyAB/darknet#5402]
I found an error below on half-precision on CMake  after I installed OpenCV via SUDO APT-GET INSTALL LIBOPENCV-DEV
And then updated the MakeFile with OpenCV=1 but why it is asking me to rebuild OpenCV from the source.

######-- Your setup does not support half-precision (it requires CC >= 7.5)
-

**Comment by AlexeyAB** [comment]
I fixed it.

Try to build the latest Darknet version from scratch.

**Comment by awaisbajwaml** [comment]
@AlexeyAB 

Great - yes it worked for me after the re-build. Closing this
