### ISSUE TITLE
spp in yolov4

### ISSUE THREAD

**Issue by liguoyu666** [AlexeyAB/darknet#5403]
![spp](https://user-images.githubusercontent.com/47743761/80572810-79388800-8a31-11ea-8dcd-d1888c6cd2f0.png)

But in my calculation，After maxpool, the featuer map size are  

![teset](https://user-images.githubusercontent.com/47743761/80572786-6faf2000-8a31-11ea-8fb5-ac61b2f4f9e5.png)

Where did I miscalculate ？

**Comment by WongKinYiu** [comment]
for maxpoll with kernel size 5/9/13, the padding value should be 2/4/6, respectively.

**Comment by liguoyu666** [comment]
> for maxpoll with kernel size 5/9/13, the padding value should be 2/4/6, respectively.

Thank you, But there is no padding in the code

`### SPP ###
[maxpool]
stride=1
size=5

[route]
layers=-2

[maxpool]
stride=1
size=9

[route]
layers=-4

[maxpool]
stride=1
size=13

[route]
layers=-1,-3,-5,-6
### End SPP ###`

**Comment by WongKinYiu** [comment]
The default setting of darknet and pytorch are different.
https://github.com/AlexeyAB/darknet/blob/master/src/parser.c#L761

**Comment by liguoyu666** [comment]
> The default setting of darknet and pytorch are different.
> https://github.com/AlexeyAB/darknet/blob/master/src/parser.c#L761

Thank you very much
