### ISSUE TITLE
Would all yolov4 augmentation tricks be used on yolov3?

### ISSUE THREAD

**Issue by kame-lqm** [AlexeyAB/darknet#5422]
Weakly ask one question, would all yolov4 augmentation tricks be used on yolov3 training? Like Mosaic, etc? Thanks.

**Comment by WongKinYiu** [comment]
Yes, all of tricks can be applied on YOLOv3.

**Comment by kame-lqm** [comment]
> Yes, all of tricks can be applied on YOLOv3.

It sounds great! Thanks so much. 
BTW, do you know how to used those tricks on yolov3.cfg? Just like to add code "mosaic=1" in yolov3.cfg?

**Comment by WongKinYiu** [comment]
which tricks you would like to use on yolov3?

**Comment by kame-lqm** [comment]
> which tricks you would like to use on yolov3?
> 
> if you only want to use mosaic, yes.

For instance, like "mosaic=1", "activation=mish", "nms_kind=greedynms", or "iou_loss=ciou".  I hope they can all be used on yolov3.

**Comment by WongKinYiu** [comment]
1. add `mosaic=1` in `[net]` block
2. replace all `leaky` to `mish`
3. copy all content of `[yolo]` block (please notice the mask of yolov3 and yolov4 are reverse order)

**Comment by kame-lqm** [comment]
> 1. add `mosaic=1` in `[net]` block
> 2. replace all `leaky` to `mish`
> 3. copy all content of `[yolo]` block (please notice the mask of yolov3 and yolov4 are reverse order)

Got it. Thanks so much!
