### ISSUE TITLE
Video-stream stopped!

### ISSUE THREAD

**Issue by LoryMANG** [AlexeyAB/darknet#5425]
When i use my own trained model to run the video, it keep outputing "Video-stream stopped!" and do nothing.
My command is : ./darknet detector demo cfg/voc.data cfg/yolo-obj.cfg backup/yolo-obj_final.weights test.mp4 -out_filename res.avi
Is there any way to solve the problem?

**Comment by lsd1994** [comment]
Video isn't exist or has wrong path.

**Comment by ANewAnonymous** [comment]
> When i use my own trained model to run the video, it keep outputing "Video-stream stopped!" and do nothing.
> My command is : ./darknet detector demo cfg/voc.data cfg/yolo-obj.cfg backup/yolo-obj_final.weights test.mp4 -out_filename res.avi
> Is there any way to solve the problem?

Did you set opencv = 1 when compiling darknet? If you set it, please check if you successfully installed ffmpeg when compiling opencv

**Comment by LoryMANG** [comment]
> > When i use my own trained model to run the video, it keep outputing "Video-stream stopped!" and do nothing.
> > My command is : ./darknet detector demo cfg/voc.data cfg/yolo-obj.cfg backup/yolo-obj_final.weights test.mp4 -out_filename res.avi
> > Is there any way to solve the problem?
> 
> Did you set opencv = 1 when compiling darknet? If you set it, please check if you successfully installed ffmpeg when compiling opencv

Thank you for solving my problem! I didnt compile opencv just install it with dnf.Now i compile it with ffmpeg,the issue is solved.
