### ISSUE TITLE
Darknet slower using cuDNN 8.0.0 / CUDA 10.2 than cuDNN 7.6.3 / CUDA 10.0 on Jetson

### ISSUE THREAD

**Issue by tdurand** [AlexeyAB/darknet#5426]
Hi @AlexeyAB 

Once again amazing work on darknet, congratulation for Yolov4 release !!  I know you have lots of people opening issue, and I am one of them, so I will be straight to the point.. 

### Problem

When I use darknet and yolov3-tiny on my jetson nano with the latest Jetpack 4.4 DP I get worse performance than with Jetpack 4.3

It seems that using the CUDNN flag makes things worse... With jetpack 4.4 I get 6.6 FPS whereas I have 16 FPS with jetpack 4.3 .

What do you think ? Maybe cuDNN 8.0 has changes and darknet isn't compatible with it.. just let me know. This problem is maybe not related to your code and directly to cuDNN in this case I will post directly on the nvidia developer forum, just let me know

Thanks

#### jetpack 4.4 (cuDNN: 8.0.0 CUDA 10.2) with CUDNN=1 flag:

darknet build with:

```
GPU=1
CUDNN=1
OPENCV=1
ARCH= -gencode arch=compute_53,code=[sm_53,compute_53]
```

result for yolov3-tiny `./darknet detector demo cfg/coco.data cfg/yolov3-tiny.cfg yolov3-tiny.weights <videoinput>`

```
CUDA-version: 10020 (10020), cuDNN: 8.0.0, GPU count: 1  
OpenCV version: 4.1.1

FPS:6.3
```

#### cuDNN: 8.0.0 CUDA 10.2 with CUDNN=0 flag (jetpack 4.4):

darknet build with:

```
GPU=1
CUDNN=0
OPENCV=1
ARCH= -gencode arch=compute_53,code=[sm_53,compute_53]
```

result for yolov3-tiny `./darknet detector demo cfg/coco.data cfg/yolov3-tiny.cfg yolov3-tiny.weights <videoinput>`

```
CUDA-version: 10020 (10020), GPU count: 1  
OpenCV version: 4.1.1

FPS:13.3
```

#### cuDNN: 7.6.3 CUDA 10 with CUDNN=1 flag (jetpack 4.4):

```
GPU=1
CUDNN=1
OPENCV=1
ARCH= -gencode arch=compute_53,code=[sm_53,compute_53]
```

result for yolov3-tiny `./darknet detector demo cfg/coco.data cfg/yolov3-tiny.cfg yolov3-tiny.weights <videoinput>`

```
CUDA-version: 10000 (10000), cuDNN: 7.6.3, GPU count: 1  
 OpenCV version: 4.1.1

 FPS:16.4
```

#### cuDNN: 7.6.3 CUDA 10 with CUDNN=0 flag (jetpack 4.3):

```
GPU=1
CUDNN=0
OPENCV=1
ARCH= -gencode arch=compute_53,code=[sm_53,compute_53]
```

result for yolov3-tiny `./darknet detector demo cfg/coco.data cfg/yolov3-tiny.cfg yolov3-tiny.weights <videoinput>`

```
CUDA-version: 10000 (10000), cuDNN: 7.6.3, GPU count: 1  
 OpenCV version: 4.1.1

FPS:13.3
```

**Comment by AlexeyAB** [comment]
> FPS:13.3

is it FPS or AVG FPS?
What Jetson version do you use, Nano, TX, TX2, Xavier?
Do you use the latest version of Darknet?
Try to run `./darknet detector demo ... -benchmark` what FPS you will get?

**Comment by tdurand** [comment]
- Yes it is AVG FPS , I copied the FPS but AVG FPS was the same, I waited a few seconds
- Jetson nano
- Yes latest master
- Doing that right now

**Comment by tdurand** [comment]
I get the same results with benchmark

**Comment by tdurand** [comment]
But this might be a bug with cuDNN, Jetpack 4.4 is still in Developer Preview and not stable...

**Comment by AlexeyAB** [comment]
It seems that cuDNN 8.0 and Jetpack 4.4 isn't released. So there are problems in them, wait for their release.

**Comment by tdurand** [comment]
Yes, you are right, I've reported the bug on the nvidia forums : https://forums.developer.nvidia.com/t/darknet-slower-using-jetpack-4-4-cudnn-8-0-0-cuda-10-2-than-jetpack-4-3-cudnn-7-6-3-cuda-10-0/121579 , must be on their end.

Will keep you updated ! Thanks again !

**Comment by aluds123** [comment]
Hi, @tdurand 
Is the problem solved?
It still slower than before. 
Thank you.

**Comment by athulvingt** [comment]
@tdurand, its been 1 year, can you give me an updated on this?
is the problem solved?
