### ISSUE TITLE
Cuda error: out of memory

### ISSUE THREAD

**Issue by abeyang00** [AlexeyAB/darknet#543]
I have succesfully trained with VOC data and now i;m trying to train yolo v3 with my own data.
I'm using 1280x960 sized image and changed yolov3.cfg file (# of filters in conv layer that comes before yolo layer and # of classes in yolo layer, and set batch = 64 and subdivisions = 8) and also changed voc.names and voc.data accordingly.

But after going into 30secs, i get a cuda error saying its out of memory.
I'm using 1080ti for gpu. 

Any ideas?

**Comment by AlexeyAB** [comment]
* Increase `subdivision` or set `random=0`
* Did you change filters and classes in the 3 yolo-layers?

**Comment by abeyang00** [comment]
Whats random?

**Comment by AlexeyAB** [comment]
params in you cfg-file.
