### ISSUE TITLE
Will LSTM on top of PAN increase mAP?

### ISSUE THREAD

**Issue by utkutpcgl** [AlexeyAB/darknet#5441]
From the comparison of different models [https://github.com/AlexeyAB/darknet/issues/3114], I understand that adding LSTM on top of PAN does not increase the mAP a lot. Is that the answer to my question?

**Comment by AlexeyAB** [comment]
Yes, just about `+10` - `+20` AP50 for the bad dataset, and may be twice more for the good dataset.

**Comment by utkutpcgl** [comment]
Thanks for the fast response. What is your guess for "yolo_v3_spp_pan_lstm" 's mAP, compared to "yolo_v3_tiny_pan3"? I guess there won't be much improvement.

Also, do you know why yolov4 does not inherit LSTMs? Is it due to PAN?

**Comment by asagotra** [comment]
Hi @utkutpcgl Could you send me the yolo_v3_spp_pan_lstm.cfg file? I haven't found anywhere

**Comment by asagotra** [comment]
Hi @utkutpcgl Could you send me the yolo_v3_spp_pan_lstm.cfg file? I haven't found anywhere

**Comment by asagotra** [comment]
Hi @utkutpcgl Could you send me the yolo_v3_spp_pan_lstm.cfg file? I haven't found anywhere

**Comment by utkutpcgl** [comment]
It was not available at the time I sent the message. I just was curious about it. Sorry...
