### ISSUE TITLE
Multi-GPU Test Support

### ISSUE THREAD

**Issue by Neel1302** [AlexeyAB/darknet#5444]
Hi @AlexeyAB,

Thanks a lot for your valueable work. I am wondering if you can add features for multi-GPU support for test time support, i.e. inference, (training with multi-GPU works). I have tested this and confirmed that multiple GPUs are not used when doing inference.

![Screenshot from 2020-05-01 12-56-04](https://user-images.githubusercontent.com/8161543/80824204-f556db00-8bab-11ea-8fc2-fff580fae3f8.jpg)

This would be a great feature and is much needed for practical applicability of the method.

Thanks!

**Comment by AlexeyAB** [comment]
Try to use such command and you will get **about ~60 FPS** on Tesla V100 / Titan V / Titan RTX / RTX 2080 Ti
`./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights test.mp4 -dont_show -ext_output  -json_port 8070 -mjpeg_port 8090`

You can run each video stream on a separate GPU (GPU-0 and GPU-1):
1. `./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights test.mp4 -dont_show -ext_output -json_port 8070 -mjpeg_port 8090 -i 0`

2. `./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights test.mp4 -dont_show -ext_output -json_port 8071 -mjpeg_port 8091 -i 1`

....

You can see the results by using Chrome/Firefox web-browers:
1. http://localhost:8070/ and http://localhost:8090/
2. http://localhost:8071/ and http://localhost:8091/

Do you mean that 60 FPS for one video stream is not enough?

**Comment by Neel1302** [comment]
Hi @AlexeyAB,

Thanks for the prompt reply!

Yes, indeed, the -i arg worked as suggested, I confirm. 

I tested on three video streams and ran two on GPU 0 and one on GPU 1 (reason being - GPU 1 is used for system graphics). I guess since inference cannot be done utilizing both of the GPUs together as a single GPU, i.e. even out the load on the 2 GPUs as a whole, it may not be possible to get about the same fps on all streams (for example if on 1 GPU I can get 60 fps, then on 2 GPUs of the same kind it is not possible to evenly get 40 fps on each video stream - instead it would be something like 60, 30, 30). Correct me if I am wrong.

![Screenshot from 2020-05-02 16-18-35](https://user-images.githubusercontent.com/8161543/80891269-f150b900-8c90-11ea-81ec-62f9ebffd50a.jpg)

Oh and yes on the GPU with one stream I do indeed get > 65 FPS consistently.

Thanks again for your help.
Neel

**Comment by Snickbrack** [comment]
@AlexeyAB can the `-i 0` Part also be used for Images to specify which GPU should be used for testing?
