### ISSUE TITLE
C++ yolo_v2_class not speeding up with yolo v4

### ISSUE THREAD

**Issue by Siset** [AlexeyAB/darknet#5472]
Hi @AlexeyAB ,

Awesome work providing us with all the darknet framework! It is deeply appreciate it!

I use an old yolo version in my C++ program (using the yolo_cpp_dll as described) and I am upgrading it because I would like to benefit from both speed and accuracy.

From the accuracy point of view we improve greatly from a 42% IoU to a 48% IoU!! (I only have one class)

But from speed I do not see any improvement at all. I have two machines one with tensor cores (RTX 2060) and another one without them (GTX 1080 Ti). I use the following code:
```
	Detector detector = new Detector("yolo-obj-old.cfg", "yolo-obj_4200.weights"); //old yolo version
        //Detector detector = new Detector("yolo-obj.cfg", "yolo-obj_4000.weights"); //yolo v4
        auto t0 = std::chrono::high_resolution_clock::now();
	result = detector->detect(img); //img is cv::Mat 
	auto t1 = std::chrono::high_resolution_clock::now();
	auto internalD = std::chrono::duration_cast<std::chrono::microseconds>(t1 - t0).count();
	std::cout << "duration detect " << internalD<<std::endl;
```

USING THE RTX2060 on the old model:

```
 Used GPU 0
 compute_capability = 750, cudnn_half = 1
net.optimized_memory = 0
mini_batch = 1, batch = 64, time_steps = 1, train = 0
   layer   filters  size/strd(dil)      input                output
   0 conv     32       3 x 3/ 1    832 x 832 x   3 ->  832 x 832 x  32 1.196 BF
   1 conv     64       3 x 3/ 2    832 x 832 x  32 ->  416 x 416 x  64 6.380 BF
  ...
 105 conv     18       1 x 1/ 1    208 x 208 x 256 ->  208 x 208 x  18 0.399 BF
 106 yolo
[yolo] params: iou loss: mse (2), iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
Total BFLOPS 324.958
avg_outputs = 2530666
 Allocate additional workspace_size = 67.53 MB
Loading weights from yolo-obj_4200.weights...
 seen 64, trained: 268 K-images (4 Kilo-batches_64)
Done! Loaded 107 layers from weights-file

 try to allocate additional workspace_size = 67.53 MB
 CUDA allocate done!
 duration detect 67379
duration detect 67884
duration detect 69720

```

Using RTX 2060 on the new yolo v4:
```
 Used GPU 0
 compute_capability = 750, cudnn_half = 1
net.optimized_memory = 0
mini_batch = 1, batch = 64, time_steps = 1, train = 0
   layer   filters  size/strd(dil)      input                output
   0 conv     32       3 x 3/ 1    832 x 832 x   3 ->  832 x 832 x  32 1.196 BF
   1 conv     64       3 x 3/ 2    832 x 832 x  32 ->  416 x 416 x  64 6.380 BF
 ...
 158 conv    512       1 x 1/ 1     26 x  26 x1024 ->   26 x  26 x 512 0.709 BF
 159 conv   1024       3 x 3/ 1     26 x  26 x 512 ->   26 x  26 x1024 6.380 BF
 160 conv     18       1 x 1/ 1     26 x  26 x1024 ->   26 x  26 x  18 0.025 BF
 161 yolo
[yolo] params: iou loss: ciou (4), iou_norm: 0.07, cls_norm: 1.00, scale_x_y: 1.05
nms_kind: greedynms (1), beta = 0.600000
Total BFLOPS 238.252
avg_outputs = 1959114
 Allocate additional workspace_size = 67.53 MB
Loading weights from yolo-obj_4000.weights...
 seen 64, trained: 256 K-images (4 Kilo-batches_64)
Done! Loaded 162 layers from weights-file
 try to allocate additional workspace_size = 67.53 MB
 CUDA allocate done!
duration detect 67717
duration detect 65842
duration detect 65869

```
Using the GTX 1080 Ti on the new model:
```
Used GPU 0
 compute_capability = 610, cudnn_half = 0
net.optimized_memory = 0
mini_batch = 1, batch = 64, time_steps = 1, train = 0
   layer   filters  size/strd(dil)      input                output
   0 conv     32       3 x 3/ 1    832 x 832 x   3 ->  832 x 832 x  32 1.196 BF
   1 conv     64       3 x 3/ 2    832 x 832 x  32 ->  416 x 416 x  64 6.380 BF
  ...
 158 conv    512       1 x 1/ 1     26 x  26 x1024 ->   26 x  26 x 512 0.709 BF
 159 conv   1024       3 x 3/ 1     26 x  26 x 512 ->   26 x  26 x1024 6.380 BF
 160 conv     18       1 x 1/ 1     26 x  26 x1024 ->   26 x  26 x  18 0.025 BF
 161 yolo
[yolo] params: iou loss: ciou (4), iou_norm: 0.07, cls_norm: 1.00, scale_x_y: 1.05
nms_kind: greedynms (1), beta = 0.600000
Total BFLOPS 238.252
avg_outputs = 1959114
 Allocate additional workspace_size = 52.43 MB
Loading weights from yolo-obj_4000.weights...
 seen 64, trained: 256 K-images (4 Kilo-batches_64)
Done! Loaded 162 layers from weights-file
 try to allocate additional workspace_size = 52.43 MB
 CUDA allocate done!
duration detect 65249
duration detect 62183
duration detect 67435

```

I am using the yolo_v2_class.hpp, which might not be using the upgrades of yolo v4? The file is the one in darknet/include/yolo_v2_class.hpp. Should I use something different?

I do not know if it is relevant but I have to train in the GTX 1080 Ti (no tensor flow and in fact no cudnn_half) , because the other one gets too hot. 

If you require extra information / extra testing let me know and I will answer immediately.

Thanks in advanced,

**Comment by LukeAI** [comment]
@Siset  I don't have an answer to your question, but I was hoping you might be able to help me... could you show me how you link your c++ program to Darknet? Are you on windows or linux? do you use the ".so"? i've been trying (and failing) to do this on linux with CMakeLists :/

**Comment by Siset** [comment]
@LukeAI Hi, 

First of all, I am far from being an expert but I will try my best.

I am using windows! I compiled the yolo_cpp_dll.sln with the release and everything just as described. 
Then I copied the "yolo files" next to my c++ program.
Yolo Files are (most of them are created in the x64 folder):
yolo_cpp_dll.dll
pthreadGC2.dll
pthreadVC2.dll
yolo_cpp_dll.lib
yolo_v2_class.hpp (this one is find in darknet/include/)
yolo-obj.cfg / yolo-obj.weights / obj.data / obj.names (or whatever you need to run your darknet instance I guess)

And my c++ code:

```
#include "yolo_v2_class.hpp"
#pragma comment(lib,"yolo_cpp_dll.lib")
void main(){
        Detector detector = new Detector("yolo-obj-old.cfg", "yolo-obj_4200.weights"); //old yolo version
        //Detector detector = new Detector("yolo-obj.cfg", "yolo-obj_4000.weights"); //yolo v4
        auto t0 = std::chrono::high_resolution_clock::now();
	result = detector->detect(img); //img is cv::Mat 
	auto t1 = std::chrono::high_resolution_clock::now();
	auto internalD = std::chrono::duration_cast<std::chrono::microseconds>(t1 - t0).count();
	std::cout << "duration detect " << internalD<<std::endl;
}
```

**Comment by Siset** [comment]
Hi @AlexeyAB , 

Any insight on this problem?

Thanks in advanced,

**Comment by AlexeyAB** [comment]
> But from speed I do not see any improvement at all. 

Acceleration of what in comparison with what?

**Comment by Siset** [comment]
Hi @AlexeyAB ,

Thanks for the answer and the great repository. 

It takes the same time to execute the detect function (using yolo_v2_class and DLL) with and without tensor cores. Or are they unused in c++ detect function?

I do not know if it is relevant but I have trained my model in a GTX 1080 Ti (no tensor cores thus, no cudnn_half). Would it be different if I trained using tensor cores in another graphic card?

Thanks,

**Comment by AlexeyAB** [comment]
Show 2 screenshots of AVG FPS by using command `./darknet detector demo ... -dont_show` on RTX2060:

1. compiled with GPU=1 CUDNN=1 CUDNN_HALF=1
2. compiled with GPU=1 CUDNN=1 CUDNN_HALF=0

**Comment by Siset** [comment]
Hi! 
Thanks for the answer.

Frames are roughly the same:


<img width="891" alt="INITIAL_HALF0" src="https://user-images.githubusercontent.com/4293758/81311137-520f3580-9085-11ea-9d00-d30463073922.PNG">
<img width="189" alt="avg FPS HALF 1" src="https://user-images.githubusercontent.com/4293758/81311127-50457200-9085-11ea-8b9f-0f2d93e66b27.PNG">
<img width="896" alt="INITIAL_HALF1" src="https://user-images.githubusercontent.com/4293758/81311139-53d8f900-9085-11ea-8aba-17a252cdeb7c.PNG">
<img width="183" alt="avg FPS HALF 0" src="https://user-images.githubusercontent.com/4293758/81311141-54718f80-9085-11ea-9a62-df35f8614e7c.PNG">

Thanks in advanced,

**Comment by AlexeyAB** [comment]
Do you use Desktop-PC or Laptop?

I get on RTX 2070 Desktop:
* CUDNN_HALF=1: 33 FPS (608x608), 55 FPS (416x416)
* CUDNN_HALF=0: 26 FPS (608x608), 48 FPS (416x416)

**Comment by Siset** [comment]
Hi,

I use Desktop PC :
width=832
height=832


Thanks,

**Comment by ahsan856jalal** [comment]
> @LukeAI Hi,
> 
> First of all, I am far from being an expert but I will try my best.
> 
> I am using windows! I compiled the yolo_cpp_dll.sln with the release and everything just as described.
> Then I copied the "yolo files" next to my c++ program.
> Yolo Files are (most of them are created in the x64 folder):
> yolo_cpp_dll.dll
> pthreadGC2.dll
> pthreadVC2.dll
> yolo_cpp_dll.lib
> yolo_v2_class.hpp (this one is find in darknet/include/)
> yolo-obj.cfg / yolo-obj.weights / obj.data / obj.names (or whatever you need to run your darknet instance I guess)
> 
> And my c++ code:
> 
> ```
> #include "yolo_v2_class.hpp"
> #pragma comment(lib,"yolo_cpp_dll.lib")
> void main(){
>         Detector detector = new Detector("yolo-obj-old.cfg", "yolo-obj_4200.weights"); //old yolo version
>         //Detector detector = new Detector("yolo-obj.cfg", "yolo-obj_4000.weights"); //yolo v4
>         auto t0 = std::chrono::high_resolution_clock::now();
> 	result = detector->detect(img); //img is cv::Mat 
> 	auto t1 = std::chrono::high_resolution_clock::now();
> 	auto internalD = std::chrono::duration_cast<std::chrono::microseconds>(t1 - t0).count();
> 	std::cout << "duration detect " << internalD<<std::endl;
> }
> ```

@Siset  Can you plese refer me to the instruction page to compile yolo_cpp_dll.dll on visual studio 2019.

**Comment by Siset** [comment]
@ahsan856jalal https://github.com/AlexeyAB/darknet#how-to-use-yolo-as-dll-and-so-libraries
