### ISSUE TITLE
for calculating anchors 

### ISSUE THREAD

**Issue by shsur-27** [AlexeyAB/darknet#5473]
Hello, I am using kiiti dataset for training yolov3-tiny model.  But for calculating anchors i am getting error like 

OpenCV Error: Assertion failed (N >= K) in cv::kmeans 

how can i solve this error any idea ??
![Capture](https://user-images.githubusercontent.com/59499212/80948481-7d2e2680-8df2-11ea-99a3-036a43cda07f.PNG)

**Comment by readicculus** [comment]
your num_clusters(K) is larger or equal to the number of labels you have.  Even though it seems you have many images maybe you didnt create the .txt file labels that yolo expects?

**Comment by shsur-27** [comment]
> your num_clusters(K) is larger or equal to the number of labels you have(N). Even though it seems you have many images maybe you didnt create the .txt file labels that yolo expects?

@readicculus how can i create txt file labels that yolo expects

**Comment by AlexeyAB** [comment]
Use one of these tools: https://github.com/AlexeyAB/darknet#how-to-mark-bounded-boxes-of-objects-and-create-annotation-files

**Comment by shsur-27** [comment]
> Use one of these tools: https://github.com/AlexeyAB/darknet#how-to-mark-bounded-boxes-of-objects-and-create-annotation-files

hello @AlexeyAB  sir i still get this error after creating label file. here is my labelling file example 
[000000.txt](https://github.com/AlexeyAB/darknet/files/4593425/000000.txt)

**Comment by AlexeyAB** [comment]
You file is wrong. Use yolo-format for labeling:

**Comment by shsur-27** [comment]
> You file is wrong. Use yolo-format for labeling:

I already created around 7000 labels in this format. Do I need to change it for each file separately ??

**Comment by AlexeyAB** [comment]
> hello @AlexeyAB  sir i still get this error after creating label file. here is my labelling file example 
> [000000.txt](https://github.com/AlexeyAB/darknet/files/4593425/000000.txt)

> Pedestrian 0.00 0 -0.20 712.40 143.00 810.73 307.92 1.89 0.48 1.20 1.84 1.47 8.41 0.01

https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

> You should label each object on images from your dataset. Use this visual GUI-software for marking bounded boxes of objects and generating annotation files for Yolo v2 & v3: https://github.com/AlexeyAB/Yolo_mark
> 
> It will create .txt-file for each .jpg-image-file - in the same directory and with the same name, but with .txt-extension, and put to file: object number and object coordinates on this image, for each object in new line:
> 
> <object-class> <x_center> <y_center> <width> <height>
> 
> Where:
> 
> <object-class> - integer object number from 0 to (classes-1)
> <x_center> <y_center> <width> <height> - float values relative to width and height of image, it can be equal from (0.0 to 1.0]
> for example: <x> = <absolute_x> / <image_width> or <height> = <absolute_height> / <image_height>
> atention: <x_center> <y_center> - are center of rectangle (are not top-left corner)
> For example for img1.jpg you will be created img1.txt containing:
> 
> 1 0.716797 0.395833 0.216406 0.147222
> 0 0.687109 0.379167 0.255469 0.158333
> 1 0.420312 0.395833 0.140625 0.166667
