### ISSUE TITLE
Not same performance between make and cmake way Ubuntu 18.04

### ISSUE THREAD

**Issue by KyloEntro** [AlexeyAB/darknet#5476]
Hi,

Thanks for your amazing work.

I always compile Darknet using make way on Ubuntu. I changed my openCV version to 4.3.0 (instead of 4.1.1) and I got an error with make. Conflict between version ... but ok. I decided to change the compilation and to use cmake 
```bash
cmake .
make
```
And ran darknet on a video with option -benchmark and suprise, I lost 2 fps on video ... Same with Python version (darknet_video.py). 

I fixed my problem with opencv version and make clean, restore the old Makefile with GPU, CUDNN, OPENCV = 1 and launched benchmark and got same performance before all my action. 

So it seems that there is a difference compilation between cmake and make. Cmake way build a less perfomant darknet than make way. 
Using nvidia-smi, cmake way darknet use 80% of GPU instead of 91% with make darknet.

### To reproduce : 
```bash
make
./darknet detector demo ./cfg/coco.data ./cfg/yolov3.cfg ./yolov3.weights [VIDEO_FILENAME] -i 0 -thresh 0.25 -benchmark
make clean
cmake .
make
./darknet detector demo ./cfg/coco.data ./cfg/yolov3.cfg ./yolov3.weights [VIDEO_FILENAME] -i 0 -thresh 0.25 -benchmark
```

PS : I'm using this commit : 
commit afb4cc4766eb8ab3686445448fa3cf652ab78eb8 (HEAD -> master)
Author: AlexeyAB
Date:   Thu Apr 2 19:04:08 2020 +0300

    Fix for iou_thresh_kind= param

Don't know if there is same issue with more recent commit

**Comment by AlexeyAB** [comment]
Some issue was solved. Try to use the latest Darknet version.

**Comment by KyloEntro** [comment]
Ok ! Nice, I will soon switch to newer version and give my feedback about this issue
