### ISSUE TITLE
bash: ./darknet: No such file or directory

### ISSUE THREAD

**Issue by mfaramarzi** [AlexeyAB/darknet#5480]
I exactly followed the instruction for compiling on linux. I opened a terminal inside darknet-master (cloned repository?) and ran: 
./build.sh
But when I run training command inside "darknet-master/build/darknet/x64" get the following error:
![Screenshot from 2020-05-04 13-52-56](https://user-images.githubusercontent.com/44882423/80996946-a5c41980-8e0e-11ea-903f-9bebe63d0011.png)
Why isnt darknet working in "darknet-master/build/darknet/x64" ?
I appreciate any help

**Comment by inafi** [comment]
You have to have the darknet executable in the same directory to have it running. This should be in the darknet-master/ directory if you made it from the Makefile.

**Comment by mfaramarzi** [comment]
@inafi That was it. It worked. tnx

**Comment by mfaramarzi** [comment]
@inafi 
Sorry but I am new and not familiar with the darknet, however I red the guide still it is confusing to me
Now the problem is that I want to see the mAP & Loss-chart during training on remote server
I set OPENCV=1 in the make file inside darknet-master, then I execute "make" command in the terminal at the same directory. But still when I run the training OpenCV isn't used.
![Screenshot from 2020-05-04 16-09-40](https://user-images.githubusercontent.com/44882423/81008924-b92cb000-8e21-11ea-95b5-a6fe2ce98907.png)

**Comment by mfaramarzi** [comment]
@inafi should I copy makefile to "darknet-master/build/darknet/x64" as well?

**Comment by inafi** [comment]
You have to use whatever darknet executable that you made with Opencv and replace the one in your directory with that.

**Comment by mfaramarzi** [comment]
@inafi 
Your answers are rally clarifying issues that I was struggling a lot to understand.
 Now I see that opencv that I installed through "conda" could not be recognized by "make".
According to AlexeyAB"s guide, "use your preferred package manager (brew, apt), build from source using vcpkg or download from OpenCV official site".
Does this installation method different from installing opencv in a virtual env like conda?
![Screenshot from 2020-05-04 16-41-18](https://user-images.githubusercontent.com/44882423/81016538-9ead0380-8e2e-11ea-9929-407936c2d9f4.png)


![Screenshot from 2020-05-04 16-41-42](https://user-images.githubusercontent.com/44882423/81016511-93f26e80-8e2e-11ea-98cd-7ddc42b57d25.png)

**Comment by mfaramarzi** [comment]
I guess I have to install using apt as below:
https://docs.opencv.org/3.4/d2/de6/tutorial_py_setup_in_ubuntu.html
