### ISSUE TITLE
GPU Isn't used

### ISSUE THREAD

**Issue by m1kelle-crypto** [AlexeyAB/darknet#5481]
Hello everyone, 
I think Alexey changed today the way to compile the darknet on windows with vcpkg. There is only one thing to type in PS:
.\vcpkg install darknet[opencv-base,weights]:x64-windows
After this training is going only on CPU. Can I build darknet one more time with GPU=1? I can't file makefile anywhere with these new metod of compiling...

Thanks for help!

**Comment by Zy1013921842** [comment]
Hi friend! Have you solved this problem? I got the same error and I compiled with vcpkg as you did so I think your solution should work for me too, thank you friend!

**Comment by m1kelle-crypto** [comment]
> Hi friend! Have you solved this problem? I got the same error and I compiled with vcpkg as you did so I think your solution should work for me too, thank you friend!

When I build vcpkg i just clone the repository again to separate folder, then I change the makefile for GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=1. Then I build darknet from that folder and everything it's correct.

**Comment by Zy1013921842** [comment]
> > Hi friend! Have you solved this problem? I got the same error and I compiled with vcpkg as you did so I think your solution should work for me too, thank you friend!
> 
> When I build vcpkg i just clone the repository again to separate folder, then I change the makefile for GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=1. Then I build darknet from that folder and everything it's correct.

Gotta! Thank you friend for your quick reply, best wishes for you!

**Comment by AlexeyAB** [comment]
@cenit Hi, What vcpkg-command should we use to install Darknet with GPU instead of  `.\vcpkg install darknet[opencv-base,weights]:x64-windows` ?

**Comment by cenit** [comment]
The readme suggests `.\vcpkg install darknet[full]` to enable all functionalities. `opencv-base` is just a small subset, cpu-only.

**Comment by cenit** [comment]
Note that yolov4 is still under revision inside Microsoft for vcpkg. I expect the procedure to be completed within 24hours, the process started almost the day after publishing and got stuck for some internal problems
