### ISSUE TITLE
How to install opencv to work with makefile?

### ISSUE THREAD

**Issue by mfaramarzi** [AlexeyAB/darknet#5482]
I see that opencv that I installed through "conda" could not be recognized by "make".
According to AlexeyAB"s guide, "use your preferred package manager (brew, apt), build from source using vcpkg or download from OpenCV official site".
Doesn't installing by a virtual env like conda do the same thing?
I am really confused how should make it work!
![Screenshot from 2020-05-04 16-41-18](https://user-images.githubusercontent.com/44882423/81022820-9f4c9680-8e3c-11ea-87cc-7fd90f5b69a2.png)
![Screenshot from 2020-05-04 16-41-42](https://user-images.githubusercontent.com/44882423/81022821-9fe52d00-8e3c-11ea-849d-925d8d0032d9.png)

I also followed opencv guide (https://docs.opencv.org/3.4/d2/de6/tutorial_py_setup_in_ubuntu.html) to install opencv inaide darknet-master directory but it didnt work at the last steps as below
![Screenshot from 2020-05-04 19-26-25](https://user-images.githubusercontent.com/44882423/81023032-2ac62780-8e3d-11ea-8a4c-87a06af6c92a.png)

**Comment by WongKinYiu** [comment]
opencv in conda is for python.

for darknet, you can use:
```
apt update
apt install libopencv-dev
```

**Comment by mfaramarzi** [comment]
@WongKinYiu 
Thanks for your response. I tried  this way to install openscv:
sudo apt-get update
sudo apt-get install libopencv-dev
And it was installed successfully.
but then when I wanted to compile by "make"/ make -j4
I got this error:
![1](https://user-images.githubusercontent.com/44882423/81178089-aaefa880-8f75-11ea-8add-957cc894ee44.png)

**Comment by WongKinYiu** [comment]
try
```
make clean
make -j4
```

**Comment by mfaramarzi** [comment]
Actually it finally worked. Those commands were correct. I did  "make" inside "darknet-master" and I got opencv working :+1: 
![2](https://user-images.githubusercontent.com/44882423/81179493-b80d9700-8f77-11ea-9ccf-a3d391de0657.png)
