### ISSUE TITLE
Questions about yolov4 architecture

### ISSUE THREAD

**Issue by kaanakan** [AlexeyAB/darknet#5484]
Hi,

> For GPU we use a small number of groups (1 - 8) in convolutional layers: CSPResNeXt50 / CSPDarknet53.

I saw this in the Yolov4 paper but when I look at the yolov4.cfg, I could not find any groups parameter in the convolutional layers. So, is the group parameter used for only classification model?

Can you provide a block diagram for yolov4? (covering end-to-end architecture, CSPDarknet53, SPP, PANet, Yolov3 heads)

It would be great if you can state which parts of the yolov4.cfg file  correspond to which model ( CSPDarknet53, SPP, PANet, Yolov3 heads).

Thanks in advance.

**Comment by WongKinYiu** [comment]
1. https://github.com/AlexeyAB/darknet/issues/5466#issuecomment-623130824

2. https://github.com/AlexeyAB/darknet/issues/5355#issuecomment-619884433

**Comment by kaanakan** [comment]
Thank you for your fast response. I understand the CSP architecture now and cfg file. 

Is there any figures that show the architecture in an end-to-end fashion? Something like the figure below,

![image](https://user-images.githubusercontent.com/34209020/81061549-35d09480-8edd-11ea-8731-2cfa62f772a7.png)
image credit: https://towardsdatascience.com/yolo-v3-object-detection-53fb7d3bfe6b

**Comment by WongKinYiu** [comment]
https://github.com/lutzroeder/netron
you can try this.

**Comment by kaanakan** [comment]
Thanks a lot!

**Comment by AlexeyAB** [comment]
> > For GPU we use a small number of **groups (1** - 8) in convolutional layers: CSPResNeXt50 / CSPDarknet53.
> 
> I saw this in the Yolov4 paper but when I look at the yolov4.cfg, I **could not find any groups parameter in the convolutional layers.**


`groups=1` by default for `[convolutional]` layers, so yes, we use groups=1 as mentioned in the paper.

**Comment by violet17** [comment]
> > > For GPU we use a small number of **groups (1** - 8) in convolutional layers: CSPResNeXt50 / CSPDarknet53.
> > 
> > 
> > I saw this in the Yolov4 paper but when I look at the yolov4.cfg, I **could not find any groups parameter in the convolutional layers.**
> 
> `groups=1` by default for `[convolutional]` layers, so yes, we use groups=1 as mentioned in the paper.

@AlexeyAB  Is this means that the `[convolutional]` layers aren't partial into to two parts in CSP module? Just like the figure below?
![image](https://user-images.githubusercontent.com/4042800/88027915-86659e80-cb6a-11ea-9bb3-7cefdac466e9.png)

**Comment by WongKinYiu** [comment]
https://github.com/AlexeyAB/darknet/issues/5466#issuecomment-623130824

**Comment by violet17** [comment]
> [#5466 (comment)](https://github.com/AlexeyAB/darknet/issues/5466#issuecomment-623130824)

Hi WongKinYiu, thanks. I figure out that yolov5 uses the conv64 stride2 and splits it into two conv 64.

**Comment by violet17** [comment]
@WongKinYiu  
Hi,  the yolov4 paper says "Improves YOLOv3’s AP and FPS by 10% and 12%, respectively"
I have fully understood it. Which input size and hardware use for comparison?
As known from Figure 1 in https://arxiv.org/pdf/2004.10934.pdf, for 608x608 input running on V100:
YOLOv4  608x608 FPS  65  AP  43.5
YOLOv3  608x608 FPS  72  AP  33

It seems that YOLOv3 is faster than YOLOv4?
I can't figure out the reason.
