### ISSUE TITLE
How to select only 3 classes from COCO?

### ISSUE THREAD

**Issue by Dragon-oniv** [AlexeyAB/darknet#5486]
I edited coco.names and coco.data but while training I'm getting error "Wrong annotation: class_id = 36. But class_id should be [from 0 to 2] " I know that error must be in labels but don't know the fix.

**Comment by GargNishant** [comment]
There are online resources which can convert the COCO to YOLO Format. Like:
https://github.com/ssaru/convert2Yolo
https://bitbucket.org/yymoto/coco-to-yolo/src/master/
etc..
They will be able to extract some classes from the COCO Dataset

**Comment by Dragon-oniv** [comment]
ohk. Thank you bro @GargNishant.

**Comment by AlexeyAB** [comment]
Without training, just add `dont_show ` before each line in `coco.names` file except your 3 classes, and run detection.

**Comment by Dragon-oniv** [comment]
@AlexeyAB Thanks bro. For training Is there a easy way around? like a script to do this task?

**Comment by Dragon-oniv** [comment]
I used this [https://bitbucket.org/yymoto/coco-to-yolo/src/master/](url) link to select 3 classes from COCO for training and it worked.
