### ISSUE TITLE
Can't open label file. (This can be normal only if you use MSCOCO):

### ISSUE THREAD

**Issue by Laudarisd** [AlexeyAB/darknet#5490]
Need help here.

First of all thank you for the great project. I am able to train darknetv3 successfully on my own data.

I am trying to train darknetv4 on same data but I got an error. I can train but all the lines are saying that can't open label file. I checked the directory, .cfg file several time but it doesn't work.

Here, I uploaded all the annotations files and images in the directory as it is mentioned in the project.
Any help would be appreciated. 
![1](https://user-images.githubusercontent.com/53330430/81135056-ac2ece80-8f91-11ea-9147-716eae005691.png)

**Comment by eduardohem** [comment]
1) Try to change de directory name from images to another one. 
2) Rename the files "usbcam..." to another pattern without parentheses.

**Comment by Laudarisd** [comment]
Thank you for your reply.
I tried to change directory but still can't fix the problem.
![3](https://user-images.githubusercontent.com/53330430/81140965-21a49a00-8fa6-11ea-8cd2-b763e64611a3.png)

**Comment by Laudarisd** [comment]
Do I have to  edit  code? Since darknet frame work is in c, I am not familiar with it.

**Comment by YCAyca** [comment]
There can be 2 reason for that.
1) Be sure you have these label files on the right path written on your terminal. So if its written "cant open label file /home/test/.../1465.txt , be sure you have this label file on this path
2)what's the type of your label file? .txt or .xml? If you have .xml files for your annotations on your own dataset, then you should go to replace_image_to_label function in detector.c and change all the find_replace_extension(output_path, ".jpg", ".txt", output_path); function to find_replace_extension(output_path, ".jpg", ".xml", output_path);  (or if the type of your input images are  "jpeg" so change find_replace_extension(output_path, ".jpeg",".txt", output_path); line to find_replace_extension(output_path, ".jpeg",".xml", output_path);)

**Comment by zj88** [comment]
I had the same problem and just copied images and annotation files into darknet dir, for example
`data/img`
and then used relative paths in train.txt and test.txt, like 
`data/img/IMG_20200611_162818.jpg`
Looks like some issue with absolute pathing

**Comment by Laudarisd** [comment]
@zj88  Thank you for your reply.
I solved the problems. 
Thank you

**Comment by Yeaminul** [comment]
Hi @Laudarisd ,
I'm still encountering this error. Any winsdom?

Image diretory -> D:\darknet\build\darknet\x64\data\images
Label directory -> D:\darknet\build\darknet\x64\data\labels

Tried with putting both Images and Labels in the same directory but encountered -> 'Error in load_data_detection() - OpenCV' error. I've provided the absolute directories above for simplicity. Any idea?

My replace_image_to_label function is as below -
find_replace(input_path, "/images/train2014/", "/labels/train2014/", output_path); // COCO
find_replace(output_path, "/images/val2014/", "/labels/val2014/", output_path); // COCO
find_replace(output_path, "/JPEGImages/", "/labels/", output_path); // PascalVOC
find_replace(output_path, "\images\train2014\", "\labels\train2014\", output_path); // COCO
find_replace(output_path, "\images\val2014\", "\labels\val2014\", output_path); // COCO
find_replace(output_path, "\JPEGImages\", "\labels\", output_path); // PascalVOC
find_replace(input_path, "/images/", "/labels/", output_path); // COCO
//find_replace(output_path, "/VOC2007/JPEGImages/", "/VOC2007/labels/", output_path); // PascalVOC
//find_replace(output_path, "/VOC2012/JPEGImages/", "/VOC2012/labels/", output_path); // PascalVOC

**Comment by Laudarisd** [comment]
@Yeaminul, It seems that you are trying to train COCO datasets.
In my case I trained my  own datasets.

I also moved my data inside of `\darknet\build\darknet\x64\data\labels` but it didn't work.  

So I followed these steps:
 
1) Make a folder `custom` inside of main `darknet` folder. Inside of custom create `images`  folders.
2) I put all the images (it was all `.jpg` format)  and annotation files (`.txt`) in `images` folder. 
3) move `test.txt` and `train.txt` files inside of `custom` folder.
```
# test.txt and train.txt file should contain path like this: 
./custom/images/usbcam(2020-03-13-10:26:43).jpg
./custom/images/usbcam(2020-03-18-17:13:19).jpg
```


4) I also moved other files like `obj.data` , `object.names` and ` .cfg`  inside of `custom` folder ( But it is not necessary, just need to mention correct path while training)


After that I ran training , It was okay.

I think, in your case path to train and test images in `test.txt` and `train.txt` files are not correct. You can check that one too.

Hope this will help.

thank you .

**Comment by Yeaminul** [comment]
@Laudarisd Thanks a bunch brother! I have followed your steps in files, directories organisation and training is going on perfectly!
I am also training on my own data set..

**Comment by Laudarisd** [comment]
@Yeaminul  You are welcome brother.
