### ISSUE TITLE
'darknet.exe' doesnt recognise

### ISSUE THREAD

**Issue by Nazrindino97** [AlexeyAB/darknet#5496]
after run this command

`darknet.exe detector train data/obj.data yolov3-palmoil-64 darknet53.conv.74`
 
> 'darknet.exe' is not recognized as an internal or external command, operable program or batch file.

is it because I didn't put `.cfg` after `yolov3-palmoil-64` ?

**Comment by Laudarisd** [comment]
yes, you need to add .cfg file directory in training command.
