### ISSUE TITLE
Creating Custom output of frame and detection data

### ISSUE THREAD

**Issue by apiszcz** [AlexeyAB/darknet#55]
It seems like modification of demo.c to add a new function that omits display unless indicated on command line or configuration file and writing out the detection data could be demo_write_detection_data so one could capture the detection data. I see the frame count is not passed in though, anyways, i'm wondering if that sounds reasonable?

**Comment by AlexeyAB** [comment]
I do not quite understand what you are proposing?

**Comment by apiszcz** [comment]
Interested in detection only data output as a CSV or JSON, with no on screen display.

test_yolo or demo are both close to what is needed, however no on screen display required.

framenumber,objid,llx,lly,urx,ury,label,confidence

**Comment by apiszcz** [comment]
I created a CSV detect module, so there is no display only generation of an output csv with attributes of interest from the detection to a file specified by -ocsvpath.
