### ISSUE TITLE
"Accuracy vs iteration diagram" of Training and validation sets

### ISSUE THREAD

**Issue by mfaramarzi** [AlexeyAB/darknet#5504]
@AlexeyAB @WongKinYiu 

Is there anyway to get  "accuracy vs iteration diagram" of Training and validation sets, simultaneously in the same diagram? Something like below:

![image](https://user-images.githubusercontent.com/44882423/81201490-54916280-8f93-11ea-9807-547c151df208.png)

it could be really intuitive to inform when to stop training.

**Comment by AlexeyAB** [comment]
Is this chart less intuitive to inform when to stop training?

![chart_yolov3-spp-front](https://user-images.githubusercontent.com/4096485/81203232-66452b00-8fd0-11ea-86d3-4f707f79becf.png)

**Comment by mfaramarzi** [comment]
> Is this chart less intuitive to inform when to stop training?
> 
> ![chart_yolov3-spp-front](https://user-images.githubusercontent.com/4096485/81203232-66452b00-8fd0-11ea-86d3-4f707f79becf.png)

@AlexeyAB 
Thanks for quick response. How can we notice when the model is over fitting using this diagram?

**Comment by AlexeyAB** [comment]
When mAP decreases (on valid/test-dataset).
