### ISSUE TITLE
Loss didn't change at all

### ISSUE THREAD

**Issue by ansonuser** [AlexeyAB/darknet#5507]
HI,

Here is my training log...

![image](https://user-images.githubusercontent.com/33833371/81242040-a93de780-903e-11ea-9f88-b5bc09c618b0.png)

and loss for the plot of chart_yolo-obj

![image](https://user-images.githubusercontent.com/33833371/81242101-d7232c00-903e-11ea-9b6e-b39c7ef4343c.png)

It seems model didn't get better at all.
Is there any way to fix that ?

By the way, I used the repo https://github.com/ultralytics/yolov3 with the same dataset and result was reasonable.

Thanks in advance : )

**Comment by AlexeyAB** [comment]
> It seems model didn't get better at all.

What mAP did you get?

**Comment by ansonuser** [comment]
> > It seems model didn't get better at all.
> 
> What mAP did you get?
I didn't draw with map flag. Where can I get mAP after training.
I ran './darknet detector valid ....' and got some txt files but all of them are empty.

**Comment by kame-lqm** [comment]
> > What mAP did you get?
> 
> I didn't draw with map flag. Where can I get mAP after training?
> I ran './darknet detector valid ....' and got some txt files but all of them are empty.
> 
> Updated:
> Replace valid with map got result below:
> ![image](https://user-images.githubusercontent.com/33833371/81247521-d396a180-904c-11ea-933d-82186bfcc9aa.png)

Add '-map' add the end of training cmd.

**Comment by Wellington-Noberto** [comment]
I think I got the same problem, even when I was using yolov3, the model doesn't seems to be learning.
All the config files are configured the same way as you described.

The label .txt are suppose to be like this, right?
Bus 0.445078125 0.7059551592920353 0.224375 0.43626000000000004

**Comment by AlexeyAB** [comment]
Set `valid=train.txt` in obj.data file and run
`./darknet detector map ....`
If mAP > 10-20% then training goes well

Check your dataset by training with flag `-show_imgs`, if you see correct bboxes, then your dataset is correct.

**Comment by Wellington-Noberto** [comment]
After running `!./darknet detector map data/obj.data cfg/yolov4-obj.cfg /mydrive/yolov4/backup/yolov4-obj_final.weights -dont_show`, I got:
(_I'm using google colab, by the way_)
![image](https://user-images.githubusercontent.com/46430006/81326878-d99e7980-9070-11ea-9cbe-9b8b62c153ab.png)

And after adding `-show_imgs` to my tranning, a lot of images were saved with a name starting with `aug_`
Here are some examples
![image](https://user-images.githubusercontent.com/46430006/81327309-73662680-9071-11ea-8d03-8900b76f5536.png)
//////
![image](https://user-images.githubusercontent.com/46430006/81327342-7eb95200-9071-11ea-9cfb-fff95d437ed5.png)
These images don't make any sense to me. At first I thought it was some kind of data augmentation technique, but in some of those images there are combination of images from others classes.

The classes in the dataset I'm using are:  Airplane, Bus and Car.
This is how  the dataset is organized:
_obj_ folder
![image](https://user-images.githubusercontent.com/46430006/81327931-6d247a00-9072-11ea-91f6-dd98aeb0778c.png)
_bbox inside txt_
> Car 0.4990234375 0.35833333333333334 0.999375 0.5425000000000001
> Car 0.9551953125 0.780417 0.08812500000000001 0.4375

_train.txt_
![image](https://user-images.githubusercontent.com/46430006/81328357-1e2b1480-9073-11ea-88ee-e31b92c37ea0.png)

_obj.data_
classes= 3
train  = data/train.txt
valid  = data/train.txt
names = data/obj.names
backup = /mydrive/yolov4/backup

**Comment by AlexeyAB** [comment]
Since you don't see correct bboxes, then your training dataset is wrong.

**Comment by Wellington-Noberto** [comment]
You're right. The mistake is inside the bbox .txt files.
There were suppose to be like you described, object class should be a integer not a string.
Now the trainning is ok. Thank you!

**Comment by ansonuser** [comment]
@AlexeyAB 

I trained with flag -show_imgs. The bboxes are all correct  but map got 0.
Therefore, I think dataset is right.
 Any possible issue come in your mind ?
