### ISSUE TITLE
Configuration guidance on YOLOv3Tiny.

### ISSUE THREAD

**Issue by tobyglei** [AlexeyAB/darknet#5515]
We're building a model to detect small objects (20x20) within 640x640 images. 

For the dataset, we got about 500 training samples and 50 test samples. 

We had a hard time to get the model pass `27% mAP@0.5`. We train it with 5000+ iterations.

Hope if anyone have similar situation could point us to the right direction.

* Config file: [yolov3-tiny-train.cfg](https://gist.github.com/tobyglei/a6f7af0edf3303a4672730790991154b)

* Training logfile: [train_log.txt](https://drive.google.com/file/d/16bGu-_s4EWTfUUu0LdWnNwEYFRffBDtc/view?usp=sharing)

**Comment by kidal5** [comment]
Hi, 

i have briefly checked your logfile and it seems that your dataset is wrong.
It says: Wrong annotation: x = 0, y = 0, < 0 or > 1 

Try to investiagate this.

**Comment by tobyglei** [comment]
Yeah, I saw it, there was one sample that has invalid annotation but overall, it wasn't affect much. Now the `mAP@0.5 is 38.69%`
