### ISSUE TITLE
For localization, is it possible to include images which has no Bounding box?

### ISSUE THREAD

**Issue by ifahim** [AlexeyAB/darknet#5516]
In my data, each image may contain a dog, a cat, both (multiple instance)  or none. If the image contains either cat, dog or both, I have the bounding box for each instances. If the image does not contain anything, there is no bounding box. 

I know how to train yolo with all the images that contain at least one bounding box. Is it possible in YOLO to somehow utilize those images (may be as negative examples, I have almost 50% of such images) which has no bounding box for training? (is this a classification problem mixed with localization?)

**Comment by kame-lqm** [comment]
You can try to create an empty xxxx.txt file for each no bounding box image.

**Comment by ifahim** [comment]
thanks. will try this

**Comment by evan0621** [comment]
@ifahim Does it work ?

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

desirable that your training dataset include images with non-labeled objects that you do not want to detect - negative samples without bounded box (empty .txt files) - use as many images of negative samples as there are images with objects

**Comment by ifahim** [comment]
@evan0621  That did work for me.

**Comment by lizq-git** [comment]
> @evan0621 That did work for me.

Hi, ifahim.

Does it means:

eg. 1_IHC.jpg (IHC is class 0)
content corresponding to the image: 1_IHC.txt ( which has a content of "0" as an indication on the class)

or 1_IHC.txt with empty content?
