### ISSUE TITLE
Why was yolo4 slower to test than your said

### ISSUE THREAD

**Issue by ioir123ju** [AlexeyAB/darknet#5519]
Hi!
GPU:V100
yolov4.cfg:608x608
**command:**
` ./darknet detector demo cfg/coco.data  cfg/yolov4.cfg  yolov4.weights  fall_down_test_2.avi  -dont_show -ext_output`
FPS:39
**command:**
`python darknet.py`
in darknet.py
`start = time.time()
    for i in range(100):
        ret = detect_image(net, meta, im, thresh, hier_thresh, nms, debug)
    end = time.time()
    print(end-start)`
fps:31
but your result is 62(V) FPS

**Comment by AlexeyAB** [comment]
* Do you use the latest version of Darknet?

* Did you compile Darknet with CUDNN_HALF=1 ?

* Do you run something else on this server?

> GPU:V100
> yolov4.cfg:608x608
> command:
> ./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights fall_down_test_2.avi -dont_show -ext_output
> FPS:39

* Just now I get 33 FPS on RTX 2070 for yolov4.cfg/weights 608x608, while V100 is 2x faster

![image](https://user-images.githubusercontent.com/4096485/81295524-3867f100-9079-11ea-807a-9de8d11dbbaf.png)


* Show screenshot of AVG FPS.
`./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights fall_down_test_2.avi -dont_show -ext_output`

* Show such screenshot:
![image](https://user-images.githubusercontent.com/4096485/81295433-140c1480-9079-11ea-969d-b47569375c33.png)




----

> python darknet.py
> in darknet.py
> start = time.time() for i in range(100): ret = detect_image(net, meta, im, thresh, hier_thresh, nms, debug) end = time.time() print(end-start)
> fps:31
> but your result is 62(V) FPS

Don't use python.py

For checking FPS you should use: https://github.com/AlexeyAB/darknet/wiki/How-to-evaluate-accuracy-and-speed-of-YOLOv4
`./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights fall_down_test_2.avi -dont_show -ext_output`
or
`./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights fall_down_test_2.avi -dont_show -ext_output -benchmark`

**Comment by ioir123ju** [comment]
> * Do you use the latest version of Darknet?
> * Did you compile Darknet with GPU=1 CUDNN=1 CUDNN_HALF=1 ?
> * Do you run something else on this server?
> 
> > GPU:V100
> > yolov4.cfg:608x608
> > command:
> > ./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights fall_down_test_2.avi -dont_show -ext_output
> > FPS:39
> 
> * Just now I get 33 FPS on RTX 2070 for yolov4.cfg/weights 608x608, while V100 is 2x faster
> 
> ![image](https://user-images.githubusercontent.com/4096485/81295524-3867f100-9079-11ea-807a-9de8d11dbbaf.png)
> 
> * Show screenshot of AVG FPS.
>   `./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights fall_down_test_2.avi -dont_show -ext_output`
> * Show such screenshot:
>   ![image](https://user-images.githubusercontent.com/4096485/81295433-140c1480-9079-11ea-969d-b47569375c33.png)
> 
> > python darknet.py
> > in darknet.py
> > start = time.time() for i in range(100): ret = detect_image(net, meta, im, thresh, hier_thresh, nms, debug) end = time.time() print(end-start)
> > fps:31
> > but your result is 62(V) FPS
> 
> Don't use python.py
> 
> For checking FPS you should use: https://github.com/AlexeyAB/darknet/wiki/How-to-evaluate-accuracy-and-speed-of-YOLOv4
> `./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights fall_down_test_2.avi -dont_show -ext_output`
> or
> `./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights fall_down_test_2.avi -dont_show -ext_output -benchmark`


yes, I use the latest version of Darknet.
I use cmake to compiled code，
COMMAND:./build.sh
GPU=1 CUDNN=1 CUDNN_HALF=1 is ON.
I use your command retest it and get the results:
./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights fall_down_test_2.avi -dont_show -ext_output
FPS:42.5  AVG_FPS:42.7
![image](https://user-images.githubusercontent.com/14951957/81379125-22bb0000-913b-11ea-8c09-887e23af4f7b.png)

**Comment by AlexeyAB** [comment]
* Use latesl version

* Show such screenshot:
![image](https://user-images.githubusercontent.com/4096485/81295433-140c1480-9079-11ea-969d-b47569375c33.png)

* And only then show screenshot of AVG FPS.
`./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights fall_down_test_2.avi -dont_show -ext_output`

**Comment by AlexeyAB** [comment]
I added small fix: https://github.com/AlexeyAB/darknet/commit/ccafff912bd42728aa873be7b4c7add2366858a8

Try again with the latest repo:

`./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights fall_down_test_2.avi -dont_show -ext_output`
and
`./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights fall_down_test_2.avi -dont_show -ext_output -benchmark`

**Comment by ioir123ju** [comment]
> I added **2 small fixes**: [ccafff9](https://github.com/AlexeyAB/darknet/commit/ccafff912bd42728aa873be7b4c7add2366858a8) and [da05036](https://github.com/AlexeyAB/darknet/commit/da050367a8b174f751a2c9720195d51a369c4a4a)
> 
> Try again with the latest repo:
> 
> `./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights fall_down_test_2.avi -dont_show -ext_output`
> and
> `./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights fall_down_test_2.avi -dont_show -ext_output -benchmark`

I found a problem。
option(ENABLE_CUDNN_HALF "Enable CUDNN Half precision" ON)
in the CMakeLists.txt 
BUT  when I run ./darknet ..., result is 'CUDNN_HALF=0'.
So I tried  to compile with **Makefile**.
It is working! Everything is all right.
 CUDNN_HALF=1.
![image](https://user-images.githubusercontent.com/14951957/81462226-9b759700-91e3-11ea-9808-5592657116d3.png)
FPS:59.
Maybe you should 
check the **CMakelist.txt**.

**Comment by AlexeyAB** [comment]
@ioir123ju 
It should work for any GPU with CC 7.0(V100), 7.2, 7.5(RTX) https://github.com/AlexeyAB/darknet/commit/f14054ec2b49440ad488c3e28612e7a76780bc5f#diff-af3b638bc2a3e6c650974192a53c7291R68

It will not work only if you use older commit.

**Comment by Li505358678** [comment]
with MSCOCO. I valided with ./darknet detector valid cfg/coco.data cfg/yolov4.cfg yolov4.weights. It took about 1200 seconds to process 20288 images.and  evaluated FPS of YOLOv4 on GPU by ./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights test.mp4 -dont_show -ext_output. FPS is around 30. Both of them were too slow . I sure that CUDNN_HALF=1. What's wrong with it?

**Comment by Li505358678** [comment]
with MSCOCO. 
I valided with ./darknet detector valid cfg/coco.data cfg/yolov4.cfg yolov4.weights.
It took about 1200 seconds to process 20288 images.

and evaluated FPS of YOLOv4 on GPU by ./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights test.mp4 -dont_show -ext_output. 
FPS is around 30. 

Both of them were too slow . I sure that CUDNN_HALF=1. What's wrong with it?

**Comment by AlexeyAB** [comment]
@Li505358678 

* Show such screenshot:
![image](https://user-images.githubusercontent.com/4096485/81295433-140c1480-9079-11ea-969d-b47569375c33.png)

----

> and evaluated FPS of YOLOv4 on GPU by ./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights test.mp4 -dont_show -ext_output.
> FPS is around 30.

* Show screenshot

**Comment by Li505358678** [comment]
> @Li505358678
> 
> * Show such screenshot:
>   ![image](https://user-images.githubusercontent.com/4096485/81295433-140c1480-9079-11ea-969d-b47569375c33.png)
> 
> > and evaluated FPS of YOLOv4 on GPU by ./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights test.mp4 -dont_show -ext_output.
> > FPS is around 30.
> 
> * Show screenshot

![image](https://user-images.githubusercontent.com/51314795/82148116-f9117f80-9884-11ea-8bfa-8ce9df9a4c0d.png)

**Comment by Li505358678** [comment]
@AlexeyAB 
from this. is there any wrong?I've had a headache for a day because this

**Comment by AlexeyAB** [comment]
Compile OpenCV and Darknet in Release mode instead of Debug.

**Comment by Li505358678** [comment]
debug change to 0?

**Comment by AlexeyAB** [comment]
Yes.

And show screenshot of FPS of these two commands:
`./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights test.mp4 -dont_show -ext_output`

`./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights test.mp4 -dont_show -ext_output -benchmark`

**Comment by Li505358678** [comment]
thank you very much! the fps of video is 65 ok ,

but fps of the images is bad about 30 .Specifically, 20288 pictures of testdev2017.txt and test2017 took about 800 seconds(812s)
commands:./darknet detector valid cfg/coco.data cfg/yolov4.cfg yolov4.weights

**Comment by AlexeyAB** [comment]
./darknet detector valid - isn't optimized for high speed, there is performance bottleneck in your CPU or HDD.

**Comment by Li505358678** [comment]
> ./darknet detector valid - isn't optimized for high speed, there is performance bottleneck in your CPU or HDD.

so is there any good way which valid images with high speed

**Comment by AlexeyAB** [comment]
* What HDD/SSD disk do you use?
* What CPU do you use?
* What is the average size of your images
* How many images do you have, how long do they take to process with DEBUG=0?
* Try to set `int nthreads = 8;` there and recompile https://github.com/AlexeyAB/darknet/blob/0ef5052ee51e82b2862fab5e9135b7bae060354f/src/detector.c#L688
    What speed do you get?

**Comment by Li505358678** [comment]
I just do as https://github.com/AlexeyAB/darknet/wiki/How-to-evaluate-accuracy-and-speed-of-YOLOv4 . the images are  test2017 which has more than 20288 images,but testdev2017.txt only have 20288. with debug=0  use  835s

**Comment by AlexeyAB** [comment]
So you got only 23 FPS for images, while 65 FPS for video.
What about other questions?

**Comment by Li505358678** [comment]
As you said.
what's mean of other question?

**Comment by AlexeyAB** [comment]
The bottleneck is in your HDD disk, buy SSD.

**Comment by Li505358678** [comment]
I see. Thank you very much for your help!
