### ISSUE TITLE
How to accelerate the detection speed of yolov3?

### ISSUE THREAD

**Issue by XP-CHRC** [AlexeyAB/darknet#552]
The accuracy of yolov3 is very good， but are there any methods to accelerate the detecttion speed of it while not lose too much accuracy?
i want to change the classes to five, but i know there will no much change.
and what about the depthwise separable convolution，dose it will works? or shufflenet?
Do any one can give me some advices? 
Thanks ahead.

**Comment by FaBeyyy** [comment]
Was wondering this aswell cause yolov3 is almost twice as slow compared to yolov2 using the same network resolution.

**Comment by AlexeyAB** [comment]
If you use medium and large objects, then you can reduce network resolution of Yolo v3, for example, to width=224 height=224.

----

Or you can try to remove all leyrs after the 1-st [yolo] layer: https://github.com/AlexeyAB/darknet/blob/726cebd3fb67d65ec6d2d49fa6bfba4c053085df/cfg/yolov3.cfg#L616-L788
and 
* change this line to this `mask = 0,1,2,3,4,5,6,7,8`: https://github.com/AlexeyAB/darknet/blob/726cebd3fb67d65ec6d2d49fa6bfba4c053085df/cfg/yolov3.cfg#L608
* change this line to this `filters=` (classes + 5)x9: https://github.com/AlexeyAB/darknet/blob/726cebd3fb67d65ec6d2d49fa6bfba4c053085df/cfg/yolov3.cfg#L603

**Comment by XP-CHRC** [comment]
@AlexeyAB thanks again, i will try right now.

**Comment by AlexeyAB** [comment]
> yolov2-tiny voc doesnt work for my objects it seems so what am i left with?

Doesn't work or works badly?

Try to use Yolo v2 with low resolution 288x288. 
And update your code from this repo - I increased speed about 7%.

**Comment by XP-CHRC** [comment]
no significant effect in the jetson tx2, yolov3 is very sensitive.
