### ISSUE TITLE
YOLOv3 won't converge

### ISSUE THREAD

**Issue by nicolasgorrity** [AlexeyAB/darknet#5521]
Hello,

This is probably a recurrent issue but I didn't find any answer that solved my problem.

### Issue
I am training YOLOv3 with a subset of classes from the COCO dataset (6 classes exactly).
The loss starts decreasing as it should at the beginning, but it never goes under 1 or 2. And the mAP never goes above 12%.

### Dataset
- I downloaded COCO2017 dataset instead of COCO2014 as indicated in pjreddie's repo because a lot of label files are missing or corrupted in the 2014 version (at least, in the files that are downloaded by the script in the repo).
- I converted the annotations from JSON to txt, and also converted the format of the annotations (converted y_top and x_left from COCO to y_center and x_center for darknet).
-  I kept only the samples containing at least one object of the classes that I am interested in. So I removed all the objects with non-relevant classes, and I removed the samples with no relevant object.
- I also tried balancing the classes repartition. To be specific, I randomly removed some objects of the classes *car* and *person*.

&rarr; That left me with a balanced dataset containing between 8k and 11k objects per class in the training set. Note that I did the same manipulations in the validation set.

### Training

- I only want an input of 416x416.
- I did adapt the cfg file for my number of classes: 
    - `classes=6` in the three `[yolo]` layers
    - `filters=33` (3 x (5+6) = 33) in the three `[convolution]` layers preceding the `[yolo]` layers
- This is the start of my cfg file:
```python
[net]
# Testing
# batch=1
# subdivisions=1
# Training
batch=64
subdivisions=16
width=416
height=416
channels=3
momentum=0.8
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.00001
burn_in=400
max_batches = 20000
policy=steps
steps=18000,19000
scales=.1,.1

[convolutional]
...
```

### Resulting behaviour
This gives the following curves during the training:
![chart_yolov3_0_20k](https://user-images.githubusercontent.com/27773142/81293428-9d1d4e80-906d-11ea-87f0-e480c01e7525.png)

### What I tried
- I tried lowering the learning rate because the loss seems quite unstable, but it didn't improve the learning. In the above graph, we can already see that it doesn't get unstuck whereas the learning rate is divided by 10 at epochs 18k and 19k.
- I tried lowering the batch size, it didn't change anything (loss was even more unstable which seems logic) but it stayed around the same value and mAP didn't improve.

&rarr; So I can't figure out why the network won't learn on these 6 classes of COCO. Any suggestions ?

**Comment by AlexeyAB** [comment]
> I converted the annotations from JSON to txt, and also converted the format of the annotations (converted y_top and x_left from COCO to y_center and x_center for darknet).

Did you change class_id from 0-79 to 0-5?

Do you calc mAP on training or validation dataset?

**Comment by nicolasgorrity** [comment]
Hello,
Yes I changed the class IDs in the annotations.
The mAP is computed on the validation dataset.

**Comment by AlexeyAB** [comment]
* Show output of command ./darknet detector map ...
* How many training images do you use?

* Try to train `max_batches = ` number of training images

**Comment by nicolasgorrity** [comment]
> * Show output of command ./darknet detector map ...

The command 
```bash
./darknet detector map cfg/coco_custom.data cfg/yolov3_custom.cfg backup/yolov3_custom_best.weights -map
```
gives
```bash
CUDA-version: 10000 (10000), cuDNN: 7.6.5, CUDNN_HALF=1, GPU count: 1  
 CUDNN_HALF=1 
 OpenCV version: 3.2.0d
 compute_capability = 750, cudnn_half = 1 
net.optimized_memory = 0 
mini_batch = 1, batch = 4, time_steps = 1, train = 0 
   layer   filters  size/strd(dil)      input                output
   0 conv     32       3 x 3/ 1    416 x 416 x   3 ->  416 x 416 x  32 0.299 BF
   1 conv     64       3 x 3/ 2    416 x 416 x  32 ->  208 x 208 x  64 1.595 BF
   2 conv     32       1 x 1/ 1    208 x 208 x  64 ->  208 x 208 x  32 0.177 BF
   3 conv     64       3 x 3/ 1    208 x 208 x  32 ->  208 x 208 x  64 1.595 BF
   4 Shortcut Layer: 1,  wt = 0, wn = 0, outputs: 208 x 208 x  64 0.003 BF
   5 conv    128       3 x 3/ 2    208 x 208 x  64 ->  104 x 104 x 128 1.595 BF
   6 conv     64       1 x 1/ 1    104 x 104 x 128 ->  104 x 104 x  64 0.177 BF
   7 conv    128       3 x 3/ 1    104 x 104 x  64 ->  104 x 104 x 128 1.595 BF
   8 Shortcut Layer: 5,  wt = 0, wn = 0, outputs: 104 x 104 x 128 0.001 BF
   9 conv     64       1 x 1/ 1    104 x 104 x 128 ->  104 x 104 x  64 0.177 BF
  10 conv    128       3 x 3/ 1    104 x 104 x  64 ->  104 x 104 x 128 1.595 BF
  11 Shortcut Layer: 8,  wt = 0, wn = 0, outputs: 104 x 104 x 128 0.001 BF
  12 conv    256       3 x 3/ 2    104 x 104 x 128 ->   52 x  52 x 256 1.595 BF
  13 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
  14 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
  15 Shortcut Layer: 12,  wt = 0, wn = 0, outputs:  52 x  52 x 256 0.001 BF
  16 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
  17 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
  18 Shortcut Layer: 15,  wt = 0, wn = 0, outputs:  52 x  52 x 256 0.001 BF
  19 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
  20 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
  21 Shortcut Layer: 18,  wt = 0, wn = 0, outputs:  52 x  52 x 256 0.001 BF
  22 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
  23 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
  24 Shortcut Layer: 21,  wt = 0, wn = 0, outputs:  52 x  52 x 256 0.001 BF
  25 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
  26 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
  27 Shortcut Layer: 24,  wt = 0, wn = 0, outputs:  52 x  52 x 256 0.001 BF
  28 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
  29 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
  30 Shortcut Layer: 27,  wt = 0, wn = 0, outputs:  52 x  52 x 256 0.001 BF
  31 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
  32 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
  33 Shortcut Layer: 30,  wt = 0, wn = 0, outputs:  52 x  52 x 256 0.001 BF
  34 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
  35 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
  36 Shortcut Layer: 33,  wt = 0, wn = 0, outputs:  52 x  52 x 256 0.001 BF
  37 conv    512       3 x 3/ 2     52 x  52 x 256 ->   26 x  26 x 512 1.595 BF
  38 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  39 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  40 Shortcut Layer: 37,  wt = 0, wn = 0, outputs:  26 x  26 x 512 0.000 BF
  41 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  42 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  43 Shortcut Layer: 40,  wt = 0, wn = 0, outputs:  26 x  26 x 512 0.000 BF
  44 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  45 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  46 Shortcut Layer: 43,  wt = 0, wn = 0, outputs:  26 x  26 x 512 0.000 BF
  47 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  48 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  49 Shortcut Layer: 46,  wt = 0, wn = 0, outputs:  26 x  26 x 512 0.000 BF
  50 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  51 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  52 Shortcut Layer: 49,  wt = 0, wn = 0, outputs:  26 x  26 x 512 0.000 BF
  53 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  54 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  55 Shortcut Layer: 52,  wt = 0, wn = 0, outputs:  26 x  26 x 512 0.000 BF
  56 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  57 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  58 Shortcut Layer: 55,  wt = 0, wn = 0, outputs:  26 x  26 x 512 0.000 BF
  59 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  60 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  61 Shortcut Layer: 58,  wt = 0, wn = 0, outputs:  26 x  26 x 512 0.000 BF
  62 conv   1024       3 x 3/ 2     26 x  26 x 512 ->   13 x  13 x1024 1.595 BF
  63 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF
  64 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  65 Shortcut Layer: 62,  wt = 0, wn = 0, outputs:  13 x  13 x1024 0.000 BF
  66 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF
  67 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  68 Shortcut Layer: 65,  wt = 0, wn = 0, outputs:  13 x  13 x1024 0.000 BF
  69 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF
  70 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  71 Shortcut Layer: 68,  wt = 0, wn = 0, outputs:  13 x  13 x1024 0.000 BF
  72 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF
  73 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  74 Shortcut Layer: 71,  wt = 0, wn = 0, outputs:  13 x  13 x1024 0.000 BF
  75 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF
  76 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  77 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF
  78 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  79 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF
  80 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  81 conv     33       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x  33 0.011 BF
  82 yolo
[yolo] params: iou loss: mse (2), iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
  83 route  79                                     ->   13 x  13 x 512 
  84 conv    256       1 x 1/ 1     13 x  13 x 512 ->   13 x  13 x 256 0.044 BF
  85 upsample                 2x    13 x  13 x 256 ->   26 x  26 x 256
  86 route  85 61                                  ->   26 x  26 x 768 
  87 conv    256       1 x 1/ 1     26 x  26 x 768 ->   26 x  26 x 256 0.266 BF
  88 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  89 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  90 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  91 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  92 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  93 conv     33       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x  33 0.023 BF
  94 yolo
[yolo] params: iou loss: mse (2), iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
  95 route  91                                     ->   26 x  26 x 256 
  96 conv    128       1 x 1/ 1     26 x  26 x 256 ->   26 x  26 x 128 0.044 BF
  97 upsample                 2x    26 x  26 x 128 ->   52 x  52 x 128
  98 route  97 36                                  ->   52 x  52 x 384 
  99 conv    128       1 x 1/ 1     52 x  52 x 384 ->   52 x  52 x 128 0.266 BF
 100 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
 101 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
 102 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
 103 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
 104 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
 105 conv     33       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x  33 0.046 BF
 106 yolo
[yolo] params: iou loss: mse (2), iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
Total BFLOPS 65.341 
avg_outputs = 517718 
 Allocate additional workspace_size = 52.43 MB 
Loading weights from backup/yolov3_custom_final.weights...
 seen 64, trained: 1312 K-images (20 Kilo-batches_64) 
Done! Loaded 107 layers from weights-file 

 calculation mAP (mean average precision)...
1012
 detections_count = 37178, unique_truth_count = 2268  
class_id = 0, name = person, ap = 1.28%          (TP = 0, FP = 0) 
class_id = 1, name = bicycle, ap = 6.36%         (TP = 1, FP = 3) 
class_id = 2, name = car, ap = 3.06%     (TP = 4, FP = 17) 
class_id = 3, name = motorbike, ap = 19.32%      (TP = 20, FP = 8) 
class_id = 4, name = bus, ap = 29.97%            (TP = 75, FP = 56) 
class_id = 5, name = truck, ap = 9.86%           (TP = 9, FP = 17) 

 for conf_thresh = 0.25, precision = 0.52, recall = 0.05, F1-score = 0.09 
 for conf_thresh = 0.25, TP = 109, FP = 101, FN = 2159, average IoU = 34.80 % 

 IoU threshold = 50 %, used Area-Under-Curve for each unique Recall 
 mean average precision (mAP@0.50) = 0.116429, or 11.64 % 
Total Detection Time: 31 Seconds

Set -points flag:
 `-points 101` for MS COCO 
 `-points 11` for PascalVOC 2007 (uncomment `difficult` in voc.data) 
 `-points 0` (AUC) for ImageNet, PascalVOC 2010-2012, your custom dataset
```

> * How many training images do you use?

The total number of training images is 23609

> * Try to train `max_batches = ` number of training images

I trained it with max_batches=20k before. So I can resume this training for 3k more batches but it seems that it won't change much. I can still try.

**Comment by AlexeyAB** [comment]
What training command did you use? https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects
Did you strictly follow this manual?
What mAP do you get on training dataset?

**Comment by nicolasgorrity** [comment]
> What training command did you use? https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects
> Did you strictly follow this manual?

Yes I followed this procedure to setup the training.
The training command I used is:
```bash
./darknet detector train cfg/coco_custom.data cfg/yolov3_custom.cfg ./darknet53.conv.74 -map
```
My file `cfg/coco_custom.data` contains:
```bash
classes= 6
train  = /home/nicolas/Documents/yolo/coco2017/list_train.txt
valid  = /home/nicolas/Documents/yolo/coco2017/list_val.txt
names = data/coco_custom.names
backup = backup/
eval=coco
```
The file `data/coco_custom.names` contains:
```
person
bicycle
car
motorbike
bus
truck
```
> What mAP do you get on training dataset?

The mAP is the same on the training set (training: 11,67% / validation: 11,64%), and the AP for each class is similar between the training set and the validation set:
```
 calculation mAP (mean average precision)...
23612
 detections_count = 848137, unique_truth_count = 52821  
class_id = 0, name = person, ap = 1.94%          (TP = 1, FP = 0) 
class_id = 1, name = bicycle, ap = 8.01%         (TP = 55, FP = 47) 
class_id = 2, name = car, ap = 2.49%     (TP = 49, FP = 287) 
class_id = 3, name = motorbike, ap = 19.31%      (TP = 413, FP = 318) 
class_id = 4, name = bus, ap = 26.22%            (TP = 1411, FP = 1440) 
class_id = 5, name = truck, ap = 12.06%          (TP = 304, FP = 344) 

 for conf_thresh = 0.25, precision = 0.48, recall = 0.04, F1-score = 0.08 
 for conf_thresh = 0.25, TP = 2233, FP = 2436, FN = 50588, average IoU = 31.97 % 

 IoU threshold = 50 %, used Area-Under-Curve for each unique Recall 
 mean average precision (mAP@0.50) = 0.116697, or 11.67 % 
Total Detection Time: 689 Seconds
```

**Comment by AlexeyAB** [comment]
* Attach your cfg-file in zip-archive.
* run training with `-show_imgs` flag, do you see correct bounded boxes?

**Comment by nicolasgorrity** [comment]
Here is my cfg file: [yolov3_custom.zip](https://github.com/AlexeyAB/darknet/files/4593918/yolov3_custom.zip)

> run training with -show_imgs flag, do you see correct bounded boxes?

Bounding-boxes seem to be correct, however a few of them look strange (see example below). If I want to check the annotation, how can I retrieve the original image filename from the saved image containing the bounding-boxes (whose name look like `aug_902234052_2_1373709179.jpg`) ?

![image](https://user-images.githubusercontent.com/27773142/81313613-630d7600-9088-11ea-8b3f-b4f1bd159287.png)

However, I think I can guess why the APs of the classes `car` and `person` are so low. When I wanted to balance the class, I dropped some objects from those two classes. But when I dropped an object, I did not drop the entire image from the dataset. If other objects were present on the image, this image still be included in the dataset. So there were plenty of examples of images with persons or cars that were not labeled, so the dataset learned not to detect those samples.

I will try retraining without the class balancing to avoid this, and I will keep you updated.

(However, that doesn't explain the low AP for other classes). 


> > I converted the annotations from JSON to txt, and also converted the format of the annotations (converted y_top and x_left from COCO to y_center and x_center for darknet).
> 
> * What script did you use?

I used the script from [this repo](https://github.com/ujsyehao/COCO-annotations-darknet-format) to convert JSON files to txt. And I wrote my own script to:
- convert bounding boxes from COCO format to darknet format
- adapt the class IDs of each object
- balance the classes by dropping some objects (which I will remove)

**Comment by AlexeyAB** [comment]
> So there were plenty of examples of images with persons or cars that were not labeled, so the dataset learned not to detect those samples.

So your dataset is totaly wrong: https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

> check that each object that you want to detect is mandatory labeled in your dataset - no one object in your data set should not be without label. In the most training issues - there are wrong labels in your dataset (got labels by using some conversion script, marked with a third-party tool, ...). Always check your dataset by using: https://github.com/AlexeyAB/Yolo_mark


-----


For balacnig set `counters_per_class=` for each [yolo] layer in cfg-file.
`counters_per_class=` values you can get by using command:
`darknet.exe detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416`


-----

> Bounding-boxes seem to be correct, however a few of them look strange (see example below). 

Yes, MSCOCO labels are too bad: https://github.com/AlexeyAB/darknet/issues/4085

----

> I downloaded COCO2017 dataset instead of COCO2014 as indicated in pjreddie's repo because a lot of label files are missing or corrupted in the 2014 version (at least, in the files that are downloaded by the script in the repo).


How did you check that  your labels are better than labels from pjreddie's site?
