### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by arkadiyhacks** [AlexeyAB/darknet#5525]
When i run the real-time recognition of YOLOv3, what does the algorithm provide in terms of figure? Is it accuracy? The output that I can see on the screen and terminal

Thanks a lot!

**Comment by AlexeyAB** [comment]
I didn’t understand what you said.

**Comment by arkadiyhacks** [comment]
So when you upload an image via detector test, the terminal window outputs %. I would like to know what is this %.
I attached the pic (that's detector demo, but still the same figure)
https://drive.google.com/file/d/15r6fWuYuuDH78Q987DXViEgdtxAXtPOJ/view?usp=sharing

Thank you very much

**Comment by AlexeyAB** [comment]
This is a confidence threshold, it isn't related to accuracy.

Run detection with `-ext_output` flag for showing coordinates of objects: https://github.com/AlexeyAB/darknet#how-to-use-on-the-command-line

**Comment by arkadiyhacks** [comment]
Thank you! I trained the model with 95% train and 5% valid set. If I simply increase valid set now and recalculate mAP, would it take into account new images? Or would I need to retrain the model?

**Comment by arkadiyhacks** [comment]
Hi Alexey, can I change the confidence threshold to recalculate mAP? Also any advice on what it should be? Why is it 0.25 as a default?

**Comment by arkadiyhacks** [comment]
In case anyone wants to change confidence threshold in detector map add -thresh X, where X is your threshold.
