### ISSUE TITLE
Testing on unseen data

### ISSUE THREAD

**Issue by arkadiyhacks** [AlexeyAB/darknet#5526]
Yolov3 just uses train and valid dataset. How to test on the unseen data? Or is it not supported? Or is there no need for cross validation?

**Comment by AlexeyAB** [comment]
This is the Accuracy (% AP) / Speed (FPS) comparison of different algorithms on the **unseen** images (test-dev)

![comparison_gpus](https://user-images.githubusercontent.com/4096485/81351643-80b0fe80-90cd-11ea-9a26-d97c26bb2017.png)

**Comment by arkadiyhacks** [comment]
Thank you, but how do I check it for my custom dataset?
