### ISSUE TITLE
Hi. I have issue about mixup or mosaic custom detector using yolov4

### ISSUE THREAD

**Issue by ubix12** [AlexeyAB/darknet#5528]
![image](https://user-images.githubusercontent.com/62841055/81365524-4ffbb400-9123-11ea-95b5-f6faecc5cae3.png)
![image](https://user-images.githubusercontent.com/62841055/81365543-5f7afd00-9123-11ea-9c48-62d071be3455.png)
![image](https://user-images.githubusercontent.com/62841055/81365546-630e8400-9123-11ea-9c83-5f11214a53bd.png)
![image](https://user-images.githubusercontent.com/62841055/81365552-6570de00-9123-11ea-9efd-a4365db16a59.png)

I had to tried 300 images about 4 class electronic components using yolov4. but when I using mixup or mosaic, mixup mosaic mAP is more decrease than not using mixup, mosaic. 

(mAP : normal 96.7, mixup 96.0, mosaic 96.6)
(But when testing some images, mixup or mosaic detectors are find well than not using one)

low mAP but find well more than high mAP... 

what is problem about this case?

traning set is 90% and valid set is 10%.

And next day
I used more valid set(180). then mixup, mosaic mAP is more high than not using one's mAP

I don't know why this custom detector is working like this..

**Comment by AlexeyAB** [comment]
Just because your dataset is small.

**Comment by ubix12** [comment]
> Just because your dataset is small.

Oh. I got it Thanks!
