### ISSUE TITLE
Lots of `weights_normalizion` typos

### ISSUE THREAD

**Issue by jerry73204** [AlexeyAB/darknet#5533]
It should be spelled `weights_normalization`. There are several typos across the repo. For example, the [darknet.h](https://github.com/AlexeyAB/darknet/blob/ccafff912bd42728aa873be7b4c7add2366858a8/include/darknet.h#L355) header.

**Comment by AlexeyAB** [comment]
This bug is fixed: https://github.com/AlexeyAB/darknet/commit/424632f3369cbd4c82f5473b9add77f7757dc2c6
