### ISSUE TITLE
problem when calculating mAP

### ISSUE THREAD

**Issue by RadouaneK** [AlexeyAB/darknet#5536]
Hi @AlexeyAB 

I'm getting the following error when I calculate mAP:

```
calculation mAP (mean average precision)...
1112corrupted size vs. prev_size
Aborted
```
I am using the latest changes of this repository. didn't use to get this error before
here is the command I'm using for calculating mAP
./darknet detector map data/obj.data yolov4-custom.cfg backup/yolov4-custom_best.weights

**Comment by AlexeyAB** [comment]
* can you successfully run `./darknet detector valid ...` or `./darknet detector recall ... ` ?

*  if you use `train=valid.txt` then can you successfully run `./darknet detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416` ?

* if you use `train=valid.txt` then can you train for 1000 iterations? (previously save your ?_last and _best.weights)



* Show such screenshot:

![image](https://user-images.githubusercontent.com/4096485/81405816-146fe280-9141-11ea-818b-5ce82022e936.png)


* show content of files bad.list and bad_label.list

**Comment by RadouaneK** [comment]
Hi @AlexeyAB  
thank you so much for your help
>     * can you successfully run `./darknet detector valid ...` or `./darknet detector recall ... ` ?
yes, I tried both commands and they're working 

>     * if you use `train=valid.txt` then can you successfully run `./darknet detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416` ?
yes, the command worked successfully, new anchors were generated

>     * if you use `train=valid.txt` then can you train for 1000 iterations? (previously save your ?_last and _best.weights)
I trained model with valid dataset, at iteration 1000, it stops while it was calculating mAP, raising same error

>     * Show such screenshot:
![sn](https://user-images.githubusercontent.com/29167349/81467589-90b20680-91d1-11ea-86ee-1ae30019b1b2.png)

>     * show content of files bad.list and bad_label.list
I think problem is in here, I have some images with wrong labels, here is the output of bad_label.list file
`/root/dataset/trave-tjxmy/trave-tjxmy_20200113T093200Z/trave-tjxmy_20200113T093200Z_frame_013.txt Wrong annotation: class_id = 10. But class_id should be [from 0 to 9]`

**Comment by AlexeyAB** [comment]
1. Compile OpenCV in Release mode instead of Debug
2. Then compile Darknet with DEBUG=0 instead of DEBUG=1

At least DEBUG is very slow, and can be unstable.

**Comment by RadouaneK** [comment]
I tried your suggestions, and training now seems to be faster than before

> Do you get this error only when you train with `-map` flag?
yes, only when map is being calculated
