### ISSUE TITLE
Do a training for Yolov3 tiny prn

### ISSUE THREAD

**Issue by KyloEntro** [AlexeyAB/darknet#5538]
Hi,

I want to use Yolov3 tiny prn to detect my own object.
Is the training is the same describe in README.md as yolov3 tiny ? 

Instead of Yolov3 Tiny, I think I need to use yolov3-tiny-prn.cfg, but for the model ?
Do i need to do `darknet.exe partial cfg/yolov3-tiny.cfg yolov3-tiny-prn.weights yolov3-tiny-prn.conv.15 15` or I need to change the value 15 by an other ? 

Thanks

**Comment by AlexeyAB** [comment]
All the same as for yolov-tiny

**Comment by KyloEntro** [comment]
Nice, thank you :)
