### ISSUE TITLE
YoloV3 Tiny configuration

### ISSUE THREAD

**Issue by andreilica** [AlexeyAB/darknet#5540]
I am trying to use OpenCV's dnn with the YoloV3 tiny model.
After loading the model using `net = cv2.dnn.readNet("yolov3-tiny.weights", "yolov3-tiny.cfg")` I am creating the blob using ` blob = cv2.dnn.blobFromImage(frame, 1 / 255.0, (320, 320), swapRB=True, crop=False)`. Using (320, 320) as size I am getting the best precision. If I change those to (416, 416) or (608, 608) it stops detecting anything, even though I change the width and height in the yolov3-tiny.cfg file also. It seems like the width and size change in the .cfg isn't changing anything. I was trying to achieve best results I can achieve using YoloV3-tiny so that's why I wanted to change the size to 608. Also, I am using the pre-trained weights on the Coco Dataset. My guess is that those weights are trained using some values for (width, height) and are not compatible if I change those sizes? If so, are there any yolov3-tiny weights trained on 608,608? Thank you!

**Comment by AlexeyAB** [comment]
Should work for any `inp_width, inp_height` which are multiple of 32:

```cpp
cv::Mat blob;
cv::dnn::blobFromImage(frame, blob, 1.0, cv::Size(inp_width, inp_height), cv::Scalar(), swap_rb, false, CV_8U);
net.setInput(blob, "", scale, mean);
std::vector<cv::Mat> outs;
net.forward(outs, out_names);
```

**Comment by andreilica** [comment]
But should I change that size in the cfg file, also? Or that doesn't do anything?

**Comment by AlexeyAB** [comment]
No, OpenCV-dnn doesn't use width= height= from cfg-file.
