### ISSUE TITLE
avg loss 0.000000

### ISSUE THREAD

**Issue by alphapibeta** [AlexeyAB/darknet#5541]
I am training for custom dataset my yolo I have created custom cfg file as per the guid; my avg loss is zero 
<img width="1440" alt="Screenshot 2020-05-09 at 2 49 21 AM" src="https://user-images.githubusercontent.com/49142689/81450367-eb326f00-919f-11ea-9a92-ea5ed66cdacb.png">
<img width="1440" alt="Screenshot 2020-05-09 at 2 49 29 AM" src="https://user-images.githubusercontent.com/49142689/81450370-ecfc3280-919f-11ea-9eab-23d057f16026.png">

**Comment by ark-** [comment]
Did you still get a working model at the end?

**Comment by alphapibeta** [comment]
Yes, I did get a working model at the end of the iterations.
While training it on multi GPU's the avg loss changed to a different value other than 0.00000
