### ISSUE TITLE
what will happen if training a tiny yolo network started with yolo's weights?

### ISSUE THREAD

**Issue by goodtogood** [AlexeyAB/darknet#555]
Hi, there

1.  I have one well trained network based on yolo,
Is it possbile to fine-tune a new tiny-yolo network with yolo model trained previously?
Can the new tiny-yolo network make use of  conv layer weights of yolo model ?
Or it'll be initialized randomly.

2. does darknet support multitask mode? 
e.g.   detecting car and predicting its attributes  (make, model, year, etc. ) in one model.
thanks!

**Comment by AlexeyAB** [comment]
1. Yes you can
* tiny-yolo-voc.cfg and yolov2-tiny-voc.cfg - are identical models
* tiny-yolo.cfg and yolov2-tiny.cfg models differ in the penultimate convolutional layer, but you can fine-tune old-weights is you set `stopbackward=1` here: https://github.com/AlexeyAB/darknet/blob/c3c6703b8bc5b769ec25fc26a5a1aff43bcb1939/cfg/yolov2-tiny.cfg#L104

2. Use Yolo9000 https://github.com/AlexeyAB/darknet#using-yolo9000

**Comment by goodtogood** [comment]
@AlexeyAB 
firstly, thank you so much for your reply.
maybe I did't say it clearly.
I have one trained model based on yolo.2.0.cfg ,
In order to improve detection speed, I want to fine-tune a new model based on tiny-yolo.cfg
what I did as follows , extracting  weight firstly,

`darknet partial ./yolo-obj.cfg ./yolo-obj-90000.weights  ./yolo-obj-90000.conv.23 23`

then start train new tiny-yolo model

`darknet detector train ./tiny-yolo-obj.data ./tiny-yolo-obj.cfg ./yolo-obj-90000.conv.23 `

in this way, can new tiny-yolo model make use of  weights of yolo model ？

thanks!

**Comment by AlexeyAB** [comment]
No, weights do not match between: tiny-yolo.cfg and yolo.2.0.cfg. Such fine-tuning will give you bad result.

**Comment by goodtogood** [comment]
that's to say there's no way to reuse yolo's weights for training tiny-yolo network?

**Comment by AlexeyAB** [comment]
Yes, there's no way.
