### ISSUE TITLE
Small object detection @1080p on Xavier AGX results & request for improvement suggestions?

### ISSUE THREAD

**Issue by pullmyleg** [AlexeyAB/darknet#5552]
Hi @AlexeyAB , I thought I should start a new issue as this is not related to the performance bug you fixed in #5234. Thanks for all your advice and sorry for the slow reply, it took me a couple of weeks to train all the different models on the different datasets. 

All models were trained at 1920x1088 on a V100 (32GB). The performance of yolov3-tiny-prn is great but it would be great if we can bring the accuracy up. Any suggestions to improve or other configurations to try?

I included some screenshots of dolphins being missed and examples of the data below. Accuracy is lower then the previous post as the testing dataset now only consists of small dolphins. 

For those who have just stumbled across this we are a not-for-profit ([MAUI63](http://maui63.org/)) and what we are doing is looking for the world's rarest dolphin (Maui) using object detection and a large UAV that flies at 120km/h. The higher we can fly and the smaller the objects (dolphins) we can detect the more area we can cover per flight. 

The goal is to find the model that performs the most accurately with the smallest objects possible from 1080p 30fps footage using a Jetson Xavier AGX. We need a minimum of 12FPS to be able to spot dolphins @120kmh but have found 20FPS+ is preferable and works better.

Name | Chart | mAP | Xavier @1920x1088 -benchmark | Dataset | Batch | Subdivisions | Random | Calc Anchors | Iterations 
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[yolo_v3_tiny_pan_lstm-sml-anc.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605135/yolo_v3_tiny_pan_lstm-sml-anc.cfg.txt) | ![chart_yolo_v3_tiny_pan_lstm-sml-anc](https://user-images.githubusercontent.com/42484083/81490530-a6a9ef00-92d7-11ea-9e0b-2e1902deea6c.png)| 64.00% |   | Small | 64 | 8 | N | y | 10200 
[yolo_v3_tiny_pan3_aa_ae_mixup_scale_giou-com.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605136/yolo_v3_tiny_pan3_aa_ae_mixup_scale_giou-com.cfg.txt) | ![chart_yolo_v3_tiny_pan3_aa_ae_mixup_scale_giou-com_final](https://user-images.githubusercontent.com/42484083/81490534-b1fd1a80-92d7-11ea-98ca-8554fc4780e9.png) | **75.00%** | 11.1FPS | Complete | 64 | 8 | N | N | 16800
[yolo_v3_tiny_pan3_aa_ae_mixup_scale_giou-sml.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605137/yolo_v3_tiny_pan3_aa_ae_mixup_scale_giou-sml.cfg.txt) |![chart_yolo_v3_tiny_pan3_aa_ae_mixup_scale_giou-sml_final](https://user-images.githubusercontent.com/42484083/81490539-c214fa00-92d7-11ea-9ec8-b7924ed360ff.png) | **77.00%** | 11.1FPS | Small | 64 | 8 | N | N | 12000
[yolo_v3_tiny_pan3_scale_giou-sml.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605139/yolo_v3_tiny_pan3_scale_giou-sml.cfg.txt)| ![chart_yolo_v3_tiny_pan3_scale_giou-sml](https://user-images.githubusercontent.com/42484083/81490557-e2dd4f80-92d7-11ea-8a0f-2ab6c38b444a.png) | **77.00%** | 12.6FPS | Small | 64 | 8 | N | N | 5000
[yolov3-tiny_3l_resize-com.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605140/yolov3-tiny_3l_resize-com.cfg.txt)| ![chart_yolov3-tiny_3l_resize-com](https://user-images.githubusercontent.com/42484083/81490564-fa1c3d00-92d7-11ea-8f74-f2d66dc93d62.png) | 49.00% | 16FPS | Complete | 64 | 16 | N | N | 8200
[yolov3-tiny_3l_resize-com-anc.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605141/yolov3-tiny_3l_resize-com-anc.cfg.txt) | ![chart_yolov3-tiny_3l_resize-com-anc](https://user-images.githubusercontent.com/42484083/81490570-191acf00-92d8-11ea-8f79-99387fe21c77.png) | 56.00% | 16FPS | Complete | 64 | 16 | N | Y | 13000
[yolov3-tiny_3l_resize-sml.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605142/yolov3-tiny_3l_resize-sml.cfg.txt)|![chart_yolov3-tiny_3l_resize-sml](https://user-images.githubusercontent.com/42484083/81490578-2a63db80-92d8-11ea-8ed8-20543e2c6693.png)| 53.00% | 16FPS | Small | 64 | 8 | N | N | 5600 
[yolov3-tiny_3l_resize-sml-anc.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605143/yolov3-tiny_3l_resize-sml-anc.cfg.txt)|![chart_yolov3-tiny_3l_resize-sml-anc_final](https://user-images.githubusercontent.com/42484083/81490625-bfff6b00-92d8-11ea-8854-ec94eea48a14.png) | 61.00% | 16FPS | Small | 64 | 8 | N | Y | 13800
[yolov3-tiny_3l_rotate_whole_maxout-com-anc.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605144/yolov3-tiny_3l_rotate_whole_maxout-com-anc.cfg.txt)|![chart_yolov3-tiny_3l_rotate_whole_maxout-com-anc](https://user-images.githubusercontent.com/42484083/81490632-d1e10e00-92d8-11ea-9180-d50eac4bf720.png)| 55.00% | 9.3FPS | Complete | 64 | 8 | N | Y | 20000 
[yolov3-tiny_3l_rotate_whole_maxout-sml-anc.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605145/yolov3-tiny_3l_rotate_whole_maxout-sml-anc.cfg.txt) |![chart_yolov3-tiny_3l_rotate_whole_maxout-sml-anc_final](https://user-images.githubusercontent.com/42484083/81490635-da394900-92d8-11ea-8d42-b4f64aa5380c.png) | 51.00% | 9.3FPS | Small | 64 | 8 | N | Y | 19000
[yolov3-tiny_3l_stretch_sway_whole_concat_maxout-sml-anc.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605146/yolov3-tiny_3l_stretch_sway_whole_concat_maxout-sml-anc.cfg.txt)|![chart_yolov3-tiny_3l_stretch_sway_whole_concat_maxout-sml-anc_final](https://user-images.githubusercontent.com/42484083/81490636-e1605700-92d8-11ea-9f47-c9fe1895b51f.png) | 68.00% | 6FPS | Small | 64 | 16 | N | Y | 28500
[yolov3-tiny-com.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605148/yolov3-tiny-com.cfg.txt)|![chart_yolov3-tiny-com](https://user-images.githubusercontent.com/42484083/81490640-eae9bf00-92d8-11ea-837f-cda098aaf2ad.png) | 68.00% | 22.5FPS | Complete | 64 | 8 | N | N | 7000
[yolov3-tiny-com-rdm.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605149/yolov3-tiny-com-rdm.cfg.txt)|![chart_yolov3-tiny-com-rdm](https://user-images.githubusercontent.com/42484083/81490645-f2a96380-92d8-11ea-96d1-50d77638e5c5.png) | 67.00% | 22.3FPS | Complete | 64 | 8 | Y | N | 7200
[yolov3-tiny-com-rdm-anc.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605151/yolov3-tiny-com-rdm-anc.cfg.txt)|![chart_yolov3-tiny-com-rdm-anc](https://user-images.githubusercontent.com/42484083/81490650-f937db00-92d8-11ea-8141-187b6b743b87.png) | 68.33% | 22.3FPS | Complete | 64 | 8 | Y | Y | 8300
[yolov3-tiny-prn-sml-rdm-anc.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605152/yolov3-tiny-prn-sml-rdm-anc.cfg.txt) |![chart_yolov3-tiny-prn-sml-rdm-anc](https://user-images.githubusercontent.com/42484083/81490654-00f77f80-92d9-11ea-8ead-44784f8f411e.png) | 68.00% | **24.8FPS** | Small | 64 | 8 | Y | Y | 11800
[yolov3-tiny-sml.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605153/yolov3-tiny-sml.cfg.txt) |![chart_yolov3-tiny-sml](https://user-images.githubusercontent.com/42484083/81490656-081e8d80-92d9-11ea-8a84-5af203023e43.png) | 68.00% | 22.2FPS | Small | 64 | 8 | N | N | 5400
[yolov3-tiny-sml-rdm.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605154/yolov3-tiny-sml-rdm.cfg.txt) |![chart_yolov3-tiny-sml-rdm](https://user-images.githubusercontent.com/42484083/81490658-0e146e80-92d9-11ea-8ce1-f8833d11a561.png) | 68.00% | 22.4FPS | Small | 64 | 8 | Y | N | 5800
[yolov3-tiny-sml-rdm-anc.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605155/yolov3-tiny-sml-rdm-anc.cfg.txt) |![chart_yolov3-tiny-sml-rdm-anc](https://user-images.githubusercontent.com/42484083/81490662-15d41300-92d9-11ea-8a98-099d67787165.png) | 68.00% | 22.4FPS | Small | 64 | 8 | Y | Y | 7400
[yolov4-sml.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605156/yolov4-sml.cfg.txt) |![chart_yolov4-sml](https://user-images.githubusercontent.com/42484083/81490666-1b315d80-92d9-11ea-8e64-06375376c0ee.png) | 78.00% | 2.3FPS | Small | 64 | 32 | N | N | 1800
[yolov4-sml-rdm.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605157/yolov4-sml-rdm.cfg.txt) |![chart_yolov4-sml-rdm](https://user-images.githubusercontent.com/42484083/81490674-1ff61180-92d9-11ea-9973-29d59493c015.png) | 81.00% | 2.3FPS | Small | 64 | 64 | Y | N | 2600
[yolo_v3_tiny_pan3_ciou_new-sml-rdm.cfg.txt](https://github.com/AlexeyAB/darknet/files/4676181/yolo_v3_tiny_pan3_ciou_new-sml-rdm.cfg.txt) |![chart_yolo_v3_tiny_pan3_ciou_new-sml-rdm](https://user-images.githubusercontent.com/42484083/82795320-f12a8e80-9ec7-11ea-8661-f7f0b0ed8d94.png)| 74.00% | 11.9 | Small | 64 | 16 | Y | N | 5100
[yolo_v3_tiny_pan3_ciou_new_stretch_sway-sml-rdm.cfg.txt](https://github.com/AlexeyAB/darknet/files/4676182/yolo_v3_tiny_pan3_ciou_new_stretch_sway-sml-rdm.cfg.txt) |![chart_yolo_v3_tiny_pan3_ciou_new_stretch_sway-sml-rdm](https://user-images.githubusercontent.com/42484083/82795402-14edd480-9ec8-11ea-8720-2e3096428a22.png)| 21.00% |   | Small | 64 | 32 | Y | N | 15000
[yolo_v3_tiny_pan3_ciou_new-com.cfg.txt](https://github.com/AlexeyAB/darknet/files/4676183/yolo_v3_tiny_pan3_ciou_new-com.cfg.txt) |![chart_yolo_v3_tiny_pan3_ciou_new-com](https://user-images.githubusercontent.com/42484083/82795427-1f0fd300-9ec8-11ea-9b9f-f899529460e5.png)| 69.00% | 11.9 | Complete | 64 | 8 | N | N | 6500
[yolov3-tiny-sml-mem.cfg.txt](https://github.com/AlexeyAB/darknet/files/4778723/yolov3-tiny-sml-mem.cfg.txt) |![chart_yolov3-tiny-sml-mem](https://user-images.githubusercontent.com/42484083/84630493-1bf48980-af40-11ea-8a1d-28e4869713fa.png)| 69.80%|22.2| Small | 112 | 2 | N | N |  

Examples of data / missed dolphins (red boxes). 

![2020-05-10_15-36-56](https://user-images.githubusercontent.com/42484083/81491089-04413a00-92de-11ea-9e1b-ea0515f8df46.png)
![2020-05-10_15-37-47](https://user-images.githubusercontent.com/42484083/81491092-05726700-92de-11ea-9e59-6505e273d319.png)
![2020-05-10_15-43-39](https://user-images.githubusercontent.com/42484083/81491093-06a39400-92de-11ea-8687-dfa6de71114c.png)
![2020-05-10_15-35-04](https://user-images.githubusercontent.com/42484083/81491095-073c2a80-92de-11ea-9039-3e3848d56728.png)

I have noticed it struggles with all angles of dolphins (as they turn), so I am going to create a new dataset based on more frames per second. Currently its using images from 6 frames per second. I could increase this to 10 or 20. This will increase training dataset size and potentially provide more angles of dolphins as they move. Any suggestion? I am guessing the more the better so will go for 20?

Note this training data is all I have at present, but the goal will be to detect much smaller dolphins, ideally (1/2 - 1/4) this size. Will need retraining.

 As always, thanks for the help and amazing repo.

**Comment by AlexeyAB** [comment]
> This will increase training dataset size and potentially provide more angles of dolphins as they move. Any suggestion? I am guessing the more the better so will go for 20?

Yes, collect as many images as possible.

Download the **latest** Darknet version.

Then try to train these 2 new models:
1. [yolo_v3_tiny_pan3_ciou_new.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605676/yolo_v3_tiny_pan3_ciou_new.cfg.txt)


2. [yolo_v3_tiny_pan3_ciou_new_stretch_sway.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605677/yolo_v3_tiny_pan3_ciou_new_stretch_sway.cfg.txt)

If Nan will occur, then set `adversarial_lr=0.001`

**Comment by pullmyleg** [comment]
Thanks @AlexeyAB . 

1. yolo_v3_tiny_pan3_ciou_new.cfg.txt is running now and I will post results once complete. 
2. yolo_v3_tiny_pan3_ciou_new_stretch_sway.cfg.txt after the first iteration causes an error: illegal memory access was encountered.

- Using the latest darknet, make clean, make. 
- The configuration is the same as you posted apart from I increased the subdivision to 32 (out of memory).

Screenshots with debug=0 below: 
![2020-05-11_8-55-52](https://user-images.githubusercontent.com/42484083/81510432-bec84f80-9365-11ea-9711-f13230d51b14.png)

![2020-05-11_8-54-51](https://user-images.githubusercontent.com/42484083/81510430-bd972280-9365-11ea-8593-e65b3eaefd6a.png)

**Comment by AlexeyAB** [comment]
> Screenshots with debug=0 below: 
> ![2020-05-11_8-55-52](https://user-images.githubusercontent.com/42484083/81510432-bec84f80-9365-11ea-9711-f13230d51b14.png)

* As I see you built Darknet with DEBUG=1
* As I see you built OpenCV in Debug mode too
* Rebuild OpenCV and Darknet in Release mode
* Rebuild Darknet with `DEBUG=0` in Makefile, try to train, and if it doesn' help, then show such screenshot again

**Comment by pullmyleg** [comment]
Hi @AlexeyAB done and the same result, please see below. I compiled with debug=0 to try and get more detailed error screenshots. 

![2020-05-11_9-40-31](https://user-images.githubusercontent.com/42484083/81511200-aa875100-936b-11ea-8a2f-e7dd3d3ace2b.png)
![2020-05-11_9-41-07](https://user-images.githubusercontent.com/42484083/81511202-abb87e00-936b-11ea-861e-3f844337f1ba.png)

**Comment by AlexeyAB** [comment]
I fixed it: https://github.com/AlexeyAB/darknet/commit/74134e5389f8804c1581988d3abe77bb0eb68537

**Comment by pullmyleg** [comment]
@AlexeyAB confirmed working now, Thanks!

**Comment by AlexeyAB** [comment]
* What is the Small and Complete datasets, what is the difference?
* Is it training or validation datasets?
* If thes are 2 different validation datasets, then do you use the same 1 Training dataset for all cases?

**Comment by pullmyleg** [comment]
@AlexeyAB 
- The 2 x datasets are different training datasets. Small & Complete. 
- All results are using the same validation dataset which is not included in the training set. 750 images. 40 - 50m drone height. 
- The small dataset is only images with really small dolphins. 40 - 50m height drone height. 3200 images.
- The Complete dataset includes small dataset images plus images with larger dolphins from lower height. 10m - 30m drone height. 900 images.

Small dataset examples: 
![image](https://user-images.githubusercontent.com/42484083/81512016-7020b280-9371-11ea-8112-8747bb96349b.png)

![image](https://user-images.githubusercontent.com/42484083/81512034-95152580-9371-11ea-9645-cc2cb356c830.png)

Complete dataset examples: 
![image](https://user-images.githubusercontent.com/42484083/81512052-b70ea800-9371-11ea-9812-40bbd8440baa.png)

![image](https://user-images.githubusercontent.com/42484083/81512079-e3c2bf80-9371-11ea-86e0-580e05b8bb02.png)

![image](https://user-images.githubusercontent.com/42484083/81512088-f50bcc00-9371-11ea-8cfe-d97182e2e0d5.png)

**Comment by AlexeyAB** [comment]
Ok, so also try to train 3rd model - the same  [yolo_v3_tiny_pan3_ciou_new.cfg.txt](https://github.com/AlexeyAB/darknet/files/4605676/yolo_v3_tiny_pan3_ciou_new.cfg.txt) 
but change these lines for each of 3 [yolo] layers
```
resize=0.2
random=0
```

try to set lower subdivisions, since you don't use random=1 for this model.
and train this model on **Complete** dataset.

----

Also 2 observations:

1. Since, for the most models, the mAP increases for ~20% max_batches and then decreases, it seems that your training dataset isn't representative, and you should add more training images.

2. Since Loss continues to decrease up to 80% of max_batches, for example for `yolo_v3_tiny_pan3_scale_giou-sml.cfg.txt`, so it seems that you can train this model longer

**Comment by pullmyleg** [comment]
@AlexeyAB thanks. 

1. I am training these 3 models in series now. Will post results in a few day's time when complete. 
2. I will also create a new small and complete dataset by extracting 4 x the frames from the videos. I will pseudo tag the images and review / re-tag them all manually. This will take a week or so :sweat_smile:.
3. I will then retrain high performing configurations on the new datasets.

**Comment by pullmyleg** [comment]
Using subdivisions 8 on below at 1920x1088 resolution slows training a lot due to CPU not being able to keep up 😅. Is there any way to utilise more than 6 threads or other suggestions to overcome the CPU bottleneck?

Current machine: 
Intel Xeon (Skylake) 2.6ghz x 16.
48GB Ram
Tesla V100 (32gb). 

>[yolo_v3_tiny_pan3_ciou_new.cfg.txt]
> ```
> resize=0.2
> random=0

![image](https://user-images.githubusercontent.com/42484083/81513051-9fd3b880-9379-11ea-9c9b-a344fa05ffcd.png)

I also found this performance issue due to the resolution I was using when trying to use the #4386 for bigger batch sizes on a larger VM then currently using.

**Comment by AlexeyAB** [comment]
Try to change 6 to 12 and recompile https://github.com/AlexeyAB/darknet/blob/74134e5389f8804c1581988d3abe77bb0eb68537/src/detector.c#L152

Do you use SSD or HDD disk?

**Comment by pullmyleg** [comment]
@AlexeyAB it is 3 x faster now thanks @ 12. 
I increased further to 16 and its even faster. Assuming this is safe? In the future can I increase to all available CPU if more then 16 are available? 

 @ 12:
![image](https://user-images.githubusercontent.com/42484083/81513666-27bbc180-937e-11ea-8390-2974e2a2b289.png)
@ 16:
![image](https://user-images.githubusercontent.com/42484083/81513750-b4ff1600-937e-11ea-841c-64b620bc8e26.png)

**Comment by AlexeyAB** [comment]
> I increased further to 16 and its even faster. Assuming this is safe? In the future can I increase to all available CPU if more then 16 are available?

Yes, but it's recommended to use `(max_cores - 2)`, so there will be at least 2 CPU-cores for interaction with GPU.

I just added minor fix, so you can un-comment first 2 lines, and comment 3rd line, it will use automatically `(max_cores - 2)` CPU-cores
https://github.com/AlexeyAB/darknet/blob/0c7305cf638bd0e692c6195e412aff93200000e4/src/detector.c#L152-L154

**Comment by pullmyleg** [comment]
Awesome - thanks.

**Comment by zys1994** [comment]
Can you tell me the meaning of com,prn,sml,edm,anc? Thanks @pullmyleg

**Comment by pullmyleg** [comment]
Hi @zys1994  most of this refers to columns in the graph and configuration settings.

Com and sml are different datasets. Anchors relate to different anchors used, you can see these in the configuration files. 

Rdm is random scaling used or not in the configuration.

PRN - partial residual networks. My understanding is it aims to maximise the combinations of gradients of different layers.

**Comment by zys1994** [comment]
Thank you very much for sharing @pullmyleg

**Comment by zys1994** [comment]
Thanks for your excellent work. I have retrained and  converted your yolo_v3_tiny_pan3_scale_giou-sml.cfg to openvino and got a Huge improvement. @pullmyleg

**Comment by pullmyleg** [comment]
@zys1994 thank @AlexeyAB, this is just publishing my results. Note there is more to come, I am in the process of training 3 different models.

**Comment by pullmyleg** [comment]
> I fixed it: [74134e5](https://github.com/AlexeyAB/darknet/commit/74134e5389f8804c1581988d3abe77bb0eb68537)

Hi @AlexeyAB, training final config 
[yolo_v3_tiny_pan3_ciou_new_stretch_sway-sml-rdm.cfg.txt](https://github.com/AlexeyAB/darknet/files/4637749/yolo_v3_tiny_pan3_ciou_new_stretch_sway-sml-rdm.cfg.txt) and it is crashing now at ~1500 iterations with: CUDA Error: an illegal memory access was encountered: File exists

![2020-05-16_15-09-14](https://user-images.githubusercontent.com/42484083/82109178-1a407600-9788-11ea-8485-b01f87194bc7.png)

Thanks for your help!

**Comment by AlexeyAB** [comment]
Try to remove `adversarial_lr=0.01`  from cfg-file and train from the begining.

**Comment by Jefflier** [comment]
@AlexeyAB 
Hi,how are you?thanks for your remarkable work in Deep Learning!l am using your yolo_v3_tiny_pan3_ciou_new_stretch_sway.cfg and use my own calculated anchors for training to detection Colorectal polyp,which is resize 512*512 and the width of object range for 5 to 150,also heights,but l get not very good results,see chart below.
Looking forward for your reply,thank you!
![yolo_v3_tiny_pan3_ciou_new_stretch_sway-chart](https://user-images.githubusercontent.com/45504633/82539367-eac2ac80-9b7f-11ea-8105-cc9769451929.png)

**Comment by Jefflier** [comment]
sorry,wrong chart.
![yolo_v3_tiny_pan3_ciou_new_stretch_sway-chart](https://user-images.githubusercontent.com/45504633/82539524-28273a00-9b80-11ea-85b8-04cb6c6825e4.png)

**Comment by AlexeyAB** [comment]
@Jefflier AP50 = 92% is a good result.

**Comment by Jefflier** [comment]
@AlexeyAB Thanks for your time,it is important how can yolo go further in small object detection?

**Comment by pullmyleg** [comment]
@AlexeyAB I have updated the chart above to include the results from 3 new suggested models. Best results the same to date :). 

Thing to note is we have calculated we really need a model that performs at > 20FPS on the Xavier AGX in order to find dolphins at 120km/h. This means we likely need to stay with a 2 layer model. 

1) I am training a large batch (56) yolov3-tiny model to see if this increases accuracy. Config also in table.
2) I am still in the process of creating a dataset with more frames. I Will update with progress. 

Any other suggestions or 2 layer models I should try to maintain speed but improve accuracy?

Thanks!

**Comment by toplinuxsir** [comment]
@pullmyleg  How to compile for Jetson Xavier ,Can you share your Makefile , Thanks !
```
GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=1
AVX=1
OPENMP=1
LIBSO=1

# Jetson XAVIER
ARCH= -gencode arch=compute_72,code=[sm_72,compute_72]
```

Is that right? Thanks!

**Comment by pullmyleg** [comment]
@toplinuxsir see below.

GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=1
AVX=0
OPENMP=1
LIBSO=0

Makefile for download: [Makefile.txt](https://github.com/AlexeyAB/darknet/files/4716115/Makefile.txt)

Also, I upgraded to OpenCV 4.2, here is the script if you want it: [install_opencv42.sh.txt](https://github.com/AlexeyAB/darknet/files/4716119/install_opencv42.sh.txt)

**Comment by toplinuxsir** [comment]
@pullmyleg  Thanks!

**Comment by moonlightian** [comment]
Hi@pullmyleg ,so thankful for your discussion and sharing.May I ask that have you calculated mAP for small object detection on Yolov4? If so,  how could that be implement by adjusting the code?

**Comment by pullmyleg** [comment]
Hi @moonlightian, you can see yolov4 implementation example I used above in the first post of this thread. Yolov4-sml-rdm.

**Comment by mbufi** [comment]
Hi @pullmyleg,

Great discussion and I think your use case is super cool! 

For the network cfg's you are training, where are you getting all the weights for these models? Are they all using yolov3-tiny as the base for them all?
**For instance: yolo_v3_tiny_pan3_aa_ae_mixup_scale_giou-sml.cfg.txt**

Where is the pretrained model and weights for this? 

Thank you!

**Comment by pullmyleg** [comment]
Hey @mbufi, thanks! 

Correct all based off the original [Yolov3-tiny.weights](https://github.com/AlexeyAB/darknet#how-to-train-tiny-yolo-to-detect-your-custom-objects). 

What you have just made me realised is that I was not adjusting them for the number of layers upon export. I will do some retraining and repost results. The 3L Yolo tiny models will all be somewhat incorrect and hopefully, get even better results. 

Thanks

**Comment by perceptoid** [comment]
Hey @pullmyleg,

Great discussion! In your current best performer [yolo_v3_tiny_pan3_scale_giou-sml](https://github.com/AlexeyAB/darknet/files/4605139/yolo_v3_tiny_pan3_scale_giou-sml.cfg.txt) I noticed that the anchor masks were reversed as opposed to standard YoloV3 cfg.

I.e.

```
########### [yolo-1]
mask = 0,1,2,3,4
########### [yolo-2]
mask = 4,5,6,7,8
########### [yolo-3]
mask = 8,9,10,11
```

as opposed to 

```
########### [yolo-1]
mask = 8,9,10,11
########### [yolo-2]
mask = 4,5,6,7,8
########### [yolo-3]
mask = 0,1,2,3,4
```

I also understand that this has been changed in YoloV4 where the masks are indeed reversed as opposed to V3. This might have caused the confusion (at least it confused me).

I tried training both (your version and one with reversed masks) on my own similar (scale wise) problem. Both ended with exactly the same performance, which baffled me.

Anyways, maybe something to look into.

Keep up the good work and keep the results streaming - very useful!

**Comment by Jefflier** [comment]
> Hey @pullmyleg,
> 
> Great discussion! In your current best performer [yolo_v3_tiny_pan3_scale_giou-sml](https://github.com/AlexeyAB/darknet/files/4605139/yolo_v3_tiny_pan3_scale_giou-sml.cfg.txt) I noticed that the anchor masks were reversed as opposed to standard YoloV3 cfg.
> 
> I.e.
> 
> ```
> ########### [yolo-1]
> mask = 0,1,2,3,4
> ########### [yolo-2]
> mask = 4,5,6,7,8
> ########### [yolo-3]
> mask = 8,9,10,11
> ```
> 
> as opposed to
> 
> ```
> ########### [yolo-1]
> mask = 8,9,10,11
> ########### [yolo-2]
> mask = 4,5,6,7,8
> ########### [yolo-3]
> mask = 0,1,2,3,4
> ```
> 
> I also understand that this has been changed in YoloV4 where the masks are indeed reversed as opposed to V3. This might have caused the confusion (at least it confused me).
> 
> I tried training both (your version and one with reversed masks) on my own similar (scale wise) problem. Both ended with exactly the same performance, which baffled me.
> 
> Anyways, maybe something to look into.
> 
> Keep up the good work and keep the results streaming - very useful!

yeah,me too.they all get maxmap=96%,it's confused.

**Comment by pullmyleg** [comment]
@perceptoid awesome thanks! Potentially @AlexeyAB can shed some light on the different mask arrangements in this config. Also a little baffled :). 

I have just posted 1 new result based on [using CPU memory](https://github.com/AlexeyAB/darknet/issues/4386) to train large batches. It was just a test not based on best model but I saw a ~1 - 2% increase in map. It took 2 weeks to train though.. But worth it if you want to squeeze that little bit extra out of your model! 

Because of the resolution of images/model I was still limited by the batch size but ended using about 84GB CPU memory, 31GB GPU memory with the config provided above.

**Comment by AlexeyAB** [comment]
anchors = 10,20, 40,50,, 100,200 - are sizes of objects in pixels
maks=0,1 - are indexies of anchors

[yolo] - layers with size (WxH) that 32 times smaller than the input network size - should use anchors bigger than 32x32

[yolo] - layers with size (WxH) that 16 times smaller than the input network size - should use anchors bigger than 16x16

It doesn’t matter in what order the layers go, what is the size of the layer.
