### ISSUE TITLE
Issues while training custom dataset in Google collab

### ISSUE THREAD

**Issue by sneha5gsm** [AlexeyAB/darknet#5554]
Hey everyone,
I wanted to train yolo on a custom dataset.
I have followed all the steps from the link 
https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects
1. I added the cfg changes by creating a new file yolo-obj.cfg in the directory build\darknet\x64\cfg with the required changes
2.Created obj.names file in build\darknet\x64\data
3. Created obj.data file in build\darknet\x64\data
4.Put .jpg and .txt files in build\darknet\x64\data\obj\
5. created train.txt in build\darknet\x64\data\  ex: data/obj/img1.jpg
I don't have a cuda supported GPU, so uploaded the folder to google collab and enabled GPU.
I tried to compile running the command 'make' in the main folder i.e /darknet
After this I couldn't run the following command in the same folder
!./darknet detector train data/obj.data yolo-obj.cfg yolov4.conv.137
It wasn't able to find obj.data file, so I tried the command:
./darknet detector train build/darknet/x64/data/obj.data build/darknet/x64/cfg/yolo-obj.cfg yolov4.conv.137
This seemed to work. But the collab notebook crashed after this stage with the following output:
----------------------------------------------
 GPU isn't used 
 OpenCV isn't used - data augmentation will be slow 
yolo-obj
mini_batch = 4, batch = 64, time_steps = 1, train = 1 
   layer   filters  size/strd(dil)      input                output
   0 conv     32       3 x 3/ 1   1024 x1024 x   3 -> 1024 x1024 x  32 1.812 BF
   1 conv     64       3 x 3/ 2   1024 x1024 x  32 ->  512 x 512 x  64 9.664 BF
   2 conv     64       1 x 1/ 1    512 x 512 x  64 ->  512 x 512 x  64 2.147 BF
   3 route  1 		                           ->  512 x 512 x  64 
   4 conv     64       1 x 1/ 1    512 x 512 x  64 ->  512 x 512 x  64 2.147 BF
   5 conv     32       1 x 1/ 1    512 x 512 x  64 ->  512 x 512 x  32 1.074 BF
   6 conv     64       3 x 3/ 1    512 x 512 x  32 ->  512 x 512 x  64 9.664 BF
   7 Shortcut Layer: 4,  wt = 0, wn = 0, outputs: 512 x 512 x  64 0.017 BF
   8 conv     64       1 x 1/ 1    512 x 512 x  64 ->  512 x 512 x  64 2.147 BF
   9 route  8 2 	                           ->  512 x 512 x 128 
  10 conv     64       1 x 1/ 1    512 x 512 x 128 ->  512 x 512 x  64 4.295 BF
  11 conv    128       3 x 3/ 2    512 x 512 x  64 ->  256 x 256 x 128 9.664 BF
  12 conv     64       1 x 1/ 1    256 x 256 x 128 ->  256 x 256 x  64 1.074 BF
  13 route  11 		                           ->  256 x 256 x 128 
  14 conv     64       1 x 1/ 1    256 x 256 x 128 ->  256 x 256 x  64 1.074 BF
  15 conv     64       1 x 1/ 1    256 x 256 x  64 ->  256 x 256 x  64 0.537 BF
  16 conv     64       3 x 3/ 1    256 x 256 x  64 ->  256 x 256 x  64 4.832 BF
  17 Shortcut Layer: 14,  wt = 0, wn = 0, outputs: 256 x 256 x  64 0.004 BF
  18 conv     64       1 x 1/ 1    256 x 256 x  64 ->  256 x 256 x  64 0.537 BF
  19 conv     64       3 x 3/ 1    256 x 256 x  64 ->  256 x 256 x  64 4.832 BF
  20 Shortcut Layer: 17,  wt = 0, wn = 0, outputs: 256 x 256 x  64 0.004 BF
  21 conv     64       1 x 1/ 1    256 x 256 x  64 ->  256 x 256 x  64 0.537 BF
  22 route  21 12 	                           ->  256 x 256 x 128 
  23 conv    128       1 x 1/ 1    256 x 256 x 128 ->  256 x 256 x 128 2.147 BF
  24 conv    256       3 x 3/ 2    256 x 256 x 128 ->  128 x 128 x 256 9.664 BF
  25 conv    128       1 x 1/ 1    128 x 128 x 256 ->  128 x 128 x 128 1.074 BF
  26 route  24 		                           ->  128 x 128 x 256 
  27 conv    128       1 x 1/ 1    128 x 128 x 256 ->  128 x 128 x 128 1.074 BF
  28 conv    128       1 x 1/ 1    128 x 128 x 128 ->  128 x 128 x 128 0.537 BF
  29 conv    128       3 x 3/ 1    128 x 128 x 128 ->  128 x 128 x 128 4.832 BF
  30 Shortcut Layer: 27,  wt = 0, wn = 0, outputs: 128 x 128 x 128 0.002 BF
  31 conv    128       1 x 1/ 1    128 x 128 x 128 ->  128 x 128 x 128 0.537 BF
  32 conv    128       3 x 3/ 1    128 x 128 x 128 ->  128 x 128 x 128 4.832 BF
  33 Shortcut Layer: 30,  wt = 0, wn = 0, outputs: 128 x 128 x 128 0.002 BF
  34 conv    128       1 x 1/ 1    128 x 128 x 128 ->  128 x 128 x 128 0.537 BF
  35 conv    128       3 x 3/ 1    128 x 128 x 128 ->  128 x 128 x 128 4.832 BF
  36 Shortcut Layer: 33,  wt = 0, wn = 0, outputs: 128 x 128 x 128 0.002 BF
  37 conv    128       1 x 1/ 1    128 x 128 x 128 ->  128 x 128 x 128 0.537 BF
  38 conv    128       3 x 3/ 1    128 x 128 x 128 ->  128 x 128 x 128 4.832 BF
  39 Shortcut Layer: 36,  wt = 0, wn = 0, outputs: 128 x 128 x 128 0.002 BF
  40 conv    128       1 x 1/ 1    128 x 128 x 128 ->  128 x 128 x 128 0.537 BF
  41 conv    128       3 x 3/ 1    128 x 128 x 128 ->  128 x 128 x 128 4.832 BF
  42 Shortcut Layer: 39,  wt = 0, wn = 0, outputs: 128 x 128 x 128 0.002 BF
  43 conv    128       1 x 1/ 1    128 x 128 x 128 ->  128 x 128 x 128 0.537 BF
  44 conv    128       3 x 3/ 1    128 x 128 x 128 ->  128 x 128 x 128 4.832 BF
  45 Shortcut Layer: 42,  wt = 0, wn = 0, outputs: 128 x 128 x 128 0.002 BF
  46 conv    128       1 x 1/ 1    128 x 128 x 128 ->  128 x 128 x 128 0.537 BF
  47 conv    128       3 x 3/ 1    128 x 128 x 128 ->  128 x 128 x 128 4.832 BF
  48 Shortcut Layer: 45,  wt = 0, wn = 0, outputs: 128 x 128 x 128 0.002 BF
  49 conv    128       1 x 1/ 1    128 x 128 x 128 ->  128 x 128 x 128 0.537 BF
  50 conv    128       3 x 3/ 1    128 x 128 x 128 ->  128 x 128 x 128 4.832 BF
  51 Shortcut Layer: 48,  wt = 0, wn = 0, outputs: 128 x 128 x 128 0.002 BF
  52 conv    128       1 x 1/ 1    128 x 128 x 128 ->  128 x 128 x 128 0.537 BF
  53 route  52 25 	                           ->  128 x 128 x 256 
  54 conv    256       1 x 1/ 1    128 x 128 x 256 ->  128 x 128 x 256 2.147 BF
  55 conv    512       3 x 3/ 2    128 x 128 x 256 ->   64 x  64 x 512 9.664 BF
  56 conv    256       1 x 1/ 1     64 x  64 x 512 ->   64 x  64 x 256 1.074 BF
  57 route  55 		                           ->   64 x  64 x 512 
  58 conv    256       1 x 1/ 1     64 x  64 x 512 ->   64 x  64 x 256 1.074 BF
  59 conv    256       1 x 1/ 1     64 x  64 x 256 ->   64 x  64 x 256 0.537 BF
  60 conv    256       3 x 3/ 1     64 x  64 x 256 ->   64 x  64 x 256 4.832 BF
  61 Shortcut Layer: 58,  wt = 0, wn = 0, outputs:  64 x  64 x 256 0.001 BF
  62 conv    256       1 x 1/ 1     64 x  64 x 256 ->   64 x  64 x 256 0.537 BF
  63 conv    256       3 x 3/ 1     64 x  64 x 256 ->   64 x  64 x 256 4.832 BF
  64 Shortcut Layer: 61,  wt = 0, wn = 0, outputs:  64 x  64 x 256 0.001 BF
  65 conv    256       1 x 1/ 1     64 x  64 x 256 ->   64 x  64 x 256 0.537 BF
  66 conv    256       3 x 3/ 1     64 x  64 x 256 ->   64 x  64 x 256 4.832 BF
  67 Shortcut Layer: 64,  wt = 0, wn = 0, outputs:  64 x  64 x 256 0.001 BF
  68 conv    256       1 x 1/ 1     64 x  64 x 256 ->   64 x  64 x 256 0.537 BF
  69 conv    256       3 x 3/ 1     64 x  64 x 256 ->   64 x  64 x 256 4.832 BF
  70 Shortcut Layer: 67,  wt = 0, wn = 0, outputs:  64 x  64 x 256 0.001 BF
  71 conv    256       1 x 1/ 1     64 x  64 x 256 ->   64 x  64 x 256 0.537 BF
  72 conv    256       3 x 3/ 1     64 x  64 x 256 ->   64 x  64 x 256 4.832 BF
  73 Shortcut Layer: 70,  wt = 0, wn = 0, outputs:  64 x  64 x 256 0.001 BF
  74 conv    256       1 x 1/ 1     64 x  64 x 256 ->   64 x  64 x 256 0.537 BF
  75 conv    256       3 x 3/ 1     64 x  64 x 256 ->   64 x  64 x 256 4.832 BF
  76 Shortcut Layer: 73,  wt = 0, wn = 0, outputs:  64 x  64 x 256 0.001 BF
  77 conv    256       1 x 1/ 1     64 x  64 x 256 ->   64 x  64 x 256 0.537 BF
  78 conv    256       3 x 3/ 1     64 x  64 x 256 ->   64 x  64 x 256 4.832 BF
  79 Shortcut Layer: 76,  wt = 0, wn = 0, outputs:  64 x  64 x 256 0.001 BF
  80 conv    256       1 x 1/ 1     64 x  64 x 256 ->   64 x  64 x 256 0.537 BF
  81 conv    256       3 x 3/ 1     64 x  64 x 256 ->   64 x  64 x 256 4.832 BF
  82 Shortcut Layer: 79,  wt = 0, wn = 0, outputs:  64 x  64 x 256 0.001 BF
  83 conv    256       1 x 1/ 1     64 x  64 x 256 ->   64 x  64 x 256 0.537 BF
  84 route  83 56 	                           ->   64 x  64 x 512 
  85 conv    512       1 x 1/ 1     64 x  64 x 512 ->   64 x  64 x 512 2.147 BF
  86 conv   1024       3 x 3/ 2     64 x  64 x 512 ->   32 x  32 x1024 9.664 BF
  87 conv    512       1 x 1/ 1     32 x  32 x1024 ->   32 x  32 x 512 1.074 BF
  88 route  86 		                           ->   32 x  32 x1024 
  89 conv    512       1 x 1/ 1     32 x  32 x1024 ->   32 x  32 x 512 1.074 BF
  90 conv    512       1 x 1/ 1     32 x  32 x 512 ->   32 x  32 x 512 0.537 BF
  91 conv    512       3 x 3/ 1     32 x  32 x 512 ->   32 x  32 x 512 4.832 BF
  92 Shortcut Layer: 89,  wt = 0, wn = 0, outputs:  32 x  32 x 512 0.001 BF
  93 conv    512       1 x 1/ 1     32 x  32 x 512 ->   32 x  32 x 512 0.537 BF
  94 conv    512       3 x 3/ 1     32 x  32 x 512 ->   32 x  32 x 512 4.832 BF
  95 Shortcut Layer: 92,  wt = 0, wn = 0, outputs:  32 x  32 x 512 0.001 BF
  96 conv    512       1 x 1/ 1     32 x  32 x 512 ->   32 x  32 x 512 0.537 BF

-------------------------------------
I have the following questions:
1. Was it correct to change the path to the obj.data file (./darknet detector train build/darknet/x64/data/obj.data build/darknet/x64/cfg/yolo-obj.cfg yolov4.conv.137)
Because it was not mentioned here https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects.
2. Did I place the data in the right folders i.e in  build\darknet\x64\data\obj\ or do I have to place it in \data folder (under the main folder).
3. Should I have put the path to image in the train.txt as  build/darknet/x64/data/obj/img1.jpg instead of data/obj/img1.jpg.?
4. Did I compile it correctly, in the right folder path?
5. How could I fix the runtime crash. I couldn't find any error logs in the runtime logs of google collab. I increased the RAM as well.
6. In my scenario, I have one class and I changed width=1024 height=1024 in my cfg-file (it is divisible by 32, it is also my image height, width), is it possible this would have caused the notebook to crash. I added a total of 3422 images.

I tried to run the same in kaggle, but I couldn't run anything in the input folder where I had uploaded the file as they are read only in kaggle.
 
Let me know your thoughts. :)

Thank you!

**Comment by waelausy** [comment]
Hello,
I think that uou must modify in the makefile file "OPENCV=1 and GPU=1" and "make" once more a time.
Goud luck

**Comment by sneha5gsm** [comment]
Thanks @waelausy !
After changing "OPENCV=1 and GPU=1 and CUDNN=1" , and making the file I was able to run it.

I did have a few path issues in files post that, after fixing those, I was able to run the model.
Thanks a lot :)

**Comment by SrikarNamburu** [comment]
@sneha5gsm can you post the final correct paths?

**Comment by SrikarNamburu** [comment]
[yolo] params: iou loss: ciou (4), iou_norm: 0.07, cls_norm: 1.00, scale_x_y: 1.05
nms_kind: greedynms (1), beta = 0.600000 
Total BFLOPS 59.570 
avg_outputs = 489910 
 Allocate additional workspace_size = 99.68 MB 
Loading weights from build/darknet/x64/yolov4.conv.137...
 seen 64, trained: 0 K-images (0 Kilo-batches_64) 
Done! Loaded 137 layers from weights-file 
Learning Rate: 0.001, Momentum: 0.949, Decay: 0.0005
Couldn't open file: /content/gdrive/MyDrive/darknet/build/darknet/x64/data/train.txt


I am getting this error.

**Comment by sneha5gsm** [comment]
Hey @SrikarNamburu 
The paths should be relative to the darknet.exe file. (Or darknet file in Linux)
In my case it was something like this:
 `darknet.exe detector train build/darknet/x64/data/obj.data train build/darknet/x64/cfg/yolo-obj.cfg train build/darknet/x64/yolov4.conv.137` (just use `./darknet` instead of `darknet.exe`)
   (i.e darknet.exe detector train (path-relative-to-darknet.exe obj.data) (path-relative-to-darknet.exe yolo-obj.cfg) (path-relative-to-darknet.exe yolov4.conv.137))

(darknet.exe = ./darknet in Linux)
