### ISSUE TITLE
[Question] How to train a subset of COCO dataset

### ISSUE THREAD

**Issue by taicaile** [AlexeyAB/darknet#5559]
Hello everyone,

I want to train a model detecting vehicles only, and I have extracted the vehicles imagest from COCO dataset.

I have several questions about the training process, hope someone can help me.

Question 1:
I want to confirm in this case which pre-trained weight I shall use:
  a, csdarknet53-omega.conv.105 - The first 105 layers from the pre-trained weights on ImageNet (ILSVRC2012):

  b, yolov4.conv.137

Question 2:

In case the need to add another class to vehicles such as tricycle. 
How many additional images do you recommend labeling, is around 2000 images?

For labeling an image, do I need to label all objects in the image? Can I only label one tricycle in an image(one image might include server tricycles and other type vehicles)?

Thanks.

**Comment by GargNishant** [comment]
For Question1:
I would go for yolo layers as mentioned in: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects point 0.
For Question2:
Recommended number of images is 2000 and each image should have atleast 1 Instance of the tricycle class and You will need to label all the tricycles in an image, otherwise, the model will degrade drastically.

**Comment by taicaile** [comment]
> For Question1:
> I would go for yolo layers as mentioned in: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects point 0.
> For Question2:
> Recommended number of images is 2000 and each image should have atleast 1 Instance of the tricycle class and You will need to label all the tricycles in an image, otherwise, the model will degrade drastically.

Hi, thanks for your answer.

May I know the reason the model will degrade if not all tricycles in an image were labeled?

And If an image include tricycles and cars, can I label tricycles only? Or I need to label all the objects that being detected?

**Comment by GargNishant** [comment]
Let's Say that there are 200 images and in each image there are 3 instance of tricycle. Now if you annotate only 1 instance in each image, the model will try to learn as, There are 3 object which are identical to each other, but only 1 is true others are false. As the three instance are identical, then the model will surely get confused on which is true and which is false, As same instance in same type of objects is true and false at the same time, in a single image

**Comment by taicaile** [comment]
> Let's Say that there are 200 images and in each image there are 3 instance of tricycle. Now if you annotate only 1 instance in each image, the model will try to learn as, There are 3 object which are identical to each other, but only 1 is true others are false. As the three instance are identical, then the model will surely get confused on which is true and which is false, As same type of objects is true and false at the same time, in a single image. At best case, it can learn through color pattern, but that's rare

Hi GargNishant,

Understood, now I know why I got a bad performance when I was trying to train Yolo with incorrect labeling.
