### ISSUE TITLE
opencv3 error

### ISSUE THREAD

**Issue by abeyang00** [AlexeyAB/darknet#556]
I'm trying to make the project but i get a opencv error, saying opencv is not found (Currently using ros kinetic so opencv 3.3 is automatically installed)
I have tried to changed makefile manaully by chaning

ifeq ($(OPENCV), 1) 
COMMON+= -DOPENCV
CFLAGS+= -DOPENCV 
LDFLAGS+= `pkg-config --libs opencv` 
COMMON+= `pkg-config --cflags opencv` 
endif

to

ifeq ($(OPENCV), 1) 
CFLAGS+= -I/opt/ros/kinetic/include
LDFLAGS+= -L/opt/ros/kinetic/lib -llibopencv_dnn.3.3.1.dylib -llibopencv_ml.3.3.1.dylib -llibopencv_objdetect.3.3.1.dylib -llibopencv_shape.3.3.1.dylib -llibopencv_stitching.3.3.1.dylib -llibopencv_superres.3.3.1.dylib -llibopencv_videostab.3.3.1.dylib -llibopencv_calib3d.3.3.1.dylib -llibopencv_features2d.3.3.1.dylib -llibopencv_highgui.3.3.1.dylib -llibopencv_videoio.3.3.1.dylib -llibopencv_imgcodecs.3.3.1.dylib -llibopencv_video.3.3.1.dylib -llibopencv_photo.3.3.1.dylib -llibopencv_imgproc.3.3.1.dylib -llibopencv_flann.3.3.1.dylib -llibopencv_core.3.3.1.dylib` 
endif

But i haven't able to make the project yet.
Ideas?

**Comment by AlexeyAB** [comment]
* What error do you get?
* What flags OPENCV, GPU, CUDNN, DEBUG, LIBSO do you use?
* Can you compile with OPENCV=1 and all other =0?

Try to use this
```
ifeq ($(OPENCV), 1)
COMMON+= -I/opt/ros/kinetic/include
CFLAGS+= -I/opt/ros/kinetic/include
LDFLAGS+= -L/opt/ros/kinetic/lib -llibopencv_dnn.3.3.1.dylib -llibopencv_ml.3.3.1.dylib -llibopencv_objdetect.3.3.1.dylib -llibopencv_shape.3.3.1.dylib -llibopencv_stitching.3.3.1.dylib -llibopencv_superres.3.3.1.dylib -llibopencv_videostab.3.3.1.dylib -llibopencv_calib3d.3.3.1.dylib -llibopencv_features2d.3.3.1.dylib -llibopencv_highgui.3.3.1.dylib -llibopencv_videoio.3.3.1.dylib -llibopencv_imgcodecs.3.3.1.dylib -llibopencv_video.3.3.1.dylib -llibopencv_photo.3.3.1.dylib -llibopencv_imgproc.3.3.1.dylib -llibopencv_flann.3.3.1.dylib -llibopencv_core.3.3.1.dylib`
endif
```

**Comment by abeyang00** [comment]
@AlexeyAB 
I have just tried your method and still failed.

I have few questions i want to ask,

1) /opt/ros/kinetic/lib folder contains files like libopencv_fuzzy3.so.3.3.1 libopencv_hdf3.so, etc...
Am i supposed to use the exact file name after LDFLAGS+= -L /opt/ros/kinetic/lib ??

![screenshot from 2018-04-02 22-28-12](https://user-images.githubusercontent.com/36392866/38197838-24ce8ca4-36c5-11e8-972f-0bf6ecfb1297.png)

2) Now i'm trying new method where i'm creating opencv.pc file inside pkg-config folder
opencv.pc file's content is as follows

![screenshot from 2018-04-02 22-27-41](https://user-images.githubusercontent.com/36392866/38197819-148773f6-36c5-11e8-981e-1688df07eb0f.png)

**Comment by AlexeyAB** [comment]
Do you have the file `/opt/ros/kinetic/opencv/opencv2/opencv.hpp`?
Find this file `opencv2/opencv.hpp` and specify path to it in the Cflags in the `opencv.pc`.

**Comment by abeyang00** [comment]
![screenshot from 2018-04-02 23-13-43](https://user-images.githubusercontent.com/36392866/38199368-878d656c-36cb-11e8-8f8a-e162cf85d5d6.png)

@AlexeyAB , should i add -I{includedir}/opencv-3.3.1/opencv2/opencv.hpp after Cflags?

**Comment by AlexeyAB** [comment]
Just change these lines: https://github.com/AlexeyAB/darknet/blob/726cebd3fb67d65ec6d2d49fa6bfba4c053085df/Makefile#L55-L57

To these:
```
ifeq ($(OPENCV), 1) 
COMMON+= -DOPENCV -I/opt/ros/kinetic/include/opencv-3.3.1/
CFLAGS+= -DOPENCV -I/opt/ros/kinetic/include/opencv-3.3.1/
```

**Comment by abeyang00** [comment]
@AlexeyAB 

Thank you, it succesfully compiled
