### ISSUE TITLE
Custom objects detection with Yolo v4

### ISSUE THREAD

**Issue by masa126** [AlexeyAB/darknet#5566]
Dear Sir,

When I change classes=80 to only 3 and filters=255 to 24 for three [yolo] layers shwon in the https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects
the darknet.exe aborted. When I use yolov4.cfg for 80 classes model, it works well.
The description about the modification for custom objects works well for yolo v3 but it might be different for yolo v4.
Will you kindly update the description for custom objects?
Best regrads,
Masataka

**Comment by AlexeyAB** [comment]
Show screenshot of the error?

> Will you kindly update the description for custom objects?

Do you mean I should show example of changing yolov4.cfg instead of yolov3.cfg?

**Comment by masa126** [comment]
![Darknet_aborted](https://user-images.githubusercontent.com/50834087/81567764-c1638d00-93d7-11ea-8112-7b4f139bc0ef.png)

Hi AlexeyAB,
Thank you for your quick response.
Here is the screen shot of Darknet.exe aborted.
I also attach the cfg file for ONE class model which I exectuted for the test.
This cfg file is based on the Yolo v3 config.
[yolov4_head.txt](https://github.com/AlexeyAB/darknet/files/4609884/yolov4_head.txt)
Yes, it is helpful to understand the required modification for yolo v4.
Thanks,
Masataka

**Comment by AlexeyAB** [comment]
I fixed it: https://github.com/AlexeyAB/darknet/commit/9cd44eea9513562c7247f4d5500d2471133f64b2

**Comment by masa126** [comment]
Hi AlexeyAB,
I updated parser.c as suggested.
One step foward but the other error happened for ONE class model.
![Darknet_error](https://user-images.githubusercontent.com/50834087/81571579-19e95900-93dd-11ea-9ba0-d1b23538cac9.png)

**Comment by masa126** [comment]
Hi AlexAB,
I understand my cause of trouble.
I deleted all my comments # from the cfg file.
Darknet.exe started to work.
Thank you so much.
