### ISSUE TITLE
VCPKG: Recompile library to effect changes to detector.h

### ISSUE THREAD

**Issue by teocns** [AlexeyAB/darknet#5569]
Hello,

sorry for the naive question, but I haven't found anything around and I have **no knowledge** about how **vcpkg** work.

I am on W10, and actively training a dataset with success, so far. I have made some changes to `detector.h` to save a backup every 100 iterations but it seems like I can't manage to recompile the solution, in order to effect the changes made to the file.

May I get any help with this? I am willing to pay as well for a solution.
Thank you anticipated.

**Comment by AlexeyAB** [comment]
Yes, 
try to run
`vcpkg\installed\x64-windows\tools\darknet\build.ps1`
https://github.com/AlexeyAB/darknet#how-to-compile-on-windows-using-cmake

**Comment by teocns** [comment]
@AlexeyAB thanks for the answer.

Sadly, there is no `build.ps1` that vcpkg created.

This is the directory content of `vcpkg\installed\x64-windows\tools\darknet` (from _Ubuntu WSL_):
```
avcodec-58.dll
avformat-58.dll
avutil-56.dll
backup
bad.list
cfg
chart.png
chart_yolov3-papersheet.png
cudnn64_7.dll
dark.dll
darknet.exe
darknet19_448.conv.23
darknet53.conv.74
data
directory.txt
jpeg62.dll
libpng16.dll
lzma.dll
opencv_calib3d.dll
opencv_core.dll
opencv_cudaarithm.dll
opencv_cudafilters.dll
opencv_cudaimgproc.dll
opencv_cudalegacy.dll
opencv_cudaoptflow.dll
opencv_cudawarping.dll
opencv_features2d.dll
opencv_flann.dll
opencv_highgui.dll
opencv_imgcodecs.dll
opencv_imgproc.dll
opencv_objdetect.dll
opencv_video.dll
opencv_videoio.dll
predictions.jpg
pthreadVC3.dll
swresample-3.dll
swscale-5.dll
tiff.dll
uselib.exe
uselib_track.exe
webp.dll
yolov2-tiny.weights
yolov2.weights
yolov3-tiny.weights
yolov3.weights
zlib1.dll
```

**Comment by cenit** [comment]
Hi! Where did you modify the source code? I mean, literally, in which folder?
I need this information in order to help you. 
If you modified the code inside the vcpkg/buildtrees folder, then it’s not going to work.
You directly modified the code of vcpkg, you did not develop a new application using Darknet library, am I right?
In this case, vcpkg is ok only for providing darknet dependencies, not Darknet itself.
You need to clone Darknet code from this repo, set an environment variable (VCPKG_ROOT) pointing to vcpkg folder, then build your own custom Darknet launching ./build.ps1 from the Darknet folder

Please let me know in case you need more informations

**Comment by teocns** [comment]
Hey @cenit thanks for the help!
I managed to compile it and it worked.
However, it seems that **GPU** isn't working on this version :/
So before I was running darknet from this folder: 
`C:\vcpkg\installed\x64-windows\tools\darknet`
I have followed your instructions and finally created a working build under:
`C:\darknet\`
Before running `.\build.ps1` I made sure to edit `Makefile`  accordingly:
```
GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=1
```
But when I run the same commands I used to run within the wrong version:
`.\darknet.exe detector train data\papersheet.data cfg\yolov3-papersheet.cfg backup\yolov3-paper
sheet_v3.weights`
I get this dreadful message on bootstrap:
```
 GPU isn't used
 Used AVX
 Used FMA & AVX2
 OpenCV version: 4.1.1
0
yolov3-papersheet
mini_batch = 1, batch = 64, time_steps = 1, train = 1
...
```
So yeah, GPU is a not used and this is not good. What changed from the previous (wrong) build I used to train with, to this one?

**Comment by cenit** [comment]
the makefile is totally out of scope for windows (it's the legacy build system for linux, but imho also linux should move to cmake).
the build.ps1 triggers cmake :)
Please show the log for building (delete the build_win_release subfolder and restart from scratch) and also attach the cmakecache.txt file that you find inside the build_win_release folder

**Comment by teocns** [comment]
[CMakeCache.txt](https://github.com/AlexeyAB/darknet/files/4614577/CMakeCache.txt)

Here's the PowerShell output: https://pastebin.com/CjKjrSB3
CMakeCache.txt is attached in this message!

**Comment by cenit** [comment]
Interesting: from the Powershell output you can see two apparently contradicting lines:
```
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - NOTFOUND
...
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2 (found suitable exact version "10.2"
```

In reality this is helping debugging your situation. In fact, you installed CUDA, because it is found, but you are missing CUDA integration with Visual Studio.
Could you please reinstall cuda and add VS integration?
Also, please update CMake to latest revision (but should not be necessary in your case)

**Comment by teocns** [comment]
This might be it!

I remember having had trouble installing **VS Integration**, so I just unchecked it from the installation.

For some reason, I always get this "_Failed_" output when attempting to install this feature:

![image](https://user-images.githubusercontent.com/59549574/81683118-f7475680-9455-11ea-9c2b-02c1bc51bb2f.png)

![image](https://user-images.githubusercontent.com/59549574/81683272-370e3e00-9456-11ea-8687-027049eccf1c.png)

**Comment by cenit** [comment]
Do you have Visual Studio 2019 (community, professional, enterprise) or Visual Studio 2019 Build Tools (command line tools)? In the second case, integration is not possible and we have to circumvent it. I did a special script in vcpkg to be able to build it anyway, we might have to do the same also in build.ps1 (if I didn't do it in both, I don't remember at the moment)

**Comment by teocns** [comment]
I have VS 2019 community installed.

**Comment by cenit** [comment]
mmm ok good. We still need to let you properly install vs integration for it to work. Can you verify you have the C++ workload properly installed in VS? The module you were highlighting is not enough

**Comment by teocns** [comment]
Well yeah, I think I have the workload installed. This is what I have by running VS 2019 Installer and choosing _"Modify"_

![image](https://user-images.githubusercontent.com/59549574/81692904-62495b00-945f-11ea-884f-022270966108.png)

**Comment by teocns** [comment]
@cenit little bump, wondering whether this can be solved in the easiest way possible. I'd also love to take a look at your workaround-script that ditches the VS/CUDA installation :)

**Comment by cenit** [comment]
sorry I was expecting for you to try to uninstall VS and reinstall it, mess around with your installation and try to fix it in order to have a working cuda installation.
Because technically what you have now is a broken CUDA installation.

Anyway, you can try this workaround, but I cannot guarantee you anything:
open the `build.ps1` script and modify the line

```
$use_ninja=$false
```

into

```
$use_ninja=$true
```

Since Ninja uses a different mechanism for CUDA detection, bypassing the VS CUDA Integration, it *might* work.

**Comment by cenit** [comment]
In case you don't have Ninja installed, please install it. Using Chocolatey, it's as simple as `cinst -y ninja`

**Comment by teocns** [comment]
@cenit thanks for the support.

I ran into dead-end errors by using the **Chocolatey** approach.
I manually cloned the [ninja-build repository](https://github.com/ninja-build/ninja) and built it from there. I had some issue which was caused by a double quotation in the _Path_ variable:

`"C:\Users\Redacted\AppData\Roaming\npm`

This was not visible by simply browsing `sysdm.cpl` GUI. Instead, I clicked on the _Path_ row, switched to _Edit Text_ and quotation mark was visible in **plain text** right there.

![image](https://user-images.githubusercontent.com/59549574/81845387-c5ff8100-9550-11ea-816c-07d59dd26bf6.png)

What led me here was the fact that I couldn't run the **VS command prompt** to compile _Ninja_. I used to get an error, such as:

`\Microsoft was unexpected at this time.`

And little research on this led to a **misconfigured** _Path_.

------------------------------------------------------------------------

Now going back to the main issue. Everything is set, ninja is in path, but CUDA COMPILER still cannot be found while running  `.\build.ps1`. I have attached the output accordingly.



[CMakeOutput.log](https://github.com/AlexeyAB/darknet/files/4623687/CMakeOutput.log)
[CMakeError.log](https://github.com/AlexeyAB/darknet/files/4623688/CMakeError.log)

**Comment by cenit** [comment]
Wow such an effort... good for you! Anyway, on the ninja-build GitHub page there was the release with the binary artifact, which was maybe easier to use ... :)

**Comment by cenit** [comment]
Can you show also the log on the command line?

**Comment by teocns** [comment]
The error says CUDACXX environment variable leads to no CUDA COMPILER.

![image](https://user-images.githubusercontent.com/59549574/81847384-cea58680-9553-11ea-8a1c-572f1877017d.png)
 

`PS C:\AI\darknet_better> .\build.ps1
Found vcpkg in VCPKG_ROOT: C:\AI\vcpkg
No default triplet has been set-up for vcpkg. Defaulting to x64-windows
Setting up environment to use CMake generator: Ninja


    Directory: C:\AI\darknet_better


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       13/05/2020     19:50                build_win_release
-- The C compiler identification is MSVC 19.25.28614.0
-- The CXX compiler identification is MSVC 19.25.28614.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - NOTFOUND
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Found PThreads4W: optimized;C:/AI/vcpkg/installed/x64-windows/lib/pthreadVC3.lib;debug;C:/AI/vcpkg/installed/x64-windows/debug/lib/pthreadVC3d.lib
-- PThreads4W_DLL_DIR: C:/AI/vcpkg/installed/x64-windows/include/../bin
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2 (found suitable exact version "10.2")
-- Found OpenCV: C:/AI/vcpkg/installed/x64-windows (found version "4.1.1")
-- Found Stb: C:/AI/vcpkg/installed/x64-windows/include
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- ZED SDK not enabled, since it requires CUDA
-- Configuring done
-- Generating done
-- Build files have been written to: C:/AI/darknet_better/build_win_release
[144/149] Linking CXX shared library dark.dll
   Creating library dark.lib and object dark.exp
[148/149] Install the project...
-- Install configuration: "Release"
-- Installing: C:/AI/darknet_better/dark.lib
-- Installing: C:/AI/darknet_better/dark.dll
-- Up-to-date: C:/AI/darknet_better/include/darknet/darknet.h
-- Up-to-date: C:/AI/darknet_better/include/darknet/yolo_v2_class.hpp
-- Installing: C:/AI/darknet_better/uselib.exe
-- Installing: C:/AI/darknet_better/darknet.exe
-- Installing: C:/AI/darknet_better/uselib_track.exe
-- Installing: C:/AI/darknet_better/share/darknet/DarknetTargets.cmake
-- Installing: C:/AI/darknet_better/share/darknet/DarknetTargets-release.cmake
-- Installing: C:/AI/darknet_better/share/darknet/DarknetConfig.cmake
-- Installing: C:/AI/darknet_better/share/darknet/DarknetConfigVersion.cmake`

**Comment by teocns** [comment]
This is the content of /bin (the folder where CUDACXX points to)
[log.txt](https://github.com/AlexeyAB/darknet/files/4623729/log.txt)

**Comment by teocns** [comment]
Well I solved the issue by changing
`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\`

to

`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe`

It now seems to be detecting it. I will let you know ASAP if I can train using GPU. 

Thanks for pointing me in the right direction.

**Comment by cenit** [comment]
Yes your cudacxx variable was broken. It has to point to nvcc, not to its folder.

**Comment by teocns** [comment]
Yep everything seems to work! Hope this helps also for future trainers.
