### ISSUE TITLE
YOLOv4 build.ps1 default build issue

### ISSUE THREAD

**Issue by NHarishGit** [AlexeyAB/darknet#5571]
@AlexeyAB 

Can't thank you enough for doing so much, so much, I mean really so so so very much.
Thank you, appreciate, all the dinners and lunches you sacrifice for all of us, on a regular basis.

I started making a build and it turns out 
"$use_vcpkg=$true" is set to true by default in the latest commit and it breaks the build if user doesn't want to use VCPKG.

https://github.com/AlexeyAB/darknet/blob/9cd44eea9513562c7247f4d5500d2471133f64b2/build.ps1#L4

Thank you billion times billion.
Nitin Harish

**Comment by AlexeyAB** [comment]
It is set 11 months ago: https://github.com/AlexeyAB/darknet/blame/9cd44eea9513562c7247f4d5500d2471133f64b2/build.ps1#L4

How does it break build? What is the error message?

**Comment by NHarishGit** [comment]
![image](https://user-images.githubusercontent.com/57957650/81618125-bc411680-93b4-11ea-8841-cc7ddf5a3fb0.png)

**Comment by NHarishGit** [comment]
Setting "$use_vcpkg=$true", I can happily build. From the readme file, it sounded like user can choose NOT to build with VCPKG by default.

**Comment by AlexeyAB** [comment]
@cenit Hi, What could be the reason?

**Comment by VisionEp1** [comment]
just adding into that:
i could reproduce it with the fresh win 10 install i did last time. 

Then i used cmake manually again

**Comment by cenit** [comment]
Can you please try #5632 and tell me if it fixes your issues?

**Comment by NHarishGit** [comment]
@cenit, I confirm, it fixed my issue. Please go ahead and merge. Thank you so very much.
