### ISSUE TITLE
如何轉換darknet訓練完成的weight to h5檔

### ISSUE THREAD

**Issue by fuzkuan** [AlexeyAB/darknet#5572]
我想要將darknet訓練完的權重移到keras上使用，請問有人知道怎麼做嗎?

**Comment by bfdxy12138** [comment]
请问可以问一下您是怎么解决的么？

**Comment by fuzkuan** [comment]
@bfdxy12138 如果是v3 google一下可以找到相關轉換的code 
v4目前可能還沒有人寫轉換的code，但你可以使用darknet.py 來利用python執行py檔

**Comment by bfdxy12138** [comment]
@fuzkuan 谢谢！
