### ISSUE TITLE
Tesla T4  FPS Slow down

### ISSUE THREAD

**Issue by yangwithtao** [AlexeyAB/darknet#5584]
Hello，AlexeyAB，What problems for me？
When I use Tesla T4, FPS will gradually slow down. But GTX 1080 will not be like this.

code ，use yolo_cpp_dll

	Detector detector("models/coco/yolov3.cfg", "models/coco/yolov3.weights", 1);
	cv::Mat frame = cv::imread("person.jpg");
	while (1) {
		clock_t detect_begin = clock();
		std::vector<bbox_t> result_vec = detector.detect(frame);
		clock_t detect_end = clock();	
		int t = detect_end - detect_begin;
		int fps = 1000 / t;
		std::cout << fps << " FPS  " <<  t << " ms"<< std::endl;
	}	

Finally, Tesla T4 only 10 FPS

![批注 2020-05-13 112419](https://user-images.githubusercontent.com/19373734/81768866-a9daf000-950e-11ea-8b29-3143ae88cb1c.jpg)

![批注 2020-05-13 1124191](https://user-images.githubusercontent.com/19373734/81768934-d4c54400-950e-11ea-9df6-d502ad78cb9d.jpg)

![批注 2020-05-13 1124192](https://user-images.githubusercontent.com/19373734/81768943-db53bb80-950e-11ea-9231-fdcde707c1af.jpg)

GTX 1080，no slow

![批注 2020-05-13 113055](https://user-images.githubusercontent.com/19373734/81769209-97ad8180-950f-11ea-84eb-40fb1f326aa0.jpg)

Tesla T4 is not released?
How do i solve this problem？

**Comment by AlexeyAB** [comment]
Use `auto start = std::chrono::steady_clock::now();` instead of `clock_t detect_begin = clock();`
`clock();` does not work correctly.

Use this code: https://github.com/AlexeyAB/darknet/blob/master/src/yolo_console_dll.cpp#L668-L684

**Comment by yangwithtao** [comment]
Thanks，I have use this code：yolo_console_dll.cpp.But the problem is not solved. 
When I use Tesla T4, run for a while, FPS slow down and Volatile GPU-Util have 95%.
GTX1080，GTX1650 no this problem.

**Comment by AlexeyAB** [comment]
Or you made mistake in the source code.
Or your GPU is overheated.

**Comment by yangwithtao** [comment]
Thanks, My GPU is overheated. I have solved it.
