### ISSUE TITLE
function activate_array_cpu_custom in gemm.c likely do leaky activation twice on AVX2 CPU

### ISSUE THREAD

**Issue by colinlin1982** [AlexeyAB/darknet#5591]
The code is:
```cpp
    else if (a == LEAKY)
    {
        if (is_fma_avx2()) {
            __m256i all256_sing1 = _mm256_set_epi32(0x80000000, 0x80000000, 0x80000000, 0x80000000, 0x80000000, 0x80000000, 0x80000000, 0x80000000);
            __m256 all256_01 = _mm256_set1_ps(0.1F);

            for (i = 0; i < n - 8; i += 8) {
                //x[i] = (x[i]>0) ? x[i] : .1*x[i];

                __m256 src256 = _mm256_loadu_ps(&x[i]);
                __m256 mult256 = _mm256_mul_ps((src256), all256_01); // mult * 0.1

                __m256i sign256 = _mm256_and_si256(_mm256_castps_si256(src256), all256_sing1); // check sign in 8 x 32-bit floats

                __m256 result256 = _mm256_blendv_ps(src256, mult256, _mm256_castsi256_ps(sign256)); // (sign>0) ? src : mult;
                _mm256_storeu_ps(&x[i], result256);
            }
        }

        for (; i < n; ++i) {
            x[i] = (x[i]>0) ? x[i] : .1*x[i];
        }
    }
```
Is the "if (is_fma_avx2())" block doing the same thing as "for (; i < n; ++i)" block? 
So does it mean there miss a "else" ?

**Comment by AlexeyAB** [comment]
```cpp
        for (; i < n; ++i) {
            x[i] = (x[i]>0) ? x[i] : .1*x[i];
        }
```
is equal to
```cpp
if(i < n) {
        for (i = n-8; i < n; ++i) {
            x[i] = (x[i]>0) ? x[i] : .1*x[i];
        }
}
```

**Comment by colinlin1982** [comment]
I got it, thank you very much.
BTW, when I calculate map with cpu/gpu for the same dataset and model weights, the map@0.5 are different, that's why I found this code. 

Another question is, when I test yolov3-tiny(5.4BF) on i7-8700, the cpu usage is 70%, while I test another network(let's call it netB, 1.5BF) , the cpu usage is only 60%, and it takes the same time as yolov3-tiny. Test on GPU(GTX1060 6G) takes same time too.

netB has conv3, conv1, 15 shortcut layers, 17 route layers, maxpool, upsample and 3 yolo layers, without group conv layers. I'm sorry I cannot post the cfg file here.

I'm wondering why the netB run so slowly. Do you have any suggestion?

**Comment by colinlin1982** [comment]
I run both model on python-opencv with i7-8700, netB cost 20ms while yolov3-tiny cost 30ms.
