### ISSUE TITLE
Performance bottleneck on CPU or Disk HDD/SSD Google Colab

### ISSUE THREAD

**Issue by Adrian398** [AlexeyAB/darknet#5592]
Hello,

My training on colab is not efficient in the beginning. I connected my drive to colab with the following code: 

from google.colab import drive
drive.mount('/content/drive')

import os
ROOT_DIR = "/content/drive/My Drive/"
os.chdir(ROOT_DIR)
os.chdir(os.path.join(ROOT_DIR, "YOLOv4_auto_polyp/darknet"))

After that I started training: 
For the first 500- 1000 iterations Coab is loading my images very slow and yolov4 makes the following output: 

Loaded: 10.038190 seconds - performance bottleneck on CPU or Disk HDD/SSD

after 1000 iteration it says:

Loaded: 0.006 seconds and everything is processing fine.

Any thoughts?

**Comment by AlexeyAB** [comment]
Dataset was cached in CPU-RAM, everything is fine

**Comment by Adrian398** [comment]
Ah yes! Thank you! Does the loading I mentioned above include data augmentation?
