### ISSUE TITLE
where can I find the pretrained backbone without mish？ 

### ISSUE THREAD

**Issue by PengfeiMa** [AlexeyAB/darknet#5593]
Hi, @AlexeyAB , your work is very great! But I want to train a yolov4 model without mish, where can I find the pretrained backbone without mish？

**Comment by AlexeyAB** [comment]
https://drive.google.com/open?id=1ULnPnamS5A6lOgidlBXD24IdxoDAFaaV

then do
`./darknet partial cfg/csdarknet53-omega.cfg csdarknet53-omega_final.weights csdarknet53-omega.conv.105 105`

**Comment by WongKinYiu** [comment]
@AlexeyAB 

> `./darknet partial cfg/csdarknet53-omega.cfg csdarknet53-omega_final.weights csdarknet53-omega.conv.105 105`

i think it should be `./darknet partial cfg/cd53paspp-gamma.cfg cd53paspp-gamma_final.weights cd53paspp-gamma.conv.137 137`

**Comment by PengfeiMa** [comment]
OK, thanks @AlexeyAB @WongKinYiu
