### ISSUE TITLE
Incorrect detection after training yolov4 on custom dataset

### ISSUE THREAD

**Issue by stanislavkuskov** [AlexeyAB/darknet#5598]
Hi @AlexeyAB !
After training yolo4 on custom dataset i have many random detections on different parts of image
![Screenshot from 2020-05-14 16-12-53](https://user-images.githubusercontent.com/11808566/81938626-d6ba0080-95fd-11ea-995e-377f0c33b2e3.png)

Training process correct. After training yolo3 with same dataset detector work correct.

**Comment by AlexeyAB** [comment]
* What date of darknet do you use for training? (when did you downloa darknet?)
* Show chart.png
* Show such screenshot
![image](https://user-images.githubusercontent.com/4096485/81870067-d37f3000-957d-11ea-8404-34babaa4fa9c.png)

* Show training command
* attach cfg-file in zip archive

**Comment by stanislavkuskov** [comment]
1. From Your repository https://github.com/AlexeyAB/darknet, 1 may.
2. Have no chart. My final loss ~0.23 after 3000 iterations (single class)
3. 
![Screenshot from 2020-05-14 01-22-59](https://user-images.githubusercontent.com/11808566/81872052-b187ac80-9581-11ea-9a84-5ba82d5240c5.png)

4. ./darknet detector train train_cases/cod/cod.data train_cases/cod/yolov4.cfg train_cases/cod/yolov4.conv.137
5. 
[yolov4.zip](https://github.com/AlexeyAB/darknet/files/4625038/yolov4.zip)

**Comment by AlexeyAB** [comment]
* What mAP do you get on training and validation datasets?
* Run training with `-show_imgs` flag at the end of training command, do you see correct bboxes?

**Comment by stanislavkuskov** [comment]
mean average precision (mAP@0.50) = 0.984007, or 98.40 % - for val. 
(./darknet detector map train_cases/cod/cod.data train_cases/cod/yolov4.cfg train_cases/cod/backup/yolov4_3000.weights)

with -show_images ok but images looks squeezed per x
![aug_1928450790_0_866246150](https://user-images.githubusercontent.com/11808566/81875020-f6aedd00-9587-11ea-9de2-3a5da47ba5bf.jpg)

Learning rate try to change in the end, when loss stop decrease.

**Comment by AlexeyAB** [comment]
Show again training and detection command.
Check that you use correct cfg and weights files during detection.

**Comment by buimanhlinh96** [comment]
i think it's threshold problem!!(confident score)

**Comment by AlexeyAB** [comment]
Calculate mAP ans show screenshot

**Comment by stanislavkuskov** [comment]
mAP:
![Screenshot from 2020-05-14 15-41-20](https://user-images.githubusercontent.com/11808566/81935603-93f62980-95f9-11ea-9ccc-ff6d8ffaa521.png)

Train cmd: ./darknet detector train train_cases/cod/cod.data train_cases/cod/yolov4.cfg train_cases/cod/yolov4.conv.137

I think i find problem. Whrn i change config its start work. I think difference between yolov4.cfg and yolov4-custom.cfg
In .zip my configs.
[yolov4_cfgs.zip](https://github.com/AlexeyAB/darknet/files/4628533/yolov4_cfgs.zip)

@AlexeyAB Thank You for help and for Your great work!

**Comment by AlexeyAB** [comment]
You must use the same 1 cfg-file for both training and detection.

**Comment by stanislavkuskov** [comment]
This situation happens becaus in my config file 80 classes, but i train with 1. It happens when i use darknet_video.py
