### ISSUE TITLE
Memory Leak:?

### ISSUE THREAD

**Issue by apiszcz** [AlexeyAB/darknet#56]
COMMAND LINE
darknet detector demo data/coco.data cfg/yolo.cfg C:/g/vx/data/model/yolo/yolo.weights -i 0 -thresh 0.1 test.mp4 -s 5

Process memory was > 15GB and then 
OpenCV Error: Insufficient memory (Failed to allocate 6220800 bytes) in cv::OutOfMemoryError, file C:\builds\2_4_PackSlave-win64-vc12-shared\opencv\modules\core\src\alloc.cpp, line 52

**Comment by AlexeyAB** [comment]
1. Does this error occur every time it starts `darknet.exe detector demo ... test.mp4 -s 5`?
2. Does this error occur if you start `yolo_console_dll.exe` and then you type `test.mp4`?
3. What is the duration of this video?

**Comment by apiszcz** [comment]
1. it occurs after processing a while perhaps 10-15 minutes. I did not time it, and there is no frame counter yet.
2. I'll need to test.
3. 60 minutes

**Comment by apiszcz** [comment]
Command line test

yolo_console_dll.exe
test.mp4

C:\yolo\yolo_cmd>dir /b
data
yolo-voc.cfg
yolo-voc.weights
yolo_console_dll.exe
yolo_cpp_dll.dll

C:\yolo\yolo_cmd>dir /b data
coco.names
dog.jpg
eagle.jpg
giraffe.jpg
goal.txt
horses.jpg
imagenet.labels.list
imagenet.shortnames.list
labels
person.jpg
scream.jpg
voc.names

**Comment by AlexeyAB** [comment]
@apiszcz 

> 2. Using the cmd line no labels are detected, memory appears constant at 2GB.

I.e. detection doesn't work by using console application that used DLL, isn't it? 
Can you show what output to console when you run  `yolo_console_dll.exe` and then you enter `test.mp4`?

**Comment by AlexeyAB** [comment]
After some fixes I tested Yolo with 2 hours of video and there isn't notable memory leak now.
