### ISSUE TITLE
Detection on GPU or CPU

### ISSUE THREAD

**Issue by sensationTI** [AlexeyAB/darknet#5600]
Does `darknet.exe detector test data/obj.data yolo-obj.cfg yolo-obj_8000.weights` use GPU or CPU?

**Comment by pullmyleg** [comment]
Both, it depends on how you have compiled the project.

**Comment by sensationTI** [comment]
> Both, it depends on how you have compiled the project.

So if I compile the project using visual studio's release and X64, what is it using?

**Comment by pullmyleg** [comment]
Post the output after running the above command and I can tell you :). darknet.exe detector test data/obj.data yolo-obj.cfg yolo-obj_8000.weights.

It will also depend if you the [requirements](https://github.com/AlexeyAB/darknet#requirements) installed. It will compile based on what's available / what it can find on your machine.

It will say GPU is used or not straight after running the command.

**Comment by sensationTI** [comment]
![1](https://user-images.githubusercontent.com/26159563/81982828-5f39a080-9600-11ea-950b-d7daf20d3d47.PNG)

I see things like CUDA, cuDNN, GPU count, so is it using GPU?


> Post the output after running the above command and I can tell you :). darknet.exe detector test data/obj.data yolo-obj.cfg yolo-obj_8000.weights.
> 
> It will also depend if you the [requirements](https://github.com/AlexeyAB/darknet#requirements) installed. It will compile based on what's available / what it can find on your machine.
> 
> It will say GPU is used or not straight after running the command.

**Comment by pullmyleg** [comment]
Yes you are using GPU in above screenshot.
