### ISSUE TITLE
Question about detecting small objects.

### ISSUE THREAD

**Issue by utkutpcgl** [AlexeyAB/darknet#5607]
As far as I know, when we increase the stride value of convolution, we lose information, hence, it gets harder to understand smaller objects. Here it says, to train for smaller objects, stride should be changed from 2 to 4, which means more loss of information [https://github.com/AlexeyAB/darknet#how-to-improve-object-detection]. Did I miss something? I assume that we do not aim to detect large objects after training on small objects.

**Comment by ttdd11** [comment]
@utkutpcgl Also wondering about this

**Comment by AlexeyAB** [comment]
>  stride should be changed from 2 to 4, which means more loss of information

This is true for **subsampling** (stride=2 for maxpool, convolutional, ...), but vice versa for **upsampling** (stide=2 for upsample, deconvolutional, ...)

**Comment by utkutpcgl** [comment]
@AlexeyAB Thanks!
