### ISSUE TITLE
cann't load darknet.sln onwindows but can load and compile the darknet_no_gpu.sln

### ISSUE THREAD

**Issue by xiaosuzhang** [AlexeyAB/darknet#561]
Hi，I run on VS2015 community cuda 8.0 and cudnn 6.
when i strat the VS2015, the darknet.sln cann't load ,some error happend:
The project requires user input.Reload the project for more information。
But i can load  and compile darknet_no_gpu.sln.

**Comment by xiaosuzhang** [comment]
I have resolved this problem

**Comment by vishesh9494** [comment]
Can you please tell me how?

Thanks!
