### ISSUE TITLE
Multiple detection simultaneously from 3 cameras

### ISSUE THREAD

**Issue by AlgirdasKartavicius** [AlexeyAB/darknet#5612]
I am developing solution for real-time objects detection. I currently have to detect objects from 3 cameras simultaneously. I can not initialize more than one model in same program. Do you have any suggestions how to solve this problem?

**Comment by NHarishGit** [comment]
Depending on your camera resolutions and how near real time you want to get and what hardware support you have:

**Suggestion #1**: Stitch all 3 camera feeds together and send one large image as input to YOLO.

**Suggestion #2**: Send 1 camera feed at a time in series (one after another)

**Suggestion #3**: Run 3 instances of YOLO (darknet.exe) with 3 individual camera feeds as inputs to them.

**Comment by AlexeyAB** [comment]
Just Run 3 instances of YOLO (darknet.exe) with 3 individual camera feeds as inputs to them.
