### ISSUE TITLE
specified GPU ,  it  still occupy other GPUS' memory resources, why?

### ISSUE THREAD

**Issue by zzm422** [AlexeyAB/darknet#5626]
I have 7 GPUS . why specified GPU "-gpus 5,6",   it  still occupy  other GPUS about 10M of memory resources when training. How to solve this question,could you do me a favor,tks

 ----------------------------------------------------------------------------+
| NVIDIA-SMI 418.74       Driver Version: 418.74       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:04:00.0 Off |                  N/A |
| 25%   22C    P8    15W / 250W |     10MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:05:00.0 Off |                  N/A |
| 25%   27C    P8    11W / 250W |     10MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:08:00.0 Off |                  N/A |
|  0%   23C    P8     8W / 250W |     10MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  Off  | 00000000:09:00.0 Off |                  N/A |
| 25%   20C    P8    10W / 250W |     10MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 108...  Off  | 00000000:85:00.0 Off |                  N/A |
| 23%   20C    P8     8W / 250W |     10MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 108...  Off  | 00000000:86:00.0 Off |                  N/A |
| 26%   54C    P2   176W / 250W |   6217MiB / 11178MiB |     94%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX 108...  Off  | 00000000:89:00.0 Off |                  N/A |
| 23%   48C    P2   233W / 250W |   6217MiB / 11178MiB |     93%      Default |
+-------------------------------+----------------------+----------------------+
|   7  GeForce GTX 108...  Off  | 00000000:8A:00.0 Off |                  N/A |
| 23%   21C    P8     8W / 250W |     10MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by WongKinYiu** [comment]
in this case, you can use `CUDA_VISIBLE_DEVICES=5,6 ./darknet ... -gpus 0,1` instead of use `-gpus 5,6`.

**Comment by zzm422** [comment]
hi,WongKinYiu, thank you, it's works.

**Comment by VisionEp1** [comment]
one quick question does 
CUDA_VISIBLE_DEVICES 
work on windows as well or only on Linux ?
