### ISSUE TITLE
Process to find small objects

### ISSUE THREAD

**Issue by ttdd11** [AlexeyAB/darknet#5630]
V4 look amazing.

I'm wondering generally what the process looks like to use yolov4 on small objects.

In addition to following the process for custom objects, the recommendation is we increase the output stride and increase the network size.

Is there also a requirement to change the anchors?

**Comment by AlexeyAB** [comment]
> Is there also a requirement to change the anchors?

Yes, if you understand how does it work.

Also you can add `max=200` for each [yolo] layer.

**Comment by ttdd11** [comment]
@AlexeyAB Alright I'll give this a try.

When training I get Realloc error. Have you seen this before? I'm running a very similar config to yolov4-custom.cfg with height = 608 and width = 608. I'm also using Titan RTX cards that have 24 gigs of memory.

**Comment by AlexeyAB** [comment]
Show fullscreen screenshot of this error.

**Comment by ttdd11** [comment]
![train_command](https://user-images.githubusercontent.com/39801645/82060686-8f268980-967c-11ea-8eaa-1b66f5782990.jpg)

![error](https://user-images.githubusercontent.com/39801645/82060692-92ba1080-967c-11ea-8043-6cc5677cc140.png)

**Comment by AlexeyAB** [comment]
* Did you change anything in the source code?

* Do you use 2 or 1 GPU for training?

* What command do you use for training?


* Try to use the latest Darknet version

* Try to train another model with this dataset

* Attach your cfg-file

**Comment by ttdd11** [comment]
1. Changed n-threads to 12 instead of 6 (thread ripper cpu can keep up)
2. 1 GPU (even though I would like to use 4, but starting with this until 1000 iterations)
3. Training command: darknet.exe detector train data/obj.data yolo-obj1.cfg yolov4.conv.137
4. I will try that now, however this version is about 1 week old.
5. Smaller models will work
6. Config is attached 
[yolo-obj1.txt](https://github.com/AlexeyAB/darknet/files/4634960/yolo-obj1.txt)

**Comment by AlexeyAB** [comment]
> I will try that now

* Try it without your changes.
* check files bad.list and bad_label.list
* try to comment `mosaic=1` in cfg-file
* try to set subdivisions=64

Does it help?

**Comment by ttdd11** [comment]
@AlexeyAB recompile from source.
-changing the number of threads had no effect
-I could not find files called bad.list or bad_label.list
-comment mosaic=1 no change
-change subdivisions to 64 and it work.

What is the impact of subdivisions from from 16 to 64? Current memory usage of the gpu is about 8 gig.

**Comment by AlexeyAB** [comment]
`mini_batch_size = batch / subdivisions`
The higher mini_batch - the more GPU memory is required.

Titan RTX has 24 GB-VRAM
How many CPU-RAM do you have?

Usually if there is not enough GPU-memory then an CUDA Out of memory error occurs. But for the first time I see an Realloc-error due to lack of memory on the GPU.

Try to use subdivisios=32

**Comment by ttdd11** [comment]
32 Gigs CPU ram.

I don't think it's because of a lack of memory. When looking at z-gpu the usage on startup (before it stops) is 13 gigs.

**Comment by ttdd11** [comment]
subdivision=32 works btw.

**Comment by ttdd11** [comment]
Is the difference really only a training time difference? If so then I consider this solved.

**Comment by AlexeyAB** [comment]
> 32 Gigs CPU ram.

It is preferable to have at least 2 times more CPU-RAM than GPU-RAM.

"Realloc error" message says that there is no enough CPU-RAM.

This is a rare case when using a Titan RTX for 2500 $, and memory for 250$ )

> Is the difference really only a training time difference?

For YOLOv4:
* Subdivisions=8 -> 16 is only training time difference
* Subdivisions=16 -> 32 training time difference and drop in acuracy 1-2% AP

For other networks mini-batch-size affects much stronger.

**Comment by ttdd11** [comment]
@AlexeyAB Thanks for the information. The plan is to use 4 Titan RTX cards so in that card should I be using 128 Gigs ram? Or 256 gigs?

**Comment by AlexeyAB** [comment]
Its preferably to use 256 GB CPU-RAM for 4 x TitanRTX.

So new nVidia DGX-A100 that is based on new Ampere-GPU will use 1 TB CPU-RAM with AMD-CPU Epyc: https://www.nvidia.com/en-us/data-center/dgx-a100/

* 8X NVIDIA A100 GPUS WITH **320 GB TOTAL GPU MEMORY**
* DUAL 64-CORE AMD CPUs AND **1 TB SYSTEM MEMORY**

CPU-RAM is 3x times more tha GPU-RAM.

**Comment by ttdd11** [comment]
@AlexeyAB Thank you for your help. This error is quite stupid and also very rare. I installed some more Ram and am no longer receiving it (subdivisions at 16).
