### ISSUE TITLE
Making a detector API

### ISSUE THREAD

**Issue by teocns** [AlexeyAB/darknet#5631]
I am trying to build an endpoint, say `/detect.py`, for detection on-demand.

So far so good, things working fine. `detect.py` would import `darknet.py`:
```
sys.path.insert(0, '/var/AI/darknet/')
import darknet
exit(
    darknet.performDetect('/var/AI/temp/9-2000-1821-2973-1493-3293-2215-2219-2580-70.jpg')
)

```

The thing is that every time I run `performDetect(imagePath)`, the **initialization** occurs and it's really, really **slow**. The server is a 2GB ram / 1 core so you make the math!

How can I make the initialization only occur once and be there, ready for getting an `imagePath` fed?

**Comment by AlexeyAB** [comment]
Look at the darknet_video.py 0 it also imports darknet.py, but **doesn't** initializarte network for each frame.

**Comment by teocns** [comment]
I guess this is the only thing I'm looking for?

```
if netMain is None:
        netMain = darknet.load_net_custom(configPath.encode(
            "ascii"), weightPath.encode("ascii"), 0, 1)  # batch size = 1
```

**Comment by teocns** [comment]
I am going to try the solution whereas I first call:

`performDetect(initOnly = true)`

...Wait for the loading process, and then call:

`performDetect(imgPath)`

for each image I need.
