### ISSUE TITLE
Potential Fix - Crash durin Map Calculations

### ISSUE THREAD

**Issue by VisionEp1** [AlexeyAB/darknet#5633]
Hi there,

i myself had some issues when running with the -map flag that it hang and crashed sometimes.
other people seemed to have it to (some issues was marked as bug in progress if i remember correctly).

When i am debugging (release mode with debug symbols on) it crashes in line 893 in network.c:
 if (dets[i].uc) free(dets[i].uc);

What prevents that from happening is:
make calloc every time instead of only with gaussian tool:
 if(l.type == GAUSSIAN_YOLO || 1==1) dets[i].uc = (float*)xcalloc(4, sizeof(float));
(line 774 network.c)
(no clean solution just to "prevent" the issue).

I did not further research into that i just saw that it stopped my crashes.
- If i shall perform any more tests or provide new information feel free to let me know

**Comment by AlexeyAB** [comment]
Hi, Thanks!

Try to change this line https://github.com/AlexeyAB/darknet/blob/73768ef6e3ee3647e198022300a9e0a7e751ef5b/src/network.c#L774

to these 2 lines, does it solve this issue?
```cpp
if(l.type == GAUSSIAN_YOLO) dets[i].uc = (float*)xcalloc(4, sizeof(float)); // Gaussian_YOLOv3
else dets[i].uc = NULL;
```

**Comment by VisionEp1** [comment]
Thats the same thing i tested first but i did not fix the error for me.

However i just did it again and it seems to work so maybe i didn't copy the file over or some "stupid" thing i did.

So it seems to work, however i would like to let it train a few hours to confirm 100%

**Comment by VisionEp1** [comment]
confirmed that fixes it. 

so i guess "your" malloc function does not set all pointers to 0 by default.
i did not look further into that but i suspect that might be caused by some optimization settings maybe system or processor dependent.

This might also occur in other places in the code if there are similar "optional" features.

Thanks for integrating the fix as always :)

**Comment by AlexeyAB** [comment]
> so i guess "your" malloc function does not set all pointers to 0 by default.

My `xcalloc()` fuction calls standard C-function `calloc()` that should zeroed all values in structure: http://www.cplusplus.com/reference/cstdlib/calloc/

> Allocate and zero-initialize array

https://github.com/AlexeyAB/darknet/blob/73768ef6e3ee3647e198022300a9e0a7e751ef5b/src/utils.c#L36-L42

So I don't know why did it happen.

---- 

I added such fix: https://github.com/AlexeyAB/darknet/commit/0ef5052ee51e82b2862fab5e9135b7bae060354f

**Comment by imaami** [comment]
Why is there neither any checking of the current value of `dets[i].uc` nor (apparently) any zeroing of it when the memory it points to is freed? I mean, both the previous and changes code lines discussed in this issue seem to lack all consideration of it. And it's a very basic thing in C.

**Comment by VisionEp1** [comment]
I would say feel free to add a pr with a better solution.

Neighter of 1 or 2 should happen. 
Since once it is not initialized it is set to NULL with calloc which is safe to call free on.

**Comment by AlexeyAB** [comment]
@imaami 

> either the value of dets[i].uc was never initialized, which means that free() is told to release a random garbage value and not an actual pointer to allocated memory, or
> 
> dets[i].uc has been freed already, but the value of that pointer hasn't been set to NULL after free().

What part of code are you talking about?
Both of your options are not possible in this part of code:

https://github.com/AlexeyAB/darknet/blob/462980d2d9cd0b4f82ea2c54383c48c21b625726/src/network.c#L895-L904
