### ISSUE TITLE
Can't proceed to training 

### ISSUE THREAD

**Issue by Nazrindino97** [AlexeyAB/darknet#5635]
> 'darknet.exe' is not recognized as an internal or external command, operable program or batch file

try to training custom data in windows 10 but got this after inserting the training command

**Comment by NHarishGit** [comment]
@Nazrindino97, can you please check your folder from where you are executing your darknet.exe command, does that folder even have that file ?

Suggest follow instructions from here:  https://github.com/AlexeyAB/darknet/blob/master/README.md

Hope it helps.

**Comment by Nazrindino97** [comment]
Thank you for the answer but may I know,
Does '_darknet.exe_' is already exist in the darknet file once we downloaded it or there is a process to produce '_darknet.exe_' ? Because i can't find the file.

And where supposedly the darknet.exe file was placed?

Please do help me ASAP 😣

**Comment by NHarishGit** [comment]
After downloading, assuming you are on WIN 10 system, ensure, you have CUDA, CMAKE, Visual Sudio 2019 community, OpenCV

https://github.com/AlexeyAB/darknet/blob/master/README.md#how-to-compile-on-windows-using-cmake

**Comment by aicukltd** [comment]
Once you have successfully built the project and you have a '.exe' file, mine was in the Darknet root 'Release' folder, you need to do the following:

1. Copy the dependencies from OpenCV 'bin' to the 'Release' folder.
2. Copy the pthread ({darknetPath}\3rdparty\pthreads\bin to the 'Release' folder. 
3. Add the 'Release' folder to the PATH environment variable.
