### ISSUE TITLE
Why can not display mAPs in training chart?

### ISSUE THREAD

**Issue by HYL-Dave** [AlexeyAB/darknet#5639]
![chart_yolo-obj](https://user-images.githubusercontent.com/39075627/82122589-2b5ca780-97c7-11ea-80ce-a7322904e38c.png)

**Comment by HYL-Dave** [comment]
I have created test.txt and use -map flag

**Comment by HYL-Dave** [comment]
I haveEven I set

**Comment by divid3d** [comment]
same issue here

**Comment by HYL-Dave** [comment]
You can add -map flag. For example, 
./darknet detector train data/obj.data yolov3-tiny.cfg yolov3-tiny.conv.11 -map
