### ISSUE TITLE
by tried to detect an image using darknet i get an issue in cfg file?

### ISSUE THREAD

**Issue by vijay180396** [AlexeyAB/darknet#5644]
**Warning: width=412 and height=412 in cfg-file must be divisible by 32 for default networks Yolo v1/v2/v3!!!**

Loading weights from backup/yolov3-obj_best.weights...
 seen 64, trained: 307 K-images (4 Kilo-batches_64)
Done! Loaded 107 layers from weights-file

 Error: in the file data/coco.names number of names 80 that isn't equal to classes=1 in the file cfg/yolov3-obj.cfg
data/A0003.jpg: Predicted in 2627.480000 milli-seconds

**Comment by AlexeyAB** [comment]
width=412 and height=412 in cfg-file must be divisible by 32

**Comment by aicukltd** [comment]
Try changing 412x412 to 416x416

width = 416
height = 416
