### ISSUE TITLE
fast-trame render problem

### ISSUE THREAD

**Issue by CSTEZCAN** [AlexeyAB/darknet#5649]
Hi!
I've trained a container recognition model and inferenced with a few videos. At ./darknet detector demo ... ... ... -out_filename ..mp4 file, I've encountered 1 frame that was really weird. It like overlay of the detection pre-rendered to the scene before the actual detection. Can anyone confirm this issue?
![Screen Shot 2020-05-17 at 11 15](https://user-images.githubusercontent.com/33690601/82160755-3b948580-98a0-11ea-82b4-b24198868a0f.jpeg)
![Screen Shot 2020-05-17 at 11 15 08](https://user-images.githubusercontent.com/33690601/82160758-3fc0a300-98a0-11ea-93a8-e4457a1e529c.jpg)
Regards

**Comment by AlexeyAB** [comment]
It averages detections on video across 3 frames by default.

I just made it switchable, download the latest Darknet version and use flag `-avgframes 1`:
`./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights test.mp4 -avgframes 1`
