### ISSUE TITLE
Where does the labelling takes place? I want to modify some changes for my project so that it can push the detected label to a database. Please help!!!

### ISSUE THREAD

**Issue by bumblebee34** [AlexeyAB/darknet#5652]

**Comment by aicukltd** [comment]
You could use the C++ compiled version and then use the results provided by the detection method and write your own code to persist it.

**Comment by bumblebee34** [comment]
Can you provide me with a link to some tutorial to how to do it?

**Comment by aicukltd** [comment]
It depends on the language my friend.

Your logic will need to look like:

1. On Object Detection - (type, confidence, bounding box)
2. Adapt to Database Model (Id, Type, Confidence, X, Y, Width, Height)
3. Save into DB

@AlexeyAB 's implementation is very popular and there are many wrappers in different programming languages out there!

**Comment by AlexeyAB** [comment]
* Or you can use Darket as SO/DLL library, just compile with LIBSO=1 in Makefile/Cmake.

* Or you can run Darknet as JSON-server, that gets video from rtsp-stream and gives you coordinates of detected objects: https://github.com/AlexeyAB/darknet#how-to-use-on-the-command-line

JSON and MJPEG server that allows multiple connections from your soft or Web-browser ip-address:8070 and 8090: `./darknet detector demo ./cfg/coco.data ./cfg/yolov3.cfg ./yolov3.weights rtsp://login:pass@192.168.0.228:554 -json_port 8070 -mjpeg_port 8090 -ext_output`

**Comment by bumblebee34** [comment]
After changing LISBO=1 in Makefile and running darknet.py file it gives following error :

Traceback (most recent call last):
  File "darknet.py", line 127, in <module>
    lib = CDLL("./libdarknet.so", RTLD_GLOBAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./libdarknet.so: cannot open shared object file: No such file or directory
