### ISSUE TITLE
No detection after training custom detector for 3 classes. Help Needed!

### ISSUE THREAD

**Issue by akshayjaryal603** [AlexeyAB/darknet#5658]
Hello @AlexeyAB 

I train the model taking 3 classes from Open-Image dataset of Glove, Helmet, and Person.

I haven't got any detection after running the detector for Inference on person.jpg.
Command for running the Inference
-> ./darknet detector test data/obj.data cfg/yolo-obj.cfg backup_old/yolo-obj_6000.weights data/person.jpg -dont_show

Loading weights from backup_old/yolo-obj_6000.weights...
 seen 64, trained: 384 K-images (6 Kilo-batches_64) 
Done! Loaded 162 layers from weights-file 
data/person.jpg: Predicted in 22.065000 milli-seconds.

Please help I stuck in this issue from the last one week, I trained the model twice but got the same issue.

**Comment by akshayjaryal603** [comment]
2708 images all 3 classes

**Comment by akshayjaryal603** [comment]
Please help me with what I am doing wrong during training process.

**Comment by AlexeyAB** [comment]
Your dataset is wrong. Check it by using Yolo_mark tool.

**Comment by akshayjaryal603** [comment]
Thanks @AlexeyAB, but I download the dataset from Open Images Dataset V6 with annotations.

**Comment by AlexeyAB** [comment]
Annotations should be in Yolo format.

**Comment by akshayjaryal603** [comment]
Yes, Annotations are in Yolo format. I follow the youtube tutorial of AI Guy for training custom detector using YOLOv3. I follow the same steps for YOLOv4.

**Comment by AlexeyAB** [comment]
Check it by using Yolo_mark tool.

Also run training with flag `-show_imgs` do you see correct bounded boxes?

**Comment by akshayjaryal603** [comment]
I follow same steps as you mentioned in the Yolov4 Github repo README.

**Comment by akshayjaryal603** [comment]
> Check it by using Yolo_mark tool.
> 
> Also run training with flag `-show_imgs` do you see correct bounded boxes?

Okay, I will try.

**Comment by akshayjaryal603** [comment]
Thanks, @AlexeyAB for your help. I solved my issue the issue is with my annotation format.

**Comment by ssrm7** [comment]
> Thanks, @AlexeyAB for your help. I solved my issue the issue is with my annotation format.

What was the issue and how did you solve it? Can you please elaborate? I am having the same issue with my custom dataset.
