### ISSUE TITLE
FPS&avg_fps

### ISSUE THREAD

**Issue by Gaondong** [AlexeyAB/darknet#5661]
I use the `./darknet detector demo ` to detect a video(mp4 format), and I saw the output include FPS and avg_fps, what's the defference between them, did them include the pre-progress and post-progress time of YOLOv3?

**Comment by AlexeyAB** [comment]
FPS - current FPS
AVG FPS - average FPS for 3 seconds

It shows real FPS, including all processes, but they are executed in 3 threads: 
1. videocapture, resizing, pre-processing, 
2. inference, post-processig
3. nms, bbox drawing, image showing

If you want to disable `bbox drawing, image showing` then use flag `-dont_show`
If you want to disable 1 and 2 the use flag `-benchmark`

**Comment by Gaondong** [comment]
> FPS - current FPS
> AVG FPS - average FPS for 3 seconds
> 
> It shows real FPS, including all processes, but they are executed in 3 threads:
> 
> 1. videocapture, resizing, pre-processing,
> 2. inference, post-processig
> 3. nms, bbox drawing, image showing
> 
> If you want to disable `bbox drawing, image showing` then use flag `-dont_show`
> If you want to disable 1 and 2 the use flag `-benchmark`

Thanks for your reply, What's the post-progressing in threads 2 doing after inference,  I previously thought that the post-processing time includes nms time.

**Comment by AlexeyAB** [comment]
`get_network_boxes()` - converts detections from 3 [yolo] layers to the array of `struct detection` and remove detections with low confidence thresholds

----

If you want to measure AVG FPS including NMS, you can move nms to point 2:
* comment these lines: https://github.com/AlexeyAB/darknet/blob/594f7ce6aff73c3e7f55b6fc31ee9a13feb5e4ef/src/demo.c#L260-L263

* add there: https://github.com/AlexeyAB/darknet/blob/594f7ce6aff73c3e7f55b6fc31ee9a13feb5e4ef/src/demo.c#L110
```cpp
        const float nms = .45;
        if (nms) {
            if (l.nms_kind == DEFAULT_NMS) do_nms_sort(dets, nboxes, l.classes, nms);
            else diounms_sort(dets, nboxes, l.classes, nms, l.nms_kind, l.beta_nms);
        }
```

**Comment by Gaondong** [comment]
> `get_network_boxes()` - converts detections from 3 [yolo] layers to the array of `struct detection` and remove detections with low confidence thresholds
> 
> If you want to measure AVG FPS including NMS, you can move nms to point 2:
> 
> * comment these lines: https://github.com/AlexeyAB/darknet/blob/594f7ce6aff73c3e7f55b6fc31ee9a13feb5e4ef/src/demo.c#L260-L263
> * add there: https://github.com/AlexeyAB/darknet/blob/594f7ce6aff73c3e7f55b6fc31ee9a13feb5e4ef/src/demo.c#L110
> 
> ```c++
>         const float nms = .45;
>         if (nms) {
>             if (l.nms_kind == DEFAULT_NMS) do_nms_sort(dets, nboxes, l.classes, nms);
>             else diounms_sort(dets, nboxes, l.classes, nms, l.nms_kind, l.beta_nms);
>         }
> ```

Thank you so much！
