### ISSUE TITLE
loss not decreasing less than 1.5

### ISSUE THREAD

**Issue by qustions** [AlexeyAB/darknet#5675]
Hi, @AlexeyAB Congratulation on yolov4 Paper. I am training on yolov4. I have 2 classes first-class is having 40k images and the second is having 10k images total 50k images. I have followed [this method](https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects). But in this cfg file, it's saying to edit yolov3 ex: line 610 and more in yolov3.cfg. But I yolov4 cfg the lines are different [line 968 and more](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4.cfg#L968) here is my [yolo.cfg ](https://pastebin.com/VmxEdCVD) and I have also changed `max_batches = 40000` because the training was stopping after 6k iteration. I have trained on 1080ti for 3 days for 40k iterations but the avg loss is not decreasing it's between 1.5 to 1.8.
1. What could be the issue for not decreasing the avg loss, the ratio between classes or someting new in yolov4?
2. Where can I see Val loss in this 
`21423: 1.261652, 1.456173 avg loss, 0.000026 rate, 2.904338 seconds, 514152 images, 12.042497 hours left`
3. What does max_batches mean?

**Comment by AlexeyAB** [comment]
1. Loss lower 20 is good
2. train with `-map` flag and look at mAP https://github.com/AlexeyAB/darknet#when-should-i-stop-training
3. how many iterations it will be trained

**Comment by qustions** [comment]
thanks, @AlexeyAB but when I am running the prediction on video CPU is being used nearly 3 cores 100% and 1gb graphic  what could be the reason in my make file this are the values 
 ```GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=1
AVX=0
OPENMP=0
LIBSO=0
ZED_CAMERA=0 # ZED SDK 3.0 and above
ZED_CAMERA_v2_8=0 # ZED SDK 2.X
```

**Comment by AlexeyAB** [comment]
Because OpenCV use CPU for reading mp4 and showing video in the window.

**Comment by qustions** [comment]
How to check if OpenCV is using CPU because I install with GPU made Cuda on

**Comment by AlexeyAB** [comment]
In the Darknet is used OpenCV-videocapturing that uses CPU for reading mp4, because the most users use OpenCV installations without CUDA support.

For using OpenCV-videocapturing on GPU you should implement it by yourself in the Darknet:
* https://github.com/opencv/opencv/blob/master/samples/gpu/video_reader.cpp
* https://developer.nvidia.com/nvidia-video-codec-sdk

**Comment by qustions** [comment]
Thanks
