### ISSUE TITLE
my webcam only show a gray image

### ISSUE THREAD

**Issue by AbdulUwais21** [AlexeyAB/darknet#568]
Hello, there.

Why I got a gray image on webcam demo?
How to solve it?

I tested using these commands:
darknet detector demo cfg/voc.data cfg/tiny-yolo-voc.cfg tiny-yolo-voc.weights
darknet detector demo cfg/coco.data cfg/yolo.cfg yolo.weights

Thanks.

**Comment by AlexeyAB** [comment]
Hi, 

I fixed it.

Use `darknet detector demo data/coco.data cfg/yolov3.cfg yolov3.weights -c 0`
