### ISSUE TITLE
some nan during training

### ISSUE THREAD

**Issue by Whisper94** [AlexeyAB/darknet#5680]
Hello!

I need your help!

I have read all instruction how to train on custom dataset. It works with training. BUT!

If I train yolov3 I'll get some nan in Avg. Although there are some nan the chart displays very good mAP. 

What I've done? My dataset has simple images with 150x150 resolution. I'm training yolo on 32x32 shape to detect these small objects on FullHD or 4k resolution. I think it is a good approach to detect small objects if  train croped images at first to detect them in the full image. But it in  in darknet in yolov3 it doesn't work. With a fork it worked very well. 
After training yolov4 with the same training parameters it works but not enough or I don't know which parameters I should change in cfg to achieve the best performance. In yolov4 during training I had also pretty good mAP but the loss was general higher then at yolov3
![final_after_all_iterations](https://user-images.githubusercontent.com/60612672/82412919-c6c67480-9a74-11ea-9646-816a08564f14.png)

You see two images with training yolov3. Sometimes 1/3 is nan. Sometimes is 2/3 is nan although mAP and loss are pretty good. 
![2020-05-19 22_13_20-Window](https://user-images.githubusercontent.com/60612672/82411457-15264400-9a72-11ea-9992-4b79c8f7dccd.png)
![2020-05-19 21_48_30-Window](https://user-images.githubusercontent.com/60612672/82411474-1ce5e880-9a72-11ea-9e88-259ef6eb05c9.png)
In this training I've tried to train original images on 128x128 shape in cfg file and after that to detect objects with 1922x1440 resolution but it was very bad. With thresh 0.1 there were only some objects with score about 10-20%. If I reduse shape in cfg for detecting there will be no or wrong detections or if increasing - out of memory (with batch and subdivisions 64 to 64).

To accelerate the training with the small resolution I use in cfg file batch 512 and sub 16 for 32x32 resolution. Another parameters are like in instructure.

Could you explain what could I improve in my parameters? Thank you!!!

**Comment by WongKinYiu** [comment]
1. every data augmentation will make loss become higher.
2. when `count=0` (it mens there is no any ground truth of object is assigned to the corresponding anchors), the loss must be nan.
![image](https://user-images.githubusercontent.com/12152972/82417563-4c1a4b00-9aae-11ea-86c8-7431103f8448.png)

i suggest you to recalculate the anchors.

**Comment by Whisper94** [comment]
Hello.
Thank you very much for your fast answer. I use default anchors in cfg file. 

anchors = 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326

Do you know how can I recalculate new anchors for so small objects? In training dataset my resolution of the image (in cfg file) is 32x32. So the objects are about 15x15 pixel on the image. But if I reshape resolution to 128x128 so will my objects about 50x50 pixels and it should be big enough for detecting ground truth with corresponding anchors.

Thank you!

**Comment by AlexeyAB** [comment]
I see that GIoU and `IoU=nan`, but I don't see `Nan avg loss`

https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

Note: If during training you see nan values for avg (loss) field - then training goes wrong, but **if nan is in some other lines - then training goes well.**

**Comment by Whisper94** [comment]
@AlexeyAB thank you for your comment and sorry. I have wrong understood and thought that if at Avg(IOU:...) is nan then is something is wrong. Because of I'll get during training 1/3 up to 2/3 nan.

Could you comment if I should recalculate anchors for training or how could I improve detection. Because with training 32x32 resolution and detecting on 1920x1920 I'll get threshold between 10%-50%. If lower resolution for detecting then it shows nothing...

**Comment by AlexeyAB** [comment]
Do you use width=32 height=32 for training? Or what do you mean? 
Show your training and testing images.

**Comment by Whisper94** [comment]
Yes. All my original images for training are 150x150 and in cfg I train with 32x32 because I'd like to detect these objects on 4k resolutions. They are on 4k also 150x150. So I thought if I reduse the training resolution yolo will be able to detect these objects also with smaller resolution like 1088 instead of 4k. Because 4k I can not implement in cfg because of out of memory. 
Ma dataset looks like this one:
![schlecht_C10_image-2](https://user-images.githubusercontent.com/60612672/82447735-ff804100-9aa8-11ea-8428-f39b40dfb6df.jpg)


If I train with 32x32 yolo detects some objects but not much and with very low accuracy between 10-30% if I try to detect with 1920x1440 resolution complete image

**Comment by AlexeyAB** [comment]
What mAP do you get on large images?

**Comment by Whisper94** [comment]
Sorry for question but how can I check mAP on large image?
Just 'map' instead of 'test'? like: darknet.exe detector map data/obj.data yolo_detection.cfg  yolov3_final.weights if so, then I get everywhere as AP 0,00%
![image](https://user-images.githubusercontent.com/60612672/82451321-1d9c7000-9aae-11ea-8698-9008f140c24b.png)


If I try to detect with WxH 1920x1440 then it works only with threshold 0.1, so I got the following results like in image
![image](https://user-images.githubusercontent.com/60612672/82450171-a31f2080-9aac-11ea-8206-5aae82d65c16.png) for lower resolution images it doesn't work

**Comment by AlexeyAB** [comment]
> Sorry for question but how can I check mAP on large image?
> Just 'map' instead of 'test'? like: darknet.exe detector map data/obj.data yolo_detection.cfg yolov3_final.weights if so, then I get everywhere as AP 0,00%

Yes, set high width and height in cfg file, set valid=valid.txt in obj.data file and run this command.
Your validation dataset should be labeled too in the same format as training dataset.

> If I try to detect with WxH 1920x1440 then it works only with threshold 0.1, so I got the following results like in image

Can you show image with detectio results?

**Comment by Whisper94** [comment]
So have labeled one image with all objects and it looks very sad because map is 0%
![image](https://user-images.githubusercontent.com/60612672/82485995-84d11900-9adc-11ea-98af-c2c696f10782.png)

even if I try with different resolutions mAP is 0% but yolo detects some objects.
https://drive.google.com/open?id=1lvxcJafZS-NbPhlADR-YrS766JmCrKfG please look here. I've uploaded some images but please don't post their
