### ISSUE TITLE
There is a problem with the ZED camera

### ISSUE THREAD

**Issue by maohu-96** [AlexeyAB/darknet#5691]
![image](https://user-images.githubusercontent.com/63272697/82561079-510df600-9ba5-11ea-8d2b-e5564aa7ae53.png)
When I run the following command,
`LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./uselib data/coco.names cfg/yolov4.cfg yolov4.weights zed_camera`
the error appears, how can I solve it, thank you @ @AlexeyAB

**Comment by AlexeyAB** [comment]
SET `1` for one of these flags https://github.com/AlexeyAB/darknet/blob/master/Makefile#L8-L9

**Comment by maohu-96** [comment]
> 设置`1`这些标志之一https://github.com/AlexeyAB/darknet/blob/master/Makefile#L8-L9

Thank you for your reply!
Is there something wrong with my Makefile setting like this?
![image](https://user-images.githubusercontent.com/63272697/82562313-8e738300-9ba7-11ea-8ac3-b0228c68bfc5.png)

**Comment by AlexeyAB** [comment]
Use debug=0.

and do
```
make clean
make
```

**Comment by maohu-96** [comment]
Thank you for your prompt reply!
I set DEBUG = 0
There are still the errors
![image](https://user-images.githubusercontent.com/63272697/82563248-46edf680-9ba9-11ea-93f6-0012cd1b3e7b.png)

**Comment by maohu-96** [comment]
> Use debug=0.
> 
> and do
> 
> ```
> make clean
> make
> ```
Thank you for your prompt reply!
I set DEBUG = 0
There are still the errors
![image](https://user-images.githubusercontent.com/63272697/82563331-769cfe80-9ba9-11ea-9731-1b32278004f1.png)

**Comment by AlexeyAB** [comment]
What ZED_SDK did you install, 2.x or 3.x?

----

Can you add there: https://github.com/AlexeyAB/darknet/blob/4098e4882c55076bfe6c02ce4ed469e86a414152/src/yolo_console_dll.cpp#L353

this line
`std::cout << " try to use ZED \n";`

recompile, run and show screenshot of the error.

**Comment by maohu-96** [comment]
> 您安装了2.x或3.x版本的ZED_SDK？
> 
> 您可以在此处添加：
> 
> https://github.com/AlexeyAB/darknet/blob/4098e4882c55076bfe6c02ce4ed469e86a414152/src/yolo_console_dll.cpp#L353
> 
> 这条线
> `std::cout << " try to use ZED \n";`
> 
> 重新编译，运行并显示错误的屏幕截图。
I installed version 3.1.2 ZED_SDK.
I added `std::cout << " try to use ZED \n";`，remake，but there are still errors
![image](https://user-images.githubusercontent.com/63272697/82564482-6e45c300-9bab-11ea-8a22-365c7ed679e6.png)

**Comment by AlexeyAB** [comment]
Show screenshot of Makefile

Show screenshot of 
```
make clean
make
```

**Comment by maohu-96** [comment]
![image](https://user-images.githubusercontent.com/63272697/82565776-8a4a6400-9bad-11ea-99af-7a92d57c6d72.png)
![image](https://user-images.githubusercontent.com/63272697/82565837-a8b05f80-9bad-11ea-9315-0c277c3923b7.png)


> 显示Makefile的屏幕截图
> 
> 显示的屏幕截图
> 
> ```
> make clean
> make
> ```
![image](https://user-images.githubusercontent.com/63272697/82566018-e6ad8380-9bad-11ea-8598-d00deaf4ab23.png)
![image](https://user-images.githubusercontent.com/63272697/82566073-faf18080-9bad-11ea-83b3-8072d13c3027.png)

**Comment by maohu-96** [comment]
> > 显示Makefile的屏幕截图
> > 显示的屏幕截图
> > ```
> > make clean
> > make
> > ```
> 
> ![image](https://user-images.githubusercontent.com/63272697/82566018-e6ad8380-9bad-11ea-8598-d00deaf4ab23.png)
> ![image](https://user-images.githubusercontent.com/63272697/82566073-faf18080-9bad-11ea-83b3-8072d13c3027.png)
There are two files with warnings, yolo_v2_class.cpp and yolo_console_dll.cpp
Is there a problem with the compilation process?
How should I solve this problem
Thanks again for your reply! @AlexeyAB

**Comment by maohu-96** [comment]
@AlexeyAB  Hi，first of all thank you for your help

I refer to the link [How to compile on Linux (using cmake)](https://github.com/AlexeyAB/darknet#how-to-compile-on-linux-using-cmake)and rerun
ZED success！I can use ZED to achieve detection！
But I have two doubts：
1.when I turn on the camera, the processing speed of the computer is very slow. I cannot use my computer normally. The camera screen displays FPS detection 22, FPS captures 45，
What should the normal fps be? How to increase fps？（My device: GTX1660ti 6G）

2.In the test results, I think that xyz represents the left coordinate of the camera as the world coordinate system, and xyz is the distance from the center point of the target. Is my understanding correct?
What does 117 in the label mean? Confidence?
![2020-05-22 10-12-26屏幕截图](https://user-images.githubusercontent.com/63272697/82624651-b39eda80-9c15-11ea-937c-c84223c78fdf.png)

Thanks！
