### ISSUE TITLE
Results are empty

### ISSUE THREAD

**Issue by xitman47** [AlexeyAB/darknet#57]
Alexey, hi! First of all thanks a lot for the work done, amazing!

I am quite new to this tool and just installed it on Windows. After running few examples I have an issue when no results are written to the "results/" folder (I have only predictions.png file). 

Can you, please, suggest how I can get the results (txt with classes and boxes coordinates)? I was using MSVS 2013 when compiling file - could that be an issue? Thanks!

**Comment by AlexeyAB** [comment]
@xitman47 Hi,

Jus use this command line: `darknet.exe detector valid data/coco.data yolo.cfg yolo.weights -thresh 0.24`

----

* In file `data/coco.data` change path `valid  = data/coco_testdev` to .txt-file with jpg-images which you want to predict
* if this is absent - you should create directory `darknet/build/darknet/x64/results/`
* then run `darknet.exe detector valid data/coco.data yolo.cfg yolo.weights -thresh 0.24`
* in the directory `darknet/build/darknet/x64/results/` will be created txt-files with obj_id and coordinates

**Comment by xitman47** [comment]
AlexeyAB, thanks a lot!

Unfortunately  I am still having issues even after following your steps mentioned =( Now it produces empty coco_results.json file, Windows asks to close the program and cmd returns:

> Cannot load image ","
> 4

when running under admin or just w/o admin:
> 4

I have tried using various image paths in images.txt file (full path, short path, with "/" or with "\", etc.) but still it does not work. I am afraid problem occurs since I used MSVS 2013 for compilation of the project so it was wrongly complied. I will try MSVS 2015 instead.

**Comment by AlexeyAB** [comment]
@xitman47 

* Do you use OpenCV 2.4.x and GPU CUDA?
* Can you detect any objects by using: `darknet.exe detector test data/voc.data yolo-voc.cfg yolo-voc.weights data\dog.jpg`
* Try also:
    * update code from this github-fork
    * download new weights-files from: https://pjreddie.com/darknet/yolo/

**Comment by xitman47** [comment]
@AlexeyAB,

> Do you use OpenCV 2.4.x and GPU CUDA?

Yes.

> Can you detect any objects by using: darknet.exe detector test data/voc.data yolo-voc.cfg yolo-voc.weights data\dog.jpg

Yes, it works but only creates predictions.png file w/o any txt files with the results.

>Try also:

Done! I have also rebuilt project using MSVS 2015 but issue remains the same. There also might be an issue with coding as it cannot open images properly when I load images.txt, it bad.list it returns:

> ђҐ¦Ё¬ўлў®¤  Є®¬ ­¤ ­  нЄа ­ (ECHO) ўЄ«озҐ­.
> ђҐ¦Ё¬ ўлў®¤  Є®¬ ­¤ ­  нЄа ­ (ECHO) ўЄ«озҐ­.
> поd

**Comment by AlexeyAB** [comment]
@xitman47 

Can you show:

* What command line do you use?
* The contents of the file `.data`
* Part of the contents of the file to which refered line `valid =` in `.data`-file (and path to this file)
* Path to images which you want to valid

**Comment by AlexeyAB** [comment]
For example, it works if I use:

* command: `darknet.exe detector valid data/obj.data yolo-obj.cfg yolo-obj_9000.weights -i 0`

* paths - relative to `darknet.exe`:

> data\obj.data
> data\obj.names
> data\train.txt

* `obj.data` contains:

> classes= 6
> train  = data/train.txt
> valid  = data/train.txt
> names = data/obj.names
> backup = backup/
> results= results/

* `train.txt` contains:

> data/voc/img_0_1224.jpg
> data/voc/img_0_2.jpg
> data/voc/img_0_4.jpg
> data/voc/img_0_6.jpg
> data/voc/img_2_192.jpg
> data/voc/img_4_347.jpg
> data/voc/img_f_14_346.jpg

* images:

data/voc/img_0_1224.jpg
data/voc/img_0_2.jpg
data/voc/img_0_4.jpg
data/voc/img_0_6.jpg
data/voc/img_2_192.jpg
data/voc/img_4_347.jpg
data/voc/img_f_14_346.jpg

----

Then in directory `results` there are .txt-files:

comp4_det_test_lamborghini.txt
comp4_det_test_camaro.txt
...

**Comment by xitman47** [comment]
@AlexeyAB,

I was writing comment while I saw yours above, put few details below. I will check your points and try to play with path names and cars classification example. Again many thanks for your support!!


.. I used 2 lines (basic and for the images list none of them produce the .txt file):
> darknet.exe detector test data/voc.data yolo-voc.cfg yolo-voc.weights data\dog.jpg
darknet.exe detector valid data/coco.data yolo.cfg yolo.weights -thresh 0.24

coco.data content:
> classes= 80
train  = data/coco/trainvalno5k.txt
valid  = data/images.txt
#valid = data/coco_val_5k.list
names = data/coco.names
backup = backup/
eval=coco

path to images.txt:
> C:\Users\hitman47\darknet\build\darknet\x64\data

and images.txt content:
> data/dog.jpg
data/eagle.jpg

**Comment by AlexeyAB** [comment]
@xitman47 

comment this line from `eval=coco` to `#eval=coco`

**Comment by xitman47** [comment]
@AlexeyAB,

> comment this line from eval=coco to #eval=coco in the file coco.data

Omg it works now!! =) Thanks a lot! Issue closed!

**Comment by faezemm7474** [comment]
> For example, it works if I use:
> 
> * command: `darknet.exe detector valid data/obj.data yolo-obj.cfg yolo-obj_9000.weights -i 0`
> * paths - relative to `darknet.exe`:
> 
> > data\obj.data
> > data\obj.names
> > data\train.txt
> 
> * `obj.data` contains:
> 
> > classes= 6
> > train  = data/train.txt
> > valid  = data/train.txt
> > names = data/obj.names
> > backup = backup/
> > results= results/
> 
> * `train.txt` contains:
> 
> > data/voc/img_0_1224.jpg
> > data/voc/img_0_2.jpg
> > data/voc/img_0_4.jpg
> > data/voc/img_0_6.jpg
> > data/voc/img_2_192.jpg
> > data/voc/img_4_347.jpg
> > data/voc/img_f_14_346.jpg
> 
> * images:
> 
> data/voc/img_0_1224.jpg
> data/voc/img_0_2.jpg
> data/voc/img_0_4.jpg
> data/voc/img_0_6.jpg
> data/voc/img_2_192.jpg
> data/voc/img_4_347.jpg
> data/voc/img_f_14_346.jpg
> 
> Then in directory `results` there are .txt-files:
> 
> comp4_det_test_lamborghini.txt
> comp4_det_test_camaro.txt
> ...



> For example, it works if I use:
> 
> * command: `darknet.exe detector valid data/obj.data yolo-obj.cfg yolo-obj_9000.weights -i 0`
> * paths - relative to `darknet.exe`:
> 
> > data\obj.data
> > data\obj.names
> > data\train.txt
> 
> * `obj.data` contains:
> 
> > classes= 6
> > train  = data/train.txt
> > valid  = data/train.txt
> > names = data/obj.names
> > backup = backup/
> > results= results/
> 
> * `train.txt` contains:
> 
> > data/voc/img_0_1224.jpg
> > data/voc/img_0_2.jpg
> > data/voc/img_0_4.jpg
> > data/voc/img_0_6.jpg
> > data/voc/img_2_192.jpg
> > data/voc/img_4_347.jpg
> > data/voc/img_f_14_346.jpg
> 
> * images:
> 
> data/voc/img_0_1224.jpg
> data/voc/img_0_2.jpg
> data/voc/img_0_4.jpg
> data/voc/img_0_6.jpg
> data/voc/img_2_192.jpg
> data/voc/img_4_347.jpg
> data/voc/img_f_14_346.jpg
> 
> Then in directory `results` there are .txt-files:
> 
> comp4_det_test_lamborghini.txt
> comp4_det_test_camaro.txt
> ...

sorry, I have gotten this .txt file but I didn't get any chart!!!!, could you pleeease help me how to get loss chart?
