### ISSUE TITLE
difference between yolov3-tiny and yolov3-tiny-prn

### ISSUE THREAD

**Issue by LeRoii** [AlexeyAB/darknet#5701]
hi everyone,
do you know what is the difference between yolov3-tiny and yolov3-tiny-prn

**Comment by AlexeyAB** [comment]
https://github.com/WongKinYiu/PartialResidualNetworks/blob/master/pdf/iccvw-prn.pdf

**Comment by vinorth05** [comment]
Hi everyone,
Why isn't there any tiny version for YOLOv4?

**Comment by LeRoii** [comment]
> https://github.com/WongKinYiu/PartialResidualNetworks/blob/master/pdf/iccvw-prn.pdf

Thanks a lot!
