### ISSUE TITLE
visualization of intermediate outputs

### ISSUE THREAD

**Issue by fishman2008** [AlexeyAB/darknet#571]
How do we visualize the intermediate outputs? 

From foward_network(net, state) function we can output from each intermediate layer, l.output. Is this a vector representation and we need to convert it to back to image? Thanks.

**Comment by AlexeyAB** [comment]
Yes, here is `l.output_gpu` is a pointer to GPU-memory with intermediate output for current layer: https://github.com/AlexeyAB/darknet/blob/be9d971ddb9ea0520da78cfff7788eb5481f095e/src/network_kernels.cu#L56

You can add after this line:
```cpp
		if (l.out_w >= 0 && l.out_h >= 1 && l.c >= 3) {
			image img = make_image(l.out_w, l.out_h, 3);
			memcpy(img.data, l.output, l.out_w*l.out_h*3 *sizeof(float));
			char buff[256];
			sprintf(buff, "layer-%d", i);
			show_image(img, buff);
		}
```

**Comment by fishman2008** [comment]
Hi, Alex, thanks for the response. This saves the entire output as the image. But, if we get M*N*32 after the first layer output, can we produce 32 images after the first layer?

**Comment by goodtogood** [comment]
@AlexeyAB 
I did as you said, but all images are black.
![bbbb](https://user-images.githubusercontent.com/10088733/38292587-e3cf2530-3816-11e8-982e-f40f33f029c9.jpg)

**Comment by AshleyRoth** [comment]
@AlexeyAB Hi Aleksey. Perhaps this is not the right topic for my problem, but I do not know how to solve it.
I want to send information about the detected objects by http. For example, dog = 1, horse = 1 if a dog or horse is found. I saw how you implemented the stream on-http _port, could you help me realize what I want to do? please
 I tried to make my method of detection using the port and ip, but I could not do it.

**Comment by AlexeyAB** [comment]
I missed 1 line ) The correct is:
```cpp
		cuda_pull_array(l.output_gpu, l.output, l.batch*l.outputs);
		if (l.out_w >= 0 && l.out_h >= 1 && l.c >= 3) {
			image img = make_image(l.out_w, l.out_h, 3);
			memcpy(img.data, l.output, l.out_w*l.out_h*3 *sizeof(float));
			char buff[256];
			sprintf(buff, "layer-%d", i);
			show_image(img, buff);
		}
```

**Comment by AlexeyAB** [comment]
@goodtogood 

> Hi, Alex, thanks for the response. This saves the entire output as one single image. But, if we get M×N×32 after the first layer output, can we produce 32 images after the first layer?

Use this code after this line: https://github.com/AlexeyAB/darknet/blob/be9d971ddb9ea0520da78cfff7788eb5481f095e/src/network_kernels.cu#L56
```cpp
		cuda_pull_array(l.output_gpu, l.output, l.batch*l.outputs);
		if (l.out_w >= 0 && l.out_h >= 1 && l.c >= 3) {
			int j;
			for (j = 0; j < l.out_c; ++j) {
				image img = make_image(l.out_w, l.out_h, 3);
				memcpy(img.data, l.output+ l.out_w*l.out_h*j, l.out_w*l.out_h * 1 * sizeof(float));
				char buff[256];
				sprintf(buff, "layer-%d slice-%d", i, j);
				show_image(img, buff);
			}
			cvWaitKey(0); // wait press-key in console
			cvDestroyAllWindows();
		}
```

**Comment by AlexeyAB** [comment]
@AshleyRoth 

Insert your code in this line: https://github.com/AlexeyAB/darknet/blob/be9d971ddb9ea0520da78cfff7788eb5481f095e/src/image.c#L363

```cpp
if(strcmp(names[class_id], "dog") == 0) {
   // insert here your code to send over sockets
}
```
You can look at this code if you want to use Darknet as a server with many connections: https://github.com/AlexeyAB/darknet/blob/be9d971ddb9ea0520da78cfff7788eb5481f095e/src/http_stream.cpp#L53-L188

**Comment by AshleyRoth** [comment]
@AlexeyAB Thanks! I have an IP and a port of another computer, to which I want to send information about detection. The code that you attached is suitable for this? I thought not that big code is needed for such a task

**Comment by goodtogood** [comment]
@AlexeyAB 
It works now , thanks !

**Comment by AshleyRoth** [comment]
@AlexeyAB I tried to do as you wrote. To begin with, I just tried the print command. I do not know why, but it does not. Do not know what the problem is?
![sd](https://user-images.githubusercontent.com/37982453/38350826-c5ebbf48-38b5-11e8-9a9f-6eacee43c305.png)

**Comment by TheMikeyR** [comment]
@AshleyRoth Did you recompile darknet after you modified it?

**Comment by AshleyRoth** [comment]
@TheMikeyR Sure. I make after changes

**Comment by AshleyRoth** [comment]
@AlexeyAB . the problem is found! I myself ran it wrong. I have a client code to send to the server:
struct sockaddr_in client;

 int sock = socket(AF_INET, SOCK_STREAM, 0);
    if (sock == -1)
    {
        printf("error: invalid socket\n");
        return -1;
    }
    client.sin_addr.s_addr = inet_addr("10.17.25.35");//INADDR_ANY;
    client.sin_port = htons(8080);
    client.sin_family = AF_INET;
    printf("wait for the connect...\n");
    if (connect(sock, (struct sockaddr *)&client, sizeof(client)) == -1)
    {
        printf("error: failed connection\n");
        return -1;
    }
    else
        printf("connected\n");
    close(sock);
    return 0;

After inserting my code, the yolo has stopped allocating the detected object.

in the picture my terminal result after 'test' on dog.jpg

What's the problem? can you help? please

![result](https://user-images.githubusercontent.com/37982453/38352628-892679fc-38bc-11e8-89bc-5665065a0ef4.png)

**Comment by AshleyRoth** [comment]
@AlexeyAB 

Hi again! I managed to deal with the problems that were and write the appropriate code for the client and the server. But I ran into the next problem, and I would be very grateful if you could help solve the remaining problem.

`if(strcmp(names[class_id], "dog") == 0) {
   // insert here your code to send over sockets
}`

You told me how to make a condition for the detection of a dog. In the case of several classes (for example, 6 classes) how can I do this? Create 6

**Comment by spaul13** [comment]
@AlexeyAB @fishman2008 @goodtogood , I have added the lines of code in darknet/src/network_kernels.cu but on windows while I build the solution again after modifying the code. Nothing built all codes showing up-to-date. After modifying .cu script how to compile on windows using visual studio? any help will highly be appreciated.

**Comment by renziver** [comment]
How can we implement this to save the image in a directory instead of opening in an OpenCV/Cv2 window? I tried to compile darknet when I uncommented it but ran through several cv2 errors. @AlexeyAB 

```
cuda_pull_array(l.output_gpu, l.output, l.batch*l.outputs);
		if (l.out_w >= 0 && l.out_h >= 1 && l.c >= 3) {
			int j;
			for (j = 0; j < l.out_c; ++j) {
				image img = make_image(l.out_w, l.out_h, 3);
				memcpy(img.data, l.output+ l.out_w*l.out_h*j, l.out_w*l.out_h * 1 * sizeof(float));
				char buff[256];
				sprintf(buff, "layer-%d slice-%d", i, j);
				show_image(img, buff);
			}
			cvWaitKey(0); // wait press-key in console
			cvDestroyAllWindows();
}
```
