### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cheolgyu** [AlexeyAB/darknet#5710]
Good morning.
Thank you for making yolo v4.

I tried running the webcam while following the readme and it was really slow
I saw the log
```

./darknet detector demo cfg / coco.data cfg / yolov4.cfg yolov4.weights -c 0
 CUDA-version: 10010 (10020), cuDNN: 7.6.5, CUDNN_HALF = 1, GPU count: 1
 CUDNN_HALF = 1
 OpenCV version: 4.2.0
Demo
 0: compute_capability = 750, cudnn_half = 1, GPU: GeForce GTX 1650
..
..
..
[WARN: 0] global /home/cheolgyu/opencv/opencv-4.2.0/modules/videoio/src/cap_gstreamer.cpp (935) open OpenCV | GStreamer warning: Cannot query video position: status = 0, value = -1, duration = -1
Video stream: 1280 x 720
Objects:
...
...
..

FPS: 3.9 AVG_FPS: 3.7

```

I'm using it on a laptop and I'm using this graphics card.
NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] (rev a1)
On this graphics card, **fps: 3.9** is normal, right?

https://medium.com/@alexeyab84/yolov4-the-most-accurate-real-time-neural-network-on-ms-coco-dataset-73adfd3602fe
I read that using TensorRT + tkDNN is faster, but applying TensorRT + tkDNN on my laptop doesn't get much faster, right?

thank you.

**Comment by AlexeyAB** [comment]
How many FPS can you get by using such command?
`./darknet detector demo cfg / coco.data cfg / yolov4.cfg yolov4.weights -c 0 -benchmark`

And try to compile with `CUDNN_HALF=0` in the Makefile.

> https://medium.com/@alexeyab84/yolov4-the-most-accurate-real-time-neural-network-on-ms-coco-dataset-73adfd3602fe
> I read that using TensorRT + tkDNN is faster, but applying TensorRT + tkDNN on my laptop doesn't get much faster, right?

It will be faster.

**Comment by WongKinYiu** [comment]
https://github.com/ceccocats/tkDNN/issues/12#issuecomment-629106439
