### ISSUE TITLE
Pruning Yolov4 and Neural Architecture Search

### ISSUE THREAD

**Issue by deepseek** [AlexeyAB/darknet#5724]
@AlexeyAB Thank you for your hard work,

- Is there any plans or consideration to introduce Pruning, Distillation, etc.. options in Yolov4 or v5.

- Why aren't you moving towards `Neural Architecture Search` for object detection?
You can create an architecture search algorithm with an aim of high accuracy and inference speed, with low flops. Along with being dataset independent. I am interested in your answer.
https://www.automl.org/automl/literature-on-neural-architecture-search/

**Comment by AlexeyAB** [comment]
1. Usually it gives low AP/FPS improvement. I think 1bit - 4bit quantization is better.

2. Very approximately, training a big model with MSCOCO dataset on GoogleCloud requires `~$500`. How many times do you need to train a model to get a good improvement? And will not the model fit for one this dataset?

> Along with being dataset **independent**. 

How to achieve this?

**Comment by deepseek** [comment]
1. hmmm... i don't know about that
though ibm has gone for some weird Hybrid stuff, have a look at the MaskRCNN part.
http://papers.neurips.cc/paper/8736-hybrid-8-bit-floating-point-hfp8-training-and-inference-for-deep-neural-networks

2. You can limit the search space, set maximum constraints for FLOPs and inference speed, etc...
these are just some examples, you can find more.

3.  By `dataset independent` I meant that each user can search for the architecture that is most suitable for his own dataset, not just COCO.

`google:` allintext:"Neural Architecture Search" "hours" "object detection" "coco"
`limiting search space example` https://github.com/megvii-model/AngleNAS
`a good nas paper with search space designing examples` https://arxiv.org/abs/1903.10979
`list of some nas` https://www.automl.org/automl/literature-on-neural-architecture-search/

**Comment by deepseek** [comment]
@AlexeyAB is 1bit quantization possible without model degradation?
ibm done it with 8 and possibly 4

**Comment by AlexeyAB** [comment]
> is 1bit quantization possible without model degradation?

Yes, wihtout significant model degration.

> By dataset independent I meant that each user can search for the architecture that is most suitable for his own dataset, not just COCO.

Is there any chart / table where are examples: it takes 10 GPU-hours to improve +1% AP (from 37% to 39%)?

**Comment by deepseek** [comment]
not that i know of

**Comment by deepseek** [comment]
@AlexeyAB i found a NAS that helped make models extremely efficient, the results are unbelievable!
Can we speak privately.
and yes, i have some charts. though not related to object detection directly

**Comment by AlexeyAB** [comment]
Yes, alexeyab84@gmail.com

**Comment by deepseek** [comment]
@AlexeyAB ok i will contact you, delete your email now

**Comment by deepseek** [comment]
@AlexeyAB have you seen the email that i sent you? what do you think

**Comment by eyebies** [comment]
@AlexeyAB 
> > is 1bit quantization possible without model degradation?
> Yes, wihtout significant model degration.
Are you planning on releasing the tiny-yolov4 version of xnor net?

**Comment by bulatnv** [comment]
https://github.com/TNTWEN/Pruned-OpenVINO-YOLO
