### ISSUE TITLE
read weights yolo4 in Python

### ISSUE THREAD

**Issue by MacNgoc** [AlexeyAB/darknet#5727]
@AlexeyAB 

Hi Alexey,
Thank you for the great work. 
I trained both yolo3 and yolo4 for my problem, yolo4 gained about 5% in accuracy compared to Yolo3.
I was so happy. (Thanks to you). Now, I would like to deploy yolo4 on flask. However, I didn't find anything to read weights of Yolo4 in Python. Should you give me some guides/suggestions about this?

Many thanks in advance,

**Comment by AlexeyAB** [comment]
Yolov4 on Pytorch: https://github.com/Tianxiaomo/pytorch-YOLOv4

The first 20 bytes is a header: https://github.com/AlexeyAB/darknet/blob/c0d6b81a78e204c04c9bf4277974e0dadad0c4e2/src/parser.c#L1776-L1780

Then how to load/save weights for each conv-layer: https://github.com/AlexeyAB/darknet/blob/c0d6b81a78e204c04c9bf4277974e0dadad0c4e2/src/parser.c#L1719-L1726

**Comment by MacNgoc** [comment]
Thank you so much !!!!
