### ISSUE TITLE
float infinity in bounding box

### ISSUE THREAD

**Issue by danlapko** [AlexeyAB/darknet#5728]
Hello, first of all thanks for great job! 
I'm trying to run python code of Yolov4 in 3 threads: Preprocessor, Detector and Postprocessor and I've  ran into the following problem - sometimes in postprocessing occurs bb with infinite height and zero width, so `map(int, ...)` funciton crashes.
Since this is a floating error and it occurs very rarely, I cannot be sure that the cause of the error is not my implementation of multi-threading.

I just parallelized the code from performBatchDetect, in this part error occurs:
```
if score > self.thresh:
    box = det.bbox
    try:
        left, top, right, bottom = map(int, (box.x - box.w / 2, box.y - box.h / 2,
                                             # TODO error (can not convert float infinity to integer)
                                             box.x + box.w / 2, box.y + box.h / 2))
    except Exception as e:
        print("Error -->", "i_img", i_img, "/", len(batch_imgs), "img_size",
              batch_imgs[i_img].shape,
              "det", i, "/", num_dets, "cls=", label, "score=", score, "bb:",
              (box.x, box.w, box.y, box.h))
        raise e
    boxes.append((left, top, right, bottom))
    scores.append(score)
    classes.append(label)
    # boxColor = (int(255 * (1 - (score ** 2))), int(255 * (score ** 2)), 0)
    # cv2.rectangle(image_list[i_img], (left, top),
    #               (right, bottom), boxColor, 2)
```

```
Error --> i_img 0 / 1 img_size (720, 1280, 3) det 1 / 187 cls= 0 score= 1.0 bb: (709.0526123046875, inf, 10.421052932739258, 0.0)
Exception in thread Thread-5:
Traceback (most recent call last):
  File ".../anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File ".../darknet/yolov4.py", line 614, in run
    raise e
  File ".../darknet/yolov4.py", line 608, in run
    box.x + box.w / 2, box.y + box.h / 2))
OverflowError: cannot convert float infinity to integer
```
batch_size=1, net_size=608x608

Have you encountered such error, or perhaps you know what caused it?

**Comment by AlexeyAB** [comment]
Do you get `Inf` value for `height` of bbox?
I don't know why does it happen. May be something wrong in `performBatchDetect()` implementation, since there are some issues: 
* https://github.com/AlexeyAB/darknet/issues/5686
* https://github.com/AlexeyAB/darknet/issues/5687

**Comment by danlapko** [comment]
Seems, the cause was that it is unsafe to pass ctypes objects between python threads, even using synchronized Queue. Sorry for disturbing, i'll try to overcome it.

**Comment by FathiMahdi** [comment]
I have the same issue on Rapberrypi4. Is there are relations with 32-bit OS because with 64-bit OS there is no issue

**Comment by FathiMahdi** [comment]
I solved this issue by regenerating the save weights
