### ISSUE TITLE
Default optimizer

### ISSUE THREAD

**Issue by eduardohem** [AlexeyAB/darknet#5735]
Please,

What's the default yolov3 optimizer?

and V4?

**Comment by AlexeyAB** [comment]
The simplest Nesterov Accelerated Gradient (`momentum` and `decay` for weights) for both Yolov3 and Yolov4:
* https://stats.stackexchange.com/questions/70101/neural-networks-weight-change-momentum-and-weight-decay
* https://cs231n.github.io/neural-networks-3/#sgd


Also you can enable Adam optimizer in cfg-file:
```
[net]
adam=1
```

May be I will add Adadelta.

**Comment by eduardohem** [comment]
great, thanks for your help!
