### ISSUE TITLE
 Video-stream stopped! error when running the video demo

### ISSUE THREAD

**Issue by ninenerd** [AlexeyAB/darknet#5740]
I have complied with opencv. For images it is working, but for video it is not reading the frames. 
What can be the issue here. 
Video file is present.

**Comment by Colonel-Latte** [comment]
hi there, I got the same problem, did you manage to fix it?

**Comment by theemtan** [comment]
@ninenerd Hi, have you managed to fix this issue?

**Comment by Colonel-Latte** [comment]
> @ninenerd Hi, have you managed to fix this issue?

yes, put your video file that you want to test to the darknet folder, change the test.mp4 on the command line to the appropriate video name (name of the video file).

**Comment by theemtan** [comment]
Thanks! Did you test it using webcam? I'm having this issue when testing on webcam at the moment.

**Comment by Colonel-Latte** [comment]
> Thanks! Did you test it using webcam? I'm having this issue when testing on webcam at the moment.

Yes, all the command lines works, video, webcam, image.

**Comment by theemtan** [comment]
@Colonel-Latte Can I know what version of OpenCV that you are using currently?

**Comment by Colonel-Latte** [comment]
@theemtan yup, I got OpenCV 4.3.0. 
Compiled using CMake 3.17.2  and CUDA 10.2  for extra detail

**Comment by theemtan** [comment]
Alright, thanks for your help!
