### ISSUE TITLE
At times I am getting two labels for same box

### ISSUE THREAD

**Issue by ninenerd** [AlexeyAB/darknet#5745]
How do I resolve them. Ideally we should be getting one label for each box. 
But for some images I am getting two labels.

Any solution to this ?

**Comment by fengxiuyaun** [comment]
see yolo layer, this maybe happen

**Comment by pullmyleg** [comment]
Adding a threshold to detection can resolve. For example try running the command with -thresh 0.25 if you are not already.

**Comment by ninenerd** [comment]
@pullmyleg Isn't 0.25 threshold default ?
