### ISSUE TITLE
letterbox

### ISSUE THREAD

**Issue by nightfuryyy** [AlexeyAB/darknet#5747]
how can i use letterbox ? i try to add letter_box=1 in file config, is that true ? 
many thanks.

**Comment by WongKinYiu** [comment]
yes, for training add `letter_box=1` in `[net]`.
for testing use `./darknet detector test ur.data ur.cfg ur.weights ur.jpg -letter_box`.

**Comment by nightfuryyy** [comment]
Thank you so much.
