### ISSUE TITLE
hashtag behind train/test .cfg file

### ISSUE THREAD

**Issue by mfaramarzi** [AlexeyAB/darknet#5748]
@AlexeyAB Hi Alex
why there is a hashtag behind test/train, batch and subdivision? also, in some .cfg files hashtag is behind batch and subdivision of test and in some other ones it's behind train's.tnx.

![Screenshot from 2020-05-26 10-32-13](https://user-images.githubusercontent.com/44882423/82913378-35f00d00-9f3c-11ea-80d9-2a49f5196218.png)
![Screenshot from 2020-05-26 10-31-45](https://user-images.githubusercontent.com/44882423/82913379-35f00d00-9f3c-11ea-825a-e324d9c3e960.png)
![Screenshot from 2020-05-26 10-31-07](https://user-images.githubusercontent.com/44882423/82913380-3688a380-9f3c-11ea-8f55-a5f7efa31f39.png)

**Comment by AlexeyAB** [comment]
`#` is a comment in ini/cfg-files. So these lines are not used.
