### ISSUE TITLE
use yolov3-voc.cfg to train error :

### ISSUE THREAD

**Issue by datamonday** [AlexeyAB/darknet#575]
when i use yolov3-voc.cfg to train ,i got this error :(I have change filters and classes)
.
.
 82 detection
darknet: ./src/parser.c:312: parse_yolo: Assertion `l.outputs == params.inputs' failed.
Aborted (core dumped)

thanks!

**Comment by datamonday** [comment]
my yolov3-voc.cfg
[net]
# Testing
# batch=1
# subdivisions=1
# Training
batch=32
subdivisions=32 #16
width=416
height=416
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1
.
.
.
[yolo]
mask = 6,7,8
anchors = 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326
classes=1
num=9
jitter=.3
ignore_thresh = .5
truth_thresh = 1
random=1
.
.
.
[yolo]
mask = 3,4,5
anchors = 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326
classes=1
num=9
jitter=.3
ignore_thresh = .5
truth_thresh = 1
random=1
.
.
.

[convolutional]
size=1
stride=1
pad=1
filters=30 #75
activation=linear

[yolo]
mask = 0,1,2
anchors = 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326
classes=1 #20
num=9
jitter=.3
ignore_thresh = .5
truth_thresh = 1
random=1

**Comment by datamonday** [comment]
my voc.data
classes= 1
train  = /home/chopin/darknet/mydata/VOC2018/2018_train.txt
valid  = /home/chopin/darknet/mydata/VOC2018/2018_val.txt
names = mydata/voc-18.names
backup = mydata/backup-18

my voc.names
person

**Comment by AlexeyAB** [comment]
You forgot to do this: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

Change to `filters=18` in the 3 convolutional layers:

> change [filters=255] to filters=(classes + 5)x3 in the 3 [convolutional] before each [yolo] layer
> https://github.com/AlexeyAB/darknet/blob/0039fd26786ab5f71d5af725fc18b3f521e7acfd/cfg/yolov3.cfg#L603
> https://github.com/AlexeyAB/darknet/blob/0039fd26786ab5f71d5af725fc18b3f521e7acfd/cfg/yolov3.cfg#L689
> https://github.com/AlexeyAB/darknet/blob/0039fd26786ab5f71d5af725fc18b3f521e7acfd/cfg/yolov3.cfg#L776

**Comment by datamonday** [comment]
@AlexeyAB  yeah!you're right! I can train mydata now! Thank you very much!
