### ISSUE TITLE
Yolov3 - Not able to train with custom objects

### ISSUE THREAD

**Issue by fmgracias** [AlexeyAB/darknet#576]
Hi all,

I want to be able to detect objects in hands of people (customers).

I tried to use Yolo9000 in order to look for objects in a ROI around the customer hands but it doesn't classify successfully objects like boxes. I think the classifier fails because I crop a region of the full image and its quality is deteriorated during the resizing procedures of darknet.

In an attempt to solve this I want to train the model with a bunch of cropped and "deteriorated" images of objects in hands of people like this:
![image](https://user-images.githubusercontent.com/32511760/38333953-f51d09f2-3851-11e8-9a44-3a90a8d19f72.png)

The current issue regards the training of the model:

When I run _darknet.exe detector train data/obj.data yolo-obj.cfg darknet53.conv.74_ **nothing happens (no errors/output)!!**:
![image](https://user-images.githubusercontent.com/32511760/38332871-ebaa1f5c-384e-11e8-8481-3c2617baf70b.png)

I've followed the steps in [https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects](url):

1. Created _yolo-obj.cfg_, made the mentioned changes in `batch=64`, `subdivisions=8` and `[convolutional]
filters=21
[yolo]
classes=2` for each of the 3 layers in yolov3. (Yes, I'm training for 2 objects only)
Placed the file in _\x64\Release_ (same folder as _darknet.exe_)

2. Created obj.data, obj.names and train.txt:
**//obj.data**
`classes= 2
train  = data/train.txt
valid  = data/test.txt
names = data/obj.names
backup = backup/
`
**//obj.names**
`book
box
`
**//train.txt**
`data/img/book1.jpg
data/img/book2.jpg
data/img/book3.jpg
(...)
`
**_(all in new lines)_**
3. Labelled every image on the dataset using the recommended tool (Yolo Mark)
![image](https://user-images.githubusercontent.com/32511760/38333313-28ed9294-3850-11e8-81d6-f69c9ea759dc.png)

4. Placed _darknet53.conv.74_ in the same folder as the _yolo-obj.cfg_ (_\x64\Release_)

My _/x64/Release/data_ folder looks like this:
![image](https://user-images.githubusercontent.com/32511760/38333534-c8cc5caa-3850-11e8-946c-a3752ed760ea.png)

Thank you everyone in advance for looking into it.

**Comment by AlexeyAB** [comment]
Hi,

Can you zip these files and drag n drop to you message?

Files `yolo-obj.cfg, obj.data, obj.names, train.txt, and for example 2 images and labels.`

**Comment by fmgracias** [comment]
Sure

[requested_files.zip](https://github.com/AlexeyAB/darknet/files/1877828/requested_files.zip)

Thank you again :)

**Comment by fmgracias** [comment]
Somehow I **fixed it by starting all over again** (download clean up-to-date project and setup everything again).

Now I can run my own training as well as the testing .cmd's recarding yolov3.

I trained for **145 iterations** and I'm getting **some enormous amount of average loss (~86.03)** is this normal? I expected it to start around 4-5, but it started at ~950 average loss :/
![image](https://user-images.githubusercontent.com/32511760/38344968-563e9bf6-3884-11e8-8e58-850f081992cf.png)

**Any tips to improve this?** Or should I do something like 1-2k iterations before rushing into conclusions?

Not sure if the image quality is affecting this, or the pre-trained weights selected isn't the best [https://pjreddie.com/media/files/darknet53.conv.74 ](url), or something else..

@AlexeyAB , thank you so much again. I'm very grateful for your prompt support 🥇 🥇

**Comment by AlexeyAB** [comment]
@fmgracias Thats ok. Training goes well.
