### ISSUE TITLE
undefined reference to 'Detector::Detector(std::string, std::string, int)'

### ISSUE THREAD

**Issue by qawsedrg** [AlexeyAB/darknet#5760]
I have successfully compiled the libdark.so and linked it to my project by using
`link_directories(/home/chz/Downloads/darknet-master/build-dir)`
`link_libraries(libdark.so)`
`target_link_libraries( My_project libdark.so )`
and I have also included yolo_v2_class.hpp.

But when compiling my project the compiler tells continuously 
`undefined reference to 'Detector::Detector(std::string, std::string, int)'`.
Could you tell me that if there is any problem concerning the way i use the libdark.so?
@AlexeyAB

**Comment by deeplearning666** [comment]
Have you solved the question? I have the save question with you. @qawsedrg

**Comment by qawsedrg** [comment]
Yes, I have. The precompiled libtorch is built with the old C++ ABI which may be incompatible with the libdark.so you have built. You may recompile libtorch with 
`if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")`
  `set(TORCH_CXX_FLAGS "-D_GLIBCXX_USE_CXX11_ABI=1")`
`endif()` 
in `TorchConfig.cmake`
or you may recompile darknet with gcc<5.1 and set `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")`  in the Cmakelists.txt in your own project to enable old C++ ABI.
You may refer to `https://discuss.pytorch.org/t/issues-linking-with-libtorch-c-11-abi/29510/9`

**Comment by xyzhai-pro** [comment]
In linux, compile darknet as libdarknet.so. I just write a simple yolo_console_dll.cpp to link .so.
when i type the command as g++ -fPIC -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 yolo_console_dll.cpp -L./lib/ -I. -ldarknet $(pkg-config --cflags --libs opencv) -o test.
The error is /tmp/ccis7rE8.o：function‘main’： yolo_console_dll.cpp:(.text+0xb11)‘Detector::Detector(std::string, std::string, int)’undefined reference 
collect2: error: ld returned 1 exit status

look forward to your reply, thanks.

**Comment by xyzhai-pro** [comment]
@qawsedrg
