### ISSUE TITLE
Why are the prediction results different from pjreddie/darknet?

### ISSUE THREAD

**Issue by keto33** [AlexeyAB/darknet#5767]
I use the same files in both, but the results are different:

`/darknet classifier predict cfg/imagenet1k.data cfg/darknet19.cfg darknet19.weights data/dog.jpg
`

**pjreddie/darknet**
```
data/dog.jpg: Predicted in 0.003919 seconds.
42.35%: malamute
23.06%: Eskimo dog
12.67%: Siberian husky
 2.75%: bicycle-built-for-two
 1.21%: mountain bike
```

**AlexeyAB/darknet**
```
data/dog.jpg: Predicted in 4.415000 milli-seconds.
malamute: 0.521573
Eskimo dog: 0.272391
Siberian husky: 0.116594
dogsled: 0.021984
bicycle-built-for-two: 0.008623
```

This difference is much more significant for other images.

My question is: when using the same pre-trained models and data, why are the predictions different?

**Comment by WongKinYiu** [comment]
The pre-pocessing of **pjreddie/darknet** and **AlexeyAB/darknet** are different.

https://github.com/pjreddie/darknet/blob/master/examples/classifier.c#L589

https://github.com/AlexeyAB/darknet/blob/master/src/classifier.c#L847-L848
