### ISSUE TITLE
Hi, It seems darknet has been changed in yolov4. Could anyone provide updates on yolov4 ROS package? 

### ISSUE THREAD

**Issue by hahaheihei09** [AlexeyAB/darknet#5768]
Hi, It seems darknet has been changed in yolov4. Could anyone provide updates on yolov4 ROS package?

**Comment by cosama** [comment]
Made a fork of: https://github.com/tom13133/darknet_ros with a few improvements at https://github.com/cosama/darknet_ros. Seems to work just fine.

**Comment by hahaheihei09** [comment]
Great! Thank!

**Comment by Shame-fight** [comment]
Thanks for your work, I have tested this version on pc and there is a problem: the exact same boundingbox was pubilshed twice and it happened very frequently. Does this mean that the same frame image was processed twice? Increase Unnecessary amount of calculation?
@cosama

**Comment by cosama** [comment]
@Shame-fight: Known issue, see https://github.com/leggedrobotics/darknet_ros/issues/150. I think there are other issues filled at `leggedrobotics` talking about the same issue and there seem to even be pull requests related to that. Check out their repo for solutions. If you find a working efficient solution I'm happy to pull it into my own repo.

**Comment by Fenix0817** [comment]
> Made a fork of: https://github.com/tom13133/darknet_ros with a few improvements at https://github.com/cosama/darknet_ros. Seems to work just fine.

Thank you.
