### ISSUE TITLE
bash: ./darknet: No such file or directory

### ISSUE THREAD

**Issue by Laudarisd** [AlexeyAB/darknet#5778]
I was trying to train in V4 . Seems darknet file is missing here. 
can anybody help me here? 
Thank you

**Comment by nanthamjeeva** [comment]
Am stuck here too ! Any solution ?

**Comment by stephanecharette** [comment]
Did you build it?  If so, which technique did you use (vcpkg, cmake, makefile)?  What directory are you in when you attempt to run it?

**Comment by Laudarisd** [comment]
@stephanecharette @nanthamjeeva  as stephanecharette asked, 
you need to run `make` file in the main directory after downloading the darknet framework from this repository. 
Hope this will help.

**Comment by stephanecharette** [comment]
> you need to run `make` file in the main directory

That is only partly true.  If you install it with vcpkg, then you don't need to run "make" or anything else.  Vcpkg takes care of all that, making it much simpler for non-developers to use Darknet.  Vcpkg also takes care of OpenCV and CUDA if needed.

**Comment by nanthamjeeva** [comment]
> Did you build it? If so, which technique did you use (vcpkg, cmake, makefile)? What directory are you in when you attempt to run it?

I run it in colab and yes , i did run the make file ..... and i am still in the correct directory ........... but it says this ... :-(

**Comment by stephanecharette** [comment]
I'm not familiar with colab. So what files are in that directory if you built it?

**Comment by nanthamjeeva** [comment]
> I'm not familiar with colab. So what files are in that directory if you built it?

Sorry for the late reply ........... i was not using the latest version of files from this repo ... when i redid the while thing, it worked like a charm :-)
