### ISSUE TITLE
train efficientnet got resize divide by zero

### ISSUE THREAD

**Issue by ald2004** [AlexeyAB/darknet#5782]
If you want to report a bug - provide:
    * description of a bug
       when using efficientnet_b0.cfg set picture w and h goes segment fail
    * what command do you use?
        detector train data/chef_enetb0.data cfg/efficientnet_b0.cfg weights/enetb0.132 -dont_show
    * do you use Win/Linux/Mac?
      Linux
    * attach screenshot of a bug with previous messages in terminal
      OpenCV(4.2.0) /home/yuanpu/opencv-4.2.0/modules/core/src/alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 10429652905774891008 bytes in function 'OutOfMemoryError'
    * in what cases a bug occurs, and in which not?
     parser.c when parse net.layer.resize didnot give a default value 1,but 0,
     give parser.c L:1502 "l.resize = option_find_float_quiet(options, "resize", 1);" should work but i am not sure
    * if possible, specify date/commit of Darknet that works without this bug
     use default cfg and efficientnet weights.
    * show such screenshot with info
```
[yuanpu@xxx efficientnet]$ darknet detector train data/chef_enetb0.data cfg/efficientnet_b0.cfg weights/enetb0.132 -gpus 0 -dont_show
 CUDA-version: 10010 (10020), cuDNN: 7.6.5, CUDNN_HALF=1, GPU count: 3  
 CUDNN_HALF=1 
 OpenCV version: 4.2.0
0
efficientnet_b0
 0 : compute_capability = 700, cudnn_half = 1, GPU: Tesla V100-PCIE-32GB 
net.optimized_memory = 0 
mini_batch = 3, batch = 96, time_steps = 1, train = 1 
   layer   filters  size/strd(dil)      input                output
   0 conv     32       3 x 3/ 2    608 x 608 x   3 ->  304 x 304 x  32 0.160 BF
   1 conv     32       1 x 1/ 1    304 x 304 x  32 ->  304 x 304 x  32 0.189 BF
   2 conv     32/  32  3 x 3/ 1    304 x 304 x  32 ->  304 x 304 x  32 0.053 BF
   3 avg                           304 x 304 x  32 ->     32
   ===========================
Total BFLOPS 6.718 
avg_outputs = 816051 
 Allocate additional workspace_size = 115.89 MB 
Loading weights from weights/enetb0.132...
 seen 64, trained: 0 K-images (0 Kilo-batches_64) 
Done! Loaded 134 layers from weights-file 
Learning Rate: 0.001, Momentum: 0.9, Decay: 5e-05
 args.resize = 0.000000 
 Create 6 permanent cpu-threads 
OpenCV(4.2.0) /home/yuanpu/opencv-4.2.0/modules/core/src/matrix.cpp:235: error: (-215:Assertion failed) s >= 0 in function 'setSize'
 
OpenCV(4.2.0) /home/yuanpu/opencv-4.2.0/modules/core/src/matrix.cpp:235: error: (-215:Assertion failed) s >= 0 in function 'setSize'
 
OpenCV(4.2.0) /home/yuanpu/opencv-4.2.0/modules/core/src/alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 10429652905774891008 bytes in function 'OutOfMemoryError'
 
*** Error in `darknet': corrupted size vs. prev_size: 0x00007f76b40011e0 ***
*** Error in `darknet': corrupted double-linked list: 0x00000000020bdaa0 ***
Segmentation fault
```

**Comment by AlexeyAB** [comment]
efficientnet_b0.cfg is a classifier, not detector.

Also attach your cfg-file.

**Comment by ald2004** [comment]
[efficientnet_b0.cfg.txt](https://github.com/AlexeyAB/darknet/files/4714335/efficientnet_b0.cfg.txt)

appreciate your time, i'm not a expert, in my mind cfg is whole detector and classifier configuration.

**Comment by AlexeyAB** [comment]
Detector:

https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/enet-coco.cfg

https://drive.google.com/file/d/1FlHeQjWEQVJt0ay1PVsiuuMzmtNyv36m/view
