### ISSUE TITLE
Making changes to the loss function

### ISSUE THREAD

**Issue by trendi4** [AlexeyAB/darknet#5785]
The first term of the loss function is shown in the picture below.
![image](https://user-images.githubusercontent.com/44017888/83228252-3da2f200-a186-11ea-848e-dbaab1f0fc37.png)

In order to adjust the loss function to my use case, I need to transform the loss function to the following:

![image](https://user-images.githubusercontent.com/44017888/83228130-06ccdc00-a186-11ea-90ac-17767f79b256.png)

Where can I find the loss function in the source code to make my adjustments? I skimmed through the code, but could not find where the loss function is defined.

**Comment by AlexeyAB** [comment]
Since in the Darknet there is no automatic differentiation and automatic execution of chain rules, then all the gradients have to be implemented manually in CUDA C++:

https://github.com/AlexeyAB/darknet/blob/e6469eb071521a4ff5be8c0e9cceb524d0a65a95/src/yolo_layer.c#L172-L184
