### ISSUE TITLE
Where is CmBN?

### ISSUE THREAD

**Issue by jasw1001** [AlexeyAB/darknet#5786]
I humbly ask for the location of CmBN codes?

I cannot fully understand the explaination of CmBN in paper..... so where can I find the codes?

**Comment by WongKinYiu** [comment]
https://github.com/AlexeyAB/darknet/blob/master/src/batchnorm_layer.c#L262-L288

**Comment by jasw1001** [comment]
Thanks

**Comment by CoinCheung** [comment]
where is the definition of this function: `fast_v_cbn_gpu` ?
Or can anyone explain the details of how cmbn is implementated?
