### ISSUE TITLE
About creating voc-datesets and training

### ISSUE THREAD

**Issue by datamonday** [AlexeyAB/darknet#579]
Hey! @AlexeyAB 
First of all, thank you for your selfless contribution and help.

I met a problem when I trian my voc data.and I guess this problem is causeb by my datasets.like this:

"Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.489743, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.425603, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: 0.322060, Class: 0.511393, Obj: 0.234028, No Obj: 0.426030, .5R: 0.000000, .75R: 0.000000,  count: 1
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.493107, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.418824, .5R: -nan, .75R: -nan,  count: 0
Region 82 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.432310, .5R: -nan, .75R: -nan,  count: 0
Region 94 Avg IOU: 0.331917, Class: 0.454190, Obj: 0.485964, No Obj: 0.491441, .5R: 0.400000, .75R: 0.000000,  count: 5
Region 106 Avg IOU: 0.251026, Class: 0.380225, Obj: 0.244140, No Obj: 0.417663, .5R: 0.000000, .75R: 0.000000,  count: 5
Region 82 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.435855, .5R: -nan, .75R: -nan,  count: 0
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.492674, .5R: -nan, .75R: -nan,  count: 0
"
I promise each picture have one box at lease ,but why got so many "count:0"? I remember train pascal voc in yolov2 not asking so much. what's wrong?

Besides,I'm not very clear about create voc datasets ,if i use  Gaussian Blur,Gray scale transformation，only use one channel in HSV, Can I  train in yolo v3?

Thank you again!

**Comment by AlexeyAB** [comment]
* How many iterations did you train and what mAP can you get?
* Do you get `nan` in all lines or only in some lines?
* Can you successfully train Yolo v3 without "Gaussian Blur,Gray scale transformation，only use one channel in HSV"?
* Gaussian Blur,Gray scale transformation - shouldn't be a problem for training Yolo v3

**Comment by AlexeyAB** [comment]
Yes. Yes.
There are no strict requirements for images. There are only recommendations to make the image larger or equal to the size of the neural network.

**Comment by datamonday** [comment]
All right!👍
