### ISSUE TITLE
Unsupported activation: mish error with OpenCV and YOLOv4 models

### ISSUE THREAD

**Issue by dsbyprateekg** [AlexeyAB/darknet#5805]
Hi,

After training a custom dataset with YOLOv4 I want to use model weights and configuration file with OpenCV. While testing I am getting below error-

`net = cv.dnn.readNetFromDarknet(model_config, model_weights)
cv2.error: OpenCV(4.2.0) ..\modules\dnn\src\darknet\darknet_io.cpp:686: error: (-212:Parsing error) Unsupported activation: mish in function 'cv::dnn::darknet::ReadDarknetFromCfgStream'`

My system configuration is as below-
Windows 10
NVidia GeForce GTX 1660 Ti
Cuda 10.1
cuDNN 7.6.5
Visual Studio 2017

Please suggest how can I resolve this error?

**Comment by AlexeyAB** [comment]
Or use OpenCV 3.4 branch: https://github.com/opencv/opencv/archive/3.4.zip
Or wait for new OpenCV release after 2020-04-23 https://opencv.org/releases/

**Comment by dsbyprateekg** [comment]
Thanks @AlexeyAB .

**Comment by yassinesefrioui** [comment]
Hello ! 
i tried with OpenCV 3.4.2. it is not working !!
@AlexeyAB, please do you have a solution ?? 

ubuntu 
yolov4-custom.cfg 
NVidia GeForce GTX 1060 
Cuda 10.1
cuDNN 7.6.5

thank you

**Comment by ramdhan1989** [comment]
> Or use OpenCV 3.4 branch: https://github.com/opencv/opencv/archive/3.4.zip
> Or wait for new OpenCV release after 2020-04-23 https://opencv.org/releases/

thanks a lot @AlexeyAB. I have old opencv 3.4.2 installed in my machine. do you have any reference how to install it the one that support yolov4 ? [https://github.com/opencv/opencv/archive/3.4.zip](url) 

thank you

**Comment by mon28** [comment]
@AlexeyAB when is this change releasing for the python library?
