### ISSUE TITLE
I make demo for a video and save frames, but the labels are one frame delay in YOLOv3

### ISSUE THREAD

**Issue by mhernandezArtificialVision** [AlexeyAB/darknet#5806]
Hello everyone
I have a problem, when I make a detection in a video, the bounding box that show in the image is from the next frame, not from the actual frame. I have the same problem when I save the frames of that video. I tried with different videos, but I have the same problem
Thank you
Best regards

**Comment by AlexeyAB** [comment]
Use flag `-avgframes 1` at the end of detection command

`./darknet detector demo ... -avgframes 1`

**Comment by mhernandezArtificialVision** [comment]
Hello AlexeyAB,
I tried it and works perfectly
Thank you so much
Best regards

**Comment by Tacokeet** [comment]
This `-avgframes 1` flag fixed the problem using the `darknet detector demo ...` command.
But now I want to use the darknet_video.py to detect and get result but there is also a one frame delay here.
Is there anyway to use this fix within the python code? Or is there any other solution?
