### ISSUE TITLE
Please explain new output parameters (.5R and .75R)

### ISSUE THREAD

**Issue by spinoza1791** [AlexeyAB/darknet#581]
Could you please explain the meaning of these two new output parameters for .5R and .75R?  Also, are they used the same in yolov2 vs yolov3?

Example:
Region 16 Avg IOU: 0.693620, Class: 0.903130, Obj: 0.184031, No Obj: 0.002081, **.5R: 0.909091, .75R: 0.418182**,  count: 55

**Comment by spinoza1791** [comment]
Found in src/yolo.c
                if(iou > .5) recall += 1;
                if(iou > .75) recall75 += 1;
                avg_iou += iou;

So, its just the recall split out under two criteria, so that you can judge for yourself

**Comment by spinoza1791** [comment]
my question is answered

**Comment by ForeverStrongCheng** [comment]
Thank you very much.

**Comment by AlexeyAB** [comment]
More about it: https://github.com/AlexeyAB/darknet/issues/636#issuecomment-381400954
