### ISSUE TITLE
how to change the loss function and non maximum suppression function

### ISSUE THREAD

**Issue by zhshen1992** [AlexeyAB/darknet#5821]
Hi,
Can someone tell me how to change the loss function and non maximum suppression function? or just tell me where is the definition/code of loss function?
Due to our target characteristics, we need a new loss function to adapt to our data set, neither iou nor ciou.
Thank you.

**Comment by AlexeyAB** [comment]
Because there is no automatic differentiation and automatic execution of chain rules, then all the gradients have to be implemented manually in C: 
https://github.com/AlexeyAB/darknet/blob/c625cc6503e9ccac41ecdd352a90fdff6d2a7859/src/yolo_layer.c#L156-L308

**Comment by zhshen1992** [comment]
Thank you! At firtst we gonna test our algorithm and then implement this in your source code

**Comment by zhshen1992** [comment]
Could you explain a little bit about the meaning of "_wrt_", like the dI_wrt_t, dU_wrt_t, dX_wrt_t and dC_wrt_t in file box.c.
https://github.com/AlexeyAB/darknet/blob/05dee78fa3c41d92eb322d8d57fb065ddebc00b4/src/box.c#L258-L392

**Comment by zhshen1992** [comment]
@AlexeyAB
