### ISSUE TITLE
File not found: highgui_c.h

### ISSUE THREAD

**Issue by abagshaw** [AlexeyAB/darknet#583]
The most recent commit (https://github.com/AlexeyAB/darknet/commit/943f6e874b819271a87665cf41199388380989a0) broke the build for me.

I don't have OpenCV installed but it appears that this line is requiring it:

https://github.com/AlexeyAB/darknet/blob/master/src/network_kernels.cu#L42

Is it necessary to use OpenCV? If so, it's a little misleading that compiling with `OPENCV=0` still requires OpenCV. Thanks!

---

As a side note, it appears that the `make LIBSO=1 GPU=0 CUDNN=0 OPENCV=0 -j 8` CI test runs on an environment with OpenCV installed. Might be a good idea to change that 😄

**Comment by AlexeyAB** [comment]
@abagshaw I fixed it now.
New commit fixes it.

PS Very strange that circleci (build bot) didn't find this error

**Comment by abagshaw** [comment]
@AlexeyAB Thanks for the lightning quick fix! See my comment above as to why CircleCI probably missed it.
