### ISSUE TITLE
train custom dataset issue

### ISSUE THREAD

**Issue by flydragon2018** [AlexeyAB/darknet#5842]
./darknet detector train /content/darknet/build/darknet/x64/data/obj.data /content/darknet/cfg/yolo-obj.cfg yolov4.conv.137

,,,,,,,,,
.........
138 Cuda malloc failed
: File exists
darknet: ./src/utils.c:326: error: Assertion `0' failed.

what could be problems?

thank you in advance!!!

**Comment by flydragon2018** [comment]
my data images are of different sizes.  Will  darknet automaticly resize the image size,  or should I preprocess the images first before training?
thanks!

**Comment by AlexeyAB** [comment]
> Will darknet automaticly resize the image size, 

Yes.

**Comment by flydragon2018** [comment]
thank you for your confirmation.   I  followed every instruction step for training custom dataset.

some people says that the error is possible caused by t the encoding of  cfg file due to copying file between different OS.   I edit the cfg files in windows 10 and uploaded to google drive. I have made sure that  these files are in ANSI format.  

what could I missed ?

**Comment by flydragon2018** [comment]
I moved the my training data etc from  /content/darknet/build/darknet/x64/data  to /content/darknet/data  etc correspondingly, It starts training.  Don't know the reason.
perhaps previously I missed something.
