### ISSUE TITLE
-json_port 8070 no listening port

### ISSUE THREAD

**Issue by 1027663760** [AlexeyAB/darknet#5846]
Command used: 
detector train Data\voc.data cfg\yolov4-tiny.cfg -gpus 0 -json_port 8070 -mjpeg_port 8090

But -json_port 8070 doesn't have a listening port at all
-mjpeg_port 8090 is functioning normally

The darknet I use is the latest version

**Comment by AlexeyAB** [comment]
![image](https://user-images.githubusercontent.com/4096485/83871547-eb8b3f00-a738-11ea-9a85-11c83def403f.png)


![image](https://user-images.githubusercontent.com/4096485/83871531-e1694080-a738-11ea-8b90-d21e8a905cd6.png)

**Comment by 1027663760** [comment]
@AlexeyAB 
-json_port is only valid for detector demo?
I use detector train ...--mjpeg_port 8090 is normal

**Comment by AlexeyAB** [comment]
> -json_port is only valid for detector demo?

Yes.
