### ISSUE TITLE
Cuda out of memory when iou_loss=giou

### ISSUE THREAD

**Issue by chinmayembedded** [AlexeyAB/darknet#5848]
When **iou_loss=ciou** (refer yolo-obj.txt), the training works fine.

But when **iou_loss=giou**(refer yolo-obj-giou.txt), the training shows out of memory issues. (refer output_log.txt)

**Changes done in each yolo layer:**

- ignore_thresh = .9 

- iou_normalizer=0.5 

- iou_loss=giou

GPU: TITAN XP 12 GB

**Command**: ./darknet detector train data/obj.data yolo-obj-giou.cfg yolov4.conv.137 -dont_show -mjpeg_port 8090 -map
**Cuda**: 9
**OpenCV**: 4.2

[output_log.txt](https://github.com/AlexeyAB/darknet/files/4735553/output_log.txt)
[yolo-obj.txt](https://github.com/AlexeyAB/darknet/files/4735554/yolo-obj.txt)
[yolo-obj-giou.txt](https://github.com/AlexeyAB/darknet/files/4735555/yolo-obj-giou.txt)

**Comment by AlexeyAB** [comment]
Use the same params
![image](https://user-images.githubusercontent.com/4096485/83870860-a6b2d880-a737-11ea-938e-5139537e96b1.png)

**Comment by chinmayembedded** [comment]
Yeah, sorry for the mis configuration in file. We tried with both ways, but still got the issue.

Currently we are using batch=64 and subdivisions=64, it's working. Just slow performance.

Thanks for the help.
