### ISSUE TITLE
Process close itself after 'Create 6 permanent cpu-threads'

### ISSUE THREAD

**Issue by jack04060201** [AlexeyAB/darknet#5854]
Hello, I use yolov3-tiny to training to do my university project, and I use vs2017 to build darknet.
But my training always closes after 'Create 6 permanent cpu-threads', and I try to add -dont-show, the result is the same.
![image](https://user-images.githubusercontent.com/17104362/83881849-d7186800-a773-11ea-8e57-4e7aa79e0818.png)
After jump out the chart, it will close in second.
![image](https://user-images.githubusercontent.com/17104362/83880898-7c324100-a772-11ea-9769-f27cd3dde26b.png)

and this is yolov3-tiny.cfg
I only use 1 class.
```
[net]
# Testing
# batch=1
# subdivisions=1
# Training
 batch=64
 subdivisions=16
width=416
height=416
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
burn_in=1000
max_batches =10000
policy=steps
steps=400000,450000
scales=.1,.1

[convolutional]
batch_normalize=1
filters=16
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=1

[convolutional]
batch_normalize=1
filters=1024
size=3
stride=1
pad=1
activation=leaky

###########

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=18
activation=linear



[yolo]
mask = 3,4,5
anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
classes=1
num=6
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1

[route]
layers = -4

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[upsample]
stride=2

[route]
layers = -1, 8

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=18
activation=linear

[yolo]
mask = 0,1,2
anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
classes=1
num=6
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1
```

Can anyone help me? Thank a lot.

**Comment by jack04060201** [comment]
I found that will 100% GPU use at the moment before close.

**Comment by jack04060201** [comment]
I found the problem, is a path-error in voc.data. How ridiculous I. Sorry for everyone

**Comment by abhi5691** [comment]
hello @jack04060201 

I am facing the same issue. No matter whether I try yolov3 or yolov3-tiny, the training is aborted with message "Create 6 permanent cpu-threads". Can you kindly elaborate on what you did to resolve it in your case?

**Comment by jack04060201** [comment]
> hello @jack04060201
> 
> I am facing the same issue. No matter whether I try yolov3 or yolov3-tiny, the training is aborted with message "Create 6 permanent cpu-threads". Can you kindly elaborate on what you did to resolve it in your case?

just path-error
