### ISSUE TITLE
Question about labeling image when training to detect custom object

### ISSUE THREAD

**Issue by SirTapir** [AlexeyAB/darknet#5857]
I want to train a model to detect 2 object: knife and machete. 
I understand that I need to label images contaning those object with the following format 

- <object-class> - integer object number from 0 to (classes-1)

- <x_center> <y_center> <width> <height> - float values relative to width and height of image, it can be equal from (0.0 to 1.0]

- for example: <x> = <absolute_x> / <image_width> or <height> = <absolute_height> / <image_height>

- attention: <x_center> <y_center> - are center of rectangle (are not top-left corner)

When training, do I also need to provide images without both knife and machete as a training dataset?

What about providing images without both knife and machete as test to check mAP? Do I need to label those images too?
If I need to label those images too, do I just provide an empty text file with the same name as those images?

**Comment by AlexeyAB** [comment]
desirable that your training dataset include images with non-labeled objects that you do not want to detect - negative samples without bounded box (empty .txt files) - use as many images of negative samples as there are images with objects

https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

**Comment by SirTapir** [comment]
@AlexeyAB Thank you for the answer.
