### ISSUE TITLE
compile yolo without gpu and opencv

### ISSUE THREAD

**Issue by robosina** [AlexeyAB/darknet#586]
Hi
I want to compile yolo without gpu and opencv and run yolo in Qt, so I open `yolo_console_dll.sln` file and remove GPU and OpenCV from preprocessor definition but even with doing that I get some error about opencv (because I haven't opencv that compiled with msvc) so I want to compile without it so I clear opencv and gpu from `yolo_console_dll.cpp` and compile it again but again I encounter with new issue 

![capture](https://user-images.githubusercontent.com/14973524/38409845-3dd141b2-3998-11e8-8222-085cacc63fd6.JPG)

**Comment by AlexeyAB** [comment]
You should compile `yolo_cpp_dll.sln` at first.

`yolo_console_dll.sln` uses Darknet as SO/DLL library, i.e. it uses `yolo_cpp_dll.dll` and `yolo_cpp_dll.lib` files.

**Comment by robosina** [comment]
I compile what you say but I want to use this dll in my program but when I use `yolo_v2_class.hpp` it give me some error about linking problem

my main.cpp
    ```
#include <opencv2/opencv.hpp>
using namespace cv;
#inclue <new_class>
int main()
 {
        new_class ins;
 }
```

my new_class definition is simple as below

new_class.h
```
#ifndef NEW_CLASS_H
#define NEW_CLASS_H
#define OPENCV
#include <yolo_v2_class.hpp>
class new_class
{
      new_class();
      Detector* detector;
}
```

new_class.cpp
```
#include "new_class.h"
new_class:new_class()
{
    detector = new Detector ("path_to_cfg","path_to_weights");
}
```

it's give me some strange error but when I remove OPENCV definition the program workes fine ... or if I declear everything even `#define OPENCV` the program still works but when I want to use in class I get below errors

**Comment by robosina** [comment]
I compile with version 2 and it hasn't any problem but newer version of yolo seems have some problem in c++ side

**Comment by robosina** [comment]
I can't understand what's wrong with yolo version 3 when I add 
`
#define OPENCV
#define#include <yolo_v2_class.hpp>
`
in more than one header files it give me some error about linking

**Comment by robosina** [comment]
@AlexeyAB , Could you please see below links that I get a video from my screen(I think there is serious Issue that I can't figure it why this happen)

[http://s8.picofile.com/d/8324000842/18a8d59e-f1cc-4fac-a333-f23c9052eec9/Rec_2018_04_18_14_51_28.mp4](url)

**Comment by AlexeyAB** [comment]
I can't open this video.

**Comment by robosina** [comment]
Sorry I upload it to another site , you can now access it via this [link](https://uploadfiles.io/e95sg) (after 3 seconds you can press slow donwload and download my video)

it video you can see sometimes my application crushed and when I debug it with visual studio I see that there is a problem with layer.c file which you can see it in below image
![capture1123](https://user-images.githubusercontent.com/14973524/38932130-91b56952-432a-11e8-8403-986e99526c61.JPG)

**Comment by AlexeyAB** [comment]
1. Change this line: https://github.com/AlexeyAB/darknet/blob/9f2dbfa7df981d41c070261c4b9a8a875b290203/src/yolo_v2_class.hpp#L449
to this: 
`static cv::Scalar obj_id_to_color(int obj_id) {`

----

2. Try to use such main function - **will the END line be shown?**
```cpp
int main() {
 {
  Detector detector2(..., ...); // add your paths
  cv::Mat img(100, 100, CV_8UC3);
  detector2.detect(img);
  std::cout << "\n Detected \n";
 }
 std::cout << "\n END \n";
return 0;
}

**Comment by robosina** [comment]
@AlexeyAB ,Thanks very much it solved with adding `static` to that line and now I can use YoloV3 header in other classes without any error but sometimes program crush with below message.

![crush](https://user-images.githubusercontent.com/14973524/38936347-d1c7877c-4335-11e8-803c-868b5669a500.JPG)

**Comment by AlexeyAB** [comment]
@robosina Try to comment all code inside destructor: https://github.com/AlexeyAB/darknet/blob/8fcf3f04eec0e4b776e053047010d29ab6b53ea5/src/yolo_v2_class.cpp#L92-L111
will there be any errors in this case?

If it helps, try to localize the line of code that causes the error.

**Comment by robosina** [comment]
@AlexeyAB ,I comment line 52 of `yolo_v2_class.hpp` and those line that you said and then rebuild both `yolo_cpp_dll.sln` and `yolo_cpp_dll_no_gpu.sln` but this problem still accuring.

**Comment by robosina** [comment]
I comment line 52 of `yolo_v2_class.hpp` and those line that you said, and then I recompile the `yolo_cpp_dll.sln` and `yolo_cpp_dll_no_gpu.sln` but the program still crushed.

**Comment by robosina** [comment]
@AlexeyAB , I test the program in ubuntu using valgrind to check if there is leak memory or not, the answer in in below pic

![selection_052](https://user-images.githubusercontent.com/14973524/38973815-d016098a-43bc-11e8-8a82-1556ac632c84.jpg)

**Comment by AlexeyAB** [comment]
Did you rename `darknet.so` (this repo) to the `libdarknet.so` (original repo)? Or do you use original repository to create SO-library? 

Try to set checkpoints or just add `printf("\n 1 \n ");`,  `printf("\n 2 \n ");` in different places to check what part of code leads to an error.

**Comment by robosina** [comment]
Yes I do that,
can You please check my weights and cfg file? you can access to this files via [this](https://ufile.io/caf5t) link

**Comment by robosina** [comment]
@AlexeyAB , I guess this situation make problems right?
![selection_057](https://user-images.githubusercontent.com/14973524/39081106-9f4e98ae-4550-11e8-98fb-c820a9e80abe.jpg)
