### ISSUE TITLE
VCPKG Install Darknet [Full]: X64-Windows has a problem

### ISSUE THREAD

**Issue by dswcmp** [AlexeyAB/darknet#5860]
Host Environment

OS: Microsoft Windows [ 10.0.18363.836]
Visual Studio 2019 16.6.1
 
I am sorry that I have no experience in this field, I just started learning "machine learning", I did not know that the mistake I encountered was the problem of which module, so I also submitted this in VCPKG.Please let me know if I shouldn't submit this here...
Here are the mistakes I encountered

PS G:\darknetYolo4\vcpkg> .\vcpkg install darknet[full]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    darknet[core,cuda,cudnn,full,opencv-cuda,weights,weights-train]:x64-windows
Starting package 1/1: darknet:x64-windows
Building package darknet[core,cuda,cudnn,full,opencv-cuda,weights,weights-train]:x64-windows...
-- Using cached G:/darknetYolo4/vcpkg/downloads/AlexeyAB-darknet-81290b07376c5abb4988a492dda70913bb90133d.tar.gz
-- Using source at G:/darknetYolo4/vcpkg/buildtrees/darknet/src/13bb90133d-a4584e7461
-- Using cached G:/darknetYolo4/vcpkg/downloads/darknet-cache/yolov3.weights
-- Using cached G:/darknetYolo4/vcpkg/downloads/darknet-cache/yolov2.weights
-- Using cached G:/darknetYolo4/vcpkg/downloads/darknet-cache/yolov3-tiny.weights
-- Using cached G:/darknetYolo4/vcpkg/downloads/darknet-cache/yolov2-tiny.weights
-- Using cached G:/darknetYolo4/vcpkg/downloads/darknet-cache/darknet53.conv.74
-- Using cached G:/darknetYolo4/vcpkg/downloads/darknet-cache/darknet19_448.conv.23
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: G:/darknetYolo4/vcpkg/buildtrees/darknet/x64-windows-dbg
    See logs for more information:
      G:\darknetYolo4\vcpkg\buildtrees\darknet\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/darknet/portfile.cmake:107 (vcpkg_install_cmake)
  scripts/ports.cmake:76 (include)

Error: Building package darknet:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: darknet:x64-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by dswcmp** [comment]
[install-x64-windows-dbg-out.log](https://github.com/AlexeyAB/darknet/files/4739298/install-x64-windows-dbg-out.log)

**Comment by dsbyprateekg** [comment]
Hi @dswcmp 
You are using Visual Studio 2019 which is not supported currently.
Please use Visual Studio 2017 and then build will be successfully.
For more details you can follow [http://dsbyprateekg.blogspot.com/2020/05/how-to-install-and-compile-yolo-v4-with.html](url)

**Comment by dswcmp** [comment]
Oh oh! Thank you very much. I didn't see the relevant hint. I'll try vS2017.

**Comment by dswcmp** [comment]
Hello @dsbyprateekg .May I ask, I have installed VS2019 and VS2017 at the same time, what do I need to set?What should I do?

**Comment by dsbyprateekg** [comment]
@dswcmp Do you really need 2019 version?
If not necessary just uninstall 2019 version and then install 2017 version only.

**Comment by dswcmp** [comment]
thank you

**Comment by dswcmp** [comment]
I uninstalled VS2019 and installed VS2017. Then I encountered other problems
This is the link to the new question
[https://github.com/microsoft/vcpkg/issues/11833](url)

I intend to modify vS2017 to install Win10SDK_10.0.10586.212,version=10.0.10586.21218, but there is an error and it cannot be installed.Is that the problem?I am sorry that I have little experience, so come here for help.
Thank you for any help.

**Comment by dswcmp** [comment]
The problem should be low end, and the completed reinstall of the Windosw SDK will suffice

**Comment by NancyLi1013** [comment]
I can build `darknet `successfully on Visual Studio 2019. So it might be nothing with this. 
```
PS F:\tools\vcpkg> .\vcpkg.exe install darknet[full]:x64-windows
Computing installation plan...
The following packages are already installed:
    darknet[core,cuda,cudnn,full,opencv-cuda,weights,weights-train]:x64-windows
Package darknet:x64-windows is already installed

Total elapsed time: 680.7 us

The package darknet:x64-windows provides CMake targets:

    find_package(Darknet CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Darknet::dark)
```
