### ISSUE TITLE
Error to build yolo v4

### ISSUE THREAD

**Issue by ramdhan1989** [AlexeyAB/darknet#5865]
I am so excited to try yolo v4. Currently, I used yolo v3 with nice result for my own dataset that built by using legacy way on windows. My question is, how to use yolo v4 ? do I need to download the repository again and rebuild from the scratch ? or I just can copy several files from the new repository and train as usual ? I have try to build yolov4 (legacy way) but it show the error as follow : 

> error : Designtime build failed for project 'D:\Ramdhan\darknet-master-v4\build\darknet\darknet.vcxproj' configuration 'Debug|Win32'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.

when set to x64 and release i got this error :

> error : Designtime build failed for project 'D:\Ramdhan\darknet-master-v4\build\darknet\darknet.vcxproj' configuration 'Release|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.

I didn't get this error when building yolo v3 previously.

please advice

thank you

**Comment by AlexeyAB** [comment]
Show full screen screenshot of this error.

**Comment by ramdhan1989** [comment]
when click darknet.sln it will opened by visual studio 2017 and show the error below

![image](https://user-images.githubusercontent.com/41245856/83947752-2bd6e400-a843-11ea-902a-f2fa6eacc70d.png)

**Comment by AlexeyAB** [comment]
Show full screen screenshot with output of x64&Release compilation

**Comment by ramdhan1989** [comment]
when open the darknet.sln the error shown is only that (previous screen shoot). does this help to analyze the problem ? 

![image](https://user-images.githubusercontent.com/41245856/83948003-bd932100-a844-11ea-809f-888b01a38850.png)

**Comment by AlexeyAB** [comment]
Show full screen screenshot, with top panel

**Comment by ramdhan1989** [comment]
![image](https://user-images.githubusercontent.com/41245856/83948197-e4058c00-a845-11ea-83c8-f5f24bef3d08.png)

when set to x64 and release--> build darknet show this error :
![image](https://user-images.githubusercontent.com/41245856/83948213-fc75a680-a845-11ea-9fb4-918a7f78a493.png)

**Comment by ramdhan1989** [comment]
I built successfuly by using vcpkg mentioned in #5860
