### ISSUE TITLE
Label of darknet predictions are just black boxes

### ISSUE THREAD

**Issue by sarmientoj24** [AlexeyAB/darknet#5868]
When I use darknet test, the labels for bounding boxes are only black boxes with no text.
![predictions](https://user-images.githubusercontent.com/8830319/83962025-e9a5b500-a8cb-11ea-85c4-893f5a7730e1.jpg)

**Comment by WongKinYiu** [comment]
Do you delete [this folder](https://github.com/AlexeyAB/darknet/tree/master/data/labels)?

**Comment by sarmientoj24** [comment]
I see,. to that was the issue. i removed the original data for my new dataset.
