### ISSUE TITLE
nan Avg (average loss) issue while training

### ISSUE THREAD

**Issue by pratesh** [AlexeyAB/darknet#588]
I am trying to train YoloV3 using PascalVOC dataset. 

I've followed the instructions in 
https://github.com/AlexeyAB/darknet#how-to-train-pascal-voc-data

But after certain iterations, the average loss is turning into **nan**
![image](https://user-images.githubusercontent.com/10672613/38420242-b729abd0-39c0-11e8-9611-c7bd545932ba.png)

Here is the loss chart:
![image](https://user-images.githubusercontent.com/10672613/38420258-c78b8e58-39c0-11e8-9981-1972594d6cbe.png)

Any reason for above behaviour or Anything that I am missing?

**Comment by AlexeyAB** [comment]
Did you set `Set batch=64 and subdivisions=8` in the file yolov3-voc.cfg?
And did you remove batch=1 subdivision=1?

**Comment by pratesh** [comment]
Thanks @AlexeyAB . This worked. 
Though basic, I suggest that these steps should be mentioned in the above instructions.

Also, could u please explain me the reason behind "nan avg" behaviour when `batch = 1` and `subdivision=1`.
