### ISSUE TITLE
make cause error with blas.c

### ISSUE THREAD

**Issue by Hyvenos** [AlexeyAB/darknet#5880]
I tried to install the latest version of darknet on Centos 8 using make.
I get the following error:

`/src/blas.c:524:5: erreur: ‘for’ loop initial declarations are only allowed in C99 mode`

This is probably due to **Added contrastive loss ** commits added 16 hours ago.
Doing the install when using cde72f8e0bc177439c32ce49740fd45ebc79859a (the previous commit) works.

**Comment by AlexeyAB** [comment]
I fixed it.

**Comment by imaami** [comment]
It might be useful to add `-std=gnu11` or at least `-std=gnu99` to the base C compiler flags in `CMakeLists.txt` and `Makefile` for Linux builds. Declaring loop variables inside the for parenthesis is convenient and C99 is 21 years old.
