### ISSUE TITLE
is these weights random generated or pretrained with COCO? yolov4.conv.137

### ISSUE THREAD

**Issue by samux87** [AlexeyAB/darknet#5885]
Hi guys,

I would just ask if these weights random generated or pretrained with COCO: yolov4.conv.137

Thank you.

**Comment by AlexeyAB** [comment]
yolov4.conv.137 - is the first 137 layers from yolov4.weight that is train on MS COCO dataset.

**Comment by samux87** [comment]
ok. So, if I would like to continue the training with just only the class person, do I need to keep the 80 classes in the *.data and *.cfg?

I would like to continue the training but just for a class (person)

**Comment by arnaud-nt2i** [comment]
@samux87 yolov4.conv.137 is meant to do transfer learning and avoiding non-converging training on custom dataset.

If you want to detect persons only, you can use an already fully trained model and weights on MS COCO and only display output if output is "person".
No need to built an entire data set and train a new model on it...

**Comment by samux87** [comment]
ok, thank you for the help.
