### ISSUE TITLE
EfficientNet-B7?

### ISSUE THREAD

**Issue by praneet195** [AlexeyAB/darknet#5896]
I wanted to know if there was any specific reason why EfficientNet-B3 instead of the larger EfficientNet-B4/B7 models?
Did it perform the best or was B3 the only model available at the time?

**Comment by AlexeyAB** [comment]
EfficientNets are very slow. So we trained only 
- EfficientNetB0 and MixNet-M-GPU classifiers
- and EfficientNetB0+Yolo detector `enet-coco.cfg (EfficientNetB0-Yolov3)`: https://github.com/AlexeyAB/darknet#pre-trained-models

We focus on real time systems. There are no calculators that quickly perform group convolutions. We hope they someday appear.

**Comment by Fetulhak** [comment]
> EfficientNets are very slow. So we trained only
> 
> * EfficientNetB0 and MixNet-M-GPU classifiers
> * and EfficientNetB0+Yolo detector `enet-coco.cfg (EfficientNetB0-Yolov3)`: https://github.com/AlexeyAB/darknet#pre-trained-models
> 
> We focus on real time systems. There are no calculators that quickly perform group convolutions. We hope they someday appear.

@AlexeyAB Hi Alexey why did not we use scale-x_y, resize, iou_los=ciou, cls_normalizer and iou_normalizer in enet-coco.cfg? is it becouse of their computation overload or they do not increase the performance that much?
