### ISSUE TITLE
Segmentation fault (core dumped) while traning 

### ISSUE THREAD

**Issue by eslambakr** [AlexeyAB/darknet#59]
Hi,

Currently I got problem when trying to train the darknet with data i collected for only two classes
1-i download the original darknet from here: https://pjreddie.com/darknet/yolo/
2-then i follow your 7 steps
3-then run the following command: ./darknet yolo train data/obj.data yolo-obj.cfg darknet19_448.conv.23
but I get : obj
Segmentation fault (core dumped)

can you help me ?
1)should i download your code ,this cause the error or what ?
2)i am new in this so i want to understand what i do definitely when i train this two classes using your pre-trained model ,is the last model I will get will be able to detect only my two classes or what ?
3)and what is the benefit of using the weights of pre-trained model?

**Comment by AlexeyAB** [comment]
@eslambakr Hi,

In my steps there is no:

> 3-then run the following command: ./darknet yolo train data/obj.data yolo-obj.cfg darknet19_448.conv.23

- this is command for old Yolo v1.

----

You should use steps only from my manual, not from others: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

> Start training by using the command line: `darknet.exe detector train data/obj.data yolo-obj.cfg darknet19_448.conv.23`

1. No
2. Yes
3. Faster training, and better accuracy

**Comment by eslambakr** [comment]
thanks a lot ,
i need to train and run all things on linux but your manual for windows.
so if i want to use your code and follow your manual but for linux not windows ,what should i do ?
again thanks a lot for your help i appreciate that

**Comment by AlexeyAB** [comment]
@eslambakr 

All the same, but on Linux you should use `./darknet` instead of `darknet.exe`
