### ISSUE TITLE
MSB3721 when building darknet

### ISSUE THREAD

**Issue by k00r** [AlexeyAB/darknet#591]
![darkneterror](https://user-images.githubusercontent.com/38154308/38453249-2070e3fc-3a5b-11e8-88b7-cc51ae2a82a5.JPG)

Hello,i receive this following error when building,i am using VS2015,OpenCV 3.4.0,CUDA 9.1,cuDNN 7.0
i am on a windows 7,x64 platform
how can i fix this issue?
Thank you.

**Comment by AlexeyAB** [comment]
Use `darknet.sln` and build x64 & Release

**Comment by k00r** [comment]
i am doing like that

**Comment by k00r** [comment]
the issue was fixed when i changed the build option from configuration manager instead of project properties
