### ISSUE TITLE
How to generate the libdarknet.so?

### ISSUE THREAD

**Issue by XP-CHRC** [AlexeyAB/darknet#592]
I want to generate a libdarknet.so like the pjreddie one does, how to do it?
Thank you very much!

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet#how-to-compile-on-linux

> `LIBSO=1` to build a library darknet.so and binary runable file uselib that uses this library. Or you can try to run so LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./uselib test.mp4 How to use this SO-library from your own code - you can look at C++ example: https://github.com/AlexeyAB/darknet/blob/master/src/yolo_console_dll.cpp

There will be `darknet.so` library, but it differs from the library of the original fork. 
I made this library for maximum performance on C++.

**Comment by XP-CHRC** [comment]
@AlexeyAB Thank you, i got it.

**Comment by XP-CHRC** [comment]
@AlexeyAB :
Hi, i wrote a function named Yolo_init() to load the .cfg and .weights files to the device under the /src, and i Make again while setting the LIBSO=1, however when i run :gcc -I ./src -L ./darknet.so main.c (the main() i used to check whether the Yolo_init works), error:
/tmp/cces8taP.o: In function `main':
main.c:(.text+0x24): undefined reference to `Yolo_init'
collect2: error: ld returned 1 exit status
and then i run: nm -D darknet.so to check whether there has Yolo_init under the darknet.so, and it's not.
so why this happened? or did i miss something?
thanks ahead.

**Comment by AlexeyAB** [comment]
Use
```cpp
#pragma once
#ifdef YOLODLL_EXPORTS
#if defined(_MSC_VER)
#define YOLODLL_API __declspec(dllexport) 
#else
#define YOLODLL_API __attribute__((visibility("default")))
#endif
#else
#if defined(_MSC_VER)
#define YOLODLL_API __declspec(dllimport) 
#else
#define YOLODLL_API
#endif
#endif



YOLODLL_API Yolo_init();
```

**Comment by XP-CHRC** [comment]
@AlexeyAB Thank you， thank you and thank you ! In china, the important thing will be said three times.

**Comment by XP-CHRC** [comment]
@AlexeyAB 
sorry for bothering you again, i wrote the function Init_YOLO() in the file named YO.c:
#include "YO.h"
#include "network.h"
#include "region_layer.h"
#include "cost_layer.h"
#include "utils.h"
#include "parser.h"
#include "box.h"
#include "demo.h"
#include "option_list.h"
YOLODLL_API int Init_YOLO(char* szCfg, char* szCfgfile char* szWeight){
    list *options = read_data_cfg(szCfg);
    char *name_list = option_find_str(options, "names", "data/names.list");
    char **names = get_labels(name_list);

    image **alphabet = load_alphabet();
    network net = parse_network_cfg_custom(szCfgfile, 1);
    if(szWeight){
        load_weights(&net, szWeight);
    }

}

and the YO.h:
#pragma once
#ifdef YOLODLL_EXPORTS
#if defined(_MSC_VER)
#define YOLODLL_API __declspec(dllexport) 
#else
#define YOLODLL_API __attribute__((visibility("default")))
#endif
#else
#if defined(_MSC_VER)
#define YOLODLL_API __declspec(dllimport) 
#else
#define YOLODLL_API
#endif
#endif

YOLODLL_API int Init_YOLO(char* szCfg, char* szCfgfile char* szWeight);

both YO.c and YO.h under the file src, i RUN make while setting LIBSO=1, and the darknet.so still don't include the function Init_YOLO, i am a newer, can you tell me why? thank you.

**Comment by AlexeyAB** [comment]
* Add here all your additional c/cpp-files that will be in SO-library: https://github.com/AlexeyAB/darknet/blob/0c95d8dfac7869ae4258f2080950cae6ea6a647e/Makefile#L102-L103

----

* Add here all your additional c/cpp-files that will be in your Application (that uses SO-library): https://github.com/AlexeyAB/darknet/blob/0c95d8dfac7869ae4258f2080950cae6ea6a647e/Makefile#L105-L106

**Comment by XP-CHRC** [comment]
@AlexeyAB 
Hi,AlexeyAB, there still something wrong when i run Make, and i wrote this:
$(LIBNAMESO): $(OBJS) src/yolo_v2_class.hpp src/yolo_v2_class.cpp src/YOLOAPI.c
	$(CPP) -shared -std=c++11 -fvisibility=hidden -DYOLODLL_EXPORTS $(COMMON) $(CFLAGS) $(OBJS) src/yolo_v2_class.cpp src/YOLOAPI.c -o $@ $(LDFLAGS)
	
$(APPNAMESO): $(LIBNAMESO) src/yolo_v2_class.hpp src/yolo_console_dll.cpp
	$(CPP) -std=c++11 $(COMMON) $(CFLAGS) -o $@ src/yolo_console_dll.cpp  $(LDFLAGS) -L ./ -l:$(LIBNAMESO)
endif

all the needed header files are included in the YOLOAPI.c,but the error:
.//darknet.so：对‘load_weights(network*, char*)’Undefined reference
.//darknet.so：对‘parse_network_cfg_custom(char*, int)’Undefined reference
.//darknet.so：对‘read_data_cfg(char*)’Undefined reference
.//darknet.so：对‘option_find_str(list*, char*, char*)’Undefined reference
collect2: error: ld returned 1 exit status
Makefile:112: recipe for target 'uselib' failed
make: *** [uselib] Error 1
Thanks ahead.

**Comment by AlexeyAB** [comment]
> .//darknet.so：对‘load_weights(network*, char*)’Undefined reference
> .//darknet.so：对‘parse_network_cfg_custom(char*, int)’Undefined reference
> .//darknet.so：对‘read_data_cfg(char*)’Undefined reference
> .//darknet.so：对‘option_find_str(list*, char*, char*)’Undefined reference

Find all these functions in the headers and add before each of these functions `__attribute__((visibility("default")))`

For example, change this line to this: https://github.com/AlexeyAB/darknet/blob/9f2dbfa7df981d41c070261c4b9a8a875b290203/src/parser.h#L11

```cpp
__attribute__((visibility("default"))) void load_weights(network *net, char *filename);
```

**Comment by XP-CHRC** [comment]
@AlexeyAB 
Thank your reply, and i try this, but still wrong: 
.//darknet.so: Undefined reference to ‘load_weights(network*, char*)’
.//darknet.so: Undefined reference to ‘parse_network_cfg_custom(char*, int)’
.//darknet.so: Undefined reference to ‘read_data_cfg(char*)’
.//darknet.so: Undefined reference to ‘option_find_str(list*, char*, char*)’
collect2: error: ld returned 1 exit status
Makefile:106: recipe for target 'uselib' failed  //error always happened in line 106 
make: *** [uselib] Error 1
Here are my Makefile:
ifeq ($(LIBSO), 1) 
CFLAGS+= -fPIC

$(LIBNAMESO): $(OBJS) src/yolo_v2_class.hpp src/yolo_v2_class.cpp src/YOLOAPI.h src/YOLOAPI.c
	$(CPP) -shared -std=c++11 -fvisibility=hidden -DYOLODLL_EXPORTS $(COMMON) $(CFLAGS) $(OBJS) src/yolo_v2_class.cpp src/YOLOAPI.c -o $@ $(LDFLAGS)
	
$(APPNAMESO): $(LIBNAMESO) src/yolo_v2_class.hpp src/yolo_console_dll.cpp
	$(CPP) -std=c++11 $(COMMON) $(CFLAGS) -o $@ src/yolo_console_dll.cpp  $(LDFLAGS) -L ./ -l:$(LIBNAMESO)
endif
Does it a compile error? the YOLOAPI.c compiled before the above four functions are compiled?
Thank you ahead.

**Comment by XP-CHRC** [comment]
I changed the  CFLAGS+= -fPIC to CFLAGS+= -shared -fPIC and then no error,but the function name in darknet.so like this:
00000000000c0e90 T _Z9Init_YOLOPcS_S_    
 //It's definition： YOLODLL_API int Init_YOLO(char* szCfg, char* szCfgfile char* szWeight)
also:
00000000000c1020 T _Z11DetectImage5image7networkP3boxPfPif
// It's defination: YOLODLL_API int DetectImage()
Dose something wrong?
Thank you!
