### ISSUE TITLE
using custom models

### ISSUE THREAD

**Issue by k00r** [AlexeyAB/darknet#593]
Hello,what is the command to use YOLO with custom object models and what files do i need besides .cfg and the .weights file?

**Comment by AlexeyAB** [comment]
Command `darknet.exe detector train data/obj.data yolo-obj.cfg yolo-obj_2000.weights`
Files data/obj.names, data/obj.data, yolo-obj.cfg, yolo-obj_2000.weights
https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

**Comment by k00r** [comment]
Hello @AlexeyAB i trained a model for 200 iterations but when i use it it doesn't detect any object.Can you help?

**Comment by AlexeyAB** [comment]
Train at least 2 000 iterations )
Also try to use flag `-thresh 0.02` for detection

**Comment by k00r** [comment]
what command should i use for detection? i renamed the file to test.mp4

**Comment by k00r** [comment]
i am getting detections with the 2000 iterations,thank you @AlexeyAB
