### ISSUE TITLE
How to load weight model once and test it on multiple image?

### ISSUE THREAD

**Issue by MindSightTH** [AlexeyAB/darknet#5930]
How to load weight model once and test it on multiple image?
I'm having a problem that I have to load weight model every time when I need to test an images.
Any idea on this? Any help would be appreciated.

**Comment by stephanecharette** [comment]
Are you doing this from within your application, or are you using the command-line?

Take a look DarkHelp, which I think does what you are asking.  The network is loaded once, and then you test all the images and videos you want:  https://www.ccoderun.ca/darkhelp/api/

The CLI part also has support for specifying [a file to read from](https://www.ccoderun.ca/darkhelp/api/Parameters.html), and within that file you can list all the images and videos you want it to use.  If you are scripting things, it also has a `--json` parameter to [output the results in JSON format](https://www.ccoderun.ca/darkhelp/api/ShellScripting.html).

**Comment by MindSightTH** [comment]
@MindSightTH I'm working on command-line and python script.

**Comment by MindSightTH** [comment]
@stephanecharette   First of all thank you for your reply.
I'm working on command-line and python script. I'm looking for a way to test an image from a condition that is stated within a python script not from a listed image file.  Example like just to test one more image from updated image file with the same exact weight model, my problem is that I had to load the weight all over again from a detector command that's kind of slowing down the process. 😥😥

**Comment by WongKinYiu** [comment]
for your reference
https://github.com/AlexeyAB/darknet/blob/master/darknet_video.py

**Comment by MindSightTH** [comment]
@WongKinYiu  Thank you! Now I've looked into darknet.py and implementation.

**Comment by yancccc** [comment]
Can you send me Python script？

**Comment by Sudhakar17** [comment]
@MindSightTH : Did you find the solution?

**Comment by MindSightTH** [comment]
@Sudhakar17  There's a python file `darknet.py` in darknet directory when you clone it.
