### ISSUE TITLE
Support for Cuda Toolkit 9.0 / 9.1

### ISSUE THREAD

**Issue by hfassold** [AlexeyAB/darknet#5936]
Currently the YoloV4 / Darknet library cannot be compiled with Cuda Toolkit 9.0 / 9.1, only with Cuda Toolkit 10.X

This is a problem, because on some Linux versions the default Cuda Toolkit version is 9.X

Would be great if this library could compile also with Cuda Toolkit 9.X

**Comment by AlexeyAB** [comment]
Each commit in this repo is successfully compiled: 
* on **CUDA 8.0** by using CirecleCI
* on CUDA 10.2 by using GitHub Actions and TravisCI
On Windows, Linux, MacOS
With GCC, MSVC++, Mingw
Using Make, Cmake, VCPKG, MSVS
....


![image](https://user-images.githubusercontent.com/4096485/84503085-33beda00-acc2-11ea-95e9-9e218110abf2.png)

![image](https://user-images.githubusercontent.com/4096485/84503141-4d602180-acc2-11ea-8663-95a12e4b0f77.png)

**Comment by AlexeyAB** [comment]
So Darknet can be compiled by using CUDA 8, CUDA 9 and CUDA 10
