### ISSUE TITLE
libdarknet.so did not generate

### ISSUE THREAD

**Issue by MindSightTH** [AlexeyAB/darknet#5943]
I've already set LIBSO = 1 in Makefile and recompile darknet with CMake./build.ps1.
But it did not generate libdarknet.so or libdark.os anywhere . 
Any thought on this ? Any help would appreciate.

CMakeList.txt 
![cmakelist](https://user-images.githubusercontent.com/34394901/84532873-385eaf00-ad11-11ea-8064-df4bcd5f32fb.png)

MakeFile
![Makefile1](https://user-images.githubusercontent.com/34394901/84533054-95f2fb80-ad11-11ea-9e80-1c8d26eefd71.png)
![Makefile2](https://user-images.githubusercontent.com/34394901/84533075-9d1a0980-ad11-11ea-92e7-f40c80f9f2c7.png)

./build.ps1
![build](https://user-images.githubusercontent.com/34394901/84533314-1a457e80-ad12-11ea-87d2-a5f1afff43e2.png)

**Comment by MindSightTH** [comment]
@cenit Any suggestion?

**Comment by cenit** [comment]
Look for dark.lib and dark.dll
The makefile is completely unnecessary for you and totally not used under Windows.

**Comment by MindSightTH** [comment]
@cenit  Thank you for reply. 
Those two files are already in the /darknet-master folder.

**Comment by cenit** [comment]
So you have it!
libdark.so is the Linux name of dark.dll/lib in Windows. You have windows, so no way you can have libdark.so :)

**Comment by MindSightTH** [comment]
@cenit  Wow, I felt dumb right now I've been searching a way to get libdark.so from recompiling darknet and reinstall everything all day to get darknet.py for linux to work on windows. 
By the way I'm really appreciate your help.
You lighten up my day, bless you.

**Comment by cenit** [comment]
Don’t worry. Glad you are now ready to do your research. Please close fixed issue and reply whenever necessary saying that you fixed your problems :)
