### ISSUE TITLE
Training with darknet53/darknet19 classifier, the batch output show strange

### ISSUE THREAD

**Issue by xjohnxjohn** [AlexeyAB/darknet#5950]
Hi AlexeyAB, I train my custom datasets with darknet53. I use command:
./darknet classifier train obj.data darknet53.cfg
The batch output show:-
74, 0.028: 0.712751, 0.704461 avg, 0.000000 rate, 6.408722 seconds, 8880 images, 123.957207 hours left
Loaded: 0.000023 seconds
 total_bbox = 0, rewritten_bbox = -nan % 
 total_bbox = 0, rewritten_bbox = -nan % 
 total_bbox = 0, rewritten_bbox = -nan % 
 total_bbox = 0, rewritten_bbox = -nan % 
 total_bbox = 0, rewritten_bbox = -nan % 
 total_bbox = 0, rewritten_bbox = -nan % 
 total_bbox = 0, rewritten_bbox = -nan % 
 total_bbox = 0, rewritten_bbox = -nan % 
 total_bbox = 0, rewritten_bbox = -nan % 
 total_bbox = 0, rewritten_bbox = -nan % 

I use the lastest repo.
( If I use the old repo commit:b56e8d11cfa4278ad5258eedb5207ae583d16e96, it train perfect. The batch output:-
Loaded: 0.000032 seconds
Syncing... Done!
4921, 1.870: 0.679301, 0.681132 avg, 0.000409 rate, 13.983938 seconds, 590520 images
Loaded: 0.000032 seconds
4922, 1.870: 0.682513, 0.681270 avg, 0.000409 rate, 13.116252 seconds, 590640 images
Loaded: 0.000029 seconds
Syncing... Done!
)

What i doing wrong?

**Comment by WongKinYiu** [comment]
This in formation is for detector training, you can just ignore it.
or temporally comment https://github.com/AlexeyAB/darknet/blob/master/src/network.c#L372 and https://github.com/AlexeyAB/darknet/blob/master/src/network_kernels.cu#L351 and re-build your darknet.

**Comment by xjohnxjohn** [comment]
@WongKinYiu thank you. The batch output "74, 0.028: 0.712751, 0.704461 avg, 0.000000 rate, 6.408722 seconds, 8880 images, 123.957207 hours left" show the rate to 0. This is ok!

**Comment by AlexeyAB** [comment]
This is normal for the first 1000 iterations
