### ISSUE TITLE
Darknet isn't detecting OpenCV.

### ISSUE THREAD

**Issue by jalayrupera** [AlexeyAB/darknet#5956]
If something doesn’t work for you, then show 2 screenshots:
1. I changed OPENCV=1 in Makefile. It is showing error like OPENCV isn't used and I am using windows.

![isssue](https://user-images.githubusercontent.com/33190512/84585227-338e1e00-ae2b-11ea-9fcb-976adb654980.png)

2. screenshots with such information
![2](https://user-images.githubusercontent.com/33190512/84585284-e199c800-ae2b-11ea-95fb-1381395713a3.png)

**Comment by newjoy2018** [comment]
I met the same problem. Waiting for answers!

**Comment by Hu-nie** [comment]
So am I. I wonder how to solve it.

**Comment by shubhambaid** [comment]
I see you're using windows here, if i'm not wrong
Did you try building OpenCV from source ?

**Comment by dsbyprateekg** [comment]
@newjoy2018 @Hu-nie @jalayrupera I used the vcpkg to install and build the darknet-
https://github.com/AlexeyAB/darknet#how-to-compile-on-windows-using-vcpkg

Although the above step will take a longer time as compare to CMake yet it's working in windows as expected.
