### ISSUE TITLE
Can I train darknet for pose estimation?

### ISSUE THREAD

**Issue by physxP** [AlexeyAB/darknet#5968]
Hello!

I am currently using yolov3 with darknet frame work in my c project. I want to detect and track hands corresponding to each detected person separately. I figured the best way to do this is via pose estimation and to accomplish this I must modify my current network or use a new network on pose detection in darknet framework. As I am too far in the project I would like to know if it possible to do pose estimation in darknet and if so can I please get some example or pointers? If you already have pretrained network it will completely solve my problem. I have looked through the wiki but I am still not sure if I can use yolov3 in darknet for pose estimation.

**Comment by WongKinYiu** [comment]
https://github.com/AlexeyAB/darknet/issues/5651
for your reference.

**Comment by physxP** [comment]
> 
> 
> #5651
> for your reference.
Thanks! That looks like a good reference to solve my problem.
