### ISSUE TITLE
Detected bounding boxes in video lag behind by one frame

### ISSUE THREAD

**Issue by yonie1** [AlexeyAB/darknet#5975]
It appears like the detection boxes lag behind by a single frame if i run this command with my custom detector on a low fps(2fps) video.

`./darknet detector demobee.datayolo4-bee.cfgyolo4-bee.weights -dont_show in.mp4 -out_filename out.avi`

I uploaded my result here

https://youtu.be/4BKA5bm_G30

the command was run in Google Colab
The detector works fine on images(tested with frames of this video)

**Comment by WongKinYiu** [comment]
https://github.com/AlexeyAB/darknet/issues/3970

**Comment by yonie1** [comment]
my solution was to add -avgframes 1 #3970 is outdated
