### ISSUE TITLE
Newbie having difficulty installing

### ISSUE THREAD

**Issue by LeeroyHannigan** [AlexeyAB/darknet#598]
Hi guys, 
Im trying to install darknet on windows 10 with the latest version of VS2017. I have a darkflow version of Yolo running on my machine but I am eager to try out Yolo v3. When I clone the repo, darknet.sln does not open in visual studio? Any help would be much appreciated.

Lee

**Comment by fmgracias** [comment]
Not an expert but you have to set "Platform Toolset" to _Visual Studio 2015 (v140)_ (right click project -> Properties -> Configuration Properties -> General).

Then make sure you configured the project properly (Library Directories and the necessary Include Directories) according to https://github.com/AlexeyAB/darknet#

Good luck ;)

**Comment by LeeroyHannigan** [comment]
Hi, thanks for your quick reply. I changed the platform toolset. 
Got the following warning
error : Designtime build failed for project 'C:\Users\leero\Desktop\Darknet\darknet\build\darknet\darknet.vcxproj' configuration 'Debug|Win32'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.

**Comment by fmgracias** [comment]
You need to run it on Release configuration and x64 platform. 

Check if it fixed that issue

**Comment by LeeroyHannigan** [comment]
Still with the same error unfortunately 

error : Designtime build failed for project 'C:\Users\leero\Desktop\Darknet\darknet\build\darknet\darknet.vcxproj' configuration 'Release|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.

**Comment by fmgracias** [comment]
I'm not familiar with that specific error and I've always been able to open dakrnet.sln on VS2017 Community (with v140 toolset).

I guess @AlexeyAB might be able to help you.

**Comment by LeeroyHannigan** [comment]
This is the error I receive when i try to build, 
1>------ Build started: Project: darknet, Configuration: Release x64 ------
1>C:\Users\leero\Desktop\Darknet\darknet\build\darknet\darknet.vcxproj(55,5): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\BuildCustomizations\CUDA 9.1.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
1>Done building project "darknet.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by LeeroyHannigan** [comment]
I eventually got it working, thanks for your help @fmgracias I think if i hadnt have gotten over that hurdle id have given up.
Lee

**Comment by mdbrannock** [comment]
@LeeroyHannigan I'm getting the exact errors in VS2017 as you were describing a couple weeks ago. How did you end up getting it working?

**Comment by mdbrannock** [comment]
I have VS2017, but I included the v140 toolset. Should I forgo 2017 entirely and just find the 2015 version?

**Comment by LeeroyHannigan** [comment]
No if you have the v140 then should be no problem. Have you configured to Release and X64?

**Comment by LeeroyHannigan** [comment]
Also which version of Cuda have you installed?

**Comment by mdbrannock** [comment]
I did configure to Release and X64 and have Cuda 9.1. If getting the v140 toolset fixed the problem for you then I might just try to reinstall VS from scratch and give it another go.

**Comment by LeeroyHannigan** [comment]
Your CUDA path set up correctly?
I didn't have V140 installed, I installed that and set the correct path for CUDA and it worked.
What error are you getting?

**Comment by mdbrannock** [comment]
By correct path for CUDA do you mean the environment variable here?

![image](https://user-images.githubusercontent.com/19409449/39097619-bda02534-462c-11e8-97a5-3e4eb9442987.png)

I _think_ it's right, but I suppose I'm not sure. Does that file path look similar to the one you used?

**Comment by LeeroyHannigan** [comment]
That looks good to me! What errors are you receiving?

**Comment by LeeroyHannigan** [comment]
When you opened the solution if VS were you sure not to update to v141?

**Comment by mdbrannock** [comment]
Here's the error. 

![image](https://user-images.githubusercontent.com/19409449/39098158-93b2033e-4634-11e8-949d-80cfdacb26be.png)

I see the CUDA 9.1.props file they are talking about, but it's not in the folder they are looking for it in. I could copy it over, but that doesn't seem like the right thing to do. It seems clear it doesn't know where to look for it, but I'm not sure how to fix that.

Yes, I was sure not to update, even though it seems to really want me to..

**Comment by LeeroyHannigan** [comment]
In the vcxproj file, does the import cuda match your file path that you have in environmental variable?

**Comment by mdbrannock** [comment]
Here's the line in the vcsproj file that is giving me trouble (line 55):

    <Import Project="$(VCTargetsPath)\BuildCustomizations\CUDA 9.1.props" />

I'm not sure where the TCTargetsPath variable is set. It seems like if that line is meant to import CUDA then it should call the CUDA_PATH variable. I suppose I could hard code in the CUDA path, but I guess I'm confused as to why I'm having this problem when no one else seems to be.

Thanks for you help, by the way. I'm very new to this and about ready to give up.

**Comment by mdbrannock** [comment]
Well, I hardcoded the path there and in one other place that referenced CUDA and the project built successfully! We'll see if it works as expected, but that's progress at least. Thanks again.

**Comment by LeeroyHannigan** [comment]
Nice one!! Keep me posted. I was about to give up too just before it worked.

**Comment by mdbrannock** [comment]
Well, there seems to be another path issue when I try to actually execute a .cmd

![image](https://user-images.githubusercontent.com/19409449/39100913-e2ecb89c-465f-11e8-938a-a10f050583d4.png)

Not sure when I'll get back to this, but if I figure out what's happening then I'll let you know.

**Comment by AlexeyAB** [comment]
Just try to copy this dll-file to the directory with `darknet.exe`

Or add path to this `opencv_world340.dll` in the system variables in the Windows:
![add_to_path_thumb](https://user-images.githubusercontent.com/4096485/39101948-3d10e5c6-46a8-11e8-84c2-4b1018bd9666.png)

**Comment by mdbrannock** [comment]
Thanks, @AlexeyAB! It looks like I gave up just a few minutes early. Copying `opencv_world340.dll` over resolved the problem and I was able to get everything working. Thanks again!
