### ISSUE TITLE
max parameter in yolo layer

### ISSUE THREAD

**Issue by JustMyselfff** [AlexeyAB/darknet#5983]
Can someone explain to me what the parameter max here means :

for training with a large number of objects in each image, add the parameter max=200 or higher value in the last [yolo]-layer or [region]-layer in your cfg-file (the global maximum number of objects that can be detected by YoloV3 is 0,0615234375*(width*height) where are width and height are parameters from [net] section in cfg-file)

I know that i should use it if i have a lot of objects in an image but setting max more than 200 is based on what? The amount of bounding boxes (annotations) for an image?

**Comment by AlexeyAB** [comment]
On some datasets in early versions of Yolo, it was desirable to limit the number of ground truth in a single image. 
But at the moment it seems there are no restrictions, now max = 200 by default, but you can put it max = 1000
