### ISSUE TITLE
yolov3 training on yolov4 repo 

### ISSUE THREAD

**Issue by hadikoub** [AlexeyAB/darknet#5985]
I have a question if I can train a yolov3 custom model using yolov3 cfg on the yolov4 repo. or if the result I will get are different than those I normally get from the yolo v3 repo for the same dataset and cfg.

**Comment by vnt1537** [comment]
I tried and the results are similar but as they have made some changes in the activation layer therefore we get some warning but it still works

**Comment by AlexeyAB** [comment]
Train with `[net] letter_box=1` in cfg-file, and detect with flag `-letter_box` and results should be the same in both repositories.
