### ISSUE TITLE
How to run detection directly in Python IDE 

### ISSUE THREAD

**Issue by WenTheProgrammer** [AlexeyAB/darknet#5989]
Hi, this question must be simple for many since I'm new to Python. I use Spyder on Windows 10. YOLOv4 detector is working perfectly for me on Windows, and I have successfully trained my own weights by following the tutorial. Currently I'm trying to automate the final detection process (open Command Prompt, change directory to darknet folder, type in detection command line, wait till detector goes through all images, close Command Prompt) by writing a Python script that can do the job. First I thought about passing the command line to a Command Prompt using Python. It turned out somehow I couldn't even open a Command Prompt with os.system or subprocess.Popen in Spyder, while they seemed to be working fine in Anaconda Prompt. I eventually managed to open a Command Prompt through subprocess.call('start',shell=True), but I wasn't able to communicate with it using Spyder. Then I thought about translate the command line used in Command Prompt into something Python can understand and directly run that in Spyder, and I couldn't get that figured out.

So in simple words I need a Python script that can give me the same detection results as if I typed something like
"darknet.exe detector test cfg/coco.data cfg/yolov4.cfg yolov4.weights -thresh 0.25 -dont_show -save_labels < data/new_train.txt"
in Command Prompt.

Hope my description is clear. Any help is greatly appreciated!

**Comment by hadikoub** [comment]
have you tried to use this method in **subprocess** 
```

import subprocess      
command: list = ["darknet.exe", "detector", "test" , "cfg/coco.data", "cfg/yolov4.cfg", "yolov4.weights","-thresh 0.25", " -dont_show ","- save_labels" , "<" ,"data/new_train.txt" ]
process: subprocess.Popen = subprocess.Popen(
            command, stdout=subprocess.STDOUT, stderr=subprocess.STDOUT
        )

```
if you wish to save the output in another way you can use  logger library and pipe the output of the subprocess to a log file  
```
import logging
from logging.handlers import RotatingFileHandler
import subprocess      

command: list = ["darknet.exe", "detector", "test" , "cfg/coco.data", "cfg/yolov4.cfg", "yolov4.weights","-thresh 0.25", " -dont_show ","- save_labels" ]

process: subprocess.Popen = subprocess.Popen(
            command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT
        )
yolo_training_logger: logging.Logger = logging.getLogger("Rotating Log")
yolo_training_logger.setLevel(logging.INFO)

# Add a rotating handler for yolo training output
log_path = "data/newtrain.log"
yolo_handler: RotatingFileHandler = RotatingFileHandler(
            yolo_log_path, maxBytes=51200, backupCount=1
        )

yolo_training_logger.addHandler(yolo_handler) 

 while True:
            line: bytes = process.stdout.readline()
            if not line:
                break
            line_decoded: str = line.decode("utf-8")
            yolo_training_logger.info(line_decoded)
```

**Comment by WenTheProgrammer** [comment]
@hadikoub Thank you very much for your help! I tried your method and got the following error:

![Error](https://user-images.githubusercontent.com/67032259/84942774-5af61c80-b0b1-11ea-9dca-8b8ddd4bfe64.png)

**Comment by hadikoub** [comment]
Please try to change the stdout to
stdout=subprocess.PIPE

But in this case u need to capture the output of the command and print it like:

```
import subprocess      
command: list = ["darknet.exe", "detector", "test" , "cfg/coco.data", "cfg/yolov4.cfg", "yolov4.weights","-thresh 0.25", " -dont_show ","- save_labels" , "<" ,"data/new_train.txt" ]
process: subprocess.Popen = subprocess.Popen(
            command, stdout=subprocess.STDOUT, stderr=subprocess.STDOUT
        )
stdout,stderr = process.communicate()
print(stdout)


```

**Comment by WenTheProgrammer** [comment]
@hadikoub I got another error:

![Untitled](https://user-images.githubusercontent.com/67032259/84947135-b62b0d80-b0b7-11ea-86ee-c05e0c77fb8e.png)

**Comment by hadikoub** [comment]
The issue here is that u are refering to darknet.exe and other file like cfg and weight file as relative path from the anaconda environment which is in another folder so at the runtime it won't find the file. What you should do is to take to absolute path of each argument of this command like
`C:\<path to darknet folder>\darknet\darknet.exe detector test C:\<path to darknet folder>\darknet\data\obj.data ...... Etc. `

Make sure to insert each argument as a element of the command list I wrote that just for example to show you how you should reference the path of each element

**Comment by WenTheProgrammer** [comment]
@hadikoub OK now I am able to run the code without any errors. I just put the script in the same folder as darknet.exe. However it still doesn't work properly.
Here is my code which is identical to yours except for the command:
`import subprocess`
`command: list = ["darknet.exe", "detector", "test", "data/obj.data", "yolo-obj.cfg", "yolo-obj_best.weights", "-thresh", "0.25", "-dont_show", "-save_labels", "<", "testimage/test.txt"]`
`process: subprocess.Popen = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)`
`stdout,stderr = process.communicate()`
`print(stdout)`
Here is the output in Spyder:
`b' CUDA-version: 10020 (10020), cuDNN: 7.6.5, CUDNN_HALF=1, GPU count: 1  \r\n CUDNN_HALF=1 \r\n OpenCV version: 4.1.0\r\n 0 : compute_capability = 750, cudnn_half = 1, GPU: GeForce RTX 2060 \r\n   layer   filters  size/strd(dil)      input                output\r\n   0 conv     32       3 x 3/ 1    352 x 352 x   3 ->  352 x 352 x  32 0.214 BF\r\n   1 conv     64       3 x 3/ 2    352 x 352 x  32 ->  176 x 176 x  64 1.142 BF\r\n   2 conv     64       1 x 1/ 1    176 x 176 x  64 ->  176 x 176 x  64 0.254 BF\r\n   3 route  1 \t\t                           ->  176 x 176 x  64 \r\n   4 conv     64       1 x 1/ 1    176 x 176 x  64 ->  176 x 176 x  64 0.254 BF\r\n   5 conv     32       1 x 1/ 1    176 x 176 x  64 ->  176 x 176 x  32 0.127 BF\r\n   6 conv     64       3 x 3/ 1    176 x 176 x  32 ->  176 x 176 x  64 1.142 BF\r\n   7 Shortcut Layer: 4,  wt = 0, wn = 0, outputs: 176 x 176 x  64 0.002 BF\r\n   8 conv     64       1 x 1/ 1    176 x 176 x  64 ->  176 x 176 x  64 0.254 BF\r\n   9 route  8 2 \t                           ->  176 x 176 x 128 \r\n  10 conv     64       1 x 1/ 1    176 x 176 x 128 ->  176 x 176 x  64 0.508 BF\r\n  11 conv    128       3 x 3/ 2    176 x 176 x  64 ->   88 x  88 x 128 1.142 BF\r\n  12 conv     64       1 x 1/ 1     88 x  88 x 128 ->   88 x  88 x  64 0.127 BF\r\n  13 route  11 \t\t                           ->   88 x  88 x 128 \r\n  14 conv     64       1 x 1/ 1     88 x  88 x 128 ->   88 x  88 x  64 0.127 BF\r\n  15 conv     64       1 x 1/ 1     88 x  88 x  64 ->   88 x  88 x  64 0.063 BF\r\n  16 conv     64       3 x 3/ 1     88 x  88 x  64 ->   88 x  88 x  64 0.571 BF\r\n  17 Shortcut Layer: 14,  wt = 0, wn = 0, outputs:  88 x  88 x  64 0.000 BF\r\n  18 conv     64       1 x 1/ 1     88 x  88 x  64 ->   88 x  88 x  64 0.063 BF\r\n  19 conv     64       3 x 3/ 1     88 x  88 x  64 ->   88 x  88 x  64 0.571 BF\r\n  20 Shortcut Layer: 17,  wt = 0, wn = 0, outputs:  88 x  88 x  64 0.000 BF\r\n  21 conv     64       1 x 1/ 1     88 x  88 x  64 ->   88 x  88 x  64 0.063 BF\r\n  22 route  21 12 \t                           ->   88 x  88 x 128 \r\n  23 conv    128       1 x 1/ 1     88 x  88 x 128 ->   88 x  88 x 128 0.254 BF\r\n  24 conv    256       3 x 3/ 2     88 x  88 x 128 ->   44 x  44 x 256 1.142 BF\r\n  25 conv    128       1 x 1/ 1     44 x  44 x 256 ->   44 x  44 x 128 0.127 BF\r\n  26 route  24 \t\t                           ->   44 x  44 x 256 \r\n  27 conv    128       1 x 1/ 1     44 x  44 x 256 ->   44 x  44 x 128 0.127 BF\r\n  28 conv    128       1 x 1/ 1     44 x  44 x 128 ->   44 x  44 x 128 0.063 BF\r\n  29 conv    128       3 x 3/ 1     44 x  44 x 128 ->   44 x  44 x 128 0.571 BF\r\n  30 Shortcut Layer: 27,  wt = 0, wn = 0, outputs:  44 x  44 x 128 0.000 BF\r\n  31 conv    128       1 x 1/ 1     44 x  44 x 128 ->   44 x  44 x 128 0.063 BF\r\n  32 conv    128       3 x 3/ 1     44 x  44 x 128 ->   44 x  44 x 128 0.571 BF\r\n  33 Shortcut Layer: 30,  wt = 0, wn = 0, outputs:  44 x  44 x 128 0.000 BF\r\n  34 conv    128       1 x 1/ 1     44 x  44 x 128 ->   44 x  44 x 128 0.063 BF\r\n  35 conv    128       3 x 3/ 1     44 x  44 x 128 ->   44 x  44 x 128 0.571 BF\r\n  36 Shortcut Layer: 33,  wt = 0, wn = 0, outputs:  44 x  44 x 128 0.000 BF\r\n  37 conv    128       1 x 1/ 1     44 x  44 x 128 ->   44 x  44 x 128 0.063 BF\r\n  38 conv    128       3 x 3/ 1     44 x  44 x 128 ->   44 x  44 x 128 0.571 BF\r\n  39 Shortcut Layer: 36,  wt = 0, wn = 0, outputs:  44 x  44 x 128 0.000 BF\r\n  40 conv    128       1 x 1/ 1     44 x  44 x 128 ->   44 x  44 x 128 0.063 BF\r\n  41 conv    128       3 x 3/ 1     44 x  44 x 128 ->   44 x  44 x 128 0.571 BF\r\n  42 Shortcut Layer: 39,  wt = 0, wn = 0, outputs:  44 x  44 x 128 0.000 BF\r\n  43 conv    128       1 x 1/ 1     44 x  44 x 128 ->   44 x  44 x 128 0.063 BF\r\n  44 conv    128       3 x 3/ 1     44 x  44 x 128 ->   44 x  44 x 128 0.571 BF\r\n  45 Shortcut Layer: 42,  wt = 0, wn = 0, outputs:  44 x  44 x 128 0.000 BF\r\n  46 conv    128       1 x 1/ 1     44 x  44 x 128 ->   44 x  44 x 128 0.063 BF\r\n  47 conv    128       3 x 3/ 1     44 x  44 x 128 ->   44 x  44 x 128 0.571 BF\r\n  48 Shortcut Layer: 45,  wt = 0, wn = 0, outputs:  44 x  44 x 128 0.000 BF\r\n  49 conv    128       1 x 1/ 1     44 x  44 x 128 ->   44 x  44 x 128 0.063 BF\r\n  50 conv    128       3 x 3/ 1     44 x  44 x 128 ->   44 x  44 x 128 0.571 BF\r\n  51 Shortcut Layer: 48,  wt = 0, wn = 0, outputs:  44 x  44 x 128 0.000 BF\r\n  52 conv    128       1 x 1/ 1     44 x  44 x 128 ->   44 x  44 x 128 0.063 BF\r\n  53 route  52 25 \t                           ->   44 x  44 x 256 \r\n  54 conv    256       1 x 1/ 1     44 x  44 x 256 ->   44 x  44 x 256 0.254 BF\r\n  55 conv    512       3 x 3/ 2     44 x  44 x 256 ->   22 x  22 x 512 1.142 BF\r\n  56 conv    256       1 x 1/ 1     22 x  22 x 512 ->   22 x  22 x 256 0.127 BF\r\n  57 route  55 \t\t                           ->   22 x  22 x 512 \r\n  58 conv    256       1 x 1/ 1     22 x  22 x 512 ->   22 x  22 x 256 0.127 BF\r\n  59 conv    256       1 x 1/ 1     22 x  22 x 256 ->   22 x  22 x 256 0.063 BF\r\n  60 conv    256       3 x 3/ 1     22 x  22 x 256 ->   22 x  22 x 256 0.571 BF\r\n  61 Shortcut Layer: 58,  wt = 0, wn = 0, outputs:  22 x  22 x 256 0.000 BF\r\n  62 conv    256       1 x 1/ 1     22 x  22 x 256 ->   22 x  22 x 256 0.063 BF\r\n  63 conv    256       3 x 3/ 1     22 x  22 x 256 ->   22 x  22 x 256 0.571 BF\r\n  64 Shortcut Layer: 61,  wt = 0, wn = 0, outputs:  22 x  22 x 256 0.000 BF\r\n  65 conv    256       1 x 1/ 1     22 x  22 x 256 ->   22 x  22 x 256 0.063 BF\r\n  66 conv    256       3 x 3/ 1     22 x  22 x 256 ->   22 x  22 x 256 0.571 BF\r\n  67 Shortcut Layer: 64,  wt = 0, wn = 0, outputs:  22 x  22 x 256 0.000 BF\r\n  68 conv    256       1 x 1/ 1     22 x  22 x 256 ->   22 x  22 x 256 0.063 BF\r\n  69 conv    256       3 x 3/ 1     22 x  22 x 256 ->   22 x  22 x 256 0.571 BF\r\n  70 Shortcut Layer: 67,  wt = 0, wn = 0, outputs:  22 x  22 x 256 0.000 BF\r\n  71 conv    256       1 x 1/ 1     22 x  22 x 256 ->   22 x  22 x 256 0.063 BF\r\n  72 conv    256       3 x 3/ 1     22 x  22 x 256 ->   22 x  22 x 256 0.571 BF\r\n  73 Shortcut Layer: 70,  wt = 0, wn = 0, outputs:  22 x  22 x 256 0.000 BF\r\n  74 conv    256       1 x 1/ 1     22 x  22 x 256 ->   22 x  22 x 256 0.063 BF\r\n  75 conv    256       3 x 3/ 1     22 x  22 x 256 ->   22 x  22 x 256 0.571 BF\r\n  76 Shortcut Layer: 73,  wt = 0, wn = 0, outputs:  22 x  22 x 256 0.000 BF\r\n  77 conv    256       1 x 1/ 1     22 x  22 x 256 ->   22 x  22 x 256 0.063 BF\r\n  78 conv    256       3 x 3/ 1     22 x  22 x 256 ->   22 x  22 x 256 0.571 BF\r\n  79 Shortcut Layer: 76,  wt = 0, wn = 0, outputs:  22 x  22 x 256 0.000 BF\r\n  80 conv    256       1 x 1/ 1     22 x  22 x 256 ->   22 x  22 x 256 0.063 BF\r\n  81 conv    256       3 x 3/ 1     22 x  22 x 256 ->   22 x  22 x 256 0.571 BF\r\n  82 Shortcut Layer: 79,  wt = 0, wn = 0, outputs:  22 x  22 x 256 0.000 BF\r\n  83 conv    256       1 x 1/ 1     22 x  22 x 256 ->   22 x  22 x 256 0.063 BF\r\n  84 route  83 56 \t                           ->   22 x  22 x 512 \r\n  85 conv    512       1 x 1/ 1     22 x  22 x 512 ->   22 x  22 x 512 0.254 BF\r\n  86 conv   1024       3 x 3/ 2     22 x  22 x 512 ->   11 x  11 x1024 1.142 BF\r\n  87 conv    512       1 x 1/ 1     11 x  11 x1024 ->   11 x  11 x 512 0.127 BF\r\n  88 route  86 \t\t                           ->   11 x  11 x1024 \r\n  89 conv    512       1 x 1/ 1     11 x  11 x1024 ->   11 x  11 x 512 0.127 BF\r\n  90 conv    512       1 x 1/ 1     11 x  11 x 512 ->   11 x  11 x 512 0.063 BF\r\n  91 conv    512       3 x 3/ 1     11 x  11 x 512 ->   11 x  11 x 512 0.571 BF\r\n  92 Shortcut Layer: 89,  wt = 0, wn = 0, outputs:  11 x  11 x 512 0.000 BF\r\n  93 conv    512       1 x 1/ 1     11 x  11 x 512 ->   11 x  11 x 512 0.063 BF\r\n  94 conv    512       3 x 3/ 1     11 x  11 x 512 ->   11 x  11 x 512 0.571 BF\r\n  95 Shortcut Layer: 92,  wt = 0, wn = 0, outputs:  11 x  11 x 512 0.000 BF\r\n  96 conv    512       1 x 1/ 1     11 x  11 x 512 ->   11 x  11 x 512 0.063 BF\r\n  97 conv    512       3 x 3/ 1     11 x  11 x 512 ->   11 x  11 x 512 0.571 BF\r\n  98 Shortcut Layer: 95,  wt = 0, wn = 0, outputs:  11 x  11 x 512 0.000 BF\r\n  99 conv    512       1 x 1/ 1     11 x  11 x 512 ->   11 x  11 x 512 0.063 BF\r\n 100 conv    512       3 x 3/ 1     11 x  11 x 512 ->   11 x  11 x 512 0.571 BF\r\n 101 Shortcut Layer: 98,  wt = 0, wn = 0, outputs:  11 x  11 x 512 0.000 BF\r\n 102 conv    512       1 x 1/ 1     11 x  11 x 512 ->   11 x  11 x 512 0.063 BF\r\n 103 route  102 87 \t                           ->   11 x  11 x1024 \r\n 104 conv   1024       1 x 1/ 1     11 x  11 x1024 ->   11 x  11 x1024 0.254 BF\r\n 105 conv    512       1 x 1/ 1     11 x  11 x1024 ->   11 x  11 x 512 0.127 BF\r\n 106 conv   1024       3 x 3/ 1     11 x  11 x 512 ->   11 x  11 x1024 1.142 BF\r\n 107 conv    512       1 x 1/ 1     11 x  11 x1024 ->   11 x  11 x 512 0.127 BF\r\n 108 max                5x 5/ 1     11 x  11 x 512 ->   11 x  11 x 512 0.002 BF\r\n 109 route  107 \t\t                           ->   11 x  11 x 512 \r\n 110 max                9x 9/ 1     11 x  11 x 512 ->   11 x  11 x 512 0.005 BF\r\n 111 route  107 \t\t                           ->   11 x  11 x 512 \r\n 112 max               13x13/ 1     11 x  11 x 512 ->   11 x  11 x 512 0.010 BF\r\n 113 route  112 110 108 107 \t                   ->   11 x  11 x2048 \r\n 114 conv    512       1 x 1/ 1     11 x  11 x2048 ->   11 x  11 x 512 0.254 BF\r\n 115 conv   1024       3 x 3/ 1     11 x  11 x 512 ->   11 x  11 x1024 1.142 BF\r\n 116 conv    512       1 x 1/ 1     11 x  11 x1024 ->   11 x  11 x 512 0.127 BF\r\n 117 conv    256       1 x 1/ 1     11 x  11 x 512 ->   11 x  11 x 256 0.032 BF\r\n 118 upsample                 2x    11 x  11 x 256 ->   22 x  22 x 256\r\n 119 route  85 \t\t                           ->   22 x  22 x 512 \r\n 120 conv    256       1 x 1/ 1     22 x  22 x 512 ->   22 x  22 x 256 0.127 BF\r\n 121 route  120 118 \t                           ->   22 x  22 x 512 \r\n 122 conv    256       1 x 1/ 1     22 x  22 x 512 ->   22 x  22 x 256 0.127 BF\r\n 123 conv    512       3 x 3/ 1     22 x  22 x 256 ->   22 x  22 x 512 1.142 BF\r\n 124 conv    256       1 x 1/ 1     22 x  22 x 512 ->   22 x  22 x 256 0.127 BF\r\n 125 conv    512       3 x 3/ 1     22 x  22 x 256 ->   22 x  22 x 512 1.142 BF\r\n 126 conv    256       1 x 1/ 1     22 x  22 x 512 ->   22 x  22 x 256 0.127 BF\r\n 127 conv    128       1 x 1/ 1     22 x  22 x 256 ->   22 x  22 x 128 0.032 BF\r\n 128 upsample                 2x    22 x  22 x 128 ->   44 x  44 x 128\r\n 129 route  54 \t\t                           ->   44 x  44 x 256 \r\n 130 conv    128       1 x 1/ 1     44 x  44 x 256 ->   44 x  44 x 128 0.127 BF\r\n 131 route  130 128 \t                           ->   44 x  44 x 256 \r\n 132 conv    128       1 x 1/ 1     44 x  44 x 256 ->   44 x  44 x 128 0.127 BF\r\n 133 conv    256       3 x 3/ 1     44 x  44 x 128 ->   44 x  44 x 256 1.142 BF\r\n 134 conv    128       1 x 1/ 1     44 x  44 x 256 ->   44 x  44 x 128 0.127 BF\r\n 135 conv    256       3 x 3/ 1     44 x  44 x 128 ->   44 x  44 x 256 1.142 BF\r\n 136 conv    128       1 x 1/ 1     44 x  44 x 256 ->   44 x  44 x 128 0.127 BF\r\n 137 conv    256       3 x 3/ 1     44 x  44 x 128 ->   44 x  44 x 256 1.142 BF\r\n 138 conv     42       1 x 1/ 1     44 x  44 x 256 ->   44 x  44 x  42 0.042 BF\r\n 139 yolo\r\n[yolo] params: iou loss: ciou (4), iou_norm: 0.07, cls_norm: 1.00, scale_x_y: 1.20\r\n 140 route  136 \t\t                           ->   44 x  44 x 128 \r\n 141 conv    256       3 x 3/ 2     44 x  44 x 128 ->   22 x  22 x 256 0.285 BF\r\n 142 route  141 126 \t                           ->   22 x  22 x 512 \r\n 143 conv    256       1 x 1/ 1     22 x  22 x 512 ->   22 x  22 x 256 0.127 BF\r\n 144 conv    512       3 x 3/ 1     22 x  22 x 256 ->   22 x  22 x 512 1.142 BF\r\n 145 conv    256       1 x 1/ 1     22 x  22 x 512 ->   22 x  22 x 256 0.127 BF\r\n 146 conv    512       3 x 3/ 1     22 x  22 x 256 ->   22 x  22 x 512 1.142 BF\r\n 147 conv    256       1 x 1/ 1     22 x  22 x 512 ->   22 x  22 x 256 0.127 BF\r\n 148 conv    512       3 x 3/ 1     22 x  22 x 256 ->   22 x  22 x 512 1.142 BF\r\n 149 conv     42       1 x 1/ 1     22 x  22 x 512 ->   22 x  22 x  42 0.021 BF\r\n 150 yolo\r\n[yolo] params: iou loss: ciou (4), iou_norm: 0.07, cls_norm: 1.00, scale_x_y: 1.10\r\n 151 route  147 \t\t                           ->   22 x  22 x 256 \r\n 152 conv    512       3 x 3/ 2     22 x  22 x 256 ->   11 x  11 x 512 0.285 BF\r\n 153 route  152 116 \t                           ->   11 x  11 x1024 \r\n 154 conv    512       1 x 1/ 1     11 x  11 x1024 ->   11 x  11 x 512 0.127 BF\r\n 155 conv   1024       3 x 3/ 1     11 x  11 x 512 ->   11 x  11 x1024 1.142 BF\r\n 156 conv    512       1 x 1/ 1     11 x  11 x1024 ->   11 x  11 x 512 0.127 BF\r\n 157 conv   1024       3 x 3/ 1     11 x  11 x 512 ->   11 x  11 x1024 1.142 BF\r\n 158 conv    512       1 x 1/ 1     11 x  11 x1024 ->   11 x  11 x 512 0.127 BF\r\n 159 conv   1024       3 x 3/ 1     11 x  11 x 512 ->   11 x  11 x1024 1.142 BF\r\n 160 conv     42       1 x 1/ 1     11 x  11 x1024 ->   11 x  11 x  42 0.010 BF\r\n 161 yolo\r\n[yolo] params: iou loss: ciou (4), iou_norm: 0.07, cls_norm: 1.00, scale_x_y: 1.05\r\nTotal BFLOPS 42.687 \r\navg_outputs = 351422 \r\n Allocate additional workspace_size = 52.43 MB \r\nLoading weights from yolo-obj_best.weights...net.optimized_memory = 0 \r\nmini_batch = 1, batch = 64, time_steps = 1, train = 0 \r\nnms_kind: greedynms (1), beta = 0.600000 \r\nnms_kind: greedynms (1), beta = 0.600000 \r\nnms_kind: greedynms (1), beta = 0.600000 \r\nDone! Loaded 162 layers from weights-file \r\n\r\n seen 64, trained: 121 K-images (1 Kilo-batches_64) \r\nCannot load image <\r\nLabel file name is too short: < \r\n'`
It looks like the code can't load images. I'm sure the command is correct since I have tested it in Command Prompt.

**Comment by WenTheProgrammer** [comment]
I finally figured out. The only change that needs to be made is adding `shell=True` in the code. Below is the fully functioning example code in Spyder:
`import subprocess`
`command: list = ["darknet.exe", "detector", "test", "data/obj.data", "yolo-obj.cfg", "yolo-obj_best.weights", "-thresh", "0.25", "-dont_show", "-save_labels", "<", "testimage/test.txt"]`
`process: subprocess.Popen = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=True)`
`stdout,stderr = process.communicate()`
`print(stdout)`
