### ISSUE TITLE
Error on running Detector constructor as dll with custom objects: "82 Type not recognized: [yolo] (...)"

### ISSUE THREAD

**Issue by fmgracias** [AlexeyAB/darknet#599]
Hi all,

After fixing my last issue reported on: https://github.com/AlexeyAB/darknet/issues/576

I've successfully trained my custom object detector and **I can run it with no issues on my console**:
`darknet.exe detector test data/obj.data yolo-obj.cfg backup/yolo-obj_3100.weights -i 0 -thresh 0.25 dog.jpg`

But when I try to run it on my application that uses yolo_console_dll I face the following error:

> **82 Type not recognized: [yolo]**
> Unused field: 'mask = 6,7,8'
> Unused field: 'anchors = 10,13,16,30,33,23,30,61,62,45,59,119,116,90,156,198,373,326'
> Unused field: 'classes = 2'
> Unused field: 'num = 9'
> Unused field: 'jitter = .3'
> Unused field: 'ignore_thresh = .5'
> Unused field: 'truth_thresh = 1'
> Unused field: 'random = 1'
>    83 route  79
>    84 conv    256  1 x 1 / 1    13 x  13 x 512   ->    13 x  13 x 256
>    85 Type not recognized: [upsample]
> Unused field: 'stride = 2'
>    86 route  85 61
>    87 Layer before convolutional layer must output image.: No error

I'm using the same files (_yolo-obj.cfg, yolo-obj_3100.weights and obj.names_) and the projects build successfully.

Code where the issue happens:
> Detector detector("yolo-obj.cfg", "data/yolo-obj_3100.weights");

Any suggestion that might fix this?
Thanks in advance

**Comment by AlexeyAB** [comment]
You should re-compile `yolo_cpp_dll.sln`
