### ISSUE TITLE
OpenCV3?

### ISSUE THREAD

**Issue by richipower** [AlexeyAB/darknet#60]
hello! i have been working with YOLO on both mac and windows(using your port) with opencv 2.4.13 but i wanted to implement also the extra modules for opencv which works for the 3.x versions. Has someone got it working with opencv 3.x? including "opencv2/videoio/videoio_c.h" ?
greeetz!

**Comment by AlexeyAB** [comment]
Hi,

Darknet Yolo doesn't work with OpenCV 3.x out of box. But you can see at: https://github.com/AlexeyAB/darknet/issues/48#issuecomment-289774991

Also you can use Darknet-Yolo as DLL `yolo_cpp_dll.sln` (which not required OpenCV): https://github.com/AlexeyAB/darknet#how-to-use-yolo-as-dll
And use your own application `yolo_console_dll.sln` that uses this DLL, and any version of OpenCV and any other libs.

**Comment by AlexeyAB** [comment]
Now this fork supported both OpenCV 3.0 and 2.4.13
Also supported both cuDNN 5.1 and 6.0
