### ISSUE TITLE
Set network random resize limit as config parameter

### ISSUE THREAD

**Issue by limwenyao** [AlexeyAB/darknet#6013]
Firstly, I would like to clarify the following concept. When training with my model with random=1, what it does is at every 10 iterations, the model gets randomly resized (according to the stdout Resizing, random_coef = 1.40) I believe this random_coef is the upper limit to how much a model can resize to, so with a model config width height set to (416 416), it can resize up to (608 608).

I’m wondering if this random_coef parameter can be exposed, as in my use case I would like to use a smaller value. I am facing OOM issues when the image just happens to resize to 608 608, and to me i would neither want to change the current model’s width height setting (416 416) nor the batch/subdivision in order to maximize compute utilization. I would like to slightly reduce this random_coef value such that it will avoid resizing the network to (608 608).

Any alternative suggestions welcome

**Comment by limwenyao** [comment]
I am also curious (referencing yolov3 cfg) why the **random** parameter is on each yolo layer rather than a global parameter. I would assume the network resizing is done at the model level and not the yolo layer level

**Comment by WongKinYiu** [comment]
you can set `random=1.2` in the last `[yolo]` layer for example.
it will overwrite random_coef.
https://github.com/AlexeyAB/darknet/blob/master/src/detector.c#L186

**Comment by limwenyao** [comment]
@WongKinYiu livesaver! I'll try it out, thanks!
