### ISSUE TITLE
Correct strategy to assign masks in yolov4's  yolo layers

### ISSUE THREAD

**Issue by PGCodehub** [AlexeyAB/darknet#6018]
Fix masks in yolov4-custom

* yolo-obj.txt - correct masks
* yolov4-custom.txt - **incorrect** masks
_Originally posted by @AlexeyAB in https://github.com/AlexeyAB/darknet/issues/5180#issuecomment-620580311_

HI @AlexeyAB ,

can you please explain what is the wrong in the mask in yolov4-custom.txt, i am confused on the strategy to choose mask indexes , please help me on how to choose which mask for each yolo layer in yolov4 custom dataset training

should lower layers generate larger anchor boxes or vise versa

the anchor box calculations on my custom dataset is
after running this command
./darknet detector calc_anchors data/obj.data -num_of_clusters 9 -width 608-height 608-show

12, 34, 18, 70, 29, 53, 29,105, 59,106, 41,165, 67,230, 116,331, 246,504

The height and width I am training( in cfg) with is 608 608
Please help me with this

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

Only if you are an expert in neural detection networks - recalculate anchors for your dataset for width and height from cfg-file: darknet.exe detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416 then set the same 9 anchors in each of 3 [yolo]-layers in your cfg-file. But you should change indexes of anchors masks= for each [yolo]-layer, so for YOLOv4 the 1st-[yolo]-layer has anchors smaller than 30x30, 2nd smaller than 60x60, 3rd remaining, and vice versa for YOLOv3. Also you should change the filters=(classes + 5)*<number of mask> before each [yolo]-layer. If many of the calculated anchors do not fit under the appropriate layers - then just try using all the default anchors.

**Comment by PGCodehub** [comment]
HI @AlexeyAB ,

Thank you so much for the help ,

one more question, as you suggested to calculate anchor sizes for 416 by 416 

will the mask setup of  

> 1st-[yolo]-layer has anchors smaller than 30x30, 2nd smaller than 60x60, 3rd remaining, 

remain the same even if i choose to train on the bigger size of 608 or 832 images in the training phase 

Please let me know this answer

**Comment by AlexeyAB** [comment]
If you use 608x608 then calculate anchors for 608x608

**Comment by PGCodehub** [comment]
but the mask choosing would remain same, I would need to assign anchors less than 30 * 30 to first yolo layer and less 60*60 to second and so on 

Thanks for the help
