### ISSUE TITLE
Low FPS in video detection with NVIDIA GeForce GTX 970

### ISSUE THREAD

**Issue by spinlud** [AlexeyAB/darknet#6027]
Hi! 
I have compiled darknet on Windows 10 with CUDA 10.2, CUDNN 7.6.5, OPENCV 4.4.0-pre.
I am testing on a PC with i7-2600k @3,40 Ghz, 32 GB Ram, NVIDIA GeForce GTX 970.

I've tried a video detection task with the following command
```shell
darknet.exe detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights video.mp4
```

During the detection I got always an average FPS of 14.0, which doesn't seem so great.
At start I can see that GPU, CUDA, CUDNN and OPENCV are properly recognized:

![image](https://user-images.githubusercontent.com/12783208/85197716-1b167b80-b2e3-11ea-95fd-4c7d92b2a1bb.png)

Is this normal? Is there anything I can do to improve FPS during detection?

**Comment by AlexeyAB** [comment]
Set width=416 height=416 in cfg-file

**Comment by spinlud** [comment]
Hi, I've actually used 256-256 😅

**Comment by AlexeyAB** [comment]
YOLOv4 416x416
* TitanX (Maxwell) - 6.6 TFlops - 38 FPS
* GTX 970 - 3.9 TFLops - 22 FPS

So for YOLOv4 256x256 should be 58 FPS

* Show screenshot of AVG FPS for these 2 commands:
`darknet.exe detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights video.mp4 -dont_show`
`darknet.exe detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights video.mp4 -benchmark`

* Show screenshot with 256x256 YOLOv4
![image](https://user-images.githubusercontent.com/12783208/85197716-1b167b80-b2e3-11ea-95fd-4c7d92b2a1bb.png)

**Comment by spinlud** [comment]
My bad sorry, I was pointing to the wrong cfg file.
I have:
- 608: 14 FPS
- 416: 26 FPS
- 256: 41.8 FPS
- 128: 51 FPS

Seems reasonable?

**Comment by AlexeyAB** [comment]
Yes.

**Comment by spinlud** [comment]
Ok thanks!
