### ISSUE TITLE
Slow detection on GPU

### ISSUE THREAD

**Issue by jessjimejess** [AlexeyAB/darknet#6037]
I have a custom dataset trained with 3 classes (aprox. 4000 images per class), the training went well, but when I tried to detect objects on a video using a GTX 1660 I´m only able to reach 7-8 FPS, is this normal?

I´m using yolov3 with this .cfg configuration:

batch=64
subdivisions=32
width=416
height=416
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

-The video is 640x480 size
-GPU usage is around 97%
-When I use COCO dataset and a clean yolov3.cfg I get the same results

![Captura de pantalla (80)](https://user-images.githubusercontent.com/45564049/85234992-d3dad880-b411-11ea-866f-c9ca637828e6.png)

**Comment by jessjimejess** [comment]
Solved - CUDNN_HALF was ON by default, I just delete CUDNN_HALF from C++ preprocessor setings

**Comment by GHao207** [comment]
Hi!
Happy to find you slove this problem, can you help me how to set CUDNN_HALF  in windows7_64.
Thank you very much
