### ISSUE TITLE
yolov4 inference using Opencv Python 

### ISSUE THREAD

**Issue by hadikoub** [AlexeyAB/darknet#6054]
I'm trying to infer a yolov4 model using Opencv using python but I get this error 
```
net = cv.dnn_DetectionModel("yolov-obj.cfg", "yolo-obj.weights")
SystemError: <class 'cv2.dnn_DetectionModel'> returned a result with an error set
```
I saw that there is a closed feature request from @AlexeyAB on OpenCV repository to add support for yolov4 

https://github.com/opencv/opencv/issues/17148#issue-606398594

I'm just wondering which version of OpenCV python supports yolov4?

**Comment by ark-** [comment]
My understanding is that it was the mish implementation brought in this commit https://github.com/opencv/opencv/commit/a5696da9ecf5c90c230c1ad74e1b276eddb20c02 which was after the release of 4.3.0.

So as of right now you need to compile the master branch yourself or wait for 4.4.0.
