### ISSUE TITLE
Make a prediction for YOLOv4 using python3 (without OpenCV) ?  

### ISSUE THREAD

**Issue by yassinesefrioui** [AlexeyAB/darknet#6073]
Hello ! 
how can i make prediction with Yolov4 using python3 ? 
i have already tested with OpenCV ( version : 3.4.2 & version 4.3.0)  but it doesn't work. 

i trained yolov4 by this cfg file : 
https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4-custom.cfg

is there any script to make prediction by Keras or Pytorch ? 

thank you :+1:

**Comment by KyloEntro** [comment]
You can use darknet_video.py script to do prediction with Yolov4.

**Comment by AlexeyAB** [comment]
https://pypi.org/project/yolov4/

Just do 

`python3 -m pip install yolov4`

to use Yolov4 with TensorFlow in Python.
