### ISSUE TITLE
Printing xmin, ymin, xmax, ymax

### ISSUE THREAD

**Issue by harrysprogramming** [AlexeyAB/darknet#6078]
Hi there Im running Yolo V4, I cant figure out how to get the bounding box coords (xmin, ymin, xmax, ymax) I tried some of the comments talking about editing the image.c file but its still not working @AlexeyAB can you help? Btw Im trying to get the Coordinates so that i can calculate if the bounding boxes are touching/overlapping each other. Also Im running the darknet.py file, instead of a command in the cmd line

**Comment by hlacik** [comment]
`    for detection in detections:

        label = detection[0].decode()
        confidence = detection[1]
        bounds = bounding_box(detection[2])`

....

`def bounding_box(bounds):
    x, y, w, h = bounds
    xmin = x - (w / 2)
    xmax = x + (w / 2)
    ymin = y - (h / 2)
    ymax = y + (h / 2)

    # xmin, ymin might be negative value
    return max(0, xmin), max(0, ymin), xmax, ymax`

**Comment by harrysprogramming** [comment]
@hlacik Hi! Thanks for ur reply. Which File is that code for?

**Comment by harrysprogramming** [comment]
Sorry my bad obvious answer (darknet.py)
