### ISSUE TITLE
Why Yolov4-tiny mask 1,2,3 not 0,1,2 ?

### ISSUE THREAD

**Issue by luckcodingdog** [AlexeyAB/darknet#6083]
Hi, AlexeyAB,

Thanks a lot for your yolov4-tiny cfg file.
The result is so good and so speed.
I have one question:
In line of 266 of Yolov4-tiny, why mask = 1,2, 3 not 0,1,2 ?

```
[yolo]

mask = 1,2,3

anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
```

**Comment by JimLee1996** [comment]
I guess, on the yolo layer of stride 16, the anchor[0] = (10, 14) is downsampled less than (1, 1) which might be meaningless for a grid. So instead, mask out it and use available anchors.

**Comment by luckcodingdog** [comment]
I found someone have raised the same question.
https://github.com/AlexeyAB/darknet/issues/6067
