### ISSUE TITLE
Highest accuracy with set fps goal, normal v4 or v4-tiny?

### ISSUE THREAD

**Issue by Denizzje** [AlexeyAB/darknet#6092]
Hello,

I have an Xavier NX and I would like to find the balance between best accuracy for a given FPS. The camera I use always sends out 25 fps. I look at quite fast moving objects, so I need the full FPS. However, I can live with 20, and even 15 is acceptable but best would be to have 25fps.

So using Opendatacam, I achieve about 30-40 fps with my Yolo v4-tiny configuration, where I changed nothing with fps and such. Using full Yolov4, I get about 11-12fps on 15W max power mode of the Xavier NX.

Due to fast moving, relatively small objects I think I need biggest resolution possible. I do not need the tiny to run at full FPS, it is just wasting FPS because my camera cant look faster. 

Would it be worth it to either increase the Tiny resolution to higher? Is there other things I can do to achieve bigger accuracy because I can lose FPS?

Or would it be better to run a lower resolution full Yolo model, in an attempt to get atleast 20 and if possible 25 fps? Is there things which can make detection speed up without losing too much accuracy?

Thank you for any advice.

**Comment by AlexeyAB** [comment]
Yes, set width=832 height=832 in yolov4-tiny.cfg


> Or would it be better to run a lower resolution full Yolo model, in an attempt to get atleast 20 and if possible 25 fps? Is there things which can make detection speed up without losing too much accuracy?

Yes, just use OpenCV or tkDNN/TensorRT

**Comment by Denizzje** [comment]
Thank you for the reply. I shall retry the higher resolution Tiny first, because I know how to do that :). 

To make sure:

I compiled Darknet with OpenCV already on, is that different from what you mean?

TensorRT is different backend, just like Darknet is a backend right? It is out of my skills to do that. Opendatacam ensures I can use Yolo in practise. So if it cannot work there I cannot use it (yet).

**Comment by Denizzje** [comment]
I am using 832 now with Tiny and it substantially reduced flickering in corners and ghost detection in difficult areas while retaining performance. Normal Yolo takes much longer too train, I think high resolution Tiny is best for me. Thanks :).
