### ISSUE TITLE
Worse perfomance with cuDNN?!

### ISSUE THREAD

**Issue by QueensGambit** [AlexeyAB/darknet#61]
First of all, thank you for your great work and detailed documentation.

I've built the following versions of yolo-v2 for Windows:
- darknet.exe (CPU)
- darknet.exe (CUDA 8.0)
- darknet.exe (CUDA 8.0 & cuDNN 5.1)
- yolo_cpp_dll.dll (CUDA 8.0)
- yolo_cpp_dll.dll (CUDA 8.0 & cuDNN 5.1)

Surprisingly, I experienced a slightly worse run-time when using **darknet.exe (CUDA & cuDNN 5.1)**
in comparison to **darknet.exe (CUDA 8.0)** on the classification on a single image.
This contradicts the given statement:

> 5.If you want to build with CUDNN to speed up then:

That's why I conducted a loop-test to classify the same image for 1000 times with **yolo_cpp_dll.dll (CUDA 8.0)** and  **yolo_cpp_dll.dll (CUDA 8.0 & cuDNN 5.1)**:
- **yolo_cpp_dll.dll (CUDA 8.0)**: **87.603s**
- **yolo_cpp_dll.dll (CUDA 8.0 & cuDNN 5.1)**: **77.554s** 

_(All tests have been executed with an Nvidia Quadro K4200.)_

## Loop-Test with DLLs
I've expanded the example project **yolo_console_dll.sln** to run a detection loop on the given image file:
```
// ...
time_start = clock();
std::vector<bbox_t> result_vec;
for (int i = 0; i < nb_loops; i++) {
    result_vec = detector.detect(mat_img);
}
time_end = clock();
// ...
```

### _LOG:_ Using yolo_cpp_dll.dll -> **CUDA 8.0 with cuDNN 5.1**
```
...
Loading weights from yolo-voc.weights...Done!
input image filename: data/dog.jpg
number of loops (default 1): 1000
prediction of 1000 images took **87.603s** to execute
obj_id = 6 - x = 449, y = 72, w = 247, h = 105, prob = 0.799758
obj_id = 1 - x = 58, y = 138, w = 546, h = 292, prob = 0.673446
obj_id = 11 - x = 125, y = 228, w = 203, h = 305, prob = 0.907202
input image filename: data/dog.jpg
number of loops (default 1): 1000
prediction of 1000 images took **88.267s** to execute
obj_id = 6 - x = 449, y = 72, w = 247, h = 105, prob = 0.799758
obj_id = 1 - x = 58, y = 138, w = 546, h = 292, prob = 0.673446
obj_id = 11 - x = 125, y = 228, w = 203, h = 305, prob = 0.907202
input image filename:
```

### _LOG:_ Using yolo_cpp_dll.dll -> **CUDA 8.0 without cuDNN 5.1**
```
...
Loading weights from yolo-voc.weights...Done!
input image filename: data/dog.jpg
number of loops (default 1): 1000
prediction of 1000 images took **77.554s** to execute
obj_id = 6 - x = 449, y = 72, w = 247, h = 105, prob = 0.799758
obj_id = 1 - x = 58, y = 138, w = 546, h = 292, prob = 0.673446
obj_id = 11 - x = 125, y = 228, w = 203, h = 305, prob = 0.907202
input image filename: data/dog.jpg
number of loops (default 1): 1000
prediction of 1000 images took **77.369s** to execute
obj_id = 6 - x = 449, y = 72, w = 247, h = 105, prob = 0.799758
obj_id = 1 - x = 58, y = 138, w = 546, h = 292, prob = 0.673446
obj_id = 11 - x = 125, y = 228, w = 203, h = 305, prob = 0.907202
input image filename:
```

Has anyone had similar results and what speed improvements in % are expected when using cuDNN?

**Comment by AlexeyAB** [comment]
@QueensGambit Hi,

1. cuDNN accelerates up ~1.5x times **training**
2. cuDNN on Maxwell and Pascal - detection has the ~ same speed with or without cuDNN. 
    (on Maxwell GeForce GTX 970 with and without cuDNN - detection on 1000 images - 29 sec.)
3. For old Kepler or Fermi architecture cuDNN can work slowly than without cuDNN

----
cuDNN will give more performance for later Yolo versions and modern GPUs.

Supported operations for non-Tesla cards (only GeForce and Quadro):

* Fermi: FP32
* Kepler: FP32 https://devtalk.nvidia.com/default/topic/905001/does-kepler-tesla-k40m-support-fp16-/
* Mawell: FP32, FP16
* Pascal: FP32, FP16, INT16, INT8

So if you use cuDNN 5.1 and Maxwell or Pascal - can be used FP16
If you use cuDNN 6.0 and Pascal - can be used INT16 and INT8
Less bit capacity - faster performance. If it will be implemented in Yolo.

![cuda_mixed_precision_support-768x367](https://cloud.githubusercontent.com/assets/4096485/24969403/5b34190e-1fb9-11e7-9a19-ae39b6c0bf47.png)

![dp4a_dp2a-768x274](https://cloud.githubusercontent.com/assets/4096485/24969564/dc2ef998-1fb9-11e7-8c68-50d31cf52d42.png)

> Figure 2: New DP4A and DP2A instructions in Tesla P4 and P40 GPUs provide fast 2- and 4-way 8-bit/16-bit integer vector dot products with 32-bit integer accumulation.

https://devblogs.nvidia.com/parallelforall/mixed-precision-programming-cuda-8/

**Comment by QueensGambit** [comment]
@AlexeyAB: Thanks a lot for your prompt and comprehensive reply.

**Comment by anonym24** [comment]
@AlexeyAB 
> cuDNN accelerates ~1.5x times training
> cuDNN on Maxwell and Pascal - detection has the ~ same speed with or without cuDNN.
> (on Maxwell GeForce GTX 970 with and without cuDNN - detection on 1000 images - 29 sec.)

so does it accelerate only training?
it doesn't accelerate detection?

**Comment by anonym24** [comment]
yeah seems that mentioned only training - https://developer.nvidia.com/cudnn

**Comment by AlexeyAB** [comment]
@anonym24 
Now, cuDNN accelerates only Yolo training.
Latter, most likely, new GPUs with new cuDNN will accelerate Yolo detection too (by using **Tensor Cores**).

**Comment by AlexeyAB** [comment]
I implemented INT8 quantization for Yolo v2 and v3 in this repo: https://github.com/AlexeyAB/yolo2_light

COCO:
* Yolov3 mAP=53.6% / 54.36% (1.3x acceleration)
* Yolov3-tiny mAP=31.58% / 33.99% (1.17x acceleration)

VOC:
* Yolov2 mAP=74.93% / 75.80% (1.7x acceleration)
* Yolov2-tiny mAP=52.64% / 57.10% (1.5x acceleration)


More: https://github.com/AlexeyAB/darknet/issues/726#issuecomment-409983119
