### ISSUE TITLE
Why cpu inference is faster in OpenCV dnn?

### ISSUE THREAD

**Issue by spinlud** [AlexeyAB/darknet#6100]
Just curious, I've trained a custom model using `tiny-yolov3` in `darknet`.
When testing inference on cpu, I got a prediction in about 600 ms in `darknet`and 40 ms in `OpenCV dnn`. 
Why is there so much difference?

**Comment by AlexeyAB** [comment]
* I didn't speedup Darknet for CPU 
* You should compile Darknet with AVX=1 OPENMP=1 DEBUG=0

**Comment by spinlud** [comment]
I see! Thanks @AlexeyAB
