### ISSUE TITLE
yolov3/yolov3-tiny is faster than yolov4/yolov4-tiny on CPU and GPU

### ISSUE THREAD

**Issue by RenLuXi** [AlexeyAB/darknet#6101]
1. Test configuration
CPU : Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
GPU : GeForce GTX 1660 Ti
2. Test code
`./darknet detector test ./cfg/coco.data cfg/yolov4-tiny.cfg yolov4-tiny.weights data/dog.jpg`
`./darknet detector demo ./cfg/coco.data cfg/yolov4-tiny.cfg yolov4-tiny.weights`
3. Test Results

 configuration| yolov4 | yolov4-tiny | yolov3 | yolov3-tiny
-- | -- | -- | -- | --
CPU | 14400ms | 1.3fps    650ms | 6050ms | 1.7fps   530ms
GPU | 16fps 60ms | 30fps 4.66ms | 30fps 32.5ms | 30fps 4.27ms

**Test results show that yolov3/yolov3-tiny is faster than yolov4/yolov4-tiny**,I am confused, so come to ask for help.
I hope you can answer for me, very grateful！

**Comment by AlexeyAB** [comment]
* Use the same width=416 height=416 in all cfg-files. (in yolov4.cfg too)
* For the same speed v4 has much higher accuracy. For the same accuracy v4 has much higher speed.
* On GTX v4-tiny is slightly faster than v3-tiny. On RTX v3-tiny is slightly faster than v4-tiny.

**Comment by RenLuXi** [comment]
Thank you for answering me, you are the best！
