### ISSUE TITLE
Is mosaic recommended for tiny v4?

### ISSUE THREAD

**Issue by ankandrew** [AlexeyAB/darknet#6105]
Default yolov4 tiny .cfg doesn't include mosaic augmentation, were any experiments done with it?

**Comment by AlexeyAB** [comment]
Yes. mosaic degrades accuracy for tiny model.
Stronger data augmentation should be used for large models.

**Comment by smallerhand** [comment]
> Yes. mosaic degrades accuracy for tiny model.
> Stronger data augmentation should be used for large models.

What is the difference between "tiny model" and "large model"?
(If it's custom model, )
Is that mean the number of the classes?
or size of the training dataset?

**Comment by ankandrew** [comment]
@smallerhand Large model is referring to normal YOLO v4 ( large because-> much more layers & computations than tiny version) The training size dataset doesn't change the computations of the CNN (it may take longer to train tho)
