### ISSUE TITLE
 YOLOv4 on TensorRT+tkDNN 

### ISSUE THREAD

**Issue by ferociousricky** [AlexeyAB/darknet#6116]
@AlexeyAB
Hi AlexeyAB:

Yesterday, i tried TensorRT + tkDNN. However, i think the link which in tkDNN （ https://git.hipert.unimore.it/fgatti/darknet.git, Export weights from darknet ）doesn't support  any longer.
Could you provide any other option for me to implement export weights from darknet to TensorRT?

BR Rex

**Comment by AlexeyAB** [comment]
What error do you get?

**Comment by ferociousricky** [comment]
Actually, i didn't get any error. However, in ceccocats's github, which you offer a solution for tensorrt solution for yolov4, i can't git clone the link and, in ceccocats's github, i couldn't find any related issue for my problem.
![Screenshot from 2020-07-07 09-51-24](https://user-images.githubusercontent.com/26264546/86688329-9349a480-c038-11ea-8515-93f5cd4f8bae.png)

**Comment by AlexeyAB** [comment]
Download and un-compress: https://git.hipert.unimore.it/fgatti/darknet/-/archive/master/darknet-master.zip

then do
```
cd darknet
make
mkdir layers debug
./darknet export <path-to-cfg-file> <path-to-weights> layers
```

**Comment by ferociousricky** [comment]
@AlexeyAB :
Can you upload the .zip file for me? I still cannot reach that website.
![Screenshot from 2020-07-08 14-57-24](https://user-images.githubusercontent.com/26264546/86887605-6629ee80-c12b-11ea-830d-ee895cd8a351.png)

**Comment by AlexeyAB** [comment]
[darknet-master.zip](https://github.com/AlexeyAB/darknet/files/4890564/darknet-master.zip)

**Comment by ferociousricky** [comment]
@AlexeyAB : Thank you!!!
