### ISSUE TITLE
Train & Labeling

### ISSUE THREAD

**Issue by mey1k** [AlexeyAB/darknet#6122]
1.
![1](https://user-images.githubusercontent.com/20632502/86445039-aadd1080-bd4c-11ea-9ba5-640e89d189a6.png)

2.
![2](https://user-images.githubusercontent.com/20632502/86445046-add80100-bd4c-11ea-9fbb-2bcd28db5778.png)

I want to train & labeling looks like number 2.

Is it possible?

**Comment by AlexeyAB** [comment]
Currently, no.

**Comment by mey1k** [comment]
@AlexeyAB Okay, Thank you!!
