### ISSUE TITLE
How to know when to stop when Average loss keep changing

### ISSUE THREAD

**Issue by elementdl** [AlexeyAB/darknet#6128]
Hi,

I'm currently training yolov3-tiny with 14 classes and around 100 000 images for my dataset.

I saw that I should stop traing when I had more than 2000* number classes : 28000 iterations, or when the average loss is around 0,XXXXXX for a small dataset, or around 3.0 for a big dataset.

I'm around 25000 iterations but the average loss keep oscillating around 2.3 (cf image).

Is it normal? Do I need to keep training way more maybe?

Sincerely,
![chart_exemple](https://user-images.githubusercontent.com/51809667/86479084-c4318d00-bd4b-11ea-9c27-6ecde64e8ac5.PNG)

**Comment by asverlov** [comment]
Judging by the graph you have a long way to go, its still falling quite sharply

**Comment by elementdl** [comment]
Here's a new image and yes it still seems that the the average loss is falling but very slowly.
Maybe it's because of the size of my dataset (100 000 images)?
![chart_exemple2](https://user-images.githubusercontent.com/51809667/86509561-2db3a900-bde9-11ea-9e7f-e7f6ab7fbffc.PNG)

**Comment by elementdl** [comment]
Do I need to continue until it goes under 0.XXX? Because it seems by the chart that it will take way more than 100 000 iterations.
An avg loss under 3.0 is it enough to detect objects?

**Comment by AlexeyAB** [comment]
Train while mAP increases

**Comment by elementdl** [comment]
Hi @AlexeyAB , I'm still training but the mAP is still around 48-9%.

At this stage, do my program will be able to detect with a good accuracy?

I used 100 000 images in total for 14 classes, is it because of that my program won't go under an avg loss of 0.XXX? 

Do maybe I need to retrain it but with way less images for some classes?

![chart_exemple3](https://user-images.githubusercontent.com/51809667/86826927-a5a3fc80-c091-11ea-87da-3be7d256842c.PNG)

**Comment by AlexeyAB** [comment]
It seems you use very old Darknet repository.

Keep training while mAP increases.

**Comment by elementdl** [comment]
Hi @AlexeyAB , I currently used the repository that was working just before Yolov4.

I stopped when mAP decreased : 

![chart_exemple4](https://user-images.githubusercontent.com/51809667/86895872-6616f800-c105-11ea-9ed5-7bf44354d85d.PNG)

And I tried my program : 
I don't know why but one particular class don't work very well : 

I made a class "person" with the class "person" of the coco dataset and the class "human body" of the openimages V4 dataset, and my results are weak : 

![pre_person1](https://user-images.githubusercontent.com/51809667/86896525-5cda5b00-c106-11ea-9c90-44d703279835.jpg)
![pre_person2](https://user-images.githubusercontent.com/51809667/86896530-5e0b8800-c106-11ea-8a07-704643980d63.jpg)
![pre_person3](https://user-images.githubusercontent.com/51809667/86896531-5e0b8800-c106-11ea-8759-08997d26824a.jpg)

Why "person" is not well detected?

It could be the database?
Is it because of my mAP (50%)? 
How can I change this?

**Comment by AlexeyAB** [comment]
> I stopped when mAP decreased 

Maybe this is just fluctiation rather than decreasing.

> Why "person" is not well detected?

* You training dataset is wrong
* Or your training dataset isn't suitable to the test dataset. https://github.com/AlexeyAB/darknet/wiki/FAQ---frequently-asked-questions
