### ISSUE TITLE
Training custom dataset

### ISSUE THREAD

**Issue by homerjack** [AlexeyAB/darknet#6138]
I noticed that there is a Yolov4 Model Zoo. May I know what will be the difference between using weights from the Model Zoo versus using the Yolov4.conv.137 for training on a custom dataset?

Would the Yolov4.conv.137 yield a better mAP compared to using the Model Zoo's weights?
What about in terms of training speed?

**Comment by AlexeyAB** [comment]
You should run this command https://github.com/AlexeyAB/darknet/blob/3af6781de273fa01f4a535c8e40c5056e809e22f/build/darknet/x64/partial.cmd#L11
to get `yolov4-sam-mish.conv.137 ` file from Model Zoo https://github.com/AlexeyAB/darknet/wiki/YOLOv4-model-zoo

And then use `yolov4-sam-mish.cfg` and `yolov4-sam-mish.conv.137` for training

Yes, you will get higher AP for difficult datasets.

**Comment by homerjack** [comment]
Let me know if my understanding is wrong here.

If I do not create a .conv.137 weights file, technically i'm retraining the entire model . So I should use first create a .conv.137 weights file in order to get pretrained weights on COCO dataset for the first 137 layers and just retrain the last few layers.

**Comment by AlexeyAB** [comment]
All layer will be trained in any cases. 
* or 137 layers will be initialized from pre-trained weights
* or 137 layers will be initialized randomly

**Comment by Luux** [comment]
@AlexeyAB Just for my understanding: Is there the difference between using darknet partial first and skipping this step by directly using the train command on the full model if classes are different?

**Comment by AlexeyAB** [comment]
> Or will there be a completely random initialization as soon as one layer does not fit from the provided weights?

Yes.

**Comment by homerjack** [comment]
Thanks alot AlexeyAB!
