### ISSUE TITLE
Question: Yolo layer params

### ISSUE THREAD

**Issue by sealedtx** [AlexeyAB/darknet#6145]
@AlexeyAB Hi! I have a question:
What is I set different params for each yolo layer, will this have any impact? Or it will use only one of values?
Interested in these params:
```
jitter=.2
scale_x_y = 1.05
cls_normalizer=1.0
ignore_thresh = .7
truth_thresh = 1
```
For example:
for last yolo layer - `jitter=.1; ignore_thresh=.8 `
and for the first yolo layer - `jitter=.2; ignore_thresh=.7`

And one more, could you please share any link where I can read about "eliminate grid sensitivity" and "label smoothing" concept? Thank you very much!

**Comment by AlexeyAB** [comment]
jitter, random, resize - will be used only from last [yolo] layer
all other params will be used for each [yolo] layer
* https://arxiv.org/abs/2004.10934
* https://arxiv.org/abs/1906.02629
* https://arxiv.org/abs/2003.02819

**Comment by sealedtx** [comment]
@AlexeyAB Thanks a lot for the answers and the links! One more question: 
Can I expect that random and resize will give me ~same accuracy? If so resize seems to be better solution as it does not resize network (which may cause out of video memory)
