### ISSUE TITLE
BUG after compiling the updated code you just submitted

### ISSUE THREAD

**Issue by 1027663760** [AlexeyAB/darknet#6152]
Darknet crashes after using random=1
Set random=0 everything works

@AlexeyAB 

2fca3c399b722934d24b9b86963215fc40ac6bcd

**Comment by AlexeyAB** [comment]
@1027663760 Thank, I fixed it: https://github.com/AlexeyAB/darknet/commit/8c77a3d532d6408cede5e5ecce70755ad248ca54

**Comment by 1027663760** [comment]
Okay, now the time in Moscow should be midnight, rest early, good night
