### ISSUE TITLE
Number of max_batches

### ISSUE THREAD

**Issue by NC200** [AlexeyAB/darknet#6157]
Is it necessary to have the max_batches greater than or equal to the number of training images. In my case I am training with a custom Yolov4 dataset with 11,695 images for training and 3 classes.

**Comment by paulheisterkamp97** [comment]
max_batches describes how many iteration(batches) are processed.

- change line max_batches to (classes*2000 but not less than number of training images, but not less than number of training images and not less than 6000), f.e. max_batches=6000 if you train for 3 classes

You should use at least your number of training examples, so in your case at least 12000. but it really depends on the application so it could take more or less. watch Loss and mAP converging.

If your training ends before loss and mAP level out you should increase max_batches, if you are overfitting early you can decrease.

I would try 15000 for starters.
