### ISSUE TITLE
Segmentation fault when I use the darknet.py

### ISSUE THREAD

**Issue by GYC1996** [AlexeyAB/darknet#6161]
when I use the darknet.py, meeting the bug of Segmentation fault (core dumped)
After my analysis, the bug occur when traversing the detection results "dets"
![image](https://user-images.githubusercontent.com/38093100/86797656-82357d80-c0a2-11ea-8603-6b82d98618ef.png)
the dets only can visit the first result, and can't visit another result
when I write the code of 
![image](https://user-images.githubusercontent.com/38093100/86799059-148a5100-c0a4-11ea-8108-13750921bf95.png)
but only print a score, then print Segmentation fault (core dumped)

**Comment by AlexeyAB** [comment]
I just fixed it. Download the latest Darknet version.

**Comment by GYC1996** [comment]
> I just fixed it. Download the latest Darknet version.
Thank you very much

**Comment by lamhoangtung** [comment]
@AlexeyAB in what commit did you fixed this? Can you point me to that one

I am having the same problem and can't seem to resolve it even with the latest code. Thanks!

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet/commit/ccb392ddf2ab49f66989e6318a2e379c9238068c

You should download the latest version and recompile it with LIBSO=1

**Comment by yamiefun** [comment]
Hi @AlexeyAB ,
I compiled .so with the latest version (commit: 103d301c) but still met the same error.
Do you have any suggestion?
I compiled with GPU, CUDNN, OPENCV, LIBSO=1 and others=0
