### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by SunJJ1996** [AlexeyAB/darknet#6173]
@AlexeyAB 
Sorry for disturb. The issue happened when I use the darknet.py in macOS. It seems like in code:
**if dets[j].prob[i] > 0:**
Finding when debug.
Is that the array overload? How can i fix it?
By the way, when I compile darknet in linux , it generate **libdarknet.so** .But in macOS is l**ibdark.dylib**, so I change the code:
**lib = CDLL("./libdarknet.so", RTLD_GLOBAL)** ----> **lib = CDLL("./libdark.dylib", RTLD_GLOBAL)**
I dont know is that OK?
_Thanks very mach!_

**Comment by AlexeyAB** [comment]
Does it work for you? if yes, then this is ok

**Comment by SunJJ1996** [comment]
> Does it work for you? if yes, then this is ok

I dont know cus the bug above. When i run the darknet.py  
**Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)** 
probably in 
**def detect_image(net, meta, im, thresh=.5, hier_thresh=.5, nms=.45, debug=False):**
**if dets[j].prob[i] > 0:**
when j = 1, and i=0 I thought.
when j = 0, i = 0,1,2,3,4, it all works.
will interrupt. so is there some way to fix this problem?
