### ISSUE TITLE
compile Darknet with OpenCV for using mosaic=1 

### ISSUE THREAD

**Issue by priteshgohil** [AlexeyAB/darknet#6176]
I'm training detector on cutom dataset on Linux. But at somepoint i'm getting follwoing error.
![Screenshot from 2020-07-08 16-05-22](https://user-images.githubusercontent.com/43172056/86928920-8363ba80-c135-11ea-94b1-78793580a12c.png)

**Comment by Ashwin-Ramesh2607** [comment]
@priteshgohil I think you have not compiled with Darknet with Opencv. Please the check the following line in the Makefile and set the OPENCV flag as 1 [here](https://github.com/AlexeyAB/darknet/blob/a47422a30ea947bcbd1753b2c10c41058024a0ba/Makefile#L4)
change it to `OPENCV=1`

After changing this, compile darknet using the command
`make`

**Comment by priteshgohil** [comment]
Thank you, I was running without setting `OPENCV=1`.
