### ISSUE TITLE
YOLOv3 detection using OpenCV with CUDA in Python is only 20FPS

### ISSUE THREAD

**Issue by KacperPaszkowski** [AlexeyAB/darknet#6177]
Hi,

I'm trying to detect 10x10px objects on 2500x2000px image with custom trained weights. I'm splitting this image into 30 416x416px images. I've compiled OpenCV with CUDA and now using it with Python. For one 416x416px image it takes about 0.055s to detect (20 FPS).

Is there any option to speed this up to 0.013s (80 FPS) per image?

I'm using GTX1050 Ti (in few days RTX2080). RAM usage is 5GB, CPU 50% and GPU ~6%.

**Comment by YashasSamaga** [comment]
I get around ~20 FPS on GTX 1050. tkDNN gives 21 FPS. GTX 1050 Ti should give better FPS.

If you're not using the latest master, please set `nms_threshold=0` in all `[yolo]` blocks in `yolov3.cfg`. I'd recommend you use master to avoid messing around with `yolov3.cfg` (and it's also faster).

You can get higher FPS by batching the images. You can pull some more FPS by using multiple `cv::dnn::Net` objects but you will have to verify if this outperforms a single batch of 30 images.

Your pre/postprocessing in python can also be a bottleneck. You can do the pre-postprocessing using [`cv::dnn::DetectionModel`](https://docs.opencv.org/master/d3/df1/classcv_1_1dnn_1_1DetectionModel.html). This is considerably faster than python pre-postprocessing.

> Is there any option to speed this up to 0.013s (80 FPS) per image?

This is impossible for GTX 1050 Ti but easily achievable for RTX 2080.

**Comment by KacperPaszkowski** [comment]
Now I'm using RTX2080 and I achive ~50 FPS. Now my problem is Python postprocessing. Model outputs around 35k predictions for one small image (~1M for large) where 99% of them have score below 0.001%. Filtering it takes around 0.015-0.02s (0.5s for large image) with list comprehension and 3 subprocesses. Is there any way to lower amount of those detections?

**Comment by YashasSamaga** [comment]
> Now I'm using RTX2080 and I achive ~50 FPS.

Are you using the FP16 target? It's much faster and you barely lose any detection performance.

Are you processing in batches?  This can increase the FPS 1.5x - 2x depending on the batch size.

The latest master can provide 10-15% higher FPS compared to OpenCV 4.3.0.

> Filtering it takes around 0.015-0.02s (0.5s for large image) with list comprehension and 3 subprocesses. Is there any way to lower amount of those detections?

The number of detections is defined by the model. I don't think you can change this without changing the input image size.

[DetectionModel](https://docs.opencv.org/master/d3/df1/classcv_1_1dnn_1_1DetectionModel.html) can reduce postprocessing costs by avoiding the python overhead.

**Comment by KacperPaszkowski** [comment]
> Are you using the FP16 target? It's much faster and you barely lose any detection performance.
Currently I'm using target 'DNN_TARGET_CUDA' and backend 'DNN_BACKEND_CUDA'. How should I change it?

> Are you processing in batches? This can increase the FPS 1.5x - 2x depending on the batch size.
I don't really know how this works. I only need to set batch size in config and model will output predictions for e.g. 2 images?

> The latest master can provide 10-15% higher FPS compared to OpenCV 4.3.0.
You mean by using script from 'darknet.py'?

> DetectionModel can reduce postprocessing costs by avoiding the python overhead.
I will try to implement it tomorrow.

Thank you.

**Comment by YashasSamaga** [comment]
> Currently I'm using target 'DNN_TARGET_CUDA' and backend 'DNN_BACKEND_CUDA'. How should I change it?

`DNN_TARGET_CUDA_FP16`

> I don't really know how this works. I only need to set batch size in config and model will output predictions for e.g. 2 images?

Make a `std::vector<cv::Mat>` of your images and use `blobFromImages` to get a single `cv::Mat`. Pass this to `cv::dnn::Net`. Avoid changing the batch size at frequently as this will cause reinitialization.

> Now I'm working on OpenCV 4.2.0

This is the first version with CUDA support. It's not very good.

**Comment by KacperPaszkowski** [comment]
> Make a std::vector<cv::Mat> of your images and use blobFromImages to get a single cv::Mat. Pass this to cv::dnn::Net. Avoid changing the batch size at frequently as this will cause reinitialization.

So for example I put 4 (416 x 416) images into numpy array and then put this array into `blobFromImages`?

**Comment by YashasSamaga** [comment]
> So for example I put 4 (416 x 416) images into numpy array and then put this array into blobFromImages?

Yes.

**Comment by KacperPaszkowski** [comment]
But how does output will look like? Now I have list with 3 arrays (I don't know why - first array 500 x 6, second 2k x 6 and third 30k x 6) which I concatenate and filter it. Now I'll have 4 lists with 3 elements?

**Comment by KacperPaszkowski** [comment]
I've tried using `DetectionModel` but it runs on CPU and with batch_size = 1. Is there an option to change it? I can't find anything about it in docs.

**Comment by YashasSamaga** [comment]
You will have 3 arrays with a new batch dimension of size 4. You index the first dimension with the image number (0 - 3).

```
for i in range(batch_size):
    blob1 = output1[batch_index, :, :]
    blob2 = output2[batch_index, :, :]
    blob3 = output3[batch_index, :, :]
    
   // blob1, blob2, blob3 are your single image outputs for image no i
```

You could also try:

```
model = cv.dnn_DetectionModel("yolov3.weights", "yolov3.cfg")
model.setInputParams(size=(416, 416), scale=1/256)
classes, scores, boxes = model.detect(image, confidence_threshold, nms_threshold)
```

**Comment by KacperPaszkowski** [comment]
I've tried `blobFromImages` with 30 images. Results are amazing. But how about batch size of 30 with `cv.dnn_DetectionModel`?

**Comment by YashasSamaga** [comment]
`dnn_DetectionModel` doesn't support batches. You can make a feature request at opencv.

I think DetectionModel would perform better since postprocessing is taking bulk of your time (probably more than inference). You should try both and test though.

**Comment by KacperPaszkowski** [comment]
I achived 0.67s for large image with `dnn_DetectionModel` I'll try master OpenCV with F16 target.

Thank you!
