### ISSUE TITLE
seem valid function problem

### ISSUE THREAD

**Issue by lurenlym** [AlexeyAB/darknet#6182]
when I test  a picture by detector test function，I get the correct label horse
![1594295157(1)](https://user-images.githubusercontent.com/26338549/87036280-28a58e00-c21d-11ea-8c58-cf1c1fa3e622.jpg)
but when I test the same picture by valid function, I got the wrong label with the same box
![image](https://user-images.githubusercontent.com/26338549/87036222-0f044680-c21d-11ea-9180-b3d051c7463c.png)

the horse label's id should be 17 in the coco.names

**Comment by AlexeyAB** [comment]
All is correct.

Read: https://stackoverflow.com/a/53352240/1558037

And: https://github.com/AlexeyAB/darknet/blob/aa002ea1f8fbce6e139210ee1d936ce58ce120e1/src/detector.c#L24

**Comment by lurenlym** [comment]
> All is correct.
> 
> Read: https://stackoverflow.com/a/53352240/1558037
> 
> And:
> 
> https://github.com/AlexeyAB/darknet/blob/aa002ea1f8fbce6e139210ee1d936ce58ce120e1/src/detector.c#L24

Got it, Thanks.
