### ISSUE TITLE
Debug / Visualize model

### ISSUE THREAD

**Issue by holger-prause** [AlexeyAB/darknet#6187]
Hello,
From time to time my training does not fit my data well and i want to find out why.
https://github.com/AlexeyAB/darknet/wiki/FAQ---frequently-asked-questions#1-i-get-low-accuracy
This certainly helps but my question is:

Is there any out of the box way to look at the feature/activation maps on certain layers to find out why my model 
makes some decisions? This would help with picking proper data or adopt my labeling strategy.

Thank you very much + Greetings,
Holger

**Comment by stephanecharette** [comment]
> This would help with picking proper data or adopt my labeling strategy.

Not exactly what you were asking for, but in case it helps you may want to checkout the "review" and "statistics" window in DarkMark.  They've helped me find several places where I had marked up an object with the wrong class id which was impacting the effectiveness of my neural networks.

- https://www.ccoderun.ca/darkmark/Summary.html#DarkMarkReview
- https://www.ccoderun.ca/darkmark/Summary.html#DarkMarkStatistics

**Comment by holger-prause** [comment]
@stephanecharette 
I have similar tooling like you mentioned, but thx for your help.
Ok so no further comment received - guess its too special or was already answered - closing.
