### ISSUE TITLE
Sorry to bother you，the paper cite problem

### ISSUE THREAD

**Issue by haotlong** [AlexeyAB/darknet#6198]
I used your darknet framework to do some work, and now it will be used to publish paper, how can I cite your work in the article? (YOLOv4 is not used, so it is unclear how to mark the reference information)

**Comment by AlexeyAB** [comment]
Try to cite Zendo DOI: https://zenodo.org/record/3829035#.Xwhd_W0zapo

**Comment by haotlong** [comment]
Thank you
