### ISSUE TITLE
cuDNN 6 support ...

### ISSUE THREAD

**Issue by VanitarNordic** [AlexeyAB/darknet#62]
Hi,

Have you tested the repository with the new cuDNN 6?

**Comment by apiszcz** [comment]
FYI:

https://groups.google.com/forum/#!topic/darknet/AEP4qwIPwa4
Build error on windows.
This may be an issue for CUDNN8.0 V6.0 builds.

CUDNN8.0 V5.1 works.

Severity Code Description Project File Line
Error C2198 'cudnnSetConvolution2dDescriptor': too few arguments for call
darknet G:\p\darknet\src\convolutional_layer.c 149

**Comment by AlexeyAB** [comment]
I didn't try cuDNN 6 yet. I think source code of Yolo should be changed for using cuDNN 6.
Then may be Yolo will support FP16, INT16 or INT8 to speed up 2-4 X times.
