### ISSUE TITLE
core dump

### ISSUE THREAD

**Issue by abeyang00** [AlexeyAB/darknet#620]
I have trained yolo v3 with about 10,000 PNG images and it worked fine.
Now i added additional 4000 JPEG images and now im getting segmentation fault (core dump)

Will having 2 different types of image files be a problem?

**Comment by AlexeyAB** [comment]
No, it shouldn't be a problem.

**Comment by abeyang00** [comment]
@AlexeyAB what can be the cause of segmentation fault?
It runs fine for like 300 iterations and code explodes. 

I have no idea what the cause is.
I have all the image data and labels for each image, correspondingly

**Comment by AlexeyAB** [comment]
Try to set `valid=` the same as `train=` in the `obj.data` file.
Then can you do successfully?
`darknet.exe detector map data/obj.data yolo-obj.cfg backup\yolo-obj_1000.weights`
`darknet.exe detector recall data/obj.data yolo-obj.cfg backup\yolo-obj_1000.weights`

**Comment by abeyang00** [comment]
@AlexeyAB i created my own (following your instruction)
i used dataset available online and they provided csv file for labeling.

I just parsed the csv file into text file accordingly.

Is that the error with txt file or image file? Because i have used the same labeling tool and previous labeling dataset and it worked fine. Its this new dataset thats giving me problem (but i don't know whats wrong with the imgs)

**Comment by AlexeyAB** [comment]
@abeyang00 

1. Add here: https://github.com/AlexeyAB/darknet/blob/b9b0bf5131940217f83a49ec2b107edc645ca7ac/src/detector.c#L486
* this line
```cpp
fprintf(stderr, " %s - %s - ", paths[i], labelpath);
```
* recompile
* then do `darknet.exe detector recall data/obj.data yolo-obj.cfg backup\yolo-obj_1000.weights`
* and press `PAUSE` on the keyboard when first `nan` will occur during recall, do screenshot and send me
* look at the jpg and txt file name for the first `nan` - Check are the paths correct, and are jpg and txt files correct - open them?

----

2. Check that there aren't values equal to 0 (except class_id) in labels

3. Check your dataset using Yolo_mark - Go through all the images using the utility: https://github.com/AlexeyAB/Yolo_mark

**Comment by abeyang00** [comment]
@AlexeyAB ,
Sorry for the late reply. Had some issues i had to take care of.

Here's the screen shot when the first 'nan' occurs. 
![screenshot from 2018-04-19 11-04-59](https://user-images.githubusercontent.com/36392866/38967341-82643054-43c1-11e8-9753-739f452f3e73.png)

I have checked the path for img and corresponding txt file
![screenshot from 2018-04-19 11-07-01](https://user-images.githubusercontent.com/36392866/38967402-cc368efc-43c1-11e8-9c8d-cebd3798ff33.png)

Txt file contains following info
![screenshot from 2018-04-19 11-07-48](https://user-images.githubusercontent.com/36392866/38967427-e737f998-43c1-11e8-966e-9eebbebcec22.png)

Still cant figure out what's wrong with the img...

**Comment by AlexeyAB** [comment]
@abeyang00 I fixed it. Update your code from this repo, and compile.

**Comment by AlexeyAB** [comment]
@abeyang00 There was missed this line `find_replace(labelpath, ".png", ".txt", labelpath);` in the detector recall, but this line was for detector training: 
So detector recall could not get the txt-filename (labels) from png-filename.
