### ISSUE TITLE
Jetson family with CUDNN 8

### ISSUE THREAD

**Issue by samsonadmin** [AlexeyAB/darknet#6202]
If something doesn’t work for you, then show 2 screenshots:
1. screenshots of your issue
2. screenshots with such information
```
GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=1
AVX=0
OPENMP=0
LIBSO=0
ZED_CAMERA=0
ZED_CAMERA_v2_8=0

When I try to make -j4

./src/convolutional_layer.c: In function ‘cudnn_convolutional_setup’:
./src/convolutional_layer.c:286:24: error: ‘CUDNN_CONVOLUTION_FWD_PREFER_FASTEST’ undeclared (first use in this function); did you mean ‘CUDNN_CONVOLUTION_BWD_FILTER_ALGO_3’?
int forward_algo = CUDNN_CONVOLUTION_FWD_PREFER_FASTEST;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CUDNN_CONVOLUTION_BWD_FILTER_ALGO_3
compilation terminated due to -Wfatal-errors.
Makefile:164: recipe for target ‘obj/convolutional_layer.o’ failed
make: *** [obj/convolutional_layer.o] Error 1

Compilation failed:

https://forums.developer.nvidia.com/t/jetpack-4-4-l4t-r32-4-3-issue-with-darknet-yolo/141191/5

AastaLLL gave some help:
https://raw.githubusercontent.com/AastaNV/JEP/master/script/topics/0001-fix-for-cudnn_v8-limited-memory-to-default-darknet-s.patch

```

If you do not get an answer for a long time, try to find the answer among Issues with a Solved label: https://github.com/AlexeyAB/darknet/issues?q=is%3Aopen+is%3Aissue+label%3ASolved

**Comment by samsonadmin** [comment]
it is already fixed

**Comment by maohu-96** [comment]
> it is already fixed
![GPUS_nano_Wallpaper](https://user-images.githubusercontent.com/63272697/87764218-9880cd80-c848-11ea-8654-c4407bd3119f.jpg)
I encountered the above error，how did you solve（Jeston Xavier NX cudnn8）

**Comment by BrooklynBoy21** [comment]
@samsonadmin How did you solve that problem? because I can't build with cmake yolov3_optimal((

The YOLOv4 is built but it doesn't work with Jetson nano, it crashes

**Comment by samsonadmin** [comment]
@BrooklynBoy21 it's running well and doesn't crash.
maybe you need to 
make clean
and make again

**Comment by samsonadmin** [comment]
for the time begin, 
in Makefile, if cudnn is enabled, it is slower that it being disabled

**Comment by BrooklynBoy21** [comment]
@samsonadmin 
Did you face such an error
`

CUDA status Error: file: /home/tima/tima/src/tima_human_detection/darknet/src/dark_cuda.c : () : line: 454 : build time: Jul 24 2020 - 16:41:32 

 CUDA Error: invalid argument
CUDA Error: invalid argument: Success
`

because on my Jetson nano the last version of darknet doesn't work. It is compiling, but when I try to launch it is crashing with an error above.

**Comment by samsonadmin** [comment]
I suspect something from your system got modified.
For me, I downloaded a new images JetPack 4.4 (no DP)
and I recompiled my opencv.
you can try use the original opencv shipped with Jetpack 
and see if that is successful

**Comment by BrooklynBoy21** [comment]
@samsonadmin I have JetPack 4.2 and  original opencv shipped with Jetpack
Maybe the problem is there

But strange thing that YOLO is working. If I run `./darknet detect cfg/yolov3.cfg yolov3.weights data/dog.jpg` it is detecting.
Only AlexeyAB wrapper doesn't work(

**Comment by BrooklynBoy21** [comment]
@samsonadmin my JetPack 4.4 [L4T 32.4.3]

**Comment by LeRoii** [comment]
> @samsonadmin I have JetPack 4.4 and original opencv shipped with Jetpack
> Maybe the problem is there
> 
> But strange thing that YOLO is working. If I run `./darknet detect cfg/yolov3.cfg yolov3.weights data/dog.jpg` it is detecting.
> Only AlexeyAB wrapper doesn't work(

I got the same issue with you, try to select the correct arch according to your device, and rebuild the libdarknet.so.
that fixed for me

**Comment by samsonadmin** [comment]
great
