### ISSUE TITLE
tiny yolov3 coco17 training check

### ISSUE THREAD

**Issue by GotG** [AlexeyAB/darknet#6203]
Training tiny yolov3 locally. Is it on the right track? please see loss/map chart. Thanks!

![chart_yolov3-tiny](https://user-images.githubusercontent.com/61444721/87176207-759f6800-c2e2-11ea-93bc-1872addffb07.png)

**Comment by AlexeyAB** [comment]
Yes, it looks like normal.
You will get final accuracy `33.1 AP50` for yolov3-tiny.cfg on MS COCO test-dev.

**Comment by GotG** [comment]
Thank you !
