### ISSUE TITLE
CUDE Error: no kernel image available for exec on the decice.

### ISSUE THREAD

**Issue by carlerickrowan** [AlexeyAB/darknet#622]
I was able to run build examples on rapsberry pi and my desktop i7 with no GPU. But when I tried my laptop with GPU GeForce 650M, I got this error when I run the command line examples. I do not have errors on compiling except many warnings on data types especially floats and doubles.

I think this is related to CUDA installation. I am planning to reinstall CUDA or install a different version of it. Am I on the right direction? I hope someone could help me. I need to speed up the processing so I want to use my laptop. Thanks!

**Comment by AlexeyAB** [comment]
Try to install CUDA 9.1 and cuDNN 7 for CUDA 9.1.
And compile with GPU=1 CUDNN=1

**Comment by carlerickrowan** [comment]
I have CUDA 9.1 and cuDNN 7 for CUDA 9.1. Also I change the makefile to have GPU=1 CUDNN=1 but I still get the error when I run the commandline examples.

Also, i got these warnings. I think I should solve this?

![30689266_10214173286039684_6079882440665464832_n](https://user-images.githubusercontent.com/20147902/38699855-da978604-3ecb-11e8-906d-6033023cbbfd.jpg)

**Comment by AlexeyAB** [comment]
* Do you try to compile default `\build\darknet\x64\darknet.sln` or do you create your own?
* What MS Visual Studio version do you use?
* Did you compile MSVS 2015 first and CUDA 9.1 only after that?
* Can you show screenshot of your MSVS?
* Do you have `Nsight` tab in the MSVS?

You should install MSVS2015, only after that you should install CUDA 9.1, and then your should open default file  `\build\darknet\x64\darknet.sln` set **x64 & Release** at the top of MSVS and press Build.

**Comment by AlexeyAB** [comment]
@carlerickrowan  Yes, I mean `\build\darknet\darknet.sln`

> Also, i got these warnings. I think I should solve this?

No, you shouldn't fix anything. As I see everything compiled fine!

**Comment by carlerickrowan** [comment]
Hmm. Compilation is ok but I still can't get the cuda to work. I believe that it is cuda related since I can run the command line examples if I build it with no_gpu. Here's my plan.

1. Uninstall everything and then reinstall it again.
2. Try different version of Cuda. Perhaps the version of Cuda I use right now has compatibility issue with Geforce 635M.

If you wan't me to try anything @AlexeyAB, I am very open with suggestions.

**Comment by carlerickrowan** [comment]
I will try Cuda 8. Upon checking, GT635M only has compute capability of 2.1.

![image](https://user-images.githubusercontent.com/20147902/38712947-4a53ee12-3f01-11e8-87dc-544c2521c76b.png)

**Comment by AlexeyAB** [comment]
> I was able to run build examples on rapsberry pi and my desktop i7 with no GPU. But when I tried my laptop with **GPU GeForce 650M**, I got this error when I run the command line examples. I do not have errors on compiling except many warnings on data types especially floats and doubles.


> I will try Cuda 8. Upon checking, **GT635M** only has compute capability of 2.1.

For Darknet:
* GPU GeForce 650M is supported.
* GPU GeForce GT635M isn't supported.
