### ISSUE TITLE
running .\build.ps1 does not work. multiple paths missing

### ISSUE THREAD

**Issue by deepkak** [AlexeyAB/darknet#6236]
* darknet
    * .\build.ps1 
    * Win10
    * 7/14/20
```
CUDA-version: release 10.2, V10.2.89 , cuDNN: 7.5.6, OpenCV version: 4.4.0 pre
GPU: GeForce RTX 2070
```
I intend to use darknet with python 3.7.7 on visual studio 19. If other IDEs/editors are recommended please do let me know. I did not compile with opencv_world.
![error](https://user-images.githubusercontent.com/68088160/87448471-e76cff80-c5c9-11ea-97e1-2390079660df.PNG)

**Comment by kadhirumasankar** [comment]
Please combine #6235 and #6236 into one issue

**Comment by deepkak** [comment]
how do I do so?
