### ISSUE TITLE
Can I use YOLOv4 with a RealSense camera?

### ISSUE THREAD

**Issue by kadhirumasankar** [AlexeyAB/darknet#6237]
I've read that YOLOv4 can be used out of the box on ZED cameras by setting `ZED_camera = 1`. Does setting ZED_camera to 1 also make it work on a RealSense camera?

**Comment by kadhirumasankar** [comment]
I found out that the only thing setting `ZED_camera = 1` does is it runs YOLO as usual and then finds the depth from the depth image. This can be done in separate steps with a RealSense camera. I'm using ROS, and you can run the output of the `/camera/color/image_raw` topic through YOLO, find the coordinates of the center of your object of interest, and then get the aligned depth image from `/camera/aligned_depth_to_color/image_raw` and index it using those coordinates to get the depth in mm.

If you have any questions please leave a comment.

**Comment by Shame-fight** [comment]
> I found out that the only thing setting `ZED_camera = 1` does is it runs YOLO as usual and then finds the depth from the depth image. This can be done in separate steps with a RealSense camera. I'm using ROS, and you can run the output of the `/camera/color/image_raw` topic through YOLO, find the coordinates of the center of your object of interest, and then get the aligned depth image from `/camera/aligned_depth_to_color/image_raw` and index it using those coordinates to get the depth in mm.
> 
> If you have any questions please leave a comment.

Have you implemented ros_yolo_zed, I currently have the same needs.
