### ISSUE TITLE
No object detected by yolov4-tiny when in openCV dnn

### ISSUE THREAD

**Issue by Asif1405** [AlexeyAB/darknet#6244]
Trying to run yolov4-tiny with openCV dnn. Model loads with cv2.readNet. But the confidence scores are all zero and no detection at all. 

Using windows 10
OpenCv 4.2

Any Idea why is that and how to fix?

**Comment by KacperPaszkowski** [comment]
Are you sure that all scores are 8? Try threshold 0.1 or lower.

**Comment by YashasSamaga** [comment]
@Asif1405 can you try with [this](https://gist.github.com/YashasSamaga/e2b19a6807a13046e399f4bc3cca3a49)?

**Comment by AlexeyAB** [comment]
>OpenCv 4.2

YOLOv4 and tiny will be only from OpenCV 4.4.0

**Comment by Asif1405** [comment]
> Are you sure that all scores are zero? Try threshold 0.1 or lower.

I tried with 0 and 0.1 threshing. But no outputs. But as @AlexeyAB memtioned it, will have to wait for opencv 4.4. Thanks for the reply.

**Comment by Asif1405** [comment]
> > OpenCv 4.2
> 
> YOLOv4 and tiny will be only from OpenCV 4.4.

Thanks @AlexeyAB. Been waiting for opencv4.4 for weeks. Wonder how much longer will have to wait..

**Comment by Asif1405** [comment]
> @Asif1405 can you try with [this](https://gist.github.com/YashasSamaga/e2b19a6807a13046e399f4bc3cca3a49)?

I will try it surely.

**Comment by YashasSamaga** [comment]
> I will try it surely.

That script won't work without OpenCV 4.4. Sorry, I didn't see your OpenCV version.

You can build OpenCV 4.4-pre using master.

**Comment by Asif1405** [comment]
> > I will try it surely.
> 
> That script won't work without OpenCV 4.4. Sorry, I didn't see your OpenCV version.
> 
> You can build OpenCV 4.4-pre using master.

Yes it does not work on 4.2. i will try to build 4.4-pre. Thanks.

**Comment by Asif1405** [comment]
Worked with 4.4-pre. Thanks @YashasSamaga 

Closing the issue.
