### ISSUE TITLE
dets[j].prob[i] > 0 Null pointer access problem

### ISSUE THREAD

**Issue by batuhanaman** [AlexeyAB/darknet#6260]
Hi,

I downloaded the latest repo and compile it on Linux (in 20.04, Ubuntu, through make and setting LIBSO=1).  However, when I try to use the library I receive the following error.
```

    if dets[j].prob[i] > 0:
ValueError: NULL pointer access
```

I check the closed issues.  There are some entries related to this problem. They either suggest downloading the new version and compile it from scratch or propose to suggest a specific older version of the code (I tried both of the solutions).  Could you please help me to solve this error? Any direction, hints, and solution strategy is appreciated. 

Thanks.

**Comment by 9r0x** [comment]
@batuhanaman Hi, could you please share how you solved this issue? I still reproduce this issue in the latest commit.

**Comment by benkelaci** [comment]
I am facing with the same issue. I recently updated the darknet.  The code that uses the older darknet version can work, but not with the new one.
@AlexeyAB : do you need the concrete commit id?

**Comment by benkelaci** [comment]
As I see the indexing was changed. Here is the hint for fixing (needs more, but this is the most important one):
`if dets[0].prob[j] > 0:`

while I was fixing this I was discovered some nan values (mainly on y_min value), are these numpy.nan or a different one?

**Comment by matt-sharp** [comment]
@benkelaci Please could you share the full solution to fixing this problem?  I've made the edit you suggest above and have run test.py successfully but unable to get any output from the print statement.

**Comment by benkelaci** [comment]
I think I was just replaced the darknet.py for the current darknet commit and everything was solved. So maybe my suggestion might be misleading, I cannot revise fully. Try to generate/use the latest darknet.py
