### ISSUE TITLE
Trainning for a while  then 'Segmentation fault (core dumped)' happend!

### ISSUE THREAD

**Issue by Young8768** [AlexeyAB/darknet#6265]
Hi, 
when I trained the yolov4 ,i met a issue that is  code runs for a while  then 'Segmentation fault (core dumped)' happens!
1、command I used is:
'./darknet detector train cfg/helmet.data cfg/yolov4_helmet.cfg models/yolov4.conv.137 '
2、 the cfg file I have chaged:
three parts:
"
[convolutional]
size=1
stride=1
pad=1
**filters=21**
activation=linear

[yolo]
mask = 0,1,2
anchors = 12, 16, 19, 36, 40, 28, 36, 75, 76, 55, 72, 146, 142, 110, 192, 243, 459, 401
**classes=2**
num=9
jitter=.3
ignore_thresh = .7
truth_thresh = 1
scale_x_y = 1.2
iou_thresh=0.213
cls_normalizer=1.0
iou_normalizer=0.07
iou_loss=ciou
nms_kind=greedynms
beta_nms=0.6
max_delta=5
"
3.、my device is RTX 2080ti, Cuda 10.2, cudnn 7.5
4、The dataset has no value like (0.0). 

Could you tell me how to solve it ?

**Comment by Young8768** [comment]
5、the device OS  is Ubuntu 16.04

**Comment by stephanecharette** [comment]
Don't know if this will help you, but I ran into something similar a while back.  Eventually figured it out:  https://github.com/AlexeyAB/darknet/issues/5261#issuecomment-616177165

**Comment by Young8768** [comment]
@stephanecharette Thanks, but it didn't work.
The same datas and configs I used could be trained on Windows, but could not on Ubuntu.

**Comment by Young8768** [comment]
I have solved the problem.
Because the image formats are not the same,e.g JPG and jpg. The "Segmentation fault (core dumped)"happend when it loads the ".JPG" images.
