### ISSUE TITLE
Same object, multiple overlapping detections

### ISSUE THREAD

**Issue by rgov** [AlexeyAB/darknet#6271]
I'm using a YOLOv4 network trained with Darknet and loaded into OpenCV. There is only one object class.

<img width="230" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/108767/87846285-cf80ce80-c89c-11ea-8757-5c1732b58f9d.png">

Note that some objects, like the upper right, are labeled twice. Is there a best practice for filtering duplicates out?

**Comment by AlexeyAB** [comment]
Enable NMS.

And attach your cfg file

**Comment by rgov** [comment]
Thanks. Here is the config file: https://gist.github.com/rgov/bd53952d1b0685edaeedd021230f1ab0

Is it simply enough to set for each `[yolo]` layer `nms_kind=diounms`? Or what are you suggesting?

**Comment by AlexeyAB** [comment]
2 months ago there was added separate NMS: https://github.com/opencv/opencv/blob/d8b2f11cc81e4aa1b2b7b063f98ba0b1da8b8fbe/samples/dnn/object_detection.cpp#L425-L437

You should do it in your code.

----

Also

> max_batches = 4000

https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

> change line max_batches to (classes*2000 but not less than number of training images, but not less than number of training images and not less than 6000), f.e. max_batches=6000 if you train for 3 classes

**Comment by rgov** [comment]
Thanks I have NMS working now. And I will retrain with more batches, good point.
