### ISSUE TITLE
Makefile compilation error while trying to use CUDA.

### ISSUE THREAD

**Issue by SamiurRahman1** [AlexeyAB/darknet#6295]
I changed my makefile lines to use CUDA as:

```
GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=1
```
But when i try to run make on the terminal, i get the following error:

```
In file included from /tmp/tmpxft_000063ee_00000000-5_convolutional_kernels.compute_61.cudafe1.stub.c:5:0,
                 from tmpxft_000063ee_00000000-5_convolutional_kernels.compute_61.cudafe1.stub.c:1:
/tmp/tmpxft_000063ee_00000000-5_convolutional_kernels.compute_61.cudafe1.stub.c: In function ‘void __device_stub__Z15binarize_kernelPfiS_(float*, int, float*)’:
/tmp/tmpxft_000063ee_00000000-5_convolutional_kernels.compute_61.cudafe1.stub.c:20:87: error: ‘__args_arr’ was not declared in this scope
 __Z15binarize_kernelPfiS_(float *__par0, int __par1, float *__par2){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaSetupArgSimple(__par2, 16UL);__cudaLaunch(((char *)((void ( *)(float *, int, float *))binarize_kernel)));}
                                                                     ^
compilation terminated due to -Wfatal-errors.
Makefile:170: recipe for target 'obj/convolutional_kernels.o' failed
make: *** [obj/convolutional_kernels.o] Error 1
```
Anyone could help please?

**Comment by SamiurRahman1** [comment]
> I changed my makefile lines to use CUDA as:
> 
> ```
> GPU=1
> CUDNN=1
> CUDNN_HALF=0
> OPENCV=1
> ```
> 
> But when i try to run make on the terminal, i get the following error:
> 
> ```
> In file included from /tmp/tmpxft_000063ee_00000000-5_convolutional_kernels.compute_61.cudafe1.stub.c:5:0,
>                  from tmpxft_000063ee_00000000-5_convolutional_kernels.compute_61.cudafe1.stub.c:1:
> /tmp/tmpxft_000063ee_00000000-5_convolutional_kernels.compute_61.cudafe1.stub.c: In function ‘void __device_stub__Z15binarize_kernelPfiS_(float*, int, float*)’:
> /tmp/tmpxft_000063ee_00000000-5_convolutional_kernels.compute_61.cudafe1.stub.c:20:87: error: ‘__args_arr’ was not declared in this scope
>  __Z15binarize_kernelPfiS_(float *__par0, int __par1, float *__par2){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaSetupArgSimple(__par2, 16UL);__cudaLaunch(((char *)((void ( *)(float *, int, float *))binarize_kernel)));}
>                                                                      ^
> compilation terminated due to -Wfatal-errors.
> Makefile:170: recipe for target 'obj/convolutional_kernels.o' failed
> make: *** [obj/convolutional_kernels.o] Error 1
> ```
> 
> Anyone could help please?

P.S. i am using

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
```

**Comment by scamianbas** [comment]
Why CUDNN_HALF=0 ?

**Comment by scamianbas** [comment]
Also, are you using CUDA 9.0 ? CUDA 10.0 is a requirement.

**Comment by SamiurRahman1** [comment]
hi, thank you for pointing out the obvious. I didn't notice them. :( now i fixed it and it is working. :)
