### ISSUE TITLE
Port tracking cpp to linux environment

### ISSUE THREAD

**Issue by giranntu** [AlexeyAB/darknet#63]
Hi @AlexeyAB ,
Really nice work for this repo, I am working on tracking part, and I saw your tracking .cpp file.
However, I can't compile at Linux system.

how could I port the tracking part to Linux environment? 

Thanks for the kindly support. :)

**Comment by AlexeyAB** [comment]
@giranntu Hi,

Just change line to `LIBSO=1` in the Makefile: https://github.com/AlexeyAB/darknet/blob/master/Makefile#L6
Then will be created `darknet.so` library and `uselib` runable file, that uses library.
Run `uselib`, then enter filename of video and you will see detection on this video with tracking numbers.

Later I'll add tracking by using optical flow, to use tracking on slow GPU.

Now this fork supports:
* both Windows and Linux
* both OpenCV 3.x and 2.4.13
* both cuDNN 5.1 and 6.0
* both SO library on Linux and DLL library on Windows

Also: https://github.com/AlexeyAB/darknet/issues/140#issuecomment-320370521

**Comment by dream-will** [comment]
@AlexeyAB Hi, how to use uselib with my weights and cfg for tracking, i used it like this" ./uselib detector demo cfg/test.data cfg/test.cfg backup/test.weights demo.avi", but there is" Couldn't open file: yolo-voc.cfg"
