### ISSUE TITLE
Modifying the obj.names file during training

### ISSUE THREAD

**Issue by aryu99** [AlexeyAB/darknet#6334]
So I just realised that two names that I had put in the obj.names file are wrong. My model has already undergone 2000 iterations. I was wondering if it's possible for me to pause training, update the names and then resume training using the weights saved in the backup directory.

Please note that the number of classes is the same. Only the names need to be modified. Would this affect the model or the weights in any way or is doing this fine?

Any help would be appreciated! :)

**Comment by stephanecharette** [comment]
Darknet doesn't use the actual names.  It only cares about the index of the class.  It knows there is a class #0, class #1, etc.

The names are only used when it wants to display a name in the annotated image.  So you don't have to stop the training, let it continue.  Then fix the name however you want, fix typos, etc, prior to *using* the neural network.  You'll see when it annotates the image, it will use whatever text happens to be in the .names file, not the text that was there during the training.

**Comment by stephanecharette** [comment]
(linking in #6333)

**Comment by aryu99** [comment]
> Darknet doesn't use the actual names. It only cares about the index of the class. It knows there is a class #0, class #1, etc.
> 
> The names are only used when it wants to display a name in the annotated image. So you don't have to stop the training, let it continue. Then fix the name however you want, fix typos, etc, prior to _using_ the neural network. You'll see when it annotates the image, it will use whatever text happens to be in the .names file, not the text that was there during the training.

Got it, thank you!
