### ISSUE TITLE
Resume training: Every 1000 iterations, or any saved weights file?

### ISSUE THREAD

**Issue by judwhite** [AlexeyAB/darknet#634]
> After each 1000 iterations you can stop and later start training from this point. For example, after 2000 iterations you can stop training, and later just copy yolo-obj_2000.weights

https://github.com/AlexeyAB/darknet/blob/16cfff811f8a5898899cdd0b7139d216466371d2/README.md#L310

Does it need to be an increment of 1000 or is a checkpoint such as `xxx_4700.weights` okay to resume training?

**Comment by AlexeyAB** [comment]
@judwhite You can resume from any weights-file. 
You can use `xxx_4700.weights`

**Comment by judwhite** [comment]
@AlexeyAB I'll raise a PR to clarify the README unless you get to it first 😄 Thanks for you all your help.
