### ISSUE TITLE
darknet: ./src/image.c:41: get_pixel: Assertion `x < m.w && y < m.h && c < m.c' failed. On running detector with my model

### ISSUE THREAD

**Issue by k1dnap** [AlexeyAB/darknet#6343]
I've trained a model using my own dataset. The main difference is that I'm using grayscale images. I've set channels=1, classes = 1, filters = 18 in yolov4-obj.cfg

But when I'm trying to run my custom detector I'm getting an error `darknet: ./src/image.c:41: get_pixel: Assertion 'x < m.w && y < m.h && c < m.c' failed.`
This error only appears when I'm trying to run detector on image which may contain the objects from custom dataset.
Like, if I run my custom detector on image and there are no any objects to seek on it, it successfully saves `predictions.jpg`

It seems like darknet fails on converting the data from the output. Any clues to start?

P.s: sorry, I'm new in this field, so maybe I've trained my model wrong, or dataset is wrong, or I'm doing something wrong.

https://pastebin.com/c91bpMPT - logs when trying to run !./darknet detector test on image which contains some objects from my dataset
https://pastebin.com/YRGLM8sN - logs when trying to run detector on image which doesn't contain any objects from my dataset
https://drive.google.com/file/d/1N94_zjn4qIztJu3PmG2zs1q2p9dz_FRs/view?usp=sharing - here is a test.zip from my dataset
https://drive.google.com/file/d/139o0IZ3YylNj_oLt3ohNBrFrf_IziA3Z/view?usp=sharing - my cfg file
https://drive.google.com/file/d/1ph81HsC5Vzzk1guFlls6kDL1Uz-GSXPp/view?usp=sharing - weights after training

**Comment by diontan524** [comment]
I am having the same issue too. Please help....

**Comment by Jay-zzcoder** [comment]
I am also having this issue,Please help me.

**Comment by Jay-zzcoder** [comment]
> I am having the same issue too. Please help....

I have solved this problem.The method is:
     you can annotate this line of code in image.c like  //assert(x < m.w && y < m.h && c < m.c)(in line 41 of image.c);
     then you remake the makefile(if you don't remake,the result doesn't change!!!)
after finishing above,you can detect your dataset without problems

**Comment by Jay-zzcoder** [comment]
> I've trained a model using my own dataset. The main difference is that I'm using grayscale images. I've set channels=1, classes = 1, filters = 18 in yolov4-obj.cfg
> But when I'm trying to run my custom detector I'm getting an error darknet: ./src/image.c:41: get_pixel: Assertion 'x < m.w && y < m.h && c < m.c' failed.
> This error only appears when I'm trying to run detector on image which may contain the objects from custom dataset.
> Like, if I run my custom detector on image and there are no any objects to seek on it, it successfully saves predictions.jpg
> It seems like darknet fails on converting the data from the output. Any clues to start?
> P.s: sorry, I'm new in this field, so maybe I've trained my model wrong, or dataset is wrong, or I'm doing something wrong.
> https://pastebin.com/c91bpMPT - logs when trying to run !./darknet detector test on image which contains some objects from my dataset
> https://pastebin.com/YRGLM8sN - logs when trying to run detector on image which doesn't contain any objects from my dataset
> https://drive.google.com/file/d/1N94_zjn4qIztJu3PmG2zs1q2p9dz_FRs/view?usp=sharing - here is a test.zip from my dataset
> https://drive.google.com/file/d/139o0IZ3YylNj_oLt3ohNBrFrf_IziA3Z/view?usp=sharing - my cfg file
> https://drive.google.com/file/d/1ph81HsC5Vzzk1guFlls6kDL1Uz-GSXPp/view?usp=sharing - weights after training

I have solved this problem.The method is:
you can annotate this line of code in image.c like //assert(x < m.w && y < m.h && c < m.c)(in line 41 of image.c);
then you remake the makefile(if you don't remake,the result doesn't change!!!)
after finishing above,you can detect your dataset without problems

**Comment by k1dnap** [comment]
> > I am having the same issue too. Please help....
> 
> I have solved this problem.The method is:
> you can annotate this line of code in image.c like //assert(x < m.w && y < m.h && c < m.c)(in line 41 of image.c);
> then you remake the makefile(if you don't remake,the result doesn't change!!!)
> after finishing above,you can detect your dataset without problems

It worked too.

I solved this problem few days ago too:D
So, I downloaded my weights, and used opencv, and it worked.

Also, the weights may be converted to tensorflow format and used using tensorflow. // I haven't tried this, but seems to be working

**Comment by XueFengHuang666** [comment]
> > > I am having the same issue too. Please help....
> > 
> > 
> > I have solved this problem.The method is:
> > you can annotate this line of code in image.c like //assert(x < m.w && y < m.h && c < m.c)(in line 41 of image.c);
> > then you remake the makefile(if you don't remake,the result doesn't change!!!)
> > after finishing above,you can detect your dataset without problems
> 
> It worked too.
> 
> I solved this problem few days ago too:D
> So, I downloaded my weights, and passed my model through openCV, and it worked.
> 
> Also, the weights may be converted to tensorflow format and used with tensorflow. // I haven't tried this, but seems to be legit

Can you shou me how you solve the problem?  I also used  grayscale images for training and meet the same error, great appreciate for you answer.
