### ISSUE TITLE
How to generate own darknet53.conv.74 ?

### ISSUE THREAD

**Issue by deeplearner93** [AlexeyAB/darknet#6354]
Hello @AlexeyAB ,
I would like to create a Custom Object detector. Therefore to start the training as mentioned in the procedure, I start with darknet53.conv.74 convolutional weight which is a pretrained weight file on ImageNet. I do not want to use the pretrained darknet53.conv.74 convolutional weight file. Instead I want to create my own convolutional weight file like darknet53.conv.74 convolutional weight file.

Request your support to share some steps. A quick support will be really helpful as i am in the middle of a project.
Thank you in advance.

**Comment by sealedtx** [comment]
@deeplearner93 If you don't want to use pretrained weights - simply do not specify them in train command:
`darknet detector train your.data your.cfg`
Note: your dataset should be big enough and you have to train much more iterations if you want to train from scratch

**Comment by deeplearner93** [comment]
@sealedtx 
Are you sure. Will the Darknet Framework be able to start Training without the weight files ??

**Comment by sealedtx** [comment]
@deeplearner93 yes, training without weights - means training from scratch

**Comment by deeplearner93** [comment]
Great Thank you
