### ISSUE TITLE
Commit f13532ce60f92859713cfa07cae24b0319e78bcf introduces training crash bug

### ISSUE THREAD

**Issue by RomanVeretenov** [AlexeyAB/darknet#6355]
On f13532ce60f92859713cfa07cae24b0319e78bcf one can see that `darknet.exe detector train ...` crashes

Steps to reproduce:
- run `git clean -dxf; git reset --hard; git checkout 3af6781de273fa01f4a535c8e40c5056e809e22f; ./build.ps1`
- make sure that training runs ok
- run `git clean -dxf; git reset --hard; git checkout f13532ce60f92859713cfa07cae24b0319e78bcf; ./build.ps1`
- make sure that training does not start

Checked on Windows, but on Linux the training crashes too on latest commits

I tried to debug it. First issue appears because region_layer has truth_size == 0 and there is a xcalloc later that leads to xcalloc(0). Fixing truth_size to i.e. 6 does not help (crash happens later).

Yolo config attached
[yolo.cfg.txt](https://github.com/AlexeyAB/darknet/files/4981959/yolo.cfg.txt)

**Comment by AlexeyAB** [comment]
I fixed it.

**Comment by RomanVeretenov** [comment]
Could you please provide the commit where it was fixed? On current master it's still reproduced

**Comment by RomanVeretenov** [comment]
Yes, now I see, bug is fixed. Thanks!
