### ISSUE TITLE
"Improves YOLOv3’s AP and FPS by 10% and 12%, respectively"

### ISSUE THREAD

**Issue by violet17** [AlexeyAB/darknet#6371]
@AlexeyAB @WongKinYiu 
Hi, thanks for the great works. 
The yolov4 paper[https://arxiv.org/pdf/2004.10934.pdf] says "Improves YOLOv3’s AP and FPS by 10% and 12%, respectively"
I have fully understood it. Which input size and hardware use for comparison?
As known from Figure 1 inyolov4 paper , for 608x608 input running on V100:
YOLOv4 608x608 FPS 65 AP 43.5
YOLOv3 608x608 FPS 72 AP 33
It seems that YOLOv3 is faster than YOLOv4. 
I can't figure out the reason.
And have you do some comparisons about YOLOv4 and YOLOv3 on pascal GPU? I haven't found it on Table 9 in yolov4 paper.

Thank you very much!

**Comment by YashasSamaga** [comment]
> YOLOv4 and YOLOv3 on pascal GPU?

If GTX 1050 counts, YOLOv4 and YOLOv3 performance are practically the same with OpenCV DNN. You get around 10-11 FPS.

**Comment by AlexeyAB** [comment]
GPU Tesla V100: https://arxiv.org/abs/2004.10934

![image](https://user-images.githubusercontent.com/4096485/88804617-de2d8680-d1b6-11ea-9f11-b255182e9c6e.png)

**Comment by violet17** [comment]
> GPU Tesla V100: https://arxiv.org/abs/2004.10934
> 
> ![image](https://user-images.githubusercontent.com/4096485/88804617-de2d8680-d1b6-11ea-9f11-b255182e9c6e.png)

V100
YOLOv4  608 FPS  62  AP  43.5
YOLOv4  512 FPS  83  AP  43
YOLOv3  608 FPS  74  AP  33

83/74-1=12%
43/33-1=30% ?
I got 30% on AP increase calculation..

**Comment by violet17** [comment]
Thank you very much.
