### ISSUE TITLE
relation between false positives&false negatives and number of iterations

### ISSUE THREAD

**Issue by k00r** [AlexeyAB/darknet#639]
Hello i have a few questions,i'll be glad if you answer them.

1)what is the relation between false positives&false negatives and number of iterations? do false positives and false negatives tend to decrease as the iteration count goes up? for example if i train for 10k iterations and take the .weights file and test it and see some false positives do i have to train more or can a previous weights file perform better? if yes how can i find the best performing weights?

2)how can i disable the graph window when training?

3)how can i show the detected objects confidence level inside the rendered label?

**Comment by AlexeyAB** [comment]
1. You can i find the best performing weights by using `darknet detector map`... and look at `mAP = x.xx %` - the heigher - the better
    Yes, false positives and false negatives tend to decrease as the iteration count goes up for training dataset, but now always for validation dataset, because there is Early stopping point: https://github.com/AlexeyAB/darknet#when-should-i-stop-training

2.  Point 8: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects
    (To disable Loss-Window use darknet.exe detector train data/obj.data yolo-obj.cfg darknet53.conv.74 -dont_show, if you train on computer without monitor like a cloud Amazaon EC2)

3. Between these 2 lines: https://github.com/AlexeyAB/darknet/blob/6aa140b3c6e9917936f73bd538fce4fe20954233/src/image.c#L355-L356

Insert this code:
```cpp
char bp[100];
sprintf(bp, " %f %", dets[i].prob[j] * 100);
strcat(labelstr, bp]);
```

**Comment by k00r** [comment]
thank you very much =) @AlexeyAB
