### ISSUE TITLE
NOT USE CUDA?

### ISSUE THREAD

**Issue by aureosun** [AlexeyAB/darknet#64]
Hello AlexeyAB,
I'm using your darknet under win10 vs2013,does it work when I do NOT use cuda?

**Comment by AlexeyAB** [comment]
@aureosun Hi,

Yes, just compile `darknet_no_gpu.sln` instead of `darknet.sln`: https://github.com/AlexeyAB/darknet/tree/master/build/darknet

**Comment by aureosun** [comment]
Thank you,Sir! And now I have another question,that is:I just run your version of darknet yolo without gpu,the speed is kind of slow,about 9 seconds per frame,so I'd like to use the blas library which is created for matrix operations,for example,OpenBLAS,MKL,Eigen and so on.My classmate have found that the function gemm  was been used for many times,so How Can I Modify the Code?Would you please give me some suggestions ?

**Comment by AlexeyAB** [comment]
@aureosun 

I think there is not simple way to use any CPU-blas library (OpenBLAS,MKL,Eigen), because source Darknet-Yolo fork doesn't support any of it out-of-box. And all functions for CPU implemented manually: 

* https://github.com/AlexeyAB/darknet/blob/master/src/blas.c
* https://github.com/AlexeyAB/darknet/blob/master/src/cpu_gemm.c

So you should implement CPU-blas support by yourself, by linking blas-library and changing functions in `blas.c`, `cpu_gemm.c`, ... to call functions from blas-library.

**Comment by aureosun** [comment]
@AlexeyAB 
Sir,there is another question:I use your version of darknet in win10 vs2013 without opencv,but the outcome
is shown as below:

Loading weights from yolo.weights...Done!
Enter Image Path: G:\darknet_win\data\person.jpg
G:\darknet_win\data\person.jpg: Predicted in 8.929000 seconds.
Not compiled with OpenCV, saving to predictions.png instead 

I guess if no opencv installed,the outcome will NOT shown?just as what I see in ubuntu?
but in ubuntu the outcome is like this

Loading weights from yolo.weights...Done!
data/dog.jpg: Predicted in 7.803236 seconds.
car: 54%
bicycle: 51%
dog: 56%
Not compiled with OpenCV, saving to predictions.png instead

What's the matter?Could you help me?

**Comment by AlexeyAB** [comment]
@aureosun Do you use on Yolo without CUDA and without OpenCV?
Is there any bounded boxes in the predictions.png on Windows in your case?
What command do you use to start yolo?

In your cases shall be output to console with predictions:
* in function `void test_detector()`
* called `draw_detections()` https://github.com/AlexeyAB/darknet/blob/a87abe8de58427f842b371c0169b4c41dc1cb6f1/src/detector.c#L481
* which print predictions to console ` printf("%s: %.0f%%\n", names[class], prob*100);` https://github.com/AlexeyAB/darknet/blob/a87abe8de58427f842b371c0169b4c41dc1cb6f1/src/image.c#L196

**Comment by aureosun** [comment]
@AlexeyAB Thanks a lot!
Sir,I just use it without CUDA and without OpenCV,after compiled successfully,I enter the cmd window,to the directory of G:\darknet_win\build\darknet\x64\,where there is an executive file darknet_no_gpu.exe,then  
I make it execute in cmd, Where is my fault?I'm really confused about it.

**Comment by aureosun** [comment]
@AlexeyAB Thanks a lot!
Sir,I just use it without CUDA and without OpenCV,after compiled successfully,I enter the cmd window,to the directory of G:\darknet_win\build\darknet\x64,where there is an executive file darknet_no_gpu.exe,then
I make it execute in cmd, Where is my fault?I'm really confused about it.
and I run it as below:

darknet_no_gpu.exe detect yolo.cfg yolo.weights -i 0 -thresh 0.2

then I enter the path,Here I'll get the outcome:

Loading weights from yolo.weights...Done!
Enter Image Path: G:\darknet_win\data\person.jpg
G:\darknet_win\data\person.jpg: Predicted in 8.929000 seconds.
Not compiled with OpenCV, saving to predictions.png instead

Could you please help me with it?As a beginner ,Your answer is very helpful to me!

**Comment by AlexeyAB** [comment]
@aureosun Try to download latest `yolo.weights` from: https://pjreddie.com/darknet/yolo/
And download latest `yolo.cfg`: https://github.com/pjreddie/darknet/raw/master/cfg/yolo.cfg
And may be also update your Darknet code from this Girhub-repo.

Your case is strange:

* I just remove define OPENCV from: Visual Studio->Project->Properties->C/C++->Preprocessor
* Open `darknet_no_gpu.sln` and recompile it
* Start this command: `darknet_no_gpu.exe detect yolo.cfg yolo.weights -i 0 -thresh 0.2`

And get good result:

![image](https://cloud.githubusercontent.com/assets/4096485/25345379/98b975f4-291d-11e7-9c92-86954538cbdf.png)

predictions.png

![predictions](https://cloud.githubusercontent.com/assets/4096485/25345787/80b3e204-291e-11e7-9fe1-80070fce80db.png)

**Comment by aureosun** [comment]
@AlexeyAB 
Thank you,Sir,the problem has been solved with your help.The reason is that the way I remove define OPENCV is wrong,I remove all about OPENCV in this project in the properties page,so I will not get any outcome.
Thank again!

**Comment by jaelim** [comment]
@AlexeyAB If I want to test on multiple image files, is there an option where I can save them in different output files, rather than `predictions.png`?

It seems like I can modify you `void test_detector()` in `detector.c` where I can change following

```
save_image(im, "predictions");
show_image(im, "predictions");
```
as
```
save_image(im, filename);
show_image(im, filename);
```

Is this modification going to work?
