### ISSUE TITLE
Problem with get_anchors.py

### ISSUE THREAD

**Issue by spenceryue97** [AlexeyAB/darknet#640]
I'm trying to recalculate anchor using get_anchors.py. But I got the following error message:

```
Traceback (most recent call last):
  File "get_anchors.py", line 166, in <module>
    main(sys.argv)
  File "get_anchors.py", line 162, in main
    kmeans(annotation_dims,centroids,eps,anchor_file)
  File "get_anchors.py", line 73, in kmeans
    k,dim = centroids.shape
ValueError: not enough values to unpack (expected 2, got 1)
```

Can anyone suggest me how to solve it? Thanks in advance!

**Comment by corentin87** [comment]
you are probably not getting any centroids. Can you print centroids before _k,dim = centroids.shape_ to see if the array is empty or not?

**Comment by changliang-sun** [comment]
I also meet this problem, would you please tell me how to solve this problem? Thank you very much.

**Comment by changliang-sun** [comment]
I also meet this problem. Would you please tell me how to solve this problem? Thank you very much.

**Comment by changliang-sun** [comment]
I found the problem. The version of get_anchors.py is the old version. The code has some problems. 
 The new code is OK. 
Compare this line: `annotation_dims.append(tuple(map(float,(w,h))))`
