### ISSUE TITLE
Is it OK to train a yolov4 If my dataset contains both 8-bit and 24-bit images?

### ISSUE THREAD

**Issue by sensationTI** [AlexeyAB/darknet#6403]
The majority of the images in my dataset are 8-bit. For better results, I added more images, but the new images are 24-bit.
Is it OK to train a yolov4 network on this hybrid dataset (8-bit and 24-bit)? or do I need to unify the bit?

**Comment by AlexeyAB** [comment]
It is ok. All images will be converted to 24-bit images automatically.
