### ISSUE TITLE
Opencv Dnn yolov4-tiny slower yolov3-tiny (ARM)

### ISSUE THREAD

**Issue by sealedtx** [AlexeyAB/darknet#6405]
Hi @AlexeyAB I am trying to run tiny models using opencv dnn on my **armv7** system. I successfully used **opencv 4.3+yolov3-tiny-3l** (before yolov4-tiny release) and it's inference time was **~1.5s**. But **opencv 4.4+yolov4-tiny** gave me **~4.5s** inference time which is surprisingly a lot. I have also tested these models on PC but yolov4-tiny is faster as excepted.
What is the problem with arm? Is there some operatation included in yolov4-tiny that are much slower on ARM systems? Thank you! 
Notes: 
- Opencv 4.3 and 4.4 are compiled with same options and flags.
- I measure time only for net.forward(), without pre-post-processing
- Both models are 416x416

**Comment by AlexeyAB** [comment]
Can you compare yolov4-tiny vs yolov3-tiny with the same resolution 416x416, the same OpenCV 4.4.0 + ARM with the same code, 1000 iterations of net.forward() in a loop?

Also try to use this code: https://gist.github.com/YashasSamaga/48bdb167303e10f4d07b754888ddbdcf

**Comment by sealedtx** [comment]
Thank you, this benchmark helped me undestand that yolov3-tiny model was pruned and this is why it overperformed yolov4-tiny.

**Comment by deepseek** [comment]
@sealedtx so were you able to improve tiney v4 speed on arm?

**Comment by sealedtx** [comment]
@deepseek I didn't focus on this, performance was ~same as yolov3-tiny model, which was enough for me.
