### ISSUE TITLE
I train the network for 9000 iterations, If I add in more images, should I re-train from scratch or continue?

### ISSUE THREAD

**Issue by sensationTI** [AlexeyAB/darknet#6411]
I trained the network using a dataset after 9,000 iterations. I collected more images and added them into my dataset, should I re-train the network from scratch? or can I just keep training using the weight from 9000th iteration?

**Comment by Yogerlan** [comment]
If the classes were not changed, keep training with the saved weights. Your initial mAP differs from the previous dataset but it will be adjusting after some epochs with the new samples.

**Comment by sensationTI** [comment]
> If the classes were not changed, keep training with the saved weights. Your initial mAP differs from the previous dataset but it will be adjusting after some epochs with the new samples.

If some objects in my newly collected images are not labeled, and I feed it into the network. Will it make any effect on the training result?

**Comment by AnchorAnalytics** [comment]
Yes.  Images with no labels negative samples.

**Comment by Mahdi89** [comment]
Note that images with desired objects without labels are not negative samples. They would impact your training and could confuse your model.
