### ISSUE TITLE
Segmentaion Error

### ISSUE THREAD

**Issue by veer345** [AlexeyAB/darknet#642]
I am using linux 16.04 intel i3
error- Not used AVX
Segmentation fault (core dumped)
what should i do ...
I am really tired now i have been trying from so many days .....
Please help me how should i proceed..

**Comment by AlexeyAB** [comment]
1. Can you show screenshot of the error?
2. What parameters in the Makefile do you use? https://github.com/AlexeyAB/darknet/blob/17d242bd506f1b94501599d68864ba36eebd2837/Makefile#L1-L6
3. What command line do you use for runing darknet?
4. Replace file `src/gemm.c` to this one: https://raw.githubusercontent.com/AlexeyAB/darknet/f1ad9a0487dc60c01e56bacb2a67de1e1006b4b7/src/gemm.c

then do
```
make clean
make -j8
```

**Comment by veer345** [comment]
![7](https://user-images.githubusercontent.com/14336679/38807701-13d56f9a-419b-11e8-98a5-0492f10aef76.png)
and what about gemm.h file

**Comment by veer345** [comment]
same i am not making any changes in make file

**Comment by veer345** [comment]
what process i follow ::
Step1-Downloaded ur darknet
Step 2- running make command in darknet folder(not in build/64x/)
step3-creating images and txt files 
step4- creating yolo-obj-cfg file
step4-test and train text file
step5- darknet19_448.conv.23 copying to darknet directory
step 6 running the train command

**Comment by veer345** [comment]
and yes i have replaced gemm.c file but same error occurs

**Comment by veer345** [comment]
after replaceing gemm file its running let's now hope for good results.
THANK YOU so much :+1:

**Comment by AlexeyAB** [comment]
@veer345 

I just fixed this bug in the last commit.

Now it can successfully detect `used AVX` or `not used AVX` on CPU without `Segmentaion Error`:
![image](https://user-images.githubusercontent.com/4096485/38810559-ce512fbe-418f-11e8-8bf8-4baeb9595194.png)

**Comment by veer345** [comment]
Couldn't open file: obj.names
now this error comes ... after 2700 iteration..
Please help me out

**Comment by AlexeyAB** [comment]
@veer345 Update your code from GitHub.
