### ISSUE TITLE
Something needs to be updated in README.md

### ISSUE THREAD

**Issue by TNTWEN** [AlexeyAB/darknet#6451]
README.md
```
Yolo v4 in other frameworks
Intel OpenVINO 2019 R1: (Myriad X / USB Neural Compute Stick / Arria FPGA): read this manual

```
These need to be updated. Yolov4 cannot be implemented in Intel OpenVINO 2019 R1 which doesn't support Mish and split. Actually the latest openvino2020 R4 begins to support the operations required by v4

**Comment by TNTWEN** [comment]
Although there is no official support for the implementation of YOLOv4. Maybe  [this project](https://github.com/TNTWEN/OpenVINO-YOLOV4) which has been verified by Intel CPU,Intel Graphics GPU and USB Neural Compute Stick2 can be used temporarily

**Comment by AlexeyAB** [comment]
@TNTWEN Thanks, great work! I fixed it: https://github.com/AlexeyAB/darknet#yolo-v4-in-other-frameworks
