### ISSUE TITLE
Visualize convolutional features  of yolov3-tiny model 

### ISSUE THREAD

**Issue by ninenerd** [AlexeyAB/darknet#6452]
Hi, how you can visualize convolution features ?
Here is an example https://towardsdatascience.com/how-to-visualize-convolutional-features-in-40-lines-of-code-70b7d87b0030  
I could not find for tiny yolov3 -darknet model ?  
Has anyone done this ?

**Comment by qingchunlizhi** [comment]
https://github.com/AlexeyAB/darknet/issues/571
