### ISSUE TITLE
Back to basics

### ISSUE THREAD

**Issue by Moorditj** [AlexeyAB/darknet#646]
I cloned the latest repository from AlexeyAB and I running this..

./darknet detector test ./cfg/coco.data ./cfg/yolov3.cfg ./yolov3.weights

I get this..

Illegal instruction (core dumped)

Same when I try to run ./darknet detector demo ./cfg/coco.data ./cfg/yolov3.cfg ./yolov3.weights test50.mp4 -i 0 -thresh 0.25

I was running my own video through a previous repository and it was all good.

I'm extremely green with all of this and any direction would be appreciated. 

CUDA: 9.1.85
OpenCV: 3.3.1
gcc: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

I can confirm that CUDA and OpenCV are working on machine as I can use the framework from https://pjreddie.com/darknet/yolo/ and run my own video.

Regards,

Tom

**Comment by ralek67** [comment]
Remove these 2 lines:

```
else
CFLAGS+= -ffp-contract=fast -mavx
```

**Comment by AlexeyAB** [comment]
@Moorditj 

Can you successfully run it

* if `CFLAGS+= -mavx` https://github.com/AlexeyAB/darknet/blob/140333977cea0ba9e384cd38fd01013a8915ef60/Makefile#L53

* or after removing this line https://github.com/AlexeyAB/darknet/blob/140333977cea0ba9e384cd38fd01013a8915ef60/Makefile#L53

**Comment by ralek67** [comment]
I have the same problem and just tried
Illegal instruction with
CFLAGS+= -ffp-contract=fast -mavx
Illegal instruction with 
CFLAGS+= -mavx

**Comment by AlexeyAB** [comment]
@ralek67 Can you show, what CPU do you use?
`lscpu`

**Comment by AlexeyAB** [comment]
@ralek67 Thanks, I added flag `AVX=0` to the Makefile, that is disabled by default.

**Comment by Moorditj** [comment]
Yes. Got working thankyou
