### ISSUE TITLE
Low mAP on Person dataset

### ISSUE THREAD

**Issue by fostjms** [AlexeyAB/darknet#6460]
Hi!
I've been training following The AI Guy tutorial on Google Colab for YOLOv4 and for a custom dataset consisting of only the Person class.
My dataset consists of images from Open Images, (1000 for training and 250 for validation) and I used [theAIGuysCode/OIDv4_ToolKit](https://github.com/theAIGuysCode/OIDv4_ToolKit) python script for the annotations.

Everything seems fine during the training, but I have to stop the training from time to time and then I resume from the last.weights saved on my google drive.
I finished my training yesterday and I checked the mAP of my weights file. It is around 33%.

How do I improve that stat? I followed everything that's been said on his video and I also checked AlexeyAB repo. I tried to retrain again and my max precision was 38% on the 1000th iteration weights file and went down from there.

**Comment by ark-** [comment]
Two things I note:

 1. The openimages dataset isn't great. Manually look at their annotations. You will find images with people not marked, and some with people's faces marked but not their bodies and so on and so on. Manually go through and adjust them all yourself.
 2. You should be training for at least 2000 images per class, and a minimum of 6000 altogether.

**Comment by fostjms** [comment]
Thank you!
I'll try with a different dataset then.
