### ISSUE TITLE
How to increase classes?

### ISSUE THREAD

**Issue by cheolgyu** [AlexeyAB/darknet#6464]
Thank you for making yolov4.

Currently only classes=7 is required.
The classes will increase in the future.

1. Would it be better to train with the current classes=80? if not
2. Now train with classes=7. In the future, can we train after increasing classes=80 from the last weight?

**Comment by karen-gishyan** [comment]
Check the original documentation.
https://github.com/alexeyab/darknet#how-to-train-to-detect-your-custom-objects
