### ISSUE TITLE
Why TENSOR CORES are disabled at the training start?

### ISSUE THREAD

**Issue by Yogerlan** [AlexeyAB/darknet#6467]
TENSOR CORES are disabled until the the first 3 * net.burn_in iterations are reached. Can someone share an explanation? What happen if i try to use TENSOR CORES from the beginning or after the burn_in iterations gets completed?

**Comment by arnaud-nt2i** [comment]
Hi, Yogerlan
See:
https://github.com/AlexeyAB/darknet/issues/3656

**Comment by Yogerlan** [comment]
Thanks.
