### ISSUE TITLE
-ext_output for video to .txt file

### ISSUE THREAD

**Issue by fostjms** [AlexeyAB/darknet#6486]
Hey,

is there a way to save the output of the detection command on video to a .txt just like I can with images?

If I run
`!./darknet detector demo data/obj.data cfg/yolov4-obj.cfg /mydrive/yolov4/backup/yolov4-obj_last.weights -dont_show /mydrive/yolov4/funny.mp4 -ext_output -i 0 -out_filename results.mp4`
the output is shown (FPS, object, bb coordinates, etc...).

How can I modify that command so that it behaves just like this one (images)
`!./darknet detector test data/obj.data cfg/yolov4-obj.cfg /mydrive/yolov4/backup/yolov4-obj_last.weights -ext_output < /mydrive/yolov4/percorsi.txt > result.txt -thresh 0.3`
so the output is written to the result.txt file?

I tried to add the `-ext_output < /mydrive/yolov4/percorsi.txt > result.txt` part but it doesn't seem to work and creates a heavy .txt file (gigabytes).

edit:
I could get the .txt file result and it's giving me this:
![image](https://user-images.githubusercontent.com/36927552/90231902-22a65c80-de1c-11ea-8bd9-239352ac5f10.png)

**Comment by fostjms** [comment]
Ok, the -out flag doesn't work for demo.
Regardless, I found a way to solve my problem. 

I'll close this issue.

**Comment by RobinV760** [comment]
Hi @fostjms how did you solve the issue? I'm trying to do the same thing here.

**Comment by fostjms** [comment]
Hello @RobinV760 just get frames from your video, save them somewhere (in my case I saved them to Google Drive), then create a txt file where each line contains the path to a frame, and then just run the command:
`!./darknet detector test cfg/coco.data cfg/yolov4.cfg yolov4.weights -dont_show -ext_output < /mydrive/yolov4/frame/paths.txt > result.txt`
where paths.txt is the txt file I just told you, and result.txt is the txt file that contains the results of the detection.
Let me know I you got it!
