### ISSUE TITLE
Couldn't get the detection results!

### ISSUE THREAD

**Issue by Young8768** [AlexeyAB/darknet#649]
Hi, I have successfully compiled the project of yolov3_no_gpu and yolov3_gpu on windows platform ,following the step. But I couldn't get the detection results when I tested the projects. I'm so confused.
I found 'l.side =0'  is the problem why no results  after I debuged the program.
I don't know how to solver it ,so hope reply.
Thanks!

**Comment by AlexeyAB** [comment]
Hi,
* What OS do you use?
* Did you use default `darknet.sln` or did you create your own?
* What CUDA, cuDNN, OpenCV, and compiler version do you use?
* What command do you use to run detection?

**Comment by Young8768** [comment]
@AlexeyAB  
I use the command 'detector test cfg\\coco.data cfg\\yolov3.cfg model\\yolov3.weights data\\person.jpg' can get the results,but why can't get results use the other command?

**Comment by AlexeyAB** [comment]
> The command is 'yolo test cfg\yolov3.cfg model\yolov3.weights data\person.jpg'

* `yolo test`... - is for Yolo v1
* `detector test`... is for Yolo v2 and v3

How to use on the command line: https://github.com/AlexeyAB/darknet#how-to-use-on-the-command-line
