### ISSUE TITLE
Visual Studio Link is unreachable 

### ISSUE THREAD

**Issue by apiszcz** [AlexeyAB/darknet#65]
The Requires section has a link that changed or is no longer available.

MS Visual Studio 2015 (v140): https://www.microsoft.com/download/details.aspx?id=48146

There appears to be a community edition link at
https://go.microsoft.com/fwlink/?LinkId=615448&clcid=0x409

**Comment by AlexeyAB** [comment]
@apiszcz Thank you! Fixed.
