### ISSUE TITLE
the yolov4.weights download here seem not work

### ISSUE THREAD

**Issue by WellAlreadyTaken** [AlexeyAB/darknet#6511]
the yolov3.weights work well and show me where are dog 
so i download yolov4.cfg and yolov4.weights and put them on the right path
using ./darknet  detector test ./cfg/coco.data ./cfg/yolov4.cfg ./yolov4.weights data/dog.jpg 
![Screenshot from 2020-08-18 20-03-35](https://user-images.githubusercontent.com/34592132/90511029-7a332800-e18e-11ea-8c6f-53739ef05140.png)
should i do something to make it working?

**Comment by AlexeyAB** [comment]
Download the latest Darknet version.

**Comment by WellAlreadyTaken** [comment]
@AlexeyAB  yes i download it from here last Friday should i redownload it？

**Comment by AlexeyAB** [comment]
Download: https://github.com/AlexeyAB/darknet/archive/master.zip

>yes i download it from here last Friday should i redownload it？

You are using a Darknet version over 7 months old: https://github.com/AlexeyAB/darknet/blame/05dee78fa3c41d92eb322d8d57fb065ddebc00b4/src/parser.c#L2109

![image](https://user-images.githubusercontent.com/4096485/90519795-29610680-e171-11ea-9aa1-0ba45fd6700e.png)

**Comment by WellAlreadyTaken** [comment]
@AlexeyAB  well cool i get it thank you very much!!!
