### ISSUE TITLE
I used darknet on TX2, and the predicted image speed was very slow and FPS only have 0.3. (GPU)who can help me！

### ISSUE THREAD

**Issue by alexis-pepe** [AlexeyAB/darknet#6512]
Here is my screenshots

./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg
 CUDA-version: 8000 (8050), cuDNN: 5.1.10, GPU count: 1
 OpenCV version: 3.3.0
 0 : compute_capability = 620, cudnn_half = 0, GPU: GP10B
net.optimized_memory = 0
mini_batch = 1, batch = 1, time_steps = 1, train = 0
   layer   filters  size/strd(dil)      input                output
   0 conv     32       3 x 3/ 1    416 x 416 x   3 ->  416 x 416 x  32 0.299 BF
```
[yolo] params: iou loss: mse (2), iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
Total BFLOPS 65.879 
avg_outputs = 532444 
 Allocate additional workspace_size = 33.55 MB 
Loading weights from ./yolov3.weights...
 seen 64, trained: 32013 K-images (500 Kilo-batches_64) 
Done! Loaded 107 layers from weights-file 
 Detection layer: 82 - type = 28 
 Detection layer: 94 - type = 28 
 Detection layer: 106 - type = 28 
./data/dog.jpg: Predicted in 1130.161000 milli-seconds.
bicycle: 99%
dog: 100%
truck: 93%
`````````````````````````````````

Hello, I run on TX2 yolov3 encountered some problems, only 0.3 FPS, test an image for about 2 seconds. when yolo is worked ,GPU-Util is 99%. what I use is jetpack3.0, cuda8.0.64, cudnn5.1.10, opencv3.3.0, I opened the maximum power and the right to edit the makefile, when I use the yolov3 - tiny, only 3 FPS, cfg in width = 416 and hight = 416, such a low FPS cannot achieve the requirements of my experiment, is that my cuda or cudnn version is too low, or do I have something incorrectly configured? My camera is kinect v1

Please help me @AlexeyAB

**Comment by alexis-pepe** [comment]
I used darknet in ubuntu16.04 and ROS environment, I need to detect in real time, I've seen others with TX2 and yolov3-Tiny get 20FPs, but I only have 3FPs.

**Comment by Shame-fight** [comment]
> Here is my screenshots
> 
> ./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg
> CUDA-version: 8000 (8050), cuDNN: 5.1.10, GPU count: 1
> OpenCV version: 3.3.0
> 0 : compute_capability = 620, cudnn_half = 0, GPU: GP10B
> net.optimized_memory = 0
> mini_batch = 1, batch = 1, time_steps = 1, train = 0
> layer filters size/strd(dil) input output
> 0 conv 32 3 x 3/ 1 416 x 416 x 3 -> 416 x 416 x 32 0.299 BF
> 
> ```
> [yolo] params: iou loss: mse (2), iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
> Total BFLOPS 65.879 
> avg_outputs = 532444 
>  Allocate additional workspace_size = 33.55 MB 
> Loading weights from ./yolov3.weights...
>  seen 64, trained: 32013 K-images (500 Kilo-batches_64) 
> Done! Loaded 107 layers from weights-file 
>  Detection layer: 82 - type = 28 
>  Detection layer: 94 - type = 28 
>  Detection layer: 106 - type = 28 
> ./data/dog.jpg: Predicted in 1130.161000 milli-seconds.
> bicycle: 99%
> dog: 100%
> truck: 93%
> ```
> 
> Hello, I run on TX2 yolov3 encountered some problems, only 0.3 FPS, test an image for about 2 seconds. when yolo is worked ,GPU-Util is 99%. what I use is jetpack3.0, cuda8.0.64, cudnn5.1.10, opencv3.3.0, I opened the maximum power and the right to edit the makefile, when I use the yolov3 - tiny, only 3 FPS, cfg in width = 416 and hight = 416, such a low FPS cannot achieve the requirements of my experiment, is that my cuda or cudnn version is too low, or do I have something incorrectly configured? My camera is kinect v1
> 
> Please help me @AlexeyAB

yolov3 runs about 3-4 frames/s on tx2, and v4 should have a similar running speed. The frame rate cannot be seen in a single picture. It is recommended that you check a video. If you have a high frame rate requirement, it is recommended that you use opencv completely , The latest version of opencv already supports v4

**Comment by Shame-fight** [comment]
> I used darknet in ubuntu16.04 and ROS environment, I need to detect in real time, I've seen others with TX2 and yolov3-Tiny get 20FPs, but I only have 3FPs.

Which ros version do you use, I also want to run under ros.

**Comment by alexis-pepe** [comment]
> > I used darknet in ubuntu16.04 and ROS environment, I need to detect in real time, I've seen others with TX2 and yolov3-Tiny get 20FPs, but I only have 3FPs.
> 
> Which ros version do you use, I also want to run under ros.

My ros version is kinetic

**Comment by Shame-fight** [comment]
> > > I used darknet in ubuntu16.04 and ROS environment, I need to detect in real time, I've seen others with TX2 and yolov3-Tiny get 20FPs, but I only have 3FPs.
> > 
> > 
> > Which ros version do you use, I also want to run under ros.
> 
> My ros version is kinetic

I may have expressed my thoughts incorrectly, can you provide the darknet_ros link you used

**Comment by alexis-pepe** [comment]
> > > > I used darknet in ubuntu16.04 and ROS environment, I need to detect in real time, I've seen others with TX2 and yolov3-Tiny get 20FPs, but I only have 3FPs.
> > > 
> > > 
> > > Which ros version do you use, I also want to run under ros.
> > 
> > My ros version is kinetic
> 
> I may have expressed my thoughts incorrectly, can you provide the darknet_ros link you used

https://github.com/leggedrobotics/darknet_ros
