### ISSUE TITLE
Multiple detectors

### ISSUE THREAD

**Issue by JasonRuan5** [AlexeyAB/darknet#6514]
We hope to use multi detectors to combine/vote the results.  Is this doable?  We have created a simple test program as below.
` class Program {

        static void Main(string[] args) {
            var theCount = 200;
            var theDetector = new MyDetector();
            try {
                for (var it = 0; it < theCount; it++) {
                    theDetector.Create(it % 2);
                    //theDetector.detect(...);
                }
            } catch (Exception ex) {
                return;
            }
        }
    }

    class MyDetector {
        #region Yolo API
        [System.Runtime.InteropServices.DllImport("yolo_cpp_dll.dll")]
        static extern int init(string configurationFilename, string weightsFilename, int gpu);

        [System.Runtime.InteropServices.DllImport("yolo_cpp_dll.dll")]
        static extern int detect_size(out int height);

        //[System.Runtime.InteropServices.DllImport("yolo_cpp_dll.dll")]
        //static extern int detect_image(string strFilename, float fThreshold, ref bbox_t_container container);
        
        [System.Runtime.InteropServices.DllImport("yolo_cpp_dll.dll")]
        static extern int dispose();
        #endregion

        private static readonly string[] ConfigFiles = { @"E:\YoloTest\model1\Config1.cfg", @"E:\YoloTest\model2\Config2.cfg"};

        private static readonly string[] WeightFiles = { @"E:\YoloTest\model1\Weights1.weights", @"E:\YoloTest\model2\Weights2.weights"};

        public void Create(int aIndex) {
            dispose();
            init(ConfigFiles[aIndex], WeightFiles[aIndex], 0);
        }
    }` 
We got out of memory exception when loop to around 90.  We simply called detector.reset() in dispose().  What do we need to release?   What is the best way to use multi-detectors?  Thanks much!

**Comment by KyloEntro** [comment]
You can run around 90 detection at same time ?

**Comment by JasonRuan5** [comment]
No, we can detect around 90 bigTiff with two detectors before run out of memory in batch.  If there is a way handle the out of memory exception, we could restart the application and continue in batch as a back up solution.

**Comment by JasonRuan5** [comment]
Hi @AlexeyAB,

What do we need to do if we need to switch model?  Currently, we just call dispose() and init(const char *configurationFilename, const char *weightsFilename, int gpu). 

We have just tried with same set of images. If we use one detector to detect all images, then switch to next detector and detect all images ... and combine detection at end, they are fine.  It would be great if we could apply multi-detectors on image by image.  Any advice you have will be greatly appreciated.

**Comment by JasonRuan5** [comment]
Found the problem: our code was updated on May 1st (not most updated).  It is fine now after we updated the source code from https://github.com/AlexeyAB/darknet/commit/03eee3092f5084fd58b97cba8d1734db2f29022b
Thanks, @AlexeyAB!
