### ISSUE TITLE
How to run on a different machine?

### ISSUE THREAD

**Issue by LeeroyHannigan** [AlexeyAB/darknet#652]
Hi everyone, 
I have successfully compiled and run this on my own machine for GPU. A colleague of mine is hoping to show a demo to some people later in the week and I am wondering if there is a simple way to get my build working on his machine. Do I have to download opencv and all the other programs on his machine also?

I'm sorry if this question doesn't make much sense, I am a second year student and still very much learning. 
Thanks, 
Lee

**Comment by AlexeyAB** [comment]
Hi,
For detection on the Video - you should install OpenCV.
If you want to detect on the image, and high speed isn't required, then you can use Darknet without OpenCV/CUDA/cuDNN.

**Comment by AlexeyAB** [comment]
1. On Windows you can send compiled project and send link to the same OpenCV version
2. On Linux desirable to recompile Darknet

**Comment by LeeroyHannigan** [comment]
Brilliant, thanks for your help @AlexeyAB
