### ISSUE TITLE
Couldn't open file: obj.names

### ISSUE THREAD

**Issue by veer345** [AlexeyAB/darknet#653]
![screenshot from 2018-04-17 22-23-12](https://user-images.githubusercontent.com/14336679/38867045-793e6b96-4260-11e8-9bad-7763e24f861a.png)
i have placed obj.data and obj.names in data folder then why this error occurs Please help me

**Comment by AlexeyAB** [comment]
Hi, show content of the file `obj.data`

**Comment by veer345** [comment]
![screenshot from 2018-04-17 22-48-03](https://user-images.githubusercontent.com/14336679/38868018-54cac9a0-4263-11e8-910b-f1bf27f13b9e.png)
HELP ME OUT !!

**Comment by AlexeyAB** [comment]
Write `data/obj.names` instead of `obj.names` in the file obj.data

----

https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

Create file obj.data in the directory build\darknet\x64\data\, containing (where classes = number of objects):
```
classes= 2
train  = data/train.txt
valid  = data/test.txt
names = data/obj.names
backup = backup/
```

**Comment by AbanoubMamdouh** [comment]
Hello,
I have the same problem right now, training went fine, but now if I want to evaluate the map or the test data, it doesn't work. I specified the full directory for obj.names not the relative directory and it doesn't work. Why wouldn't it work for map and work for the training? I also added the line -map in the train command. Any help would be much appreciated!

**Comment by AlexeyAB** [comment]
@AbanoubMamdouh Show your full commands for Test and mAP.

**Comment by AbanoubMamdouh** [comment]
The training command: ./darknet detector train data/obj.data cfg/yolov3-tiny_obj1.cfg yolov3-tiny.conv.15 -map
The map command: ./darknet detector map data/obj.data cfg/yolov3-tiny_obj1.cfg backup/yolov3-tiny_obj1_5000.weights
The test command: ./darknet detector test data/obj.data cfg/yolov3-tiny_obj1.cfg backup/yolov3-tiny_obj1_5000.weights
The content of obj.data: 
classes= 8
train  = /home/abanoub/Desktop/train.txt
valid  = /home/abanoub/Desktop/train.txt
names = /home/abanoub/Desktop/daknet-master_last/data/obj.names
backup = backup/
Thank you very much for your help and swift response!

**Comment by AlexeyAB** [comment]
@AbanoubMamdouh 

Try to do
```
cd home/abanoub/Desktop/daknet-master_last/data/
sudo apt-get install dos2unix
dos2unix obj.data
dos2unix obj.names
```

----

`./darknet detector test data/obj.data cfg/yolov3-tiny_obj1.cfg backup/yolov3-tiny_obj1_5000.weights`

What error do you get using this command?

**Comment by AbanoubMamdouh** [comment]
@AlexeyAB 

> ./darknet detector test data/obj.data cfg/yolov3-tiny_obj1.cfg backup/yolov3-tiny_obj1_5000.weights What error do you get using this command?
It's the same error
`Couldn't open file: /home/abanoub/Desktop/daknet-master_last/data/obj.names`
Should I run the map and test commands again after dos2unix?

**Comment by AlexeyAB** [comment]
@AbanoubMamdouh 

* show me the full path to the `./darknet` 

* Show screenshot of output of these commands:
```
cat data/obj.data
cat /home/abanoub/Desktop/daknet-master_last/data/obj.names
ls -l /home/abanoub/Desktop/daknet-master_last/data/obj.names
```

* run this command:
`./darknet detector test /home/abanoub/Desktop/daknet-master_last/obj.data cfg/yolov3-tiny_obj1.cfg backup/yolov3-tiny_obj1_5000.weights`

**Comment by AlexeyAB** [comment]
@AbanoubMamdouh 

Look at this image - there is incorrect path:

![darknet](https://user-images.githubusercontent.com/38405613/50386050-503f0f00-06e8-11e9-88b8-87d828118478.png)

you should use `data/obj.names` instead `obj.names`

**Comment by AbanoubMamdouh** [comment]
Added the path and same error again
![update](https://user-images.githubusercontent.com/38405613/50386354-48359e00-06ed-11e9-91ea-f0da210591bb.png)

**Comment by AbanoubMamdouh** [comment]
The power of a letter... Thanks man!
