### ISSUE TITLE
Object Detection vs Instance Segmentation

### ISSUE THREAD

**Issue by OAT7963** [AlexeyAB/darknet#6537]
I would like to find out whether it is better to use instance segmentation or object detection to classify vehicles and count them, in the case of traffic congestion. 

From my experience, traffic congestion has a lot of occlusion for bounding box to be accurate, it may classify a car as a truck, and a truck as a car.  I have a relatively large datasets, approx 8000 - 10000 images, in my opinion it may be better to just use object detection as it will be easier to manage as the dataset gets larger. However, If anyone can give some input, that would be greatly appreciated.

Thanks  

Image example: 
![image](https://user-images.githubusercontent.com/58838171/91002533-83dee480-e601-11ea-85a1-ea8d11c12f49.png)

**Comment by AlexeyAB** [comment]
@OAT7963 Hi,

1. For counting object it is enough to use Object detection. Some SOTA Instance segmentation approaches (like YOLACT++, Poly-YOLO) uses YOLO Object detection, and then just refine shape of object, so instance segmentation doesn't count objects better the object detector.


2. If there are very much objects, then try to use yolov4.cfg with higher resolution `width=608 height=608` or `width=832 height=832`

3. If there are small objects try to use https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

> for training for small objects (smaller than 16x16 after the image is resized to 416x416) - set layers = 23 instead of https://github.com/AlexeyAB/darknet/blob/6f718c257815a984253346bba8fb7aa756c55090/cfg/yolov4.cfg#L895
> 
> set stride=4 instead of https://github.com/AlexeyAB/darknet/blob/6f718c257815a984253346bba8fb7aa756c55090/cfg/yolov4.cfg#L892
> set stride=4 instead of https://github.com/AlexeyAB/darknet/blob/6f718c257815a984253346bba8fb7aa756c55090/cfg/yolov4.cfg#L989

4. If you will recalculate anchors, then set the most of `masks=` to the `[yolo]` layer with the highest resolution.

5. Use post-processing to count only the number of intersections of line in the bottom half of the image.

**Comment by OAT7963** [comment]
Hi @AlexeyAB, 

I appreciate the swift and informative reply.  

Thanks
