### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_70' Makefile:138: recipe for target 'obj/convolutional_kernels.o' failed

### ISSUE THREAD

**Issue by spinoza1791** [AlexeyAB/darknet#655]
Makefile fails to compile on AWS Ubuntu 16.04 instance with V100

nvcc fatal   : Unsupported gpu architecture 'compute_70'
Makefile:138: recipe for target 'obj/convolutional_kernels.o' failed

Makefile:
GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=0
AVX=0
OPENMP=0
LIBSO=0
DEBUG=0

ARCH= -gencode arch=compute_70,code=[sm_70,compute_70]

**Comment by spinoza1791** [comment]
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17

nvidia-smi
Tue Apr 17 14:32:51 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   42C    P0    37W / 300W |      0MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by AlexeyAB** [comment]
You have chosen the wrong Amazon Machine Images (AMI) with old CUDA version.

Use this AMI ID: Deep Learning Base AMI (Ubuntu) Version 3.0 (ami-38c87440)

> Deep Learning base AMI with NVidia drivers like CUDA 8 and 9, CuDNN 6 and 7, CuBLAS 8 and 9, NCCL and more
