### ISSUE TITLE
Why are there only three parameters in the BN layer?

### ISSUE THREAD

**Issue by Lowell-IC** [AlexeyAB/darknet#6551]
There are three parameters in BN layer: scales, rolling_mean, rolling_variance. When we use the network to inference, how to use the three parameters to caculate? In the first picture, we just save three parameters. But in the second one, we have four parameters., which is mean variance γ and β. Is there someone who can help me to understand this three parameters? 
![1598416738(1)](https://user-images.githubusercontent.com/63527482/91256156-2d0c1300-e799-11ea-80e7-5ca7bf3ece02.png)
![BN](https://user-images.githubusercontent.com/63527482/91256159-2ed5d680-e799-11ea-9292-66f36aeb0440.jpg)

**Comment by Lowell-IC** [comment]
I just want to know how to use this three parameters in practice. Given the input x, how to caculate the output y.

**Comment by AlexeyAB** [comment]
> There are three parameters in BN layer: scales, rolling_mean, rolling_variance. 

Because 4th param `shift` (bias) is already in the Convolutional layer (in any case).

**Comment by Lowell-IC** [comment]
> > There are three parameters in BN layer: scales, rolling_mean, rolling_variance.
> 
> Because 4th param `shift` (bias) is already in the Convolutional layer (in any case).

OK. I got it. Thanks a lot.
