### ISSUE TITLE
yolov4.conv.137 dataset

### ISSUE THREAD

**Issue by aryu99** [AlexeyAB/darknet#6561]
I wanted to know that the pre-trained weights yolov4.conv.137 that are used for training a custom dataset on YOLOv4, was originally trained on which dataset? MS COCO or ImageNet or some other dataset?

Any help would be appreciated! Thanks :)

**Comment by YCmove** [comment]
`yolov4.conv.137` was pre-trained on MS COCO dataset, [check this issue.](https://github.com/AlexeyAB/darknet/issues/5804)

**Comment by aryu99** [comment]
@YCmove Got it, thank you!
