### ISSUE TITLE
About resize method implemented in this repo

### ISSUE THREAD

**Issue by mariojy10** [AlexeyAB/darknet#6563]
Hi @AlexeyAB  i want to ask a question. Im sorry if the question already been asked multiple times in the past. My question is if the network size is set to H = 800 and W = 800 then for  images  that have resolution 800 x 600 (or (H,W) <=800) , the images will not be resized anymore right ? This based on my understanding on the function ```resize_image()``` in src/image.c. Thankyou so much.

**Comment by stephanecharette** [comment]
@mariojy10 I'm only 80% certain of this answer, so perhaps Alexey will provide better details:

If the network is 800x800 and the image is 800x600, then the image will be stretched to match the 800x800.  Aspect ratio will not be maintained.

The images will *always* be stretched -- up or down as necessary -- to match the *exact* width and height of the neural network.

There is an old "letterbox" option that would maintain the aspect ratio and add black bars, but from my understanding it doesn't look like that option is used by many people anymore.

**Comment by mariojy10** [comment]
Ah i see that why there is a if condition im.w == w && im.h == h. So if i use letterbox option will be padded to match the network size of input the image as is (where (im.h,i,.w) <= network_size.
