### ISSUE TITLE
CUDA Status Error when calling cuda_free() (CUDA Error: Invalid argument) during inference with darknet.exe on Windows

### ISSUE THREAD

**Issue by KyryloAntoshyn** [AlexeyAB/darknet#6569]
Hi, Alexey, I have the issue during inference with darknet.exe.

**I am working on Windows.**

**Before installing darknet i made these steps:**
1. Installed Python 3.7 (3.7.9) and numpy (pip install numpy);
2. Installed CUDA toolkit 10.2.89;
3. Installed cuDNN 10.2 (8.0.2.39);
4. Copied cuDNN files from _/bin_, _/include_ and _/lib_ directories to _NVIDIA GPU Computing Toolkit/CUDA/v10.2_ appropriate folders;
5. Built and installed OpenCV (4.4.0) using CMake and Visual Studio 2019 with these flags: BUILD_opencv_world, OPENCV_EXTRA_MODULES_PATH (path to opencv-contrib here), WITH_CUDA, OPENCV_DNN_CUDA, ENABLE_FAST_MATH, WITH_CUDNN, CUDA_FAST_MATH, WITH_CUBLAS and CUDA_ARCH_BIN (6.1);
6. Successfully imported cv2 module in python and checked cv2 version after it in order to verify OpenCV installation.

**After it I made following steps:**
1. Cloned darknet;
2. Navigated to darknet\build\darknet\;
3. Copied cudnn64_8.dll, opencv_videoio_ffmpeg440_64.dll and opencv_world440.dll to x64 folder;
4. Changed CUDA props and targets to CUDA 10.2 from CUDA 10.1 in yolo_cpp_dll.vcxproj and darknet.vcxproj;
5. Built yolo_cpp_dll.sln;
6. In darknet.sln I changed these properties: added additional include directory for OpenCV include folder, removed CUDNN_HALF preprocessor definition, added opencv_world.lib path for linker;
7. Built darknet.sln, imported it in python and got following results: 
![image](https://user-images.githubusercontent.com/26432700/91641033-82ab1e80-ea2a-11ea-8a28-2fce6955d84b.png).

When I try to run detection on images or videos I receive following CUDA error:
![image](https://user-images.githubusercontent.com/26432700/91641069-bbe38e80-ea2a-11ea-9b76-a9ae037543a0.png)

All builds (OpenCV and darknet) were in Release configuration.

Screenshot with detailed information:
![image](https://user-images.githubusercontent.com/26432700/91643338-0cfb7e80-ea3b-11ea-9060-88e58a538e25.png)

Please, help to resolve it. Thanks in advance!

**Comment by yanrubi** [comment]
Seems like it's running by setting random=0 in yolo-obj.cfg

**Comment by KyryloAntoshyn** [comment]
> Seems like it's running by setting random=0 in yolo-obj.cfg
I didn't change YOLOv4 config file. Random equals to 1.

**Comment by procule** [comment]
https://github.com/AlexeyAB/darknet/issues/6555
Also, be sure you are using the latest CUDA driver (>r440)

**Comment by KyryloAntoshyn** [comment]
> #6555
> Also, be sure you are using the latest CUDA driver (>r440)

Here is my driver version:
![image](https://user-images.githubusercontent.com/26432700/91667427-48667d80-eb0d-11ea-8de6-3a7488fa3e67.png)

**Comment by KyryloAntoshyn** [comment]
Works perfectly (CUDA 10.1.243, cuDNN 7.6.5.32): https://github.com/AlexeyAB/darknet#how-to-compile-on-windows-using-cmake

**Comment by quelibrio** [comment]
resize=1.5 fixed the problem for me
