### ISSUE TITLE
YOLOV4 training - Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by tomlawrenceuk** [AlexeyAB/darknet#6570]
Hi,

When training using yolov4 tiny and yolov3, everything works fine but when using the exact same data set on yolov4 I get the following error when compiled with debug=1:

`corrupted size vs. prev_size
Aborted (core dumped)`

When debug=0 I just get the core bumped error.

I have tried a range of subdivisions between 16 and 64, I have tried a few batches between 1 and 64, GPU = 0 and 1, CUDA =0 and 1.

I have attached my .cfg file, which apart from the weights (yolov4.conv.137) is the only change made between my successful yolov4-tiny run and the unsuccessful yolov4 attempt:

[yolov4-broken.txt](https://github.com/AlexeyAB/darknet/files/5146016/yolov4-broken.txt)

Thanks

**Comment by AlexeyAB** [comment]
* Do you get this error with DEBUG=0?

* Show files bad.list and bad_label.list

* Show screenshot with such information
```
./darknet detector test cfg/coco.data cfg/yolov4.cfg yolov4.weights data/dog.jpg
 CUDA-version: 10000 (10000), cuDNN: 7.4.2, CUDNN_HALF=1, GPU count: 1
 CUDNN_HALF=1
 OpenCV version: 4.2.0
 0 : compute_capability = 750, cudnn_half = 1, GPU: GeForce RTX 2070
net.optimized_memory = 0
mini_batch = 1, batch = 8, time_steps = 1, train = 0
   layer   filters  size/strd(dil)      input                output
   0 conv     32       3 x 3/ 1    608 x 608 x   3 ->  608 x 608 x  32 0.639 BF
```

**Comment by tomlawrenceuk** [comment]
Hi Alexey, thanks for getting back to me. 

Problem solved after some sleep. 

mosaic=1 needs openCV. I will install openCV.

Model trains fine when mosaic=0 so that seems to isolates the problem.
