### ISSUE TITLE
During training, in the plot there´s a C: green line stuck in zero... What is it? Nowhere in documentation...

### ISSUE THREAD

**Issue by CdAB63** [AlexeyAB/darknet#6595]
During training, in the plot, there are two clear understandable lines (loss, mAP) but then there´s a 3rd line C that is plotted in green and seems to be stuck in zero. What is it? Couldn´t find anywhere in the docs. BTW mAP is low at this point because it´s just 10% of training... final result about 56% in a hard training set...

![Capturar](https://user-images.githubusercontent.com/28064711/91981693-9a6ef500-ecff-11ea-9197-f238edd57e4c.JPG)

```

**Comment by stephanecharette** [comment]
I think it is called "Constrastive loss".  See #6004 for details.

**Comment by CdAB63** [comment]
@stephanecharette Thank you.

**Comment by stephanecharette** [comment]
See issue #6290.
