### ISSUE TITLE
darknet.sln issue (load failed)

### ISSUE THREAD

**Issue by apiszcz** [AlexeyAB/darknet#66]
It may be the environment, however darknet_no_gpu.sln loads into Visual Studio correctly.
THe darknet.sln fails with (load failed) next to the darknet project in the solution explorer.

Any suggestions welcome.

**Comment by AlexeyAB** [comment]
@apiszcz It can be if your CUDA version is not 8.0 or if you have not CUDA.

**Comment by apiszcz** [comment]
CUDA 8.0 was installed, will reinstall and test.


Sent from Mail for Windows 10

**Comment by apiszcz** [comment]
The issue of installation is IMPORTANT and critical.
I had installed CUDA then Visual Studio and it does not work.
Installed Visual Studio then CUDA and it worked, CUDA displays it detected the compiler.
Tx
