### ISSUE TITLE
Modified tiny_yolo_v3.cfg to Tensorflow

### ISSUE THREAD

**Issue by GotG** [AlexeyAB/darknet#6660]
Hello

Does anyone have experience with converting modified yolov3 cfg to Tensorflow 1.x?
I am using a modified tiny_yolo_v3.cfg where i decreased the number of filters.
The model trains and detects well in Darknet. 
However, I need this model in TF 1.x. 
I modified the tiny-yolov3 model from mystic123 https://github.com/mystic123/tensorflow-yolo-v3 repo to match my cfg.
The conversion works well but the model detects less objects than in darknet (and the boxes are of wrong size).
Thanks!

**Comment by johnny-mueller** [comment]
I haven't made any experience with this myself but if the weights are correctly transferred or converted to the new tensorflow model the same results should be produced. 

I am not sure if you will find a concrete answer here. I think you should either check the conversion of the model again or create an issue in the Tensorflow repository - maybe someone there has already had the same problem and solved it.
