### ISSUE TITLE
How to visualize the val results?

### ISSUE THREAD

**Issue by wulongjian** [AlexeyAB/darknet#6686]
Hello, I am a new learner in yolo, I follow your tutorial and succeed to train coco dataset, finally I get a coco_results.json file.
but I don't konw how to use this json file. Is there a .sh or .py file to visualize the result?  Thanks a lot.

**Comment by nikola310** [comment]
Here's a python script I wrote to visualize results from darknet json file: https://github.com/nikola310/yolo-utils

I know this is old issue, but it might be useful for someone new.
