### ISSUE TITLE
Compilation failed on Linux server using make

### ISSUE THREAD

**Issue by CaiyuZhang** [AlexeyAB/darknet#6693]
Only set GPU =1 and CUDNN =1, cannot compile with error described below. I install cuda in other path(not in /usr/local/cuda), because I don't have `$: sudo`  right, but I change cuda and cudnn path in `Makefile`.

CUDA : 10.2

![image](https://user-images.githubusercontent.com/54944384/93663019-2cfceb80-fa97-11ea-97b8-bd0b9208b99d.png)

**Comment by stephanecharette** [comment]
Is this a mounted share?  Is it a DOS type drive, such as FAT* or NTFS that doesn't maintain Linux file permissions?  Because the "permission denied" makes it look like you don't have execute permission to run that command.
