### ISSUE TITLE
Darknet searches for wrong folder while training

### ISSUE THREAD

**Issue by jasrk11** [AlexeyAB/darknet#67]
Platform - Ubuntu 14.04

Folders in my custom training data have the word "images" in their names. During training, darknet searches by replacing "images" to "labels" in the folder name. This leads to "Couldn't open file" error.

For ex:
supposed folder name: "data/cat_images"
The folder darknet searches: "data/cat_labels"

**Comment by AlexeyAB** [comment]
@jasrk11 What command do you use for training?

**Comment by jasrk11** [comment]
command to train: `./darknet detector train cfg/yolo-cat.data cfg/yolo-cat.cfg darknet19_448.conv.23`

**Comment by AlexeyAB** [comment]
@jasrk11 Show content of `cfg/yolo-cat.data` and `train.txt` to which refered cfg/yolo-cat.data.

**Comment by jasrk11** [comment]
`cfg/yolo-cat.data`:
```
classes= 2
train  = data/baggage_data/cat_train.txt
valid  = data/baggage_data/cat_test.txt
names = data/baggage_data/cat.names
backup = backup/cat_8k/
```

`train.txt`
```
data/cat_data/cat_tags_3classes_part6/j6_d10_images/j6_d10_frame_5871.png
data/cat_data/cat_tags/j1_d125_frame_19694.png
data/cat_data/cat_tags_3classes_part2/Tag_out/j6_d10_images/j6_d10_frame_1106.png
data/cat_data/cat_tags_3classes_part2/j7_d45_images/j7_d45_frame_554.png
```

**Comment by AlexeyAB** [comment]
@jasrk11 Do you mean that insetd path `data/cat_data/cat_tags_classes_part6/j6_d10_images/j6_d10_frame_5871.png` Yolo try to get image by path `data/cat_data/cat_tags_classes_part6/j6_d10_labels/j6_d10_frame_5871.png`?

**Comment by AlexeyAB** [comment]
@jasrk11  

Just now you can comment this 2 lines: https://github.com/AlexeyAB/darknet/blob/a87abe8de58427f842b371c0169b4c41dc1cb6f1/src/data.c#L257

```
    find_replace(path, "images", "labels", labelpath);
    find_replace(labelpath, "JPEGImages", "labels", labelpath)
```

And may be I'll fix it in repo.

**Comment by jasrk11** [comment]
Didn't solve the problem though..

**Comment by AlexeyAB** [comment]
@jasrk11 

Did you try to comment all lines such as `find_replace(path, "images", "labels",` ... ?

* here: https://github.com/AlexeyAB/darknet/blob/da6258bd12e2c6da206cd81f1518ae5c695f740a/src/detector.c#L406

* also here: https://github.com/AlexeyAB/darknet/blob/da6258bd12e2c6da206cd81f1518ae5c695f740a/src/data.c#L257

* and here: https://github.com/AlexeyAB/darknet/blob/da6258bd12e2c6da206cd81f1518ae5c695f740a/src/data.c#L305

**Comment by jasrk11** [comment]
No man. I just went ahead by removing the word "images" from folder names.
