### ISSUE TITLE
Wrong classes between darknet and darknet.py

### ISSUE THREAD

**Issue by scaramouche88** [AlexeyAB/darknet#6713]
Hello,
I mark as bug even if it might not be. It might be a mistake on my side.

I have retrained on custom cls (9 total classes) and images (.tiff images)
When I test on a bunch of new images with `./darknet etc.` there is no problem.  I tested both the `map` (it works fine and it shows the mAP for all classes) and the `test` options.
When I test the same image with the python API, it seems that only one class (the first in the .names file) is used. Indeed it finds only object with this class and nothing else.

when I run darknet_images.py I have this:
`Loaded - names_list: voc_ALL_bgk_spe_all.names, classes = 1 
`
and not `classes = 9` as it should be. 

I wrote that is maybe not a bug since it happens with both yolov3 (old repo on which I made some dev)/old darknet.py and yolov4 with old weights/darknet_images.py

I've compiled with 
`GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=1
AVX=0
OPENMP=0
LIBSO=1
ZED_CAMERA=0
ZED_CAMERA_v2_8=0`

My names file is something like this:
`ALO`
`ANG`
`...`

Is there a bug or am I getting something wrong? in case, any suggestion?
Thanks in advance for the help/opinion/debug

**Comment by scaramouche88** [comment]
The problem seems to be relative to the python API. If i print the classes right after they are read from the METADATA there is only one class:
https://github.com/AlexeyAB/darknet/blob/fdb1841eb1699cf24a193787c2da7b2d9bd10070/darknet.py#L115-L118

btw my .names file is encoded in us-ascii, so it should not be the problem, right?

**Comment by scaramouche88** [comment]
Error found. 
Not a bug, but a stupid typo. 
Closing here.

**Comment by Goru1890** [comment]
Hi, I'm having the same issue. What was your error?

**Comment by Goru1890** [comment]
I just saw it
