### ISSUE TITLE
points to take into account when annotating

### ISSUE THREAD

**Issue by k00r** [AlexeyAB/darknet#672]
Hello,what are the important points i should keep in mind when annotating? Should the gaps between the object and the bounding box be minimized or the object being inside the bounding box is just enough? How strict should i be?

Thanks.

**Comment by AlexeyAB** [comment]
Hi, there is only one restriction - all objects should be labeled in the same way.
No other restrictions.

Yolo will detect with the same gap as you labeled.

**Comment by k00r** [comment]
Thank you very much :)
