### ISSUE TITLE
Too low usage of video card when training in process

### ISSUE THREAD

**Issue by Aleksey1555** [AlexeyAB/darknet#6725]
Hello.
In training process i see very low GPU percent usage - 10%.
Is it normal? Maybe there is some mistake in configuring yolov3?
I want to use all GPU power!!))

**Comment by lsd1994** [comment]
It is normal if you use 416 x 416. What FPS do you get?

**Comment by Aleksey1555** [comment]
where to get FPS?

**Comment by Aleksey1555** [comment]
FPS - this is for video!
I train darknet
