### ISSUE TITLE
CUDA Error: out of memory

### ISSUE THREAD

**Issue by WenTheProgrammer** [AlexeyAB/darknet#6726]
My graphics card is GeForce RTX 2060. I have 2770 images with resolution being 1920x1080 for training. I successfully trained a YOLOv4-CSP-SAM model with network size being 320 and subdivisions=32. I want to train another two models with network sizes being 640 and 960, however my graphics card doesn't have enough memory for that even with subdivisions=64. Is there anything I can do to make the training going?

**Comment by gsaltintas** [comment]
Changing random in cfg file to `random=0` helped others in the past. See #6416

**Comment by WenTheProgrammer** [comment]
It did work for network size 640
