### ISSUE TITLE
why does maP% do a sudden drop to zero?

### ISSUE THREAD

**Issue by stephanecharette** [AlexeyAB/darknet#6730]
I have a network that I've been using for about a year now.  Trained with YOLOv3-tiny.  Chart looks normal, mAP% increases as loss decreases.

Today I tried training that same network with YOLOv4-tiny instead.  But partway through training, the chart goes sour.  Looks like this:

![image](https://user-images.githubusercontent.com/5061352/94116773-4c31ab00-fe00-11ea-9cab-a01b59fc0499.png)

Any thoughts as to what makes the training do this drop to zero?

Network contains 374 images with 14838 labels.  Items I've changed at the start of the .cfg file:

    batch=64
    subdivisions=8
    width=1216
    height=896
    saturation=2.500000
    exposure=2.500000
    hue=0.500000
    max_batches=10000
    steps=8000,9000
    max_chart_loss=4.000000
    mixup=0
    mosaic=1

Then `filters` in the convolutional section before YOLO, and the classes in YOLO.

The training command I use is:

    ~/darknet/darknet detector -map -dont_show train ~/nn/mailboxes/mailboxes.data ~/nn/mailboxes/mailboxes.cfg

Training is done on a linux rig, and I can tell it is using the GPU:

```
stephane@loup ~> nvidia-smi 
Thu Sep 24 01:06:11 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.95.01    Driver Version: 440.95.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070    On   | 00000000:01:00.0 Off |                  N/A |
| 58%   67C    P2    83W / 175W |   7231MiB /  7981MiB |     47%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     19487      C   /home/stephane/darknet/darknet              7228MiB |
+-----------------------------------------------------------------------------+
```

**Comment by lsd1994** [comment]
I meet the same problem, reduce learning rate can solve,

**Comment by stephanecharette** [comment]
> I meet the same problem, reduce learning rate can solve,

Default learning rate for YOLOv4-tiny is 0.00261.
I lowered it to 0.00200, and the results do look better so far, thank you:

![image](https://user-images.githubusercontent.com/5061352/94352481-6c3cb680-001a-11eb-84b6-7363499472f4.png)
