### ISSUE TITLE
how to train a model on cropped car logos?

### ISSUE THREAD

**Issue by IbrahimBond** [AlexeyAB/darknet#6732]
If you have an issue with training - no-detections / Nan avg-loss / low accuracy:
    * read FAQ: https://github.com/AlexeyAB/darknet/wiki/FAQ---frequently-asked-questions
    * what command do you use?
   ./darknet detector train logo-config/trainer.data logo-config/yolov4-tiny.cfg yolov4-tiny.conv.29 

    * what dataset do you use?   
     Custom dataset of cropped car logos like the one below
![logo_6](https://user-images.githubusercontent.com/29629098/94132140-8a15ea00-fe67-11ea-9de6-59ff156b512e.jpg)

    * what Loss and mAP did you get?
    loss reached 

    * check your dataset - run training with flag `-show_imgs` i.e. `./darknet detector train ... -show_imgs` and look at the `aug_...jpg` images, do you see correct truth bounded boxes?

    * rename your cfg-file to txt-file and drag-n-drop (attach) to your message here
[logo.txt](https://github.com/AlexeyAB/darknet/files/5275198/logo.txt)

i have 20k images of cropped car logos similar to this one: ![logo_6](https://user-images.githubusercontent.com/29629098/94132140-8a15ea00-fe67-11ea-9de6-59ff156b512e.jpg)

each image has one class and the class consist of the whole image. i labeled all images with those bounds: ([class] 0.5 0.5 0.99 0.99) and trained on width and height of 128. calculated anchors gave anchors = 127, 127  127, 127  127, 127  127, 127  127, 127  127, 127. after the training was done the model could not make any detections. 

what is the correct way to train a model on such dataset?

thanks

**Comment by enhany** [comment]
IMHO, better to use some classification network, not yolo

**Comment by stephanecharette** [comment]
"Could not make any detections" ...on what?  On images of cars, or images of logos?

You *must* train the network with images similar to what you want to detect.  If your training images are logos that take up 100% of the image and are 128x128, then it will learn to detect logos that take up 100% of the image when the images are resized to 128x128.

If you want to detect logos on cars, then your images better be of *cars* where you have marked up the logos.

This was actually discussed earlier today on the Darknet/YOLO discord:  https://discord.gg/zSq8rtW

**Comment by IbrahimBond** [comment]
It could not make detections on images of logos that are 128x128 in shape and take up 100% of threimage. I dont want to detect logos on cars. Just want to detect the cropped logos type.

**Comment by stephanecharette** [comment]
Try this:

1. Fix your .cfg file, it has the wrong number of filters.
2. Use the default YOLOv4-tiny anchors for now until we can figure out what is going on.
3. Use this command:  ./darknet detector -map train logo-config/trainer.data logo-config/yolov4-tiny.cfg

If you don't have X, then also use `-dont_show` like this:

3. ./darknet detector -map -dont_show train logo-config/trainer.data logo-config/yolov4-tiny.cfg

**Comment by IbrahimBond** [comment]
1- in training i had the correct number of filters. 129 filter
2- i will train again and let you know.
3 - does it make sense to  lower number of anchors to one since the detection is 100% of the image?

**Comment by stephanecharette** [comment]
> 1- in training i had the correct number of filters. 129 filter

On line 212, you have filters=128, not 129.

**Comment by IbrahimBond** [comment]
> > 1- in training i had the correct number of filters. 129 filter
> 
> On line 212, you have filters=128, not 129.

yeah i had a typo in the txt file i attached.

**Comment by shubham-shahh** [comment]
> "Could not make any detections" ...on what? On images of cars, or images of logos?
> 
> You _must_ train the network with images similar to what you want to detect. If your training images are logos that take up 100% of the image and are 128x128, then it will learn to detect logos that take up 100% of the image when the images are resized to 128x128.
> 
> If you want to detect logos on cars, then your images better be of _cars_ where you have marked up the logos.
> 
> This was actually discussed earlier today on the Darknet/YOLO discord: https://discord.gg/zSq8rtW

Hello, Stephen, I am training YOLOv4 with image size ranging from 200x80 to 600(width)x150. what should be the height and width in the .cfg file? also, shall I provide the model with varied aspect ratio images or constant spect ratio images for better accuracy?
