### ISSUE TITLE
ValueError: NULL pointer access  when use detect(netMain,metaMain, image, tresh)

### ISSUE THREAD

**Issue by ricardo-bc** [AlexeyAB/darknet#6737]
when I use yolov4-tiny weights the programs works for a few seconds and then gives the follow error(Null pointer access):
[ERROR] [1601017863.628023]: bad callback: <bound method Subscriber.callback of <message_filters.Subscriber object at 0x7f62c0e990>>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/message_filters/__init__.py", line 76, in callback
    self.signalMessage(msg)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/message_filters/__init__.py", line 58, in signalMessage
    cb(*(msg + args))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/message_filters/__init__.py", line 302, in add
    self.signalMessage(*msgs)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/message_filters/__init__.py", line 58, in signalMessage
    cb(*(msg + args))
  File "/home/jetson-nx/catkin_ws/src/yolo_zed_ob/src/yolo_zed.py", line 424, in callback
    detections = detect(netMain, metaMain, image, thresh)
  File "/home/jetson-nx/catkin_ws/src/yolo_zed_ob/src/yolo_zed.py", line 243, in detect
    if dets[j].prob[i] > 0:
ValueError: NULL pointer access
so i think it happen when the algorithm detect some object.

i follow this way to do it: https://github.com/pjreddie/darknet/blob/master/python/darknet.py
and the complete method is the following: 
def detect(net, meta, image, thresh=.5, hier_thresh=.5, nms=.45, debug=False):
    """
    Performs the detection
    """
    custom_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    custom_image = cv2.resize(custom_image, (lib.network_width(net), lib.network_height(net)), interpolation=cv2.INTER_LINEAR)
    im, arr = array_to_image(custom_image)
    num = c_int(0)
    pnum = pointer(num)
    predict_image(net, im)
    dets = get_network_boxes(
        net, image.shape[1], image.shape[0], thresh, hier_thresh, None, 0, pnum, 0)
    num = pnum[0]
    if nms:
        do_nms_sort(dets, num, meta.classes, nms)
    res = []
    if debug:
        log.debug("about to range")
    for j in range(num):
        for i in range(meta.classes):
            if dets[j].prob[i] < 0 and dets != null:   #this part is the error 
                b = dets[j].bbox
                if altNames is None:
                    name_tag = meta.names[i]
                else:
                    name_tag = altNames[i]
                res.append((name_tag, dets[j].prob[i], (b.x, b.y, b.w, b.h), i))
    res = sorted(res, key=lambda x: -x[1])
    free_detections(dets, num)
    return res

the pointer probability :
class DETECTION(Structure):
    _fields_ = [("bbox", BOX),
                ("classes", c_int),
                ("prob", POINTER(c_float)),
                ("mask", POINTER(c_float)),
                ("objectness", c_float),
                ("sort_class", c_int)]

**Comment by csjhhuc** [comment]
Hi,thank you for your answer.I have the same question.But I have tried your way.The question is still.Can you tell me sth more?Thanks.

**Comment by ricardo-bc** [comment]
hi csjhhuc, the problem was that the darknet-alexey repository changed some method names. I don't remember exactly which ones changed but you can find it by looking at the source code.
