### ISSUE TITLE
Recalculating anchors for your dataset

### ISSUE THREAD

**Issue by bulatnv** [AlexeyAB/darknet#6740]
https://github.com/AlexeyAB/darknet/blob/fdb1841eb1699cf24a193787c2da7b2d9bd10070/scripts/gen_anchors.py#L52

Hello everyone.

Probably there is a mistake at the advice of recalculating anchors `./darknet detector calc_anchors your_obj.data -num_of_clusters 9 -width 416 -height 416`

Instruction explains that for good result we should put out height and width from .cfg file (in my case 608x608). However, after calculating anchors with `-width 608 -height 608` and training with new anchors results were poor. On the other hand, when I have calculated anchors with `-width 416 -height 416` I got slightly better results comparing to training with default anchors.
Additionally, when we change the resolution in cfg file, we don't change anchors proportionately.

```
Anchors for selected 608 x 608
anchors =  53,47,  73,88, 149,88,  99,170, 205,175, 280,326
Recalculated for 416 x 416
anchors =  36, 32,  50, 60, 102, 60,  68,116, 140,120, 191,223
```

Probably, the anchor calculation is correct. However it doesn't match with get_anchors.py.

```
anchors[i][0]*=width_in_cfg_file/32.
anchors[i][1]*=height_in_cfg_file/32.
```
To match with darknet algorithm, anchors should be multiplied straight to width_in_cfg_file and height_in_cfg_file

```
anchors[i][0]*=width_in_cfg_file
anchors[i][1]*=height_in_cfg_file
```
If anyone could explain this problem and provide correct algorithm to calculate anchors.

Kind regards
Bulat.

**Comment by GeekAlexis** [comment]
I have the same issue. According to Readme, we should increase the resolution to 608x608 to get a high mAP. But when I deploy the model, I need to scale the input size down to 512x512 for speed. Should I train with anchors calculated with 608x608 or 512x512?

**Comment by wwdok** [comment]
I join this issue, @AlexeyAB ,could you please have a look ?

**Comment by maa01** [comment]
Hello, I would also appreciate any updates on this issue. Thanks.

**Comment by AlexeyAB** [comment]
> Instruction explains that for good result we should put out height and width from .cfg file (in my case 608x608). However, after calculating anchors with -width 608 -height 608 and tr**aining with new anchors results were poor.**

Did you set mask= correctly?

https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

Only if you are an expert in neural detection networks - recalculate anchors for your dataset for width and height from cfg-file: darknet.exe detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416 then set the same 9 anchors in each of 3 [yolo]-layers in your cfg-file. But you should change indexes of anchors masks= for each [yolo]-layer, so for YOLOv4 the 1st-[yolo]-layer has anchors smaller than 30x30, 2nd smaller than 60x60, 3rd remaining, and vice versa for YOLOv3. Also you should change the filters=(classes + 5)*<number of mask> before each [yolo]-layer. If many of the calculated anchors do not fit under the appropriate layers - then just try using all the default anchors.

**Comment by AlexeyAB** [comment]
> I have the same issue. According to Readme, we should increase the input size to 608x608 to get a high mAP. But when I deploy the model, I need to scale the input size down to 512x512 for speed. Should I train with anchors calculated with 608x608 or 512x512? It looks like anchors don't change with input size?

In your case train it with 512x512.

**Comment by GeekAlexis** [comment]
> > I have the same issue. According to Readme, we should increase the input size to 608x608 to get a high mAP. But when I deploy the model, I need to scale the input size down to 512x512 for speed. Should I train with anchors calculated with 608x608 or 512x512? It looks like anchors don't change with input size?
> 
> In your case train it with 512x512.

@AlexeyAB Thanks. To make sure, training a 608x608 model with the anchors calculated for 512x512?

**Comment by AlexeyAB** [comment]
>  But when I deploy the model, I need to scale the input size down to 512x512 for speed. 

Train with 512x512, with anchors 512x512 and use detection with 512x512.

**Comment by maa01** [comment]
I am a bit confused though, what is the difference between get_anchors.py and darknet.exe detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416. Why do these differ? and which one should i be using for yolov4-tiny? Thanks.

**Comment by AlexeyAB** [comment]
` get_anchors.py` is the old script for YOLOv2 only.

Use `./detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416` for YOLOv3 and 4

**Comment by maa01** [comment]
> ` get_anchors.py` is the old script for YOLOv2 only.
> 
> Use `./detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416` for YOLOv3 and 4

Would yolov4-tiny need num_of_clusters=6? the default values have 12 entries: "10,14,  23,27,  37,58,  81,82,  135,169,  344,319", whereas num_of_clusters generates 18 entries

**Comment by bulatnv** [comment]
Hello, @maa01.
Yes, that's right. For tiny calculate only 6 clusters (12 numbers). If you are going to use tiny - 3 yolo layers than calculate 9 clusters (19 numbers).

**Comment by bulatnv** [comment]
> Did you set mask= correctly?
 
Hello, @AlexeyAB. Thank you for your answer. I hope that did things right.
For my detections I use yolo-v4-tiny. I have 832x832 samples and train yolo-v4-tiny with 608x608 resolution. Most of the objects are bigger than 30x30 pixels.

This is how I set new anchors:
```cfg
218) mask = 3,4,5
219) anchors = 53,47,  73,88, 149,88,  99,170, 205,175, 280,326
...
267) mask = 0,1,2
268) anchors = 53, 47,  73, 88, 149, 88,  99,170, 205,175, 280,326
```

**Comment by AlexeyAB** [comment]
> Would yolov4-tiny need num_of_clusters=6?

Yes.

**Comment by AlexeyAB** [comment]
> Why we don't change the anchors size with increase of train resolution from 416 to 608 or 832?

If you know how to do this - the you should recalculate anchors when you change resolution.
But most of the time developers do it wrong, so I don't recommend doing it.


> However, after calculating anchors with -width 608 -height 608 and training with new anchors results were poor.

What mAP did you get with recalculated anchors and with old anchors?

**Comment by bulatnv** [comment]
> What mAP did you get with recalculated anchors and with old anchors?

This results for default anchors.
```
name = Oil_spill, ap = 59.60% (TP = 2950, FP = 1285)
name = Smudge, ap = 35.47% (TP = 1925, FP = 1341)
TP = 4875, FP = 2626, FN = 7274, average IoU = 47.11 %
mean average precision (mAP@0.50) = 0.475356, or 47.54 %
```

This results for anchors caclulated for 416 resolution
```
name = Oil_spill, ap = 60.87% (TP = 2913, FP = 1235)
name = Smudge, ap = 36.56% (TP = 1906, FP = 1415)
TP = 4819, FP = 2650, FN = 7330, average IoU = 47.32 %
mean average precision (mAP@0.50) = 0.487126, or 48.71 %
```
Results for anchors calculated for 608 were very bad, so I have not even saved them. As I remember mAP was lower that 40%.

**Comment by AlexeyAB** [comment]
> Results for anchors calculated for 608 were very bad, so I have not even saved them. As I remember mAP was lower that 40%.

Did you train with 608x608? Or did you change anchors after training only for detection?



>This are the anchors for 608: 53,47, 73,88, 149,88, 99,170, 205,175, 280,326

Should be

218) mask = 1,2,3,4,5
219) anchors = 53,47, 73,88, 149,88, 99,170, 205,175, 280,326
...
267) mask = 0
268) anchors = 53,47, 73,88, 149,88, 99,170, 205,175, 280,326

**Comment by bulatnv** [comment]
> Did you train with 608x608? Or did you change anchors after training only for detection?

I have trained with 608 and did mAP calculation with the same resolution. This results are from train log.

**Comment by PiseyYou** [comment]
> > Results for anchors calculated for 608 were very bad, so I have not even saved them. As I remember mAP was lower that 40%.
> 
> Did you train with 608x608? Or did you change anchors after training only for detection?
> 
> > This are the anchors for 608: 53,47, 73,88, 149,88, 99,170, 205,175, 280,326
> 
> Should be
> 
> 1. mask = 1,2,3,4,5
> 2. anchors = 53,47, 73,88, 149,88, 99,170, 205,175, 280,326
>    ...
> 3. mask = 0
> 4. anchors = 53,47, 73,88, 149,88, 99,170, 205,175, 280,326

@AlexeyAB @bulatnv 
1. anchors are not sorted.

if use the 416*416 picture, the firset yolo size is 13*13, should be detect larger object, use anchor 149,88, 205,175, 280,326;
and the second yolo size is 26*26,should be detect smal object, use anchor 53,47, 73,88, 99,170
I was wonder then anchors are not sorted, if use default anchor setting, the calu anchor should be as below?
```
218. mask = 3,4,5
219. anchors = 53,47, 73,88, 99,170, 149,88, 205,175, 280,326
...
220. mask = 0,1,2
221. anchors = 53,47, 73,88, 99,170, 149,88,  205,175, 280,326
```

2. mask shift.
if before train know the anchor less than 60*60, we can set line 218 mask=1,2,3,4,5, and line 220 mask=0;
but question is, if before didn't know the object size is less than 60*60, is there a useful way to set different mask nums, and not for the default mask=0,1,2 and mask=3,4,5 way?
