### ISSUE TITLE
Cudnn 8 possible improvement

### ISSUE THREAD

**Issue by mattangus** [AlexeyAB/darknet#6763]
I saw this commit that says [cudnn 8 is slow](https://forums.developer.nvidia.com/t/jetpack-4-4-l4t-r32-4-3-issue-with-darknet-yolo/141191/5). Before I found that commit I stumbled across this: https://forums.developer.nvidia.com/t/jetpack-4-4-l4t-r32-4-3-issue-with-darknet-yolo/141191/5

Which references a patch:

https://raw.githubusercontent.com/AastaNV/JEP/master/script/topics/0001-fix-for-cudnn_v8.patch

I haven't tested it but it might be helpfull for improving performance.

**Comment by AlexeyAB** [comment]
> Which references a patch:
> 
> https://raw.githubusercontent.com/AastaNV/JEP/master/script/topics/0001-fix-for-cudnn_v8.patch

It seems that this patch just fixes compilation for old Darknet repo, but it doesn't use cuDNN 8.0 in a high performance way.

Current implementation should be better than this patch.

**Comment by mattangus** [comment]
Yeah that's why I closed it. I replaced the current implementation with this patch and it was very slow to initialize. Roughly the same runtime though.

It seems that the performance issues are actually in cudnn (from the release notes) and not how it is being used here. I just downgraded for now, hopefully they get fixed soon.
