### ISSUE TITLE
CHECK_CUDA(cudaSetDeviceFlags Causing CUDA out of memory error

### ISSUE THREAD

**Issue by zgbkdlm** [AlexeyAB/darknet#6786]
OS: Ubuntu 18.04

Bullt using this Makefile
```
GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=0
AVX=0
OPENMP=0
LIBSO=0
ZED_CAMERA=0
ZED_CAMERA_v2_8=0
```

However, when I start to train using `./darknet detector train data/mydata.data cfg/yolov4.cfg yolov4.conv.137 -dont_show -map`. It throws the following error:

```
CUDA status Error: file: ./src/darknet.c : () : line: 470 : build time: Oct  3 2020 - 11:21:14 

 CUDA Error: out of memory
CUDA Error: out of memory: No such file or directory
darknet: ./src/utils.c:326: error: Assertion `0' failed.
zsh: abort
```

Then I wen to the `line 470` of `darknet.c`. it is `CHECK_CUDA(cudaSetDeviceFlags(cudaDeviceScheduleBlockingSync));`

For some reasons, this code gives a CUDA out of memory error

**Comment by stephanecharette** [comment]
What config are you using, what size is the network, and how much ram does your GPU have?

https://www.ccoderun.ca/programming/2020-09-25_Darknet_FAQ/#cuda_out_of_memory
