### ISSUE TITLE
Error while calculating IOU & Recall for PNG images

### ISSUE THREAD

**Issue by jasrk11** [AlexeyAB/darknet#68]
Tried running `darknet.exe detector recall data/obj.data yolo-obj.cfg backup\yolo-obj_7000.weights`
Gave the following error:
`Couldn't open file: data/voc.2007.test`

I'm not using the VOC data & haven't referenced it anywhere in my data/cfg files. I'm not sure why it is looking up for VOC test dataset. I have my own custom validation dataset and have referenced it in the .data file:
`valid  = data/cat_data/test.txt`

**Comment by AlexeyAB** [comment]
I fixed it.

**Comment by jasrk11** [comment]
I'm getting an error while making it
`./src/detector.c:336:13: error: incompatible type for argument 6 of ‘get_region_boxes’
             get_region_boxes(l, w, h, thresh, probs, boxes, 0, map);
             ^
compilation terminated due to -Wfatal-errors.
`

**Comment by AlexeyAB** [comment]
What C++ compiler do you use?

**Comment by jasrk11** [comment]
I'm using version 4.8. Also, I have cloned the darknet repo from pjreddie due to Ubuntu & Windows compatibility issues. To test your fixes, I've copied the contents of src/detector.c to the current repo without changing anything else.

**Comment by jasrk11** [comment]
I've made changes similar to yours at [Line 372](https://github.com/AlexeyAB/darknet/blob/master/src/detector.c#L372). 

After doing that & running the code, the code is isn't giving outputs as expected. IOU and Recall are nan for all images.
Output:
```
 1807     0     0	RPs/Img: 1.72	IOU: -nan%	Recall:-nan%
 1808     0     0	RPs/Img: 1.72	IOU: -nan%	Recall:-nan%
 1809     0     0	RPs/Img: 1.72	IOU: -nan%	Recall:-nan%
 1810     0     0	RPs/Img: 1.72	IOU: -nan%	Recall:-nan%
 1811     0     0	RPs/Img: 1.72	IOU: -nan%	Recall:-nan%
 1812     0     0	RPs/Img: 1.72	IOU: -nan%	Recall:-nan%
```

**Comment by AlexeyAB** [comment]
> To test your fixes, I've copied the contents of src/detector.c to the current repo without changing anything else.

This fork is only for Windows, it can't work on Linux

**Comment by jasrk11** [comment]
The fork for Windows also gives the same output when running the code: `darknet.exe detector recall data/obj.data yolo-obj.cfg backup\yolo-obj_7000.weights`

```
 1807     0     0	RPs/Img: 1.72	IOU: -nan%	Recall:-nan%
 1808     0     0	RPs/Img: 1.72	IOU: -nan%	Recall:-nan%
 1809     0     0	RPs/Img: 1.72	IOU: -nan%	Recall:-nan%
 1810     0     0	RPs/Img: 1.72	IOU: -nan%	Recall:-nan%
 1811     0     0	RPs/Img: 1.72	IOU: -nan%	Recall:-nan%
 1812     0     0	RPs/Img: 1.72	IOU: -nan%	Recall:-nan%
```

**Comment by AlexeyAB** [comment]
Did you add this 3 line? 
```
	list *options = read_data_cfg(datacfg);
	char *valid_images = option_find_str(options, "valid", "data/train.txt");
        list *plist = get_paths(valid_images);
```

Try to set this value: https://github.com/AlexeyAB/darknet/blob/master/src/detector.c#L387
to: `float thresh = .001;`

**Comment by jasrk11** [comment]
Yes, I've added the 3 lines and changed data/train.txt in `char *valid_images = option_find_str(options, "valid", "data/train.txt"); ` to the relative path to my validation dataset.

I've also tried setting thresh value to as low as .0001

Nothing seems to work.. seems like somewhere the division is going wrong.

**Comment by AlexeyAB** [comment]
@jasrk11 

It's strange, I just run this command: `darknet.exe detector recall data/obj.data yolo-obj.cfg yolo-obj_8000.weights -i 0`

And I get good result:

![image](https://cloud.githubusercontent.com/assets/4096485/25431473/5d4dbcec-2a89-11e7-809d-2a0212482b03.png)

**Comment by jasrk11** [comment]
My training dataset contains png files which the detector.c code doesn't account for. I've fixed it and created a PR

**Comment by AlexeyAB** [comment]
@jasrk11 I merged it. Thank you!

**Comment by JasOlean** [comment]
when I run this command 
./darknet detector map data/obj.data yolo-obj.cfg backup\yolo-obj_8000.weights, I do not get anythin results for mAP, IOU, Recall. How can I do?

**Comment by AlexeyAB** [comment]
@JasOlean 
* Can you show screenshot of output?
* Did you set `valid=train.txt` in the `obj.data`?
