### ISSUE TITLE
Training yolov4 to understand orientation of objects

### ISSUE THREAD

**Issue by marvision-ai** [AlexeyAB/darknet#6807]
How would you annotate and configure yolo to understand orientation of objects?

Picture for instance: 
![image](https://user-images.githubusercontent.com/7716574/95593002-3682cf00-0a17-11eb-8d3b-f2faf511fc43.png)

**Comment by stephanecharette** [comment]
You wouldn't.  What you'll get from Darknet is rectangular areas (a single x, y, width, and height) for each object.  You'd need to do some OpenCV work, or you'd need a different framework that does segmentation.

**Comment by marvision-ai** [comment]
@stephanecharette  I figured... I was just curious if anyone had done it. thanks for the feedback!
