### ISSUE TITLE
which .c files are used when detection command is used and where is the main() function?

### ISSUE THREAD

**Issue by shubham-shahh** [AlexeyAB/darknet#6822]
Hi @AlexeyAB  
I am using this command

`./darknet detector test ./cfg/coco.data ./cfg/yolov4.cfg ./yolov4.weights data/dog.jpg -i 0 -thresh 0.25`

I want to know what all .c files are called during this command and where is the main function? I want to loop through all the images in a folder and get their class id. I don't want the program to stop and should wait for more images.

**Comment by stephanecharette** [comment]
Shubham, I already answered this for you in the discord earlier this morning.  Look at the readme, there are examples of how to do this.  In addition, like I wrote, you can also use DarkHelp which has a command-line option.

**Comment by shubham-shahh** [comment]
I wasn't able to find it in the readme sir

**Comment by stephanecharette** [comment]
For example, from the readme:

![image](https://user-images.githubusercontent.com/5061352/95773413-47c81780-0c73-11eb-8799-04b02c29f480.png)

**Comment by shubham-shahh** [comment]
I want to know where is the main function, I want to put a loop in it so that it keeps running as more and more new images are added to the folder

**Comment by stephanecharette** [comment]
That is definitely the wrong way to go about it.  The right way would be to use the API instead.

But if that is what you want to do, why ask on both discord and in this issue?  Finding `main()` is easy:

    > grep "main(" ~/darknet/src/*.c
    .../darknet/src/darknet.c:int main(int argc, char **argv)

**Comment by shubham-shahh** [comment]
Thank you I'll look into it.

**Comment by shubham-shahh** [comment]
the main() function is located in the darknet.c.
