### ISSUE TITLE
multiclass classification without bboxes in darknet

### ISSUE THREAD

**Issue by iMeleon** [AlexeyAB/darknet#6841]
Hi.
I need just make multiclass classification with darknet framework.
In default darknet i found just how to perform  classification(single per image).
In Yolo-version from AlexeyAB i can do it but i dont need bbox output from network.
How can i achieve my goal?   
How i need to annotate images(for default darknet it seems just need classname in image_classname.jpg) ?
May be i need to make annotation like in Yolo format but without bbox cordinates. may be it will work?

**Comment by stephanecharette** [comment]
See if this tutorial is of any help:  https://www.ccoderun.ca/programming/2020-03-07_Darknet/

Otherwise we'll need a bit more information on where exactly you need assistance.

**Comment by lizq-git** [comment]
> See if this tutorial is of any help: https://www.ccoderun.ca/programming/2020-03-07_Darknet/
> 
> Otherwise we'll need a bit more information on where exactly you need assistance.

Hi, Step, I have a question regarding using YOLO-darknet to train a classifier, I have followed this tutorial - https://pjreddie.com/darknet/train-cifar/, I then used the cifar.cfg to train on my dataset which works.

So, I went on the try out my dataset with the VGG16.cfg, but the loss quickly go up to infinity.

My question will be: do you have any experience in training a classifier via the darknet?

Appreciate your help.
