### ISSUE TITLE
How to disable GPU training when darknet is compiled with GPU=1?

### ISSUE THREAD

**Issue by witignite** [AlexeyAB/darknet#6847]
I was just wondering if there is any way to disable GPU training when `darknet` is compiled with `GPU=1`?

**Comment by LeKristapino** [comment]
just recompile with GPU=0 ? That shouldn't be any husttle

**Comment by witignite** [comment]
@LeKristapino Thanks. On a second thought, I guess that is the only way, because preprocessor macro is used to separate between GPU and non-GPU code (?).
