### ISSUE TITLE
Why FN is negetive number and recall>1?

### ISSUE THREAD

**Issue by hemp110** [AlexeyAB/darknet#685]
I use "detector map" to evaluate the pretrained yolov3.weights on a person dataset where only persons are annotated. The result is like this 
![2018-04-24 2 26 02](https://user-images.githubusercontent.com/17939760/39169745-8eb26ec6-47cb-11e8-837e-bf07668a82b1.png)
Other classes are all zeros, which is reasonable, but in the end
![2018-04-24 2 27 57](https://user-images.githubusercontent.com/17939760/39169874-fcabfc80-47cb-11e8-8fb7-842bd15664c5.png)
FN is negetive number and recall>1, I guess some detections hit the same ground truth, and FN is calculated by unique_truth_count-TP.
I think it's better to record whether each GT is detected and define FN as the number of GTs that are not detected.

**Comment by AlexeyAB** [comment]
> FN is negetive number and recall>1, I guess some detections hit the same ground truth

There were multiple hit for GT, so TP/FP/FN/IoU could be calculated wrong. (with mAP everything was fine.)
**I fixed it.** Now I check was this GT already detected or not. In any cases should be  `unique_truth_count=TP+FN`

What TP/FP/FN/IoU can you get now?

**Comment by AlaaMaz** [comment]
I was running into the same problem, it appears to have been fixed now

**Comment by hemp110** [comment]
Yes, it goes well now, thanks!
I'm very glad to see the recall of benchmark weights decreases by nearly a half, and my new-trained weights appears to work a little :)
