### ISSUE TITLE
question : what does -i 0  mean and waht is the difference of -ext_output and -out_filename ?

### ISSUE THREAD

**Issue by wwdok** [AlexeyAB/darknet#6850]
Hi, can anyone tell me what does -i 0  mean and waht is the difference of -ext_output and -out_filename in the command line, thanks !

**Comment by stephanecharette** [comment]
`-i` is the GPU index.  The default is zero, meaning the first GPU.

Looking at [the Darknet readme file](https://github.com/AlexeyAB/darknet), looks like `-ext_output` is to get the output coordinates, while `-out_filename` is where the output video will be saved.

**Comment by wwdok** [comment]
@stephanecharette Well, I think you make sense ~ thanks !
