### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by Artiintern** [AlexeyAB/darknet#6858]
getting this error while building darknet.sln

error : Designtime build failed for project 'C:\darknet-master\build\darknet\darknet.vcxproj' configuration 'Release|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.

**Comment by BrandonHdz2707** [comment]
how could you solved the issue? I have the same error :(

**Comment by BrandonHdz2707** [comment]
how did you solve the issue? I have the same error :(

**Comment by Artiintern** [comment]
You may resolve it by installing a different version of VS and cuDNN 8.0, 
by the way, I will suggest, use Linux as it does not require VS and will be much much easier to build all the commands of the darknet.
