### ISSUE TITLE
RTX3080 Inference error

### ISSUE THREAD

**Issue by Bubble-water** [AlexeyAB/darknet#6888]
I used CUDA 11.1and CUDNN64_8. and Opencv 342
this error:
cuDNN status Error in: file: D:/darknet-master/src/convolutional_kernels.cu : forward_convolutional_layer_gpu() : line: 471 : build time: Oct 27 2020 - 18:13:48

 cuDNN Error: CUDNN_STATUS_EXECUTION_FAILED

**Comment by haviduck** [comment]
did you compile opencv when you got your 3080?
there are some issues with arch for lower 30 and the New 86 etc.

**Comment by Bubble-water** [comment]
> did you compile opencv when you got your 3080?
> there are some issues with arch for lower 30 and the New 86 etc.
update cuda11.0 to cuda11.1，the questions is solved

**Comment by Wenlong0605** [comment]
Does it support RTX3080 now?

**Comment by ROBYER1** [comment]
How can I install opencv4 on a rtx 3080 system with vcpkg now?
