### ISSUE TITLE
Is there a visual model or architecture of YOLOv4-tiny?

### ISSUE THREAD

**Issue by AlainMindana** [AlexeyAB/darknet#6890]

**Comment by haviduck** [comment]
you can load it into netron

**Comment by AlainMindana** [comment]
Thank you! I found a way on how to see the summary of the YOLOv4-tiny architecture. Here is the summary:
[YOLOv4-tiny Architecture.txt](https://github.com/AlexeyAB/darknet/files/5463258/YOLOv4-tiny.Architecture.txt)
