### ISSUE TITLE
OSError: exception: access violation writing 0x000001F0282AA040

### ISSUE THREAD

**Issue by DoriHp** [AlexeyAB/darknet#6897]
I'm facing with this issue when running ```darknet_video.py``` file
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Default\Anaconda\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Default\Anaconda\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "darknet_video.py", line 72, in video_capture
    darknet.copy_image_from_bytes(darknet_image, frame_resized.tobytes())
OSError: exception: access violation writing 0x000001F0282AA040
```
on Window 10, OpenCV 4.5.0 built from source. Please help :(

**Comment by zzpbuaa** [comment]
Facing the same issue.

**Comment by zzpbuaa** [comment]
I think I may find the reason:
in thread 1, when run:
`darknet.copy_image_from_bytes(img_for_detect, `frame_resized.tobytes())`

copy_image_from_bytes is trying to write into the image.

meanwhile, in thread 2,
`detections = darknet.detect_image(network, class_names, darknet_image, thresh=args.thresh)`
detect_image is reading the image.

My solution:
```
def video_capture(frame_queue, darknet_image_queue):

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        frame_resized = cv2.resize(frame_rgb, (width, height),
                                   interpolation=cv2.INTER_LINEAR)
        frame_queue.put(frame_resized)
        img_for_detect = darknet.make_image(width, height, 3)
        darknet.copy_image_from_bytes(img_for_detect, frame_resized.tobytes())
        darknet_image_queue.put(img_for_detect)
    cap.release()
```

And I'll delete the definition of darknet_image, 
![image](https://user-images.githubusercontent.com/12425434/102968136-46964f00-452e-11eb-907a-844188ba9627.png)

I don't know if this solution is good or bad, but now it works.

**Comment by DoriHp** [comment]
Thanks @zzpbuaa 
Close because this problem has been solved :3
