### ISSUE TITLE
Should I create empty text files for the image where no object is present ? 

### ISSUE THREAD

**Issue by vishnuvardhan58** [AlexeyAB/darknet#6902]
Hello , I have 100 images where 60 images consist of objects and 40 images does not contain any object. So before starting training with darknet should I create empty 40 text files for the images where no object is present ?

**Comment by stephanecharette** [comment]
Yes, as is mentioned in the readme.

**Comment by vishnuvardhan58** [comment]
Thankyou @stephanecharette for you reply. So when I  create  emtpy text files , how will they be considered as during prediction ? FN ?

**Comment by stephanecharette** [comment]
What?

**Comment by barzan-hayati** [comment]
> 
> 
> Thankyou @stephanecharette for you reply. So when I create emtpy text files , how will they be considered as during prediction ? FN ?

Create any empty text file that its file name is like image file name.

**Comment by VolkovAK** [comment]
@vishnuvardhan58 No, it will be TN - True Negative, but since almost all possible bounding boxes are TN, this term is not used in detection metrics.

**Comment by vishnuvardhan58** [comment]
@VolkovAK, Thankyou.
