### ISSUE TITLE
Running Multiple Models Simultaniously

### ISSUE THREAD

**Issue by Cartucho** [AlexeyAB/darknet#692]
Is it possible to run multiple weight files at the same time?

Like replacing:

`./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg`

by: 

`./darknet detector test cfg/coco_1.data cfg/yolov3_1.cfg yolov3_1.weights cfg/obj.data cfg/obj.cfg obj.weights data/dog.jpg`

**Comment by AlexeyAB** [comment]
No.

But you can run two different instances of Darknet in two terminals simultaneously.

**Comment by Cartucho** [comment]
I'm not sure if I'm right, but when we train YOLO we don't train the initial layers (the ones already trained on ImageNet), we only train the final classifier. So that given the features of the first ImageNet layers it recognizes the objects.

If it is like this then it should be possible for me to use the same features (outputted from the first layers) and use more than one YOLO classifier?

Because if I run the two terminals simultaneously then I will be loading the same first layers twice, right?

**Comment by AlexeyAB** [comment]
> I'm not sure if I'm right, but when we train YOLO we don't train the initial layers (the ones already trained on ImageNet), 

When we train Yolo - we train all layers.

> we only train the final classifier. 

When we train Yolo - we train detector instead of classifier.

> If it is like this then it should be possible for me to use the same features (outputted from the first layers) and use more than one YOLO classifier?

Yolo isn't classifier - it is detector.

> Because if I run the two terminals simultaneously then I will be loading the same first layers twice, right?

Yes. For detection it uses batch=1 so it takes a little memory.

**Comment by Cartucho** [comment]
Oh ok, I was wrong! Thank you!
