### ISSUE TITLE
Build darknet with aarch64

### ISSUE THREAD

**Issue by vinorth05** [AlexeyAB/darknet#6928]
Hello,

I am trying to build darknet with a RaspberryPi 4 (Ubuntu 19.10 aarch64 + 4 Threads) and I have two questions:

- On the contrary to a RaspberryPi 3, I want to see if the performances of a rpi4 could be correct (inference time < 2s would be great). I already tried with my darknet model converted to tflite (with this repo https://github.com/hunglc007/tensorflow-yolov4-tflite), the inference time is quite promising (0.8s) but the accuracy is way lower than my original darknet model... 

So, did anyone try darknet performance with a RaspberryPi 64 bits? Do you have good results?

- When I try to build darknet with cmake, I have the following error : 
[cmake_build_output.txt](https://github.com/AlexeyAB/darknet/files/5495233/cmake_build_output.txt)

- And with make (with OPENCV=1 and everything else equal to 0), I have this error:
[make_build_output.txt](https://github.com/AlexeyAB/darknet/files/5495239/make_build_output.txt)

Do you have an idea what could be the problem?

**Comment by raizazel** [comment]
Same error here, did you manage to fix it?

**Comment by vinorth05** [comment]
Unfortunately not, I am still having this issue

**Comment by raizazel** [comment]
So I've come with a solution, at least for my case, aarch64 systems don't support either AVX and SSE instrucctions so I've commented out line 175 and 176 of the CMakeLists.txt. I don't know if that breaks it further for you since I'm running everything on GPU and you are not.

**Comment by vinorth05** [comment]
Thank you very much it is working for me now!
