### ISSUE TITLE
CUDA Error Prev: no error

### ISSUE THREAD

**Issue by XP-CHRC** [AlexeyAB/darknet#697]
Hi, i solved the problem that darknet.so doesn't has Init_YOLO, the main changeis: $(CPP) to (CC) in Makefile.
now i wrote a test file as follow,but error:
CUDA Error Prev: no error    test: ./src/cuda.c:45: check_error: Assertion `0' failed.
and i know the code stop before: float *network_predict_image(network *net, image im);
and i have enough GPU RAM, so where do you think may be wrong? thanks ahead!

**Comment by AlexeyAB** [comment]
Did you get an error in this function?
`int nCount = DetectImage(img, boxes, probs, classes, 0.5, net);`

**Comment by XP-CHRC** [comment]
no error about the function DetectImage  ,  when no define gpu, test.c works. and i add $(COMMEN), it works with gpu. thank your reply.
