### ISSUE TITLE
What weight should i use with yolov3-tiny-3l.cfg ?

### ISSUE THREAD

**Issue by mjack3** [AlexeyAB/darknet#6972]
Hello, I am fine tunning for one class with **yolov3**-tiny-3l.cfg. I have tried with **yolov4-tiny**.conv.29 and **yolov3-tiny**.weights (dowloaded from https://pjreddie.com/media/files/yolov3-tiny.weights) and both training are running. I am wondering if there is a "correct" weight to use with yolov3-tiny-3l.cfg version

Thanks

**Comment by stephanecharette** [comment]
If you are training your own custom network, I would use none.  Let it start from the default random values.  Note that the weights file for yolov3-tiny-3l (34 MiB) are a different size than yolov3-tiny (33 MiB) and yolov4-tiny (23 MiB).

**Comment by stephanecharette** [comment]
Example command to train a custom network:

Linux: ~/darknet/darknet detector -map -dont_show train dogs.data dogs.cfg 2>&1 | tee --append output.log
Windows: darknet.exe detector -map -dont_show train dogs.data dogs.cfg
