### ISSUE TITLE
Gtk WARNING **: cannot open display:

### ISSUE THREAD

**Issue by shapu** [AlexeyAB/darknet#6981]
I was trying to train YOLOv4 on my custom dataset which has 2 classes. I have changed the filters according in the cfg file to 21. However, some reason, I am getting Gtk Warning error. I am using batch size of 64 as recommended with subdivisions of 16. Wondering if this is due to out of memory error or some other issue.

I have set GPU = 1, cudNN = 1 and CUDA = 1 in my makefile and ran cmake then make to compile darknet. I have also made sure that I used relative paths in my train.txt and test.txt files from the darknet.exe. 

 CUDA-version: 10010 (10010), cuDNN: 7.6.4, GPU count: 1  
 OpenCV version: 4.9.1
valid: Using default '/home/shashank/Documents/thesis-project/yolov4-detection-experiments/sharks/640_110720/train.txt'
 0 : compute_capability = 520, cudnn_half = 0, GPU: GeForce GTX TITAN X 
   layer   filters  size/strd(dil)      input                output
   0 conv     32       3 x 3/ 1    640 x 640 x   3 ->  640 x 640 x  32 0.708 BF
   1 conv     64       3 x 3/ 2    640 x 640 x  32 ->  320 x 320 x  64 3.775 BF
   2 conv     64       1 x 1/ 1    320 x 320 x  64 ->  320 x 320 x  64 0.839 BF
   3 route  1 		                           ->  320 x 320 x  64 
   4 conv     64       1 x 1/ 1    320 x 320 x  64 ->  320 x 320 x  64 0.839 BF
   5 conv     32       1 x 1/ 1    320 x 320 x  64 ->  320 x 320 x  32 0.419 BF
   6 conv     64       3 x 3/ 1    320 x 320 x  32 ->  320 x 320 x  64 3.775 BF
   7 Shortcut Layer: 4,  wt = 0, wn = 0, outputs: 320 x 320 x  64 0.007 BF
   8 conv     64       1 x 1/ 1    320 x 320 x  64 ->  320 x 320 x  64 0.839 BF
   9 route  8 2 	                           ->  320 x 320 x 128 
  10 conv     64       1 x 1/ 1    320 x 320 x 128 ->  320 x 320 x  64 1.678 BF
  11 conv    128       3 x 3/ 2    320 x 320 x  64 ->  160 x 160 x 128 3.775 BF
  12 conv     64       1 x 1/ 1    160 x 160 x 128 ->  160 x 160 x  64 0.419 BF
  13 route  11 		                           ->  160 x 160 x 128 
  14 conv     64       1 x 1/ 1    160 x 160 x 128 ->  160 x 160 x  64 0.419 BF
  15 conv     64       1 x 1/ 1    160 x 160 x  64 ->  160 x 160 x  64 0.210 BF
  16 conv     64       3 x 3/ 1    160 x 160 x  64 ->  160 x 160 x  64 1.887 BF
  17 Shortcut Layer: 14,  wt = 0, wn = 0, outputs: 160 x 160 x  64 0.002 BF
  18 conv     64       1 x 1/ 1    160 x 160 x  64 ->  160 x 160 x  64 0.210 BF
  19 conv     64       3 x 3/ 1    160 x 160 x  64 ->  160 x 160 x  64 1.887 BF
  20 Shortcut Layer: 17,  wt = 0, wn = 0, outputs: 160 x 160 x  64 0.002 BF
  21 conv     64       1 x 1/ 1    160 x 160 x  64 ->  160 x 160 x  64 0.210 BF
  22 route  21 12 	                           ->  160 x 160 x 128 
  23 conv    128       1 x 1/ 1    160 x 160 x 128 ->  160 x 160 x 128 0.839 BF
  24 conv    256       3 x 3/ 2    160 x 160 x 128 ->   80 x  80 x 256 3.775 BF
  25 conv    128       1 x 1/ 1     80 x  80 x 256 ->   80 x  80 x 128 0.419 BF
  26 route  24 		                           ->   80 x  80 x 256 
  27 conv    128       1 x 1/ 1     80 x  80 x 256 ->   80 x  80 x 128 0.419 BF
  28 conv    128       1 x 1/ 1     80 x  80 x 128 ->   80 x  80 x 128 0.210 BF
  29 conv    128       3 x 3/ 1     80 x  80 x 128 ->   80 x  80 x 128 1.887 BF
  30 Shortcut Layer: 27,  wt = 0, wn = 0, outputs:  80 x  80 x 128 0.001 BF
  31 conv    128       1 x 1/ 1     80 x  80 x 128 ->   80 x  80 x 128 0.210 BF
  32 conv    128       3 x 3/ 1     80 x  80 x 128 ->   80 x  80 x 128 1.887 BF
  33 Shortcut Layer: 30,  wt = 0, wn = 0, outputs:  80 x  80 x 128 0.001 BF
  34 conv    128       1 x 1/ 1     80 x  80 x 128 ->   80 x  80 x 128 0.210 BF
  35 conv    128       3 x 3/ 1     80 x  80 x 128 ->   80 x  80 x 128 1.887 BF
  36 Shortcut Layer: 33,  wt = 0, wn = 0, outputs:  80 x  80 x 128 0.001 BF
  37 conv    128       1 x 1/ 1     80 x  80 x 128 ->   80 x  80 x 128 0.210 BF
  38 conv    128       3 x 3/ 1     80 x  80 x 128 ->   80 x  80 x 128 1.887 BF
  39 Shortcut Layer: 36,  wt = 0, wn = 0, outputs:  80 x  80 x 128 0.001 BF
  40 conv    128       1 x 1/ 1     80 x  80 x 128 ->   80 x  80 x 128 0.210 BF
  41 conv    128       3 x 3/ 1     80 x  80 x 128 ->   80 x  80 x 128 1.887 BF
  42 Shortcut Layer: 39,  wt = 0, wn = 0, outputs:  80 x  80 x 128 0.001 BF
  43 conv    128       1 x 1/ 1     80 x  80 x 128 ->   80 x  80 x 128 0.210 BF
  44 conv    128       3 x 3/ 1     80 x  80 x 128 ->   80 x  80 x 128 1.887 BF
  45 Shortcut Layer: 42,  wt = 0, wn = 0, outputs:  80 x  80 x 128 0.001 BF
  46 conv    128       1 x 1/ 1     80 x  80 x 128 ->   80 x  80 x 128 0.210 BF
  47 conv    128       3 x 3/ 1     80 x  80 x 128 ->   80 x  80 x 128 1.887 BF
  48 Shortcut Layer: 45,  wt = 0, wn = 0, outputs:  80 x  80 x 128 0.001 BF
  49 conv    128       1 x 1/ 1     80 x  80 x 128 ->   80 x  80 x 128 0.210 BF
  50 conv    128       3 x 3/ 1     80 x  80 x 128 ->   80 x  80 x 128 1.887 BF
  51 Shortcut Layer: 48,  wt = 0, wn = 0, outputs:  80 x  80 x 128 0.001 BF
  52 conv    128       1 x 1/ 1     80 x  80 x 128 ->   80 x  80 x 128 0.210 BF
  53 route  52 25 	                           ->   80 x  80 x 256 
  54 conv    256       1 x 1/ 1     80 x  80 x 256 ->   80 x  80 x 256 0.839 BF
  55 conv    512       3 x 3/ 2     80 x  80 x 256 ->   40 x  40 x 512 3.775 BF
  56 conv    256       1 x 1/ 1     40 x  40 x 512 ->   40 x  40 x 256 0.419 BF
  57 route  55 		                           ->   40 x  40 x 512 
  58 conv    256       1 x 1/ 1     40 x  40 x 512 ->   40 x  40 x 256 0.419 BF
  59 conv    256       1 x 1/ 1     40 x  40 x 256 ->   40 x  40 x 256 0.210 BF
  60 conv    256       3 x 3/ 1     40 x  40 x 256 ->   40 x  40 x 256 1.887 BF
  61 Shortcut Layer: 58,  wt = 0, wn = 0, outputs:  40 x  40 x 256 0.000 BF
  62 conv    256       1 x 1/ 1     40 x  40 x 256 ->   40 x  40 x 256 0.210 BF
  63 conv    256       3 x 3/ 1     40 x  40 x 256 ->   40 x  40 x 256 1.887 BF
  64 Shortcut Layer: 61,  wt = 0, wn = 0, outputs:  40 x  40 x 256 0.000 BF
  65 conv    256       1 x 1/ 1     40 x  40 x 256 ->   40 x  40 x 256 0.210 BF
  66 conv    256       3 x 3/ 1     40 x  40 x 256 ->   40 x  40 x 256 1.887 BF
  67 Shortcut Layer: 64,  wt = 0, wn = 0, outputs:  40 x  40 x 256 0.000 BF
  68 conv    256       1 x 1/ 1     40 x  40 x 256 ->   40 x  40 x 256 0.210 BF
  69 conv    256       3 x 3/ 1     40 x  40 x 256 ->   40 x  40 x 256 1.887 BF
  70 Shortcut Layer: 67,  wt = 0, wn = 0, outputs:  40 x  40 x 256 0.000 BF
  71 conv    256       1 x 1/ 1     40 x  40 x 256 ->   40 x  40 x 256 0.210 BF
  72 conv    256       3 x 3/ 1     40 x  40 x 256 ->   40 x  40 x 256 1.887 BF
  73 Shortcut Layer: 70,  wt = 0, wn = 0, outputs:  40 x  40 x 256 0.000 BF
  74 conv    256       1 x 1/ 1     40 x  40 x 256 ->   40 x  40 x 256 0.210 BF
  75 conv    256       3 x 3/ 1     40 x  40 x 256 ->   40 x  40 x 256 1.887 BF
  76 Shortcut Layer: 73,  wt = 0, wn = 0, outputs:  40 x  40 x 256 0.000 BF
  77 conv    256       1 x 1/ 1     40 x  40 x 256 ->   40 x  40 x 256 0.210 BF
  78 conv    256       3 x 3/ 1     40 x  40 x 256 ->   40 x  40 x 256 1.887 BF
  79 Shortcut Layer: 76,  wt = 0, wn = 0, outputs:  40 x  40 x 256 0.000 BF
  80 conv    256       1 x 1/ 1     40 x  40 x 256 ->   40 x  40 x 256 0.210 BF
  81 conv    256       3 x 3/ 1     40 x  40 x 256 ->   40 x  40 x 256 1.887 BF
  82 Shortcut Layer: 79,  wt = 0, wn = 0, outputs:  40 x  40 x 256 0.000 BF
  83 conv    256       1 x 1/ 1     40 x  40 x 256 ->   40 x  40 x 256 0.210 BF
  84 route  83 56 	                           ->   40 x  40 x 512 
  85 conv    512       1 x 1/ 1     40 x  40 x 512 ->   40 x  40 x 512 0.839 BF
  86 conv   1024       3 x 3/ 2     40 x  40 x 512 ->   20 x  20 x1024 3.775 BF
  87 conv    512       1 x 1/ 1     20 x  20 x1024 ->   20 x  20 x 512 0.419 BF
  88 route  86 		                           ->   20 x  20 x1024 
  89 conv    512       1 x 1/ 1     20 x  20 x1024 ->   20 x  20 x 512 0.419 BF
  90 conv    512       1 x 1/ 1     20 x  20 x 512 ->   20 x  20 x 512 0.210 BF
  91 conv    512       3 x 3/ 1     20 x  20 x 512 ->   20 x  20 x 512 1.887 BF
  92 Shortcut Layer: 89,  wt = 0, wn = 0, outputs:  20 x  20 x 512 0.000 BF
  93 conv    512       1 x 1/ 1     20 x  20 x 512 ->   20 x  20 x 512 0.210 BF
  94 conv    512       3 x 3/ 1     20 x  20 x 512 ->   20 x  20 x 512 1.887 BF
  95 Shortcut Layer: 92,  wt = 0, wn = 0, outputs:  20 x  20 x 512 0.000 BF
  96 conv    512       1 x 1/ 1     20 x  20 x 512 ->   20 x  20 x 512 0.210 BF
  97 conv    512       3 x 3/ 1     20 x  20 x 512 ->   20 x  20 x 512 1.887 BF
  98 Shortcut Layer: 95,  wt = 0, wn = 0, outputs:  20 x  20 x 512 0.000 BF
  99 conv    512       1 x 1/ 1     20 x  20 x 512 ->   20 x  20 x 512 0.210 BF
 100 conv    512       3 x 3/ 1     20 x  20 x 512 ->   20 x  20 x 512 1.887 BF
 101 Shortcut Layer: 98,  wt = 0, wn = 0, outputs:  20 x  20 x 512 0.000 BF
 102 conv    512       1 x 1/ 1     20 x  20 x 512 ->   20 x  20 x 512 0.210 BF
 103 route  102 87 	                           ->   20 x  20 x1024 
 104 conv   1024       1 x 1/ 1     20 x  20 x1024 ->   20 x  20 x1024 0.839 BF
 105 conv    512       1 x 1/ 1     20 x  20 x1024 ->   20 x  20 x 512 0.419 BF
 106 conv   1024       3 x 3/ 1     20 x  20 x 512 ->   20 x  20 x1024 3.775 BF
 107 conv    512       1 x 1/ 1     20 x  20 x1024 ->   20 x  20 x 512 0.419 BF
 108 max                5x 5/ 1     20 x  20 x 512 ->   20 x  20 x 512 0.005 BF
 109 route  107 		                           ->   20 x  20 x 512 
 110 max                9x 9/ 1     20 x  20 x 512 ->   20 x  20 x 512 0.017 BF
 111 route  107 		                           ->   20 x  20 x 512 
 112 max               13x13/ 1     20 x  20 x 512 ->   20 x  20 x 512 0.035 BF
 113 route  112 110 108 107 	                   ->   20 x  20 x2048 
 114 conv    512       1 x 1/ 1     20 x  20 x2048 ->   20 x  20 x 512 0.839 BF
 115 conv   1024       3 x 3/ 1     20 x  20 x 512 ->   20 x  20 x1024 3.775 BF
 116 conv    512       1 x 1/ 1     20 x  20 x1024 ->   20 x  20 x 512 0.419 BF
 117 conv    256       1 x 1/ 1     20 x  20 x 512 ->   20 x  20 x 256 0.105 BF
 118 upsample                 2x    20 x  20 x 256 ->   40 x  40 x 256
 119 route  85 		                           ->   40 x  40 x 512 
 120 conv    256       1 x 1/ 1     40 x  40 x 512 ->   40 x  40 x 256 0.419 BF
 121 route  120 118 	                           ->   40 x  40 x 512 
 122 conv    256       1 x 1/ 1     40 x  40 x 512 ->   40 x  40 x 256 0.419 BF
 123 conv    512       3 x 3/ 1     40 x  40 x 256 ->   40 x  40 x 512 3.775 BF
 124 conv    256       1 x 1/ 1     40 x  40 x 512 ->   40 x  40 x 256 0.419 BF
 125 conv    512       3 x 3/ 1     40 x  40 x 256 ->   40 x  40 x 512 3.775 BF
 126 conv    256       1 x 1/ 1     40 x  40 x 512 ->   40 x  40 x 256 0.419 BF
 127 conv    128       1 x 1/ 1     40 x  40 x 256 ->   40 x  40 x 128 0.105 BF
 128 upsample                 2x    40 x  40 x 128 ->   80 x  80 x 128
 129 route  54 		                           ->   80 x  80 x 256 
 130 conv    128       1 x 1/ 1     80 x  80 x 256 ->   80 x  80 x 128 0.419 BF
 131 route  130 128 	                           ->   80 x  80 x 256 
 132 conv    128       1 x 1/ 1     80 x  80 x 256 ->   80 x  80 x 128 0.419 BF
 133 conv    256       3 x 3/ 1     80 x  80 x 128 ->   80 x  80 x 256 3.775 BF
 134 conv    128       1 x 1/ 1     80 x  80 x 256 ->   80 x  80 x 128 0.419 BF
 135 conv    256       3 x 3/ 1     80 x  80 x 128 ->   80 x  80 x 256 3.775 BF
 136 conv    128       1 x 1/ 1     80 x  80 x 256 ->   80 x  80 x 128 0.419 BF
 137 conv    256       3 x 3/ 1     80 x  80 x 128 ->   80 x  80 x 256 3.775 BF
 138 conv     21       1 x 1/ 1     80 x  80 x 256 ->   80 x  80 x  21 0.069 BF
 139 yolo
[yolo] params: iou loss: ciou (4), iou_norm: 0.07, obj_norm: 1.00, cls_norm: 1.00, delta_norm: 1.00, scale_x_y: 1.20
 140 route  136 		                           ->   80 x  80 x 128 
 141 conv    256       3 x 3/ 2     80 x  80 x 128 ->   40 x  40 x 256 0.944 BF
 142 route  141 126 	                           ->   40 x  40 x 512 
 143 conv    256       1 x 1/ 1     40 x  40 x 512 ->   40 x  40 x 256 0.419 BF
 144 conv    512       3 x 3/ 1     40 x  40 x 256 ->   40 x  40 x 512 3.775 BF
 145 conv    256       1 x 1/ 1     40 x  40 x 512 ->   40 x  40 x 256 0.419 BF
 146 conv    512       3 x 3/ 1     40 x  40 x 256 ->   40 x  40 x 512 3.775 BF
 147 conv    256       1 x 1/ 1     40 x  40 x 512 ->   40 x  40 x 256 0.419 BF
 148 conv    512       3 x 3/ 1     40 x  40 x 256 ->   40 x  40 x 512 3.775 BF
 149 conv     21       1 x 1/ 1     40 x  40 x 512 ->   40 x  40 x  21 0.034 BF
 150 yolo
[yolo] params: iou loss: ciou (4), iou_norm: 0.07, obj_norm: 1.00, cls_norm: 1.00, delta_norm: 1.00, scale_x_y: 1.10
 151 route  147 		                           ->   40 x  40 x 256 
 152 conv    512       3 x 3/ 2     40 x  40 x 256 ->   20 x  20 x 512 0.944 BF
 153 route  152 116 	                           ->   20 x  20 x1024 
 154 conv    512       1 x 1/ 1     20 x  20 x1024 ->   20 x  20 x 512 0.419 BF
 155 conv   1024       3 x 3/ 1     20 x  20 x 512 ->   20 x  20 x1024 3.775 BF
 156 conv    512       1 x 1/ 1     20 x  20 x1024 ->   20 x  20 x 512 0.419 BF
 157 conv   1024       3 x 3/ 1     20 x  20 x 512 ->   20 x  20 x1024 3.775 BF
 158 conv    512       1 x 1/ 1     20 x  20 x1024 ->   20 x  20 x 512 0.419 BF
 159 conv   1024       3 x 3/ 1     20 x  20 x 512 ->   20 x  20 x1024 3.775 BF
 160 conv     21       1 x 1/ 1     20 x  20 x1024 ->   20 x  20 x  21 0.017 BF
 161 yolo
[yolo] params: iou loss: ciou (4), iou_norm: 0.07, obj_norm: 1.00, cls_norm: 1.00, delta_norm: 1.00, scale_x_y: 1.05
Total BFLOPS 140.995 
avg_outputs = 1159550 
 Allocate additional workspace_size = 52.43 MB 
Loading weights from /home/shashank/Documents/thesis-project/yolov4-detection-experiments/sharks/640_110720/yolov4.conv.137...yolov4-custom
net.optimized_memory = 0 
mini_batch = 4, batch = 64, time_steps = 1, train = 1 
nms_kind: greedynms (1), beta = 0.600000 
nms_kind: greedynms (1), beta = 0.600000 
nms_kind: greedynms (1), beta = 0.600000 
Done! Loaded 137 layers from weights-file 

(chart_yolov4-custom.png:30753): Gtk-WARNING **: cannot open display: 

 seen 64, trained: 0 K-images (0 Kilo-batches_64) 
Learning Rate: 0.001, Momentum: 0.949, Decay: 0.0005
 Detection layer: 139 - type = 28 
 Detection layer: 150 - type = 28 
 Detection layer: 161 - type = 28 
 If error occurs - run training with flag: -dont_show 

```

**Comment by stephanecharette** [comment]
> Wondering if this is due to out of memory error or some other issue.
...
> If error occurs - run training with flag: -dont_show

Have you tried to add the `-dont_show` parameter?

**Comment by shapu** [comment]
Hello Stephane,

Thank you for the response. I actually forgot to mention the main issue, the model just doesn't train for some reason. It just aborts after displaying the above message. To add, I am using symbolic links to my original image paths in the folder where I store the data relative to darknet.exe. Do you know why the training just aborts?

**Comment by stephanecharette** [comment]
Yes, probably because it tries to use X and you either don't have it installed or are using a plain text ssh connection.  I'll ask again -- did you try to add the `-dont_show` parameter?

**Comment by shapu** [comment]
Hello Stephane,

I actually managed to fix the issue. One issue was due to the paths I was using in my train.txt and test.txt files. I had to use absolute paths instead of relative paths from the darknet.exe. The other issue was with the memory. I had to reduce the subdivisions from 16 to 32 as my GPU could not handle the big batch size for 512 x 512 image size. Thanks for your help.
