### ISSUE TITLE
Yolo training

### ISSUE THREAD

**Issue by VanitarNordic** [AlexeyAB/darknet#7]
Hello,

is there anyway to pause the Yolo training at some stages (to turn off the computer or something like that) and then re-train it some time later from where it has paused?

**Comment by AlexeyAB** [comment]
@VanitarNordic 
something like this: https://github.com/AlexeyAB/darknet#how-to-train-with-multi-gpu
but without  `-gpus 0,1,2,3`, i.e.

1. start initially: `darknet.exe detector train data/voc.data yolo-voc.cfg darknet19_448.conv.23`
2. start from 1000 iterations: `darknet.exe detector train data/voc.data yolo-voc.cfg yolo-voc_1000.weights`

looking `yolo-voc_1000.weights` at backup `build\darknet\x64\backup\`

**Comment by VanitarNordic** [comment]
so a folder in the name of backup should be existed to store the current weights?

please look at the images, how many iterations does it passed?

![2017-01-11_23-07-24](https://cloud.githubusercontent.com/assets/18719591/21863489/f2f7f1f6-d852-11e6-8a95-cfd144298839.jpg)

**Comment by AlexeyAB** [comment]
@VanitarNordic 

`2: ...` - it means that 2 iterations passed

Each iteration is a batch which include training 64 times as set in `batch=64` and divided at 8 as set in `subdivisions=8`: https://github.com/AlexeyAB/darknet/blob/master/build/darknet/x64/yolo-voc.cfg#L2

Backup folder already created: https://github.com/AlexeyAB/darknet/tree/master/build/darknet/x64/backup 
if you start darknet.exe from this path: https://github.com/AlexeyAB/darknet/tree/master/build/darknet/x64

Intermediate backups are created at intervals as set here: https://github.com/AlexeyAB/darknet/blob/master/src/detector.c#L140

* `100 - 1000` - each 100 iterations
* `1000 - 120 000` - each 1000 iterations

**Comment by VanitarNordic** [comment]
Okay, So at least 100 iterations should be passed for one saved backup. anyway, I'm running with `nogpu` and as I see it will take ages :-( 

I gonna ask you if there is anyway to run it on a remote server with GPU. You are really professional.
