### ISSUE TITLE
Implementation of Grad Cam in YOLO v3 and YOLO v4 by Darknet

### ISSUE THREAD

**Issue by tmori2918** [AlexeyAB/darknet#7003]
Hello.
Now I Develop YOLO v3 and YOLO v4 AI, and I want to apply Grad CAM to those AIs and output a heatmap.
Is there an optional command to output a heatmap in the darknet options?
Or can I implement Grad CAM by making minor changes to any file in the src directory?

I want to know what part of the Bounding Box the AI ​​is paying particular attention to.
However, I am new to AI and programming and do not know advanced implementation methods.

If anyone knows how to implement Grad CAM on darknet, please help me.
Thank you.

**Comment by SaraPiresNobrega** [comment]
Hello ! 
Did you found an answer ?
Thanks !
