### ISSUE TITLE
Optput Labels in YOLO Format

### ISSUE THREAD

**Issue by MarvinKlemp** [AlexeyAB/darknet#7005]
Is there a way to run `darknet detector test ...` with a flag to store predicted labels in yolo format (using the same name as the image but using file estension .txt)?

We already have a trained network and new data. So we would like to first classify using our existing network and then correct the labeling by hand and then retrain the network.

I could build a little python/opencv script. But maybe there is already such a feature?

**Comment by tmori2918** [comment]
All you want to do is add "-save_labels" to the object detection command.

For example, run the following command:

`./darknet detector test cfg/coco.data cfg/yolov4.cfg yolov4.weights data/dog.jpg -save_labels`

If you add "-save_lables" and execute the command, darknet will create annotation data in YOLO format in the directory containing the test image data.
However, this option doesn't seem to work for videos.

I hope it helps you.

**Comment by MarvinKlemp** [comment]
Perfect :) !

Thanks a lot
