### ISSUE TITLE
mAP of Tiny YOLOv3 on coco test-dev2017 seems lower.

### ISSUE THREAD

**Issue by OsamuNomusan** [AlexeyAB/darknet#7007]
Hi, guys, I need your advice.

I tried to evaluate accuracy of Tiny YOLOv3 on COCO test2017 dataset, following the tutorial "How to evaluate accuracy and speed of YOLOv4".
https://github.com/AlexeyAB/darknet/wiki/How-to-evaluate-accuracy-and-speed-of-YOLOv4

I changed some configurations to match Tiny YOLOv3 (size: 416) and run validation.
$ ./darknet detector valid cfg/coco.data cfg/yolov3-tiny.cfg yolov3-tiny.weights

I got the following results (0.178 mAP@0.5), but it seems quite lower than 33.1% mAP@0.5 shown in the official page (https://github.com/AlexeyAB/darknet#pre-trained-models).

overall performance
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.088
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.178
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.076
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.055
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.226
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.119
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.209
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.227
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.016
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.201
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.473

I'd really appreciated if you could tell me the reason of the difference.
Thanks.

**Comment by WongKinYiu** [comment]
1. change [`mask = 0,1,2`](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov3-tiny.cfg#L175) to `mask = 1,2,3`.
2. add `letter_box=1` in [`[net]`](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov3-tiny.cfg#L17)

**Comment by OsamuNomusan** [comment]
I got the following reasonable result with test-dev2017!!
I really appreciate your help.

overall performance
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.153
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.323
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.125
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.043
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.153
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.247
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.167
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.278
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.302
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.077
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.330
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.500

**Comment by louielu1027** [comment]
@WongKinYiu  why......
