### ISSUE TITLE
Fruit 360 fruit data set does not give correct results in yolov4 model.

### ISSUE THREAD

**Issue by kadirnar** [AlexeyAB/darknet#7011]
I label the fruit in the Fruit-360 dataset. I am using the Yolov4-tiny model. Map value is 100%. When I run the model, the train recognizes 90% of the images in the data set. When I run real fruit pictures, it doesn't recognize at all. When I test 3 apple images, it detects it as 1 apple.

Model: Yolov4-tiny

[meyve-tiny.txt](https://github.com/AlexeyAB/darknet/files/5579186/meyve-tiny.txt)

**Comment by stephanecharette** [comment]
Never seen the fruit360 data set.  How close is it to the images you are running?

**Comment by kadirnar** [comment]
Fruit 360: https://www.kaggle.com/moltean/fruits 
I collect images from google images. I think the diversity in this dataset is a little minimal. I wonder if there's a problem with that?

![chart_meyve-tiny](https://user-images.githubusercontent.com/36204372/99900988-51a65700-2cc4-11eb-8a02-628613bc5b6c.png)

**Comment by stephanecharette** [comment]
The network can only find what you train it to find.  If you images are of quality/size/shape/<something> very different than the images you then use to test the results ...don't be surprised if things don't work.

**Comment by kadirnar** [comment]
Can you suggest a dataset for the fruit dataset? (I'm working on an agricultural drone.)

**Comment by stephanecharette** [comment]
I've always created my own data set, I've never used one made by someone else.  So if you have images you are using which you took yourself, I would start training with those.

**Comment by stephanecharette** [comment]
You must have images from your agricultural drone?  *Those* are the images you should be using to create your neural network.

**Comment by kadirnar** [comment]
Thank you very much. How many pictures should there be for each fruit?

**Comment by stephanecharette** [comment]
> How many pictures should there be for each fruit?

https://www.reddit.com/r/learnmachinelearning/comments/jxy7w5/question_if_i_want_to_create_an_app_that_can/gczv5b0?utm_source=share&utm_medium=web2x&context=3

**Comment by stephanecharette** [comment]
And if you're looking for a way to create a darknet/yolo project and mark up images, I recommend:  https://www.ccoderun.ca/darkmark/Summary.html

**Comment by kadirnar** [comment]
Thank you. I got the answer to my question.
