### ISSUE TITLE
Weird average loss on RTX 3080

### ISSUE THREAD

**Issue by jjjstringer** [AlexeyAB/darknet#7036]
When I use RTX 3080 to train with my own dataset, the acerage loss chart is weird.
What's the problem?

The picture below is RTX 3080(I have updated Makefile and remake darknet)
![Screenshot from 2020-11-26 19-05-52](https://user-images.githubusercontent.com/72988884/100343637-97dc1d00-301a-11eb-8ba7-412e766517ed.png)

The picture below is Gtx 1050 ti with the same dataset
![chart](https://user-images.githubusercontent.com/72988884/100343796-d1ad2380-301a-11eb-9b28-ce5b522a71e5.png)

**Comment by JJangD** [comment]
I have same problem with TITAN RTX as the first picture above.
The MAP value(89% at the end of the training) of validation set increases while loss of train set increases.
