### ISSUE TITLE
problem with detecting poker cards

### ISSUE THREAD

**Issue by gms2009** [AlexeyAB/darknet#7045]
Try to detect poker cards,
After training(all cards are same size with number on top and set on bottom with color, each card has 512jpg in training set), it detect single card ok but not multiple cards, any suggestion?

**Comment by stephanecharette** [comment]
You need training images with multiple cards in them.  Darknet will detect things it has previously seen.  So if your training images don't match the images you want to use, then you need to add into the training set the types of images you want it to detect.
Also see https://www.ccoderun.ca/programming/darknet_faq/#crop_training_images and https://www.ccoderun.ca/darkmark/ImageMarkup.html

**Comment by gms2009** [comment]
I have 52 classes for 52 kind of cards, each cards has 512 same images for training, and detect a image with single card works fairly well(will recognize spade 8, or heart 4 etc), but not image with multiple cards,(if the original message is not clear enough)
I thought the whole idea of object detection is to train with objects and detect them in any images, instead of train for some images(with objects in them) and only detect those images

**Comment by stephanecharette** [comment]
No, you're thinking of templates.  I'm telling you, Darknet will detect the types of images that it trains with.  If you want it to detect multiple cards, then train with images that has multiple cards.  If you don't believe me, then see the project's `readme`:

> for each object which you want to detect - there must be at least 1 similar object in the Training dataset with about the same: shape, side of object, relative size, angle of rotation, tilt, illumination. So desirable that your training dataset include images with objects at diffrent: scales, rotations, lightings, from different sides, on different backgrounds - you should preferably have 2000 different images for each class or more, and you should train 2000*classes iterations or more

You don't need every mathematically possible combination of cards.  But you need 2 cards together.  And 3 cards together.  And cards in the upper-left of the image, cards in the lower-right of the image, cards rotated 90 degrees, 180 degrees, etc.

In addition, you may want to visit the Darknet/YOLO discord if you want to discuss further:  https://discord.gg/zSq8rtW

**Comment by gms2009** [comment]
It is working great, Thanks
