### ISSUE TITLE
Detection result is not same when run on python vs bash file

### ISSUE THREAD

**Issue by vanchung1995** [AlexeyAB/darknet#7054]
I trained my model ok. I run 2 command bellow but the result is difference:
`./darknet detector test ./data/obj.data ./cfg/yolov4-obj.cfg ./backup/yolov4-obj_final.weights -i 0 -thresh 0.5 ./test_images/BD_19-06-2020.png`
vs
`python darknet_images.py --weights weights/yolov4-obj_final.weights --config_file cfg/yolov4-obj.cfg --thresh 0.5 ` and fill the path is ./test_images/BD_19-06-2020.png

the result is bellow:

![Screenshot from 2020-11-30 15-49-38](https://user-images.githubusercontent.com/15941200/100587909-c2342000-3323-11eb-8158-baf21117ed74.png)
![Screenshot from 2020-11-30 15-50-06](https://user-images.githubusercontent.com/15941200/100587916-c4967a00-3323-11eb-8bf4-8265a4816f52.png)

I realize that `./darknet detector test ./data/obj.data ./cfg/yolov4-obj.cfg ./backup/yolov4-obj_final.weights -i 0 -thresh 0.5 ./test_images/BD_19-06-2020.png` make perfect prediction but `python darknet_images.py --weights weights/yolov4-obj_final.weights --config_file cfg/yolov4-obj.cfg --thresh 0.5 ` didnot. Why there was this difference?

**Comment by vanchung1995** [comment]
Bellow is the another example

![Screenshot from 2020-11-30 15-52-24](https://user-images.githubusercontent.com/15941200/100588210-2b1b9800-3324-11eb-9fab-29bdba65b53a.png)
![Screenshot from 2020-11-30 15-52-44](https://user-images.githubusercontent.com/15941200/100588215-2ce55b80-3324-11eb-83c9-202d8757aa6c.png)

**Comment by versavel** [comment]
@vanchung1995 : Did you find out what caused the difference ?
