### ISSUE TITLE
Is there downsampling in Mosaic augmentation?

### ISSUE THREAD

**Issue by yldrmBtn** [AlexeyAB/darknet#7057]
My question is related to mosaic augmentation. Assume that I have images at resolution of 1920x1080 and during training I set image size to 1088. As I understand, 4 random images will be used and combined during mosaic augmentation( (4x1920)x(4x1080) ) and then, a crop at a size of 1088x1088 will be taken for training. This means input image will not be down-sampled and objects will remain at original size. Am I correct? Because, I do not want any downsampling operation during training.

**Comment by AlexeyAB** [comment]
> This means input image will not be down-sampled and objects will remain at original size. Am I correct?

Yes.


But Up/Down-scale will be performed due to `[yolo] jitter= and resize=` parameters: https://github.com/AlexeyAB/darknet/wiki/CFG-Parameters-in-the-different-layers

**Comment by yldrmBtn** [comment]
I see, thank you very much.
