### ISSUE TITLE
Regarding: Yolov3-voc.cfg map value

### ISSUE THREAD

**Issue by akshayjrkp** [AlexeyAB/darknet#706]
I followed the readme file and trained YoloV3 for Pascal VOC dataset.
The map value obtained is 74.48 %.
Shouldn't it be better than this? The cfg file is following:

```
[net]
#Testing
 batch=8
 subdivisions=2
#Training
#batch=64
#subdivisions=16
width=416
height=416
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1
learning_rate=0.001
burn_in=1000
max_batches = 100200
policy=steps
steps=40000,45000
scales=.1,.1 
```
```
The Makelfile options are as follow:

GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=1
AVX=0
OPENMP=0
LIBSO=0
```
Please suggest.

**Comment by AlexeyAB** [comment]
It should be better if you will train `100200` iterations with `batch=64 subdivision=16` or 8.

**Comment by akshayjrkp** [comment]
Thank you so much for the reply.
If I use batch=64 and subdivision=16, then effective real batch size equals=64/16=4; which will be same as in my case 8/2=4. Will "64/16" result in an almost same map as "8/2"?

I will try to train with "64/8" to check if map increases.
