### ISSUE TITLE
Why is detections.prob an array of mostly zeros?

### ISSUE THREAD

**Issue by AntMorais** [AlexeyAB/darknet#7061]
In the detect_image function in darknet.py, we get the detections, as well as the probability of each detection belonging to each class. However in my case the probabilities are only positive for one class, and all the others are zero. 

![Screenshot from 2020-12-01 11-46-43](https://user-images.githubusercontent.com/26347971/100736612-ec8ce880-33ca-11eb-8880-4433bf688dd1.png)
This is a sample of the values that are in the detections, which in my case is 30 bboxes x 80 classes.
Is this to be expected? Why is that? Is there a way to get values for the other classes that are different from zero?

**Comment by AntMorais** [comment]
@AlexeyAB

**Comment by lsd1994** [comment]
After NMS, most of prob is set to 0, it's normal.
