### ISSUE TITLE
giou avg loss stays high only in updated repo

### ISSUE THREAD

**Issue by lars-ek** [AlexeyAB/darknet#7067]
I am training yolov4-tiny (swish activation) with giou loss.

Usually, the avg loss approaches ~0.1 with my training data set after 50000 iterations. Two days ago I updated the repo, and now the avg-loss decreases to ~4 and stays there for ever.

I switched back to old repo (october?) and its behaving normal again. Same input, same training data.
Very weird.

Using ubuntu, GTX 1070.

**Comment by lars-ek** [comment]
#7078

**Comment by rabsym** [comment]
Same happens here with lastest repo, going back to september-october works as expected with avg loss decreasing till 0.1

(Windows version)

**Comment by AlexeyAB** [comment]
It is fixed: https://github.com/AlexeyAB/darknet/issues/7097#issuecomment-742737350
