### ISSUE TITLE
What is the standard for saving the optimal weight in YOLOv4? Thank you

### ISSUE THREAD

**Issue by joe660** [AlexeyAB/darknet#7070]
What is the standard for saving the optimal weight in YOLOv4? Thank you

**Comment by stephanecharette** [comment]
I'm unclear on what you mean.  Can you elaborate?

**Comment by joe660** [comment]
> I'm unclear on what you mean. Can you elaborate?

It is to save the weight of the best model according to what standard measurement, such as accuracy, recall, or AP value, etc.

**Comment by lsd1994** [comment]
best mAP
