### ISSUE TITLE
gcc: error trying to exec 'cc1plus': execvp: No such file or directory

### ISSUE THREAD

**Issue by jobpasin** [AlexeyAB/darknet#7076]
I tried to build darknet on Ubuntu 20.04 using `make` command. (CUDA 10.1, GTX2070)

But there are the following errors

```
/work/darknet$ make
chmod +x *.sh
/usr/local/cuda-10.1/bin/nvcc -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -gencode arch=compute_61,code=[sm_61,compute_61] -gencode arch=compute_70,code=[sm_70,compute_70] -Iinclude/ -I3rdparty/stb/include -DOPENCV `pkg-config --cflags opencv4 2> /dev/null || pkg-config --cflags opencv` -DGPU -I/usr/local/cuda/include/ -DCUDNN -DCUDNN_HALF --compiler-options "-Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -fopenmp -DGPU -DCUDNN -I/usr/local/cudnn/include -DCUDNN_HALF -fPIC" -c ./src/convolutional_kernels.cu -o obj/convolutional_kernels.o
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
make: *** [Makefile:177: obj/convolutional_kernels.o] Error 1
```
I'm not sure if gcc is the problem here since I tried to reinstall using the below command but it still doesn't work. But I also don't know where the problem could be.

```
sudo apt-get update
sudo apt-get install --reinstall build-essential
```

If you need any other information, please let me know. Thanks in advance!

**Comment by stephanecharette** [comment]
I would say something about your C/C++ compiler toolchain wasn't installed correctly.

Normally I would tell you to run `sudo apt-get install build-essential` but from your comment it looks like you've already done that.  Anything else you can tell us about how you installed gcc/g++, or anything strange about this system?

On my Ubuntu 20.04, I get this:

```
> g++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
> gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
> cc1plus
cc1plus: command not found
> dpkg -l | egrep "g\+\+|build-essential"
ii  build-essential                               12.8ubuntu1.1                              amd64        Informational list of build-essential packages
ii  g++                                           4:9.3.0-1ubuntu2                           amd64        GNU C++ compiler
ii  g++-9                                         9.3.0-17ubuntu1~20.04                      amd64        GNU C++ compiler
```
Have you made any modifications to `Makefile`?  Run `git status` or `git diff` in your darknet directory to review any changes.

**Comment by jobpasin** [comment]
@stephanecharette 

Here is my result using similar command with yours. Looks like gcc version is different.

```
ndrs@ndrs:~$ g++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ndrs@ndrs:~$ gcc --version
gcc (Ubuntu 8.4.0-3ubuntu2) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ndrs@ndrs:~$ cc1plus
cc1plus: command not found
ndrs@ndrs:~$ dpkg -l | egrep "g\+\+|build-essential"
ii  build-essential                      12.8ubuntu1.1                         amd64        Informational list of build-essential packages
ii  g++                                  4:9.3.0-1ubuntu2                      amd64        GNU C++ compiler
ii  g++-9                                9.3.0-17ubuntu1~20.04                 amd64        GNU C++ compiler
```

As for the Makefile changes, I changed some configuration which should not affect anything.

```
@@ -1,10 +1,10 @@
-GPU=0
-CUDNN=0
-CUDNN_HALF=0
-OPENCV=0
+GPU=1
+CUDNN=1
+CUDNN_HALF=1
+OPENCV=1
 AVX=0
-OPENMP=0
-LIBSO=0
+OPENMP=1
+LIBSO=1
 ZED_CAMERA=0
 ZED_CAMERA_v2_8=0
```

By the way, I tried to build with cmake first (using `./build.sh`) as mentioned in the guide but it seems that the version it created did not use GPU, so I tried to build it using the `make` command instead. I don't think this affects anything but I want to mention just in case.

**Comment by stephanecharette** [comment]
> ndrs@ndrs:~$ g++ --version
> g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
> ...
> ndrs@ndrs:~$ gcc --version
> gcc (Ubuntu 8.4.0-3ubuntu2) 8.4.0

Don't know how you managed to setup your system that way, but something is very wrong.  gcc and g++ should be the same version number, and with Ubuntu 20.04 should be v9.3.0.  Try with a different VM or a different system, or document what you did to get the compilers setup that way so we can advise you on what needs to be fixed.

**Comment by jobpasin** [comment]
@stephanecharette  Thanks for the suggestion.

I tried changing my default gcc version using the link here:
https://askubuntu.com/questions/26498/how-to-choose-the-default-gcc-and-g-version

And now the version is the same, which is 9.3.0. However, it seems like there is some new error instead from cuda. 

```

In file included from /usr/local/cuda/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/local/cuda/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
  138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      |  ^~~~~
compilation terminated due to -Wfatal-errors.
make: *** [Makefile:177: obj/convolutional_kernels.o] Error 1
```

Does this mean that I should use a higher version of CUDA in order to use gcc version 9?

**Comment by stephanecharette** [comment]
I have no idea.  But 1) I don't particularly trust your installation since something was installed in a strange way, and 2) if you have a GTX 2070, then I'm guessing you'll need a recent release of CUDA to support it.

**Comment by jobpasin** [comment]
The problem is fixed now. Although I have not really know the actual reason (I tried many things at the same time) but these are probably things that make it works. Thanks to [Joseph's guide](https://robocademy.com/2020/05/01/a-gentle-introduction-to-yolo-v4-for-object-detection-in-ubuntu-20-04/#Installing_YOLO_v4_on_Ubuntu_20_04)

- `sudo apt install libomp-dev`
- `sudo apt install make git g++  ` (But all package were already up to date so it wasn't the actual solution I think)
- Change `OPENMP=0`  (apparently it was 1 before)
