### ISSUE TITLE
YOLOv3 on TX2 on-board-camera: Segmentation fault (core dump)

### ISSUE THREAD

**Issue by passion3394** [AlexeyAB/darknet#708]
My work environment like this:
TX2
Opencv 3.3 with V4L2 support and gstreamer support
when I use the following command to detect the objects with the on-board-camera, it appears 
**Segmentation fault (core dumped)**
`./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights`
when I plug on a usb camera on the TX2 and add -c 1 option after the following command, 
everything works fine.
so what's the problem with the on-board-camera? and what should I do if I want to use the on-board-camera? Thanks very much.
![wechatimg2](https://user-images.githubusercontent.com/14256482/39340198-6490032a-49ff-11e8-8351-8a41a0c5ba79.jpeg)

**Comment by passion3394** [comment]
I have found the solutino from the nvidia forum.
The solution is two steps:
1 follow the following link to rebuild the opencv 3.x which added the V4L2 support.
http://dev.t7.ai/jetson/opencv/
2 run the darknet with the following command:
./darknet detector demo cfg/coco.data cfg/yolo.cfg yolo.weights "nvcamerasrc ! video/x-raw(memory:NVMM), width=(int)1280, height=(int)720,format=(string)I420, framerate=(fraction)30/1 ! nvvidconv flip-method=0 ! video/x-raw, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink"

BTW, I use the above command and get only 3.3 fps. How can I get more fps? 
I have only some ideas:
1  modify the "width=(int)1280, height=(int)720" config in the above command, but it is not a good idea.
2 use tensorRT, but I don't know how to do
3 optimize the tegra Ubuntu system, such as kill some useless processes.

**Comment by passion3394** [comment]
@AlexeyAB thx for your reply. Now my question is how to make the detection more fast? Could you give me some suggestions?

**Comment by AlexeyAB** [comment]
@passion3394 

1. Run `jetson-clocks.sh` and `sudo nvpmodel -m 0` https://github.com/AlexeyAB/darknet/issues/436#issuecomment-371786781
More info: http://www.jetsonhacks.com/2017/03/25/nvpmodel-nvidia-jetson-tx2-development-kit/

2. Change these lines to `width=288 height=288`: https://github.com/AlexeyAB/darknet/blob/5e3dcb6f34868e341466b57b13ad63f86b337250/cfg/yolov3.cfg#L8-L9

3. What param do you use here? https://github.com/AlexeyAB/darknet/blob/5e3dcb6f34868e341466b57b13ad63f86b337250/Makefile#L1-L2

4. Un-comment this line and re-compile: https://github.com/AlexeyAB/darknet/blob/5e3dcb6f34868e341466b57b13ad63f86b337250/Makefile#L36

And comment these lines: https://github.com/AlexeyAB/darknet/blob/5e3dcb6f34868e341466b57b13ad63f86b337250/Makefile#L15-L19
