### ISSUE TITLE
v3 vs v4 speed comparison

### ISSUE THREAD

**Issue by EmileTestUser** [AlexeyAB/darknet#7086]
Hi @AlexeyAB ,

I am currently writing my bachelor thesis in Munich about a comparison of version 3 and your well improved version 4. In order to fully understand the performance differences I have a question:

When comparing speed and accuracy of yolo v3 and v4 with my data I can notice a ~16% decrease of speed. As #6630 #5308 and Figure1 in the v4 paper prove, v4 speed will be lower for the same image size.

In contradiction, Table 8 in the paper shows the following values for a size of 416:
v4 - 38 FPS
v3 - 35 FPS

This would be an improvement of speed for the same image size. For other GPUs this is even higher.

What am I understanding wrong?

Thank you

**Comment by 1993cathyzhao1993** [comment]
You mean the speed of v4 is faster than v3 based your data?

**Comment by AlexeyAB** [comment]
1. Speed in this repository was improved
 Table 8 in the paper shows the following values for a size of 416: https://arxiv.org/pdf/2004.10934.pdf
v4 - 38 FPS - https://github.com/AlexeyAB/darknet
v3 - 35 FPS - https://github.com/pjreddie/darknet

2. If we use the same framework, then 
* YOLOv3 is slightly faster than YOLOv4 for the same resolution
* YOLOv4 is many times faster than YOLOv3 for the same accuracy

https://arxiv.org/abs/2011.08036
![scaled_yolov4_resolution - копия - копия](https://user-images.githubusercontent.com/4096485/101355489-adb5d180-38a7-11eb-9137-d797e41ace8d.png)
