### ISSUE TITLE
Bug in new commit

### ISSUE THREAD

**Issue by Diaislam** [AlexeyAB/darknet#7097]
I have been using this repo for a long time, and this happended for the first time.
last training was a fail, values are -nan.
![image](https://user-images.githubusercontent.com/33395350/101607444-e8814c00-3a04-11eb-8473-a892f41f3528.png)

a checkout to and old commit solved the problem
i'm using ubuntu gpu cuda 10.2

**Comment by MKiremitci** [comment]
@Diaislam Hi, I also have met some problems with new commit during custom traininig. I was thinking create a new issue with it. I am wondering how could you reach the old commit _("a checkout to and old commit solved the problem")_? I am newbie. Can you help me?  I am using this command
"!git clone https://github.com/AlexeyAB/darknet.git"
What kind of command should I use the reach commit of 1 week ago?

**Comment by Diaislam** [comment]
> @Diaislam Hi, I also have met some problems with new commit during custom traininig. I was thinking create a new issue with it. I am wondering how could you reach the old commit _("a checkout to and old commit solved the problem")_? I am newbie. Can you help me? I am using this command
> "!git clone https://github.com/AlexeyAB/darknet.git"
> What kind of command should I use to reach commit of 1 week ago?

just git checkout 8c9c5171891ea92b0cbf5c7fddf935df0b854540 after you clone the repo

this particular commit everything was working fine : https://github.com/AlexeyAB/darknet/commit/8c9c5171891ea92b0cbf5c7fddf935df0b854540

until they fix the issue

**Comment by MKiremitci** [comment]
Thanks, I will try it now

**Comment by Diaislam** [comment]
@AlexeyAB please check this.

**Comment by AlexeyAB** [comment]
@Diaislam 
* Attach your cfg-file
* Did you try to use last commit?
* What training command do you use?

**Comment by Diaislam** [comment]
> @Diaislam
> 
> * Attach your cfg-file
> * Did you try to use last commit?
> * What training command do you use?

1-here is the cfg file :

[yolo.txt](https://github.com/AlexeyAB/darknet/files/5666322/yolo.txt)

2- yes the last commit was failing to train , i checked latest issues they all said the same Values go to NaN, and by going to an older commit everything worked fine as usual i've been training with this repo at least once a week for more than a year.

3- training command : ./darknet detector train data/obj.data weights_file cfg_file -dont_show -mjpeg_port 8090 -map -clear . [using yolov4]

**Comment by pycoco** [comment]
i also met same problem。same data and cfg file,when i use old version,loss can down to 3。 but use the last commit version, loss just can down to 70

**Comment by lars-ek** [comment]
#7067

**Comment by AlexeyAB** [comment]
I fixed the display of too high loss: https://github.com/AlexeyAB/darknet/commit/a72bb059d88bb7a4a0ec2451eec243e9de4f62b0

I trained your https://github.com/AlexeyAB/darknet/files/5666322/yolo.txt cfg-file (just change `filters=255 classes=80`) on MS 
COCO for ~2000 iterations and get **34.5% AP50** and **Loss ~= 8.0**


![chart](https://user-images.githubusercontent.com/4096485/101818613-2b424180-3b35-11eb-8a66-f926b4b972b5.png)

![image](https://user-images.githubusercontent.com/4096485/101818767-604e9400-3b35-11eb-9407-12180a343290.png)

![image](https://user-images.githubusercontent.com/4096485/101818558-1b2a6200-3b35-11eb-8d92-55c87719770c.png)

**Comment by pycoco** [comment]
@AlexeyAB  when i use yolov4-custom cfg file ,everything is ok。 but when i use yolov4-csp.cfg, the loss is very high 。and  iou loss is negative .
![image](https://user-images.githubusercontent.com/11053628/101881816-eddec200-3bcf-11eb-8f8f-29b9d5eaf6a6.png)

**Comment by pycoco** [comment]
@AlexeyAB  when i use yolov4-custom cfg ,everything is ok now,but use yolov4-csp.cfg,loss is also very high，and iou loss is negative. when the iou loss can be negative ?

![image](https://user-images.githubusercontent.com/11053628/101893540-d8719400-3bdf-11eb-9bd7-0928e8969243.png)

**Comment by arnaud-nt2i** [comment]
Having high loss was not a problem but since  `a72bb05` "Show GIoU/IoU loss instead of RMSE by default"
I cannot resume my training, loss goes from where it was ~100 then to 800 then to 1600 to ... and then to nan !

**Comment by rabsym** [comment]
Using lastest master with 0.1% mAP after 1700 iterations, going back to an october commit and working as usual... 

![chart](https://user-images.githubusercontent.com/63374639/101948865-0b715300-3bf3-11eb-882e-c1288d0cafbb.png)

Any hint on this? Windows machine. Thanks.

**Comment by AlexeyAB** [comment]
@pycoco @arnaud-nt2i @rabsym 

* I added another fix for display of GIoU / IoU.

* About mAP. 
    * Attach your cfg-file
    * show training command

Now `yolov4-csp.cfg` and `yolov4x-mish.cfg` files should use `activation=logistic` instead of `activation=linear` before `[yolo]` layer

**Comment by rabsym** [comment]
@AlexeyAB Here you have cfg, is almost as standard

[yolov4-obj.zip](https://github.com/AlexeyAB/darknet/files/5681865/yolov4-obj.zip)

**Comment by AlexeyAB** [comment]
@rabsym Can you show chart.png for the october commit? To compare them.

**Comment by AlexeyAB** [comment]
@arnaud-nt2i 

> Having high loss was not a problem but since a72bb05 "Show GIoU/IoU loss instead of RMSE by default"
> I cannot resume my training, loss goes from where it was ~100 then to 800 then to 1600 to ... and then to nan !
> 
> Could RMSE or GIoU/IoU loss be a parameter?
> 
> I just took an older version and its fine now...

Use
```
[yolo]
show_details=0
```

**Comment by pycoco** [comment]
@AlexeyAB 
[yolov4-csp.txt](https://github.com/AlexeyAB/darknet/files/5682295/yolov4-csp.txt)
cfg file is almost as standard

./darknet detector train ./cfg/yolov4-csp.data ./cfg/yolov4-csp.cfg ./yolov4-csp.conv.142 -gpus 0,1,2,3 -dont_show

**Comment by AlexeyAB** [comment]
It seems I finaly found the bug: https://github.com/AlexeyAB/darknet/commit/b25c2c6cbdef3a849fd1f17eddfb5aa1387d868d

**Comment by rabsym** [comment]
@AlexeyAB Here is the working chart, lastest fix b25c2c6 is about this or mine is another different issue?

![chart01](https://user-images.githubusercontent.com/63374639/101977026-ee686e80-3c4a-11eb-8f07-ab3720bc59e0.png)

**Comment by marcoslucianops** [comment]
@AlexeyAB, it's only a visual bug? I'm training since 14 days ago and loss is above 64. I need restart my train?

**Comment by AlexeyAB** [comment]
@rabsym 

>Here is the working chart from october, lastest fix b25c2c6 is about this or mine is another different issue?

This bug https://github.com/AlexeyAB/darknet/issues/7097#issuecomment-743396756 is related to your problem. 
It is fixed now. Just download the latest code, recompile, and restart training: https://github.com/AlexeyAB/darknet/issues/7109

**Comment by rabsym** [comment]
@AlexeyAB Working as expected now, thanks so much for a good work!

Thought encountered and strange thing that maybe is normal and I didn't know but would like to ask you about.

map command results from a weights file (last.weights) not align with detector test with same weights file and test images. Usually doing this test after train with same results from map and detector. 

MAP results reads TP=41, FP=1, FN=2 while detector test finds 42 objects, not having any false positive and not find 1 object (TP=42, FP=0, FN=1) 

![image](https://user-images.githubusercontent.com/63374639/102013565-5903d200-3d51-11eb-8673-28029f5af383.png)

**Comment by AlexeyAB** [comment]
@rabsym 
> MAP results reads TP=41, FP=1, FN=2 while detector test finds 42 objects, not having any false positive and not find 1 object (TP=42, FP=0, FN=1)

What is the detector test? 
- ./darknet detector test... - uses confidence thrreshold 0.25 by default
- ./darknet detector map ... - uses confidence thrreshold 0.005 by default

Or do you mean that you get different mAP during training `./darknet detector train` and during manual map calculation `./darknet detector map` ?

**Comment by rabsym** [comment]
@AlexeyAB 

I use ./darknet detector map -thresh 0.25 (anyway looks like default value at least at windows build is 0.25) and get TP=41, FP=1, FN=2  

Later with ./darknet detector test... (over the same 25 valid images used in training) I compute (TP=42, FP=0, FN=1)

Regarding this, not tried but could happen that?

> "Or do you mean that you get different mAP during training ./darknet detector train and during manual map calculation ./darknet detector map ?

**Comment by AlexeyAB** [comment]
> Later with ./darknet detector test... (over the same 25 valid images used in training) I compute (TP=42, FP=0, FN=1)

May be you are doing this incorrectly. You should increase TP only if IoU > 0.5.
