### ISSUE TITLE
Should i keep training?

### ISSUE THREAD

**Issue by janoglezcampos** [AlexeyAB/darknet#7103]
**Hello everyone!**

I'm a little bit lost with all of this, this is my first time retraining a model with a really custom dataset, and I'm getting strange result, the avg loss doesn't go under ~10 and AP keep increasing. The thing is that i don't have that much resources to expend on cloud GPU for trainig, and my GPU is a 1060gtx with 6gb so training time is gold for me.

I have 2 datesets, both of them splited 80/20 for train/validation:
Dataset 1: 1000 images, all cropped to 416x416 with black bars
        * Train set augmented with hue modification and gray scale resulting on a 2091 images set.

Dataset 2: 1200 images, not cropped, not data augmented.

(The dataset has some missing annotations)
(The 1000 images on the first dataset came from the 12000 images dataset)

This are the results of the +- 6000 first batches:

- Dataset 1:
![chart_custom_cfg_last](https://user-images.githubusercontent.com/47823818/101741924-a91d3300-3aca-11eb-90a9-2872016e31de.png)

- Dataset 2:
![resize_chart](https://user-images.githubusercontent.com/47823818/101752043-4ed3a080-3ad1-11eb-8971-b3b89a1fcf46.png)
(the last mAP decreased)
I did a little experiment too, I tested the mAP of both best weights over the validation set of the 12000 (not cropped and not data augmented):

Trained with dataset 1, batch=64, 6000 batchs, 183 epoch best weights:
![Screenshot from 2020-12-10 09-51-17](https://user-images.githubusercontent.com/47823818/101749301-dddeb980-3acd-11eb-9141-2c2dac3c85c5.png)

Trained with dataset 2, batch=64, 5400 batchs, 36 epoch best weights:
![Screenshot from 2020-12-10 09-50-56](https://user-images.githubusercontent.com/47823818/101749308-dfa87d00-3acd-11eb-813b-d89008874496.png)

Its curious how the small dataset (being trained for 600 more epoch), gives better results on a set that doesn't even match the training average img resolution, i know darknet crop too to match 416x416 (if cfg is configured like that), but for sure is generalizing better than the second.

Adding more info to my problem, here is my cfg file: [https://drive.google.com/file/d/1FuThzUEzhHSDOZbSEBJxHgxCd79bw8oJ/view?usp=sharing](url)

Soo thats it, and my question is: Should I keep training 50 hours or there is no point on trying and i should change something before.

**Comment by Chitti21** [comment]
Hi.. @janoglezcampos 
 Did you continue training on dataset 2?
