### ISSUE TITLE
inference returns confidence values greater than 100%

### ISSUE THREAD

**Issue by stephanecharette** [AlexeyAB/darknet#7111]
When I run either of these commands:

- `./darknet detector test cfg/coco.data cfg/yolov4.cfg yolov4.weights data/person.jpg`
- `./darknet detect cfg/yolov4.cfg yolov4.weights data/person.jpg`

I'm getting values over 100%:

```
Done! Loaded 162 layers from weights-file 
 Detection layer: 139 - type = 28 
 Detection layer: 150 - type = 28 
 Detection layer: 161 - type = 28 
data/person.jpg: Predicted in 2951.865000 milli-seconds.
dog: 104%
person: 110%
horse: 101%
```

This is from the most recent version checked out and built just a few minutes ago:

```
> git log -1
commit b25c2c6cbdef3a849fd1f17eddfb5aa1387d868d (HEAD -> master, origin/master, origin/HEAD)
Author: AlexeyAB <kikots@mail.ru>
Date:   Sat Dec 12 05:52:58 2020 +0300

    Final training fix
```

First reported to me by huancayopower on Discord.

![image](https://user-images.githubusercontent.com/5061352/101977059-b2f48280-3bff-11eb-9330-e31db1c3ac22.png)

**Comment by AlexeyAB** [comment]
It seems it is related to this fixed bug: https://github.com/AlexeyAB/darknet/issues/7109
Just try to use the latest Darknet version.

**Comment by stephanecharette** [comment]
> It seems it is related to this fixed bug: #7109
> Just try to use the latest Darknet version.

Take a look at the version I'm using, Alexey.  I am using that version.  See the screenshot above.

**Comment by stephanecharette** [comment]
And just to make sure, I just tried again, and I'm getting the same results with no updates available:

```
stephane@2004-dev ~/darknet (master)> ./darknet detector test cfg/coco.data cfg/yolov4.cfg yolov4.weights data/person.jpg
[...]
data/person.jpg: Predicted in 3160.427000 milli-seconds.
dog: 104%
person: 110%
horse: 101%
stephane@2004-dev ~/darknet (master)> git log -1
commit b25c2c6cbdef3a849fd1f17eddfb5aa1387d868d (HEAD -> master, origin/master, origin/HEAD)
Author: AlexeyAB <kikots@mail.ru>
Date:   Sat Dec 12 05:52:58 2020 +0300

    Final training fix
stephane@2004-dev ~/darknet (master)> git pull
Already up to date.
stephane@2004-dev ~/darknet (master)> 
```

**Comment by AlexeyAB** [comment]
`dog: 104%` -  is definitely a bug that I fixed.

>And just to make sure, I just tried again, and I'm getting the same results with no updates available:

Did you recompile after git pull?
```
make clean
make
```

I don't have this issue:
`darknet detector test cfg/coco.data cfg/yolov4.cfg yolov4.weights data/person.jpg`
![image](https://user-images.githubusercontent.com/4096485/101997945-99c60180-3ce5-11eb-94ba-bb0b8d0337c8.png)

**Comment by stephanecharette** [comment]
Yes, I did make clean.  Just redid it again to make sure.

Is it a Windows/Linux difference?  I'm on Ubuntu 20.04.  I can test 18.04 as well later tonight.

Or maybe a CPU/GPU thing?  This is a VM I'm using, so I only have CPU.  These are the only changes that I have:

> git diff
diff --git a/Makefile b/Makefile
index 5fb7054..05ec536 100644
--- a/Makefile
+++ b/Makefile
@@ -1,10 +1,10 @@
 GPU=0
 CUDNN=0
 CUDNN_HALF=0
-OPENCV=0
-AVX=0
-OPENMP=0
-LIBSO=0
+OPENCV=1
+AVX=1
+OPENMP=1
+LIBSO=1
 ZED_CAMERA=0
 ZED_CAMERA_v2_8=0

Note that other users on Discord are having the same problem, so I'm certain it isn't just me.

**Comment by AlexeyAB** [comment]
@stephanecharette Thanks! I forgot to fix it for CPU. Now it is fixed: https://github.com/AlexeyAB/darknet/commit/a488131a1158665ec421ef258f55292127da1487

**Comment by stephanecharette** [comment]
Bingo.  Thanks, Alexey, it now works for me too:

```
data/person.jpg: Predicted in 2875.870000 milli-seconds.
dog: 99%
person: 100%
horse: 98%
```
