### ISSUE TITLE
About ASFF or Bifpn in Yolo

### ISSUE THREAD

**Issue by joe660** [AlexeyAB/darknet#7112]
May I ask the author,
Using ASFF in Yolo can improve performance. Do you have a cfg file that can be used directly in the yorknet version. 3Q!

**Comment by AlexeyAB** [comment]
Yes, sure: [yolov4-asff.cfg.txt](https://github.com/AlexeyAB/darknet/files/5684621/yolov4-asff.cfg.txt)

**Comment by AlexeyAB** [comment]
Yes, sure [yolov4-asff.cfg.txt](https://github.com/AlexeyAB/darknet/files/5684628/yolov4-asff.cfg.txt)

Just may be decrease `learning_rate=0.0001`

**Comment by joe660** [comment]
> Yes, sure [yolov4-asff.cfg.txt](https://github.com/AlexeyAB/darknet/files/5684628/yolov4-asff.cfg.txt)
> 
> Just may be decrease `learning_rate=0.0001`

[scale_channels]
from=-11
scale_wh=1

Thank you for your reply. I use the pytorch version of yolov4 which you recommend. [scale_ channels] , There is no cfg file before this. How to define and use it

**Comment by joe660** [comment]
> Yes, sure [yolov4-asff.cfg.txt](https://github.com/AlexeyAB/darknet/files/5684628/yolov4-asff.cfg.txt)
> 
> Just may be decrease `learning_rate=0.0001`

Thank you for your reply..Can we use it directly in yorknet version asff.cfg Documents?  [scale_ channels] , There is no cfg file before this. How to define and use it scale_ Wh = 1, what do you mean? thank you

**Comment by AlexeyAB** [comment]
What is the ` yorknet version asff.cfg Documents` ?

About `scale_wh=1` https://github.com/AlexeyAB/darknet/wiki/CFG-Parameters-in-the-different-layers

>scale_wh=0 - SE-layer (previous layer 1x1xC), scale_wh=1 - ASFF-layer (previous layer WxHx1)

**Comment by joe660** [comment]
I see. There seems to be no definition in the yolov4 version of Wong kinyiu that you recommend. scale_ Wh = 1, can't use ASFF, do not know how to solve?

**Comment by joe660** [comment]
> What is the ` yorknet version asff.cfg Documents` ?
> 
> About `scale_wh=1` https://github.com/AlexeyAB/darknet/wiki/CFG-Parameters-in-the-different-layers
> 
> > scale_wh=0 - SE-layer (previous layer 1x1xC), scale_wh=1 - ASFF-layer (previous layer WxHx1)
