### ISSUE TITLE
input size of yolov4-csp in readme

### ISSUE THREAD

**Issue by syjeon121** [AlexeyAB/darknet#7119]
@AlexeyAB hi, two images below are the readme and a table of your paper.
I think the input size 608 and 640 are the same model, right?

![image](https://user-images.githubusercontent.com/43084198/102052031-e0704480-3e28-11eb-89ae-0437d8267b0e.png)

![image](https://user-images.githubusercontent.com/43084198/102052068-f3831480-3e28-11eb-9eab-ed7a57228bba.png)

**Comment by AlexeyAB** [comment]
@syjeon121 Hi, thanks! I fixed it: https://github.com/AlexeyAB/darknet#pre-trained-models
It should be 640x640

**Comment by syjeon121** [comment]
thanks!
