### ISSUE TITLE
csp-p7x-mish.cfg fails in training detector

### ISSUE THREAD

**Issue by praneet195** [AlexeyAB/darknet#7129]
I have made the following changes to the csp-p7x-mish.cfg:
width = 640
height = 480
Since, I only have one class , I've also changed the number of filters before each yolo layer to  filters=18 and classes = 1
When, I run my detector for training i run into the following erros:
`
 244 route  243 241 The width and height of the input layers are different.
                                   ->    0 x   0 x   0
 245 Layer before convolutional layer must output image.: File exists
darknet: ./src/utils.c:326: error: Assertion `0' failed.
Aborted (core dumped)
`
Any idea why this is happening?

**Comment by AlexeyAB** [comment]
Calculate: `filters=(5 + classes)*4`

So use `filters=24` in your case. And use this pre-trained weights file https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/cspx-p7-mish_hp.344.conv

**Comment by praneet195** [comment]
Thank you!!!

**Comment by namasang1** [comment]
> Thank you!!!

could you solve the problem??
