### ISSUE TITLE
[yolo] section params for full support yolov4 and yolov4x-mish on DeepStream SDK

### ISSUE THREAD

**Issue by marcoslucianops** [AlexeyAB/darknet#7141]
Hi, I would like to know, if possible, which of the new parameters used in the [yolo] section in the new yolov4 and yolo 4x-mish are used for detection, more specifically these parameters:

objectness_smooth
scale_x_y
resize
iou_thresh
iou_normalizer
cls_normalizer
obj_normalizer
iou_loss
nms_kind
beta_nms
new_coords
max_delta

beta_nms changes default 0.45 nms to 0.6?
iou_thresh changes default 0.25 conf_thresh to 0.2?

Thanks

**Comment by AlexeyAB** [comment]
New parameters from yolov4.cfg to yolov4-csp.cfg/yolov4x-mish.cfg are: `objectness_smooth`, `new_coords`, `obj_normalizer`


The most of these parameters are used during training only.
For both training and detection are used only: `new_coords`, `scale_x_y`, `beta_nms`

**Comment by marcoslucianops** [comment]
@AlexeyAB,

About [convolutional] activation=logistic in yolov4x-mish and yolov4-csp, do these models use this activation? Because, when I set activation sigmoid for this layer, on deepstream, i can't run the generated model. When I bypass activation (setting to activation=linear), the model runs.

Thanks

**Comment by AlexeyAB** [comment]
> About [convolutional] activation=logistic in yolov4x-mish and yolov4-csp, do these models use this activation? 

Yes.



>  i can't run the generated model. 

Do you mean that Deepstream doesn't support logistic activation?
What error do you see?

**Comment by marcoslucianops** [comment]
> Do you mean that Deepstream doesn't support logistic activation?

DeepStream supports logistic/sigmoid activation. But I I use the sigmoid activation in last convolutional layer, the FPS drops to 0 and I can't run demo.

<details><summary>With sigmoid/logistic activation (yolov4x-mish):</summary>

![DeepStream](https://user-images.githubusercontent.com/47423225/102557732-9dbd9f00-40aa-11eb-874f-a0e9ded7f0b6.png)
![Terminal](https://user-images.githubusercontent.com/47423225/102557740-a0b88f80-40aa-11eb-81ad-45f7eb950694.png)

</details>

<details><summary>With linear activation (yolov4x-mish):</summary>

![DeepStream](https://user-images.githubusercontent.com/47423225/102557947-1c1a4100-40ab-11eb-9bf5-a2475c043ada.png)
![Terminal](https://user-images.githubusercontent.com/47423225/102557957-20465e80-40ab-11eb-865e-1133e734cfbf.png)

</details>

<details><summary>I edit the kernel to:</summary>

```
    float alpha = scale;
    float beta = -0.5 * (scale - 1);

    if (new_coords == 1) {
        output[bbindex + numGridCells * (z_id * (5 + numOutputClasses) + 0)]
            = sigmoidGPU(input[bbindex + numGridCells * (z_id * (5 + numOutputClasses) + 0)]) * alpha + beta;

        output[bbindex + numGridCells * (z_id * (5 + numOutputClasses) + 1)]
            = sigmoidGPU(input[bbindex + numGridCells * (z_id * (5 + numOutputClasses) + 1)]) * alpha + beta;

        output[bbindex + numGridCells * (z_id * (5 + numOutputClasses) + 2)]
            = pow(sigmoidGPU(input[bbindex + numGridCells * (z_id * (5 + numOutputClasses) + 2)]) * 2, 2);

        output[bbindex + numGridCells * (z_id * (5 + numOutputClasses) + 3)]
            = pow(sigmoidGPU(input[bbindex + numGridCells * (z_id * (5 + numOutputClasses) + 3)]) * 2, 2);
    }
    else {
        output[bbindex + numGridCells * (z_id * (5 + numOutputClasses) + 0)]
            = sigmoidGPU(input[bbindex + numGridCells * (z_id * (5 + numOutputClasses) + 0)]) * alpha + beta;

        output[bbindex + numGridCells * (z_id * (5 + numOutputClasses) + 1)]
            = sigmoidGPU(input[bbindex + numGridCells * (z_id * (5 + numOutputClasses) + 1)]) * alpha + beta;

        output[bbindex + numGridCells * (z_id * (5 + numOutputClasses) + 2)]
            = __expf(input[bbindex + numGridCells * (z_id * (5 + numOutputClasses) + 2)]);

        output[bbindex + numGridCells * (z_id * (5 + numOutputClasses) + 3)]
            = __expf(input[bbindex + numGridCells * (z_id * (5 + numOutputClasses) + 3)]);
    }

    output[bbindex + numGridCells * (z_id * (5 + numOutputClasses) + 4)]
        = sigmoidGPU(input[bbindex + numGridCells * (z_id * (5 + numOutputClasses) + 4)]);

    for (uint i = 0; i < numOutputClasses; ++i)
    {
        output[bbindex + numGridCells * (z_id * (5 + numOutputClasses) + (5 + i))]
            = sigmoidGPU(input[bbindex + numGridCells * (z_id * (5 + numOutputClasses) + (5 + i))]);
    }
```

</details>

Use sigmoid function in pW and pH, is the same as logistic activation in conv layer?

**Comment by AlexeyAB** [comment]
> Use sigmoid function in pW and pH, is the same as logistic activation in conv layer?

Yes.
You shouldn't use  logistic activation in conv layer, because you already use sigmoidGPU in Yolo-layer.

It will work slightly faster if you remove all `sigmoidGPU` from `if (new_coords == 1) { ... }` and will use logistic activation in the conv layers.

**Comment by marcoslucianops** [comment]
> > Use sigmoid function in pW and pH, is the same as logistic activation in conv layer?
> 
> Yes.
> You shouldn't use logistic activation in conv layer, because you already use sigmoidGPU in Yolo-layer.
> 
> It will work slightly faster if you remove all `sigmoidGPU` from `if (new_coords == 1) { ... }` and will use logistic activation in the conv layers.

when new_coords = 1, does the last convolutional layer always use activation = logistic?

**Comment by AlexeyAB** [comment]
Yes, it should be always, at least for all current models.


`[convolutional] activation=logistic` and `[yolo] new_coords=1` should be used together.

**Comment by AlexeyAB** [comment]
What is the difference between https://github.com/NVIDIA-AI-IOT/yolov4_deepstream and your https://github.com/marcoslucianops/DeepStream-Yolo ?
Did you involved in creating both implementations?

**Comment by marcoslucianops** [comment]
> What is the difference between https://github.com/NVIDIA-AI-IOT/yolov4_deepstream and your https://github.com/marcoslucianops/DeepStream-Yolo ?

I created code to generate TensorRT model directly from yolov4 cfg and weights. I'm updating my repo to support full cfg parse (without need any changes in nvdsparsebbox_Yolo.cpp or another file), scale_x_y and new_coords this week.

> Did you participate in the creation of both implementations?

No, my code is different from NVIDIA-AI-IOT repo.

**Comment by AlexeyAB** [comment]
I added URL to your repo: https://github.com/AlexeyAB/darknet#yolo-v4-in-other-frameworks

**Comment by marcoslucianops** [comment]
> I added URL to your repo: https://github.com/AlexeyAB/darknet#yolo-v4-in-other-frameworks

Thanks
