### ISSUE TITLE
Is this training process right?

### ISSUE THREAD

**Issue by pervin0527** [AlexeyAB/darknet#7145]
![chart_yolov4-custom_coco](https://user-images.githubusercontent.com/43873288/102442473-d2f4cd80-4067-11eb-8086-4d415fae7599.png)

First of all, I am not good at English. Please understand if the sentence is weird.

what dataset do you use?
i'm try to train the coco2017 dataset with yolov4. but avg loss looks weird. 
So you guys see what I've tried and tell me what was wrong
-  what command do you use?

      ./darknet detector train data/obj.data yolo-obj.cfg csdarknet53-omega.conv.105

csdarknet53-omega.conv.105 was created by looking at that link.
[https://github.com/AlexeyAB/darknet/wiki/Train-Detector-on-MS-COCO-(trainvalno5k-2014)-dataset#required-files](https://github.com/AlexeyAB/darknet/wiki/Train-Detector-on-MS-COCO-(trainvalno5k-2014)-dataset#required-files)

1. coodrinate convert to yolo format (In my case VOC_format to YOLO_format(txt))

        def convert_coordinates(img_width, img_height, xmin, ymin, xmax, ymax):
            x_center = (xmin + xmax) / (2 * img_width)
            y_center = (ymin + ymax) / (2 * img_height)
            width = (xmax - xmin) / img_width
            height = (ymax - ymin) / img_height
        
            return (x_center, y_center, width, height)

2. obj.data
- classes= 80
- train  = /home/v100/tf_workspace/darknet/build/darknet/x64/data/coco2017_train.txt
- valid  = /home/v100/tf_workspace/darknet/build/darknet/x64/data/coco2017_test.txt
- names = /home/v100/tf_workspace/darknet/build/darknet/x64/data/coco2017_obj.names
- backup = /home/v100/tf_workspace/darknet/weights/COCO2017_2020.12.17

3. yolov4.cfg
This was downloaded from the link, and only the width and height were modified.
[https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4.cfg](https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4.cfg)

        [net]
        batch=64
        subdivisions=8
        # Training
        width=512
        height=512
        channels=3
        momentum=0.949
        decay=0.0005
        angle=0
        saturation = 1.5
        exposure = 1.5
        hue=.1
        
        learning_rate=0.0013
        burn_in=1000
        max_batches = 500500
        policy=steps
        steps=400000,450000
        scales=.1,.1
        
        #cutmix=1
        mosaic=1
        
        #:104x104 54:52x52 85:26x26 104:13x13 for 416
        
        [convolutional]
        batch_normalize=1
        filters=32
        size=3
        stride=1
        pad=1
        activation=mish
        
        # Downsample
        
        [convolutional]
        batch_normalize=1
        filters=64
        size=3
        stride=2
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=64
        size=1
        stride=1
        pad=1
        activation=mish
        
        [route]
        layers = -2
        
        [convolutional]
        batch_normalize=1
        filters=64
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=32
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=64
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        [convolutional]
        batch_normalize=1
        filters=64
        size=1
        stride=1
        pad=1
        activation=mish
        
        [route]
        layers = -1,-7
        
        [convolutional]
        batch_normalize=1
        filters=64
        size=1
        stride=1
        pad=1
        activation=mish
        
        # Downsample
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=3
        stride=2
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=64
        size=1
        stride=1
        pad=1
        activation=mish
        
        [route]
        layers = -2
        
        [convolutional]
        batch_normalize=1
        filters=64
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=64
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=64
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        [convolutional]
        batch_normalize=1
        filters=64
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=64
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        [convolutional]
        batch_normalize=1
        filters=64
        size=1
        stride=1
        pad=1
        activation=mish
        
        [route]
        layers = -1,-10
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=1
        stride=1
        pad=1
        activation=mish
        
        # Downsample
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=3
        stride=2
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=1
        stride=1
        pad=1
        activation=mish
        
        [route]
        layers = -2
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=1
        stride=1
        pad=1
        activation=mish
        
        [route]
        layers = -1,-28
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=1
        stride=1
        pad=1
        activation=mish
        
        # Downsample
        
        [convolutional]
        batch_normalize=1
        filters=512
        size=3
        stride=2
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=1
        stride=1
        pad=1
        activation=mish
        
        [route]
        layers = -2
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=1
        stride=1
        pad=1
        activation=mish
        
        [route]
        layers = -1,-28
        
        [convolutional]
        batch_normalize=1
        filters=512
        size=1
        stride=1
        pad=1
        activation=mish
        
        # Downsample
        
        [convolutional]
        batch_normalize=1
        filters=1024
        size=3
        stride=2
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=512
        size=1
        stride=1
        pad=1
        activation=mish
        
        [route]
        layers = -2
        
        [convolutional]
        batch_normalize=1
        filters=512
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=512
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=512
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        [convolutional]
        batch_normalize=1
        filters=512
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=512
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        [convolutional]
        batch_normalize=1
        filters=512
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=512
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        [convolutional]
        batch_normalize=1
        filters=512
        size=1
        stride=1
        pad=1
        activation=mish
        
        [convolutional]
        batch_normalize=1
        filters=512
        size=3
        stride=1
        pad=1
        activation=mish
        
        [shortcut]
        from=-3
        activation=linear
        
        [convolutional]
        batch_normalize=1
        filters=512
        size=1
        stride=1
        pad=1
        activation=mish
        
        [route]
        layers = -1,-16
        
        [convolutional]
        batch_normalize=1
        filters=1024
        size=1
        stride=1
        pad=1
        activation=mish
        
        ##########################
        
        [convolutional]
        batch_normalize=1
        filters=512
        size=1
        stride=1
        pad=1
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        size=3
        stride=1
        pad=1
        filters=1024
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        filters=512
        size=1
        stride=1
        pad=1
        activation=leaky
        
        ### SPP ###
        [maxpool]
        stride=1
        size=5
        
        [route]
        layers=-2
        
        [maxpool]
        stride=1
        size=9
        
        [route]
        layers=-4
        
        [maxpool]
        stride=1
        size=13
        
        [route]
        layers=-1,-3,-5,-6
        ### End SPP ###
        
        [convolutional]
        batch_normalize=1
        filters=512
        size=1
        stride=1
        pad=1
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        size=3
        stride=1
        pad=1
        filters=1024
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        filters=512
        size=1
        stride=1
        pad=1
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=1
        stride=1
        pad=1
        activation=leaky
        
        [upsample]
        stride=2
        
        [route]
        layers = 85
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=1
        stride=1
        pad=1
        activation=leaky
        
        [route]
        layers = -1, -3
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=1
        stride=1
        pad=1
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        size=3
        stride=1
        pad=1
        filters=512
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=1
        stride=1
        pad=1
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        size=3
        stride=1
        pad=1
        filters=512
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=1
        stride=1
        pad=1
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=1
        stride=1
        pad=1
        activation=leaky
        
        [upsample]
        stride=2
        
        [route]
        layers = 54
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=1
        stride=1
        pad=1
        activation=leaky
        
        [route]
        layers = -1, -3
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=1
        stride=1
        pad=1
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        size=3
        stride=1
        pad=1
        filters=256
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=1
        stride=1
        pad=1
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        size=3
        stride=1
        pad=1
        filters=256
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        filters=128
        size=1
        stride=1
        pad=1
        activation=leaky
        
        ##########################
        
        [convolutional]
        batch_normalize=1
        size=3
        stride=1
        pad=1
        filters=256
        activation=leaky
        
        [convolutional]
        size=1
        stride=1
        pad=1
        filters=255
        activation=linear
        
        
        [yolo]
        mask = 0,1,2
        anchors = 12, 16, 19, 36, 40, 28, 36, 75, 76, 55, 72, 146, 142, 110, 192, 243, 459, 401
        classes=80
        num=9
        jitter=.3
        ignore_thresh = .7
        truth_thresh = 1
        scale_x_y = 1.2
        iou_thresh=0.213
        cls_normalizer=1.0
        iou_normalizer=0.07
        iou_loss=ciou
        nms_kind=greedynms
        beta_nms=0.6
        max_delta=5
        
        
        [route]
        layers = -4
        
        [convolutional]
        batch_normalize=1
        size=3
        stride=2
        pad=1
        filters=256
        activation=leaky
        
        [route]
        layers = -1, -16
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=1
        stride=1
        pad=1
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        size=3
        stride=1
        pad=1
        filters=512
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=1
        stride=1
        pad=1
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        size=3
        stride=1
        pad=1
        filters=512
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        filters=256
        size=1
        stride=1
        pad=1
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        size=3
        stride=1
        pad=1
        filters=512
        activation=leaky
        
        [convolutional]
        size=1
        stride=1
        pad=1
        filters=255
        activation=linear
        
        
        [yolo]
        mask = 3,4,5
        anchors = 12, 16, 19, 36, 40, 28, 36, 75, 76, 55, 72, 146, 142, 110, 192, 243, 459, 401
        classes=80
        num=9
        jitter=.3
        ignore_thresh = .7
        truth_thresh = 1
        scale_x_y = 1.1
        iou_thresh=0.213
        cls_normalizer=1.0
        iou_normalizer=0.07
        iou_loss=ciou
        nms_kind=greedynms
        beta_nms=0.6
        max_delta=5
        
        
        [route]
        layers = -4
        
        [convolutional]
        batch_normalize=1
        size=3
        stride=2
        pad=1
        filters=512
        activation=leaky
        
        [route]
        layers = -1, -37
        
        [convolutional]
        batch_normalize=1
        filters=512
        size=1
        stride=1
        pad=1
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        size=3
        stride=1
        pad=1
        filters=1024
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        filters=512
        size=1
        stride=1
        pad=1
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        size=3
        stride=1
        pad=1
        filters=1024
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        filters=512
        size=1
        stride=1
        pad=1
        activation=leaky
        
        [convolutional]
        batch_normalize=1
        size=3
        stride=1
        pad=1
        filters=1024
        activation=leaky
        
        [convolutional]
        size=1
        stride=1
        pad=1
        filters=255
        activation=linear
        
        
        [yolo]
        mask = 6,7,8
        anchors = 12, 16, 19, 36, 40, 28, 36, 75, 76, 55, 72, 146, 142, 110, 192, 243, 459, 401
        classes=80
        num=9
        jitter=.3
        ignore_thresh = .7
        truth_thresh = 1
        random=1
        scale_x_y = 1.05
        iou_thresh=0.213
        cls_normalizer=1.0
        iou_normalizer=0.07
        iou_loss=ciou
        nms_kind=greedynms
        beta_nms=0.6
        max_delta=5

**Comment by pervin0527** [comment]
After seeing this article, I git pull and build again.
Then, when I started learning again, the graph appeared normally. Thank you.

    https://discord.com/channels/741676058666860635/741683683077128223

**Comment by dek8v5** [comment]
Hi, I encountered the same problem. 
which article did you see? I tried to open the discord link, it doesn't work even tho I logged in. Thanks

**Comment by pervin0527** [comment]
> Hi, I encountered the same problem.
> which article did you see? I tried to open the discord link, it doesn't work even tho I logged in. Thanks

Hello, @dek8v5
It's a pity that the attached Discord link doesn't open.
So I attached a link to that issue https://github.com/AlexeyAB/darknet/issues/7109
Anyway, I just did **pull darknet** and **build** again.
When I did that, I was able to achieve the desired result.
![chart](https://user-images.githubusercontent.com/43873288/103538682-0645b200-4eda-11eb-8ce4-489132ec9d58.png)

I hope this helps you.
