### ISSUE TITLE
Same Image, Different Results

### ISSUE THREAD

**Issue by maybepossible** [AlexeyAB/darknet#715]
I use yolo V3 to detect cars.  I test one image several times, most trials with the model trained by myself can not find the target, but sometimes(maybe three in ten times) it did. Could you give me some hints about it?

**Comment by AlexeyAB** [comment]
Just do everything that described here: https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

**Comment by maybepossible** [comment]
Should I set jitter=0, random =0 during inference? Thanks in advance.
[yolo]
mask = 0,1,2
anchors = 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326
classes=80
num=9
jitter=.3
ignore_thresh = .5
truth_thresh = 1
random=1

**Comment by AlexeyAB** [comment]
* Did you change any line in the source code?
* What command do you use for detection?
* What OS and params in your Makefile?
* What version of CUDA, cuDNN, OpenCV?
* Can you show screenshot with the same image and different results?

**Comment by maybepossible** [comment]
Thanks for your reply, After I set random =0, jitter=0, the results are stable.
