### ISSUE TITLE
When adding SiameseNetwork?

### ISSUE THREAD

**Issue by wwzh2015** [AlexeyAB/darknet#7152]
The siamese networks based on DarknetAB for calculate the image similarity of the two?

**Comment by AlexeyAB** [comment]
Is there any paper with comparison, what is better for comparison image similarity?
* or siamse network with 2 inputs
* or network with 1 input and output with embeddings which can be compared by using cosine similarity (it is trained by using contrastive loss)

**Comment by wwzh2015** [comment]
> Is there any paper with comparison, what is better for comparison image similarity?
> 
> * or siamse network with 2 inputs
> * or network with 1 input and output with embeddings which can be compared by using cosine similarity (it is trained by using contrastive loss)
the SiameseNetwork is popular for multi-class classification，
but the darknet only to object detection？it's too cult.

**Comment by Hwijune** [comment]
> > Is there any paper with comparison, what is better for comparison image similarity?
> 
> refer：https://link.springer.com/chapter/10.1007/978-3-319-48881-3_56
> the SiameseNetwork is popular for multi-class classification in small sample，
> but the darknet only to object detection？it's so narrow.

Extract each object's vector, and calculate the cosine similarity

``
float cosine_similarity(int *A, int *B, int Vector_Length)
{
    float dot = 0.0, denom_a = 0.0, denom_b = 0.0 ;
     for(int i = 0; i < Vector_Length; ++i) {
         dot += A[i] * B[i] ;
         denom_a += A[i] * A[i] ;
         denom_b += B[i] * B[i] ;
    }
    return dot / (sqrt(denom_a) * sqrt(denom_b)) ;
}
``

**Comment by wwzh2015** [comment]
> > > Is there any paper with comparison, what is better for comparison image similarity?
> > 
> > 
> > refer：https://link.springer.com/chapter/10.1007/978-3-319-48881-3_56
> > the SiameseNetwork is popular for multi-class classification in small sample，
> > but the darknet only to object detection？it's so narrow.
> 
> Extract each object's vector, and calculate the cosine similarity
> 
> ```
> float cosine_similarity(int *A, int *B, int Vector_Length)
> {
>     float dot = 0.0, denom_a = 0.0, denom_b = 0.0 ;
>      for(int i = 0; i < Vector_Length; ++i) {
>          dot += A[i] * B[i] ;
>          denom_a += A[i] * A[i] ;
>          denom_b += B[i] * B[i] ;
>     }
>     return dot / (sqrt(denom_a) * sqrt(denom_b)) ;
> }
> ```
where in the network?

**Comment by Hwijune** [comment]
> > > > Is there any paper with comparison, what is better for comparison image similarity?
> > > 
> > > 
> > > refer：https://link.springer.com/chapter/10.1007/978-3-319-48881-3_56
> > > the SiameseNetwork is popular for multi-class classification in small sample，
> > > but the darknet only to object detection？it's so narrow.
> > 
> > 
> > Extract each object's vector, and calculate the cosine similarity
> > ```
> > float cosine_similarity(int *A, int *B, int Vector_Length)
> > {
> >     float dot = 0.0, denom_a = 0.0, denom_b = 0.0 ;
> >      for(int i = 0; i < Vector_Length; ++i) {
> >          dot += A[i] * B[i] ;
> >          denom_a += A[i] * A[i] ;
> >          denom_b += B[i] * B[i] ;
> >     }
> >     return dot / (sqrt(denom_a) * sqrt(denom_b)) ;
> > }
> > ```
> 
> where in the network?

you can use any purpose-trained classification network.
