### ISSUE TITLE
how to train with yolov3-spp,I want to use pre-train weights

### ISSUE THREAD

**Issue by futureflsl** [AlexeyAB/darknet#7178]
I use commnad
./darkent partial cfg/yolov3-spp.cfg Yolov3-spp.weight yolov3-spp.conv.15 15
But yolov3-spp.conv.15  size is just 3.6MB.So how to get pre-train weights?

**Comment by lsd1994** [comment]
same as yolov3 pre-train weights

**Comment by futureflsl** [comment]
> same as yolov3 pre-train weights

thanks,I have a try
