### ISSUE TITLE
smallest object size and the accuracy of the model

### ISSUE THREAD

**Issue by k00r** [AlexeyAB/darknet#718]
Hello Alexey =) when annotating do we have a limit for what the smallest object should be,or can we say small objects that are annotated beyond a certain size will decrease the models overall accuracy in the end?Keep in mind that of course i'm not annotating 5x5 windows or likes =D This question was bugging me for some time i'll be glad if you answer it.

Thanks.

**Comment by AlexeyAB** [comment]
@k00r Hi,
You can use any window in the training dataset. 
But you should know, that if the `object_width < image_width / network_width` then after resizieng image to the network size, this object will be smaller than 1 pixel, so network can't be trained for it, but this label will be rejected automatically, don't worry about it: https://github.com/AlexeyAB/darknet/blob/5e3dcb6f34868e341466b57b13ad63f86b337250/src/data.c#L336

But if there are objects with `object_width < image_width / network_width` in the validation dataset, then these object willn't be rejected and can't be detected, and it will show low accuracy.

I trained my model with the network resolution 1024x1024 and object size 1x1 pixel on 1024x1024 images, and it works fine with mAP ~= 65 - 70%.

**Comment by k00r** [comment]
so basically i can annotate any size in my training dataset just not too small and it won't affect the detection accuracy?

**Comment by AlexeyAB** [comment]
@k00r It dependson your tast. My task requires very small objects, otherwise this task doesn't matter.

But if you want to get formal high accuracy, then yes, you should avoid very small objects in the training and validation datasets.

**Comment by k00r** [comment]
Thanks @AlexeyAB  =)
