### ISSUE TITLE
Question: Can I train with images that are the same size as the bounding box of the object, and have no background?

### ISSUE THREAD

**Issue by aidamanzano** [AlexeyAB/darknet#7180]
I am training yolo on a custom dataset of faces where the images have been cropped to a square ratio and the face lies in the centre. This means that effectively, my images are the same size as the bounding boxes.
For example with this image 
![image](https://user-images.githubusercontent.com/40214590/103152497-70df4b00-4780-11eb-8194-cf5ec84ef950.png)

The data I have is the following:
x = 134, y = 134, width = 899, weight = 899.

I read on your repo that the coordinates should be relative so I calculated relative x=x/width and relative y=y/height. For relative width and height they equal 1 because the height and width of the object is the same as the height and width of the image.

My new data would be:
x = 0.149054505, y = 0.149054505, width = 1, height = 1

I wanted to ask if training yolo with images the size of the object with no background is a problem, and if it is not, what are the parameters I need to change on the cfg file to reflect this?

Thank you in advance!

**Comment by stephanecharette** [comment]
1) If your X and Y are not exactly zero, then your width and height should not be exactly 1.
2) See this:  https://www.ccoderun.ca/programming/darknet_faq/#crop_training_images

**Comment by k00r** [comment]
no it should be like this in your annotation file
<object id> 0.5 0.5 1 1

**Comment by aidamanzano** [comment]
Thank you both, I realised that in fact all my annotations are going to be 0.5, 0.5, 0.87, 0.87 because they include a 15% increase of the object in the bounding box. Thank you @stephanecharette for the links, they're really useful. I think for this purpose the model will work fine, as I will be using it to take photos of myself to detect the facial expression, so I will simply post process the photo to be the same size and format as the ones I have to train the model. Thank you both for your replies!
