### ISSUE TITLE
calculating map gets stuck

### ISSUE THREAD

**Issue by k00r** [AlexeyAB/darknet#7184]
![image](https://user-images.githubusercontent.com/38154308/103176768-be91ab80-4885-11eb-8f98-90b168022e5c.png)

Hello @AlexeyAB 
my training gets stuck like this at 1000th iteration (first map calculation),my CPU load is around %25 and GPU load is %0 when this happens,nothing happens when i press enter,i'm using the vcpkg version which i installed 2 days ago successfully,it sees opencv,cuda and cudnn versions correctly,below is my cfg file
Any help is much appreciated =)

[yolov4-csp.txt](https://github.com/AlexeyAB/darknet/files/5744913/yolov4-csp.txt)

**Comment by stephanecharette** [comment]
As I wrote to you in discord:

> Stéphane: does it do anything if you press ENTER?
> Stéphane: There are places in the code where it waits for keyboard input if it encounters a serious error.
> Stéphane: how large is your data set, and how many images do you have in your validation set?
> Stéphane: cause at 1000 would be the first time it writes a .weights file to disk, and it would also have to calculate the mAP if you ran with -map

**Comment by AlexeyAB** [comment]
How big is your dataset?
Did you change anything in source code?
Do you use the latest version of Darknet?

**Comment by Whisper94** [comment]
Hello @AlexeyAB 
I had the same issue after I've changed calculation mAP after each 100 iterations in detector.c and saving weights after each 100 iterations. 
I've solved it after changing "1. mAP calculation at 200 iterations". If I try to use weights with 100 iterations for mAP calculation it gets stuck also after training. Probably a same bug?
P.S.: I've compiled darknet with VS darknet.sln

**Comment by k00r** [comment]
@AlexeyAB 
1) 237 images,1000 boxes (i wasn't having this error with the previous versions of this repo with the same dataset)
2) No
3)yes,i installed it with vcpkg 3 days ago

**Comment by k00r** [comment]
@Whisper94 how did you change the map calculation interval?

**Comment by Whisper94** [comment]
@k00r you have a small dataset like me. My issue Was that my mAP drops after ~1000 iterations down from 90+% to ~0% because of it I changed in detector.c (folder scr) number of iterations for save weights and calc_map for lower value. Just try. Probably it could help you

**Comment by k00r** [comment]
issue solved by using the correct weights file with the correct cfg file for training
