### ISSUE TITLE
When we support: NVIDIA GeForce RTX 3060 Ti???

### ISSUE THREAD

**Issue by badpaybad** [AlexeyAB/darknet#7187]
Sorry if I bothered you

I saw this in Makefile, When we support: NVIDIA GeForce RTX 3060 Ti ???
            # GeForce RTX 3070, 3080, 3090
            # ARCH= -gencode arch=compute_86,code=[sm_86,compute_86]

**Comment by Studds-PM** [comment]
@badpaybad I think the value of arch is the same as 8.6 for NVIDIA GeForce RTX 3060 Ti also.
Have you faced any issues while building?

**Comment by marcoslucianops** [comment]
![image](https://user-images.githubusercontent.com/47423225/103219588-e708bc80-48fc-11eb-86d6-f4e31cb54b70.png)

It's the same for all RTX 3000 series

**Comment by badpaybad** [comment]
I built done, no error. But when I run in computer with gtx 3060 I got hang up.
I my other computer with gtx 2070 still working.

here is computer with gtx 3060.
![image](https://user-images.githubusercontent.com/6204507/103254571-61e2dd80-49b8-11eb-93e7-b27ecf3490a3.png)

**Comment by marcoslucianops** [comment]
> I built done, no error. But when I run in computer with gtx 3060 I got hang up.
> 
> I my other computer with gtx 2070 still working.
> 
> 
> 
> here is computer with gtx 3060.
> 
> ![image](https://user-images.githubusercontent.com/6204507/103254571-61e2dd80-49b8-11eb-93e7-b27ecf3490a3.png)
> 
> 

I think you should test with newer cudnn (8.0+).

**Comment by badpaybad** [comment]
I tried install new version of cuda (11.1) and cudnn 
But after run build.ps1 
I still got old one cudnn64_7.dll. Which step am I missing?

![image](https://user-images.githubusercontent.com/6204507/103348821-bfb51980-4acd-11eb-96a9-1a9ef17e4fa8.png)

**Comment by badpaybad** [comment]
Tks I can upgraded now. I were pull new git darknet 
And modify Makefile
ARCH= -gencode arch=compute_35,code=sm_35 \
      -gencode arch=compute_50,code=[sm_50,compute_50] \
      -gencode arch=compute_52,code=[sm_52,compute_52] \
	  -gencode arch=compute_61,code=[sm_61,compute_61] \
	  -gencode arch=compute_86,code=[sm_86,compute_86]

**Comment by asfarley** [comment]
@badpaybad Did you get this to work using master branch? Was pulling darknet the only change? I've followed the vcpkg build instructions exactly and it's not working on my RTX3070, but it's working on a GTX2070 exactly as you described. 

I previously tried building with only -gencode arch=compute_86,code=[sm_86,compute_86] but it seemed to make no difference. 

Which version of cudnn do you have installed? Did you have to copy and paste the cudnn files into "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1"?

**Comment by badpaybad** [comment]
Yes I pulled master aloso installed cuda 11.1 and copied cudnn.
I working mostly in c# , now I trying to learn c/c++ to understand the code. 
![image](https://user-images.githubusercontent.com/6204507/103348821-bfb51980-4acd-11eb-96a9-1a9ef17e4fa8.png)

**Comment by asfarley** [comment]
@badpaybad  Thanks, I'm using C# too - I eventually got it working using the CMake build process.
