### ISSUE TITLE
Darknet memory keeps increasing

### ISSUE THREAD

**Issue by cccmdls** [AlexeyAB/darknet#719]
Hi Alexey. Here is the problem.
When I start to use darknet, It only takes me 15.4% memory.
![time1](https://user-images.githubusercontent.com/22991938/39406393-aad226cc-4ba5-11e8-9f61-ced43a1fd82b.png)
1 minute later, it takes me 38.4% memory
![time2](https://user-images.githubusercontent.com/22991938/39406405-c86efab6-4ba5-11e8-9036-288c3a9c60ad.png)
2 minutes later, it takes me 72.9% memory
![time4](https://user-images.githubusercontent.com/22991938/39406422-f845e664-4ba5-11e8-9698-b9532a45c37f.png)

At the end, this process was killed by the system.
I can't figure out why this process's memory keeps increasing. Can you help me?
How can I fix it?

**Comment by AlexeyAB** [comment]
Hi,
What command do you use?

**Comment by cccmdls** [comment]
Hi, Alexey
command:
./darknet detector demo cfg/voc.data cfg/yolov2-tiny-voc.cfg yolov2-tiny-voc-3100.weights -c 1 -thresh 0.3
params:
GPU=1 CUDNN=1 OPENCV=1 OPENNMP=0 DEBUG=0
version:
CUDA=9.0 cuDNN=7.0.5 OpenCV 3.4.0

**Comment by cccmdls** [comment]
And here are my parameters in yolo2-tiny-voc.cfg
batch=64
subdivisions=8
width=384
height=384

filters=30
classes=1

**Comment by AlexeyAB** [comment]
Can you see this problem if you use video-file instead of web-cam?
`./darknet detector demo cfg/voc.data cfg/yolov2-tiny-voc.cfg yolov2-tiny-voc-3100.weights test.mp4 -thresh 0.3`

**Comment by cccmdls** [comment]
No. It doesn't increase.

**Comment by msfanggao** [comment]
Hi, I meet this problem too today when I use Hikvision RTSP in demo command.
The memory keeps going up at around 60MB/sec. 
My command is 
`./darknet detector demo cfg/x.data cfg/x.cfg /backup/x.backup rtsp://user:pass@ip:554/h264/ch01/main/av_stream`
![screenshot from 2018-04-30 17-27-06](https://user-images.githubusercontent.com/10386624/39421481-d475b70e-4c9b-11e8-80c2-777849fbd0b7.png)
You may see memory curve steadily going up and finally the system lags, the process is killed and end the darknet instance.

**Comment by msfanggao** [comment]
Update for the problem:
If I set the Hikvision camera video frame rate lower(i.e. 1fps or 2fps), the memory usage shall grow up not as fast as in a high fps(such as 25fps) camera setting, but still, the memory goes up steadily.

**Comment by AlexeyAB** [comment]
@cccmdls @msfanggao 
I'v fixed all these issues.

Tested on:
* video-file, web-cam, ip-cam
* OpenCV 2.4.13 and OpenCV 3.4.0

**Comment by cccmdls** [comment]
Hi Alexey. Thank you.
