### ISSUE TITLE
is it possible to change anchor values or anchors distribution in yolo layers during training or after training?

### ISSUE THREAD

**Issue by IbrahimBond** [AlexeyAB/darknet#7194]

**Comment by readicculus** [comment]
you have to retrain, if the network is trained with a set of anchors it is not likely to work very well with a different set of anchors afterwards.  The distribution can't change as the final conv output is a dimension based on the number of anchors in the yolo layer.

**Comment by IbrahimBond** [comment]
thanks for your info, appreciated.
