### ISSUE TITLE
mAP Calculation is consuming all available RAM 180gB

### ISSUE THREAD

**Issue by github-jeff** [AlexeyAB/darknet#7202]
I have been making headway on the csp model with 257 classes.  mAP has increased to 11% and loss is hovering around 120% after 55K iterations.  Obviously I am continuing but the question is two fold:

1) mAP uses only one CPU and takes a good while.  Is there a way to use more than one CPU or GPU?  I am currently training on 4 GPU's but yolo switches to CPU for mAP calculation.

2) Sometimes mAP errors out because it runs out of system RAM.  If I am reading this right the validation set should have ~329K boxes but the model detected a little bit more than 43M objects.  So it errors out around 20M objects as it just runs out of RAM.  I am also seeing this when I am testing the weights files as I go.  Quite a bit of duplicate detection objects.  Somewhere in the neighborhood of 50 classes are being detected at north of 200% and the confidence is high for all of them so it will be difficult to weed this out.
```
[yolo] params: iou loss: ciou (4), iou_norm: 0.05, obj_norm: 0.40, cls_norm: 0.50, delta_norm: 1.00, scale_x_y: 2.00
nms_kind: diounms (2), beta = 0.600000 
Total BFLOPS 92.521 
avg_outputs = 689862 
 Allocate additional workspace_size = 577.11 MB 
Loading weights from backup/yolov4-csp_obj_v1_last.weights...
 seen 64, trained: 3110 K-images (48 Kilo-batches_64) 
Done! Loaded 175 layers from weights-file 

 calculation mAP (mean average precision)...
 Detection layer: 144 - type = 28 
 Detection layer: 159 - type = 28 
 Detection layer: 174 - type = 28 
5400
 detections_count = 43002001, unique_truth_count = 329400  
 rank = 23720400Killednks = 43002001 
```

**Comment by AlexeyAB** [comment]
1. GPU has much less VRAM, so it doesn't make sense, because you already don't have enough CPU RAM.

2. Try to change it to `0.02` and recompile, but mAP can be slightly lower https://github.com/AlexeyAB/darknet/blob/95339f2df57624ae1b27a560ff643e49eff238eb/src/detector.c#L995

**Comment by github-jeff** [comment]
Thanks @AlexeyAB I will give that a try.

For now I just pulled out -map from the training command and my current plan to run this training without -map until the average loss is within a reasonable range i.e < 20%.  I will simply check map manually on a side machine every so often to make sure this is not spiraling out of control.
