### ISSUE TITLE
1080TI faster than 2080TI?

### ISSUE THREAD

**Issue by readicculus** [AlexeyAB/darknet#7203]
**1080TI**
```
CUDA-version: 10020 (10020), cuDNN: 7.4.1, CUDNN_HALF=1, GPU count: 2  
 CUDNN_HALF=1 
 OpenCV version: 3.4.2
0
 1 : compute_capability = 610, cudnn_half = 0, GPU: GeForce GTX 1080 Ti 
net.optimized_memory = 0 
mini_batch = 1, batch = 4, time_steps = 1, train = 0 
   layer   filters  size/strd(dil)      input                output
   0 conv     16       3 x 3/ 1    416 x 416 x   3 ->  416 x 416 x  16 0.150 BF
   0 - receptive field: 3 x 3 
   1 max                2x 2/ 2    416 x 416 x  16 ->  208 x 208 x  16 0.003 BF
   1 - receptive field: 4 x 4 
   2 conv     32       3 x 3/ 1    208 x 208 x  16 ->  208 x 208 x  32 0.399 BF
   2 - receptive field: 8 x 8 
   3 max                2x 2/ 2    208 x 208 x  32 ->  104 x 104 x  32 0.001 BF
   3 - receptive field: 10 x 10 
   4 conv     64       3 x 3/ 1    104 x 104 x  32 ->  104 x 104 x  64 0.399 BF
   4 - receptive field: 18 x 18 
   5 max                2x 2/ 2    104 x 104 x  64 ->   52 x  52 x  64 0.001 BF
   5 - receptive field: 22 x 22 
   6 conv    128       3 x 3/ 1     52 x  52 x  64 ->   52 x  52 x 128 0.399 BF
   6 - receptive field: 38 x 38 
   7 max                2x 2/ 2     52 x  52 x 128 ->   26 x  26 x 128 0.000 BF
   7 - receptive field: 46 x 46 
   8 conv    256       3 x 3/ 1     26 x  26 x 128 ->   26 x  26 x 256 0.399 BF
   8 - receptive field: 78 x 78 
   9 max                2x 2/ 2     26 x  26 x 256 ->   13 x  13 x 256 0.000 BF
   9 - receptive field: 94 x 94 
  10 conv    512       3 x 3/ 1     13 x  13 x 256 ->   13 x  13 x 512 0.399 BF
  10 - receptive field: 158 x 158 
  11 max                2x 2/ 1     13 x  13 x 512 ->   13 x  13 x 512 0.000 BF
  11 - receptive field: 190 x 190 
  12 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  12 - receptive field: 254 x 254 
  13 conv    256       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 256 0.089 BF
  13 - receptive field: 254 x 254 
  14 conv    512       3 x 3/ 1     13 x  13 x 256 ->   13 x  13 x 512 0.399 BF
  14 - receptive field: 318 x 318 
  15 conv     21       1 x 1/ 1     13 x  13 x 512 ->   13 x  13 x  21 0.004 BF
  15 - receptive field: 318 x 318 
  16 yolo
[yolo] params: iou loss: mse (2), iou_norm: 0.75, obj_norm: 1.00, cls_norm: 1.00, delta_norm: 1.00, scale_x_y: 1.00
  16 - receptive field: 318 x 318 
  17 route  13 		                           ->   13 x  13 x 256 
  17 - receptive field: 254 x 254 
  18 conv    128       1 x 1/ 1     13 x  13 x 256 ->   13 x  13 x 128 0.011 BF
  18 - receptive field: 254 x 254 
  19 upsample                 2x    13 x  13 x 128 ->   26 x  26 x 128
  19 - receptive field: 254 x 254 
  20 route  19 8 	                           ->   26 x  26 x 384 
  20 - receptive field: 254 x 254 
  21 conv    256       3 x 3/ 1     26 x  26 x 384 ->   26 x  26 x 256 1.196 BF
  21 - receptive field: 286 x 286 
  22 conv     35       1 x 1/ 1     26 x  26 x 256 ->   26 x  26 x  35 0.012 BF
  22 - receptive field: 286 x 286 
  23 yolo
[yolo] params: iou loss: mse (2), iou_norm: 0.75, obj_norm: 1.00, cls_norm: 1.00, delta_norm: 1.00, scale_x_y: 1.00
  23 - receptive field: 286 x 286 
  24 route  21 		                           ->   26 x  26 x 256 
  24 - receptive field: 286 x 286 
  25 conv    128       1 x 1/ 1     26 x  26 x 256 ->   26 x  26 x 128 0.044 BF
  25 - receptive field: 286 x 286 
  26 upsample                 2x    26 x  26 x 128 ->   52 x  52 x 128
  26 - receptive field: 286 x 286 
  27 route  26 6 	                           ->   52 x  52 x 256 
  27 - receptive field: 286 x 286 
  28 conv    128       3 x 3/ 1     52 x  52 x 256 ->   52 x  52 x 128 1.595 BF
  28 - receptive field: 302 x 302 
  29 conv      7       1 x 1/ 1     52 x  52 x 128 ->   52 x  52 x   7 0.005 BF
  29 - receptive field: 302 x 302 
  30 yolo
[yolo] params: iou loss: mse (2), iou_norm: 0.75, obj_norm: 1.00, cls_norm: 1.00, delta_norm: 1.00, scale_x_y: 1.00
  30 - receptive field: 302 x 302 
Total BFLOPS 7.098 
avg_outputs = 306522 
 Allocate additional workspace_size = 52.43 MB 
Loading weights from /fast/generated_data/EO/seals_416x416_v2/models/yolov3-tiny_3l/weights/yolov3-tiny_3l_best.weights...
 seen 64, trained: 2182 K-images (34 Kilo-batches_64) 
Done! Loaded 31 layers from weights-file 

 calculation mAP (mean average precision)...
 Detection layer: 16 - type = 28 
 Detection layer: 23 - type = 28 
 Detection layer: 30 - type = 28 
7520
 detections_count = 36264, unique_truth_count = 10511  
class_id = 0, name = Ringed Seal, ap = 95.73%   	 (TP = 8806, FP = 884) 
class_id = 1, name = Bearded Seal, ap = 91.62%   	 (TP = 942, FP = 687) 

 for conf_thresh = 0.25, precision = 0.86, recall = 0.93, F1-score = 0.89 
 for conf_thresh = 0.25, TP = 9748, FP = 1571, FN = 763, average IoU = 70.65 % 

 IoU threshold = 50 %, used Area-Under-Curve for each unique Recall 
 mean average precision (mAP@0.50) = 0.936740, or 93.67 % 
Total Detection Time: 23 Seconds
```
**Total Detection Time: 23 Seconds**

**2080TI**
```
 CUDA-version: 10020 (10020), cuDNN: 7.4.1, CUDNN_HALF=1, GPU count: 2  
 CUDNN_HALF=1 
 OpenCV version: 3.4.2
0
 0 : compute_capability = 750, cudnn_half = 1, GPU: GeForce RTX 2080 Ti 
net.optimized_memory = 0 
mini_batch = 1, batch = 4, time_steps = 1, train = 0 
   layer   filters  size/strd(dil)      input                output
   0 conv     16       3 x 3/ 1    416 x 416 x   3 ->  416 x 416 x  16 0.150 BF
   0 - receptive field: 3 x 3 
   1 max                2x 2/ 2    416 x 416 x  16 ->  208 x 208 x  16 0.003 BF
   1 - receptive field: 4 x 4 
   2 conv     32       3 x 3/ 1    208 x 208 x  16 ->  208 x 208 x  32 0.399 BF
   2 - receptive field: 8 x 8 
   3 max                2x 2/ 2    208 x 208 x  32 ->  104 x 104 x  32 0.001 BF
   3 - receptive field: 10 x 10 
   4 conv     64       3 x 3/ 1    104 x 104 x  32 ->  104 x 104 x  64 0.399 BF
   4 - receptive field: 18 x 18 
   5 max                2x 2/ 2    104 x 104 x  64 ->   52 x  52 x  64 0.001 BF
   5 - receptive field: 22 x 22 
   6 conv    128       3 x 3/ 1     52 x  52 x  64 ->   52 x  52 x 128 0.399 BF
   6 - receptive field: 38 x 38 
   7 max                2x 2/ 2     52 x  52 x 128 ->   26 x  26 x 128 0.000 BF
   7 - receptive field: 46 x 46 
   8 conv    256       3 x 3/ 1     26 x  26 x 128 ->   26 x  26 x 256 0.399 BF
   8 - receptive field: 78 x 78 
   9 max                2x 2/ 2     26 x  26 x 256 ->   13 x  13 x 256 0.000 BF
   9 - receptive field: 94 x 94 
  10 conv    512       3 x 3/ 1     13 x  13 x 256 ->   13 x  13 x 512 0.399 BF
  10 - receptive field: 158 x 158 
  11 max                2x 2/ 1     13 x  13 x 512 ->   13 x  13 x 512 0.000 BF
  11 - receptive field: 190 x 190 
  12 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  12 - receptive field: 254 x 254 
  13 conv    256       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 256 0.089 BF
  13 - receptive field: 254 x 254 
  14 conv    512       3 x 3/ 1     13 x  13 x 256 ->   13 x  13 x 512 0.399 BF
  14 - receptive field: 318 x 318 
  15 conv     21       1 x 1/ 1     13 x  13 x 512 ->   13 x  13 x  21 0.004 BF
  15 - receptive field: 318 x 318 
  16 yolo
[yolo] params: iou loss: mse (2), iou_norm: 0.75, obj_norm: 1.00, cls_norm: 1.00, delta_norm: 1.00, scale_x_y: 1.00
  16 - receptive field: 318 x 318 
  17 route  13 		                           ->   13 x  13 x 256 
  17 - receptive field: 254 x 254 
  18 conv    128       1 x 1/ 1     13 x  13 x 256 ->   13 x  13 x 128 0.011 BF
  18 - receptive field: 254 x 254 
  19 upsample                 2x    13 x  13 x 128 ->   26 x  26 x 128
  19 - receptive field: 254 x 254 
  20 route  19 8 	                           ->   26 x  26 x 384 
  20 - receptive field: 254 x 254 
  21 conv    256       3 x 3/ 1     26 x  26 x 384 ->   26 x  26 x 256 1.196 BF
  21 - receptive field: 286 x 286 
  22 conv     35       1 x 1/ 1     26 x  26 x 256 ->   26 x  26 x  35 0.012 BF
  22 - receptive field: 286 x 286 
  23 yolo
[yolo] params: iou loss: mse (2), iou_norm: 0.75, obj_norm: 1.00, cls_norm: 1.00, delta_norm: 1.00, scale_x_y: 1.00
  23 - receptive field: 286 x 286 
  24 route  21 		                           ->   26 x  26 x 256 
  24 - receptive field: 286 x 286 
  25 conv    128       1 x 1/ 1     26 x  26 x 256 ->   26 x  26 x 128 0.044 BF
  25 - receptive field: 286 x 286 
  26 upsample                 2x    26 x  26 x 128 ->   52 x  52 x 128
  26 - receptive field: 286 x 286 
  27 route  26 6 	                           ->   52 x  52 x 256 
  27 - receptive field: 286 x 286 
  28 conv    128       3 x 3/ 1     52 x  52 x 256 ->   52 x  52 x 128 1.595 BF
  28 - receptive field: 302 x 302 
  29 conv      7       1 x 1/ 1     52 x  52 x 128 ->   52 x  52 x   7 0.005 BF
  29 - receptive field: 302 x 302 
  30 yolo
[yolo] params: iou loss: mse (2), iou_norm: 0.75, obj_norm: 1.00, cls_norm: 1.00, delta_norm: 1.00, scale_x_y: 1.00
  30 - receptive field: 302 x 302 
Total BFLOPS 7.098 
avg_outputs = 306522 
 Allocate additional workspace_size = 52.43 MB 
Loading weights from /fast/generated_data/EO/seals_416x416_v2/models/yolov3-tiny_3l/weights/yolov3-tiny_3l_best.weights...
 seen 64, trained: 2182 K-images (34 Kilo-batches_64) 
Done! Loaded 31 layers from weights-file 

 calculation mAP (mean average precision)...
 Detection layer: 16 - type = 28 
 Detection layer: 23 - type = 28 
 Detection layer: 30 - type = 28 
7520
 detections_count = 36270, unique_truth_count = 10511  
class_id = 0, name = Ringed Seal, ap = 95.73%   	 (TP = 8805, FP = 885) 
class_id = 1, name = Bearded Seal, ap = 91.61%   	 (TP = 941, FP = 687) 

 for conf_thresh = 0.25, precision = 0.86, recall = 0.93, F1-score = 0.89 
 for conf_thresh = 0.25, TP = 9746, FP = 1572, FN = 765, average IoU = 70.63 % 

 IoU threshold = 50 %, used Area-Under-Curve for each unique Recall 
 mean average precision (mAP@0.50) = 0.936721, or 93.67 % 
Total Detection Time: 32 Seconds

```
**Total Detection Time: 32 Seconds**
Any thoughts?  This is just using a pretty generic yolov3-tiny_3l model and as you can see ran on 7520 images 416x416px.  Whats odd is the 2080ti has no usage unless I run on it while the 1080ti has chrome/monitors using a bit of resources from it but it is still somehow a lot faster...

![x](https://user-images.githubusercontent.com/3818801/103448426-69231900-4c4e-11eb-83d3-76d0f4ab3498.png)

**Comment by stephanecharette** [comment]
Did you remember to enable the `ARCH=` line for the 2080 in the Makefile?

**Comment by AlexeyAB** [comment]
Use 
`./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights test.mp4 -dont_show`
to measure speed.


mAP calculation is CPU-bound.

**Comment by readicculus** [comment]
I get similar results with demo.  I'm not sure if im doing it right but I used ffmpeg to turn my images into a mp4 and used the -benchmark flag.  Thee -gpus flag doesn't work for me.  I have a 1080ti and a 2080ti in my machine and I can select which when I'm training but for some reason not here.  I've been using cuda_set_device in the demo code which works to force set either the 1080ti or the 2080ti.

After running for a minute I get an avg fps of ~160 for 2080ti and ~175 for 1080ti.  When I run demo I see the same gpus stats as above(cuDNN version, CUDNN_HALF=1, etc..).  I don't really know how to play around with the makefile configs now that this is cmake and once I build my Makefile is gone.  Is it possible I need to rebuild with the compute capability for a gpu before benchmarking that gpu?  Above you see it correctly has 750 for 2080ti and 610 for 1080ti but I'm not really sure what to try out next.

I guess if nothing else comes to mind any ideas on a good way to benchmark my gpu to see if maybe I have an issue with cuda or other drivers?

Really appreciate the help over the years Alexy, you're doing amazing stuff.

**Comment by readicculus** [comment]
Weird... The OpenCV build it was pointing to was giving a warning during build saying I should rebuild with cuda. I pointed it to an OpenCV build I have that was built with cuda and its fast as heck now. 2080TI 310FPS, 1080TI 327FPS.  So 2080 still slower but things are almost twice as fast? I have batch=1 and subdivision=1

**Comment by stephanecharette** [comment]
> Thee -gpus flag doesn't work for me.

Remember from the readme, that `-gpus` is the flag during training, and `-i`is the flag during inference.  (I have no idea why it is inconsistent.)

**Comment by AlexeyAB** [comment]
For GPU-0:
`./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights test.mp4 -benchmark -i 0`

For GPU-1:
`./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights test.mp4 -benchmark -i 1`

**Comment by readicculus** [comment]
**yolov4.cfg**
1080TI ~ 32.7 FPS

2080TI ~ 40.3 FPS

guess things are working, still not sure why yolov3_tiny_3l I have different results but as I need to report my results I'll be playing with this a lot this week and will respond if I can provide any more useful information as to why this may be the case.  Its actually not a 3l tiny its a 1l tiny that is similar to 3l tiny but with only the final yolo layer at 64x80(input size is 512x640), 1 class, 5 anchors, I can't think of why these specifics would matter but I tried using the default yolov3-tiny_3l that is in the repo and got similar results.

**yolov3-tiny_3l.cfg**
(had to change coco.data to classes=2 to run on the default yolov3-tiny_3l.cfg)
1080TI
`./darknet detector demo cfg/coco.data cfg/yolov3-tiny_3l.cfg /data/pretrained_weights/yolov3-tiny.weights out.mp4 -benchmark -i 1`
avg_fps: 203.5

2080TI
`./darknet detector demo cfg/coco.data cfg/yolov3-tiny_3l.cfg /data/pretrained_weights/yolov3-tiny.weights out.mp4 -benchmark -i 0`
avg_fps: 144.5

I'm not sure if this detail matters but I'll mention in case,  I actually have to use the -i 1 to get it to run on the 1080ti and -i 0 for the 2080 ti even though in nvidia-smi the 1080ti is first and 2080ti second.  When I ran the commands above nvidia-smi showed the intended gpu was being used (when i ran with -i 1 the memory was loaded onto 1080ti and avg fps was 203.5 for the second experiment) so I am fairly confident the gpu it says it is using is in fact the one being used but figured worth mentioning in case this is a red flag.

![image](https://user-images.githubusercontent.com/3818801/103486617-f764df80-4db3-11eb-9d48-1462744f35c8.png)

**Comment by AlexeyAB** [comment]
> yolov4.cfg
> 1080TI ~ 32.7 FPS
> 2080TI ~ 40.3 FPS

So 2080TI  is faster than 1080TI.

> yolov3-tiny_3l.cfg
> (had to change coco.data to classes=2 to run on the default yolov3-tiny_3l.cfg)
> 1080TI
> ./darknet detector demo cfg/coco.data cfg/yolov3-tiny_3l.cfg /data/pretrained_weights/yolov3-tiny.weights out.mp4 -benchmark -i 1
> avg_fps: 203.5
> 
> 2080TI
> ./darknet detector demo cfg/coco.data cfg/yolov3-tiny_3l.cfg /data/pretrained_weights/yolov3-tiny.weights out.mp4 -benchmark -i 0
> avg_fps: 144.5

This can be normal for very small models on very powerful GPUs. 

> I'm not sure if this detail matters but I'll mention in case, I actually have to use the -i 1 to get it to run on the 1080ti and -i 0 for the 2080 ti even though in nvidia-smi the 1080ti is first and 2080ti second. When I ran the commands above nvidia-smi showed the intended gpu was being used (when i ran with -i 1 the memory was loaded onto 1080ti and avg fps was 203.5 for the second experiment) so I am fairly confident the gpu it says it is using is in fact the one being used but figured worth mentioning in case this is a red flag.

This is normal. 
nvidia-smi (nVidia driver) and nVidia CUDA iterate GPUs in different order.

**Comment by readicculus** [comment]
Awesome, all my questions are answered then.  Thanks again for helping me understand.
