### ISSUE TITLE
After I download the recently updated darknet package, testing cost a lot of time and my train.txt changes

### ISSUE THREAD

**Issue by laurence-lin** [AlexeyAB/darknet#7207]
Recently I re-download the darknet packages to resolve the mAP larger than 1 problem. 

After training, I found that the problem no longer happen-- but I meet a new issue during training. 

When I run the command for test: `!./darknet detector map data/obj.data cfg/yolov4-tiny_1c.cfg backup/yolov4-tiny_1c_last.weights`

It runs for a long period of time, and keep stuck in `Loading weights from backup/yolov4-tiny_1c_10000.weights...Done! Loaded 35 layers from weights-file` state. 

And there is another problem: whenever the testing failed, my train.txt in darknet/data folder is changed to error message:

 

> CUDNN_HALF=1 
> net.optimized_memory = 0 
> mini_batch = 1, batch = 8, time_steps = 1, train = 0 
> nms_kind: greedynms (1), beta = 0.600000 
> nms_kind: greedynms (1), beta = 0.600000 
> 
>  seen 64, trained: 80 K-images (1 Kilo-batches_64) 
> Enter Image Path: 

This makes me to upload the train.txt again, which is strange, why would my train.txt file changed?

Thank you for any help!

**Comment by stephanecharette** [comment]
You must be redirecting output to that file.  You probably copy-pasted something, and accidentally left some stray redirection in place.  Check your command again to make sure you didn't put ` darknet ...etc... > train.txt` or something of the sort.

**Comment by laurence-lin** [comment]
> You must be redirecting output to that file. You probably copy-pasted something, and accidentally left some stray redirection in place. Check your command again to make sure you didn't put ` darknet ...etc... > train.txt` or something of the sort.

Oh yeah, I mistook the result.json  < train.txt to result.json > train.txt. I would try out later!

**Comment by laurence-lin** [comment]
Problem solved, close the issue.
