### ISSUE TITLE
Understanding enet-coco configuration/architecture

### ISSUE THREAD

**Issue by eagledot** [AlexeyAB/darknet#7208]
Hi,
I was trying to implement efficient-b0 based YOLO [architecture](https://github.com/AlexeyAB/darknet/blob/master/cfg/enet-coco.cfg) in pytorch.But according to ``shortcut layer`` in config at [https://github.com/AlexeyAB/darknet/blob/0968058b546193d2d2d0ce66de1b4bed36f369d1/cfg/enet-coco.cfg#L1036](https://github.com/AlexeyAB/darknet/blob/0968058b546193d2d2d0ce66de1b4bed36f369d1/cfg/enet-coco.cfg#L1036]) ,i am supposed to add latest output and output from layer 90 ,but [layer 90]( https://github.com/AlexeyAB/darknet/blob/0968058b546193d2d2d0ce66de1b4bed36f369d1/cfg/enet-coco.cfg#L680) seems to have ``576`` filters as opposed to ``128`` .I may be missing something but i cannot seem to understand what.
Thanks.

**Comment by lsd1994** [comment]
#6955

**Comment by eagledot** [comment]
Thanks.I got it.
May be  issue ``#6955`` could be mentioned in ``wiki``.
