### ISSUE TITLE
Training +30 Million images

### ISSUE THREAD

**Issue by seekingdeep** [AlexeyAB/darknet#7209]
@AlexeyAB @stephanecharette 

Hi there,
Currently i am testing the practicality of using yolov4 in a large workflow.
In the situation of having a dataset that is made of more than 30 Million images of size (736*1024)
The following questions arise:

- Does yolo load all the training data into the memory all at once, or can i divide the data into chunks? can i "train on-the-fly"?
inwhich a small part of the data is loaded, used in training, then flushed. Later-on another part is loaded ..... again and again.

- In an image of size (736*1024) , how small can an object be, to be detected?
- If [Image Tiling](https://www.ccoderun.ca/darkhelp/api/Tiling.html) is used, say an object happened to be between 2 tiles, will yolo still be able to detect?
- Are image augmentation and rotation, etc.... of any benefits?
- Do you have any recommendation to increase efficiency of training and decrease costs?

**Comment by readicculus** [comment]
How small are your objects? I'm less familiar with yolov4 but for v3 with 3 layers it works for small objects in my experience with my dataset that has most objects ~8-11px but if those small objects overlap or are very close(ex 2 tiny objects in an 8x8px area) it will struggle as each feature map cell can in the end only predict one bounding box.  

I also have to tile for my project, it often picks up my objects if they are half on but if less it usually misses.  I would recommend using a stride smaller than your input size so that even if an object is cut off it will be fully in another chip, then when you post-process(aggregate results for chips in an image) you can correct.

Augmentations are helpful in all the datasets I've worked with, type of augmentation and how much augmentation depends on the dataset though.

It sounds like you might be working with aerial/sat data.  I would recommend trying yolov3_tiny_3l or if there is a yolov4_tiny_3l try that, it works well for the aerial detection stuff I do but I only have a few classes, it could be that the tiny networks dont do as well when you have a lot of classes, I'm not sure.

**Comment by seekingdeep** [comment]
- For the tiling, say the object was divided into 2 tiles equally, having detected (40% top tile) and (30% bottom tile), will the top and bottom portion be combined into a single object?
- What about "training on-the-fly"? can yolov4 instead of loading all the data into the memory, it continually load only the required portion for training?
- Is there an Auto-Yolo, inwhich the best stride/tile/etc... are searched for?

**Comment by readicculus** [comment]
As far as I am aware tiling is a preprocessing step that you have to do on your own, you could use the python wrapper when you want to detect and tile then call detect on all tiles individually then aggregate results from all the tiles.  It's a fairly simple algorithm to do this.
Here is one way which I often use, given a chip width and height and a chip strid_x/y and your image width and height(m_h/m_w) this will return a dictionary of all the chip coordinates.
```
def tile_2d_stride(m_w, m_h, c_w, c_h, stride_x, stride_y):
        m = m_w // stride_x
        n = m_h // stride_y
        m_remainder = m_w - (m * (c_w))
        n_remainder = m_h - (n * (c_h))

        tiles = []
        for i in range(m + 1):
            for j in range(n + 1):
                x1 = i * (stride_x) if i != m else m_w - c_w
                x2 = x1 + c_w
                y1 = j * (stride_y) if j != n else m_h - c_h
                y2 = y1 + c_h
                tiles.append({'x1': x1, 'x2': x2, 'y1': y1, 'y2': y2, 'i': i, 'j': j})
        return tiles

```
It shouldn't be loading all data in to memory, just the batch that it is working with so if you are running out of memory increase subdivisions. Maybe I'm wrong when it comes to yolov4 as I don';t use v4 yet but I bet its the same in v4.

Auto-yolo?  Alexy said there is some attention model in yolov4 in another post recently, I think it had SAM in the config name.  Can't help more than that though sorry.

**Comment by stephanecharette** [comment]
> As far as I am aware tiling is a preprocessing step that you have to do on your own

See the original message which references the tiling option built into DarkHelp.

> ... will the top and bottom portion be combined into a single object?

With the simple tiling options in DarkHelp, the answer is no, there is no attempt to combine an object which has been split across multiple tiles.

> Does yolo load all the training data into the memory all at once

Darknet/YOLO does not load your 30 million images at once.  It only loads as many images as required to process together at once, so a handful, depending on how you setup your batches, subdivisions, whether you've enabled mosaic, etc.  Remember darknet is limited by the amount of vram available to the GPU, so you can only load a handful of images at once.

> In an image of size (736*1024) , how small can an object be, to be detected?

I think the readme might mention 16x16 pixels.  I found it does better than that, especially in high contrast images for example, but I start to get worried once you go below that size.

> If Image Tiling is used, say an object happened to be between 2 tiles, will yolo still be able to detect?

Most of the time, yes.  Same as objects on the outside edge of an image.  Depends on training, size, colour, etc.

> Are image augmentation and rotation, etc.... of any benefits?

Yes.  Darknet does some augmentation itself during training, though not rotation.  See:
* https://www.ccoderun.ca/programming/darknet_faq/#turn_off_data_augmentation
* https://www.ccoderun.ca/programming/darknet_faq/#rotating_images

Again, this depends on your project.  If you're looking for traffic lights, then to distinguish between red/green/amber lights you'll need to turn down (or turn off) the colour options.  If you're looking at dash cam footage, then 180° rotation probably doesn't make sense.

> Do you have any recommendation to increase efficiency of training and decrease costs?

Yes, see here:  https://www.ccoderun.ca/programming/darknet_faq/#time_to_train
For example, depending on the options you choose, that network can take between 2 hours and 6 days to train.  Some options make a huge difference.

**Comment by seekingdeep** [comment]
@stephanecharette is there an Auto-yolo   option with a similar concept to Neural Architecture Search, inwhich initially we it try to find the best network configurations, then it trains using those configs?
@readicculus Thanks!

**Comment by stephanecharette** [comment]
> @stephanecharette is there an Auto-yolo option with a similar concept to Neural Architecture Search, inwhich initially we it try to find the best network configurations, then it trains using those configs?

I have no idea what that means.

**Comment by seekingdeep** [comment]
i mean when training a yolo model we use a predefined config file and network model, that might be more suited for the coco dataset, of-course we can modify it according to our preferences and own dataset and i understand that it's a "trial and error" way, but still, is there a script that can automate the "TWEAKING" process, such that it tries to find the best settings, configuration, network structure, etc... that is most suitable to our own dataset.

**Comment by stephanecharette** [comment]
Not that I know.

**Comment by seekingdeep** [comment]
Thanks
