### ISSUE TITLE
Is it safe to disable non max suppression? (Custom trained data)

### ISSUE THREAD

**Issue by saihv** [AlexeyAB/darknet#721]
I am working on a custom trained version of tiny YOLO, with my train/test image resolution at 640x360, while the network is trained at a resolution of 640x352 with random=0. This combination gives me pretty good IoU during inference. 

I've noticed in my some of my evaluations that non max suppression doesnt seem to improve the IoU in any way, even though the IoU threshold for NMS is changed. Furthermore, I know for a fact that there is only one object of interest in my test images, so I'm really only interested in the bounding box with the highest probability. Given this info,is it safe to disable non max suppression (for a slight boost in performance)? Additionally, I'm curious as to why NMS doesnt seem to affect the inference at all.

**Comment by AlexeyAB** [comment]
I think yes, it is safe to disable NMS in your case.
But I think this will not give a noticeable increase in performance.

**Comment by saihv** [comment]
Thanks! I am actually working on a very FPS-critical pipeline, and disabling NMS (depending on the threshold) is giving me about 0.5-1 fps more on the TX2.
