### ISSUE TITLE
no bounding box in dog.jpg

### ISSUE THREAD

**Issue by z3rO1997** [AlexeyAB/darknet#7215]
![image](https://user-images.githubusercontent.com/46732343/103728086-53cc3700-5020-11eb-9ed3-08d6ed978c42.png)
![image](https://user-images.githubusercontent.com/46732343/103728161-8e35d400-5020-11eb-9bb9-2112e5942578.png)
![image](https://user-images.githubusercontent.com/46732343/103728212-ae659300-5020-11eb-9202-fd610e752f10.png)
Why doesn't bounding box appear in dog.jpg
Simple example, but it doesn't work.
I can't start because it
If someone has experienced and solved this problem
Please let me know in a way that is easy for everyone

**Comment by z3rO1997** [comment]
Solved

**Comment by stephanecharette** [comment]
Solved how?

**Comment by z3rO1997** [comment]
I am using gtx 1660 super
There is no tensor core, so cudnn_half should not be 1
Just remove cudnn_half from the preprocessor
