### ISSUE TITLE
OpenCV Plotting Loss Curves During Training

### ISSUE THREAD

**Issue by Brandhsu** [AlexeyAB/darknet#7222]
In order to compile OpenCV for plotting the loss curves during traIning with the -map flag, does OpenCV need to be downloaded from source, or will a pip install suffice?

Thanks.

**Comment by stephanecharette** [comment]
Run:  `sudo apt-get install libopencv-dev`.

**Comment by Brandhsu** [comment]
Thank you, good sir! I tried compiling OpenCV from source and couldn't figure out how to get the paths working correctly, this is a wonderful fix for Linux users
