### ISSUE TITLE
Could you please give some references that use objectness smooth?

### ISSUE THREAD

**Issue by wtiandong** [AlexeyAB/darknet#7226]
##❔Question
Could you please give some references that use IOU as objectness labels?

##Additional context
I notice it is called objectness smooth in yolov4 codes, but I can't find who is first using this method or in any papers, not even in the yolov4 paper.
Thank you.

**Comment by wtiandong** [comment]
Refer to https://github.com/ultralytics/yolov5/issues/1863

**Comment by AlexeyAB** [comment]
This is from YOLOv2 - 2016 year: https://github.com/AlexeyAB/darknet/blob/b11af9e93b4ec225450b0dd73bdd7aaa1f2912b8/src/region_layer.c#L349-L352


YOLO9000: Better, Faster, Stronger 25 Dec 2016: https://arxiv.org/pdf/1612.08242.pdf

> Following YOLO, the **objectness prediction still predicts
> the IOU of the ground truth and the proposed box** and the
> class predictions predict the conditional probability of that
> class given that there is an object.

Losses:
![image](https://user-images.githubusercontent.com/4096485/103968728-686e1380-5175-11eb-9efb-f141032b9255.png)

**Comment by wtiandong** [comment]
OK, Thank you! @AlexeyAB 
It's interesting that in Yolov3 the IOU in objectness is removed, and now back in Yolov4.


https://github.com/pjreddie/darknet/blob/a3714d0a2bf92c3dea84c4bea65b2b0c64dbc6b1/src/yolo_layer.c#L183

**Comment by AlexeyAB** [comment]
* `objectness_smooth` slightly increases AP (AP50...95) but decreases AP50

* `objectness_smooth`  was forcibly enabled in YOLOv2, while it is optional in YOLOv4 (enabled in Scaled-YOLOv4 and disabled in YOLOv4)

**Comment by wtiandong** [comment]
> * `objectness_smooth` slightly increases AP (AP50...95) but decreases AP50
> * `objectness_smooth`  was forcibly enabled in YOLOv2, while it is optional in YOLOv4 (enabled in Scaled-YOLOv4 and disabled in YOLOv4)

OK，thank you!
