### ISSUE TITLE
Refining Yolov4 for Vehicle Detection (~+10% mAP:50)

### ISSUE THREAD

**Issue by blake-espeland** [AlexeyAB/darknet#7247]
Hello! 

I'm not sure if you've read this paper yet or not, but It describes a few features that may be nice to implement in darknet.

Paper: https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3628439
Title: *Refining Yolov4 for Vehicle Detection*

The authors of this paper propose improving Yolov4 for real-time vehicular detection. They don't go into depth with some of the methods used, however, if anything, these are ideas for a potential boost in video detection.

Following features used:
 - ABK: Anchor Box optimization using K-means clustering
 - DIoU NMS
 - SAM: Spatial Attention Module **(lead to the largest improvement)**
 - SAT: Self Adversarial Training

Existing features in darknet (that I'm aware of):
- DIoU NMS
- SAM ([yolov4-csp-sam.cfg](https://drive.google.com/file/d/1h7amsxwtWz6v66kzx53R3_Sxst5pti06/view) on modelzoo)
- SAT ```adversarial_lr=0.05```

The only thing I'm not sure exists in darknet is the ABK aspect of this model. I've [read](https://openaccess.thecvf.com/content_WACV_2020/papers/Zhong_Anchor_Box_Optimization_for_Object_Detection_WACV_2020_paper.pdf) where it can increase mAP by up to 4% in smaller models.

They didn't provide code or .cfg files with the paper, and this implementation is really interesting to me. I'm looking for a good object tracking/video detection model, and a .cfg file, or an idea of how to make one with these features, would be nice. @AlexeyAB, let me know if this is of any use to you.

**Comment by AlexeyAB** [comment]
@blake-espeland Hi,

>ABK: Anchor Box optimization using K-means clustering

Yes, there is K-means clustering for anchors: https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

> darknet.exe detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height


Do you have this paper in better quality?

> This final combined model gives benchmark results with an mAP of 67.7% (10%-point higher than base model) on the DETRAC-test dataset.
![image](https://user-images.githubusercontent.com/4096485/104521388-db600a00-560d-11eb-8843-3f2a47e8341d.png)

**Comment by blake-espeland** [comment]
I cannot find a better image than the one they provided in the paper, so I'll use the data they provide and strain my eyes a bit.

Key values from table 2:
| Model | Precision | F1 Score | mAP@.50 |
| --- | ----------- | ------ | -------- | 
| Yolov3 | 0.75 | 0.7 | 0.541 |
| Yolov4 | 0.62 | 0.58 | 0.578 |
| Refined Yolov4 | **0.77** | **0.74** | **0.677** |
| Difference from v4 | 0.15 | 0.16 | 0.099 |

"Refined" Yolov4 is the combination of all 4 technologies.
I will try to get the gpu resources to get a second look at these numbers, however, I still need to create the .cfg file they describe in the paper.

**Comment by blake-espeland** [comment]
Here is the link to my .cfg file for 2 classes. It runs without errors, but I don't have the local compute power to test mAP right now.

[yolov4-refined.cfg](https://drive.google.com/file/d/15-Szj0g3rEZ_zQlIvM5uspuNV68N_Llp/view?usp=sharing)

**Comment by AlexeyAB** [comment]
Did you recalc anchors for DETRAC?
Why did you set subdivisions=64 and max_batches=8000?

**Comment by blake-espeland** [comment]
- I recalculated for my custom dataset.
- Subdivisions and max_batches are both what they outlined in the paper
- I’ll change subdivisions when I get an instance running with more vram

To save time, I’ll train yolov4 and the refined version on my dataset to check the difference.

**Comment by Goru1890** [comment]
There are also other options to Anchor Box optimization using K-means clustering explained in this [paper](https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123500545.pdf). I have no idea if it is already implemented in darknet, but AABO seems to improve mAP over k-means.

![Captura de pantalla de 2021-01-14 08-44-53](https://user-images.githubusercontent.com/35274844/104559571-de2a2180-5644-11eb-8be8-0ca293508738.png)

**Comment by blake-espeland** [comment]
@Goru1890, thanks for the paper! I'll read through it when I get a chance.

I'm currently in the process of creating my dataset, so the training on a custom dataset will have to wait.

I tried a test-run with the yolov4-refined.cfg file, but I got ```-nan``` loss after 1000 steps. I'm not sure which feature caused this, but I've had instability before with the plain yolov4-csp-sam.cfg file before as well.

**Comment by blake-espeland** [comment]
@AlexeyAB, thanks! I'll try it.

@Goru1890, if you think AABO would be beneficial to add to darknet as a whole, make a feature request for it so that it gets more visibility.

**Comment by lars-ek** [comment]
is it possible to add the SAM-Module to yolov4-tiny?

**Comment by blake-espeland** [comment]
@lars-ek, I just did. Here it is (2 classes):
It got about **5%** higher AP50 than normal the v4-tiny on my custom dataset.

[yolov4-tiny-refined.cfg](https://drive.google.com/file/d/1Ur7CUcWk9FHMWvxtrlfzYlhTUZx4K6nE/view?usp=sharing)

**Comment by lars-ek** [comment]
@blake-espeland thank you! I will give it a try!

**Comment by lars-ek** [comment]
Unfortunately I dont see an gain in mAP with the additions for tiny-yolo v4 (SAM and DIoU NMS) for my data set :(

Is there an alternative place to put the SAM-layer?

**Comment by blake-espeland** [comment]
@lars-ek Sorry about that, my dataset was small and relatively invariant (~200 similar images for 2 classes). I was trying to train on sequential video data.

I'm not sure if the SAM works well on small models anyways, however, you're welcome to tweak the cfg file if you like. I'm pretty confident at this point that it's been ruled out for small models.

After further testing on a different dataset, the normal ```yolov4-tiny-3l.cfg``` with ```mish``` activation and **DIoU NMS** works best. I'll share a training plot once I get the chance. I've just started classes again, so I don't have as much opportunity to be active on here.

**Comment by cpsu00** [comment]
Hi @blake-espeland, I wonder if you have found out whether the SAM can improve small models performance. 
On my custom dataset, training with the yolov4-tiny-refined.cfg(anchors were recalculated) decrease my map for about 6% comparing to the original yolov4-tiny-3l. 
Would be wonderful if you can give me some suggestions.
