### ISSUE TITLE
Turn on GitHub discussions

### ISSUE THREAD

**Issue by cenit** [AlexeyAB/darknet#7268]
What about turning on discussions, here on this repo, right here on github?
@AlexeyAB it's under settings -> discussions. A new tab will appear, better for discussing topics which are not PR nor code Issues...

**Comment by AlexeyAB** [comment]
@cenit Yes, we can try it.
I enabled darknet Discussions and created one post: https://github.com/AlexeyAB/darknet/discussions/7269
