### ISSUE TITLE
Can we save average loss values into a file? I can not use -dont_show as no GUI display on the server.

### ISSUE THREAD

**Issue by akshayjrkp** [AlexeyAB/darknet#727]

**Comment by AlexeyAB** [comment]
1. You can train using this command:
    `./darknet detector train data/obj.data yolo-obj.cfg darknet53.conv.74 > test.log`

2. Or this command to **Show output in terminal and Log it**:
    `./darknet detector train data/obj.data yolo-obj.cfg darknet53.conv.74 | tee test.log`

As result you will have `test.log` with training log.

Then just copy `test.log` file to the computer with display, and run this Python script: https://raw.githubusercontent.com/AlexeyAB/darknet/master/scripts/log_parser/log_parser.py

----

You should install numpy and matplotlib, so just do in the console on Linux:
```
pip install numpy
pip install matplotlib
```
Or run this file on Windows: https://raw.githubusercontent.com/AlexeyAB/darknet/master/scripts/log_parser/run_log_parser_windows.cmd

More about it: https://github.com/AlexeyAB/darknet/tree/master/scripts/log_parser

**Comment by starkgate** [comment]
I wish it'd save to a file automatically. I noticed too late that outside of the chart.png file, there's no log of the training.

**Comment by aparico** [comment]
@AlexeyAB How do you change the saving location of `test.log`? I'm trying to train in colab and I want to save it somewhere safe.
