### ISSUE TITLE
Required Cmake vision too high

### ISSUE THREAD

**Issue by KangJialiang** [AlexeyAB/darknet#7278]
It requires Cmake vision above 3.18, which seems unnecessary, and is not the defualt cmake vision in most machines.

**Comment by cenit** [comment]
It is necessary to support recent cuda architectures detection.
Updating CMake is very easy, you can find pre-built versions here: https://cmake.org/download/

**Comment by cenit** [comment]
Please let me know if you need more info, unfortunately we cannot downgrade required version

**Comment by KangJialiang** [comment]
Yeah, totally agree. Not a big problem indeed and can be solved quite easily. But it's still a bit confusing that you only required CMake >= 3.12 in readme. Could you change the requirements in readme to meet the actual dependency needed?

**Comment by cenit** [comment]
I will do that in #7279. Sorry I forgot to update README in the previous update

**Comment by KangJialiang** [comment]
Oh, great. Thank you for your contribution!
