### ISSUE TITLE
is cuda toolkit a necessity for running darknet? 

### ISSUE THREAD

**Issue by IbrahimBond** [AlexeyAB/darknet#7283]
i am trying to run darknet inside cuda docker container. my issue is that the cuda-devel base image which include the cuda toolkit has a size of over 3gb. i want to use the absolute bare minimum of cuda functionality in my docker image for running darknet in order to reduce docker image size. 

any insight regarding this is appreciated.

**Comment by shubham-shahh** [comment]
It is not necessary I would say, but without Cuda's support, the inference will be insanely slow.

**Comment by IbrahimBond** [comment]
@shubham-shahh i know about that. i want to run darknet on GPU with bare minimum cuda functionality. so my question is: is cuda runtime with cudnn enough for inference after darknet is already compiled with make?

**Comment by shubham-shahh** [comment]
In my opinion it wouldn't work as the shared files could not be accessed in absence of cuda toolkit

**Comment by IbrahimBond** [comment]
i have tried the theory outside docker containers, and it proved to be correct. i have removed the cuda toolkit path from the bashrc file and darknet could detect objects perfectly fine.

the toolkit is only necessary when building darknet with make.
