### ISSUE TITLE
Unable to detect on custom dataset with Yolov4-tiny

### ISSUE THREAD

**Issue by Faultiness** [AlexeyAB/darknet#7284]
Thanks for reading my issue.

I tried to train Yolov4x-mish on my custom dataset and the training process is unobstructed. Here is the chart.png when I finished the training:
![图片](https://user-images.githubusercontent.com/12472447/105634502-3a890e80-5e99-11eb-93fa-6e5f86232005.png)

When I tried to use the *_last.weights to identify the images that were not involved in the training and validation, I was unable to get any results. The confidence of the result goes down to 5%. 

Then I tried to use Yolov4-custom to trained and identify the images I mentioned before. And the result is great with confidence up to 97%. So the image is fine.

What could be the reason for this?

### More infos about the training of Yolov4x-mish:
Pre-train weights I used for training: [yolov4x-mish.conv.166](https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4x-mish.conv.166)
cfg file: [yolov4x-mish.cfg](https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4x-mish.cfg) and I modified these lines:
Changed [Line 6](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4x-mish.cfg#L6) and [Line 7](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4x-mish.cfg#L7) to `batch=8` and `subdivisions=8` cause I trained the model on RTX 2080 Ti which only has 11GB VRAM.
Changed [Line 20](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4x-mish.cfg#L20) to `max_batches=8000` cause I need to classify 4 different objects.
Changed [Line 22](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4x-mish.cfg#L22) to `steps=6400,7200`
Changed [Line 1159](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4x-mish.cfg#L1159), [Line 1289](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4x-mish.cfg#L1289), and [Line 1419](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4x-mish.cfg#L1419) to `classes=4`
Changed [Line 1152](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4x-mish.cfg#L1152), [Line 1282](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4x-mish.cfg#L1282), and [Line 1412](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4x-mish.cfg#L1412) to `filters=27`, which equals to (classes+5)*3

**Comment by AlexeyAB** [comment]
>Changed Line 6 and Line 7 to batch=8 and subdivisions=8 cause I trained the model on RTX 2080 Ti which only has 11GB VRAM.

You must use batch=64 subdivisions=64 for training

https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

> Note: if error Out of memory occurs then in .cfg-file you should increase subdivisions=16, 32 or 64: link

**Comment by Faultiness** [comment]
Thanks for your reminder and sorry for such a stupid question. I confused the batch and subdivisions. I'll try to train the model again. Thanks again for your contribution to Yolo.

**Comment by Faultiness** [comment]
I tried to re-train the Yolov4x-mish with `batch=64` and `subdivisions=32` on RTX 3090 and the result goes great now. Thanks for your suggestion.

But, when I tried to train the Yolov4-tiny and the same situation happened again. Here is the chart.png when I trained the Yolov4-tiny:
![chart_yolov4-tiny](https://user-images.githubusercontent.com/12472447/105677160-7c13cb00-5f26-11eb-8c3b-c99a5fc88ab2.png)

Since the mAP looks good so I decided to early stop at 2400 iteration and used the *_last.weight for prediction. And the same situation occurred to me. I was unable to get any results. The confidence of the result goes down to 15%.

Then I tried to use Yolov4x-mish I trained to identify the images I mentioned before. And the result is great with confidence up to 98%.

What could be the reason for this time?

### More infos about the training of Yolov4-tiny:
Pre-train weights I used for training: [yolov4-tiny.conv.29](https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-tiny.conv.29)
cfg file: [yolov4-tiny.cfg](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4-tiny.cfg) and I modified these lines:
Changed Line 6 and Line 7 to `batch=64` and `subdivisions=16`
Changed Line 8 and Line 9 to `width=960` and `height=960`
Changed Line 21 to `max_batches=8000` cause I need to classify 4 different objects.
Changed Line 22 to `steps=6400,7200`
Changed Line 229 and Line 280 to `classes=4`
Changed Line 221 and Line 274 to `filters=27`, which equals to (classes+5)*3
Changed Line 238 and Line 289 from `random=0` to `random=1`
