### ISSUE TITLE
Take too long to clone the master repo

### ISSUE THREAD

**Issue by trocolit2** [AlexeyAB/darknet#7285]
Hello!

I used to clone this repo in the master branch in a few minutes. However, during git clone, the repository spent almost 30 minutes to complete the cloning procedure.

Maybe it will be good to check if some unnecessary files were uploaded to the repo. 

Regards.

**Comment by AlexeyAB** [comment]
I just cloned a repository https://github.com/AlexeyAB/darknet in 4 seconds.

**Comment by trocolit2** [comment]
Thanks for your fast reply! It was an issue on my internet.. I am sorry for waste your time..
