### ISSUE TITLE
"File does not have expected hash" while building with vcpkg

### ISSUE THREAD

**Issue by KangJialiang** [AlexeyAB/darknet#7286]
I've tried to using recommended vcpkg to build on win10, and failed when it downloaded darknet:x64-windows. I doubted whether it's caused by a internet error, but even if I got "yolov4-tiny.weights" directly from the given url and put it in "darknet-cache/yolov4-tiny.weights", the error still exists. Could it be possible that the "Expected hash" itself is not correct? The error messages are posted below:
Computing installation plan...
The following packages will be built and installed:
    darknet[core,cuda,cudnn,full,opencv-cuda,weights,weights-train]:x64-windows -> 2021-01-21
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\11341\AppData\Local\vcpkg\archives\09\097d094458a5f9927d4c70b6f045a97939b2fb50.zip
Starting package 1/1: darknet:x64-windows
Building package darknet[core,cuda,cudnn,full,opencv-cuda,weights,weights-train]:x64-windows...
-- Using cached C:/Users/11341/Desktop/vcpkg/downloads/AlexeyAB-darknet-00d578e327c22638ea12e73c4efb74c798c08de5.tar.gz
-- Cleaning sources at C:/Users/11341/Desktop/vcpkg/buildtrees/darknet/src/c798c08de5-d29893808b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/11341/Desktop/vcpkg/downloads/AlexeyAB-darknet-00d578e327c22638ea12e73c4efb74c798c08de5.tar.gz
-- Using source at C:/Users/11341/Desktop/vcpkg/buildtrees/darknet/src/c798c08de5-d29893808b.clean
-- Using cached C:/Users/11341/Desktop/vcpkg/downloads/darknet-cache/yolov4-tiny.weights
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:105 (message):

  File does not have expected hash:

          File path: [ C:/Users/11341/Desktop/vcpkg/downloads/darknet-cache/yolov4-tiny.weights ]
      Expected hash: [ 804ca2ab8e3699d31c95bf773d22f901f186703487c7945f30dc2dbb808094793362cb6f5da5cd0b4b83f820c8565a3cba22fafa069ee6ca2a925677137d95f4 ]
        Actual hash: [ 7d4d9fe150f9fe3ea7d2310f1445fe983b31fbf06d301c70ecfe00e8559e6f1bf940198c2dd55db772238f23ea0092fb6553558e5414f3ee173b8b28e53c5b54 ]

  Please delete the file and retry if this file should be downloaded again.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:118 (test_hash)
  ports/darknet/portfile.cmake:28 (vcpkg_download_distfile)
  scripts/ports.cmake:128 (include)

Error: Building package darknet:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: darknet:x64-windows
  Vcpkg version: 2021-01-13-unknownhash

Additionally, attach any relevant sections from the log files above.
(base) PS C:\Users\11341\Desktop\vcpkg> .\vcpkg install darknet[full]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    darknet[core,cuda,cudnn,full,opencv-cuda,weights,weights-train]:x64-windows -> 2021-01-21
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\11341\AppData\Local\vcpkg\archives\09\097d094458a5f9927d4c70b6f045a97939b2fb50.zip
Starting package 1/1: darknet:x64-windows
Building package darknet[core,cuda,cudnn,full,opencv-cuda,weights,weights-train]:x64-windows...
-- Using cached C:/Users/11341/Desktop/vcpkg/downloads/AlexeyAB-darknet-00d578e327c22638ea12e73c4efb74c798c08de5.tar.gz
-- Cleaning sources at C:/Users/11341/Desktop/vcpkg/buildtrees/darknet/src/c798c08de5-d29893808b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/11341/Desktop/vcpkg/downloads/AlexeyAB-darknet-00d578e327c22638ea12e73c4efb74c798c08de5.tar.gz
-- Using source at C:/Users/11341/Desktop/vcpkg/buildtrees/darknet/src/c798c08de5-d29893808b.clean
-- Downloading https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-tiny.weights -> darknet-cache/yolov4-tiny.weights...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:105 (message):

  File does not have expected hash:

          File path: [ C:/Users/11341/Desktop/vcpkg/downloads/temp/darknet-cache/yolov4-tiny.weights ]
      Expected hash: [ 804ca2ab8e3699d31c95bf773d22f901f186703487c7945f30dc2dbb808094793362cb6f5da5cd0b4b83f820c8565a3cba22fafa069ee6ca2a925677137d95f4 ]
        Actual hash: [ 7d4d9fe150f9fe3ea7d2310f1445fe983b31fbf06d301c70ecfe00e8559e6f1bf940198c2dd55db772238f23ea0092fb6553558e5414f3ee173b8b28e53c5b54 ]

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:195 (test_hash)
  ports/darknet/portfile.cmake:28 (vcpkg_download_distfile)
  scripts/ports.cmake:128 (include)

Error: Building package darknet:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: darknet:x64-windows
  Vcpkg version: 2021-01-13-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by dsbyprateekg** [comment]
@KangJialiang follow the below link to solve this error-
[https://github.com/microsoft/vcpkg/issues/15256](url)

**Comment by KangJialiang** [comment]
A good workaround for me, thank you.

**Comment by hadi-ghnd** [comment]
@KangJialiang did you solve this issue? The link in @dsbyprateekg answer doesn't work for me

**Comment by KangJialiang** [comment]
@hadi-ghnd It has been a long time since my last attempt to compile it in Windows. That link worked, but I cannot quite remember why I still failed in the end. Ubuntu is obviously a much simpler and more straightforward way for that.

**Comment by hadi-ghnd** [comment]
@KangJialiang thanks. that error was solved but I am getting other errors. Ubuntu seems like the best option
