### ISSUE TITLE
How to get absolute coordinates of grid cell in get_yolo_detections?

### ISSUE THREAD

**Issue by AntMorais** [AlexeyAB/darknet#7289]
Hello everyone.

I need to get the absolute coordinates of the bounding boxes in the _get_yolo_detections_ function in the _yolo_layer.c_ file.
Bounding boxes in that function have relative coordinates with respect to a grid cell, so my question is how do I get the absolute coordinates for that grid cell.
Thank you.

**Comment by AntMorais** [comment]
Solved by using the _box_to_boxabs_ function from  _utils.c_.

```
box * bbox = &dets[count].bbox;
boxabs boxab = box_to_boxabs(bbox, w, h, 1);
float center_x = boxab.left + (boxab.right - boxab.left) / 2;
float center_y = boxab.top + (boxab.bot - boxab.top) / 2;
```

**Comment by akashAD98** [comment]
@AntMorais hey im looking for bbox without applying NMS ,Can you please help me to figure out it?
