### ISSUE TITLE
The weights file is not automatically saved

### ISSUE THREAD

**Issue by 1027663760** [AlexeyAB/darknet#7296]
![1](https://user-images.githubusercontent.com/26378634/105805814-b8810e80-5f9a-11eb-84fd-605524acc08e.png)
![2](https://user-images.githubusercontent.com/26378634/105805819-ba4ad200-5f9a-11eb-9f63-a532523b3b83.png)
yolov4-tiny-3l_1000.weights Why does this file not appear?

**Comment by 1027663760** [comment]
[net]
max_batches=14000
@AlexeyAB

**Comment by Ashinhuang** [comment]
I had the same problem, did you solve it?@1027663760
