### ISSUE TITLE
cuda_convert_f32_to_f16()no kernel image is available for execution on the device  

### ISSUE THREAD

**Issue by MickyNQN** [AlexeyAB/darknet#7299]
Hi, all!
Today, i build all my dataset in RTX3090 ( cuda 11). When it finished, i copy result (weight,cfg) to my old PC ( RTX2080ti). 
But, when linking, this error message appears:

> CUDA status Error: file: C:/Library/darknet/darknet-master/src/convolutional_kernels.cu : cuda_convert_f32_to_f16() : line: 138

> CUDA Error: no kernel image is available for execution on the device

> CUDA Error: no kernel image is available for execution on the device: Invalid argument

Here is my screenshot:

Could you help me resolve this problem?

Thanks in advance!

**Comment by AlexeyAB** [comment]
If you use Cmake for building, then you should compile on the target computer where you will use it.

@cenit Do we use currently only CUDA Compute Capability for the current GPU, or several CC 3.5, 7.5, 8.0 by default?

**Comment by MickyNQN** [comment]
I use Cmake GUI for building darknet project. So, i only see "CUDA_Architectures" section which may relative to target GPUs.
I choose it as "Auto", is it wrong ?
Thanks @AlexeyAB

**Comment by MickyNQN** [comment]
![image](https://user-images.githubusercontent.com/8621084/105937968-33285780-6089-11eb-877c-325cf8e26180.png)
Here is my screenshot of Cmake GUI.

**Comment by AlexeyAB** [comment]
Auto means that it will be built for only current GPU RTX 3090.
* Or build Darknet on RTX 2080Ti PC.
* Or Try to set ALL or Common.

**Comment by MickyNQN** [comment]
Thank you verymuch @AlexeyAB!

**Comment by cenit** [comment]
In the latest CMake update situation is not improved very much. That line is unfortunately lost. CMake will default to building to current GPU, but you can manually override and tell as many architectures that you want.
Maybe we can re-add an "ALL" option made by ourself, just to make it easy for non-expert people, to build darknet on a pc and be able to run it also on others with different configs
