### ISSUE TITLE
cudnn_half=0, but Makefile has changed to 1

### ISSUE THREAD

**Issue by RainbowSun11Q2H** [AlexeyAB/darknet#7303]
Thanks for you code and work.

I have updated my code to your newest version yesterday.

However, when I make the code, I have set the cudnn_half=1. But when I train and test, the cudnn_half still equals 0.

Moreover, the inference speed is very slow based on the trained weights. 

My cuda is 10.2, cudnn is 8.0.4 

![image](https://user-images.githubusercontent.com/63624265/106122347-930b2500-6193-11eb-86be-8e3ac2701b5c.png)

Thanks for your time.

**Comment by shubham-shahh** [comment]
https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html

there's no version cudnn 8.0.4 mentioned in above link

**Comment by RainbowSun11Q2H** [comment]
> https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html
> 
> there's no version cudnn 8.0.4 mentioned in above link

Got it. Thanks.
