### ISSUE TITLE
cudnn_half=0, but Makefile has changed to 1

### ISSUE THREAD

**Issue by RainbowSun11Q2H** [AlexeyAB/darknet#7304]
Thanks for your work.

I have changed the CUDNN_HALF to 1, but the cudnn_half in training and inference is still 0.

The repo is updated yesterday. The previous version is OK.
 
My cuda is 10.2 
cudnn is 8.0.4 (I tried 7.6.5, the situation is same)

![image](https://user-images.githubusercontent.com/63624265/106136536-68759800-61a4-11eb-823b-eeafe3dc6e62.png)

Thanks for your time.

**Comment by RainbowSun11Q2H** [comment]
I have tried the repo (Download on Dec 11, 2020).

The cudnn_half = 1 when I changed the Makefile. 

![image](https://user-images.githubusercontent.com/63624265/106137414-a1fad300-61a5-11eb-9b70-e4b1ba12f655.png)

**Comment by xufuzhi** [comment]
I had the same problem.
My cudnn is also 8.0.4, but I'm not sure it's cudnn's problem.

**Comment by RainbowSun11Q2H** [comment]
> I had the same problem.
> My cudnn is also 8.0.4, but I'm not sure it's cudnn's problem.

I solved this problem by compile using make.
Now cudnn_half = 1.

**Comment by xufuzhi** [comment]
I solved it too.
Add this line in cmakelists.txt: `set(CMAKE_CUDA_ARCHITECTURES 75)`
This new variable be added in latest version but not be initialize.
CMake18 defaults this value to 52 which  does not support fp16.
