### ISSUE TITLE
What if after calculating anchors, there is a yolo layer without any?

### ISSUE THREAD

**Issue by Scolymus** [AlexeyAB/darknet#7305]
I have a quick question about recalculating anchors. In yolov4, if you have anchors with less than 30x30 they go to layer 1. Then, in between 30x30 and 60x60 go to layer 2. Else, layer 3. But what if after recalculating anchors, there is some layer that do not have anchors (because they're bigger or smaller for that layer)? Can you leave it like "mask="? Would you remove that layer? or simply, would you create one specific for that layer even anchors did not show you any for that layer?

I think the easiest would be to add one random, and have one more anchor in the system, but just in case I preferred to ask it.

**Comment by AlexeyAB** [comment]
> or simply, would you create one specific for that layer even anchors did not show you any for that layer?

This is the best way.

**Comment by idoadse** [comment]
I had 2 followup questions to this issues as this answer partially answer it:
1. Is there additional changes to perform in this case? I mainly refer to the comment `filters=(classes + 5)*<number of mask> before each [yolo]-layer`, which means filters will need recalculation as <number of mask>=10 now
2. Generally speaking, is it correct to state the the smaller detected elements are, the smaller the anchors will be? And more particularly, if I have no >60 anchors and my detected objects will *always* be smaller than 60px*60px - will you suggest disabling the last layer?
