### ISSUE TITLE
object detection & overlapping objects

### ISSUE THREAD

**Issue by zanaviska** [AlexeyAB/darknet#7311]
I'm trying to create model which should detect object(any object on background) so my marked photos looks like this 
![image](https://user-images.githubusercontent.com/31745527/106281946-98767700-6248-11eb-8063-f714a6a01042.png)

So I have 2 question:
1) Іs there a better way than to create a set of tagged images that would contain all valid objects? It seems that this method is not very suitable for me, because it finds a specific object, and I need any object in the background, and I'm not sure if I can predict all possible objects
2) If I marked 2 objects, and their squares is overlapping, will program recognize them well? So will the following image be good example for training? 
![image](https://user-images.githubusercontent.com/31745527/106282867-dc1db080-6249-11eb-83c8-97d62b5fb90c.png)

**Comment by stephanecharette** [comment]
I'm not sure how I would handle your first question.  But your 2nd question is definitely answered on this page:  https://www.ccoderun.ca/darkmark/ImageMarkup.html

**Comment by rsek147** [comment]
In your first question, do you want to achieve what is described in the following paper?
https://www.amazon.science/publications/class-agnostic-object-detection
