### ISSUE TITLE
Run inference on particular GPU id

### ISSUE THREAD

**Issue by aksub99** [AlexeyAB/darknet#7321]
Hi!
How can I run inference with `./darknet test` on a particular gpu id?
For example, on a cluster with 4 GPUs, I would like to run the inference on GPU 2. I tried setting `-gpus 2` but this didn't seem to work.

**Comment by stephanecharette** [comment]
See the readme which has some examples showing how to do this.  `-gpus` is the flag used during training.  The flag used during inference for some strange reason is different:  `-i`.  E.g.,:

> Yolo v3 Tiny on GPU #1: `darknet.exe detector demo cfg/coco.data cfg/yolov3-tiny.cfg yolov3-tiny.weights -i 1 test.mp4`

**Comment by aksub99** [comment]
Ah I see, I had no idea that `-i` was referring to the id. Thanks a lot @stephanecharette !
