### ISSUE TITLE
Anchor dimensions

### ISSUE THREAD

**Issue by mate-cape** [AlexeyAB/darknet#733]
What are the dimensions of anchor boxes in YOLOv2 and v3?Because from the significant differences in the .cfg files it seems that they are different.

Is v3 just simply in pixels? 

And is v2 defines it relative to the output 'cell size' (or in other terms, the downsampling factor)? So that anchor box dimensions are relative to a 32x32 px square?

I'm asking it as I'm trying to change the output cell size to 16x16, and I guess in this case I need to multiply anchor dimensions by two to keep the same boxes.

**Comment by AlexeyAB** [comment]
* Yolo v2 - anchor size is relative to **output** network resolution
* Yolo v3 - anchor size is relative to **input** network resolution

----

* For **default models Yolo v2** with `width=416 height=416 num=5` you can calculate anchors using:
`darknet.exe detector calc_anchors data/obj.data -num_of_clusters 5 -width 13 -height 13`

* For **any models of Yolo v3** with `width=416 height=416 num=9` you can calculate anchors using:
`darknet.exe detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416`

**Comment by mate-cape** [comment]
Thanks @AlexeyAB!
