### ISSUE TITLE
different subdivisions needed for YOLOv4 compared to YOLOv3?

### ISSUE THREAD

**Issue by matt-sharp** [AlexeyAB/darknet#7337]
When running YOLOv4 on exactly the same data and configuration as a previous model built successfully using YOLOv3 I got a CUDA out of memory error.  The error message indicated that I should increase my subdivisions to 64.  The only difference with the cfg file is the option for mosaic data augmentation which I have set to 1 and was not available in YOLOv3.
Below is the top section of my cfg file.  After changing subdivisions to 64 it now works but I'm not sure why.

[net]
# Testing
#batch=1
#subdivisions=1
# Training
batch=64
subdivisions=16
width=608
height=608
channels=3
momentum=0.949
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
burn_in=1000
max_batches = 500200
policy=steps
steps=400000,450000
scales=.1,.1

#cutmix=1
mosaic=1

**Comment by stephanecharette** [comment]
> When running YOLOv4 on exactly the same data and configuration as a previous model built successfully using YOLOv3 I got a CUDA out of memory error.

Note that v4 does take more memory than v3:  https://www.ccoderun.ca/programming/darknet_faq/#memory_consuption

**Comment by matt-sharp** [comment]
> > When running YOLOv4 on exactly the same data and configuration as a previous model built successfully using YOLOv3 I got a CUDA out of memory error.
> 
> Note that v4 does take more memory than v3: https://www.ccoderun.ca/programming/darknet_faq/#memory_consuption

Thanks for the explanation, this makes sense.  
I'm looking to increase the size of my network for my next experiment.  If I receive an out of memory again error using subdivisions=64 does that mean I've reached the limit of what my GPU can process and is my only option then to reduce the config size?

**Comment by stephanecharette** [comment]
No.  Go back and read the link.  For example yolo-tiny takes a lot less memory than yolo.  So the first thing I would do is choose a better-suited configuration for the hardware.  If that is not an option and you don't want to reduce the dimensions of the network, then I guess the next thing would be to decrease the batch size from 64 to 32.

**Comment by matt-sharp** [comment]
> No. Go back and read the link. For example yolo-tiny takes a lot less memory than yolo. So the first thing I would do is choose a better-suited configuration for the hardware. If that is not an option and you don't want to reduce the dimensions of the network, then I guess the next thing would be to decrease the batch size from 64 to 32.

Ok, thanks for the guidance.  It seems like 64 is always used for the batch size so I assumed this was the most optimal parameter never to be changed.  Makes sense to reduce this, just that I've not seen it mentioned anywhere else.
