### ISSUE TITLE
which files does make edit when Darknet is compiled?

### ISSUE THREAD

**Issue by matt-sharp** [AlexeyAB/darknet#7339]
Is this just those contained within src and include directories?

The reason I ask is because the AWS environment I'm executing YOLOv4 in is restricted so I can't run the make command. To circumvent this I'm compiling Darknet in Google Colab and then uploading the whole directory into my Darknet directory on my AWS instance.
Now I just want to upload the parts changed by make and I want to be sure I'm not breaking anything.

**Comment by shubham-shahh** [comment]
in src, object files are created, plus outside src, the darknet shared object file is also modified.

**Comment by awaisbajwaml** [comment]
Why dont you spin off an EC2 from scratch and do whatever you want to do? 

May I know which machine you are using on AWS?

**Comment by matt-sharp** [comment]
> Why dont you spin off an EC2 from scratch and do whatever you want to do?
> 
> May I know which machine you are using on AWS?

I haven't been given any AWS credentials for this project.  The environment sits behind a firewall which I connect to via VPN and the image is managed by someone else.  So, I can't connect to external resources when compiling Darknet and it fails when trying to connect to Nvidia.

**Comment by shubham-shahh** [comment]
> Is this just those contained within src and include directories?
> 
> The reason I ask is because the AWS environment I'm executing YOLOv4 in is restricted so I can't run the make command. To circumvent this I'm compiling Darknet in Google Colab and then uploading the whole directory into my Darknet directory on my AWS instance.
> Now I just want to upload the parts changed by make and I want to be sure I'm not breaking anything.

do note that while compilation, darknet also refers to /include/darknet.h

**Comment by stephanecharette** [comment]
> do note that while compilation, darknet also refers to /include/darknet.h

Can you elaborate on this statement?  Darknet does not expect, require, or attempt to include a file named `/include/darknet.h` as far as I can tell.

**Comment by shubham-shahh** [comment]
sir, darknet.h consists of function definition of test_detector, the changes made in this file are consided while compilation.

**Comment by matt-sharp** [comment]
> sir, darknet.h consists of function definition of test_detector, the changes made in this file are consided while compilation.

So, to confirm:  If I copy src + include directories and the darknet shared object file from Colab into my AWS directory then this covers everything that is updated after compilation?

**Comment by shubham-shahh** [comment]
> > sir, darknet.h consists of function definition of test_detector, the changes made in this file are consided while compilation.
> 
> So, to confirm: If I copy src + include directories and the darknet shared object file from Colab into my AWS directory then this covers everything that is updated after compilation?

include folder is required for compilation, not after compilation. and imo you should be fine with those files

**Comment by matt-sharp** [comment]
Thanks for the guidance, I've compiled and uploaded into AWS a few times now and everything seems to be working.

**Comment by shubham-shahh** [comment]
please conclude your steps so that someone in the future can benefit from it.
