### ISSUE TITLE
Please tell me how to find the number of epochs on the darknet.

### ISSUE THREAD

**Issue by vhkjhk** [AlexeyAB/darknet#7344]
I'm not familiar with image recognition.
Training for custom objects.
Please tell me how to find the number of epochs on the darknet.
Max_batches = 6000.  Class = 1. Batch = 64.  Number of Images = 500. learning_rate = 0.001
Please tell me how to find it🙇‍♂️

**Comment by aparico** [comment]
epoch=max_batches/(total_num_images/(batch*no. of gpu))
If no. of gpu =1, then:
epoch=6000/(500/64)=768

**Comment by vhkjhk** [comment]
Thank you very much. It was really easy to understand.

**Comment by aparico** [comment]
> Thank you very much. It was really easy to understand.

Glad to help. I think you can close this issue now if your question has been answered.
