### ISSUE TITLE
Training switches between gpu and cpu utilization

### ISSUE THREAD

**Issue by RobinBram** [AlexeyAB/darknet#7363]
At the start of every batch, the gpu usage goes to zero and the cpu usage goes to 100%. What could be the reason for this?
![image](https://user-images.githubusercontent.com/70885556/107521968-761f1a80-6bb3-11eb-8096-171c626cdae3.png)

**Comment by RobinBram** [comment]
I'm training yolov4tiny with this configuration:
[net]
# Testing
#batch=1
#subdivisions=1
# Training
batch=512
subdivisions=32
width=416
height=416
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

**Comment by stephanecharette** [comment]
Needing to load images from disk, performing things like mosaic, resizing images, etc.

**Comment by RobinBram** [comment]
Thank you for your answer. Well it seems like a very inefficient use of computing power. How can i speed this up. I tried setting OPENCV=1 in Makefile but I'm not sure it made any difference.

**Comment by RobinBram** [comment]
I also tried removing all the data augmentation specified in the cfg file

**Comment by RobinBram** [comment]
THe issue is now solved. I think it may hjave been a problem with opencv. I installed opencv after darknet before. Now I reinstalled darknet after I installed opencv
