### ISSUE TITLE
Vcpkg install on Windows with RTX 3080 is broken

### ISSUE THREAD

**Issue by ROBYER1** [AlexeyAB/darknet#7376]
Installation via vcpkg windows 10, have prerequisites installed, VS 2017 community, Cuda 11.1, matched cudnn version

System is Windows 10 with an RTX 3080

Installation via the [full] method has build failure at OpenCV4 build stage, building with the darknet[opencv-base,cuda,cudnn]:x64-windows command builds fine.

Darknet works when running
./darknet imtest data/eagle.jpg

However, running any test train or train commands result in the console showing Layer 0 and nothing happens, no errors nothing. I had to reinstall Windows lately so I was testing both in the darknet folder with the test script, and within my projects I was running prior to the winfows reinstall. 

Building this way on a system with a 20 series RTX GPU works fine so this is exclusive to the 30 series cards

Not my screenshot but this is what it looks like:
![image](https://user-images.githubusercontent.com/10745594/107886810-3b421d00-6efa-11eb-9900-d6fcef30778a.png)

```
./darknet detector test cfg/coco.data cfg/yolov4.cfg yolov4.weights data/dog.jpg
 CUDA-version: 11.1, cuDNN: 8.0.5, CUDNN_HALF=1, GPU count: 1
 CUDNN_HALF=1
 OpenCV version: 4.5.1
 0 : compute_capability = 860, cudnn_half = 1, GPU: GeForce RTX 3080
```

For now I am going to try building again with cmake but can this be investigated please?

**Comment by ROBYER1** [comment]
To get the build working at all using the cmake process on windows I had to download OpenCV 4.5.1 from here https://opencv.org/releases/ and clicked on the windows button, which downloads a .exe file, extracted it to a proper localtion using the .exe
also i added 
C:\<path where you downloaded opencv>\opencv\build\x64\vc15\bin
 to my path and added an OpenCV_DIR variable to my system variables with this value 
C:\<path where you downloaded opencv>\opencv\build

Once that was done, to actually build darknet I had to follow the cmake proces but also I had to do this:

1.In cmake GUI change the CUDA Architecture to 86 as it autodetected as 52 for no good reason
2. Then it would let me set CUDNN to on in Cmake once I changed the architecture number 
3. You need to put "pthreadGC2.dll" and "pthreadVC2.dll" from the darknet git repo into the Release directory manually, which is not documented anywhere. Darknet would not run until I moved those two files which were not mentioned anywhere in setup?!

**Comment by MiguelEsteve** [comment]
I have followed exactly the same steps you mention Ihave the same problem.
Darknet gets hanged and several far wawy minutes, does not predict on the  basic test run test.
![imagen](https://user-images.githubusercontent.com/5907561/114231748-1fe41300-997b-11eb-9021-88aa85e63820.png)

**Comment by MiguelEsteve** [comment]
People has to be very unprofessional and have little shame to say that this Darknet crap can be run on windows with RTX 3090 by following the instructions on the web. It is simply a nigtmare.
