### ISSUE TITLE
How to crop out all the bounding boxes with pictures. 

### ISSUE THREAD

**Issue by mrigankchugh** [AlexeyAB/darknet#7378]
I want a video with a black background and only the detected bounding boxes with the picture inside should be visible in the frame.

**Comment by stephanecharette** [comment]
Neither Darknet nor DarkHelp currently provide that functionality.  It is a bit too specific.  But anyone with a bit of OpenCV and C/C++ could write something up relatively easily to do exactly that.

**Comment by mrigankchugh** [comment]
Thanks a lot for the quick reply. I will try to code that myself!
