### ISSUE TITLE
Is darknet only limited to 5 annotations per image?

### ISSUE THREAD

**Issue by androuino** [AlexeyAB/darknet#7386]
I was training with custom datasets with 13 classes or names annotated per single image but the console is giving me a warning of the **Wrong annotation: class_id 13. But class_id should be [from 0 to 4]**

I guess this is where it's checking it:
https://github.com/AlexeyAB/darknet/blob/64efa721ede91cd8ccc18257f98eeba43b73a6af/src/data.c#L223

My question is, is there a way to increase the limit from 5 up to something like the size of the classes? Is that possible?

Thanks in advance.

**Comment by stephanecharette** [comment]
My guess is something you've done is wrong.  I have some images with hundreds of annotations, and I have some projects with dozens of classes.

The line you quote above is where it reads in the 5 values that make up a single annotation.  If it doesn't return 5, then your annotations are corrupted.  The annotation format is shown here:  https://www.ccoderun.ca/programming/darknet_faq/#darknet_annotations

You'll note the 5 numbers that make up the class id, the point, and the size all add up to 5.

**Comment by androuino** [comment]
oh, I see, so the 5 is expecting the 5 values from coco annotations that were split by space. Hmmm maybe, you're right, something got wrong with my annotations.
