### ISSUE TITLE
train yolov3 on this version of darknet

### ISSUE THREAD

**Issue by TIMETOTIAO** [AlexeyAB/darknet#7396]
Just want to confirm that if I use the yolov3.cfg with this version of darknet, I will get the same and compatibale result(or .weights) as Joseph's darknet right?
Thanks

**Comment by stephanecharette** [comment]
The "same"?  That's hard to say.  Joseph's darknet was abandoned quite a few years ago now, and many fixes have been made since then.

But it should be compatible, yes, and if not exactly the same, it should be very similar.
