### ISSUE TITLE
do I have to increase max_batches when I increase the number of trainset?

### ISSUE THREAD

**Issue by LeRoii** [AlexeyAB/darknet#7420]
It is suggested that max_batches to be 2000*classes,
let's say I have a dataset of 8 classes with 5000 images, the max_batches should be 16000,
when I double the number of image to 10000, the number of classes is still 8, is it okay to keep max_batches unchanged? 
Thanks in advance

**Comment by matt-sharp** [comment]
Follow the guidance for training your own custom dataset:

`change line max_batches to (classes*2000 but not less than number of training images, but not less than number of training images and not less than 6000), f.e. max_batches=6000 if you train for 3 classes`
