### ISSUE TITLE
Output frame number with object and bounding box coordinates

### ISSUE THREAD

**Issue by willcheng00** [AlexeyAB/darknet#7421]
I need to output the frame number along with the object class and its bounding box coordinates. I use the command

./darknet detector demo ./cfg/coco.data ./cfg/yolov4.cfg weights/yolov4.weights 
-ext_output test.mp4 -gpus 1

I get these on the standard output (i.e.,, output to screen):

FPS:9.0 	 AVG_FPS:0.0

umbrella: 40% 	(left_x:  222   top_y:   80   width:  233   height:  101)
umbrella: 30% 	(left_x:  222   top_y:   81   width:  131   height:  103)

It would be nice to get the frame number as well, e.g.,

frame55, umbrella: 40% 	(left_x:  222   top_y:   80   width:  233   height:  101)

If anyone knows how to do it, that'd be much appreciated! Thank you!

**Comment by russskiykorablidinah** [comment]
Hello.
Can you tell me how did you solve this issue?
Thanks
