### ISSUE TITLE
Failed to build darknet with openCV 

### ISSUE THREAD

**Issue by athulvingt** [AlexeyAB/darknet#7427]
when tried to build  with
GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=1

I got this error 
```
collect2: error: ld returned 1 exit status
Makefile:176: recipe for target 'darknet' failed
make: *** [darknet] Error 1
```

**Comment by stephanecharette** [comment]
That's not the error.  That's the message telling you the build failed.  The error would be printed just prior to that text.

**Comment by athulvingt** [comment]
These are the last few lines, but  I don't understand anything from these
```
obj/image_opencv.o: In function `cvflann::anyimpl::big_any_policy<cv::String>::move(void* const*, void**)':
image_opencv.cpp:(.text._ZN7cvflann7anyimpl14big_any_policyIN2cv6StringEE4moveEPKPvPS5_[_ZN7cvflann7anyimpl14big_any_policyIN2cv6StringEE4moveEPKPvPS5_]+0x10): undefined reference to `cv::String::deallocate()'
image_opencv.cpp:(.text._ZN7cvflann7anyimpl14big_any_policyIN2cv6StringEE4moveEPKPvPS5_[_ZN7cvflann7anyimpl14big_any_policyIN2cv6StringEE4moveEPKPvPS5_]+0x24): undefined reference to `cv::String::deallocate()'
obj/image_opencv.o: In function `cv::String::String(char const*)':
image_opencv.cpp:(.text._ZN2cv6StringC2EPKc[_ZN2cv6StringC5EPKc]+0x30): undefined reference to `cv::String::allocate(unsigned long)'
obj/http_stream.o: In function `MJPG_sender::write(cv::Mat const&)':
http_stream.cpp:(.text._ZN11MJPG_sender5writeERKN2cv3MatE[_ZN11MJPG_sender5writeERKN2cv3MatE]+0x1d6): undefined reference to `cv::imencode(cv::String const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
http_stream.cpp:(.text._ZN11MJPG_sender5writeERKN2cv3MatE[_ZN11MJPG_sender5writeERKN2cv3MatE]+0x1de): undefined reference to `cv::String::deallocate()'
http_stream.cpp:(.text._ZN11MJPG_sender5writeERKN2cv3MatE[_ZN11MJPG_sender5writeERKN2cv3MatE]+0x710): undefined reference to `cv::String::deallocate()'
collect2: error: ld returned 1 exit status
```

**Comment by stephanecharette** [comment]
Did you try to google any of those errors?  To me, it looks like OpenCV wasn't built correctly.

**Comment by athulvingt** [comment]
The problem was something related to open CV, I followed the following step and it worked for me


**Step 1**
```
cd $home
mkdir OpenCV
cd OpenCV
git clone https://github.com/opencv/opencv.git
git clone https://github.com/opencv/opencv_contrib.git

```
**Step 2**
```
mkdir build_opencv
cd build_opencv
```
**Step 3** configure the opencv by executing cmake, as per the following command:
`cmake -DCMAKE_BUILD_TYPE=Release -D OPENCV_GENERATE_PKGCONFIG=ON -DBUILD_EXAMPLES=ON -D CMAKE_INSTALL_PREFIX=/usr/local ../opencv `

**Step 4** build using the following command
`make -j7`

**Step 5** If all goes well it should build successfully and you can execute the following command to install opencv
`sudo make install`

**Step 6** Once it installed successfully you can test that pkg-config is configured properly using the following command
`pkg-config --cflags opencv4`

You should get an output like this:
`-I/usr/local/include/opencv4`

Try to compile darknet again, if you encounter the error where it still can’t find opencv.pc, you might want to check that you have the opencv4.pc in the following location. _I didn't have to do step 7, OpenCV got installed properly. Since I saw this also in the source where I found the solution, I am posting it here._

> **Step 7**
> `ls /usr/local/lib/pkgconfig/opencv4.pc`
> 
> if you do then just copy opencv4 to opencv by using the following command
> `sudo cp /usr/local/lib/pkgconfig/opencv4.pc /usr/local/lib/pkgconfig/opencv.pc`
> 
> Now try to compile darknet again but first you will need to change the option opencv=1 in the Makefile. When you try to run the make command you might get the following error if you are using opencv version 4
> `error: #error "OpenCV 4.x+ requires enabled C++11 support"`
> 
> To solve this you will need to edit the Makefile by adding the -std=c++11 in the following line:
> `CPP=g++ -std=c++11`

**Step 8**Finally
`nano ~/.bashrc`
and then add the following line at the end of the file

**Comment by RohitKeshari** [comment]
Thanks @athulvingt, I am able to build darknet with some warnings but needed step 7 (for pkg-config). However I am getting the following error:
```
./darknet: error while loading shared libraries: libopencv_cudabgsegm.so.3.4: cannot open shared object file: No such file or directory
```

OpenCV version: 3.4.0

**Comment by athulvingt** [comment]
@RohitKeshari I am not an expert in this and I did only training on the darknet framework. I did inference using python and OpenCV
