### ISSUE TITLE
Error occurred when running python3 darknet_video.py

### ISSUE THREAD

**Issue by GTSyu** [AlexeyAB/darknet#7435]
As the title showed above. While I was running `python3 darknet_video.py` , the error showed bellow occurred
Does anyone here met this problem before or can help me out with this? Thank you so much.

![Screenshot from 2021-02-27 14-52-35](https://user-images.githubusercontent.com/73150188/109378317-784fdb80-790c-11eb-825e-9aae04d8a1ff.png)

**Comment by shubham-shahh** [comment]
you are using the Jetson device? Gstreamer is unable to access the cam

**Comment by GTSyu** [comment]
> you are using the Jetson device? Gstreamer is unable to access the cam

yeah this happened on jetson xavier NX. But the problem has solved somehow after I redefine the cam path
