### ISSUE TITLE
How to add new class/category on custom trained weights

### ISSUE THREAD

**Issue by danzigjabalpur** [AlexeyAB/darknet#744]
I have trained a set of weights to detect my custom objects of one class. If wanted to add another class, what do I need to change or add?

1. let say class 0 is damaged cables and class 1 is curled cables,
For the 2nd class,assuming i only have one object/class per image does my YOLO annotations need to be labeled as a 2nd class? 
e.g: 0 xxxx xxxx xxxx  -- where 0 is first class
1 xxxx xxxx xxxx -- where 1 is 2nd class.
Because right now I have them all annotated as single classes (class 0). So i was wondering if I can train new classes without needing to adjust the annotations.

2. I know that i would have to change number of classes in obj.cfg & obj.data and add a new class label into obj.names but I'm not sure about the annotated images part. can i put the images of different category/class into different folders or do I have to dump all images inside one main folder?

**Comment by AlexeyAB** [comment]
> e.g: 0 xxxx xxxx xxxx -- where 0 is first class
> 1 xxxx xxxx xxxx -- where 1 is 2nd class.

If you want to detect Damaged cables and Curled cables as the same class, then use `0` for both
If you want to detect Damaged cables and Curled cables as different classes, then use `0` for Damaged and `1` for Curled

**Comment by danzigjabalpur** [comment]
Thanks for clarifying, @AlexeyAB
