### ISSUE TITLE
The predict result problem

### ISSUE THREAD

**Issue by er778899789** [AlexeyAB/darknet#7446]
Whwn I finish training the model with yolov4,and the result is look pretty good.
I use it to test my test datasets, the accuracy is nice but sometimes will happend double recognize.
What's the reason to cause the problem?

![擷取](https://user-images.githubusercontent.com/32409355/109577503-a31a7980-7b30-11eb-9bc3-77b1e13a36fd.PNG)

**Comment by stephanecharette** [comment]
How many classes (0-9 plus A-Z?) and how many iterations did you train?

I don't know if this is the same thing, but have a look at this page.  I found I would get lots of duplicates when I didn't train enough iterations:  https://www.ccoderun.ca/programming/2020-01-04_neural_network_training/#Details

**Comment by er778899789** [comment]
@stephanecharette 
12 classes (0-9 plus B,C)
I train about 1200 iterations, and result is pretty good. So I think is enough to use in the project.
Only the duplicates bounding box is Annoying.

**Comment by stephanecharette** [comment]
The *MINIMUM* you should train is 6000 iterations or 2000 * the number of classes.  (See the readme.)  So with 12 classes, you should train for 12,000 iterations.

**Comment by er778899789** [comment]
@stephanecharette 
Oh , I see.
Thanks for answer my question.
