### ISSUE TITLE
error: identifier "cudaStreamCaptureModeGlobal" is undefined

### ISSUE THREAD

**Issue by RohitKeshari** [AlexeyAB/darknet#7452]
I have older version of this repo which is working fine but current version giving the following error:  

./src/network_kernels.cu(706): error: identifier "cudaStreamCaptureModeGlobal" is undefined

./src/network_kernels.cu(706): error: too many arguments in function call

2 errors detected in the compilation of "/tmp/tmpxft_0001639c_00000000-9_network_kernels.compute_61.cpp1.ii".
make: *** [obj/network_kernels.o] Error 1

 CUDA Version: nvcc -V 
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

```
NVIDIA driver
```
NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0
```

MakeFile setup
```
GPU=1
CUDNN=0
CUDNN_HALF=0
OPENCV=0
AVX=1
OPENMP=1
LIBSO=1
ZED_CAMERA=0
ZED_CAMERA_v2_8=0
```

**Comment by AlexeyAB** [comment]
Currently Darknet supports CUDA >= 10.0

Show output of
```
nvcc --version
```

**Comment by octavflorescu** [comment]
wasn't this introduced with CUDA 10.1? (cudaStreamCaptureModeGlobal)

**Comment by AlexeyAB** [comment]
It seems yes, it was added in CUDA 10.1, because there was an issue for CUDA 10.0 https://github.com/triton-inference-server/server/issues/635#issuecomment-529274175

In general this is related to this feature, that can accelerate any neural network +20% for Inference (Detection): https://github.com/AlexeyAB/darknet/issues/7444

**Comment by huangpan2507** [comment]
> wasn't this (cudaStreamCaptureModeGlobal) introduced with CUDA 10.1? ... from here [triton-inference-server/server#635](https://github.com/triton-inference-server/server/issues/635)
> In order to temporary be able to build, i have just commented out the line containing this undeclared var:
> `//CHECK_CUDA(cudaStreamBeginCapture(stream0, cudaStreamCaptureModeGlobal));`

it works when  i use cuda 10.0.

**Comment by lilyswang** [comment]
@huangpan2507 Hi  I use cuda 10.0 too ,but meet the same problem could you tell me how to deal with it ? thanks alot
![image](https://user-images.githubusercontent.com/30424943/116230432-37e4d080-a78a-11eb-9938-a51076da060e.png)
![image](https://user-images.githubusercontent.com/30424943/116230474-44692900-a78a-11eb-841b-811bfec8074f.png)

**Comment by stephanecharette** [comment]
Have you done a search?

For example, see ticket #7439, #7486, #7557, as well as the text above telling you that CUDA 10.0 won't work.

**Comment by prsntmaurya** [comment]
> Currently Darknet supports CUDA >= 10.1
> 
> Show output of
> 
> ```
> nvcc --version
> ```

Thanks,
Changing CUDA version from 10.0 to 10.1 fixed the problem.

**Comment by MrComNguoi** [comment]
If you don't want to change CUDA to 10.1, just delete this line `CHECK_CUDA(cudaStreamBeginCapture(stream0,cudaStreamCaptureModeGlobal));` in file `darknet/src/network_kernels.cu`
