### ISSUE TITLE
Output all of the class probabilities for a given detected bbox yolov4

### ISSUE THREAD

**Issue by cmehrshad** [AlexeyAB/darknet#7463]
Hello,

I am using C++ version of darknet to detect objects using YoloV4. For now, I am just getting the best class's probability. I have 13 classes and I want the probability of all 13 of them for the best bounding box.

How/Where should I change the C++ code to get these values?

Thanks,

**Comment by stephanecharette** [comment]
You question is unclear.  Do you mean you are using one of several C++ darknet API?  Or you're using the original darknet C API from within your C++ application?

If you are using the DarkHelp C++ API, then `all_probabilities` is what you want:  https://www.ccoderun.ca/darkhelp/api/structDarkHelp_1_1PredictionResult.html#a8cb22ace207dc50fda85ce6993b1f4e8

If you aren't using DarkHelp but want to look up how that is implemented:  https://github.com/stephanecharette/DarkHelp/blob/master/src-lib/DarkHelp.cpp#L1189-L1203

**Comment by cmehrshad** [comment]
> You question is unclear. Do you mean you are using one of several C++ darknet API? Or you're using the original darknet C API from within your C++ application?
> 
> If you are using the DarkHelp C++ API, then `all_probabilities` is what you want: https://www.ccoderun.ca/darkhelp/api/structDarkHelp_1_1PredictionResult.html#a8cb22ace207dc50fda85ce6993b1f4e8
> 
> If you aren't using DarkHelp but want to look up how that is implemented: https://github.com/stephanecharette/DarkHelp/blob/master/src-lib/DarkHelp.cpp#L1189-L1203

Hello Stephan,

I am using the detector functionality of darknet from this repo. I have not written any additional C++ code yet. So I just build this project according to the README file and run the following command:

```sh
./darknet detector test data/objects.data cfg/yolo-custom.cfg backup_custom/yolo-custom_best.weights test.jpg -dont_show -ext_output
```

What I get as the output is:
```sh
 CUDA-version: 11020 (11020), cuDNN: 8.0.5, CUDNN_HALF=1, GPU count: 1  
 CUDNN_HALF=1 
 OpenCV version: 3.2.0
 0 : compute_capability = 750, cudnn_half = 1, GPU: GeForce RTX 2080 Ti 
net.optimized_memory = 0 
mini_batch = 1, batch = 64, time_steps = 1, train = 0 
   layer   filters  size/strd(dil)      input                output
   0 conv     32       3 x 3/ 1    608 x 608 x   3 ->  608 x 608 x  32 0.639 BF
   1 conv     64       3 x 3/ 2    608 x 608 x  32 ->  304 x 304 x  64 3.407 BF
.
.
.
 158 conv    512       1 x 1/ 1     19 x  19 x1024 ->   19 x  19 x 512 0.379 BF
 159 conv   1024       3 x 3/ 1     19 x  19 x 512 ->   19 x  19 x1024 3.407 BF
 160 conv     54       1 x 1/ 1     19 x  19 x1024 ->   19 x  19 x  54 0.040 BF
 161 yolo
[yolo] params: iou loss: ciou (4), iou_norm: 0.07, obj_norm: 1.00, cls_norm: 1.00, delta_norm: 1.00, scale_x_y: 1.05
nms_kind: greedynms (1), beta = 0.600000 
Total BFLOPS 127.418 
avg_outputs = 1049582 
 Allocate additional workspace_size = 42.19 MB 
Loading weights from backup_custom/yolo-custom_best.weights...
 seen 64, trained: 1747 K-images (27 Kilo-batches_64) 
Done! Loaded 162 layers from weights-file 
 Detection layer: 139 - type = 28 
 Detection layer: 150 - type = 28 
 Detection layer: 161 - type = 28 
test.jpg: Predicted in 376.663000 milli-seconds.
Bottle: 100%	(left_x:  530   top_y:    7   width:  147   height:  312)
➜
```

What I want is not only the class probability of bottle, but also all the other classes in this specific bbox. For instance:

bottle: 0.99, laptop: 0.5, hat: 0.0001, ... (left_x:  530   top_y:    7   width:  147   height:  312)

**Comment by stephanecharette** [comment]
I'm confused.  You talk about C++, but then the example you give is running darknet from the command-line.  If you are using C or C++ then you definitely can get the probabilities for each class if you follow the links I provided.

I don't know if that is somehow exposed when using the original Darknet CLI.  I know I do expose it in the DarkHelp CLI when using the `--json` CLI option (https://www.ccoderun.ca/darkhelp/api/ShellScripting.html).

**Comment by cmehrshad** [comment]
> I'm confused. You talk about C++, but then the example you give is running darknet from the command-line. If you are using C or C++ then you definitely can get the probabilities for each class if you follow the links I provided.
> 
> I don't know if that is somehow exposed when using the original Darknet CLI. I know I do expose it in the DarkHelp CLI when using the `--json` CLI option (https://www.ccoderun.ca/darkhelp/api/ShellScripting.html).

Hello Stephan,

Yes, I'm using darknet CLI. By C++ I meant not python (darknet.py). Unfortunately, since we are using darknet_ros on top, we cannot afford a framework change. However, I looked at your code and it gave me some ideas on where to modify the original darknet CLI codes. Will probably share it here if I had success.

Thanks,

**Comment by stephanecharette** [comment]
Just so you know, lots of people incorporate DarkHelp with ROS.  You certainly wouldn't be the first.  You don't have to change any "framework", DarkHelp is a C++ layer (and/or CLI tool) that sits on top of Darknet.

**Comment by cmehrshad** [comment]
I fixed this. Anyone who needed help please reopen it.
