### ISSUE TITLE
How to get pseudo-labelling and loss?

### ISSUE THREAD

**Issue by ebonetti** [AlexeyAB/darknet#7465]
Hello YOLO folks,
is there a way from command line to get pseudo-labelling and loss for a set of labelled images?

This is needed to validate a big dataset against mislabelling and missing labels, as suggested in your manual section ([How to improve object detection](https://github.com/AlexeyAB/darknet#how-to-improve-object-detection)). Already done this by eye and took almost a day, but I'm pretty sure I missed some.

Keep up the great work,
Enrico Bonetti Vieno

P.S.: I adore the Plug & Play simplicity and effectiveness of your library, big fan here 👍 Thanks for maintaining it!

**Comment by stephanecharette** [comment]
May want to look at the "review" parts of DarkMark as it can be used to quickly find mislabelling (though not missing labels):  https://www.ccoderun.ca/darkmark/Summary.html#DarkMarkReview

**Comment by ebonetti** [comment]
I watched a few of your videos: WOW, now that's a Tool!!
I had set up a few script to pseudo-label and later review it with YOLO Mark, but yours is the real deal!
(High chances I'll switch to yours, thanks a lot for making it!)

Mmmh, sooo, it helps but doesn't completely solve the problem, but probably it can be worked around:
- _darknet detector recall_ to calculate the loss per image; (**is there a better command I'm missing??**)
- _darknet detector test_  for pseudo-labelling;
- integrate the results;
- sort by highest loss;
- review worst N. 
(This could be an interesting addition to your tool too 😉)
