### ISSUE TITLE
bounding boxes are out of the correct location

### ISSUE THREAD

**Issue by Jureong** [AlexeyAB/darknet#7471]
To make my custom yolov3 model, I converted a dataset(its format is coco) to yolo label format and trained yolov3.
After training is done, I tested the custom model but the results are weird.
All bounding boxes are out of their location!
classes are correct but their bounding boxes are above the left diagonal.
!https://thumb1.photo.mybox.naver.com/3472444973440437292?type=m1280_1280_2&nocache=4032150603
!https://thumb1.photo.mybox.naver.com/3472444973933637677?type=m1280_1280_2&nocache=5643150603

The followings are the parameter I used.
Ubuntu : 18.04
GPU : geForce 2080ti * 2
nvidia driver : 460
CUDA, cudnn : 11.2
openCV : 3.4.0

batch 64
subdivisions 16
width, height 416
learning rate 0.001
iterations 20000

I never touched any other parameter of darknet.

And the conversion formula I used is like next. 
coco dataset format is (xmin, ymin, w, h).

'''

        dw = 1. / image_w
        dh = 1. / image_h

        print(idx, bbox)
        xmin = bbox[0] 
        ymin = bbox[1]  
        xmax = bbox[2] + bbox[0] 
        ymax = bbox[3] + bbox[1] 

        x = (xmin + xmax) / 2.0
        y = (ymin + ymax) / 2.0

        w = xmax - xmin
        h = ymax - ymin

        bbox_x = x * dw
        bbox_w = w * dw
        bbox_y = y * dh
        bbox_h = h * dh

        ann_data = str(category_id) + ' ' + str(bbox_x) + ' ' + str(bbox_y) + ' ' + str(bbox_w) + ' ' + str(bbox_h) + '\n'

'''

what's wrong with this?
Am I wrong when I converted that?

I need somebody's help ASAP.
Thanks.

**Comment by readicculus** [comment]
should be
```
w = (xmax-xmin)
h = (ymax-ymin)
x = xmin + w/2
y = ymin +h/2

bbox_w = w*dw
bbox_h = h*dh
bbox_x = x*dw
bbox_y = y*dh
```

**Comment by Jureong** [comment]
> should be
> 
> ```
> w = (xmax-xmin)
> h = (ymax-ymin)
> x = xmin + w/2
> y = ymin +h/2
> 
> bbox_w = w*dw
> bbox_h = h*dh
> bbox_x = x*dw
> bbox_y = y*dh
> ```

Thank you for replying. But the result is the same as mine.
anyway, I solved this.
dw, dh values were incorrect and I adjusted these.
