### ISSUE TITLE
Segfault in load_network_custom when used as a library

### ISSUE THREAD

**Issue by dtmoodie** [AlexeyAB/darknet#7481]
When I call load_network_custom or load_network from a library, I get a segfault.  darknet executable works correctly from command line.

Environment:
Linux Ubuntu 20.04
cuda 11.2
cudnn 8.0.5
nvidia driver = 460.39
    
```
./darknet detector test cfg/coco.data cfg/yolov4.cfg cfg/yolov4.weights data/dog.jpg
 DEBUG=1 
 CUDA-version: 11020 (11020), cuDNN: 8.0.5, CUDNN_HALF=1, GPU count: 1  
 CUDNN_HALF=1 
 OpenCV isn't used - data augmentation will be slow 
 0 : compute_capability = 860, cudnn_half = 1, GPU: GeForce RTX 3090 
net.optimized_memory = 0 
mini_batch = 1, batch = 8, time_steps = 1, train = 0 
   layer   filters  size/strd(dil)      input                output
   0 conv     32       3 x 3/ 1    608 x 608 x   3 ->  608 x 608 x  32 0.639 BF
   1 conv     64       3 x 3/ 2    608 x 608 x  32 ->  304 x 304 x  64 3.407 BF
   2 conv     64       1 x 1/ 1    304 x 304 x  64 ->  304 x 304 x  64 0.757 BF
   3 route  1                                      ->  304 x 304 x  64 
```
Output from my application:

```
Try to load cfg: /home/dan/code/ml/darknet/cfg/yolov4.cfg, weights: /home/dan/code/ml/darknet/cfg/yolov4.weights, clear = 0 
 0 : compute_capability = 860, cudnn_half = 1, GPU: GeForce RTX 3090 
net.optimized_memory = 0 
mini_batch = 1, batch = 8, time_steps = 1, train = 0 
   layer   filters  size/strd(dil)      input                output
   0 
```

Callstack from segfault:

![callstack](https://user-images.githubusercontent.com/7254941/110369005-bf7a5280-8017-11eb-80a1-94172ab2bb8a.png)

Same issue with / without CUDNN_HALF.
Issue is not present when built with CUDNN=0

**Comment by stephanecharette** [comment]
If you're trying to use the C API, take a look at how DarkHelp uses it:  https://github.com/stephanecharette/DarkHelp/tree/master/src-lib from https://github.com/stephanecharette/DarkHelp#what-is-darkhelp  (Or use DarkHelp itself.)

**Comment by dtmoodie** [comment]
I've discovered that this is an issue with cudnn when used with boost fibers.  More investigation to come.
