### ISSUE TITLE
stair_gradient_kernel") is not allowed

### ISSUE THREAD

**Issue by futureflsl** [AlexeyAB/darknet#7500]
environment:
windows 10 x64
Visual Studio 2019
cuda10.2+cudnn7.6.5
nvidia driver cuda api==11.2

compile darknet error occurred!I try at least 3 computers.in recently this error confused me.I donot konw how it happend.

警告	C4819	该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失	darknet	C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include\cuda.h	13166	
警告	C4819	该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失	darknet	C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include\cuda_runtime_api.h	9349	
警告		variable "step" was set but never used	darknet	D:\darknet-master\src\blas_kernels.cu	1130	
错误		calling a __host__ function("__floorf") from a __device__ function("stair_gradient_kernel") is not allowed	darknet	D:\darknet-master\src\activation_kernels.cu	88	
警告		variable "stage_id" was declared but never referenced	darknet	D:\darknet-master\src\blas_kernels.cu	1736	
警告		variable "cur_scale" was declared but never referenced	darknet	D:\darknet-master\src\dropout_layer_kernels.cu	140	
警告		variable "cur_scale" was declared but never referenced	darknet	D:\darknet-master\src\dropout_layer_kernels.cu	245	
警告		variable "block_prob" was declared but never referenced	darknet	D:\darknet-master\src\dropout_layer_kernels.cu	262	
错误		calling a __host__ function("__floorf") from a __global__ function("smooth_rotate_weights_kernel") is not allowed	darknet	D:\darknet-master\src\blas_kernels.cu	1761	
错误		identifier "__floorf" is undefined in device code	darknet	D:\darknet-master\src\blas_kernels.cu	1761	
错误		calling a __host__ function("__ceilf") from a __global__ function("smooth_rotate_weights_kernel") is not allowed	darknet	D:\darknet-master\src\blas_kernels.cu	1762	
错误		identifier "__ceilf" is undefined in device code	darknet	D:\darknet-master\src\blas_kernels.cu	1762	
错误		calling a __host__ function("__floorf") from a __global__ function("smooth_rotate_weights_kernel") is not allowed	darknet	D:\darknet-master\src\blas_kernels.cu	1764	
错误		identifier "__floorf" is undefined in device code	darknet	D:\darknet-master\src\blas_kernels.cu	1764	
错误		calling a __host__ function("__ceilf") from a __global__ function("smooth_rotate_weights_kernel") is not allowed	darknet	D:\darknet-master\src\blas_kernels.cu	1765	
错误		identifier "__ceilf" is undefined in device code	darknet	D:\darknet-master\src\blas_kernels.cu	1765	
错误		calling a __host__ function("__floorf") from a __global__ function("stretch_weights_kernel") is not allowed	darknet	D:\darknet-master\src\blas_kernels.cu	1858	
错误		identifier "__floorf" is undefined in device code	darknet	D:\darknet-master\src\blas_kernels.cu	1858	
错误		calling a __host__ function("__ceilf") from a __global__ function("stretch_weights_kernel") is not allowed	darknet	D:\darknet-master\src\blas_kernels.cu	1859	
错误		identifier "__ceilf" is undefined in device code	darknet	D:\darknet-master\src\blas_kernels.cu	1859	
错误		calling a __host__ function("__floorf") from a __global__ function("stretch_weights_kernel") is not allowed	darknet	D:\darknet-master\src\blas_kernels.cu	1861	
错误		identifier "__floorf" is undefined in device code	darknet	D:\darknet-master\src\blas_kernels.cu	1861	
错误		calling a __host__ function("__ceilf") from a __global__ function("stretch_weights_kernel") is not allowed	darknet	D:\darknet-master\src\blas_kernels.cu	1862	
错误		identifier "__ceilf" is undefined in device code	darknet	D:\darknet-master\src\blas_kernels.cu	1862	
错误		calling a __host__ function("__floorf") from a __global__ function("sway_and_flip_weights_kernel") is not allowed	darknet	D:\darknet-master\src\blas_kernels.cu	1956	
错误		identifier "__floorf" is undefined in device code	darknet	D:\darknet-master\src\blas_kernels.cu	1956	
错误		calling a __host__ function("__ceilf") from a __global__ function("sway_and_flip_weights_kernel") is not allowed	darknet	D:\darknet-master\src\blas_kernels.cu	1957	
错误		identifier "__ceilf" is undefined in device code	darknet	D:\darknet-master\src\blas_kernels.cu	1957	
错误		calling a __host__ function("__floorf") from a __global__ function("sway_and_flip_weights_kernel") is not allowed	darknet	D:\darknet-master\src\blas_kernels.cu	1959	
错误		identifier "__floorf" is undefined in device code	darknet	D:\darknet-master\src\blas_kernels.cu	1959	
错误		calling a __host__ function("__ceilf") from a __global__ function("sway_and_flip_weights_kernel") is not allowed	darknet	D:\darknet-master\src\blas_kernels.cu	1960	
错误		identifier "__ceilf" is undefined in device code	darknet	D:\darknet-master\src\blas_kernels.cu	1960	
错误		calling a __host__ function("__floorf") from a __global__ function("stretch_sway_flip_weights_kernel") is not allowed	darknet	D:\darknet-master\src\blas_kernels.cu	2147	
错误		identifier "__floorf" is undefined in device code	darknet	D:\darknet-master\src\blas_kernels.cu	2147	
错误		calling a __host__ function("__ceilf") from a __global__ function("stretch_sway_flip_weights_kernel") is not allowed	darknet	D:\darknet-master\src\blas_kernels.cu	2148	
错误		identifier "__ceilf" is undefined in device code	darknet	D:\darknet-master\src\blas_kernels.cu	2148	
错误		calling a __host__ function("__floorf") from a __global__ function("stretch_sway_flip_weights_kernel") is not allowed	darknet	D:\darknet-master\src\blas_kernels.cu	2150	
错误		identifier "__floorf" is undefined in device code	darknet	D:\darknet-master\src\blas_kernels.cu	2150	
错误		calling a __host__ function("__ceilf") from a __global__ function("stretch_sway_flip_weights_kernel") is not allowed	darknet	D:\darknet-master\src\blas_kernels.cu	2151	
错误		identifier "__ceilf" is undefined in device code	darknet	D:\darknet-master\src\blas_kernels.cu	2151	
错误		calling a __host__ function("__floorf") from a __global__ function("stretch_sway_flip_weights_kernel") is not allowed	darknet	D:\darknet-master\src\blas_kernels.cu	2206	
错误		identifier "__floorf" is undefined in device code	darknet	D:\darknet-master\src\blas_kernels.cu	2206	
错误		calling a __host__ function("__ceilf") from a __global__ function("stretch_sway_flip_weights_kernel") is not allowed	darknet	D:\darknet-master\src\blas_kernels.cu	2207	
错误		identifier "__ceilf" is undefined in device code	darknet	D:\darknet-master\src\blas_kernels.cu	2207	
错误		calling a __host__ function("__floorf") from a __global__ function("stretch_sway_flip_weights_kernel") is not allowed	darknet	D:\darknet-master\src\blas_kernels.cu	2209	
错误		identifier "__floorf" is undefined in device code	darknet	D:\darknet-master\src\blas_kernels.cu	2209	
错误		calling a __host__ function("__ceilf") from a __global__ function("stretch_sway_flip_weights_kernel") is not allowed	darknet	D:\darknet-master\src\blas_kernels.cu	2210	
错误		identifier "__ceilf" is undefined in device code	darknet	D:\darknet-master\src\blas_kernels.cu	2210	
错误	MSB3721	命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe" -gencode=arch=compute_35,code=\"sm_35,compute_35\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64" -x cu  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -ID:\opencv344\build\include -I\include -IC:\opencv_3.0\opencv\build\include -I..\..\include -I..\..\3rdparty\stb\include -I..\..\3rdparty\pthreads\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -I\include -I\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static     -DOPENCV -DCUDNN_HALF -DCUDNN -D_TIMESPEC_DEFINED -D_SCL_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -D_CRT_RAND_S -DGPU -DWIN32 -D_CONSOLE -D_LIB -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdx64\Release\vc142.pdb /FS /Zi  /MD " -o x64\Release\activation_kernels.cu.obj "D:\darknet-master\src\activation_kernels.cu"”已退出，返回代码为 1。	darknet	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 10.2.targets	764	
错误	MSB3721	命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe" -gencode=arch=compute_35,code=\"sm_35,compute_35\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64" -x cu  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -ID:\opencv344\build\include -I\include -IC:\opencv_3.0\opencv\build\include -I..\..\include -I..\..\3rdparty\stb\include -I..\..\3rdparty\pthreads\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -I\include -I\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static     -DOPENCV -DCUDNN_HALF -DCUDNN -D_TIMESPEC_DEFINED -D_SCL_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -D_CRT_RAND_S -DGPU -DWIN32 -D_CONSOLE -D_LIB -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdx64\Release\vc142.pdb /FS /Zi  /MD " -o x64\Release\blas_kernels.cu.obj "D:\darknet-master\src\blas_kernels.cu"”已退出，返回代码为 1。	darknet	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 10.2.targets	764

**Comment by stephanecharette** [comment]
Did you try and search for this error? https://github.com/AlexeyAB/darknet/issues?q=calling+a+host+function

**Comment by futureflsl** [comment]
thanks,I got it
