### ISSUE TITLE
Exception when using webcam

### ISSUE THREAD

**Issue by Rufus1123** [AlexeyAB/darknet#751]
I am trying to use YOLO with the webcam using
`darknet.exe detector demo data/coco.data yolov3.cfg yolov3.weights` 

However within about a minute the program crashes. Running from visual studio I found that the following exception is thrown:
![image](https://user-images.githubusercontent.com/32542901/39632574-bf3dfb18-4fb5-11e8-9847-6b4b6a18cc15.png)

The exception is thrown at this line:
`cvResize(src, new_img, CV_INTER_LINEAR);`
darknet\src\image.c line:917

I have managed to get it working by streaming my webcam to localhost and then capturing from localhost, but I would like to get it working from the webcam directly. Also capturing from video files works just fine.

I have built darknet using VS15 for x64 in release mode. (Somehow debug mode doesn't even build)
OS is Windows 10 and I use CUDA 9.1, CUDnn and opencv 3.4.0.

Any ideas why this happens and how to resolve it?

**Comment by AlexeyAB** [comment]
@Rufus1123 Hi,

I fixed this issue. 

Tested on Windows 7 x64:
* video-file, web-cam, ip-cam
* OpenCV 2.4.13 and OpenCV 3.4.0

**Comment by Rufus1123** [comment]
Is there also a way to configure what resolution / fps the Webcam input stream should use? (By default my webcam uses a 4:3 format even though it should support full 1080p)

**Comment by AlexeyAB** [comment]
Uncomment these lines: https://github.com/AlexeyAB/darknet/blob/812d143ebd8e308b3908d66ced8cb9608c88461f/src/http_stream.cpp#L221-L222

And set your resolution.

----

OpenCV sometimes requires 2x more resolution than you want, some OpenCV-bugs.
