### ISSUE TITLE
(-215:Assertion failed) classes > 0 && num_of_anchors > 0 && (num_of_anchors * 2) == anchors_vec.size() in function 'ReadDarknetFromCfgStream'

### ISSUE THREAD

**Issue by SyedSaifAliAlvi** [AlexeyAB/darknet#7523]
I am training my network on 1 class, using yolov4-tiny network. 
While testing the network using saved weights, I am getting this error:

![Screenshot from 2021-03-21 00-08-37](https://user-images.githubusercontent.com/43503954/111882104-b86d2000-89d9-11eb-8f49-7fcccf5df024.png)

The configuration file - 
[yolov4-tiny.zip](https://github.com/AlexeyAB/darknet/files/6176189/yolov4-tiny.zip)

I have only changed the number of batches, subdivision, classes, nums and filters in the config file.
Is there any way to resolve this issue ? and What is the reason behind this issue ?

**Comment by stephanecharette** [comment]
Make sure you've edited the .cfg file correctly.  This assert is telling you that some of the values don't match what was expected.  Compare your .cfg file against the template you used to ensure you didn't accidentally edit something, and read through the instructions in the readme to see which values you must fix (various instances of filters, classes, etc).

There are also tools like DarkMark on Ubuntu that automatically sets up all of the files for Darknet so you can avoid these problems.  For example:  https://www.youtube.com/watch?v=pJ2iyf_E9PM

**Comment by SyedSaifAliAlvi** [comment]
> Make sure you've edited the .cfg file correctly. This assert is telling you that some of the values don't match what was expected. Compare your .cfg file against the template you used to ensure you didn't accidentally edit something, and read through the instructions in the readme to see which values you must fix (various instances of filters, classes, etc).
> 
> There are also tools like DarkMark on Ubuntu that automatically sets up all of the files for Darknet so you can avoid these problems. For example: https://www.youtube.com/watch?v=pJ2iyf_E9PM

Thank you for your response, I have fixed that issue and now it is working, the problem was with the number of anchors,

Nums *2  = Number of Anchors, I changed that and now It's working.

**Comment by stephanecharette** [comment]
> Thank you for your response, I have fixed that issue and now it is working, the problem was with the number of anchors,

You changed the anchors?  Note your message:

> > I have only changed the number of batches, subdivision, classes, nums and filters in the config file.

Also note Alexey's message on changing anchors in the readme.

**Comment by SyedSaifAliAlvi** [comment]
> > Thank you for your response, I have fixed that issue and now it is working, the problem was with the number of anchors,
> 
> You changed the anchors? Note your message:
> 
> > > I have only changed the number of batches, subdivision, classes, nums and filters in the config file.
> 
> Also note Alexey's message on changing anchors in the readme.

Previously my anchors were not changed, When I have written this  : 
>>I have only changed the number of batches, subdivision, classes, nums and filters in the config file.

Later I changed my anchors according to the formula, while debugging.
>I have fixed that issue and now it is working, the problem was with the number of anchors
<br>
Yes I have read that, but thank you for mentioning it.

>Also note Alexey's message on changing anchors in the readme.
