### ISSUE TITLE
What is the arguments of load_image in darknet.py

### ISSUE THREAD

**Issue by zhaoguanao** [AlexeyAB/darknet#7524]
I've tried to detect image by using darknet.py like this
![18](https://user-images.githubusercontent.com/47096417/111892600-e719e380-8a37-11eb-8019-c4bfb01b2693.jpg)
but the third argument is in a wrong type
![QQ截图20210321111909](https://user-images.githubusercontent.com/47096417/111892617-fdc03a80-8a37-11eb-9025-ab7fa768d3e3.jpg)
it says "expected IMAGE instance instead of bytes", can anybody tell me how to input my image as a IMAGE instance object? or just tell me how to detect image by using darknet.py, THX

**Comment by solder-fumes-asthma** [comment]
Hey! I am struggling to load images with the python bindings on darknet.py. Did you find a solution for you issue?
