### ISSUE TITLE
How can I edit or remove the bounding box labels?

### ISSUE THREAD

**Issue by varungupta31** [AlexeyAB/darknet#7538]
@AlexeyAB 
**I wish to display only the probability of detection over the bounding box, not the label.**
I tried editing the `'image.c'` file in `darknet/src` and re-making the darknet (`!make`), **but it still shows the class label over the bounding box.**

**The edits I made were:**
In image.c file, line 511 ->
`printf("%s: %.0f%%", names[class_id], prob * 100);`  **to** `printf("%s: %.0f%%", " ", prob * 100);`
In line 519 ->
`image label = get_label(alphabet, names[class_id], (im.h*.03)/10);` **to** `image label = get_label(alphabet, " ", (im.h*.03)/10);`

How shall I do this?
(I'm a beginner with this, apologies if these edits seems naive.)

Thank you.

**Comment by lsd1994** [comment]
delete this
https://github.com/AlexeyAB/darknet/blob/1e3a616ed6cefc517db6c8c106c83de24fad275c/src/image.c#L441-L446

**Comment by varungupta31** [comment]
I updated the file with the suggested edits, rebuilt the darknet (!make) but the **labels are still present** (no change)

**Comment by lsd1994** [comment]
Oh I forgot this
https://github.com/AlexeyAB/darknet/blob/1e3a616ed6cefc517db6c8c106c83de24fad275c/src/image.c#L436
delete it and have another try.

**Comment by varungupta31** [comment]
Perfect!
Thanks to @lsd1994 the way to remove class labels and display only the detection probability score is to :

1. Locate the file `darknet/src/image.c`
2. **Delete line of code at 436** - `strcat(labelstr, names[selected_detections[i].best_class]); ` **and from 441 to 446** 
 ```
   for (j = 0; j < classes; ++j) { 
     if (selected_detections[i].det.prob[j] > thresh && j != selected_detections[i].best_class) { 
         strcat(labelstr, ", "); 
         strcat(labelstr, names[j]); 
     } 
 } 
```
3. Don't clone the repository again and make to sure to build the darknet (`!make`) in the project after these updates.
