### ISSUE TITLE
Getting AP metrics from darknet (AP@0.50:0.95 & more) 

### ISSUE THREAD

**Issue by solder-fumes-asthma** [AlexeyAB/darknet#7542]
Hello, I am trying to obtain a kind-of-normalized AP table for an academic project I'm doing in which I am training various object detectors, something similar to the following table (which was produced with [efficientDet](https://github.com/google/automl/tree/master/efficientdet)) with darknet:

```
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.304
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.512
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.350
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.050
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.270
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.392
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.005
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.050
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.354
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.054
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.315
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.449
```

Besides the Dets thing I believe this type of AP table is pretty standard, please correct me if I'm wrong.  Would someone please be able to show me how to export a reasonably similar thing with darknet? And if the former is not possible, can an AP@0.50:0.95 be exported? Thanks a bunch!

For now I've tried using derivations of the following without success:
`./darknet detector map   *args   -points 101 -iou_thresh 0.50:0.95`

**Comment by solder-fumes-asthma** [comment]
Just by chance I found [this page](https://gitmemory.com/issue/AlexeyAB/darknet/2746/477459452). That table can be obtained with the commands shown in there.

**Comment by pabsan-0** [comment]
Hey @aniket611 I believe the link pointed to [this issue](https://github.com/AlexeyAB/darknet/issues/2746). However, if you're literally after the table shown above you're better off reformatting your results according to the [MS COCO standards](https://cocodataset.org/#format-data) and then using the official [pycocotools](https://github.com/cocodataset/cocoapi/tree/master/PythonAPI/pycocotools). I honestly do not know if it is possible to get the table straight out of darknet, but that was the path I finally took a year ago.
