### ISSUE TITLE
darknet build error MSB3721 (VS2015)

### ISSUE THREAD

**Issue by Unice-CS** [AlexeyAB/darknet#7545]
My environment:Windows 10 + CUDA 10.0.130 + cudnn 7.6.5 + Opencv 3.4.0 + Visual Studio 2015+ GPU: RTX 2070
When I tried to compile yolov4 in legacy way, I encountered the problem shown in the sceenshot below.

![error1](https://user-images.githubusercontent.com/74975816/112626812-b12b9380-8e6b-11eb-8d04-2dceeaddef15.PNG)
![error2](https://user-images.githubusercontent.com/74975816/112626817-b38ded80-8e6b-11eb-87a0-279c155a0fd8.png)

And here are my Visual Studio configurations down below.

![yolo4](https://user-images.githubusercontent.com/74975816/112626862-c43e6380-8e6b-11eb-89b6-5a10f432b7da.png)
![yolo4_2](https://user-images.githubusercontent.com/74975816/112626868-c86a8100-8e6b-11eb-93db-a69ca4c93e79.png)
![yolo4_3](https://user-images.githubusercontent.com/74975816/112626880-cb657180-8e6b-11eb-818b-55879e419d4b.png)
![yolo4_4](https://user-images.githubusercontent.com/74975816/112626884-cd2f3500-8e6b-11eb-9d59-791ed1449da4.png)

I've tried to delete "compute_75,sm_75" or change it to different figures, however it's still not working...
Please help me figure it out! Thanks a lot!

**Comment by stephanecharette** [comment]
You didn't show us the error, you only showed us that the build command failed.  But I can guess at the error.  CUDA 10.0 is no longer supported.  Darknet requires 10.1 or higher.  See this post for details: https://github.com/AlexeyAB/darknet/issues/7486#issuecomment-794073736

**Comment by Unice-CS** [comment]
> You didn't show us the error, you only showed us that the build command failed. But I can guess at the error. CUDA 10.0 is no longer supported. Darknet requires 10.2 or higher. See this post for details: [#7486 (comment)](https://github.com/AlexeyAB/darknet/issues/7486#issuecomment-794073736)

Thanks a million, that helps a lot!!!
I change it to CUDA 11.2.2 + Visual Studio 2017, and that works!
