### ISSUE TITLE
can't detect image when use GPU

### ISSUE THREAD

**Issue by Diagru25** [AlexeyAB/darknet#7563]
Hello everyone, I have a problem:
**I change makefile:**
GPU = 1
...
OPENCV=1

but when I run in google colab I don't get result.

**my command:**
`!./darknet detect cfg/yolov3.cfg yolov3.weights data/dog.jpg`

**this's my result:**
[yolo] params: iou loss: mse (2), iou_norm: 0.75, obj_norm: 1.00, cls_norm: 1.00, delta_norm: 1.00, scale_x_y: 1.00
Total BFLOPS 65.879 
avg_outputs = 532444 
 Allocate additional workspace_size = 49.84 MB 
Loading weights from yolov3.weights...
 seen 64, trained: 32013 K-images (500 Kilo-batches_64) 
Done! Loaded 107 layers from weights-file 
 Detection layer: 82 - type = 28 
 Detection layer: 94 - type = 28 
 Detection layer: 106 - type = 28 
data/dog.jpg: Predicted in 533.459000 milli-seconds.
Unable to init server: Could not connect: Connection refused

(predictions:3184): Gtk-WARNING **: 03:55:08.967: cannot open display:

How can I fix it ?

**Comment by stephanecharette** [comment]
> Unable to init server: Could not connect: Connection refused
> (predictions:3184): Gtk-WARNING **: 03:55:08.967: cannot open display:

Do you have a server with X-Windows installed?  Did you remember to `ssh -X`?  If not, the remember to darknet with `-dont_show` so it darknet knows to skip opening X-Windows.

**Comment by Diagru25** [comment]
> > Unable to init server: Could not connect: Connection refused
> > (predictions:3184): Gtk-WARNING **: 03:55:08.967: cannot open display:
> 
> Do you have a server with X-Windows installed? Did you remember to `ssh -X`? If not, then remember to run darknet with `-dont_show` so it knows to skip opening X-Windows.

I use ubuntu on google colab. with gpu = 0 and opencv = 0 I detect normaly. but when i change gpu = 1, oprncv = 1. It not working ?. Can u explain it ?

**Comment by stephanecharette** [comment]
> > > Unable to init server: Could not connect: Connection refused
> > > (predictions:3184): Gtk-WARNING **: 03:55:08.967: cannot open display:

> > Do you have a server with X-Windows installed? Did you remember to `ssh -X`? If not, then remember to run darknet with `-dont_show` so it knows to skip opening X-Windows.

> Can u explain it ?

I already did.  If you're not on a local machine, and you're not using `ssh -X`, then add `-dont_show` parameter to darknet so it doesn't try to open a X-Windows dialog window.  When using OpenCV, Darknet will attempt to use HighGUI to create a X-Windows dialog window in which it displays the results.

**Comment by Diagru25** [comment]
I fixed it. thank you @stephanecharette
