### ISSUE TITLE
train for certain classes

### ISSUE THREAD

**Issue by Sennevds** [AlexeyAB/darknet#758]
Hi i've downloaded the coco dataset and now I want to train for only 6 classes.
(person,bicycle,car,motorbike,bus,truck) Is there an easy way so that when I create a new weights file it only recognizes these classes?

**Comment by Sennevds** [comment]
So i've downloaded the coco dataset. To remove certain classes I just remove the lines in labels/train2014/*txt files that I don't want to train or do I need to edit the 9k.tree and coco9k.map?

**Comment by Sennevds** [comment]
Owkey thanks.
I've made following script to do so:
`import glob, os
allowedClasses = ['person', 'bicycle', 'car','motorbike','bus','train','truck']
classes = []
newContent = []
with open('coco.names') as names:
    classes = names.readlines()
os.chdir("labels/train2014")
for file in glob.glob("*.txt"):
    with open(file, "r+") as f:
        content = f.readlines()
        f.seek(0)
        f.truncate()
        content = [x.strip() for x in content]
        for line in content:
            splittedString = line.split()
            currentClass = classes[int(splittedString[0])].strip()
            if currentClass in allowedClasses:
                if(int(splittedString[0]) > 3):
                    splittedString[0] = str(int(splittedString[0]) - 1)
                newContent.append(' '.join(splittedString))
        f.write('\n'.join(newContent))
`
So I think this should work. One question though if we train with the Voc dataset the txt files need to be in the same directory as the images. If I read right this is not necessary for Coco database but can't find the place in the code where it searches for the labels where is this done?

**Comment by akashAD98** [comment]
> Owkey thanks. I've made following script to do so:
> 
> ```python
> import glob, os
> allowedClasses = ['person', 'bicycle', 'car','motorbike','bus','train','truck']
> classes = []
> newContent = []
> with open('coco.names') as names:
>     classes = names.readlines()
> os.chdir("labels/train2014")
> for file in glob.glob("*.txt"):
>     with open(file, "r+") as f:
>         content = f.readlines()
>         f.seek(0)
>         f.truncate()
>         content = [x.strip() for x in content]
>         for line in content:
>             splittedString = line.split()
>             currentClass = classes[int(splittedString[0])].strip()
>             if currentClass in allowedClasses:
>                 if(int(splittedString[0]) > 3):
>                     splittedString[0] = str(int(splittedString[0]) - 1)
>                 newContent.append(' '.join(splittedString))
>         f.write('\n'.join(newContent))
> ```
> 
> So I think this should work. One question though if we train with the Voc dataset the txt files need to be in the same directory as the images. If I read right this is not necessary for Coco database but can't find the place in the code where it searches for the labels where is this done?

its python script right? how should i add this to C language in darknet?
I have 40 classes & its label so i want to do it for only few classes ,lets say 20. & i dont want to remove any other classes.
