### ISSUE TITLE
Darknet installation on Windows10 with RTX 3090 - CUDA 11.2 and cudNN 8 

### ISSUE THREAD

**Issue by MiguelEsteve** [AlexeyAB/darknet#7599]
I set an issue with the instalation of Darknet on Windows 10, using RTX 3090, and configuration as follow:
 
1.- Installed CUDA 11.2 and dudNN 8.1.1, according the next binaries:

>         cuda_11.2.2_461.33_win10
>         cudnn-11.2-windows-x64-v8.1.1.33
>             I unzip the bin/include/lib files in c:/cuda folder, and copy to CUDA
>                      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\...... 
>                       corresponding paths.

 2.- Installed opencv-4.5.1-vc14_vc15, in the folder C:/opencv
 3.- Set the proper enviroment variables

>         OpenCV_DIR = C:\opencv\build\x64\vc15\bin
>         CUDA_PATH = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2

        I also added to system path:
      

>             C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin
>             C:\cuda\bin

4.- I cloned the vcpkg repo and follow next commands:

>     PS Code\>              git clone https://github.com/microsoft/vcpkg
>     PS Code\>              cd vcpkg
>     PS Code\vcpkg>      $env:VCPKG_ROOT=$PWD
>     PS Code\vcpkg>      .\bootstrap-vcpkg.bat 
>     PS Code\vcpkg>      .\vcpkg install darknet[opencv-base,cuda,cudnn]:x64-windows 

 #replace "full" with "opencv-base,cuda,cudnn"
    PS Code\vcpkg>         cd ..

 7.-   On darknet, then I cloned the repo

>     PS Code\>              git clone https://github.com/AlexeyAB/darknet
>     PS Code\>              cd darknet

  8.-  Before executing build, I edit "makefile" and enable CUDA, cuDNN and change architecture:

>     GPU=1
>     CUDNN=1
>     OPENCV=1
>     # ARCH= -gencode arch=compute_35,code=sm_35 \
>     #       -gencode arch=compute_50,code=[sm_50,compute_50] \
>     #       -gencode arch=compute_52,code=[sm_52,compute_52] \
>     # 	    -gencode arch=compute_61,code=[sm_61,compute_61]
> 
>     ARCH= -gencode arch=compute_86,code=[sm_86,compute_86]

9.-    Then build darknet:

>     PS code\darknet> .\build.ps1

10.- All the steps run well, and then I execute the next to test the installation

> ./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg

I get the next output. Darknet hangs for about 30 minutes and at the end prints the image with no prediction at all.
![imagen](https://user-images.githubusercontent.com/5907561/114442173-8f9d0c80-9bcc-11eb-99d5-a980a1d03b15.png)

I have spent more than 40 hours at this facility and it is being an absolute nightmare. 
The Alexey github instructions to install Darknet in windows are a bug as a whole.
Any professional help I will really appreciate!

**Comment by Goru1890** [comment]
Press enter if you think it's stucked.

**Comment by MiguelEsteve** [comment]
Well, finally i got it running in my system:

- Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz   3.70 GHz
- 128 GB
- 3 x RTX 3090
- Windows 10 Pro build 19042.867

Whenever I utilized vcpkg, the build failed. Finally I decided to install all dependencies separatelly out of vcpkg as follows:

1.- Uninstall Visual Studio 17 and any other versions you may have of visual studio.
2.- Uninstall CUDA 11.2
3.- Delete all enviroment variables and references in path to Visual Studio and CUDA.
4.- Restart system
5.- Install Visual Studio 17
6.- Install CUDA 11.2 (cuda_11.2.2_461.33_win10)
 - Check env variabes:
     CUDA_PATH = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
     CUDA_PATH_V11_2 = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
     NVCUDASAMPLES_ROOT= C:\ProgramData\NVIDIA Corporation\CUDA Samples\v11.2
     NVCUDASAMPLES11_2_ROOT = C:\ProgramData\NVIDIA Corporation\CUDA Samples\v11.2
     NVTOOLSEXT_PATH = C:\Program Files\NVIDIA Corporation\NvToolsExt\
7,. Install cudNN 8 (cudnn-11.2-windows-x64-v8.1.1.33): take the file, uncompress and save it in C:/CUDA
8.-Download opencv instalator from opencv web: https://opencv.org/releases/
    opencv-4.5.2-vc14_vc15.exe
9.- Execute "opencv-4.5.2-vc14_vc15.exe" and save it on C:\
10.- By selecting C:\, the installer will create folder C:\opencv.   In my case, It was mandated to utilize this directory for opencv, otherwise darknet compilation later will not detect opencv out of vcpkg.
11.- Create var environment OpenCV_DIR = C:\opencv\build\x64\vc15\bin
12.- Remove vcpkg enviroment variables (VCPKG_ROOT, VCPKG_DEFAULT_TRIPLET). If those two enviroment variables are not removed, then when executing >C:\code\darknet\ .\build.ps1, Darknet will consider vcpkg as installed and will try on its location to load the dependecies, failing the buiild.
12.- in C:/Code, git clone Darkney
        git clone https://github.com/AlexeyAB/darknet
14.- cd /Darknet, edit makefile, set vars
       GPU = 1
       CUDNN = 1
       CUDNN_HALF = 0
       opencv=1
      #ARCH= -gencode arch=compute_35,code=sm_35 \
      # -gencode arch=compute_50,code=[sm_50,compute_50] \
      # -gencode arch=compute_52,code=[sm_52,compute_52] \
      # -gencode arch=compute_61,code=[sm_61,compute_61]
       ARCH = -gencode arch=compute_86,code=[sm_86,compute_86]

15.- .\build.ps1
The build is complete with no vcpkg. The folder created is C:/code/darknet/build_with_release_novcpkg
16.- download "yolov3.weights" and copy to C:/code/darknet
17. Test the instalation by running: ./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg
As a result, the network will be loaded immediatelly (no hang at all), and immediatelly the picture dog.jpg will be displayed with the inferred bounding boxes.

Good luck !

**Comment by stephanecharette** [comment]
Thank you for the writeup.

**Comment by bulatnv** [comment]
Thank you @MiguelEsteve.
Installed darknet by this guide. It worked.

**Comment by cenit** [comment]
> Well, finally i got it running in my system:
> 
> * Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz
> * 128 GB
> * 3 x RTX 3090
> * Windows 10 Pro build 19042.867
> 
> When using vcpkg to install opencv[cuda, cudnn, ffmpeg], vcpkg does not detect the alrealy installed CUDA 11.2 and cudnn 8 and then vcpkg installs and compile dependencies with somehow a "default" cuda 10.1 and cudnn 7.6.5. Vcpkg seems not to detect the required cuda versión according graphic card installed. Darknet builds but when executed gets hanged for many time before loading the model. Once model is loaded, then does not infers any bounding box on the test picture provided. When executed for training, besides the hang to load model, it fails with NaN losses in all cases.
> 
> When I decide to utilize vcpkg just for opencv[ffmpeg] (with no cuda, cudnn), in order to hold my CUDA 11.2 and cudnn 8 instalation out of vcpkg, then the vcpkg build fails at the point to install tiny-dnn for opencv.
> 
> Finally I decided to install all dependencies separatelly out of vcpkg. Note that the instalation I describe below does not rely on vcpgk, so vcpgk must be totally unistalled. The sequence of steps I followed are required:
> 
> 1.- Uninstall Visual Studio 17 and/or any other versions you may have of visual studio.
> 
> 2.- Uninstall CUDA installed whatever was the version.
> 
> 3.- Delete all enviroment variables and references in path to Visual Studio and CUDA.
> 
> 4.- Restart system
> 
> 5.- Install CMAKE in c:/Program Files/CMake
> 
> 6.- Install NINJA on the folder c:/Program Files/CMake/bin
> 
> 7.- Add to the system enviroment path C:\Program Files\CMake\bin
> 
> 8.- Install Visual Studio 17
> 
> 9.- Install CUDA 11.2 (cuda_11.2.2_461.33_win10)
> Check system enviroment variables:
> 
> ```
>  - CUDA_PATH = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
>  - CUDA_PATH_V11_2 = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
>  - NVCUDASAMPLES_ROOT= C:\ProgramData\NVIDIA Corporation\CUDA Samples\v11.2
>  - NVCUDASAMPLES11_2_ROOT = C:\ProgramData\NVIDIA Corporation\CUDA Samples\v11.2
>  - NVTOOLSEXT_PATH = C:\Program Files\NVIDIA Corporation\NvToolsExt\
> ```
> 
> 10,. Install cudNN 8 (cudnn-11.2-windows-x64-v8.1.1.33): take the file, uncompress and save it in C:/CUDA
> C:\cuda\bin
> 
> 11.- Add to the system enviroment path C:\cuda/bin
> 
> 12.-Download opencv instalator from opencv web: https://opencv.org/releases/
> I utilized: opencv-4.5.2-vc14_vc15.exe
> 
> 13.- Execute "opencv-4.5.2-vc14_vc15.exe" and save it on C:\
> 
> 14.- By selecting C:, the installer will create folder C:\opencv. In my case, It was mandated to utilize this directory for opencv, otherwise darknet compilation later will not detect opencv out of vcpkg.
> 
> 15.- Create var environment OpenCV_DIR = C:\opencv\build\x64\vc15\bin
> 
> 16.- Remove vcpkg enviroment variables (VCPKG_ROOT, VCPKG_DEFAULT_TRIPLET). If those two enviroment variables are not removed, then when executing >C:\code\darknet\ .\build.ps1, Darknet will consider vcpkg as installed and will try on vcpkg location to load the dependecies, failing the buiild.
> 
> 17.- in C:/Code, git clone Darknet
> git clone https://github.com/AlexeyAB/darknet
> 
> 18.- cd /Darknet, edit makefile, set the next values to some vars
> 
> ```
>    - GPU = 1
>    - CUDNN = 1
>    - CUDNN_HALF = 0
>    - OPENCV=1
>    Comment the next lines
>    ARCH= -gencode arch=compute_35,code=sm_35 \                      -> to be commented
>            -gencode arch=compute_50,code=[sm_50,compute_50] \      -> to be commented
>            -gencode arch=compute_52,code=[sm_52,compute_52] \       -> to be commented
>            -gencode arch=compute_61,code=[sm_61,compute_61]         -> to be commented
>  
>    uncoment the next, as compute_86 is the architecture for RTX3090:
>    - ARCH = -gencode arch=compute_86,code=[sm_86,compute_86]   
> ```
> 
> 19.- .\build.ps1
> The build is complete with no vcpkg. The folder created is C:/code/darknet/build_with_release_novcpkg
> 
> 20.- download "yolov3.weights" and copy to C:/code/darknet
> 
> 1. Test the instalation by running: ./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg
>    As a result, the network will be loaded immediatelly (no hang at all), and the picture dog.jpg will be displayed with the inferred bounding boxes.
> 
> Good luck !

Thanks for your guide on how to build darknet in a "very manual way".

Two things
1) vcpkg does not install cuda, so if you installed CUDA 11.2, vcpkg just detects it or fails if not found. vcpkg cannot install libraries which require system privileges and so cuda is out. For cuDNN the situation is a little bit different but similar, meaning that vcpkg installs it only if not already found on system and is able to install only few versions of it. Recently nvidia changed distribution of it and newer versions cannot be installed by vcpkg, so if you have cuda 11.2 and you lack cuDNN, it just errors out asking you to do it
2) step 18 is fully unnecessary, since you are modifying makefile while in the build.ps1 only cmake is involved

Apart from that: is it working better in the latest release for you?
Please let me know your opinion and any improvement in guidelines and/or scripts you might like

**Comment by patrickhennessy-dal** [comment]
Hi @MiguelEsteve, thank you for the installation instructions!

I'm having an issue getting this to work with OpenCV, though:
![image](https://user-images.githubusercontent.com/80766219/124516903-bbd1bf00-ddb0-11eb-8a8f-a1da4d987dcb.png)

I've installed OpenCV to "C:\" and created the environment variable "OpenCV_DIR = C:\opencv\build\x64\vc15\bin" just like in your instructions.

Disabling OpenCV allows the Darknet installation to complete without any errors, but I'd like to have OpenCV.

Do you have any suggestions?

**Comment by bulatnv** [comment]
> OpenCV_DIR = C:\opencv\build\x64\vc15\bin

Wrong OpenCV_DIR.
OpenCV_DIR = "C:\opencv\build"
cmake is looking for "*.cmake" files in the folder

**Comment by ozxdno** [comment]
emmm. any suggestions for me? plz
win10 rtx3070ti
![image](https://github.com/AlexeyAB/darknet/assets/26242905/25fe889d-d537-4a29-8cc7-0efcc705c6dd)
