### ISSUE TITLE
Frame rate of detector - demo capped at 15fps?

### ISSUE THREAD

**Issue by Timebutt** [AlexeyAB/darknet#76]
Hi @AlexeyAB,

I am using your code as a vital part of my research, big thanks so far as it works wonders! Part of your code had to be modified for my purpose, but the core remains unchanged. I trained my own model, and want to use it in a real-time detection chain that gets an RTMP video feed as source. This works fine, but framerate was capped at around 15fps (it dances around this 15fps mark, sometimes the output shows 17.9fps, sometimes 13.6fps).

At the time, I was using a GTX670 (about 2,50TFLOPS). To get the algorithm running at >24fps, I installed an NVIDIA GTX1080Ti  (about 11TFLOPS, 400% increase!) and hoped to see a massive increase in frame rate (the YOLOv2 page mentions that 67fps should be feasible using a Pascal Titan X, which is comparable to my GPU), but instead got the same 15fps! I went looking through the code, to find out if maybe there is a parameter keeping the frame rate fixed, but couldn't find anything. My GPU is only stressed at about 30% load when I process a video file, so there is a huge performance margin there to be had. My CPU (Intel i7 6700K) can't be the limiting factor at ~25% load either ...

Do you know what may be causing this frame rate cap? Am I looking over something specific to your YOLOv2 implementation? I am currently installing YOLOv2 on a Linux machine to see if I can match the performance the authors report in parallel.

For reference, this is the command I use to start YOLOv2:

`darknet.exe detector demo data/obj.data yolo-obj.cfg yolo-obj_19000.weights testvlucht6.mp4 -i 0 -thresh 0.5`

Thanks!

**Comment by Timebutt** [comment]
A first thing I found out when running YOLOv2 on my Linux machine, is that resizing the output OpenCV window has a major influence of the frame rate. Apparently, if OpenCV needs to upscale the image (which it currently does, see line 160 in _demo.c_):

`cvResizeWindow("Demo", 1352, 1013);`

If I set this to for instance 416x416 (output of the YOLOv2 network) I get a drastically improved frame rate. Omitting the visualization entirely finally delivers the frame rate I expect my new GPU to deliver (around 40fps right now). I will be looking into this further, to see what impacts the frame rate.

I guess this is not really a bug report per se. Maybe the documentation should include somewhere that the OpenCV visualization has a major impact on the frame rate? I didn't find this thought on the official YOLOv2 page either.

**Comment by AlexeyAB** [comment]
@Timebutt Hi,

* Yes, you can set low fixed size of the displayed image `cvResizeWindow("Demo", 416, 416);`: https://github.com/AlexeyAB/darknet/blob/master/src/demo.c#L160

* Also to avoid spent time to save output video-file you can comment this line `cvWriteFrame(output_video, disp);` https://github.com/AlexeyAB/darknet/blob/master/src/image.c#L458

* And also you can change this line from `if (c == 10){` to `if (c == 9){` and by presss "Tab"-button you will can switch frame skipping: https://github.com/AlexeyAB/darknet/blob/master/src/demo.c#L174
    (But you should know, that FPS is not calculated very accurately, because you see an instant FPS for each frame: https://github.com/AlexeyAB/darknet/blob/master/src/demo.c#L212
    So now you see FPS of the slowest frame. It would be more accurate to calculate its average value in 1 second or in a few seconds.)

----

I just launched the detection on video-file 1280x720 with this line `cvResizeWindow("Demo", 1352, 1013);`,  by using `darknet.exe detector demo data/voc.data yolo-voc.cfg yolo-voc.weights test.mp4 -i 0` and got **32 FPS** on the GeForce GTX 970 (**3.5 Tflops**). 

![image](https://cloud.githubusercontent.com/assets/4096485/25806562/4a4bffa0-340c-11e7-8242-9740efe0d2c9.png)

Usually, the FPS limitation may occur due to the HTTP-mpeg-stream or RTMP/RTSP protocol (slow network, packet loss, uneven packet arrival.). But as I see you test on `testvlucht6.mp4` video file and get only 15 FPS. 

* Do you use cuDNN v5.1, OpenCV 2.4.9, MSVS 2015 and CUDA 8.0?
* What network resolution do you use?
* So how did you measure FPS? 
* And what FPS can you get by using default voc-model? `darknet.exe detector demo data/voc.data yolo-voc.cfg yolo-voc.weights test.mp4 -i 0`
* Also try to compile without cuDNN and test FPS again.
    Open \darknet.sln -> (right click on project) -> properties -> C/C++ -> Preprocessor -> Preprocessor Definitions, and remove at the beginning of line: CUDNN;

**Comment by zenvendof** [comment]
@Timebutt I had similar FPS issue running on a GTX 1080 the frame rate wasn't high at all.  If you are generating a Debug exe file, everything slows down, the 1080 was at 49% utilisation, switching over to Release and CUDNN will give you close to Yolo homepage FPS results, it's very fast :-).  Now to think that I wasted 5 days to train my VOC data for 41000 epochs....:-P....

**Comment by Timebutt** [comment]
Hi @AlexeyAB,

thank you for your very complete answer!
In reply:

- On closer investigation: I found that resizing the output window didn't affect performance on my Windows machine very much, the difference was maybe 4 or 5fps. The impact on my Linux machine was huge however (20fps dropped to 4fps when viewing the video at full size). That machine has a slower CPU however, maybe upscaling the OpenCV output window is a CPU intensive task and that machine is bottlenecked by resizing.

- I uncommented the output line as you described, which made a big performance difference.

- I will try the frame skipping option today, not sure if this is something I can use as dropping frames is a no go in my application. I know that the way FPS is calculated right now is rather inaccurate, will focus on implementing a solution that determines the frame rate in a more robust way (over longer period of time).

- Meanwhile, I have installed CUDNN on my machine and compile my project using the added definition in the preprocessor. I currently use CUDA 8.0, CUDNN 5.1, OpenCV 2.4.9 and MSVS 2015 as you stated. The network resolution is at the default 416x416 (batch 128, subdivision 8, but these only affect training, correct?), as I found the false positive detection to increase massively if I increased the network resolution. FPS were measured/estimated rather inaccurately using terminal output.

- I tested the standard voc-model using a different video and got HUGE frame rates. Apparently the resolution of the input video makes a huge difference, inputting a 1920x1080 video gets me about 22fps, 1200x566 gets me 66fps! Transcoding my video feed to a slightly lower resolution using an RTMP server may hugely benefit my framerate, without compromising my detection accuracy (as YOLOv2 will resize to 416x416 anyway, correct?)

- @zenvendof, thanks for the hint, but I am already building a release x64 version so that can't be it ;)

- Compiling with or without CUDNN didn't make any difference at all, so I'll leave that out of the equation.

Guess this issue is resolved, all in all. Had to do some research to find out what the different impact factors on YOLOv2 performance are. Maybe I should write all of this together in some kind of overview article?

**Comment by AlexeyAB** [comment]
@Timebutt Hi,

> (batch 128, subdivision 8, but these only affect training, correct?

> as YOLOv2 will resize to 416x416 anyway, correct?

Yes

Also cuDNN accelerates ~1.5x times training, but can decrease detection FPS on old GPUs (Kepler, Fermi): https://github.com/AlexeyAB/darknet/issues/61#issuecomment-293644312

**Comment by Timebutt** [comment]
I will close this, as the excellent tips in this issue fixed my issues.
