### ISSUE TITLE
Mish v.s. ReLU

### ISSUE THREAD

**Issue by Unice-CS** [AlexeyAB/darknet#7614]
I'm wondering in what circumstances will the Mish activation function be significantly better than the ReLU function?

I've made my own dataset and trained it with YOLOv4  and I also trained it with YOLOv4 which I changed the Mish function to ReLU function.

However, mAP of the original YOLOv4 is 89.1474% , as for the modified YOLOv4 is 90.4668%.

Please help me figure it out! Thanks a lot!

**Comment by lsd1994** [comment]
It's normal, it's hard to say which activation function is better.

**Comment by Unice-CS** [comment]
> It's normal, it's hard to say which activation function is better.

I think there must be some specific situation that ReLU performs better than Mish, I'm still trying to figure it out.

**Comment by Unice-CS** [comment]
@AlexeyAB Could you please help me with this question?

**Comment by AlexeyAB** [comment]
@Unice-CS Can you show Loss & mAP chart.png for both trainings?
There can be just fluctuations due to small training and validation datasets.

**Comment by Unice-CS** [comment]
> @Unice-CS Can you show Loss & mAP chart.png for both trainings?
> There can be just fluctuations due to small training and validation datasets.

Sorry, I trained it on a virtual machine and didn't save it. But I think you're right, maybe my datasets are too small. I'll try on bigger datasets and see how it goes! 
Thank you for the reply!
