### ISSUE TITLE
Yolo is super slow in RTX 3060

### ISSUE THREAD

**Issue by vfbsilva** [AlexeyAB/darknet#7618]
Running stays for minutes under this stage before loading the weights. When they are loaded no bounding boxes are shown. I´m compiling with:
   ARCH= -gencode arch=compute_86,code=[sm_86,compute_86] 
Using Nvidia driver: 460.67

```
 $ ./darknet detector demo ./cfg/coco.data ./cfg/yolov3.cfg ./yolov3.weights test50.mp4 -i 0 -thresh 0.25
 CUDA-version: 11020 (11020), cuDNN: 7.6.0, GPU count: 1  
 OpenCV version: 4.5.1
Demo
 0 : compute_capability = 860, cudnn_half = 0, GPU: GeForce RTX 3060 
net.optimized_memory = 0 
mini_batch = 1, batch = 1, time_steps = 1, train = 0 
   layer   filters  size/strd(dil)      input                output
   0 

```

**Comment by Hyvenos** [comment]
Hey,
Few questions:
- Is it still slow when using detector test or detector train command?
- What weights are you trying to load, the official yolov4? Are you using the official cfg file or one of your own?
- Was it working before? If so, did you make any change for this to happen?
- Do you use the latest version of this repo?

Your Cuda version is fine as well as your ARCH and your drivers. What's surprise me the most is your CUDNN version.
In my point of view it may be worth to upgrade it to the 8.1 version of cuDNN (and thus recompile darknet using it), it also may be necessary to recompile opencv as well unfortunatelly...
I can't guarantee it'll solve your issue however.

**Comment by vfbsilva** [comment]
- It was 
- they were
- it was
- I did
- upgrading cudnn did the trick. And yes I had to find a compatible opencv. Thanks a lot!
```
CUDA-version: 11010 (11020), cuDNN: 8.1.0, GPU count: 1  
 OpenCV version: 4.5.1
```
