### ISSUE TITLE
Cannot compile with cuda =1 error: ‘CUDNN_CONVOLUTION_FWD_PREFER_FASTEST’ undeclared

### ISSUE THREAD

**Issue by vfbsilva** [AlexeyAB/darknet#7624]
My compilation fails with:
```
gcc -Iinclude/ -I3rdparty/stb/include -DOPENCV `pkg-config --cflags opencv4 2> /dev/null || pkg-config --cflags opencv` -DGPU -I/usr/local/cuda/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -c ./src/convolutional_layer.c -o obj/convolutional_layer.o
./src/convolutional_layer.c: In function ‘cudnn_convolutional_setup’:
./src/convolutional_layer.c:284:24: error: ‘CUDNN_CONVOLUTION_FWD_PREFER_FASTEST’ undeclared (first use in this function); did you mean ‘CUDNN_CONVOLUTION_BWD_FILTER_ALGO_3’?
  284 |     int forward_algo = CUDNN_CONVOLUTION_FWD_PREFER_FASTEST;
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                        CUDNN_CONVOLUTION_BWD_FILTER_ALGO_3
compilation terminated due to -Wfatal-errors.
make: *** [Makefile:179: obj/convolutional_layer.o] Erro 1
```
@AlexeyAB commented: https://github.com/AlexeyAB/darknet/issues/7205
That I need:

    or CUDA 10.2 and cuDNN v8.0.2 (July 24th, 2020), for CUDA 10.2
    or CUDA 11.1 and cuDNN 8.0.5(for CUDA 11.1) - preferably

I`m running:
CUDA: instalado: 11.1.1-1
CUDNN: instalado: 8.0.5.39-1

What am I missing? I`m running Manjaro Linux. I found some extra comments: https://forum.manjaro.org/t/what-is-the-best-configuration-to-get-cuda-and-cudnn-with-the-current-state-of-drivers/47480/6

Still not sure about what to do.

**Comment by daliel** [comment]
faced the same problem.
downloaded the darknet from https://github.com/AlexeyAB/darknet/
changed:
  ```
GPU = 1
  CUDNN = 1
  OPENCV = 1
  CUDNN_HALF = 1
  arch = compute_86, code = [sm_86, compute_86]
  else
  LDFLAGS + = -L / usr / local / cuda-11.2 / lib64 -lcuda -lcudart -lcublas -lcurand
  endif
  else
  CFLAGS + = -DCUDNN -I / usr / local / cuda-11.2 / include
  LDFLAGS + = -L / usr / local / cuda-11.2 / lib64 -lcudnn
  endif

```
run make

everything works.
downloaded the darknet from https://github.com/opendatacam/darknet
made the same changes as above.
after the make received an error:
```
./src/convolutional_layer.c:286:24: error: ‘CUDNN_CONVOLUTION_FWD_PREFER_FASTEST’ undeclared (first use in this function); did you mean ‘CUDNN_CONVOLUTION_BWD_FILTER_ALGO_3’?
     int forward_algo = CUDNN_CONVOLUTION_FWD_PREFER_FASTEST;
                        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                        CUDNN_CONVOLUTION_BWD_FILTER_ALGO_3
compilation terminated due to -Wfatal-errors.
Makefile: 163: recipe for target 'obj / convolutional_layer.o' failed
make: *** [obj / convolutional_layer.o] Error 1
```


what changes did you make? Will the odc work if I replace your darknet with AlexeyAB / darknet?

**Comment by HaileeKim** [comment]
Hi, I've got same issue with you, how did you solve it?

**Comment by vfbsilva** [comment]
I've manage to have it running with:
community/cuda 11.6.1-1 [instalado]
community/cudnn 8.3.2.44-1

There are some alternatives like the package from aur:
https://aur.archlinux.org/packages/darknet-alexeyab-git

You can also look at he package deps to pick up the right libs.
