### ISSUE TITLE
yolov4 Couldn't find activation function mish, going with ReLU

### ISSUE THREAD

**Issue by bjajoh** [AlexeyAB/darknet#7625]
Hi,

I just installed darknet with Cuda 10.2 and cuDNN7 (CUDNN_HALF=1, Tesla V100), downloaded the yolov4 cfg and weights.
However, for some reason the mish activation function is missing. It seems weird to me.
Can you point me in the right direction?

**Couldn't find activation function mish, going with ReLU**

Thanks for your help!
Bjarne

**Comment by lsd1994** [comment]
Do you use the lastest darknet?

**Comment by bjajoh** [comment]
Yes, I just cloned it.

**Comment by bjajoh** [comment]
It was stupid mistake, apparently I cloned the old repo: https://github.com/pjreddie/darknet
But thanks for your help! :)
