### ISSUE TITLE
Can you train 2 diferent models on the same GPU?

### ISSUE THREAD

**Issue by Duarte-Nunes** [AlexeyAB/darknet#7631]
Basically the question above, in linux if i open a terminal and start training a network and then open another terminal and start training a diferent network, will the training be succefull if the computer only has 1 GPU?

**Comment by stephanecharette** [comment]
I've never tried, but I believe it is possible to do this.  It would depend on the amount of vram you have available, which is related to these 3 items:

1) The configuration used (YOLOv4, YOLOv4-tiny, YOLOv4-tiny, etc)
2) The dimensions of the network
3) The total amount of vram on the GPU.

Run `nvidia-smi` after you start training the first network and see how much memory is still available.

**Comment by Duarte-Nunes** [comment]
Thanks for the answer, luckily i was able to train the networks on a server made avaiable to me with lots of GPU ram.
I trained two tiny networks at the same time and found no problems in either one.

Closing the issue.
