### ISSUE TITLE
Using 16 bit images instead of 8

### ISSUE THREAD

**Issue by Luxato** [AlexeyAB/darknet#764]
Hello @AlexeyAB 
I want to ask, how I can change the model to make it accept 16 bit images as input, instead of 8 bit.

Thank you

**Comment by AlexeyAB** [comment]
@Luxato Do you want to load 16-bit x 3-channels image, 48-bit per pixel?

You should change these 1-3 functions:
1. https://github.com/AlexeyAB/darknet/blob/6b8fd6f33f6a61138136fd022c2b887ae39e2c42/src/image.c#L853-L871

2. and probably this:
    * if OpenCV can't load your format of images: https://github.com/AlexeyAB/darknet/blob/6b8fd6f33f6a61138136fd022c2b887ae39e2c42/src/image.c#L873-L897
    * or this if you compile without OpenCV: https://github.com/AlexeyAB/darknet/blob/6b8fd6f33f6a61138136fd022c2b887ae39e2c42/src/image.c#L1626-L1648

**Comment by Lakshya-Kejriwal** [comment]
@Luxato Did changing these functions work for 16 bit images?

**Comment by Luxato** [comment]
@Lakshya-Kejriwal yes it worked. We compiled without openCV in our project so we changed this last one load_image_stb
