### ISSUE TITLE
What are Supported Image Formats for training YOLOv4 on Darknet Framework?

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [AlexeyAB/darknet#7652]
Hi, I was wondering what are the supported image formats for training a Yolov4 object detector on the Darknet Framework? I ask this question because I have not found a list of acceptable image formats and from my research online I found that Yolov4 Darknet only support **jpg and jpeg format**, so would just like to confirm. Thanks!

**Comment by stephanecharette** [comment]
What is the difference between "jpg" and "jpeg" format?  Where online did you find that Darknet only supports these?  What have you tried so far?

**Comment by ekesdf** [comment]
Well basically every normal format like JPG, PNG and there is no difference between JPG and JPEG it is just a naming thing nothing to worry about

**Comment by ekesdf** [comment]
![Bildschirmfoto von 2021-04-27 19-55-28](https://user-images.githubusercontent.com/64316659/116289315-acbc0880-a792-11eb-9c2a-2a2eb4c2b5be.png)
well there is a screenshot of all formats darknet is able to store images in

**Comment by ekesdf** [comment]
If you build it with OpenCV support it can read any format supported via OpenCV

so all those formats
Windows bitmaps - *.bmp, *.dib (always supported)
JPEG files - *.jpeg, *.jpg, *.jpe (see the Note section)
JPEG 2000 files - *.jp2 (see the Note section)
Portable Network Graphics - *.png (see the Note section)
WebP - *.webp (see the Note section)
Portable image format - *.pbm, *.pgm, *.ppm *.pxm, *.pnm (always supported)
PFM files - *.pfm (see the Note section)
Sun rasters - *.sr, *.ras (always supported)
TIFF files - *.tiff, *.tif (see the Note section)
OpenEXR Image files - *.exr (see the Note section)
Radiance HDR - *.hdr, *.pic (always supported)
Raster and Vector geospatial data supported by GDAL (see the Note section)
