### ISSUE TITLE
Advice wanted : Detection on small image patches

### ISSUE THREAD

**Issue by holger-prause** [AlexeyAB/darknet#7668]
Hello,
I succesfully trained an object detector with network width 608 * 608
My objects are detected pretty well there.

One of our clients wants to perform object detection on "unusual" image sizes (small image patches) where the model performs 
sometimes very poorly.

How do i improve the object detection on those small image patches but at the same time dont loose accuracy on "normal" image sizes? I think the most obvious thing to do would be:
- Just include those "unusual" / small patches in the training (using cropping on existing data)

Are there any other techniques i could use to improve object detection on those small patches?
Some ideas:

- Analyze aspect ratio resize and do an additional resize before resizing to network dimensions
- Change network resolution "on the fly" - based on the image dimensions

Any input on this is highly welcome.
Thank you very much - Greetings - Holger

**Comment by holger-prause** [comment]
Answer to myself - chaning the network resolution based on image dimensions is very promising.
I just tested this on a small patch and it seems to get the job done.

**Comment by holger-prause** [comment]
Hello, thanks a lot for your input - it certainly helps.

I am currently using opencv for resizing with cv.INTER_LINEAR 
From what i am reading in the documenatation this is used for "zooming". So basically i am already doing this for the small patches.
But i did not include those in my dataset yet and for this reason failing with my detections. 

But just picking a smaller network resolution (opposite of zooming the image - decrease networks resolution) - i can can archieve a similar effect.

"random crop + zoom/resize" is something i could easily do on my dataset.
**Thanks a lot for your help - this is certainly a valid and easy solution.**

**Comment by holger-prause** [comment]
closing issue as solved - consider using darkmark - or hiring stephanecharette.

**Comment by stephanecharette** [comment]
> closing issue as solved - consider using darkmark - and/or hiring stephanecharette.

I'm available for hire.  I do short-term (less than 1 week) contracts all the time. :)

**Comment by holger-prause** [comment]
_**Ok so thats what i did in the end to get this "small patch" problem working:**_

**Before training**
In the net section - set letter_box=1 in [net] section and train your model.
This will keep the aspect ratio of the image and padd rest with black pixels

**When doing detection:**
Resize the image but keep the aspect ratio of the image and pad rest with black pixels.
Sounds familar? Yes this is the same like letter_box was doing during training.
_This way the detection image is somewhat similar to the image the network has seen during training._

Its such a simple technique and it does the job for me. No network resizing or augementation of existing data is needed.
At least for me this does the job.

**Comment by stephanecharette** [comment]
> In the net section - set letter_box=1 in [net] section and train your model.

The problem with that is letterbox is no longer fully supported.  There are new parts of the darknet codebase that expects letterbox to always be set to zero.

**Comment by holger-prause** [comment]
Doh...

Thx Stephane for  pointing this out - but even without letter_box=1 training and just implementing this technique for detection images - we got reasonable results on small patches where we previously failed.

So i will stick to it for now.
