### ISSUE TITLE
Error: cuDNN isn't found FWD algo for convolution

### ISSUE THREAD

**Issue by CAT1210** [AlexeyAB/darknet#7669]
I am having issues with this error and, from what I read, it is a memory issue.
![image](https://user-images.githubusercontent.com/74838388/116801945-90d2a280-aac3-11eb-875c-cce66a994138.png)

![image](https://user-images.githubusercontent.com/74838388/116801953-a2b44580-aac3-11eb-9a62-6b8f402f20c1.png)

I have a 1660 TI and not sure what to do to get it to stop taking so much GPU that it bombs out very quickly.

Can I limit the memory used like I can in tensorflow? I read I can decrease batch size but not sure where to do that. I tried in darknet.cfg and then rebuilding but that didn't work. Also tried to increase subdivisions but that had no change either.

**Comment by zhihancn** [comment]
![image](https://user-images.githubusercontent.com/40417178/116805627-4ea87000-ab5a-11eb-9e45-f437bf92bb09.png)

**Comment by CAT1210** [comment]
Thanks! Yes, I saw that, but as I mention, I'm not sure where people are changing the batch size. I see batch size in the darknet.cfg file but changing it there makes no difference in batch size when I run darknet.exe (after using cmake to  create it all again, etc).

**Comment by CAT1210** [comment]
I think I found where to change the batch size, or at least it is reflected as such at the beginning of training, but when I run training it still gives me the same error when batch is on 32, 16, 1, and two...not sure what to do with it.

**Comment by CAT1210** [comment]
Ended up just training on Google Colab. Flakey at best but....at least I can train.

**Comment by huynhthaihoa** [comment]
I also got the same issue when trying to training on my laptop (RTX 3060 laptop):
![Capture 2](https://user-images.githubusercontent.com/14910317/118086264-a23e7780-b3fe-11eb-98b5-7e5d0b0ca5ff.PNG)
![Capture 1](https://user-images.githubusercontent.com/14910317/118086269-a36fa480-b3fe-11eb-8d3d-d6ec407965ad.PNG)

**Comment by romulofff** [comment]
I had the same issue while training on a RTX 2060 GPU with custom dataset. 
Reducing the batch size seems to fix it just fine, but I'm not sure what is the relation between cuDNN conv algorithm and this batch size fix. 

At least the training started.

**Comment by CAT1210** [comment]
> I had the same issue while training on a RTX 2060 GPU with custom dataset.
> Reducing the batch size seems to fix it just fine, but I'm not sure what is the relation between cuDNN conv algorithm and this batch size fix.
> 
> At least the training started.

Unfortunately, adjusting the batch size made no difference for me....I have taken to training on Google Colab instead...

**Comment by huynhthaihoa** [comment]
> I had the same issue while training on a RTX 2060 GPU with custom dataset.
> Reducing the batch size seems to fix it just fine, but I'm not sure what is the relation between cuDNN conv algorithm and this batch size fix.
> 
> At least the training started.



> > I had the same issue while training on a RTX 2060 GPU with custom dataset.
> > Reducing the batch size seems to fix it just fine, but I'm not sure what is the relation between cuDNN conv algorithm and this batch size fix.
> > At least the training started.
> 
> Unfortunately, adjusting the batch size made no difference for me....I have taken to training on Google Colab instead...

The same with my case, I've also tried with different batch sizes but still got the same issue every time. I guest the lying problem is my hardware (maybe?)

**Comment by FakhrTarabay** [comment]
I faced this problem as well and fixed it by changing the value of subdivisions to 64 in the cfg file.

**Comment by romulofff** [comment]
It seems to be a problem related to the amount of memory used during training then. Because if changing batch size fixes it for some cases, and changing subdivisions on other, then it's probably something related to the memory size. @CAT1210, have you tried messing around with different batch sizes and subdivisions?

**Comment by CAT1210** [comment]
I have played around with the batch sizes a lot and I thought I had played around with subdivisions but I want to do subdivisions again to make sure. Unfortunately, I have done a lot since my first post and have lost my darknet-gpu and having difficulty getting it stood back up now. I will try to get it all back before tomorrow and give subdivisions a try.

**Comment by CAT1210** [comment]
I'm afraid I just cannot get this setup again on my PC. CMake, VS, PS, everything I try fails for some reason or another and I don't want to uninstall everything I have setup since I am actively running scripts in YOLO-V4 Keras and don't want to break anything for that and it has just been too long and I probably made a lot of changes since I was trying to get this going last. Plus...as much as I hate using Google Colab, it is easy to stand it up and get training quickly rather than troubleshoot my own PC for hours at this point, and potentially breaking scripts that are more important than training....so....hopefully, batch size or subdivisions is the answer for others.

**Comment by CAT1210** [comment]
@romulofff I was able to get this stood back up on my PC successfully and can firm that adjusting batch size or subdivisions makes no difference to me. I have tried 16, 32, 64 for batch size and subdivisions and it still takes up all the GPU to failure...

**Comment by stephanecharette** [comment]
What are your network dimensions?  How much vram do you have?  What config are you using?

**Comment by CAT1210** [comment]
I'm not sure what you mean by "network dimensions"? Internet speed? If so, then that is 1GB (ethernet). My GPU has 6GB of dedicated GPU memory, 16GB shared GPU memory (but I don't think anything has ever ran on that or could run on that). I am using a config file for YoloV4 that I put together for 3 classes to train. Here is how the original would have looked at the top:

[net]
# Training
batch=64
subdivisions=64
# Testing
#batch=1
#subdivisions=1
width=608
height=608
channels=3
momentum=0.949
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
burn_in=1000
max_batches=8000
policy=steps
steps=3000,3600
scales=.1,.1

max_chart_loss=40.0

#cutmix=1
mosaic=1

#:104x104 54:52x52 85:26x26 104:13x13 for 416

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=mish

**Comment by stephanecharette** [comment]
> I'm not sure what you mean by "network dimensions"? Internet speed? If so, then that is 1GB (ethernet). My GPU has 6GB of dedicated GPU memory, 16GB shared GPU memory (but I don't think anything has ever ran on that or could run on that). I am using a config file for YoloV4 that I put together for 3 classes to train. Here is how the original would have looked at the top:

Network dimensions:  what size is your neural network.  The width and height at the top of your .cfg file.  Looks like you are using 608x608.

Note that a 608x608 YOLOv4 network needs approximately 7 GiB of vram to train.  https://www.ccoderun.ca/programming/darknet_faq/#memory_consumption

But you say your GPU has 6 GiB of vram.  Like the FAQ states -- choose a better suited configuration, change the network dimensions, or upgrade your hardware.

**Comment by CAT1210** [comment]
Thanks for that! Training on Colab, I had it up on 608x608 but changing it back down to 416x416 plus having subdivisions and batches set down to 16 is allowing me to train!! Thank you!!!!!!!!!!!!
