### ISSUE TITLE
Deployment using Flask

### ISSUE THREAD

**Issue by varungupta31** [AlexeyAB/darknet#7670]
I have trained a custom YoloV4 model and trained it on google colab. 

I converted my model into a `.pb `file as well.
I wish to deploy my model using flask on local-host, can someone please guide me on how to proceed?

I'm completely stuck.

**Comment by dsbyprateekg** [comment]
@varungupta31 follow this link:
[https://dsbyprateekg.blogspot.com/2020/06/how-to-deploy-your-ml-model-as-fast-api.html

](url)

**Comment by varungupta31** [comment]
@dsbyprateekg Thanks, i'll check it out. Though, I am still looking for a Flask implementation.

**Comment by haviduck** [comment]
where are you stuck?

**Comment by varungupta31** [comment]
@haviduck Actually, at the time of asking this question, I didn't know what to do at all, but have made decent progress since then. 
Now I'm actually stuck at a specific problem, let me know if you can help.
There is python file I have - `app_helper.py` (This file is basically the `detect.py` file with some edits).
The `app_helper.py` has a method - `get_image(filepath)` i.e, it takes the path of the input image as its argument and then, reads the image, run YOLO on it,  save the final image with detections in a given directory.

When I'm running `app_helper.py` 
``` 

def get_images():
   Read, Detect, Save

get_image(<myDir>)
```
it is working completely fine, and the image with detection gets saved.

**But doesn't do anything when imported and called inside the flask `app.py` file. (Neither produces an error)**

```
import app_helper
from app_helper import *
@app.route('/uploader', methods = ['GET', 'POST'])
def upload_file():
   if request.method == 'POST':
      f = request.files['file']
      # create a secure filename
      filename = secure_filename(f.filename)
      print(filename)
      # save file to /static/uploads
      filepath = os.path.join(app.config['UPLOAD_FOLDER'], filename)
      print(filepath)
      f.save(filepath)
      get_image(filepath)         <<<-----------------------------------HERE
              
      return render_template("uploaded.html", display_detection = filename, fname = filename)      

if __name__ == '__main__':
   app.run(port=4000, debug=True)
```

- I have re-checked the file paths, all are absolutely correct.
- The `upload_file` method as mentioned in code - is supposed to take input image from the user (which they will upload).
- The image uploading functionality is working well and the images is getting saved in the right location.
- The get_image function doesn't return anything, it saves the image with detection at the specified path.

The `uploaded.html` template expects the uploaded image and the image with detection, but the images with detection is not being written when used in the flask app. I even tried removing the variable 'filepath' and mentioned a specific path, then too the image is not being written.

_I understand this might not be the most optimal way, but once I learn the process, I'll make it optimized._

**Comment by varungupta31** [comment]
@haviduck I figured out what I was doing wrong. I ended up having two 'main' files in the overall application that were colliding.
I got it working now!
I'm closing this thread, for those who want to see it implemented, I'll post the final version in my repo, in a few weeks.
