### ISSUE TITLE
Is there any command for pre-loading the model weights and "waiting" for the image for inference?

### ISSUE THREAD

**Issue by dwwelch11** [AlexeyAB/darknet#7680]
I have a trained yolov4-tiny custom model running on an Nvidia Jetson Xavier. It is working perfectly! So thank you for the detailed instructions. 

My issue is, I want to be able to use my model very quickly (~1s). While the predictions happen much faster than that (0.3s) the model spends ~10s loading weights. Is there any way to load the weights separately, and then be able to call the model with weights already loaded? 

I would also like to say, my only issue I've had with this is not knowing where to find more information on the command line commands for running the model. For example, it took hours of googling to figure out I could use the "-ext_output" command to get the bounding box printed with the results output. Anyone have any idea where these commands and arguments are found?

**Comment by stephanecharette** [comment]
The `-ext_output` and other params are documented in the readme.

People aren't expected to use the command-line version of Darknet for inference in the scenario you described.  The command-line is when you want to test things out with just a few images.

If you want to load the network once and then apply it to every video frame from a camera, or a large set of images, you'd use the API.  Either the python one, the original C one, or the C++ one.

For example, I maintain a C++ API called DarkHelp which I use on my Jetson Nano and Jetson NX devices:  https://www.ccoderun.ca/darkhelp/api/API.html

**Comment by dwwelch11** [comment]
Hey Stephane,

I found the params in the readme, but it's not quite what I was looking
for. The APIs look promising, unfortunately I can't seem to find a Python
API that will work with Yolo-v4-tiny on a custom trained model. If you know
of one (that has documentation as good as yours) please let me know.

I don't know any C/C++, so to use DarkHelp I'd have to use the CLI. Is
there a way on the CLI to pre-load the weights and config and then wait on
user input for an image? Specifically, I would need to tile the image also.

So is it possible to do:

> DarkHelp yv4-tiny-obj.cfg yv4-tiny-obj_final.weights yv4-tiny-obj.names -T
> true

and then wait for an image input? If I try this I get an exception related
to "failed to properly identify the [net] section in yv4-tiny-obj.cfg" so I
can't test it myself.

this is my [net]

> [net]
> # Testing
> #batch=1
> #subdivisions=1
> # Training
> batch=64
> subdivisions=16
> width=1344
> height=1344
> channels=3
> momentum=0.9
> decay=0.0005
> angle=0
> saturation = 1.5
> exposure = 1.5
> hue=.1
>
> learning_rate=0.00261
> burn_in=1000
> max_batches = 30000
> policy=steps
> steps=24000,27000
> scales=.1,.1
>

Any advice you could provide would be a huge help. Thanks so much for your
reply.

**Comment by stephanecharette** [comment]
> unfortunately I can't seem to find a Python API that will work with Yolo-v4-tiny on a custom trained model.

What is wrong with the python one that comes with Darknet?

> DarkHelp yv4-tiny-obj.cfg yv4-tiny-obj_final.weights yv4-tiny-obj.names -T true
> and then wait for an image input? If I try this I get an exception related to "failed to properly identify the [net] section in yv4-tiny-obj.cfg" so I can't test it myself. this is my [net]

You didn't read the documentation well enough if that is the command you tried.

Either use `--help` to get the help, or see the many examples on these pages:
- https://www.ccoderun.ca/darkhelp/api/Tool.html
- https://www.ccoderun.ca/darkhelp/api/Parameters.html
- https://www.ccoderun.ca/darkhelp/api/ShellScripting.html

**Comment by dwwelch11** [comment]
Thanks for the example resources. Sorry for not understanding. 

There is nothing wrong with the python one that comes with darknet, but the "example" on how to use it isn't really an example. As I don't know C++, I have no idea what the functions defined at the bottom of the example file mean. 

To anyone else struggling with this, this was my solution using the provided darknet Python API on Linux. 

`python
import cv2
import darknet as dn 

cfg = b"yv4-tiny-obj.cfg"
data = b"obj.data"
wgt = b"yv4-tiny-obj_final.weights"
img = b"test_img.jpg"

net = dn.load_net_custom(cfg, wgt, 0, 1)
# if you didn't make a custom version, you can just use dn.load_net()

meta = dn.load_meta(data)
classes = [meta.names[i].decode("ascii") for i in range(meta.classes)]

# from the 'darknet.py' file it was not immediately obvious that you had to load the image first
i = dn.load_image(img, img_width, img_height)  # w and h both int types
predictions = dn.detect_image(net, classes, i)

>>> [("obj", confidence, (center_horiz, center_vert, width, height))]
`

As you say, Stephane, the it's likely that I am just not good at reading documentation. Hopefully this helps someone spend less hours on this than I did.
