### ISSUE TITLE
what do [resize] and [scale_x_y] params in yolov4-tiny yolo layer mean?

### ISSUE THREAD

**Issue by ThomsonW** [AlexeyAB/darknet#7683]
hi there, i have to develop a detection app on edge device, so i need to convert the darknet model to caffemodel. the model i used is yolov4-tiny.
the problem is that  i use the decode function i used for yolov3 and the bbox i got is smaller than the result from darknet. i mean, the width and height is smaller, but the center point is fine.
so i check the cfg file, and i found the new params like [resize] and [scale_x_y], i guess the param is used to scale the bbox, but i dont know the formulation.
can anybody help me, thanks.

**Comment by lsd1994** [comment]
resize=1.5 - randomly resizes image in range: 1/1.5 - 1.5x
scale_x_y=1.05 - eliminate grid sensitivity(details #3293)

**Comment by akashAD98** [comment]
It has all parameters from Yolo cfg [https://github.com/AlexeyAB/darknet/wiki/CFG-Parameters-in-the-%5Bnet%5D-section](url) . Hope it will help you.

**Comment by Hiwyl** [comment]
@ThomsonW  HI，yolov4-tiny 如何转成caffemodel格式得，我caffe源码不改动得情况下会有bug

**Comment by ThomsonW** [comment]
@lsd1994 @akashAD98  Thanks a lot.  I have fixed the post-process according to your advice, and the problem was solved.
@Hiwyl yolov4-tiny中的route层的参数（groups和group_id）在caffe中并不支持，你需要在转换代码中针对上述两个参数在cfg转prototxt中进行调整。一般来说需要用split层去替换。

**Comment by ThomsonW** [comment]
@lsd1994 @akashAD98  Thanks a lot.  I have fixed the post-process according to your advice, and the problem was solved.
@Hiwyl yolov4-tiny中的route层的参数（groups和group_id）在caffe中并不支持，你需要在转换代码中针对上述两个参数在cfg转prototxt中进行调整。一般来说需要用split层去替换。

**Comment by ThomsonW** [comment]
@lsd1994 @akashAD98  Thanks a lot.  I have fixed the post-process according to your advice, and the problem was solved.
@Hiwyl yolov4-tiny中的route层的参数（groups和group_id）在caffe中并不支持，你需要在转换代码中针对上述两个参数在cfg转prototxt中进行调整。一般来说需要用split层去替换。

**Comment by ThomsonW** [comment]
@lsd1994 @akashAD98  Thanks a lot.  I have fixed the post-process according to your advice, and the problem was solved.
@Hiwyl yolov4-tiny中的route层的参数（groups和group_id）在caffe中并不支持，你需要在转换代码中针对上述两个参数在cfg转prototxt中进行调整。一般来说需要用split层去替换。

**Comment by Hiwyl** [comment]
@ThomsonW ok，tks

**Comment by xixidiaosoulianwa** [comment]
@ThomsonW 请问您提到的 fixed the post-process 具体指的是什么？
