### ISSUE TITLE
Including negative samples reduces mAP in yolov4-tiny.

### ISSUE THREAD

**Issue by poornimajd** [AlexeyAB/darknet#7697]
Hey,I read some issues and suggestions on improving accuracy.
I tried to include 500 background images to the dataset(10k images),but the mAP reduces from 70%(no negative samples while training ) to 42% during training with negative samples.Is there something wrong I am doing?

**Comment by bulatnv** [comment]
Hello @poornimajd 

1) check dataset, visualise it and have a look.
2) try runnung train script with _-show_imgs_ flag.
3) negative samples should be really negative, means your model should make false predictions on them. If your model trained only on positive samples doesn't make false prediction (for example, samples are totally black) I think this negative samples are useless.

Best of luck.
