### ISSUE TITLE
Saving von weights only every 10 000 iterations

### ISSUE THREAD

**Issue by GuybrushThreepwood75** [AlexeyAB/darknet#7698]
Hello,
the training went sooth, but the weihts were only saved every 10 000 iterations... in an earlier version it was every 1 000 iterations. 
Is 10 000 now the new default? How can this be changed?

Thanks und stay healty!!!

**Comment by nqthai309** [comment]
i also have the same problem, please tell me how to solve them. Thanks!

**Comment by stephanecharette** [comment]
This is not a problem...this is exactly what it should be.  If you train for < 10K iterations, then it saves every 1000.  If you train for >= 10K, then it saves every 10K.  But the one you should use is ..._best.weights, which you'll have if you train with `-map`.

**Comment by stephanecharette** [comment]
I don't recommend messing with it, but _if_ you want to modify this, do a grep for `max_batches < 10000` in the `src` directory.

**Comment by nqthai309** [comment]
thank you <3
