### ISSUE TITLE
warning C4244: 'return': conversion from 'double' to 'float', possible loss of data

### ISSUE THREAD

**Issue by NicolaiHG** [AlexeyAB/darknet#77]
When i try to release the no gpu version i get a bunch of c4244 errors.
Im using visual studio 2017 and opencv 320.

**Comment by AlexeyAB** [comment]
@NicolaiHG 

Darknet can't be compiled by using OpenCV 3.2.0: https://github.com/AlexeyAB/darknet/issues/60#issuecomment-293527194

To remove this Warning try to add at the top of this file: `#pragma warning(disable: 4244) // possible loss of data`

**Comment by NicolaiHG** [comment]
Ok thanks. Got it working with opencv249 and visual 15. CUDA would not work with visual 17

**Comment by AlexeyAB** [comment]
> CUDA would not work with visual 17

What did you install the first: CUDA8.0 or MSVS2017?

If you installed MSVS after CUDA, then you should reinstall CUDA to integrate CUDA-plugin into MSVS.
