### ISSUE TITLE
./src/image.c:240:2: error: ‘for’ loop initial declarations are only allowed in C99 mode

### ISSUE THREAD

**Issue by dexception** [AlexeyAB/darknet#770]
ocal/cudnn/include -DCUDNN_HALF -c ./src/image.c -o obj/image.o
./src/image.c: In function ‘get_actual_detections’:
./src/image.c:240:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (int i = 0; i < dets_num; ++i) {
  ^
compilation terminated due to -Wfatal-errors.
make: *** [obj/image.o] Error 1

**Comment by AlexeyAB** [comment]
I fixed it.
