### ISSUE TITLE
Bounding Box Coordinates

### ISSUE THREAD

**Issue by kukil-kashyap-borgohain** [AlexeyAB/darknet#7712]
Hi,
I want to store the coordinates of the detected bounding boxes in a .csv file. I tried to edit the darknet.py file but it is not doing anything. I added the following lines to the draw_box() function. How should I proceed?
```
with open ('coordinates.csv', 'wt') as f:
		writer = csv.writer(f)
		row = ('{}, {}, {}, {}'.format(left,top,right,bottom))
		writer.writerow(row)
```

**Comment by bharath5673** [comment]
@kukil-kashyap-borgohain 

hope this`https://stackoverflow.com/questions/65381312/how-to-convert-a-yolo-darknet-format-into-csv-file` can help u :3

**Comment by kukil-kashyap-borgohain** [comment]
Thanx @bharath5673 for replying. But the link is for converting the annotation dataset. I want to extract the bbox coordinates of the detections.

**Comment by kukil-kashyap-borgohain** [comment]
Thanx. That solved it.
