### ISSUE TITLE
Makefile:185: recipe for target 'obj/network_kernels.o' failed

### ISSUE THREAD

**Issue by Aniruddha7** [AlexeyAB/darknet#7719]
I am recently getting this error when I run the command `!make` 

`
![image](https://user-images.githubusercontent.com/19803877/118812200-7e31d900-b8cb-11eb-84fc-6e1d8c24d248.png)

I have installed Cuda release 8.0 and had no issues while installing it but during the `!make` step, it is throwing this error. I have also tried with `!make clean` and setting up `NVCC = /usr/local/cuda/bin/nvcc` and `ARCH= -gencode arch=compute_37,code=sm_37` in make file mentioned in other issues but couldn't fix the issue. Can anyone please help?

**Comment by stephanecharette** [comment]
Did you do a search for any of these errors?

https://github.com/AlexeyAB/darknet/issues?q=cudagraphexec_t

**Comment by Aniruddha7** [comment]
> Did you do a search for any of these errors?
> 
> https://github.com/AlexeyAB/darknet/issues?q=cudagraphexec_t
Thank you so much. Updating CUDA from 8.0 to 10.2 resolved the issue. I searched for the similar error but could not find the above thread earlier. Thank you for the quick help!
