### ISSUE TITLE
Detect Problem: Cannot load image "XXXXXX.jpg"

### ISSUE THREAD

**Issue by Leontree** [AlexeyAB/darknet#772]
First,thanks for your come in. I've trained a datasets and got my_yolov3_900.weights.
When I detect picture "dog.jpg", it is ok. At least, it has a result~~~~
![prediction](https://user-images.githubusercontent.com/25098297/39791068-fd2de05a-536b-11e8-9639-a4f32836876b.png)
But when I test another picture (horses.jpg). **Cannot load image "horses.jpg"**
I tried to: 
1.Renamed "horses.jpg" as "dog.jpg", but prediction still shown the content of "dog.jpg".
2.Deleted "dog.jpg", but prediction still shown the content of "dog.jpg"!!   Didn't report any error.
![issue](https://user-images.githubusercontent.com/25098297/39790823-afaa91d0-536a-11e8-993a-32d6ef57e35d.png)
![issue2](https://user-images.githubusercontent.com/25098297/39790825-b3e8030e-536a-11e8-871e-f9bd5784124f.png)
![issue3](https://user-images.githubusercontent.com/25098297/39790827-b66afe2e-536a-11e8-80cc-f0fea1d7c911.png)
Thank you!!!!

**Comment by AlexeyAB** [comment]
May be because `horses.jpg` is in the `data/` folder. But there are two `dog.jpg` files, in the data/ folder and near with the darknet.exe

So use `data/horses.jpg`

**Comment by Leontree** [comment]
Thanks for replying. Problem solved.｡:.ﾟヽ(｡◕‿◕｡)ﾉﾟ.:｡+ﾟ
