### ISSUE TITLE
What exactly does the `ignore_thresh` parameter mean? 

### ISSUE THREAD

**Issue by gh-BumsooKim** [AlexeyAB/darknet#7722]
In this repository Wiki, `ignore_thresh` means that **\"keeps duplicated detections if IoU(detect, truth) > ignore_thresh, which will be fused during NMS (is used for training only)\"**

But, i can't understand that mean exactly.

If `ignore_thresh = .8`, what's different in object detection?

I wonder that `ignore_thresh = .7` and `truth_thresh = 1` means in object detection in details.

**Comment by lsd1994** [comment]
#4448

**Comment by gh-BumsooKim** [comment]
Thank you for your help. @lsd1994 

But, I have one more question.
What is the 'best parameters' or 'conditions' for Object Detection?
Is it best for iou to be between `ignore_thresh` and `truth_thresh` in training?

I want to overfit my model a bit on purpose.
Because I need to classify my face-classes between human.

**Comment by lsd1994** [comment]
It's hard to say what the best parameters and conditions for your specific application, maybe you can use default settings.

**Comment by gh-BumsooKim** [comment]
Thanks, I'll have to study this more.
