### ISSUE TITLE
Guidance on changes for Custom Darknet Tracker

### ISSUE THREAD

**Issue by SriHarsha-Paladugula** [AlexeyAB/darknet#7726]
We have trained a custom yolo detector with 3 classes (Mask, Unmask, Rear). These are the two things we want to achieve
1.  Track the detections based on track id
2.  Depending on threshold(say 10) for the last 10 detections of the same track id, I will check the counts of labels mask, unmask and rear and if any of those counts > 5 then we are considering that bounding box with label which satisfied the above criteria.

(Reason for second step is the output from the detector changes sometimes between mask and unmask that is the reason we are taking a majority vote across frames)

Problem here is here is there are too much changes in track id which is hampering us achieving the second goal. Can anyone provide us a way to stabilize the track id's across multiple frames with C++ implementation.

**Comment by SriHarsha-Paladugula** [comment]
Sorry I forgot to update we are using C++ implementation of tracking algorithm the Norfair/sort are in python do you have any references for C++ implementations.

**Comment by haviduck** [comment]
yeah check out the lib_tracker implementation in this repo. he added optflow and kalman
