### ISSUE TITLE
Drawing bbox on the original input image (before resizing)

### ISSUE THREAD

**Issue by wjassim** [AlexeyAB/darknet#7728]
Hi,

I am just wondering how to modify the https://github.com/AlexeyAB/darknet/blob/master/darknet_images.py to force darknet drawing bbox on the original input image instead of drawing on the resized one? 

Thanks a million..

**Comment by woosal1337** [comment]
For that, you are supposed to modify the codes below
```
width = darknet.network_width(self.network)
height = darknet.network_height(self.network)
```
to 
```
width = 480 # (Any size you want to use)
height = 640 # (Any size you want to use)
```

**Comment by wjassim** [comment]
Thank you @woosal1337 . I got it. Best regards..
