### ISSUE TITLE
Route and upsample 

### ISSUE THREAD

**Issue by johnnydept** [AlexeyAB/darknet#773]
Hi @AlexeyAB,

Pjreddie just released Tiny-Yolo-v3. I'm sorry but can you explain how Route layer and up-sample layer works? 
Much appreciated. Thanks 

[EDIT] I saw this [site](https://blog.paperspace.com/how-to-implement-a-yolo-v3-object-detector-from-scratch-in-pytorch-part-2/) explained how layers work.

**Comment by AlexeyAB** [comment]
@johnnydept Hi,

About `[route]` layer - this is the same as Concat-layer from Caffe: https://github.com/AlexeyAB/darknet/issues/120#issuecomment-313371171

----

* `[upsample]` during forward - just resizes input 13x13x256 to output 26x26x256, using nearest approach.

* `[upsample]` during backward - just sum deltas from each 4 pixels (4x4) to 1 pixel (1x1), i.e. resizes 26x26x256 to 13x13x256.
If is used `stride=2`

**Comment by johnnydept** [comment]
Thanks Alex

**Comment by TaihuLight** [comment]
@AlexeyAB @johnnydept 
The site https://blog.paperspace.com/how-to-implement-a-yolo-v3-object-detector-from-scratch-in-pytorch-part-2/ said that 
**Upsamples the feature map in the previous layer by a factor of stride using bilinear upsampling.**

The upsample layer in Darknet uses nearest approach or bilinear upsampling?
During forward, after resize the feature map, how to fill the newly increased pixels?  
A. copy the original pixel to new pixels
B. compute the value of new pixels using bilinear interpolation.
which is correct? A or B?

**Comment by AlexeyAB** [comment]
@TaihuLight 

1. scale by default = 1 https://github.com/pjreddie/darknet/blob/61c9d02ec461e30d55762ec7669d6a1d3c356fb2/src/parser.c#L597

2. Darknet uses nearest approach (A) instead of bilinear: https://github.com/pjreddie/darknet/blob/61c9d02ec461e30d55762ec7669d6a1d3c356fb2/src/blas_kernels.cu#L1027
