### ISSUE TITLE
CutMix Data Augmentation

### ISSUE THREAD

**Issue by atikapane** [AlexeyAB/darknet#7733]
I am currently trying to build my own custom mask detector. I want to use CutMix as my data augmentation method, but when I use it, I get 
```
cutmix=1 - isn't supported for Detector (use cutmix=1 only for Classifier)
```
Is that mean I can't use cutmix as my data augmentation method? If I can, am I doing it wrong?

**Comment by lsd1994** [comment]
cutmix is only for classifier
