### ISSUE TITLE
a yolo_v2_class.hpp question

### ISSUE THREAD

**Issue by tuteming** [AlexeyAB/darknet#7735]
for object detect( image in and bbox out),  
yolo_v2_class.hpp
in LIB_API std::vector<bbox_t> detect(image_t img, float thresh = 0.2);
and
in std::vector<bbox_t> detect_resized(image_t img, int init_w, int init_h, float thresh = 0.2)

now I want use yolo_v2_class.hpp for image processing
 (ex. pix2pix image in and image out)
LIB_API std::vector<bbox_t> detect--> must change to ?
and 
std::vector<bbox_t> detect_resized --> must change to ?
For image out, I want to opencv Mat format or image format defined in original darket.

Thank for your attention.

**Comment by cenit** [comment]
which kind of image out would you like? one decorated with detections?

**Comment by tuteming** [comment]
thanks, I have solved.
