### ISSUE TITLE
darknet detector map doesn't show anything

### ISSUE THREAD

**Issue by bloomingseed** [AlexeyAB/darknet#7748]
Hi, I have trained my tiny Yolov3 model and I can see my prediction result with `detector test` for `data/person.jpg` and all my test images, but when I run `detector map`, i.e `./darknet detector map data/obj.data cfg/obj.cfg backup/obj_final.weights` then the output is empty, i.e. nothing shows up at all. How do I fix this issue? Although I was able to run this command in my last training process which is about 1 month ago.

**Comment by Luoxsh6** [comment]
same

**Comment by JasmineLi-805** [comment]
Same issue, has it been solved?

**Comment by bloomingseed** [comment]
Sorry everyone, seems like I built pjreddie's darknet instead. I got my mAP results now, although the accuracy that the new darknet detects is slightly worse idk.
