### ISSUE TITLE
Question regarding resuming trained model

### ISSUE THREAD

**Issue by Rodeazzo** [AlexeyAB/darknet#7750]
Good Morning,

This might be a stupid question, but I trained a model using transfer learning with darknet53.conv74 using a dataset that consisted of only positive images. When I tested it versus positive and negative images, I obviously didn't get the best expected results (still wasn't terrible when you factor the threshold). For example, I trained it to detect guns, but when I showed it a guy holding a banana as a gun, no detections happened (good), but when I showed it a taser/drill/glue gun, it got a very high prediction (bad).

So, I was thinking on resuming the training on the model by adding negative images. Would this help? or should I start a model from scratch and have both positive and negatives to train with from the get go? 

Thanks

**Comment by lsd1994** [comment]
https://github.com/AlexeyAB/darknet#how-to-improve-object-detection
