### ISSUE TITLE
Model trained on grayscale images won't work on coloured images and vice-versa?

### ISSUE THREAD

**Issue by varungupta31** [AlexeyAB/darknet#7756]
I trained a custom YOLOv4 Traffic signs detector using the RGB images from the GTSRB dataset,
hue, configuration, etc were default values as in the custom.cfg file and the channels I kept 3 (default)

Trained the model, worked completely fine on RGB images, but when the same image is converted to grayscale using openCV (CV2.cvtColor function) the model won't detect anything!

In other try, I trained a detector using a class from the open images dataset, let the setting (hue, saturation, channels=3, etc. as default) but converted the training data to grayscale images using cv2.cvtColor function and trained the model using these converted to grayscale images)

The model completely fine on grayscale inputs but won't work at all on RGB.

(No errors were obtained upon the time on training above two models)

Is this a limitation of YOLO or am I missing something, that is resulting in such issues?

Thanks.

**Comment by stephanecharette** [comment]
So add a mix of both colour and black-and-white images to your training set.

**Comment by varungupta31** [comment]
Yeah, I deduced that too, my question is more about _why_.

So, is YOLO generalizing the color variations or the geometry specifically? 
Say I have images of candies with spiral design and train YOLO on it, 
If I train using colored images, is YOLO going to emphasize more on learning the color info or will it emphasize of learning the geometry? (circular shape with a pattern inside)

Why is it that a model trained on grayscale data won't detect anything on same data but with color?
(with exact same training parameters)

**Comment by lsd1994** [comment]
> If I train using colored images, is YOLO going to emphasize more on learning the color info or will it emphasize of learning the geometry? (circular shape with a pattern inside)

Both of them.

> Why is it that a model trained on grayscale data won't detect anything on same data but with color?
Sometimes it can be detected, but the performance is bad.

**Comment by varungupta31** [comment]
@lsd1994 @stephanecharette  Thank you for the inputs, I'd continue searching for why this happens. But until then, it's best recommended to include all types of images, in fair proportion, in the training set that you wish to detect your model on.

**Comment by Elise-J** [comment]
Hello @varungupta31,

Did you found anything on why this happened?

**Comment by varungupta31** [comment]
Hey @Elise-J,
**No** I wasn't able to identify the cause for this.
Something else that I identified was that this is not simply a _Color vs Grayscale_ issue, It is also a color palette issue!
I was having a set of thermal images, some were in color scale like - 
![image](https://user-images.githubusercontent.com/51288316/149653498-05592381-4e09-41ef-b8f6-bfaf731519ab.png)

and others were in scale, like-
![image](https://user-images.githubusercontent.com/51288316/149653526-a95b7cdb-2195-474d-8371-d51b3862dea8.png)

The model trained on one type, didn't work on other.
So this issue goes beyond 'color vs grayscale'.

**Comment by Elise-J** [comment]
Ok, that's interesting !

Thank you for your answer :)
