### ISSUE TITLE
There's something wrong with my loss curve

### ISSUE THREAD

**Issue by GolinY** [AlexeyAB/darknet#7767]
When I train, IOU is always 0. Is that normal？
![image](https://user-images.githubusercontent.com/62426927/120423303-baba0600-c39c-11eb-8929-216ae0990b1a.png)
Loss is falling fast
![image](https://user-images.githubusercontent.com/62426927/120423613-5481b300-c39d-11eb-8c9a-35f00b0d04d1.png)

When loss is close to 0, stop training and use weights file, but no object can be detected during the test，The result is the original image。

**Comment by GolinY** [comment]
my bad，There's something wrong with my data set

**Comment by Srikeshram** [comment]
@GolinY Will you please tell me how to resolve the issue?
