### ISSUE TITLE
What layers are included in the weight file?

### ISSUE THREAD

**Issue by yankee624** [AlexeyAB/darknet#7775]
Just out of curiosity...

According to the tutorial, if I want to train the model with my custom dataset, I can change the number of classes.
When I change the number of classes, I also have to change the `filters` in last few convolutional layers.
Then, the number of weights in the model will be changed also.
However, I use the same pretrained weight [yolov4.conv.137](https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.conv.137).
How is this possible?
Does the weight file only include the layers except the last few convolutional layers where number of filters are changed?

**Comment by stephanecharette** [comment]
You don't have to use the MSCOCO pre-trained weights.  Especially if your custom network has nothing to do with the classes in the MSCOCO dataset.  The training command you'd use would look like this:  https://www.ccoderun.ca/programming/darknet_faq/#training_command

**Comment by yankee624** [comment]
@stephanecharette 
Thanks for the reply. But the point is that I "can" use the pre-trained weight file.
I am curious how this is possible.
How is using the weight file possible, even when the number of weights in the model changes?

**Comment by lsd1994** [comment]
yolov4.conv.137 only contains weights of backbone, not neck layer.

**Comment by yankee624** [comment]
@lsd1994 If that is true, how come we can run inference right away with yolov4.conv.137 weights? Are the weights of neck layer stored somewhere else?
