### ISSUE TITLE
Darknet Can't Build, CUDA not found

### ISSUE THREAD

**Issue by jpoirier1** [AlexeyAB/darknet#7795]
I am trying to compile darknet on Windows 10 using the PowerShell build script but keep running into an error where CUDA is not found, despite it being installed (Version 11.3 but have tried with 10.2 as well).  I have looked through other solutions on issues similar to this one but haven't gotten any of their fixes working.

Here is what command I am running:
.\build.ps1 -UseVCPKG -EnableOPENCV -EnableCUDA -EnableCUDNN -EnableOPENCV_CUDA

Here is what the running script outputs:
![image](https://user-images.githubusercontent.com/49181111/121721511-2dac3680-ca99-11eb-801e-361c0def5abc.png)

And here is the CMakeError.txt:
Looking for a CUDA compiler failed with the following output:
CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/CMakeDetermineCUDACompiler.cmake:25 (message):
  Could not find compiler set in environment variable CUDACXX:

  C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin.

Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

CMake Error: CMAKE_CUDA_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/Users/james.poirier/AIML/darknet/build_release/CMakeFiles/CheckCUDA/CMakeFiles/CMakeOutput.log".

Finally here are my CUDA environment variables:
![image](https://user-images.githubusercontent.com/49181111/121722258-10c43300-ca9a-11eb-9a30-599247a74f00.png)

Any help is appreciated!

**Comment by cenit** [comment]
can you please show full log from powershell, including initial lines?

**Comment by andsoft** [comment]
Faced the same problem. CUDA was installed before VS2019. Reinstalling CUDA with VS integration fixes problem for me.

**Comment by jpoirier1** [comment]
Not sure what the best way to attach this is, but here is the full log with the commands run:

[build.log](https://github.com/AlexeyAB/darknet/files/6688046/build.log)

Tried reinstalling CUDA with VS integration but still having the same problem

**Comment by cenit** [comment]
can you please copy paste from shell? build.log is incomplete (i was not able to redirect all the output that was on screen)

**Comment by jpoirier1** [comment]
Yeah of course here it is:

PS C:\Users\james.poirier\AIML\darknet> .\build.ps1 -UseVCPKG -EnableOPENCV -EnableCUDA -EnableCUDNN -EnableOPENCV_CUDA
Transcript started, output file is C:\Users\james.poirier\AIML\darknet/build.log
Darknet build script version 0.9.5
PowerShell version:
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  906
vcpkg bootstrap script: bootstrap-vcpkg.bat
CUDA is enabled
CUDNN is enabled
OPENCV is enabled
VCPKG is enabled
VCPKG will be updated to latest version if found
VisualStudio integration is enabled, please pass -DoNotSetupVS to the script to disable
Yolo C# wrapper integration is disabled, please pass -EnableCSharpWrapper to the script to enable. You must be on Windows!
Ninja is enabled, please pass -DoNotUseNinja to the script to disable
ForceCPP build mode is disabled, please pass -ForceCPP to the script to enable
Using git from C:\Program Files\Git\cmd\git.exe
Darknet has been cloned with git and supports self-updating mechanism
Darknet will self-update sources, please pass -DoNotUpdateDARKNET to the script to disable
Already up to date.
Using CMake from C:\Program Files\CMake\bin\cmake.exe
cmake version 3.20.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
Using Ninja from C:\ninja\ninja.exe
Ninja version 1.10.2
Found vcpkg in VCPKG_ROOT: C:\Users\james.poirier\vcpkg-master
Setting up environment to use CMake generator: Ninja
Removing folder ./build_release
Configuring CMake project
CMake args: -G "Ninja"  -DCMAKE_BUILD_TYPE=Release -DENABLE_VCPKG_INTEGRATION:BOOL=ON -S ..
Darknet_VERSION: 0.2.5.4
-- VCPKG found: C:\Users\james.poirier\vcpkg-master
-- Using VCPKG integration
-- VCPKG_MANIFEST_FEATURES: cuda;cudnn;opencv-cuda
-- Running vcpkg install
C:\Users\james.poirier\AIML\darknet
Detecting compiler hash for triplet x64-windows...
The following packages will be built and installed:
    bzip2[core]:x64-windows -> 1.0.8#1
    cuda[core]:x64-windows -> 10.1#7
    cudnn[core]:x64-windows -> 7.6.5#2
    ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,postproc,swresample,swscale]:x64-windows -> 4.3.2#7
    giflib[core]:x64-windows -> 5.1.4-6
    hdf5[core,szip,zlib]:x64-windows -> 1.12.0#1
    leptonica[core]:x64-windows -> 1.80.0#2
    libarchive[bzip2,core,libxml2,lz4,lzma,openssl,zstd]:x64-windows -> 3.4.3#5
    libiconv[core]:x64-windows -> 1.16#8
    libjpeg-turbo[core]:x64-windows -> 2.0.6
    liblzma[core]:x64-windows -> 5.2.5#2
    libpng[core]:x64-windows -> 1.6.37#14
    libwebp[core,nearlossless,simd,unicode]:x64-windows -> 1.1.0#3
    libxml2[core]:x64-windows -> 2.9.10#6
    lz4[core]:x64-windows -> 1.9.3
    opencv[contrib,core,cuda,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.1
    opencv4[contrib,core,cuda,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.1#1
    openjpeg[core]:x64-windows -> 2.3.1#4
    openssl[core]:x64-windows -> 1.1.1k
    protobuf[core]:x64-windows -> 3.15.8
    pthreads[core]:x64-windows -> 3.0.0#9
    quirc[core]:x64-windows -> 1.1#2
    stb[core]:x64-windows -> 2020-09-14
    szip[core]:x64-windows -> 2.1.1-6
    tesseract[core]:x64-windows -> 4.1.1#8
    tiff[core]:x64-windows -> 4.1.0#2
    xxhash[core]:x64-windows -> 0.8.0#1
    zlib[core]:x64-windows -> 1.2.11#10
    zstd[core]:x64-windows -> 1.4.9
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\a9\a923271b32bee4082d71ffd0ce85e7c8a45cf339.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\e5\e5fb388b20c2f8557bd65de77cebc76c241fcb57.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\70\70bfb1c63d3b4ec78b657343df57abcc46d5f63b.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\4f\4feab1bc945c19808c9d8a7edffadffdff1407aa.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\ba\bad11818e2da98107533996a3f5f0c10c6a1db5e.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\2f\2f4303e75fbaa0229a80deccf94a9cabe970a61f.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\86\86f475c092f3941d843ae249258f2f73c223d10f.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\33\330bdfc553a933f4a7e3ce7b26e2e366f4edb2ae.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\58\58f4367c59149231f535271a30a4c96c2a8f3479.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\ff\ffc38f737b68213fe49817eec8cd717fd67a4f7e.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\c5\c56f16df712dd612e279e21536773e415a2f6579.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\ae\ae663120bc02294f8dd8d7d610895082578cd1ed.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\90\90fb73f54e52cf0d432c172a561303faf77b371a.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\dd\dd881cebd4a68c1a05dfc90ea5f5d89b87752d3c.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\05\05b290e6cd688129840d1f0ee30d9d00da416fd0.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\6c\6cab7604d6f77baacce5d0e47e71936e3f41816b.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\87\87c152ec2dd62c7c2231a3015875278458b4a2b5.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\04\0424c417e5467ee058f2f31ff640b795a0fbc7ab.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\36\3675139c7edaf5d2bf415c19d6b2bcb49c8f9bb4.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\a9\a9dee569fc9c4e741f17ab6642e4a621dd1a992b.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\a7\a78f0a22bb4730aedbc2ea229efb67cd0c38ea1d.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\77\7782eeee0a1dfa33fc82430cefd302b53576079b.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\29\29d6c99f05f46e299774fc4d4606b0123f696ba6.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\bc\bcd1188eb74cbf5d35ef8781039f0a321dc203c9.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\21\2110431202ad214eccea24f21a22dd1dd94ba09e.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\55\553291ac3823b8599821edba7110b002a36e6080.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\12\1295d0d9ce3a0e314cd4bb957838f0a8bcc8c652.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\02\02c763741692d6482ea9a54b52715794d6c10575.zip
Using cached binary package: C:\Users\james.poirier\AppData\Local\vcpkg\archives\68\68b6d0af47f49a5beff3d50a892552928d1fcc9c.zip
Starting package 1/29: pthreads:x64-windows
Building package pthreads[core]:x64-windows...
Building package pthreads[core]:x64-windows... done
Installing package pthreads[core]:x64-windows...
Installing package pthreads[core]:x64-windows... done
Elapsed time for package pthreads:x64-windows: 20.09 ms
Starting package 2/29: stb:x64-windows
Building package stb[core]:x64-windows...
Building package stb[core]:x64-windows... done
Installing package stb[core]:x64-windows...
Installing package stb[core]:x64-windows... done
Elapsed time for package stb:x64-windows: 17.06 ms
Starting package 3/29: cuda:x64-windows
Building package cuda[core]:x64-windows...
Building package cuda[core]:x64-windows... done
Installing package cuda[core]:x64-windows...
Installing package cuda[core]:x64-windows... done
Elapsed time for package cuda:x64-windows: 4.12 ms
Starting package 4/29: cudnn:x64-windows
Building package cudnn[core]:x64-windows...
Building package cudnn[core]:x64-windows... done
Installing package cudnn[core]:x64-windows...
Installing package cudnn[core]:x64-windows... done
Elapsed time for package cudnn:x64-windows: 3.889 ms
Starting package 5/29: libwebp:x64-windows
Building package libwebp[core,nearlossless,simd,unicode]:x64-windows...
Building package libwebp[core,nearlossless,simd,unicode]:x64-windows... done
Installing package libwebp[core,nearlossless,simd,unicode]:x64-windows...
Installing package libwebp[core,nearlossless,simd,unicode]:x64-windows... done
Elapsed time for package libwebp:x64-windows: 44.42 ms
Starting package 6/29: zlib:x64-windows
Building package zlib[core]:x64-windows...
Building package zlib[core]:x64-windows... done
Installing package zlib[core]:x64-windows...
Installing package zlib[core]:x64-windows... done
Elapsed time for package zlib:x64-windows: 14.28 ms
Starting package 7/29: liblzma:x64-windows
Building package liblzma[core]:x64-windows...
Building package liblzma[core]:x64-windows... done
Installing package liblzma[core]:x64-windows...
Installing package liblzma[core]:x64-windows... done
Elapsed time for package liblzma:x64-windows: 26.66 ms
Starting package 8/29: libjpeg-turbo:x64-windows
Building package libjpeg-turbo[core]:x64-windows...
Building package libjpeg-turbo[core]:x64-windows... done
Installing package libjpeg-turbo[core]:x64-windows...
Installing package libjpeg-turbo[core]:x64-windows... done
Elapsed time for package libjpeg-turbo:x64-windows: 24.04 ms
Starting package 9/29: tiff:x64-windows
Building package tiff[core]:x64-windows...
Building package tiff[core]:x64-windows... done
Installing package tiff[core]:x64-windows...
Installing package tiff[core]:x64-windows... done
Elapsed time for package tiff:x64-windows: 21.25 ms
Starting package 10/29: quirc:x64-windows
Building package quirc[core]:x64-windows...
Building package quirc[core]:x64-windows... done
Installing package quirc[core]:x64-windows...
Installing package quirc[core]:x64-windows... done
Elapsed time for package quirc:x64-windows: 9.376 ms
Starting package 11/29: libpng:x64-windows
Building package libpng[core]:x64-windows...
Building package libpng[core]:x64-windows... done
Installing package libpng[core]:x64-windows...
Installing package libpng[core]:x64-windows... done
Elapsed time for package libpng:x64-windows: 23.4 ms
Starting package 12/29: ffmpeg:x64-windows
Building package ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,postproc,swresample,swscale]:x64-windows...
Building package ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,postproc,swresample,swscale]:x64-windows... done
Installing package ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,postproc,swresample,swscale]:x64-windows...
Installing package ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,postproc,swresample,swscale]:x64-windows... done
Elapsed time for package ffmpeg:x64-windows: 223.7 ms
Starting package 13/29: protobuf:x64-windows
Building package protobuf[core]:x64-windows...
Building package protobuf[core]:x64-windows... done
Installing package protobuf[core]:x64-windows...
Installing package protobuf[core]:x64-windows... done
Elapsed time for package protobuf:x64-windows: 160.1 ms
Starting package 14/29: zstd:x64-windows
Building package zstd[core]:x64-windows...
Building package zstd[core]:x64-windows... done
Installing package zstd[core]:x64-windows...
Installing package zstd[core]:x64-windows... done
Elapsed time for package zstd:x64-windows: 22.67 ms
Starting package 15/29: openssl:x64-windows
Building package openssl[core]:x64-windows...
Building package openssl[core]:x64-windows... done
Installing package openssl[core]:x64-windows...
Installing package openssl[core]:x64-windows... done
Elapsed time for package openssl:x64-windows: 94.82 ms
Starting package 16/29: xxhash:x64-windows
Building package xxhash[core]:x64-windows...
Building package xxhash[core]:x64-windows... done
Installing package xxhash[core]:x64-windows...
Installing package xxhash[core]:x64-windows... done
Elapsed time for package xxhash:x64-windows: 14.13 ms
Starting package 17/29: lz4:x64-windows
Building package lz4[core]:x64-windows...
Building package lz4[core]:x64-windows... done
Installing package lz4[core]:x64-windows...
Installing package lz4[core]:x64-windows... done
Elapsed time for package lz4:x64-windows: 14.23 ms
Starting package 18/29: libiconv:x64-windows
Building package libiconv[core]:x64-windows...
Building package libiconv[core]:x64-windows... done
Installing package libiconv[core]:x64-windows...
Installing package libiconv[core]:x64-windows... done
Elapsed time for package libiconv:x64-windows: 25.34 ms
Starting package 19/29: libxml2:x64-windows
Building package libxml2[core]:x64-windows...
Building package libxml2[core]:x64-windows... done
Installing package libxml2[core]:x64-windows...
Installing package libxml2[core]:x64-windows... done
Elapsed time for package libxml2:x64-windows: 41.7 ms
Starting package 20/29: bzip2:x64-windows
Building package bzip2[core]:x64-windows...
Building package bzip2[core]:x64-windows... done
Installing package bzip2[core]:x64-windows...
Installing package bzip2[core]:x64-windows... done
Elapsed time for package bzip2:x64-windows: 14.66 ms
Starting package 21/29: libarchive:x64-windows
Building package libarchive[bzip2,core,libxml2,lz4,lzma,openssl,zstd]:x64-windows...
Building package libarchive[bzip2,core,libxml2,lz4,lzma,openssl,zstd]:x64-windows... done
Installing package libarchive[bzip2,core,libxml2,lz4,lzma,openssl,zstd]:x64-windows...
Installing package libarchive[bzip2,core,libxml2,lz4,lzma,openssl,zstd]:x64-windows... done
Elapsed time for package libarchive:x64-windows: 25.25 ms
Starting package 22/29: openjpeg:x64-windows
Building package openjpeg[core]:x64-windows...
Building package openjpeg[core]:x64-windows... done
Installing package openjpeg[core]:x64-windows...
Installing package openjpeg[core]:x64-windows... done
Elapsed time for package openjpeg:x64-windows: 17.14 ms
Starting package 23/29: giflib:x64-windows
Building package giflib[core]:x64-windows...
Building package giflib[core]:x64-windows... done
Installing package giflib[core]:x64-windows...
Installing package giflib[core]:x64-windows... done
Elapsed time for package giflib:x64-windows: 9.328 ms
Starting package 24/29: leptonica:x64-windows
Building package leptonica[core]:x64-windows...
Building package leptonica[core]:x64-windows... done
Installing package leptonica[core]:x64-windows...
Installing package leptonica[core]:x64-windows... done
Elapsed time for package leptonica:x64-windows: 41.52 ms
Starting package 25/29: tesseract:x64-windows
Building package tesseract[core]:x64-windows...
Building package tesseract[core]:x64-windows... done
Installing package tesseract[core]:x64-windows...
Installing package tesseract[core]:x64-windows... done
Elapsed time for package tesseract:x64-windows: 64.87 ms
Starting package 26/29: szip:x64-windows
Building package szip[core]:x64-windows...
Building package szip[core]:x64-windows... done
Installing package szip[core]:x64-windows...
Installing package szip[core]:x64-windows... done
Elapsed time for package szip:x64-windows: 19.93 ms
Starting package 27/29: hdf5:x64-windows
Building package hdf5[core,szip,zlib]:x64-windows...
Building package hdf5[core,szip,zlib]:x64-windows... done
Installing package hdf5[core,szip,zlib]:x64-windows...
Installing package hdf5[core,szip,zlib]:x64-windows... done
Elapsed time for package hdf5:x64-windows: 136.6 ms
Starting package 28/29: opencv4:x64-windows
Building package opencv4[contrib,core,cuda,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows...
Building package opencv4[contrib,core,cuda,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows... done
Installing package opencv4[contrib,core,cuda,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows...
File C:\Users\james.poirier\AIML\darknet\build_release\vcpkg_installed\x64-windows\debug/bin/opencv_cudaoptflowd.dll was already present and will be overwritten
File C:\Users\james.poirier\AIML\darknet\build_release\vcpkg_installed\x64-windows\debug/bin/opencv_cudastereod.dll was already present and will be overwritten
Installing package opencv4[contrib,core,cuda,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows... done
Elapsed time for package opencv4:x64-windows: 2.002 s
Starting package 29/29: opencv:x64-windows
Building package opencv[contrib,core,cuda,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows...
Building package opencv[contrib,core,cuda,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows... done
Installing package opencv[contrib,core,cuda,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows...
Installing package opencv[contrib,core,cuda,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows... done
Elapsed time for package opencv:x64-windows: 20.88 ms

Total elapsed time: 22.62 s

-- Running vcpkg install - done
-- The C compiler identification is MSVC 19.29.30037.0
-- The CXX compiler identification is MSVC 19.29.30037.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - NOTFOUND
-- CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
-- CUDACXX: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin
CMake Error at CMakeLists.txt:148 (message):
  CUDA not found, please build explicitly with -DENABLE_CUDA=OFF if you do
  not want CUDA.


-- Configuring incomplete, errors occurred!
See also "C:/Users/james.poirier/AIML/darknet/build_release/CMakeFiles/CMakeOutput.log".
See also "C:/Users/james.poirier/AIML/darknet/build_release/CMakeFiles/CMakeError.log".
Config failed! Exited with error code 1.
Press any key to continue...
ScriptHalted
At C:\Users\james.poirier\AIML\darknet\build.ps1:84 char:5
+     throw
+     ~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted

**Comment by cenit** [comment]
looks like you have a broken cudacxx env variable

CUDACXX: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin

this is not valid, it should point to a nvcc.exe not it’s folder

did you set it?
please remove it, better to not have it than have a broken one

**Comment by jpoirier1** [comment]
Removed the CUDACXX variable, I think that was left over from another solution I tried...

Finally builds now, thanks so much for all the help!
