### ISSUE TITLE
1000x iteration weights are not saving

### ISSUE THREAD

**Issue by aditya-5842** [AlexeyAB/darknet#7798]
I am training a custom YOLOV4-Tiny model for detecting 7 classes. I have made necessary changes in _*.cfg_ file. The model has trained for more than 6000 iterations. But it is saving only two weight files (i.e. last and best model) in the backup folder. 

I am training the model in Google-Colab.

I am attaching the screenshot for _obj.names_ and _obj.data_. This is the config
[yolov4-tiny-608.cfg](https://github.com/AlexeyAB/darknet/files/6643349/yolov4-tiny-608.cfg.txt) file that I am using to train the model. 

![obj.data](https://user-images.githubusercontent.com/49398685/121796787-44898f00-cc39-11eb-8b29-39aa7360269a.png)
![Screenshot from 2021-06-13 11-18-47](https://user-images.githubusercontent.com/49398685/121796789-45babc00-cc39-11eb-84e6-a1a585dceec8.png)
![Screenshot from 2021-06-13 11-24-33](https://user-images.githubusercontent.com/49398685/121796885-18bad900-cc3a-11eb-8a72-e4c983e5882c.png)

**Comment by aditya-5842** [comment]
After going through this [issue](https://github.com/AlexeyAB/darknet/issues/7104), it is clear to me why it is happening.
When _**max_batches**_ will be greater than 10,000, a new model will be saved every 10,000 iterations.

https://github.com/AlexeyAB/darknet/blob/master/src/detector.c#L385-L386

**Comment by lamnguyenkhoa** [comment]
I think this issue can be closed. @aditya-5842

**Comment by aditya-5842** [comment]
Yes.
