### ISSUE TITLE
Training csresnext50.cfg with multi-gpus crashed randomly

### ISSUE THREAD

**Issue by erikguo** [AlexeyAB/darknet#7799]
CUDA: 11.2 cuDNN: 8.1.1.33  cuDNN_HALF=1, OPENCV=1, GPU: RTX3090 24G  x 4
OPENCV 4.4.0    Ubuntu 16.04

When I trained csresnext50.cfg with multi-gpus, it always crashed randomly to reboot the machine.  Sometimes it crashed after 1-2 hours, sometimes it crashed after 1-2 days. I didn't find any logs left in the machine and didn't find the coredump.

Could you please give me some suggestions to do the debug to find out the root cause ?

Thank you very much!

@AlexeyAB

**Comment by erikguo** [comment]
After one month test, we confirmed that when training with 4 GPUs,  the server will reboot randomly （Maybe after one hour, or after one day).  But when training with 2 GPUs, the trainging is very stable.

Are there some ideas to debug these cases?

Thanx 

@AlexeyAB

**Comment by stephanecharette** [comment]
Upgrade your power supply.  Mine would reboot as well.  Was caused by brownouts.  Once I upgraded the power supply, problem went away.  This was about 2 years ago now.

**Comment by erikguo** [comment]
Thank you. After I update the latest commits, it fixes the random reboot. I've already tested for three days.
