### ISSUE TITLE
how to change demo avi bounding box width?

### ISSUE THREAD

**Issue by LiaoZihZrong** [AlexeyAB/darknet#7805]
i edit demo.c
but i can't find the key word to change boufing box widith?
i want  save the test.avi that it's bounding box more bold. (or it word more bold)

**Comment by Micky-123** [comment]
> i edit demo.c
> but i can't find the key word to change boufing box widith?
> i want save the test.avi that it's bounding box more bold. (or it word more bold)

I think for  'test' scenario for images - it is in draw_detections_v3() function in src/image.c file. I am not sure if for 'demo' also it take the same path or not.  But probably good to check in the above function around the place where draw_box_width() is called.

**Comment by stephanecharette** [comment]
If you want to use DarkHelp, it has a property called "line_thickness": https://www.ccoderun.ca/DarkHelp/api/classDarkHelp.html#ad2df5d21d21cef8957ddf37f14a4f7cd
Scroll through that page to see what can be customized.

**Comment by haviduck** [comment]
to just make the rectangle thicker, change 8 to 14 for example here

https://github.com/AlexeyAB/darknet/blob/00b8e29b6802cc085e30f64b48f4a693e6019235/src/image_opencv.cpp#L1005

**Comment by LiaoZihZrong** [comment]
thank you all!
i use all your following 
and the web https://hackmd.io/@ZZ/SylrOgwsd
and i success~
thank you ~
