### ISSUE TITLE
Train own dataset label.txt location

### ISSUE THREAD

**Issue by 89douner** [AlexeyAB/darknet#781]
Below command is "train-command", right?
./darknet detector train cfg/voc.data cfg/yolov3-voc.cfg darknet53.conv.74

I just wonder that how do we know where labels.txt files are when this model is trained.
That means that to train this model, the model has to know 'labels.txt' location including " " information. But, above command doesn't include the information.

**Comment by Jacky3213** [comment]
@89douner  In train command, now let us have a look at the voc.data . It maybe:
train = voc.txt
In voc.txt ,for example, it maybe:
d:/JPEGImages/01.jpg
d:/JPEGImages/02.jpg
...

When training, the program loads the file(cfg/voc.data cfg/yolov3-voc.cfg darknet53.conv.74), in data.c there is func load_data_detection. In load_data_detection there is func fill_truth_detection. Just read it, we find that it can replace the JPEGImages with labels,(JPEGImages  and labels all under the same folder). So it is how the program finds the labels. 

Forgive my poor English.

**Comment by AlexeyAB** [comment]
If images are in the folder: `VOCdevkit\VOC2012\JPEGImages`
Then labels are in the folder: `VOCdevkit\VOC2012\labels`

Is used this code: https://github.com/AlexeyAB/darknet/blob/cda8171feb76bcb405350fd8341d42a0300e2f4b/src/data.c#L301

**Comment by 89douner** [comment]
I just trained my dataset.
As you can see below, image files, label files, train.txt, and test.txt are in the same location ('darknet/data/images')
![2018-05-10 22-00-46](https://user-images.githubusercontent.com/31752297/39870803-9e497eb8-549d-11e8-9f4c-989ed88813c7.png)

Also, I made obj.data (related to own training data) like below
![2018-05-10 22-03-47](https://user-images.githubusercontent.com/31752297/39870923-07f57aa6-549e-11e8-91a1-35548243d7cc.png)

When I inserted below command
![6 2018-05-10 18-17-57](https://user-images.githubusercontent.com/31752297/39870968-315682b4-549e-11e8-90a3-21452ca8353d.png)

I don't know Region 82, Region 94, Region 106 mean 
![6 2018-05-10 18-17-57](https://user-images.githubusercontent.com/31752297/39870991-4c01312c-549e-11e8-95ee-97ff60d0a66d.png)
Also, I don't know whether the model is being trained.

I wanna train the model to detect two objects, penguin, and airplane. I just made Images folder including 10 penguins and 10 airplanes. I know there are a small number of images. but, Is it possible not to detect any objects when I detect a train_image as below?
![2018-05-10 22-14-00](https://user-images.githubusercontent.com/31752297/39871353-78bb65a6-549f-11e8-8f57-c7aa31ed87ec.png)
![2018-05-10 22-14-52](https://user-images.githubusercontent.com/31752297/39871383-95b989d0-549f-11e8-8bdc-59ba54e97aca.png)

**Comment by AlexeyAB** [comment]
Train at least 2000 iterations.
If you can't detect anything, try to use `-thresh 0.01` flag for detection.

----

> I don't know Region 82, Region 94, Region 106 mean

Read more: https://github.com/AlexeyAB/darknet/issues/636#issuecomment-381400954

> Region 82 - index of current [yolo]-layer (in the default yolov3.cfg there are 3 yolo layers: 82, 94, 106)

**Comment by 89douner** [comment]
I changed my own model into voc model as follow official site because I think that the number of training images is small. 
But, when I trained VOC model, also I got nan average loss score after 727 iterations as below. 
![2018-05-11 00-41-41](https://user-images.githubusercontent.com/31752297/39878753-183c7d40-54b4-11e8-8acf-9c1c5b2b5bea.png)

Also, after about 500 iterations, avg loss score increased.
![3 2018-05-11 00-45-57](https://user-images.githubusercontent.com/31752297/39879065-d69f76de-54b4-11e8-9a58-80c8952a9e53.png)

In addtion, when I applied  -thresh 0.01, the result is same.
when I applied -thresh 0, the endless loop was made as below

![2018-05-11 00-48-57](https://user-images.githubusercontent.com/31752297/39879300-73b27f8e-54b5-11e8-9046-8bf802b63c64.png)

I think that that's something wrong.. is there any problem?

**Comment by AlexeyAB** [comment]
* Do you use this repo?
* Check your dataset using: https://github.com/AlexeyAB/Yolo_mark
* Remove `burn_in=1000` from your cfg-file. And train from the begining - about 2000 iterations

**Comment by dexception** [comment]
@AlexeyAB I am also facing the same issue. Even after removing burin_in=1000 and waiting for 2000 iterations. Yolov3 is showing NaN.

**Comment by Mahibro** [comment]
@dexception Did you resolve the issue?
