### ISSUE TITLE
Problem in Installation darknet with both CMAKE and build.ps1

### ISSUE THREAD

**Issue by JeremySOfficial** [AlexeyAB/darknet#7810]
Hi, Im using CMAKE  to build darknet and apparently it doesn't work (This error is the same as using build.ps1). Error is following:

Darknet_VERSION: 0.2.5.4
VCPKG found: C:\src\vcpkg
Using VCPKG integration
VCPKG_MANIFEST_FEATURES: cuda;cudnn;opencv-cuda
Running vcpkg install
Detecting compiler hash for triplet x64-windows...

The following packages will be built and installed:
    bzip2[core]:x64-windows -> 1.0.8#1
    cuda[core]:x64-windows -> 10.1#7
    cudnn[core]:x64-windows -> 7.6.5#4
    ffmpeg[avcodec,avdevice,avfilter,avformat,core,gpl,postproc,swresample,swscale]:x64-windows -> 4.4#4
    giflib[core]:x64-windows -> 5.1.4-6
    hdf5[core,szip,zlib]:x64-windows -> 1.12.0#3
    leptonica[core]:x64-windows -> 1.80.0#2
    libarchive[bzip2,core,libxml2,lz4,lzma,openssl,zstd]:x64-windows -> 3.4.3#6
    libiconv[core]:x64-windows -> 1.16#8
    libjpeg-turbo[core]:x64-windows -> 2.0.6
    liblzma[core]:x64-windows -> 5.2.5#2
    libpng[core]:x64-windows -> 1.6.37#15
    libwebp[core,nearlossless,simd,unicode]:x64-windows -> 1.1.0#3
    libxml2[core]:x64-windows -> 2.9.10#7
    lz4[core]:x64-windows -> 1.9.3
    opencv[contrib,core,cuda,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.1
    opencv4[contrib,core,cuda,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.1#1
    openjpeg[core]:x64-windows 
-> 2.3.1#4
    openssl[core]:x64-windows -> 1.1.1k#5
    protobuf[core]:x64-windows -> 3.15.8#2
    pthreads[core]:x64-windows -> 3.0.0#9
    quirc[core]:x64-windows -> 1.1#2
    stb[core]:x64-windows -> 2020-09-14
    szip[core]:x64-windows -> 2.1.1#7
    tesseract[core]:x64-windows -> 4.1.1#8
    tiff[core,jpeg,lzma,zip]:x64-windows -> 4.3.0
    vcpkg-cmake[core]:x64-windows -> 2021-02-28#3
    vcpkg-cmake-config[core]:x64-windows -> 2021-05-22
    vcpkg-pkgconfig-get-modules[core]:x64-windows -> 2021-04-02#1
    xxhash[core]:x64-windows -> 0.8.0#1
    zlib[core]:x64-windows -> 1.2.11#10
    zstd[core]:x64-windows -> 1.4.9
Using cached binary package: C:\Users\User\AppData\Local\vcpkg\archives\3f\3f166d8ba84cc3a7ee2318cc31b69b025b3535a4.zip

Using cached binary package: C:\Users\User\AppData\Local\vcpkg\archives\d1\d10c206fcbb5b525fb17dfa2bcd81c640a1d5499.zip

Using cached binary package: C:\Users\User\AppData\Local\vcpkg\archives\ec\eca0244d0fb3474bf67eb2443b4ef068344f94b8.zip

Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\31\31f1a5f459ce973c40e23880c6dade0a62304615.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\39\3937bfe5582bcbef66f52b4a97426f2dd758af9b.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\50\509f699cb9cf73923351e19363332ac6e2a34e80.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\2f\2f6d6c7480544b9bd83ae3ad0aa8136b4fdc0815.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\10\101b6be051e777bc82f8e853f1bb29d60a40044d.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\0e\0e0b543da6a01f7c49efabd2b84a6f4801df61c2.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\d3\d33972a7ef3fea38f4d777598201cb74b2dc8dd0.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\f4\f473202bdc372224c9b8b3c2db4f3d87e74e26d3.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\fb\fbc4b7288a0d1ee13c37c2fcf30dda5025102bdd.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\8b\8b8c65e619c325a1079eace49877da57c30062c1.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\0c\0c3fdb4d4852ddea5b4e53cc0f509b7266f5595d.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\ca\ca181e10506c83408f823170fef767c3e62e00de.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\ed\edfc80aba8275b37c110f1a9b82052255466fd4d.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\63\636f8722e51e01cf79a6ad28b6b0f934b7806b33.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\7f\7fb9d29a3325096b5d00ff35
7bd26ec37f56f717.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\ea\ea36814887828411051c151f758b9332e6b04a1a.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\b2\b2c579fcf90d78f395240636a26cd7c1cd5097f9.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\64\64c9845ad77c19fa25c5e81c244cae4232cdae26.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\77\779d16a95380a901c1e34edbfb046cd103a213b0.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\10\1043f1fd13ad3dd33a9bb4c3df66eb52d05ada38.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\c7\c7e7304ca8cd2e8bb66f31a722505814e8473fb4.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\8a\8a072afdd950f26fc65fecff375bfd8493e38096.zip
Could not locate cached archive: C:\
Users\User\AppData\Local\vcpkg\archives\02\027468160040a1f6dcb2508ce3ed58d0c5126aa2.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\aa\aab0da7b3a7c4405225ea481cbe1677905622576.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\e8\e89c7eec28315f6f0966693a5d59e9cafef69e73.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\37\37d359770ad82b0a1aa0b1a33e8676e93f26b4d3.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\43\431a92e80c7a0d5ee2ba6c524395f8fbc9690805.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\c9\c9066446dc8821be399a6ba00d1b300691e406c6.zip
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\57\57afaed8180ee56a7a8688333fd7973ba3477828.zip
Starting package 1/32: pthreads:x64-windows
Building package pthreads[core]:x64-windows...
B
uilding package pthreads[core]:
x64-windows... done
Installing package pthreads[core]:x64-windows...
Installing package pthreads[core]:x64-windows... done
Elapsed time for package pthreads:x64-windows: 61.98 ms
Starting package 2/32: stb:x64-windows
Building package stb[core]:x64-windows...
Building package stb[core]:x64-windows... done
Installing package stb[core]:x64-windows...
Installing package stb[core]:x64-windows... done
Elapsed time for package stb:x64-windows: 38.26 ms
Starting package 3/32: cuda:x64-windows
Building package cuda[core]:x64-windows...
Building package cuda[core]:x64-windows... done
Installing package cuda[core]:x64-windows...
Installing package cuda[core]:x64-windows... done
Elapsed time for package cuda:x64-windows: 9.144 ms
Starting package 4/32: cudnn:x64-windows
Building package cudnn[core]:x64-windows...

-- Found CUDA V10.1.243
-- CUDNN_INCLUDE_DIR: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/cuda/include
-- CUDNN_LIBRARY: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64/cudnn.lib
CMake Error at ports/cudnn/portfile.cmake:69 (message):
  Please download CUDNN from official sources (such as
  https://developer.nvidia.com/rdp/cudnn-download ) and extract the zip into
  your CUDA_TOOLKIT_ROOT (C:/Program Files/NVIDIA GPU Computing
  Toolkit/CUDA/v10.1).  (For example: tar.exe -xvf
  cudnn-11.2-windows-x64-v8.1.1.33.zip --strip 1 --directory "C:/Program
  Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1"
Call Stack (most recent call first):
  scripts/ports.cmake:139 (include)

Error: Building package cudnn:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cudnn:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae7
6681c27b0c1be9d9

Additionally, attach any relevant sections from the log files above.

Running vcpkg install - failed
CMake Error at C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake:807 (message):
  vcpkg install failed.  See logs for more information:
  C:\src\darknet\build\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/CMakeDetermineSystem.cmake:123 (include)
  CMakeLists.txt:103 (project)

Configuring incomplete, errors occurred!

Cuda version is 10.1 and Cudnn is 7.5. I have installed and copy paste the cudnn file into appropriate folder. I also believed that VCPKG is the updated version

[vcpkg-manifest-install.log](https://github.com/AlexeyAB/darknet/files/6671092/vcpkg-manifest-install.log)

**Comment by stephanecharette** [comment]
Like I wrote to you on Discord, or if you had searched for the error here in github, your version of cuda is too old.  Darknet requires 10.2 or newer.

**Comment by stephanecharette** [comment]
> Cuda version is 10.1 and ...

See issues #7486, #7724, #7452, #7486, #7545, and #7439 for other issues related to CUDA versions older than 10.2.

Also see the darknet project readme which states:

![image](https://user-images.githubusercontent.com/5061352/122433136-ca178280-cf4a-11eb-8be7-d262362ba683.png)

**Comment by cenit** [comment]
also, first and foremost please read the error itself

it says

```
Please download CUDNN from official sources (such as
https://developer.nvidia.com/rdp/cudnn-download ) and extract the zip into
your CUDA_TOOLKIT_ROOT (C:/Program Files/NVIDIA GPU Computing
Toolkit/CUDA/v10.1)
```

**Comment by cenit** [comment]
Lap, as @stephanecharette said, later you would have also discovered that you need cuda 10.2 (and a compatible cudnn too)
