### ISSUE TITLE
Clean Instalation on a Windows 10, Visual Studio 2019 Community environment

### ISSUE THREAD

**Issue by lglovera** [AlexeyAB/darknet#7842]
Hi there, today i attempted to compile DarkNet in order to use it on an OpenCV project i am working.

I tried to follow the install instructions for Windows Environments but i keep getting the same error and i dont have much clues as to what might be happening.

I recently tried to install the english language pack as stated in the instalation instructions.

![image](https://user-images.githubusercontent.com/25929780/123720250-048df300-d85a-11eb-9a79-94927b98ba37.png)

Could it be that i am missing some requirement?

**Comment by sg12056** [comment]
try disabling Ninja with flag -DoNotUseNinja.

**Comment by cenit** [comment]
that should not be the problem because the script is supposed to download automatically a portable ninja if not found

can you please share the file D:\yolo\darknet\build_release\vcpkg-manifest-install.log?

**Comment by gavinnn101** [comment]
Uninstall the CMake release candidate and install the latest stable(3.20.5) release instead.

**Comment by lglovera** [comment]
> Uninstall the CMake release candidate and install the latest stable(3.20.5) release instead.

Will uninstall my current version of CMake and install version 3.20.5, as soons as i am able to try it will share the results.

**Comment by lglovera** [comment]
![image](https://user-images.githubusercontent.com/25929780/124190359-81a6ab80-da98-11eb-8381-c7288c962790.png)

The build was succesful, thx to everyone.
Seems there is a discrepancy between the RC and the Stable version of CMake.

**Comment by CatHas4Paw** [comment]
This solution dont work for me. I have the same output as @lglovera. 
Can anyone help me?

**Comment by cenit** [comment]
please show full logs from build
