### ISSUE TITLE
Is YOLOv4-csp is supported by OpenCV 4.5.2 ?

### ISSUE THREAD

**Issue by kgksl** [AlexeyAB/darknet#7843]
Is yolov4-csp is supported by OpenCV? I tried to performed inference with provided weight files  for yolov4-csp with Opencv version (4.5.2). The results I got is not garbage, but seemed like the confidence scores were very high (incorrect) and thus resulted in a large number of predictions above confidence threshold = 0.001.

I was following this thread [ https://github.com/opencv/opencv/issues/18975#issuecomment-745012567 ](url)
I am new to Darknet andOpenCV, and wasn't completely sure if only yolov4-mish  is not supported or all scaled yolov4 models are not supported. If this issue gets solved the changes will be released with 3.4.15 and will propagate to 4.5.3? I am new to OpenCV and I was under the impression OpenCV 3.x doesn't support CUDA so not clear to me if this change will solve/provide support for 4.x if its missing support for scaled models. I apologize in advance for my lack of knowledge, and hope someone can explain or provide me some reference. Thanks alot

**Comment by akashAD98** [comment]
@kgksl  have you solved the problem?

**Comment by kgksl** [comment]
@akashAD98 
as I undertand YOLOv4-csp is not yet supported by OpenCV
https://github.com/opencv/opencv/issues/18975#issuecomment-773886413
