### ISSUE TITLE
Current master darknet is more GPU memory consuming per model

### ISSUE THREAD

**Issue by folkien** [AlexeyAB/darknet#7847]
* description of a bug

After updating darknet from 4f794aa15265d2a068d9f452e5efd9d7a3574524 to 86ced7151a71c05fab57bc14f77d6a4bb97b9ee6 I have observed more memory consuming of my YOLOv4 model (cfg and weights doesn't changed). Before update i could load 3x models per GPU (RTX2060). Now i can load only two and memory usage is similar in both cases (around 75%). 
But to by honest I doesn't observed lower GPU processor usage so from my point of view (more FPS) it's not as problematic as it could be. :smile: 

    * what command do you use?
I've use my own python code with darknet .so python wrapper.

    * do you use Win/Linux/Mac?
Ubuntu 18.04 LTS

    * attach screenshot of a bug with previous messages in terminal
TODO
    * in what cases a bug occurs, and in which not?
 Everytime with newer darknet library.

    * if possible, specify date/commit of Darknet that works without this bug
Revision 4f794aa15265d2a068d9f452e5efd9d7a3574524

    * show such screenshot with info
TODO

**Comment by AlexeyAB** [comment]
Try the latest commit, I fixed a bug recently.

**Comment by folkien** [comment]
Ok, tried. Memory usage returned back to previous values.
