### ISSUE TITLE
How to use python API ?

### ISSUE THREAD

**Issue by JayantGoel001** [AlexeyAB/darknet#7854]
If something doesn’t work for you, then show 2 screenshots:
1. screenshots of your issue
The actual time shown by yolov4-csp in the following image is 36.0330 milliseconds but the actual time that it took was 3.627533435821533 seconds.
![image](https://user-images.githubusercontent.com/54479676/124373321-08cd6c80-dcaf-11eb-9b8f-1d1a3921f785.png)

2. screenshots with such information
![image](https://user-images.githubusercontent.com/54479676/124373357-59dd6080-dcaf-11eb-9b65-296056f03e60.png)

I used this code in colab for inferencing on GPU.
```
./darknet detector test cfg/coco.data cfg/yolov4.cfg yolov4.weights data/dog.jpg
 CUDA-version: 10000 (10000), cuDNN: 7.4.2, CUDNN_HALF=1, GPU count: 1
 CUDNN_HALF=1
 OpenCV version: 4.2.0
 0 : compute_capability = 750, cudnn_half = 1, GPU: GeForce RTX 2070
net.optimized_memory = 0
mini_batch = 1, batch = 8, time_steps = 1, train = 0
   layer   filters  size/strd(dil)      input                output
   0 conv     32       3 x 3/ 1    608 x 608 x   3 ->  608 x 608 x  32 0.639 BF
```

If you do not get an answer for a long time, try to find the answer among Issues with a Solved label: https://github.com/AlexeyAB/darknet/issues?q=is%3Aopen+is%3Aissue+label%3ASolved

**Comment by agjunyent** [comment]
Try to run it multiple times. The first time it needs to load everything into memory (cuda, model, weights, etc.

I also recommend not running the cli interface, as each time it terminates, it frees everything, so when you run it again it needs to load all the stuff again

**Comment by JayantGoel001** [comment]
> Try to run it multiple times. The first time it needs to load everything into memory (cuda, model, weights, etc.
> 
> I also recommend not running the cli interface, as each time it terminates, it frees everything, so when you run it again it needs to load all the stuff again

Hi @agjunyent 
Can you please tell me what are the other approaches to Inference without using CLI?
And How can I run it multiple times without losing old loaded stuff?

**Comment by stephanecharette** [comment]
> Can you please tell me what are the other approaches to Inference without using CLI?
> And How can I run it multiple times without losing old loaded stuff?

Use the API, not the CLI.

- There is the original C API in libdarknet.so / darnet.dll.
- There is the old C++ API in the YOLO dll.
- There is a newer C++ API called DarkHelp.  (This is what I maintain.)  https://www.ccoderun.ca/darkhelp/api/API.html
- There is the Python API in the root directory of the darknet project.
- There is OpenCV's CUDNN module, which is available from C++ and Python as well.

**Comment by JayantGoel001** [comment]
> > Can you please tell me what are the other approaches to Inference without using CLI?
> > And How can I run it multiple times without losing old loaded stuff?
> 
> Use the API, not the CLI.
> 
> * There is the original C API in libdarknet.so / darknet.dll.
> * There is the old C++ API in the YOLO dll.
> * There is a newer C++ API called DarkHelp.  (This is what I maintain.)  https://www.ccoderun.ca/darkhelp/api/API.html
> * There is the Python API in the root directory of the darknet project.
> * There is OpenCV's CUDNN module, which is available from C++ and Python as well.

Hi @stephanecharette 
Thank a lot for above methods but I ran into a small issue.
Where can I get libdarknet.so file I am not able to see it even after running make command.
I want to run it in python and that's the issue I got.
![image](https://user-images.githubusercontent.com/54479676/124444420-36441400-dd9c-11eb-947c-a9bd3ebb5ec2.png)
But it didn't worked as expected.

**Comment by agjunyent** [comment]
Have you compiled with the LIBSO option set to 1?

LIBSO=1

Otherwise the shared object is not built

**Comment by JayantGoel001** [comment]
> Have you compiled with the LIBSO option set to 1?
> 
> LIBSO=1
> 
> Otherwise the shared object is not built

Ya it worked.
but now I am getting this issue.
![image](https://user-images.githubusercontent.com/54479676/124447772-51fce980-dd9f-11eb-8a09-6beb5f7188f6.png)

I ran this command 
```!python darknet_images.py --input data/person.jpg --weights yolov4-csp.weights --config_file ./cfg/yolov4.cfg  --ext_output```

**Comment by cenit** [comment]
are you running on a remote system?
looks like you don't have a X server available. Did you connect with ssh -X ?

**Comment by cenit** [comment]
@stephanecharette there is no deprecate c++ dll / classic c dll, please do not create confusion. And do not spam your personal tools here thanks

**Comment by JayantGoel001** [comment]
> are you running on a remote system?
> looks like you don't have a X server available. Did you connect with ssh -X ?

I am running it on colab but i am getting any detection

**Comment by elias-work** [comment]
The best place to see how to use the Python API is probably here: https://github.com/AlexeyAB/darknet/blob/master/darknet_images.py#L100

Note that it loads darknet.py in the same directory, which looks for libdarknet.so, so you need to have compiled with LIBSO=1 and it needs to be in a suitable location.

**Comment by JayantGoel001** [comment]
> The best place to see how to use the Python API is probably here: https://github.com/AlexeyAB/darknet/blob/master/darknet_images.py#L100
> 
> Note that it loads darknet.py in the same directory, which looks for libdarknet.so, so you need to have compiled with LIBSO=1 and it needs to be in a suitable location.

Ya but when I ```print(detection)``` after line number 113 It gave me empty list

**Comment by stephanecharette** [comment]
> @stephanecharette there is no deprecate c++ dll / classic c dll, please do not create confusion. And do not spam your personal tools here thanks

I'm not creating confusion anywhere.  There is the original C API, which is the core of the Darknet framework.  There is the C++ wrapper API which hasn't been updated in 2 or 3 years.  Neither of which have any documentation.  And there is the C++ API which I fully support and is documented.  It is as simple as that.  Everyone is free to use the API they want to use.  Just like you, I support Darknet, and I'm not "spamming" anything.  If you don't want to use it, you are free to use one of the other APIs.

**Comment by elias-work** [comment]
> > The best place to see how to use the Python API is probably here: https://github.com/AlexeyAB/darknet/blob/master/darknet_images.py#L100
> > Note that it loads darknet.py in the same directory, which looks for libdarknet.so, so you need to have compiled with LIBSO=1 and it needs to be in a suitable location.
> 
> Ya but when I did `print(detection)` after line number 113 It gave me an empty list

Well, that script is essentially a minimal example of using the Python API, so your problem is reduced from not knowing where to learn the API to fixing that bug. Try to run the full script from CLI and see if it yields any detections, and go from there.
