### ISSUE TITLE
Error in load_data_detection() - OpenCV  Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by seabass1217** [AlexeyAB/darknet#7860]
Hi All,

I'm receiving the follow error when trying to train: 

Error in load_data_detection() - OpenCV  Segmentation fault (core dumped)  

My system:
OS: Ubuntu 20.04
GPU: Quardro RTX 6000

Command is in the command.png file
Error is output-1 and output-2 files

Any help is appreciated.
Thanks,

![command](https://user-images.githubusercontent.com/86954802/124449565-95306b80-dd51-11eb-8ffc-878123af4fc5.png)
![output-1](https://user-images.githubusercontent.com/86954802/124449566-95306b80-dd51-11eb-8ae4-1245e9884513.png)
![output-2](https://user-images.githubusercontent.com/86954802/124449567-95306b80-dd51-11eb-88c7-9248b8b48b6e.png)

**Comment by seabass1217** [comment]
Hi All,

I'm getting "Error in load_data_detection() - OpenCV  Segmentation fault (core dumped)" when training.  

My system:
OS: Ubuntu 20.04 
GPU: Quadro 6000

The training command is below  in command.png file.
The output and error  is output-1 and output-1 .png files.

Any help is appreciated.
Thanks

![command](https://user-images.githubusercontent.com/86954802/124448599-a167f900-dd50-11eb-806e-11803d72ebb3.png)
![output-1](https://user-images.githubusercontent.com/86954802/124448602-a167f900-dd50-11eb-90ed-890a29f09f8e.png)
![output-2](https://user-images.githubusercontent.com/86954802/124448603-a2008f80-dd50-11eb-80bf-fd49298c73b3.png)

**Comment by stephanecharette** [comment]
I strongly recommend you use something like DarkMark to verify your annotations, and to build your Darknet project files correctly.

See:  https://github.com/stephanecharette/DarkMark#what-is-darkmark

**Comment by seabass1217** [comment]
Thanks for your feedback!  I will look into it.

**Comment by Micky-123** [comment]
> Hi All,
> 
> I'm receiving the follow error when trying to train:
> 
> Error in load_data_detection() - OpenCV Segmentation fault (core dumped)
> 
> My system:
> OS: Ubuntu 20.04
> GPU: Quardro RTX 6000
> 
> Command is in the command.png file
> Error is output-1 and output-2 files
> 
> Any help is appreciated.
> Thanks,
> 
> ![command](https://user-images.githubusercontent.com/86954802/124449565-95306b80-dd51-11eb-8ffc-878123af4fc5.png)
> ![output-1](https://user-images.githubusercontent.com/86954802/124449566-95306b80-dd51-11eb-8ae4-1245e9884513.png)
> ![output-2](https://user-images.githubusercontent.com/86954802/124449567-95306b80-dd51-11eb-88c7-9248b8b48b6e.png)

This is because of the .txt files that are present in your training dataset. I recently mistakenly put one .txt file in my training dataset and faced similar issue. Once I removed the .txt file from my training dataset, it was fine.

**Comment by seabass1217** [comment]
Thanks @Micky-123 and @stephanecharette 
My dataset was corrupt but ended up re-building darknet and opencv.
