### ISSUE TITLE
why is cmake_minimum_required 3.18

### ISSUE THREAD

**Issue by StephanHasler** [AlexeyAB/darknet#7874]
I'm wondering why the required cmake version is set to 3.18?
I'm working on ubuntu 20.04. There the standard cmake version is 3.16.
And darknet compiles fine with 3.16.

Please consider to reduce the required version, if possible.
This could increase the number of persons that can use the code without modification or without having to update their cmake.

**Comment by cenit** [comment]
we need cmake 3.18 because of the newer cuda integration with cmake.

it’s not possible it worked for you in cmake 3.16, and also updating cmake is very easy. Can you give more details on what you did to make it work on 3.16? you had to disable everything related to cuda at the minimum (or rewrite using older syntax, like what we had in the past)

**Comment by StephanHasler** [comment]
It worked basically out of the box.
In the CMakeLists.txt I changes 3.18 to 3.16, and I had to set few environment variables.
 
Im using cuda11.21 and cudnn 8.2 on ubuntu 20.04 with cmake 3.16.3.
My $CUDA_HOME is pointing to my cuda installation, but I have it in a custom folder not the system one.
The LD_LIBRARY_PATH is pointing to $CUDA_HOME/lib64
My cudnn installation is inside cuda. Here was the problem that FindCUDNN.cmake could not find it.
It uses these hints: HINTS ${CUDA_HOME} ${CUDA_TOOLKIT_ROOT_DIR} $ENV{cudnn} $ENV{CUDNN}.
I just did:
export CUDNN=$CUDA_HOME
Then he said he found Cuda and cudnn and I could compile it.

I'm not sure why he searches for cudnn under ${CUDA_HOME} and not $ENV{CUDA_HOME}.
Maybe the newer versions of cmake set the internal ${CUDA_HOME} variable.

The docu of cmake says:
cuda support for check_language/enable_language was added in 3.8
https://cmake.org/cmake/help/latest/command/enable_language.html

There is a further issue with FindCUDNN.cmake
I tries to get the version from the file cudnn.h. It reports (found version "?")
But this information is now in cudnn_version.h. It reports (found version "8.2.0")
But in both cases it compiles fine.

**Comment by StephanHasler** [comment]
I attached the logs for the config and build phase:
[darknet_build.txt](https://github.com/AlexeyAB/darknet/files/6799758/darknet_build.txt)
[darknet_config.txt](https://github.com/AlexeyAB/darknet/files/6799759/darknet_config.txt)

**Comment by cenit** [comment]
but CMAKE_CUDA_ARCHITECTURES is new from CMake 3.18
https://cmake.org/cmake/help/git-stage/variable/CMAKE_CUDA_ARCHITECTURES.html (look for the first line)

You are right about the FindCUDNN module, which is not up-to-date here on darknet repo. I already have a newer version but didn't push it here

**Comment by cenit** [comment]
and in fact you have an empty field there, which means that you are not building for any particular compute capability.
I don't know how the final binary works in this way, might be ok-ish in your config or even totally unable to run on your GPU.
Sorry but I think we don't have time to maintain scripts for older cmake versions, considering how easy it is to update it

**Comment by StephanHasler** [comment]
You are right.
I assume CMAKE_CUDA_ARCHITECTURES is not set for me and therefore he reports "No half precision".
And right, he does not build it for a particular compute capability.
I overlooked this.

I should upgrade! Thank you for your time.

**Comment by cenit** [comment]
> There is a further issue with FindCUDNN.cmake
> I tries to get the version from the file cudnn.h. It reports (found version "?")
> But this information is now in cudnn_version.h. It reports (found version "8.2.0")
> But in both cases it compiles fine.

can you please tell me if #7891 fixes the cudnn version also for you? thanks

**Comment by StephanHasler** [comment]
The version is now detected correctly.

But why did you rename CUDNN_VERSION to _CUDNN_VERSION?

Renaming it to _CUDNN_VERSION has the effect that the version is not printed, I get:
-- Found CUDNN: /hri/sit/latest/External/cuda/11.21/focal64/include
Changing it to CUDNN_VERSION I get:
-- Found CUDNN: /hri/sit/latest/External/cuda/11.21/focal64/include (found version "8.2.0")

**Comment by StephanHasler** [comment]
You now changed the hints for cudnn to:
HINTS $ENV{CUDA_PATH} $ENV{CUDA_TOOLKIT_ROOT_DIR} $ENV{cudnn} $ENV{CUDNN} $ENV{CUDNN_ROOT_DIR} /usr/include

I also still need to do:
export CUDNN=$CUDA_HOME
as CUDA_HOME is not considered in the hints.

Is CUDA_HOME deprecated?
To find cuda it seems still be used and sufficient.

**Comment by StephanHasler** [comment]
Are $ENV{cudnn} $ENV{CUDNN} somehow official. If not you should consider to remove/rename them.
Especially $ENV{cudnn} looks like a hack.

$ENV{CUDNN_PATH}  would correspond to the cuda variables.

**Comment by StephanHasler** [comment]
On this site:
https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html
$(CUDA_HOME) is used for certain examples.
It looks like it is the common variable for ubuntu.
You should consider to add it to the hints.

**Comment by cenit** [comment]
thanks for your suggestions. please post in the PR thread in the future, so that i do not loose track of them (i wrote to you here only to make you aware of the PR)
