### ISSUE TITLE
Should I resize BB for training?

### ISSUE THREAD

**Issue by Bacus96** [AlexeyAB/darknet#7883]
I believe Darknet automatically resizes images for training. Does it do the same for associated Bounding Boxes?

**Comment by stephanecharette** [comment]
Darknet does indeed resize images to exactly match the network size.  There is a cost to do this, described here:

https://www.ccoderun.ca/programming/darknet_faq/#time_to_train

Resizing the bounding boxes does not make sense.  The bounding boxes are already normalized:  https://www.ccoderun.ca/programming/darknet_faq/#darknet_annotations

**Comment by Bacus96** [comment]
Thank you. I have BB coordinates for X min, X Max, Y Min, Y Max for a custom dataset (essentially the corners of a BBox. How would I convert these into Yolo format? I currently use the following formula:
x = xmin
y = ymin
w = xmax - xmin
h = ymax - ymin

Is this correct? Since my network loss remains high after a large number of epochs.

**Comment by stephanecharette** [comment]
No, that is not correct:  https://www.ccoderun.ca/programming/darknet_faq/#darknet_annotations

Also see the troubleshooting section here:  https://www.ccoderun.ca/programming/darknet_faq/#tldr
