### ISSUE TITLE
Scaled-YOLOv4:training error when i set flag random=1 in my .cfg-file

### ISSUE THREAD

**Issue by only-zzx** [AlexeyAB/darknet#7889]
I reand how to improve object detection and change random=1 in my .cfg-file
then the error :Assertion "0"failed happend,
i think this error about the networksize,during upsample
anyone can help me about that?

    * show such screenshot with info
![2](https://user-images.githubusercontent.com/65695179/125222917-79066e80-e2fd-11eb-803a-a8acc4534b36.jpg)

![企业微信截图_1](https://user-images.githubusercontent.com/65695179/125222786-4197c200-e2fd-11eb-9172-54f5c4296f57.png)

**Comment by AlexeyAB** [comment]
Yes, these models are not suitable for training with random=1, because it will require a lot of GPU-memory, and decreasing mini-batch size will reduce accuracy a lot.

**Comment by only-zzx** [comment]
> Yes, these models are not suitable for training with random=1, because it will require a lot of GPU-memory, and decreasing mini-batch size will reduce accuracy a lot.

ok,thanks for your answer
