### ISSUE TITLE
yolv3-tiny model gets 2FPS on jetson nano

### ISSUE THREAD

**Issue by Choikyungho9** [AlexeyAB/darknet#7900]
I created a custom model that was trained 10000 times on the yolov3-tiny model.

But when I run darknet I was able to get 2 frames.

The operation was done in jetson-nano using Ubuntu 18.04.

Is there any way to speed up FPS of yolov3-tiny on jetson nano?

How do I reduce the screen size? 

There is no specific method on how to increase the FPS. Please help.

**Comment by agjunyent** [comment]
To run on Jetson embeded boards you need to use tensorRT. Look for tutorials on how to convert .weights to tensorRT. I follow this other repo:
https://github.com/jkjung-avt/tensorrt_demos

Jetson boards DO NOT use "normal" CUDA, as their GPU's are not meant to be running it, but tensorRT
