### ISSUE TITLE
Executable no output with darknet in Windows compiled with Cmake.

### ISSUE THREAD

**Issue by migvel** [AlexeyAB/darknet#7901]
Hello,

I followed this compilation guide: https://github.com/AlexeyAB/darknet#how-to-compile-on-windows-using-cmake

And it compiled aparently succesfully, I can see the executable darknet.exe, but when I execute in a power shell,
for example:

./darknet.exe detector test cfg/coco.data cfg/yolov4.cfg yolov4.weights data/dog.jpg

Returns no information, any input parametters returns nothing.

Any idea would be very appreacited.
Regards.

**Comment by heiybb** [comment]
I run into exactly the same issue.
Using OpenCV 4.5.3 compile with CUDA support.
cuda_11.4.0_471.11_win10
cudnn cudnn-11.3-windows-x64-v8.2.1.32

**Comment by migvel** [comment]
I think it's related to this #7842 

After installing a previous version of cmake, and cleaning some overlap with env variables,
it compiled successfully with the vcpkg method.

**Comment by jzchenriver** [comment]
I met the same problem.  Do you solve it?

I have installed the cmake 3.20.5, but there were still no output.

**Comment by MollyHoo** [comment]
same problem
