### ISSUE TITLE
about  a "Very small path to the image" problem

### ISSUE THREAD

**Issue by tuteming** [AlexeyAB/darknet#7903]
I run darknet has a
"Very small path to the image" problem
I check this is in data.c line 75.
if (strlen(sequentia_paths[i]) <= 4) printf(" Very small path to the image: %s \n", sequentia_paths[i]);
The training hasn't stopped, but I wonder if this problem affects the training results.

by google, someone give the following answer
=>That's because of the "\n" characters in your label or train list. Check your list and remove empty lines. Specially check the end of the list.

but, I sure this is a wrong answer.
How can I solve this problem?

Thanks.

**Comment by stephanecharette** [comment]
What does the image path look like?  Is it shorter than 4 characters?  Do you have blank lines?

**Comment by tuteming** [comment]
thanks. my problem has solves. 
 Is it shorter than 4 characters? yes this problem.
