### ISSUE TITLE
 Is there any pre-trained weights yolov3-tiny ?

### ISSUE THREAD

**Issue by uday60** [AlexeyAB/darknet#791]
I am sorry if i have missed any links but are there any pre trained weights for yolov3-tiny model ?

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet#pre-trained-models-for-different-cfg-files-can-be-downloaded-from-smaller---faster--lower-quality

yolov3-tiny.cfg (34 MB COCO Yolo v3 tiny) - requires 1 GB GPU-RAM: https://pjreddie.com/media/files/yolov3-tiny.weights

**Comment by AlexeyAB** [comment]
@uday60 Usually we shouldn't take conv-layers before detection-yolo-laeyrs. So we shouldn't take layer-15.
But there is no strict rules, so you can take 21 or 23 layers.

![image](https://user-images.githubusercontent.com/4096485/39926365-aa645e30-5537-11e8-92e7-c02aba5a5c46.png)

**Comment by Haffon** [comment]
This is what I need, thank you.
