### ISSUE TITLE
Python API : Could not find module 'darknet.dll'

### ISSUE THREAD

**Issue by Ciclarion** [AlexeyAB/darknet#7924]
Hello,

I'm having a strange problem :  I'm on windows 10, and i've build without any trouble the project. So i can train the model without any trouble, and the detection works fine too (with darknet.exe detector test data/obj.data yolo-obj.cfg ). So everythings seems to work very well !

Now i would like to be able to use the YoloV4 model from a python script in order to use it in another program. Therefore i'm trying to make the python exemple files working.

However, when i'm using `python darknet_images.py` i'm having the following error :
![image](https://user-images.githubusercontent.com/46332920/126046740-8f94b940-2f81-41b3-bd96-5d6e934f5365.png)

It's strange because : 
1) I know the compilation was done correctly since the darknet.exe train/test works.
2) The dll and the python script are in the same folder
![image](https://user-images.githubusercontent.com/46332920/126046751-de2b3ca1-ec88-4d1f-baa9-66ca2f9bd429.png)
3) Even if i try to indicate the full path, by changing : 
`lib = CDLL("darknet.dll", RTLD_GLOBAL) `to `lib = CDLL("C:/Users/xxxxx/Desktop/darknet/darknet.dll", RTLD_GLOBAL)` i'm having the same error.

Do you have any idea ?

**Comment by m-kalashnikova** [comment]
> Hello,
> 
> I'm having a strange problem : I'm on windows 10, and i've build without any trouble the project. So i can train the model without any trouble, and the detection works fine too (with darknet.exe detector test data/obj.data yolo-obj.cfg ). So everythings seems to work very well !
> 
> Now i would like to be able to use the YoloV4 model from a python script in order to use it in another program. Therefore i'm trying to make the python exemple files working.
> 
> However, when i'm using `python darknet_images.py` i'm having the following error : ![image](https://user-images.githubusercontent.com/46332920/126046740-8f94b940-2f81-41b3-bd96-5d6e934f5365.png)
> 
> It's strange because :
> 
> 1. I know the compilation was done correctly since the darknet.exe train/test works.
> 2. The dll and the python script are in the same folder
>    ![image](https://user-images.githubusercontent.com/46332920/126046751-de2b3ca1-ec88-4d1f-baa9-66ca2f9bd429.png)
> 3. Even if i try to indicate the full path, by changing :
>    `lib = CDLL("darknet.dll", RTLD_GLOBAL) `to `lib = CDLL("C:/Users/xxxxx/Desktop/darknet/darknet.dll", RTLD_GLOBAL)` i'm having the same error.
> 
> Do you have any idea ?

hi @Ciclarion @AlexeyAB !
I'm having the same issue now...
Have you managed to resolve that?
