### ISSUE TITLE
Hope to record the learning rate in real time

### ISSUE THREAD

**Issue by 1027663760** [AlexeyAB/darknet#7927]
@AlexeyAB 
Can you add a learning rate curve to the image? This will make it easier for everyone to better determine the appropriate learning rate
![1](https://user-images.githubusercontent.com/26378634/126086697-6ec7f280-f84c-4eca-b228-6c7204ecfd50.png)

**Comment by stephanecharette** [comment]
What curve exactly are you looking to see?  Your chart should look similar to this if you've setup everything correctly:  
![image](https://user-images.githubusercontent.com/5061352/126087236-2ec5c92c-7d75-4ae6-9293-0cb5f6b270ba.png)

**Comment by 1027663760** [comment]
> What curve exactly are you looking to see? Your chart should look similar to this if you've setup everything correctly:
> ![image](https://user-images.githubusercontent.com/5061352/126087236-2ec5c92c-7d75-4ae6-9293-0cb5f6b270ba.png)

rate
![1](https://user-images.githubusercontent.com/26378634/126087338-d60bdc87-51e9-4530-ac28-fd9449b00133.png)

**Comment by stephanecharette** [comment]
Isn't that a flat line and set as an option in your .cfg file?  E.g., the default for yolov4-tiny is 0.00261, right?

**Comment by lsd1994** [comment]
@stephanecharette Maybe he means learning rate for each iters. It's not hard to implement, just modify draw_chart function.

**Comment by Chitti21** [comment]
@AlexeyAB 
Is there an option to plot the **learning rate vs iteration number** ??
(Either during training or just by reading the parameters of the config file)

**Comment by stephanecharette** [comment]
Isn't the learning rate a static number?

**Comment by Chitti21** [comment]
@stephanecharette Pls check out the "Policy = steps " under Optimizator section on this link [https://github.com/AlexeyAB/darknet/wiki/CFG-Parameters-in-the-%5Bnet%5D-section]

Hope that is useful.
