### ISSUE TITLE
mAP VERY unstable (4%-92%)

### ISSUE THREAD

**Issue by cpsu00** [AlexeyAB/darknet#7942]
I got this weird mAP while training yolov4-tiny-3l on my custom dataset. 
I thought it was cause by augmentations but reducing them still got unstable results. 
This also happens when I train yolov4 and yolov4-csp.
Any help will be wonderful! Thank you!

![98](https://user-images.githubusercontent.com/85643374/126912193-caa47d06-9410-46e6-a3e8-e6b2a8c8cbe3.png)

My config
[cfg.txt](https://github.com/AlexeyAB/darknet/files/6874501/cfg.txt)

**Comment by lsd1994** [comment]
How many images do you have in your dataset?

**Comment by abhigoku10** [comment]
@cpsu00  @WongKinYiu @lsd1994  i am also facing the same issue when training the yolov4 from scratch on COCO dataset ? Please share your thougths
