### ISSUE TITLE
Whatever dataset I am training, it is always missing one class.

### ISSUE THREAD

**Issue by MLHafizur** [AlexeyAB/darknet#7962]
I am trining Tiny Yolo V3 to detect objects of two classes. but whatever dataset I am training, it is always missing one class, like: class_id = 0, name = Acceptable_Ferrule_placement, ap = 100.00% (TP = 45, FP = 0)
class_id = 1, name = UnAcceptable_Ferrule_Placement, ap = 0.00% (TP = 0, FP = 0)

class_1 is 0

mAP@.50 is 50% 

the same thing is happening for all datasets. I double-checked all of the labels.

**Comment by stephanecharette** [comment]
I've trained hundreds of YOLO-tiny networks but have never seen this problem as you describe.  So something is off in your data.  Either you forgot that classes are zero-based, not one-based, or your project files are not setup correctly.

I would recommend you use [DarkMark](https://www.ccoderun.ca/darkmark/Summary.html#DarkMarkLauncher) to setup the project and generate the output files, and see exactly what is different between what it generates, and what you are attempting to use.
