### ISSUE TITLE
decrease false positive rate

### ISSUE THREAD

**Issue by canergun** [AlexeyAB/darknet#798]
Hello Alexey,what road should i follow to decrease false positives? more iterations or increase dataset size? and by the way is there an indication to increase dataset size?

Thanks

**Comment by AlexeyAB** [comment]
@canergun Hi,
You should increase training dataset size, and include images with false-detections.

You should use at least 2000 images per class with objects. And the same amount without objects. So fo 5 classes you should have 20 000 images. The more - the better.

https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

> desirable that your training dataset include images with non-labeled objects that you do not want to detect - negative samples without bounded box (empty .txt files)

**Comment by canergun** [comment]
Thanks alot
