### ISSUE TITLE
Error Import darknet

### ISSUE THREAD

**Issue by StrikerOnLine** [AlexeyAB/darknet#7988]
https://github.com/AlexeyAB/darknet/blob/0968058b546193d2d2d0ce66de1b4bed36f369d1/build/darknet/x64/darknet.py#L203-L208

Run: darknet_images.py or:

python.exe darknet_video.py --data_file cfg/coco.data --config_file cfg/yolov4.cfg --weights yolov4.weights --input test.mp4

name 'DARKNET_FORCE_CPU' is not defined
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\YoloV4\darknet\build\darknet\x64\darknet.py", line 213, in <module>
    lib = CDLL(winGPUdll, RTLD_GLOBAL)
  File "C:\Users\NewCat\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\YoloV4\darknet\build\darknet\x64\yolo_cpp_dll.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by cenit** [comment]
i will do a PR asap to fix this

**Comment by haviduck** [comment]
latest darknet.py only requires darknet.dll
https://github.com/AlexeyAB/darknet/blob/master/darknet.py

you are using an older darknet which requires you to compile the two dlls in your error log. thats done by building the relevant two vs projects from the build folder

**Comment by cenit** [comment]
yeah, the build folder is somehow “deprecated” in my view, and so duplicated python scripts there still depends on vs projects contained there too
