### ISSUE TITLE
Scaled yolov4 training

### ISSUE THREAD

**Issue by cespedesk** [AlexeyAB/darknet#7992]
Hi I want to train scaled yolov4 and I have some questions.
<img width="650" alt="Capture" src="https://user-images.githubusercontent.com/84055434/128873534-eed795e2-c01e-4e99-aeaa-d877d2528a4d.PNG">
In this section Is yolov4-csp the same as scaled yolov4?
And are the weights in the link below the scaled yolov4 weights?

**Comment by akashAD98** [comment]
yes, it's the same. scaled YOLO contains  yolov4-csp & yolov4-mish,yolov4-csp-swish.
