### ISSUE TITLE
Train Yolo-2 on a remote server

### ISSUE THREAD

**Issue by VanitarNordic** [AlexeyAB/darknet#8]
Hello

My laptop does not have a high end GPU, therefore training a model could take ages with `nogpu`

DO you know is there anyway to train this on a remote server? most of them run Linux and they say if you want to run a custom task (job), you gonna use Docker. Do you know how?

**Comment by AlexeyAB** [comment]
@VanitarNordic 
I know only Amazon EC2, but there is much more expensive than buying your own desktop nVidia GPU GeForce.
Because there are only **server** GPUs, see types **p2** and **g2**: https://aws.amazon.com/ec2/instance-types/

* **p2** - NVIDIA Tesla K80 (2 x GK210) - x10 times more expensive than desktop video card, because with Double-precision-float ALU and GPU-Direct, which is not required in neureal networks (DNN uses Half or Single-precision-float)
* **g2** - NVIDIA GRID - has virtualization for sharing 1 GPU across many Amazon instances, than very slow

See `p2.xlarge` for price: https://aws.amazon.com/ec2/pricing/on-demand/
And for hardware details: https://aws.amazon.com/blogs/aws/new-p2-instance-type-for-amazon-ec2-up-to-16-gpus/

**Comment by VanitarNordic** [comment]
Do you mean using a 24GB K80 will not necessarily make the training faster?

I know another company which a K80 GPU, a 4-cores processor and 32GB RAM can be rented for almost 1.0 per hour. but they only accessible thorough a mechanism called `docker` which I do not know what is it.

**Comment by AlexeyAB** [comment]
I mean [nVidia Tesla K80 (8 Tf-SP)](https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units#Tesla) with price $4000 will such fast as [GeForce GTX 1080 (8 Tf-SP)](https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units#GeForce_10_series) with price $690

And if you want to train DNN less than 700 hours during all time then `p2.xlarge` $0.9/per hour will be cheaper, than buy GTX 1080.

Also you should know that Tesla K80 is mult-GPU (2× GK210), i.e. CUDA see it as 2 GPUs, and you should train on it as on multi-GPU: https://github.com/AlexeyAB/darknet#how-to-train-with-multi-gpu

**Comment by VanitarNordic** [comment]
How long 2000 (as you mentioned could be a rule of thumb for one class enough training) iteration was taken on you own GPU? 

I want to make approximation about training hours

**Comment by AlexeyAB** [comment]
2000 iterations about 1 hour. 
If you want to train for 20 classes, then 40 000 iterations = 40 hours = $36.

Also you absolutely must know than Amazon EC2 is **postpay** service, and if you: forget to stop the server, or the login-password or key is stolen, then to you may be billed ~ x $10000 :)

https://it.slashdot.org/story/15/01/02/2342228/bots-scanning-github-to-steal-amazon-ec2-keys

http://www.itnews.com.au/news/aws-urges-developers-to-scrub-github-of-secret-keys-375785

You must set two-factor auth, set sending alerts. And should practice on a free instance `t2.micro` on which create your own snapshot and later plug it to `p2.xlarge`.

**Comment by VanitarNordic** [comment]
That's amazing, you know on a CPU, this one hour GPU training could take 50 days :-D

Thank you about the security notice. I keep this topic open if I had more question about this. otherwise I gonna close it. You are an absolute professional and explain everything nicely. brilliant.

**Comment by VanitarNordic** [comment]
That's amazing, you know on a CPU, this one hour GPU training could take 50 days :-D

Thank you about the security notice. I keep this topic open if I had more question about this. otherwise I gonna close it. You are an absolute professional and explain everything nicely. brilliant.

**Comment by VanitarNordic** [comment]
That's amazing, you know on a CPU, this one hour GPU training could take 50 days :-D

Thank you about the security notice. I keep this topic open if I had more question about this. otherwise I gonna close it. You are an absolute professional and explain everything nicely. brilliant.

**Comment by VanitarNordic** [comment]
Do yo know how can I make a "Docker" of this?
