### ISSUE TITLE
Problem training own dataset

### ISSUE THREAD

**Issue by 89douner** [AlexeyAB/darknet#800]
I used one GPU and official site repo.
Also, I had 20 images file (10 images: penguin + 10 images: airplane) to detect two objects, penguin and airplane.
I tried training my own dataset, but there is a problem.
I will show some steps to train my own dataset as below

1) I made obj.names 
- I just wanted to predict two objects, penguin and airplane. 
![1 2018-05-13 16-02-36](https://user-images.githubusercontent.com/31752297/39964847-5f53590e-56c8-11e8-9114-09ab8a740bf8.png)

2) I located all images file, label text file, train.txt, and test.txt
(you can see the directory)
![2 2018-05-13 16-03-29](https://user-images.githubusercontent.com/31752297/39964859-a68b06aa-56c8-11e8-9e54-517f3699b8ba.png)
![2 2018-05-13 16-07-56](https://user-images.githubusercontent.com/31752297/39964863-bedda80c-56c8-11e8-94a2-3ed9991f1dc4.png)

3) And, I made obj.data
![3 2018-05-13 16-04-47](https://user-images.githubusercontent.com/31752297/39964875-0dbc2c50-56c9-11e8-9a38-9cac400bc980.png)

4) finally, I copied yolov3-voc.cfg, made new empty file (yolov3-obj.cfg), pasted yolov3-voc.cfg into yolov3-obj.cfg, and modified some lines as below (training, test, classes, filter).
![4 2018-05-13 16-05-31](https://user-images.githubusercontent.com/31752297/39964892-603a3846-56c9-11e8-9a93-6b4a8e08f1b9.png)
![5 2018-05-13 16-06-18](https://user-images.githubusercontent.com/31752297/39964893-621e38ba-56c9-11e8-872e-7bc2b12ec645.png)

5) And executed training command as below
![9993 2018-05-13 00-24-26](https://user-images.githubusercontent.com/31752297/39964899-794e73ce-56c9-11e8-97e3-89312fbc792f.png)
![9994 2018-05-13 00-24-44](https://user-images.githubusercontent.com/31752297/39964900-7d876a86-56c9-11e8-930f-b794c17eb238.png)

I thought that this training was going well as I checked backup files.
![6 2018-05-13 16-20-15](https://user-images.githubusercontent.com/31752297/39964909-d0a21e32-56c9-11e8-88e1-de122d06f1ef.png)

But, when I tried test, the obj-weight files predicted wrong object.
![7 2018-05-13 16-28-58](https://user-images.githubusercontent.com/31752297/39964967-ed3d6622-56ca-11e8-8c42-7a0ad936e97f.png)
Also, I dont understand why the trained model detected wrong object which I didn't made the objects on obj.names, yolov3-obj.cfg. 
![7 2018-05-13 16-29-21](https://user-images.githubusercontent.com/31752297/39964974-fece67e2-56ca-11e8-89c6-8e4126d32d6c.png)
![7 predictions_screenshot_13 05 2018](https://user-images.githubusercontent.com/31752297/39964975-00f006d4-56cb-11e8-8eb9-fe17e7581787.png)

(it is the same.. wrong detection at 10000 weight file)
![8 2018-05-13 16-31-43](https://user-images.githubusercontent.com/31752297/39964983-46c6d070-56cb-11e8-80cf-9e4c06c6c162.png)
![8 2018-05-13 16-32-07](https://user-images.githubusercontent.com/31752297/39964984-48a86c0a-56cb-11e8-833f-5b8a963873b6.png)
![8 predictions_screenshot_13 05 2018](https://user-images.githubusercontent.com/31752297/39964986-4ca4d802-56cb-11e8-9f5a-944ed32cf8a7.png)

Please, let me know answers, Thanks !

**Comment by AlexeyAB** [comment]
Hi,
You use wrong command for detection.
Use command like this: https://github.com/AlexeyAB/darknet#custom-object-detection
`./darknet detector test cfg/obj.data cfg/yolov3-obj.cfg yolov3-obj_10000.weights`

**Comment by 89douner** [comment]
Thanks a lot !!

**Comment by jessiffmm** [comment]
I have some questions:

    I have my images (in jpg format) in the directory darknet/data/images and the labels (.txt) in teh directory darknet/data/labels
    When I try to train with my own dataset I get the following in the first iterations:
    Region 94 Avg IOU: 0.327257, Class: 0.436315, Obj: 0.025532, No Obj: 0.005994, .5R: 0.000000, .75R: 0.000000, count: 4
    Region 106 Avg IOU: 0.218748, Class: 0.485177, Obj: 0.011414, No Obj: 0.003186, .5R: 0.125000, .75R: 0.000000, count: 8
    264: 45.015869, 26.430340 avg, 0.000005 rate, 0.082373 seconds, 264 images
    Loaded: 0.000038 seconds

But after a while I get the following:
Region 94 Avg IOU: nan, Class: 0.000000, Obj: 0.000000, No Obj: 0.000000, .5R: 0.000000, .75R: 0.000000, count: 1
Region 106 Avg IOU: nan, Class: 0.000000, Obj: 0.000000, No Obj: 0.000000, .5R: 0.000000, .75R: 0.000000, count: 6
1139: -nan, nan avg, 0.001000 rate, 0.094441 seconds, 1139 images
Loaded: 0.000038 seconds

I try to put the label files in the same directory(darknet/data/images) that the images, but I have the same problem.

What could be the problem?

Regards!

**Comment by AlexeyAB** [comment]
@jessiffmm 
* What parameters do you use in the Makefile?
* What GPU do you use?
* Did you use https://github.com/AlexeyAB/Yolo_mark for labeling?
