### ISSUE TITLE
Darknet.exe location is different

### ISSUE THREAD

**Issue by Huseyin-Kurt** [AlexeyAB/darknet#8001]
Hello, I compiled the darknet for windows with vcpkg method , following the guideline step by step. It is stated in the documentation that executable file for windows will be located in "\build\darknet\x64" however my exe file appeared in main darknet folder.

I tried some basic commands and for now everything works good.
![darknet exe](https://user-images.githubusercontent.com/44071761/129278665-d7497c1f-b4eb-45ce-96cb-830a53721651.png)
 I am curious about if I did something wrong or is that how it supposed to be with vcpkg compilation process.

**Comment by stephanecharette** [comment]
The installation process for Windows was recently re-written to make it more robust.  It is very possible and likely that some documentation needs to be updated to catch up to the new process.  Tagging @cenit as he may know more about this.

**Comment by cenit** [comment]
darknet.exe is supposed to appear in the main folder, together with the dll and the other executables (uselib and uselib_track - last one available only under certain circumstances).
Can you please show me in the readme where is it said that it should appear under build folder, so that i can fix it?

**Comment by Huseyin-Kurt** [comment]
> darknet.exe is supposed to appear in the main folder, together with the dll and the other executables (uselib and uselib_track - last one available only under certain circumstances).
> Can you please show me in the readme where is it said that it should appear under build folder, so that i can fix it?

İt is on the main github page,right below the title "How to use on the command line"
![darknet exe](https://user-images.githubusercontent.com/44071761/129315608-5ae39b78-d5ce-4240-9ef8-12bf03d72b9d.png)

**Comment by barryyan0121** [comment]
> darknet.exe is supposed to appear in the main folder, together with the dll and the other executables (uselib and uselib_track - last one available only under certain circumstances). Can you please show me in the readme where is it said that it should appear under build folder, so that i can fix it?

Under the `How to train (to detect your custom objects)` section, the ```darknet.exe``` is referred as in `build\darknet\x64`. 

In addition, when I run darknet.exe from the main folder in PowerShell, 
```darknet.exe detector train data/obj.data yolo-obj.cfg yolov4.conv.137``` 
it automatically quits.
