### ISSUE TITLE
Output Shapes of Tiny-YoloV4 (Question)

### ISSUE THREAD

**Issue by DJT777** [AlexeyAB/darknet#8008]
Hello,

I am wondering if you can tell me what the output shapes of the tiny-YoloV4 network are.

**Comment by stephanecharette** [comment]
What do you mean?

Darknet returns a vector of objects, using the CX, CY, and W, H coordinates.  So the shape would be rectangles.  (Did I understand your question?)

**Comment by DJT777** [comment]
Well, I am working with some TensorRT code that is used for YoloV4, and it has the output shapes of YoloV3 Tiny as [(1, 255, 13, 13), (1, 255, 26, 26)]. I am wondering what the shape of TinyYoloV4 would be.

**Comment by stephanecharette** [comment]
Sorry, I have no idea what "output shapes" means.

**Comment by AbdullahAldosari** [comment]
You can use a program called netron on the cfg files to visualize the network and scroll all the way down to see the output shapes of the model.

Keep in mind that the output shape depends on the input shape and the number of classes. By default the input shape of yolov4-tiny is 416 and the number of classes is 80 (coco dataset).  To get the height and width of the first output you divide the input shape by 16 (416/16=26) and for the second output you divide by 32 (416/32=13). To get the number of channels you have to use the following equation: (classes + 5)x3,  Therefore if you are using the coco dataset it will be (80+5)*3=255.

**Comment by DJT777** [comment]
@stephanecharette 
@AbdullahAldosari 
I got the answer I was looking for. Thanks for showing me Netron.

**Comment by DJT777** [comment]
So my output shapes are (1, 18, 16, 16) and (1, 18, 32, 32).

However [this code](https://github.com/Stephenfang51/tracklite/blob/master/tracker/tracker_tiny.py) is giving me the error:

```
user@nano:~/tracklite$ python3 run_tracker_tiny.py --usb
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (933) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
Loading weights from ./deep_sort/deep/checkpoint/ckpt.t7... Done!
Reading engine from file /home/user/tracklite/yolov4-tiny-synth-mk1.trt
Traceback (most recent call last):
  File "run_tracker_tiny.py", line 116, in <module>
    main()
  File "run_tracker_tiny.py", line 102, in main
    loop_and_track(cam, tracker, args)
  File "run_tracker_tiny.py", line 76, in loop_and_track
    img_final = tracker.run(img)
  File "/home/user/tracklite/tracker/tracker_tiny.py", line 67, in run
    trt_outputs = [output.reshape(shape) for output, shape in zip(trt_outputs, self.output_shapes)]
  File "/home/user/tracklite/tracker/tracker_tiny.py", line 67, in <listcomp>
    trt_outputs = [output.reshape(shape) for output, shape in zip(trt_outputs, self.output_shapes)]
ValueError: cannot reshape array of size 5376 into shape (1,18,32,32)
```

I am wondering what exactly is throwing the error when I have the correct output shape reshaping the trt_outputs of the yolo model.
