### ISSUE TITLE
Demo needs OpenCV for webcam images

### ISSUE THREAD

**Issue by cnbabycrazy** [AlexeyAB/darknet#801]
WINDOWS 7 64 + GTX 750 + cuda_9.1.85 + cudnn 7.1.3 + opencv-3.4.0 + VS2015
![qq 20180513172521](https://user-images.githubusercontent.com/7571957/39965806-ba45ea34-56d2-11e8-9f43-4e90a25d6ae2.png)

**Comment by AlexeyAB** [comment]
You should compile **x64 and Release**

https://github.com/AlexeyAB/darknet#how-to-compile-on-windows

> 1. If you have MSVS 2015, CUDA 9.1, cuDNN 7.0 and OpenCV 3.x (with paths: C:\opencv_3.0\opencv\build\include & C:\opencv_3.0\opencv\build\x64\vc14\lib), then **start MSVS, open build\darknet\darknet.sln, set x64 and Release,**

**Comment by cnbabycrazy** [comment]
This problem has been solved. I haven't finished this important step.（set x64 and Release,）
