### ISSUE TITLE
Could not find file: coco.names

### ISSUE THREAD

**Issue by datletrung** [AlexeyAB/darknet#803]
When I run ./darknet detect cfg/yolov3.cfg yolov3.weight data/dog.jpg it return error Couldn't open file: data/coco.names.
I am using https://github.com/pjreddie/darknet

**Comment by datletrung** [comment]
I have tried this and it doesn't return error anymore but it doesn't run too??? [http://warcraft.ml/Capture.PNG](url)

**Comment by datletrung** [comment]
Still get that error.
But if I remove `test`, it's okay??

**Comment by AlexeyAB** [comment]
Remove your darknet and download it again.
If you still get that error - this is an issue of original github repo that you use:  https://github.com/pjreddie/darknet
