### ISSUE TITLE
Question related to [route] and group?

### ISSUE THREAD

**Issue by m3sibti** [AlexeyAB/darknet#8030]
What are `groups` and `group_id` in **[route]** layers? I found information on groups for **conv** layer on [yolov4-wikis](https://github.com/AlexeyAB/darknet/wiki/CFG-Parameters-in-the-different-layers) but there is no explanation of these parameters for **route**. So I wanted to know how they work in **route** ?

**Comment by AbdullahAldosari** [comment]
You can use a program called "netron" on the yolov4-tiny.cfg to visualize the model to help you get some insights about the architecture. It seems the `groups=n` parameter slices the filter into n equal slices and `group_id` is the index of the slice that you want to choose. I am unsure if the indexing starts at 1 or 0.

**Comment by m3sibti** [comment]
@AbdullahAldosari Are group here represent the concept of depthwise-separable conv operation?

**Comment by AbdullahAldosari** [comment]
@m3sibti  Depthwise-separable conv operation relies on splitting the kernel channels into smaller parts (groups) and then applying a convolution operation on each of those parts. in the route layer there isn't any convolution operation happening.

The `groups` keyword is only responsible for separating the channels and nothing else, it is only used as a component to do depthwise-separable convolution (when it is used in a convolutional layer).

**Comment by m3sibti** [comment]
@AbdullahAldosari, Ok thank you for your clearer explanation.

**Comment by KuoEuran** [comment]
@sbmalik @bkapadia02 Hi, Do you know how to convert yolo model with depthwise separable convolution?

**Comment by kaarmu** [comment]
Just to comment on whether `group_id` starts at 1 or 0. 

Just as one would expect, it seems to start at 0.

https://github.com/AlexeyAB/darknet/blob/695d562918d6cd878ffe34104a9c1b518a2de740/src/parser.c#L1107
