### ISSUE TITLE
CUDA Error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by ratkhohieu** [AlexeyAB/darknet#804]
i have cuda 9.1 ( GeForce GT 625M ). I got this error when I run the command line examples.
![image](https://user-images.githubusercontent.com/32360741/39967365-02f16f86-56e4-11e8-9acf-2e8eb20a39a1.png). 
It is same with the other files cmd. Can you help me ?

**Comment by AlexeyAB** [comment]
Your GPU too old. Darknet doesn't support CC 2.1 such as GeForce GT 625M.

https://github.com/AlexeyAB/darknet#requires

> Requires:
> 
> GPU with CC >= 3.0: https://en.wikipedia.org/wiki/CUDA#GPUs_supported

**Comment by Luxato** [comment]
@AlexeyAB This information could be written in the main readme file.

**Comment by AlexeyAB** [comment]
@Luxato It's already written here: https://github.com/AlexeyAB/darknet#requires

> **Requires**:
> Linux GCC>=4.9 or Windows MS Visual Studio 2015 (v140): https://go.microsoft.com/fwlink/?LinkId=532606&clcid=0x409 (or offline ISO image)
> CUDA 9.1: https://developer.nvidia.com/cuda-91-download-archive
> OpenCV 3.3.0: https://sourceforge.net/projects/opencvlibrary/files/opencv-win/3.3.0/opencv-3.3.0-vc14.exe/download
> or OpenCV 2.4.13: https://sourceforge.net/projects/opencvlibrary/files/opencv-win/2.4.13/opencv-2.4.13.2-vc14.exe/download
> OpenCV allows to show image or video detection in the window and store result to file that specified in command line -out_filename res.avi
> **GPU with CC >= 3.0**: https://en.wikipedia.org/wiki/CUDA#GPUs_supported
