### ISSUE TITLE
What does the -clear flag do?

### ISSUE THREAD

**Issue by Duarte-Nunes** [AlexeyAB/darknet#8042]
After training i get the message "If you want to train from the beginning use the -clear flag at the end of the training command".

I just wanted to know what it did in case im missing something. I'm currently training a number of networks to compare results, after training i copy all the weights in the backup file, delete them from the darknet directory, change the cfg to the new paremeters, and train again.

Just wondering if the -clear flag would make any difference, since i delete the backup weights everytime.

**Comment by agjunyent** [comment]
.weights files save apart from the weights some metadata of the training, being one the total number of batches and the last batch it did. What the `-clear` flag does is to set the last batch to 0, meaning the training will start from the begining when loading a .weights file.

If you delete them and start from scratch, or if you use .conv.xxx files, it does not matter

**Comment by Duarte-Nunes** [comment]
Thank you very much that answers all my questions. Yes i do train with a .conv.xxx file so yeah good to know it wasn't afecting my results.
