### ISSUE TITLE
 CUDA Error when training conv. with xnor 

### ISSUE THREAD

**Issue by zrobotparking** [AlexeyAB/darknet#805]
I tried to train yolo with xnor, but i encounter a CUDA error after few iteration. 
Code is as followed
[tiny-yolo-voc_xnor.zip
](https://github.com/pjreddie/darknet/files/1998472/tiny-yolo-voc_xnor.zip)

Execute
> ./darknet detector train data/vco.data tiny-yolo-voc_xnor.cfg 

Error message:
> try to allocate workspace = 16777216 * sizeof(float),  CUDA allocate done! 
> Loaded: 0.000056 seconds
> CUDA Error: an illegal memory access was encountered
> darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
> Aborted (core dumped)
> 

My environment:
Cuda: 8.0
cudnn: 6.0
GPU: GTX1080 8G

**Comment by AlexeyAB** [comment]
Try to train with `random=0` in your cfg-file.

**Comment by zrobotparking** [comment]
@AlexeyAB  Thanks! 
But is that possible to train model with multi scale `random=1`  with GPU?

My environment:
OS. Ubuntu 16.04
CUDA, 9.0
Cudnn,7.1
GPU, GTX1080 11G *3

**Comment by AlexeyAB** [comment]
@zrobotparking I fixed xnor for random=1, update your code from GitHub.
