### ISSUE TITLE
raspberry pi camera bounding box output

### ISSUE THREAD

**Issue by lingogogo** [AlexeyAB/darknet#8086]
command line
./darknet detector demo data/obj.data cfg/yolov3-tiny.cfg /home/gordonlin/yolov3tiny/yolov3-tiny_last.weights "nvarguscamerasrc ! video/x-raw(memory:NVMM), width=(int)1280, height=(int)720,format=(string)NV12, framerate=(fraction)30/1 ! nvvidconv flip-method=2 ! video/x-raw, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink" -ext_output -out ROS_data/result.json -dont_show

However, there is no coordinate info in the result.json.

I found the command line from the website.
However ,I only get the solution to catch the bounding box from .jpg or .mp4 
I want to use it with live stream and take the bounding box coordinate for my ROS msg.
Anyone knows how to deal with the problem.
I use jetson nano developer kit.
Many thanks in advance

**Comment by haviduck** [comment]
teied passing 0 as input?

**Comment by lingogogo** [comment]
> teied passing 0 as input?

i am noob on the yolo.
Can you tell me more detailed ?
Thank you a lot

**Comment by haviduck** [comment]
> > teied passing 0 as input?
> 
> i am noob on the yolo.
> Can you tell me more detailed ?
> Thank you a lot

i dont use jetson so i dont know for sure, but for webcam usually you just pass the device id. dev/video/0 etc. so i guess id try:
darknet detector demo data/obj.data cfg/yolov3-tiny.cfg /home/gordonlin/yolov3tiny/yolov3-tiny_last.weights -c 0 -ext_output -out ROS_data/result.json -dont_show

**Comment by lingogogo** [comment]
i tried this
but it will show green screen.

thank for your help

**Comment by lingogogo** [comment]
Can i ask some question for you

if i buy a webcamera, the command line can be use correctly.
it can transfer data into result.json.
Can it do this?

thank you in advanca.

**Comment by haviduck** [comment]
i know you can sorta do it using detector test instead of demo on images, but besides that id really go python on this. maybe someone with jetson knowhow can guide you further but im not gonna get you to buy hw based on my uninformed reply.

i use darknet detector test for pseudolabelling but thats on a dir of images.

for my projects i use darknets api via python. gives me total control without going into c. so thats what id recommend.

**Comment by lingogogo** [comment]
ok
Thank for your answer ,i take another way to deal with the problem.
