### ISSUE TITLE
Adding an additional element to loss function 

### ISSUE THREAD

**Issue by smolendawid** [AlexeyAB/darknet#8103]
Hi
I'm working on object detection and I'm thinking about adding an additional element to the loss function, so that the loss function considers also the angle of the object in the image. I think it could make learning faster and I can easily extract this information from my data.

I am very new to the repository here and I would appreciate any hints, even simple ones, like where I could find the current loss function code, how should I modify the config so that every layer input-output works, etc. I'm just thinking about a simple loss where LOSS = L_ciou + L_conf + L_class **+ L_angle**

I appreciate any comments
Thanks

**Comment by WongKinYiu** [comment]
L_box
https://github.com/AlexeyAB/darknet/blob/master/src/yolo_layer.c#L174

L_class
https://github.com/AlexeyAB/darknet/blob/master/src/yolo_layer.c#L309

L_obj
search `delta[obj_index]` in https://github.com/AlexeyAB/darknet/blob/master/src/yolo_layer.c#L389

**Comment by smolendawid** [comment]
Thanks for your suggestions!
