### ISSUE TITLE
Error: Building package pthreads:x64-windows failed with: BUILD_FAILED and CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.

### ISSUE THREAD

**Issue by maheshchahare** [AlexeyAB/darknet#8114]
![build error-1](https://user-images.githubusercontent.com/48707775/135055327-a0af8a6d-bc81-4d0a-bccf-3cd27c3500a4.jpg)
![build error-2](https://user-images.githubusercontent.com/48707775/135055343-c0634cc1-d4a0-4c94-acf8-46c94050708e.jpg)
CMAKE version 3.20.5

**Comment by cenit** [comment]
![00645567-4300-43BF-B82B-A9E16A1BE401](https://user-images.githubusercontent.com/721187/135135490-1538f505-cf46-48fa-bdc6-06b793482453.jpeg)

can you please share those files circled in red?

**Comment by awaescher** [comment]
I had the same error 

```
CMake Error: CMake was unable to find a build program corresponding to "Ninja". CMAKE_MAKE_PROGRAM is not set. You probably need to select a different build tool.
```

Fixed it by installing the CMake tools for Windows and Linux with the Visual Studio Installer:

- https://stackoverflow.com/a/72175308/704281
