### ISSUE TITLE
aerial detection from drone

### ISSUE THREAD

**Issue by vkaragounis** [AlexeyAB/darknet#8148]
Hi everybody and thank you for the library.
Have anyone used aerial video from drone just above intersections?
I used  both 3 and 4 'yolo' weights without detected a single car.

![aerial](https://user-images.githubusercontent.com/2451672/136528302-76093026-3525-45df-ae86-f3e5c2ca8b83.jpeg)

Any suggestions?

**Comment by stephanecharette** [comment]
I assume you are using the MSCOCO pre-trained weights?  They're not trained with aerial photography.  You'll want to either train your own custom network, or find a network that someone has created specifically for drones.

The MSCOCO weights are trained with images from ground level.  So cars as seen from the front, sides, and rear, not from above.

**Comment by vkaragounis** [comment]
@stephanecharette 
I 've used the weights existed in 'darknet' folder and a 'yolov3' weight file found in internet.
I suppose i 'll have to create my own file.
Thank you for your response.
