### ISSUE TITLE
Detection

### ISSUE THREAD

**Issue by johnnydept** [AlexeyAB/darknet#815]
Hi Alex,

@AlexeyAB , im running tiny-yolov2 coco dataset which have 80 classes. Is it possible to speed up the inference time by reducing the number of classes? Cause i only need the detector to detect few objects(e.g. person,dog,cat, some animal). Of course, i wanted to attain the accuracy of the detector for the few objects.

**Comment by AlexeyAB** [comment]
@johnnydept Hi,

You can speedup detection, only if you will reduce number of `filters=` twice `/2` in each `[convolutional]` layer **(with `size=3` and `activation=leaky`)**, then you will reduce twice /2 or /4 number of classes in [yolo]-layers, and then you will train your model from the begining. May be using pre-trained weights `yolov3.conv.105` that you can get by using command: https://github.com/AlexeyAB/darknet/blob/8b5344ee2dc551dbe673020a33021e7f84f305f1/build/darknet/x64/partial.cmd#L21
and train
`darknet.exe detector train data/obj.data yolov3_obj.cfg yolov3.conv.105`

**Comment by johnnydept** [comment]
alright Alex,i will try. thanks
