### ISSUE TITLE
Darknet + YOLO4 = cuBLAS status Error in win10?

### ISSUE THREAD

**Issue by DaniilAnd** [AlexeyAB/darknet#8161]
The problem is on windows 10 pro. When running train custom object, if subdivisions = 16, 32 - not enough memory. If 64 is a cuBLAS error 
![](https://i.stack.imgur.com/aUXoF.png)

Configure: config.cfg
![](https://i.stack.imgur.com/3psjn.png)

System: Win 10 pro, gtx 1650 4gb mobile, ryzen 5 5500u, 8gb memory. Use only vcpkg. CUDA 11.4 cudNN 8.2.2 openCV 4.5.3 cuDNN is disabled because mAP doesn't work with it. How can there be a cuBLAS error on win10 ? Thanks for the help!
use PowerShell: .\build.ps1 -UseVCPKG -EnableOPENCV -EnableCUDA -EnableOPENCV_CUDA (not use -EnableCUDNN)

**Comment by DaniilAnd** [comment]
@AlexeyAB сan you tell me please?

**Comment by bulatnv** [comment]
@DaniilAnd 

1) Rebuild darknet with cuDNN. There shouldn't be a map problem.
2) Train tiny version of yolo4, for proper model training minibatch should be at least 4 (subdivision 16).

Good luck.
