### ISSUE TITLE
question on CPU and GPU usage 

### ISSUE THREAD

**Issue by Iamthegeekdavid** [AlexeyAB/darknet#818]
hi there, I compiled the latest (downloaded last week) code and ran on my Windows 10 PC.
CPU: Intel(R) Core(TM) i5-8400 CPU @3.00GHz 
Mem: 16GB
Windows 10
GPU: Nvidia Geforce 730m
I connected an old webcam (resolution: around 700x500) to my PC. I ran the script: darknet_webcam_voc.cmd to do the detection.

For the real time detection, CPU usage is about 33% and GPU usage is about 13%.
I am curious that (1) why such a high CPU usage in my case, (2) output shows that FPS(frame per second) is about 2.5 (why not close to 20).

**Comment by AlexeyAB** [comment]
Hi,
GeForce GT 730M is about 552.2 GFlops, so using `yolov3.cfg` you can get only about 2.5 FPS: https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units

CPU is used to capture frames from web-cam, decode it and resize to the network size.

Try to use tiny yolo v3: yolov3-tiny.cfg (34 MB COCO Yolo v3 tiny) - requires 1 GB GPU-RAM: https://pjreddie.com/media/files/yolov3-tiny.weights

If it will work too slow, read this issue: https://github.com/AlexeyAB/darknet/issues/811

**Comment by Iamthegeekdavid** [comment]
@AlexeyAB ,

Thanks for the information.

**Comment by Iamthegeekdavid** [comment]
Thanks, @AlexeyAB
