### ISSUE TITLE
"change [filters=255] to filters=(classes + 5)x3" seems not applicable on YOLOv4-P5 or P6, what is the new rule?

### ISSUE THREAD

**Issue by willSapgreen** [AlexeyAB/darknet#8189]
In https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4.cfg,
"change [filters=255] to filters=(classes + 5)x3" is still appliable
80 classes -> (80+5)*3 = 255
https://github.com/AlexeyAB/darknet/blob/04b0b15ee42c3b54ae457eb639d9b666a9f5ca8d/cfg/yolov4.cfg#L961

But in
https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4-p5.cfg
and
https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4-p6.cfg
filters is 340 but classes remains 80
https://github.com/AlexeyAB/darknet/blob/04b0b15ee42c3b54ae457eb639d9b666a9f5ca8d/cfg/yolov4-p5.cfg#L1720

So if I want to train P5 or P6 with 1 classes,
what is the new rule to apply?
I use filters=18 but get "Error: l.outputs == params.inputs"

Thank you for your precious time on my question.
Please let me know if you need any other information.

**Comment by willSapgreen** [comment]
Never mind. 
I figure out that the new rule is (classes+5)x4.
So filters=24 if classes=1.
Sorry for wasting this discussion feed.

**Comment by stephanecharette** [comment]
The equation is not "multiply by 3", instead the real equation is "multiply by the number of anchor masks in the [yolo] section.

So if you have `mask=0,1,2` in YOLOv3 and YOLOv4 for example, then you multiply by 3.

Since YOLOv4-p5 has 4 masks, then you multiply by 4.
