### ISSUE TITLE
Help with printing bounding boxes

### ISSUE THREAD

**Issue by TeingQiHao** [AlexeyAB/darknet#8211]
Hi all,

I have been trying to print the co-ordinates of the bounding boxes along with the class. 
There are a lot of files and functions in the repository which give some co-ordinates of the boxes but I am unable to pin point which of those c++ files and the functions to use. Could someone please kindly point me to the correct file and the function to print out the co-ordinates? 
Thank you!

**Comment by akashAD98** [comment]
`!python darknet_images.py --input data/dog.jpg --weights  yolov4.weights --config_file ./cfg/yolov4.cfg --ext_output --dont_show --thresh 0.10`


Use darknet_image.py to run detection & print inside darknet.py to get bbox




def print_detections(detections, coordinates=False):
    print("\nObjects:")
    for label, confidence, bbox in detections:
        x, y, w, h = bbox
        if coordinates:
            print("{}: {}%    (left_x: {:.0f}   top_y:  {:.0f}   width:   {:.0f}   height:  {:.0f})".format(label, confidence, x, y, w, h))
        else:
            print("{}: {}%".format(label, confidence))

**Comment by TeingQiHao** [comment]
Cool! Thanks! Will try it out.

**Comment by cydni** [comment]
hi @TeingQiHao I'm working on the same things now. I'm assuming since you closed the issue this solution worked for you?
