### ISSUE TITLE
RTSP stream as input results in 'Video-stream stopped!" error in Windows

### ISSUE THREAD

**Issue by TheYvesYves** [AlexeyAB/darknet#8217]
Hi there! I would just like to ask for any assistance regarding the use of RTSP stream as input. I have used the following code to try and perform object detection from an RTSP stream created in OBS Studio. This is the code that I used in the command prompt:

`darknet.exe detector demo data/uwg.data cfg/yolov4-uwg.cfg backup/yolov4-uwg_best.weights rtsp://login:pass@127.0.0.1:554/live -i 0`

![image](https://user-images.githubusercontent.com/93991912/140936646-94f1583c-944c-4e9a-80d0-c4a8098877ee.png)

However, doing this results in an error of "Video-stream stopped!"
![image](https://user-images.githubusercontent.com/93991912/140936797-64181f23-c635-42bd-8de8-639ae406ae1d.png)

The RTSP stream could be viewed using VLC which means that OBS successfully outputs an RTSP stream. Any help on this would be highly appreciated. Thanks!

**Comment by haviduck** [comment]
drop the -i 0, its the input parameter so u asking it to use rtsp and webcam 0

**Comment by TheYvesYves** [comment]
> drop the -i 0, its the input parameter so u asking it to use rtsp and webcam 0

Hi thanks for the reply! I tried what you have said:
![image](https://user-images.githubusercontent.com/93991912/141031945-d3658890-b16f-4103-ac9e-a55241fa0960.png)


Sadly, even dropping the `-i 0` did not work:
![image](https://user-images.githubusercontent.com/93991912/141032004-87ed1f43-c9c6-4737-a735-d89106e9816a.png)

I'm quite unsure why this happens, as I have seen others have made an RTSP stream into an input possible.

**Comment by haviduck** [comment]
all examples use -i 0 etc after having a look, so my reply was probably faulty. try with bigbuckbunny or others to ensure your installation handles rtsp. 

rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4

**Comment by TheYvesYves** [comment]
> all examples use -i 0 etc after having a look, so my reply was probably faulty. try with bigbuckbunny or others to ensure your installation handles rtsp.
> 
> rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4

Hi, I have tried your suggestion and ran the following code:
`darknet.exe detector demo data/uwg.data cfg/yolov4-uwg.cfg backup/yolov4-uwg_best.weights rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4`

The stream worked and successfully ran:
![image](https://user-images.githubusercontent.com/93991912/141049528-d3e149e1-8e54-458f-8c97-4e30e52dd6fc.png)

Really baffled as to why the RTSP stream from OBS doesn't work. I'm thinking it could be a possible issue with OBS and the RTSP server, however I haven't looked into that yet.

**Comment by haviduck** [comment]
check codecs :)

**Comment by TheYvesYves** [comment]
> check codecs :)

I'll look into this and update you on how it goes. Thanks!

**Comment by TheYvesYves** [comment]
> check codecs :)

Hi again! I have tried changing the encoder in OBS and the error isn't appearing anymore and shows this output on the command prompt:
![image](https://user-images.githubusercontent.com/93991912/141074006-986fbd24-5dc9-4403-ab19-352dce3982fc.png)

Although it takes really long for a window of the detection to pop up, it eventually still works. Thanks for your inputs. All of them definitely helped!
