### ISSUE TITLE
Is it possible to remove camera frame but still continue detection in command prompt console?

### ISSUE THREAD

**Issue by PIjarihd** [AlexeyAB/darknet#8225]
I am working with YOLOv4 for detection through IP Camera. I have a GUI for camera control. So I don't want the camera frame to show the detected objects. However, I want the detected objects and the percentage to be shown in the Command Prompt console. Is it possible to make that? If yes, please suggest the way. Thank You.

**Comment by haviduck** [comment]
-dont_show

**Comment by PIjarihd** [comment]
Thank You.

**Comment by PIjarihd** [comment]
Thank You
