### ISSUE TITLE
Sir, I have implemented customized yolov3 darknet for detecting digits of 7 segment display, the model is showing good accuracy. But on the generated results, output digits are sorted in descending order(output 293 in result generated is showing as 932). Is it possible to save the results without sorting? where to edit in code to disable this sorting?

### ISSUE THREAD

**Issue by sabinajashir** [AlexeyAB/darknet#8230]
For Feature-request:
    * describe your feature as detailed as possible
    * provide link to the paper and/or source code if it exist
    * attach chart/table with comparison that shows improvement

**Comment by thuangb** [comment]
There is no order as the order of the output is random. So you have to base on the position of the bounding box to sort the result as the way you want

**Comment by stephanecharette** [comment]
I've answered this twice already.  https://github.com/AlexeyAB/darknet/issues/8228#issuecomment-971260135

**Comment by sabinajashir** [comment]
Thank you both for your reply...
@thuangb I'll try this way sir..thank you

**Comment by sabinajashir** [comment]
> There is no order as the order of the output is random. So you have to base on the position of the bounding box to sort the result as the way you want
It worked !! thanks
