### ISSUE TITLE
How to create .exe (or one click program) for yolov4?

### ISSUE THREAD

**Issue by PIjarihd** [AlexeyAB/darknet#8234]
I want to use YOLOv4 in another computer as .exe file. I **don't want** to type command in the command propmt everytime. So, how can I make an exe file which will run yolov4 automatically?
P.S. for windows
Please suggest me. Thanks in advance.

**Comment by haviduck** [comment]
think the closest youll get without really getting into it is to make a shortcut to darknet.exe and pass the arguments in the shortcut parameters. keep in mind the "other computer" needs the same opencv, cuda etc. packaging your entire build is just not a straight forward thing to do but docker can get you somewhat close.

**Comment by PIjarihd** [comment]
> think the closest youll get without really getting into it is to make a shortcut to darknet.exe and pass the arguments in the shortcut parameters. keep in mind the "other computer" needs the same opencv, cuda etc. packaging your entire build is just not a straight forward thing to do but docker can get you somewhat close.

Thank you for your reply Sir. Sure, I will keep that in mind.
However, I did not understand well about adding parameter in shortcut parameter. I think to create shortcut is easy: 

> RightClick the .exe file and  create shorcut (in windows)
Please correct me if I misunderstood this.

However, how do I pass the argument? Do I have to create another GUI or program for that? How do I pass command which I used to insert in command line `darknet.exe detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights -ext_output test.mp4`?

Please explain detailly. Thank You.

**Comment by haviduck** [comment]
![image](https://user-images.githubusercontent.com/4920887/141957489-ad3b39a5-695b-4c2e-97d8-0982573e15a2.png)
theres also a bunch of cmd examples in build/darknet that you can have a look at. .cmd and .bat will both work aswell.

**Comment by PIjarihd** [comment]
> ![image](https://user-images.githubusercontent.com/4920887/141957489-ad3b39a5-695b-4c2e-97d8-0982573e15a2.png) You might have to use full paths in your shortcut, my example had the shortcut in the same dir as the exe. theres also a bunch of cmd examples in build/darknet that you can have a look at. .cmd and .bat will both work aswell.

Thank You so much Sir. It works. I learnt a new thing today. Thank you so much.

**Comment by PIjarihd** [comment]
> ![image](https://user-images.githubusercontent.com/4920887/141957489-ad3b39a5-695b-4c2e-97d8-0982573e15a2.png) You might have to use full paths in your shortcut, my example had the shortcut in the same dir as the exe. theres also a bunch of cmd examples in build/darknet that you can have a look at. .cmd and .bat will both work aswell.

Thank you so much Sir. This works. Learnt something new tody. Thank You again.
