### ISSUE TITLE
I don't want to apply augmentation with my dataset.

### ISSUE THREAD

**Issue by Wooks-git** [AlexeyAB/darknet#8236]
I trained yolov4-csp-custom (width,height = 256, classes=3)
But when i using $./darknet detector train .data .cfg .weights -dont_show -show_imgs  command, i got strange annotation.
When i check my annotation files (e.g img1.txt , img2.txt ... files) they were not problematic.
So i want to check my input data without augmentation.
1. Does anyone know how not to apply augmentation?
2. The annotation files are normal, but does anyone know why the input data is weird?

**Comment by thuangb** [comment]
Just use labeling tools such as yolo_mark, labelimg, ... to check you annotation

**Comment by stephanecharette** [comment]
FAQ:  https://www.ccoderun.ca/programming/darknet_faq/#turn_off_data_augmentation

**Comment by Wooks-git** [comment]
Sorry, there was a mistake in the process of making the label file.
