### ISSUE TITLE
Yolov4 Train -Custom Model Combing 3 classes noMask, facemask and person detection

### ISSUE THREAD

**Issue by KarthickMani87** [AlexeyAB/darknet#8242]
Hi Alexy,

I have been working on training a custom model which has 3 classes "no face mask" as one class, face masks as 2nd class and people as 3rd class. 
class 1 = NO FaceMask (bounding box on people's face who have no facemask)
class 2 = FaceMask (bounding box on people's face with facemask)
class 3 = Person

I am training it on multi-gpu amazon AWS (GPU: Tesla V100-SXM2-16GB). I start training with following command : 
./darknet detector train /home/ubuntu/obj/obj.data /home/ubuntu/obj/yolov4-obj.cfg /home/ubuntu/yolov4.conv.137 -gpus 0,1,2,3 -dont_show

When I train them as a single class individually the detection on video input works with good accuracy.

However, I face an issue when these three classes are combined together. I have labelled their respective images correctly.
After 8000 iterations, when I checked the detection output on the video, it predominantly detects only nofaceMask and facemask classes (class 1 and class 2) and hardly detects class 3 (person) (only one or 2 persons detected for every 30-40 frames). 
 
I did 2 experiments. Same yolov4.cfg and obj.data were applied for both experiments

1. I excluded "facemask and No facemask" people dataset completely and fed only the people dataset. The model detected person (with label 2) with good accuracy.

2. Now trained the model with all 3 dataset, the model detected mostly "face-mask" and "nofaceMask" classes with good accuracy and hardly detected class 3 (person) here and there. The same class 3 (person) who got detected in the 1st experiment was not getting detected in this experiment.  

My finding is that as soon as the model starts detecting/converging (I took the weights once in a while and tested) on "facemask" and "noFaceMask", class 3 (people) detection gets faded/suppressed and only the first 2 classes results dominate. 

I am attaching the cfg file for reference. 

What might be the reason? Why does "nofaceMask" and "FaceMask" classes influence class 3 (person) detection? Any suggestion would greatly help.

Warm Regards,
Karthick
[yolov4-obj_3classes.txt](https://github.com/AlexeyAB/darknet/files/7560746/yolov4-obj_3classes.txt)
k

**Comment by stephanecharette** [comment]
What is "a few thousand"?  Because the *minimum* is 6000.

When you combined the classes, are you certain that you renumbered them correctly?  Is it at all possible that some labels for "person" are incorrectly set to "facemask", or the other way around?

Have you tried to use a tool like DarkMark to verify your annotations?

**Comment by KarthickMani87** [comment]
Hi @stephanecharette ,

Thanks for the quick response. Sorry about the misleading phrase ("a few thousand"). I ran for more than 8000 iterations. 

The labels are fine and I verified it.  

I was wrong about 2 classes but indeed I have been training with 3 classes.

I did 2 experiments. Change in yolov4.cfg and obj.data for 3 classes applied for both experiments

1. I excluded "facemask and No facemask" people dataset completely and fed only the people dataset. The model detected person (with label 2) with good accuracy.

2. Now trained the model with all 3 dataset, the model detected mostly "face-mask" and "nofaceMask" classes with good accuracy and hardly detected class 3 (person) here and there. The same class 3 (person) who got detected in the 1st experiment was not getting detected in this experiment.  

My finding is that as soon as the model starts detecting/converging (I took the weights once in a while and tested) on "facemask" and "noFaceMask", class 3 (people) detection gets faded/suppressed and only the first 2 classes results dominate. 

I am attaching the cfg file for reference. 

Please let me know if you need more information.

Warm Regards,
Karthick



[yolov4-obj_3classes.txt](https://github.com/AlexeyAB/darknet/files/7560567/yolov4-obj_3classes.txt)

**Comment by KarthickMani87** [comment]
Hi @AlexeyAB, @WongKinYiu @cenit 

Please check this issue.

Warm Regards,
Karthick

**Comment by KarthickMani87** [comment]
Not resolved
