### ISSUE TITLE
Training without CUDA GPU - Possible?

### ISSUE THREAD

**Issue by DP1701** [AlexeyAB/darknet#8243]
Hello all,

Is it possible to train the detector with a CPU?
I know GPU is better, but unfortunately I only have an AMD GPU.

**Comment by awaisbajwaml** [comment]
Yes CPU is possible but patience is the requirement. I did once , it took 21 days and later I rented GPU as it worth doing so

**Comment by tiva-0007** [comment]
This already sounds so discouraging... But, how do I get my training on CPU running?

**Comment by stephanecharette** [comment]
See the FAQ https://www.ccoderun.ca/programming/darknet_faq/#how_to_get_started and/or see the tutorials on youtube, such as https://youtu.be/pJ2iyf_E9PM

Just like that youtube video, don't setup darknet to use a GPU, meaning it will use your CPU.
