### ISSUE TITLE
Modifying yolov4 neck

### ISSUE THREAD

**Issue by erminkev1** [AlexeyAB/darknet#8244]
I have been reading dozens of papers on YOLOv4 network, in which they talk about modifying the existing architecture. A common example was to modify the neck of the YOLOv4, specifically by deleting some layers or even changing the outputs that are fed into YOLO head for detection.

Now, I have tried to understand the official config files provided, as they contain information about the network structure. However, the problem was here that I am not so familiar with config files in the first place, therefore I could not understand too much. In example, where is the neck of YOLO located when looking at the .cfg, or the file in question is mainly representing the backbone for the algorithm? And if it can be altered, it would be great to have an explanation :)

**Comment by Fetulhak** [comment]
@erminkev1 the neck of YOLOV4 is the PANet part which is used for feature aggregation at different locations on the network. you can refer the following figure in the link provided, it may help you understand where on .cfg file the three major components in yolov4 structured. https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04036-4/figures/5
