### ISSUE TITLE
mAP FLAG NOT WORKING

### ISSUE THREAD

**Issue by barryyan0121** [AlexeyAB/darknet#8262]
Hi, I was trying to show mAP curve during the training process, but my `chart.png` is not showing any red lines.

![2](https://user-images.githubusercontent.com/43865968/144026593-4c7e0b67-59ea-47b3-b445-ddee508dbfec.png)
Steps to reproduce:
`darknet.exe detector train data/obj.data yolo-obj.cfg yolov4.conv.137 -map`

System Information:
![1](https://user-images.githubusercontent.com/43865968/144026569-466b188a-82a8-48fc-9a5b-f21d0341560f.png)

**Comment by barryyan0121** [comment]
Apparently, MAP is created for every 1,000 iterations.

**Comment by lsd1994** [comment]
> Apparently, MAP is created for every 1,000 iterations.

map is created at least 1000 iters, then how often to get map is depend on image nums ans batch size.
