### ISSUE TITLE
Same model performs different on Ubuntu and Windows

### ISSUE THREAD

**Issue by yangulei** [AlexeyAB/darknet#828]
I had trained a yolov2 model on Ubuntu, which performs well on Ubuntu. And then I test the model with exactly the same data-file, cfg-file, weights-file and video file using 'darknet.exe detector demo ...' command in Windows 10 cmd app. It turns out that the results are obviously different. Here are the results on the same (almost) frame:
![ubuntu_demo_frame](https://user-images.githubusercontent.com/24203353/40091200-edae7676-58e8-11e8-8f7b-62f9e5c1bf0b.jpg)
![win_demo_frame](https://user-images.githubusercontent.com/24203353/40091209-f60ef71e-58e8-11e8-86ab-7cfbab3e29ea.jpg)

Then I compare the results of 'darknet detector test ...', here is the results:
![ubuntu_test](https://user-images.githubusercontent.com/24203353/40091291-5b94f138-58e9-11e8-97c3-af73cb4a6538.jpg)
![win_test](https://user-images.githubusercontent.com/24203353/40091294-5e1fd4d6-58e9-11e8-8419-169fe9053563.jpg)
The results looks like identical at first glance, but they do differ slightly (just check the bus and the car on the right hand side of the bus).

I have tried to train the model on Windows 10 with the same dataset and configuration, but I got the same difference in the results.

So, please help me to find out where are the difference come from and how to avoid this, thanks!

**Comment by AlexeyAB** [comment]
Change  https://github.com/AlexeyAB/darknet/blob/e29fcb703f8d936e17507bf78043a8b8bc6279b0/src/demo.c#L18
to
`#define FRAMES 1`

**Comment by AlexeyAB** [comment]
* Do you use this repository for Windows and Linux? https://github.com/AlexeyAB/darknet
* Do you use the same version of repository?
* Did you compile both versions using the same version of OpenCV?

It looks like (by the width of edges of bounded boxes) that is used different code or compiled with/without OpenCV.

**Comment by yangulei** [comment]
* Yes I do use your repository.
* No, the version on Ubuntu is older, git log shows the last commit is on Mar 20 2018. The version on Windows was downloaded at May 15 2018.
* The version of OpenCV doesn't matter, I have checked with different versions of OpenCV and the results are identical. 
It looks like some thing is wrong in the new version since I complete the checking and get the following results:
|     case     | old version | new version |
|    :------:    | :-------------: | :--------------: |
|   Ubuntu   |      good     |        bad       |
| Windows  |      good     |        bad       |
test
name | age
------- | ------
me | 30

**Comment by yangulei** [comment]
* Yes I do use your repository.
* No, the version on Ubuntu is older, '_git log_' shows the last commit was done on Mar 20 2018. The version on Windows was downloaded on May 15 2018.
* No, but the version of OpenCV doesn't matter, I have checked with different versions of OpenCV and the results are identical. I'm using OpenCV 3.4.0 in both Ubuntu and Windows now.

It looks like some thing wrong in the new version since I complete the checking and get the following results:

|  | old version | new version |
| :------: | :-------------: | :--------------: |
| Ubuntu | good | bad |
| Windows | good | bad |

**Comment by AlexeyAB** [comment]
* What does you mean by bad? mAP is lower or what?
* Try to comment this line: https://github.com/AlexeyAB/darknet/blob/fb9fcfb3ba0057b1196d1b95fd53cdb0b874b1c3/src/detector.c#L1069
   and this: https://github.com/AlexeyAB/darknet/blob/fb9fcfb3ba0057b1196d1b95fd53cdb0b874b1c3/src/demo.c#L147

**Comment by yangulei** [comment]
Sorry for the confusing.
* This means good:
![ubuntu_demo_frame](https://user-images.githubusercontent.com/24203353/40091200-edae7676-58e8-11e8-8f7b-62f9e5c1bf0b.jpg)
And This means bad, which shows missing of some obvious objects:
![win_demo_frame](https://user-images.githubusercontent.com/24203353/40091209-f60ef71e-58e8-11e8-86ab-7cfbab3e29ea.jpg)
* I tried your suggestion, but no visible improvement.
* I also tried different version of the code using the data-file, cfg-file and weights-file downloaded form the original darknet website, just in case that my model has something wrong, but I got the same results: the older version performs better than the new one.

**Comment by AlexeyAB** [comment]
1. Do you mean that **Original Darknet old**-version gives better result than **Original Darknet new**-version?

2. What specifically command did you use for detection?

3. What params do you use in the Makefile?

**Comment by AlexeyAB** [comment]
Try to change in your cfg-file `[reorg]` to `[reorg_old]`

**Comment by yangulei** [comment]
1. Sorry for I didn't make it clear. I use _your repo_ all the time for all the cases. The 'original' I mentioned refers to the data-file, cfg-file and weights-file which were downloaded from pjreddie's website. The 'old-version' and 'new-version' refers to _your repo_ I downloaded on Mar 20 and May 15 respectively. So what I'm trying to say is that, using the untouched 'original' yolov2 _model files_, the older version from _your repo_ performs better than the new one. By the way, I don't use pjreddie's repo any more since I found your excellent repo, thanks a lot! 
1. I use the 'darknet/darknet.exe detector demo data-file cfg-file weights-file video-file -out_filename results.avi' on Ubuntu and Windows respectively, and select the same frame for comparison.
1. I set GPU=1, CUDNN=1, OPENCV=1 and no other changes in the Makefile. I'm using CUDA 9.1, cuDNN 7, and OpenCV 3.4.0 both on Ubuntu and Windows. 
1. I tried to change [reorg] to [reorg_old]  in the original yolov2.cfg, then run your old and new version with the original coco.data and yolo.weights, but still gets bad results with the new-version. Moreover, the cfg-file in _my model_ has no route/reorg layers, so [reorg] or [reorg_old] doesn't change the results.

Could you please try a model with the old-version and new-version? Because I'm wondering why other users haven't mention this problem, maybe I did something that cause this. So if you can give it a try, then we can confirm something.

**Comment by AlexeyAB** [comment]
@yangulei 

1. Change this line in the new version: https://github.com/AlexeyAB/darknet/blob/94c84da85015f0dcc6deaff53b24ff46a730711c/src/detector.c#L1156
to this `float thresh = find_float_arg(argc, argv, "-thresh", .24);`

2. Change this line in the new version: https://github.com/AlexeyAB/darknet/blob/94c84da85015f0dcc6deaff53b24ff46a730711c/src/demo.c#L77
to this `float nms = .4;`

3. Try to get mAP on the old and new version:
`./darknet detector map data/obj.data yolo-obj.cfg backup\yolo-obj_7000.weights`

I get the same mAP = 75.92% for yolov2-voc.cfg on the old and new code.

**Comment by yangulei** [comment]
1. I tried to change the confidence and non-max-suppression threshold, but no visible improvement noticed in the new-version code.
1. Yes, I get the same mAP too on the old and new code.
1. Have you try 'darknet detector demo ...' with the old and new code? Looks like the problem comes from the _demo_ routine.

**Comment by AlexeyAB** [comment]
1. Try to set thresh=0.24, nms=0.4 and change these lines: https://github.com/AlexeyAB/darknet/blob/c1bb8c129d7d4d8fc85348d5e7ac5441fa36ead5/src/demo.c#L155-L156
    to this:
    `cap = cvCaptureFromFile(filename);`

2. Can you check, what commit of these brakes demo detection? There are history of commits related only to demo.c: https://github.com/AlexeyAB/darknet/commits/c1bb8c129d7d4d8fc85348d5e7ac5441fa36ead5/src/demo.c

3. I don't see any visual differences between old and new commits. But I didn't check this frame by frame.

**Comment by yangulei** [comment]
1. I tried your suggestion, but no visible difference found. Moreover, I don't think the thresholds cause the problem, for the new code miss some objects, like the white car near the right-button corner, that should have higher confidence than some of the objects, like the much smaller cars, that is hard to detect, just like the following frame:
![last_frame_new_code](https://user-images.githubusercontent.com/24203353/40288561-5dd9baae-5ce6-11e8-8e41-459b2ae77ee1.png)

1. I checked all kinds of the commits, not just the commits related to demo.c. I find out that the most early version of the code that give bad results is on Mar 28, 2018, 991a24016794f3412d668919a94e9994711874d2. And the last version that don't have this problem is on Mar 27, 2018, 47c7af1cea5bbdedf1184963355e6418cb8b1b4f. Sorry for I can't do the debugging further, for I'm not good enough at coding.
1. Here is [my video and results](https://github.com/AlexeyAB/darknet/files/2021067/test_video_and_demo_results.zip), can you give it a try? I didn't need to check the results frame by frame, because the differences are so obvious.

**Comment by yangulei** [comment]
@AlexeyAB 
Are you online? Don't give up on this please~

**Comment by AlexeyAB** [comment]
@yangulei Im online :) 
So, if there is no problem for detector test, but only problem for detector demo, then I think there is some issue in the `do_nms_obj()` :)


Try to use 
`if (nms) do_nms_sort(dets, nboxes, l.classes, nms); `
instead of: https://github.com/AlexeyAB/darknet/blob/4403e71b330b42d3cda1e0721fb645cf41bac14f/src/demo.c#L101

**Comment by AlexeyAB** [comment]
@yangulei Also did you see the same problem by using new original Darknet repo?
Looks like there are the same code and should be the same issue:

demo.c: https://github.com/pjreddie/darknet/blob/d3828827e70b293a3045a1eb80bfb4026095b87b/src/demo.c#L82

do_nms_obj(): https://github.com/pjreddie/darknet/blob/d3828827e70b293a3045a1eb80bfb4026095b87b/src/box.c#L6-L55

![image](https://user-images.githubusercontent.com/4096485/40317612-af335844-5d2a-11e8-984e-22a0c9cec9e0.png)

**Comment by yangulei** [comment]
1. The new original Darknet repo don't have this problem, I had checked this out this morning.
1. I saw your commit that fix this, I tried the newest version, and it works fine! Thanks a lot!

Happy debugging with you :)

**Comment by AlexeyAB** [comment]
@yangulei Thanks for the help in finding the bug! )
