### ISSUE TITLE
What does yolov4.conv.81 mean?

### ISSUE THREAD

**Issue by Turkishvein** [AlexeyAB/darknet#8281]
csdarknet53-omega.conv.105 - The first 105 layers from the pre-trained weights on ImageNet (ILSVRC2012):
Why partialling first 105 layers or 81 layers? Why not other numbers?

**Comment by Turkishvein** [comment]
Actually 140 layers existing before first yolo layer

**Comment by lsd1994** [comment]
The backbone has 105 layers.
