### ISSUE TITLE
Output prediction dataset on test set

### ISSUE THREAD

**Issue by valentindbdg** [AlexeyAB/darknet#8290]
Hello,

Thank you for your repo! My model training goes well, I try to evaluate on a test set and output the prediction dataset.

Here is what I tried:
`!./darknet detector test /content/obj_test.data $cfg_file $weights_best -dont_show -ext_output </content/data/test.txt> result2.txt`
What I would like to obtain is a .txt file for each image containing one row for each bounding box (Yolo format).

Any way I could directly get this result or something close?

Thank you!

**Comment by lsd1994** [comment]
Maybe you should change source code to implement it.
