### ISSUE TITLE
Detect Cropped Object

### ISSUE THREAD

**Issue by ferdyandannes** [AlexeyAB/darknet#8300]
Hi Guys,

I have a questions regarding my training, I trained the pad defect using tiny yolo v3 with the size of around 100x100.
If I pass the whole images like the image below, it could detect the defect. The original image size is around 1000x1000

![image](https://user-images.githubusercontent.com/28348831/146445331-143f00f7-f7b7-49f8-b720-adbe3b1d7fc1.png)

But why if I pass the cropped image of the defect, why it couldn't detect the defect? like in the image below

![image](https://user-images.githubusercontent.com/28348831/146445409-0d71eb60-ef09-4691-a953-12724b9bfcc7.png)

My goal is to train the pad defect, but my input is just cropped image like in the 2nd images. 

Thank you very much, I hope someone could give me some idea about it. Cheers!

*Notes: I trained the model with the normal image size and then label for each object. Is it because I am not trained with the cropped image directly?

**Comment by stephanecharette** [comment]
https://www.ccoderun.ca/programming/darknet_faq/#crop_training_images

**Comment by ferdyandannes** [comment]
> https://www.ccoderun.ca/programming/darknet_faq/#crop_training_images

thank you very much for the insight, sorry for late reply
