### ISSUE TITLE
detector used on multiple images

### ISSUE THREAD

**Issue by rodthebuilder1** [AlexeyAB/darknet#8305]
Hi all,

I saw in another issue a line of code to detects objects on multiples images and save the result in a txt file. I tried to run the command below and got a cannot load image error.  Anybody used their model on multiple images succesfuly ? I am running it on Windows btw. If you know a how I could use my model and write my own code to apply it on multiple images and save the txt file it would be perfect. Any help is appreciated:

![command used](https://user-images.githubusercontent.com/95254170/147147641-64f74f3c-7ea5-401c-bbd2-599fac0a8004.PNG)
![cannot load images](https://user-images.githubusercontent.com/95254170/147147656-bb74a56b-3460-4ee9-8c2f-fc268c2454fe.PNG)

Here is my train file:

![train file](https://user-images.githubusercontent.com/95254170/147147748-8288ce39-c25a-434f-96e7-42564b7a0488.PNG)

 and here is the issue I got the initial line of code from:

https://github.com/pjreddie/darknet/issues/903

**Comment by stephanecharette** [comment]
Also see this which may do what you need:  https://www.ccoderun.ca/darkhelp/api/Server.html

**Comment by stephanecharette** [comment]
This might help:  https://www.ccoderun.ca/programming/darknet_faq/#json_output
