### ISSUE TITLE
Compile Using Visual Studio 2013

### ISSUE THREAD

**Issue by ferdyandannes** [AlexeyAB/darknet#8312]
Hello guys,

I tried to compile Darknet using visual studio 2013 (VS120), the darknet_no_gpu.sln project. But I facing a issue that I couldn't compile, I found some reference said that the minimum version is Visual Studio 2015. (I tried to fix the error one by one but it keep getting very much and more. Is there any one of you guys had tried to compile the darknet_no_gpu project with visual studio 2013?

And if I build the yolo_cpp_dll_no_gpu.sln using Visual Studio 2019 (VS140), could I use the yolo_cpp_dll_no_gpu.lib in the project that compiled in the Visual Studio 2013?

My aim is I would like to combine object detection with the my current code for both training and testing (my code is C++ code that compiled in vs120, which is compiler that we use in Visual Studio 2013), I see the code that have project to generate .dll file, but still I couldn't compile it using VS120.

Thank you very much, hope I could get some insight about it to solve my problem.

This is the example of one of the error.
![image](https://user-images.githubusercontent.com/28348831/147612559-b963193c-27fb-460e-bd80-aa3145fbd722.png)

**Comment by stephanecharette** [comment]
> using visual studio 2013 (VS120)

No one should be using such an old compiler.  I think it is unlikely you'll get this to work.

**Comment by ferdyandannes** [comment]
> > using visual studio 2013 (VS120)
> 
> No one should be using such an old compiler. I think it is unlikely you'll get this to work.

Hello, yeah right, finally I changed my compiler with the new one (VS142). Now, I could compile and generate the .lib file to embed it with my current program.

Thank you very much for your help.
