### ISSUE TITLE
Possible BUG: Output Create 6 permanent cpu-threads on AMD 5950x

### ISSUE THREAD

**Issue by 1027663760** [AlexeyAB/darknet#8341]
Shouldn't it be creating 32 threads?
After testing, it is found that mosaic = 1 will cause the training speed to slow down a lot. Set args manually Threads = 32, error will be reported during post compilation training
@AlexeyAB  Can you check it out when you have time?
![1](https://user-images.githubusercontent.com/26378634/150664686-52cbab47-e981-43f8-b0c4-1ee959e23d10.png)

**Comment by 1027663760** [comment]
libpng error: bad adaptive filter value
Error in load_data_detection() - OpenCV

**Comment by sreddy-es** [comment]
Was the libpng error introduced when you changed the threads arg manually? Also which file did you edit?
