### ISSUE TITLE
How to obtain pre-trained weight for tiny yolo v3?

### ISSUE THREAD

**Issue by off99555** [AlexeyAB/darknet#835]
I saw this command is for yolo v2:
`darknet.exe partial cfg/yolov2-tiny-voc.cfg yolov2-tiny-voc.weights yolov2-tiny-voc.conv.13 13`
But I want to train my own dataset on yolo v3. What is the command to obtain a partial weight for it? 
Here's the file I downloaded: https://pjreddie.com/media/files/yolov3-tiny.weights

Also another question:
In the yolo tiny cfg file:
```
[net]
# Testing
batch=1
subdivisions=1
# Training
# batch=64
# subdivisions=2
width=416
height=416
```
If I want to train it, I need to uncomment `batch=64` and `subdivision=2` right?

**Comment by dexception** [comment]
see https://github.com/AlexeyAB/darknet/issues/791

**Comment by off99555** [comment]
Thanks!
