### ISSUE TITLE
 Error: cuDNN isn't found FWD algo for convolution. - Please help!

### ISSUE THREAD

**Issue by JSarko27** [AlexeyAB/darknet#8362]
Hi,

So I'm trying to run the command to begin training my own custom dataset and I'm getting the " Error: cuDNN isn't found FWD algo for convolution." error. I am running this on my laptops GPU (GeForce RTX 3050 Ti), with CUDA version 11.6 & cuDNN 8.3.2 and I have not incorporated tensorflow at all so far. It usually runs for about 5 seconds before presenting the error, as shown in the screenshots below.

<img width="661" alt="Screenshot 2022-02-16 050444" src="https://user-images.githubusercontent.com/99783917/154200322-2c106734-34d1-40dc-97c9-d82870895a80.png">

<img width="670" alt="Screenshot 2022-02-16 050830" src="https://user-images.githubusercontent.com/99783917/154200343-e9dcc91a-2742-45c4-a5de-dceefea77ba9.png">

Please help me out if possible!

**Comment by yamiefun** [comment]
Hi, how did you solve the problem?

**Comment by JSarko27** [comment]
I couldn't do anything directly, I saw somewhere that this error occurs because your system requires 8GB VRAM to train your dataset with YOLOv4. I'm not sure if thats the actual reason but I ended up using YOLOv4-tiny.

**Comment by DTQX** [comment]
You need set a bigger subdivisions in cfg.
![image](https://user-images.githubusercontent.com/27469379/228937579-3efd838a-33d1-42cb-a2ad-3066e983d6ee.png)
