### ISSUE TITLE
Necessary components

### ISSUE THREAD

**Issue by Sennevds** [AlexeyAB/darknet#837]
Hi a little question.
I'm trying to run the software on several pc's I've changed some things to the yolo console application and try to distribute them to several PC's. 
Now which dll's do I need to get it up an running. The PC's where it's going to run don't have visual studio. Do I need to install cuda and cdnn or can I copy the right dll's to get it working?

Kind regards 
Senne

**Comment by AlexeyAB** [comment]
Hi, you should copy DLLs:
* for cuDNN 7: `cudnn64_7.dll`
* for CUDA 9.1: `cudart64_91.dll`,  `cublas64_91.dll`,  `cufft64_91.dll`,  `curand64_91.dll`
* for OpenCV 3.4.0: `opencv_world340.dll` 
    and if you use Optical flow: `opencv_cudaoptflow340.dll`, `opencv_cudaimgproc340.dll`, `opencv_core340.dll`, `opencv_imgproc340.dll`, `opencv_highgui340.dll`

Also: `yolo_cpp_dll.dll` and `pthreadVC2.dll`, `pthreadGC2.dll`

**Comment by Sennevds** [comment]
I've copied them all but apparently I was missing some visual c++ packages installed them and everything is working fine! Thank you very much we are starting this monday with a project to track how much traffic (comparsion of cars vs by foot bike or public transport) on several spots so it's going to be an interesting project.

**Comment by AlexeyAB** [comment]
@Sennevds Can you share it with the people, what other dll-s did you copy?
