### ISSUE TITLE
Is there anyone who can send a statically compiled program (Opencv +CUDA)？

### ISSUE THREAD

**Issue by PTA00** [AlexeyAB/darknet#8376]
My computer currently does not have a graphics card and cannot compile CUDA support, please help me.

**Comment by stephanecharette** [comment]
Leave `GPU=0`, `CUDNN=0`, and `CUDNN_HALF=0` in `Makefile`, and it wont look for CUDA.

**Comment by PTA00** [comment]
> 离开`GPU=0`, `CUDNN=0`, 和`CUDNN_HALF=0`，`Makefile`它不会寻找 CUDA。

But I'm going to run it on a computer with a graphics card.So I still need GPU=1.........

**Comment by stephanecharette** [comment]
I don't understand.  In that case, why don't you build it on the computer that has the graphics card?

We cannot build it for you.  We have no idea was OS you are using.  (Linux, Mac, Windows?)  We have no idea what version OS you are using.  We have no idea what OpenCV you are using, what CUDA and CUDNN version, and which graphics card you have.  This is something that you need to do.

See here to build:
- https://www.ccoderun.ca/programming/darknet_faq/#how_to_build_on_linux
- https://www.ccoderun.ca/programming/darknet_faq/#how_to_build_on_windows

**Comment by PTA00** [comment]
> 
thank you for the response！
I still have a question.Does the application built have to run on a CUDA and CUDNN-installed computer?

**Comment by PTA00** [comment]
> I don't understand. In that case, why don't you build it on the computer that has the graphics card?
> 
> We cannot build it for you. We have no idea was OS you are using. (Linux, Mac, Windows?) We have no idea what version OS you are using. We have no idea what OpenCV you are using, what CUDA and CUDNN version, and which graphics card you have. This is something that you need to do.
> 
> See here to build:
> 
> * https://www.ccoderun.ca/programming/darknet_faq/#how_to_build_on_linux
> * https://www.ccoderun.ca/programming/darknet_faq/#how_to_build_on_windows

thank you for the response！
I still have a question.Does the application built have to run on a CUDA and CUDNN-installed computer?

**Comment by stephanecharette** [comment]
If you build it to run on CUDA and CUDNN?  Yes.  See `Makefile`.

**Comment by PTA00** [comment]
> If you build it to run on CUDA and CUDNN? Yes. See `Makefile`.

OK.I am building using a COMPUTER with RTX3060.😉
