### ISSUE TITLE
Can you please upload it to YouTube on VOC based image learning method?

### ISSUE THREAD

**Issue by songminkyu** [AlexeyAB/darknet#84]
HI? can you please upload it to YouTube on VOC based image learning method?
I tried to follow the manual, but the image does not work well.
I would really appreciate it if you upload it.

I love you AlexeyAB

**Comment by AlexeyAB** [comment]
Hi, do you use Windows Yolo v2 for training?
If yes, then try to use to use `yolo-voc.2.0.cfg` instead of `yolo-voc.cfg` for training.
