### ISSUE TITLE
GStreamer: Error opening bin: Unrecoverable syntax error while parsing pipeline

### ISSUE THREAD

**Issue by Moorditj** [AlexeyAB/darknet#840]
Hi,

Just trying to get some basics going

I'm using this command:

./darknet detector demo cfg/coco.data cfg/yolo.cfg yolo.weights mytestvideo -out_filename res.avi

CUDA: 9.1.85
OpenCV: 3.3.1
gcc: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

and git cloned from here:

https://github.com/AlexeyAB/darknet/tree/47c7af1cea5bbdedf1184963355e6418cb8b1b4f#how-to-train-pascal-voc-data

Any one got ideas?

**Comment by AlexeyAB** [comment]
> ./darknet detector demo cfg/coco.data cfg/yolo.cfg yolo.weights mytestvideo -out_filename res.avi

Try to detect on the well-formed videofile with corresponding extension .avi or .mp4 such as `test.mp4` instead of `mytestvideo`

**Comment by Moorditj** [comment]
all good thanks.
