### ISSUE TITLE
What different of shortcut and route?

### ISSUE THREAD

**Issue by ryotaro137** [AlexeyAB/darknet#8409]
I would like to modify the cfg of YOLOv4-tiny.
However, I do not understand the difference between shortcut and route.
I think shortcut refers to the attention on the right in the figure below, and route represents the connect on the left, is this correct?
Thank you in advance.

![image](https://user-images.githubusercontent.com/77430355/158048970-6c9389be-f78e-4169-848d-b37fbfa9ff64.png)

**Comment by abcc235** [comment]
Shortcut is to add the values of each channel, and the number of channels remains the same. Route is to stack the channels of each path, and the final number of channels is the sum of the channels of each path

**Comment by ryotaro137** [comment]
Thank you for teaching me useful information. 
I mean, I think my interpretation is right, don't you?

**Comment by abcc235** [comment]
yes，Your point is right

**Comment by ryotaro137** [comment]
Thank you!!!
