### ISSUE TITLE
Select frames for tests 

### ISSUE THREAD

**Issue by krayni** [AlexeyAB/darknet#842]
Hello,
how i can use demo to detect objects in video (but not the whole video : i need to use a period of 5 seconds).
Thanks

**Comment by TheMikeyR** [comment]
cut your video with ffmpeg is a possibility, there are nothing in this repository which makes it possible to specify start:end timestamp for detection when using video as an input.

`ffmpeg -i input.mp4 -ss 00:00:00 -to 00:00:05 -c copy output.mp4`
