### ISSUE TITLE
What is mean of [×] in SAM?

### ISSUE THREAD

**Issue by ryotaro137** [AlexeyAB/darknet#8423]
I would like to understand SAM, the model during YOLOv4. However, I am confused as to the meaning of the "x" in the diagram. Please tell me what module name this "x" represents in yolov4.cfg in darknet.

Thank you in advance.
![image](https://user-images.githubusercontent.com/77430355/159121472-77e51f80-3697-4df4-af09-463630617496.png)

**Comment by bulatnv** [comment]
Hello!
x - stands for multiplication, main idea is the same as SEnet.

[https://github.com/AlexeyAB/darknet/wiki/CFG-Parameters-in-the-different-layers](https://github.com/AlexeyAB/darknet/wiki/CFG-Parameters-in-the-different-layers)
"[sam] - Spatial Attention Module (SAM) - it multiplies elements of one layer by elements of another layer
from=-3 - relative layer number (this and previous layers should be the same size WxHxC)"

Have a look at the papers:
[ThunderNet: Towards Real-time Generic Object Detection](https://arxiv.org/pdf/1903.11752v2.pdf)
[CBAM: Convolutional Block Attention Module](https://openaccess.thecvf.com/content_ECCV_2018/papers/Sanghyun_Woo_Convolutional_Block_Attention_ECCV_2018_paper.pdf)
[SCA-CNN: Spatial and Channel-wise Attention in Convolutional Networks for Image Captioning](https://arxiv.org/pdf/1611.05594.pdf)

**Comment by ryotaro137** [comment]
Thank you for tips!!!
