### ISSUE TITLE
Get error when set batch=8 & subdivisions=1 in yolov4-csp.cfg

### ISSUE THREAD

**Issue by er778899789** [AlexeyAB/darknet#8435]
I get the error like below.

![image](https://user-images.githubusercontent.com/32409355/160048710-98eb872e-a8b7-4b41-a323-441b55c219cc.png)

When I set subdivisions=64 and it can training successfully. But it will cost a lot of time to training.
I don't want to spend so much time on training, because my dataset only have almost 300 images.
I think it don't need to cost several days to training. (Or it really need several days on training?)
How can I set subdivisions below 64 (like 16、8、or maybe less than these) and training well ?
Help me, PLZ!!

**Comment by stephanecharette** [comment]
See:  https://www.ccoderun.ca/programming/darknet_faq/#cuda_out_of_memory
And:  https://www.ccoderun.ca/programming/darknet_faq/#time_to_train

**Comment by er778899789** [comment]
@stephanecharette 
THX. I solve the problem.

**Comment by stephanecharette** [comment]
Solved how?  You should include some details some when other people run into this problem and look up your issue, they can have an idea of what needs to change.

**Comment by er778899789** [comment]
The error say need to set subdivisions = 64.
I directly set to 64, not try to set 4,8,16....... And set subdivisions = 64, it will cost almost 270 hours on training.
I change batchsize = 8 and subdivisions = 8, it can run normally, and it only need to cost 20 hours on training.
THX for helping @stephanecharette .
