### ISSUE TITLE
How to apply OCR in objects detected?

### ISSUE THREAD

**Issue by blackShine-2** [AlexeyAB/darknet#8449]
I have installed darknet and detecting license plate using IP camera. Now, I want to use OCR in the license plate region in real-time. Will anybody suggest me how should I do that?
Thank you in advance

**Comment by stephanecharette** [comment]
See:  https://github.com/stephanecharette/DarkPlate#darkplate

Or, one of my many Youtube tutorials such as https://www.youtube.com/watch?v=_BsLM4e3_oo or https://www.youtube.com/watch?v=jz97_-PCxl4

**Comment by blackShine-2** [comment]
> See: https://github.com/stephanecharette/DarkPlate#darkplate
> 
> Or, one of my many Youtube tutorials such as https://www.youtube.com/watch?v=_BsLM4e3_oo or https://www.youtube.com/watch?v=jz97_-PCxl4


You are amazing. You have created almost everything related to darknet. How, can I customize myown licenseplate? I need to use characters other than english. So.

**Comment by blackShine-2** [comment]
> See: https://github.com/stephanecharette/DarkPlate#darkplate
> 
> Or, one of my many Youtube tutorials such as https://www.youtube.com/watch?v=_BsLM4e3_oo or https://www.youtube.com/watch?v=jz97_-PCxl4

You are amazing. You have created almost everything related to darknet.

I have following queries.

1. How, can I customize myown licenseplate? I need to use characters other than english language.

2. Again, I have already labeled the images using some other GUI. The annotations are in .txt file. I hope this does not make a problem. Or should I use darkmark only?

3. Did you use OCR or did you train each numbers and letters? I found there are 37 classes in darkplate repo.

**Comment by stephanecharette** [comment]
> 1. How, can I customize myown licenseplate? I need to use characters other than english language.

See the youtube videos posted above.  I have lots of tutorials showing how to do things related to Darkplate and Darknet.

> 2. Again, I have already labeled the images using some other GUI. The annotations are in .txt file. I hope this does not make a problem. Or should I use darkmark only?

If you choose to use DarkMark, it will automatically import the .txt annotations.

> 3. Did you use OCR or did you train each numbers and letters? I found there are 37 classes in darkplate repo.

The DarkPlate project uses Darknet/YOLO to do OCR.
