### ISSUE TITLE
Gain access to bounding box data

### ISSUE THREAD

**Issue by lesreaper** [AlexeyAB/darknet#846]
Hello again!

I’m back to try a different approach with Yolo v2 or V3. The custom class worked great you recommended here, but the ID’ing of a person (full body without facial landmarks) which I tried to run in a separate instance, is just beyond the current traditional cNN setups I think. Too many possibilities of clothing destroys the network generalizing and prediction.

So, for my next attempt, I want to take an image and get the array values (don’t want to save to disk) of the contents of the bounding boxes (top 3 or 4 above a threshold of 0.4 or so) and also the quantity of those items in image. That info will be sent to another program for further real time analysis.

Where in the code is that information found?

My C is currently terrible (though improving), so how would I go about accessing that via python if possible?

**Comment by AlexeyAB** [comment]
@lesreaper Hello,

If you want to use Python, you can look at this example: https://github.com/AlexeyAB/darknet/blob/master/darknet.py

For using darknet.py you should build with `LIBSO=1` in the Makefile on Linux, or build `yolo_cpp_dll.sln` on Windows.

1. by default it reads image from disk to the Darknet `image` structure using Darknet function `load_image()`: https://github.com/AlexeyAB/darknet/blob/24f563ce7165c2c44486fe8d0a2caea8d7c5a887/darknet.py#L224

2. but you can read image from disk to the NumPy array using OpenCV: https://github.com/AlexeyAB/darknet/blob/24f563ce7165c2c44486fe8d0a2caea8d7c5a887/darknet.py#L225-L226
    and then convert it to the Darknet `image` structure: https://github.com/AlexeyAB/darknet/blob/24f563ce7165c2c44486fe8d0a2caea8d7c5a887/darknet.py#L229

3. or you can do the same by using scipy: https://github.com/AlexeyAB/darknet/blob/24f563ce7165c2c44486fe8d0a2caea8d7c5a887/darknet.py#L227-L229

For 2 & 3 cases you should comment this line: https://github.com/AlexeyAB/darknet/blob/24f563ce7165c2c44486fe8d0a2caea8d7c5a887/darknet.py#L266

You can see what packages it requires: https://github.com/AlexeyAB/darknet/blob/master/build/darknet/x64/darknet_python.cmd

**Comment by lesreaper** [comment]
Hmmm....

I’m not sure how this gets me access to the items within the bounding box, as if I had a bounding box around a person and then saved just that part of the image.

**Comment by dexception** [comment]
@AlexeyAB 

Which method can we call to process one frame of webcam ?

```
    capture = cv2.VideoCapture(0)
    print(capture.get(cv2.CAP_PROP_FPS))
    
    capture.set(cv2.CAP_PROP_FRAME_WIDTH, 1024)
    capture.set(cv2.CAP_PROP_FRAME_HEIGHT, 768)

    while True:
        ret, frame = capture.read()
        results = model.detect([frame], verbose=0)
        r = results[0]
        #which method i need to call to process opencv frame ?
        cv2.imshow('frame', frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    capture.release()
    cv2.destroyAllWindows()
```

**Comment by AlexeyAB** [comment]
@lesreaper I mean if you don't know C but know Python, you can try to implement your logic based on the example: https://github.com/AlexeyAB/darknet/blob/master/darknet.py

> I’m not sure how this gets me access to the items within the bounding box, as if I had a bounding box around a person and then saved just that part of the image.

Do you want to save to the files parts of image with objects?

> So, for my next attempt, I want to take an image and get the array values (don’t want to save to disk) of the contents of the bounding boxes (top 3 or 4 above a threshold of 0.4 or so) and also the quantity of those items in image. That info will be sent to another program for further real time analysis.

Or do you want to get only text (coordinates, class_id and probabilty) of objects?
How do you want to send it to another program, by using TCP/IP sockets? 

----

If you want to send only text (coordinates, class_id and probabilty) of objects to the your real-time program by using TCP/IP sockets, then you can do:


1. add here: https://github.com/AlexeyAB/darknet/blob/94c84da85015f0dcc6deaff53b24ff46a730711c/src/image.c#L439
```cpp
#ifdef _WIN32  
#pragma comment(lib, "ws2_32.lib")
#include <winsock.h>
#include <windows.h>
#include <time.h>
#define PORT        unsigned long
#define ADDRPOINTER   int*
#else       /* ! win32 */
#include <unistd.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#define PORT        unsigned short
#define SOCKET    int
#define HOSTENT  struct hostent
#define SOCKADDR    struct sockaddr
#define SOCKADDR_IN  struct sockaddr_in
#define ADDRPOINTER  unsigned int*
#define INVALID_SOCKET -1
#define SOCKET_ERROR   -1
#endif /* _WIN32 */
```

2. add here: https://github.com/AlexeyAB/darknet/blob/94c84da85015f0dcc6deaff53b24ff46a730711c/src/image.c#L463
these code:
```cpp
			if(dets[i].prob[class_id] > 0.4) // if probability > 40%
			{
				static int sock;
				static struct sockaddr_in server;
				static int initialized = 0;

				if (initialized == 0) {
#ifdef _WIN32  
					static WSADATA w;
					WSAStartup(MAKEWORD(2, 1), &w);
#endif

					sock = socket(AF_INET, SOCK_STREAM, 0);

					server.sin_family = AF_INET;
					server.sin_addr.s_addr = inet_addr("127.0.0.1"); // server IP
					server.sin_port = htons(1010);  // server Port

					if (connect(sock, (struct sockaddr *)&server, sizeof(server)) == 0)
					{
						initialized = 1;  // successfully connected to the server
					}
				}


				if (initialized == 1)
				{
					size_t length;
					char *ptr;
					ptr = (char*)names[class_id]; // send "dog"
					length = strlen(ptr);

					while (length > 0)
					{
						int i;
						i = send(sock, ptr, length, 0);
						if (i < 1) break;
						ptr += i;
						length -= i;
					}
				}
			}
```

3. Run your real-time Application (Server), and change in the code above ip  `127.0.0.1` and port `1010`  to the one which of the server.

4. Run Darknet (client):
`./darknet detector demo data/coco.data cfg/yolov3.cfg yolov3.weights -thresh 0.25 test.mp4`
 (without running of server, the Darknet will work slowly)

**Comment by AlexeyAB** [comment]
@dexception 
Something like this:

```python
    capture = cv2.VideoCapture(0)
    print(capture.get(cv2.CAP_PROP_FPS))
    
    capture.set(cv2.CAP_PROP_FRAME_WIDTH, 1024)
    capture.set(cv2.CAP_PROP_FRAME_HEIGHT, 768)

    while True:
        ret, frame = capture.read()
        im, arr = array_to_image(custom_image)
        #results = model.detect(im, verbose=0)
        predict_image(net, im)
        dets = get_network_boxes(net, im.w, im.h, thresh, hier_thresh, None, 0, pnum, 1)
        if nms:
            do_nms_sort(dets, num, meta.classes, nms)
        res = []
        if debug: print("about to range")
        for j in range(num):
            for i in range(meta.classes):
                if dets[j].prob[i] > 0:
                    b = dets[j].bbox
                    nameTag = meta.names[i]
                    res.append((nameTag, dets[j].prob[i], (b.x, b.y, b.w, b.h)))
        print(res)
        #r = results[0]
        #which method i need to call to process opencv frame ?
        cv2.imshow('frame', frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    capture.release()
    cv2.destroyAllWindows()
```

**Comment by dexception** [comment]
@AlexeyAB 

I guess i am passing the wrong type... 

```
 106 yolo
Total BFLOPS 65.864
Loading weights from yolov3.weights...
 seen 64
Done!
Loaded - names_list: data/coco.names, classes = 80
0.0
Traceback (most recent call last):
  File "darknet2.py", line 491, in <module>
    print(capture())
  File "darknet2.py", line 471, in capture
    predict_image(netMain, im)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: expected IMAGE instance instead of tuple
```

```
def capture(thresh=.5, hier_thresh=.5, nms=.45, configPath = "./cfg/yolov3.cfg", weightPath = "yolov3.weights", metaPath= "./data/coco.data", showImage= True, makeImageOnly = False, initOnly= False):
    global metaMain, netMain, altNames #pylint: disable=W0603
    assert 0 < thresh < 1, "Threshold should be a float between zero and one (non-inclusive)"
    if not os.path.exists(configPath):
        raise ValueError("Invalid config path `"+os.path.abspath(configPath)+"`")
    if not os.path.exists(weightPath):
        raise ValueError("Invalid weight path `"+os.path.abspath(weightPath)+"`")
    if not os.path.exists(metaPath):
        raise ValueError("Invalid data file path `"+os.path.abspath(metaPath)+"`")
    if netMain is None:
        netMain = load_net_custom(configPath.encode("ascii"), weightPath.encode("ascii"), 0, 1)  # batch size = 1
    if metaMain is None:
        metaMain = load_meta(metaPath.encode("ascii"))
    if altNames is None:
        # In Python 3, the metafile default access craps out on Windows (but not Linux)
        # Read the names file and create a list to feed to detect
        try:
            with open(metaPath) as metaFH:
                metaContents = metaFH.read()
                import re
                match = re.search("names *= *(.*)$", metaContents, re.IGNORECASE | re.MULTILINE)
                if match:
                    result = match.group(1)
                else:
                    result = None
                try:
                    if os.path.exists(result):
                        with open(result) as namesFH:
                            namesList = namesFH.read().strip().split("\n")
                            altNames = [x.strip() for x in namesList]
                except TypeError:
                    pass
        except Exception:
            pass
    if initOnly:
        print("Initialized detector")
        return None
    
    num = c_int(0)
    pnum = pointer(num)
    num = pnum[0]

    capture = cv2.VideoCapture(0)
    print(capture.get(cv2.CAP_PROP_FPS))
    
    capture.set(cv2.CAP_PROP_FRAME_WIDTH, 1024)
    capture.set(cv2.CAP_PROP_FRAME_HEIGHT, 768)

    while True:
        ret, frame = capture.read()
        im = array_to_image(frame)
        predict_image(netMain, im)
        dets = get_network_boxes(netMain, im.w, im.h, thresh, hier_thresh, None, 0, pnum, 1)
        if nms:
            do_nms_sort(dets, num, metaMain.classes, nms)
        res = []
        for j in range(num):
            for i in range(metaMain.classes):
                if dets[j].prob[i] > 0:
                    b = dets[j].bbox
                    nameTag = metaMain.names[i]
                    res.append((nameTag, dets[j].prob[i], (b.x, b.y, b.w, b.h)))
        print(res)
        cv2.imshow('frame', frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    capture.release()
    cv2.destroyAllWindows()

if __name__ == "__main__":
    print(capture())
```

**Comment by dexception** [comment]
@AlexeyAB 
My bad !!

Its working but the amount of CPU it is taking is too much ! 50% CPU usage !

```
def capture(thresh=.5, hier_thresh=.5, nms=.45, configPath = "./cfg/yolov3.cfg", weightPath = "yolov3.weights", metaPath= "./data/coco.data", showImage= True, makeImageOnly = False, initOnly= False):
    global metaMain, netMain, altNames #pylint: disable=W0603
    netMain = load_net_custom(configPath.encode("ascii"), weightPath.encode("ascii"), 0, 1)  # batch size = 1
    metaMain = load_meta(metaPath.encode("ascii"))
    
    num = c_int(0)
    pnum = pointer(num)
    num = pnum[0]

    capture = cv2.VideoCapture(0)
    print(capture.get(cv2.CAP_PROP_FPS))
    
    capture.set(cv2.CAP_PROP_FRAME_WIDTH, 1024)
    capture.set(cv2.CAP_PROP_FRAME_HEIGHT, 768)

    while True:
        ret, frame = capture.read()
        im, arr = array_to_image(frame)
        predict_image(netMain, im)
        dets = get_network_boxes(netMain, im.w, im.h, thresh, hier_thresh, None, 0, pnum, 1)
        if nms:
            do_nms_sort(dets, num, metaMain.classes, nms)
        res = []
        for j in range(num):
            for i in range(metaMain.classes):
                if dets[j].prob[i] > 0:
                    b = dets[j].bbox
                    nameTag = metaMain.names[i]
                    res.append((nameTag, dets[j].prob[i], (b.x, b.y, b.w, b.h)))
        print(res)
        cv2.imshow('frame', frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    capture.release()
    cv2.destroyAllWindows()

if __name__ == "__main__":
    print(capture())

```

**Comment by AlexeyAB** [comment]
@dexception Try this:
```python
        ret, frame = capture.read()
        resized_frame= cv.resize(frame, (lib.network_width(netMain), lib.network_height(netMain)), interpolation = cv.INTER_LINEAR)
        im, arr = array_to_image(resized_frame)
        predict_image(netMain, im)
```

Or try to optimize this function:
https://github.com/AlexeyAB/darknet/blob/c1bb8c129d7d4d8fc85348d5e7ac5441fa36ead5/darknet.py#L195-L205

**Comment by lesreaper** [comment]
@AlexeyAB 

Thank you for the sending text code. I may incorporate that later in the project.

Right now, I'm looking to 'save to the files parts of image with objects'.

I'd like it to be the raw array data, versus having to waste the read/write (ms) to write and then read it again further along the python chain.

**Comment by AlexeyAB** [comment]
@lesreaper 

1. Update your code from GitHub
2. Un-comment these lines: https://github.com/AlexeyAB/darknet/blob/7b7c669f4952479ac7667cf7def4d09109cc6789/src/image.c#L522-L529
3. Create `result_img` directory near with `darknet`-executable file
4. Run darknet on the video file:
`./darknet detector demo data/coco.data cfg/yolov3.cfg yolov3.weights test.mp4`
5. Look at the `result_img` directory
You will see files like `img_<frame_id>_<img_id>_<class_id>.jpg`

**Comment by lesreaper** [comment]
@AlexeyAB , that is awesome. Thanks for pointing out where in the code it was and showing how to set it up.

It's very close to the final output for me. I'll need to drop the bounding boxes that appear in the images, as well as figure out a better number scheme to keep things tied together, but this is an awesome push in the right direction!

I appreciate all the help again. You're the best!

**Comment by AlexeyAB** [comment]
@lesreaper Update your code again from GitHub.

And uncomment these lines: https://github.com/AlexeyAB/darknet/blob/a720bf74e233c956e5281871ede722a2c7cf54db/src/image.c#L520-L534

**Comment by lesreaper** [comment]
@AlexeyAB Works great! Thank you!

**Comment by PallawiSinghal** [comment]
> @lesreaper Hello,
> 
> If you want to use Python, you can look at this example: https://github.com/AlexeyAB/darknet/blob/master/darknet.py
> 
> For using darknet.py you should build with `LIBSO=1` in the Makefile on Linux, or build `yolo_cpp_dll.sln` on Windows.
> 
> 1. by default it reads image from disk to the Darknet `image` structure using Darknet function `load_image()`: 
>      
>        
>          [darknet/darknet.py](https://github.com/AlexeyAB/darknet/blob/24f563ce7165c2c44486fe8d0a2caea8d7c5a887/darknet.py#L224)
>        
>        
>             Line 224
>          in
>          [24f563c](/AlexeyAB/darknet/commit/24f563ce7165c2c44486fe8d0a2caea8d7c5a887)
>        
>        
>        
>        
>    
>            
>              
>               im = load_image(image, 0, 0)
> 2. but you can read image from disk to the NumPy array using OpenCV: 
>      
>        
>          [darknet/darknet.py](https://github.com/AlexeyAB/darknet/blob/24f563ce7165c2c44486fe8d0a2caea8d7c5a887/darknet.py#L225-L226)
>        
>        
>            Lines 225 to 226
>          in
>          [24f563c](/AlexeyAB/darknet/commit/24f563ce7165c2c44486fe8d0a2caea8d7c5a887)
>        
>        
>        
>        
>    
>            
>              
>               #import cv2 
>            
>    
>            
>              
>               #custom_image = cv2.imread(image) # use: detect(,,imagePath,) 
>            
>        
>      
>    
>    
>    and then convert it to the Darknet `image` structure: 
>      
>        
>          [darknet/darknet.py](https://github.com/AlexeyAB/darknet/blob/24f563ce7165c2c44486fe8d0a2caea8d7c5a887/darknet.py#L229)
>        
>        
>             Line 229
>          in
>          [24f563c](/AlexeyAB/darknet/commit/24f563ce7165c2c44486fe8d0a2caea8d7c5a887)
>        
>        
>        
>        
>    
>            
>              
>               #im, arr = array_to_image(custom_image)		# you should comment line below: free_image(im)
> 3. or you can do the same by using scipy: 
>      
>        
>          [darknet/darknet.py](https://github.com/AlexeyAB/darknet/blob/24f563ce7165c2c44486fe8d0a2caea8d7c5a887/darknet.py#L227-L229)
>        
>        
>            Lines 227 to 229
>          in
>          [24f563c](/AlexeyAB/darknet/commit/24f563ce7165c2c44486fe8d0a2caea8d7c5a887)
>        
>        
>        
>        
>    
>            
>              
>               #import scipy.misc 
>            
>    
>            
>              
>               #custom_image = scipy.misc.imread(image) 
>            
>    
>            
>              
>               #im, arr = array_to_image(custom_image)		# you should comment line below: free_image(im)
> 
> For 2 & 3 cases you should comment this line:
> 
> [darknet/darknet.py](https://github.com/AlexeyAB/darknet/blob/24f563ce7165c2c44486fe8d0a2caea8d7c5a887/darknet.py#L266)
> 
> Line 266 in [24f563c](/AlexeyAB/darknet/commit/24f563ce7165c2c44486fe8d0a2caea8d7c5a887)
> 
>  free_image(im) 
> You can see what packages it requires: https://github.com/AlexeyAB/darknet/blob/master/build/darknet/x64/darknet_python.cmd

Thank you for the help. I am training on grayscale and I need run detect on grayscale image. Can you please guide me.
