### ISSUE TITLE
Wrong mask in yolov4-tiny.cfg

### ISSUE THREAD

**Issue by spasserkongen** [AlexeyAB/darknet#8483]
in the default yolov4-tiny.cfg (avilable from here https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4-tiny.cfg) the last yolo-layer uses mask = 1,2,3. Shouldnt this be mask = 0,1,2? anchor = 3 is used in both yolo-output layers

**Comment by stephanecharette** [comment]
Yes, do a search for it in the github issues, this is a well-known typo.

**Comment by spasserkongen** [comment]
okay fair enough, case closed I guess.
