### ISSUE TITLE
How to run YOLO (darknet) build on one computer to another computer in Windows 10?

### ISSUE THREAD

**Issue by blackShine-2** [AlexeyAB/darknet#8492]
I have installed and build darknet in windows 10 using Cmake. Now, for running the same built darknet and training weights in another windows 10 computer, do I have to repeat all the process again (downloading, cmaking and all), or is there a way to use without all these process?

**Comment by stephanecharette** [comment]
Same version of OpenCV?  Same version of CUDA?  Same version of CUDNN?  Same GPU hardware?  Same CPU hardware?  Same Visual Studio C++ runtime?  Sure, copy the executable.

But otherwise, or if you aren't certain, it is probably wiser to rebuild.
