### ISSUE TITLE
Training error with frozen layer 

### ISSUE THREAD

**Issue by Franz777-iot** [AlexeyAB/darknet#8506]
Hello was get an error while training with the frozen layer (frozen layer at 136) , How to solve this problem?
Here's the scenario, I run all the program in Google Colab

**Run command :**
```
!./darknet detector train data/obj.data cfg/csdarknet53-panet-spp-mish.cfg yolov4.conv.137 -dont_show -map -clear
```

**Modified .cfg file (freeze layer from 1 to 136) :**
```
stopbackward=1

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=256
activation=mish
```

**Error log :**
```
Allocate additional workspace_size = 52.43 MB 
Loading weights from yolov4.conv.137...
 seen 64, trained: 0 K-images (0 Kilo-batches_64) 
Done! Loaded 137 layers from weights-file 
Learning Rate: 0.001, Momentum: 0.949, Decay: 0.0005
 Detection layer: 139 - type = 28 
 Detection layer: 150 - type = 28 
 Detection layer: 161 - type = 28 
Resizing, random_coef = 1.40 

 608 x 608 
 Create 6 permanent cpu-threads 
 try to allocate additional workspace_size = 106.46 MB 
 CUDA allocate done! 
Loaded: 0.000047 seconds

 CUDA Error Prev: an illegal memory access was encountered
Darknet error location: ./src/dark_cuda.c, check_error, line #80
CUDA Error Prev: an illegal memory access was encountered: File exists
```

I have already tried to freeze another layer and it seems to work at the first n-iteration, but at the end get the same error

Thank you in advance

**Comment by slavazhulanov** [comment]
Have you found a solution to your problem?

**Comment by Franz777-iot** [comment]
Yes, I already found the solution. You cannot just simply put stopbackward=1 to a random line in the .cfg file.
From what I found, you only can put stopbackward=1 at the last layer after concatenation from CSP blocks, I use the Netron application to visualize the layer structure and make it easier to find the last CSP blocks. Hope can help u guys

**Comment by slavazhulanov** [comment]
@Franz777-iot Please explain your answer. What are CSP blocks? How to find them?
