### ISSUE TITLE
RTX 3060 and Cuda 11.6 Not Compatible

### ISSUE THREAD

**Issue by yuviabhi** [AlexeyAB/darknet#8539]
Is it possible to run on `CUDA 11.6 `and `RTX 3060 GPU`?

**Comment by saikatbasu97** [comment]
same issue facing..

**Comment by hackerfactor** [comment]
I'm using an RTX 3060.  I have darknet working well with cuda 10.1.  I've never been able to get it to work with cuda 11.x.

NOTE: I don't know if it's just me, or if there's something else going on. Give how poorly documented the cuda installation is, I decided it wasn't worth the time to find out why it wasn't working.

**Comment by stephanecharette** [comment]
Should be fine.  I know of nothing that would prevent it from working.  I'm personally using a RTX 3090 and 11.7, but I was using 11.6 prior to upgrading.

Not that Darknet doesn't work with CUDA 10.1.  Not sure how @hackerfactor got it working, unless it is a very old version of Darknet, or custom modifications to the source code to comment out the calls into the new CUDA functionality.  You'll note that [on the list of requirements in the readme.md file](https://github.com/AlexeyAB/darknet#requirements-for-windows-linux-and-macos), Darknet requires CUDA 10.2 or newer.

**Comment by clemtaylor** [comment]
FWIW I've been training with darknet using cuda-11.7 and cudnn 8.4.0 on an RTX3060 without problems. Just wish I had a better GPU for training. Maybe the 4000s will actually be purchasable.
