### ISSUE TITLE
What does mean partial command in yolo-tiny train section

### ISSUE THREAD

**Issue by Biblbrox** [AlexeyAB/darknet#8544]
Hello, I can't understand what does mean "partial" in command (Yolov4-tiny train section):
`darknet.exe partial cfg/yolov4-tiny-custom.cfg yolov4-tiny.weights yolov4-tiny.conv.29 29`

It is related to pretrained weights?

**Comment by LanguageFlowCho** [comment]
Hello, the partial I know is a work to extract NNs for custom training again from weights that have been trained.
Did you solve your question?

**Comment by Biblbrox** [comment]
> Hello, the partial I know is a work to extract the NN layer for custom learning again from the weights that have been trained.
> Did you solve your question?

Yes, thanks
