### ISSUE TITLE
5 FPS in yolov4 and yolov3 using RTX3060

### ISSUE THREAD

**Issue by MatheusCaltran** [AlexeyAB/darknet#8593]
Operating System: ubuntu 20.04
GPU: RTX 3060 Laptop
NVIDIA Driver: 515.48.07
CUDA: cuda 11.2 
cuDNN: 8.1.0
openCV: 4.2.0

Even changing between the yolov4 and yolov3 model I only get 5 fps with the GPU, CUDNN, CUDNN_HALF makefile to 1, if I put 0 in the makefile I have 1 FPS

code I'm using to test:
./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights
![Captura de tela de 2022-07-05 16-12-30](https://user-images.githubusercontent.com/88856093/177405446-3f070a88-9216-4281-9ac8-3ff476592697.png)

./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights
![Captura de tela de 2022-07-05 16-11-55](https://user-images.githubusercontent.com/88856093/177405457-f3514505-32d9-44dd-ae16-e9453261db0e.png)

![Captura de tela de 2022-07-05 16-13-28](https://user-images.githubusercontent.com/88856093/177405507-b22d087f-33c8-42bd-b98b-0d2d0f00664a.png)

**Comment by bariscankurtkaya** [comment]
> Operating System: ubuntu 20.04 GPU: RTX 3060 Laptop NVIDIA Driver: 515.48.07 CUDA: cuda 11.2 cuDNN: 8.1.0 openCV: 4.2.0
> 
> Even changing between the yolov4 and yolov3 model I only get 5 fps with the GPU, CUDNN, CUDNN_HALF makefile to 1, if I put 0 in the makefile I have 1 FPS
> 
> code I'm using to test: ./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights ![Captura de tela de 2022-07-05 16-12-30](https://user-images.githubusercontent.com/88856093/177405446-3f070a88-9216-4281-9ac8-3ff476592697.png)
> 
> ./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights ![Captura de tela de 2022-07-05 16-11-55](https://user-images.githubusercontent.com/88856093/177405457-f3514505-32d9-44dd-ae16-e9453261db0e.png)
> 
> ![Captura de tela de 2022-07-05 16-13-28](https://user-images.githubusercontent.com/88856093/177405507-b22d087f-33c8-42bd-b98b-0d2d0f00664a.png)

Hello! Did you change anything on the yolov4.cfg files and could you copy-paste your makefile?

**Comment by bariscankurtkaya** [comment]
@MatheusCaltran Actually, I didn't see any problem on your makefile.txt 

Try to decrease width=416 and height=416 in the [yolo.cfg file](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4.cfg)

and could you tell me your image resolution? Also you can look for this issue thread too. https://github.com/pjreddie/darknet/issues/80

**Comment by MatheusCaltran** [comment]
I made the change here to 416 and I still have 5 fps, I even tested it on yolo-tinyv4 and it still has 5 fps, it seems that there is something that limits the GPU to be used


I will install an older version of the nvidia and cuda driver, if you find something you can send it here, thanks a lot for the help

**Comment by stephanecharette** [comment]
There is something else that you are doing -- or not doing? -- because I'm getting 413.8 FPS on my 3090 when using YOLOv3-tiny @ 416x416:  https://www.ccoderun.ca/programming/2021-10-16_darknet_fps/

**Comment by bariscankurtkaya** [comment]
Hey @MatheusCaltran ! Could you solve the problem?

**Comment by MatheusCaltran** [comment]
I still haven't found any solution, I downgraded your version and it's still 5 fps

**Comment by MatheusCaltran** [comment]
well I have an installation document that I created based on the old computer I used to help me install this new notebook that I'm using so I don't have a problem (but even so team) follow the step by step:

install NVIDIA DRIVER 515 using programs and updates;

sudo apt install git;

**Comment by bariscankurtkaya** [comment]
@MatheusCaltran sometimes Cuda can be a pain. I remember I tried for more than a week to install everything correctly. After that, I found this link [download documentation](https://medium.com/analytics-vidhya/install-cuda-11-2-cudnn-8-1-0-and-python-3-9-on-rtx3090-for-deep-learning-fcf96c95f7a1) and after that, I could install it correctly every time.

I think you don't need to uninstall and install the driver again. I guess you can skip that part.

On the other hand, I couldn't understand why did you unzip cudnn v8.1.0.77 and copy to the inside of the library, and after that dpkg -install to cudnn_8.1.1.33? I think cudnn part creates the problem.

I hope finally we can figure out the solution.

**Comment by MatheusCaltran** [comment]
I also checked this, so I formatted the notebook and installed everything again by changing:

sudo dpkg -i libcudnn8_8.1.0.77-1+cuda11.2_amd64.deb

sudo dpkg -i libcudnn8-dev_8.1.0.77-1+cuda11.2_amd64.deb

sudo dpkg -i libcudnn8-samples_8.1.0.77-1+cuda11.2_amd64.deb

but continuous with 5 FP
[Screencast from 13-07-2022 19:40:43.webm](https://user-images.githubusercontent.com/88856093/178849261-432b3318-316f-48d2-b0ee-a3a254e36cd4.webm)
S

**Comment by bariscankurtkaya** [comment]
@MatheusCaltran It says cudnn_half is 0 right now did you change the makefile ?

**Comment by MatheusCaltran** [comment]
yes I changed

**Comment by bariscankurtkaya** [comment]
@MatheusCaltran I think we finally fixed it!!! Congrats! Have a nice day. I think you can close the issue. If you have any problem don't hesitate to write.

**Comment by MatheusCaltran** [comment]
thanks

**Comment by MatheusCaltran** [comment]
thanks
