### ISSUE TITLE
Yolov7-tiny.cfg trained on pytorch

### ISSUE THREAD

**Issue by Noodlekingsfl** [AlexeyAB/darknet#8602]
>I’ve managed to train both cfg/.yaml

You mentioned you trained it on pytorch and converted it to darknet and expected accuracy to be less on darknet training.

my question is how did you convert over to .weights or train in pytorch for .weights

**Comment by Noodlekingsfl** [comment]
@AlexeyAB  any input regarding this?

**Comment by AlexeyAB** [comment]
You can train cfg-file https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov7-tiny.cfg using this repo: https://github.com/WongKinYiu/yolor

Just use:
* `activation=logistic` for Darknet
* `activation=linear` for Pytorch

In these layers:
* https://github.com/AlexeyAB/darknet/blob/25505164a3bd6235c75deaad325878ceda90249a/cfg/yolov7-tiny.cfg#L598
* https://github.com/AlexeyAB/darknet/blob/25505164a3bd6235c75deaad325878ceda90249a/cfg/yolov7-tiny.cfg#L641
* https://github.com/AlexeyAB/darknet/blob/25505164a3bd6235c75deaad325878ceda90249a/cfg/yolov7-tiny.cfg#L684

**Comment by Noodlekingsfl** [comment]
Thanks man really appreciate it

**Comment by Noodlekingsfl** [comment]
`AssertionError: Unsupported fields ['objectness_smooth', 'resize', 'obj_normalizer', 'new_coords', 'max_delta'] in cfg/yolov7_tiny.cfg. See https://github.com/ultralytics/yolov3/issues/631`

assuming you commented these out to succeed?

**Comment by AlexeyAB** [comment]
@Noodlekingsfl 
You can Train and Detect
* on Pytorch using this cfg-file: https://raw.githubusercontent.com/WongKinYiu/yolov7/darknet/cfg/yolov7-tiny.cfg
* on Darknet using this cfg-file: https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov7-tiny.cfg

while weights are the same

**Comment by psj6335490** [comment]
how i get weight
