### ISSUE TITLE
Unkown OS, unsupported for Windows 11

### ISSUE THREAD

**Issue by AlizerUncaged** [AlexeyAB/darknet#8604]
I got this error when building darknet in Windows 11:

> PS D:\X\darknet> ./build.ps1
> Transcript started, output file is D:\X\darknet/build.log
> Build script version 2.0.0, utils module version 0.0.2
> Enable vcpkg to install dependencies (yes/no): yes
> Enable CUDA integration (yes/no): yes
> Enable CUDNN optional dependency (yes/no): yes
> Enable OpenCV optional dependency (yes/no): yes
> PowerShell version:
> Major  Minor  Build  Revision
> -----  -----  -----  --------
> 5      1      22000  653
> vcpkg bootstrap script: bootstrap-vcpkg.bat
> CUDA is enabled
> CUDNN is enabled
> OPENCV is enabled
> OPENCV with CUDA extension is not enabled, you can enable it passing -EnableOPENCV_CUDA
> VCPKG is enabled
> VCPKG will be updated to latest version if found
> VisualStudio integration is enabled, please pass -DoNotSetupVS to the script to disable
> Yolo C# wrapper integration is disabled, please pass -EnableCSharpWrapper to the script to enable. You must be on Windows!
> Ninja is enabled, please pass -DoNotUseNinja to the script to disable
> ForceCPP build mode is disabled, please pass -ForceCPP to the script to enable
> Using git from D:\Program Files\Git\cmd\git.exe
> Darknet has been cloned with git and supports self-updating mechanism
> Darknet will self-update sources, please pass -DoNotUpdateDARKNET to the script to disable
> Already up to date.
> Using CMake from D:\Program Files\CMake\bin\cmake.exe
> cmake version 3.24.0-rc3
> 
> CMake suite maintained and supported by Kitware (kitware.com/cmake).
> Unable to find Ninja, downloading a portable version on-the-fly
> Unknown OS, unsupported
> Press any key to continue...

Add support for Windows 11?

**Comment by cenit** [comment]
thanks for noticing, I will add support for win11 today

**Comment by cenit** [comment]
yes it's a regression if you use Windows Powershell and not the latest powershell.
I am already testing a fix

**Comment by cenit** [comment]
can you please try PR #8607 to see if it fixes the problem for you?
