### ISSUE TITLE
Number of training images dependent on number of sources?

### ISSUE THREAD

**Issue by CAT1210** [AlexeyAB/darknet#8610]
I have read a bit about the ideal number of training images because I am trying to make training more efficient for my use case. Right now, I have 12 classes and 105K images for those 12 classes and have read that, ideally, at least 2000 images for each class is recommended.

I broke my images up into class and found in most cases I have at least 2000 images each, some classes much, much more (for most important things like cats and people in my everyday use). Then I started to wonder if the source matters. I have 7 IP cameras around my home, each with very different images (scenery, distance to objects I want to detect, even resolutions--some are 4K, some are only 720p). Would it make sense to have 2000 images for each class for each camera image? Or should that even matter?

I do train yolov4 models, which, of course, takes quite a lot of time but end up with good results. Breaking up the training in a nicer way is appealing to me from a dataset perspective and image organization. I have tried tiny and I love how quickly that trains but the accuracy is just not good enough by the end of training for me.

**Comment by stephanecharette** [comment]
Read this:  https://www.ccoderun.ca/programming/darknet_faq/#how_many_images

It doesn't matter what resolution you use.  Before Darknet looks at it, the images are resized to match the network dimensions.  So even if you have 999999x999999 images, by the time Darknet/YOLO looks at it, the image will be 416x416 or whatever network dimension you are using.

Remember that 50% of your images should be negative samples.  Could this be why you say tiny isn't good enough?  Cause YOLOv4-tiny is usually more than enough, especially if what you are trying to find is simple objects like people and pets around the house.

**Comment by CAT1210** [comment]
Thank you for that input. Yes, I had read that prior and where I took a lot of my information for wanting to organize my data. I just wasn't sure if the different scenes from each camera would need different datasets. I play with resolution a lot. I have a trained 416x416 model that I keep trained for when I am training my main model (an 832x832 model) since the gpu will only handle running the 416 while training a higher resolution.

Oh yeah, I have 50k images of classes I want detected and 54K negative samples for my original dataset so I don't think that is why tiny doesn't work well for me. I tried running several tests to figure out tiny because I really want it to work for speed of training, it works extremely well on license plates (to fire routines for smart home) but my most trained class (most images and negatively-geared images), which is person, it gives far lower accuracy. The tiny model I have is an 832x832 that trained through the entire 105K iterations, my 416x416 v4 is trained through 12k iterations, and my 832x832 v4 is trained through 26k iterations and the tiny model rarely gives accuracy as good as the lesser trained v4 models. Below are a couple of good examples of this. My v4 models are low trained because I started all over but results are still better than tiny.

**416 model at 608:**
![Garage 20220718-181044 - 608_832 jpg-detect608](https://user-images.githubusercontent.com/74838388/180833514-15a54717-c678-484f-a510-b0ccfff5bc88.jpg)
![Garage 20220720-184416 - 608_832 jpg-detect608](https://user-images.githubusercontent.com/74838388/180834149-4e142409-4813-4b6a-a861-a234769a592b.jpg)

**832 model at 1088:**
![Garage 20220718-181044 - 608_832 jpg-detect832](https://user-images.githubusercontent.com/74838388/180833611-af18d04e-ae49-43cc-9e11-a502898b23ce.jpg)
![Garage 20220720-184416 - 608_832 jpg-detect832](https://user-images.githubusercontent.com/74838388/180834217-971d0f41-2142-4db1-a5f5-a1b5b01673a8.jpg)

**Tiny-832 model at 1088:**
![Garage 20220718-181044 - 608_832 jpg-detectTiny](https://user-images.githubusercontent.com/74838388/180833759-9dc63751-de4a-44ca-bb6f-0ee3211260b2.jpg)
![Garage 20220720-184416 - 608_832 jpg-detectTiny](https://user-images.githubusercontent.com/74838388/180834240-b2221224-a7d3-4d99-8a19-bce70eca49a0.jpg)

**Comment by CAT1210** [comment]
Since I was put back on this path, I would like to know. does anybody know why my tiny model would be so much less accurate with my conditions and the info I provided? I would like to use tiny, but I get rid of any detections that are less than 85% and, as you can see, the simple images above while running tiny are quite a bit less than this threshold.

**Comment by CAT1210** [comment]
I'm pretty sure I figured this out for myself (why tiny is so much less accurate). I wasn't comparing apples to apples so much....random flag in tiny was not what I had set in the other v4 models.
