### ISSUE TITLE
darknet for yolov7

### ISSUE THREAD

**Issue by Miuney** [AlexeyAB/darknet#8611]
hello,are there plans to update darknet for "yolov7"?

**Comment by dragan07-07** [comment]
I am interesting in this question too. I need tiny-yolov7 pre-training model.

**Comment by Miuney** [comment]
> I am interesting in this question too. I need tiny-yolov7 pre-training model.

https://github.com/AlexeyAB/darknet/issues/8595#issue-1296709732

**Comment by Miuney** [comment]
> > I am interesting in this question too. I need tiny-yolov7 pre-training model.
> 
> [#8595 (comment)](https://github.com/AlexeyAB/darknet/issues/8595#issue-1296709732)

https://github.com/AlexeyAB/darknet/issues/8595#issuecomment-1179780967

**Comment by Miuney** [comment]
> 

i think, it will help you.

**Comment by dragan07-07** [comment]
Tnx. This is for I am looking for.

**Comment by bariscankurtkaya** [comment]
@Miuney I think the problem is solved. So, could you please close the issue?
