### ISSUE TITLE
./darknet detector test error: cannot load image

### ISSUE THREAD

**Issue by CemEntok** [AlexeyAB/darknet#8616]
- Hello, Here is the command i have been using:

`./darknet detector test /home/sureuser/objdetection/datasetYolo/250722/obj.data /home/sureuser/objdetection/datasetYolo/250722/yolov4-obj.cfg /home/sureuser/objdetection/datasetYolo/250722/backup/yolov4-obj_best.weights -ext_output -dont_show < /home/sureuser/objdetection/datasetYolo/250722/test.txt > result.txt`

- Here the inside of folder `/home/sureuser/objdetection/datasetYolo/250722`

`backup  data_knife  obj.data  obj.names  result.txt  test.txt  train.txt  yolov4.conv.137  yolov4-obj.cfg`

- Here the inside of `test.txt` file: 
`/home/sureuser/objdetection/datasetYolo/250722/data_knife/test/95_.jpg`
`/home/sureuser/objdetection/datasetYolo/250722/data_knife/test/96_.jpg`
`/home/sureuser/objdetection/datasetYolo/250722/data_knife/test/97_.jpg`
`/home/sureuser/objdetection/datasetYolo/250722/data_knife/test/98_.jpg`
`/home/sureuser/objdetection/datasetYolo/250722/data_knife/test/99_.jpg`
`/home/sureuser/objdetection/datasetYolo/250722/data_knife/test/9_.jpg`
`...`

- After using the command, the output log and the **Error** becomes:

 `CUDA-version: 11020 (11040), cuDNN: 8.2.4, CUDNN_HALF=1, GPU count: 1  
 OpenCV version: 4.6.0
 0 : compute_capability = 700, cudnn_half = 1, GPU: Tesla V100-PCIE-32GB 
   layer   filters  size/strd(dil)      input                output
   0 conv     32       3 x 3/ 1    416 x 416 x   3 ->  416 x 416 x  32 0.299 BF`
`...`
![image](https://user-images.githubusercontent.com/97525722/181459740-4cf16588-d1a2-41df-8019-75f714af7910.png)
`...`
![image](https://user-images.githubusercontent.com/97525722/181459853-6496bc77-0248-4ac6-a362-aee481acbfcc.png)

**As @stephanecharette says:**

> Did you try simple things like `file /home/sureuser/objdetection/darknet/data_knife/test/0_.jpg` or `ls -l /home/sureuser/objdetection/darknet/data_knife/test/0_.jpg`?

>Did you build a custom version of OpenCV, or did you install it as described here: https://www.ccoderun.ca/programming/darknet_faq/#opencv_and_cuda

**I did:**

- `file /home/sureuser/objdetection/darknet/data_knife/test/0_.jpg`

`/home/sureuser/objdetection/darknet/data_knife/test/0_.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 640x480, components 3`

- `ls -l /home/sureuser/objdetection/darknet/data_knife/test/0_.jpg`

`-rw-rw-r-- 1 sureuser sureuser 186768 heinä  26 13:30 /home/sureuser/objdetection/darknet/data_knife/test/0_.jpg`

- Now we can think OpenCV did not being built correctly. But, **The interesting thing is** I can use test command for a single image:

![image](https://user-images.githubusercontent.com/97525722/181461702-cd396827-81c2-4f46-8e11-2c9be412bbbd.png)

`...`
![image](https://user-images.githubusercontent.com/97525722/181462372-95526889-92ed-4d4d-a9ad-7291693c2f1f.png)

Now, is it still related with OpenCV build? If so, how single test image utility works (Does single test work without using Opencv?) and then why writing an output result.txt by loading multiple images does not work?

**Comment by bariscankurtkaya** [comment]
Hello @CemEntok, This is a little complicated way to describe the problem but I think I had an idea. Firstly, when I look for the error It says It couldn't open the image and on the other hand, I saw little differences between your paths.

`/home/sureuser/objdetection/datasetYolo/250722/data_knife/test/95_.jpg`  
`/home/sureuser/objdetection/darknet/data_knife/test/0_.jpg` 

So, maybe it can be the problem.

**Comment by CemEntok** [comment]
@bariscankurtkaya Ty for your response. The differences of paths are my mistake. Now I will show the problem in a more proper way.

- I am using single test image command like this:
- `./darknet detector test /home/sureuser/objdetection/datasetYolo/250722/obj.data /home/sureuser/objdetection/datasetYolo/250722/yolov4-obj.cfg /home/sureuser/objdetection/datasetYolo/250722/backup/yolov4-obj_best.weights -ext_output /home/sureuser/objdetection/datasetYolo/250722/data_knife/test/1c60c3a3bbddc658.jpg -dont_show`


- Here is the result screenshot:

![image](https://user-images.githubusercontent.com/97525722/182179571-f313c1fe-662a-41dd-b099-7dc24ad1f7f1.png)


- When I used test command for every image in a folder like this:


- `./darknet detector test /home/sureuser/objdetection/datasetYolo/250722/obj.data /home/sureuser/objdetection/datasetYolo/250722/yolov4-obj.cfg /home/sureuser/objdetection/datasetYolo/250722/backup/yolov4-obj_best.weights -dont_show -ext_output < /home/sureuser/objdetection/datasetYolo/250722/test.txt > result010822.txt`

- Error Becomes:


![image](https://user-images.githubusercontent.com/97525722/182180107-900a77b6-b470-4e58-8c7a-3230329ef6e8.png)


- Lets check files:

`/home/sureuser/objdetection/datasetYolo/250722/data_knife/test/9_.jpg`

> /home/sureuser/objdetection/datasetYolo/250722/data_knife/test/9_.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 640x480, components 3


![image](https://user-images.githubusercontent.com/97525722/182180371-ec5c399f-6d59-42d2-91a1-b7033841e9a4.png)


**Can someone please explain to me where the problem is ?**

P.S.
> CUDA-version: 11020 (11040), cuDNN: 8.2.4, CUDNN_HALF=1, GPU count: 1  
 OpenCV version: 4.6.0

@bariscankurtkaya @stephanecharette

**Comment by annagusevacode** [comment]
The problem is the same for me
It can't open files from the "test.txt", but works fine with the single file

Also, I've noticed that it works fine with the last image from the "test.txt" file.
And it can read any file when it stands last.
Now I'm assuming that the problem is with the delimiters between filenames, but the list in "test.txt" simply looks like:

data/image1.jpg
data/image2.jpg
data/image3.jpg

and the model would fail for data/image1.jpg and data/image2.jpg, but works for data/image3.jpg

**Comment by stephanecharette** [comment]
Are you using Windows EOL, or Linux EOL?  `\r\n` vs `\n`?  I wouldn't be surprised if Darknet is expecting just \n, so you end up with a stray \r at the end of every filename *except* for the very last image in the file.

**Comment by stephanecharette** [comment]
> So, probably darknet test might have some problems reading `\n`.

No, the opposite.  The problem is with `\r` which is specific to Windows.  Darknet incorrectly parses the lines based on '\n' which leaves behind a `\r` at the end of each line.

**Comment by CemEntok** [comment]
@annagusevacode @stephanecharette @bariscankurtkaya 

The problem is solved for me when I changed `test.txt` file format from CRLF to LF format (In VS Code, it is easy to change).

Here is the better explanation:

[https://github.com/pjreddie/darknet/issues/611#issuecomment-401942856](url)
