### ISSUE TITLE
Crash in delta_yolo class

### ISSUE THREAD

**Issue by VisionEp1** [AlexeyAB/darknet#867]
Hi,
my training crashes after some minutes (faster on multiple gpus).

The debuger says its this line: 
`   if(avg_cat) *avg_cat += output[index + stride*class_id];`

fole: yolo_layer.c
function delta_yolo_class

Error:

Access violation while reading 

(orig message:
Ausnahme ausgelöst bei 0x00007FF7317ED666 in darknet.exe: 0xC0000005: Zugriffsverletzung beim Lesen an Position 0x000001BBA0E34FB8.)
Thx in advance

**Comment by AlexeyAB** [comment]
@VisionEp1 Hi,

* what params did you set in the Makefile?

* can you get this error if you change this line to this one: 
    `if(avg_cat) *avg_cat += 1;`

* or can you get this error if you comment this line: https://github.com/AlexeyAB/darknet/blob/d01a686246550b524140d4c9c3580bf066d8d71e/src/yolo_layer.c#L117

* can you show your cfg-file?

**Comment by VisionEp1** [comment]
hi.
i did some debug myself.

this call causes the error:
 output[index + stride*class_id]

so if i change line
 if (delta[index])
to
 if (delta[index] && delta[index + stride * class_id])

it works.

But i dont know if thats a bad thing to do? 
I used the default params from yolov3.
i also checked the test dataset with the mark tool

What does the delta[index] part do?

**Comment by VisionEp1** [comment]
never mind. it still crashes.
maybe its the
output[index + stride*class_id] pointer
ill add that to the check list

**Comment by AlexeyAB** [comment]
Yes, it should be `if (delta[index + stride*class_id]){` 
But it can't lead to seg-fault if you use correct `classes=` in the [yolo]-layer and `filters=` in the previous [convolutional]-layer.

I fixed it.
1. Update your code from GitHub
2. Do: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

> change [filters=255] to filters=(classes + 5)x3 in the 3 [convolutional] before each [yolo] layer
> * https://github.com/AlexeyAB/darknet/blob/0039fd26786ab5f71d5af725fc18b3f521e7acfd/cfg/yolov3.cfg#L603
> * https://github.com/AlexeyAB/darknet/blob/0039fd26786ab5f71d5af725fc18b3f521e7acfd/cfg/yolov3.cfg#L689
> * https://github.com/AlexeyAB/darknet/blob/0039fd26786ab5f71d5af725fc18b3f521e7acfd/cfg/yolov3.cfg#L776

**Comment by AlexeyAB** [comment]
Can you share your cfg-file?

**Comment by VisionEp1** [comment]
sure: 
[sample.cfg.txt](https://github.com/AlexeyAB/darknet/files/2027179/sample.cfg.txt)

**Comment by AlexeyAB** [comment]
@VisionEp1 I added another fix.
Seg-fault occurred if <class_id> in your labels more or equal to `classes=1` in your cfg-file.
I.e. if in the cfg-file you set `classes=1` then in your txt-labels should be only class_id  `0`.
Now it should occur segmentation fault.

**Comment by VisionEp1** [comment]
ahhh the old start count with 0.
My bad and thanks for the fix
