### ISSUE TITLE
YOLOv7 darknet small object

### ISSUE THREAD

**Issue by hafidh561** [AlexeyAB/darknet#8674]
![image](https://user-images.githubusercontent.com/46504516/193421036-bb1667f7-3db3-4e29-9243-6ff71da9f736.png)

Hello, I want to ask about a small object configuration in yolov7. How to implement this config yolov4 for a small object on yolov7.cfg darknet? Is that any idea to make yolov7 darknet more robust in small objects?

**Comment by stephanecharette** [comment]
> How to implement this config yolov4 for a small object on yolov7.cfg darknet?

See https://www.ccoderun.ca/darkhelp/api/Tiling.html and https://www.youtube.com/watch?v=861LvUXvJmA as well as the FAQ: https://www.ccoderun.ca/programming/darknet_faq/#optimal_network_size

**Comment by hafidh561** [comment]
> > How to implement this config yolov4 for a small object on yolov7.cfg darknet?
> 
> See https://www.ccoderun.ca/darkhelp/api/Tiling.html and https://www.youtube.com/watch?v=861LvUXvJmA as well as the FAQ: https://www.ccoderun.ca/programming/darknet_faq/#optimal_network_size

So, do we need to implement image tiling in inference, rather than change the yolov7 config when training?

**Comment by stephanecharette** [comment]
It is already implemented.  See the links I provided in the comment above.

**Comment by hafidh561** [comment]
> It is already implemented. See the links I provided in the comment above.

No, I mean we need to use image tiling when inference, rather than change the yolov7 config?

**Comment by Avv22** [comment]
@stephanecharette. How to edit the YOLOv4 configuration to be able to deal with small objects, please?

**Comment by Avv22** [comment]
> > @stephanecharette. How to edit the YOLOv4 configuration to be able to deal with small objects, please?
> 
> I have lots of tutorials on my youtube channel showing how to do this. See the links above. Or join the Darknet/YOLO discord server for details.

Thank you very much. Someone suggested changing YOLOv4 config file as follows. Are you with this, please? I have an object of size 53x46 at a distance of 80 meters from the camera and I still got a lot of false detections. 

![image](https://user-images.githubusercontent.com/45768058/217926380-88224167-0114-46e7-8526-bad297b7cb4c.png)
