### ISSUE TITLE
bounding box coordinates from video

### ISSUE THREAD

**Issue by yuliiasergeeva** [AlexeyAB/darknet#868]
Hello, I need to get live coordinates of bounding boxes while using webcam. Do you mind to recommend how it can be done? Thanks!

**Comment by AlexeyAB** [comment]
Hi, update your code from GitHub and use this command with `-ext_output` flag:

`./darknet detector demo data/coco.data yolov3.cfg yolov3.weights test.mp4 -ext_output`

**Comment by yuliiasergeeva** [comment]
Thank you! However I get this issue:

`Loading weights from yolov3.weights...
 seen 64
Done!
video file: test.mp4
warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:808)
warning: test.mp4 (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:809)
 Video-stream stoped!
Stream closed.
 Video-stream stoped!
Stream closed.
[2J[1;1H
FPS:0.0
Objects:

 Video-stream stoped!
Stream closed.
[2J[1;1H
FPS:0.0
Objects:

 Video-stream stoped!
Stream closed.
[2J[1;1H
FPS:0.0
Objects:

input video stream closed.`

**Comment by yuliiasergeeva** [comment]
Thank you so much! It works!

**Comment by yuliiasergeeva** [comment]
Just a quick stupid question: what file should I edit if I want to edit the output (print it into a file, etc)?

**Comment by yuliiasergeeva** [comment]
And how to read the coordinates? I understand w and h but what is Left and top (distance from the left and top? what are the units? what it the size of the whole field than?) Thanks!

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet/blob/032acd408acd119a5bd5c132765fcdd6caedea6b/src/image.c#L538-L539

* left - x coordinate of the left-top corner of bounded box
* top - y coordinate of the left-top corner of bounded box

**Comment by yuliiasergeeva** [comment]
Thank you! And what are those units and how can I figure out the "size" of the video frame?

**Comment by AlexeyAB** [comment]
> And what are those units and how can I figure out the "size" of the video frame?

These are coordinates of objects in pixels on original frames from your video.


Just update your code from GitHub and you will see "size" of the video frame:
![image](https://user-images.githubusercontent.com/4096485/40372466-6ebd7650-5ded-11e8-841c-14ae6c16ebbf.png)

**Comment by yuliiasergeeva** [comment]
Wonderful! thank you so much for your help and quick replies!

**Comment by aNothing** [comment]
When I use following command to do demo through camera, will it save a file in json or csv format in a folder? If there is a file stored, which folder will it in(I can test use the following code but have not seen any stored file).

**./darknet detector demo data/coco.data yolov3.cfg yolov3.weights -i 0 -ext_output**

**Comment by AlexeyAB** [comment]
@aNothing Use this command:
`./darknet detector demo data/coco.data yolov3.cfg yolov3.weights -i 0 -ext_output > result.txt`

And look at result.txt file

**Comment by aNothing** [comment]
Thanks for your reply, it worked!!

**Comment by AlexeyAB** [comment]
@aNothing On Linux:
`./darknet detector demo data/coco.data yolov3.cfg yolov3.weights -i 0 -ext_output | tee result.txt`

For Windows you should install: https://code.google.com/archive/p/wintee/downloads

**Comment by buzdarbalooch** [comment]
@AlexeyAB hi sir can't we see the top left - x coordinate of the left-top corner of bounded box
top - y coordinate of the left-top corner of bounded box for a vido rather then the  coordinates of objects in pixels.
