### ISSUE TITLE
During the training process, a lot of time wasted on data enhancement and loading pictures

### ISSUE THREAD

**Issue by 1027663760** [AlexeyAB/darknet#8684]
Can you make the loading picture → sample enhancement → training process into the mode of asynchronous queue?
In this case, in the process of loading pictures → Sample enhancement, you can load the data required for the next iteration in advance during the GPU operation. In theory, this can increase the GPU usage rate
@AlexeyAB

**Comment by 1027663760** [comment]
MOSAIC = 1 The training speed is slower. I manually modified the number of threads of DarkNet to 32, and the speed is still very slow.

**Comment by 1027663760** [comment]
https://github.com/AlexeyAB/darknet/issues/7567

**Comment by kossolax** [comment]
it's already threaded and async

 you are loading the next batch of image during a training iteration.

https://github.com/AlexeyAB/darknet/blob/master/src/detector.c#L188
https://github.com/AlexeyAB/darknet/blob/master/src/detector.c#L242

**Comment by 1027663760** [comment]
> it's already threaded and async
> 
> you are loading the next batch of image during a training iteration.
> 
> https://github.com/AlexeyAB/darknet/blob/master/src/detector.c#L188 https://github.com/AlexeyAB/darknet/blob/master/src/detector.c#L242

Oh, thank you, but why is the GPU CUDA usage only 80%average? Is there any other bottleneck existence
