### ISSUE TITLE
Validating trained weights file crashes darknet

### ISSUE THREAD

**Issue by Timebutt** [AlexeyAB/darknet#87]
Hi,

I want to validate a set of trained weights to find the best one to use for future detection. I use the following command, adapted from your instructions. The file references are all valid (you'll see in the screenshot further down below that they get loaded correctly).

```
darknet.exe detector valid cfg/obj2.data cfg/yolo-obj2.cfg output/obj-2/_1000.weights
```
When I run this command however, I get an error message saying _'darknet.exe has stopped working'_.

![error](https://cloud.githubusercontent.com/assets/10674081/26404922/d9df8c70-4093-11e7-80eb-b8b35dd5b5aa.png)

I'm currently validating the code to see where it crashes, but haven't found anything so far. Is this an issue or problem you have seen before? Can you reproduce this?

**Comment by AlexeyAB** [comment]
Hi,

Did you have folder `darknet\build\darknet\x64\results`?
And show content of `cfg/obj2.data`.

**Comment by Timebutt** [comment]
Hi @AlexeyAB,

the folder `results` exists, and apparently the validation already created a file there:

![results_folder](https://cloud.githubusercontent.com/assets/10674081/26411999/b01beb18-40a7-11e7-827a-e04160e73f97.PNG)

Contents of my `cfg/obj2.data` file:
```
classes= 2
train  = train.txt
valid  = test.txt
names = obj.names
backup = output/obj-2/
```

**Comment by AlexeyAB** [comment]
@Timebutt Try to change `valid  = train.txt` instead of `valid  = test.txt`.

Did you have marked label .txt-files for images from dataset to which referenced `test.txt`?
Does recall work successfully? `darknet.exe detector recall cfg/obj2.data cfg/yolo-obj2.cfg output/obj-2/_1000.weights`

**Comment by Timebutt** [comment]
Just changed my `cfg/obj2.data` file to reflect `valid = train.txt`, same crash unfortunately.

This is what I get, when I run the recall command:

![recall](https://cloud.githubusercontent.com/assets/10674081/26412584/87dbb7ee-40a9-11e7-8af0-b7dc05f63e43.PNG)

I went looking through both your, and the original repository but I couldn't find a voc.2007.test file (it's hard coded in `detector.c`, in the validate_detector_recall() function.

I changed this into the `test.txt` I want to use, and the code started working perfectly. Results are pretty awful though, it seems, let's ignore that for now ;)

![output](https://cloud.githubusercontent.com/assets/10674081/26412737/0a5fd8e4-40aa-11e7-8518-35182a7d4dd2.PNG)

Weird. Judging by the code, the `validate_detector_recall()`  function is not identical to the `validate_detector()` function. When should I use which one? Seems something is off in the latter then?

**Comment by AlexeyAB** [comment]
* Use `detector recall` to get **IoU** to find the best weights-file at Early Stoping Point with the greatest IoU: https://github.com/AlexeyAB/darknet#when-should-i-stop-training

* Use  `detector valid` to get the found coordinates - for each object in a separate .txt-file, that will be created in folder `/result/`, for example, to get **mAP**: https://github.com/AlexeyAB/darknet/issues/16

For using `valid = train.txt` from `obj.data` instead of hardcoded `voc.2007.test` for detector recall - you should do this fix in your source code: https://groups.google.com/d/msg/darknet/zKHRxm9FFF4/twUoD-4mAAAJ
Or just update Darknet from this repository (it was fixed at Commits on Apr 25, 2017).

**Comment by Timebutt** [comment]
Thank you, seems I misunderstood the valid and recall commands.
