### ISSUE TITLE
hallo,I want to know what the Green Line C = 0.0% on the map means during training?

### ISSUE THREAD

**Issue by darkxzk** [AlexeyAB/darknet#8715]
![144026593-4c7e0b67-59ea-47b3-b445-ddee508dbfec](https://user-images.githubusercontent.com/119394700/204450682-aae2ef5c-8331-4e67-b702-0a45be38e1a5.png)

**Comment by stephanecharette** [comment]
Issue #6290.

**Comment by darkxzk** [comment]
> 问题 #6290。

Thanks
