### ISSUE TITLE
When the RTX3060 graphics card uses CUDA11.1 to train, the instruction -map will not respond when the number of iterations is 999. How to solve it?

### ISSUE THREAD

**Issue by YFforever2022** [AlexeyAB/darknet#8727]
When the RTX3060 graphics card uses CUDA11.1 to train, the instruction -map will not respond when the number of iterations is 999. How to solve it?

**Comment by stephanecharette** [comment]
Is it the same as issue #8669?

**Comment by YFforever2022** [comment]
> Is it the same as issue #8669?

Thank you for your reply, I seem to have solved this problem, using CUDA11.3 and CUDNN8.4.0.27, windowsx64 after recompiling darknet and using -map did not crash

**Comment by YFforever2022** [comment]
> Is it the same as issue #8669?

Hello friends, I need your help, how to solve this problem, when I modify the width and height in the network file and iterate, it still does not respond when iterating 999 times, it is normal without using the -map command
