### ISSUE TITLE
Yolo has 100 percent of accuracy running test command but do not detect the objects

### ISSUE THREAD

**Issue by proplayer2020** [AlexeyAB/darknet#8728]
Hello, I created a simple yoloV4 tiny with transfer learning to recognize flowers, I used 260 images with 1 class and I trained the model with following command : **./darknet detector train data/obj.data data/yolov4-tiny.cfg data/yolov4-tiny.conv.29 -dont_show -map**. I trained for about 500 epochs and loss is 1. I can't upload an image because i compiled darknet with opencv but you can see micro bounding boxes with all 100 percent chance on the image, (the image is from train set, so I expect it to be good) but no.
I also tried to run with -show_images and my dataset seems to be good.
In clear : I want to know if it's possible to transfer learning with yolov4-tiny and with 1 class
I really don't know what to do I really need help. Thank you very much for your help.
PS : I don't have -nan values in training and all seems to be normal.

**Comment by proplayer2020** [comment]
by the way here is my .cfg file :
[yolov4-tiny.txt](https://github.com/AlexeyAB/darknet/files/10471813/yolov4-tiny.txt)

**Comment by awaisbajwaml** [comment]
@proplayer2020  yes you can train 1 class, please share further details

did you provide negative samples ? images without flowers ?  
the sub divisions seems pretty low did you train via same config? i assume you have a lot of mem to cach images 
can you please share details about the GPU? cuda version?

**Comment by proplayer2020** [comment]
Thanks for fast reply, yes i provided negative samples (images without flowers).
Recently I am retraining the model with 64 batch and 2 subdivision if this can be better. Tell me if more subdivision would be better (because i found those settings in a tutorial for 1 class transfer learning with yolo v4.
I use just the integrated crappy graphic card of my portable computer lol, (amd radeon vega) and so i didn't compile with cuda.

**Comment by proplayer2020** [comment]
64 batch and 16 subdivisions*

**Comment by proplayer2020** [comment]
The test command output that : (the white flowers is what i want to detect)
![predictions](https://user-images.githubusercontent.com/116555319/213910253-873c4d4e-5c2f-48ad-a63c-f765a861a7d3.jpg)

**Comment by proplayer2020** [comment]
I first thought it detect just white but no
![predictions](https://user-images.githubusercontent.com/116555319/213910301-075b9930-c213-44f9-8f68-23be53c21fdb.jpg)

**Comment by proplayer2020** [comment]
I've been training for a week and i want to know if getting **obj : 1.00** is normal in training?

**Comment by proplayer2020** [comment]
after 1000 iterations its better, but its weird that the model had 1.0 of loss with bad results
