### ISSUE TITLE
detector train stops after random interations

### ISSUE THREAD

**Issue by VitaliCzymmek** [AlexeyAB/darknet#874]
Hi, 
I am training my custom dataset with yolov3 and like mentioned the training stops after random interations. 

As seen in the image it shows "   Cannot load image ""    " and then stops without an error.

I can go on with the training when i use the previous weights but then the problem occurs again.

I hope you can help me and thank you in advance! :)

![problem](https://user-images.githubusercontent.com/26389656/40351129-f944130c-5dab-11e8-8dfc-f9f747a282ec.jpg)

**Comment by AlexeyAB** [comment]
Your dataset is broken.
Did you get your training dataset by using Yolo_mark?

**Comment by VitaliCzymmek** [comment]
Yes, I used Yolo_mark.

I can continue with the training by using the previous weights and then it crashes at random iterations

**Comment by AlexeyAB** [comment]
* Do all your files have `.jpg` extension?
* Do you use the latest code from this GitHub?
* Can you share your dataset or at least `train.txt`?
* What command do you use for training?
* What do you see in the file `bad.list`?
* Can you successfully do the command like this?
`darknet.exe detector map obj.data yolo.cfg yolo_1700.weights`

**Comment by AlexeyAB** [comment]
@VitaliCzymmek Ive done some fixes. 
Try to update your code from GitHub and recompile.

**Comment by ashuezy** [comment]
@AlexeyAB 
Updated the code. It crashed without error after 129th iteration.

**Comment by AlexeyAB** [comment]
* Do all your files have `.jpg` extension?
* Can you share your dataset or at least `train.txt`?
* What command do you use for training?
* What do you see in the file `bad.list`?
* Can you successfully do the command like this?
`darknet.exe detector map obj.data yolo.cfg yolo_1700.weights`

**Comment by VitaliCzymmek** [comment]
- Yes all files have .jpg extension
- Our dataset consists out of 700 dogs and cat images.
[train.txt](https://github.com/AlexeyAB/darknet/files/2047101/train.txt)
- we use your recommended command " darknet.exe detector train data/obj.data yolo-obj.cfg darknet53.conv.74 "
 and for the continued training the same but with the weights in the backup folder
- bad.list shows " ECHO ist eingeschaltet (ON). " in german this means " ECHO is turned on "
- No we get an error " Cannot load image 704 but we don't have 704 images in train.txt or in the obj folder
![error cannot load image](https://user-images.githubusercontent.com/26389656/40644118-8550042a-6322-11e8-82e3-92c7a92106b3.png)

Thank you again for your help! :)

**Comment by AlexeyAB** [comment]
I also added fix, that ignores empty extra lines in train.txt
