### ISSUE TITLE
cuDNN status Error in: file: darknet\src\convolutional_kernels.cu : backward_convolutional_layer_gpu() : line: 854?

### ISSUE THREAD

**Issue by Andersama** [AlexeyAB/darknet#8750]
I suspect this is likely a memory issue when trying to run the training program. I have gotten for example the error about not finding the forward algorithm. I reduced the network's width and height to 320 x 320 and set batch and subdivision to 64. Currently there are six labels I'm meant to detect. While running the memory usage skyrockets to around 24 GB, stabilizes somewhat and then this error appears. The edits I've made are here: https://github.com/Andersama/darknet which mostly introduces a slightly different api to parse my ever so slightly different label files. Which instead of looking like `<id> <x> <y> <w> <h>` are `<x> <y> <w> <h> <label_string>`.

Things to note: I have been struggling to get a custom version of darknet and cuda in my own project to play nice. I installed CUDA v12 and I'm noticing that the .dll's my parent project wants to load seem to be from v11. My workaround, somewhat crossing fingers was just to rename the .dll's (not ideal, but seemed to get at least part way into training). I'm going to install older cuda versions to see if I can find the expected .dll file in the event I'm dealing with an abi break.

Currently building on Windows 10 x64, with a GTX 1080.

![image](https://user-images.githubusercontent.com/25020235/221996955-1fcf68f5-7c04-4847-8631-f1ea6024d007.png)

**Comment by stephanecharette** [comment]
It is extremely unlikely someone will help you with this, since you are running with modified source.

I strongly suggest you get things working in "vanilla" Darknet first, and report any errors that happen in that version before attempting to report issues with custom source code.

**Comment by Andersama** [comment]
That's fair. the source isn't modified significantly though. The important bit and the part that's failing is the network training code. That part of how darknet works I've not edited. The strange part for me is that I installed CUDA v12 but the .dll's the parent project seems to want to use are not that version. I looked at vcpkg's files and it looks as though their "port" has a line requiring 10.1.0, but the code past that point seems to be treating that "requirement" as a minimum, not necessarily forcing an exact version. I'm not sure what is determining the names for the dlls and why it'd be generating names for a cuda library I don't have installed.

**Comment by Andersama** [comment]
After downloading what appears to be the right .dll's from nvidia and copying them over and further reducing the memory load I've successfully managed to get far enough through training to have an output weight file. So I'm going to close, I can't say which change fixed the issue, but at the very least if someone runs into this error you'll have some direction.
