### ISSUE TITLE
Error when compile Darknet with OpenCV undefined reference to Vtk

### ISSUE THREAD

**Issue by lnhutnam** [AlexeyAB/darknet#8751]
Hi authors, 

I have an issue when compile Darknet with opencv, cuda like this

```
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/../../../../lib/libopencv_viz.so: undefined reference to `vtkAlgorithm::Register(vtkObjectBase*)'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/../../../../lib/libopencv_viz.so: undefined reference to `vtkAlgorithm::UnRegister(vtkObjectBase*)'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/../../../../lib/libopencv_viz.so: undefined reference to `vtkAlgorithmOutput::GetProducer()'
collect2: error: ld returned 1 exit status
make: *** [Makefile:177: darknet] Error 1
```

I use Arch linux to install opencv, and already have vtk on my machine. However, it seem to be missing something?  So I need some help to solve this.

Thanks,

**Comment by stephanecharette** [comment]
VTK is not used by Darknet.  This must be something specific to your installation of OpenCV.

**Comment by lnhutnam** [comment]
@stephanecharette I use the command `pacman -Sy opencv vtk hdf5`. Are you ever seen this problem when use this installation way?

**Comment by lnhutnam** [comment]
I think this problem solved.

The detail in this link: https://bugs.archlinux.org/task/60901

So we need to change some thing in /usr/lib/pkgconfig/opencv4.pc. For especially, we remove -lopencv_viz.

I close this issue now. Thanks for previous comment.
