### ISSUE TITLE
Yolov4-tiny training

### ISSUE THREAD

**Issue by rajban94** [AlexeyAB/darknet#8752]
I have trained yolov4-tiny model for object detection having 3 classes. So in my .cfg file i gave max batches 6000 and i had training images around 4080. But after 6000 iterations the training automatically got stopped and i got 6000.weights and final.weights. After testing the model it's bit on and off so can you let me know how to setup the .cfg file so that it will not stop after reaching max batches and i can manually stop the training?

**Comment by stephanecharette** [comment]
I'm not sure I understand.  You told it to train to 6000, but you didn't want it to stop at 6000?

**Comment by rajban94** [comment]
@stephanecharette yes, i want to train more that 6000 but as the no of classes are 3 in my case so i put max batches as 6000. And after reaching max batches the training got stopped. How can i change the config so that it will do the training for above 6000 iterations as well?

**Comment by stephanecharette** [comment]
6000 is the minimum.  You can use any number you want.

**Comment by rajban94** [comment]
For 3 classes max batch should be 3*2000=6000 or i can put higher max batches as well for 3 classes?

**Comment by stephanecharette** [comment]
I've already answered this.  The **MINIMUM** you should use with 3 classes is 6000.  The maximum is up to you.

**Comment by rajban94** [comment]
Okay thank you.
