### ISSUE TITLE
FileNotFoundError and Download Failure in AlexeyAB Darknet's YOLO Object Detection Framework

### ISSUE THREAD

**Issue by Simiao03** [AlexeyAB/darknet#8785]
If you want to report a bug - provide:
    * description of a bug
    * what command do you use?
    * do you use Win/Linux/Mac?
    * attach screenshot of a bug with previous messages in terminal
    * in what cases a bug occurs, and in which not?
    * if possible, specify date/commit of Darknet that works without this bug
    * show such screenshot with info
```
./darknet detector test cfg/coco.data cfg/yolov4.cfg yolov4.weights data/dog.jpg
 CUDA-version: 10000 (10000), cuDNN: 7.4.2, CUDNN_HALF=1, GPU count: 1
 CUDNN_HALF=1
 OpenCV version: 4.2.0
 0 : compute_capability = 750, cudnn_half = 1, GPU: GeForce RTX 2070
net.optimized_memory = 0
mini_batch = 1, batch = 8, time_steps = 1, train = 0
   layer   filters  size/strd(dil)      input                output
```
Product: AlexeyAB Darknet
Version: Unknown
Operating System: Windows

Description of the issue:
When attempting to run the program "main.py" which utilizes the AlexeyAB Darknet library, the following error occurred:

"Downloading yolov4.cfg from https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4.cfg
Could not establish connection. Download failed
Downloading yolov4.weights from https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights
Could not establish connection. Download failed
Downloading yolov3_classes.txt from https://github.com/arunponnusamy/object-detection-opencv/raw/master/yolov3.txt
Could not establish connection. Download failed
Traceback (most recent call last):
File "C:\Users\cshang\PycharmProjects\if\read\live object detection\main.py", line 20, in <module>
bbox, label, conf = cv.detect_common_objects(frame)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\cshang\PycharmProjects\if\read\live object detection\venv\Lib\site-packages\cvlib\object_detection.py", line 124, in detect_common_objects
classes = populate_class_labels()
^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\cshang\PycharmProjects\if\read\live object detection\venv\Lib\site-packages\cvlib\object_detection.py", line 19, in populate_class_labels
f = open(class_file_abs_path, 'r')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\cshang\.cvlib\object_detection\yolo\yolov3\yolov3_classes.txt'

Process finished with exit code 1"

The error indicates that the program could not establish a connection to download necessary files such as yolov4.cfg, yolov4.weights and yolov3_classes.txt. This resulted in the program being unable to execute the function "cv.detect_common_objects(frame)" and ultimately, the program terminated with an exit code of 1.

Steps to reproduce:

Attempt to run the program "main.py" which utilizes the AlexeyAB Darknet library.
Expected result:
The program should execute without any errors and perform live object detection using the webcam.

Actual result:
The program failed to execute due to the inability to download necessary files resulting in the function "cv.detect_common_objects(frame)" failing and terminating the program with an exit code of 1.

Additional information:
The program was written using Python and was executed on a Windows operating system. It is unclear what version of the AlexeyAB Darknet library was utilized.
main.py file is in .txt file form that is attached to this report.
[main.txt](https://github.com/AlexeyAB/darknet/files/11363264/main.txt)

**Comment by cenit** [comment]
It looks like you have connection issues. All your links work for me
