### ISSUE TITLE
Bug in YOLOv4 darknet_images.py at line 106

### ISSUE THREAD

**Issue by robmlee** [AlexeyAB/darknet#8802]
While using YOLOv4, when I call funtion image_detection:
```
import darknet_images as di
!wget -O capture.jpg --quiet $strHttpCapture
image, detections = di.image_detection(
'capture.jpg', network, class_names, class_colors, 0.25 # Threshold, remove detections with lower confidence
)
```

I will get error mesg as fellow:
```
error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src'
```

The problem is in darknet_images.py at line 106:

`if type(image_or_path) == "str":`

it should be:

`if type(image_or_path) == str:`

**Comment by Mehul-Agrawal410** [comment]
If this is still open, could it be assigned to me? I would like to do this

**Comment by cenit** [comment]
should be fixed in latest commit. Please reopen if you still have problems!
