### ISSUE TITLE
Work with data containing "inverted" bounding boxes (from bottom right to top left)

### ISSUE THREAD

**Issue by proplayer2020** [AlexeyAB/darknet#8814]
Hello, i was just wondering if the training command works with data containing bounding boxes starting from bottom right to top left, because it seems less natural.
Here is an example :
![question](https://github.com/AlexeyAB/darknet/assets/116555319/20b7668c-dc84-479c-8952-e433d20bc220)

Sorry for bad english, i'm not english 😅.
Thanks in advance.

**Comment by stephanecharette** [comment]
That is not how YOLO annotations work.  See the FAQ:  https://www.ccoderun.ca/programming/darknet_faq/#darknet_annotations

You understand that how you draw the annotations has zero impact on how the annotations are saved to disk, right?

**Comment by proplayer2020** [comment]
Ok, i was just wondering. Thanks for helping me and for fast reply.
