### ISSUE TITLE
Error when compiling OPENCV=1

### ISSUE THREAD

**Issue by yujianxiang** [AlexeyAB/darknet#882]
While CPU, GPU=1 make succeeds, but OPENCV = 1fails.
System details:
Ubuntu 16.04
CUDA 9.2
OpenCV 3.4.0

**Compiling error:**
/usr/bin/ld: warning: libjpeg.so.9, needed by /usr/local/lib/libopencv_imgcodecs.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libpng16.so.16, needed by /usr/local/lib/libopencv_imgcodecs.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcudart.so.9.1, needed by /usr/local/lib/libopencv_core.so, may conflict with libcudart.so.9.2
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_set_interlace_handling@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_set_IHDR@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_get_io_ptr@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `jpeg_set_quality@LIBJPEG_9.0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `jpeg_quality_scaling@LIBJPEG_9.0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `jpeg_resync_to_restart@LIBJPEG_9.0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_set_longjmp_fn@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `jpeg_set_defaults@LIBJPEG_9.0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_set_gray_to_rgb@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_set_bgr@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `jpeg_stdio_src@LIBJPEG_9.0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `jpeg_finish_compress@LIBJPEG_9.0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_set_rgb_to_gray@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `jpeg_calc_output_dimensions@LIBJPEG_9.0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `jpeg_std_error@LIBJPEG_9.0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_set_swap@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_destroy_read_struct@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_set_palette_to_rgb@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_get_tRNS@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `jpeg_write_scanlines@LIBJPEG_9.0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `jpeg_simple_progression@LIBJPEG_9.0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `jpeg_read_header@LIBJPEG_9.0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `jpeg_start_compress@LIBJPEG_9.0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `jpeg_destroy_compress@LIBJPEG_9.0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_set_packing@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_read_end@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_set_read_fn@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_write_end@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_set_expand_gray_1_2_4_to_8@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_set_write_fn@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_create_write_struct@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_error@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_destroy_write_struct@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `jpeg_stdio_dest@LIBJPEG_9.0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_set_strip_16@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_create_read_struct@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `jpeg_finish_decompress@LIBJPEG_9.0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `jpeg_destroy_decompress@LIBJPEG_9.0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_set_tRNS_to_alpha@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `jpeg_CreateDecompress@LIBJPEG_9.0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `jpeg_alloc_huff_table@LIBJPEG_9.0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_set_compression_level@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `jpeg_CreateCompress@LIBJPEG_9.0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_set_filter@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `jpeg_default_qtables@LIBJPEG_9.0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_init_io@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_get_IHDR@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `jpeg_start_decompress@LIBJPEG_9.0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_set_compression_strategy@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_write_info@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `jpeg_read_scanlines@LIBJPEG_9.0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_create_info_struct@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_read_update_info@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_write_image@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_read_image@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_read_info@PNG16_0'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `png_set_strip_alpha@PNG16_0'
collect2: error: ld returned 1 exit status
Makefile:127: recipe for target 'darknet' failed
make: *** [darknet] Error 1

Any suggestions are welcome. Thanks.

**Comment by AlexeyAB** [comment]
> /usr/bin/ld: warning: libjpeg.so.9, needed by /usr/local/lib/libopencv_imgcodecs.so, not found (try using -rpath or -rpath-link)
> /usr/bin/ld: warning: libpng16.so.16, needed by /usr/local/lib/libopencv_imgcodecs.so, not found (try using -rpath or -rpath-link)
> /usr/bin/ld: warning: libcudart.so.9.1, needed by /usr/local/lib/libopencv_core.so, may conflict with libcudart.so.9.2

You should install `libjpeg` and `libpng16`

```
sudo apt-get install libjpeg-dev
sudo apt-get install libpng-dev
```

**Comment by aNothing** [comment]
Thanks for your quick reply. I have installed these two library, and still this error.

**Comment by AlexeyAB** [comment]
Can you show current log of errors or is it absolutely the same?

**Comment by xuesongle** [comment]
@AlexeyAB I have the similar issue here after make:
System details:
Ubuntu 16.04
Cuda release 8.0, V8.0.6
OpenCV 3.3.1

collect2: error: ld returned 1 exit status
Makefile:127: recipe for target 'darknet' failed
make: *** [darknet] Error 1

griffith@Jane:~/AlexeyAB/darknet$ make
g++  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -fopenmp -DGPU -DCUDNN -I/usr/local/cudnn/include obj/http_stream.o obj/gemm.o obj/utils.o obj/cuda.o obj/convolutional_layer.o obj/list.o obj/image.o obj/activations.o obj/im2col.o obj/col2im.o obj/blas.o obj/crop_layer.o obj/dropout_layer.o obj/maxpool_layer.o obj/softmax_layer.o obj/data.o obj/matrix.o obj/network.o obj/connected_layer.o obj/cost_layer.o obj/parser.o obj/option_list.o obj/darknet.o obj/detection_layer.o obj/captcha.o obj/route_layer.o obj/writing.o obj/box.o obj/nightmare.o obj/normalization_layer.o obj/avgpool_layer.o obj/coco.o obj/dice.o obj/yolo.o obj/detector.o obj/layer.o obj/compare.o obj/classifier.o obj/local_layer.o obj/swag.o obj/shortcut_layer.o obj/activation_layer.o obj/rnn_layer.o obj/gru_layer.o obj/rnn.o obj/rnn_vid.o obj/crnn_layer.o obj/demo.o obj/tag.o obj/cifar.o obj/go.o obj/batchnorm_layer.o obj/art.o obj/region_layer.o obj/reorg_layer.o obj/reorg_old_layer.o obj/super.o obj/voxel.o obj/tree.o obj/yolo_layer.o obj/upsample_layer.o obj/convolutional_kernels.o obj/activation_kernels.o obj/im2col_kernels.o obj/col2im_kernels.o obj/blas_kernels.o obj/crop_layer_kernels.o obj/dropout_layer_kernels.o obj/maxpool_layer_kernels.o obj/network_kernels.o obj/avgpool_layer_kernels.o -o darknet -lm -pthread  `pkg-config --libs opencv`  -lgomp -L/usr/local/cuda/lib64 -lcuda -lcudart -lcublas -lcurand -L/usr/local/cudnn/lib64 -lcudnn -lstdc++ 
/usr/bin/ld: warning: libicui18n.so.54, needed by //home/griffith/anaconda3/lib/libQt5Core.so.5, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicuuc.so.54, needed by //home/griffith/anaconda3/lib/libQt5Core.so.5, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicudata.so.54, needed by //home/griffith/anaconda3/lib/libQt5Core.so.5, not found (try using -rpath or -rpath-link)
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_clone_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `u_strToLower_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_setMillis_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_fromUnicode_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_getDefaultName_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_inDaylightTime_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_get_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_close_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_openTimeZones_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_toUnicode_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `u_strToUpper_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_close_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_getMaxCharSize_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_countAvailable_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_getDefaultTimeZone_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `uenum_next_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_getStandardName_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucol_setAttribute_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucol_strcoll_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_setSubstChars_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_getTimeZoneDisplayName_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_openCountryTimeZones_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_open_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucol_open_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucol_close_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucol_getSortKey_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_getAvailableName_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_getDSTSavings_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_openTimeZoneIDEnumeration_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_open_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `u_errorName_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `uenum_close_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_getAlias_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_compareNames_54'
//home/griffith/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_countAliases_54'
collect2: error: ld returned 1 exit status
Makefile:127: recipe for target 'darknet' failed
make: *** [darknet] Error 1

**Comment by AlexeyAB** [comment]
@xuesongle Something wrong with installation of Qt5 or ICU. Check these:
https://askubuntu.com/questions/1011636/opencv-undefined-references-for-libqt5core-so-5

https://stackoverflow.com/questions/35864617/compile-error-libicui18n-so-54-needed-by-libqt5core-so-5-not-found

https://stackoverflow.com/questions/29455836/linkage-against-libqt5core/40327731#40327731

**Comment by aNothing** [comment]
@AlexeyAB , sorry for the late reply. I tries this repository **https://github.com/AlexeyAB/darknet**, and download and install this OpenCV-version: **https://github.com/opencv/opencv/archive/3.4.0.zip**, compile it with:
 cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-3.4.0/modules -D WITH_CUDA=ON -D WITH_CUBLAS=ON -D CUDA_FAST_MATH=ON -D WITH_CUFFT=ON -D WITH_NVCUVID=ON -D WITH_V4L=ON -D WITH_LIBV4L=ON -D WITH_OPENGL=ON -D WITH_FFMPEG=ON -D INSTALL_C_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D BUILD_SHARED_LIBS=OFF ..

All of these operations are good. When I compile darknet with:
**GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=1
AVX=0
OPENMP=0
LIBSO=0**

There is an error:
**/usr/bin/ld: /usr/local/lib/libopencv_core.a(opencl_core.cpp.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:127: recipe for target 'darknet' failed
make: *** [darknet] Error 1**

I also tried CUDNN = 0 and CUDNN_HALF=0, the same error.

**Comment by AlexeyAB** [comment]
@aNothing 
* use `DEBUG=0` in Makefile
* Try to change this line: https://github.com/AlexeyAB/darknet/blob/0713fd9784bbd0c67eb82df6f6e2c072a53e09e8/Makefile#L52
    to this `LDFLAGS= -lm -pthread -ldl `
    or to this `LDFLAGS= -ldl -pthread `

**Comment by aNothing** [comment]
Thanks for your reply, I will try your suggestions and update the newest situation. Really appreciate for your help.

**Comment by aNothing** [comment]
I used the following command compiled opencv 3.4.0 successfully.

**cmake -D CMAKE_BUILD_TYPE=RELEASE -D BUILD_EXAMPLES=ON -D WITH_FFMPEG=ON -D WITH_V4L=ON -D WITH_OPENGL=ON -D WITH_CUDA=ON -D CUDA_ARCH_BIN="3.0 5.0 6.1" -D WITH_CUBLAS=ON -D WITH_CUFFT=ON -D WITH_EIGEN=ON ./**

**GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=1
AVX=0
OPENMP=0
LIBSO=0
DEBUG=0**

Since this method works well and schedule is tight, I have not tested your suggestion. But when I watch the GPU memory usage, there is only one gpu used even if I used gpus 0,1.

Every 10.0s: nvidia-smi                                 Mon Jun  4 10:13:05 2018

Mon Jun  4 10:13:05 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.26                 Driver Version: 396.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0  On |                  N/A |
| 50%   84C    P2   189W / 250W |   6036MiB / 11175MiB |     97%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
| 23%   32C    P8     8W / 250W |     12MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1109      G   /usr/lib/xorg/Xorg                           182MiB |
|    0      1797      G   /opt/teamviewer/tv_bin/TeamViewer              2MiB |
|    0      2000      G   compiz                                        43MiB |
|    0     25215      C   ./darknet                                   5803MiB |

**Comment by AlexeyAB** [comment]
@aNothing Yes, that's the way it has to be for detection - all is ok.

**Comment by aNothing** [comment]
Ok, get it. Thanks for your help.

**Comment by Lucas-Fan** [comment]
> @aNothing
> 
> * `DEBUG=0`在Makefile中使用
> * 尝试更改此行： https://github.com/AlexeyAB/darknet/blob/0713fd9784bbd0c67eb82df6f6e2c072a53e09e8/Makefile#L52
>   
>   对此`LDFLAGS= -lm -pthread -ldl `
>   或对此`LDFLAGS= -ldl -pthread `



@AlexeyAB 
Hello, I have encountered the same problem, but this solution does not work. What advice do you have?
I am running the code at
Ubuntu18.04
Cuda9.0
Cudnn7.1.3
Opencv3.4.0

**Comment by Lucas-Fan** [comment]
> @aNothing
> 
> * use `DEBUG=0` in Makefile
> * Try to change this line: https://github.com/AlexeyAB/darknet/blob/0713fd9784bbd0c67eb82df6f6e2c072a53e09e8/Makefile#L52
>   
>   to this `LDFLAGS= -lm -pthread -ldl `
>   or to this `LDFLAGS= -ldl -pthread `

@AlexeyAB 
Hello, I have encountered the same problem, but this solution does not work. What advice do you have?
I am running the code at
Ubuntu18.04
Cuda9.0
Cudnn7.1.3
Opencv3.4.0

**Comment by AlexeyAB** [comment]
@Lucas-Fan 

Tru to compile by using
```
cmake .
make
```

**Comment by Lucas-Fan** [comment]
Thank you for your reply, but this did not solve my problem. I have already run other versions of the YOLO v3 code, thanks again.
