### ISSUE TITLE
convolutional_layer.c:286:24: error: ‘CUDNN_CONVOLUTION_FWD_PREFER_FASTEST’ was not declared in this scope; did you mean ‘CUDNN_CONVOLUTION_FWD_ALGO_FFT’?

### ISSUE THREAD

**Issue by lvshaoqing** [AlexeyAB/darknet#8821]
system environment：
MakeFile:
CUDNN=1
CUDNN_HALF=1

cudnn:
cudnn-linux-x86_64-8.9.3.28_cuda11-archive.tar.xz
cudnn-11.0-linux-x64-v8.0.2.39.solitairetheme8

nv:
NVIDIA-SMI 510.108.03   Driver Version: 510.108.03   CUDA Version: 11.6

**Comment by stephanecharette** [comment]
Note the new Darknet/YOLO repo is at https://github.com/hank-ai/darknet

**Comment by cenit** [comment]
are you using the latest commit ?
darknet supports cudnn >= 8 since some time now
