### ISSUE TITLE
Cuda 11.7 & cudnn8.8.0   unhandled exception

### ISSUE THREAD

**Issue by zirid** [AlexeyAB/darknet#8825]
If you want to report a bug - provide:
    * description of a bug
    *  unhandled exception in the function `:void create_convolutional_cudnn_tensors(layer *l)` specifically in                                                      
    *  " CHECK_CUDNN(cudnnCreateConvolutionDescriptor(&l->convDesc));"
    * what command do you use?
    * 
    * do you use Win/Linux/Mac?
    * Win10
    * attach screenshot of a bug with previous messages in terminal
    * 
![unhadled_exception](https://github.com/AlexeyAB/darknet/assets/31682698/11fa3e19-0458-43dc-9dac-4010f1d88332)

```
 CUDA-version: 11.7, cuDNN: 8.8.0.121, CUDNN_HALF=1, GPU count: 1
 CUDNN_HALF=1
 OpenCV version:  without Opencv
 0 : compute_capability = 750, cudnn_half = 1, GPU: GeForce RTX 2070

**Comment by stephanecharette** [comment]
Note this repo is no longer maintained.  Instead, please see https://github.com/hank-ai/darknet
