### ISSUE TITLE
CUDDA status error

### ISSUE THREAD

**Issue by mizo-1980** [AlexeyAB/darknet#8826]
Hello 
I still not able to run darknet.exe 
i write the command like >>
D:\darknet>darknet.exe detect cfg/yolov4.cfg yolov4.weights data/dog.jpg
 CUDA-version: 12020 (12020), cuDNN: 8.9.4, GPU count: 1
 OpenCV version: 4.8.0
 0 : compute_capability = 500, cudnn_half = 0, GPU: NVIDIA GeForce GTX 960M
net.optimized_memory = 0
mini_batch = 1, batch = 8, time_steps = 1, train = 0
   layer   filters  size/strd(dil)      input                output
   0 Create CUDA-stream - 0
 Create cudnn-handle 0
conv     32       3 x 3/ 1    608 x 608 x   3 ->  608 x 608 x  32 0.639 BF
   1 conv     64       3 x 3/ 2    608 x 608 x  32 ->  304 x 304 x  64 3.407 BF
   2 conv     64       1 x 1/ 1    304 x 304 x  64 ->  304 x 304 x  64 0.757 BF
   3 route  1                                      ->  304 x 304 x  64
   4 conv     64       1 x 1/ 1    304 x 304 x  64 ->  304 x 304 x  64 0.757 BF
   5 conv     32       1 x 1/ 1    304 x 304 x  64 ->  304 x 304 x  32 0.379 BF
   6 conv     64       3 x 3/ 1    304 x 304 x  32 ->  304 x 304 x  64 3.407 BF
   7 Shortcut Layer: 4,  wt = 0, wn = 0, outputs: 304 x 304 x  64 0.006 BF
   8 conv     64       1 x 1/ 1    304 x 304 x  64 ->  304 x 304 x  64 0.757 BF
   9 route  8 2                                    ->  304 x 304 x 128
  10 conv     64       1 x 1/ 1    304 x 304 x 128 ->  304 x 304 x  64 1.514 BF
  11 conv    128       3 x 3/ 2    304 x 304 x  64 ->  152 x 152 x 128 3.407 BF
  12 conv     64       1 x 1/ 1    152 x 152 x 128 ->  152 x 152 x  64 0.379 BF
  13 route  11                                     ->  152 x 152 x 128
  14 conv     64       1 x 1/ 1    152 x 152 x 128 ->  152 x 152 x  64 0.379 BF
  15 conv     64       1 x 1/ 1    152 x 152 x  64 ->  152 x 152 x  64 0.189 BF
  16 conv     64       3 x 3/ 1    152 x 152 x  64 ->  152 x 152 x  64 1.703 BF
  17 Shortcut Layer: 14,  wt = 0, wn = 0, outputs: 152 x 152 x  64 0.001 BF
........
.........
and finally i have 
Done! Loaded 162 layers from weights-file
 Detection layer: 139 - type = 28
 Detection layer: 150 - type = 28
 Detection layer: 161 - type = 28
CUDA status Error: file: D:\darknet\src\blas_kernels.cu: func: add_bias_gpu() line: 121

 CUDA Error: no kernel image is available for execution on the device

![image](https://github.com/AlexeyAB/darknet/assets/7603414/f32081d0-15eb-45fe-a75e-1787b17f7cb4)
![1](https://github.com/AlexeyAB/darknet/assets/7603414/fcf625f5-0493-47cc-9c17-c116af0ccd47)

and i think i have every think ok
![1](https://github.com/AlexeyAB/darknet/assets/7603414/8b4b7d9f-63a8-4477-b1cd-321debba2cd6)

ANY Idea?
thanks

**Comment by rian-cst** [comment]
Hi,

This appears to be an issue with the CUDA architecture that you have chosen.

For a Nvidia GTX 960M, the CUDA architecture compute version [seems to be 5.0](https://en.wikipedia.org/wiki/CUDA).

**Comment by mizo-1980** [comment]
thak you for your response ( rian-cst )
