### ISSUE TITLE
Cfg file format

### ISSUE THREAD

**Issue by proplayer2020** [AlexeyAB/darknet#8827]
Hello, i was wondering if changing spaces, line breaks, matters in yolo.cfg, 

f.e. width=416 instead of width = 416

or 

[YOLO]
width=416
height= 416

instead of 

[YOLO]

width=416
height=416

Im asking this because i am unfamiliar with cfg files.  Sorry for bad english because im not english.

Any help would be greatly appreciated.

**Comment by rian-cst** [comment]
No, the spaces and line breaks in your example (and similar) do not matter.

**Comment by proplayer2020** [comment]
ok thanks you very much !
