### ISSUE TITLE
Cuda Stream error

### ISSUE THREAD

**Issue by qjrm2333** [AlexeyAB/darknet#8835]
When the model is turned on for reference, the program is forced to shut down with Create CUDA-stream - 0.

I installed darknet[full]:x64-windows through vcpkg, CUDA uses version 12.2.1 and cudnn uses version 8.9.3.28.

```
 Try to load cfg: D:\Task\annotation\project_lpd\yolov7-tiny_Viet-lpr.cfg, weights: D:\Task\annotation\project_lpd\yolov7-tiny_Viet-lpr_154000.weights, clear = 1
max_batches: Using default '0'
 0 : compute_capability = 750, cudnn_half = 0, GPU: NVIDIA GeForce RTX 2080 SUPER
net.optimized_memory = 0
mini_batch = 1, batch = 1, time_steps = 1, train = 0
   layer   filters  size/strd(dil)      input                output
   0 Create CUDA-stream - 0

```

**Comment by qjrm2333** [comment]
The problem has been resolved.
When I ran darknet.exe myself, I could get an error code.

![image](https://github.com/AlexeyAB/darknet/assets/102504014/b5921880-4c8e-4e19-9c96-971e07963408)

**Comment by cenit** [comment]
thanks for noticing the error, Certain versions of cudnn require zlibwapi.dll installed inside cudnn folder.
Please update or install dll as described here
https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-windows
