### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by TidelyPom** [AlexeyAB/darknet#8845]
I am getting a segmentation fault when training with Yolov4. I have 2 classes, 1903 training images and 201 test images, the PC is a Dell Alienware Aurora R15 with an Nvidia RTX 4090 GPU, 64 GB memory, i9-13900KF (32 cores), Ubuntu  22.04.3 LTS, gnome 42.9. If if reduce the number of training images to 1500 it doesn't crash. 

Any idea ?

**Comment by TidelyPom** [comment]
Apologies, my train.txt file had a mistake in it. The bug doesn't exist.

**Comment by cenit** [comment]
great. Closing the issue :)
