### ISSUE TITLE
How to use Yolo as DLL after building Yolo as C++ DLL-file yolo_cpp_dll.dll

### ISSUE THREAD

**Issue by berkgungor** [AlexeyAB/darknet#8852]
Hi, I have trained Darknet yolov4 with my custom dataset and built on VS and made it work as darknet.exe file on windows with GPU. I currently run my exe with my custom parameters like
`darknet.exe detector demo ball_config/yolo.data ball_config/yolov4-custom_best.cfg`

I try to run the same model as dll from a C++ code. I have built yolo_cpp_dll.sln and generated yolo_cpp_dll.dll under "\build\darknet\x64" . But i do not know how to call this dll. Also i am not sure how can i call this dll with my custom weights and cfg files to detect my specific object.

Can anybody have any experience with this?

**Comment by stephanecharette** [comment]
Note that a C++ layer for Darknet called DarkHelp exists.  It has much more documentation.  If interested, you can find it here:  https://www.ccoderun.ca/darkhelp/api/API.html

The source for it is here:  https://github.com/stephanecharette/DarkHelp#what-is-the-darkhelp-c-api

**Comment by BerkGungor1** [comment]
Thanks for making me aware of DarkHelp, this is what i needed. However, when i followed the documentation and try to build DarkHelp on windows, I faced an issue as follows : 

`C:\Users\berkg\source\DarkHelp\build>cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:/Users/berkg/source/vcpkg/scripts/buildsystems/vcpkg.cmake ..`

-- The C compiler identification is MSVC 19.36.32535.0
-- The CXX compiler identification is MSVC 19.36.32535.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Building ver: 1.5.5-1
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- Found Protobuf: C:/Users/berkg/source/vcpkg/installed/x64-windows/tools/protobuf/protoc.exe (found version "3.21.12.0")
-- Found TIFF: optimized;C:/Users/berkg/source/vcpkg/installed/x64-windows/lib/tiff.lib;debug;C:/Users/berkg/source/vcpkg/installed/x64-windows/debug/lib/tiffd.lib (found version "4.5.1")
-- Found OpenCV: C:/Users/berkg/source/vcpkg/installed/x64-windows (found version "4.7.0")
-- Configuring done (5.7s)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Darknet
    linked by target "cli" in directory C:/Users/berkg/source/DarkHelp/src-tool
    linked by target "server" in directory C:/Users/berkg/source/DarkHelp/src-tool

-- Generating done (0.2s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by berkgungor** [comment]
Thanks for making me aware of DarkHelp. This is what I needed. I followed the documentation and tried to build DarkHelp on windows but I faced an issue as follows : 

`C:\Users\berkg\source\DarkHelp\build>cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:/Users/berkg/source/vcpkg/scripts/buildsystems/vcpkg.cmake ..`
-- The C compiler identification is MSVC 19.36.32535.0
-- The CXX compiler identification is MSVC 19.36.32535.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Building ver: 1.5.5-1
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- Found Protobuf: C:/Users/berkg/source/vcpkg/installed/x64-windows/tools/protobuf/protoc.exe (found version "3.21.12.0")
-- Found TIFF: optimized;C:/Users/berkg/source/vcpkg/installed/x64-windows/lib/tiff.lib;debug;C:/Users/berkg/source/vcpkg/installed/x64-windows/debug/lib/tiffd.lib (found version "4.5.1")
-- Found OpenCV: C:/Users/berkg/source/vcpkg/installed/x64-windows (found version "4.7.0")
-- Configuring done (5.7s)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Darknet
    linked by target "cli" in directory C:/Users/berkg/source/DarkHelp/src-tool
    linked by target "server" in directory C:/Users/berkg/source/DarkHelp/src-tool

-- Generating done (0.2s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by stephanecharette** [comment]
That means the darknet DLL, LIB, and the header files haven't been installed, so CMake cannot find them:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Darknet
```

This can be done with the AlexeyAB repo if you manually build and copy the files, or you can use these Windows instructions with the new Hank.ai repo of Darknet:  https://github.com/hank-ai/darknet#windows-cmake-method

**Comment by berkgungor** [comment]
I have generated DLL, LIB and header files from darknet repo. I installed NSIS, `C:\Program Files\Darknet ` folder waas generated with include, bin and cfg without any problem. Then I tried again to build DarkHelp with 
`msbuild.exe /property:Platform=x64;Configuration=Release /target:Build -maxCpuCount -verbosity:normal -detailedSummary DarkHelp.sln`
and 
`msbuild.exe /property:Platform=x64;Configuration=Release PACKAGE.vcxproj`
```
Build FAILED.

"C:\Users\berkg\source\DarkHelp\build\PACKAGE.vcxproj" (default target) (1) ->
"C:\Users\berkg\source\DarkHelp\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\Users\berkg\source\DarkHelp\build\src-tool\cli.vcxproj" (default target) (4) ->
"C:\Users\berkg\source\DarkHelp\build\src-lib\dh.vcxproj" (default target) (5) ->
(ClCompile target) ->
  C:\Users\berkg\source\DarkHelp\src-lib\DarkHelpNN.cpp(38,10): fatal  error C1083: Cannot open include file: 'darknet.h': No such file or directory [C:\Users\berkg\source\DarkHe
lp\build\src-lib\dh.vcxproj]

    0 Warning(s)
    1 Error(s)
```

It did not navigate darknet.h. I think I must copy the inlcude and lib files somewhere under` Darkhelp/build` ? There is no step about it in the documentation.

**Comment by stephanecharette** [comment]
Did you remember to delete the CMakeCache file in the DarkHelp/build folder?  You probably should join the Darknet/YOLO discord, it would be much easier to support you than via this "issue" ticket.

**Comment by berkgungor** [comment]
there is a good explanation about installation process for both linux and windows in darknet discord channels. I found the solution there. 

Basically, build locations had to be updated via cmake GUI and build again.
