### ISSUE TITLE
I cannot install on windows

### ISSUE THREAD

**Issue by Waariss** [AlexeyAB/darknet#8868]
`
PS C:\darknet> .\build.ps1 -UseVCPKG -EnableOPENCV -EnableCUDA -EnableCUDNN
Transcript started, output file is C:\darknet/build.log
Build script version 3.6.1, utils module version 0.3.0
Working directory: C:\darknet, log file: C:\darknet/build.log, build.ps1 is in submodule: False
PowerShell version:
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22621  2506
Running on Windows Powershell, please consider update and running on newer Powershell versions
vcpkg bootstrap script: bootstrap-vcpkg.bat
CUDA is enabled
CUDNN is enabled
OPENCV is enabled
OPENCV with CUDA extension is not enabled, you can enable it passing -EnableOPENCV_CUDA
VCPKG is enabled
VCPKG will be updated to latest version if found
VisualStudio integration is enabled, please pass -DoNotSetupVS to the script to disable
Yolo C# wrapper integration is disabled, please pass -EnableCSharpWrapper to the script to enable. You must be on Windows!
Ninja is enabled, please pass -DoNotUseNinja to the script to disable
ForceCPP build mode is disabled, please pass -ForceCPP to the script to enable
Using git from C:\Program Files\Git\cmd\git.exe
This tool has been cloned with git and supports self-updating mechanism
This tool will self-update sources, please pass -DoNotUpdateTOOL to the script to disable
Already up to date.
Test-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
At C:\darknet\build.ps1:541 char:19
+     if (Test-Path "$GitModulesPath") {
+                   ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Test
   PathCommand

Using CMake from C:\Program Files\CMake\bin\cmake.exe
cmake version 3.28.0-rc4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
Using Ninja from C:\ninja\ninja.exe
Ninja version 1.11.1
Found VS in C:\Program Files\Microsoft Visual Studio\2022\Community
Visual Studio Command Prompt variables set
Setting up environment to use CMake generator: Ninja
Added missing env variable CUDA_TOOLKIT_ROOT_DIR
Added missing env variable CUDACXX
Found vcpkg in VCPKG_ROOT: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg
Removing folder C:\darknet/build_release
Configuring release CMake project
CMake args: -G "Ninja"  -DCMAKE_BUILD_TYPE=Release  -DCMAKE_INSTALL_PREFIX=C:\darknet   -DENABLE_VCPKG_INTEGRATION:BOOL=ON -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON -DVCPKG_BUILD_OPENCV_WITH_CUDA:BOOL=OFF -DENABLE_DEPLOY_CUSTOM_CMAKE_MODULES:BOOL=ON -DVCPKG_INSTALL_OPTIONS=--clean-buildtrees-after-build -S ..
-- Setting default vcpkg target triplet to x64-windows
-- VCPKG found: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg
-- Using VCPKG integration
-- VCPKG_MANIFEST_FEATURES: cuda;cudnn;opencv-base
Darknet_VERSION: 0.2.5.7
-- Running vcpkg install
error: this vcpkg instance requires a manifest with a specified baseline in order to interact with ports. Please add 'builtin-baseline' to the manifest or add a 'vcpkg-configuration.json' that redefines the default registry.
-- Running vcpkg install - failed
CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Community/VC/vcpkg/scripts/buildsystems/vcpkg.cmake:893 (message):
  vcpkg install failed.  See logs for more information:
  C:\darknet\build_release\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:170 (include)
  CMakeLists.txt:132 (project)

CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
Config failed! Exited with error code 1.
Press any key to continue...
ScriptHalted
At C:\darknet\scripts\utils.psm1:323 char:5
+     throw
+     ~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted
`

**Comment by saqib772** [comment]
I will Suggest you to Watch Augemented Startup Video on YOLOv4 using Darknet. 
You are Facing errors in Building, Install the Things according to that video.
