### ISSUE TITLE
cudnn error - out of memory

### ISSUE THREAD

**Issue by maharleeeka** [AlexeyAB/darknet#887]
![error](https://user-images.githubusercontent.com/15627208/40461521-5337168c-5f3e-11e8-9208-aef4b1ba6471.png)

![cfg](https://user-images.githubusercontent.com/15627208/40461529-592db37a-5f3e-11e8-9b3f-022b13e24ff2.png)

I used yolov3.cfg

Any idea how I can solve this? Thank youuu

**Comment by AlexeyAB** [comment]
* What GPU do you use?
* What command do you use for training?

**Comment by maharleeeka** [comment]
@AlexeyAB 
GPU: GTX 730 
command: `darknet.exe detector train data/obj.data yolo-obj.cfg darknet53.conv.74`

But I'm thinking of closing this issue because I switched to YOLOv2 and it already works.

**Comment by AlexeyAB** [comment]
It seems you have not enough GPU-RAM.
Just use `random=0` and reduce `width=288 height=288` or less.

**Comment by maharleeeka** [comment]
@AlexeyAB thank you, will try doing that.

does it have lesser chance of detecting smaller objects if the width and height are also small?

**Comment by AlexeyAB** [comment]
> does it have lesser chance of detecting smaller objects if the width and height are also small?

Yes.

Or you can try to train yolov3-tiny.cfg with high `width height.`

**Comment by maharleeeka** [comment]
Thank you for your help.

yolov3-tiny.cfg (or the tiny versions) are for images with smaller resolution?

**Comment by AlexeyAB** [comment]
Usually for small object yolov3-tiny.cfg better than yolov2.cfg.
But yolov3.cfg more better.

**Comment by maharleeeka** [comment]
@AlexeyAB does yolov3 consumes more ram than v2?

**Comment by AlexeyAB** [comment]
* `yolov3.cfg` consumes more ram than `yolov2.cfg`
* `yolov3-tiny.cfg` consumes less  ram than `yolov2.cfg`
