### ISSUE TITLE
Darknet is not building | Darknet Sucks.

### ISSUE THREAD

**Issue by saqib772** [AlexeyAB/darknet#8873]
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	MSB3721	The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\bin\nvcc.exe"  --use-local-env -ccbin "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64" -x cu    -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\include"     --keep-dir x64\Debug  -maxrregcount=0   --machine 64 --compile -cudart static -std=c++14 -arch=native -Xcompiler="/EHsc -Zi -Ob0" -g  -D_WINDOWS -DGPU -DH5_BUILT_AS_DYNAMIC_LIB -DOPENCV -DOPENMP -DNOMINMAX -D_CRT_SECURE_NO_WARNINGS -D_USE_MATH_DEFINES -D"CMAKE_INTDIR=\"Debug\"" -D_MBCS -DWIN32 -D_WINDOWS -DGPU -DH5_BUILT_AS_DYNAMIC_LIB -DOPENCV -DOPENMP -DNOMINMAX -D_CRT_SECURE_NO_WARNINGS -D_USE_MATH_DEFINES -D"CMAKE_INTDIR=\"Debug\"" -Xcompiler "/EHsc /W1 /nologo /Od /FS /Zi /RTC1 /MDd " -Xcompiler "/Fddarknetobjlib.dir\Debug\darknetobjlib.pdb" -o darknetobjlib.dir\Debug\maxpool_layer_kernels.obj "C:\src\darknet\src\maxpool_layer_kernels.cu"" exited with code 2.	darknetobjlib	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\BuildCustomizations\CUDA 12.3.targets	799		

this sucks everytime.

**Comment by stephanecharette** [comment]
You're using a repo that was abandoned several years ago.  You may want to try the new Darknet/YOLO repo instead:  https://github.com/hank-ai/darknet#table-of-contents

**Comment by saqib772** [comment]
I tried that also, It also Have Errors in the Cmake Lists and Project didn't even run on Windows.

**Comment by stephanecharette** [comment]
Thousands of people run it on Windows.
