### ISSUE TITLE
License for linked resources (i.e. weights file)

### ISSUE THREAD

**Issue by koichiHik** [AlexeyAB/darknet#8881]
Thank you for sharing & maintaining the repo! I really appreciated.

Though I hesitate to ask about license issue after reading Yolo license that says "2. Stop emailing me about it!",   I have one question, and could not find the related issues in the past.

Regarding weights file that are not placed in Github, the Yolo lilcense still applies? For example,,,,

**yolov3.weights**
https://pjreddie.com/media/files/yolov3.weights

**yolov4.weights**
https://drive.google.com/open?id=1cewMfusmPjYWbrnuJRuKhPMwRe_b9PaT

**Comment by cenit** [comment]
[yolov4.weights](https://github.com/AlexeyAB/darknet/releases/download/yolov4/yolov4.weights)

This is the correct link for the yolov4.weights.

Everything that is in this repo is under YOLO license if not explicitly said
