### ISSUE TITLE
I compiled the darknet. But when train, it has a lot beep sound. Can i turn it off?

### ISSUE THREAD

**Issue by avkwok** [AlexeyAB/darknet#8889]
I compiled the DarkNet with my RTX-4080 laptop. But when run training, it has a lot beep sound. Can i turn it off?
In my old RTX-2070 laptop, i run DarkNet training and it has no beep sound.

./darknet detector train data/obj.data cfg/yolov7-tiny_training_480.cfg yolov7-tiny.conv.87 -dont_show -map

**Comment by avkwok** [comment]
I change the compile command
.\build.ps1 -UseVCPKG -EnableOPENCV -EnableCUDA
Enable CUDNN optional dependency (yes/no): yes
Then the beep sound is gone. Do know why?

**Comment by avkwok** [comment]
I found the solution to remove the beep sound. It is b'cos i forgot to update Makefile ARCH. After change it and recompile, everything is fine.
ARCH= -gencode arch=compute_89,code=[sm_89,compute_89]

**Comment by avkwok** [comment]
I made a mistake the beep sound still hear.

**Comment by stephanecharette** [comment]
The repo you are using is no longer supported.  You should probably be using the new Darknet/YOLO repo.  See the readme for the link.

**Comment by avkwok** [comment]
Thanks for reminder. I will try the new Darknet/YOLO repo to compile and test.

**Comment by avkwok** [comment]
Thanks for reminder. I will try the new Darknet/YOLO repo to compile and test.
