### ISSUE TITLE
For training what should be the content of corresponding .txt file for an image with no ground truth.

### ISSUE THREAD

**Issue by akshayjrkp** [AlexeyAB/darknet#890]

**Comment by AlexeyAB** [comment]
Empty txt-files:

https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

> desirable that your training dataset include images with non-labeled objects that you do not want to detect - negative samples without bounded box (empty .txt files)

**Comment by akshayjrkp** [comment]
Okay, thanks a lot.
Is it a good idea to have images with no ground truth included in the training data or should I remove them?

**Comment by AlexeyAB** [comment]
It is very desirable to have such images, as I quoted above.

**Comment by akshayjrkp** [comment]
Thanks alot.
