### ISSUE TITLE
gpu inferencing of darknet.cfg returns wrong result

### ISSUE THREAD

**Issue by vinjn** [AlexeyAB/darknet#908]
`darknet.exe classifier predict obj.data darknet.cfg darknet.weights` always give
0.6%: paintbrush
0.5%: sunglasses
0.4%: hammer
0.4%: cowboy hat
0.4%: bucket

`darknet_no_gpu.exe classifier predict obj.data darknet.cfg darknet.weights` gives correct results.

**Comment by AlexeyAB** [comment]
1. Is this happen only for your model? Or for default model too?

2. What can you get by the command?
`darknet.exe classifier predict cfg/imagenet1k.data cfg/darknet19_448.cfg darknet19_448.weights`

**Comment by vinjn** [comment]
For some unknown reason, it's working again today 💯
