### ISSUE TITLE
Changes in makefile of darknet to train detector on GPU

### ISSUE THREAD

**Issue by visha-l** [AlexeyAB/darknet#91]
I am working on image processing project and I want to train a model which can detect objects in images.
 I have made the `dataset`  using `yolo_mark` and now want to train the model on the `gpu`  tell me the changes I should make in the `MAKEFILE` so that it can be trained on `gpu` .

My files ares ::
`darknet/yolo_mark/x64/Release/data/img` , Contains the image files and corresponding text files.
`darknet/yolo_mark/x64/Release/data/obj.data`, Contain meta data.
`darknet/yolo_mark/x64/Release/data/obj.names`, Contain the name of classes.
`darknet/yolo_mark/x64/Release/data/train.txt` , Contain the path of all image files which are located in `data/img` folder.
`darknet/darknet19_448.conv.23`, this is pre-trained model.

And now i am using this command for training purpose 
`./darknet detector train data/obj.data yolo-obj.cfg darknet19_448.conv.23`
but this is running only on one `cpu`.
And if run with this command ::
`./darknet detector train data/obj.data yolo-obj.cfg darknet19_448.conv.23 -gpus 0,1,2,3`

Than also it is running on one `cpu`, This may be because I don't have `gpu` in my system, But i can find a system with `gpu` .
Tell me which version of `cuda` do i need and how to make changes in `MAKEFILE`?

Sorry for the way i have written this, (I mean the layout and sentences) . Because this is my first issue on   `github`

**Comment by AlexeyAB** [comment]
You should use CUDA 8.0, (optional cuDNN v5.1 for CUDA 8.0), and nVidia GPU.

Just set `GPU=1` here: https://github.com/pjreddie/darknet/blob/master/Makefile#L1
Also if you use cuDNN too, then set `CUDNN=1`
