### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by Luminoscity** [AlexeyAB/darknet#910]
I'm getting the following error:

```
> darknet.exe detector test data/coco.data yolov3.cfg yolov3.weights -i 0 -thresh 0.25 dog.jpg
CUDA Error: CUDA driver version is insufficient for CUDA runtime version
CUDA Error: CUDA driver version is insufficient for CUDA runtime version: No error
>
```

I'm thinking it's trying to use the wrong graphics card for darknet.
I have an NVIDIA Quadro 600 for my monitors.
But I am using an NVIDIA GTX 1080 for compute purposes only.
I'm guessing darknet is attempting to use the Quadro instead of the GTX 1080.
The Quadro definitely can't handle CUDA 9.1, but the GTX can of course.

Is my assumption right and can I force darknet to use the correct GPU?
Windows 10
CUDA 9.1 Patch 3
MSVS 2015
OpenCV 3.4.0
No compilation errors when building the solution of course.

I can try to install the display drivers for my GTX 1080, but then windows always chooses the GTX for display instead of the Quadro and I don't get the full compute capacity of the GTX 1080, so I'd rather not unless you know how I can tell windows to use the Quadro and not the GTX for display.

**Comment by AlexeyAB** [comment]
1. try to use `-i 1`:
`darknet.exe detector test data/coco.data yolov3.cfg yolov3.weights -i 1 -thresh 0.25 dog.jpg`

2. What do you by this command?
`nvidia-smi`


> I can try to **install the display drivers for my GTX 1080,** but then windows always chooses the GTX for display instead of the Quadro and **I don't get the full compute capacity of the GTX 1080**

It will take only ~2% of GPU usage, until you run the 3D application.

**Comment by Luminoscity** [comment]
Same exact message when I try `-i 1` and just for the heck of it `-i 2`
Same error message.
Output of nvidia-smi:

```
Sat May 26 04:31:39 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 377.83                 Driver Version: 377.83                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro 600         WDDM  | 0000:03:00.0      On |                  N/A |
| 30%   74C    P0    N/A /  N/A |    431MiB /  1024MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

It looks like it can't even see the GTX 1080. Maybe I will try reinstalling the display driver and plugging my monitors into the GTX card. I'm sure the compute performance drop will be almost unnoticeable as you say.

**Comment by Luminoscity** [comment]
I reinstalled the display driver and darknet works great. Super fast on the GTX 1080! Bye Bye Quadro 600, I may find use for you again one day.
