### ISSUE TITLE
bounding box coordinates, random detection, wrongly configured cfg for training

### ISSUE THREAD

**Issue by maharleeeka** [AlexeyAB/darknet#912]
1. I wanted to auto crop the objects detected, how do I get the coordinates of the boxes from predictions.png? - https://github.com/AlexeyAB/darknet/issues/912#issuecomment-392251258

2. Is it normal for weights in 300,400,500... to not detect anything at all, even if it's random detection?
the current avg loss is 2.3 something ->  https://github.com/AlexeyAB/darknet/issues/912#issuecomment-392262118
configuration:
- yolov2-voc.cfg
- filter = 45
- classes = 4
- batch = 64
- subdivision = 32

**Comment by AlexeyAB** [comment]
May be it helps you: https://github.com/AlexeyAB/darknet/issues/846#issuecomment-390785676

**Comment by maharleeeka** [comment]
@AlexeyAB Thank you. Do I have to build darknet in VS again after I edit some files inside src folder?

**Comment by AlexeyAB** [comment]
Yes.

**Comment by maharleeeka** [comment]
@AlexeyAB out of topic question (as I don't want to make a new issue), is it normal for weights 300,400,500... to not detect anything at all even if it's just a random detection, no accuracy at all?

**Comment by AlexeyAB** [comment]
Yes. Until 2000 iteration it shouldn't detect anything.

**Comment by AlexeyAB** [comment]
@maharleeeka It's okay, training is going well.
