### ISSUE TITLE
Use darknet framework on raspberry

### ISSUE THREAD

**Issue by nsantavas** [AlexeyAB/darknet#921]
@AlexeyAB I run darknet on raspberry pi model 3 using [darknet](https://github.com/shizukachan/darknet-nnpack) with FAST_NNPACK implementation. Is there any way to use your fork with NNPACK to achieve faster speed?

Thank you

**Comment by AlexeyAB** [comment]
@nsantavas No.

**Comment by jinyu121** [comment]
I tested it on TinyYOLOv3 on RaspberryPi 3B. Here are the results:

1. Compile directly: 15s
2. `OPENMP=1` : 11s
3. Add `-marm` in `CFLAGS`: 7.3s

---

nnpack on TinyYOLOv2: 0.8s, and detection result is totally  WRONG (the screen is filled with `bicycle` detection)
