### ISSUE TITLE
gray image

### ISSUE THREAD

**Issue by xunkaixin** [AlexeyAB/darknet#93]
Hi,  i want to accelerate the speed and reduece the model size.  can i  change the model input from rgb image to gray image? such as 416 * 416 * 3 to 416 * 416 * 1. i think the gray image have enough information to detect objects. but  when  i set channels =1, the model cannot detect anything? can you give me some suggestion?

**Comment by AlexeyAB** [comment]
@xunkaixin Hi, if you want to use only 1 channel, then after changing cfg-file - you should train network again.

Also there is not a good idea, to change number of channels or filters. If you want to speed-up Yolo, just use Tiny-Yolo:
* `tiny-yolo-voc.cfg`: https://github.com/AlexeyAB/darknet/blob/b585124e55fcd18a7511d3b2fdc6bc3db5368ef4/cfg/tiny-yolo-voc.cfg
* `tiny-yolo-voc.weights`: https://pjreddie.com/media/files/tiny-yolo-voc.weights
----

Or you can train Tiny-Yolo for your own custom objects - all steps are the same as for the ordinary `yolo-voc.2.0.cfg`, as described here: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects
