### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by Choneke** [AlexeyAB/darknet#935]
At first, when training YOLO V3 on the window with GPU Nvidia GeForce GTX 750 Ti  gives the message out of memory, try to fix by changing subdivision to 16, 32, still gives that error but when I changed  subdivision to 64, it runs well but at 110 iterations gives that as shown in the attachment below. How can I fix this?
![capture](https://user-images.githubusercontent.com/39613742/40732127-966c263e-646d-11e8-8ac1-5f4f760b4639.JPG)

**Comment by AlexeyAB** [comment]
* How many GB of GPU-memory do you have?
* You should use random=0 or width=288 height=288

**Comment by Choneke** [comment]
It has the following features.

![memory](https://user-images.githubusercontent.com/39613742/40755552-d2116662-64b9-11e8-8d04-6093c36e973e.JPG)

**Comment by Choneke** [comment]
And the following is the system memory
![pc](https://user-images.githubusercontent.com/39613742/40757198-58386972-64c2-11e8-9719-80fc92ee6d9a.JPG)

**Comment by AlexeyAB** [comment]
You don't have enough GPU-memory. So you should use random=0 or width=288 height=288

**Comment by Choneke** [comment]
Thank you, After changing the width and height, do I need to recalculate anchors for my dataset for width and height from cfg-file: darknet.exe detector calc_anchors data/obj.data -num_of_clusters 9 -width 288 -height 288 ?
As you stated on the procedure before training on how to improve object detection.

**Comment by AlexeyAB** [comment]
Yes you need to recalculate anchors.
You should set random=0 in all three layers.

**Comment by AlexeyAB** [comment]
For Yolo-v3 - yes.

For Yolo-v3-tiny use `-num_of_clusters 6`

**Comment by Choneke** [comment]
Thank you for your reply, I recalculate the anchor, put the same value in all 9 values in all three layers and also set random=0 in all three layer. 

Now is in progress. I will give the update.

**Comment by Choneke** [comment]
After training 2000 dataset, with one class, The avg loss seems to range from 2-1.9 for many iterations (i.e from 2000th iterations to 2700th iteration.) as shown in figures below.

![avgloss chart 2700](https://user-images.githubusercontent.com/39613742/40869983-67e452d8-6660-11e8-9013-da0c3cf97f80.JPG)

And its training progress:

![training2700iteration](https://user-images.githubusercontent.com/39613742/40870000-ad1dd612-6660-11e8-80de-92e935a081a4.JPG)


Should I stop training? Because as you comment on #419  it seems that loss cant be specific and it can range from 0.0.03 to 3.0.

If I stopped training at this iteration with this loss will it be okay or I have to wait. And for a single class as suggested in this repo  **(When Should I stop Training)**, I could train up to 2000th iteration and I can get the result.

Should I wait for more iterations?

**Comment by Choneke** [comment]
But also #419  gives me contradiction with repo **(When Should I stop training)** because in repo suggest that I should stop when avg loss=0,xxxx  and there is no longer decreasing, but in #419  said that; avg loss not specific but can range from 0.03 to 3.0.
Can I get clarification on this?

**Comment by AlexeyAB** [comment]
Try to train with width=416 height=416 and random=0, will it work?

**Comment by Choneke** [comment]
With that setting didn't work. Gives GPU memory error.

**Comment by AlexeyAB** [comment]
* After 2000 iterations usually should be avg loss less than 1.0
* Check your dataset by using: https://github.com/AlexeyAB/Yolo_mark
* What avg-loss and mAP can you get for 5000 iterations?

**Comment by Choneke** [comment]
At 6500th iteration, with avg loss of 1.7 i get the mAP =1.00,,or 100%.

As shown in the attached file below. 

![map 6500](https://user-images.githubusercontent.com/39613742/40882342-fc49ef3c-6719-11e8-9872-e694b5d1fdcf.JPG)


May be this satement which you have said **( For very hard dataset (a lot of classes, diversity of shapes, scales and rotations of objects, ...) or for non-standard network, avg-loss can be more than 1)**
Is valid for this kind of dataset. And the result may be it is ok.

**Comment by AlexeyAB** [comment]
> TP = 4104, FP = 0, FN=96
> mean average precision (mAP) = 1.000000, or 100.0 %

mAP is a primary indicator, so all works very well.

**Comment by Choneke** [comment]
Thank you for your reply
