### ISSUE TITLE
"precision" and MAP differs for single class detection. Why? Shouldn't they be same?

### ISSUE THREAD

**Issue by akshayjrkp** [AlexeyAB/darknet#949]
Result I got
precision= 0.79
ap = 48.48 %
map = 48.48 %

**Comment by AlexeyAB** [comment]
* AP (average precision) == mAP (mean average precision) for 1 class.
* Precision is not AP (average precision). Precision is calculated for specified threshold `-thresh 0.24`. But AP (average precision) is calculated for any threshold for 11 points on Precision-Recall curve.

**Comment by akshayjrkp** [comment]
Okay. Thank you so much for the clarification.
