### ISSUE TITLE
Get error when tried to train classifier model

### ISSUE THREAD

**Issue by visha-l** [AlexeyAB/darknet#95]
I want to make a classifier which can distinguish among 3 different fruits (apple,mango,banana). and I followed the instructions from [LINK ]().
I create a separate folder `Fruits` and put `train` folder which contain the `.jpg` files of all three fruits. 
I added `test` folder which contains `.jpg` files of all three fruits.
I added `test;.list` file which contains all paths of the images stored in `test` folder.
I added `train.list` file which contains all paths of the images stored in `train` folder
I added `label.txt` file which contains the name of these three fruits name.
  Preview

I want to make a classifier which can distinguish among 3 different fruits (apple,mango,banana). and I followed the instructions from [LINK ]().
I create a separate folder `Fruits` and put `train` folder which contain the `.jpg` files of all three fruits. 
I added `test` folder which contains `.jpg` files of all three fruits.
I added `test;.list` file which contains all paths of the images stored in `test` folder.
I added `train.list` file which contains all paths of the images stored in `train` folder
I added `label.txt` file which contains the name of these three fruits name.

```
pause@user1:~/darknet$ ./darknet classifier train cfg/fruits.data  cfg/fruits.cfg
fruits
1
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1    28 x  28 x   3   ->    28 x  28 x  32
    1 max          2 x 2 / 2    28 x  28 x  32   ->    14 x  14 x  32
    2 conv     64  3 x 3 / 1    14 x  14 x  32   ->    14 x  14 x  64
    3 max          2 x 2 / 2    14 x  14 x  64   ->     7 x   7 x  64
    4 conv    128  3 x 3 / 1     7 x   7 x  64   ->     7 x   7 x 128
    5 conv      3  1 x 1 / 1     7 x   7 x 128   ->     7 x   7 x   3
    6 avg                        7 x   7 x   3   ->     3
    7 softmax                                           3
    8 cost                                              3
Learning Rate: 0.1, Momentum: 0.9, Decay: 0.0005
0
Floating point exception (core dumped)

```

How can i remove this error. please help me out.

**Comment by barresoft** [comment]
i think that you have to put file names into a train.txt files inside data, not a train folder with the pictures....
