### ISSUE TITLE
Fail to open darknet.sln

### ISSUE THREAD

**Issue by daiwc** [AlexeyAB/darknet#959]
There is nothing while i open the darknet.sln!

**Comment by AlexeyAB** [comment]
What MSVS, OpenCV and CUDA version do you have?

Follow this guide: https://github.com/AlexeyAB/darknet#how-to-compile-on-windows

**Comment by daiwc** [comment]
The  version of VS2015 is 14.0.25431.01 Update3
 Opencv is 3.4.0
 CUDA is 9.0 and cudnn is 7.0

**Comment by daiwc** [comment]
@AlexeyAB  Thanks a lot. I am sorry for my carelessness.
