### ISSUE TITLE
Detector not training faster why ?

### ISSUE THREAD

**Issue by visha-l** [AlexeyAB/darknet#96]
I am making a detector as you have mentioned in this link [build detector from scratch](https://github.com/AlexeyAB/darknet), I followed all the instructions and now I am using `p2.xlarge`  (`EC2` instance of `AWS`) to provide it `gpu` for fast training, but it is training with the same speed as it was, when I was not using `gpu`.
This `p2.xlarge` has `GPU=1` so It should run faster but, this is not happening why ?

I have changed in `Makefile` (GPU=1) , as instructed in [link](https://github.com/AlexeyAB/darknet).
so tell me what else needs to be done.

**Comment by AlexeyAB** [comment]
At first, make sure that everything is compiled without errors.

* What CUDA version do you use?
* What cuDNN version do you use?
* Copy-pase here output from command `make`, when you try to make Darknet Yolo with flags GPU=1 CUDNN=1.
* Copy-pase here output from command `nvidia-smi`

**Comment by visha-l** [comment]
```
vishal@user756:~/darknet$ make
gcc  -DGPU -I/usr/local/cuda/include/ -Wall -Wfatal-errors  -Ofast -DGPU -c ./src/detector.c -o obj/detector.o
nvcc  -gencode arch=compute_20,code=[sm_20,sm_21] -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52]  -DGPU -I/usr/local/cuda/include/ --compiler-options "-Wall -Wfatal-errors  -Ofast -DGPU" -c ./src/convolutional_kernels.cu -o obj/convolutional_kernels.o
/bin/sh: 1: nvcc: not found
make: *** [obj/convolutional_kernels.o] Error 127
```

I am using `CUDA Version 8.0.61`.
No `cuDNN` 
I am using `p2.xlarge` which is on some remote machine so I was not able to run `nvidia-smi`  command.

**Comment by AlexeyAB** [comment]
Try to solve this make-error: https://www.google.ru/search?q=fatal+error%3A+cuda_runtime.h%3A+No+such+file+or+directory&rlz=1C1MSIM_enRU714RU714&oq=fatal+error%3A+cuda_runtime.h%3A+No+such+file+or+directory&aqs=chrome..69i57.199j0j7&sourceid=chrome&ie=UTF-8

**Comment by visha-l** [comment]
Is this the problem of `cuda` . only right.
I have `cuDnn` with 6.0.21 version is that fine.

**Comment by visha-l** [comment]
```
nvcc  -gencode arch=compute_20,code=[sm_20,sm_21] -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52]  -DGPU -I/usr/local/cuda-7.0/include/ --compiler-options "-Wall -Wfatal-errors  -Ofast -DGPU" -c ./src/convolutional_kernels.cu -o obj/convolutional_kernels.o
nvcc fatal   : 'sm_21]' is not in 'keyword=value' format
make: *** [obj/convolutional_kernels.o] Error 255

```

why getting this error?

**Comment by visha-l** [comment]
Please help me out.
```
ubuntu@ip-10-0-0-226:~/darknet$ ./darknet detector train Yolo_mark-master/x64/Release/data/obj.data Yolo_mark-master/x64/Release/yolo-obj.cfg darknet19_448.conv.23
yolo-obj
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1  1088 x1088 x   3   ->  1088 x1088 x  32
    1 max          2 x 2 / 2  1088 x1088 x  32   ->   544 x 544 x  32
    2 conv     64  3 x 3 / 1   544 x 544 x  32   ->   544 x 544 x  64
    3 max          2 x 2 / 2   544 x 544 x  64   ->   272 x 272 x  64
    4 conv    128  3 x 3 / 1   272 x 272 x  64   ->   272 x 272 x 128
    5 conv     64  1 x 1 / 1   272 x 272 x 128   ->   272 x 272 x  64
    6 conv    128  3 x 3 / 1   272 x 272 x  64   ->   272 x 272 x 128
    7 max          2 x 2 / 2   272 x 272 x 128   ->   136 x 136 x 128
    8 CUDA Error: out of memory
darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
Aborted (core dumped)

```

**Comment by AlexeyAB** [comment]
Show first 10 lines of `Yolo_mark-master/x64/Release/yolo-obj.cfg`

And try to set `subdivisions=16` in `yolo-obj.cfg`: https://github.com/AlexeyAB/darknet/blob/master/cfg/yolo-voc.2.0.cfg#L3

**Comment by visha-l** [comment]
[net]
batch=1
subdivisions=8
height=1088
width=1088
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

**Comment by AlexeyAB** [comment]
As said here: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

> * change line batch to batch=64
> * change line subdivisions to subdivisions=8

----

https://www.google.ru/search?q=libcudart.so.7.0%3A+cannot+open+shared+object+file&rlz=1C1MSIM_enRU714RU714&oq=libcudart.so.7.0%3A+cannot+open+shared+object+file&aqs=chrome..69i57.680j0j7&sourceid=chrome&ie=UTF-8

> export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

**Comment by visha-l** [comment]
Ok sir , I will check it, right now I am reinstalling `OpenCV` because it was giving me error when I run this command 
```
ubuntu@ip-10-0-0-226:~/darknet/Yolo_mark-master$ cmake .
CMake Error at CMakeLists.txt:3 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/darknet/Yolo_mark-master/CMakeFiles/CMakeOutput.log".

```
Can you please tell me how to fix that error I found this [LINK](https://stackoverflow.com/questions/8711109/could-not-find-module-findopencv-cmake-error-in-configuration-process) but do not understand. 

`CMakeLists.txt` File is ::
```
cmake_minimum_required(VERSION 2.8)
project( yolo_mark CXX )
find_package( OpenCV REQUIRED )
TARGET_LINK_LIBRARIES(MY_TARGET_NAME ${OpenCV_LIBS})
set( sources main.cpp )

add_executable( yolo_mark ${sources} )

target_compile_options( yolo_mark PUBLIC -std=c++11 -fpermissive -w -Wall )

target_link_libraries( yolo_mark ${OpenCV_LIBS} -L/usr/lib64 -ldl )

```

**Comment by visha-l** [comment]
If I understand it correctly then `batch in .cfg` file  is the number of images that It will train in each  iteration. I am using `p2.xlarge` which has `count of gpu=1 ` , and when i start my detector training with `batch=32, subdivisions=8` it give `core dump` ,  and when I decreased this `batch` value to `batch=16` it runs it 579 iterations but then it stopped with error It can not load `backup//yolo-obj_580.weights` file. and also when I checked the `weight` file like `yolo-obj_300.wieghts` it contains some bytes `256MB` but the other files above 300 were not containing the data. even file `yolo-obj_350.weights` file is not containing data.

And sir, when I tested my image with this file  it gives following output.
```

 vishal@user756:~/darknet$ ./darknet detect Yolo_mark-master/x64/Release/yolo-obj.cfg /home/vishal/Desktop/yolo-obj_300.weights /home/vishal/CARS/Audi/audi_1.jpg -thres 0
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1  1088 x1088 x   3   ->  1088 x1088 x  32
    1 max          2 x 2 / 2  1088 x1088 x  32   ->   544 x 544 x  32
    2 conv     64  3 x 3 / 1   544 x 544 x  32   ->   544 x 544 x  64
    3 max          2 x 2 / 2   544 x 544 x  64   ->   272 x 272 x  64
    4 conv    128  3 x 3 / 1   272 x 272 x  64   ->   272 x 272 x 128
    5 conv     64  1 x 1 / 1   272 x 272 x 128   ->   272 x 272 x  64
    6 conv    128  3 x 3 / 1   272 x 272 x  64   ->   272 x 272 x 128
    7 max          2 x 2 / 2   272 x 272 x 128   ->   136 x 136 x 128
    8 conv    256  3 x 3 / 1   136 x 136 x 128   ->   136 x 136 x 256
    9 conv    128  1 x 1 / 1   136 x 136 x 256   ->   136 x 136 x 128
   10 conv    256  3 x 3 / 1   136 x 136 x 128   ->   136 x 136 x 256
   11 max          2 x 2 / 2   136 x 136 x 256   ->    68 x  68 x 256
   12 conv    512  3 x 3 / 1    68 x  68 x 256   ->    68 x  68 x 512
   13 conv    256  1 x 1 / 1    68 x  68 x 512   ->    68 x  68 x 256
   14 conv    512  3 x 3 / 1    68 x  68 x 256   ->    68 x  68 x 512
   15 conv    256  1 x 1 / 1    68 x  68 x 512   ->    68 x  68 x 256
   16 conv    512  3 x 3 / 1    68 x  68 x 256   ->    68 x  68 x 512
   17 max          2 x 2 / 2    68 x  68 x 512   ->    34 x  34 x 512
   18 conv   1024  3 x 3 / 1    34 x  34 x 512   ->    34 x  34 x1024
   19 conv    512  1 x 1 / 1    34 x  34 x1024   ->    34 x  34 x 512
   20 conv   1024  3 x 3 / 1    34 x  34 x 512   ->    34 x  34 x1024
   21 conv    512  1 x 1 / 1    34 x  34 x1024   ->    34 x  34 x 512
   22 conv   1024  3 x 3 / 1    34 x  34 x 512   ->    34 x  34 x1024
   23 conv   1024  3 x 3 / 1    34 x  34 x1024   ->    34 x  34 x1024
   24 conv   1024  3 x 3 / 1    34 x  34 x1024   ->    34 x  34 x1024
   25 route  16
   26 reorg              / 2    68 x  68 x 512   ->    34 x  34 x2048
   27 route  26 24
   28 conv   1024  3 x 3 / 1    34 x  34 x3072   ->    34 x  34 x1024
   29 conv    125  1 x 1 / 1    34 x  34 x1024   ->    34 x  34 x 125
   30 detection
Loading weights from /home/vishal/Desktop/yolo-obj_300.weights...Done!
Segmentation fault (core dumped)

```

I am trying to find the logo of the car,  so I gather 20 different make cars and took around 25 images per class, and also used `yolo_mark` to create `txt` file corresponding to each image file.

I created obj.names file which contains the class (name of make of car) in each new line.

```
chevrolet
honda
hyundai
mahindra
nissan
skoda
tata
toyota
audi
bmw
datsun
fiat
ford
jaguar
maruti-suzuki
mercedes
range-rover
renault
volkswagen
volvo
```

I created obj.data file which contains.
```
classes= 20
train  = data/train.txt
valid  = data/train.txt
names = data/obj.names
backup = backup/

```
`Makefile` starting content .
```
GPU=1
CUDNN=1
OPENCV=1
DEBUG=0

ARCH= -gencode arch=compute_20,code=[sm_20,sm_21] \
      -gencode arch=compute_30,code=sm_30 \
      -gencode arch=compute_35,code=sm_35 \
      -gencode arch=compute_50,code=[sm_50,compute_50] \
      -gencode arch=compute_52,code=[sm_52,compute_52]
ed obj.names file which co
# This is what I use, uncomment if you know your arch and want to specify
# ARCH=  -gencode arch=compute_52,code=compute_52

VPATH=./src/
```
Sir in above comment I have shown you my `.cfg` file.


So please answer me how can I solve the problem of segmentation fault  which is coming during training as wekk as during testing which I tested with starting `weight` files. 

It will be great help sir.

thanks a lot for all help  you did till now, please help me little more

**Comment by visha-l** [comment]
Please help me out .

One more thing sir I want to ask you. If a single `weight` file is taking `256MB` ,which is created by a single iteration and we are suppose to run it for 1000 iterations at-least then what will be the storage requirement for this number of weight file.

I was using `60GB` storage for this and , It get filled and training stopped at 579th iteration. by giving error that can't load `yolo-obj_580.weights` file. and `no storage left`. 

So, How much storage is required to store these `weight` files.

**Comment by AlexeyAB** [comment]
* for (0 - 1000) iterations - for each 100 iterations weights saved
* for (1000 - inf) iterations - for each 1000 iterations weights saved

If you use `height=1088` and `width=1088` then set:
`batch=16`
`subdivisions=16`
`random=0`

**Comment by vg123** [comment]
What all these terms stand for. Is there any documentation to understand the meaning of these term of `.cfg` file.

**Comment by AlexeyAB** [comment]
@visha-l @vg123 You should use:

* `yolo-voc.2.0.cfg` as initial cfg-file for your `yolo-car.cfg` as described here: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects
* If you train on Linux, then you should use this Linux version of Darknet Yolo v2: https://github.com/pjreddie/darknet
* You shouldn't change any lines in source code, or any lines in cfg-file which aren't described in manual
