### ISSUE TITLE
Inappropriate ioctl for device

### ISSUE THREAD

**Issue by jackwei0117** [AlexeyAB/darknet#963]
Hi AlexeyAB,

I got this message while running yolov2(old version released about a half year ago).
"Inappropriate ioctl for device"
It seems like a opencv issue, could you please help me with this ?
Thank you.

Some information:
CUDA 9.1
OPENCV 3.4.0
GPU GTX980
ubuntu 18.04 lts

**Comment by AlexeyAB** [comment]
@jackwei0117  Hi,

> "Inappropriate ioctl for device"

* Looks like you try to open file that is located on remote disk (NFS, SMB, ...).
* What command do you use for run yolo?
* What can you see when run `nvidia-smi`?

**Comment by jackwei0117** [comment]
1. It's in local machine, and I can open the video as well
2. darknet detector demo
3.
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.26                 Driver Version: 396.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980     Off  | 00000000:03:00.0  On |                  N/A |
| 32%   35C    P8    22W / 195W |    166MiB /  4042MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1202      G   /usr/lib/xorg/Xorg                            12MiB |
|    0      1288      G   /usr/bin/gnome-shell                          49MiB |
|    0      1473      G   /usr/lib/xorg/Xorg                            47MiB |
|    0      1612      G   /usr/bin/gnome-shell                          53MiB |
+-----------------------------------------------------------------------------+
Thanks!

**Comment by AlexeyAB** [comment]
* Can you show full command?
* Can you run `detector demo` after compilation with `OPENCV=0` in the Makefile?
* Can you run `detector demo` after compilation with `GPU=0 CUDNN=0 OPENCV=0` in the Makefile?

**Comment by wait1988** [comment]
So how you solve this problem?

**Comment by visshvesh** [comment]
Any one with the solution on this?

**Comment by jackwei0117** [comment]
Dear all,

Sorry for extremely late reply.
I didn't solve it, I simply switch to the pjreddie's version from official website:
https://pjreddie.com/darknet/yolo/

Regards
