### ISSUE TITLE
Reduced recognition rate after updating GitHub code

### ISSUE THREAD

**Issue by cuteyuyu** [AlexeyAB/darknet#964]
After using darknet_no_gpu and yolov2_tiny to train my weight in April.
After using Update my code from GitHub, using the same weight, the same photo recognition rate becomes lower
When ipcam is used, the video is terminated halfway (as shown below)!! Old code does not terminate.
Do you need to make any changes after updating GitHub?Want to train weight again?
![ss](https://user-images.githubusercontent.com/38469710/40871941-b867bfb2-6677-11e8-919b-7ea8d92788ad.JPG)

Video termination!!!
![7](https://user-images.githubusercontent.com/38469710/40872313-bab99ba8-667e-11e8-821b-8d331328367b.JPG)

**Comment by AlexeyAB** [comment]
in the new repo:
* un-comment this line: https://github.com/AlexeyAB/darknet/blob/4cf4a89f05c671041c217a724fc9b4b026eb9de9/src/detector.c#L1101
* comment this line: https://github.com/AlexeyAB/darknet/blob/4cf4a89f05c671041c217a724fc9b4b026eb9de9/src/detector.c#L1102

What probability can you get now?


> When ipcam is used, the video is terminated halfway (as shown below)!! 

how many seconds?

**Comment by cuteyuyu** [comment]
@AlexeyAB The method is feasible, the recognition rate is solved ~
![89](https://user-images.githubusercontent.com/38469710/40878531-32b92c0e-66c5-11e8-9add-af24ff9f2df3.JPG)

However, the new GitHub code ipcam video will still stop and stop in about 5 seconds.
Old GitHub Code Does Not stop to occur

**Comment by AlexeyAB** [comment]
> However, the new GitHub code ipcam video will still stop and stop in about 5 seconds.
> Old GitHub Code Does Not stop to occur

@cuteyuyu Ok, I will check.
* What OpenCV version do you use?
* What OS do you use?
* Do you have `opencv_ffmpeg320_64.dll` file near with `darknet.exe` on Windows?
* Does it work correctly with video-files?

**Comment by cuteyuyu** [comment]
@AlexeyAB Video test is very important to me Please help me
1.I use cmd...
darknet_no_gpu.exe detector demo data/obj.data cfg/yolov2-tiny-obj.cfg backup/yolov2-tiny-obj_2000.weights http://admin:idblab@203.64.95.60:554/video/mjpg.cgi?dummy=.mjpg -i 0
2.opencv3.0
3.MVS2015 opencv3.0  I have no gpu
4.Is this ? Put the .dll in the same directory as darknet.exe?
![77](https://user-images.githubusercontent.com/38469710/40883473-a78f8fda-6730-11e8-8be4-0a247d06f33f.JPG)

**Comment by cuteyuyu** [comment]
@AlexeyAB 
After updating the code
Ipcam will not stop, but the video will go dark after 3 seconds, but the program is still running
How to solve this problem?
![99](https://user-images.githubusercontent.com/38469710/40897188-3b809f20-67ec-11e8-9907-ca27bc19c076.JPG)

**Comment by AlexeyAB** [comment]
* If you wait about 60 seconds, will screen still black?

* Try to change this line: https://github.com/AlexeyAB/darknet/blob/132251d72325e1005ef6c47f83d6a4e9b9355d12/src/image.c#L1037

to these code:
```cpp
if (cpp_video_capture) {
  cvReleaseImage(&src); 
  int z = 0;
  for(z = 0; z < 5; ++z) {
    get_webcam_frame(cap);
  }
}
```

**Comment by cuteyuyu** [comment]
@AlexeyAB 
Is there a way to solve it? Video is very important to me
please help me

**Comment by cuteyuyu** [comment]
@AlexeyAB  
There will be no black sreen after the change. The video is also smooth.
But the accuracy rate has dropped . Picture accuracy is also down 89% to 44%
Is it because of the change cfg-file factor?
Do I want to retrain new weights?
![88](https://user-images.githubusercontent.com/38469710/41077063-4731fb36-6a47-11e8-875f-519842989f82.JPG)

**Comment by AlexeyAB** [comment]
@cuteyuyu 

1. If you can, decrease GOP-length in your IP-camera.

2. Just set back `width=416 height=416`

3. And change this code:
```cpp
if (cpp_video_capture) {
  cvReleaseImage(&src); 
  int z = 0;
  for(z = 0; z < 5; ++z) {
    get_webcam_frame(cap);
  }
}
```

to this
```cpp
		if (cpp_video_capture) {
			cvReleaseImage(&src);
			int z = 0;
			for (z = 0; z < 30; ++z) {
				get_webcam_frame(cap);
				cvReleaseImage(&src);
			}
		}
```

**Comment by cuteyuyu** [comment]
@AlexeyAB 
I don't know how to lower gop . I will lower the bps and fps
Change back to width=416 height=416
Sometimes it will be black sreen when it is executed. Sometimes it will not happen.
Do you still need to modify anything?

**Comment by AlexeyAB** [comment]
> Sometimes it will be black sreen when it is executed. Sometimes it will not happen.

When black screen is apeared, then it remains forever or after 1-2 seconds the image from IP-cam appears again?

**Comment by cuteyuyu** [comment]
@AlexeyAB 
Will always be black 
Need to turn off re-execution . 
But sometimes the implementation will not happen with black .

**Comment by AlexeyAB** [comment]
> I don't know how to lower gop . I will lower the bps and fps

Did you try this? If you can't set GOP-length, try to change another codec MJPEG instead of H264.

Also try to set here 40, 50, 100 instead of 30 in this line: `for (z = 0; z < 30; ++z) {`

**Comment by AlexeyAB** [comment]
In general - you should use:

* or IP-camera with GOP-length = 1

* or buy GPU that can detect with 30 FPS (for example GeForce GTX 1050 - 170$) with 1500 GFlops or higher: https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units#GeForce_10_series
