### ISSUE TITLE
Core Dump with CUDNN_HALF set to 1 on Azure V100 VM

### ISSUE THREAD

**Issue by yyuzhongpv** [AlexeyAB/darknet#968]
Hi,

I crate a VM with V100 on Microsoft Azure, and installed Ubuntu 16.04, CUDA 9.1 and CUDNN 7.1 etc.
I used the latest codes (06/02/18) on GitHub, and call the C interfaces in my C++ codes.  
If I turn off the CUDNN_HALF, everything is good.
However, after I turn on CUDNN_HALF, I got core dump error in network_predict().

Any suggestions to debug?

Thanks!

**Comment by AlexeyAB** [comment]
Hi,

> However, after I turn on CUDNN_HALF, I got core dump error in network_predict().

* Did you get core dump error immideately or after some predictions/frames?
* Can you train or detect with `CUDNN_HALF=1` without your own C++ code, by using `./darknet detector test ...`?
* Do you use flags in the Makefile `GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=1 DEBUG=0`?
* How many GPUs do you use?

**Comment by yyuzhongpv** [comment]
Hello Alexey,
Thanks for your quick reply. 
I can't reproduce the problem now after I run the command line ./darknet detector test successfully even with my C/C++ codes. I will try to run more tests.

1. •Did you get core dump error immideately or after some predictions/frames?
Yes. At first frame.
•Can you train or detect with CUDNN_HALF=1 without your own C++ code, by using ./darknet detector test ...?
Yes. it works in that command. 
•Do you use flags in the Makefile GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=1 DEBUG=0?
Yes.
•How many GPUs do you use?
Only one V100 on Azure VM.

However, another problem I found is that I can't see any difference with CUDNN_HALF set to 1 and 0.
The running time of network_predict keeps on 0.02s or 20ms with CUDNN_HALF set to 1 and 0 .

Any suggestions?
Thanks!

**Comment by AlexeyAB** [comment]
> I can't reproduce the problem now after I run the command line ./darknet detector test successfully even with my C/C++ codes. I will try to run more tests.

* Yes, check you C++ code or try to localize this error in the Darknet-code.

> However, another problem I found is that I can't see any difference with CUDNN_HALF set to 1 and 0.
> The running time of network_predict keeps on 0.02s or 20ms with CUDNN_HALF set to 1 and 0 .

* What model do you use?
* What can you see by using `nvidia-smi` command?

For `tiny-yolo-voc.cfg` it doesn't give any advantage, but 3x faster for `yolov3.cfg` and `yolo-voc.2.0.cfg`: https://github.com/AlexeyAB/darknet/issues/407
I didn't test it on `yolov3-tiny.cfg`.

Try to run:
`./darknet detector test data/coco.data yolov3.cfg yolov3.weights -i 0 -thresh 0.25` without image file
and then enter `dog.jpg` several times.

**Comment by yyuzhongpv** [comment]
Thanks Alexy!
I use yolov3.cfg. 

The output of NVidia-smi:
-----------------------------------------------------------------------------+| NVIDIA-SMI 396.26                 Driver Version: 396.26                    ||-------------------------------+----------------------+----------------------+| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC || Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. ||===============================+======================+======================||   0  Tesla V100-PCIE...  Off  | 0000802F:00:00.0 Off |                    0 || N/A   30C    P0    36W / 250W |      0MiB / 16160MiB |      4%      Default |+-------------------------------+----------------------+----------------------++-----------------------------------------------------------------------------+| Processes:                                                       GPU Memory ||  GPU       PID   Type   Process name                             Usage      ||=============================================================================||  No running processes found                                                 |+-----------------------------------------------------------------------------+

It is wired that if I run my C/C++ code to call darknet.so, I got this performance.
/home/yyuzhong/NxGen7200/0000201701264918_JB_JC_rr.jpg: Predicted in **0.021736** seconds.

If I run the command: ./darknet detector test /home/yyuzhong/Jointbar-Inspection_WS/yolo.data /home/yyuzhong/Jointbar-Inspection_WS/yolo.cfg /home/yyuzhong/Jointbar-Inspection_WS/backup/yolo_final.weights -i 0 -dont_show  -thresh 0.25 and type in the jpeg file, I got: 
/home/yyuzhong/NxGen7200/0000201701264918_JB_JC_rr.jpg: Predicted in **0.012385** seconds.

Why it has the big difference in the processing time? 

This is the codelet I call the darknet, I compare them with the codes of detector.c in your repo, and seems no much difference.  

    clock_t t;
    t = clock();
    image im = load_image_color((char *) imagePath.c_str(), 0, 0);
    t = clock() - t;
    accLoadTime += ((float)(t)/CLOCKS_PER_SEC);
    printf("Image Load Time: %.6f\n", ((float)t)/CLOCKS_PER_SEC);

    t = clock();
    image sized = letterbox_image(im, net->w, net->h);
    t = clock() - t;
    accResizeTime += ((float)(t)/CLOCKS_PER_SEC);
    printf("Image Resize Time: %.6f\n", ((float)t)/CLOCKS_PER_SEC);
    int imw = im.w;
    int imh = im.h;
    #endif

    layer l = net->layers[net->n-1];
    float *X = sized.data;
    t = clock();
    set_batch_network(net,1);
    #if OFFICIAL_DARKNET
    network_predict(net, X);
    #else
    network_predict(*net, X);
    #endif
    t = clock() - t;
    accPredictTime += ((float)(t)/CLOCKS_PER_SEC);
    printf("%s: Predicted in %.6f seconds.\n", imagePath.c_str(), ((float)t)/CLOCKS_PER_SEC);

    int nboxes = 0;
    #if OFFICIAL_DARKNET
    detection *dets = get_network_boxes(net, imw, imh, thresh, hier_thresh, 0, 1, &nboxes);
    #else
    detection *dets = get_network_boxes(net, imw, imh, thresh, hier_thresh, 0, 1, &nboxes,1);
    #endif

    if (nms) do_nms_sort(dets, nboxes, l.classes, nms);

    int nclasses = 6;

    // Result of the detection will be collected in objects vector.
    vector <Object> objects;
    for (int j = 0; j < nboxes; j++){
        box boxes = dets[j].bbox;
        for (int i = 0; i < nclasses; i++){
            if (dets[j].prob[i] > 0){
                Object obj;
                // Setup attributes
                obj.name = names[i];
                obj.probability = dets[j].prob[i];
                obj.centerX = boxes.x;
                obj.centerY = boxes.y;
                obj.width = boxes.w;
                obj.height = boxes.h;
                // Convert from YOLO to BB
                obj.x1 = (int)((obj.centerX - (obj.width / 2.0))*imw);
                obj.y1 = (int)((obj.centerY - (obj.height / 2.0))*imh);
                obj.x2 = (int)((obj.centerX + (obj.width / 2.0))*imw);
                obj.y2 = (int)((obj.centerY + (obj.height / 2.0))*imh);
                obj.rgb = Color::getColorForLabel(obj.name);
                objects.push_back(obj);
            }
        }
    }
    // Deleting Reference to the image data pointer and other extra pointers.
    free_detections(dets, nboxes);
    //free_image(im); 
    free_image(sized);

    return objects;

**Comment by AlexeyAB** [comment]
* `set_batch_network(net,1);` - this command re-allocate CPU and GPU memory, it takes very long time.

* Also I just yet added fix, to use `fuse_conv_batchnorm(network net)` from DLL/SO-library.

Use this code with the latest version from this repository:

```cpp
set_batch_network(net,1);
#ifndef OFFICIAL_DARKNET
fuse_conv_batchnorm(*net); // you can fuse: batch-norm + conv --to--> single conv-layer
#endif
layer l = net->layers[net->n-1];
float *X = sized.data;
t = clock();
//set_batch_network(net,1); // this command re-allocate CPU and GPU memory, it takes very long time
#if OFFICIAL_DARKNET
network_predict(net, X);
#else
network_predict(*net, X);
#endif
t = clock() - t;
accPredictTime += ((float)(t)/CLOCKS_PER_SEC);
printf("%s: Predicted in %.6f seconds.\n", imagePath.c_str(), ((float)t)/CLOCKS_PER_SEC);
```

**Comment by AlexeyAB** [comment]
Also better to use `what_time_is_it_now()` instead of `clock();`

**Comment by yyuzhongpv** [comment]
Thanks Alexey.
It means that while I test multiple images, set_batch_network and fuse_conv_batchnorm only need to be called once after I crate the network, right?

**Comment by AlexeyAB** [comment]
Yes.

**Comment by yyuzhongpv** [comment]
Remember to use the same compiling options (GPU and CUDNN) in both Darknet and own C/C++ codes.
