### ISSUE TITLE
darknet.sln 

### ISSUE THREAD

**Issue by MyAusweis** [AlexeyAB/darknet#97]
Dear all

Darknet.sln cannot open project using visual studio community 2015, any one know why ? (load failed)

Thx

**Comment by AlexeyAB** [comment]
Hi, install CUDA **8.0** only after MSVS2015 installed.

**Comment by MyAusweis** [comment]
Dear 

I already installed msvs2015, and i plan to use cpu only, 

Thx

**Comment by AlexeyAB** [comment]
Then use `yolo_cpp_dll_no_gpu.sln`
