### ISSUE TITLE
How to Increase the FPS ?

### ISSUE THREAD

**Issue by halimB8** [AlexeyAB/darknet#971]
Hello, 
I am using yolov3's weight and make a filter to just save cars and trucks detected I tried to test it in Google colab ( tesla K80), ( video.mp4, 30fps , 640x360)
I compiled yolo with : 
cuda 8.0
cudnn 7.0.5
OpenCv 3.4.0
and when I run a video test I got just 12 to 13 fps 
is it maybe because GPU in google colab is shared by all the users ? or there is something to do to increase fps ? cause I need a real time detection ( I can't use tiny yolo cause I need accuracy too ) !
and will the number of fps increase if I train my network to detect just these 2 classes ? 
Best regards

**Comment by AlexeyAB** [comment]
Hello,

> and will the number of fps increase if I train my network to detect just these 2 classes ?

No, speed doesn't depend on number of classes. Accuracy depends on number of classes.

K80 GPU Accelerator - **2×** GK210 - 5591–8736 GFlops ~ 7000 GFlops: https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units#Tesla

So actually you have 2 GPUs on the one VideoCard, but detection can use only 1 GPU, so you have ~3500 Gflops. Such GPU should give you about **20 FPS on Yolo v3 416x416.**

> is it maybe because GPU in google colab is shared by all the users ? or there is something to do to increase fps ?

May be yes. 
But even if only you will use entire GPU in exclusive manner, then you can reach not more than 20 FPS, that is less than 30 FPS in your video.

You can try to train Yolov3-tiny for only your two classes. So if you will use 2 classes instead of 80 - then accuracy will be higher than default Yolov3-tiny model. But you should use number of images the same or more than were used for training default Yolov3-tiny model.

**Comment by halimB8** [comment]
Thank you for all these informations, I will prepare a database of cars and train my network with Yolov3-tiny :)

**Comment by yyuzhongpv** [comment]
So I can get about 80fps with YoloV3 on V100 (14000 Gflops), right? 
Thanks!

**Comment by AlexeyAB** [comment]
@yyuzhongpv Theoretically yes. 
But as I measured - you can get ~33 FPS with `CUDNN_HALF=0` and ~90 FPS with `CUDNN_HALF=1` on V100: https://github.com/AlexeyAB/darknet/issues/407

**Comment by yyuzhongpv** [comment]
@AlexeyAB Very good. It is similar to my test on V100 VM on Azure with CUDNN_HALF=0. 
My image is a little larger (2048x7200), and image resize is very slow on CPU, and GPU version will be better. I am sure we can get near real-time processing on video streaming. Thanks for your and Joseph's wonderful work!

Average Loading Time: 0.047624
Average Resizing Time: 0.003772 (GPU Version)
Average Predicting Time: 0.018770

**Comment by AlexeyAB** [comment]
@yyuzhongpv 
I use `cvResize()` https://github.com/AlexeyAB/darknet/blob/1e512b23089b23e91fa5ed6a617641d9286d1417/src/image.c#L1044
that is **~4x times faster** than `letterbox_image_into()` https://github.com/pjreddie/darknet/blob/f6d861736038da22c9eb0739dca84003c5a5e275/src/image.c#L944-L958
that is used **in the original repo for video** `./darknet detector demo ...`: https://github.com/pjreddie/darknet/blob/f6d861736038da22c9eb0739dca84003c5a5e275/src/demo.c#L144

So I can get ~30 FPS on 4K (3840x2026) and ~60 FPS on Full-HD (1920x1080). For my cases it was enough, I can process Full-HD video 50 FPS in real-time.

Do you use satellite imagery with resolution `2048x7200`? 
And did you write your own CUDA function for resizing using linear interpolation?
Almost all information about small objects will be lost if you do not use a very large size of neural network (at least `width=2048 height=1024`).

**Comment by yyuzhongpv** [comment]
Thanks for you information Alexey!
My images are from line scan camera with about 100 fps. I refer these codes (http://www.coldvision.io/2015/12/22/image-resize-with-opencv-and-cuda/) to optimize resize, which has similar performance to resize in OpenCV. 
The objects in my images are not so small. I will try to increase the size of neural network if I can't detect small objects with v3 model.

**Comment by danimod92** [comment]
Sorry to comment this old post, but I'd like to ask a question:
@AlexeyAB  you answered that speed (so I guess FPS) is not influenced by number of classed used to train the network. Why?what's the reason behind it?
