### ISSUE TITLE
verifying that darknet is using all images in the dataset

### ISSUE THREAD

**Issue by k00r** [AlexeyAB/darknet#972]
Hello Alexey,is there a way to verify that darknet is using all the images in my dataset while training,can we say if the gui bounding box tool that you have is having no problems opening an image darknet will also have no problem,are they using the same methods?

**Comment by AlexeyAB** [comment]
@k00r Hello,

* You can see file `bad.list` with images that were not used. Just remove `bad.list` before starting the training.

* In the remaining cases Darknet will use images, but may not use some wrong labels.
**Update your code from GitHub**, I added fix to store wrong annotations to the file `bad_labels.list`: https://github.com/AlexeyAB/darknet/blob/7359843a4b0ed053aaa4cb5cc4337e821e83a1a1/src/data.c#L325-L361


So if files `bad.list` or `bad_labels.list` is empty or absent - then all images and all annotations were used.

**Comment by AlexeyAB** [comment]
@k00r Small annotation, or x,y,w,h = equal to 0, less than 0, more than 1, class_id more than classes, ...

**Comment by k00r** [comment]
@AlexeyAB thank you very much Alexey,by the way can you e-mail me?I have something to tell you which i can't tell from here. (basan.hasan24@gmail.com)

**Comment by AlexeyAB** [comment]
@k00r I mailed you.
