### ISSUE TITLE
@AlexeyAB Consultation on darknet

### ISSUE THREAD

**Issue by omar391** [AlexeyAB/darknet#975]
Hi Alexy,

Sorry for this public post. I would like to have a private conversation with you. Please send me an email omar391 @ gmail . com.

Thank you.

**Comment by AlexeyAB** [comment]
@omar391 Hi,

1. Check that your dataset has images without labels - this is wrong: `cars/00000.jpg`, `cars/00001.jpg`, `00002.jpg` - **there are many such wrong-labels**

2. Check that on some images the same object labeled as different class_id, look at white car class_id = 3 then 2: `00014.jpg`, `00015.jpg` - **there are many such wrong-labels**

3. Why do you have different directories `cars, trailer, ...`? Did you train one by one for each of these directories? - it is a bad idea. You should train by using single dataset with all images and labels.

4. In the folder `trucks` there are labled `trucks`, but there are many unlabeled `cars`? - **All objects should be mandatory labeled on each image, always.**

5. What model do you use, `yolov3.cfg`?

6. What weight= height= ranom= do you use?

7. Do you use the latest version of the Darknet code from this repository?

8. How many iterations did you train and what mAP can you get?

9. What GPU do you use?

So merge all images into one dataset in single directory and fix labels - all objects should be labeled. Use https://github.com/AlexeyAB/Yolo_mark

Also read: https://github.com/AlexeyAB/darknet#how-to-improve-object-detection
