### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by wolaipaopao** [AlexeyAB/darknet#978]
Hello, @AlexeyAB 
   I use v3 to train my dataset, and occured segmentation fault after it worked a while. Here are my options:
gpu=1, cudnn=1, opencv=1  opencv3.4.0, the others are 0, ubuntu16.04, cuda=9.1, cudnn=7.0.5, two nvidia GPU:Quadro k620 and Tesla M40(24G memory)
.cfg: batch=64 subdivisions=4 weight=416 height=416 
 I read all the issues but still dont know how to fix the problem, please help me.

**Comment by AlexeyAB** [comment]
@wolaipaopao Hello,

* Do you use the latest code? There was fixed issue, when you set in the label txt-file: `class_id >= classes`, now it is fixed.
* How many iterations aproximately can you train successfully?
* Do you use `random=1`?
* Do you train on M40?
* Can you show screenshot of this error?
* Can you get the same error on original repo?

**Comment by AlexeyAB** [comment]
Looks like your `train.txt` is wrong - it contains empty lines (may be at the end of file)

* Can you show content of files `bad.list` and `bad_labels.list` if them are present?
* Can you show full path to the one of images in the train.txt?
* Try to open your dataset by using https://github.com/AlexeyAB/Yolo_mark and you will get new `train.txt` file, that you should use for training.

**Comment by wolaipaopao** [comment]
Thank you for your advises, I have solved the problem. It is that train.txt contains empty line at the end of file, and maybe coded format is wrong too since I opened it with libreOffice. By the way, I wonder that the label.txt and the .jpg should be put in diffrent dirs? Thanks very much!

**Comment by AlexeyAB** [comment]
@wolaipaopao txt-labels and jpg-images can be in the same directory.
Only case when txt and jpg should be in different dirs, if you are using Pascal VOC or MS COCO datasets (with directories names `images/train2014/`, `"VOC2007/JPEGImages`, ...) where are txt & jpg files already in different dirs: https://github.com/AlexeyAB/darknet/blob/1c05ebf522f0bb5776ba51a46d94aa101220fea1/src/utils.c#L208-L216

**Comment by wolaipaopao** [comment]
@AlexeyAB I got it and thank you so much!
