### ISSUE TITLE
Use DLL in C# Project like Unity

### ISSUE THREAD

**Issue by feber** [AlexeyAB/darknet#98]
Dear all,
We are trying to use DLL from `yolo_cpp_dll.sln`. DLL file is generated without a problem. However, we need to use it inside C# project.
Based on the API, we are trying to do:
```C#
[DllImport("yolo_cpp_dll.dll")]
private static extern Object Detector(string cfg_filename, string weight_filename, int gpu_id = 0);
```
`EntryPointNotFoundException` always shown up when we call `Detector(..., ...)` at some part inside a method.

Any suggestion or idea how can we made this possible?
Thank you.

**Comment by feber** [comment]
Finally we figure it out. We need to declare new function which do the detection and return the result.
In C# code, declare as following:
``` C#
[DllImport("yolo_cpp_dll.dll")]
private static extern IntPtr detect_image();

[DllImport("yolo_cpp_dll.dll")]
private static extern void free_mem(IntPtr ptr);

static void Main(string[] args)
{
    IntPtr data = detect_image();
    int[] result = new int[1024];
    Marshal.Copy(data, result, 0, 1024);
    free_mem(data);
    // ... process the result variable ...
}
```

Declare new function outside the Detector class. In yolo_v2_class.hpp:
```C++
extern "C" {
    YOLODLL_API int* detect_image();
    YOLODLL_API void free_mem(int* pArray);
}
```
and implement it inside yolo_v2_class.cpp (outside Detector class):
```C++
YOLODLL_API int* detect_image()
{
    Detector detector("yolo-voc.cfg", "yolo-voc.weights");
    auto obj_names = objects_names_from_file("data/voc.names");
    const int limit = 1024;
    int* detectedObjects = new int[limit];
    // ... detect the objects and assigned to array ...
    return detectedObjects;
}

YOLODLL_API void free_mem(int* pArray)
{
	delete pArray;
}
```

Hope it helps.

**Comment by mcjjin** [comment]
Hi I am also trying to use the yolo_cpp_dll on my C# application but it failed when I am using the detect method which showing an access violation error, could you share some of you codes that may help?  : )

**Comment by feber** [comment]
@mcjjin yes, we are facing the same problem actually. Sometimes it works well as expected, but access violation error also appear at many times. We have not solved it yet. Sorry.
