### ISSUE TITLE
how to test mAP on COCO dataset?

### ISSUE THREAD

**Issue by linyuanze** [AlexeyAB/darknet#984]
how to test mAP on COCO dataset(5k)??

**Comment by AlexeyAB** [comment]
`./darknet detector map cfg/coco.data cfg/yolov3.cfg yolov3_10000.weights`

**Comment by Jped** [comment]
Hi, the issue with this is that there [isnt annotation files for every coco image](https://github.com/cocodataset/cocoapi/issues/76);however, darknet complains when a certain images doesnt have an annotation, is there any way around this?

**Comment by AlexeyAB** [comment]
@Jped 

There are 2 ways:

1. or change script that creates COCO annotations in Yolo format to generate empty txt-files

2. or just change this line: https://github.com/AlexeyAB/darknet/blob/e301fee8a0d1343824dd8038bc051f728b93bc57/src/data.c#L145
to these 2:
```cpp
*n = 0;
return boxes;
```
