### ISSUE TITLE
Linker error: unresolved symbols in blas.h file

### ISSUE THREAD

**Issue by ritwikdubey** [AlexeyAB/darknet#988]
Hi AlexeyAB, need a bit of help building darknet on Win10.  Let me get version info out of the way first,
1- MSVS 2017 Community Ed, 
2- CUDA 9.0 
3- OpenCV 3.4.0

I have successfully built darknet using Cygwin and tested yolov3 using the compiled binaries. I however wasn't sure how to get the CUDA/cuDNN paths configured to make a "GPU=1" equivalent build in Cygwin. So I decided to work through your instructions for building using MSVS. 

I'm compiling darknet.sln and I think I've figured out most of the include/library dependencies. To be concise, my darknet.vcxproj looks like this:

< ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
 < AdditionalIncludeDirectories>C:\opencv_3.0\build\include;..\..\3rdparty\include;%(AdditionalIncludeDirectories);$(CudaToolkitIncludeDir);$(CUDA_PATH)\include;C:\cuda\include;$(cudnn)\include< /AdditionalIncludeDirectories>
 < AdditionalLibraryDirectories>C:\opencv_3.0\build\x64\vc14\lib;C:\opencv_2.4.13\opencv\build\x64\vc14\lib;C:\opencv_2.4.13\opencv\build\x64\vc12\lib;$(CUDA_PATH)\lib\$(PlatformName);$(cudnn)\lib\x64;C:\cuda\lib\$(PlatformName);%(AdditionalLibraryDirectories)< /AdditionalLibraryDirectories>
< AdditionalDependencies>..\..\3rdparty\lib\x64\pthreadVC2.lib;cublas.lib;curand.lib;cudart.lib;%(AdditionalDependencies)< /AdditionalDependencies>

I'm currently stuck on figuring out following bunch of linker errors like these:

1>------ Build started: Project: darknet, Configuration: Release x64 ------
1>activation_layer.obj : error LNK2001: unresolved external symbol copy_ongpu
1>activation_layer.obj : error LNK2001: unresolved external symbol activate_array_ongpu
1>activation_layer.obj : error LNK2001: unresolved external symbol gradient_array_ongpu
1>avgpool_layer.obj : error LNK2001: unresolved external symbol forward_avgpool_layer_gpu

These functions are declared in `ifdef GPU` preprocessor across bunch of header files and quite a few in blas.h. Bit of grep-ing showed me these are implemented in blas_kernel.cu files.  This is where it gets out of my depth. Is there any configuration required to compile these *.cu files? How do I make sure the caller sees the implementation of the function in the compiled *.cu files?

**Comment by ritwikdubey** [comment]
Wonder where does Windows compilation configuration do something similar to:

```
c:\Users\ritwik\Downloads\darknet-master\darknet-master>grep -rin "nvcc" *
Makefile:50:NVCC=nvcc
Makefile:136:   $(NVCC) $(ARCH) $(COMMON) --compiler-options "$(CFLAGS)" -c $< -o $@
```

**Comment by AlexeyAB** [comment]
@ritwikdubey Hi,

1. Did you set CUDA 9.0 here? https://devblogs.nvidia.com/wp-content/uploads/2015/01/VS2013-R-5.jpg

2. open `\darknet.sln` -> (right click on project) -> properties -> C/C++ -> Preprocessor -> Preprocessor Definitions, and add here: `GPU;`

3. Just add all `*.cu` files to the Solution explorer in the MSVS2017 when darknet.sln is opened (drag n drop cu-files)

4. Can you compile default `darknet.sln` file?
5. Can you see Nsight folder at the top of your MSVS2017?

**Comment by ritwikdubey** [comment]
1. Yes. The screenshot shows the configuration
2. Added GPU; preprocessor
3. Added *.cu files to the solution
4. I get the same linker error after these steps
5. I don't see Nsight folder at the top of MSVS2017. Where should I expect it to be?
Is it something I need to install from [here](https://developer.nvidia.com/gameworksdownload#?dn=nsight-visual-studio-edition-5-4-0)?
![msvs2017-screen1](https://user-images.githubusercontent.com/1186630/41075256-81922d1c-69d1-11e8-8480-090b463433c4.png)

**Comment by ritwikdubey** [comment]
I did install Nsight from the link and now I see `Nsight` in the top menu bar.

![msvs20172](https://user-images.githubusercontent.com/1186630/41076121-87afc9da-69d5-11e8-9e99-5f7d25d5254c.png)

Does Nsight require more configuration? Tried to compile it as is, still same linker errors.

**Comment by AlexeyAB** [comment]
CUDA must be installed only after that MSVS2015 had been installed.

So remove nSight, remove CUDA. And install it again (during installation set to install plugins nSights for MSVS2017)

**Comment by ritwikdubey** [comment]
@AlexeyAB  
Reinstalling CUDA 9.0 did the trick. CUDA C/C++ shows as a compiler in project properties. I'm able to compile the code and generate darknet.exe. Thanks for the help.
