### ISSUE TITLE
How to issue a detection signal?

### ISSUE THREAD

**Issue by samjob1** [AlexeyAB/darknet#99]
I have already compiled Darknet under Windows all working but I would like to do the following: if an object is found, a person should give a signal or display a message in the window that the person is found. But I can not figure out which of the modules to do this.

**Comment by AlexeyAB** [comment]
Just add you code lines with "signal or display a message in the window" in the function `draw_detections` in the file `image.c` here: https://github.com/AlexeyAB/darknet/blob/b585124e55fcd18a7511d3b2fdc6bc3db5368ef4/src/image.c#L188

For example:

    for(i = 0; i < num; ++i){
        int class = max_index(probs[i], classes);
        float prob = probs[i][class];
        if(prob > thresh){
            
            printf("\n Object found, class = %d \n", class);
            int width = im.h * .012;

---- 

Or other way is to use C++-DLL in your custom project: https://github.com/AlexeyAB/darknet#how-to-use-yolo-as-dll
